### ISSUE TITLE
Does not it make sense to enable option to disable immersive menus by default?

### ISSUE THREAD

**Issue by Anix-x** [valinet/ExplorerPatcher#102]
I cannot imagine a use-case where one would want the Win10 immersive menus. The non-immersive Win8/7 context menus fit with all themes much better (they have to because they use the generic menu controls).

Also, this option is located in File Explorer settings but affects the taskbar as well.

**Comment by valinet** [comment]
First of all, refrain from posting in issues when the content is actually a question about the app, suggestion, inquiry about the future of the app etc. This is a basic rule which should not be skipped over. It is written in ALL CAPS in the recommended issues section, in the hope that users notice it and act accordingly.

This post is about a possible enhancement. It belongs to the discussions section. Also, I saw that you discovered that, but you post intermittently here and there. Also, please let's group together issues on the same topic. I don't want to have 20 separate pages for each problem the "classic theme" (I'd rather call it the "ThemeData" handle close hack) has with this application or applications on the desktop in general. To be honest, supporting this is... hard, it involves A LOT of separate code paths, and the benefits are not immediately obvious... this configuration is incredibly unsupported (apps nowadays do not really expect to run without themes), it is prone to breaking various stuff, a lot of applications don't work with it etc. 

Now, back to the original post, my answer is no, it shouldn't disable immersive menus by default. If you look closely, with the default theme, you'll see that the owner drawn (immersive) menus actually look better and have less glitches, with the default theme, that is:

![image](https://user-images.githubusercontent.com/6503598/137488435-5e7f8746-35ab-4b75-9ea9-c5939a3ba493.png)

On the other hand, the classic menu has some visual glitches, at aleast on stock theme which the vast majority of users use:

![image](https://user-images.githubusercontent.com/6503598/137488602-6abe0b57-7191-49f4-a07d-ed97ffb1c1c0.png)

So no, I won't enable that by default. Regarding the second point, the option in the "File Explorer" section only affects File Explorer windows. The option "Skin taskbar and tray pop-up menus" in the "Taskbar" section has a similar effect when unchecked, but for the taskbar and the system tray icons. This is intended behavior.

Thanks
