### ISSUE TITLE
Taskbar icons too wide and Explorer check boxes

### ISSUE THREAD

**Issue by valinet** [valinet/ExplorerPatcher#1022]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/976

<div type='discussions-op-text'>

<sup>Originally posted by **Bec-de-Xorbin** March  3, 2022</sup>
After updating to 22000.493.42.26 and trying centered taskbar and then reverting to default settings (At screen edge), taskbar icons got wider. I don't know how to get them back to normal. Also in Explorer every item has a check box now, even when View -> Show -> Item check boxes is not enabled (tried to enable -> disable that, no effect). Downgrading to 22000.493.42.25 didn't work either. Any ideas?

EDIT: I cannot reproduce this under Windows Sandbox so maybe it was user error or something... Anyways, solved it by system restore.</div>

**Comment by rounk-ctrl** [comment]
yeah it also happened to me
I fixed it by going to tablet mode settings and unchecking all these options (idk if this exists in windows 11)
![image](https://user-images.githubusercontent.com/70931017/157015550-94ee80ee-229e-4407-90db-c40c618b38b6.png)
