### ISSUE TITLE
Feature request : Replace the search engine used in the start menu

### ISSUE THREAD

**Issue by rp1231** [valinet/ExplorerPatcher#1026]
Would it be possible to replace the search engine used in the start menu?

![sidekick_kFc9Q6znvc](https://user-images.githubusercontent.com/47380919/157116399-e8a9cdde-18ca-4526-9664-ba28f71a71c5.png)
 
 Thanks

**Comment by Shaughn-david** [comment]
I think you are supposed to use discussions

**Comment by rp1231** [comment]
Oh I didn't know that.
I'll create a topic in discussions.
