### ISSUE TITLE
Enable Win10 window switcher option by default is disabled but acts as enabled

### ISSUE THREAD

**Issue by Anix-x** [valinet/ExplorerPatcher#103]
By default the option is marked as X but the window switcher is big and transparent. First change to this option (enabling) does not affect anything. Disabling it back brings the simple task switcher as in Windows 2000.

**Comment by valinet** [comment]
Indeed, the default was set to `Enabled`. Corrected that. Thanks.

**Comment by Anix-x** [comment]
Here is a manual on how to enable it: https://www.windowscentral.com/how-bring-back-old-alt-tab-experience-windows-10

**Comment by valinet** [comment]
> 
> Also, would not it be better to have 3-way "radio buttons" for the choices of context menus and window switchers?

Okay, I guess I could make the window switcher a drop down option, to choose between "Windows 11", "Windows 10" and "Windows 95". For context menus, it is technically challenging to implement, as the 3 settings live in 2 places. And idk if it makes that much sense... the settings are independent. Not all the Explorer context menus use the Windows 11 style by default. Those that do not, will not be immersive, if they were. That's a valid configuration which would not be possible with what you suggest.

Anyway, I'd bother more about writing a guide for how to use this with the classic theme. That would be something useful you definitely could help with.

**Comment by Anix-x** [comment]
Thanks. On Windows 8.1 once you switch to the Classic theme, you get the Win95-like switcher automatically. On Windows 11 all 3 seem to work well.

**Comment by Anix-x** [comment]
The old switcher may be useful for those who want see more of the screen while switching the tasks.

**Comment by valinet** [comment]
> 
> 
> Thanks. On Windows 8.1 once you switch to the Classic theme, you get the Win95-like switcher automatically. On Windows 11 all 3 seem to work well.

Yeah, the new UI is implemented in some further framework that simply does not care anymore about whether themes are enabled or not, it just gets the measurements and from some internal stuff and gets going. Funnily enough, even Microsoft bypasses their theme engine.

> 
> 
> The old switcher may be useful for those who want see more of the screen while switching the tasks.

Indeed.

**Comment by valinet** [comment]
I renamed "Disable the Windows 10 (immersive) context menu" to "Use immersive menus when displaying Windows 10 context menus". Makes it more clear, imo.
