### ISSUE TITLE
Windows 10-style Start menu portion text is not the localized language

### ISSUE THREAD

**Issue by any-possible** [valinet/ExplorerPatcher#1069]
**Hello!**

I am using this new feature (Windows 10-Style Start menu) in Windows 11, but I found a problem:
Windows 10-style Start menu portion text is not the localized language.

e.g. *"Pin to Start", "Uninstall", "Run as Administrator"*

![image](https://user-images.githubusercontent.com/96678274/158148414-eb66bedc-cbdd-4591-bba5-b7ba4d2dfdef.png)

Different language displays mixed together are *not* very nice.

Is this a problem with the system?

My Windows Version: 22000.556

**Comment by valinet** [comment]
#56

Search past threads. This has already been discussed.
