### ISSUE TITLE
ExplorerPatcher seems to remove Camera driver until updated?

### ISSUE THREAD

**Issue by pisorsisaac** [valinet/ExplorerPatcher#1088]
I know this sounds bizarre and hard to believe, but I have a relatively new Gateway laptop running Windows 11.  Ever since I got it and installed ExplorerPatcher, at first the machine started saying "Camera not found" or "camera not detected", etc.  After doing ALL the usual troubleshooting (extensive device manager, driver updates, etc, nothing worked and even talked to both Windows support and Gateway support), my only option was to reset PC.  Once again, the camera disappeared AFTER running/installing ExplorerPatcher.  Now recently I'm in the same situation, only I've been ignoring ExplorerPatcher's invitations to me to run an Update on it. Finally I just now ran the requested Update, and the moment I installed the latest ExplorerPatcher update, the camera is working normal - suddenly goes from Not Detected to working fine!  Surely SOMEONE else has had this troubling problem??

**Comment by meemore** [comment]
If the camera is built into laptop, explorer patcher reboots explorer.exe so it possible, this is simply that.   if you go to Device Manager and look for the camera,  look for disable and enable button of the camera,  It may be connected to windows Privacy settings for the camera, so this could simply be windows, not knowing what to do.    And just so you know,  I have had my USB Camera disappear, and it was a privacy setting that I had turned on.

**Comment by valinet** [comment]
I cannot reproduce this.
