### ISSUE TITLE
Volume flyout not working with Windows 10 taskbar style

### ISSUE THREAD

**Issue by MikeCardiff** [valinet/ExplorerPatcher#1096]
## Issue Details
Since updating Windows and Explorer Patcher to the latest versions, the volume flyout no longer displays when changing volume using keyboard media controls.

## Versions
**Windows Build**

> **Edition**	Windows 11 Pro
> **Version**	22H2
> **OS build**	22621.1413
> **Experience**	Windows Feature Experience Pack 1000.22639.1000.0

**Explorer Patcher version**
> 2261.1344.53.1

## Reproduction Steps
1. Set Taskbar style to Windows 10
3. Change volume using keyboard media controls
4. Volume flyout will not be displayed

If the taskbar style is set to Windows 11 the volume flyout works as normal.

**Comment by egorbunovs** [comment]
Yeap - same issue for me as well

**Comment by 99Wasdqwop** [comment]
same issue for me

**Comment by Leokuma** [comment]
See the workaround here: https://github.com/valinet/ExplorerPatcher/discussions/1087

**Comment by egorbunovs** [comment]
> See the workaround here: #1087
Could you please be more precise on what to do? Tried disabling this `26008830` with ViveTool (If that was the workaround) and no - that didn't help

**Comment by Leokuma** [comment]
@egorbunovs Yes that was the workaround.

Have you restarted your PC?

**Comment by CthRio** [comment]
> > See the workaround here: #1087
> 
> Could you please be more precise on what to do? Tried disabling this `26008830` with ViveTool (If that was the workaround) and no - that didn't help

This requires restarting the PC.

**Comment by egorbunovs** [comment]
You are right - restart did the trick! Thank you! 🥳

**Comment by MikeCardiff** [comment]
Another workaround I'm using is [ModernFlyouts](https://modernflyouts-community.github.io/) to replace the standard Windows flyouts.

**Comment by MikeCardiff** [comment]
Just noticed #1093 also reporting this so closing to avoid duplicates.

**Comment by RC2P** [comment]
Seems like the bug came back in W11 Build 22631.1972

**Comment by pyrates999** [comment]
> Seems like the bug came back in W11 Build 22631.1972

That's a preview release: https://blogs.windows.com/windows-insider/2023/06/29/announcing-windows-11-insider-preview-build-22621-1972-and-22631-1972/

Uninstall it if you want to use explorer patcher: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
