### ISSUE TITLE
How to uninstall / Can't update to new version: 'File in use'

### ISSUE THREAD

**Issue by ErickWei** [valinet/ExplorerPatcher#11]
How to update it to new version(or just delete it)?
Can't replace it with new vesion dll,and error show "file in use".
![snipaste_20210901_144659](https://user-images.githubusercontent.com/62826892/131624869-2367b51a-e03b-40b1-aebe-12637d89237b.png)

**Comment by valinet** [comment]
Of course, it is in use by Explorer where it gets injected.

You can use this batch script:
```
@echo off
ren C:\Windows\dxgi.dll dxgia.dll
taskkill /f /im explorer.exe
explorer.exe
del C:\Windows\dxgia.dll
```

Afterwards, copy the new DLL to `%windri%` and restart Explorer (regular installation procedure).

That script is derived from the following, which I use to test development versions:

```
@echo off
del C:\Windows\dxgia.dll
ren C:\Windows\dxgi.dll dxgia.dll
xcopy "C:\Users\root\Documents\Visual Studio 2019\Projects\ExplorerPatcher\x64\Release\dxgi.dll" C:\Windows
taskkill /f /im explorer.exe
explorer.exe
```

Good luck!
