### ISSUE TITLE
Uninstall issue

### ISSUE THREAD

**Issue by FlameOfArda** [valinet/ExplorerPatcher#1100]
So I went to uninstall this program through the regular means (control panel).  It uninstalled, but didn't reinstall microsoft's file explorer for some reason.  It kept croshing and launching in a loop, and my desktop was flashing and taskbar was gone.   Took me two hours to reinstall this program through safe boot.  How am I supposed to safely uninstall this?

**Comment by CthRio** [comment]
There may be backups of explorer.exe in two folders, SysWoW64 and WinSxS.

**Comment by CthRio** [comment]
EP has also modified some Librarys(.dll), you can take a look at the project's EP_ Setup understands what the installer has done, and then rolls it back manually, if the given uninstaller is invalid.

**Comment by CthRio** [comment]
Or you can copy the resource manager and its resource files from the image file file of the corresponding system version to the corresponding directory. (If none of the methods given above works.)

**Comment by CthRio** [comment]
> 所以我通过常规方式（控制面板）卸载了这个程序。它卸载了，但由于某种原因没有重新安装微软的文件资源管理器。它一直在循环播放和启动，我的桌面在闪烁，任务栏不见了。我花了两个小时通过安全启动重新安装此程序。我应该如何安全地卸载它？

Maybe it works: https://github.com/valinet/ExplorerPatcher/issues/1104#issue-1630146041

**Comment by CthRio** [comment]
There may be backups of explorer.exe in two folders, SysWoW64 and WinSxS.



> So I went to uninstall this program through the regular means (control panel). It uninstalled, but didn't reinstall microsoft's file explorer for some reason. It kept croshing and launching in a loop, and my desktop was flashing and taskbar was gone. Took me two hours to reinstall this program through safe boot. How am I supposed to safely uninstall this?

There may be backups of explorer.exe in two folders, SysWoW64 and WinSxS.
EP has also modified some Librarys(.dll), you can take a look at the project's EP_ Setup understands what the installer has done, and then rolls it back manually, if the given uninstaller is invalid.
Or you can copy the resource manager and its resource files from the image file file of the corresponding system version to the corresponding directory. (If none of the methods given above works.)

**Comment by valinet** [comment]
Follow the source code and remove all the files the installer places. `explorer` is hooked by placing `dxgi.dll` in `C:\Windows`. If you remove that, `explorer` won't have problems anymore. To remove it, `explorer` and any other program that might be using it has to be closed. Alternatively, it can be renamed while in use.

**Comment by FlameOfArda** [comment]
Thanks for your time!  I really appreciate it!
