### ISSUE TITLE
Problem with right clicking the taskBar

### ISSUE THREAD

**Issue by NGonzalezc** [valinet/ExplorerPatcher#1103]
The taskbar stop working when i right clicking it in WIN11 mode
also trying to pass windows between monitors,
its like close the ExplorePatcher and start a new one, 
this issue starts with the las update i think

**Comment by valinet** [comment]
Unable to reproduce. The report doesn't contain essential information...

https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems
