### ISSUE TITLE
The latest ExplorerPatcher break windows search

### ISSUE THREAD

**Issue by frijheid** [valinet/ExplorerPatcher#1109]
EP version: 22621.1413.54.1
Os version: Win 11 build 1122621.1344
The win+tab can be fixed by turning off a feature in vivetool.

Problem
After updating the latest version break the search windows.
Search is not working and can't be clicked at all in the Start menu.
Any solution? Thank You.

Regards

**Comment by valinet** [comment]
Unable to reproduce. It definitely is not broken. Try restarting Windows... Reset the feature in vivetool to the default, EP addresses the issue, the workaround is not needed anymore.

**Comment by ghnp5** [comment]
@frijheid - To me, it got broken when I updated Windows. It was broken before ExplorerPatcher's update.

**Comment by frijheid** [comment]
Ok, it worked after completing all the windows updates then reinstalling the ep.
Thanks

**Comment by devedse** [comment]
I had this issue too. I uninstalled EP and then everything worked again.

Everything in the start menu was clickable except the search field.

**Comment by e-t-l** [comment]
> I had this issue too. I uninstalled EP and then everything worked again.
> 
> Everything in the start menu was clickable except the search field.

Do you mean that after you uninstalled EP, clicking the search field in start menu *still* didn't work?

**Comment by pyrates999** [comment]
This is not caused by EP.  This is a known bug in windows 11 where you gotta rebuild the search index sometimes.

**Comment by e-t-l** [comment]
> This is not caused by EP. This is a known bug in windows 11 where you gotta rebuild the search index sometimes.

Thanks for your responsiveness. I was just trying to clarify what exactly @devedse experienced, but I will keep this info in mind. My current problem—which as you pointed out, is likely caused by the Preview update—is that typing is no longer received to trigger a search when start is open. If I manually open the search, like with Win + S, I can type and click the field fine.

**Comment by pyrates999** [comment]
Uninstall the preview update.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

**Comment by e-t-l** [comment]
> > I had this issue too. I uninstalled EP and then everything worked again.
> > Everything in the start menu was clickable except the search field.
> 
> Do you mean that after you uninstalled EP, clicking the search field in start menu _still_ didn't work?

@devedse could you please clarify what your experience was? Did searching from the start menu work correctly when EP was uninstalled?
