### ISSUE TITLE
KB5023706 - Windows 11

### ISSUE THREAD

**Issue by Faks** [valinet/ExplorerPatcher#1127]
Hi, guys after installing update:
https://support.microsoft.com/en-us/topic/march-14-2023-kb5023706-os-build-22621-1413-9d3f2de5-08e7-4462-8fba-d944201f4ae1
seems it breaks the patcher, let me break it down.
1.) alt-tab is dead on it it crashes constantly 
2.) it crashed permantly doesn't start at all at boot
3.) it partily crashed start button doesn't respond but everything starts

Note: Winver: Microsoft Windows [Version 10.0.22621.1413]

**Comment by topia** [comment]
Please update to the latest ExplorerPatcher if you didn't.

**Comment by valinet** [comment]
Update to latest EP which adresses your issues…

**Comment by Faks** [comment]
did, and didn't solve.

**Comment by Faks** [comment]
![image](https://user-images.githubusercontent.com/1909645/226175696-80439f6c-a37e-4517-a14f-01306a1a1cca.png)

**Comment by Faks** [comment]
![image](https://user-images.githubusercontent.com/1909645/226175725-cc16fa6a-c26b-4bdf-8a48-1e5e4aac99a9.png)
only for you...

**Comment by topia** [comment]
Could you check EP's version by checking the details tab inl properties of `C:\Windows\dxgi.dll` (not system32)? I expect it's 22621.1413.54.x. If you use the latest version, I doubt you're using another explorer patching app.

**Comment by valinet** [comment]
> ![image](https://user-images.githubusercontent.com/1909645/226175725-cc16fa6a-c26b-4bdf-8a48-1e5e4aac99a9.png) only for you..., download today, all issues after fresh re-install. if wish I can record a video to prove you wrong....

No need to prove me wrong, idk what do you expect, it's Microsoft's OS, not mine, I don't know all its ins and outs. Even if you show me and I believe you, is it going to magically solve your issues? No. maybe it's some rare bug that happens on your config. It's pointless to believe in it if I cannot reproduce it or don't know how to fix it anyway.

**Comment by Faks** [comment]
> > ![image](https://user-images.githubusercontent.com/1909645/226175725-cc16fa6a-c26b-4bdf-8a48-1e5e4aac99a9.png) only for you..., download today, all issues after fresh re-install. if wish I can record a video to prove you wrong....
> 
> No need to prove me wrong, idk what do you expect, it's Microsoft's OS, not mine, I don't know all its ins and outs. Even if you show me and I believe you, is it going to magically solve your issues? No. maybe it's some rare bug that happens on your config. It's pointless to believe in it if I cannot reproduce it or don't know how to fix it anyway.

https://www.veed.io/view/61b568e5-e0b4-465b-9c62-a37c67cb3c20?sharingWidget=true&panel=share

**Comment by Faks** [comment]
![image](https://user-images.githubusercontent.com/1909645/226176654-720e02c3-4bb8-479d-bbec-ec352d15526e.png)

**Comment by Faks** [comment]
> ~Could you check EP's version by checking the details tab inl properties of `C:\Windows\dxgi.dll` (not system32)? I expect it's 22621.1413.54.x.~ If you use the latest version, I doubt you're using another explorer patching app.

you are right.

**Comment by Faks** [comment]
just did reinstall.
![image](https://user-images.githubusercontent.com/1909645/226176782-819f0853-7689-44b0-8054-7f2b897f4fbf.png)
