### ISSUE TITLE
duplicated taskbar when you have two or more screens

### ISSUE THREAD

**Issue by Gandalf58** [valinet/ExplorerPatcher#1132]
Hello,

When you have two or more screens, it would be good to have a duplication of the task bar from the main screen to the other (s).
I am thinking in particular of the possible added toolbar, all the tasks and the Systray. By possibly leaving each user the option of displaying or not

Thanks in advancece

**Comment by thalandor46** [comment]
New user, seconding this!  The secondary taskbar is notably less useful when all it has is the start menu and clock.  It would be great to have toolbars and notification icons.

**Comment by pyrates999** [comment]
Please move this to discussions and all new feature requests to discussions.
