### ISSUE TITLE
App switching broken with latest Windows 11 release

### ISSUE THREAD

**Issue by BlueHoopyFrood** [valinet/ExplorerPatcher#1133]
After the latest Windows 11 release (OS Build 22621.1413), app switching (Alt-tab, Windows-tab) no longer works. Uninstalling ExplorerPatcher fixed the problem. Microsoft lists incompatibility of ExplorerPatcher as a known issue with the update.
https://support.microsoft.com/en-us/topic/march-14-2023-kb5023706-os-build-22621-1413-9d3f2de5-08e7-4462-8fba-d944201f4ae1

**Comment by DavidBerdik** [comment]
This was already fixed. Try the latest update.

**Comment by JoGr223** [comment]
this is not fixed, I have the same issue since today after updaing ExplorerPatcher; workaround is to switch to "simple" alt-tab in optiona, then restart EP, then it works; another issue that causes EP to crash is moving window (eg brave browser) from main monitor to internal laptop's display

**Comment by BlueHoopyFrood** [comment]
Confirmed fixed with 22621.1413.54.5. Thank you.
