### ISSUE TITLE
Weather location is missing, just shows undefined

### ISSUE THREAD

**Issue by Carrotcruncheruk** [valinet/ExplorerPatcher#1141]
Weather only shows undefined, tried a reinstall still the same, not sure if its a windows issue or bug so reporting it anyway, you hard work is appreciated, you make W11 usable. thanks!

**Comment by valinet** [comment]
Try "Clear weather widget local data" in "Properties - Weather". Should not happen in latest EP update.

**Comment by Carrotcruncheruk** [comment]
Hi there, I tried what you said and I install the latest pre-release update and it's cured all the problems. Thanks for your fantastic work. You make windows worth using, I have made a contribution, Thanks again!
