### ISSUE TITLE
Notification banner seems to be overlapping on the taskbar

### ISSUE THREAD

**Issue by JPFlySolo** [valinet/ExplorerPatcher#1144]
This issue just recently started happening a few days ago with the "windows 10"  taskbar style as shown in the first screenshot. But when using the "windows 11" taskbar style, this issue doesn't seem to happen. Tried restarting the "File Explorer" and restarting the computer.
![Windows 10 Notification Overlapping](https://user-images.githubusercontent.com/28690549/226237213-6337b84b-8acf-40ea-9475-0050920b7340.png)
![Windows 11 Notification Not Overlapping](https://user-images.githubusercontent.com/28690549/226237216-c1e4829c-9d04-4f85-b539-5df19b4e3a54.png)

**Comment by trainvoi** [comment]
This is happening to me too.
