### ISSUE TITLE
File explorer crashes when i right click on the task bar.

### ISSUE THREAD

**Issue by riccardosimo** [valinet/ExplorerPatcher#1147]
Hi there. With the new version of explorerpatcher every time I right-click on the taskbar, file explorer crashes and I'm not able to go into the properties :( (I'm on Win11 23403.1001

**Comment by valinet** [comment]
EP is not tested on Insider builds, I have specified multiple times. Attach with a debugger and see what the cause is.

Properties can be opened from Run using `rundll32 C:\Windows\dxgi.dll,ZZGUI`.

**Comment by riccardosimo** [comment]
> I've had the same problem. Win 11 Build 22621. Reinstalled EP, several times, even older versions. Problem still there. I opened the settings with rundll, changed a few settings and now right-clicking on the taskbar opens the menu as normal. Found out that when the taskbar-style is set on Win11, explorer stops working on a right click. When the style is set on win10, there is no problem.

Thank u man :)

**Comment by NathanielJS1541** [comment]
I had the same issue on Windows 11 Pro Version 10.0.22621 Build 22621 and disabling "Skin taskbar and tray pop-up menus" under "System Tray". This let me right click on the taskbar with the Win11 style. I did notice also that Alt+Tab seems to cause explorer to crash now too...

**Comment by NathanielJS1541** [comment]
On that note it seems like changing "Window Switcher" style to "SimpleWindowSwitcher" also fixes that problem.

**Comment by ELowry** [comment]
I can confirm that `Skin taskbar and tray pop-up menus` is at fault for Windows 11 Pro `22621.1483`
