### ISSUE TITLE
Issue with Win10 Start and Taskbar

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#1158]
1. There is a issue with Win10 Start Menu that it doesn't show some apps and uwp apps. And also we can't those apps to the start menu. Shown notepad and Store in the video (very important).
https://user-images.githubusercontent.com/93650504/226585759-2d30ca87-4c75-4244-aaf2-be32e518aa34.mp4

2. Can you pls bring back the Win10 Win-X menu as we are not able to customize the Win-x menu. Neither with Win-X Editor nor from the File Explorer. This will help us to add or remove items we don't like. This was previously there in EP but not in latest version. (MS made them permanent). And also the toolbar option is broken on taskbar.
![2023-03-21_14h03_36](https://user-images.githubusercontent.com/93650504/226587241-dec526bc-28c1-4f4d-a064-6ac323d5266e.png)

**Comment by miklosakos** [comment]
+1 to the Win10 Start Menu problem

**Comment by topia** [comment]
You should not describe multiple in a single issue, and the developer doesn't want to use issues about that: #56; use discussions instead.
