### ISSUE TITLE
How to remove Es setup file?

### ISSUE THREAD

**Issue by VaibhavVerma21** [valinet/ExplorerPatcher#1161]
I seem to have deleted the es setup after installing the latest release from github, but it pops up at startup asking from admin perms. how can i remove it?

**Comment by jwgn** [comment]
So.. you think this is a bug that needs attention by the developer? Or why are you filing an issue for that question?

**Comment by jwgn** [comment]
Have a look here https://github.com/valinet/ExplorerPatcher/discussions

**Comment by VaibhavVerma21** [comment]
Thanks :D
