### ISSUE TITLE
Simple Window Switcher is automatically enabling the Language Bar

### ISSUE THREAD

**Issue by Magirus-Deutz** [valinet/ExplorerPatcher#1165]
When i enable the simple window switcher, then language bar comes in the taskbar and even if the language bar is disabled.

OS: Windows 11 22H2 (22621.1028) but i also tested on Windows 11 (22000)
EP Version: 22621.1413.54.3

**Comment by jwgn** [comment]
Have you tried with the Windows version matching the EP version? 22621.1028 is not the same as 22621.1413.

**Comment by nclemons78** [comment]
That looks like a typo to me, as I'm on Windows 11 version **22623.1028**, which was an Insider build (I exited Insider several months ago now, but I've been waiting for the mainline releases to catch up so that I can reinstall EP). I have a hard time believing that the exact same minor build version was released in both major build versions. But if I'm wrong and it was, definitely try running Wind9ws Update first.

**Comment by Magirus-Deutz** [comment]
> Have you tried with the Windows version matching the EP version? 22621.1028 is not the same as 22621.1413.

yes, it's still same. i have also win10 1903 and i tested EP on this old Windows, but still have the same issue.
By the way, my computers isn't native english, maybe Simple Window Switcher needs to English, so it's adding the bar. But why?

> That looks like a typo to me, as I'm on Windows 11 version **22623.1028**, which was an Insider build (I exited Insider several months ago now, but I've been waiting for the mainline releases to catch up so that I can reinstall EP). I have a hard time believing that the exact same minor build version was released in both major build versions. But if I'm wrong and it was, definitely try running Wind9ws Update first.

No, i'm literally use the build 22621.1028, but also i have Windows 10 2019 Update (a.k.a 1903) Build 18362

**Comment by pyrates999** [comment]
this could be a bug in windows

**Comment by Magirus-Deutz** [comment]
> I keep getting the language switcher randomly reappearing in the tray as well on my Win 11 22H2. I think this issue is the same as issue #1347. I am also using Simple Window Switcher but haven't verified whether this issue occurs without it.
> 
> A good hint might be - I can make it disappear again immediately if I go _Settings > Time & Language > Typing > Advanced Keyboard Settings_ and then **un**check and **re**check "_Use the desktop language bar when it's available_" (whereas the language bar itself is set to "hidden" of course).
> 
> Would really love to have it fixed. I'd also like to use this opportunity to say a huge thank you!

Yes, it is the same issue, and thank you for sharing this. I added the regs as it say in the answer on #1347 and it seems to be fixed. I enabled SWS, then restarted the computer and no more language bar.

> this could be a bug in windows

i don't know, may be
