### ISSUE TITLE
after the last windows update i have a lot of problems 

### ISSUE THREAD

**Issue by befkuh** [valinet/ExplorerPatcher#1166]
since i had the last update of windows i have a lot of problems with the taskbar and start buttons and the icons are black and the letters are gone so in short very annoying
![337114777_178087964579874_8817195480474835089_n](https://user-images.githubusercontent.com/128559228/226778161-12be7141-e416-494a-ac49-9b737bf4e4d6.jpg)

and when I wake up my computer from sleep mode, many icons are black

**Comment by astounding777** [comment]
Same. After latest Windows 11 update (just over 25 hours ago), moment entered the desktop, it kept constantly restarting explorer.exe in endless loop. It shows desktop for half a sec, then restarts, then shows, restarts, etc.

Had to go to Safe Mode > Task Manager > open add/remove programs (via Run command) > Uninstall ExplorerPatcher. 

Immediately fixed the issue.

**Comment by phffmnn** [comment]
I also uninstalled the ExplorerPatcher and still have issues.
My Taskbar is thin and the cut off:
![image](https://user-images.githubusercontent.com/34192428/227158265-fe550723-72f5-4271-b508-7f9fad6202bb.png)
And now I am left with the default terrible win11 taskbar again.

**Comment by befkuh** [comment]
now i have also discovered a new problem.. with some mkv movies i get an error message that refers to something with explorer
