### ISSUE TITLE
Feature Request for Taskbar

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#1167]
1. Can DEV's work on introducing Search Box on Win10 Taskbar as we have to use the Win11 Taskbar for that.

2. Can DEV's add a option to center the task icons and keep the start button on left like this : 
![2023-03-22_08h41_26](https://user-images.githubusercontent.com/93650504/226792389-1b980126-bc7c-40f9-9933-4242e5fcba1f.png)
 This is the feature for StartIsBack which is not usable on Win11.

**Comment by Poopooracoocoo** [comment]
Aren't there other projects for that?

**Comment by Magirus-Deutz** [comment]
> Aren't there other projects for that?

no, they can not. 
![e68705327b7e73244b89f15f7b048fdb](https://user-images.githubusercontent.com/20948362/227789644-f99027f3-6dae-4a23-a462-40117103e91d.jpg)
You see, Windows 10's Search Box is different than Win11's Search Box

> 2. Can DEV's add a option to center the task icons and keep the start button on left like this :

Actually, EP can do that. Look the EP taskbar properties and click "primary taskbar alignment", then select the Centered option.
