### ISSUE TITLE
Can't pin some apps to start menu

### ISSUE THREAD

**Issue by Lanfan4** [valinet/ExplorerPatcher#1170]
Hey, I tried to pin the Control Panel and Recycle Bin to the Windows 10 start menu, but it didn't work. I have searched for some methods to solve this problem, but to no avail.

**Comment by sqwirral** [comment]
Also failed when trying to pin `This PC` from here:
![image](https://user-images.githubusercontent.com/243372/227055167-b7b059af-d72e-40c0-9eea-90560bab0f5f.png)

**Comment by andrew-karelin** [comment]
same here

**Comment by azerik92** [comment]
> I cannot pin anything to start menu at all in Windows 10 mode... Rightclik, "pin to start" does nothing and cannot drag icons to the menu.

To pin items to the Win10 Style Start Menu you need to click this option in the ExplorerPatcher Properties app. It will open a tweaked Explorer window that allows you to pin things to the Win10 Start Menu. So long as you navigate within that opened Explorer window anything can be pinned, but if you close it you will have to reopen it from the Properties app window again.

![Screenshot 2023-04-06 025831](https://user-images.githubusercontent.com/74346616/230296020-401a5da0-05f8-4c02-80ed-1a4bbaf720ec.png)

**Comment by NeoCyrus** [comment]
The "pin tiles to Windows 10" option doesn't work for me, it does nothing.

**Comment by pyrates999** [comment]
This is the same as this: https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. Note that the first time an object in explorer is pinned, this may happen:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/8bd959c2-f303-4993-b01a-76259f57500c)

In this case you can unpin it and pin again which will always work. I try to find a fix for this.

**Comment by Amrsatrio** [comment]
I've pushed a new prerelease that has flawless Pin to Start/Unpin from Start in Explorer and Start Menu. Just the Search window left because EP isn't loaded there.

**Comment by chiefisreal** [comment]
I like how the Pin items to start workaround is no longer their.

Amazing, where did it go?

**Comment by Amrsatrio** [comment]
???

**Comment by chiefisreal** [comment]
> > I cannot pin anything to start menu at all in Windows 10 mode... Rightclik, "pin to start" does nothing and cannot drag icons to the menu.
> 
> To pin items to the Win10 Style Start Menu you need to click this option in the ExplorerPatcher Properties app. It will open a tweaked Explorer window that allows you to pin things to the Win10 Start Menu. So long as you navigate within that opened Explorer window anything can be pinned, but if you close it you will have to reopen it from the Properties app window again.
> 
> ![Screenshot 2023-04-06 025831](https://user-images.githubusercontent.com/74346616/230296020-401a5da0-05f8-4c02-80ed-1a4bbaf720ec.png)

This is missing now.

**Comment by Amrsatrio** [comment]
Because we do not need it anymore.

**Comment by chiefisreal** [comment]
I just tried release version still didn't work (Latest). Tried pre release Ver and it worked. 

Sooooooo....yeah I think you still need it.

**Comment by Amrsatrio** [comment]
Every prerelease build will soon be a release build. So.... as long as there is an EP version that can pin to start without that workaround, we don't need that thing anymore. I've removed the code for that link anyways.

**Comment by chiefisreal** [comment]
Cool

But I got a much bigger issue probably not the place but you seem to know whats up. I had the new file explorer with the gallery and removable tabs then I installed EP and my explorer reverted to the version that launched with tabs no gallery or separable tabs. Tried uninstalling and still messed up. Any ideas?

**Comment by Amrsatrio** [comment]
Revert the command bar to Windows 11 before uninstalling EP. EP's method of disabling the command bar breaks the new Home, Gallery, and the new context menu.

**Comment by chiefisreal** [comment]
It was set to windows 11. Thats what I used for the tabs. Only thing I wanted was the Windows 10 start menu everything else was stock (great job on that menu its amazing)
