### ISSUE TITLE
Taskbar issue when using fullscreen borderless window

### ISSUE THREAD

**Issue by Joaquin500** [valinet/ExplorerPatcher#1173]
Every few random minutes a new explorer window appears containing the Start folder. 

EDIT: Finally I have solved this issue, which is not related to ExplorerPatcher but to the new Explorer window tab feature. In case someone else has the same issue, disabling the feature solves it.

Joaquín

**Comment by Joaquin500** [comment]
Happy that my post have helped you. I was getting crazy with it too, and couldnt find peace until I found a fix. 

From what I've read, Microsoft is aware of the bug and supposedly it will be fixed in some future Windows uptade. In the meanwhile, however, it would be nice if they added an option to disable the Explorer tabs feature, so we do not need to mess with the registry.

**Comment by Poopooracoocoo** [comment]
>Finally I have solved this issue, which is not related to ExplorerPatcher but to the new Explorer window tab feature. In case someone else has the same issue, disabling the feature solves it.

Closing as it sounds like its not related to EP
