### ISSUE TITLE
Issue in Windows build version 22621.1413

### ISSUE THREAD

**Issue by Krowne** [valinet/ExplorerPatcher#1174]
This is the last current Windows update, and the last update for Explorer Patcher, but something very strange is going on. On my current work computer it works perfectly with no issues, but on the second computer, upon installation it reboots 3 times, and force closes saying update to the latest version or uninstall waiting for an update. So how is it possible that being the same version of the system on both computers, and the same version of Explorer Patcher, on one it works perfectly as always, and on the other this error is occurring?

If there is any way to get a record, please tell me how.

**Comment by monkeeboy3** [comment]
I have information that _might_ be relevant. When 22621.1413 initially released, I was running ExplorerPatcher 53.1 and ran into the issue of `Win+Tab` not working with the Windows 10 taskbar (and all the related issues), which I found sufficiently aggravating to uninstall the Windows update until EP was patched. Now on the latest version of EP (54.5), I decided to try reinstalling 22621.1413, only to run into this same crash loop, which also happened on a fresh install of both 54.5 and 53.1 (the latter having the added bonus of not having the mechanism to break the loop).

So now I'm back on my previous Windows build again. The next logical step seems to me to be trying a fresh install of EP 53.1, updating Windows, and then updating EP, but I'm a little leery of experimenting too much, as I just recently had to replace my computer unexpectedly.

**Comment by Krowne** [comment]
The only difference between the version that works for me and the one that doesn't. It's that the one that works is from an update of the previous version, and the one that doesn't work was directly installing the latest version.

**Comment by monkeeboy3** [comment]
Right, but on the one where it works, did you update to the current version before or after updating to Windows 22621.1413? Because if it's after, we might be two points on a line, is what I'm trying to get at.

**Comment by Krowne** [comment]
Yes, I did both tests, doing it with a previous version and then the latest version, and also the latest version directly, but that wasn't the problem. The problem was because of what I am going to say next.

The program was failing and gave the error after the 3 restarts. It was because I was trying to install it in the System Administrator session, and apparently, you cannot use the Explorer Patcher program as System Administrator, you have to do it with a user other than the Administrator, but what he be an administrator.

The reason why I wanted to do it as System Administrator, is because I was preparing a custom Windows ISO with the programs I use the most, but once I log in normally, the program works fine, so I will have to wait to finish installing the ISO to install Explorer Patcher, because I can't leave it pre-installed in the system since it gives the error that I have commented in this post.

**Comment by Krowne** [comment]
Yes, I did both tests, doing it with a previous version and then the latest version, and also the latest version directly, but that wasn't the problem. The problem was because of what I am going to say next.

The program was failing and gave the error after the 3 restarts. It was because I was trying to install it in the System Administrator session, and apparently, you cannot use the Explorer Patcher program as System Administrator, you have to do it with a user other than the Administrator, but what he be an administrator.

The reason why I wanted to do it as System Administrator, is because I was preparing a custom Windows ISO with the programs I use the most, but once I log in normally, the program works fine, so I will have to wait to finish installing the ISO to install Explorer Patcher, because I can't leave it pre-installed in the system since it gives the error that I have commented in this post.

Therefore, I close the post, since this is working correctly.
