### ISSUE TITLE
how to uninstall this program?

### ISSUE THREAD

**Issue by dangdkhanh** [valinet/ExplorerPatcher#1175]
i accidentally pressed reset and it caused my classic menu rightclick to revert back to win11 style.
I can't fix the registry either. strange.

**Comment by Krowne** [comment]
It explains it in the documentation.

https://github.com/valinet/ExplorerPatcher/wiki#uninstalling

**Comment by tahayaseenp** [comment]
> 

uninstalling it will not change it back to the classic style
you can run this command in cmd to restore the old menu

`reg.exe add “HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32” /f & taskkill /f /IM explorer.exe & start explorer.exe
`

**Comment by dangdkhanh** [comment]
hi @tahayaseenp ,
genius, this worked as expected.
