### ISSUE TITLE
Start menu App list.

### ISSUE THREAD

**Issue by HongYue1** [valinet/ExplorerPatcher#1176]
Windows 10 Start menu App list won't be hidden after updating to Windows 11 (22621.1344)
Reinstalling and resetting won't fix the problem.

![image](https://user-images.githubusercontent.com/87040288/227000436-712b514d-5d82-4155-99c6-4880931a3512.png)

![image](https://user-images.githubusercontent.com/87040288/227000510-bc0e7503-dc00-4f55-9dc6-acfe35f6f49f.png)

**Comment by 200433zc** [comment]
WIN10 option is not work on my computer22621.1413

**Comment by Poopooracoocoo** [comment]
Cannot reproduce with ExplorerPatcher version 22621.1413.54.5 for Windows 11, OS build 22621.1413. 
Also please read the rules that the maintainer has put here. It tells you to use discussions and what to include in there.

**Comment by HongYue1** [comment]
> Cannot reproduce with ExplorerPatcher version 22621.1413.54.5 for Windows 11, OS build 22621.1413. Also please read the rules that the maintainer has put here. It tells you to use discussions and what to include in there.

Ok I closed it.
