### ISSUE TITLE
Windows + X menu suddenly stopped working for me

### ISSUE THREAD

**Issue by jasoncaserta** [valinet/ExplorerPatcher#1180]
It used to work but no longer does.

**Comment by jasoncaserta** [comment]
![image](https://user-images.githubusercontent.com/9168525/227070296-7e70952b-5c62-4e6f-9be1-a5810449e60f.png)

**Comment by topia** [comment]
Unfortunately, Insider previews aren't supported. (if you find the solution and send PR, it's so lovely)

**Comment by mcoleksajr** [comment]
> Unfortunately, Insider previews aren't supported. (if you find the solution and send PR, it's so lovely)

I did not know this. I signed in just so I could thank you!

**Comment by Amrsatrio** [comment]
Closing this as newer EP builds should try to make Win+X work when symbols are not available or before symbols are downloaded.
