### ISSUE TITLE
Search Inside Start Menu not working after latest update

### ISSUE THREAD

**Issue by zaltanis** [valinet/ExplorerPatcher#1198]
Not the first time this has happened, but after the latest update I'm no longer able to search within the start menu, usually I can start typing and programs will filter, but doenst work anymore after the latest update.

**Comment by zaltanis** [comment]
though this seems to have resolved itself after a reboot, the search breaking has happened on multiple occasions

**Comment by Poopooracoocoo** [comment]
Please read what was strikethroughed in https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems. At minimum, state what EP version, OS build, and whether you have any third party programs that modify the shell such as OpenShell, Start11, StartAllBack, 7+ Taskbar Tweaker.
