### ISSUE TITLE
Implement Crash Detection on builds newer that you expect 

### ISSUE THREAD

**Issue by petersvp** [valinet/ExplorerPatcher#1199]
Hello. I suffered from the crash loop issue in Moment 2 update. Had to reinstall Windows and lost my office retail key in the process among all the annoyances.

Please, implement Crash Detection in ExplorerPatcher. Implement something that if it detects crashes just bails to do anything. You can detect the entries in Event Viewer for example.

I'm firing this as issue because the damage it can do to users who don't know how to deal with this is annoying.

Consider adding a hardware key checks. For example of certain key is being held down during EP dll init cancel everything and bail out too. With such a complex tool safety must be an issue that is top priority. 

Also is some Microsoft Employee reads this comment... MICROSOFT PLEASE GIVE US OPTIONS TO USE SMALL TASKBAR, VISIBLE TASKBAR LABELS AND USING THE OLD CLASSIC RIGHT CLICK MENU. THIS IS BASIC USABILITY FEATURE. START LISTENING TO YOUR USERS AND YOUR PARTNERS.

**Comment by valinet** [comment]
There is this: https://github.com/valinet/ExplorerPatcher/commit/d7e5b7d3c965803d4d52aefd7fedefe11e3518c4

**Comment by petersvp** [comment]
That's nice. Better keep this issue open for a while so more people see that this is actually a thing. 

That is until the crash wave caused by the moment 2 update fades away. And thanks. 

Obviously my fault was that I'm not updated. And thanks for this excellent tool. Windows 11 comes with great optimizations under the hood... And horrible forced design decisions.

**Comment by Amrsatrio** [comment]
Seems like it's really been "a while" since Valinet implemented  repeated crash detection. Now everyone knows that EP has it (and I'm really thankful too so I'd have the chances to fix my dumb mistakes when developing EP), therefore this can be closed now.
