### ISSUE TITLE
Fix the Broken Buttons on Win10 Wi-Fi Flyout and Win-X menu

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#1201]
The buttons (Wifi, Airplane Mode, etc) are broken in Win10 Wi-Fi Flyout. These buttons need fixes.

![2023-03-27_19h34_36](https://user-images.githubusercontent.com/93650504/227964033-14c24dc8-535a-46d2-bdd2-33391ec218d5.png)

**Comment by jshir** [comment]
+ vote for the issue in the OP (I'm not bothered by the Win11 power menu though)
Would really like those buttons to work.

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. You don't need to delete dxgi.dll from ShellExperienceHost anymore.
