### ISSUE TITLE
Safely Remove Hardware and Eject Media no longer working after update.

### ISSUE THREAD

**Issue by Seeker1970** [valinet/ExplorerPatcher#1203]
I received an update for Explorer Patcher last night and now I cannot use the Safely Remove Hardware feature in the system tray.  When I click on it, everything hangs up for a second, everything disappears off the taskbar and after 15 or so seconds my start button and pins apps such as Firefox and Chrome reappear, but if I go back to the Safely Remove Hardware and click it, it just repeats the same issue.  I just noticed it does the same thing if I try to access the Bluetooth setting from the tray icon as well.

**Comment by ofthelit** [comment]
I have the same issue with the Bluetooth Devices tray icon. The Eject Media feature works for me.
