### ISSUE TITLE
Unable to find symbols for 10.0.22000.282....

### ISSUE THREAD

**Issue by jrg63** [valinet/ExplorerPatcher#121]
I'm on the release preview ring for Windows 11 Pro and a new update was applied this morning. I installed the DLL and followed the instructions but its not working. I get a pop up that says

![image](https://user-images.githubusercontent.com/25476144/137567740-517ed984-69cb-42fe-b89c-608247f3b50c.png)

Cannot find symbols for 10.0.22000.282

Any suggestions on how to resolve this?

**Comment by valinet** [comment]
Well, at first run, it has to download some data from Microsoft. Unless it does that, it won’t function. Make sure nothing blocks or interferes with that. You should see network activity after that message (in Task Manager for example) and then after some time when the download finishes, Explorer would restart and that’d be it, you’d see the old taskbar and from there on it starts working.
