### ISSUE TITLE
Unpin shortcut from taskbar, but didn't delete the shortcut

### ISSUE THREAD

**Issue by HumanMus1c** [valinet/ExplorerPatcher#1210]
If pin this app to taskbar again, it will make a copy rename with XXX(2)(3)

**Comment by redkurn** [comment]
having a similar issue, but mine just won't unpin.

**Comment by pyrates999** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Amrsatrio** [comment]
This doesn't happen with the recent builds of Windows 11 22H2 and EP. Closing this issue.
