### ISSUE TITLE
Can't switch between Win11 and Win10/7 command bar

### ISSUE THREAD

**Issue by danielstreba** [valinet/ExplorerPatcher#1216]
Hello!

First things first, thank you developing for this project!

File Explorer > Control Interface switching does not seem to work. Can't switch back to Win10 or Win7 ribbon. I can select the Windows 10 ribbon or the Windows 7 command bar config setting instead of the Win11 one, but after that the command bar stays the same, it does not actually switches the UI. Everything else works perfectly (like Windows 10 fly outs and taskbar). I tried restarting explorer and my PC too, after changing the settings.

This is a freshly reinstalled Windows instance, the ISO came from MSDN, so no ISO tweaking shenanigans. This didn't work on the previous installation either, but I thought something broke it, so I didn't cared about it. I don't use any other shell/explorer modifying program (like StartAllBack or etc)

I tried searching here in the issues section about this, but I didn't found anything.

Am I doing something wrong or MS broke something?

Thank you,
Daniel

ExplorerPatcher version: 22622.1413.54.5.38505974ea340d7f
Windows version: Win11 Enterprise 22H2 (10.0.22621.1485)

![image](https://user-images.githubusercontent.com/16244188/228881893-0e85ae49-da31-41be-b9a3-d23d24e8bc43.png)
![image](https://user-images.githubusercontent.com/16244188/228882090-d80b61bf-a735-41fb-8f60-d818b57cb84e.png)

**Comment by atagliafe** [comment]
I have the same issue.

Also the modern search bar is permanently disabled irrespective to the Exploter Patcher's option.

ExplorerPatcher version: 22622.1413.54.5
Windows version: Win11 Enterprise 22H2 (10.0.22621.1555)

Thank you for any help or suggestion.

Alberto


![image](https://user-images.githubusercontent.com/130714421/231908606-82161ce8-73f7-44d2-b493-02b2549fe32e.png)

**Comment by kotenok2000** [comment]
I have the same problem.
I have set UAC Run all administrators in Admin Approval Mode to disabled in secpol.msc

**Comment by kotenok2000** [comment]
I also have "launch folder windows in a separate process" enabled

**Comment by Poopooracoocoo** [comment]
As per https://github.com/valinet/ExplorerPatcher/issues/1757#issuecomment-1734032018, closing
