### ISSUE TITLE
Start Menu issue

### ISSUE THREAD

**Issue by SufyHub** [valinet/ExplorerPatcher#1219]
so apparently when i go to Start Menu, i try to change the start menu style to win 11, it doesnt show up, neither do 4 other options, i am on the latest version of windows 10 22H2

**Comment by oOFinaLOo** [comment]
Try downgrading to 22621.1413.54.4 may be temporarily fixed

**Comment by denistorresan** [comment]
Seems that when click on Start Menu, the process crash and restart. After various crash the following message appears.

![immagine](https://user-images.githubusercontent.com/1846826/229080504-4190710d-565e-4cfc-a5f1-2665c57a6563.png)

**Comment by unique-mysticism** [comment]
I have the same issue and it happened after updating my windows

**Comment by coldimmune** [comment]
Start menu completely unresponsive today (after issues with searching since last update)

Rolled back to 22621.1413.54.4 and it's working properly

**Comment by DerpDerpingtonIsHere** [comment]
> Seems that when click on Start Menu, the process crash and restart. After various crash the following message appears.
> 
> ![immagine](https://user-images.githubusercontent.com/1846826/229080504-4190710d-565e-4cfc-a5f1-2665c57a6563.png)

This is a separate issue that is known about already. Stop reporting about stuff under things that are not relevant with your issue. Also, report these issues under the discussion tab if it hasn't been reported already. It literally says this at the top of the issues page.

**Comment by SufyHub** [comment]
no like guys you dont get it. let me just show you a picture.
![image](https://user-images.githubusercontent.com/129418728/229372203-531b9df6-af2e-48b7-8838-d6916e5708fd.png)
where is the start menu option to change it, like to win 10 or 11.

**Comment by mbartlett21** [comment]
@SufyHub 
If you are on Windows 10, you can't use any features that are from Windows 11, such as the start menu or taskbar.

**Comment by SufyHub** [comment]
@mbartlett21 thanks for the info.

**Comment by topia** [comment]
@SufyHub, now this is not an issue (it may become a feature request, but I think it's out of the scope of the software - it needs reimplementing the windows 11 feature in windows 10). So please consider closing this issue.
