### ISSUE TITLE
[Not Breaking][Bug]Pressing Windows key before startmenu is fully closed show pinned&recent

### ISSUE THREAD

**Issue by BraINstinct0** [valinet/ExplorerPatcher#122]
How to reproduce:
1) set Start menu to show All apps by default
2) press Win key to open start menu
3) press Win key (quickly) twice to close&open start menu quickly
4) repeat 3)
5) press Win key, give Start menu time to close
6) press Win key to open start menu

3) and 4) shows the original pinned&recent, ad 6) shows the intended All apps.
This is not a breaking bug&doesn't seem to be important enough to be mitigated, but reporting since this still doesn't seem to be the intended behavior.

Windows 11 Home, build 22000.258
EPatcher 22000.258.30.3

**Comment by valinet** [comment]
It's a bug in Start menu itself, I'd might even add to that, the way it seems to me.

**Comment by BraINstinct0** [comment]
Sorry, didn't see the dupe before

**Comment by valinet** [comment]
No worries, provided the link so I do not have to reiterate the same idea basically.
