### ISSUE TITLE
The console/code opens up on startup and is impossible to close without closing ExplorerPatcher.

### ISSUE THREAD

**Issue by BrieferMoss1606** [valinet/ExplorerPatcher#1222]
![image](https://user-images.githubusercontent.com/129512589/229114822-79bf9fa6-ffd7-4cca-bdf0-fe1f14c1988a.png)
The image above opens each time I start up and closing it 3 times gives me the error for when it closes 3 times in 10 seconds. I genuinely have no idea what is going on, as when I first downloaded it everything was completely fine. 

I have tried uninstalling and reinstalling, restarting my computer and restarting the file explorer from task manager.

![image](https://user-images.githubusercontent.com/129512589/229115632-18b59e53-14d6-4ab4-8984-b3a17fe52877.png)
Here is what it looks like on my taskbar.

Also, is there any way for the names of applications not to appear to the right of the application icon on taskbars? Thanks.

**Comment by BrieferMoss1606** [comment]
Oh and by the way, I installed ExplorerPatcher's setup from the majorgeek website and the master file from github.
I couldn't find where the setup.exe was in the master file so I just just got it from majorgeek.

**Comment by topia** [comment]
Turn off "Enable console" from "Advanced", in ExplorerPatcher's Properties. after that, you can close it.

Also, you can download the setup from the release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1413.54.5_0344a5e

**Comment by BrieferMoss1606** [comment]
oh thank you, I didnt know it was that easy
