### ISSUE TITLE
Bug with File Explorer after opening from Search Results

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#1224]
I don't know how to write this bug so I made a clip to show this.

Steps to Reproduce : -
1. Search for any app.
2. R-Click and choose "Open File Location" option.
3.  You will get the buggy File Explorer with no Close,Minimize,Max. buttons.

It happens in every 9/10 times.

https://user-images.githubusercontent.com/93650504/229163055-cc8f08cb-9c25-4596-8e70-724327b3b8ea.mp4

( Don't go on system tray icons as I use Rectify11 Icons )

**Comment by Vipin2003** [comment]
This only happens after installing EP...I tried 10-15 times after uninstalling EP, it works fine. But with EP installed, this happens 12/15 times. Don't Know Why?

**Comment by Obi-Shinobi** [comment]
I've had some of the same issue, I've also had it just crash file explorer when try to open file location from the task manager .  Sometimes it looks like it tries to open it twice really fast, or it appears like it tries to do that.

**Comment by Amrsatrio** [comment]
Works just fine on 22621.1992 and 2134. If you switched to the Win11 command bar from Win7 or Win10, please make sure to restart Explorer or you will see this abomination:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/895dd426-8f37-40d6-80d9-ded817dde803)
