### ISSUE TITLE
Cant create new local user when EP is installed

### ISSUE THREAD

**Issue by GoneGrim** [valinet/ExplorerPatcher#1226]
Today I created a new user account on my win11(22H2) PC. When it was set up, I wanted to log in for the first time. After the "we are setting everything up for you" screens, the setup screen for the userdata started opening up over and over again, making it impossible to use them. That meant I was stuck in the screen and had to shut down my PC.
Looking in to the userprofile with the other account on my PC, I found crashdumps for the explorer. After uninstalling EP, I was able to log in to the profile and nothing looped like before.
So something is happening with the EP and the setupscreen by windows.

https://user-images.githubusercontent.com/107324397/229167232-7bf8d60c-c51a-4515-813d-604698835907.mp4

**Comment by Parsa307** [comment]
Hold Reset Button And Turn On The Computer And Reset 3 Time Before Windows Starts And It's Say Preparing Automatic Repair And Boot To Safe Mod And Remove ExplorerPatcher In Control Panel

**Comment by Parsa307** [comment]
And Create A New User

**Comment by gillius** [comment]
I also experienced the same issue, workaround is to uninstall EP. If you wait for about an hour the initial "getting things ready" screen it goes go away. Then you get a desktop where EP says it failed in a loop so disabled itself. You are left at desktop with no shell process (EP or stock Win 11) but start button does work. When you log out and back in you get the actual setup screens where you pick location, ad ID, etc. settings and that loops forever when EP is installed.

Uninstall EP and finish creating the user here... Then once user is created you can re-install EP.

**Comment by Amrsatrio** [comment]
The underlying culprit should be fixed now with the latest prerelease, but I haven't tested creating a new user while EP is installed. Feel free to reopen if it's still crashing.
