### ISSUE TITLE
Volume indicator issue using Windows 10 style

### ISSUE THREAD

**Issue by malacaton** [valinet/ExplorerPatcher#1235]
Since I installed Windows 11 22H2 update, using the bar in Windows 10 style, when I turn the volume up or down from the keyboard the volume indicator no longer appears. Is it a known issue? Do you know if there is a solution for that?

**Comment by Andrew1988123123** [comment]
try this https://github.com/valinet/ExplorerPatcher/issues/1093#issuecomment-1474861939
