### ISSUE TITLE
Window snap disabled

### ISSUE THREAD

**Issue by maziogra** [valinet/ExplorerPatcher#1240]
When I installed the application the **window snap**  was disabled.
I tried to reactivate it (looking for ExplorerPatcher setting which deactivate it) but It didn't work.
I would like to specify that this bug occurred as soon as the application was installed, therefore before my customization.
My windows version is Windows 11 22H2 (build 23424.1000)

**Comment by Amrsatrio** [comment]
Does the issue still persist now with the latest EP and Windows builds? Note that we do not support the Canary channel and we only partially support the Dev channel.

**Comment by Amrsatrio** [comment]
Does the issue still persist now with the latest EP and Windows builds? Note that we do not support the Canary channel and we only partially support the Dev channel.

Since window snap works just fine on 23545.1000 Insider Dev, I will be closing this issue.
