### ISSUE TITLE
'start manu\position on screen' doesn't work properly

### ISSUE THREAD

**Issue by EvilDragonfiend** [valinet/ExplorerPatcher#1250]
![image](https://user-images.githubusercontent.com/87972842/229655787-d778fd7b-4738-4a74-803f-67a03d5855d5.png)

My window start menu button (*taskbar) is located at right side
If start menu window has taken search strings (i.e. CMD), the window location is supposed to be right side, but it moves to down as if my taskbar is at bottom

![image](https://user-images.githubusercontent.com/87972842/229656287-713f1731-5ccf-41f4-aa77-c23a8d48b6d7.png)

**Comment by rammiebonbon** [comment]
I also have this issue. Just wondering if it's being looked at.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.

**Comment by EvilDragonfiend** [comment]
> duplicate of: #1803
> 
> Please close this.

Hearing that it's a dupe when mine was posted earlier than it sounds very weird but I understand the point here. Still, you'll need to be careful to say such because not everyone will understand the detail of your request. Please be nice too.
