### ISSUE TITLE
Font switches to underlined Courier 8 in Simple Window Switcher and Properties

### ISSUE THREAD

**Issue by zulc22** [valinet/ExplorerPatcher#1252]
It prevents many of the options from being completely readable, cutting them off with ellipses. Sometimes it does switch to a proper display font for me, but it's usually underlined Courier 8.

**Comment by Amrsatrio** [comment]
Out of 20ish VMs and physical devices I've installed EP on with varying Windows builds, I've never had them switch to Courier 8. So I think this issue is isolated to your installation which is not worth our time to investigate. Sorry.

**Comment by zulc22** [comment]
I don't know how to recreate it either, I'm afraid. I don't think it's still happening for me anyway; I do apologize for wasting your time with that.

**Comment by sashaaaaaaaaa** [comment]
Happens here too so it's not isolated.
