### ISSUE TITLE
Start menu won't change

### ISSUE THREAD

**Issue by LittleTimmy52** [valinet/ExplorerPatcher#1253]
So I have set the style to windows 10, no matter what I do, the menu still looks like windows 11. I got the latest release and i have tried resetting the explorer to no avail

**Comment by LittleTimmy52** [comment]
oh also the window switcher won't change either, stays the same after reset explorer

**Comment by adi32PL** [comment]
I have the same.
Windows 11 22h2 (build 22621.1265).
Changing Start Menu style to W11 and back to W10 doesn't help.
![start menu](https://user-images.githubusercontent.com/10198869/231679541-2dc3a2eb-acb2-485e-9731-4a50e8c62588.png)
