### ISSUE TITLE
Locking the Taskbar causes explorer menu to be obscured 

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [valinet/ExplorerPatcher#1255]
Windows 11 Pro all updates
Open-Shell 4.4.170

with the taskbar in window 10 mode with Explorer Patcher and Open-Shell installed for both menu and explorer locking the taskbar causes the icons of Classic Explorer to become justified to the left, unlocking it and reopening explorer and the icon justify right (where its supposed to be)

Statusbar Locked
![Statusbar Locked](https://lookimg.com/images/2023/04/04/QTXFYR.png)

Statusbar Unlocked
![Statusbar Unlocked](https://lookimg.com/images/2023/04/04/QTXHne.png)

**Comment by Amrsatrio** [comment]
We do not fully support scenarios where other tweak software are present in the system, so in this case please get in touch with Open Shell developers, if you want. Sorry.
