### ISSUE TITLE
inside preview with stack

### ISSUE THREAD

**Issue by merunaaa** [valinet/ExplorerPatcher#1256]
When I restart explorer in windows 11 inside preview with the properties start menu style set to windows 10, explorer will not open.
In some builds, right clicking on the taskbar forces a restart.
Please address this issue.

**Comment by topia** [comment]
Why do you want to post to both places (issues and discussions)? By the way, insider builds are not supported by the developer. Please consider digging by yourself and submitting the PR.

**Comment by Vipin2003** [comment]
Yup...it is crashing on build 22621.1485. Not even able to r-click on both Win10 and 11 Taskbar. It get restart automatically n after 2-3 times, the EP get disabled automatically. Disabling Search box doesn't fix it.
