### ISSUE TITLE
Taskbar icons can't collapse

### ISSUE THREAD

**Issue by aprilherron** [valinet/ExplorerPatcher#126]
Just installed your latest release (22000.258.30.4), everything works very well (thank you so much for this btw), but I can't seem to collapse my taskbar tray icons (on the right). I see in the screenshot you have the little carrot ( ^ ) to show/hide these, but my taskbar is now just displaying all of them and I don't see any setting to toggle this in the "Properties" menu.

**Comment by valinet** [comment]
Look in the system taskbar settings, there is an option there to collapse unused notification icons. It’s a Windows setting, not something enabled by ExplorerPatcher.

Thanks.

**Comment by KingKrimmson** [comment]
In Windows 11 this is controlled on a _per app_ basis, and definitely have apps I'm trying to hide.

![2021-10-16 11_20_30-Settings](https://user-images.githubusercontent.com/7947742/137592950-0b19567f-27ba-4da8-ada8-07463b5de3e0.png)

And yet, they _all_ appear on the taskbar after installing ExplorerPatcher (this was not the case prior to installing)

![2021-10-16 11_20_51-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/7947742/137593002-2d1b0bae-be42-4009-8f80-96172d765040.png)

**Comment by valinet** [comment]
Yeah, idk why, for me it does not do that, so that's why I don't have experience with this... I don't touch that area in code in any way. Maybe try to see if StartAllBack behaves the same...?
