### ISSUE TITLE
[Support Request/Appeal] Windows 11 latest canary insider build support

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [valinet/ExplorerPatcher#1263]
Can this patch be supported on this OS build and version. I've tried but the explorer is crashing, slowly starting and many settings don't apply property and even windows start menu doesn't work so it's not yet supported by this version and build of windows.

So, if you can add support for this build, thank you so much in advance! 🥰

**Comment by mertgoksel** [comment]
+1

**Comment by pyrates999** [comment]
According to comments from others, insider and canary builds do not have symbols to be downloaded.  Therefore they can never be supported.  Only official releases can.

**Comment by Poopooracoocoo** [comment]
They're moving targets.

**Comment by admin-elvistrujanovic** [comment]
> They're moving targets. 

What that means - while they are moving targets, will they work on some kind of installer that will build ExplorerPatcher for the build version that machine currently is running? Or it will never be possible to add support for Insider Builds

**Comment by pyrates999** [comment]
> > They're moving targets.
> 
> What that means - while they are moving targets, will they work on some kind of installer that will build ExplorerPatcher for the build version that machine currently is running? Or it will never be possible to add support for Insider Builds

It means the code is not final and can change with each new release.

**Comment by admin-elvistrujanovic** [comment]
> > > They're moving targets.
> 
> > 
> 
> > What that means - while they are moving targets, will they work on some kind of installer that will build ExplorerPatcher for the build version that machine currently is running? Or it will never be possible to add support for Insider Builds
> 
> 
> 
> It means the code is not final and can change with each new release.

So... there is a high chance just like Rectify11 patcher to work on any build based on how their patcher patching the system

**Comment by pyrates999** [comment]
> > > > They're moving targets.
> > 
> > 
> > > 
> > 
> > 
> > > What that means - while they are moving targets, will they work on some kind of installer that will build ExplorerPatcher for the build version that machine currently is running? Or it will never be possible to add support for Insider Builds
> > 
> > 
> > It means the code is not final and can change with each new release.
> 
> So... there is a high chance just like Rectify11 patcher to work on any build based on how their patcher patching the system

0% chance.

**Comment by admin-elvistrujanovic** [comment]
> > > > > They're moving targets.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > What that means - while they are moving targets, will they work on some kind of installer that will build ExplorerPatcher for the build version that machine currently is running? Or it will never be possible to add support for Insider Builds
> > > 
> > > 
> > > It means the code is not final and can change with each new release.
> > 
> > So... there is a high chance just like Rectify11 patcher to work on any build based on how their patcher patching the system
> 
> 0% chance.

WHAT.... No man

That's not true

It's not that hard for them who knows the whole code very well and coding to just build an installer for ExplorerPatcher that will compile/build ExplorerPatcher for their OS Build
