### ISSUE TITLE
[Bug] People widget appears instead of a weather widget

### ISSUE THREAD

**Issue by michaelmuselik** [valinet/ExplorerPatcher#1266]
Instead of the weather widget, a people widget appears after some time. Explorer must be restarted.
Win version 21H2 22000.176.1

https://user-images.githubusercontent.com/73330785/230437149-443df687-1ba0-4b98-866d-66019686911e.mp4

**Comment by jw-mn** [comment]
Got the same issue. Rolled back to 22621.1344.53.1. Uninstall and reinstall the older version. This fixed it for me.

Check here: https://github.com/valinet/ExplorerPatcher/issues/1310
