### ISSUE TITLE
Windows 10 start menu won't open

### ISSUE THREAD

**Issue by luisl173** [valinet/ExplorerPatcher#1267]
After changing start menu to the Windows 10 one, clicking on the start menu does nothing, I tried reinstalling but still nothing happens

Windows version: Windows 11 (tiny11) 22H2 22621.1485
ExplorerPatcher version: 22621.1413.54.5

Any other features work as expected, except the already mentioned Windows 10 start menu one.
Console shows nothing.

Another issue but less important, no idea if in this case the win10 network selector should show only the text or also the rounded buttons with accent color, idk.
![image](https://user-images.githubusercontent.com/108156867/230481357-816c396b-e0a6-46fa-896e-6790a5baf0e3.png)

**Comment by antoniu200** [comment]
I second to this. The Windows 10 start menu does not open. I have attached the WER files generated by Event Viewer for this crash.
Using Windows 11 22621.1485 as well, but installed from official .iso file.

[viewer.zip](https://github.com/valinet/ExplorerPatcher/files/11179751/viewer.zip)

**Comment by warchlak** [comment]
After changing options randomly and multiple explorer restarts start menu started working. Strange.

**Comment by antoniu200** [comment]
Same here. Tried again and now it works. This is because the Symbols specific to the Windows 11 version you are running have been downloaded automatically in the background. Apparently, they are required for multiple modifications ExplorerPatcher allows, and apparently the Windows 10 Start Menu is included.
See #1274, I am tring to keep tabs on all functionalities that require Symbols before they start working properly.

**Comment by laneAfterRain** [comment]
same here.windows 22621.1413

**Comment by rzhangbq** [comment]
Same here. It worked before I updated my system (my previous windows version is 22000.1969, it worked), but it failed after updating to 22621.1413

**Comment by rzhangbq** [comment]
It works after I uninstall and install the app.

**Comment by luisl173** [comment]
Don't know why, but renaming dxgi.dll on StartMenuExperienceHost's install folder instantly fixes the start menu issue
![image](https://user-images.githubusercontent.com/108156867/230804306-3eee9c8d-7a4f-40f4-b71a-12e6273b68e5.png)
