### ISSUE TITLE
File Explorer opens 

### ISSUE THREAD

**Issue by Ffffffmaa** [valinet/ExplorerPatcher#1277]
Hello, first of all i want to thank you for your great work, i have a problem, at "random" home folders open, like when going full screen on a player, alt tab on anything, i get sometimes like 1-2-3+ home folders opening in 2-3 seconds,

bellow i added my windows build version,
![image](https://user-images.githubusercontent.com/120339789/230715715-ef82daf4-9437-4b63-9d2e-5210742e7868.png)

And i'm using the Patchexplorer version reflected bellow
![image](https://user-images.githubusercontent.com/120339789/230715773-a20cfe1a-5a66-4af0-8948-f05dbdb7297b.png)

Thank you.

**Comment by etnMathy** [comment]
Hi! I have identical problem! It's pretty darn annoying :( . Any luck solving it?

**Comment by etnMathy** [comment]
Well. I was tinkering with the settings. And changed the tabing setting, meaning the the switching visual for alt-tab. 

> Hello, first of all i want to thank you for your great work, i have a problem, at "random" home folders open, like when going full screen on a player, alt tab on anything, i get sometimes like 1-2-3+ home folders opening in 2-3 seconds,
> 
> bellow i added my windows build version, ![image](https://user-images.githubusercontent.com/120339789/230715715-ef82daf4-9437-4b63-9d2e-5210742e7868.png)
> 
> And i'm using the Patchexplorer version reflected bellow ![image](https://user-images.githubusercontent.com/120339789/230715773-a20cfe1a-5a66-4af0-8948-f05dbdb7297b.png)
> 
> Thank you.

Try installing latest windows update. And try to tinker with the alt-tab visual setting (the window that shows when you alt-tabing). One of that thing worked for me...or it was something totaly else, I duno, I tried like everything (including reseting to default and reinstalling the thing :D )

**Comment by SanderGit** [comment]
I think this is a bug in Windows and not related to Explorer Patcher, [see this article](https://www.howtogeek.com/884624/youre-not-alone-windows-11-is-randomly-opening-file-explorer/).
