### ISSUE TITLE
Allow to dismiss Win+C hotkey

### ISSUE THREAD

**Issue by atbest** [valinet/ExplorerPatcher#128]
I used to use `Win + C` to start or activate browser with `autohotkey`, however, updating to Windows 11 disrupted this process. Even though I have uninstalled Microsoft Teams completely with `dism++`, pressing `Win + C` still open the Chat flyout, which is really annoying. 

I am glad to see that `ExplorerPatcher` can remap `Win + C` to open the calendar flyout, which is much useful than the original Chat flyout. In spite of this, I would like to know if it is possible to just dismiss the system `Win + C` function and leave it to users so that I can use it to start or activate browser with `autohotkey`.
Thanks.

**Comment by atbest** [comment]
It was the only hotkey that autohotkey could not take over, so I switched to a new one `Win + Q`. With ExplorerPatcher installed, autohotkey can take over `Win + C` now. I just forgot to changed it back. Thanks for the reminder.

**Comment by valinet** [comment]
I feel that freeing the hotkey for use with Autohotkey while also providing some default functionality is an acceptable compromise regarding this problem. Thanks for the input.
