### ISSUE TITLE
ExplorerPatcher: Taskbar won't automatically hide 

### ISSUE THREAD

**Issue by realdevnullius** [valinet/ExplorerPatcher#1286]
Per title. Whenever I unhide the taskbar, it won't hide anymore. I have to press Start - empty space in start menu and only then will it hide again. 

It's Windows 7 all over again! :(

Please advise? :)

**Comment by pyrates999** [comment]
Right click on the taskbar and select taskbar settings.  There's 2 options:
* Automatically hide the taskbar in desktop mode
* Automatically hide the taskbar in tablet mode

**Comment by realdevnullius** [comment]
["Automatically hide the taskbar"] option is enabled.

**Comment by pyrates999** [comment]
Both of them?

**Comment by Amrsatrio** [comment]
I do not observe this issues in the latest builds of 22621. If it still happens on your installation, you can reopen this issue.
