### ISSUE TITLE
UWP Apps Un-pin Themselves from Taskbar Frequently

### ISSUE THREAD

**Issue by lucasrevvo** [valinet/ExplorerPatcher#1291]
It appears to be random, or possibly when Windows installs an update. But UWP (Sticky Notes and Snip Tool) unpin themselves from the taskbar and require to be re-pinned from time to time. This doesn't happen to standard apps. Thanks

Windows 11 Pro: 22H2 22624.1546 and previous versions.
Patcher: 22621.1413.54.5 and previous versions.

**Comment by Amrsatrio** [comment]
This doesn't happen anymore woth the recent builds of Windows 11 22H2 and EP. Closing this issue. If this still happens, you may reopen this issue.
