### ISSUE TITLE
Notification area icons are all hidden, even if exceptions are added

### ISSUE THREAD

**Issue by stanciupaul** [valinet/ExplorerPatcher#1292]
All apps are hidden in the notification are, even those that were excepted and should be visible:

Excepted apps:
![image](https://user-images.githubusercontent.com/6516725/231081920-f5350316-9acc-4838-b1bb-2bc6ea080cd5.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/6516725/231082011-2e46d123-f605-4f74-9f68-8e4d22426c2b.png)

ExplorerPatcher setting which is affected:
![image](https://user-images.githubusercontent.com/6516725/231081216-2e86a5b9-a370-43cb-b365-4eb2fa29e7d8.png)

**Comment by topia** [comment]
Please use drag&drop to move an icon between the overflow and visible areas.

**Comment by stanciupaul** [comment]
@topia that trick seems to solve the issue, maybe it should be mentioned somewhere to make the user aware.

**Comment by topia** [comment]
Agreed. But recent updates broke many things, and devs may need more time to fix or note them.
(personally) I hope users try searching this forum and find workarounds by themselves.
