### ISSUE TITLE
Crash when clicking “windows” after installing Windows 11 Version 22H2 04 

### ISSUE THREAD

**Issue by mj17shAlice** [valinet/ExplorerPatcher#1300]
![bhu_steal](https://user-images.githubusercontent.com/56729639/231389855-1909efba-284c-42fc-9791-28a2617bd9d6.gif)

**Comment by tesar-tech** [comment]
I have the same. 
OS Build: 22621.1555
EP version: 22621.1413.54.5
When pressing "Start" button it restarts itself and not show the menu at all.

**Comment by izogfif** [comment]
Note to self: uninstalling update KB5023706 fixes the issue. Confirmed second time (uninstalled it or another one few weeks ago due to the same problem). Will probably have to reinstall in a few weeks once Windows decides to re-download and re-install it again...

**Comment by topia** [comment]
Could you confirm your ExplorerPatcher finished downloading the latest symbol?
It should be done if you enable Symbol download and keep running the explorer for a few minutes.

**Comment by JordanBerger** [comment]
Can confirm enabling "Enable symbols download", waiting for the notification that it completed, then restarting explorer resolved it. On build 22621

**Comment by mj17shAlice** [comment]
> Could you confirm your ExplorerPatcher finished downloading the latest symbol? It should be done if you enable Symbol download and keep running the explorer for a few minutes. (And restart file explorer after symbol downloading)

Done. I can't understand why the download wouldn't start until I click the notification.

**Comment by topia** [comment]
> Done. I can't understand why the download wouldn't start until I click the notification.

Minor correction: the notification showed after the download finished, but it'll be reflected only when Explorer starts.
