### ISSUE TITLE
Prevent System/About page being redirected to Settings not run. 

### ISSUE THREAD

**Issue by MANTISInf** [valinet/ExplorerPatcher#1302]
Prevent System/About page being redirected to Settings not run in lastest versions of Windows and ExplorerPatcher.

**Comment by Amrsatrio** [comment]
Works just fine on 23545.1000. Because of that and no more activities on this issue, I will be closing this.

**Comment by pyrates999** [comment]
This should be re-opened.

Windows Version: 10
Windows OS Build: 19045.3448
EP version: 22621.2361.58.1

Here's where it still sends you to system in the settings app:

1. Right click on This PC and click on properties

Expected Result:

It opens the system control panel

Actual Result:

It opens system in the settings app

Second area where this is happening:

1. Open up control panel
2. Click on System and Security
3. Click on System

Expected Result:

It opens the system control panel

Actual Result:

It opens system in the settings app
