### ISSUE TITLE
Windows Update (KB5025239)

### ISSUE THREAD

**Issue by igorank** [valinet/ExplorerPatcher#1307]
File explorer started crashing after new Windows update (KB5025239)

**Comment by vkochladze** [comment]
Yup, same here

**Comment by Worven** [comment]
Weather widget not work, cant load - no internet connection

**Comment by emilianog94** [comment]
Fixed it by disabling the option "Enable symbols download" under the Advanced tab and then clicking the "Restart File Explorer".

**Comment by Cthululz** [comment]
I've never had enable symbols download enabled.  It's still crashing everytime I right click the taskbar.  It has also been crashing every time my computer is woken from sleep and I have to hard reset to do anything.

**Comment by Cthululz** [comment]
Enabling symbols download and disabling my firewall and letting explorerpatcher crash 3 times to disable itself, then re-running it from the start menu seems to have done the trick.  Now it's running without crashing when i open the start menu or when i right click the taskbar.

**Comment by pyrates999** [comment]
Don't disable the symbols download option.  Explorer patcher uses that to patch windows explorer.  You'll get a notification when the symbols are done downloading.

**Comment by jobeid** [comment]
I had this right click crash issue after a previous Win11 update. To fix it: uninstall ExplorerPatcher, clean its registry footprint, i.e., delete its settings in the registry: 
HKEY_CURRENT_USER\Software\ExplorerPatcher
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher

(you can save/export them first to remember what your settings were)
Then start over again by reinstalling it clean.
Let me know if this works for you too.

**Comment by Mikeupoftea** [comment]
Hey, for any non-CS people here, I spent the last 3 hours trying to figure out how to fix the crashing issue. 
Here are the steps I did to fix the issue:

Step 1: 
Access your task manager by pressing ctrl+alt+del

Step 2: Locate and click 'Run New Task'; **Make sure you run it with administrative privileges.**
![image](https://user-images.githubusercontent.com/130623384/231630019-0ef30002-ab9f-46ca-8233-804a00966094.png)

Step 3: Type cmd and press run in the prompt
![image](https://user-images.githubusercontent.com/130623384/231630184-ac6c409a-b742-46da-a447-f14fc1528666.png)

Step 4: You want to locate the executable file that you used to install Explorer Patcher. To do this type **dir /s /b *.exe** in the command prompt and press enter. You'll find alphabetized list of executables. Locate the executable titled '**ep_setup.exe**'
![image](https://user-images.githubusercontent.com/130623384/231630785-068f237c-2f77-4469-880c-13cdc1e790c0.png)

Step 5: Write down the entire directory line and head back to the run new task prompt in the Task Manager.

Step 6: Type in the following prompt: **[ENTER THE DIRECTORY LINE HERE] /uninstall** ;**Make sure you run it with administrative privileges.**
For me it was: C:\Program Files\ExplorerPatcher\ep_setup.exe /uninstall

Once you run it, it should uninstall and it'll take a minute or two for your computer to work normally!!

Hope this helps :)

**Comment by topia** [comment]
ExplorerPatcher **currently** uses the dedicated registry key to store its required symbol data: `HKCU\Software\ExplorerPatcher\twinui.pcshell`.
So, you can delete cached symbol data with this command: `reg delete HKCU\Software\ExplorerPatcher\twinui.pcshell /f`.
After that, enable symbol downloading, wait for the symbol downloaded notification, and restart file explorer.

Warning: do not make a command mistake because that can break your Windows installation.

**Comment by Mikeupoftea** [comment]
> ExplorerPatcher **currently** uses the dedicated registry key to store its required symbol data: `HKCU\Software\ExplorerPatcher\twinui.pcshell`. So, you can delete cached symbol data with this command: `reg delete HKCU\Software\ExplorerPatcher\twinui.pcshell /f`. After that, enable symbol downloading, wait for the symbol downloaded notification, and restart file explorer.
> 
> Warning: do not make a command mistake because that can break your Windows installation.

Is that something I should run on the command prompt? I'm really unfamiliar with this whole process, lol.

**Comment by topia** [comment]
> Is that something I should run on the command prompt? I'm really unfamiliar with this whole process, lol.

You can run it on Powershell or the command prompt.
Maybe it can use directly via "Run new task," but I didn't test it, and you can't know success/failure because you can't get any message from it. So, I don't recommend it.

**Comment by sparc** [comment]
Not crashing, but task bar search icon does nothing, also search on start menu does not work

**Comment by Gufderald** [comment]
Got same issue; disabling and enabling symbols download did the trick for me. 

> Fixed it by disabling the option "Enable symbols download" under the Advanced tab and then clicking "Restart File Explorer" on the bottom left corner.
> 
> ![image](https://user-images.githubusercontent.com/38828911/231592680-e143d2ec-cedc-4fef-99ea-7db2180a76ca.png)

**Comment by sparc** [comment]
does not work for me

**Comment by Normalninja** [comment]
I have a separate additional issue wherin windows Search within the start menu is no longer functioning, makes it quite cumbersome to open programs I dont have pinned in the taskbar/startmenu has anyone else encountered this functionality failing?

**Comment by mikal-s** [comment]
> File explorer started crashing after new Windows update (KB5025239)

yes I agree this does seem to me to be when EP broke, was fine before this update and have looked on Microshits site for that update and, IT!!! does state that it BREAKS EP and other similar modification scripts/program

**Comment by sparc** [comment]
Not sure if it was the last windows update or the restart it did but now it works
