### ISSUE TITLE
Taskbar Empty after RDP connect/reconnect

### ISSUE THREAD

**Issue by tomhafner** [valinet/ExplorerPatcher#1312]
In the latest version, after RDP connect/reconnect the taskbar is empty. So i have to restart the File Explorer oder switch with Alt-Tap through all apps to view the apps in the taskbar.

**Comment by Amrsatrio** [comment]
I do not experience this issue when using the latest versions of EP on the latest versions of Windows 11 22H2. Closing this issue.
