### ISSUE TITLE
Crash when I hit "Windows Key"

### ISSUE THREAD

**Issue by danielhw2** [valinet/ExplorerPatcher#1313]
OS Name: Microsoft Windows 11 Pro
Version: 10.0.22621 Build 22621
Processor: AMD Ryzen 9 5900X
BaseBoard Product: TUF GAMING X570-PLUS_BR
ExplorerPatcher: 22621.1413.54.5

Every time when I hit the Left Windows Key, to open the "Start Menu", the Explorer crashes and reopens.

**Comment by Vipin2003** [comment]
just take backup of EP settings and reinstall with symbols download

**Comment by blueveno** [comment]
i have update latest ExplorerPatcher version  and got same this issue.

Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
Installed RAM	8.00 GB (7.84 GB usable)
Device ID	1FEA65F2-6249-4E81-8D7F-13B8E23693F3
Product ID	00327-35824-44218-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 2 touch points
Edition	Windows 11 Home Single Language
Version	22H2
Installed on	‎2/‎14/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

**Comment by Vipin2003** [comment]
just uninstall EP completely and restart. and then, reinstall the EP. Just press win key and crash the EP 3-4 times. A pop-up will appear. Just OK that. And restart the EP. It will download the Latest symbols and problem got fixed

**Comment by MrUrf** [comment]
> just uninstall EP completely and restart. and then, reinstall the EP. Just press win key and crash the EP 3-4 times. A pop-up will appear. Just OK that. And restart the EP. It will download the Latest symbols and problem got fixed

I have the same Issue, with the Addition, that I can't even Right-Click the Taskline. 

I did the process as you told  @Vipin2003, but I still have the Issue. 
Even Uninstalled twice and repeated the way you mentioned.

**Comment by Vipin2003** [comment]
Judt uninstall EP once again.

**Comment by Avnsx** [comment]
same issue here @valinet

**Comment by topia** [comment]
Uninstalling/reinstalling is not the right direction to fix the crashing problem. Instead, you just need to restart Explorer after downloading the correct symbol information.

1. First, we must stop the crashing loop; ExplorerPatcher is downloading the new symbol in the background, so keep Explorer running for enough time. There are many ways to do this, but I suggest removing old symbol information by running `reg delete HKCU\Software\ExplorerPatcher\twinui.pcshell /f` on the command prompt or PowerShell.
2. Explorer should stop crashing now, but some features are not working.
3. Open the ExplorerPatcher setting menu and ensure symbol downloading is enabled.
4. Wait a few minutes, and you should get a notification about the symbol download being done.
5. Click on `Restart file explorer` in ExplorerPatcher settings.


Please refrain from pinging the author. it's not a good option for the open-source author.

**Comment by Nitroito** [comment]
keeps crashing... i had to uninstall EP so i can use windows

**Comment by Faks** [comment]
tested topia fix with powershell it seems address the issue.
