### ISSUE TITLE
Weather widget issue

### ISSUE THREAD

**Issue by TotemicWeevil** [valinet/ExplorerPatcher#1318]
I can't say when this issue started but at the moment my weather widget is reporting that I have "No Internet Connection" despite the fact that I do.

I have followed the steps via RegEdit to add PeopleBand because my registry entries did not contain it and set it to zero.
I also enabled dev-mode on the weather widget.  However neither seems to have taken effect.
I have also tried resetting explorer back to its initial settings.
Apart from disabling the widget is there any way to fix this?

**Comment by jw-mn** [comment]
Got the same issue. Rolled back to 22621.1344.53.1. Uninstall and reinstall the older version.   This fixed it for me.

**Comment by kevinmon91** [comment]
Same issue here

**Comment by BigheadSMZ** [comment]
Yep. Weather no longer connects, says "No Internet access" when hovering the widget.

Bringing it up shows the following message:

Unable to load weather information

Make sure that the location you have entered is correct.
Verify that you are connected to the Internet.

Reload

**Comment by erhanertem** [comment]
Same here man. No internet access.. For a sec I can see its retrieving data then goes offline.

**Comment by rodrigoma-zz** [comment]
Same here using 22621.1413.54.5

**Comment by Caladian1** [comment]
Same here using 22621.1413.54.5

**Comment by silvia95guy** [comment]
Yeah, I have had this issue on and off for a few months, some updates have fixed it, but lately it has been broken more than it has worked. I'm hardwired in to a 1gig connection, with everything else working as normal. Sucks, as it is/was so much better than Windows' taskbar weather widget.

**Comment by mikal-s** [comment]
YES i have same issue on all my computers and laptops, started about a week ago for me...

**Comment by gaiking-uk** [comment]
Have the same issue too... for clarification, here is an example...
![EP Weather Widget Issue](https://user-images.githubusercontent.com/37931190/232600900-6ee9fabf-5f7d-4964-8b81-55428245b4c8.gif)

Error behaviour:
1. Weather widgets shows no internet available
2. Clicking reload brings up google for a second (and also what appears to be some kind of cookie acceptance popup)
3. After ~1 second or so the widgets *re-detects* that there is no internet available

(Will try rolling back as interim solution)

**Comment by SamBukka** [comment]
You can use 22621.1413.54.5 with the old "ep_weather_host.dll" from 22621.1344.53.1.

Just disable weather, replace the dll in "c:\Program Files\ExplorerPatcher\" and re-enable weather.

here is the dll: https://rg.to/file/d9ba10fc3f7640f1451ee5a1588204b7/ep_weather_host.dll.html

**Comment by mikal-s** [comment]
> You can use 22621.1413.54.5 with the old "ep_weather_host.dll" from 22621.1344.53.1.
> 
> Just disable weather, replace the dll in "c:\Program Files\ExplorerPatcher" and re-enable weather.
> 
> here is the dll: https://rg.to/file/d9ba10fc3f7640f1451ee5a1588204b7/ep_weather_host.dll.html

**Thank You @SamBukka, Now working correctly**

**Comment by TotemicWeevil** [comment]
Yay! Tis now working.. Thanks mate!!

**Comment by gaiking-uk** [comment]
Thanks @SamBukka, I am also pleased to report this works fine!

Also, and please don't take this the wrong way but as I ***really*** don't like downloading `.dlls` (especially from 3rd party sites), I think I've been watching too many hacking and ransomware videos on youtube or something 🙂 I was a bit dubious on this one, however for the benefit of any other readers, I can confirm that the file you provided is legit and has the same hashes as the one officially released! 👍🏼

```
File:   ep_weather_host.dll
MD5:    86340d54b042ee3130121ef7490928a0
SHA1:   96f9ad5e1e95fd8c9381509840015efb2cae96cf
SHA256: 48409a1699890dbcff309c331e4af1492e22228ef126800e624829668979bbc7
```

One last (albeit minor) thing -- The link didn't work for me initially and I had to remove the `.html` from the url and go to: https://rapidgator.net/file/d9ba10fc3f7640f1451ee5a1588204b7/ep_weather_host.dll -- just thought I'd share in case you wanted to edit the link your original comment.

**Comment by claudiutamas** [comment]
> Have the same issue too... for clarification, here is an example...
> 
> ![EP Weather Widget Issue](https://user-images.githubusercontent.com/37931190/232600900-6ee9fabf-5f7d-4964-8b81-55428245b4c8.gif)
> 
> Error behaviour:
> 
> 1. Weather widgets shows no internet available
> 2. Clicking reload brings up weather page for a split second
> 3. Is immediately covered by what appears to be some kind of cookie acceptance popup
> 4. A split-second later the widgets _re-detects_ that there is no internet available
> 
> (Will try rolling back as interim solution)

Same issue here
