### ISSUE TITLE
Explorer Switch error

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [valinet/ExplorerPatcher#1321]
Explorer /Switch or drive letter D:\ or E:\ in a shortcut results in Control Interface (Windows 10 Ribbon and Windows 7 Command Bar NOT being applied

Example 1:
open Explorer and click on the C: drive icon and right+click drag-and-drop it onto your desktop and select **Create Shortcut here** opening this explorer shortcut will produce the results from image 1 (the expected results) opening the Explorer shortcut from the start menu also results in the correct display.

Example 2:
Create a shortcut on the desktop with the target `%SystemRoot%\explorer.exe /e,C:` the uppercase C is the 'C' drive on your system you could also use an absolute path like `C:\Windows\explorer.exe C:\` both will result in image 2 (windows 11 native ribbon is still present)

1: Explorer without switch
![Explorer without switch](https://lookimg.com/images/2023/04/14/Qd7RuR.png)

2: Explorer with switch
![Explorer with switch](https://lookimg.com/images/2023/04/14/Qd7SDe.png)

Due to my use of other modifications to my installation of window 11 I ask a small favour of the community here to try to replicate my findings and post a reply to this thread. Thank you

**Comment by Jamesstevens-3rd** [comment]
just a follow up for this problem, after uninstalling open-shell and installing StartAllBack v 3.6.1 the problem disappeared.

**Comment by Amrsatrio** [comment]
This should have been fixed in the latest releases.
