### ISSUE TITLE
[Bug] Atfer installing ExplorerPatcher Windows Explorer is broken on Windows 11 build 22621.1555

### ISSUE THREAD

**Issue by Onmp314** [valinet/ExplorerPatcher#1322]
After installing ExplorerPatcher, the explorer.exe file stops working properly and launching applications is only possible through Task Manager.

Steps to reproduce:
1. Use Windows 11 with build tag 22621.1555
2. click ep_install.exe
3. explorer.exe will be broken and won't start

The only way to fix explorer.exe is to uninstall ExplorerPatcher or roll back to a previous version of Windows.

**Comment by Girofox** [comment]
I'm on Windows 11 Build 22621.1555 too and so far it works. Maybe it makes a difference if you update Windows first or Explorer Patcher, in my case I updated EP manually via settings some days ago before installing Build 22621.1555. Do you have another local user account where EP is not installed by chance?

**Comment by Onmp314** [comment]
the first thing I did was upgrade Windows and then installed ExplorerPatcher

**Comment by Onmp314** [comment]
Explorer.exe starts longer, but works.
