### ISSUE TITLE
[Bug] ExplorerPatcher does not work on Windows 11 ARM 22621.525 

### ISSUE THREAD

**Issue by Pixel556** [valinet/ExplorerPatcher#1323]
Whenever I try installing ExplorerPatcher on Windows 11 ARM 22621.525, it does install, but nothing gets changed. Trying to configure the settings also doesn't work, whether it requires Explorer to restart or not.

https://user-images.githubusercontent.com/95143545/232078938-cf0e0903-bbe3-4fcc-ac12-02282a4183c7.mov

**Comment by pyrates999** [comment]
I think it is x64 only.

**Comment by pyrates999** [comment]
Please close this as I don't think it can be implemented at this time.

**Comment by finnie2006** [comment]
> Please close this as I don't think it can be implemented at this time.

How do you know? did you try to compile it for arm?

**Comment by pyrates999** [comment]
You can try if you like.

**Comment by pyrates999** [comment]
You can make the effort by downloading the source code and figuring out how to compile and install it for arm.

**Comment by finnie2006** [comment]
I am not able to do that myself as i dont have the knowledge, the only thing that i am saying is how do you know it can`t be done, but i am ending this discussion
