### ISSUE TITLE
border around taskbar popup slider

### ISSUE THREAD

**Issue by hovedmannen** [valinet/ExplorerPatcher#1326]
Is it possible to remove the white border in attached image?

![image](https://user-images.githubusercontent.com/22261507/232090215-baf90db9-d37f-41fe-a62f-28785488b469.png)

**Comment by DubbyOW** [comment]
I agree that it's a bit annoying

**Comment by Amrsatrio** [comment]
This issue https://github.com/valinet/ExplorerPatcher/issues/1448 should be a duplicate of this, but because it explained more, I wil be closing this instead.
