### ISSUE TITLE
Explorer doesn't work after KB5025298 Win Insider update

### ISSUE THREAD

**Issue by Moonclair** [valinet/ExplorerPatcher#1327]
Already uninstalled-installed.

https://blogs.windows.com/windows-insider/2023/04/13/releasing-windows-11-build-22000-1879-to-the-release-preview-channel/
I'm in insider program
Win 11 Pro 21H1 - KB5025298

**Comment by jastranlove2020** [comment]
I am sure to confirm that The explorer patcher is crashing on the Windows 11 ( not yet install 22H2 ), just update 

![image](https://user-images.githubusercontent.com/76111758/232210213-28aec2e8-c932-472d-920b-5b1ee6532bd7.png)


![image](https://user-images.githubusercontent.com/76111758/232210174-14be1f07-16f1-4325-9865-2d05c0c9a245.png)

I have uninstall / reinstall many times carefully restart process explorer but it is always making crashing

Please check further to the issue for the case above

Thank you

Sang N
Senior engineer

**Comment by topia** [comment]
Supporting builds for insider preview / update preview is out of the scope of this software. because Microsoft doesn't release symbols for these builds.

**Comment by Moonclair** [comment]
oh! thank you for your reply!
