### ISSUE TITLE
Cumulative Update KB5025239 causes crashing

### ISSUE THREAD

**Issue by nicholaszuccarelli** [valinet/ExplorerPatcher#1328]
Installed the latest Win11 22H2 Cumulative Update KB5025239

EP will continually crash when using the Windows 11 taskbar
EP will crash when opening the Windows 11 start menu when using the Windows 10 taskbar

**Comment by khang06** [comment]
Seems to work after it downloads symbols

**Comment by jastranlove2020** [comment]
today, i got black screen after new update 2023-04 patch.

i have fixed by uninstall ep_setup and reboot, then windows is back.

Use Ctrl + Alt + Del to Task manager -> new Task, type cmd with Admin option selected then use "cd 'c:\program files\explorerpatcher", then type "ep_setup /uninstall" by the guide.

The Explorer Patcher is out of date, it is not working now, hope, the author will have new update ASAP for community

Sharing with someone about current solution to go back windows

**Comment by nicholaszuccarelli** [comment]
Not working. Usually it downloads symbols for me straight away. Attempted uninstall and reinstall, but no new symbols have been found.

**Comment by khang06** [comment]
Try extracting this to %appdata%/ExplorerPatcher [ExplorerPatcher.zip](https://github.com/valinet/ExplorerPatcher/files/11238061/ExplorerPatcher.zip)

**Comment by jastranlove2020** [comment]
Windows 11, not 22H2, 2023-04 update package not working with symbol mentioned in the thread.

**Comment by 2001db8** [comment]
> today, i got black screen after new update 2023-04 patch.
> 
> i have fixed by uninstall ep_setup and reboot, then windows is back.
> 
> Use Ctrl + Alt + Del to Task manager -> new Task, type cmd with Admin option selected then use "cd 'c:\program files\explorerpatcher", then type "ep_setup /uninstall" by the guide.
> 
> The Explorer Patcher is out of date, it is not working now, hope, the author will have new update ASAP for community
> 
> Sharing with someone about current solution to go back windows

No need to uninstall, just instead of starting "cmd" start your browser, download latest release from https://github.com/valinet/ExplorerPatcher/releases and install.

**Comment by nicholaszuccarelli** [comment]
Just got an update for the latest symbols. Issue is resolved.

**Comment by Faks** [comment]
Nope, still dead.

**Comment by m-brooks** [comment]
@nicholaszuccarelli , how did you get that update? My machine is crashing Explorer so frequently (faster than once per second) that it has no chance to download any symbols. I have had to uninstall EP from two PCs now.

**Comment by topia** [comment]
I wrote this: https://github.com/valinet/ExplorerPatcher/issues/1313#issuecomment-1508994935
