### ISSUE TITLE
Context Menu causing crashes

### ISSUE THREAD

**Issue by TriggeredTrigz** [valinet/ExplorerPatcher#1333]
I disabled the Win11 context menu to get the Win10 version, but the moment i did that, whenever I used the context menu, FileExplorer would freeze for a second, then crash and restart.

**Comment by shockelite** [comment]
I would recommend Run: `rundll32 C:\Windows\dxgi.dll,ZZGUI` to open the properties window. This should bypass the context menu crash.

**Comment by TriggeredTrigz** [comment]
> I would recommend Run: `rundll32 C:\Windows\dxgi.dll,ZZGUI` to open the properties window. This should bypass the context menu crash.

it says that the module "C:\Windows\dxgi.dll" could not be found

**Comment by TriggeredTrigz** [comment]
I have found an issue with windows, even after i uninstalled ExplorerPatch

My file explorer keeps freezing and crashing every time i open more options or select a zip file. When i checked Event Viewer, it said that the module causing the crashes was a "shcore.dll"

**Comment by felix-redlich** [comment]
I think I have the same problem described in #1368

**Comment by felix-redlich** [comment]
For me, it seems like PDF24 was the actual cause. After finding this thread [https://www.reddit.com/r/WindowsHelp/comments/122xuu3/explorer_crash_when_i_select_zip_file/](url) I uninstalled PDF24 and that seems to have solved my problem so far.
