### ISSUE TITLE
Windows 11 taskbar style cut the clock on the corner

### ISSUE THREAD

**Issue by Ayting69** [valinet/ExplorerPatcher#1338]
Hello.

https://i.imgur.com/HNwdJm5.png

And on WIndows 10 style it's shown normally : 

https://i.imgur.com/KYgbNb3.png

I prefer the Windows 11 taskbar style so i'm wondering how to fix that ? 
 

My resolution is 2560*1440.

**Comment by Amrsatrio** [comment]
You are using something that reduces the Win11 taskbar height, which EP does not do. Try to revert the trick that is explained in here: https://pureinfotech.com/change-taskbar-size-windows-11/
