### ISSUE TITLE
Does 22621.1413.54.5 support 22H2 22624.1610?

### ISSUE THREAD

**Issue by kingmustard** [valinet/ExplorerPatcher#1341]
I woke this morning and Explorer Patcher will not run, so I've lost my Start menu, taskbar shortcuts etc.

There appears to be nothing mentioned in Issues nor Discussions, so I thought I'd check.

Do we know if an update is in the works?

I also posted here: https://www.elevenforum.com/t/new-version-of-explorerpatcher.1991/post-287499, I hope that's ok.

**Comment by topia** [comment]
Supporting builds for insider preview / update preview is out of the scope of this software. The dev repeatedly said that.

**Comment by kingmustard** [comment]
> Supporting builds for insider preview / update preview is out of the scope of this software. The dev repeatedly said that.

Thank you 😊

**Comment by Vipin2003** [comment]
Please close the issue if resolved.
