### ISSUE TITLE
Start menu not popup in Windows 11 25336

### ISSUE THREAD

**Issue by 318cyz** [valinet/ExplorerPatcher#1342]
When you press Windows icon or key, Start menu will not popup in Windows 11, version 25336 if you choice Windows 10 Taskbar style.
Windows 10 style Alt+Tab also not work.

Plz fix it
Thank you,

**Comment by topia** [comment]
I don't know which channel has Windows 11 25536 ([maybe 25336?](https://learn.microsoft.com/en-us/windows-insider/flight-hub/)), but if it's an insider, this software doesn't support that channel.

**Comment by 318cyz** [comment]
Thank you.

**Comment by 318cyz** [comment]
> I don't know which channel has Windows 11 25536 ([maybe 25336?](https://learn.microsoft.com/en-us/windows-insider/flight-hub/)), but if it's an insider, this software doesn't support that channel.

Oh yes, it's a Canary Bulid.
(I'm now regret to install it haha)

**Comment by Robert-Ernst** [comment]
I have windows build 22000.1817 and this issue since around 1-2 weeks.
My Windows Menu doesn't open. Neither on click nor on pressing the windows button.
Although my ALT+Tab works.

**Comment by 318cyz** [comment]
I check the log, it says
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for unknown OS version 10.0.25336.1010.

and

[Symbols] Windows 10 window switcher style is not available in this build.

**Comment by topia** [comment]
> I have windows build 22000.1817 and this issue since around 1-2 weeks.

Please consider creating another issue or discussion for another problem.
BTW I suspect that you turned off the symbol downloading or something is blocking your symbol download because that build is an official security release.
Could you confirm the symbol download is enabled in the advanced setting and check the log by turning on "Enable Console" and restarting the File Explorer?

**Comment by Robert-Ernst** [comment]
```
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.1413.54.5.38505974ea340d7f"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Unable to check for updates because the remote server is unavailable.
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for unknown OS version 10.0.22000.1817.
[Symbols] Downloading to "C:\Users\User\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\Windows\system32\twinui.pcshell.dll" ("efbeadf6af6cdef992d0c4885288b4a0")...
[Symbols] Symbols for "C:\Windows\system32\twinui.pcshell.dll" are not available - unable to download.
[Symbols] Please refer to "https://github.com/valinet/ExplorerPatcher/wiki/Symbols" for more information.
```

**Comment by topia** [comment]
It's a surprising result, but it's understandable if it can't download. And unfortunately, it's an issue on the Microsoft symbol server (or rarely a connectivity issue), so the dev can't work on it.

**Comment by 318cyz** [comment]
> It's a surprising result, but it's understandable if it can't download. And unfortunately, it's an issue on the Microsoft symbol server (or rarely a connectivity issue), so the dev can't work on it.

I got this issue too.
The new release fix a lot of features, but Windows 10 style Start Menu still not works.

[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.1555.55.1.5758b678431cded2"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for unknown OS version 10.0.25346.1001.
[Symbols] Downloading to "C:\Users\31971\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\WINDOWS\system32\twinui.pcshell.dll" ("e65ac20a97ea016a49b731ea68c03c1c")...
[Updates] Hash of remote file is "22622.1555.55.1.5758b678431cded2" (valid).
[Updates] Local version obtained from hash is 22622.1555.55.1.
[Updates] No updates are available.
0 0
[Symbols] Reading symbols...
[Symbols] Downloading symbols for "C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartDocked.dll" ("91b662463d84ab2b640d283d3f1283ad")...
[Symbols] Reading symbols...
[Symbols] Downloading symbols for "C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartUI.dll" ("")...
[Symbols] Symbols for "C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartUI.dll" are not available - unable to download.
[Symbols] Please refer to "https://github.com/valinet/ExplorerPatcher/wiki/Symbols" for more information.

**Comment by homoioi** [comment]
Similar issue
[Symbols] Attempting to download symbols for unknown OS version 10.0.22000.2057.
[Symbols] Symbols for "C:\Windows\system32\twinui.pcshell.dll" are not available - unable to download.

**Comment by pyrates999** [comment]
> Similar issue [Symbols] Attempting to download symbols for unknown OS version 10.0.22000.2057. [Symbols] Symbols for "C:\Windows\system32\twinui.pcshell.dll" are not available - unable to download.

You've got windows 11 21h2 installed.  Update to windows 11 22h2.

https://en.wikipedia.org/wiki/Windows_11_version_history
