### ISSUE TITLE
how to uninstall this?

### ISSUE THREAD

**Issue by filip2cz** [valinet/ExplorerPatcher#1343]
Hello,
I want to uninstall this program, but I don't know how. When I try to do it through the control panels, it just offers me to delete the shortcut in those panels, but it doesn't uninstall. There is no uninstaller in the program files.
How can I uninstall this program?

**Comment by KiroTheFoxo** [comment]
Rename the install file to ep_uninstall

**Comment by filip2cz** [comment]
thanks

**Comment by filip2cz** [comment]
I tried this, but it didn't anything.

**Comment by KiroTheFoxo** [comment]
There's a guide in one of the documents that says how, sorry

**Comment by filip2cz** [comment]
Yes, sorry, I missed it.
Here it is for anyone who happens to be looking for it: https://github.com/valinet/ExplorerPatcher/wiki#uninstalling
