### ISSUE TITLE
Apps can only pin to Win10 Start Menu from the Start Menu

### ISSUE THREAD

**Issue by faielgila** [valinet/ExplorerPatcher#1346]
Some apps (such as Samsung Notes) don't show up in the "all apps" list on the Start menu, where pinning apps to the Start menu does work. However, when using Search to select "Pin to Start", the app does not get pinned.
The same issue applies to locally-developed UWP apps, and probably other programs that -- since their disappearance from the Start menu -- I don't remember any other specific examples.
Since the executables for installed apps like Samsung Notes are not easily available, adding them using the "Pin tiles to Windows 10 Start menu from File Explorer" feature doesn't seem feasible, but maybe there's a workaround.

Windows ver: _Win11 OS Build 10.0.22621.1555_
ExplorerPatcher ver: _22621.1413.54.5_

**Comment by topia** [comment]
Seems to be duplicate of #1108

**Comment by Vipin2003** [comment]
Close the issue if it is resolved.

**Comment by faielgila** [comment]
My apologies, closing as duplicate.
