### ISSUE TITLE
ExplorerPatcher Weather glitching out

### ISSUE THREAD

**Issue by Niblocono** [valinet/ExplorerPatcher#1353]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1352

<div type='discussions-op-text'>

<sup>Originally posted by **Niblocono** April 20, 2023</sup>
Is anyone else having the problem where the weather on the taskbar doesn't work right? For me, it shows the weather then says, 'you're not connected'. @valinet help!
I will upload a video file here:

https://user-images.githubusercontent.com/125621033/233514805-7aaea2c1-bb6e-4a1e-a964-6ab047fb0c40.mp4

</div>

**Comment by gui-nvieira** [comment]
Yeah, I have a problem like that in the same functionality. The widget can reload, but in 1~2sec breaks again.

**Comment by topia** [comment]
Please refrain from opening new issues on the same problem.
You should get this information if you search: https://github.com/valinet/ExplorerPatcher/issues/1324#issuecomment-1514347774

**Comment by jw-mn** [comment]
Fixed in https://github.com/valinet/ExplorerPatcher/issues/1310

**Comment by Fredrik-69** [comment]
> Please refrain from opening new issues on the same problem. You should get this information if you search: [#1324 (comment)](https://github.com/valinet/ExplorerPatcher/issues/1324#issuecomment-1514347774)

People don't read anything - haven't you learned? ;-) 

![image](https://user-images.githubusercontent.com/68969282/233704610-223bd224-7a7d-4def-af34-a9018e79349c.png)

**Comment by Niblocono** [comment]
Oops lol

**Comment by valinet** [comment]
Should be fixed in 22621.1555.55.1.

**Comment by Niblocono** [comment]
Ok yep its fixed now thx
