### ISSUE TITLE
problam safely remove the USB device

### ISSUE THREAD

**Issue by Diego02upa** [valinet/ExplorerPatcher#1355]
Hi, I just installed the latest version of explorer patcher; the weather works but again there is another problem about safely removing a USB device;

in practice, when you try to safely remove the USB device by pressing the icon, the taskbar crashes and restarts and you can't remove it safely.
I tried uninstalling explorer patcher and with the icon in the Windows 11 taskbar it works.
Could you please check? Thank you.

**Comment by pyrates999** [comment]
Please check for a notification of symbols being downloaded.  Then open up task manager and look for windows explorer under the processes tab.  Select it and look for the button restart in the bottom right corner.  Click on it to restart windows explorer.

**Comment by Diego02upa** [comment]
Yes, the symbols are installed and are used correctly in the weather screen but the problem to safely remove the USB device remains.
Thank you

**Comment by valinet** [comment]
Testing in a clean VM, I cannot reproduce the issue on my end. I use Windows 10 taskbar, click the "Safely Remove Hardware and Eject Media" icon in the taskbar. The pop-up menu shows, allowing me to eject devices. I advise narrowing down a way to reproduce the issue in a clean environment, or alternatively debug the application on your end (you can use the Visual Studio debugger, or WinDbg, to attach to `explorer.exe` and debug it on your machine).

OS build: 10.0.22621.1555
EP build: 22621.1555.55.1
![image](https://user-images.githubusercontent.com/6503598/233817897-6e18fada-fd91-4c03-9f6d-8b932ddc4f41.png)

**Comment by Diego02upa** [comment]
I fixed it by reinstalling Windows.

Now everything is fine and fully functional.

Thank you
