### ISSUE TITLE
Windows arm64

### ISSUE THREAD

**Issue by pb5050** [valinet/ExplorerPatcher#136]
anyway you can do that? release it for arm64 anbd if anything i can do let me know

**Comment by valinet** [comment]
Moved to discussions as it is not an issue.

I have been asked previously, I do not own an arm64 machine, so I cannot test it. Some stuff has to be coded specIfically for that architecture. Furthermore, I also do not have too much time free time. Considering all of the above, the chances of me picking this up are slim.


Anyway, if you want to take a chance and attempt a port, I can help you with any questions regarding the code. Good luck!
