### ISSUE TITLE
Taskbar Relaunching indefinitely [FIXED]

### ISSUE THREAD

**Issue by 76Nomad** [valinet/ExplorerPatcher#1361]
I need some urgent help with that, as I download the build and started it, my taskbar has been flickering as it seem to be trying to restart the windows 10 again and again, making it impossible to open anything else except the taskbar and stuff from starting a new task.

I've downloaded it from there (I know rookie mistake) and I'm desesperatly looking for a solution as I would like not to have to factory reset my stuff, please help :(

**Comment by ramsedie** [comment]
I have the same problem with Windows 11.

**Comment by 76Nomad** [comment]
UPDATE : I've actually manage to fix the issue ! I restarted the computer to have access to the troubleshooting section (wehnever you are about to log in, juste press de restart button while keeping SHIFT pushed down)

And uninstall the last Quality Update as it will install again, as I did that, the plugin didn't seem to start and I could download a version which was not the last one !
