### ISSUE TITLE
THIS APP DOESN'T WORK and MY TASK BAR WAS CRUSHED

### ISSUE THREAD

**Issue by ogaaaan** [valinet/ExplorerPatcher#1362]
this app broke my desktop.
i don't want to use this app never.
Why don't exists repair functino?

**Comment by pyrates999** [comment]
Please include the version of windows that you are running and a screen shot of what you mean by "your task bar was crushed"?

To uninstall, go here: https://github.com/valinet/ExplorerPatcher/wiki#uninstalling

**Comment by ogaaaan** [comment]
I found this settings below.

- `Combine taskbar icons on primary taskbar`
- `Combine taskbar icons on secondary  taskbar(ss)`

finaly i changed those settings to "Always combine".
therefore my taskbar icons to be corrected i thought.

I used Windows 10 and 11 longtime. i completely forget those settings.

anyway, this app is good. thanks!!
