### ISSUE TITLE
DO NOT INSTALL windows11 4/24 safety update KB5025239 !!!!  It almost KILLS MY COMPUTER!!!!

### ISSUE THREAD

**Issue by Alethiea-Cheng** [valinet/ExplorerPatcher#1365]
My computer is close to dead. 
very very close I am still fritened 
even if I harshly tried to open task manager、tried to resisting the explorer's crash which kept interrupting my typing and ran `ep_setup.exe /uninstall`, THE UNINSTALLATION FAILED ALONG WITH EP_SETUP.EXE FILE DISAPEARING!!! NO PROGRAM CAN FIX ITSELF ANYMORE
Fortunately an only one recovery node being built just an hour ago before I did windows update.
Thank you windows. Fuxk you windows. Thank you EP. Fuxk you EP.

**Comment by Alethiea-Cheng** [comment]
From now on, before I turn off my computer and allow it to do windows update, I am sure to check this page.

**Comment by pyrates999** [comment]
you got the command wrong.  It is:
`ep_setup.exe /uninstall`

**Comment by Alethiea-Cheng** [comment]
> you got the command wrong. It is: `ep_setup.exe /uninstall`

Fine. Just a typo on github.

**Comment by hauserkristof** [comment]
> > you got the command wrong. It is: `ep_setup.exe /uninstall`
> 
> Fine. Just a typo on github.

Me too. For sure.
I rarely use my windows machine, but I need it quick, I've completely forgot about this is installed, so I had restored windows completely... Kind of akward.

Anyway I love this software, so I have to pay more attention next time.

**Comment by lostmsu** [comment]
Perhaps ExplorerPatcher should check if explorer does not crash too often and disable itself.

**Comment by pyrates999** [comment]
Latest release does that already.
