### ISSUE TITLE
Releases 22621.1555.55.1_a95a688 smartscreen warning

### ISSUE THREAD

**Issue by skadefrony** [valinet/ExplorerPatcher#1367]
I can't install the latest due smartscreen error

**Comment by diogocatossi** [comment]
It would be great if ExplorerPatcher could get digitally signed so that Windows could trust it.

**Comment by Poopooracoocoo** [comment]
> It would be great if ExplorerPatcher could get digitally signed so that Windows could trust it.

would be nice if microsoft didn't require that people pay hundreds of dollars for signing to get rid of a scary warning.
