### ISSUE TITLE
Start Menu doesnt work

### ISSUE THREAD

**Issue by asifashraf80** [valinet/ExplorerPatcher#1369]
When I install explorer patcher it works but the start menu wont work only the search bar works pls fix!!!!

**Comment by TobiasAC** [comment]
Same here!

**Comment by ch4d1** [comment]
Did you use the Windows 11 Start Menu or Windows 10? Because Windows 10 is working on my side, Windows 11 is not.

**Comment by TobiasAC** [comment]
Neither Start menu is working for me (Win 10/11 mode). Tried to redownload symbols, restart EP etc. Using Windows 11 Enterprise 21H2

**Comment by i004909** [comment]
Same issue for me - clicking Start button seems to cause Explorer to restart

**Comment by mokiii** [comment]
Same problem，Windows 11 Pro for Workstations 22H2

**Comment by yymyyy** [comment]
Same problem. It used to work fine, but at some point it stopped working. Not sure if it's because Windows updated or if ExplorerPatcher itself updated.

**Comment by GronbergInfo** [comment]
I just updated to Pre-release and it fixed this for me.

**Comment by TobiasAC** [comment]
Not fixing it for me. Start menu and Win-key does not work with relesese or pre-relesese

**Comment by zss823158062** [comment]
Same problem，problems come and go

**Comment by pyrates999** [comment]
Can you explain how the start menu isn't working?

Try the following:

1. uninstall explorer patcher
2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher

**Comment by DJBainbridge** [comment]
I had an issue where Explorer was not working correctly after Windows update. 
Tell tell sign was the start menu search was not working. 

I uninstalled and deleted the Reg key as to the instruction above.
Reinstalled, and all is working again :)

**Comment by Uraharadono** [comment]
For those who are still struggling here is the thing that happened to me. Got the startup button not working and I jumped to start looking for solutions. Thing is that this program has no GUI so you don't see that it is doing work in background. 

Wait for 5-10 minutes until it downloads the binaries for your release of Win11 and you should be good to go. Don't panic as I did.

**Comment by lolmaus** [comment]
> Wait for 5-10 minutes until it downloads the binaries for your release of Win11 and you should be good to go. Don't panic as I did.

I had to reboot after that for the start menu to appear. Used `shutdown -r` from Task Manager (Ctrl+Shift+Esc).

**Comment by Administartor568** [comment]
ill never use ep agian its so suck and my windows start isnt working pls choose another software
