### ISSUE TITLE
"Open Start in All apps by default" broken among a few stuff

### ISSUE THREAD

**Issue by seventhstorm** [valinet/ExplorerPatcher#137]
After the update, the open start in aöö apps by default is broken. Also, after a some minutes, default start menu tends to break.
Otherwise, it´s a great tweak.

**Comment by valinet** [comment]
What Windows build?

**Comment by seventhstorm** [comment]
22000.258

**Comment by seventhstorm** [comment]
> What Windows build?

22000.258

**Comment by valinet** [comment]
Yeah, idk, for me it works, I am on the same build, and use that setting as well and it works. I haven't touched that code area in a while, definitely not by any recent update. What EP version? Maybe try with the latest...?

**Comment by frankbons** [comment]
Classic taskbar is not working anymore in build 22000.282.

**Comment by valinet** [comment]
let's continue the talk here: https://github.com/valinet/ExplorerPatcher/issues/129 then, it is the same issue basically.
