### ISSUE TITLE
Windows Start Menu moves when searching

### ISSUE THREAD

**Issue by Cookie4Free** [valinet/ExplorerPatcher#1378]
I have my Taskbar on the right side and when pressing the Windows Button the menu opens as usually on the top right corner. But when I start typing anything to search something the menu moves to the bottem left corner.
This happened few days ago and I guess a recent Windows Update causes this issue. Any way to fix this?

**Comment by ThePhxRises** [comment]
This is also happening to me with my taskbar at top. While I would like to see this issue fixed, the ability to override the default start menu search-on-type behavior to be handled by another application would be ideal, for example PowerToys Run.

**Comment by tivengodentro** [comment]
same

**Comment by pavelhegr** [comment]
Same for me. Taskbar on the right side, search window in the bottom left.
