### ISSUE TITLE
ALT+TAB results in flickering and refill of taskbar

### ISSUE THREAD

**Issue by Alexibad** [valinet/ExplorerPatcher#1379]
After upgrade to Version: 22621.1555.55.1 I experience issues when hitting ALT+TAB 
The machine becomes non-responsive for a few seconds. During this time the taskbar flickers, get black (empty) and fills again. Then I can continue to work normally.
On windows 11 - Microsoft Windows [Version 10.0.22621.1555]  
Using windows 10 taskbar settings with ExplorerPatcher

**Comment by Alexibad** [comment]
This only happens with properties "Window switcher"  value  “Windows 10”. With the default value "Windows 11" the error does not occur.

**Comment by Sharkum** [comment]
Yep, facing the same issue with my laptop

**Comment by pyrates999** [comment]
You're on the April update.  Perhaps you should try updating to the July update: https://support.microsoft.com/en-au/topic/july-11-2023-kb5028185-os-build-22621-1992-605fa18f-bd49-41d8-80b1-245080e26c3d
