### ISSUE TITLE
Request a new function on the system tray.

### ISSUE THREAD

**Issue by HyGuGunG** [valinet/ExplorerPatcher#1385]
Among other system tray icons, you need a function to turn off or turn on the hidden icon menu.
Currently, it seems to be possible only when the hidden icon menu is turned off.
If you already have this feature and I can't find it, please let me know.

**Comment by Vipin2003** [comment]
Put this in Discussions and Close the issue here.

**Comment by HyGuGunG** [comment]
OK!
Thanks!

**Comment by HyGuGunG** [comment]
Move Discussions!
