### ISSUE TITLE
Windows 10 Network Flyout Text cut off

### ISSUE THREAD

**Issue by evanunzicker** [valinet/ExplorerPatcher#1391]
I just recently discovered this issue, its more of a pet peeve, but under the network and internet, where it says WiFi, airplane mode and mobile hotspot, the text gets cut off so it instead of saying mobile hotspot at the end, it says mobile hotspo... here`s an image:
![image](https://user-images.githubusercontent.com/79116708/234887558-3e221bac-78f7-4608-ac0d-9c2454c08f6b.png)
could also be a feature update to remove the items below "Network and Internet Settings" 🤷‍♂️

**Comment by Faulty-Windows** [comment]
Same, for whatever reason, on another account, it was all working fine, no cut off text.

**Comment by ARestrepo228** [comment]
Go To C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy and rename dxgi.dll and the issue will be fixed

**Comment by Vipin2003** [comment]
Close issue if resolved.
