### ISSUE TITLE
File Explorer impacts

### ISSUE THREAD

**Issue by slcpunk** [valinet/ExplorerPatcher#1393]
I love this program - it works so well.  Unfortunately, it seems to really impact my File Explorer ( Explorer.exe ) windows.  Whether I'm looking at a local folder ( Downloads ) or One Drive or a remote file share, I get random slowdowns where the cursor spins and Explorer just "thinks".  I didn't even realize it was ExplorerPatcher until I uninstalled it and all my File Explorer windows started acting normally again.  Re-installed and the slowdowns/hangs started again.  Curious if there is a setting ( I tried resetting to "default", same issue ) that I might have missed?  I do have mapped drives, One Drive, Google Drive etc.

thanks in advance.

**Comment by Amrsatrio** [comment]
Which command bar are you using? Does this issue still persist on the latest Windows and EP?

**Comment by slcpunk** [comment]
I feel like it has been better recently.  ( always on latest both Windows and EP ).  I'll close this, sorry to trouble you.  If I have similar problems again, I'll re-open it.
