### ISSUE TITLE
Search totally unresponsive

### ISSUE THREAD

**Issue by nicemoreoften** [valinet/ExplorerPatcher#1395]
After new Windows 11 update, search bar has been totally unresponsive with ExplorerPatcher. Did a few things like restarting search process and such, restarting comp, but no luck.

**Comment by andrewteg** [comment]
This is happening for me where I hit search and cannot search for a program.  Is it staying this way?

**Comment by Lumince** [comment]
Were you able to fix this issue? I now have this issue after the latest update...

**Comment by andrewteg** [comment]
I had the issue myself but it resolved itself Friday. I had backed up and installed and the issue was with windows 11 as it happened on stock start menu as well.
