### ISSUE TITLE
ExplorerPatcher won't work on OS build 22621.1635

### ISSUE THREAD

**Issue by luisl173** [valinet/ExplorerPatcher#1399]
Hey, so after Windows updated itself explorer started to repeatdly crash, after thet i got a message that ExplorerPatcher was disabled due to this, so i had to uninstall it.
![image](https://user-images.githubusercontent.com/108156867/235331378-2a99f159-c076-4254-ae74-b12176642fc5.png)
Windows 11 version: 10.0.22621.1635
ExplorerPatcher version: 22621.1555.55.2
![image](https://user-images.githubusercontent.com/108156867/235331288-a471b35d-3c2a-4f30-b3ca-12f1397e3287.png)
Is there any way to fix this or we'll have to wait for a new release?

**Comment by luisl173** [comment]
Weird update: Even if it crashes it still works... kind of.
![image](https://user-images.githubusercontent.com/108156867/235331431-cdac5e72-e4f9-45c9-b82f-c76dbee2ead7.png)

**Comment by pyrates999** [comment]
If you see that message, it means explorer patcher is not loaded.  That's why everything is working for you at that point.

**Comment by morphias2004** [comment]
Same issue.

Things 'sort' of work, but the Start menu is messed up, etc.

**Comment by Willgefortz** [comment]
Same here. Windows 11 22621.1702
It started after Windows update KB5026372.
Reset to defaults and reinstall won't help.

**Comment by pyrates999** [comment]
The reporter installed a preview update.  Those are not supported as Microsoft doesn't include symbols to download for those and insider builds.  Uninstall any preview updates, then uninstall explorer patcher, reboot, and install the release of explorer patcher.  Then restart windows explorer once you get the notification that symbols have been downloaded.
