### ISSUE TITLE
Ask here any question about functionality of the app

### ISSUE THREAD

**Issue by valinet** [valinet/ExplorerPatcher#14]
Please do not file new issues where you ask about application features, how to configure the app and so on. Instead, post it here and we will help you out by the minute.

Thank you.

**Comment by KedarWolf** [comment]
I copied the .dll to the three folders using 22000.176.

I restarted explorer, signed out, back on. Still have the wrong right-click menus in explorer.

I'm not sure what I'm doing wrong.

**Comment by valinet** [comment]
Does anything else work? Win+X for example.

**Comment by KedarWolf** [comment]
I can't test that, I keep my Windows key disabled because it interferes with a game I play and is a hassle enabling it, I need to download, install a program and write to my keyboard memory.

**Comment by KedarWolf** [comment]
Start menu is left aligned though. But I did that with Start11.

**Comment by valinet** [comment]
Please take the time and read the README and do the stuff mentioned there and try to gather some information. Run with `AllocConsole=1` and wait for it to finish before logging off. Of course it does not work if you restart it without it doing the initial prep work, it has to download some stuff initially. If you have toast notifications off, run with `AllocConsole=1` so yo use what it is doing. Start menu when I ask I don't mean Start11, I mean if it is left aligned using this app, of course. Please, take the time and read the README file.

**Comment by KedarWolf** [comment]
I enabled the Win key. Win X not working.

Sorry, I'm not sure what you mean by run with AllocConsole=1

I followed the instructions in the ReadMe.

It might be I'm using a custom Windows 11 ISO modded with Optimize Offline.

**Comment by valinet** [comment]
No, it is not that (Optimize Offline). If you read the ENTIRE README, you find mentions above `AllocConsole=1`. You set that in `settings.ini` file and the app will show a console at startup where debug info is printed. Again, as I said, read the ENTIRE README, up until the section called "License". And read it thoughtfully. Thank you.

**Comment by KedarWolf** [comment]
Never mind, logging out and back in wasn't enough. I had to reboot. Thank you. :)

**Comment by valinet** [comment]
You had to let it download the symbols. It is not a matter of reboot/sign out/whatever. Until we chated here, it probably downloaded and then no matter what you do, restart Explorer/reboot/sign out, it works. I am glad it did. Please read the README information thoughtfully, for each project that you use, it clearly states there what to expect. Good luck!

**Comment by TheForgottenKing** [comment]
I'm looking to just use this to force the start menu to skip to All Apps, but I'd like to avoid the issues with the wifi and battery icon. Is it possible to only install it to the start menu folder to leave the rest alone?

**Comment by TheForgottenKing** [comment]
I'd like to only enable the option to have the Start Menu open to All Apps, but I'd like to keep the Windows 11 taskbar and everything else the same. Is this possible? I can't find a way to leave the Windows 11 taskbar enabled.

**Comment by BraINstinct0** [comment]
Would it be possible to use the win 10 start menu?
I really miss my well-organized live tiles.

**Comment by valinet** [comment]
> I'd like to only enable the option to have the Start Menu open to All Apps, but I'd like to keep the Windows 11 taskbar and everything else the same. Is this possible? I can't find a way to leave the Windows 11 taskbar enabled.
> 
> Edit: Actually it seems to work perfectly by simply installing just to the Start Menu folders. I removed it from %windir% and now it's working perfectly. The only issue is that spam-opening the start menu causes it to go back to the default menu, but that's pretty minor. Thanks a ton.

Spamming it probably cancels the command to animate go to All 

> Would it be possible to use the win 10 start menu?
> I really miss my well-organized live tiles.

I will investigate that when I’ll have some time.

**Comment by cleanremote** [comment]
Does this DLL bring back the old search box in File Explorer on Windows 10?

**Comment by valinet** [comment]
> 
> 
> Does this DLL bring back the old search box in File Explorer on Windows 10?

Yes.

**Comment by IsraelNS902** [comment]
@valinet 

I just wanted to take a moment to thank you for sharing your project with us! Your talents are being put to good use every single day on my system, a true legend in my books. 🙏🙏

Screenshot: https://i.imgur.com/lselpXw.png

**Comment by valinet** [comment]
Thank you very much, I am glad that it serves you well.

**Comment by IlllIIIIlIIllIl** [comment]
Hi @valinet - not working for me.

bAllocConsole = 1 but no console appears
Killing and re-running explorer.exe provides the "Unable to find symbols for OS version 10.0.22000.194" notification but this sits there indefinitely, and over the past few hours my windows.ui.xaml.pdb keeps updating the date modified and increasing in size

**Comment by IlllIIIIlIIllIl** [comment]
Also when trying to run `rundll32.exe C:\Windows\dxgi.dll,ZZGUI` I get the following

![image](https://user-images.githubusercontent.com/56378783/136175562-dece673d-94c4-4829-97b7-77333606307a.png)

**Comment by valinet** [comment]
Please, if it wasn’t obvious already (nothing is, apparently), please run the **latest** version of the DLL, available in the releases section. Thanks.

**Comment by Spaeck** [comment]
Hi @valinet 

Thanks for sharing your Project, it just made my transition to Win11 "acceptable". I do still have kind of an issue and i am not sure, if this is a bug or just misconfiguration.

I have 3 monitors, where the center one is configured as Primary. This is where my main taskbar appears on. I can untick the "lock all taskbars" and move the main taskbar to the left monitor and relock the bars. So far everything works find. When i restart the Computer (or restart explorer.exe) the main Taskbar is reset to the main desktop. Hope you can help. 

Cheers.

**Comment by BraINstinct0** [comment]
> Hi @valinet - not working for me.
> 
> bAllocConsole = 1 but no console appears Killing and re-running explorer.exe provides the "Unable to find symbols for OS version 10.0.22000.194" notification but this sits there indefinitely, and over the past few hours my windows.ui.xaml.pdb keeps updating the date modified and increasing in size

This is not a feature discussion, so open it as a separate issue. Besides, windows version/EPatcher version should both be noted.

**Comment by valinet** [comment]
I properly enabled this behavior in the latest pre-release version.
