### ISSUE TITLE
ExplorerPatcher Taskbar Style Windows 7 support

### ISSUE THREAD

**Issue by TK50P** [valinet/ExplorerPatcher#1401]
Hi, I want to get Taskbar Windows 7 style (and Network Flyout Windows 7 Style).
Are there any plans to develop that feature (Windows 7 style support) in this project?

**Comment by Vipin2003** [comment]
For Win7 Taskbar, It is not planned yet and For network flyouts, it is not possible microsoft ruined it completely. It is dead.

**Comment by TheDolphinSlayer** [comment]
Would about context menus? Its possible to turn off taskbar context menu skinning, but we're stuck with the icons on it, any way to turn off the icons (foran example the gear on taskbar settings)

**Comment by AndiDink00x** [comment]
I would like to add also my desire for the implementation of this feature. Adding **Win7** or even **Win8** taskbar would allow customisation of the taskbar through a custom .msstyles (theme) file which is one of the main reasons why i use SAB.

**Comment by AndiDink00x** [comment]
Although have to say that SAB now uses custom theme rendering on context menus thats why i returned to EP
