### ISSUE TITLE
[Suggestion] "Properties entry in Win+X menu and right-click on the taskbar

### ISSUE THREAD

**Issue by Seto-A** [valinet/ExplorerPatcher#1403]
The "**Properties**" entry in the Win+X menu is too general a name to be intuitively associated with ExplorerPatcher.
I suggest you change the name in the Win+X menu to "**ExplorerPatcher Properties**" to make it obvious.
The same can be argued for the name (Properties) used when you right-click on the taskbar.

**Comment by pyrates999** [comment]
The Win+x menu doesn't show the properties option.  But right clicking on taskbar does show the properties option.  Is this what you meant?

**Comment by pyrates999** [comment]
So whatever menu has the properties shortcut that then opens explorer patcher properties, when clicked on, rename that to ExplorerPatcher Properties.

**Comment by Seto-A** [comment]
We are not talking about "whatever" menu. This concerns the Win+X menu which is where you (ExplorerPatcher) have added the **Properties** item.

As you know, the Win+X menu is closely controlled/protected by Windows and it is difficult, if not impossible for users to mess with.

I made a suggestion. If you don't see the value in my suggestion that's another story. I still maintain that the "Properties" name in the Win+X menu does not give any indication as to "properties of what?".

**Comment by pyrates999** [comment]
I'll rephrase:

Any menu (including the menu that comes up if you press Win+X) that has the properties shortcut that then opens explorer patcher properties, when clicked on, rename that to ExplorerPatcher Properties.

**Comment by pyrates999** [comment]
I didn't mean for you to do that.  Just clarifying what you meant so a contributor to the code of explorer patcher can do it.

Please move this to discussions now as issues are for bugs, not new feature requests.

**Comment by Seto-A** [comment]
I don't have the authority to move an issue to discussions. The only thing I can do is open a new discussion (duplicating my initial report in this issue), in which case your numerous responses will be lost.

Please advise how to proceed:
A. I assume you have the authority to make the move to discussions - will you do this?
B. I will open a NEW discussion thread (without your comments in this thread).

**Comment by pyrates999** [comment]
I don't have the ability to move an issue into discussion.  So please close this and open a new one under Discussions.

**Comment by Seto-A** [comment]
Moved to Discussions.
