### ISSUE TITLE
Windows 11 Taskbar becoming unresponsive

### ISSUE THREAD

**Issue by BryanJDaniel** [valinet/ExplorerPatcher#1406]
First noticed this issue when Steam tried to play a game and it wouldn't launch.  
Tried to switch back to Windows 11 Taskbar, and it was completely unresponsive.

Tried multiple restarts and every other fix when searching "Windows 11 taskbar unresponsive" but no luck. Issue persisted even after uninstalling.

The only thing that worked was uninstalling and ending the following through the TaskManager
ShellExperienceHost.exe
SearchIndexer.exe
SearchHost.exe
RuntimeBroker.exe

I like the software and the idea, but needs an option from within to kill these 4 options when switching between Windows 11 and Windows 10 options.

**Comment by hakufu** [comment]
I started having this issue today as well. Really annoying. Right clicking start menu seems to make it go away briefly then it's back again...

**Comment by nicemoreoften** [comment]
Having a similar issue with Explorer becoming unresponsive constantly and killing those processes helps.
