### ISSUE TITLE
Steam error by right clicking Steam tray icon.

### ISSUE THREAD

**Issue by SMxSoMuch** [valinet/ExplorerPatcher#1408]
I'm currently using win10 style top taskbar in Win11.
![image](https://user-images.githubusercontent.com/132253241/235421224-1493a07a-3191-4acb-abdf-cbb17c70ecc7.png)
By right clicking more than once steam icon cause steamwebhelper.exe to not responding.

No issue at all using same setting but only changed to bottom, left and right taskbar.
No issue at all in Win10's top, bottom, left and right taskbar.
 A Steam log on top of Steam window said Error Reference: Shared SteamUI_XXXXXXX_XXXX and Cannot read property 'top'.
Here is the captured shot.
![image](https://user-images.githubusercontent.com/132253241/235422233-bbb26d95-50a7-4b02-9a17-4a8cbe11b459.png)

**Comment by shinseitom** [comment]
I have the same issue.  Explorer patcher with the taskbar at the top.  Right clicking the steam icon causes the same error as you.

Switching back to bottom of the screen fixes the issue.

**Comment by Amrsatrio** [comment]
Tried it just now on 22621.1992 (which was released after this issue was created). Put my taskbar at the top, and spammed right click on the Steam tray icon. No crashes.

Since there seem to be no more activity on this, and that it works fine with the latest Steam, I will be closing this issue.
