### ISSUE TITLE
Pressing windows key while in a game causes crash of game and holds system, turns all monitors off then back on again.

### ISSUE THREAD

**Issue by iosnerd** [valinet/ExplorerPatcher#1417]
I have been playing PUBG with discord and i am not 100% if this is caused by this program but every time i press windows key while in PUBG to use mouse on other monitor without fully alt tabbing to keep game focused, occassionally the game will lock up and about 5 seconds later all 3 monitors go black, discord crashes along with the game then about 5-10 seconds later monitors come back again. Only ever happens when i use the windows key while gaming which brings up the start menu which seems like its crashing explorer, the graphics driver (no notification to say so) or something else then restarting it all again. I believe i get the disconnect windows sound when monitors turn off then back on again. Only been happening for maybe the last month and is only when pressing windows key to bring up start menu. Was happening with my 3080 and now 4080 within the month so shouldnt be GPU and have tried about 3 or nvidia drivers of the most recent releases. Fully updated windows 11 using windows 10 start menu with your program.

Much love for this software, appreciate it greatly!

**Comment by pyrates999** [comment]
If you want to test it, uninstall explorer patcher and see if it still happens.
