### ISSUE TITLE
Clicking on Control Center icon randomly opens the Calendar / Notifications panel

### ISSUE THREAD

**Issue by stanciupaul** [valinet/ExplorerPatcher#1419]
Sometimes when clicking on Control Center icon, it randomly opens the Calendar / Notifications panel instead of Control Center view.

`Version 22621.1555.55.1`

**Comment by stanciupaul** [comment]
Steps to reproduce:
- click on battery status
- click on Control Center icon immediately after
- Calendar / Notifications panel is shown instead of Control Center

**Comment by Amrsatrio** [comment]
Fixed in the latest release, along with the Wi-Fi flyout buttons. Just as a reminder, please do not use the Wi-Fi list in the Control Center after using the Wi-Fi flyout menu for stability reasons.
