### ISSUE TITLE
Left/right side taskbar location settings do not register

### ISSUE THREAD

**Issue by tdubourg** [valinet/ExplorerPatcher#1420]
Hi! I have been using ExplorerPatcher on another computer on Windows 11 for a while. Only way I could use Windows 11... 

But today I tried to install it on another fresh install of Windows 11 and the setting to change the taskbar location on the screen doesn't seem to work properly.

If I select bottom or top, it saves the setting and applies it. However, if I select left or right for the primary, it neither applies it not registers it.

Interestingly, all top/bottom/left/right _do_ get applied and register for the secondary taskbar... but no the first one.

Any idea? I've already tried: rebooting, uninstalling and re-installing EP, running Windows update.

**Comment by wackro** [comment]
Try restaring explorer.exe after making a change king

**Comment by tdubourg** [comment]
> Try restaring explorer.exe after making a change king

Now that's interesting... I did try that, but using the "restart explorer" button in the settings window, and that did not work. I also tried rebooting the machine, which of course restarts explorer.exe and that did not work either... But I have tried switching the setting and restarting explorer via the task manager and now that time it worked... 🤔

From this, I am kind of suspecting that the setting might not live past a reboot... I will try the reboot now and check and close the issue if it does work.

**Comment by tdubourg** [comment]
Looks like it did live past reboot, so I guess it did work this time ¯\_(ツ)_/¯ Thanks!
