### ISSUE TITLE
File explorer content labels black on dark mode (win11)

### ISSUE THREAD

**Issue by Dsj0036** [valinet/ExplorerPatcher#1428]
![imagen_2023-05-07_094116317](https://user-images.githubusercontent.com/97750772/236681033-b1a10602-e25c-4132-bb45-4f329921504c.png)

**Comment by Amrsatrio** [comment]
Please turn this off.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/71296aad-4c02-4b74-a600-3aa841c5b7bc)
