### ISSUE TITLE
While clicking on start menu "StartMenuEXperienceHost.exe" is crashing after changing the start menu style as Windows 10.

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#1432]
ExplorerPatcher Version: 22621.1413.54.5
OS: Win11
Repro Steps:
1.	Launch the Application.
2.	Click on Start menu and change the Start menu style as Windows 10.
3.	Click on Windows button or start menu.
4.	Observe the Crash.

**Comment by pyrates999** [comment]
Please update to the current release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.1_a95a688
And then test again.

**Comment by pyrates999** [comment]
Symbols might not have been downloaded:

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

Do you have any third party firewall software installed?  Try the following:

1. uninstall explorer patcher
2. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. disable the third party firewall software temporarily
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher 
7. enable the third party firewall software

**Comment by Amrsatrio** [comment]
Latest builds of 22621 and 22631 with latest EP have no major problems with the Win10 start menu. Closing this issue.
