### ISSUE TITLE
Windows Explorer is hard crashing after updating win11 today to build 22621.1702 [ EP also is latest build  22621.1555.55.1 ]

### ISSUE THREAD

**Issue by bathindahelper** [valinet/ExplorerPatcher#1434]
Explorer patcher was working ok till today morning (till build 22621.1344 or any build lower than 1702). And then, there was a big windows update on my Win11 to build 22621.1702.

After updating the windows (to latest build 22621.1702), when I rebooted, explorer (and even desktops) weren't showing. Only task manager was working and thru it I uninstalled EP. Explorer started working. Downloaded EP's latest version from EP github site, installed and again explorer crashed as soon as I ran EP.

Its giving some error (thru a small dialouge) like this: 
"::{26EE0668-A00A-44D7-9371-BEB064C98683}\0  Server Execution Failed"

**Comment by canatoly** [comment]
for me helped uninstalling "ep_setup.exe /uninstall" and when original explorer back instrall patcher again

**Comment by bathindahelper** [comment]
No. Uninstalling and Reinstalling EP didn't work. 
I reinstalled windows (I tried to 'Rollback' my windows, which corrupted boot system and I had to reinstall Win11), and now EP itself tries 3 times to start explorer and in the end reports that I should uninstall EP till a new remedy to this problem/crash is posted.

**Comment by elgerm** [comment]
I can confirm. Uninstalling / resinstalling doesn't work. Crashes 3 times then disables itself (which is a good feature btw). Sigh, just started out w windows 11 and was happy with it.

**Comment by fellrnr** [comment]
I had similar problems, but on login the explorer would crash and restart every couple of seconds. I was able to bring up task manager, but it was tricky to type the commands to uninstall. I had to browse to the ep_setup.exe (which thankfully I'd not removed) and add the /uninstall command.

**Comment by pyrates999** [comment]
@elgerm @fellrnr are you also on windows 11 version 22621.1702?

**Comment by laurensiusadi** [comment]
I'm on 22621.1702.
It was crashing when right click on the taskbar.
So I download latest `ep_setup.exe`, copy and rename to `ep_uninstall.exe`.
Run uninstall as administrator. Then run the setup again.
Now works again.

**Comment by DaBomber60** [comment]
> I'm on 22621.1702. It was crashing when right click on the taskbar. So I download latest `ep_setup.exe`, copy and rename to `ep_uninstall.exe`. Run uninstall as administrator. Then run the setup again. Now works again.

This doesn't work for me on `22621.1702`.

**Comment by creeper-0910** [comment]
Have you tried deleting the ExplorerPatcher registry?
That solved the problem in my environment.

**Comment by bathindahelper** [comment]
No, till now the issue exists exactly as it did when it appeared.

**Comment by DaBomber60** [comment]
> Have you tried deleting the ExplorerPatcher registry? That solved the problem in my environment.

Deleting the registry key from `Computer\HKEY_CURRENT_USER\Software` worked!

**Comment by bathindahelper** [comment]
Which subkey is to be deleted from ""Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"? 
Because this folder of registery contains several keys in the right side pane.

**Comment by DaBomber60** [comment]
1. Uninstall explorer patcher
2. Delete entire `Computer\HKEY_CURRENT_USER\Software\ExplorerPatche` folder
3. Reinstall explorer patcher

**Comment by creeper-0910** [comment]
As a precaution, deleting the wrong registry can corrupt Windows.
And if you delete the registry, ExplorerPatcher settings will be reset to defaults.

**Comment by OreoProMax** [comment]
> I'm on 22621.1702. It was crashing when right click on the taskbar. So I download latest `ep_setup.exe`, copy and rename to `ep_uninstall.exe`. Run uninstall as administrator. Then run the setup again. Now works again.

Same problem but doesn't work for me. What a pity.

**Comment by dinceraydin** [comment]
Hi,
I experienced the same crashes on 22621.1702, but clearing the registry entry of EP as mentioned above does fixes it. Thanks a lot!

**Comment by valinet** [comment]
It would have been useful to save the settings prior to deleting them and posting them here, so I can apply them to a test VM, then delete each one of them one by one, thus attempting to figure out which setting exactly, and in turn what functionality is causing the crashing. Deleting the whole key is just a workaround, not a real fix, but without such vital info, a fix is impossible to develop. On my test VM, I have upgraded as well, and it did not crash for me, so obviously I do not have the exact config that's causing the crashing, unfortunately.

**Comment by Seanst3r** [comment]
I renamed the key so I have all the settings I can restore. If it is of value I can try them one by one until the problem reappears.

**Comment by valinet** [comment]
@Seanst3r Great! If you could do that, it might help. We could find out roughly what could be the culprit, and investigate the code around there.

**Comment by Seanst3r** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/88554732/746702c2-3ecc-47d5-9b67-57691fc7dfb4)

Very few settings, here's a photo. HKCU/S/ExplorerPatcher

**Comment by Seanst3r** [comment]
FYI; Current os build is 22621.1702

**Comment by bathindahelper** [comment]
for those who're struck in the loop, its very easy to uninstall or run any program. Just press C+A+ Delete to bring up task manager (any windows) and click on 'Run New Task' and browse to run any program. Sometimes you can switch into any other user profile where it'd even allow you to run/open control panel also.

**Comment by rescend** [comment]
> 1. Uninstall explorer patcher
> 2. Delete entire `Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher` folder
> 3. Reinstall explorer patcher

I can verify that this works properly! I did the extra step of running the uninstall and reinstall in Administrator mode.

**Comment by Geobert** [comment]
As the test VM doesn’t show the crash, I’m wondering if multi-monitor related settings could be the culprit? I’ve seen the crash on my GF’s computer yesterday and this morning, and she has 2 screens, and have the taskbar on her secondary screen, vertical, on the right side of the 2nd screen (which is the left screen).

**Comment by bathindahelper** [comment]
No. I've single monitor. And it was I who reported this issue.

**Comment by bathindahelper** [comment]
> It would have been useful to save the settings prior to deleting them and posting them here, so I can apply them to a test VM, then delete each one of them one by one, thus attempting to figure out which setting exactly, and in turn what functionality is causing the crashing. Deleting the whole key is just a workaround, not a real fix, but without such vital info, a fix is impossible to develop. On my test VM, I have upgraded as well, and it did not crash for me, so obviously I do not have the exact config that's causing the crashing, unfortunately.

Even if I updated my windows11 to latest build, and install EP fresh, my 'explorer' will crash. It happened even when I installed windows and ep fresh.

**Comment by Tokra110** [comment]
Can confirm that KB5026372 is the one that is causing issues. Uninstalling that update fixed the issue for me as a temporary solution.

**Comment by Geobert** [comment]
> Can confirm that KB5026372 is the one that is causing issues. Uninstalling that update fixed the issue for me as a temporary solution.

It’s a combination of this update and settings in EP. As the author said, he has the update but can’t reproduce. What are the values of `Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher` in your registry?

**Comment by bathindahelper** [comment]
I think the offending registry entries have already been pasted in this answer: https://github.com/valinet/ExplorerPatcher/issues/1434#issuecomment-1544967160

**Comment by Tokra110** [comment]
> It’s a combination of this update and settings in EP. As the author said, he has the update but can’t reproduce. What are the values of `Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher` in your registry?

![image](https://github.com/valinet/ExplorerPatcher/assets/9090339/201e5a63-9ec2-4522-89fc-a3e3d517a6cc)

These are the currect registry entries, but this is after uninstalling the mentioned update.

**Comment by bathindahelper** [comment]
EP Installed and crashing on WinVer 22621.1702, with these exact settings:

![image](https://github.com/valinet/ExplorerPatcher/assets/49483022/13db6d6c-f8e8-4ae1-9c00-0c3fdbde0de4)

**Comment by annikajayuk** [comment]
If it helps track this down, here are my exported settings (EP Properties > About > Export current settings) from 1555 which WORKED when updating to 1702.

[ExplorerPatcher_22621.1555.55.1.reg.txt](https://github.com/valinet/ExplorerPatcher/files/11487734/ExplorerPatcher_22621.1555.55.1.reg.txt)

**Comment by oznetmaster** [comment]
I have KB5026372 installed and ExplorerPatcher is operating correctly.  It fails when I install KB5026446.  Works when I uninstall it.

**Comment by pyrates999** [comment]
Don't install preview updates.  They're not supported by explorer patcher:

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by bathindahelper** [comment]
Solved:
https://github.com/valinet/ExplorerPatcher/issues/1487#issuecomment-1565259835

**Comment by bathindahelper** [comment]
I, being the first discoverer of this bug/issue (and starter of this topic also), I've found a workaround/Temporary solution to this issue, as told [here](https://bathindahelper.com/t/explorer-patcher-for-windows-any-all-versions-crashing-on-latest-win11/4087?u=Bathinda_Helper).
