### ISSUE TITLE
Calculator doesn't show icon on Taskbar

### ISSUE THREAD

**Issue by michaelmuselik** [valinet/ExplorerPatcher#1441]
![Schránka 01](https://github.com/valinet/ExplorerPatcher/assets/73330785/b786e52c-400b-4fc9-b1e6-90dfb9942956)

**Comment by pyrates999** [comment]
Please post the version of windows that you have installed.  You can find it by running the command "winver".

**Comment by michaelmuselik** [comment]
WIN 11 21H2 22000.1936
