### ISSUE TITLE
Explorer Patcher keeps crashing in Windows 11 22H2

### ISSUE THREAD

**Issue by TK50P** [valinet/ExplorerPatcher#1445]
I updated to Latest version of windows 11, it crashes explorer patcher
It says:
![Screenshot 2023-05-13 210923](https://github.com/valinet/ExplorerPatcher/assets/127497974/70f8c215-f3ef-4f4c-8620-4be278a883c5)
Is there any fix this error?
It still keeps crashing restart again, Uninstall then install

**Comment by pyrates999** [comment]
Do the following:

1. uninstall explorer patcher
2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher

**Comment by TK50P** [comment]
Wow Thank U So much!!!!!! I Solved!!!!!!!
and no more crashes after restart!

**Comment by pyrates999** [comment]
You gotta redo all your settings though.  Please post the reg file so someone can recreate it on here.

**Comment by TK50P** [comment]
Where do I post reg file?
Just upload this issue?

**Comment by TK50P** [comment]
https://www.mediafire.com/file/q6ynj2rswqz9ua5/fix_ep_crashes_after_update.reg/file
Download the files, then Double-click to merge

**Comment by pyrates999** [comment]
Seems you can't upload reg files.  So open it up in notepad and then select all the text and post it here.

**Comment by TK50P** [comment]
Windows Registry Editor Version 5.00

[-HKEY_CURRENT_USER\Software\ExplorerPatcher]

--ends with this line--
copy this (exclude "--ends with this line--")

**Comment by pyrates999** [comment]
Should be more then that unless you haven't changed any settings yet for it.

**Comment by gdh1995** [comment]
I met this crash today, and it's enough for me just to delete `HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell` folder and then restart explorer.exe.

My env is Win 11 Pro 22621.1702 and ExplorerPatcher 22621.1555.55.2 .

**Comment by TK50P** [comment]
I don't like modern style. I downgraded to Windows 10.

**Comment by morphias2004** [comment]
Same issue. Windows Explorer crashing when I right click on the desktop, launch and exe from File Explorer, etc.

I have tried:

- uninstalled ExplorerPatcher from and elevated the command line, which says it successfully uninstalled
- restarted explorer.exe
- deleted the ExplorerPatcher registry keys
- deleted the ExplorerPatcher folder in C:\Program Files
- restarted explorer.exe again
- rebooted
- installed ExplorerPatcher 22621.1555.55.2
- rebooted and explorer.exe still crashes
- uninstalled ExplorerPatcher from and elevated the command line, which says it successfully uninstalled
- restarted explorer.exe
- deleted the ExplorerPatcher registry keys
- deleted the ExplorerPatcher folder in C:\Program Files
- rebooted
- explorer.exe still crashes
- installed ExplorerPatcher 22621.1555.55.1
- rebooted and explorer.exe still crashes
- uninstalled ExplorerPatcher from and elevated the command line, which says it successfully uninstalled
- restarted explorer.exe
- deleted the ExplorerPatcher registry keys
- deleted the ExplorerPatcher folder in C:\Program Files
- rebooted

And I still experience the explorer.exe crashes.

In none of the reinstall attempts did ExplorerPatcher become available inthe Taskbar context menu.

**Comment by morphias2004** [comment]
Install the latest ExplorerPatcher, running this command:

`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

Credit to this issue thread https://github.com/valinet/ExplorerPatcher/issues/1387

And selecting 'Restore Default Settings' and restarting explorer.exe has resolved the issue.

I can now uninstall ExplorerPatcher, clean up the registry keys and folder and put this nightmare chapter in the rear vision mirror.

**Comment by Lacuranas** [comment]
I had a similar problem, reinstalling alone didn't help. But after deleting the repository entries everything was ok again.
Thank you very much
