### ISSUE TITLE
Network icon not showing in windows 10 taskbar

### ISSUE THREAD

**Issue by glitch128** [valinet/ExplorerPatcher#1447]
Hey, the network icon doesn't show at all on version 22621.155.55.2.
![image](https://github.com/valinet/ExplorerPatcher/assets/78228404/589419dc-d482-4b0b-9864-9ff25844fcdb)
I am on Windows 11 version 22H2 dev channel.
Also, the Windows 10 start menu doesn't work on this version.
OS build: 25309.1000
Experience: Windows Feature Experience Pack 1000.25309.1000.0

**Comment by glitch128** [comment]
hello, I have tried uninstalling and reinstalling explorer patcher and the problems still persist.

**Comment by glitch128** [comment]
hello?

**Comment by pyrates999** [comment]
My instructions said to just uninstall explorer patcher and restart and see if the network icon is shown in the system tray.

**Comment by glitch128** [comment]
I uninstalled and reinstalled explorer patcher, but the problem wasn't fixed

**Comment by pyrates999** [comment]
If you don't reinstall explorer patcher, does the network icon show?

**Comment by glitch128** [comment]
hello, sorry that this has taken so long, but the network icon does indeed show when explorer patcher is uninstalled
![image](https://github.com/valinet/ExplorerPatcher/assets/78228404/c4c507de-33cf-4c05-8b63-bfbbb96b604c)

**Comment by pyrates999** [comment]
Ok, this might sound tedious.  But with explorer patcher uninstalled, check that you're able to hide and unhide each icon in the system tray using the settings app.

If that all works, then install explorer patcher.  And check if you're able to hide and unhide each icon in the system tray using the settings app.

Then report back any that do not hide when you set them to be hidden using the settings app.

Then report back any that do not show when you set them to be shown using the settings app.

I'd say to use a table to show this, but a bulleten list like this would be fine:

- network set to be shown: not working
- network set to be hidden: ?

**Comment by glitch128** [comment]
in the "settings app", do you mean the control panel? because when explorer patcher is uninstalled, I can't get to the control panel page "Notification Area Icons\System Icons", and in "Personalization > Taskbar", there is no option to hide any of the icons such as network, battery, or volume.

**Comment by pyrates999** [comment]
Right click on taskbar and click on Taskbar settings.

Then click on Turn system icons on and off.

**Comment by Amrsatrio** [comment]
Have you tried to turn the network icon on through this control panel page which can be accessed through this?

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/dc4de248-fc12-4fc0-a6c9-70d0dbda496b)

Also, we do not support EP on Canary builds (at least what they refer to >= 25000 builds as of now). And also since there seem to be no more activity on this, I will be closing this issue.
