### ISSUE TITLE
Start menu remains in English on German system

### ISSUE THREAD

**Issue by nexusV2** [valinet/ExplorerPatcher#1450]
Start menu (style Windows 10) remains in englisch on german system (pinned tiles, all apps, etc. ...)

![english-menu-1](https://github.com/valinet/ExplorerPatcher/assets/24851823/b0bc0575-36a0-4e98-a7bc-ac6b1fabaf84)
![english-menu-2](https://github.com/valinet/ExplorerPatcher/assets/24851823/121ebf06-ef93-48e9-a3bd-228b3e717753)

When switching to Win 11 style the language adapts to system language (german).

![german-start-menu](https://github.com/valinet/ExplorerPatcher/assets/24851823/1d1499e7-36a8-402b-9ca2-44d0f580b189)

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. Let me know if there are issues.
