### ISSUE TITLE
Minimize of Application on left click

### ISSUE THREAD

**Issue by Fabian-Schmidt** [valinet/ExplorerPatcher#1453]
Hi,
I am used to left click on application in the taskbar to appear and then left click again to hide it again.
I don't know when this stopped working. Instead the application is just focused.

Is it possible to bring back this 'simple' feature?

Cheers,
Fabian

**Comment by Poopooracoocoo** [comment]
Should not occur anymore. Leave a comment or make a new issue if you still see this.
