### ISSUE TITLE
UWP apps not showing up when using Windows 10 start menu

### ISSUE THREAD

**Issue by Bledrock** [valinet/ExplorerPatcher#1457]
Explorer Patcher version: 22621.1555.1
Notebook: Redmibook 16
Windows 11 version: 2262.1702
Can you fix this bug?

**Comment by pyrates999** [comment]
it's being looked at I think here https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Poopooracoocoo** [comment]
Closing as duplicate of #1108
