### ISSUE TITLE
Windows 10 ribbon don't work on win 11 22h2

### ISSUE THREAD

**Issue by andrew071117** [valinet/ExplorerPatcher#1461]
Hi why is win 10 ribbon not working on win 11 22h2

**Comment by Paolo-O** [comment]
I have to pc's. One was setup with Explorer Patch before the update to Win 22H2 and the File Explorer Win10 ribbon is working perfectly. in the other pc Explorer Patch was installed after the 22H2 update. In this second pc Explorer Patch is not working and I can't understand why

**Comment by pyrates999** [comment]
Please check if you're using the same settings in explorer patcher on both pc's.

**Comment by pyrates999** [comment]
So the Windows 10 ribbon is not working on windows 11 22h2?

**Comment by Paolo-O** [comment]
Exactly, but only on the pc which has installed Explorer Patcher after the update to 22H2.
On the one that EP was installed before 22H2 the Win 10 File Explorer ribbon is working perfectly

--
Inviato da Libero Mail

**Comment by Paolo-O** [comment]
I have installed other tweaker but Explorer Patcher.
Please look at the attached pictures
The first is the File Explorer page of Explorer Patcher.where the Win10 ribbon is set up
The second is the Explorer windows where the ribbon is still thw Win11 one
 
P.S. I can still access the the Win10 ribbon if I use the workaround highlighted in several forum (I mean pressing the up arrow within the Control panel window)

**Comment by pyrates999** [comment]
No pictures were attached.  Convert them to jpg and then upload them here using your web browser.

**Comment by Paolo-O** [comment]
Sorry, here they are as jpg files

Thanks

**Comment by pyrates999** [comment]
Did you have winaero tweaker installed at one point?  If so, what settings did you change?

**Comment by Paolo-O** [comment]
I have never installed Winaero, nor other tweakers.
Yesterday, for the first time, I uninstalled EP and tried StarAllBack, That works for the Win10 Explorer ribbon. Since I do not like all the rest of it, I uninstalled it and I installed back EP, but unfortunately EP cannot change the ribbon yet.
I may try to install Winaero to see if something changes and what "switches" are already "on". What do you think?

**Comment by pyrates999** [comment]
Sure, being thorough is always helpful.

**Comment by Amrsatrio** [comment]
Win10 ribbon works on the latest 22621 and 22631 builds. Closing this issue.
