### ISSUE TITLE
Windows Native Apps Not Displaying in Start Menu & Not Pinning to Start

### ISSUE THREAD

**Issue by ATCJas** [valinet/ExplorerPatcher#1464]
My windows version is Win 11 version 22H2 (OS Build 22621.1702)
I installed the latest version of explorerpatcher on 8th or 9th May, 2023, and the all native apps, such as calculator, notepad, paint, CMD etc. disappeared from start menu. However, these were searchable and were getting pinned to taskbar, but not to start. I uninstalled explorerpatcher just now and observed that all the apps are back and can be pinned to start as well.

Please fix this. Please inform me if more info or screenshots are required. I'll reinstall explorerpatcher and send the same.

**Comment by pyrates999** [comment]
It's being looked at here https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by ATCJas** [comment]
sorry for the duplicate post, and thank you. Will monitor #1108 for a fix.
