### ISSUE TITLE
battery icon

### ISSUE THREAD

**Issue by Zycelz** [valinet/ExplorerPatcher#1466]
wtf happened to it, it doesn't look like the win10 one
![Screenshot 2023-05-18 034404](https://github.com/valinet/ExplorerPatcher/assets/105969023/ef51e0cd-5ddf-4fa4-a945-8f9790adc3a3)

**Comment by Poopooracoocoo** [comment]
Well you're not using the Windows 11 taskbar... What'd you expect?
