### ISSUE TITLE
How to get Search Box?

### ISSUE THREAD

**Issue by erffy** [valinet/ExplorerPatcher#1468]
I have only Search Icon. I'm changed from settings but not worked.
(Windows 11 22H2 | Build 22624.1755)

**Comment by svta-7125** [comment]
Hope it does soon.

**Comment by svta-7125** [comment]
For the time being, you can use the address bar, it still looks really ugly.
![image](https://github.com/valinet/ExplorerPatcher/assets/117646988/b7b94d62-d588-408a-a8ce-935bd5362707)

**Comment by svta-7125** [comment]
For the time being, you can use the address bar, it still looks really ugly.
![image](https://github.com/valinet/ExplorerPatcher/assets/117646988/b7b94d62-d588-408a-a8ce-935bd5362707)

**Comment by glitch128** [comment]
hey, how can I do that?

**Comment by glitch128** [comment]
nevermind, found out how
