### ISSUE TITLE
File explorer Crashing

### ISSUE THREAD

**Issue by ahyr0** [valinet/ExplorerPatcher#1469]
Hello, my windows 11 update to 22H2, 22621.1702 and it makes de file explorer to crash so the app dont work. Anything to do or just wait for an update on the program?

**Comment by pyrates999** [comment]
Do the following:

1. uninstall explorer patcher
2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher

**Comment by timir0n** [comment]
I had the same problem. Re-Installation without manual removing registry key can't fix issue.
Removing registry key fixed it for me. Thanks for tip.

**Comment by echan101github** [comment]
I had the same problem, but downloading [22621.1555.55.2] and using the uninstalling using "ep_setup.exe /uninstall" seemed to work. I then rebooted and reinstalled Explorer Patcher and it seemed to work, but just in case I then uninstalled Explorer Patcher for now.

**Comment by bathindahelper** [comment]
https://github.com/valinet/ExplorerPatcher/issues/1434
