### ISSUE TITLE
Win+X menu

### ISSUE THREAD

**Issue by bufce2010** [valinet/ExplorerPatcher#1477]
First of all I want to thank you for this awesome app.
As for the only issue I'm having right now:
when I Right Click Start Menu button a menu used to appear in both windows 10 and 11, but sadly not available in this app settings.
here is a screenshot of what I'm talking about:
![image](https://github.com/valinet/ExplorerPatcher/assets/50169186/d6f2aa6d-b6fa-4768-8e96-80763d01cb88)

Edition	Windows 11 Pro
Version	22H2
Installed on	‎19/‎05/‎2023
OS build	22621.1702
Experience	Windows Feature Experience Pack 1000.22641.1000.0

**Comment by bufce2010** [comment]
> What menu is not appearing in the Win+X menu?

I mean The Whole menu that appears when you Right Click Start Menu button or click Windows logo + X,
it's screenshot is attached in the post.

**Comment by pyrates999** [comment]
Check that the symbols have been downloaded by checking notifications and restart file explorer using task manager.  You can also try rebooting.

Problems like these are usually from the symbols not having downloaded, which explorer patcher needs to function.

**Comment by bufce2010** [comment]
> symbols

kindly tell me where I can find them, sorry to bother you

**Comment by pyrates999** [comment]
Check notifications if it says windows symbols have been downloaded.  Also check in explorer patcher properties, go to Advanced.   Make sure **Enable symbols download** has a tick mark beside it on the left.

**Comment by pyrates999** [comment]
Use task manager to restart windows explorer.

**Comment by pyrates999** [comment]
Read this: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

It answers your question.  Look for:

If it fails, ExplorerPatcher will usually work without the functionality described above as requiring symbol data and no notification will be shown in this case. Telling if you're in this mode is easy: press Win+X for example. If nothing shows, you're likely in this mode.

**Comment by bufce2010** [comment]
> Read this: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> It answers your question. Look for:
> 
> If it fails, ExplorerPatcher will usually work without the functionality described above as requiring symbol data and no notification will be shown in this case. Telling if you're in this mode is easy: press Win+X for example. If nothing shows, you're likely in this mode.
I fixed it ^_^ here are the steps:

- Disabled Firewalls (I have GlassWire and NetLimiter)
- Downloaded an older version and installed it
- On updates section:
      Checked Both:
          Update Pre-Release...
          suggest the latest version...
- and everything got solved

![image](https://github.com/valinet/ExplorerPatcher/assets/50169186/c9e6422c-042b-4c7c-9eca-b10f10714828)

![image](https://github.com/valinet/ExplorerPatcher/assets/50169186/c029a526-66fc-4173-8699-0f9eb4e1bddf)

**Comment by pyrates999** [comment]
I think your firewalls were preventing explorer patcher from downloading the symbols for windows.  Good to hear you found a fix.

You only need one firewall though, so choose one.  They might be interfering with each other that caused this.  Just like you shouldn't have 2 antivirus software installed.

Next I would untick those 2 options.  And if you intend to stick with the pre-release and plan to submit bug reports, keep the option **Receive pre-releases** ticked.

Otherwise, try uninstalling the preview release of explorer patcher and go back to the last release.  It should work for you since you know your 2 firewalls were causing this.

**Comment by bufce2010** [comment]
> I think your firewalls were preventing explorer patcher from downloading the symbols for windows. Good to hear you found a fix.
> 
> You only need one firewall though, so choose one. They might be interfering with each other that caused this. Just like you shouldn't have 2 antivirus software installed.
> 
> Next I would untick those 2 options. And if you intend to stick with the pre-release and plan to submit bug reports, keep the option **Receive pre-releases** ticked.
> 
> Otherwise, try uninstalling the preview release of explorer patcher and go back to the last release. It should work for you since you know your 2 firewalls were causing this.

Thank you for your time and advices, I'll keep them in mind

**Comment by Amrsatrio** [comment]
The latest EP version should at least get Win+X and Win10 Alt+Tab working on 22621+ builds when symbols are not or not yet available. Closing this issue.

**Comment by christianbearslyclark** [comment]
Yeah !   How to GET ......twinui.pcshell.dll: Win+X menu   ?
