### ISSUE TITLE
bug text on taskbar

### ISSUE THREAD

**Issue by truefriend-cz** [valinet/ExplorerPatcher#148]
![image](https://user-images.githubusercontent.com/7845691/137647617-1de8ab9b-ed99-40e8-9b02-59ab0bf8eeca.png)

Tested on:
Windows 22000.258
App version: 22000.258.30.6

**Comment by valinet** [comment]
Have you enabled "Properties - Advanced - Enable advanced mitigations for correct rendering using classic theme"?

**Comment by truefriend-cz** [comment]
Yes, after disable "mitigations for correct rendering using classic theme" is text ok.
Thanks for speedy reaction :)
