### ISSUE TITLE
Cause Win11 Moment3 (KB5026446) Black Screen

### ISSUE THREAD

**Issue by nijawang** [valinet/ExplorerPatcher#1486]
After update Win11 Moment3 (KB5026446), there is only black screen after login.
I use Task Manager to have Control and remove ExplorerPatcher.
Then my Win11 back to normal after reboot. t

**Comment by 6Tom** [comment]
Yes, that happens.

Windows 11 Professional 22621.1778

**Comment by kanlukasz** [comment]
I'm not sure if this is related to EP. I had the same problem about six months ago when I wasn't using EP yet.
All you need to do is launch `explorer.exe` using Task Manager, and then restart Windows. After these steps, everything works fine

**Comment by igroglaz** [comment]
Indeed kanlukasz way worked.
1) ctrl alt del
2) "Run new task" button on top of the window
3) enter "explorer" -> press Enter

Explorer will load.. restart PC and now it's fixed

**Comment by 6Tom** [comment]
Well, thanks to [kanlukasz](https://github.com/kanlukasz) and [igroglaz](https://github.com/igroglaz).

I have tried restarting the explorer before, but I didn't restart my computer, so it did not work. Now everything is fine.

Or, uninstalling and reinstalling may also be workable.
(Because before [kanlukasz](https://github.com/kanlukasz) and [igroglaz](https://github.com/igroglaz) replied, I had already uninstalled Explorer Patcher and restarted my computer. Then I just install it again, this time it works fine. **Perhaps the most important thing is: to restart the computer** )

**Comment by pyrates999** [comment]
That is a preview update.  They're not supported because microsoft doesn't provide symbols to download for them.  Uninstall any preview updates if you want to use explorer patcher.

source: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by bathindahelper** [comment]
https://github.com/valinet/ExplorerPatcher/issues/1434

**Comment by nijawang** [comment]
I just reinstall EP and it works fine now.
Maybe some EP reg items conflict with Win11 KB5026446 at the begining.

**Comment by pyrates999** [comment]
Preview updates aren't supported by explorer patcher:

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by KabanFriends** [comment]
The update just came and I don't think it's in preview anymore? I had the same issue today.

**Comment by pyrates999** [comment]
No, it's a preview update.

**Comment by 6Tom** [comment]
Yeah, sad to hear that. But that's the truth. Here:
[https://support.microsoft.com/en-us/topic/may-24-2023-kb5026446-os-build-22621-1778-preview-3c547100-7a73-4ae6-bb7d-ebd02e87dc04](https://support.microsoft.com/en-us/topic/may-24-2023-kb5026446-os-build-22621-1778-preview-3c547100-7a73-4ae6-bb7d-ebd02e87dc04)

But it seems that some time ago, these symbols were already available. At least I have been using it for over a week without issue, without rolling back to the old version.

**Comment by crucinal1** [comment]
I've had to uninstall latest update via Troubleshooting menu. Run new task "explorer" didn't help.

**Comment by 6Tom** [comment]
Don't be discouraged. You may try **restarting the computer**. Miraculous things may happen.
