### ISSUE TITLE
Windows 11 Update break ExplorerPatcher

### ISSUE THREAD

**Issue by oznetmaster** [valinet/ExplorerPatcher#1487]
The latest Windows 11 update (KB5026446) released today breaks ExplorerPatcher.

Windows Explorer continually crashes after the update is installed.

Uninstalling the Windows update fixes the problem, so it is definitely the update causing it.

**Comment by bathindahelper** [comment]
https://github.com/valinet/ExplorerPatcher/issues/1434

**Comment by oznetmaster** [comment]
FYI.  I did not install this update.  It was installed automatically as a "required" update.  I was not even near the computer.

**Comment by pyrates999** [comment]
Here's how to disable preview updates from being installed: https://www.tomshardware.com/how-to/leave-windows-insider-builds-windows-11

And you can uninstall a preview update the same way you do with any other update for windows.

**Comment by oznetmaster** [comment]
Not relevant in the least.  I am not on any insider or preview track.  I do not have "Get the latest update as soon as they are available" set.  The updates just show up in Windows Update, and usually do not install unless requested.  This on apparently.

Also, after uninstalling it, ExplorerPatcher work correctly, EXCEPT that now Windows Explorer crashes and restarts whenever the Settings window is closed.  All Settings work correctly, it is just when the window is closed that Explorer crashes, and then restarts.

**Comment by Ndbele** [comment]
https://i.imgur.com/ZQXh0p6.png
these the updates ive received that have broken ExplorerPatcher, i frehs instaled windows 3 days ago on pro with no preview or insider builds

**Comment by pyrates999** [comment]
Do the following:

1. uninstall explorer patcher
2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher

**Comment by dleer** [comment]
This particular preview update installed automatically on one of my machines as well.  I never enable any insider or preview options, or that toggle for latest updates.

**Comment by punkonjunk** [comment]
This is impacting me as well. Removing KB5026446 did not resolve the issue for me, however.

**Comment by punkonjunk** [comment]
This is impacting me as well. Removing KB5026446 did not resolve the issue for me, however.

**Comment by pyrates999** [comment]
As to why it is being installed, someone else reported it here: https://www.bleepingcomputer.com/news/microsoft/windows-11-moment-3-released-with-kb5026446-update-how-to-enable/

To receive the Windows configuration update, you must first go into **Settings** > **Windows Update**, enable the **Get the latest updates as soon as they're available** setting, and then click on the **Check for updates** button.

Except untick this and then uninstall kb5026446.  Otherwise you will keep getting preview updates installed.

**Comment by oznetmaster** [comment]
Unfortunately, that is not true either.  I have never had that ticked, and KB5026446 was automatically installed.

**Comment by pyrates999** [comment]
Check here as well to be sure you're not part of the insider program: https://learn.microsoft.com/en-us/windows-insider/troubleshooting

**Comment by oznetmaster** [comment]
I have already told you that I am not part of the insider program.

"This email address is not registered as a Windows Insider."

**Comment by pyrates999** [comment]
It's called being thorough and checking for every possible reason why KB5026446 was automatically installed.  So make sure it doesn't get installed if you want to use explorer patcher.

This can be closed now.

**Comment by gBoole01** [comment]
I ran into the samie issue updating to "2023-05 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5026446)" 

My fix was:
- Go to `C:\Program Files\ExplorerPatcher`
- Rename `ep_setup.exe` to `ep_uninstall.exe`
- Run `ep_uninstall.exe`
- Delete ``C:\Program Files\ExplorerPatcher`
- Reboot and reinstall ExplorerPatcher again
- (You may reboot one more time after the installation)

**Comment by cjahn50** [comment]
What worked for me was to roll back to 22621.1344.53.1, reboot and then update to the current version.

**Comment by asiro85** [comment]
I did install this update on my desktop and laptop. First time, you have to wait at the black screen for the download of the symbols in the background (no visual feedback). After a minute, open task manager, click button "execute new task" and type "explorer.exe". Windows 11 22621.1778 works fine after that, at least for me.

**Comment by bangrobe** [comment]
KB5026446 was not instaled to my system yet. ExplorerPatcher crashed after my system had installed KB5026372 patch (2023-05 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems).

**Comment by AlfonsoSogara** [comment]
> Do the following:
> 
> 1. uninstall explorer patcher
> 2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
> 3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
> 4. install explorer patcher
> 5. verify you get a notification that symbols have been downloaded
> 6. restart windows explorer using either the task manager or in the properties window of explorer patcher

Me

it worked for me

**Comment by bathindahelper** [comment]
> 

I did succeed by installing ep_setup 22621.1344.53.1 (1Mar2023) (even without first uninstalling its latest version ep_setup 22621.1555.55.1 ). But as told in the above post of Cjahn50, I've not updated EP to the latest version, after it worked well. Why test my luck??!! :)

**Comment by mindplay-dk** [comment]
Looks like [lots of duplicates](https://github.com/valinet/ExplorerPatcher/issues?q=is%3Aissue+is%3Aopen+11+crash) 😬

**Comment by Ratatoskr1** [comment]
FIY. My Windows 11 was unrecoverable after this. No recovery method worked.

**Comment by Jamesstevens-3rd** [comment]
KB5026446 has been installed on my system for 7 days without an error... if it is this update its because of some other interaction with it.

![Q0sge9.png](https://lookimg.com/images/2023/05/31/Q0sge9.png)

**Comment by aldeniangman** [comment]
Once Valinet fixes the problem, it is now safe to go back to insider

**Comment by aldeniangman** [comment]
> Once Valinet fixes the problem, it is now safe to go back to insider

I must wait when microsoft releases new sable build to fix MY PRoblems
/hi

**Comment by Timovzl** [comment]
> FIY. My Windows 11 was unrecoverable after this. No recovery method worked.

This worked for me:

- Ctrl+alt+del => Task Manager
- File => Run new task
- "cmd"
- dir C:\Program Files\ExplorerPatcher
- ep_setup /uninstall (if the file does not exist, first send "rename ep_setup.prev ep_setup.exe")
- Explorer should stop glitching

I did this in safe mode, which is probably unnecessary and makes it even harder to keep the focus on a window to type! If you _do_ need to get into safe mode, use the same trick to start "msconfig", go to the Boot tab, and enable safe boot. You can repeat the steps from there, but it's a lot more annoying to do so.

**Comment by pyrates999** [comment]
> Once Valinet fixes the problem, it is now safe to go back to insider

Insider builds will never be supported by EP.

**Comment by yunpeng-zhang** [comment]
the laptop automatically updated using 2023-09 Cumulative Update for .NET Framework 3.5, 4.8 and 4.8.1 for Windows 11 for x64 (KB5030181)  then EP failed. I rolled it back by uninstalling the update and EP still not working any more.... missing EP but why Microsoft remove all good features like this. The product manager should be fired.
