### ISSUE TITLE
Broken context menu animation

### ISSUE THREAD

**Issue by montagros** [valinet/ExplorerPatcher#1489]
When I invoke the context menu on any element, a white rectangle appears, which only after a while fills with content. I have not found a correlation between any settings, this happens right after installing the program and goes away after removing it. I recorded this effect on video.

https://github.com/valinet/ExplorerPatcher/assets/31985889/f0f0540b-9c3d-4d7c-938d-723452b6ea82

**Comment by pyrates999** [comment]
Did you try rebooting?

Also what version of windows are you running? You can find out by running the command: winver

**Comment by montagros** [comment]
Windows version is 22621.17.02 and ExplorerPatcher 22621.1555.55.2

**Comment by montagros** [comment]
I uninstalled the application, exported and deleted the registry keys, reinstalled, but there was no symbol download message (I remember it was only on the first installation) and I don't know how to force the symbols to download again. The problem still occurs. Attached is the exported registry key.
[EP.zip](https://github.com/valinet/ExplorerPatcher/files/11572396/EP.zip)

**Comment by pyrates999** [comment]
Thank you.  Hopefully one of the developers here are able to recreate this bug.

**Comment by montagros** [comment]
I hope so too, if there is any additional information needed, I am at your service.

**Comment by Amrsatrio** [comment]
Try updating EP and your Windows installation to the latest release build of 22621. I do not observe these issues on my fresh VMs with the latest versions (excluding Insider Canary). If they still occur, you can reopen this issue.
