### ISSUE TITLE
Taskbar with 2 monitors -> jumps back to primary display after restart / reset

### ISSUE THREAD

**Issue by djtomcat** [valinet/ExplorerPatcher#149]
Hi

when reset / restart explorer.exe the taskbar will restart everytime on the primary monitor - instead of (even when its in fixed mode) on the second display :(

**Comment by valinet** [comment]
This has been previously discussed here: https://github.com/valinet/ExplorerPatcher/issues/14#issuecomment-936412362. Have a look there, please.
