### ISSUE TITLE
Icons not displaying, Task Manager and file/folder properties not opening

### ISSUE THREAD

**Issue by GithubUser46173584** [valinet/ExplorerPatcher#1494]
After I uninstalled ExplorerPatcher all icons in Windows have disappeared or are not showing. I did a reset of the Windows icon cache to no avail.

Task Manager also no longer opens and the properties menu for folders or files also no longer opens.

I installed the latest version of ExplorerPatcher 22621.15555.55.2, restored it to default settings, restarted Windows but the issues remain. Using Windows 11 Version 22H2 (OS Build 22621.1413).

See the screenshot below. Attached is an export of the ExplorerPatcher registry settings.

<img width="1920" alt="2023-05-26_173150" src="https://github.com/valinet/ExplorerPatcher/assets/134728881/0aa92d7b-57aa-482d-828c-9d844e5834b5">

[ExplorerPatcher_registry.zip](https://github.com/valinet/ExplorerPatcher/files/11578458/ExplorerPatcher_registry.zip)

**Comment by pyrates999** [comment]
Any other applications installed that modify the windows interface such as 7+ taskbar tweaker and windhawk?

do you have any third party firewalls installed?

Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot

**Comment by BugFixesAndPerformanceImprovements** [comment]
> Any other applications installed that modify the windows interface such as 7+ taskbar tweaker and windhawk?

Only OpenShell.

> do you have any third party firewalls installed?

ESET Smart Security.

> Try the following:
> 
> 1. uninstall explorer patcher
> 
> 2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
> 
> 3. reboot


I tried it but didn't seem to do anything.

**Comment by pyrates999** [comment]
I suspect eset smart security is preventing the windows symbols from being downloaded.

So try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. disable eset smart security temporarily
5. install explorer patcher
6. wait for the notification that windows symbols had been downloaded
7. restart file explorer using either explorer patcher properties app or using task manager
8. enable eset smart security temporarily

Any time you need to update explorer patcher, you may need to disable eset smart security temporarily first so that the windows symbols can be downloaded.

**Comment by GithubUser46173584** [comment]
Same as @BugFixesAndPerformanceImprovements. I ended up just reinstalling Windows.

Guess I can close the issue for now?

**Comment by pyrates999** [comment]
go ahead and close it.

**Comment by realasjad** [comment]
> After I uninstalled ExplorerPatcher all icons in Windows have disappeared or are not showing. I did a reset of the Windows icon cache to no avail.
> 
> Task Manager also no longer opens and the properties menu for folders or files also no longer opens.
> 
> I installed the latest version of ExplorerPatcher 22621.15555.55.2, restored it to default settings, restarted Windows but the issues remain. Using Windows 11 Version 22H2 (OS Build 22621.1413).
> 
> See the screenshot below. Attached is an export of the ExplorerPatcher registry settings.
> <img alt="2023-05-26_173150" width="1920" src="https://user-images.githubusercontent.com/134728881/241284809-0aa92d7b-57aa-482d-828c-9d844e5834b5.png">
> 
> [ExplorerPatcher_registry.zip](https://github.com/valinet/ExplorerPatcher/files/11578458/ExplorerPatcher_registry.zip)

Hi, I'm encountering the exact same set of problems u were having and i spent a whole day trying to find out all solutions on the internet and nothing worked out and i was one step behind reinstalling windows and where i found someone's comment saying the regedit u did to remove arrows from shortcuts was the reason of it and yes i went on and deleted the exact key i made in regedit and restarted windows explorer using cmd as i couldnt open task manager too... and FINALLY thank god everything came back to normal. It wasnt that i did the shortcut arrow editing thing recently but that has affected this time's deletion of Explorer Patcher and thus all this troubles.. I wish i had found it sooner but Im happy that atleast i found the way out before having to reset and reinstall windows.. Sharing this here incase anyone else ever encounters the same thing in the future.

**Comment by pyrates999** [comment]
> > After I uninstalled ExplorerPatcher all icons in Windows have disappeared or are not showing. I did a reset of the Windows icon cache to no avail.
> > Task Manager also no longer opens and the properties menu for folders or files also no longer opens.
> > I installed the latest version of ExplorerPatcher 22621.15555.55.2, restored it to default settings, restarted Windows but the issues remain. Using Windows 11 Version 22H2 (OS Build 22621.1413).
> > See the screenshot below. Attached is an export of the ExplorerPatcher registry settings.
> > <img alt="2023-05-26_173150" width="1920" src="https://user-images.githubusercontent.com/134728881/241284809-0aa92d7b-57aa-482d-828c-9d844e5834b5.png">
> > [ExplorerPatcher_registry.zip](https://github.com/valinet/ExplorerPatcher/files/11578458/ExplorerPatcher_registry.zip)
> 
> Hi, I'm encountering the exact same set of problems u were having and i spent a whole day trying to find out all solutions on the internet and nothing worked out and i was one step behind reinstalling windows and where i found someone's comment saying the regedit u did to remove arrows from shortcuts was the reason of it and yes i went on and deleted the exact key i made in regedit and restarted windows explorer using cmd as i couldnt open task manager too... and FINALLY thank god everything came back to normal. It wasnt that i did the shortcut arrow editing thing recently but that has affected this time's deletion of Explorer Patcher and thus all this troubles.. I wish i had found it sooner but Im happy that atleast i found the way out before having to reset and reinstall windows.. Sharing this here incase anyone else ever encounters the same thing in the future.

What registry key was added that removes the arrow from the icon on shortcuts?

**Comment by realasjad** [comment]
> > > After I uninstalled ExplorerPatcher all icons in Windows have disappeared or are not showing. I did a reset of the Windows icon cache to no avail.
> > > Task Manager also no longer opens and the properties menu for folders or files also no longer opens.
> > > I installed the latest version of ExplorerPatcher 22621.15555.55.2, restored it to default settings, restarted Windows but the issues remain. Using Windows 11 Version 22H2 (OS Build 22621.1413).
> > > See the screenshot below. Attached is an export of the ExplorerPatcher registry settings.
> > > <img alt="2023-05-26_173150" width="1920" src="https://user-images.githubusercontent.com/134728881/241284809-0aa92d7b-57aa-482d-828c-9d844e5834b5.png">
> > > [ExplorerPatcher_registry.zip](https://github.com/valinet/ExplorerPatcher/files/11578458/ExplorerPatcher_registry.zip)
> > 
> > 
> > Hi, I'm encountering the exact same set of problems u were having and i spent a whole day trying to find out all solutions on the internet and nothing worked out and i was one step behind reinstalling windows and where i found someone's comment saying the regedit u did to remove arrows from shortcuts was the reason of it and yes i went on and deleted the exact key i made in regedit and restarted windows explorer using cmd as i couldnt open task manager too... and FINALLY thank god everything came back to normal. It wasnt that i did the shortcut arrow editing thing recently but that has affected this time's deletion of Explorer Patcher and thus all this troubles.. I wish i had found it sooner but Im happy that atleast i found the way out before having to reset and reinstall windows.. Sharing this here incase anyone else ever encounters the same thing in the future.
> 
> What registry key was added that removes the arrow from the icon on shortcuts?

Addition of '**Shell Icons**' key in  **HKEY_LOCAL_MACHINE > SOFTWARE > Microsoft > Windows > CurrentVersion > Explorer** and adding new string '**29**' and setting the value data of it to '**%windir%\System32\shell32.dll,-50**'

**Comment by pyrates999** [comment]
> > > > After I uninstalled ExplorerPatcher all icons in Windows have disappeared or are not showing. I did a reset of the Windows icon cache to no avail.
> > > > Task Manager also no longer opens and the properties menu for folders or files also no longer opens.
> > > > I installed the latest version of ExplorerPatcher 22621.15555.55.2, restored it to default settings, restarted Windows but the issues remain. Using Windows 11 Version 22H2 (OS Build 22621.1413).
> > > > See the screenshot below. Attached is an export of the ExplorerPatcher registry settings.
> > > > <img alt="2023-05-26_173150" width="1920" src="https://user-images.githubusercontent.com/134728881/241284809-0aa92d7b-57aa-482d-828c-9d844e5834b5.png">
> > > > [ExplorerPatcher_registry.zip](https://github.com/valinet/ExplorerPatcher/files/11578458/ExplorerPatcher_registry.zip)
> > > 
> > > 
> > > Hi, I'm encountering the exact same set of problems u were having and i spent a whole day trying to find out all solutions on the internet and nothing worked out and i was one step behind reinstalling windows and where i found someone's comment saying the regedit u did to remove arrows from shortcuts was the reason of it and yes i went on and deleted the exact key i made in regedit and restarted windows explorer using cmd as i couldnt open task manager too... and FINALLY thank god everything came back to normal. It wasnt that i did the shortcut arrow editing thing recently but that has affected this time's deletion of Explorer Patcher and thus all this troubles.. I wish i had found it sooner but Im happy that atleast i found the way out before having to reset and reinstall windows.. Sharing this here incase anyone else ever encounters the same thing in the future.
> > 
> > 
> > What registry key was added that removes the arrow from the icon on shortcuts?
> 
> Addition of '**Shell Icons**' key in **HKEY_LOCAL_MACHINE > SOFTWARE > Microsoft > Windows > CurrentVersion > Explorer** and adding new string '**29**' and setting the value data of it to '**%windir%\System32\shell32.dll,-50**'

So this change?

[no arrows on shortcut icons.zip](https://github.com/valinet/ExplorerPatcher/files/12646468/no.arrows.on.shortcut.icons.zip)

Delete this registry key to fix this?

**Comment by realasjad** [comment]
yes deleting the key fixed the issue

**Comment by pyrates999** [comment]
thank you.

**Comment by zV1nz** [comment]
thank you @realasjad and @pyrates999 soooo much

**Comment by realasjad** [comment]
> thank you @realasjad and @pyrates999 soooo much

glad it helped !
