### ISSUE TITLE
Windows 11 won't boot after 25'May Cumulative Windows Update

### ISSUE THREAD

**Issue by Heeere-GittyGitty** [valinet/ExplorerPatcher#1499]
Hello, 

I've had this issue on my laptop on 26th May and ended up formatting it, and now I had the same issue with my workstation but fortunately found a way to bypass the issue.

I have a strong suspicion that this might have to do with Explorer Patcher, I'll explain the behavior and the workaround, but please tell me on what other info should be necessary to pinpoint this issue, and I'll try to get it.

**Behavior:**

- After going to Windows Update settings in control panel and selecting "download and install" cumulative update from around 25th May, the updated installed OK and the computer rebooted.
- Windows has booted ok and asked for login.
- After login, the mouse cursor and the wallpaper were OK, but no explorer was started.
- There was a possibility of CTRL+SHIFT+ESC to start task manager, but starting explorer wouldn't work.

**Workaround:**

- On the second computed with this behavior, I started the task manager
- The on menu "File", then "Run new task", then "control"
- The old control panel appears without skin or customizations, but when you press the UP arrow on the address bar, it goes to My Computer, and it loads the user theme and explorer preferences. Still no window manager.
- Back to the Task Manager and Run new task, now typing "explorer" boots the rest of the window manager.
- After this, the previous Windows update finished correctly, and the computer is able to reboot and boot normally.

Hope this help anyone else, and if the devs want some logs or something, please ask me, and I'll try gathering it on the second PC. The first one got formatted.

Cheers

**Comment by wonderful123** [comment]
Same thing for me. Restarted 5 times or so and it worked. Have some issues. Can't run task manager.

**Comment by pyrates999** [comment]
26th of June is not for another month.  Did you mean the 26th of may?

And what KB are you referring to?

**Comment by ffuser1** [comment]
I had to system restore to fix. it's the recent update 5-2023. OP meant May obviously

**Comment by Heeere-GittyGitty** [comment]
> 26th of June is not for another month. Did you mean the 26th of may?
> 
> And what KB are you referring to?

Sorry, changed to "May", June was an error.

I think this is the KB
**2023-05 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5026361)** 

Cheers

**Comment by pyrates999** [comment]
Looks like there are bugs with that update: https://www.windowslatest.com/2023/05/20/windows-10-kb5026361-may-2023-update-is-causing-issues-for-some-users/

I would update to windows 10 version 22h2.

**Comment by Heeere-GittyGitty** [comment]
> Looks like there are bugs with that update: https://www.windowslatest.com/2023/05/20/windows-10-kb5026361-may-2023-update-is-causing-issues-for-some-users/
> 
> I would update to windows 10 version 22h2.

This is Win 11 :)

**Comment by pyrates999** [comment]
> > 26th of June is not for another month. Did you mean the 26th of may?
> > And what KB are you referring to?
> 
> Sorry, changed to "May", June was an error.
> 
> I think this is the KB **2023-05 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5026361)**
> 
> Cheers

You initially said windows 10 21h2 for the KB.

**Comment by joberreiter** [comment]
Same problem here.

Running "control" via task manager does not work for me, getting a "::{26EE0668-A00A-44D7-9371-BEB064C98683} server failed to start" error message.

**Comment by wonderful123** [comment]
For some reason my computer started after a few restarts. Then I couldn't get it going again on the next restart. Just a login screen. I could ctrl+alt+del but task manager wouldn't start (using process explorer as default). I had to roll back windows update and uninstall explorer patcher.

Insiders build 21390.

**Comment by pyrates999** [comment]
> For some reason my computer started after a few restarts. Then I couldn't get it going again on the next restart. Just a login screen. I could ctrl+alt+del but task manager wouldn't start (using process explorer as default). I had to roll back windows update and uninstall explorer patcher.
> 
> Insiders build 21390.

Insider builds are not supported:

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Aduahawen** [comment]
Ive been having a similar problem since the april update and Im also suspecting this program being the problem. Black screen, no desktop.

I just uninstall the KB package number via cmd prompt everytime and it goes back to normal. 
in cmd, type wusa.exe /uninstall /kb:5026372 (in mycase this is kb package causing trouble. When i see windows is about to force an update, i always double check the KB number to see what its going to be installing and write it down, just incase i need to roll it back)

**Comment by pyrates999** [comment]
https://www.windowslatest.com/2023/05/17/microsoft-investigates-issues-in-windows-11-kb5026372-may-2023-update/

**Comment by Aduahawen** [comment]
> Ive been having a similar problem since the april update and Im also suspecting this program being the problem. Black screen, no desktop.
> 
> I just uninstall the KB package number via cmd prompt everytime and it goes back to normal. in cmd, type wusa.exe /uninstall /kb:5026372 (in mycase this is kb package causing trouble. When i see windows is about to force an update, i always double check the KB number to see what its going to be installing and write it down, just incase i need to roll it back)

I will say, this program is 100% the cause of my blackscreen issue. After updating and getting the black screen, I was able to bring up task manager, end the program and then run explorer.exe and desktop came up as normal. Heres to hoping this project isnt abandoned and will be updated soon.

**Comment by agsteane** [comment]
> I will say, this program is 100% the cause of my blackscreen issue. After updating and getting the black screen, I was able to bring up task manager, end the program and then run explorer.exe and desktop came up as normal. Heres to hoping this project isnt abandoned and will be updated soon.

Agree, this is 100% the problem. 

I had a slightly different issue - the screen would get stuck in "loading services" mode. Which is to say windows booted fine, but then got stuck in a cycle as if it was constantly trying to load explorer and / or other software services. The CPU was always engaged and it made it nearly impossible to run any other programs.

I was able to run the command prompt and rename the file (it was easier to use the task manager "run new task" and nav directly to [insert directory where you stored the file]. For me this was still in downloads. I renamed it to ep_uninstall.exe and ran it. Instantly Windows started working fine again. 

I should point out you need to be PATIENT. I often had to re-click on the task manager to make it the active window. This entire process took about 30 tediuous minutes, but it WORKED. It was still easier than trying to roll back changes and/or re-instal windows.

**Comment by joberreiter** [comment]
I can confirm that it is not necessary to reinstall windows nor is it necessary to uninstall KB5026372.
The available latest release of EP (with the currently latest beta release 22621.1555.55.2_6fb998e) runs with KB5026372 -- but it is kind of tricky to uninstall and reinstall EP.

![grafik](https://github.com/valinet/ExplorerPatcher/assets/13220647/dba6ab9f-b570-404e-bff9-107d8ffa2d82)

**Comment by agsteane** [comment]
Agree with @joberreiter, uninstall / re-install of either Windows or the KB is unnecessary. 

For me, because it keeps cycling the service / app starting screen, using CMD or task manager is the only way to do it. Easiest would be to make a copy of each by file name and put them in a simple DIR so you can run them one after the other. For me this was at least instant, but took 30 min to sort and run so prepping would save time.

**Comment by pyrates999** [comment]
Don't install preview updates ever or use insider builds of windows if you want to use explorer patcher.  Symbols aren't available for those builds and having symbols to download is a technical requirement for using explorer patcher.

https://github.com/valinet/ExplorerPatcher/wiki/Symbols
