### ISSUE TITLE
Start Menu "position on screen" setting doesn't work

### ISSUE THREAD

**Issue by w4133d** [valinet/ExplorerPatcher#1500]
Start Menu "position on screen" setting doesn't work, but every other setting does??

Used to work before a few updates ago. Just stays on the side 
```
Versions {
  "App version" : "Pre-release 22621.1555.55.2"
  "OS Build"    : "10.0.19044.2965 (Windows 10 21H2)"
}
```
Edit: Added screenshot

![image](https://github.com/valinet/ExplorerPatcher/assets/113371782/6fd7304b-e742-4018-af57-6dcadce8ce95)

_(I use TaskbarX, that's why the taskbar is in the middle. Yes, ExplorerPatcher worked with TaskbarX up until a few updates ago as explained above, but I don't think this is a conflict issue, as I have the taskbar settings on Explorer Patcher all on default, and TaskbarX doesn't interfere w/ the start menu)_

Edit 2: I'm updating to Windows 10 22H2

**Comment by naufkia** [comment]
same here

**Comment by pyrates999** [comment]
Try uninstalling taskbarX to see if it's a default setting that it is using that is causing this.

**Comment by max1c** [comment]
Same here.

**Comment by lunarwolfspirit** [comment]
Same issue however not using TaskbarX but on Insider Preview build 23560.ni_prerelease.230929-1513

**Comment by Amrsatrio** [comment]
Has been always working on me. I only have OldNewExplorer and TranslucentTB installed on my PC which went through 22621 since its release. You may reopen if this is still happening.
