### ISSUE TITLE
Is it possible to make news widgets like in Windows 10 instead of the weather?

### ISSUE THREAD

**Issue by Bledrock** [valinet/ExplorerPatcher#1501]
**Is this feature still in the Windows 11 regedit?
Instead of this:**
![Снимок экрана 2023-05-30 115841](https://github.com/valinet/ExplorerPatcher/assets/111048284/ff1ee90c-7737-40dc-b869-cc472c467210) 

**And this:** 

![Снимок экрана 2023-05-30 115946](https://github.com/valinet/ExplorerPatcher/assets/111048284/2d073130-6841-43fb-a0b2-c601165f6aca)

**Replace with this menu:**

![Снимок экрана 2023-05-30 120155](https://github.com/valinet/ExplorerPatcher/assets/111048284/676a96e8-f69a-4bab-94ad-d2fe83e2b51e)

**Comment by Poopooracoocoo** [comment]
Create a feature request in Discussions.
