### ISSUE TITLE
Windows 10 taskbar color

### ISSUE THREAD

**Issue by eiqnepm** [valinet/ExplorerPatcher#1506]
In Windows 11 the taskbar is a dark gray, in Windows 10 it is pitch black.
Please may an option be added to use the Windows 10 taskbar color?

Windows 10
![](https://i.imgur.com/z6EL7bG.png)
Windows 11
![](https://i.imgur.com/jh2yu1D.png)

**Comment by pyrates999** [comment]
The taskbar colour is controlled by the following:

1. right click on the desktop and click on **personalize**
2. click on **colors** on the left side
3. look for **windows colors** and the colour of it is what you have chosen
