### ISSUE TITLE
Start Menu Applist not updating properly on Windows 11

### ISSUE THREAD

**Issue by ryuenma** [valinet/ExplorerPatcher#1508]
I currently use Win 11 Moment 2 Update

Taskbar style is Win10, and some of my programs aren't shown in the startmenu app list, but i can still search for it. Is there any workaround to refresh this properly?

**Comment by pyrates999** [comment]
Moment 2 update is a preview update and not supported because microsoft doesn't provide symbols for previews and insider builds:

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by ryuenma** [comment]
I see, thank you for the reply. I'll try to solve this alternatively then, since i needed ExplorerPatcher in order for TaskbarX to work

![image](https://github.com/valinet/ExplorerPatcher/assets/71396519/d01c66ed-39aa-4718-9085-265e5c5a5cb5)

**Comment by Amrsatrio** [comment]
This has been fixed in an EP update from months ago. Closing this issue.
