### ISSUE TITLE
Much windows elements doesn't appear in the explorerpatcher in Windows 11 Insider Builds.

### ISSUE THREAD

**Issue by drdaxer** [valinet/ExplorerPatcher#1515]
Hello, I have an issue with start menu , a lot of elements like MSN News, Xbox App, Console Companion, Your phone, Mail and more metro apps and tiles doesn't appear in the explorer patcher that I installed in the insider builds of windows 11

**Comment by pyrates999** [comment]
Insider builds and preview updates are not supported due to symbols not being available:

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Vipin2003** [comment]
> Hello, I have an issue with start menu , a lot of elements like MSN News, Xbox App, Console Companion, Your phone, Mail and more metro apps and tiles doesn't appear in the explorer patcher that I installed in the insider builds of windows 11

You might be using Win10 SM....If yes, then see this #1108
