### ISSUE TITLE
Missing "Show badges on taskbar buttons"

### ISSUE THREAD

**Issue by ggnull35** [valinet/ExplorerPatcher#1519]
I can not find a way to enable this feature after ExplorerPacther installation.
Do I miss anything?

**Comment by pyrates999** [comment]
It's a an option in windows:

https://support.microsoft.com/en-us/windows/how-to-use-the-taskbar-in-windows-0657a50f-0cc7-dbfd-ae6b-05020b195b07#WindowsVersion=Windows_11

**Comment by ggnull35** [comment]
Thank you
