### ISSUE TITLE
Task Manager animation flickers white on dark mode

### ISSUE THREAD

**Issue by OrbitStorm** [valinet/ExplorerPatcher#1521]
I'm unsure if this is a bug with EP or Windows 11 but since the only Google result I found that resembles this issue is #1489 on this repo, I figured I should submit an issue here just in case.

That said, when unminimizing the Task Manager, the animation briefly flickers white before displaying, much like the context menu animation referenced above.

**Edition:** Windows 11 Home
**Version:** 22H2
**Installed on:** ‎6/‎3/‎2023
**OS build:** 22621.1778
**Experience:** Windows Feature Experience Pack 1000.22642.1000.0

**ExplorerPatcher Version:** 22621.1555.55.1

https://github.com/valinet/ExplorerPatcher/assets/4934144/983c25fd-4751-4e9c-aaa2-01a41912e598

**Comment by pyrates999** [comment]
Please include your windows 11 version and build number.
Please include the version of explorer patcher you have installed.

If you uninstall explorer patcher and reboot, does the animation flickering white still occur with the task manager?

**Comment by OrbitStorm** [comment]
Apologies for not including that information to start, I edited my post accordingly.

I should also add this may be a Windows 11 bug after all. I did another few searches and came upon [this Reddit post](https://www.reddit.com/r/Windows11/comments/11ydw9s/any_idea_why_there_is_a_white_screen_coming/) which is essentially the same issue as mine and responses indicate it's just a thing with Windows 11.

I don't recall Task Manager doing this before installing EP and after uninstalling EP it still does it although (oddly) not as consistently but since I've had no other issues with EP, it's likely just a Windows 11 issue.

So, apologies are also in order for what appears to be a false bug report. Sorry for that and thank you for the quick response!

**Comment by Poopooracoocoo** [comment]
>Apparently, this is a Windows 11 bug after all. I did another few searches and came upon [this Reddit post](https://www.reddit.com/r/Windows11/comments/11ydw9s/any_idea_why_there_is_a_white_screen_coming/) which is essentially the same issue as mine and responses indicate it's just a thing with Windows 11. So, apologies are also in order for what appears to be a false bug report. Sorry for that and thank you for the quick response!

Thus closing
