### ISSUE TITLE
Translation Start Menu

### ISSUE THREAD

**Issue by Pokye** [valinet/ExplorerPatcher#1525]
I'm from Brazil, and I use Portuguese-Brazil language, and the start menu is in English. Would you be able to fix this?
![Captura de tela 2023-06-05 161238](https://github.com/valinet/ExplorerPatcher/assets/98105181/c1941e9c-77a8-416b-bc46-52e7208063f7)
![Captura de tela 2023-06-05 161303](https://github.com/valinet/ExplorerPatcher/assets/98105181/3dbbae0c-581e-4af2-a63a-9ba6472b4e3b)

**Comment by pyrates999** [comment]
I think this is what you're talking about: https://github.com/valinet/ExplorerPatcher/issues/1108

So if it is, it is already known.

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. Let me know if there are issues.
