### ISSUE TITLE
Explorer crashes upon right-clicking taskbar if 'Skin taskbar and tray pop-up menus' is disabled on Windows 10 1909 18363.2274

### ISSUE THREAD

**Issue by dimmskii** [valinet/ExplorerPatcher#1527]
Winver:
Windows 10 1909 18363.2274
![image](https://github.com/valinet/ExplorerPatcher/assets/4108751/c5b25ec5-8334-4e61-9b96-98f0c06c4872)

I noticed that upon updating to 1909 I got those 2000+ trojan horse 'features' with the news, context menus look anti-aliased, etc. I thought all this dreck was exclusive to 2004 and upwards. They seem to have replaced all context menus with their idiotic new UI code. Is there a shot in hell we can still have the old Windows Forms menus on post-2021/2022 (not sure when it changed) explorers? I immediately got stripped of my Windows.old folder after jumping from 1903, so I'm screwed :)

![image](https://github.com/valinet/ExplorerPatcher/assets/4108751/cef4bc50-2fc6-419b-a748-da09ca6c2afa)

![image](https://github.com/valinet/ExplorerPatcher/assets/4108751/6bbe358c-54f1-49dd-a08d-afb5f696d9c5)

**Comment by pyrates999** [comment]
Windows 10 1909 is 4 years old and no longer supported by Microsoft.  Please update to Windows 10 22H2.

**Comment by FeyrisTan** [comment]
Having the same problem.
Winver see below
![image](https://github.com/valinet/ExplorerPatcher/assets/88407761/30e5614c-bdae-44ba-a185-9c7af407f88a)

**Comment by pyrates999** [comment]
Insider builds are not supported because Microsoft doesn't provide symbols to download for them: https://betawiki.net/wiki/Windows_11_build_25387

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Amrsatrio** [comment]
Does not happen on 19045.3693. Probably not worth the time to add support for this certain version, since you seem to have upgraded to 19045 in your other issue.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/c9738381-3f09-4515-b960-4e6cf44c35e9)
