### ISSUE TITLE
Can't update the EP

### ISSUE THREAD

**Issue by iJahangard** [valinet/ExplorerPatcher#1530]
![Update_for_ExplorerPatcher_from_https꞉∕∕github com∕valinet∕ExplorerPatcher∕releases∕download∕22621 1](https://github.com/valinet/ExplorerPatcher/assets/67248292/76d71cac-568a-4a85-a9dd-40e8a205f5e7)
every time i try to update , this window showed up
i do followed the steps but that just something not working

**Comment by pyrates999** [comment]
Please close this if my suggestion was the answer.

**Comment by iJahangard** [comment]
I tried to uninstall EP but it just didn't work
If you try to uninstall it, the error in first comment wil shows up

**Comment by pyrates999** [comment]
> I tried to uninstall EP but it just didn't work If you try to uninstall it, the error in first comment wil shows up

That error is from it trying to run explorer patcher.  Close it and then try to uninstall explorer patcher using the instructions here: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To
