### ISSUE TITLE
Question: how can we create custom wide/large tiles?

### ISSUE THREAD

**Issue by convalise** [valinet/ExplorerPatcher#1534]
Hello!

Before on windows 10 we could create custom tiles with programs like edgeTile (https://www.microsoft.com/store/apps/9nblggh20dz9), Pin Steam, and many others. They let us create a custom tile with a custom image and custom target (exe or url).

Since these programs don't work on Windows 11 (obviously), is there a way to create those tiles while using Explorer Patcher with Windows 10 start menu? Maybe a manual process?

For reference, this is what I'm trying to achieve (made with photoshop):

![tile](https://github.com/valinet/ExplorerPatcher/assets/12805305/c979e6b6-9f51-4009-b398-cb22a855f938)

Thanks!

**Comment by pyrates999** [comment]
If that is a windows 11 start menu exclusive feature, then I'll say no.

**Comment by pyrates999** [comment]
Here's how you can do it in windows 10 I think:

https://www.makeuseof.com/tag/create-custom-start-menu-tiles-windows-10/

**Comment by convalise** [comment]
I'm not using Windows 10, I'm using Windows 11 + Explorer Patcher.

**Comment by pyrates999** [comment]
Try it since that is for the windows 10 start menu, which you said you're using in windows 11 with explorer patcher.

**Comment by convalise** [comment]
Man, that's the whole point of my question, fells like you are not reading what I'm writing.

> After installing EP I tried using the old programs to create a wide tile but they don't work.

You probably don't know so let's wait for more people to pitch in.

**Comment by Vipin2003** [comment]
You want to pin tiles of apps in other options too like large, wide, etc like in Win10...Right??

It can be done but that need to get a fix for UWP Apps to be shown in Win10 start.

I've tried but it doesn't show anything except a download button in place of app icon. So, last option is to wait for it or to use older version of windows

**Comment by pyrates999** [comment]
You won't be able to until this is fixed I think: https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by convalise** [comment]
Yes, right.
So it was possible until a couple months ago... good to know. I've just started using EP, I didn't know those issues were related. Thanks! I'm gonna keep an eye for the fix then.

**Comment by Vipin2003** [comment]
#Sorry for poor english..
Talking about this one or not?? .....

![2023-06-11_16h18_35](https://github.com/valinet/ExplorerPatcher/assets/93650504/6f608081-9037-4a7e-85a7-fe491e21d983)

This is the known issue #1108 ... It was working fine in old builds lower than 1000. After recent changes in UWP apps in Win10 start made by Microsoft, this issue take place.. You can do this. Just download apps from Store and it will be there..but lainching won't work.

**Comment by Vipin2003** [comment]
> Yes, right. So it was possible until a couple months ago... good to know. I've just started using EP, I didn't know those issues were related. Thanks! I'm gonna keep an eye for the fix then.


Hello @convalise, If you wish, you can copy this files (StartTileData.dll and AppResolver.dll) from **Windows\System32** to the folder, there AppResolverLegacy.dll and StartTileDataLegacy.dll are located **C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy** and rename them to AppResolverLegacy.dll and StartTileDataLegacy.dll there (I would suggest to backup original AppResolverLegacy.dll and StartTileDataLegacy.dll by adding 0 after dll). This will fix UWP apps, but brake "Pin to Start".You can simply pin them by dragging them but I doesn't have a way to unpin. So, be careful, while pinning

**Comment by Vipin2003** [comment]
By this way, You will be able to restore the Wide, large options on tiles. Thanks

**Comment by Crumdidlyumshis** [comment]
Having same issues, but in general cannot get anything to pin to the menu. Tried the above method @Vipin2003 suggested but still didn't work.

**Comment by Vipin2003** [comment]
You can't pin them directly. You have to drag the app from menu to tile area as "Pin to Start" context menu is broken. 

> Having same issues, but in general cannot get anything to pin to the menu. Tried the above method @Vipin2003 suggested but still didn't work.
