### ISSUE TITLE
ep_extra flagged by my companies InfoSec

### ISSUE THREAD

**Issue by AndriSig** [valinet/ExplorerPatcher#1538]
Hi, I'm currently in a battle with InfoSec to get them to greenlight EP after they flagged ep_extra as unsafe.

I've been trying to explain how it isn't.  But its a struggle and I see no end in sight.  This flagging came from some automated tool that they use and I assume that this will happen to others who work at large corporations.  

Would it be possible to get a version without that in the compilation?  I know i could just fork the project on my own and remove it.  But keeping up to date like that would be a big struggle.

**Comment by pyrates999** [comment]
You could submit a pull request to make it a compile option to include ep_extra or not.
