### ISSUE TITLE
uou can make search box?

### ISSUE THREAD

**Issue by BussyBakks** [valinet/ExplorerPatcher#1539]
yeah if yes, make in another vers pls

**Comment by stretch07** [comment]
This issue is not constructive.

**Comment by vkochladze** [comment]
Same here. Had this issue before and found a fix on here, but forgot what it was

**Comment by pyrates999** [comment]
Please provide more details.  Otherwise this should be closed due to lack of information provided.

**Comment by BussyBakks** [comment]
Uh i want owner to add searchbox in windows10 taskbar, i cant use without searchbox

**Comment by pyrates999** [comment]
Right click on the taskbar and go to search menu.  See if you're able to add search that way.

**Comment by BussyBakks** [comment]
@pyrates999 wat?

**Comment by stretch07** [comment]
@BussyBakks can you not just search from the start menu?
otherwise you can just install powertoys and do alt+space

**Comment by pyrates999** [comment]
> @pyrates999 wat?

https://support.microsoft.com/en-us/windows/hide-and-unhide-your-search-box-in-windows-6d8252b7-864f-c1b6-6a56-3eea0cda08dc
