### ISSUE TITLE
Crashed after installing KB5027119

### ISSUE THREAD

**Issue by mj17shAlice** [valinet/ExplorerPatcher#1550]
![image](https://github.com/valinet/ExplorerPatcher/assets/56729639/2559b0bc-0f85-428f-97d2-47f65a22236a)
![image](https://github.com/valinet/ExplorerPatcher/assets/56729639/5ab7373e-e89d-484a-8ac5-0d9433f0b340)
By the way, this update might led to some changes in bottom sidebar, and my Everthing search box disappeared.
![image](https://github.com/valinet/ExplorerPatcher/assets/56729639/381540d6-807a-4508-a127-5d0cbd529d9b)

**Comment by aylaanne** [comment]
Got the same error this morning; I think it has to do with whatever update just got pushed through:
 ![image](https://github.com/valinet/ExplorerPatcher/assets/136718293/dfd40e26-0733-484e-9e97-a2cb3a2c1a99)
