### ISSUE TITLE
Blackout after login with KB5027231 applied

### ISSUE THREAD

**Issue by PCL86** [valinet/ExplorerPatcher#1551]
After applying KB5027231, it becomes a blackout state after login.

**Comment by cy18** [comment]
Exactly same problem occurs to me. After hours, I found my way to save the system. Since my Windows are Chinese, the names in the following steps may not be exactly right.

1. Executate Task Manager with Ctrl+Shift+Esc
2. Kill explorer.exe
3. Run explorer.exe with "Run new task"
4. Well, this worked on my previous blackout months ago, but does not work this time. But it still worth trying. Now Let's continue.
5. Run your webbrowser by "Run new task", download explorer patcher setup file ep_setup.exe.
6. Run ep_setup.exe /uninstall to uninstall explorer patcher.
7. Reboot. 
8. Step 5~7 are the steps I tried. I'm not sure if they are necessary.
9. In Task Manager, run “Computer Manager” by creating a new task called compmgmt.msc 
10. Create a new user, and add the new user to the group Administrators.
11. Switch to login window by Win+L and login as the new user.
12. The explorer should starts normally as the new user. Find Explorer Patcher in Settings > Apps > Installed Apps and uninstall it. 
13. Logout and login to your old user, it should be restored now.

After this, I tried install explorer again, it still does not work. So I think I have to bear the Win11 style UI before a fix comes out.

**Comment by cy18** [comment]
> > Exactly same problem occurs to me. After hours, I found my way to save the system. Since my Windows are Chinese, the names in the following steps may not be exactly right.
> > ```
> > 1. Executate Task Manager with Ctrl+Shift+Esc
> > 
> > 2. Kill explorer.exe
> > 
> > 3. Run explorer.exe with "Run new task"
> > 
> > 4. Well, this worked on my previous blackout months ago, but does not work this time. But it still worth trying. Now Let's continue.
> > 
> > 5. Run your webbrowser by "Run new task", download explorer patcher setup file ep_setup.exe.
> > 
> > 6. Run ep_setup.exe /uninstall to uninstall explorer patcher.
> > 
> > 7. Reboot.
> > 
> > 8. Step 5~7 are the steps I tried. I'm not sure if they are necessary.
> > 
> > 9. In Task Manager, run “Computer Manager” by creating a new task called compmgmt.msc
> > 
> > 10. Create a new user, and add the new user to the group Administrators.
> > 
> > 11. Switch to login window by Win+L and login as the new user.
> > 
> > 12. The explorer should starts normally as the new user. Find Explorer Patcher in Settings > Apps > Installed Apps and uninstall it.
> > 
> > 13. Logout and login to your old user, it should be restored now.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this, I tried install explorer again, it still does not work. So I think I have to bear the Win11 style UI before a fix comes out.
> 
> You can simplify to:
> 
> 1. Open Task Manager via Ctrl+Shift+Esc
> 2. Via "Run new task" in right corner open powershell/cmd
> 3. "C:\Program Files](c:\Program Files\ExplorerPatcher\ep_setup.exe" /uninstall
> 4. Confirm the dialog and wait for the successful uninstall modal to popup
> 5. After clicking Ok on the successful uninstall modal the explorer will restart and Win should be working and be _W11 ugly_ again...

I'm wondering why my step 5~7 does not fix the system? Because of a wrong version of ep_setup.exe?

**Comment by cy18** [comment]
> I had the same problem.
> 
> 1. Restart into command prompt as a startup option. (You have to reboot multiple times after POST but before Windows login, then let one of the boots continue until the blue diagnostics screen appears. I think startup options are F1.)
> 2. `wusa.exe /uninstall /kb:5027231`
> 3. Reboot into Windows
> 4. Pause updates (because it will try to update again)
> 5. Backup EP settings
> 6. Uninstall/disable EP (or see if it will download symbols; for me, it did not)
> 7. Install the Windows Update
> 8. Reinstall EP

I tried completely uninstall EP, uninstall/reinstall KB5027231, and reinstall EP, it still blacks out. I tried both EP 22621.1555.55.1 and 22621.1555.55.2, while my system version is 22621.1848, maybe this is the reason?

**Comment by abap-weasel** [comment]
+1

**Comment by cy18** [comment]
> You could try uninstalling the other KBs possibly installed at the same time, discoverable via: `wmic qfe list brief /format:table`
> 
> If that doesn't work, I'm out of answers.

Thank you for your reply. I tried uninstalling KBs. After uninstalling 3 or 4 KBs, it failed at KB5025239, with code 0x800f0905. Then I tried `DISM /Online /Cleanup-Image /RestoreHealth` before another try, it still failed to uninstall KB5025239. So I moved on to the next steps, i.e. , Install all KBs, reboot, install EP. It still black out.

Do you have any idea where can I find some log to help addressing the problem? Thank you.

**Comment by pyrates999** [comment]
Windows has lots of logs in windows event viewer.  Here's how to access it:

1. On the desktop, right click on This PC and select manage
2. Go to System Tools -> Event Viewer -> Windows Logs
3. From there check Application and System

**Comment by qheartq616** [comment]
1.Ctrl+Alt+Delete
2.Execute Task Manager
3.Click "Run new task"
4.Input "explorer.exe" and press enter
5.Tried setp 4 again and again, my computer came out an alert and says that explorer had reboot over 10 times and your task bar turn back to win11 style.
6.Uninstall your explorer patcher or wait until an update that fixes this problem

I met problem like this before. I thought it's probably this soft has a bug that make your explorer down. View it on [https://github.com/valinet/ExplorerPatcher/discussions/1087](url)

**Comment by cy18** [comment]
I tried create a new user and install EP in that user's desktop environment, it works. However, when I login with the old user, it still blacks out. I tried restore EP default settings, it does not work.
So the problem should be some user settings.

**Comment by pyrates999** [comment]
To see if it's a setting that explorer patcher has set, try this:

1. login as the user that has the black screen
2. press ctrl+alt+delete to bring up the task manager
3. use the run feature in task manager to run cmd.exe
4. cd into C:\Program Files\ExplorerPatcher by running: cd "C:\Program Files\ExplorerPatcher"
5. then run: ep_setup.exe /uninstall
6. that should uninstall explorer patcher
7. run regedit
8. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
9. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
10. reboot and log into that same user who had the black screen
11. install explorer patcher
12. verify you get a notification that symbols have been downloaded
13. restart windows explorer using either the task manager or in the properties window of explorer patcher

**Comment by SimonMacer** [comment]
I have updated to Windows 11 Build 22000.2121 (KB5027292) the Blackout or explorer crash issues are resolved.

The new KB5027292 preview update fixes this issue.

June 13, 2023—KB5027223 (OS Build 22000.2057) Known issues
https://support.microsoft.com/en-us/topic/june-13-2023-kb5027223-os-build-22000-2057-168b3781-ffd0-4779-83da-162b880a0b24

**Comment by cy18** [comment]
> To see if it's a setting that explorer patcher has set, try this:
> 
> 1. login as the user that has the black screen
> 2. press ctrl+alt+delete to bring up the task manager
> 3. use the run feature in task manager to run cmd.exe
> 4. cd into C:\Program Files\ExplorerPatcher by running: cd "C:\Program Files\ExplorerPatcher"
> 5. then run: ep_setup.exe /uninstall
> 6. that should uninstall explorer patcher
> 7. run regedit
> 8. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
> 9. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
> 10. reboot and log into that same user who had the black screen
> 11. if there is no black screen now, continue, otherwise stop
> 12. install explorer patcher
> 13. verify you get a notification that symbols have been downloaded
> 14. restart windows explorer using either the task manager or in the properties window of explorer patcher

Thank you for your reply. The black screen consists  in the old user as long as EP is installed. Since the explorer is crached, I cannot see the notification even if the symbols are downloaded. According to the manual mentioned in https://github.com/valinet/ExplorerPatcher/wiki/Symbols , I see no symbols loaded in the console.

**Comment by SimonMacer** [comment]
> Preview updates and insider builds are not supported by explorer patcher: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> So I would advise you to uninstall explorer patcher then as it can't work without symbols.

It work good for me ^^^
https://i.imgur.com/tpqN1PL.png

Windows 11 21H2 Inside Preview 22000.2121

**Comment by PCL86** [comment]
> Exactly same problem occurs to me. After hours, I found my way to save the system. Since my Windows are Chinese, the names in the following steps may not be exactly right.
> 
>     1. Executate Task Manager with Ctrl+Shift+Esc
> 
>     2. Kill explorer.exe
> 
>     3. Run explorer.exe with "Run new task"
> 
>     4. Well, this worked on my previous blackout months ago, but does not work this time. But it still worth trying. Now Let's continue.
> 
>     5. Run your webbrowser by "Run new task", download explorer patcher setup file ep_setup.exe.
> 
>     6. Run ep_setup.exe /uninstall to uninstall explorer patcher.
> 
>     7. Reboot.
> 
>     8. Step 5~7 are the steps I tried. I'm not sure if they are necessary.
> 
>     9. In Task Manager, run “Computer Manager” by creating a new task called compmgmt.msc
> 
>     10. Create a new user, and add the new user to the group Administrators.
> 
>     11. Switch to login window by Win+L and login as the new user.
> 
>     12. The explorer should starts normally as the new user. Find Explorer Patcher in Settings > Apps > Installed Apps and uninstall it.
> 
>     13. Logout and login to your old user, it should be restored now.
> 
> 
> After this, I tried install explorer again, it still does not work. So I think I have to bear the Win11 style UI before a fix comes out.

thank you.
The method you taught me worked fine.
appreciate

**Comment by x011** [comment]
- start normally until you get the black desktop
 - `crtl + lshift + esc` to open task manager
 - new task: `cmd` (admin?)
 - `wusa.exe /uninstall /kb:5027231`
- reboot
- remove explorer patch `ep_setup.exe /uninstall`
- reboot
- reinstall `kb:5027231`

**Comment by x011** [comment]
uninstalling ep , kb and reinstalling ep didn't work for me. Will wait until new ep or kb fixes this.

**Comment by Tsaukpaetra** [comment]
Personal anecdote: After uninstalling both the KB and EP, clearing the registry settings, rebooting, installing the KB and EP, all is well again.

Only major differences between the two reg changes is the broken one has stuff under twinui.pcshell whereas the clean install (currently) does not.

**Comment by BotAwesome** [comment]
Same problem here with the 22621.1848 Build

**Comment by Raptor007** [comment]
My workaround for this is to first try restarting a couple of times, and if that doesn't fix it, go into Recovery Mode, Advanced, Uninstall Updates, then Uninstall Latest Quality Update.  This has successfully resolved the issue for me several times now.  Something in the 2023-06 Cumulative Update batch seems especially likely to cause the black screen problem.

I'm also not convinced this is ExplorerPatcher's fault; when looking around for fixes, it sounds like the black screen after login is just a common occurrence on Windows 11, especially after installing updates.  But if ExplorerPatcher is contributing to the problem, I'd sure love it fixed!

**Comment by vnvn-org** [comment]
Each one during the reboot process for the update gave me a black screen, somebody help me now. My OS is 22621.1848. I try uninstall EP and reinstall but not working

**Comment by pyrates999** [comment]
If it works when EP is uninstalled, I would wait until there's a fix.

**Comment by appleguy010** [comment]
The KB5027231 update applied on two of my machines, but only one of them experienced this issue.
I have very different settings applied on these machines so I suspect certain configurations are affected by this issue.
Perhaps machines with the Windows 10 style start menu and taskbar configured? That is the main difference between my configurations from my memory.

I would like to export my settings and compare them between my two machines, but unfortunately I didn't realize ExplorerPatcher was causing the issue at the time so I ended up bricking my windows install after attempting to load a restore point from a few days prior (using rstrui.exe)
I suppose I could still do this by checking registry keys manually. Are all the settings for ExplorerPatcher stored in the registry?

**Comment by Raptor007** [comment]
I'm not sure this will work for everyone, but I was able to successfully install the 2023-06 Cumulative Update without the black screen problem.  The trick seemed to be updating to the latest Nvidia driver (536.23 6/14/2023) in GeForce Experience _before_ letting Windows Update install.  I did not have to uninstall ExplorerPatcher!

I got the idea of the graphics driver being part of the problem from [this black screen troubleshooting guide](https://windowsreport.com/windows-11-black-screen-with-cursor/), which suggests resetting the graphics driver as a possible fix.

**Comment by appleguy010** [comment]
I was able to completely recover my environment in a much more elegant way than uninstalling the program or uninstalling any updates.
Here was my process.

Once I was logged in but explorer.exe wouldn't launch (black screen), I opened task manager (Ctrl-Shift-Esc)
Task Manager > Run new task:
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

Once the "Properties" window appeared, I clicked "Restart File Explorer (*)" in the bottom left.

At this point explorer.exe launched successfully for the first time and I got a toast notification stating the following:
"Successfully downloaded symbols for OS build 10.0.22521.1848"
From there I rebooted the system and everything is working normally now.

I'll attach my exported settings from my two machines in case that data is useful.
[explorerpatcher-settings.zip](https://github.com/valinet/ExplorerPatcher/files/11842210/explorerpatcher-settings.zip)

Is ExplorerPatcher unable to download symbols automatically when explorer.exe doesn't launch?
I genuinely don't know the answer to that because my computer installed the windows update while offline (so the downloading the symbols would have failed on the first boot anyways).
If it is unable to download symbols that is definitely an issue since it seems to me like they were a prerequisite to get my explorer.exe working.

**Comment by qheartq616** [comment]
> I was able to completely recover my environment in a much more elegant way than uninstalling the program or uninstalling any updates. Here was my process.
> 
> Once I was logged in but explorer.exe wouldn't launch (black screen), I opened task manager (Ctrl-Shift-Esc) Task Manager > Run new task: `C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`
> 
> Once the "Properties" window appeared, I clicked "Restart File Explorer (*)" in the bottom left.
> 
> At this point explorer.exe launched successfully for the first time and I got a toast notification stating the following: "Successfully downloaded symbols for OS build 10.0.22521.1848" From there I rebooted the system and everything is working normally now.
> 
> I'll attach my exported settings from my two machines in case that data is useful. [explorerpatcher-settings.zip](https://github.com/valinet/ExplorerPatcher/files/11842210/explorerpatcher-settings.zip)
> 
> Is ExplorerPatcher unable to download symbols automatically when explorer.exe doesn't launch? I genuinely don't know the answer to that because my computer installed the windows update while offline (so the downloading the symbols would have failed on the first boot anyways). If it is unable to download symbols that is definitely an issue since it seems to me like they were a prerequisite to get my explorer.exe working.

I think this is the solution.
What's more, after "Properties" window appeared, we can enable console in "Advanced" and then Restart File Explorer. It turns out that it was forced to download symbols for OS.
Remember to disable it after download completed.

**Comment by pyrates999** [comment]
> > I was able to completely recover my environment in a much more elegant way than uninstalling the program or uninstalling any updates. Here was my process.
> > Once I was logged in but explorer.exe wouldn't launch (black screen), I opened task manager (Ctrl-Shift-Esc) Task Manager > Run new task: `C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`
> > Once the "Properties" window appeared, I clicked "Restart File Explorer (*)" in the bottom left.
> > At this point explorer.exe launched successfully for the first time and I got a toast notification stating the following: "Successfully downloaded symbols for OS build 10.0.22521.1848" From there I rebooted the system and everything is working normally now.
> > I'll attach my exported settings from my two machines in case that data is useful. [explorerpatcher-settings.zip](https://github.com/valinet/ExplorerPatcher/files/11842210/explorerpatcher-settings.zip)
> > Is ExplorerPatcher unable to download symbols automatically when explorer.exe doesn't launch? I genuinely don't know the answer to that because my computer installed the windows update while offline (so the downloading the symbols would have failed on the first boot anyways). If it is unable to download symbols that is definitely an issue since it seems to me like they were a prerequisite to get my explorer.exe working.
> 
> I think this is the solution. What's more, after "Properties" window appeared, we can enable console in "Advanced" and then Restart File Explorer. It turns out that it was forced to download symbols for OS. Remember to disable it after download completed.

Never disable downloading of symbols for the OS.  They are needed by explorer patcher.  Unless you are a developer, you should not be disabling that.

**Comment by qheartq616** [comment]
> > > I was able to completely recover my environment in a much more elegant way than uninstalling the program or uninstalling any updates. Here was my process.
> > > Once I was logged in but explorer.exe wouldn't launch (black screen), I opened task manager (Ctrl-Shift-Esc) Task Manager > Run new task: `C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`
> > > Once the "Properties" window appeared, I clicked "Restart File Explorer (*)" in the bottom left.
> > > At this point explorer.exe launched successfully for the first time and I got a toast notification stating the following: "Successfully downloaded symbols for OS build 10.0.22521.1848" From there I rebooted the system and everything is working normally now.
> > > I'll attach my exported settings from my two machines in case that data is useful. [explorerpatcher-settings.zip](https://github.com/valinet/ExplorerPatcher/files/11842210/explorerpatcher-settings.zip)
> > > Is ExplorerPatcher unable to download symbols automatically when explorer.exe doesn't launch? I genuinely don't know the answer to that because my computer installed the windows update while offline (so the downloading the symbols would have failed on the first boot anyways). If it is unable to download symbols that is definitely an issue since it seems to me like they were a prerequisite to get my explorer.exe working.
> > 
> > 
> > I think this is the solution. What's more, after "Properties" window appeared, we can enable console in "Advanced" and then Restart File Explorer. It turns out that it was forced to download symbols for OS. Remember to disable it after download completed.
> 
> Never disable downloading of symbols for the OS. They are needed by explorer patcher. Unless you are a developer, you should not be disabling that.

disable console in "Advanced"

**Comment by pyrates999** [comment]
> > > > I was able to completely recover my environment in a much more elegant way than uninstalling the program or uninstalling any updates. Here was my process.
> > > > Once I was logged in but explorer.exe wouldn't launch (black screen), I opened task manager (Ctrl-Shift-Esc) Task Manager > Run new task: `C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`
> > > > Once the "Properties" window appeared, I clicked "Restart File Explorer (*)" in the bottom left.
> > > > At this point explorer.exe launched successfully for the first time and I got a toast notification stating the following: "Successfully downloaded symbols for OS build 10.0.22521.1848" From there I rebooted the system and everything is working normally now.
> > > > I'll attach my exported settings from my two machines in case that data is useful. [explorerpatcher-settings.zip](https://github.com/valinet/ExplorerPatcher/files/11842210/explorerpatcher-settings.zip)
> > > > Is ExplorerPatcher unable to download symbols automatically when explorer.exe doesn't launch? I genuinely don't know the answer to that because my computer installed the windows update while offline (so the downloading the symbols would have failed on the first boot anyways). If it is unable to download symbols that is definitely an issue since it seems to me like they were a prerequisite to get my explorer.exe working.
> > > 
> > > 
> > > I think this is the solution. What's more, after "Properties" window appeared, we can enable console in "Advanced" and then Restart File Explorer. It turns out that it was forced to download symbols for OS. Remember to disable it after download completed.
> > 
> > 
> > Never disable downloading of symbols for the OS. They are needed by explorer patcher. Unless you are a developer, you should not be disabling that.
> 
> disable console in "Advanced"

ah my mistake.  I thought you meant to disable download symbols.

**Comment by voldemarz** [comment]
I had this black screen issue after the update on 3 different machines. On all of them I started the Task Manager with Ctrl+Shift+Esc and from there a new explorer taks. After that had no issues un subsequent reboots.

Two machines use Nvidia GPUs (4090 and P4000), the third is a laptop with Integrated Intel Xe graphics.
