### ISSUE TITLE
Explorer Crash Loop

### ISSUE THREAD

**Issue by dirtybrie** [valinet/ExplorerPatcher#1552]
This program caused my computer to do a explorer crash loop. Meaning my whole screen kept blinking over and over. I couldnt access anything cause each each time it blinked it prevented me from typing anything in on task manager. I had to go into safe mode with cmd and use the control panel to uninstall it. Once i did everything went back to normal.
The new windows updates and this program combined will do that. Do not download this. Just revert back to windows 10 if your taskbar is that much of an issue.
If your experiencing the same issue do as I did go into safe mode with just cmd. Open task manager, click on run new task. Type in control panel. Go to programs and uninstall explorer patcher and it will stop.

I will add it worked perfectly up untill that point. (Had it for 6 mo.)
Yesterday morning I logged in and this started happening.
The developer has done a great job but it really is never a good idea to download something that manipulates OS.

**Comment by pyrates999** [comment]
Please post your windows version, build (you can find this by running winver) and explorer patcher version you had installed.

**Comment by dirtybrie** [comment]
I dont need to use winver its in settings. 
The newest one June 13th OS Build 22621.1848.
As I said I downloaded ExplorerPatcher 6 months ago. So whatever version it was in january.

**Comment by pyrates999** [comment]
Please run winver and either post the build number from it or post a screen shot.
And please post a screen shot of the version of explorer patcher that you got installed.

**Comment by dirtybrie** [comment]
I gave what you needed bro.

**Comment by pyrates999** [comment]
Missing explorer patcher version that you installed.

**Comment by erspark2002** [comment]
I'm getting this as well. Started happening after the following Windows Updates:

**3 Quality Updates**
2023-06 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5027231)
Successfully installed on Mon 19/06/2023

2023-06 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for (KB5027119)
Successfully installed on Mon 19/06/2023

2023-06 .NET 6.0.18 Security Update for x64 Client 0<85027797)
Successfully installed on Mon 19/06/2023

I reverted the Windows updates as I didn't know what was going on.
Unfortunately I updated ExplorerPatcher before capturing the previous version.

I havent reinstalled the Windows updates yet.
Is there an error log on my system somewhere?

**Comment by pyrates999** [comment]
> I'm getting this as well. Started happening after the following Windows Updates:
> 
> **3 Quality Updates** 2023-06 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5027231) Successfully installed on Mon 19/06/2023
> 
> 2023-06 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for (KB5027119) Successfully installed on Mon 19/06/2023
> 
> 2023-06 .NET 6.0.18 Security Update for x64 Client 0<85027797) Successfully installed on Mon 19/06/2023
> 
> I reverted the Windows updates as I didn't know what was going on. Unfortunately I updated ExplorerPatcher before capturing the previous version.
> 
> I havent reinstalled the Windows updates yet. Is there an error log on my system somewhere?
> 
> If it helps, the file ExplorerPatcher.IA-32.prev is 151,040 bytes in size, timestamp: 27/1/2023. and ep_setup.prev is 777,728 bytes.

I suggest you post in a new discussion as the person who opened this one isn't willing to do any troubleshooting.

**Comment by erspark2002** [comment]
Microsoft Windows
Version 22H2 (0S Build 22621.1265)
@ Microsoft Corporation. All rights reserved.

**Comment by caibissmix** [comment]
[call command line from Task manager.pdf](https://github.com/valinet/ExplorerPatcher/files/11803185/call.command.line.from.Task.manager.pdf)

**Comment by erspark2002** [comment]
A lot of people having this issue will have no idea that it is ExplorerPatcher causing this problem. It took me 6 months to work it out, after pulling out a lot of hair. 

**Uninstall**
Task Manager > Run New Task
cmd
Then paste in the following and run
cd C:\Program Files\ExplorerPatcher
ep_setup.exe /uninstall

Is there a log file anywhere?

**Comment by erspark2002** [comment]
I don't know if there's any useful info here, but this is the dump from EventViewer when explorer.exe crashes.

```
- System 
  - Provider 
   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
   EventID 1000 
    Version 0 
    Level 2 
    Task 100 
    Opcode 0 
    Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2023-06-19T01:27:48.1583521Z 
 
   EventRecordID 57438 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  18100 
   [ ThreadID]  18104 
 
   Channel Application 
 
   Computer xxxxxxx
 
  - Security 

   [ UserID]  S-1-5-21-375856860-3624745720-4172748489-1001 
 

- EventData 

  AppName Explorer.EXE 
  AppVersion 10.0.22621.1778 
  AppTimeStamp 38884ebd 
  ModuleName windowsudk.shellcommon.dll 
  ModuleVersion 10.0.22621.1778 
  ModuleTimeStamp 99a8264b 
  ExceptionCode c0000005 
  FaultingOffset 0000000000262ad0 
  ProcessId 0x3fd0 
  ProcessCreationTime 0x1d9a24d39c3710e 
  AppPath C:\WINDOWS\Explorer.EXE 
  ModulePath C:\WINDOWS\system32\windowsudk.shellcommon.dll 
  IntegratorReportId 81d99c35-0d58-44c0-bd85-78c6108928f9 
  PackageFullName  
  PackageRelativeAppId  
```

**Comment by erspark2002** [comment]
C:\Users\<user>\AppData\Roaming\ExplorerPatcher
There is no log file here. Is it possible to add one to help with debugging?

**Comment by pyrates999** [comment]
That log is generated by explorer.exe crashing, so no it would not be saved in C:\Users<user>\AppData\Roaming\ExplorerPatcher.

All crashes are saved in windows event viewer in windows logs -> application as a log entry.

**Comment by mnott** [comment]
Same here. Explorer cycles crashing. Version 22H2 (OS Build 22621. 1848). ep_setup.exe done from an administrative command line.

**Comment by mirari** [comment]
Click `Browse` to find `ep_setup.exe` and rename it to `ep_uninstall.exe` then run it is also the solution to uninstall ExplorerPatcher.

**Comment by TreehouseFalcon** [comment]
Can verify that update KB5023706, build 22621.1413 had the same behavior. There's more people reporting this issue on the Microsoft forums. I've redirected them to this issue.

**Comment by delapazruiz** [comment]
I also had this issue. Fortunately, I had my browser opened.

I went to file:///C:/Users/myusername/Downloads/. 
From here, I got access to the ep_setup.exe file,
I right-clicked on the file and saved it as ep_uninstall.exe. 
After uninstalling it, my computer works well.

**Comment by Localcrack** [comment]
![20230712_135203](https://github.com/valinet/ExplorerPatcher/assets/139331483/31c89f74-a0f2-4b3f-b7d7-f31ca6ced74a)
ExplorerPatcher works fine in normal mode but in safe mode it continuously crashes and stuck in loop.
Is there any solution ?

**Comment by Localcrack** [comment]
Is it possible to disable ExplorerPatcher in safe mode ?

**Comment by hkpD** [comment]
> Titus app

That's funny, that's exactly the same dumb situation that I am in. 

I'm going to check out this app.

**Comment by TheAloyz** [comment]
> A lot of people having this issue will have no idea that it is ExplorerPatcher causing this problem. It took me 6 months to work it out, after pulling out a lot of hair.
> 
> **Uninstall** Task Manager > Run New Task cmd Then paste in the following and run
> 
> ```
> cd C:\Program Files\ExplorerPatcher
> ep_setup.exe /uninstall
> ```
> 
> Is there a log file anywhere?

GREAT THANKS mate!!! You saved my life (and probably a bit more...)!!!

Regards

**Comment by pyrates999** [comment]
This needs to be closed as the original poster is no longer responding.

**Comment by koendebock** [comment]
> Solution to get rid of the blinking screen:
> 
> ExplorerPatcher Version: 22621.1555.55.1 Windows 11, Version 22H2 (Build 22621.1848) The Problem occured after KB5027119 was installed via windows update. My solution to get rid of the blinking screen: Uninstall ExploterPatcher But once the screen is blinking, it is not possible to call Windows control panel to uninstall apps. It was also not possible to uninstall ExplorerPatcher when using the command line (cmd) in Windows Recovery Environment (winRE). There I first changed from drive X: to dricve C: . Then I changed to directory where the file ep_setup.exe was located. Now I used the command .\ep_setup.exe /uninstall - but nothing happened.
> 
> At the end I found the following solution to uninstall ExplorerPatcher:
> 
> > Start Windows (in normal mode) until I get the blinking screen again.
> > Press CTRL + ALT + DEL and chose TaskManager. In Taskmanager ther is a button to call the command line (CMD).
> > At command line I succeeded to uninstall Explorer Pathcher using the same command as mentioned above:
> > .\ep_setup.exe /uninstall
> 
> Now I can at least work with Windows 11 again - although without the Windows10 taskbar
> 
> ![call command line from Task manager](https://user-images.githubusercontent.com/137197104/247180487-bcd57ff3-ba72-4852-a356-df03531a351f.jpg)

Thank you @caibissmix!!!

So glad I found this discussion. Stay away from ExplorerPatcher!
