### ISSUE TITLE
explorer patcher crash after every windows update

### ISSUE THREAD

**Issue by frankyblaye** [valinet/ExplorerPatcher#1556]
Good morning,
Preview of Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5026446) and Updates for Windows (KB2693643)(KB5026446) and earlier, each time after installing these updates, at the time opening the windows desktop there is a total blockage and a black or white screen, including in safe mode.
It is therefore necessary, each time, to uninstall the update then to uninstall explorer patcher to finally reinstall the update.
Finally as soon as there is a new version of explorer patcher, it is installed and windows works perfectly.
Seems like every windows update blocks explorer patcher.
Franc

**Comment by pyrates999** [comment]
Preview updates and insider builds are not supported due to no symbols being available to download: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by DrMartyG** [comment]
Yes, every Windows 11 update is making Explorer Patcher crash

**Comment by Kijan** [comment]
after the last update i get black screen on startup. i can start the task manager and uninstall explorer patcher and then all is ok. but as soon as i install it again all goes black again. 
so with the newest not preview and not inside build i cant use it :(

Edition	Windows 11 Home
Version	22H2
Installiert am	‎19.‎10.‎2022
Betriebssystembuild	22621.1848
Leistung	Windows Feature Experience Pack 1000.22642.1000.0

and newest Download of Explorer Patcher

**Comment by frankyblaye** [comment]
As I tried to say, you have to wait each time for a new version of explorer patcher so that there is no longer any blockage.
I wonder if Microsoft does not block this application with each windows update

**Comment by frankyblaye** [comment]
my issue is not closed

**Comment by pyrates999** [comment]
> my issue is not closed

Uninstall any preview updates and never install any preview updates if you want to use explorer patcher.

**Comment by Kijan** [comment]
but i dont think i have a preview version, do I? i postet my version and updates. but i dont clicked any preview and i am not in the insider program. where should i opt out of preview? i cant find any words about preview. it seems that were normal updates

**Comment by pyrates999** [comment]
Uninstall this preview update: https://support.microsoft.com/en-us/topic/may-24-2023-kb5026446-os-build-22621-1778-preview-3c547100-7a73-4ae6-bb7d-ebd02e87dc04

And do not install any updates that are labeled as preview in the settings app.

**Comment by Kijan** [comment]
but this was the question. i don't know what a preview version is and what not. And where i can disable the auto installation of those. i did not manually installed the preview update and in my system there is no word that this specific update is an preview update. i can see it on the website but you don't want me to check the website after each update, if this is an preview, do you?

**Comment by Kijan** [comment]
So i did what you said. Checked winver.

![grafik](https://github.com/valinet/ExplorerPatcher/assets/2981692/64a76159-b93c-4809-b910-7818b2189f1d)

This is the version. This is not labeled as Preview.

**Comment by exsersewo** [comment]
Can also report blank screen after logging in with KB5027231 on W11Pro. 

Had to uninstall to get explorer to work.

[KB5027231](https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=eac58b58-fb7d-4cd4-a78a-a39f87e0f232) isn't a preview update with it not being marked as a "Cumulative Update Preview" on WUC. 
Like [KB5026446](https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=ec3769c8-2cd5-4e89-a0a3-6e7830c38f6f) for example.

**Comment by exsersewo** [comment]
Reinstalling "fixed" it. Here's the old reg, and the new reg

[ExplorerPatcherReg.zip](https://github.com/valinet/ExplorerPatcher/files/11868444/ExplorerPatcherReg.zip)

**Comment by Kijan** [comment]
yeah same, after deleting the registry entry and installing all is fine now.

[explorerPatcherOld.zip](https://github.com/valinet/ExplorerPatcher/files/11869358/explorerPatcherOld.zip)

**Comment by pyrates999** [comment]
Ok, now reapply the settings you had in explorer patcher and see if the crash happens again.  If it does not, export the settings in the registry and compare against the ones you had before.

**Comment by pyrates999** [comment]
There's actually quite a number of differences:

- left is old
- right is new

**Comment by joelnedev** [comment]
Hey, I'm having a similar issue where every 2 months windows goes black besides my lock screen. When this happens, I can use ctrl+shift+esc to get into task manager and unsuccessfully try to restart explorer or run windows terminal, but no other apps will open. A week or two ago was the 3rd time since December I've had to reset windows 11 :/ 

Do we have any sort of idea about what *specifically* could be causing this? I might have had Win11 Preview before that first time I was forced to reset, but I know since then I've never had any sort of preview. 

Currently, I'm on Windows 11 22H2 (22621.1848) and am afraid to update. Is it safe to install ExplorerPatcher currently, and is there a recent build I can upgrade to that would be safe to install EP on?

**Comment by ffuser1** [comment]
I'm in the same boat. I disabled windows updates but today I got notified that something just got installed. I don't want to have to be in a situation where I have to use system restore to get me out of exactly what you're describing. If windows updates and I am stuck, can one uninstall explorerpatcher from task manager / command prompt? I understand the symbols situation and am not complaining. This software is great and needed - I just need to be able to get back into windows and don't want to go back to restore points etc.

**Comment by exsersewo** [comment]
> can one uninstall explorerpatcher from task manager / command prompt?

If you still have the installer you can run `ep_setup.exe/uninstall` from cams to uninstall it

**Comment by frankyblaye** [comment]
Good morning,
I applied what pyrate999, exsersevo and kijan told me about explorerpatcherreg.zip and it works.
Thank you so much.
Franc

**Comment by frankyblaye** [comment]
Good morning,
I applied what pyrate999, exsersevo and kijan told me about explorerpatcherreg.zip and it works.
Thank you so much.
Franc

**Comment by erspark2002** [comment]
An alternative option if you just want to be able to drag to reorder subgroup icons on the taskbar is to install Windhawk.
https://windhawk.net/
Add plugin: Taskbar Thumbnail Reorder
- Click Details, then install.
Works out of the box.

I am running:
Edition	Windows 11 Pro
Version	22H2
Installed on	Thu 17/11/2022
OS build	22621.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

Hotfix(s): 5 Hotfix(s) Installed.
[01]: KB5034467
[02]: KB5012170
[03]: KB5034765
[04]: KB5032393
[05]: KB5034225
