### ISSUE TITLE
Weather Widget Reports No Internet Access

### ISSUE THREAD

**Issue by EscalatorMan** [valinet/ExplorerPatcher#1560]
Obviously I do have internet access as I am creating this post. I have restarted file explorer, uninstalled then reinstalled, turned off/on the weather widget in WIndows 11 settings, and still I am left with the blank weather icon in my task bar that says "no internet access" when I hover my mouse over it.

Also no updates of any kind were installed between yesterday (when it was working) and this morning. The only thing I did was restart my xps.

**Comment by cjahn50** [comment]
Not seeing the no internet access message, but the weather widget is not working. The is Version 22621.1555.55.1

**Comment by gtdurham** [comment]
I'm getting the same "no internet access" message. I too haven't done any updates to my system either.

**Comment by cjahn50** [comment]
Just checked it for grins and it is working now/again. And there has been no updates done since Wednesday, 6/14 and it worked after that, until this morning.

**Comment by gtdurham** [comment]
That's really wierd. Just checked it again and it working again.

**Comment by EscalatorMan** [comment]
Yup it's working again.

**Comment by EscalatorMan** [comment]
Closing this out
