### ISSUE TITLE
star menu problem - search not working

### ISSUE THREAD

**Issue by gabrielgranado** [valinet/ExplorerPatcher#1566]
when i open the star menu, i cannot search for anything. I cannot click on the search box. If i type anything, instead of start the search it navigates between the icons.

**Comment by andrew-polk** [comment]
Same here. Started happening late last week.
This is a blocker for using this software.

**Comment by pyrates999** [comment]
Please post your windows version by running winver and the version of explorer patcher you have installed.

Also check that symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by andrew-polk** [comment]
Windows: 22H2 Build 22621.1848
ExplorerPatcher: 22621.1555.55.1

console reports, "Loaded symbols"
Win-X works.

**Comment by FilipeNGO** [comment]
Me too

**Comment by VarunAgw** [comment]
Happens to me too sometime. Restarting windows explorer fixes it usually

**Comment by DGodding-603** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/137179913/1b9d5ee3-451b-4161-b2cf-ba19c436484a)
![image](https://github.com/valinet/ExplorerPatcher/assets/137179913/38af4798-ef07-4ade-bef9-b832383d58bd)
Same promlem here.

**Comment by JamesJackson123** [comment]
Same issue here, completely unable to use the search function. On the latest version of Windows & ExplorerPatcher

**Comment by andrew-polk** [comment]
Uninstall / restart / reinstall seems to have resolved it for me.

**Comment by pyrates999** [comment]
You could try a pre-release of explorer patcher.  Check the release notes to see if it mentions fixes for search.

**Comment by gabrielgranado** [comment]
> Uninstall / restart / reinstall seems to have resolved it for me.

that solved the issue for me too.
