### ISSUE TITLE
network flyout toggles non functioning

### ISSUE THREAD

**Issue by ZeldrexK0DE** [valinet/ExplorerPatcher#1574]
![image](https://github.com/valinet/ExplorerPatcher/assets/83987610/24128881-5d12-49c8-beb1-37749fcdce1a)

Idk, i reinstalled, reset settings and also just came from an update now on 22621.1848

**Comment by ZeldrexK0DE** [comment]
Heres the console windows log
`Launching : "C:\WINDOWS\system32\rundll32.exe" "C:\WINDOWS\dxgi.dll",ZZGUI
funchook create 1
Running on Windows 11, OS Build 10.0.22621.1848.
Loaded symbols
Setup ntdll functions done
Setup user32 functions done
Patched taskbar transparency in newer OS builds
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
Progman: 262676
Progman hook: 5571919
[Positioning] Added settings for monitor 0000000000010001 : 1
[Positioning] Added settings for monitor 0000000000010003 : 1
>>> Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
0 0
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[sws] Wallpaper RECT 0 0 3840 1080
[sws] Refreshing theme: 0
[sws] Refreshing theme: 0
[sws] Refreshing theme: 0






`

**Comment by Vipin2003** [comment]
Its just a bug. You can simply fix it by renaming **dxgi.dll** in **C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\** to anything like **dxgi.dll0**

**Comment by ZeldrexK0DE** [comment]
> Its just a bug. You can simply fix it by renaming **dxgi.dll** in *_C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy*_ to anything like **dxgi.dll0**
ah it recently fixed I think after I did an SFC scan, Thanks though
