### ISSUE TITLE
Microsoft sore app fail to appear in start menu of explorerpatcher window 10 style.

### ISSUE THREAD

**Issue by Melktad** [valinet/ExplorerPatcher#1587]
Microsoft store and app from Microsoft store are not appearing in start menu and cannot pinned to window 10.

**Comment by pyrates999** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Vipin2003** [comment]
Full solution : 

https://github.com/valinet/ExplorerPatcher/issues/1534#issuecomment-
1601017536

**Comment by Poopooracoocoo** [comment]
Closing as duplicate of #1108
