### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by pjotrekdev** [valinet/ExplorerPatcher#1588]
![image](https://github.com/valinet/ExplorerPatcher/assets/81621168/2525ad3f-fb2f-4d7d-a201-f3a96e57a057)
is there any way to remove this menu and go back to windows 11's taskbar context menu? i am using windows 11 taskbar in explorer patcher with no changes and a windows 10 start menu.

**Comment by Vipin2003** [comment]
There is a option already added to EP to disable this. Just check for "do not change context menu" option in settings.

**Comment by pjotrekdev** [comment]
> There is a option already added to EP to disable this. Just check for "do not change context menu" option in settings.

in what category? i cannot find it

**Comment by Vipin2003** [comment]
I'm currently not on my lapi.. so i can't tell u exact. But check it in others or advanced tab.

**Comment by Vipin2003** [comment]
![2023-06-25_18h26_39](https://github.com/valinet/ExplorerPatcher/assets/93650504/a39094a8-a9c3-4b95-a87f-86740745ccd2)

**Comment by pjotrekdev** [comment]
thanks a lot

**Comment by pyrates999** [comment]
The option "do not change the taskbar context menu" is not documented here:

https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings
