### ISSUE TITLE
Fix for "UWP Apps" not showing in Windows 10 Start Menu (Win32 Dll's used)

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#1591]
@valinet  If you can pin this, then please pin this Issue. Give reactions if you like it guys.

Till @valinet is busy, there is a fix for UWP apps which are not shown in Win10 Start. I've seen that people are creating issue regarding this again and again. And @pyrates999 (and me too)  also get frustrated writing "#1108" again and again.
So, I'm writing the full fix with steps. I think that it will prevent #1108 issues occurring again and again. Here are the steps:
1. Go to system32 location (easy navigate by typing it in address bar).
2. Copy two files : **AppResolver.dll** and **StartTileData.dll**
3. Navigate to this location : **C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy** . (Just copy the location and paste in address bar).
4. Rename already present **AppResolverLegacy.dll** and **StartTileData.dll** and change .dll to .dll0
5. Now rename copied files to the above names i.e. add **Legacy** in their names.
6. Restart the File Explorer.

Only bug is that "Pin to Start" and "Unpin to Start" won't work. Here is the alternative to these also :
1. **Pinning an App** : Just Drag and Drop the app to the Tile area.
2. **Unpinning an App** : Just move the app tile to new group and R-Click on the naming area. Just select "Unpin group from Start".

Tutorial for Pinning and Unpinning:
https://github.com/valinet/ExplorerPatcher/assets/93650504/c0fde3ce-6d1e-48da-be99-8b61074fd21d

Don't ask for more tile options like wide, large, etc. It will be there only for some apps like Notepad, Get Started, etc. You can check for this.

The only work remaining for valinet is to fix the 'pin to start' option.

**Comment by pyrates999** [comment]
I've got the tab open on https://github.com/valinet/ExplorerPatcher/issues/1108 since this is happening quite a bit.

**Comment by Vipin2003** [comment]
Not broken fir me bro... I've already tested

**Comment by pyrates999** [comment]
Try rebooting to see if that is required.

**Comment by PeteM92** [comment]
This procedure worked fine in Win11 **Home**, but I was not succesful in Win11 **PRO**.
In Win11 PRO Start Menu did not open at all after applying this Procedure, even not after reboot.

**Comment by Vipin2003** [comment]
> This procedure worked fine in Win11 **Home**, but I was not succesful in Win11 **PRO**. In Win11 PRO Start Menu did not open at all after applying this Procedure, even not after reboot.

There is no issue as I'm using it on Pro and education..

**Comment by PeteM92** [comment]
I unsuccessfully tried it a couple of times ... (Windows 11 22H2 build 22621.1848, ExplorerPatcher no updates available)
Is there anything else to test?

**Comment by nljxlove** [comment]
期待更新

**Comment by Vipin2003** [comment]
> 

Me too.

**Comment by djcholapin** [comment]
I'm not very keen into messing up with win32 DLLs. A future windows update could mess the whole thing up again, and if that happens after months / years, you can loose sight of the DLL that has been removed. I feel like a toggle in EP would be more appropriate.

**Comment by Vipin2003** [comment]
> I'm not very keen into messing up with win32 DLLs. A future windows update could mess the whole thing up again, and if that happens after months / years, you can loose sight of the DLL that has been removed. I feel like a toggle in EP would be more appropriate.

But I think that it is quite better than having nothing. Just waiting for valinet to add a toggle for this.

**Comment by ggets** [comment]
Just dropping a report for 22621.1992 this workaround still works.

**Comment by mdio33** [comment]
Just notice this topic and I'm happy to see that I can pin uwp apps again... but how can I unpin them?

**Comment by Vipin2003** [comment]
https://github.com/valinet/ExplorerPatcher/assets/93650504/c0fde3ce-6d1e-48da-be99-8b61074fd21d

**Comment by Vipin2003** [comment]
> Just notice this topic and I'm happy to see that I can pin uwp apps again... but how can I unpin them?

I've updated the post with tutorial for pinning and unpinning..Check it once. I'm sure it will help you.

**Comment by mdio33** [comment]
> > Just notice this topic and I'm happy to see that I can pin uwp apps again... but how can I unpin them?
> 
> I've updated the post with tutorial for pinning and unpinning..Check it once. I'm sure it will help you.
Nice workaround, unpin the group instead of the app..

thank you very much.  ;)

**Comment by kenyeoh58** [comment]
I can confirm that this works as advertised on Windows 11 Pro Version 22H2 Build 22621.1992
Thank you so very much.

**Comment by mdio33** [comment]
> I can confirm that this works as advertised on Windows 11 Pro Version 22H2 Build 22621.1992 Thank you so very much.

I cam confirm it works on Windows 11 Pro Version 23H2 Build 22631.2045.

**Comment by pyrates999** [comment]
> > I can confirm that this works as advertised on Windows 11 Pro Version 22H2 Build 22621.1992 Thank you so very much.
> 
> I cam confirm it works on Windows 11 Pro Version 23H2 Build 22631.2045.

Preview updates and insider builds are not supported by explorer patcher due to symbols not being available to download: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Vipin2003** [comment]
> > I can confirm that this works as advertised on Windows 11 Pro Version 22H2 Build 22621.1992 Thank you so very much.
> 
> I cam confirm it works on Windows 11 Pro Version 23H2 Build 22631.2045.



> > > I can confirm that this works as advertised on Windows 11 Pro Version 22H2 Build 22621.1992 Thank you so very much.
> > 
> > 
> > I cam confirm it works on Windows 11 Pro Version 23H2 Build 22631.2045.
> 
> Preview updates and insider builds are not supported by explorer patcher due to symbols not being available to download: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

I know as I posted it after all checks on every build..(even on canary)
Just waiting for @valinet to add this as toggle in settings...Also, I've made a PR for this too.

**Comment by pyrates999** [comment]
> > > I can confirm that this works as advertised on Windows 11 Pro Version 22H2 Build 22621.1992 Thank you so very much.
> > 
> > 
> > I cam confirm it works on Windows 11 Pro Version 23H2 Build 22631.2045.
> 
> > > > I can confirm that this works as advertised on Windows 11 Pro Version 22H2 Build 22621.1992 Thank you so very much.
> > > 
> > > 
> > > I cam confirm it works on Windows 11 Pro Version 23H2 Build 22631.2045.
> > 
> > 
> > Preview updates and insider builds are not supported by explorer patcher due to symbols not being available to download: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> I know as I posted it after all checks on every build..(even on canary) Just waiting for @valinet to add this as toggle in settings...Also, I've made a PR for this too. Let valinet to finish his imp. work. That's why, I made him to pin this fix.

Understood.
