### ISSUE TITLE
Win10 Start Menu Style Not working

### ISSUE THREAD

**Issue by EmilyMCjava** [valinet/ExplorerPatcher#1593]
I am using Windows 11 pro 22h2 and trying to use the win10  start menu style but if i press the `⊞ Win` key or press the window logo using the cursor it doesn't pop up it just put every window open on unfocus mode. Please help me i want Win10 start menu style the win11 sucks.
<img width="601" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/135965129/edb6374f-470d-46b1-a6cc-0ad7a2148eeb">

### _**PLEASE HELP ME**_

**Comment by Vipin2003** [comment]
Firstly share the build you are using. If using stable, try uninstalling it by iobit uninstaller (if you don't want to delete every EP files and registry manually). and reinstall it. after installing, wait for symbols to download or perform a restart. Then check if the issue persists.

**Comment by EmilyMCjava** [comment]
> Firstly share the build you are using. If using stable, try uninstalling it by iobit uninstaller (if you don't want to delete every EP files and registry manually). and reinstall it. after installing, wait for symbols to download or perform a restart. Then check if the issue persists.

<img width="337" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/135965129/001e3fb8-1272-446b-b1a3-732295f8d88f">

it works but when i type it goes to the win11 style anyway to change this?

**Comment by pyrates999** [comment]
Do the following:

1. uninstall explorer patcher
2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. Reapply the settings you had set

**Comment by EmilyMCjava** [comment]
> Do the following:
> 
> 1. uninstall explorer patcher
> 2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
> 3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
> 4. install explorer patcher
> 5. verify you get a notification that symbols have been downloaded
> 6. restart windows explorer using either the task manager or in the properties window of explorer patcher
> 7. Reapply the settings you had set

that doesnt work
<img width="481" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/135965129/32369208-73fb-47a3-a504-ca0c0b2a9138">
this 
<img width="587" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/135965129/e540b9b7-b112-42d9-87eb-b08706ed64c8">

**Comment by pyrates999** [comment]
Thank you for confirming this is happening.

**Comment by EmilyMCjava** [comment]
> Thank you for confirming this is happening.

then how to fix it or it hasnt been done as a feature cuz reinstalling it doesnt work...

**Comment by pyrates999** [comment]
It requires it to be implemented as a new feature.  Check the link I put for how to add a separate search bar in your taskbar as a work around.

**Comment by Amrsatrio** [comment]
With the latest EP, I do not observe this issue on builds 22000.2416, 22621.1, 22621.2134, 22621.2361, 22631.2338, and 23545.1000. Since newer versions than yours work fine, I will be closing this issue.
