### ISSUE TITLE
Windows 11 update crashing ExplorerPathcer

### ISSUE THREAD

**Issue by phpjunkie420** [valinet/ExplorerPatcher#1594]
Windows 11 update KB5027303 is causing ExplorerPatcher to crash.

**Comment by seansusmilch** [comment]
I believe I'm running into this too. When I log in my desktop is black but I can still see my cursor, launch task manager, run tasks, etc.

Restarting explorer in task manager did not solve the problem

**Comment by janseris** [comment]
Got the same. Just after today's update.

**Comment by pyrates999** [comment]
That's a preview update: https://blogs.windows.com/windows-insider/2023/06/20/releasing-windows-11-build-22621-1926-to-the-release-preview-channel/

Uninstall it and don't install preview updates because they do not supply symbols to download: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by just4t** [comment]
After upgrading to 22621.1928 (final) (aka KB5027303) symbols for that build are not being downloaded afterwards …
Then, tried to force them to be downloaded by enabling 'Advanced/Enable console' but symbols install fails, too !? 
► Your help to solve the issue would be very apreciated

Here the console log:

```funchook create 1
Running on Windows 11, OS Build 10.0.22621.1928.
Attempting to download symbol data; for now, the program may have limited functionality.
Setup ntdll functions done
Setup user32 functions done
Patched taskbar transparency in newer OS builds
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
Progman: 131500
Progman hook: 984115
0 0
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
[Updates] Starting daemon.
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for unknown OS version 10.0.22621.1928.
[Symbols] Downloading to "C:\Users\gamx\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\WINDOWS\system32\twinui.pcshell.dll" ("c723168734ed6540acb76138cff011d5")...
[Symbols] Reading symbols...
[Symbols] Windows 10 window switcher style is not available in this build.
[Symbols] Failure in reading symbols for "C:\WINDOWS\system32\twinui.pcshell.dll".
```

**Comment by gorillale** [comment]
I have make the win update, no black screen.
Now on the BT Symbol right Click will give ExplorerCrash. after 3 Times a white Windows is displayed.
Right Click on the START no more Work, same ExplorerCrash...
Deinstall of EP and reinstall will not help (administrator user).

Now i have a big problem.

**Comment by phpjunkie420** [comment]
Uninstall the update, and use the [Microsoft's Show or Hide Updates Troubleshooter](https://www.majorgeeks.com/files/details/microsoft_show_or_hide_updates_troubleshooter.html). This is a Microsoft tool that has been deprecated, so you won't find it on any of Microsoft's websites. Microsoft has added something new to the troubleshooter that is built into windows itself. This is the reason the tool is deprecated.

**Comment by pyrates999** [comment]
Preview updates and insider builds are not supported due to symbols not being available to download for them: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b

**Comment by gorillale** [comment]
Hey, thankyou for tips, it works. 
After update Symbols all ok.
regards

**Comment by Asphiii** [comment]
I confirm that KB5027231 is crashing the app

Steps:
1. Alt+ctrl+delete
2. In task manager run cmd
3. Type:
`wusa /uninstall /kb:5027231`
4. After uninstalling restart the PC

Hope it helps for ya

**Comment by pyrates999** [comment]
You can also try the following:

1. uninstall explorer patcher
2. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
3. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
