### ISSUE TITLE
Windows start button context menu mising

### ISSUE THREAD

**Issue by Fabikus** [valinet/ExplorerPatcher#1599]
No context menu is shown when right click on Windows start menu button

**Comment by Vipin2003** [comment]
Just wait for Symbols to be downloaded

**Comment by sergiopoverony** [comment]
Start menu cant work permanently. cant work Win button for call menu.

**Comment by serdarevica** [comment]
Same here.
Win 11 22631.1972
Windows Feature Experience Pack 1000.22658.1000.0

Tried all combinations - uninstall, install, reset to defaults... no work

**Comment by Fabikus** [comment]
After reboot it works :)

**Comment by sergiopoverony** [comment]
> After reboot it works :)

Version windows, build and etc please/

**Comment by sergiopoverony** [comment]
> More information on symbols: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

so...
[Symbols] Attempting to download symbols for unknown OS version 10.0.22621.1928.
[Symbols] Downloading to "C:\Users\SergioPoverony\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\WINDOWS\system32\twinui.pcshell.dll" ("c723168734ed6540acb76138cff011d5")...
[Symbols] Symbols for "C:\WINDOWS\system32\twinui.pcshell.dll" are not available - unable to download.
[Symbols] Please refer to "https://github.com/valinet/ExplorerPatcher/wiki/Symbols" for more information.

**Comment by pyrates999** [comment]
That's a preview update.  Uninstall it.

https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b
