### ISSUE TITLE
Explorer restart loop 

### ISSUE THREAD

**Issue by ThatBulgarian** [valinet/ExplorerPatcher#16]
hi, i tried installing this today and it installed the missing icons fine but the when it started to restart explorer to do its checks, it didnt stop. kept going for an hour. my windows version is 22000.176 if thats helpful

**Comment by valinet** [comment]
Hi

I don't really understand what happened. What "missing icons"? I can't possibly guess what happened for you based on your Windows version alone. I have the exact same version on which I do development, I tested on that and it works just fine. I am not a wizard. Have you thoughtfully read the README file?

Also, on 22000.176 only a single restart should happen. It shows a notification, downloads the symbols, extracts the info from them, shows a notification that it is done, Explorer restarts in a couple of seconds and then that's it. What "checks"?

Please post the `settings.ini` file that it generated here so I can see whether it stopped unexpectedly.

**Comment by ThatBulgarian** [comment]
Missing symbols sorry not icons

**Comment by valinet** [comment]
Okay, I got it. Again, please post the `settings.ini` file so I can see whether it really downloaded them fine.

**Comment by ThatBulgarian** [comment]
[explorer]
CTray::_HandleGlobalHotkey=6992
CTray::v_WndProc=62144
CTray::_FireDesktopSwitchIfReady=160304
CTray::Init=186208
OffsetOK=0
Dirty=0
OffsetStrat=48
Offset=995
[twinui.pcshell]
CImmersiveContextMenuOwnerDrawHelper::s_ContextMenuWndProc=2183030
CLauncherTipContextMenu::GetMenuItemsAsync=6072240
ImmersiveContextMenuHelper::ApplyOwnerDrawToMenu=6242504
ImmersiveContextMenuHelper::RemoveOwnerDrawFromMenu=6244560
CLauncherTipContextMenu::_ExecuteShutdownCommand=6131272
CLauncherTipContextMenu::_ExecuteCommand=6130436
CLauncherTipContextMenu::ShowLauncherTipContextMenu=6077440
winrt::Windows::Internal::Shell::implementation::MeetAndChatManager::OnMessage=313504
[twinui]
CImmersiveHotkeyNotification::_GetMonitorForHotkeyNotification=2411916
IsDesktopInputContext=43992
CImmersiveHotkeyNotification::OnMessage=410208
[stobject]
SysTrayWndProc=19808
HotPlugButtonClick=96336
[Windows.UI.FileExplorer]
ContextMenuPresenter::DoContextMenu=265520
[StartDocked]
StartDocked::LauncherFrame::ShowAllApps=1609404
StartDocked::LauncherFrame::OnVisibilityChanged=1601824
StartDocked::SystemListPolicyProvider::GetMaximumFrequentApps=15376
StartDocked::StartSizingFrame::StartSizingFrame=1444588
[Windows.UI.Xaml]
CJupiterWindow::StaticCoreWindowSubclassProc=2038048
[OS]
Build=10.0.22000.176

**Comment by valinet** [comment]
Which version of the DLL are you on? Right click the DLL, Properties, Details, File version.

**Comment by ThatBulgarian** [comment]
i think i was on 22449.1000.0.16. I've just tried clearing the folder where settings.ini was and used the latest version you uploaded 3 hours ago and that works!

**Comment by valinet** [comment]
Great, that's very good. In the future, as a general rule of thumb, make sure that you have taken care of the basics yourself, like resetting everything to 0 and retrying, making sure you're on the latest version, restarting the computer to install any pending updates/changes, disabling software that might be incompatible etc, just to make the life of the support 'personnel' easier. 'Personnel', heck, I'm a single guy trying to help as much as I can, although I am not necessarily mad, I'd appreciate if people would take care of the basics themselves before posting an 'issue' here. Although yeah, that gets overshadowed of the sheer joy that it indeed is not a bug and it just works fine.

Take care!
