### ISSUE TITLE
Explorer.exe crashing

### ISSUE THREAD

**Issue by SD308** [valinet/ExplorerPatcher#1601]
If I try to load explorer to see files, or transfer files, I will get the error: "runtime error explorer.exe r6030 crt not initialized". I am using the latest Windows 11 Pro, as well as the latest Explorer Patcher (since I tried to install it).

**Comment by pyrates999** [comment]
Please post your windows 11 build number.
Please post your version of explorer patcher.

**Comment by SD308** [comment]
22621.1848 for OS build
[22621.1555.55.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.1_a95a688) for explorer patcher.

**Comment by pyrates999** [comment]
Try the suggestion here: https://answers.microsoft.com/en-us/windows/forum/all/microsoft-visual-c-runtime-library-runtime-error/68df9f46-937b-4824-9887-41fe9a6de3f4

**Comment by SD308** [comment]
I did that. It works in Safe Mode, but as soon as I go out of it, it still crashes. Even with supposedly only Microsoft Services being activated on startup.

**Comment by SD308** [comment]
I solved the issue by resetting the pc. This caused all apps to get wiped, however.

**Comment by pyrates999** [comment]
Ok, looks like your windows install had errors then.

**Comment by SD308** [comment]
I suppose so. At least it should be working now.

**Comment by pyrates999** [comment]
> I suppose so. At least it should be working now.

You could also do a reinstall using the windows media installer by just mounting the iso and reinstalling from that.  Your apps would not be touched then.

**Comment by jmlambarri** [comment]
I've been experiencing the same issue for the last 10 months and in my case, it only happens in one of the accounts I have configured in my pc.

**Comment by pyrates999** [comment]
> I've been experiencing the same issue for the last 10 months and in my case, it only happens in one of the accounts I have configured in my pc. I've tried eeeeeeverything I've found in internet, but nothing works:
> 
> * reinstallation of all visual C++ runtimes
> * sfc /scannow
> * DISM.exe /Online /Cleanup-Image /RestoreHealth
> * in place windows 11 upgrade
> 
> There should be something that could be done instead of creating a new account and reconfiguring all the things I use or resetting the system...

Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by jmlambarri** [comment]
Thanks for the prompt response @pyrates999 
I will gather all the info you have asked for and I will post it here.

**Comment by pyrates999** [comment]
> Thanks for the prompt response @pyrates999 I will gather all the info you have asked for and I will post it here.

Please open up a new issue as this one has been closed.
