### ISSUE TITLE
Explorer Restart

### ISSUE THREAD

**Issue by Romz24** [valinet/ExplorerPatcher#1604]
I just received the Windows 11 Pro update. As soon as I installed it and restarted my computer, I can no longer open Settings. Whenever I try to open Settings, explorer.exe simply restarts. Additionally, the Start menu only opens on the second attempt.

ExplorerPatcher version: **22621.1555.55.1**
Windows build: **22621.1928**

**Comment by pyrates999** [comment]
That's a preview update: https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b

Uninstall it.

Symbols are not available for download on preview updates and insider builds: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
