### ISSUE TITLE
[BUG] Windows fall behind or over taskbar when resuming from display off, windows ignoring taskbar bounds. 

### ISSUE THREAD

**Issue by ossnorry** [valinet/ExplorerPatcher#1605]
As title, I propose adding a restart/delay option like the one introduced for login for sleep/monitor on+off events, or enabling the ability to bind such events being exposed to the user. 

Can be reproduced by simply letting your display go to sleep, happens around 25% of the time, may be related to display port hot plug and the deeper sleep functions.

**Comment by Amrsatrio** [comment]
Definitely related to DP deep sleep with multiple monitors. I experience no issues on my HDMI display, on almost all 22621 versions MS has ever released.
