### ISSUE TITLE
Using interactive window positioning (half screen etc) restarts explorer

### ISSUE THREAD

**Issue by janseris** [valinet/ExplorerPatcher#1607]
When a window is dragger to the side so that interactive window size feature is launched from Windows (e.g. so that the window occupies the left side of the screen), Windows explorer restarts.

https://github.com/valinet/ExplorerPatcher/assets/64279914/b07eea6e-b234-4068-b1f0-5dafcba09ffc

**Comment by pyrates999** [comment]
I don't see the crash here.

**Comment by janseris** [comment]
@pyrates999 please see the task bar. I don't know if it is explorer crashing directly to be honest because I'm not that much an expert, so I might be calling it wrong.

**Comment by pyrates999** [comment]
Open up Event Viewer.  Go to Windows Logs -> Application.  The crash should be logged in there.

**Comment by pyrates999** [comment]
Please post your full windows version that includes the build number.
Please post the version of explorer patcher you have installed.

**Comment by janseris** [comment]
Thanks for guiding.
My windows version is Windows 11 Home build 22621.1702

Log contains these 4 events for the "crash". I post them below from oldest to newest.
![image](https://github.com/valinet/ExplorerPatcher/assets/64279914/8c8e544e-1242-4beb-a2f5-73c5a4f87468)

Btw I now detected that the crash also happens everytime I close the Windows 10/11 Settings app.

Red error:

```
Faulting application name: Explorer.EXE, version: 10.0.22621.1635, time stamp: 0xa4159e29
Faulting module name: twinui.pcshell.dll, version: 10.0.22621.1635, time stamp: 0xe28885c2
Exception code: 0xc0000005
Fault offset: 0x000000000064b6a4
Faulting process id: 0x0x1F78
Faulting application start time: 0x0x1D9ABF426700EB6
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\WINDOWS\SYSTEM32\twinui.pcshell.dll
Report Id: afcfa2b0-615a-44fe-8b8a-8b70d1bb9670
Faulting package full name: 
Faulting package-relative application ID: 
```

Error above red (1001):

```
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Explorer.EXE
P2: 10.0.22621.1635
P3: a4159e29
P4: twinui.pcshell.dll
P5: 10.0.22621.1635
P6: e28885c2
P7: c0000005
P8: 000000000064b6a4
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4b759ee7-da81-44d2-855a-fcd7dbe69957.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2be3bd30-5ede-4bae-a09a-e4a1f3a49b23.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ff85a418-975c-4248-95c3-c76b135d18df.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.405d2683-6828-4c29-aaeb-b57ceaf547aa.tmp.txt
\\?\C:\Users\janse\AppData\Local\Temp\WER.4cb81c27-8b58-4dfe-a17f-aa3d25f3c9c1.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.28b063a2-c554-4f86-a317-02489d416d33.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Explorer.EXE_e7e7ed614d515ddb4f62f2a8923327eb265cbc6_086d8e7d_cab_e01f291b-9436-483c-bd69-2fbdef772d33

Analysis symbol: 
Rechecking for solution: 0
Report Id: afcfa2b0-615a-44fe-8b8a-8b70d1bb9670
Report Status: 4
Hashed bucket: 
```

Next (1002):

`The shell stopped unexpectedly and explorer.exe was restarted.`

Newest event(1001):

```
Fault bucket 2112331406591930521, type 4
Event Name: APPCRASH
Response: Není k dispozici. ("not available")
Cab Id: 0

Problem signature:
P1: Explorer.EXE
P2: 10.0.22621.1635
P3: a4159e29
P4: twinui.pcshell.dll
P5: 10.0.22621.1635
P6: e28885c2
P7: c0000005
P8: 000000000064b6a4
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4b759ee7-da81-44d2-855a-fcd7dbe69957.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2be3bd30-5ede-4bae-a09a-e4a1f3a49b23.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ff85a418-975c-4248-95c3-c76b135d18df.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.405d2683-6828-4c29-aaeb-b57ceaf547aa.tmp.txt
\\?\C:\Users\janse\AppData\Local\Temp\WER.4cb81c27-8b58-4dfe-a17f-aa3d25f3c9c1.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.28b063a2-c554-4f86-a317-02489d416d33.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Explorer.EXE_e7e7ed614d515ddb4f62f2a8923327eb265cbc6_086d8e7d_e01f291b-9436-483c-bd69-2fbdef772d33

Analysis symbol: 
Rechecking for solution: 0
Report Id: afcfa2b0-615a-44fe-8b8a-8b70d1bb9670
Report Status: 268435456
Hashed bucket: bc2308c0e05a75c6bd50823901d03099
Cab Guid: 0
```

The only file I could find from the event is `Report.wer` (attached as `Report.zip`) one from the folder `C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Explorer.EXE_e7e7ed614d515ddb4f62f2a8923327eb265cbc6_086d8e7d_e01f291b-9436-483c-bd69-2fbdef772d33`

[Report.zip](https://github.com/valinet/ExplorerPatcher/files/11925283/Report.zip)

**Comment by pyrates999** [comment]
Let's verify that explorer patcher is causing this or not.  Please uninstall explorer patcher and reboot.

Then try creating the crash again and let me know if explorer crashes or not.

**Comment by janseris** [comment]
I uninstalled ExplorerPatcher and it is no more happening.

**Comment by pyrates999** [comment]
Great.  Now let's try the following:

1. export this registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" and upload it to here
2. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. install explorer patcher
4. verify you get a notification that symbols have been downloaded
5. restart windows explorer using either the task manager or in the properties window of explorer patcher
6. Check if the crash is still happening.  Continue if not.
7. Reapply the settings you used in explorer patcher properties application
8. Check if the crash is still happening.

**Comment by Amrsatrio** [comment]
How's the issue going with the latest Windows general availability release and latest ExplorerPatcher? I observe no issues on 22621.1992, 2134, 2283, and 2361.
