### ISSUE TITLE
Trying to open Settings crashes ExplorerPatcher

### ISSUE THREAD

**Issue by Faulty-Windows** [valinet/ExplorerPatcher#1608]
One day, I got an update for the june 2023 update, and then I downloaded and installed it. Shortly after that, I got a major issue: Trying to open settings would crash. I could still do other things with other UWP apps. Not even from the control menu (the cog menu) still didn't work, it would crash. I don't even know what's the problem. Please help me. I miss the Windows 10 Taskbar.

**Comment by VergLsm** [comment]
Same bug. Can't open settings after I update my win11.

**Comment by mcfauzi** [comment]
yes its confirmed, after update my win 11 to build 22621.1928 crashed when open settings

**Comment by Vipin2003** [comment]
not for mine...it's working fine here

**Comment by pyrates999** [comment]
> yes its confirmed, after update my win 11 to build 22621.1928 crashed when open settings

That's a preview release: https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b

Uninstall it if you want to install explorer patcher: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by pyrates999** [comment]
> One day, I got an update for the june 2023 update, and then I downloaded and installed it. Shortly after that, I got a major issue: Trying to open settings would crash. I could still do other things with other UWP apps. Not even from the control menu (the cog menu) still didn't work, it would crash. I don't even know what's the problem. Please help me. I miss the Windows 10 Taskbar.

Please post windows version and build.
Please post explorer patcher version.

**Comment by MingHejin** [comment]
Dear friend, let me tell you how to uninstall it.
&nbsp;Please rename the installation program, "install", to uninstall. "
Which is renamed as ep_uninstall.exe I hope I can help you.




等待去年来临
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "valinet/ExplorerPatcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月2日(星期天) 下午5:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [valinet/ExplorerPatcher] Trying to open Settings crashes ExplorerPatcher (Issue #1608)





 
yes its confirmed, after update my win 11 to build 22621.1928 crashed when open settings
