### ISSUE TITLE
[BUG] Overlapping

### ISSUE THREAD

**Issue by michaelmuselik** [valinet/ExplorerPatcher#1611]
@valinet , please, what is the correct behavior of the window and taskbar? Should the taskbar overlap the window, or should the window overlap the taskbar? Ideally, the window should stop at the edge of the taskbar so that both elements are visible.
![2023-07-04_16h26_21](https://github.com/valinet/ExplorerPatcher/assets/73330785/952b9def-3e34-477b-806d-743089214a91)

**Comment by Vipin2003** [comment]
Noth the element should be visible

**Comment by michaelmuselik** [comment]
I think too.

**Comment by michaelmuselik** [comment]
please, is anyone else with the same problem?

**Comment by michaelmuselik** [comment]
Sorry, it was due to disabling aero snapping :-(.
