### ISSUE TITLE
"Never Combine" option for Taskbar doesn't apply to non-primary monitors

### ISSUE THREAD

**Issue by AMurderOfCrows** [valinet/ExplorerPatcher#1613]
Firs time trying out the "Never combine" setting as a suggestion from a co-worker, but i'm finding that the latest version (pulled tonight from this github) combined with Windows 11 22H2 is showing grouped icons on the secondary taskbar.

further, when moving an application window from the left side monitor to the center (main) monitor, the icons appear on the left side of the center taskbar's pinned items.

this secondary behavior isn't seen when you have the taskbar set to "always combine".

thoughts?

UPDATE:
second behavior is due to pinned icons. for whatever reason i expected the "pinned" items to move to the right when engaged, and i guess i never realized that wasn't how that worked.

Winver:
Windows 11
Version 22H2 (OS Build 22621.1848)

ExplorerPatcher Ver:
22621.1555.55.1

**Comment by AMurderOfCrows** [comment]
Winver:
Windows 11
Version 22H2 (OS Build 22621.1848)

ExplorerPatcher Ver:
22621.1555.55.1

**Comment by pyrates999** [comment]
Thank you.

**Comment by Vipin2003** [comment]
I think that EP needs an update. As I personally use beta with EP and the Win11 flyout overlap the Win10 taskbar which shows that EP is going to be outdated with the Stable soon. It was not there until moment 3 update in beta.

**Comment by pyrates999** [comment]
> I think that EP needs an update. As I personally use beta with EP and the Win11 flyout overlap the Win10 taskbar which shows that EP is going to be outdated with the Stable soon. It was not there until moment 3 update in beta.
> 
> **Now, pls don't advise me that EP is not recommended for beta and insiders. As I know this and I use it for canary too.**

Then you should know that EP can't be used with preview and insider builds because the symbols are not available for download.  It's a technical requirement and you can't ignore it.

**Comment by Amrsatrio** [comment]
Update to 67.1. Change the setting using the Settings app, and see if it works. 67.1+ no longer uses EP's own reg key for the taskbar combine setting.
