### ISSUE TITLE
Taskbar set to auto hide doesn't pop up when dragging mouse to bottom of screen. 

### ISSUE THREAD

**Issue by gnagga** [valinet/ExplorerPatcher#1614]

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by gnagga** [comment]
I've noticed it on two separate machines, both run newest EP Vesion 22621.1555.55.1 
My Desktop with 22H2  22621.1928 doesnt retract the taskbar down anymore once it slided up after touching the screen border. Only via pressing the windows key twice. 
My Laptop, also 22H2 newest build works fine, except when Edge is opened, touching the screen border doesnt slide up the taskbar. 
All very weird.

**Comment by pyrates999** [comment]
That's a preview release: https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b

Uninstall it if you want to install explorer patcher: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Amrsatrio** [comment]
This doesn't happen on the latest release builds of Win11. I will be closing this issue.
