### ISSUE TITLE
Suggestion: Remove the access key for the entry in Win+X menu

### ISSUE THREAD

**Issue by CrendKing** [valinet/ExplorerPatcher#162]
Sorry if this sounds rude. Please take no offense.

Currently you add a "Properties" in the Win+X menu. The "P" is the access key, so that user can press P key as shortcut. Because some people put their most frequently used apps in Win+X (with help of apps such as [Win+X Menu Editor](https://winaero.com/winx-menu-editor-for-windows-10-and-windows-8/)), the access keys are kinda already crowded. For example, I already have an app with "P" as shortcut.

Considering that people are unlikely to customize the patcher settings on daily basis, can you remove the access key?

**Comment by valinet** [comment]
I use that quite a lot, to be honest. So I will add an option then...

**Comment by valinet** [comment]
I test the app frequently… not something I particularly enjoy.
