### ISSUE TITLE
Explorer Patcher development was abandoned?

### ISSUE THREAD

**Issue by nestg** [valinet/ExplorerPatcher#1620]
Last version was published near 3 months ago, in every new Windows 11 Update Explorer Patcher fail more, i uninstall it weeks ago, now Windows 11 will be have some features in the taskbar of Explorer Patcher, features of Windows 10 taskbar, then i ask if this project was abandoned? thanks.

**Comment by TheLovinator1** [comment]
What version of Windows are you using? I on Version 22H2 (OS Build 22621.1848) and are using ExplorerPatcher 22621.1555.55.1 and it works perfectly for me.

**Comment by nestg** [comment]
I am using Windows 11 Pro 22H2 Build 22621.1928, every Windows update the problems are diferent, in one the start Menu return to the native Windows 11, other times scroll does not work above the tasskbar, other the windows change the focus ramdonly, well, now not import, i think that the important Windows 10 taskbar features like the non group tabs are coming to Windows 11, i use Explorer Patcher for a year and was a solution but not now with the problems and the no updates, thanks.

**Comment by pyrates999** [comment]
> I am using Windows 11 Pro 22H2 Build 22621.1928, every Windows update the problems are diferent, in one the start Menu return to the native Windows 11, other times scroll does not work above the tasskbar, other the windows change the focus ramdonly, well, now no import, i think that the important Windows 10 taskbar features like the non group tabs are coming to Windows 11, i use Explorer Patcher for a year and was a solution but not now with the problems and the no updates, thanks.

That is a preview update: https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by pyrates999** [comment]
Windows prompts you to install preview updates.  They are not automatically installed on their own.

**Comment by nestg** [comment]
No, i never say to Windows Update that install and that not install, all is automatic.

**Comment by pyrates999** [comment]
Check this: https://winaero.com/windows-11-now-allows-you-to-automatically-install-preview-updates/

**Comment by Poopooracoocoo** [comment]
Please create a discussion
