### ISSUE TITLE
Start menu location setting and search no longer working

### ISSUE THREAD

**Issue by ninaran** [valinet/ExplorerPatcher#1622]
Hey there!

I've been using the option "When using multiple displays, open Start on this monitor when invoked using they keyboard:" set on "Monitor #2" to have it open on my secondary monitor where my taskbar is at.
However since the most recent update this doesn't work any more and the Start menu opens on the primary screen as usual.

I can also no longer just "press windows key and start typing" to search for programs on my PC, nor use the search bar in the Start menu (just can't click into it). 

ExplorerPatcher version 22621.1555.55.1
Windows 11 version 22H2 22621.1928

Thank you in advance for fixes. :)

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by ninaran** [comment]
That fixed the issue regarding opening on the wrong monitor. I'll be more careful with updates, thank you.

The search function in the Start menu still doesn't work, however. Neither by automatically opening when I start typing (which is how I start most of my programs, since I dislike desktop icons, so it not working is a big deal), nor by actively clicking in the "Search for apps, settings, and documents" search bar.

I mean specifically the search in Start, not the one on the task bar.

**Comment by pyrates999** [comment]
https://github.com/valinet/ExplorerPatcher/issues/1566

**Comment by ninaran** [comment]
Just a heads-up, KB5028185 causes this issue as well, even with it not being a Preview update.

Which means I'll just have to try and avoid updates as long as possible to keep this from happening. 

The description of that other issue also helped with my search, so I guess the issue is fixed for at least the next few days until that update gets forced.
