### ISSUE TITLE
File Explorer is crashing. 

### ISSUE THREAD

**Issue by ajsin** [valinet/ExplorerPatcher#1624]
An error occurred after installation. Notifications related to symbol also did not appear. 
Could you help me? Thank you.

Here is version i tried :
Windows 11 OS version : 22621.1
ExplorerPatcher version : 22621.1555.55.1

Here is my reg exported : 
PC\HKEY_CURRENT_USER\Software\ExplorerPatcher

`
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"CrashCounter"=dword:00000000
"Start_MaximumFrequentApps"=hex(18):06,00,00,00
"StartDocked_DisableRecommendedSection"=hex(18):00,00,00,00
"StartUI_ShowMoreTiles"=hex(18):00,00,00,00
"StartUI_EnableRoundedCorners"=hex(18):00,00,00,00
"OpenPropertiesAtNextStart"=dword:00000000
"IsUpdatePending"=dword:00000000
"TaskbarGlomLevel"=dword:00000000
"MMTaskbarGlomLevel"=dword:00000000
"MigratedFromOldSettings"=dword:00000001
"FileExplorerCommandUI"=dword:00000000

[HKEY_CURRENT_USER\Software\ExplorerPatcher\StartUI]

[HKEY_CURRENT_USER\Software\ExplorerPatcher\sws]

[HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell]

`

**Comment by pyrates999** [comment]
Preview builds are not supported due to symbols not being available to download for them: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Vipin2003** [comment]
> Preview builds are not supported due to symbols not being available to download for them: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

I think that he is not using preview build....It was just a starting build of 22621. An old build and on this build, symbols are provided.
