### ISSUE TITLE
Can no longer expand Start Menu and certain OS dropdown lists

### ISSUE THREAD

**Issue by michael-zock** [valinet/ExplorerPatcher#1626]
I've run into something similar to what's described in #1622 but don't have the KB5027303 installed, so I'm still on 11 Enterprise 22621.1848

About two days ago, I noticed that the search function in the start menu was no longer working (just closes the menu instead), same thing happens with the "All Apps" button in the start menu and now I had to act against a false positive triggered by Windows Defender and it turns out that I can no longer use OS-level dropdown menus, either in Defender's "Protection History" section to restore the folder access for the false positive nor in the Apps list to try and uninstall Explorer Patcher to see if that fixes it.

The broken "All Apps" button in the start menu can be worked around in the Patcher settings with the "Open Start in All apps by default" option, but that still leaves me with the dropdown list problem and the broken start menu search (vanishes as soon as I type a character or click into the text field).

Eventually I found https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To but even after the uninstall, the problems still persist.

**Comment by michael-zock** [comment]
Seems there's a need to toggle something, I managed to uninstall ExplorerPatcher, ran "sfc/scannow", made two reboots and about half a  day later the problem suddenly went away. 
Now the start menu and the dropdown lists work again, wonder for how long...

**Comment by pyrates999** [comment]
> Seems there's a need to toggle something, I managed to uninstall ExplorerPatcher, ran "sfc/scannow", made two reboots and about half a day later the problem suddenly went away. Now the start menu and the dropdown lists work again, wonder for how long...

Looks like your windows install was corrupted and running sfc /scannow fixed it.

**Comment by michael-zock** [comment]
The SFC command alone came up empty (it's usually pretty eager to mention if it finds something.)
Weird thing is that there seems to be something going on under the hood that only corrects itself hours after the other steps.

**Comment by pyrates999** [comment]
If some menus are not expanding, that could be a sign you don't have symbols downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by michael-zock** [comment]
Thanks, that seems to be there, but so is the problem.
Pre-release version didn't help either.
```
funchook create 1
Running on Windows 11, OS Build 10.0.22621.1992.
Loaded symbols
Setup ntdll functions done
Setup user32 functions done
Patched taskbar transparency in newer OS builds
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
Progman: 459608
Progman hook: 6619557
[Positioning] Added settings for monitor 0000000000010001 : 0
[Positioning] Added settings for monitor 0000000000010003 : 0
>>> Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
0 0
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.1555.55.2.d8a404763e5404f8"
[Updates] Update URL: https://api.github.com/repos/valinet/ExplorerPatcher/releases?per_page=1
[Updates] Prerelease update URL: "https://github.com/valinet/ExplorerPatcher/releases/download/22621.1555.55.2_6fb998e/ep_setup.exe"
[Updates] Release notes URL: "https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.2_6fb998e"
[Updates] Hash of remote file is "22622.1555.55.2.d8a404763e5404f8" (valid).
[Updates] Local version obtained from hash is 22622.1555.55.2.
[Updates] No updates are available.
```

**Comment by pyrates999** [comment]
Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by Poopooracoocoo** [comment]
Are you still seeing these issues, @michael-zock?

**Comment by michael-zock** [comment]
Nothing worked and the problem continued to return, so I abandoned this in favor of Start11.

**Comment by Amrsatrio** [comment]
Perhaps one of the weirdest issues I've ever seen. On 20ish of physical PCs and VMs (none are Win11 Enterprise), I've _never_ had this issue.

Also because OP has abandoned this software and that there have been no more responses, I will be closing this issue.
