### ISSUE TITLE
Windows 11 Start menu not working

### ISSUE THREAD

**Issue by TAlim-1994** [valinet/ExplorerPatcher#1628]
When the Start menu style is set to Windows 11, the Start Menu does not appear when the Windows key or Start button is pressed/clicked. The Windows 10 Start Menu appears normally when selected as the Start menu style. I have attempted to reinstall ExplorerPatcher and to restart my PC, to no avail. My ExplorerPatcher version is 22621.1555.55.1; my Windows 11 version is 22H2, build 22621.1992.

**Comment by pyrates999** [comment]
Check that symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

If you did not get a notification they were downloaded, make sure you have not disabled symbols from being downloaded by opening up the explorer patcher properties application and go to advanced.  Make sure the option **Enable Symbols Download** is ticked.

After symbols have been downloaded, restart file explorer.  Sometimes you also need to reboot after as well.  I had to.
