### ISSUE TITLE
At a random moment, the explorer restarts 4-5 times, a black screen appears, and an error window from Explorer Patcher

### ISSUE THREAD

**Issue by Bledrock** [valinet/ExplorerPatcher#1629]
What can I do with it?

**Comment by schefi** [comment]
I experienced the same. It started after installing this Windows Update package: July 11, 2023—KB5028185 (OS Build 22621.1992)
Windows 11 version 22H2, all editions. I had to remove Explorer Patcher for the time being.

**Comment by SouthernHeftruck** [comment]
I had the same yesterday and uninstalled EP. Reinstalled ExplorerPatcher 1555.55.1 today and suddenly it worked. 
On 2 other computers I updated Windows 11 today expecting the same error but everything worked well, maybe the first time I started Windows Setting it took a while or I closed it but on a second run everything OK.

**Comment by UT-cgz** [comment]
`wusa.exe /uninstall /kb:5028185`

**Comment by saamprs** [comment]
It's all because of Windows' latest update. We just have to wait for an update for EP.

**Comment by IMSoley** [comment]
I thought it crashed because I use Windows Insider Build (Canary).

**Comment by pyrates999** [comment]
> I thought it crashed because I use Windows Insider Build (Canary).

Insider builds are not supported because symbols are not available for them: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by IMSoley** [comment]
> > I thought it crashed because I use Windows Insider Build (Canary).
> 
> Insider builds are not supported because symbols are not available for them: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

I hope someone finds a way

**Comment by pyrates999** [comment]
There's no work around if debug symbols can't be downloaded.

**Comment by IMSoley** [comment]
> There's no work around if debug symbols can't be downloaded.

Is this the same reason the registry hack doesn't work, either for making the taskbar small or moving it to the top?

**Comment by pyrates999** [comment]
If that is a setting in explorer patcher properties application, then yes.
