### ISSUE TITLE
Windows 10 Start Menu is not working on 11 insider build

### ISSUE THREAD

**Issue by darkpixlz** [valinet/ExplorerPatcher#1635]
The Windows 10 start menu option has not been working for me for a while now, for multiple versions. Still not fixed on 15393.1

**Comment by pyrates999** [comment]
Insider builds are not supported because the symbols are not available for them: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Amrsatrio** [comment]
Assuming your build version is 25393.1, we would support Dev builds, but not as far as Canary which is yours. Sorry about that. Closing this issue.
