### ISSUE TITLE
Start menu odd behavior

### ISSUE THREAD

**Issue by ITDev93** [valinet/ExplorerPatcher#1637]
Hiya all,
Just want to see if it's me or others as well having same issue and if there is a fix for it...

Sometimes if I click the start menu, it shows but nothing is clickable, I close it or click anywhere to close it and I open it the start menu again. Everything is clickable...

I did reinstall and restart the explorer patcher but still the same random occurrence...

For Start menu settings:
I have windows 11 default style, screen edge, 6 frequent apps (default), primary monitor (default), enabled the option to disable recommended section and the last option is disabled...

Thanks all...

**Comment by pyrates999** [comment]
Symbols haven't been downloaded is my guess: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

Please post windows version and build.
Please post explorer patcher version.

**Comment by ITDev93** [comment]
> Symbols haven't been downloaded is my guess: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> Please post windows version and build. Please post explorer patcher version.

Nope, Symbols are installed (Advanced -> symbols are checked), so it must be something else?

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by ITDev93** [comment]
> Please post windows version and build. Please post explorer patcher version.

![image](https://github.com/valinet/ExplorerPatcher/assets/22062468/24b3c84b-b665-44e3-b35d-c5dbf720dd94)

**Comment by pyrates999** [comment]
Open up the properties application for explorer patcher, go to advanced, and click on enable console.  Then try to open the start menu to create this behavior.  And paste the output from the console.

**Comment by ITDev93** [comment]
> Open up the properties application for explorer patcher, go to advanced, and click on enable console. Then try to open the start menu to create this behavior. And paste the output from the console.

I don't know if I did it right because the console did not print anything when I wasn't able to interact with the start menu:
![image](https://github.com/valinet/ExplorerPatcher/assets/22062468/ffa5552e-98b4-4cc9-80eb-1b34cb164674)

So I recorded a video:
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/NvwLJBW0H7c/0.jpg)](https://www.youtube.com/watch?v=NvwLJBW0H7c)

The first time I opened the start menu, nothing was clickable or highlighted to be selected. 
I moved the cursor around and clicked on everything. 

The second time opening, everything is highlighted and clickable...

Hope this helps...

**Comment by ITDev93** [comment]
This behavior also happens with the search bar; if I type anything, I cannot select it, I have to close and type the search again, and then I can select anything...

**Comment by pyrates999** [comment]
Uninstall explorer patcher and reboot.

Does this behavior still occur?

**Comment by ITDev93** [comment]
> Uninstall explorer patcher and reboot.
> 
> Does this behavior still occur?

well, that's odd. it does behave the same way...
But why...? maybe install Windows 11 to fix the system and registry...?

Maybe because of this silly icon in search bar...?
I wanted the icon, so I followed some guide on using ViVeTool to enable it...

Sorry for wasting your time, I thought it was Explorer Patcher related...

**Comment by pyrates999** [comment]
No problem.

**Comment by ITDev93** [comment]
> No problem.

I re-installed Windows (keep apps and files)...
The issue was still there, then I decided to run:
`vivetool /fullreset`

restarted the windows, the issue is gone, so anyone fiddling with ViVeTool, may end up messing with how Windows work...
I don't know if it would mess with Explorer Patcher, but it might do that as well...
It's a good thing to consider when checking other people's issues whether they used this tool or not...

Thanks a lot, I am closing this issue...
