### ISSUE TITLE
Explorer crashing when trying to open Windows Settings after an Windows Update

### ISSUE THREAD

**Issue by studiobuttermedia** [valinet/ExplorerPatcher#1639]
Recently I just updated my PC with KB5028185 Update, It requires 3 restart during update to finished the update. It may contained changes to Explorer that break the Patcher when trying to open Windows Settings thru Start. Search, PowerToys Run or Windows + I.

I just uninstalled the Patcher after a Pop-up about Patcher telling there's something wrong and tell me to wait until the new Update for a fix.

Update Link from Database: https://www.catalog.update.microsoft.com/Search.aspx?q=KB5028185

**Comment by pyrates999** [comment]
Please post windows version.
Please post explorer patcher version.

**Comment by fuzun** [comment]
This is fixed for me after the new symbols are downloaded.

**Comment by pyrates999** [comment]
For those who don't know, always check that symbols have been downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by xmae** [comment]
After installing the happy windows update that produces the error in explorer pacther, even having the option checked, it does not download the symbols for me. The only solution at the moment is to uninstall the windows update. I don't know whether to wait for an explorer pacther update or another solution.

**Comment by studiobuttermedia** [comment]
@xmae Yes this is the same version I had. When I tried to find a fix, I tried to force update the ExplorerPatcher and it didn't work. I have to uninstall the Patcher for it to work.
During that time, it only tell me it's on the latest version of Patcher.

Sorry, this is my first time reporting a bug on GitHub

**Comment by studiobuttermedia** [comment]
Usually when ExplorerPatch updates, I would receive the notification to update the patcher. But because it's an update that happened in the background on Windows's End before I heard there's a new Symbols that got out. 

But by the time I try to force Update ExplorerPatcher, there was no stable update. It was my main machine so I wouldn't dare to use any pre-release version.

Because Windows changed so much in the System Update (hence the 3 reboots), I might check later if reinstalling Patcher fixes.

**Comment by studiobuttermedia** [comment]
Apologies again, here's the latest Windows Build: Windows 11 - 22621.1992
Previous Latest ExplorerPatcher version before the crash happened: 22621.1555.55.1

**Comment by pyrates999** [comment]
Try this:

1. verify you get a notification that symbols have been downloaded
2. restart windows explorer using either the task manager or in the properties window of explorer patcher
3. reboot

**Comment by xmae** [comment]
The case where it fails me is on the desktop, but I have a laptop with windows 11 2621.1992 and in that case it does download the symbols and it works without problem, on the desktop for more than a clean registry, I reinstall and check that the options are marked in explorerpacther , doesn't work. I don't understand what is missing.

**Comment by rsauve** [comment]
First it was Windows 11 explorer.exe restart loop at login. Most annoying! Now its Windows app crashes (Settings) or app exit/restart (refuse to quit) looping (Maps).
I was pretty much ready to give up on ExplorerPatcher and OpenShell for Windows 11.

I think I now have it worked out (maybe).
1. Uninstall ExplorerPatcher.
2. Install ExplorerPatcher version 22621.1555.55.2
3. Reset settings back to defaults.
4. Ensure that "Enable symbols download *" is checked.
5. Select "Restart File Explorer (*) link a few times (just to ensure those symbols download).

![Screenshot 2023-07-18 180058](https://github.com/valinet/ExplorerPatcher/assets/26235138/64a7c545-e0d3-4864-84bb-852ed38911f7)

![Screenshot 2023-07-18 180150](https://github.com/valinet/ExplorerPatcher/assets/26235138/edf15f5e-28c3-48e2-8215-97891755102f)

Hopefully, hopefully this is the end of the ExplorerPatcher/Windows11 bug fest.

**Comment by pyrates999** [comment]
> i think i'll hold the latest (kb5028185) update till explorer patcher fixes the problem, I suggest the developer integrate symbols into the program itself as a new update to avoid confusion....... having to update symbols independently with main program itself

Read here on why that is not possible: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by studiobuttermedia** [comment]
Just fully reinstalled Windows 11, another application was conflicted and is deleting some Windows System Files
Now that I reinstall the full OS and reinstall the Patcher, I'm currently monitoring the System Explorer Console

`
funchook create 1
Running on Windows 11, OS Build 10.0.22621.1992.
Attempting to download symbol data; for now, the program may have limited functionality.
Setup ntdll functions done
Setup user32 functions done
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Open Start on monitor thread
EP Service Window thread
Initialized taskbar centering module.
0 0
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.1555.55.1.5758b678431cded2"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.1555.55.1.5758b678431cded2" (valid).
[Updates] Local version obtained from hash is 22622.1555.55.1.
[Updates] No updates are available.
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for unknown OS version 10.0.22621.1992.
[Symbols] Downloading to "C:\Users\bebos\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\Windows\system32\twinui.pcshell.dll" ("c723168734ed6540acb76138cff011d5")...
EnsureXAML 141 ms.
Started "Open Start on current monitor" thread.
Progman: 66026
Progman hook: 66445

10000 46000000
0 46000000
[3076:0720/115612.711:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is
[Symbols] Reading symbols...
[Symbols] Downloading symbols for "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartDocked.dll" ("392bd979fe469702b3bd130cc9dbb703")...

`

**Comment by studiobuttermedia** [comment]
Anyway, everything should be working normal now. Tho hopefully next time a new update comes, Patcher should pick up the update instantly

**Comment by studiobuttermedia** [comment]
Confirmed: Patcher has been updated
![image](https://github.com/valinet/ExplorerPatcher/assets/55838591/33166619-8bc4-4c49-8dd1-af61d51ce027)

**Comment by pyrates999** [comment]
An application deleting windows system files sounds like a virus.

**Comment by studiobuttermedia** [comment]
> An application deleting windows system files sounds like a virus.

Yes, but it's not related to ExplorerPatcher or any other programs.

I'm trying to be careful when downloading programs online but it's isn't always the option as crack software can misbehave without you knowing.

I use Adobe Software because "Industry Standard", while I would love to use other alternatives (and avoid cracks). It would be a problem if I'm working for a company that also use "Industry Standard"

I would pay, but I'm a student and I can't pay for neither Individual or Student because of the price.

**Comment by xmae** [comment]
I found the solution in my case:
It was a problem with the windowsdefender firewall, it blocks the symbol download address.

1_ Disable windows defender firewall momentarily
2_ Activate console in explorerpatcher settings
3_ Restore file explorer from explorerpatcher settings

When restored, in the console, it is already observed that it connects to the server and downloads the symbols and it works fine.
