### ISSUE TITLE
Suggestion: Add full screen start as an option

### ISSUE THREAD

**Issue by LemonadeSnake** [valinet/ExplorerPatcher#1642]
The full screen start still exists in 11, so why not add it as a feature here?

**Comment by pyrates999** [comment]
https://support.microsoft.com/en-us/windows/make-start-full-screen-13bc1e29-65dd-ba38-e3ec-7959b8d770dc

**Comment by LemonadeSnake** [comment]
this only applies to windows 10 it literally does not say windows 11 there bruh

**Comment by pyrates999** [comment]
How do you know the full screen start still exists in windows 11?  Did you find a way to enable it manually?

**Comment by LemonadeSnake** [comment]
There is a group policy that if you enable then restart explorer, allows for you to force normal start or full screen start. Forcing full screen start allows it to show up and functions exactly the same as it did in windows 10.

**Comment by pyrates999** [comment]
https://www.thewindowsclub.com/how-to-enable-windows-10-full-screen-start-menu-using-regedit-or-gpedit

**Comment by LemonadeSnake** [comment]
Ive been searching for a regedit version of this, thats really helpful

**Comment by Amrsatrio** [comment]
Is full screen Windows 11 start menu even a thing?

**Comment by Amrsatrio** [comment]
I will close this issue since there seem to be no more responses, and the fact that full screen start works on the latest release builds of Windows 11 with latest EP.
