### ISSUE TITLE
symbols download

### ISSUE THREAD

**Issue by none3** [valinet/ExplorerPatcher#1645]
how to force update symbols like check for updates.. i've already enabled symbols for download and console and still don't see any symbols downloading.

**Comment by none3** [comment]
i had to restart explorer to download and now they're downloaded... but according to someone said update the symbols should fix the latest security windows 11 update (kb5028185), the problem still exist. My problem is win button either not working or open the windows 11 native start menu instead of the customised start button (note i used open shell too). Forced to uninstall the update for the time being till explorer patcher's fixes the issue.

os: windows 11 22621.1848

**Comment by pyrates999** [comment]
https://github.com/valinet/ExplorerPatcher/issues/1529
