### ISSUE TITLE
Unable to pin Snipping Tool to Start Menu

### ISSUE THREAD

**Issue by rustyjarz** [valinet/ExplorerPatcher#1649]
Hi

Trying to pin the Snipping Tool to the Start Menu is failing, I'm receiving the successful message but when I check to see if it's on the Start Menu the Snipping Tool isn't there.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Vipin2003** [comment]
fix #1591

**Comment by Poopooracoocoo** [comment]
Closing as duplicate of #1108
