### ISSUE TITLE
Can you hide Ethernet/sound icon and Time/Clock with this tool?

### ISSUE THREAD

**Issue by WilliamLeGod** [valinet/ExplorerPatcher#1651]
As title.

Thank you for your work!

**Comment by Vipin2003** [comment]
yes...you can do this.
go to **customize system icons in notification area** in EP properties.
and turn off them.

**Comment by pyrates999** [comment]
Or you don't even need to use this tool.  Right click on the taskbar and click on taskbar settings.

Click on turn system icons on or off.

From there you can hide or unhide any of those system icons.

**Comment by WilliamLeGod** [comment]
> Or you don't even need to use this tool. Right click on the taskbar and click on taskbar settings.
> 
> Click on turn system icons on or off.
> 
> From there you can hide or unhide any of those system icons.

Thanks for the help. I forget to mention I'm using Windows 11 so those options are not there anymore :(

**Comment by pyrates999** [comment]
https://www.makeuseof.com/system-tray-icons-windows-11/

**Comment by Poopooracoocoo** [comment]
Use discussions for questions
