### ISSUE TITLE
Explorer Crash Loop (duplicate of #1552)

### ISSUE THREAD

**Issue by MadManMoon** [valinet/ExplorerPatcher#1652]
Hi, just logging a duplicate issue of this causing explorer crash looping.

This can be closed once it's registered as a duplicate of:
https://github.com/valinet/ExplorerPatcher/issues/1552

Just logging it as a dupe as the ITIL in me wants you to have as much data for how much it's affecting stuff.

Keep up the good work!

**Comment by RobGMun** [comment]
Just has this too. Installed a fresh copy of W11:
Edition	Windows 11 Home
Version	22H2
Installed on	‎19/‎07/‎2023
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0

And installed EP Releases 210 22621.1555.55.1

Rebooted and got into this death loop, please resolve this asap.

**Comment by pyrates999** [comment]
Explorer Patcher stops trying to load after 3 crashes.

Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by RobGMun** [comment]
"Explorer Patcher stops trying to load after 3 crashes."

No, it doesn't, it looks like it tries to recover for a couple of seconds but then goes back into the death loop.

Anyway, I wiped the drive and reinstalled everything again and it seems to be working after some reboots. The difference this time is that I'm using another 3rd party app to return the W10 Tile Start menu as the one on EP doesn't include Windows apps. Before I turned it on via EP, then installed Startup11 over it. I'll keep you guys up to date if it happens again tonight

**Comment by pyrates999** [comment]
> "Explorer Patcher stops trying to load after 3 crashes."
> 
> No, it doesn't, it looks like it tries to recover for a couple of seconds but then goes back into the death loop.
> 
> Anyway, I wiped the drive and reinstalled everything again and it seems to be working after some reboots. The difference this time is that I'm using another 3rd party app to return the W10 Tile Start menu as the one on EP doesn't include Windows apps. Before I turned it on via EP, then installed Startup11 over it. I'll keep you guys up to date if it happens again tonight

That's due to this bug: https://github.com/valinet/ExplorerPatcher/issues/1108
