### ISSUE TITLE
Windows 10 & 11 start menu not Working with Microsoft Windows [version 10.0.22621.1992]

### ISSUE THREAD

**Issue by rudstone** [valinet/ExplorerPatcher#1655]
Hi,

After apply Windows 11 Patch (KB5028185), Windows 10 & 11 start menu didnt show after update OS.
I try to reinstall / update Valinet, unsuccessful.

> [Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.1555.55.1.5758b678431cded2"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.1555.55.1.5758b678431cded2" (valid).
[Updates] Local version obtained from hash is 22622.1555.55.1.
[Updates] No updates are available.
[Symbols] Started "Download symbols" thread.
**[Symbols] Attempting to download symbols for unknown OS version 10.0.22621.1992**.
[Symbols] Downloading to "C:\Users\user\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\WINDOWS\system32\twinui.pcshell.dll" ("c723168734ed6540acb76138cff011d5")...
[Symbols] Symbols for "C:\WINDOWS\system32\twinui.pcshell.dll" are not available - unable to download.
[Symbols] Please refer to "https://github.com/valinet/ExplorerPatcher/wiki/Symbols" for more information.

Can I try to help me?

**Comment by pyrates999** [comment]
Check that antivirus or third party firewall is not blocking the download of the symbols.

The output says it can't download symbols.

Please check the url it refers to here:

> [Symbols] Please refer to "https://github.com/valinet/ExplorerPatcher/wiki/Symbols" for more information.
