### ISSUE TITLE
Unable to search in the start menu

### ISSUE THREAD

**Issue by codygp** [valinet/ExplorerPatcher#1662]
Title says it all, when i click on the search box in the start menu, it just starts bouncing around all the different tiles instead of searching.
When I turn the search button on for the task bar, clicking it has no action. 

EplorerPatcher 22621.1555.55.2
Windows 11 OS 22621.2050

Everything else works great! Thanks!

Let me know if I can provide any other info.

**Comment by pyrates999** [comment]
That is a preview update: https://blogs.windows.com/windows-insider/2023/07/21/announcing-windows-11-insider-preview-build-22621-2050-and-22631-2050/

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by codygp** [comment]
You are correct, but I suspect its probably still good information to have for the developer. 

I updated to 22631 and now its working. Still an insider build.

**Comment by codygp** [comment]
Marking closed as my issue is now resolved.
