### ISSUE TITLE
How do I make Live tiles anywhere work with ep?

### ISSUE THREAD

**Issue by Caddy8970** [valinet/ExplorerPatcher#1663]
Live tiles anywhere is a ms store app that allows you to make custom live tiles for your start screen.
However, the "pin to start" option doesn't do anything because, of course, it tries to pin the tile to the windows 11 start menu (not the windows 10 one that ep has).
Is there a way to make the app work with ep's start menu?

**Comment by Vipin2003** [comment]
Do you want to pin the UWP Apps as Live tiles in Win11 SM or Win10 start menu?? I'm unable to properly understand that.

**Comment by Vipin2003** [comment]
Close issue if it resolves your issue.

**Comment by Caddy8970** [comment]
I mean if I can pin the live tiles (which are mostly links to regular windows apps, not UWP) that I made with the app. Sorry for the misunderstanding but I'm not great at explaining
-------- Original Message --------

**Comment by Vipin2003** [comment]
It is not possible with EP's win10 start... Sorry

**Comment by Caddy8970** [comment]
It's fine
