### ISSUE TITLE
No windows 10 menu 

### ISSUE THREAD

**Issue by erqf** [valinet/ExplorerPatcher#1668]
When i click windows button i see windows 11 even after symbols had been downloaded

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

Restart windows explorer using either the task manager or in the properties window of explorer patcher.

You can also try rebooting.

**Comment by erqf** [comment]
Version:22H2 build:22621.1848
patcher version:22621.1992.56.1(latest)

i tried everything still windows 11 menu

**Comment by pyrates999** [comment]
Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by erqf** [comment]
Thanks so much now its working.

**Comment by pyrates999** [comment]
Please close this then.
