### ISSUE TITLE
explorer restart on trying to start hotspot

### ISSUE THREAD

**Issue by annajiat** [valinet/ExplorerPatcher#1670]
On a dual monitor windows 11 system, explorer restarts on trying to start hotspot from start menu

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by Amrsatrio** [comment]
There is no such thing as enabling mobile hotspot from the start menu. And enabling it through control center and the Win10 network flyout works just fine on 22621.2428.

Since there have been no responses for a long time, I will be closing this issue.

**Comment by annajiat** [comment]
Windows 11 Home
Version 22H2 OS Build 22621.2428

**Comment by annajiat** [comment]
It was the latest version at that time as I have tried with the updated version.

**Comment by annajiat** [comment]
Procedure -> Start Menu -> Search for hotspot -> opens "system settings under Network & internet -> mobile hotspot"

**Comment by Amrsatrio** [comment]
It doesn't crash on me. Have you tried updating your WiFI drivers?

**Comment by annajiat** [comment]
WiFi drivers were the latest one. It seems to be solved in the current version of the Explorer Patcher, working nicely, thank you for the great product.
