### ISSUE TITLE
Possible issue - Can't type in start menu search field

### ISSUE THREAD

**Issue by TurkeyMan** [valinet/ExplorerPatcher#1675]
Windows rolled out an update a week ago; big-ish one, computer rebooted several times installing, and asked me to set things up on first boot, normal things like authorising Edge to claim browser duties, opt-in to MS OneDrive, etc...
It seems since then, my start menu doesn't work. I can click the start button or press the windows key, and it appears as normal. I can navigate the start menu with the mouse as normal, so it's working, but for whatever reason, when I normally type to find/filter the item that I'm looking for in the start menu, I can't type into the search box at the top (which normally contains the cursor by default). Instead, it highlights pinned icons that start with the letter I press by placing a square around the icon.
If I click in the search box to try and place the cursor in it in order to type and search, it won't focus the search box, and typing continues to highlight pinned items starting with the letter.
This may be unrelated, but my system is pretty much stock, almost nothing tweaked, only odd thing I'm running is ExplorerPatcher, so I wonder if it's related to the start menu's recent misbehaviour following the Microsoft update rollout?
Anyone else experienced this? Known issue?
I tried to install [22621.1555.55.2](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.2_6fb998e) as a hail-mary, no change.

**Comment by pyrates999** [comment]
Please post windows version and build.

**Comment by Twit123** [comment]
Hi,

I had the exact same problem, then realized there was an update to Explorer patcher, I updated and rebooted and all working again.

ExplorerPatcher - 22621.1992.56.1
Windows 11: 22H2
OS Build: 10.0.22621.1992

NOTE: In case someone comes looking for solutions, I had to reboot before the start search started working again.

Simon

**Comment by cellentano** [comment]
Hi,
I cant solve this issue. Unistall/Reinstall/Update of EP didnt help.

ExplorerPather - 22621.1992.56.1
Windows 11: 22H2
OS Build: 10.0.22621.1702

Any idea ?

Ado

**Comment by pyrates999** [comment]
Try this: https://learn.microsoft.com/en-us/answers/questions/1183404/my-windows-search-bar-on-windows-11-isnt-working

**Comment by Tyler-IN** [comment]
Just gonna mention ran into the same issue. I'll post here if I figure out what works.

**Comment by Tyler-IN** [comment]
Forcing a rebuild of the Windows Search index via Advanced indexing options causes a hang; after a reboot, issue appears to have resolved. I'll post again if the problem reoccurs.

**Comment by pyrates999** [comment]
If search is now working after you force a rebuild of the windows search index, please close this.

**Comment by Tyler-IN** [comment]
Issue https://github.com/valinet/ExplorerPatcher/issues/1803 may be related, all related to input event handling on the start menu.

@TurkeyMan were you able to get search working?

**Comment by cellentano** [comment]
Well,
there are plenty fixes how to solve the "search issue", but nothing worked for me. I did windows reset/reinstall finally and search from taskbar is back.

**Comment by pyrates999** [comment]
This should be closed because it is not a bug in explorer patcher.

**Comment by TurkeyMan** [comment]
@Tyler-IN I did an uninstall-reboot-reinstall dance, and that seemed to resolve the problem for me.
I'll close this I guess, but regardless whether it's a bug in explorer-patcher, it should be investigated if any workarounds are possible and implemented. You can't point at mega-corps buggy software you interact with say "it's their bug, send the bug request to them"; that's just not how this works. If there is any workaround possible, it can/should be integrated into explorer-patcher.

**Comment by e-t-l** [comment]
> I did an uninstall-reboot-reinstall dance, and that seemed to resolve the problem for me.

I'm gald that worked for you, but it doesn't work for me. When I have ExplorerPatcher installed (and _only_ when I have EP), when I go to the start menu and type, it doesn't respond. As suggested earlier, it's like it's not receiving the text input. To clarify, this is _not_ the Search bar on the taskbar. This is when the start menu is open, typing should automatically begin searching

@pyrates999 Are you aware of any other issues that could be related to this?

**Comment by e-t-l** [comment]
Note: I guess the easiest workaround is just to remember that when you want to use Windows Search, instead of just hitting the `Windows Key`, hit `Win + S`.

**Comment by pyrates999** [comment]
> > I did an uninstall-reboot-reinstall dance, and that seemed to resolve the problem for me.
> 
> I'm gald that worked for you, but it doesn't work for me. When I have ExplorerPatcher installed (and _only_ when I have EP), when I go to the start menu and type, it doesn't respond. As suggested earlier, it's like it's not receiving the text input. To clarify, this is _not_ the Search bar on the taskbar. This is when the start menu is open, typing should automatically begin searching
> 
> @pyrates999 Are you aware of any other issues that could be related to this?
> 
> -- Win 11 Home: 22h2 OS build: 10.0.22621.2215 ExplorerPatcher: 22621.1992.56.3

That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by e-t-l** [comment]
Ah, thank you. Is a preview update different than the Insider program? I am *not* a part of the Insider program so I thought that meant I was safe from getting not-fully-stable releases :/

**Comment by pyrates999** [comment]
Yes, but you have to opt-in to it unless you already have through the above setting.

**Comment by e-t-l** [comment]
@pyrates999 I am still having this issue, even though I have opted out of preview updates and uninstalled all currently present preview updates. To confirm, here is a list of my Windows Update History:
```
2023-08 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5029263)
Successfully installed on 8/23/2023
2023-08 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5029263)
Successfully installed on 8/23/20232023-08 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for x64 (KB5028948)
2023-04 Update for Windows 11 Version 22H2 for x64-based Systems (KB4023057)
2023-08 Cumulative Update for .NET Framework 3.5, 4.8 and 4.8.1 for Windows 11 for x64 (KB5029650)
2023-08 .NET 7.0.10 Security Update for x64 Client (KB5029689)
2023-08 .NET 6.0.21 Security Update for x64 Client (KB5029688)

**Comment by pyrates999** [comment]
> Try this: https://learn.microsoft.com/en-us/answers/questions/1183404/my-windows-search-bar-on-windows-11-isnt-working

Do the above.  This isn't a bug with EP.
