### ISSUE TITLE
Black Task bar and empty right click menu

### ISSUE THREAD

**Issue by maybenotxand** [valinet/ExplorerPatcher#1677]
After a restart, buttons work but no text.
![image](https://github.com/valinet/ExplorerPatcher/assets/140608662/c9b2a0a3-fda3-4362-b990-1c8976975e8e)
![image](https://github.com/valinet/ExplorerPatcher/assets/140608662/7f7c3600-9e9e-48d9-b166-3e61e782d630)

**Comment by Vipin2003** [comment]
Update EP to Latest

**Comment by maybenotxand** [comment]
Did not fix the issue.

**Comment by maybenotxand** [comment]
Caused by classic theme
