### ISSUE TITLE
One strange, clickabled, small grey dot on right side of Start Menu

### ISSUE THREAD

**Issue by alexgoldreyer** [valinet/ExplorerPatcher#1681]
![Screenshot_1](https://github.com/valinet/ExplorerPatcher/assets/31568970/81c7e9e7-417c-4172-a5ec-80191e565ebb)

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

Then open the start menu where the grey dot is supposed to appear.

**Comment by alexgoldreyer** [comment]
Attached screen record

https://github.com/valinet/ExplorerPatcher/assets/31568970/815e92e5-591e-4f62-a1fd-b9b6d403f1aa

**Comment by alexgoldreyer** [comment]
Attached screen record:

https://github.com/valinet/ExplorerPatcher/assets/31568970/83698793-24ca-4823-a50e-79785e67aee5

**Comment by alexgoldreyer** [comment]
Disappeared when I disabled the "Recommended" section

**Comment by pyrates999** [comment]
Good to know.

**Comment by nadinoob** [comment]
It's (part) of an indicator for "there's another page scroll down".

**Comment by pyrates999** [comment]
Please close this then as this is intentional by windows.

**Comment by Vipin2003** [comment]
It is just a feature provided by windows to switch between pages having pinned items.
