### ISSUE TITLE
ExplorerPatcher crashes when I right click on Battery icon

### ISSUE THREAD

**Issue by SynStark** [valinet/ExplorerPatcher#1684]
I used the program for awhile without any issues, but from today everytime I right click the Battery Icon in the lower right corner to change the Power Plan the Windows Explorer crashes. Also when I click on the Task View icon in the lower left nothing happens.
Any ideas?

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by SynStark** [comment]
> Please post windows version and build. Please post explorer patcher version.

Asus Scar 18 Windows 11 Home 22621.2070
Explorer 22621.1992.56.1

**Comment by ephedrin3** [comment]
Same versions when i right click tasbar, uninstalled for now, waiting for a fix, Thank you

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Poopooracoocoo** [comment]
KB5028254 and 22621.2070 was a preview update
