### ISSUE TITLE
Bitlocker issue

### ISSUE THREAD

**Issue by ManPython** [valinet/ExplorerPatcher#1685]
Is possible to refresh automatically bar with icons in case some of this are as shortcuts from drive where is Bitlocker and encrypted drive?
The situation is that after pass password to unlock drive the icons are broken (like bad path). This require to kill explorer process and restart to refresh icons, and this same eg. shortcuts dirs as toolbar (if not refreshed then no exist arrows to open this dirs to the drives).

In fact is Windows 10/11 problem, but not sure where to report. Also similar when want lock drives after unlock as missed functions around.

**Comment by pyrates999** [comment]
Try uninstalling explorer patcher and see if this still occurs.

**Comment by ManPython** [comment]
Noo.. it's old problem.

**Comment by pyrates999** [comment]
If it is not caused by explorer patcher, then this is not the place to post it.

**Comment by ManPython** [comment]
It's question about option to implement refresh explorer by pather when Bitlocker unlocking dirs. It's possible?

**Comment by pyrates999** [comment]
Suggestions for new features go into discussions.

**Comment by BraINstinct0** [comment]
Close issue as it is a suggestion, not a bug. Better yet - move this to discussions
