### ISSUE TITLE
Taskbar Search "Box"

### ISSUE THREAD

**Issue by ItsMeSB77** [valinet/ExplorerPatcher#1686]
No issues to report yet, just an ask... Would love to see the search "box" added as an option to the Windows 10 taskbar. Thx.

**Comment by pyrates999** [comment]
New feature requests are in discussions, not issues.

**Comment by ItsMeSB77** [comment]
Thx. Sorry about that :)

**Comment by BraINstinct0** [comment]
Close the issue please, as it is not an issue.
