### ISSUE TITLE
✅ Fixed: EP broken after installing Windows update KB5028254

### ISSUE THREAD

**Issue by gaiking-uk** [valinet/ExplorerPatcher#1689]
I just restarted after...
- Installing `KB5028254` [2023-07 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems](https://support.microsoft.com/en-gb/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8)
- Updating ExplorerPatcher to `22621.199256.1`

## ⚠️ EP is now completely nuked on my system and can't start at all

Am not sure what the root cause is, i.e. which one of the above updates potentially caused the issue (or even if it was something else un-related to the above) but I will post a follow-up comment if I am able to track the root issue.

For now though, I wanted to create this initial post for community awareness of potential issue / Microsoft update blocking EP from working.

**Comment by Soldier874** [comment]
Same problem here

**Comment by OliverBorgmann** [comment]
I found out that if you change the taskbar style from 11 to 10, the error went away

**Comment by BenjaminWKI** [comment]
Same situation here with EP constantly crashing and unusable since getting the latest Windows 11 update. Wish I procrastinated on that.
@OliverBorgmann that kinda makes having and running EP pointless, no?

**Comment by gaiking-uk** [comment]
> @OliverBorgmann: I found out that if you change the taskbar style from 11 to 10, the error went away

Appreciate the suggested fix, unfortunately this didn't work for me 😔...
- My taskbar style was already set to Win10 when EP stopped working
- I tried manually changing it to Win11 and then back to Win10 but this didn't work either

**Comment by gaiking-uk** [comment]
If it's helpful for the devs, please find extract from the Windows Event Log...

```
Faulting application name: Explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c
Faulting module name: ntdll.dll, version: 10.0.22621.1928, time stamp: 0x7dd9e350
Exception code: 0xc0000374
Fault offset: 0x000000000010c1f9
Faulting process ID: 0x0x5708
Faulting application start time: 0x0x1D9C058560714C9
Faulting application path: C:\Windows\Explorer.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll

Faulting application name: DllHost.exe, version: 10.0.22621.1, time stamp: 0x05e70ed3
Faulting module name: ntdll.dll, version: 10.0.22621.1928, time stamp: 0x7dd9e350
Exception code: 0xc0000409
Fault offset: 0x000000000008ea6f
Faulting process ID: 0x0x3CC0
Faulting application start time: 0x0x1D9C0582D8AB216
Faulting application path: C:\Windows\system32\DllHost.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
```

NB: I tried switching Shell Integration on/off a few times (as thought that could be a path to get EP working) -- some of the errors may be related to this (and so may not appears in other user's event log potentially.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by gaiking-uk** [comment]
@pyrates999 -- Your comment was a bit minimal has 👍🏼👎🏼 reactions but it did help me find a path to get EP working again, so thanks for that!...

### Core issue: Additional info
- The latest version of EP (currently [22621.1992.56.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541)) supports Windows up to build: `22621.1992`
- [KB5028254](https://support.microsoft.com/en-gb/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8) essentially upgrades Windows to `22621.2070`
- KB5028254 isn't a 'Windows Insider' or 'Beta' update
- It is ***available to all Windows users*** who have ticked the `Get the latest updates when they're available` checkbox

> Over the last 24 hours or so, I reluctantly uninstalled ExplorerPatcher just to get my system stable again...
My god, I had forgotten ***how horrendously bad*** native Windows 11 is/was! 🤦🏼‍♂️
❌ No Explorer Ribbon, ❌ No taskbar menu, ❌ No custom toolbars, ❌ Worse start menu
Needless to say, I was extremely relieved to get EP working again and so thank you to everyone who helped achieve this!

### ✅ Steps to fix EP...
1. ***Turn off 'Preview' updates*** Settings > Windows Updates > Un-tick `Get the latest updates as soon as they're available`
2. ***Uninstall KB5028254:*** Settings > Windows Updates > Update History > (Scroll down) > Uninstall updates

NB: The above will take 2-5 minutes, then require a reboot which needs another 5-10 minutes of pre/post-OS updating
CC: @Soldier874

**Comment by gaiking-uk** [comment]
@pyrates999 -- Your comment was a bit minimal has 👍🏼👎🏼 reactions but it did help me find a path to get EP working again, so thanks for that!...

## ✅ Steps to fix EP...
1. ***Turn off 'Preview' updates*** Settings > Windows Updates > Un-tick `Get the latest updates as soon as they're available`
2. ***Uninstall KB5028254:*** Settings > Windows Updates > Update History > (Scroll down) > Uninstall updates
3. The above takes around 2-5 mins + a reboot, which needs another 5-10 mins of pre/post-OS updating

CC: @Soldier874 

***

## Core issue: Additional info
- The latest version of EP (currently [22621.1992.56.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541)) supports Windows up to build: `22621.1992`
- [KB5028254](https://support.microsoft.com/en-gb/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8) essentially upgrades Windows to `22621.2070`
- KB5028254 isn't a 'Windows Insider' or 'Beta' update
- It is ***available to all Windows users*** who have ticked the `Get the latest updates when they're available` checkbox

> Over the last 24 hours or so, I reluctantly uninstalled ExplorerPatcher just to get my system stable again...
My god, I had forgotten ***how horrendously bad*** native Windows 11 is/was! 🤦🏼‍♂️
❌ No Explorer Ribbon, ❌ No taskbar menu, ❌ No custom toolbars, ❌ Worse start menu
Needless to say, I was extremely relieved to get EP working again and so thank you to everyone who helped achieve this!

**Comment by pyrates999** [comment]
> @pyrates999 -- Your comment was a bit minimal has 👍🏼👎🏼 reactions but it did help me find a path to get EP working again, so thanks for that!...
> 
> ## ✅ Steps to fix EP...
> 1. _**Turn off 'Preview' updates**_ Settings > Windows Updates > Un-tick `Get the latest updates as soon as they're available`
> 2. _**Uninstall KB5028254:**_ Settings > Windows Updates > Update History > (Scroll down) > Uninstall updates
> 3. The above takes around 2-5 mins + a reboot, which needs another 5-10 mins of pre/post-OS updating
> 
> CC: @Soldier874
> 
> ## Core issue: Additional info
> * The latest version of EP (currently [22621.1992.56.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541)) supports Windows up to build: `22621.1992`
> * [KB5028254](https://support.microsoft.com/en-gb/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8) essentially upgrades Windows to `22621.2070`
> * KB5028254 isn't a 'Windows Insider' or 'Beta' update
> * It is _**available to all Windows users**_ who have ticked the `Get the latest updates when they're available` checkbox
> 
> > Over the last 24 hours or so, I reluctantly uninstalled ExplorerPatcher just to get my system stable again...
> > My god, I had forgotten _**how horrendously bad**_ native Windows 11 is/was! 🤦🏼‍♂️
> > ❌ No Explorer Ribbon, ❌ No taskbar menu, ❌ No custom toolbars, ❌ Worse start menu
> > Needless to say, I was extremely relieved to get EP working again and so thank you to everyone who helped achieve this!

Some people just didn't like the answer.  Although it was the answer.  Thanks for the detailed answer!

**Comment by gaiking-uk** [comment]
Sure, I get that. -- FYI: I think the reason for the 👎🏼 reaction was because your message sounded a bit like...

> That is a preview update
If you want to use explorer patcher and don't install preview updates in the future

 └▷  Sounded a bit like you were implying...
- "You shouldn't enable settings or try new things"
- "This is your own fault for installing a non-standard update"

If I was using a Windows Insider build (or some other kind of explicit "Beta" updates) then I would agree this would somewhat of self-inflicted problem, but I wasn't and thought I was just getting standard Windows updates, so thinking you were saying the seemed a bit harsh / critical.

- I uninstalled KB5028254 and used an old Microsoft "hide Windows updates" tool to stop it re-installing but this didn't work
- Like I say though, your reference to the ***Preview*** update made me do some further research into what updates I was actually getting and how to disable them
- That's when I confirmed the Windows Update setting that needed to be changed

> I wasn't planning on sharing the above as it's not related to the issue with EP, but thought it may be helpful... I realised you were just trying to help out after all.

**Comment by mauriciopfl** [comment]
Same problem here. Even after uninstalling the update, Windows automatically updates again, only pausing Windows Update so that it does not occur. ExplorerPatcher will be missed until a new version is released.

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

**Comment by gaiking-uk** [comment]
Thanks @pyrates999 👍🏼

@mauriciopfl -- Yes, this happened to me to (I even tried blocking the update using a Microsoft tool) but as pyrates / my 'solution' comment above advised, unticking `Get the latest updates as soon as available` is the key thing you need to do and will stop this re-installing for you 👍🏼

Further thought: Hopefully this doesn't become an issue for a huge amount of people.... As I alluded to in my comments above, my concern is that EP is broken by a Microsoft "Preview" update, but these are relatively easy for people to get unintentionally. For instance, at one point I was on the Windows Insider build but had since opted out and so as far as I thought was just getting "normal" Windows updates, however this wasn't actually the case - and all because of ticking one box in settings 🤔

**Comment by gaiking-uk** [comment]
> Re-posting the fix to help any future readers (i.e. making this easier to find amongst other comments)

## ✅ Fix found!
Please note: at this time (July 2023) the only known fix is to uninstall the update. Please see steps below and some important information...

1. ***Turn off 'Preview' updates***
- `Settings` > `Windows Updates` > Un-tick `Get the latest updates as soon as they're available`
- This will stop any future 'Preview' Windows updates
- If you don't do this, KB5028254 will automatically reinstall itself next time Windows update runs

2. ***Uninstall KB5028254***
- `Settings` > `Windows Updates` > `Update History` > (Scroll down) > Uninstall updates
- The above takes around 2-5 mins + a reboot, which needs another 5-10 mins of pre/post-OS updating

**Comment by mauriciopfl** [comment]
Thank you all. In fact, I decided to try Microsoft's Windows Insider program and installed Windows build 25915.1000 (Canary), and the functionality of ungrouping icons was excellent. For the rest of Windows features I didn't notice any difference or difficulty.

**Comment by gaiking-uk** [comment]
> Re-posting the fix to help any future readers (i.e. making this easier to find amongst other comments)

## ✅ Fix found!
Please note: at this time (July 2023) the only known fix is to uninstall the update. Please see steps below and some important information...

1. ***Turn off 'Preview' updates***
- `Settings` > `Windows Updates` > Un-tick `Get the latest updates as soon as they're available`
- This will stop any future 'Preview' Windows updates
- If you don't do this, KB5028254 will automatically reinstall itself next time Windows update runs

2. ***Uninstall KB5028254***
- `Settings` > `Windows Updates` > `Update History` > (Scroll down) > Uninstall updates
- The above takes around 2-5 mins + a reboot, which needs another 5-10 mins of pre/post-OS updating

**Comment by aldeniangman** [comment]
> I just restarted after...
> 
> * Installing `KB5028254` [2023-07 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems](https://support.microsoft.com/en-gb/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8)
> * Updating ExplorerPatcher to `22621.199256.1`
> 
> ## ⚠️ EP is now completely nuked on my system and can't start at all
> Am not sure what the root cause is, i.e. which one of the above updates potentially caused the issue (or even if it was something else un-related to the above) but I will post a follow-up comment if I am able to track the root issue.
> 
> For now though, I wanted to create this initial post for community awareness of potential issue / Microsoft update blocking EP from working.

I WISH MICROSOFT ALLOWED US TO USE OLD SETTINGS FROM WINDOWS 10. And then, open shell could use the update to fix the see-through WIndows Icon menu.
Does StartAllBack (the app I hate because it cost s money) had this issue
