### ISSUE TITLE
New windows opened within existing Explorer ones don't retain the patched Windows 7 non-ribbon interface (Regression somewhere between Win10 1903 and 22H1)

### ISSUE THREAD

**Issue by dimmskii** [valinet/ExplorerPatcher#1690]
Ver: Windows NT 10.19045.3208 22H2 Enterprise Edition
Links opening in a new window from Control panel like like _Administrative Tools_ do not retain Windows 7 non-ribbon interface if the option is enabled.

Win 10 1903 last update doesn't have this bug. This behavior had been introduced somewhere in between.

Coming back to Windows 22H2 this was the first bug I checked to see if it was fixed. If you are not aware of it already, my apologies. Perhaps I should have posted about it earlier. I also remember a bug where the Explorer _Open in each folder in a (its own/same) window_ setting behavior became reversed. It opened in new windows also with the Win 7 interface missing until I selected the opposite option. Rebooting fixed it. I cannot reproduce this on demand.

https://github.com/valinet/ExplorerPatcher/assets/4108751/94ff3fe6-5cbb-40af-be03-e31069ab8dfc

**Comment by dimmskii** [comment]
Here is which behavior got reversed randomly as I recall before (again, cannot reproduce on demand):

![image](https://github.com/valinet/ExplorerPatcher/assets/4108751/5ba6c0ba-c1f9-489e-8cd4-7165e5a86da8)

**Comment by pyrates999** [comment]
You installed a preview update: https://pureinfotech.com/kb5028166-windows-10-build-19045-3208-22h2-21h2/

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

**Comment by Amrsatrio** [comment]
This has been fixed in a recent release.
