### ISSUE TITLE
ExplorerPatcher continuosly crashes, had to uninstall on Windows 22H2 Build 22621.2070

### ISSUE THREAD

**Issue by ansorre** [valinet/ExplorerPatcher#1694]
As per by title.
I think there was an aouto update during the Night and now ExplorerPatcher does not work anymore.

**Comment by rtngdn** [comment]
Same problem. Fortunately, I saved the previous version & reinstalled it. Have Win11, Home 64 bit, very few apps installed.

**Comment by doubleddav** [comment]
I'm having exactly the same issue on the same version on Windows. Just after the update and reboot, the software crashes. Sometimes it will load and work for about half a second. Running exp version 22621.1992.56.1

**Comment by zhanghuizong** [comment]
Same problem

![image](https://github.com/valinet/ExplorerPatcher/assets/4384876/995b5a80-254e-4176-99d9-8d0f6967cec9)

**Comment by piaoxue2000** [comment]
Same problem.

**Comment by nabel0** [comment]
Same here

**Comment by vitaalijs** [comment]
same here. fixed?

**Comment by vitaalijs** [comment]
> Same problem. Fortunately, I saved the previous version & reinstalled it. Have Win11, Home 64 bit, very few apps installed.

where to get the last version?

**Comment by TheProgrammer92** [comment]
I have de same problem

**Comment by SthMax** [comment]
I have the same problem

**Comment by betisak** [comment]
Hi, I uninstalled the older version. Installed the new one, and imported the save program that I had backed up. I also saved the registries separately just to be safe. I have done this twice and the program is working normally now and does not crash or give an error message.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by valinet** [comment]
The EP update in itself has nothing to do with the program not working, compared to the previous version, there's very few of the functionality changed.

Regarding Windows 11 22H2 build 22621.2070, I have installed this build on my test VM, plus latest EP, and it works fine on my end. That is, on a clean install, with no EP settings whatsoever. So, if there's a problem indeed, it's caused by a particular setting which has to be identified and then the code regarding it studied, in order to determine exactly what is happening.

**Comment by AndiDink00x** [comment]
@valinet the crashing happens on W11 taskbar for me and it seems for the others also, if changed to W10 taskbar it works fine

**Comment by valinet** [comment]
> > The EP update in itself has nothing to do with the program not working, compared to the previous version, there's very few of the functionality changed.
> > Regarding Windows 11 22H2 build 22621.2070, I have installed this build on my test VM, plus latest EP, and it works fine on my end. That is, on a clean install, with no EP settings whatsoever. So, if there's a problem indeed, it's caused by a particular setting which has to be identified and then the code regarding it studied, in order to determine exactly what is happening.
> 
> Is there any WIKI or instruction how to remove all settings? Then i'll try it again here...

The source code is the best documentation there is so far (https://github.com/valinet/ExplorerPatcher/blob/master/ExplorerPatcher/def.h).

These keys contain **most** of the settings:
* `HKCU\SOFTWARE\ExplorerPatcher`
* `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`

**Comment by valinet** [comment]
> @valinet the crashing happens on W11 taskbar for me and it seems for the others also, if changed to W10 taskbar it works fine

Tested with Windows 11 taskbar, seems to work. Interestingly, the console tells me that it looks like Microsoft removed the `Windows.Internal.Shell.XamlExplorerHost.XamlApplication` interface. Yeah, internal undocumented stuff is prone to changing without notice...

**Comment by Phoenix-** [comment]
Working fine for me with W11 taskbar, but crashes when I switch to W10 taskbar. All settings were reset previously with 'Restore default settings' option in About section of properties.
I can provide extra info if needed.

Windows 11 Pro 22H2
Build 22621.2070
Windows Feature Experience Pack 1000.22659.1000.0

**Comment by Garry050** [comment]
I guess I found workaround for that.
in my enviroment, ExplorerPatcher seems failed to download or read symbols from online (checked from console)
so i need to disable "Advanced" - "Enable symbols download *" from ExplorerPatcher properties
![image](https://github.com/valinet/ExplorerPatcher/assets/6926151/06fe615f-0afd-4a3c-86ed-e878e9392a82)


**DO NOT FORGET ENABLE THAT OPTION WHEN DEV FIXED THAT PROBLEM**

**Comment by valinet** [comment]
Symbol download fails when you are disconnected from the Internet, or your antivirus product/firewall/whatever blocks the download. On vanilla systems, the download works just fine.

**Comment by Garry050** [comment]
> Symbol download fails when you are disconnected from the Internet, or your antivirus product/firewall/whatever blocks the download. On vanilla systems, the download works just fine.

Uh, that was correct. but that's first time to blocking download or reading symbols by ESET. weird

**Comment by valinet** [comment]
> > Symbol download fails when you are disconnected from the Internet, or your antivirus product/firewall/whatever blocks the download. On vanilla systems, the download works just fine.
> 
> Uh, that was correct. but that's first time to blocking download or reading symbols by ESET. weird

Nah, it's classical antivirus shenanigans. There's also [this](https://github.com/valinet/ExplorerPatcher/discussions/1697#discussioncomment-6565243) that happened to some other guy. Antivirus vendors are a PITA.

**Comment by dayandnight-nomix** [comment]
When I put the taskbar to the right or left on screen, it crashes. By keeping it at the bottom, it works just fine!

**Comment by hypo-thesis** [comment]
> > > Symbol download fails when you are disconnected from the Internet, or your antivirus product/firewall/whatever blocks the download. On vanilla systems, the download works just fine.
> > 
> > 
> > Uh, that was correct. but that's first time to blocking download or reading symbols by ESET. weird
> 
> Nah, it's classical antivirus shenanigans. There's also [this](https://github.com/valinet/ExplorerPatcher/discussions/1697#discussioncomment-6565243) that happened to some other guy. Antivirus vendors are a PITA.

I don't even have an antivirus ( yes I believe in vaccination ) and this is happening to me.

**Comment by huqedato** [comment]
Same problem here. It needs update.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by piaoxue2000** [comment]
After uninstalling KB5028254, the EP works correctly.

**Comment by Vipin2003** [comment]
It works fine on every build..but on other builds, the notification panel is overlayed on taskbar and the taskbar notification button is inaccessible. I think thst something is changed

**Comment by p1gd0g** [comment]
Same here

**Comment by PRORITESH** [comment]
same here

**Comment by nljxlove** [comment]
I use the latest ExplorerPatcher on the new system version 22621.2070. Right clicking on the Taskbar will cause the resource manager to restart.

**Comment by pyrates999** [comment]
Scroll up for the fix.

**Comment by Garry050** [comment]
Please stop spamming (garbage) answer to every depend 22621.2070 issues.

**Comment by Vipin2003** [comment]
> > @valinet the crashing happens on W11 taskbar for me and it seems for the others also, if changed to W10 taskbar it works fine
> 
> Tested with Windows 11 taskbar, seems to work. Interestingly, the console tells me that it looks like Microsoft removed the `Windows.Internal.Shell.XamlExplorerHost.XamlApplication` interface. Yeah, internal undocumented stuff is prone to changing without notice...

It works fine but it have a little bug in insider builds that the Action center overlaps taskbar i win10 style. After which, taskbar tray icons are inaccessible until clicking on empty area. like this:

![2023-07-28_12h21_39](https://github.com/valinet/ExplorerPatcher/assets/93650504/b56d6fd4-b273-43df-8bc0-e17a3d3b06c4)

**Comment by XC3N** [comment]
@hypo-thesis @Garry050 why are you guys claiming it's a garbage/nonsense answer? The windows update I just installed and indeed made this issue happen on my system is a preview update. Furthermore, the link @pyrates999 posted shows the following:

_Symbols are usually NOT made available for the following types of builds:

builds shipped via the Beta and Release Preview channel of the Windows Insider Program
"C" and "D" stable OS builds - these are builds labeled as "Preview" and offered via Windows Update in the second part of a month, representative of what will generally arrive on the next Patch Tuesday; these are optional, the user has to explicitly click "Download and install" to have them applied on their computer, they are never automatically installed by Windows Update_

you guys are just being aggressive and not clearly explaining why you think this is incorrect information...

**Comment by hypo-thesis** [comment]
> @hypo-thesis @Garry050 why are you guys claiming it's a garbage/nonsense answer? The windows update I just installed and indeed made this issue happen on my system is a preview update. Furthermore, the link @pyrates999 posted shows the following:
> 
> Symbols are usually NOT made available for the following types of builds: builds shipped via the Beta and Release Preview channel of the Windows Insider Program "C" and "D" stable OS builds - these are builds labeled as "Preview" and offered via Windows Update in the second part of a month, representative of what will generally arrive on the next Patch Tuesday; these are optional, the user has to explicitly click "Download and install" to have them applied on their computer, they are never automatically installed by Windows Update.
> 
> you guys are just being aggressive and not clearly explaining why you think this is incorrect information...
> 
> ETA: I have two windows 11 systems set up to download preview updates, both have the same issue with EP, and both are fixed after uninstalling said update (KB5028254) I strongly suggest you tone down your attitudes a notch and understand that not everyone who has the same symptoms have the same issue, yours seem different and your attitude will prevent other users with the same issue from having the right fix because you dissuaded them to try...

Symbols are downloaded within a minute or two. The answer is irrelevant as it suggests to uninstall the updates instead of providing a solution. I am using the latest windows update and downloading the symbols were sufficient to get it running again hence making the answer nonsense.

**Comment by pyrates999** [comment]
> > @hypo-thesis @Garry050 why are you guys claiming it's a garbage/nonsense answer? The windows update I just installed and indeed made this issue happen on my system is a preview update. Furthermore, the link @pyrates999 posted shows the following:
> > Symbols are usually NOT made available for the following types of builds: builds shipped via the Beta and Release Preview channel of the Windows Insider Program "C" and "D" stable OS builds - these are builds labeled as "Preview" and offered via Windows Update in the second part of a month, representative of what will generally arrive on the next Patch Tuesday; these are optional, the user has to explicitly click "Download and install" to have them applied on their computer, they are never automatically installed by Windows Update.
> > you guys are just being aggressive and not clearly explaining why you think this is incorrect information...
> > ETA: I have two windows 11 systems set up to download preview updates, both have the same issue with EP, and both are fixed after uninstalling said update (KB5028254) I strongly suggest you tone down your attitudes a notch and understand that not everyone who has the same symptoms have the same issue, yours seem different and your attitude will prevent other users with the same issue from having the right fix because you dissuaded them to try...
> 
> Symbols are downloaded within a minute or two. The answer is irrelevant as it suggests to uninstall the updates instead of providing a solution. I am using the latest windows update and downloading the symbols were sufficient to get it running again hence making the answer nonsense. On top of that he has been spamming the same thing all over the relative questions. How is that gonna help anyone?

Because it's simple and gets to the point.

Fact's don't care whether you like them or not.  In the end, they are still true.

**Comment by XC3N** [comment]
@hypo-thesis idk, they didn't download on either of my system  after quite some time, and the PE documentation claims that symbols are not downloaded for preview updates... anyway, this is my last intervention here.

**Comment by Garry050** [comment]
Is that allowed to "spamming" to every issues? i dont think so.
its just annoying and still not get to point...

and its will come to next windows release. dev can work early to work solve to microsoft changed smth with that update by issues.

I don't mean to deny everything you, but nobody likes spamming the same thing over and over again.

**Comment by XC3N** [comment]
FWIW I don't disagree with the multiple comments part.

**Comment by hypo-thesis** [comment]
> > > @hypo-thesis @Garry050 why are you guys claiming it's a garbage/nonsense answer? The windows update I just installed and indeed made this issue happen on my system is a preview update. Furthermore, the link @pyrates999 posted shows the following:
> > > Symbols are usually NOT made available for the following types of builds: builds shipped via the Beta and Release Preview channel of the Windows Insider Program "C" and "D" stable OS builds - these are builds labeled as "Preview" and offered via Windows Update in the second part of a month, representative of what will generally arrive on the next Patch Tuesday; these are optional, the user has to explicitly click "Download and install" to have them applied on their computer, they are never automatically installed by Windows Update.
> > > you guys are just being aggressive and not clearly explaining why you think this is incorrect information...
> > > ETA: I have two windows 11 systems set up to download preview updates, both have the same issue with EP, and both are fixed after uninstalling said update (KB5028254) I strongly suggest you tone down your attitudes a notch and understand that not everyone who has the same symptoms have the same issue, yours seem different and your attitude will prevent other users with the same issue from having the right fix because you dissuaded them to try...
> > 
> > 
> > Symbols are downloaded within a minute or two. The answer is irrelevant as it suggests to uninstall the updates instead of providing a solution. I am using the latest windows update and downloading the symbols were sufficient to get it running again hence making the answer nonsense. On top of that he has been spamming the same thing all over the relative questions. How is that gonna help anyone?
> 
> Because it's simple and gets to the point.
> 
> Fact's don't care whether you like them or not. In the end, they are still true.

Let the dev team talk about facts please. In the meantime stop spamming the same comment all over this board.

**Comment by nljxlove** [comment]
Open "Do not modify the Taskbar context menu" in Advanced, and right click the Taskbar to restore it to normal.

**Comment by pyrates999** [comment]
> > > > @hypo-thesis @Garry050 why are you guys claiming it's a garbage/nonsense answer? The windows update I just installed and indeed made this issue happen on my system is a preview update. Furthermore, the link @pyrates999 posted shows the following:
> > > > Symbols are usually NOT made available for the following types of builds: builds shipped via the Beta and Release Preview channel of the Windows Insider Program "C" and "D" stable OS builds - these are builds labeled as "Preview" and offered via Windows Update in the second part of a month, representative of what will generally arrive on the next Patch Tuesday; these are optional, the user has to explicitly click "Download and install" to have them applied on their computer, they are never automatically installed by Windows Update.
> > > > you guys are just being aggressive and not clearly explaining why you think this is incorrect information...
> > > > ETA: I have two windows 11 systems set up to download preview updates, both have the same issue with EP, and both are fixed after uninstalling said update (KB5028254) I strongly suggest you tone down your attitudes a notch and understand that not everyone who has the same symptoms have the same issue, yours seem different and your attitude will prevent other users with the same issue from having the right fix because you dissuaded them to try...
> > > 
> > > 
> > > Symbols are downloaded within a minute or two. The answer is irrelevant as it suggests to uninstall the updates instead of providing a solution. I am using the latest windows update and downloading the symbols were sufficient to get it running again hence making the answer nonsense. On top of that he has been spamming the same thing all over the relative questions. How is that gonna help anyone?
> > 
> > 
> > Because it's simple and gets to the point.
> > Fact's don't care whether you like them or not. In the end, they are still true.
> 
> Let the dev team talk about facts please. In the meantime stop spamming the same comment all over this board.

The dev team only tests on releases, not not preview versions of updates from what I can tell.

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new version should never do irrecoverable crashes like these anymore. There should be no more major issues on 22621 builds up to 22621.2359.
