### ISSUE TITLE
Unable to update Explorer Patcher

### ISSUE THREAD

**Issue by LJB001** [valinet/ExplorerPatcher#1698]
I am currently running version 22621.1555.55.1

Explorer Patcher displays a start up message that version 22621.1992.56.1 is available and that I after right-clicking on the taskbar and selecting properties.  After doing that I left click on Restart File Explorer.  Explorer Patcher appears to restart but it does not upgrade itself to version 22621.1992.56.1; version 22621.1555.55.1 is still running.

I have restarted Windows but the process still does not work.

I am running Win-11 build 22621.1992 on an HP LAPTOP-M79FUT05 with processor 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.40 GHz and 8 GB of RAM.

**Comment by pyrates999** [comment]
In Explorer Patcher Properties:

1. go to updates
2. click on Update Program and Restart File Explorer

After it's done, you will get a notification that explorer patcher was updated.

**Comment by nikssj** [comment]
Same problem. Solution not working after last update from windows 11

**Comment by LJB001** [comment]
pyrates999 process above WORKS:

  1.  Right click on taskbar
  2. Left click on "Properties"
  3. Left click on "Updates"
  4. Left click on "Update program and restart File Explorer"

To get a warm/fuzzy confirmation:
  1. Right click on taskbar
  2. Left click on "Properties"
  3. Left click on "About"

**Comment by pyrates999** [comment]
Some clearly can't follow instructions.  So if you can't do that, just go here: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

**Comment by Fatima29h** [comment]
Upgrading to Explorer Patcher version22621.1992.56.1, right-click on the taskbar does not work. I have the same problem. I tried restrating file explorer on taskbar manager but it was not helpful.
