### ISSUE TITLE
Error when right-clicking on the taskbar

### ISSUE THREAD

**Issue by WhatsaMods** [valinet/ExplorerPatcher#1700]
With Windows 11 version 10.0.22621.2070, when upgrading to Explorer Patcher version 22621.1992.56.1, whenever I right-click on the taskbar, Windows File Explorer restarts, making it impossible for me to access to the right-click menu on the taskbar.

I have tried to uninstall and reinstall, even with previous versions, but the error persists. Is there any solution?

**Comment by Soldier874** [comment]
Same issue here and no fixes for the moment, wait and see :(

**Comment by Vipin2003** [comment]
Uninstall EP completely or let the FE (file explorer) to crash. After that, it will switch back to win11 taskbar...forcefully make symbols to download and restart the device

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by hypo-thesis** [comment]
> Uninstall EP completely or let the FE (file explorer) to crash. After that, it will switch back to win11 taskbar...forcefully make symbols to download and restart the device

What are symbols and how to make them download?

**Comment by 0Andras** [comment]
Sorry, how did you restart it without being able to right-click on the taskbar?

**Comment by Fatima29h** [comment]
Upgrading to Explorer Patcher version22621.1992.56.1, right-click on the taskbar does not work. I have the same problem. I tried restrating file explorer on taskbar manager but it was not helpful.

**Comment by WhatsaMods** [comment]
> That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8
> 
> Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

So do you recommend uninstalling the previous Windows update KB5028254?

I had the stable version of Explorer Patcher, when installing this update everything broke. I tried the latest version of Explorer Patcher and with the same problem, I uninstalled, rebooted and reinstalled, and everything remains the same, hopefully the problem will be fixed in the final version.

**Comment by WhatsaMods** [comment]
At the moment the solution that I have found to avoid having to uninstall the Windows update and continue with ExplorerPatcher installed, is to look for explorerpatcher in the windows search, run from there to the ExplorerPatcher configuration, and in the taskbar, put the Windows 10, but putting the visual configuration of Windows 11. The only visible difference compared to Windows 11 is that the start icon is a little smaller, but the rest is the same, and the right button works again on the taskbar.

**Comment by Girofox** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/43116061/d41a78a7-b645-48c3-b970-8cb8dac72d7c)
So it seems the latest cumulative update was listed as a regular update in some countries like Germany as you can see in attached screenshot. Is this the problem currently?

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by jshir** [comment]
KB5028254 is now part of KB5029263 and is an automatic update, not a preview. EP still does not function properly with KB5029263. Please address ASAP.

**Comment by Girofox** [comment]
There is a new cumulative update which tried to install on its own when i plugged in my charger! Cancelled it in taskmanager (process TiWorker.exe) because could not stop it in Windows update. In group policy i postponed all quality updates by 30 days so this not happen again, very annoying that Microsoft pushes cumulative updates even without prompt.

**Comment by pyrates999** [comment]
You gotta wait for it to be fixed then.

**Comment by hypo-thesis** [comment]
> You gotta wait for it to be fixed then.

Can you stop adding non-productive comments under every thread here? @valinet should really consider blocking you from any further comment. I am getting tens of emails because of your nonsense comments everyday.

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. There should be no more major issues on 22621 builds up to 22621.2359.
