### ISSUE TITLE
Can't pin to Win10 live tile mode start menu

### ISSUE THREAD

**Issue by CAT5NEKO** [valinet/ExplorerPatcher#1704]
## Sysinfo🔧
OS: Windows11　22H2
EP: 22621.1992.56.1

## About🤯
In the current version update, Windows standard apps and apps purchased from the MS store have been corrected so that they are displayed in Win10 StartMenu mode, but next all apps can no longer be pinned to live tiles.

## Desired behavior😊
App of StartMenu can be pinned to live tile part.

**Comment by pyrates999** [comment]
Please post windows build.

**Comment by Vipin2003** [comment]
You can do that...check out the important:must read point in start menu section

**Comment by pyrates999** [comment]
known issues: https://github.com/valinet/ExplorerPatcher/discussions/1679
