### ISSUE TITLE
EP keeps crashing after Windows Update

### ISSUE THREAD

**Issue by Lh50gcrl** [valinet/ExplorerPatcher#1707]
Hi

EP no longer stays open and crashes multiple times in quick succession.  This then displays the message saying that due to the high amount of crashes in less than 10 seconds, it's suggested to update EP or uninstall.

I've updated EP but it still crashes.

Any suggestions on how to resolve?

**Comment by ahamling27** [comment]
Uninstall the latest windows update preview. It worked for me.

**Comment by Lh50gcrl** [comment]
Are you talking about update KB5028254?

**Comment by Lh50gcrl** [comment]
I uninstalled KB5028254 and this also worked for me.  I presume whatever the issue is will be patched/fixed on a future update because I also presume at some point in the future, I'll be prompted to install this update again.

**Comment by ahamling27** [comment]
> Are you talking about update KB5028254?

Yes, but I see you figured that out. Yeah, hopefully they’ll release an update between the preview and the release of this windows update.

**Comment by darkpixlz** [comment]
I'm experiencing this as well, my explorer crashes every 30 seconds and it's getting really annoying

**Comment by pinyball2** [comment]
Same aswell, but I can't revert the update due to "the files we need to take you back to a previous version of windows were removed from this PC", despite only updating yesterday.
Obv I know to uninstall till an update comes around for EP, but hope it happens soon.
![image](https://github.com/valinet/ExplorerPatcher/assets/84483269/3f165f66-96f0-41eb-ae20-fbded1d88975)

**Comment by Lh50gcrl** [comment]
I didn’t revert Windows, I just uninstalled that specific update KB5028254

**Comment by pinyball2** [comment]
> I didn’t revert Windows, I just uninstalled that specific update KB5028254

My bad, didnt have a situation to uninstall specific updates before. Got it sorted now

**Comment by Vipin2003** [comment]
> > I didn’t revert Windows, I just uninstalled that specific update KB5028254
> 
> My bad, didnt have a situation to uninstall specific updates before. Got it sorted now

Uninstall that using "view installed updates" option from classic programs and apps.

**Comment by bigfloppa234** [comment]
I have the same issue, despite uninstalling the update and disabling updates Windows kept reinstalling, and now I can't uninstall the update. What can I do until this gets fixed?

**Comment by ahamling27** [comment]
You’ll probably have to uninstall Explorer Patcher until they can address it unfortunately. :/

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

**Comment by BenjaminWKI** [comment]
Follow [these instructions](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555) to fix the issue ... and you don't need to uninstall the Windows 11 update.

**Comment by Poopooracoocoo** [comment]
KB5028254 and 22621.2070 was a preview update
