### ISSUE TITLE
Duplicate: Move taskbar permanently to secondary monitor

### ISSUE THREAD

**Issue by Riam-Mar** [valinet/ExplorerPatcher#171]
This is probably more a feature request, than a bug issue, since the Windows 11 built-in taskbar features are in many places inferior to previous windows versions. Especially with the taskbar focused being on the main display.

With ExplorerPatcher, it is really nice to be able to drag and drop the taskbar to the side of the screen and even to the secondary monitor, like in i.e. Windows 10. That is where I like to keep my taskbar, on the right side of my secondary monitor.

After every restart of the explorer process, or windows itself, the taskbar keeps the position, e.g. right or bottom side, but skips back to the main monitor. Is there a way to keep it on the secondary monitor permanently?

Switching the secondary and main monitor is not an option for me and dragging the taskbar over to the secondary screen once in a while isn't that big of a deal, but it would be quite convenient if it would stay there.

Current OS Build 22000.282, happened in 22000.258 as well.
ExplorerPatcher version 22000.258.31.1 and previous

**Comment by PINPAL** [comment]
Any updates regarding this? I have been able to move the taskbar to the left side of the right monitor and it persists between restarts however when opening any fullscreen application (like games) on the primary monitor the taskbar visually remains where it was but is treated as if it on the primary monitor:
The taskbar visually appears to be where it was however the "space" that is occupies is applied to the primary monitor meaning maximised windows have a empty bar showing the desktop on the primary.
Windows maximised on the secondary monitor where the taskbar visually is can be maximised to cover up the taskbar.

**Comment by FaySmash** [comment]
> Any updates regarding this? I have been able to move the taskbar to the left side of the right monitor and it persists between restarts however when opening any fullscreen application (like games) on the primary monitor the taskbar visually remains where it was but is treated as if it on the primary monitor: The taskbar visually appears to be where it was however the "space" that is occupies is applied to the primary monitor meaning maximised windows have a empty bar showing the desktop on the primary. Windows maximised on the secondary monitor where the taskbar visually is can be maximised to cover up the taskbar.

What version are you using? And you have enabled only one Taskbar? I don't have any problems anymore using 22000.469.41.16 and having Taskbars on all monitors at the bottom (like seen on my previous comment)

**Comment by PINPAL** [comment]
> > Any updates regarding this? I have been able to move the taskbar to the left side of the right monitor and it persists between restarts however when opening any fullscreen application (like games) on the primary monitor the taskbar visually remains where it was but is treated as if it on the primary monitor: The taskbar visually appears to be where it was however the "space" that is occupies is applied to the primary monitor meaning maximised windows have a empty bar showing the desktop on the primary. Windows maximised on the secondary monitor where the taskbar visually is can be maximised to cover up the taskbar.
> 
> What version are you using? And you have enabled only one Taskbar? I don't have any problems anymore using 22000.469.41.16 and having Taskbars on all monitors at the bottom (like seen on my previous comment)

22000.469.41.16 The issue I'm having is that I want the taskbar to just be on one monitor (but not the primary), this is how I've always had it set up for many years which allows me to still access the taskbar when in fullscreen applications without wasting any space on the primary display.

**Comment by valinet** [comment]
Okay, so what's the problem, this has been implemented for quite a while now. Try with the latest pre-release, but I remember implementing it long ago, so I strongly believe it is in 22000.469.41.16 as well, as far as I remember. I am able to have only a primary taskbar displayed and move it to whatever monitor and it sticks there after a restart just fine.
