### ISSUE TITLE
PC unusable after opening ep_setup.exe.

### ISSUE THREAD

**Issue by nachito9380** [valinet/ExplorerPatcher#1711]
I've opened ep_setup.exe and now my PC is constantly flashing the screen. I can't do anything except open task manager. I've tried uninstalling the latest quality updates. Nothing. Loading up a restore point. Doesn't work (says it can't complete the restore). Booting in safe mode. Still flashing the screen. My only option is to load up troubleshooting and use the command prompt, but idk how to uninstall it from there. Can anyone help please?

**Comment by IliasKs** [comment]
SOS - Same here. Exactly the same. The computer is useless. Only access to Task Manager, which is actually flashing programs and makes too difficult to work it. Safe mode too. Is there a means by terminating a process or a program in Task Manager , to stabilize the system??

**Comment by IliasKs** [comment]
Problem just solved! - Go to New Task - Type Control Panel - Open Programs Manager - Uninstall Explorer Patcher
Tip: As your pc flashes continuously, type "control Panel" at the top search bar of Task Manager and cut-paste to the New Task window. It worked for me, entered the programs management, uninstalled the program and returned to my computer....

**Comment by nachito9380** [comment]
> Problem just solved! - Go to New Task - Type Control Panel - Open Programs Manager - Uninstall Explorer Patcher Tip: As your pc flashes continuously, type "control Panel" at the top search bar of Task Manager and cut-paste to the New Task window. It worked for me, entered the programs management, uninstalled the program and returned to my computer....

I've deleted the files and uninstalled the program and the screen is still flashing. Is there anything else I can do to fix this?

**Comment by nachito9380** [comment]
> Problem just solved! - Go to New Task - Type Control Panel - Open Programs Manager - Uninstall Explorer Patcher Tip: As your pc flashes continuously, type "control Panel" at the top search bar of Task Manager and cut-paste to the New Task window. It worked for me, entered the programs management, uninstalled the program and returned to my computer....

I gave up and ended up resetting my PC with a fresh install of windows 11. That seems to have fixed the problem. At least all my files are safe and sound. Thanks for helping anyways.

**Comment by BraINstinct0** [comment]
No need to reset, deleting the files first is the cause. Actually if you can access the terminal or installation file, reinstalling and uninstalling can solve it. The uninstaller is bundled within the installer (iirc), so deleting files will inevitably break it. It's actually explicitly noted NOT to do it that way, as I rememeber

**Comment by pyrates999** [comment]
Here's how to uninstall for future cases: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To
