### ISSUE TITLE
Setting taskbar style to windows 10 disables touchpad gestures

### ISSUE THREAD

**Issue by KarkanAlzwayed** [valinet/ExplorerPatcher#1716]
Like the title says, setting the taskbar to Windows 10 disables the touchpad gestures. No more 3 finger swipe up for overview or to tile windows left and right, nothing works beside the normal scrolling and clicking. Not sure if there is a setting for that or if it's a bug.

ExplorerPatcher Version: 22621.1992.56.1

Edition: Windows 11 Home
Version: 22H2
Installed on: ‎7/‎12/‎2023
OS build: 22621.2070
Experience: Windows Feature Experience Pack 1000.22659.1000.0

**Comment by BraINstinct0** [comment]
It is linked to the Window Switcher. Setting it to Windows 11 style might help, as it worked for me.
