### ISSUE TITLE
Setting Shortcut in Win 10 Start Menu

### ISSUE THREAD

**Issue by nafisuling** [valinet/ExplorerPatcher#1726]
Hello, is there a setting to add the Settings app shortcut to the Win 10 start menu?

**Comment by Vipin2003** [comment]
It was already there...update to latest EP

**Comment by nafisuling** [comment]
I just downloaded it today, so I'm sure it's the latest version, but it's not there.

If there's a setting for it, please tell me where to find it as I might've missed it

![image](https://github.com/valinet/ExplorerPatcher/assets/92410089/79af8d85-b990-4ddb-9d56-8b92b04844c8)

And for avoidance of doubt, this is what I mean:

![image](https://github.com/valinet/ExplorerPatcher/assets/92410089/ec5715b2-ea4a-4370-9f9c-9d80f3accedf)

**Comment by Amrsatrio** [comment]
This should be fixed in the latest release. Open Personalization > Start > Folders or something, and you can configure there.
