### ISSUE TITLE
Task view and Cortana (windows 10 1903 or later only) icon missing and not working properly on windows 10

### ISSUE THREAD

**Issue by TK50P** [valinet/ExplorerPatcher#1727]
I using explorerpatcher on windows 10
but always task view icon is missing (somethime press start button, it works)
Was it fixed or not?

![missing](https://github.com/valinet/ExplorerPatcher/assets/127497974/31b223db-5983-4717-809b-2d449d9f7e8e)

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

Also: https://www.theverge.com/2023/6/2/23747162/microsoft-windows-ai-cortana-end-support

**Comment by TK50P** [comment]
Version is Windows 10 and Build number is 1809 (17763.1075)
ExplorerPatcher version is 22621.1992.56.1

**Comment by pyrates999** [comment]
Support for 1809 ended in November 10, 2020.  Please update to a newer version.
