### ISSUE TITLE
Add a option to turn the task bar search bar on and off

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#1732]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1667

<div type='discussions-op-text'>

<sup>Originally posted by **Cherrrrryyy** July 25, 2023</sup>
I don't know if it's just an issue for me but I can't get the search bar on my task bar, if this is simply not able to be implemented then that's my bad it is probably written somewhere, if it isn't though I would very much appreciate this feature and think other people would too :3</div>

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.

**Comment by Poopooracoocoo** [comment]
Duplicate of #1667
