### ISSUE TITLE
[Feature Request] Windows 10 News and interests

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#1733]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1674

<div type='discussions-op-text'>

<sup>Originally posted by **XuanChen1234** July 26, 2023</sup>
![Annotation 2023-06-06 093201 (2)](https://github.com/valinet/ExplorerPatcher/assets/140480110/1ccdc339-57fa-4a5b-9b42-e1ce6aa48760)
If it is not planned yet, I hope this will be a thing in the next update.
</div>

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.

**Comment by Poopooracoocoo** [comment]
Duplicate of #1674
