### ISSUE TITLE
[Feature Request] Windows 8.1 Start Screen, there is only "Desktop" tiles

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#1735]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1688

<div type='discussions-op-text'>

<sup>Originally posted by **XuanChen1234** July 27, 2023</sup>
![R-C](https://github.com/valinet/ExplorerPatcher/assets/140480110/fe361135-e99f-4b72-a868-29cff12d6cbf)
</div>

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.
