### ISSUE TITLE
Cant open properties menu

### ISSUE THREAD

**Issue by SELEKCJONER** [valinet/ExplorerPatcher#1736]
I use newest ExplorerPatcher version and I am unable to open properties menu on my windows 10 10.0.14393 

Properties is not showing up after right clicking on taskbar and runing command rundll32.exe C:\Windows\dxgi.dll,ZZGUI gives me cant find specified procedure error. Other than that nothing crashes and i probably still can change settings through registry.

![image](https://github.com/valinet/ExplorerPatcher/assets/136343482/f43fddce-004f-4d55-9259-2beb021d190b)
![image](https://github.com/valinet/ExplorerPatcher/assets/136343482/1fa66191-e813-4333-9314-e2dbb85b1ed1)

**Comment by SELEKCJONER** [comment]
update registry entries didnt exist and i tried to manually make this one HKEY_CURRENT_USER\Software\ExplorerPatcher\sws with value dword32 IncludeWallpaper set to 1 to no effect after restarting explorer.exe process and running again setup program

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by SELEKCJONER** [comment]
Well i already said i use newest explorer patcher version which is this release at the moment https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541

and my windows version is this one Version 10.0.14393 its from 2016 


its preety old i know but updating it makes me unable to log on i have restored it 2 times from cloned disk image because of this so updating is not an option for me 

Also this version of explorer patcher works perfectly fine on my laptop with newest windows 11

**Comment by pyrates999** [comment]
I would try doing a reinstall from the version of windows that you're running.  Then try updating to the current release.

**Comment by Amrsatrio** [comment]
Really sorry for the long and unexpected response but, we have decided to cut support for Windows 10 versions older than 17763. If you're rocking LTSC then I advise you to upgrade to it if you want to keep using EP.

<img width="399" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/6d1a12a3-0e3d-4126-a0ac-b2b7cda39a16">
