### ISSUE TITLE
[bug] Determine whether the file exists before downloading the required file & Repeated downloads by different users & Unable to restart normally when downloading takes too long

### ISSUE THREAD

**Issue by xxxxj-up** [valinet/ExplorerPatcher#1737]
For those located in China, the download of required files is very slow. Can the download link be output on the terminal. Before downloading, check whether the local file is consistent with the downloaded file. If it is the same, use the downloaded file directly

**Comment by xxxxj-up** [comment]
Repeated downloads by different users

**Comment by xxxxj-up** [comment]
I have read the code. I think we should separate the download section from the link splicing section and use the link as a value for the download

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.

**Comment by xxxxj-up** [comment]
Unable to restart normally when downloading takes too long

**Comment by xxxxj-up** [comment]
> Issues are for bugs only, not feature requests.

ok... I have reclassified it, but these are actually three bugs

**Comment by pyrates999** [comment]
It's a new feature request.  Please move it to discussions.

**Comment by Amrsatrio** [comment]
Latest EP does not have file downloads during setup anymore.
