### ISSUE TITLE
Everything working, but taskbar is black, half height, icons are extremely small, text black

### ISSUE THREAD

**Issue by HenryTheVacuum** [valinet/ExplorerPatcher#1740]
See title and screenshot below

[https://i.imgur.com/zeg7Utt.png](https://i.imgur.com/zeg7Utt.png)

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by HenryTheVacuum** [comment]
Window 11 Home Build 22621.ni_release.220506-1250

**Comment by HenryTheVacuum** [comment]
Window 11 Home

Build 22621.ni_release.220506-1250

**Comment by pyrates999** [comment]
Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install the latest explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by HenryTheVacuum** [comment]
This worked, thanks.
