### ISSUE TITLE
[Feature Request] Windows Vista/7 style switcher (3D Aero Flip)

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#1742]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1669

<div type='discussions-op-text'>

<sup>Originally posted by **XuanChen1234** July 26, 2023</sup>
Is it Possible to integrate the Flip3D Design for App Switcher?
If it is not planned yet, I hope this will be a thing in the next update.
![3D Aero Flip](https://github.com/valinet/ExplorerPatcher/assets/140480110/5e738df7-2b76-4ae1-aaf6-15ed2ebabab1)
https://github.com/valinet/ExplorerPatcher/discussions/1381
</div>

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.
