### ISSUE TITLE
[Feature request] Option to clear symbols cache and force them to re-download

### ISSUE THREAD

**Issue by Caesar008** [valinet/ExplorerPatcher#1748]
Hi,
It would be good to have some option in EP menu to clear symbols cache and force them to redownload in case of issues.
Or have this feature in installer so it removes all EP records during uninstall/repair (configuration can be kept).
I had to search and then do that manually after July 2023 cumulative updates (Windows 11 X64) when it was not downloading symbols (thinking I have latest one) and thus crashing to BSOD.
Standard uninstall did not help (uninstall - reboot - install - reboot), still was crashing to BSOD.
In my case I had to uninstall EP, remove folders %appdata%\ExplorerPatcher (as symbols are most probably here) and C:\Program Files\ExplorerPatcher (not sure if this one was necessary to remove), and registry key HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell. Then I installed EP, let it to download symbols again, and after all that it was OK and did not crashed.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by Caesar008** [comment]
I was not aware of discussion section and that ideas are there (some projects - including me - handle ideas and feature requests in issues section)
