### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by leserg73** [valinet/ExplorerPatcher#175]
I translated the interface lines in the settings.reg file into Russian.
The encoding of the settings.reg file is UTF-8 with BOM.
Then I replaced in the file dxgi.dll resource RCData->101 on the localized.
After launching in the properties window all lines with the label "**;x** " 
are displayed _incorrectly_ (see attached screenshots).

Could you please fix this.
Thank you for the very useful tool.

![NotCyrillic](https://user-images.githubusercontent.com/67634778/138442063-1f80c077-9810-4254-a145-f7840d67bb4a.png)

![NotCyrillic01](https://user-images.githubusercontent.com/67634778/138447362-8551e19d-5415-4fdf-ae7b-5a1d70417258.png)

**Comment by Galixte** [comment]
[settings.reg_french.zip](https://github.com/valinet/ExplorerPatcher/files/7503433/settings.reg_french.zip)
Hi @valinet,

Thanks for your tool, it’s very usefool and appreciated!

Please find the FRENCH translation of ExplorerPatcher settings.reg file.

Regards.

**Comment by Hunter23071985** [comment]
Please add the translation of **leserg73** to the About section of Properties window.

**Comment by pyrates999** [comment]
> Please add the translation of **leserg73** to the About section of Properties window.

Please open a new discussion as this has been closed for over 2 years.
