### ISSUE TITLE
Start menu position and corner settings doesn't work on Windows 10

### ISSUE THREAD

**Issue by logoffon** [valinet/ExplorerPatcher#1750]
I know that this is a duplicate of #1288 and #1354, but neither of those provided any useful information beyond "this doesn't work", so I decided to open a new issue for this bug.

Apparently, this bug have been happening since at least version [22621.819.52.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.819.52.1_02cb6e9), as the version immediately before it ([22621.608.51.6](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.608.51.6_d262c41)) still have the options working fine. It's also worth noting that this bug does not happen on Windows 11.

Below this is a video installing different versions of EP on latest version of Windows 10 (build 19045.3208) to demonstrate this bug:

https://cdn.discordapp.com/attachments/918883942470406194/1135841006835728444/vmware_2023-08-01_14-41-19.mp4

As I mentioned above, this bug does not happen on Windows 11 (at least the latest version, 22621.2070) as demonstrated below:

https://cdn.discordapp.com/attachments/918883942470406194/1135896463591886900/8mb.video-zK3-9v6qfDTG.mp4

(Be aware that Explorer crashes sporadically when the first two versions are installed. If you're sensitive to flashing images, consider yourself warned before watching the video above.)

**Comment by pyrates999** [comment]
Looks like Microsoft has fixed it then with the current preview update.

But then preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by logoffon** [comment]
https://github.com/valinet/ExplorerPatcher/assets/7828523/e145c822-5d77-4ce8-8612-f8c8ec78060a

If you mean 19045.3271: no, it still has this bug.

**Comment by pyrates999** [comment]
That is also a preview update: https://support.microsoft.com/en-us/topic/july-25-2023-kb5028244-os-build-19045-3271-preview-8cf92c9b-3a60-4c6a-8f4c-fc41fe8f4f2c

I would uninstall it.

**Comment by logoffon** [comment]
You should've clarified that I should test this without any updates installed.
Anyway, here's a clean install of 22H2 with an ISO from May 2023 (19045.2965) that has no further updates installed demonstrating the bug.

https://github.com/valinet/ExplorerPatcher/assets/7828523/65580bae-a357-45f1-a8fb-ba5669d8eebb

**Comment by pyrates999** [comment]
Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install the latest explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

Then when recreating this bug, open up the properties application for explorer patcher, go to advanced, and click on enable console.  Post the results here.

**Comment by logoffon** [comment]
Did a clean install and installed the latest stable update. The bug continues to happen, and I'm not getting any relevant console output:

https://github.com/valinet/ExplorerPatcher/assets/7828523/4ad9c594-2f9b-4460-acd1-fd0e390b8562


https://github.com/valinet/ExplorerPatcher/assets/7828523/d75db95a-5c66-4c70-8637-c20fe774417f

**Comment by pyrates999** [comment]
I think those options are only for windows 11, not windows 10.  I don't even think windows 10 has any rounded corners.

**Comment by logoffon** [comment]
Please refer to the first video in original post, as the version [22621.608.51.6](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.608.51.6_d262c41) have those options working on Windows 10 but versions after that broke them, so that statement doesn't make sense unless they actually make it 11-only and ended up being an oversight.

**Comment by max1c** [comment]
Same issue. Build 22621.2134 the position on screen center doesn't work.

**Comment by logoffon** [comment]
> Did you try https://github.com/valinet/ExplorerPatcher/releases/tag/22621.608.51.6_d262c41 against your current version of windows 10 22h2 19045.3208 to see if these options work?

Apologies for the delay, but here it is.

https://github.com/valinet/ExplorerPatcher/assets/7828523/44c74d67-e78d-4ce3-9ca6-e7c105a14d01

**Comment by pyrates999** [comment]
Ok, thanks.

**Comment by logoffon** [comment]
Fixed in [release 22621.1992.56.3](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.3_5bda71f). 👍
