### ISSUE TITLE
[BUG] Right-click on taskbar crashes Explorer

### ISSUE THREAD

**Issue by xPumaa** [valinet/ExplorerPatcher#1756]
Pretty much what the title says. 
I updated my Windows 3 hours ago and then ExplorerPatcher wanted to update.
Right clicking didn't work at all, because of the crashes, so I installed the update manually, but the crashes remained.

I enabled the console and hoped I would see something there, but I found nothing.

_Edit: When I enable the option "Do not change the taskbar context menu...", the Explorer doesn't crash._

This is the output of the console
```
funchook create 1
Running on Windows 11, OS Build 10.0.22621.2070.
Loaded symbols
Setup ntdll functions done
Setup user32 functions done
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
Progman: 922842
Progman hook: 398813
0 0
Error in sub_1800135EC on RoGetActivationFactory.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.1992.56.1.b50a7e3beffb83cf"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.1992.56.1.b50a7e3beffb83cf" (valid).
[Updates] Local version obtained from hash is 22622.1992.56.1.
[Updates] No updates are available.```

**Comment by chojann** [comment]
x2

**Comment by zcmir2** [comment]
me too

**Comment by YDITC** [comment]
I can confirm this as well, also uninstalling using the Win11 GUI doesn't remove the program, and uninstalling with the ep_setup.exe /uninstall command keeps the program running and the explorer closed, so you can only start the explorer manually and kill the uninstaller running in the background.

**Comment by kommando828** [comment]
x5

**Comment by BenjaminWKI** [comment]
Follow [these instructions](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555) to fix the issue ... and you don't need to uninstall the Windows 11 update.

**Comment by BinToss** [comment]
Alternatively...
[In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu (...)".](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6622912)
![image](https://github.com/valinet/ExplorerPatcher/assets/7243190/08e9450b-9df0-4cae-bed6-f11651eb14ec)

**Comment by 2hug** [comment]
> Follow [these instructions](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555) to fix the issue ... and you don't need to uninstall the Windows 11 update.

Thanks!

**Comment by XxJooO** [comment]
> Alternatively... [In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu (...)".](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6622912) ![image](https://user-images.githubusercontent.com/7243190/257988639-06120080-8260-4c95-b01b-cade750f8909.png)

Unfortunately this does not work for me. Hopefully it will soon be fixed! The program is very helpful.

**Comment by pyrates999** [comment]
If you can't wait for it to be fixed, you could just uninstall the preview update.

**Comment by HumanMus1c** [comment]
+1

**Comment by StevenCN1892** [comment]
+1

**Comment by barbudor** [comment]
> Alternatively... [In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu (...)".]

Thanks @BinToss that worked for me

I don't have the "Get the latest updates as soon as available" ticked, and the last previexw that was install was back in june

**Comment by Poopooracoocoo** [comment]
KB5028254 and 22621.2070 was a preview update

**Comment by CogitoICT** [comment]
If right clicking on your desktop restarts the explorer, or when using right click on files and folders in Windows Explorer crashes it, go to the properties of ExplorerPatcher -> 'File Explorer' -> untick 'Disable the Windows 11 context menu'.
