### ISSUE TITLE
File Explorer > Control Interface Doesn't Work

### ISSUE THREAD

**Issue by Meddi1980** [valinet/ExplorerPatcher#1757]
File Explorer > Control Interface: Windows 10 Ribbon,  and  Windows 7 Command Bar   both don't appear to be working.

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by Meddi1980** [comment]
Windows 11 Pro version: 22H2 (OS Build 22621.2070)
Explorer Patcher version: 22621.1992.56.1

While we're at it, the Weather taskbar widget disappears once in a while and turns into the People icon.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Meddi1980** [comment]
Thanks for the suggestion. However I still can't get this to work. I uninstalled kb5028254, unticked "Get the latest updates as soon as available", restarted Windows a couple of times... My winver is now: 22621.1992

**Comment by BenjaminWKI** [comment]
Follow [these instructions](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555) to fix the issue ... and you don't need to uninstall the Windows 11 update.

**Comment by pyrates999** [comment]
I would advise you don't install preview updates.  Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Meddi1980** [comment]
> Follow [these instructions](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555) to fix the issue ... and you don't need to uninstall the Windows 11 update.

Yes, I followed the instructions to a tee, and still can't get Win10 style ribbons in Explorer. The fact that ExplorerPatcher even exists with all these options is a blessing... All the other options work beautifully EXCEPT for this one thing.

**Comment by BennyBu1234** [comment]
I have the same problem.
Windows 11 Pro version: 22H2 (OS Build 22621.1992)
Explorer Patcher version: 22621.1992.56.1
The problem appeared only in one computer. For other computer this function works good.

**Comment by pyrates999** [comment]
Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install the latest explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by Amrsatrio** [comment]
Disable this: https://github.com/valinet/ExplorerPatcher/issues/1337#issuecomment-1530201994

With that disabled, I experience no issues on 22621.1992 and newer.
