### ISSUE TITLE
[Feature Request] Disable new search box in Windows 11 start menu/search home

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#1762]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1713

<div type='discussions-op-text'>

<sup>Originally posted by **XuanChen1234** July 29, 2023</sup>
![LXUfR5q9PckFqqHAoP9gdj](https://github.com/valinet/ExplorerPatcher/assets/140480110/ebb61619-127d-4a01-9298-fcb648b7a496)
</div>

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by Poopooracoocoo** [comment]
Duplicate of #1713
