### ISSUE TITLE
[bug] If I restart explorer.exe, the buttons on the taskbar will be combined.

### ISSUE THREAD

**Issue by hellolin-oi** [valinet/ExplorerPatcher#1768]
I prefer not to merge the buttons on the taskbar. I made the following settings:

- Go to Settings > Personalization > Taskbar > Taskbar behaviors, and change the "Combine taskbar buttons and hide labels" option to "When task bar is full".

Everything looks fine. But when I restart explorer.exe (or restart my device), I find that the buttons on the taskbar are merged again without any other operations.

Although it worked fine again after changing the option in the Settings App, I still hope for a better solution to replace it. Thanks!

---

OS: Windows 11 Pro for Workstations Insider Preview

Version: 22H2 (Build 23511.1000)

EP: v22621.1992.56.1

**Comment by hellolin-oi** [comment]
My EP settings:

[ExplorerPatcher_22621.1992.56.1.zip](https://github.com/valinet/ExplorerPatcher/files/12251093/ExplorerPatcher_22621.1992.56.1.zip)

**Comment by pyrates999** [comment]
Uninstall explorer patcher, reboot, and see if this is still happening.

**Comment by hellolin-oi** [comment]
> Uninstall explorer patcher, reboot, and see if this is still happening.

The buttons aren't combined after restarting.

**Comment by pyrates999** [comment]
Then this is a bug in windows, not in explorer patcher.

**Comment by hellolin-oi** [comment]
> Then this is a bug in windows, not in explorer patcher.

Sorry, you may have missed my point.

I mean if I uninstall EP and restart my device, the "Combine taskbar buttons and hide labels" option will not be changed. As I hope, the buttons are not combined.

But if EP is installed and I restart my device, the option will be changed, and I have to change it again.

**Comment by pyrates999** [comment]
Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install the latest explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by hellolin-oi** [comment]
> Try the following:
> 
> 1. uninstall explorer patcher
> 2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
> 3. reboot
> 4. install the latest explorer patcher
> 5. verify you get a notification that symbols have been downloaded
> 6. restart windows explorer using either the task manager or in the properties window of explorer patcher
> 7. reboot
> 
> Then apply your settings again in explorer patcher to see if it fixes it.

It isn't fixed.

Btw, I've found that if I change the "Taskbar style" option (In Explorer Patcher) to "Windows 10", and change the "Combine taskbar icons on primary taskbar" option to "Combine when taskbar is full", it will be fixed.

But, if I also use "Simple Window Switcher" as window switcher style, actually it will be shown as Windows NT style.

**Comment by pyrates999** [comment]
ok, glad you found a work around.
