### ISSUE TITLE
Patcher not working on new dev Build 2129

### ISSUE THREAD

**Issue by Rahliah** [valinet/ExplorerPatcher#1769]
Have the latest version of explorer patcher installed but after the install of 22631.2129 last night I'm no longer able to access the patcher and Windows has reverted back to normal Win 11 taskbar.  Have restarted explorer several times, rebooted and reinstalled the patcher none of this works.

**Comment by Daisyfan1995** [comment]
me too, happends same. in lastest build in Beta Insider:
https://blogs.windows.com/windows-insider/2023/08/02/announcing-windows-11-insider-preview-build-22621-2129-and-22631-2129/

Sorry for 4k Resolution.

Windows 11 - 10.0.22631 2129 Windows 10 Taskbar no working
![windows 11 - 10 0 22631 2129 v1](https://github.com/valinet/ExplorerPatcher/assets/65993904/1ed404ae-001a-4266-a1d7-c119dc2ee638)

Windows 11 10.0.22731.2115
![windows 11 - 10 0 22631 2115 v1](https://github.com/valinet/ExplorerPatcher/assets/65993904/cd2cacd2-9b02-4664-bfca-e1b071d4bbac)

![2129](https://github.com/valinet/ExplorerPatcher/assets/65993904/812ed521-b6d5-41a3-abe0-1cc5139e14d4)
![2115](https://github.com/valinet/ExplorerPatcher/assets/65993904/849c70bd-8328-4b6f-86e4-5befc70a58f8)

**Comment by hlth-pro** [comment]
Thanks @Rahliah & @Daisyfan1995 for the heads-up. Uninstalled Patcher prior to updating to Windows build 2129. Will await update to Patcher before re-installing it.

**Comment by pyrates999** [comment]
To avoid preview updates automatically installing, in the settings app, untick "Get the latest updates as soon as available".

**Comment by hlth-pro** [comment]
> To avoid preview updates automatically installing, in the settings app, untick "Get the latest updates as soon as available".

Unticked for me, but it's the Windows update that is the problem. Computer press have highlighted ExplorerPatcher breaking the Start Menu with the latest Windows update (citing reliance on undocumented hooks).

- https://www.yahoo.com/lifestyle/windows-11-customization-apps-might-140703167.html
- https://www.yahoo.com/lifestyle/windows-11-third-party-apps-211543906.html
- https://www.inferse.com/645856/microsoft-windows-11-kb5028254-start-menu-not-starting-with-third-party-apps/

**Comment by Daisyfan1995** [comment]
To New update of Windows 11 10.0.22631.2134 (Release Update) 2023-08-08 is no happened

https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

![image](https://github.com/valinet/ExplorerPatcher/assets/65993904/de9e993b-6163-4f21-9432-ab8162b968ff)
![image](https://github.com/valinet/ExplorerPatcher/assets/65993904/1e61b528-8527-4ba7-9fc6-a9e82316ce01)

**Comment by Daisyfan1995** [comment]
To New update of Windows 11 10.0.22631.2134 (Release Update) 2023-08-08 is no happened

https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

![image](https://github.com/valinet/ExplorerPatcher/assets/65993904/1fc93221-5225-48f4-89bc-cad2dfc2d080)
![image](https://github.com/valinet/ExplorerPatcher/assets/65993904/094842ad-f329-4acf-9ffb-80934a1ddd7c)

**Comment by pyrates999** [comment]
Now you gotta wait for these bugs to be fixed.

**Comment by Daisyfan1995** [comment]
> Now you gotta wait for these bugs to be fixed.

This Capture Is Captured in My Laptop

**Comment by Daisyfan1995** [comment]
Same Problem in 2191 https://blogs.windows.com/windows-insider/2023/08/10/announcing-windows-11-insider-preview-build-22621-2191-and-22631-2191/

**Comment by Poopooracoocoo** [comment]
EP is not compatible with Insider builds
