### ISSUE TITLE
Explorer.exe crash with Windows 11 Command Bar

### ISSUE THREAD

**Issue by saucyknave** [valinet/ExplorerPatcher#1770]
Windows 11 22H2, OS Build 22621.2070
Explorer Patcher version 22621.1992.56.1

Explorer.exe is crashing on me, consistently every other time I open the file manager.  It's pretty clear it's because of Explorer Patcher.  If I uninstall EP, the problem goes away.  

I was able to narrow it down to a particular setting combination.  I noticed that when the file manager (explorer.exe) crashes, the Windows 11 command bar is blank.  So I found the "Control Interface" setting in EP (Properties -> File Explorer -> Control Interface). 
 The default option is "Windows 11 Command Bar", which will cause the crash.  If I change it to Windows 10 Ribbon, the crashes stop.  The side effect, of course, is that I no longer have the Windows 11 Command Bar in the Explorer window.

Any ideas from more knowledgeable people if and when this will be addressed?

By the way, thanks to everyone who's ever worked on this project; I LOVE this.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by EricClaeys** [comment]
Just updated Windows to Windows 11 22H2, OS Build 22621.2070 and on the first reboot, got this:

![image](https://github.com/valinet/ExplorerPatcher/assets/83164203/11644e27-9efe-4696-a0cc-50000382a2e0)

Just prior to updating Windows I updated Explorer Patcher to the latest release.  Is this a known problem?

**Comment by fireaxel777** [comment]
#pyrates999 Thanks, I didn't see that (build 2070 is preview) while updating to 2070.

**Comment by pauljayd** [comment]
I also have this problem on build 2070.
In addition, when I uninstalled ExplorerPatcher, I lost the "control center" icon on the taskbar, and can't seem to restore it.

**Comment by pyrates999** [comment]
I would uninstall any preview update and never install any preview updates in the future.  Stick with the updates that have been fully tested.

**Comment by saucyknave** [comment]
...Aaaand here we are, on 8/10/2023.  That preview update is no longer a preview update, and EP still causes Explorer.exe to crash every other time I open File Explorer.  I've uninstalled EP, cleared the registry of it's entries, reinstalled EP, and it hasn't made any difference.  At this point, my fingers are crossed that Valiant still cares enough to try to fix this.  

And to think, this is all so I can have a shorter taskbar with small icons.  I bet modern Windows developers really hate customization enthusiasts like us.

**Comment by pyrates999** [comment]
Did you check that symbols were downloaded?

**Comment by pauljayd** [comment]
To: saucyknave
Thanks for noting that "Windows 10 RIbbon" fixes this temporary problem.
I can't live without "never combine" on the taskbar!

**Comment by Amrsatrio** [comment]
I experience no issues with the Win11 command bar on builds up to the second-latest Dev build with latest EP. Closing this issue.
