### ISSUE TITLE
MS Decided to break the windows 10 taskbar with build 22631.2129

### ISSUE THREAD

**Issue by Caddy8970** [valinet/ExplorerPatcher#1778]
Explorer Patcher still works, but the taskbar wont change to the windos 10 one

**Comment by Caddy8970** [comment]
Using winareo tweaker fixes this, at the cost of the start menu not working at all

**Comment by felo1** [comment]
can confirm

**Comment by Daisyfan1995** [comment]
Duplication Of https://github.com/valinet/ExplorerPatcher/issues/1769

**Comment by pyrates999** [comment]
Insider builds are not fully tested by Microsoft, but you knew that already.

You can try disabling symbols being downloaded as insider builds usually have them included already: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Daisyfan1995** [comment]
The Windows 10 taskbar appears now in Windows 11 10.0.22631.2134 (Release Update) 2023-08-08

https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

**Comment by pyrates999** [comment]
Windows 11 10.0.22631.2134 is a beta build and not what you referred to in the link here: 

https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

**Comment by Daisyfan1995** [comment]
More Problems in 2191 https://blogs.windows.com/windows-insider/2023/08/10/announcing-windows-11-insider-preview-build-22621-2191-and-22631-2191/
