### ISSUE TITLE
Windows 11 10.0.22621.2070 Transparent Taskbar with Classic Shell

### ISSUE THREAD

**Issue by fatguy1121** [valinet/ExplorerPatcher#1779]
I don’t think 2070 is a preview build, but the taskbar goes completely transparent as soon as classic shell runs. Exiting classic shell returns the color to normal. No combination of settings or defaults seem to make EP not transparent.

**Comment by pyrates999** [comment]
It is: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

**Comment by Globespy** [comment]
Yep, it's a release preview which means that unless the TTB dev has been working with Microsoft to ensure TTB will work, everyone will have the same problem a week from today when this 'preview' becomes general release. Generally RP releases like this tend to be more or less what goes to general release unless insiders identify major issues, and important to know that many will not use TTB.
Fingers crossed that TTB dev is able to resolve whatever is breaking functionality.

**Comment by pyrates999** [comment]
Preview updates never become general releases.  A new update is released instead on the second tuesday of every month.  Those updates you should install.

**Comment by Manuel1948** [comment]
I have the same issue since a few days (Windows 11 22H2 Build: 22621.2134), don't know what you guys talking about (like what TTB means and what preview update etc.).

Is this an issue Open Shell developers has to fix or the ExplorerPatcher developers?

**Comment by firehawkx** [comment]
Funny enough, I got the invisible taskbar since last night update, and was also running with Classic Shell (not knowing it was no longer maintained/updated)... I was able to install Open Shell on top of it (it kept all the settings) and now everything works properly again :)

**Comment by Poopooracoocoo** [comment]
KB5028254 and 22621.2070 was a preview update
