### ISSUE TITLE
Add Windows 10 Search

### ISSUE THREAD

**Issue by UserDumpster** [valinet/ExplorerPatcher#1781]
When using the windows style  start menu the search menu stay the same 
<img width="960" alt="Screenshot 2023-08-04 233755" src="https://github.com/valinet/ExplorerPatcher/assets/141473097/bba1a121-cb35-47f7-9235-19cca6902785">
<img width="960" alt="Screenshot 2023-08-04 233804" src="https://github.com/valinet/ExplorerPatcher/assets/141473097/392c198f-d8ef-4d9a-8956-aecb79befd4e">

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by UserDumpster** [comment]
@pyrates999 

im using explore patcher version 22621.1992.56.1 and windows version 22h2 and build 22621.1992

**Comment by pyrates999** [comment]
You mean the search window shows up on top of the start menu?

You started searching using "f" right?  It gave you a suggestion then of "file explorer" it looked like.

**Comment by UserDumpster** [comment]
no i ment that the search menu was still the windows 11 style

**Comment by pyrates999** [comment]
What settings did you change to cause this?

**Comment by UserDumpster** [comment]
i didnt change any apart from a couple and even at the begging it was like this i can send screenshots of my settings if needed

**Comment by Vipin2003** [comment]
Win10 Search menu was not implemented in EP... And have not planned yet to implement this. Thanks

**Comment by Poopooracoocoo** [comment]
Please use Discussions for feature requests.
