### ISSUE TITLE
Start Menu appears underneath taskbar

### ISSUE THREAD

**Issue by Sleepingeye** [valinet/ExplorerPatcher#1782]
If the Start menu has been placed on the left side of the screen with auto-hide on, activating the Start Menu causes the left third of the start menu to appear underneath the start bar.

Resolution:
Either set a higher Z height, or reposition the start menu to be offset the actual width of the start bar instead of assuming the offset.

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by Sleepingeye** [comment]
ExplorerPatcher 22621.1992.56.1
Windows 11 Build 10.0.22621.1992

Though it's been a bug since I've used it... ie., for all the updates since install

**Comment by pyrates999** [comment]
Ok, thanks.  Now the devs know how to recreate it.

**Comment by Zetalight16** [comment]
Quick notes, as I've also had this happen:

1. It does not happen every time, but often
2. opening the start menu from a taskbar that is on the right side of the screen (that is, if you have one taskbar on the left of one monitor and one on the right of another monitor) fixes the left taskbar's start menu to have the correct offset temporarily

**Comment by Amrsatrio** [comment]
Please show a screenshot. I do not experience your issue on 10.0.22621.1992.

**Comment by Zetalight16** [comment]
![With the issue](https://github.com/valinet/ExplorerPatcher/assets/127622523/9a185186-5528-4e07-ab7c-d0394274ff05) vs 
![expected behavior](https://github.com/valinet/ExplorerPatcher/assets/127622523/bf749ba2-7f71-45de-91c8-62f77a443986)

**Comment by Zetalight16** [comment]
Those screenshots are
ExplorerPatcher v 22621.2361.58.1
Windows 11 build 10.0.22621.2283

**Comment by pyrates999** [comment]
Might be related to this: https://github.com/valinet/ExplorerPatcher/issues/1759

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/ccbd305c-a876-41be-aec9-e65641039340)

**Comment by Balenty** [comment]
This issue apparently reappeared. Check #4510 for further details on reproduction.
