### ISSUE TITLE
Search menu

### ISSUE THREAD

**Issue by UserDumpster** [valinet/ExplorerPatcher#1786]
When using the windows style start menu the search menu stays the same and has no option to change it
<img width="960" alt="Screenshot 2023-08-04 233755" src="https://github.com/valinet/ExplorerPatcher/assets/141473097/194fabc9-dd4d-4bdd-9834-1e24b1378fcb">
<img width="960" alt="Screenshot 2023-08-04 233804" src="https://github.com/valinet/ExplorerPatcher/assets/141473097/6d5f0f08-f838-41e3-bc6e-6bac45ea78d7">

im using explore patcher version 22621.1992.56.1 and windows version 22h2 and build 22621.1992

**Comment by pyrates999** [comment]
Don't open duplicates: https://github.com/valinet/ExplorerPatcher/issues/1781
