### ISSUE TITLE
Uninstall / upgrade failed by "An error has occurred while servicing this product"

### ISSUE THREAD

**Issue by adrien1018** [valinet/ExplorerPatcher#1787]
Currently I cannot uninstall / upgrade ExplorerPatcher, or even reinstall the same version. After running `ep_setup.exe`, it failed with the following prompt:

```
An error has occurred while servicing this product.
This is most likely caused by one or more of the backup files from the previous update still being in use. Unlocking the files should fix this issue.

Troubleshooting steps:
* Close and reopen the "Properties" dialog if it is currently open.
* Kill and restart all "explorer.exe" processes.
* If you have registered this application as a shell extension, then restarting the computer will probably fix this.
* Lastly, reboot the computer and try again.
```

Things that I have tried, and they all failed with the same message:
1. Use the `ep_setup.exe` from `C:\Program Files\ExplorerPatcher`, or version 22621.1555.55.1 or 22621.1992.56.1 downloaded from GitHub
2. Boot into safe mode and try upgrade / uninstall there
3. Run it from command line by `ep_setup.exe`, `ep_setup.exe /uninstall` or renaming it to `ep_uninstall.exe`
4. Uninstall from "Apps and features" in the Settings
5. Run it on Windows versions 22621.1992 and 22621.2070

Windows build number: 22621.1992 / 22621.2070
Current ExplorerPatcher version: 22621.1555.55.1

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by adrien1018** [comment]
@pyrates999 This issue also presents on 22621.1992, which is not a preview release.

**Comment by pyrates999** [comment]
Then under 22621.1992 you can attempt a reinstall: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

**Comment by adrien1018** [comment]
@pyrates999 Please read the description. My issue is that I cannot reinstall or uninstall.

**Comment by pyrates999** [comment]
can you open up computer management?  You can do so by right clicking on this pc.

Then go to System Tools -> Event Viewer -> Windows Logs -> Application

Now try to uninstall explorer patcher like you have.  And refresh those logs and see what it says when you tried to do that.  Post that here.

**Comment by adrien1018** [comment]
@pyrates999 No new log entries were displayed after I tried to uninstall the program and refreshing Event Viewer. I also tried reinstalling / upgrading, and no new log entries were generated either.

**Comment by pyrates999** [comment]
Seems someone else also had this problem: https://github.com/valinet/ExplorerPatcher/discussions/713

**Comment by adrien1018** [comment]
I managed to solve this problem by manually deleting everything under `C:\Program Files\ExplorerPatcher` and re-run the installer again. The root cause of the issue is still not clear, though.

**Comment by Amrsatrio** [comment]
If that happens try to uncheck "register as shell extension" in File Explorer section of the properties menu, restart the PC if that was enabled, and then delete .prev files in that folder.

I will close this since this rarely happens and that a workaround is available.

**Comment by pyrates999** [comment]
> If that happens try to uncheck "register as shell extension" in File Explorer section of the properties menu, restart the PC if that was enabled, and then delete .prev files in that folder.
> 
> I will close this since this rarely happens and that a workaround is available.

This work around should be added to this page then: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To
