### ISSUE TITLE
Crash and restart explorer with KB5029263 Build 22621.2134

### ISSUE THREAD

**Issue by MaybeAnge** [valinet/ExplorerPatcher#1798]
Build 22621.2134 
KB5029263

**Comment by young-zhang** [comment]
Also, with the latest update, when it wasn't crashing, Windows-Tab did not work until ExplorerPatcher was terminated.

**Comment by racofer** [comment]
I can confirm the same issue after today's update.

**Comment by bubbismith** [comment]
I'm having a problem again too... It was today's update, the volume slider was not showing again. Another post said it came back when switched to Windows 11 taskbar style. I switched to that, and now when I right-click the taskbar, Explorer reloads. I had to do it three times in a row to get "unfortunately, fe is crashing :(" screen , which got back here. I'm so dependent on this stuff. I'm actually have to figure out where things are right now without the win10 menu bar, etc.

![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/ac7a84cc-537f-4bab-8c88-60d214709592)

**Comment by arcyc** [comment]
Right-clicking Task Bar causes crash in latest cumulative update.

**Comment by bubbismith** [comment]
OK, I was able to uninstall everything and bring me back to the below WinVer and all is OK again at the moment. I did need to uninstall EP, it was rebooting Explorer on each right-click, but when I reinstalled it, (after all the Windows Updates were uninstalled) it went back to all is well. So, I think that new WinVer from my post above is the new one, which introduces some problems with EP. Here's my current Winver.

![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/a51b23c5-4bc8-4ae9-a4a5-1ce66dd3968f)

**Comment by bubbismith** [comment]
Here's the WinVer with the problems:
![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/2aeb650b-0500-46c7-a140-ea964ec82b74)

**Comment by pyrates999** [comment]
That is a regular update.  So now you gotta wait for the dev's of explorer patcher to fix it.

**Comment by bubbismith** [comment]
Here's the ones I uninstalled, they are asking to be installed again...
![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/a95b7c86-a6ed-4b7d-b7b4-bff242eaa01d)

**Comment by MaybeAnge** [comment]
> **I ALSO CONFIRM THIS PROBLEM.**
I just tested it's true, I hadn't noticed

**Comment by MaybeAnge** [comment]
> J'ai encore un problème aussi... C'était la mise à jour d'aujourd'hui, le curseur de volume ne s'affichait plus. Un autre article a déclaré qu'il était revenu lors du passage au style de la barre des tâches de Windows 11. Je suis passé à cela, et maintenant, lorsque je clique avec le bouton droit sur la barre des tâches, Explorer se recharge. J'ai dû le faire trois fois de suite pour obtenir l'écran "malheureusement, fe plante :(" , qui est revenu ici. Je suis tellement dépendant de ce genre de choses. Je dois en fait comprendre où en sont les choses en ce moment sans la barre de menu win10, etc.
> 
> ![image](https://user-images.githubusercontent.com/30091315/259220053-ac7a84cc-537f-4bab-8c88-60d214709592.png)

**I ALSO CONFIRM THIS PROBLEM.**
I just tested it's true, I hadn't noticed

**Comment by slon872** [comment]
Also, "Task View" button on Win10 taskbar does not work.
The same behavior was with preview update two weeks ago.
Symbol files in AppData\Roaming\ExplorerPatcher have fresh date/time.

**Comment by SESNut** [comment]
i dont know why people are surprised its broken despite what pyrates999 kept saying about the preview update from 2 weeks ago. Microsoft basically never changes anything from preview to release

**Comment by FunFrog-BY** [comment]
The only one you need to uninstall is KB5029263.

**Comment by SimonCropp** [comment]
note that KB5029263 is a security update https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

**Comment by bubbismith** [comment]
Actually a Cumulative Update:
2023-08 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5029263)

**Comment by getify** [comment]
how do we uninstall this windows update so we can keep using EP?

**Comment by bubbismith** [comment]
I just paused my updates for a week after I just had 29263 install again. I'm hoping EP will be updated soon, as Windows 11 is a real drag without it. 

To, those that asked how to uninstall a KB. From the Windows Update page (in settings) click on Update History, then scroll all the way to the bottom and you'll see Uninstall Updates.

**Comment by minmik528** [comment]
same issue.....

**Comment by Girofox** [comment]
Actually you can prevent restart loop when right clicking taskbar by checking "do not change the standard context menu" under explorer patcher settings. Just type explorerpatcher in windows search bar and you can access settings without right clicking.

**Comment by jan-glx** [comment]
see also [this workaround](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555) mentioned in [this duplicate issue](https://github.com/valinet/ExplorerPatcher/issues/1802#issuecomment-1670928799)

**Comment by aptexd** [comment]
me too
Windows 11 Pro 22621.2134

**Comment by Girofox** [comment]
> The issues were resolved on my Windows 11 after deleting the keys `IsUndockedAssetAvailable` (located at `HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell`) and `OSBuild` (located at `HKEY_CURRENT_USER\Software\ExplorerPatcher`). After that, I restarted EP and about 3 minutes later I received a notification of symbols being downloaded. After that, I restarted EP again and had no more problems.

I will try that, didn't deleted OSBuild yet because the value seemed correct in my registry.

**Comment by c8c8** [comment]
I installed the update, because it's basically forced.  Upon completion, I deleted the OSBuild and IsUndockedAssetAvailable keys and hit restart.  Windows restarted, I got a message that the new symbols were downloaded, and ExplorerPatcher is working without problems.  Win-Tab does nothing for me, but I only tried it because I saw other comments here; I have no idea what it's supposed to do and therefore don't care much.  

Things are getting a big dodgy though.  I feel like I can't live without ExplorerPatcher, but I am not a fan of something that breaks whenever Windows updates itself and needs me to go in and start editing the registry.  Sure with Microsoft was less stupid.  Or that we could just splice in the Windows 10 taskbar and know that it's going to reliably remain in place.  Le sigh.

**Comment by flavio-b-74** [comment]
The workarounds don't work for me (see #1840) on Win 11 22H2 (build SO 22621.2134):

- uninstalled explorer patcher
- deleted registry keys
- rebooted
- installed the last version (22621.1992.56.2)
- rebooted again

It randomly crashes while opening file explorer.

Tried to enable "Do not change the taskbar context menu", rebooted, same behavior.

In the event viewer:
`Event 1000, Application error
Faulting Application Name: Explorer.EXE, Version: 10.0.22621.2070, Timestamp: 0x2bd7252c
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.2070, timestamp: 0xa1d6b8fe
Exception code: 0xc000027b
Error offset 0x00000000008720c0
Process ID that generated the error: 0x0x58C
Start time of the application that generated the error: 0x0x1D9D5D02F4FE8F5
Path to Faulting Application: C:\Windows\Explorer.EXE
Path to the module that generated the error: C:\Windows\System32\Windows.UI.Xaml.dll
Report ID: 0438fcb3-e100-40f1-98e7-12c6793773c9
Full package name that generated the error:
Application ID of the package that generated the error:`

**Comment by Msprg** [comment]
With the newest release of ExplorerPatcher 22621.1992.56.3 running on Windows 11 build 10.0.22621.2134 with downloaded symbols seems to be working correctly 🎉 , even with Windows 10 style taskbar and `Do not change the taskbar context menu` setting disabled.

EP settings were backed up, defaults restored, and after symbols download backup restored.
Windows updates left untouched.

**Comment by flavio-b-74** [comment]
Unfortunately, the newest release did not resolve the problem on my PC. Same behavior.
To systematically replicate the problem:

- I opened 7 or 8 file explorer windows
- I closed them
- I opened "This computer" file explorer window: file explorer crashed

Then, It randomly crashes.

**Comment by Msprg** [comment]
I could not reproduce the issue in my enviroment, there might be different issues  at play here.

**Comment by pyrates999** [comment]
> Unfortunately, the newest release did not resolve the problem on my PC. Same behavior. To systematically replicate the problem:
> 
> * I opened 7 or 8 file explorer windows
> * I closed them
> * I opened "This computer" file explorer window: file explorer crashed
> 
> Then, It randomly crashes.

After that happens, open up windows event viewer or computer management
go to Event Viewer and go to Windows Logs -> Application
check the list of entries there for any that stand out

**Comment by flavio-b-74** [comment]
> After that happens, open up windows event viewer or computer management
> go to Event Viewer and go to Windows Logs -> Application
> check the list of entries there for any that stand out

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-08-24T07:35:43.2336298Z" /> 
  <EventRecordID>41286</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="9872" ThreadID="9004" /> 
  <Channel>Application</Channel> 
  <Computer>xxxxx</Computer> 
  <Security UserID="S-1-5-21-xxxxx-xxxxx-xxxxx-1001" /> 
  </System>
- <EventData>
  <Data Name="AppName">explorer.exe</Data> 
  <Data Name="AppVersion">10.0.22621.2070</Data> 
  <Data Name="AppTimeStamp">2bd7252c</Data> 
  <Data Name="ModuleName">Windows.UI.Xaml.dll</Data> 
  <Data Name="ModuleVersion">10.0.22621.2070</Data> 
  <Data Name="ModuleTimeStamp">a1d6b8fe</Data> 
  <Data Name="ExceptionCode">c000027b</Data> 
  <Data Name="FaultingOffset">00000000008720c0</Data> 
  <Data Name="ProcessId">0xd60</Data> 
  <Data Name="ProcessCreationTime">0x1d9d65d936c2675</Data> 
  <Data Name="AppPath">C:\Windows\explorer.exe</Data> 
  <Data Name="ModulePath">C:\Windows\System32\Windows.UI.Xaml.dll</Data> 
  <Data Name="IntegratorReportId">4c83a7d9-599f-4b42-804d-a40e2ee03cba</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
```

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Winlogon" Guid="{DBE9B383-7CF3-4331-91CC-A3CB16A3B538}" EventSourceName="Wlclntfy" /> 
  <EventID Qualifiers="16384">1002</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-08-24T07:35:44.4118503Z" /> 
  <EventRecordID>41287</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="6560" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>xxxx</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>explorer.exe</Data> 
  </EventData>
  </Event>
```

```- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" /> 
  <EventID>1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-08-24T07:35:43.9716159Z" /> 
  <EventRecordID>41288</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="9872" ThreadID="9004" /> 
  <Channel>Application</Channel> 
  <Computer>xxxxx</Computer> 
  <Security UserID="S-1-5-21-xxxxxx-xxxxxxx-xxxxxxx-1001" /> 
  </System>
- <EventData>
  <Data Name="Bucket" /> 
  <Data Name="BucketType">0</Data> 
  <Data Name="EventName">APPCRASH</Data> 
  <Data Name="Response">Non disponibile</Data> 
  <Data Name="CabId">0</Data> 
  <Data Name="P1">explorer.exe</Data> 
  <Data Name="P2">10.0.22621.2070</Data> 
  <Data Name="P3">2bd7252c</Data> 
  <Data Name="P4">combase.dll</Data> 
  <Data Name="P5">10.0.22621.2070</Data> 
  <Data Name="P6">275170a5</Data> 
  <Data Name="P7">80004005</Data> 
  <Data Name="P8">000000000009053b</Data> 
  <Data Name="P9" /> 
  <Data Name="P10" /> 
  <Data Name="AttachedFiles" /> 
  <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_explorer.exe_58a3ec16bde7eec2cc85ca924e4b93bcda519f_3c6b86e2_58dae4e6-594b-4858-b123-b22fb0f1c5f3</Data> 
  <Data Name="AnalysisSymbol" /> 
  <Data Name="Rechecking">0</Data> 
  <Data Name="ReportId">4c83a7d9-599f-4b42-804d-a40e2ee03cba</Data> 
  <Data Name="ReportStatus">4</Data> 
  <Data Name="HashedBucket" /> 
  <Data Name="CabGuid">0</Data> 
  </EventData>
  </Event>`

`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" /> 
  <EventID>1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-08-24T07:35:44.9687778Z" /> 
  <EventRecordID>41289</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="2088" ThreadID="9176" /> 
  <Channel>Application</Channel> 
  <Computer>PC2023</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="Bucket">1943428220992881100</Data> 
  <Data Name="BucketType">4</Data> 
  <Data Name="EventName">APPCRASH</Data> 
  <Data Name="Response">Non disponibile</Data> 
  <Data Name="CabId">0</Data> 
  <Data Name="P1">explorer.exe</Data> 
  <Data Name="P2">10.0.22621.2070</Data> 
  <Data Name="P3">2bd7252c</Data> 
  <Data Name="P4">combase.dll</Data> 
  <Data Name="P5">10.0.22621.2070</Data> 
  <Data Name="P6">275170a5</Data> 
  <Data Name="P7">80004005</Data> 
  <Data Name="P8">000000000009053b</Data> 
  <Data Name="P9" /> 
  <Data Name="P10" /> 
  <Data Name="AttachedFiles">\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.804ec645-ee63-49e8-9e8d-4d493ab34293.tmp.WERInternalMetadata.xml</Data> 
  <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_explorer.exe_58a3ec16bde7eec2cc85ca924e4b93bcda519f_3c6b86e2_58dae4e6-594b-4858-b123-b22fb0f1c5f3</Data> 
  <Data Name="AnalysisSymbol" /> 
  <Data Name="Rechecking">0</Data> 
  <Data Name="ReportId">4c83a7d9-599f-4b42-804d-a40e2ee03cba</Data> 
  <Data Name="ReportStatus">268435456</Data> 
  <Data Name="HashedBucket">4041bec862beeeba5af871ab96c001cc</Data> 
  <Data Name="CabGuid">0</Data> 
  </EventData>
  </Event>`


`C:\ProgramData\Microsoft\Windows\WER\ReportQueue` is empty.

`WER.804ec645-ee63-49e8-9e8d-4d493ab34293.tmp.WERInternalMetadata.xml` : 

`<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>10.0</WindowsNTVersion>
		<Build>22621</Build>
		<Product>(0x30): Windows 10 Pro</Product>
		<Edition>Professional</Edition>
		<BuildString>22621.2134.amd64fre.ni_release.220506-1250</BuildString>
		<Revision>2134</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1040</LCID>
		<BuildLayers>
			<BuildLayer LayerName="22621.1.amd64fre.ni_release.220506-1250" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="2134" IsTopLevel="1" IsChecked="0" BuildStamp="220506-1250" BuildBranch="ni_release" BuildArch="amd64" BuildLab="22621.ni_release.220506-1250" BuildLabEx="22621.1.amd64fre.ni_release.220506-1250"/>
			<BuildLayer LayerName="22621.1928.amd64fre.ni_release_svc_prod3.230622-0951" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="1928" IsTopLevel="0" IsChecked="0" BuildStamp="230622-0951" BuildBranch="ni_release_svc_prod3" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod3.230622-0951" BuildLabEx="22621.1928.amd64fre.ni_release_svc_prod3.230622-0951"/>
			<BuildLayer LayerName="22621.2134.amd64fre.ni_release_svc_prod1.230727-1316" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="2134" IsTopLevel="0" IsChecked="0" BuildStamp="230727-1316" BuildBranch="ni_release_svc_prod1" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod1.230727-1316" BuildLabEx="22621.2134.amd64fre.ni_release_svc_prod1.230727-1316"/>
			<BuildLayer LayerName="22621.2134.amd64fre.ni_release_svc_prod1.230727-1316" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="2134" IsTopLevel="0" IsChecked="0" BuildStamp="230727-1316" BuildBranch="ni_release_svc_prod1" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod1.230727-1316" BuildLabEx="22621.2134.amd64fre.ni_release_svc_prod1.230727-1316"/>
		</BuildLayers>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>explorer.exe</Parameter0>
		<Parameter1>10.0.22621.2070</Parameter1>
		<Parameter2>2bd7252c</Parameter2>
		<Parameter3>combase.dll</Parameter3>
		<Parameter4>10.0.22621.2070</Parameter4>
		<Parameter5>275170a5</Parameter5>
		<Parameter6>80004005</Parameter6>
		<Parameter7>000000000009053b</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>10.0.22621.2.0.0.256.48</Parameter1>
		<Parameter2>1040</Parameter2>
		<Parameter22>8833</Parameter22>
		<Parameter23>88330f62c5e29402e4cb8b793c0208a1</Parameter23>
		<Parameter24>0837</Parameter24>
		<Parameter25>08379b34f09d2a59db1cafbceb128db2</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>260A370D-9348-4F84-8D40-492D05042130</MID>
		<SystemManufacturer>Gigabyte Technology Co., Ltd.</SystemManufacturer>
		<SystemProductName>B550M DS3H</SystemProductName>
		<BIOSVersion>F2e</BIOSVersion>
		<OSInstallDate>1676760149</OSInstallDate>
		<OSInstallTime>1601-01-02T22:59:20Z</OSInstallTime>
		<TimeZoneBias>-01:00</TimeZoneBias>
	</SystemInformation>
	<SecureBootState>
		<UEFISecureBootEnabled>0</UEFISecureBootEnabled>
	</SecureBootState>
	<ReportInformation>
		<Guid>58dae4e6-594b-4858-b123-b22fb0f1c5f3</Guid>
		<CreationTime>2023-08-24T07:35:44Z</CreationTime>
	</ReportInformation>
</WERReportMetadata>`

**Comment by perdrix52** [comment]
So I deleted registry keys an reinstalled:

![image](https://github.com/valinet/ExplorerPatcher/assets/20211762/629f7763-4a8f-4e26-b81e-8ccb780a0a1b)

So it's still broken

**Comment by pyrates999** [comment]
Did you try rebooting?

**Comment by bubbismith** [comment]
I let windows update when I got the new version of EP, so running 22621.1992.56.3 on Windows 22621.2215 and EP is working fine, Win10 taskbar with modified context menu. I decided to wait without the volume slider until EP has that one feature fixed.

**Comment by pyrates999** [comment]
> I let windows update when I got the new version of EP, so running 22621.1992.56.3 on Windows 22621.2215 and EP is working fine, Win10 taskbar with modified context menu. I decided to wait without the volume slider until EP has that one feature fixed.

That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by bubbismith** [comment]
> >
> That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692
> Preview updates are also not fully tested by Microsoft and thus could have bugs.

Ah shoot! I did it again. I had paused the updates, and then I thought I was just catching up. It is working though, only issue I have is the volume slider. 

![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/c5d15eb0-4235-4833-83c7-e67557dd3a55)
![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/662834ca-2edd-4e90-a73c-009fc69aa132)
![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/0deaecee-d966-4bcc-a049-b9f1561e0dff)

Thanks very much, I'll more careful on that going forward.

**Comment by flavio-b-74** [comment]
No workaround works for me. I uninstalled KB5029351, same behavior. I'm looking forward to receiving a new version of EP with bug fix. Thanks!

**Comment by CarlosJSA** [comment]
Same here. And the annoying IT department forcing updates... Looking forward to receive the new version of EP! ❤️

**Comment by pyrates999** [comment]
> Same here. And the annoying IT department forcing updates... Looking forward to receive the new version of EP! ❤️

I would not be running EP on any work computer.

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. There should be no more major issues on 22621 builds up to 22621.2359.

**Comment by flavio-b-74** [comment]
I'm sorry, but I still have the same issue: when I open explorer, then i close it, the next time it crashes. So: one time it opens, the next time it crashes, and so on...
