### ISSUE TITLE
Disable blue highlight in context menus

### ISSUE THREAD

**Issue by valinet** [valinet/ExplorerPatcher#18]
As you probably know already, newer builds (including 22000.176 and 22449.1000) do not introduce many changes, if any, regarding the system theme, except another work-in-progress feature that it's said to look better but in reality does not necessarily do so: the blue highlight in the context menus:
![image](https://user-images.githubusercontent.com/6503598/132145284-fd74304d-3a07-487c-ba0f-583d99a6f946.png)
Personally, I prefer the old gray highlight which also filled better the containing rectangle. This is all dictated by the theme that's currently in use. Not much can be done from inside the applications that we hook, as those usually call things like `DrawThemeBackground ` from `uxtheme` which supply them with the required data from the theme file/draw some stuff acording to the theme file. Even the custom skinned menus Explorer use (Win+X, every context menu on the taskbar) still use the blue highlight although there is a bit better represented, as shown above.

Anyway, for people that want to revert to the old gray highlight, I recommend using the theme file from previous Windows 11 builds (22000.51, for example). You could also edit the theme file, but then of course, as you probably know, the digital signature of the file becomes invalid and Windows will refuse to load the theme file unless a [uxtheme patcher](https://www.google.com/search?q=uxtheme+patcher) is used. But the signature is not invalidated when you use a signed file, but from a previous OS version. I prefer this method since I do not use custom themes, I do not want to patch the theme service etc. I basically want the proper stock theme.

1. To get the required file, download the core Windows Update file for build 22000.51 from Microsoft using a helper like UUP dump: https://uupdump.net/getfile.php?id=bfe6f0bd-fb83-442f-b225-7ad7a61b48f3&file=core_en-us.esd
2. After that, open the file using 7-Zip or any other archive tool, and navigate to `2\Windows\resources\Themes\aero\`. In there you will find the required `aero.msstyles` theme, grab that.
3. On the system that you want to modify, go to `C:\Windows\Resources\Themes\aero`. In there, [take ownership](https://winaero.com/add-take-ownership-context-menu-windows-10/) of the file, rename it to something like `aero_original.msstyles` and paste in the new `aero.msstyles` file.

Reboot and you should be good to go!
![image](https://user-images.githubusercontent.com/6503598/132145293-845f15ca-8d61-4d99-8008-92cbb4f4dc62.png)

**Comment by ErickWei** [comment]
Not enough height is the reason of bule background looked so ugly.
Is there a way to change bule background height ( or maybe padding or margin)?

**Comment by valinet** [comment]
I don’t know, maybe take a look on the theme file, aero.msstyles, tinker a bit with it and see what you get. Don’t forget to disable theme signing! Good luck!

**Comment by krlvm** [comment]
I'd like to have an ability to use accent color everywhere.

Unfortunately, the simple way to do this using `SetSysColors` works only with hyperlinks, selected text, explorer selection rectangle and some of list items. There's an open-source app for that: [AccentApplicator](https://github.com/mcdenis/AccentApplicator).

To colorize the rest of Win32 UI, StartAllBack uses uxtheme API to get handle of UI controls bitmap and uses a complicated algorithm to replace the blue color (and its shades) with accent color.

I've made a working prototype that replaces the original bitmaps with colored ones, but it is worthless unless needs some changes are made to get the blue replacement to work correctly.

This means that ExplorerPatcher (although it would be better to separate this into a separate project), could have this functionality after combining these two approaches, in the end, having received what StartAllBack provides. I don't have a lot of Win32 API knowledge, but can share the prototype if it may be useful for @valinet.

**Comment by valinet** [comment]
Hi

I have looked on the disassembly of SAB before as well, basically what @nullnullnullnull0 posted above and some more even. Indeed, it's a combination of simply hooking the classic `GetSysColors`/`SetSysColors` and some custom stuff for the bitmaps, something like this maybe: https://github.com/valinet/ExplorerPatcher/discussions/199 for the context menu color.

Idk, I mean, sure, this should be built-in, that would be indeed professional, but it's Windows, after all, I just have other things to work on and things being blue do not bother me that much. Also, as you have discovered, it's not that easy and getting to a useful implementation regarding this takes some work, indeed. I don't have much extra time anyway, so personally, I won't be taking on implementing this. Of course, if you want to work on it, and maybe even one day contribute it to EP so it can be offered as functionality and a reference implementation for how such a thing should be done, I'd be more than happy to receive such a contribution, sure. But regarding me, personally, I won't take on this endevour any time soon, especially since I also do not use this feature. As I said, it's nice, but not something vital, like taskbar label buttons :D

As well, if you want to, I encourage you to share any implementation that you have, maybe other people find it useful and something gets put together. You know, I am a single person as well, no matter how skilled one is, a day still has 24 hours of which you barely get a few, if any, to work on various stuff, so despite all my goodwill, enthusiasm and work I put, I can only do so much, so of course outside contributions are always welcome.

Thank you
