### ISSUE TITLE
Explorer reloads if I open explorer

### ISSUE THREAD

**Issue by Balabai1337** [valinet/ExplorerPatcher#1813]
Sometimes when you open File Explorer, it completely reloads. I don’t know what this is connected with, the EP version is the latest, Windows 11 Version 22621.2070. Resetting the settings in the EP does not help.

**Comment by rrech** [comment]
It worked perfectly here! Tks!

**Comment by ctrlcmdshft** [comment]
> 

This will create issues for alt-tab, win+tab according to others mentioning it on other issue threads

**Comment by rrech** [comment]
> > The issues were resolved on my Windows 11 after deleting the keys IsUndockedAssetAvailable (located at HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell) and OSBuild (located at HKEY_CURRENT_USER\Software\ExplorerPatcher). After that, I restarted EP and about 3 minutes later I received a notification of symbols being downloaded. After that, I restarted EP again and had no more problems.
> 
> This will create issues for alt-tab, win+tab according to others mentioning it on other issue threads

Alt+tab works fine until you use win+tab. If you don't use win+tab, this key combination works without a problem. If you restart ExplorerPatcher, alt+b works fine again. It's worth it to me.

**Comment by Poopooracoocoo** [comment]
Should be resolved now. Leave a comment or open a new issue if you're still seeing issues. Make sure to include your Windows OS Build and ExplorerPatcher version.
