### ISSUE TITLE
FYI: A workaround for the crashing issue causing by KB5029263

### ISSUE THREAD

**Issue by Max-Meng** [valinet/ExplorerPatcher#1819]
For what it worth, I happened to found that the Windows 11 Insider Preview Build 23481 has bring back the 'Never combined mode'. 
https://blogs.windows.com/windows-insider/2023/06/14/announcing-windows-11-insider-preview-build-23481/

Although the Insider Preview is not recommended for production, but the KB5029263 is causing issues already. 

So, on your choice.

**Comment by pyrates999** [comment]
Please close this as you should be commenting on the original issue where this happened on.
