### ISSUE TITLE
Windows continually reboots front UI

### ISSUE THREAD

**Issue by bujibena** [valinet/ExplorerPatcher#1820]
Hi all,

windows keeps rebooting the front end UI (forgot the name of it, everything showing taskbar etc) at startup

what is Explorerpatcher called in Task manager process? So I can find it and end it manually 

thanks!
Anton

**Comment by pyrates999** [comment]
How to uninstall: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

**Comment by bujibena** [comment]
> How to uninstall: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

Thank you!
