### ISSUE TITLE
It's a perfect solution.

### ISSUE THREAD

**Issue by lovebear94** [valinet/ExplorerPatcher#1821]
To fix crashing on preview updates, simply uninstall EP completely and delete these reg. keys :
Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher

After deleting these, restart ur device. Then, install EP (with latest updates) and wait till the symbols to be downloaded msg appear. After that, simply restart ur device again.
For win11 flyout users, action center will be overlapped over Win10 taskbar.

**Comment by bujibena** [comment]
How do I reinstall EP without being able to use the explorer UI?

**Comment by bipinq** [comment]
I had high hopes for this workaround, as it's way better than "Do not use preview builds" advice.
So I went through all the steps (symbols also downloaded automatically), but still doesn't work :(
(Win11 23H2 22631.2191). 
The Properties button is still not showing up right clicking on the taskbar (because it's a regular Win11 taskbar), so cannot even get into EPs menu.

**Comment by pyrates999** [comment]
I disagree.  Not using preview builds mean you have a more stable system because you only have software that's been fully tested by microsoft.  You aren't missing out on anything important by installing preview updates.

**Comment by Undisputed00x** [comment]
Using latest update of 22H2 and still this didnt fix the crashing

**Comment by pyrates999** [comment]
To open up the explorer patcher properties application, search for "Properties (ExplorerPatcher)" in the start menu.

**Comment by bujibena** [comment]
Can I uninstall explorer patcher through CMD?

Since explorer.exe is crashing I can only reach Task Manager and work from there

Anton

**Comment by pyrates999** [comment]
Follow steps here to uninstall it: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new version should never do irrecoverable crashes like these anymore. There should be no more major issues on 22621 builds up to 22621.2359.
