### ISSUE TITLE
WSL window maximize broken

### ISSUE THREAD

**Issue by kastoestoramadus** [valinet/ExplorerPatcher#1822]
When the Win10 taskbar is set on the right side.
When I maximize a window from WSL (tested on newest Intelij Idea via gWSL) the window is set to incorrect sizes and the cursor engage point is shifted. Like adjustments are calculated exactly to the bottom Windows 11 taskbar sizes.
So instead of reacting on the top left part of the cursor it reacts somewhere close to the bottom right part of the cursor.
Everything works fine if I manually resize the WSL window.

**Comment by gtazoo** [comment]
I also came across

**Comment by kastoestoramadus** [comment]
Looks like a general problem of gWsl, not Explorer Patcher.
After uninstall I still get this problem sometimes.

**Comment by pyrates999** [comment]
> Looks like a general problem of gWsl, not Explorer Patcher. After uninstall I still get this problem sometimes.

Please close this then.
