### ISSUE TITLE
Folders didn't show up on Windows 10-style Start menu

### ISSUE THREAD

**Issue by llwynog** [valinet/ExplorerPatcher#1823]
### OS:
Edition	Windows 11 Pro
Version	22H2
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

### Explorer Patcher:
Version: 22621.1992.56.1

I'm using Windows 10-style Start menu, but I can't add more folders (e.g. Settings, File Explorer) to the area up to the Power and Account icons.

![explorer_ljeu10Tdty](https://github.com/valinet/ExplorerPatcher/assets/48166239/c44e3117-832e-43fb-86c0-5a2d78f97820)

**Comment by Vipin2003** [comment]
It is a bug with EP in latest builds.

**Comment by Blackdrazon** [comment]
I don't suppose there's a workaround we can use in the interim? Figured it was worth asking.

**Comment by Poopooracoocoo** [comment]
> I don't suppose there's a workaround we can use in the interim? Figured it was worth asking.

#1974

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease.
