### ISSUE TITLE
Cannot Update, Cannot Uninstall, Cannot Right Click the Taskbar

### ISSUE THREAD

**Issue by Americapax** [valinet/ExplorerPatcher#1825]
Dear Mr. Radu,
I installed this program because at the beginning of Windows 11 i prefered the "Windows 10" look and feel.

As the title says the program called "explorer.exe" crashes every time i right click in the blank space of the taskbar, as this occurred i tried to uninstall "Explorer Patcher" but the screen becomes black and appears a windows with this written in it: 

"An error has occurred while servicing this product.

Troubleshooting steps:
*Close and reopen the "Properties" dialog if it is currently open.
*Kill and restart all "explorer.exe" processes.
*If you have registered this application as a shell extension , then restarting the computer will probably fix this.
*Lastly reboot the computer and try again."

I have tried all these "solutions" but none worked. 

Please resolve.

Thank you 

Mark Scott

P.S,

I have installed this "Explorer Patcher" program by the .exe file provided in the "releases" section.

**Comment by OxygenSpace** [comment]
i have this problem,too

**Comment by OxygenSpace** [comment]
Windows 11  22H2 22621.2134

**Comment by Americapax** [comment]
I am with Windows 11 22h2

**Comment by nirav72** [comment]
Yep, I have same issue. Right-clicking on taskbar causes explorer to crash and restart.  I'm on Windows 11 Pro, 22H2.

**Comment by xblubbx2** [comment]
same, bricked my system. I tried uninstalling, now I don't have a taskbar at all

**Comment by pyrates999** [comment]
open up task manager.  Go to file, run new task, type in explorer and hit the enter key.

**Comment by Tylerun** [comment]
Heres the fix. Ran into this on multiple computers with the latest win updates.

Ctrl+Alt+Dlt
Task Manager
File Run
CMD
taskkill /f /im explorer.exe
Close CMD
File Run in task manager
Run "Control Panel"
Uninstall a Program
Remove Explorer Patcher.

**Comment by xblubbx2** [comment]
> Heres the fix. Ran into this on multiple computers with the latest win updates. [...]

I followed these instructions and was able to uninstall ExplorerPatcher this way, however, after uninstalling it the taskbar is invisible and right-clicking the space where the taskbar is supposed to be doesn't produce a menu either. Windows Explorer is running, and restart doesn't help either.

**Comment by Litchytsu** [comment]
I do have the exact same issue after updating to Windows 11 10.0.22621

**Comment by rashemihmih** [comment]
yeah stupid windows 11 updated tonight and broke explorer patcher

**Comment by pyrates999** [comment]
If you got classic shell installed, remove it.  That is causing problems with the latest windows update it seems.  It's also no longer maintained and you should install open shell instead.

**Comment by bujibena** [comment]
> Heres the fix. Ran into this on multiple computers with the latest win updates.
> 
> Ctrl+Alt+Dlt Task Manager File Run CMD taskkill /f /im explorer.exe Close CMD File Run in task manager Run "Control Panel" Uninstall a Program Remove Explorer Patcher.

This fixed it for me - THANK YOU!

**Comment by wdtfshi** [comment]
> Heres the fix. Ran into this on multiple computers with the latest win updates.
> 
> Ctrl+Alt+Dlt Task Manager File Run CMD taskkill /f /im explorer.exe Close CMD File Run in task manager Run "Control Panel" Uninstall a Program Remove Explorer Patcher.

It seems you need admin privilegies to do this. Do you know if there's any way to stop or manually delete ExplorerPatcher without requiring admin?

**Comment by bujibena** [comment]
> > Heres the fix. Ran into this on multiple computers with the latest win updates.
> > Ctrl+Alt+Dlt Task Manager File Run CMD taskkill /f /im explorer.exe Close CMD File Run in task manager Run "Control Panel" Uninstall a Program Remove Explorer Patcher.
> 
> It seems you need admin privilegies to do this. Do you know if there's any way to stop or manually delete ExplorerPatcher without requiring admin?

I did this on my company computer so I don’t believe admin is required. Maybe depends on what level of privilege they set users to

**Comment by wdtfshi** [comment]
> 

not sure how it is set-up either. When I first installed it we had local admin on our machines which was then removed for company policies. When I tried uninstalling EP it gave me the generic pop-up asking me to log in with a user with higher privilege. Also tried manually removing EP's files through cmd and that doesn't work either, says access denied. I see some people are talking about EP auto-disabling itself after 3 tries but that never happened to me, it's in an infinite loop of restarting until I manually end the explorer through task manager

**Comment by pyrates999** [comment]
> > > > Heres the fix. Ran into this on multiple computers with the latest win updates.
> > > > Ctrl+Alt+Dlt Task Manager File Run CMD taskkill /f /im explorer.exe Close CMD File Run in task manager Run "Control Panel" Uninstall a Program Remove Explorer Patcher.
> > > 
> > > 
> > > It seems you need admin privilegies to do this. Do you know if there's any way to stop or manually delete ExplorerPatcher without requiring admin?
> > 
> > 
> > I did this on my company computer so I don’t believe admin is required. Maybe depends on what level of privilege they set users to
> 
> not sure how it is set-up either. When I first installed it we had local admin on our machines which was then removed for company policies. When I tried uninstalling EP it gave me the generic pop-up asking me to log in with a user with higher privilege. Also tried manually removing EP's files through cmd and that doesn't work either, says access denied. I see some people are talking about EP auto-disabling itself after 3 tries but that never happened to me, it's in an infinite loop of restarting until I manually end the explorer through task manager

Contact your company sysadmin to get explorer patcher removed then.  You no longer have access to remove it since you are no longer a local sysadmin.

**Comment by Poopooracoocoo** [comment]
Closing in favour of #1798 and #1826
