### ISSUE TITLE
My Screen Keeps Flashing and My Computer is Unusable 

### ISSUE THREAD

**Issue by Frenzy45** [valinet/ExplorerPatcher#1837]
I installed the program but after the install my screen proceeded to flash uncontrollably and my mouse has a constant loading circle above it. My computer is now Unusable and I can't remove the program as nothing opens.

**Comment by Shockelite** [comment]
This happened to me after an Windows update. I had to roll back the update by going into the startup recovery.

**Comment by RussKie** [comment]
Ditto. Started after Windows updated itself to 22000.2295.

After some mucking around I was able to start a command line, then opened MMC from which I was able to have some kind of browsing and found where I had the EP installer (ep_setup.exe). Then I was able to uninstall it from the command line, i.e.: `ep_setup.exe /uninstall`. That was the end of the endless Windows Explorer crash loop.

**Comment by pyrates999** [comment]
Known issue.  Please wait for a new release to fix it.

**Comment by RussKie** [comment]
Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1829.
