### ISSUE TITLE
Explorer patcher

### ISSUE THREAD

**Issue by Ale141175** [valinet/ExplorerPatcher#1844]
Ho dovuto per mia necessità reistallare windows 11, quindi ho anche installato explorer patcher ma dagli ultimi aggiornamenti della Microsoft, explorer patcher per windows 11 non funziona più bene come prima. Cliccando di destro sulla barra delle applicazioni anzichè aprire la famosa tendina con più opzioni da scegliere il monitor si refrescia per un secondo e non apre niente. Per esempio per aprire la gestione attività dovevo premere CTRL + MAIUSCOLO + ESC. E quindi il programma l'ho dovuto disinstallare. Eè possibile con qualche altro programma risolvere il problema? Grazie.

**Comment by shejdsagjkwsduefgrhkjwdwfkjwqd** [comment]
not for me

**Comment by johnwasme** [comment]
You would get a lot more responses if you wrote in English though a translator .

**Comment by Poopooracoocoo** [comment]
Dupicate of #1805
