### ISSUE TITLE
WinKey+Tab Issue

### ISSUE THREAD

**Issue by Hadipour** [valinet/ExplorerPatcher#1848]
[22621.1992.56.1] still have this issue with WinKey+Tab Issue. 
the first time that you use this shortcut then the ALt+Tab shortcut would also stop working.

**Comment by a-allard** [comment]
Same on windows 11 10.0.22621.2134.

To get back the Alt+Tab shortcut after pressing Win+Tab I have to restart explorer.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

**Comment by Poopooracoocoo** [comment]
Closing as duplicate of #1687
