### ISSUE TITLE
weird behaviors with windows key commands in os build 22621.2134

### ISSUE THREAD

**Issue by MinerAC4** [valinet/ExplorerPatcher#1855]
I've noticed that some of the typical windows key commands aren't functioning correctly. Win + N just opens onenote now, and Win + A just doesn't do anything. This was already mentioned by someone else, but Win + TAB also doesn't function at all and actually breaks the function of ALT + TAB.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

And add your comments to that one.
