### ISSUE TITLE
Widgets button not working on Win11 22478.1012

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [valinet/ExplorerPatcher#186]
On Windows 11 22478.1012 with ExplorerPatcher 22000.282.31.4 and StartAllBack completely disabled, the Widgets button isn't working. Search and Task View button, Show Desktop button toggles work.

Well, if ExplorerPatcher is disabled and SAB enabled, the Widgets button (which was actually the transformed Cortana button) is also broken.

Just giving a heads-up. I don't request you to urgently fix it :)) In fact, you could support only final/release builds of Windows 11 with their cumulative updates, and I would be happy. I just run the latest dev build on an experimental machine for fun.

**Comment by valinet** [comment]
For now, I won’t bother with that; if anyone wants to take the task, I am open to merging a PR.

Thanks.
