### ISSUE TITLE
Windows 11 22H2 build 22621.2134 Taskbar Windows 10 style transparent

### ISSUE THREAD

**Issue by Zac1209** [valinet/ExplorerPatcher#1865]
I've updated my Windows to the version in the title. My taskbar is now always transparent in Windows 10 mode. It's fine in Windows 11 mode.

EP up to date version 22621.1992.56.1

**Comment by pyrates999** [comment]
If you have classic shell installed, uninstall it. That is no longer maintained.

**Comment by Zac1209** [comment]
> If you have classic shell installed, uninstall it. That is no longer maintained.

That's the case and it "fixed" the problem. I'm bummed that it doesn't support it anymore. Those 2 where great together. 

Thanks

**Comment by Zac1209** [comment]
UPDATE: Installing Open Shell fixed the issue and let me keep all my Classic Shell config.
