### ISSUE TITLE
StartMenuExperiencehost.exe crashes on launching start menu while ExplorerPatcher app is installed on Win11

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#1866]
ExplorerPatcher v22621.1992.56.1
Repro Steps:

1. Prepare SV2 RTM 22621.1
2. Install below SV2 Moments Package
    - a. Install 2023.08A UNO Package KB5029336 v1.001 from below.
    - b. [171584 - Package Artifacts (trafficmanager.net)](https://nam06.safelinks.protection.outlook.com/? url=https:%2f%2fpackagecloud.trafficmanager.net%2fartifacts?id%3D171584&data=05%7c01%7cv-lakrac%40microsoft.com%7cf4a41d9d3133443beee908db93d1d8db%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638266301867905643%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=5n7eEcjqcF836ju25xQJBjbbIrFBH%2fGdcjdkRU7WvJ4%3D&reserved=0)
    - c. Restart the machine.

1. Observe the Winver as 22621.2191
2. Install below Feature Enablement Package
3. Install EKB Package KB5027397 v1.000 from below.
4. [169285 - Package Artifacts (trafficmanager.net)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fpackagecloud.trafficmanager.net%2fartifacts?id%3D169285&data=05%7c01%7cv-lakrac%40microsoft.com%7ca7583fc5f5384b6f5ece08db8f14b2eb%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638261091397928927%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=3r0t1K1ArVVUW4HauXSirvZI7IP2SthS4OLRctgwFRk%3D&reserved=0)
5. Restart the machine.
6. Observe the Winver as 22631.2191
7. Install the ExplorerPatcher application.
8. Observe.

Actual Result:
StartMenuExperiencehost.exe crashes on launching start menu while ExplorerPatcher app is installed

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by Michellehdr** [comment]
@pyrates999 
on enabling the console, the application is trying to download the symbols, but failed to do so with an error.
![Screenshot](https://github.com/valinet/ExplorerPatcher/assets/75816577/e054d541-91d5-43e8-bc4b-f7e236e4925b)

**Comment by pyrates999** [comment]
Your version of windows is an insider build and it looks like Microsoft doesn't provide symbols to download for it: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

And when I googled your version of windows, there's no Microsoft Page on it.  This is the last insiders build that Microsoft released: https://blogs.windows.com/windows-insider/2023/08/18/announcing-windows-11-insider-preview-build-22621-2199-and-22631-2199-beta-channel/

Is there any technical reason why you are running an insider build?

**Comment by Michellehdr** [comment]
@pyrates999 I'm from Microsoft Windows team, we are testing with latest version. That might be the reason you cannot find it from google. I'm wondering do you know how could we get those symbols on all Windows version?

**Comment by pyrates999** [comment]
> @pyrates999 I'm from Microsoft Windows team, we are testing with latest version. That might be the reason you cannot find it from google. I'm wondering do you know how could we get those symbols on all Windows version?

Microsoft provides the symbols.  Either as a download or as part of the windows install for insider builds.

**Comment by Michellehdr** [comment]
Thanks for your kind reply @pyrates999 our engineer will take a look at the issue.

**Comment by iAmWednesday** [comment]
I have the same setup, Insider Preview Build 23486.ni_prerelease.230616-1447
Same issue occurs - StartMenuExperienceHost.exe crashes every time Start button is pressed.
I uninstalled ExplorerPatcher, but Start still crashes all the time. How do I fix?

**Comment by pyrates999** [comment]
Recent changes here indicate that preview builds and insider builds are not supported by EP.

**Comment by Poopooracoocoo** [comment]
Leave a comment if you think this should be reopened.

**Comment by Amrsatrio** [comment]
Our latest release have been tested to work fine on 22631.2338 (Beta channel). Since the build in question is lower than that, I will be closing this issue.

(Also why are you sending Outlook links to internal endpoints?)
