### ISSUE TITLE
UPDATE: Updated Windows 11 to new version

### ISSUE THREAD

**Issue by aldeniangman** [valinet/ExplorerPatcher#1870]
UPDATE! MY EXPLORERPATCHER wont let me change taskbar position. Need a alternative for now. ideas? NO STARTALLBACK!

**Comment by rustyjarz** [comment]
I've got a similar issue where if I right click the task bar explorer crashes.

**Comment by Ghostdreamer11** [comment]
Same here, right click the task bar explorer crashes :(

**Comment by pyrates999** [comment]
Please do not cross post.  The crash you described was already reported: https://github.com/valinet/ExplorerPatcher/issues/1828

This should be closed because it doesn't serve any purpose except for ranting.

**Comment by Gxtod** [comment]
Update the version of ExplorerPatcher, make all the necessary procedures automatic, the tips that you give here do not work, no symbols are set manually, editing the paths in the registry does nothing and the Explorer patcher still crashes, it crashes with an error and it tires and infuriates. 
Do something about this ugly and miserable bug. It's been a month now, please fix this issue in the coming days!!!

**Comment by aldeniangman** [comment]
> 

Updated to Latest Version. lets install from here.

**Comment by rustyjarz** [comment]
> > 
> 
> Updated to Latest Version. lets install from here.

What the hell does this even mean?

**Comment by aldeniangman** [comment]
closed
