### ISSUE TITLE
After updated to new Windows Insider version, ExplorerPatcher won't let me change the taskbar alignment or apply modifcations. Fix?

### ISSUE THREAD

**Issue by aldeniangman** [valinet/ExplorerPatcher#1877]
I have updated to the new Windows Insider version, but it's not letting me modify the taskbar or use explorerpatcher right-click style. It's showing labels though. How do you think I could fix it?

**Comment by pyrates999** [comment]
What is the technical reason for why you are running an insider build?

**Comment by aldopaolo** [comment]
in my case, both Build
- 23H2 22631.2199 feature pack 1000.22672.1000.0
- Insider preview - 22H2 23526.1000 feature pack 1000.23526.1000.0;Build 22H2;
works correctly:
- 22H2 22621.2134 feature 1000.22659.1000.0
all on VM

**Comment by aldeniangman** [comment]
> 

STOP ASKING. The reason why because I wanna try out new features

**Comment by Poopooracoocoo** [comment]
EP is not compatible with Insider builds.

**Comment by aldeniangman** [comment]
ill wait
until made new update
