### ISSUE TITLE
Lenovo onscreen display no longer works

### ISSUE THREAD

**Issue by helloguys88** [valinet/ExplorerPatcher#1878]
With the latest version of EP (22621.1992.56.1), Lenovo on screen display no longer works.  Uninstalling EP fixes the problem.

Lenovo on screen display is an app that displays the volume or screen brightness value when adjusting them with the keyboard.

**Comment by helloguys88** [comment]
Duplicated with "volume, brightness bar not visible" issue.

**Comment by pyrates999** [comment]
Work around until this gets fixed: install an application from the microsoft store called "modernflyouts".
