### ISSUE TITLE
Total crashed PC after opening ep_setup.exe (video)

### ISSUE THREAD

**Issue by real-mack** [valinet/ExplorerPatcher#1881]
Hi,
when I downloaded the release and opened "ep_setup.exe" in Win 11 Home my PC totally died. Everything dissapeard and both my monitors started blinking and never stopped. Only thing what i could do was open Task Manager. Restart PC did not help. Safe mode did not help. Repair PC did not help. Basically nothing. 

I dont know what to do. I currently switched my SSD for SSD with Win10 so I can do at least something while I figure this out.

Video what happened after opening ep_setup.exe you can watch here in the attachment.

https://github.com/valinet/ExplorerPatcher/assets/142815941/f37898d7-0f44-44ea-98c6-f7765805363b

**Comment by Daniel-OS01** [comment]
I've had the same problem since the last Win11 update about two weeks ago.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by real-mack** [comment]
@Tehtoom I wasnt able to do that at all. That was first i was trying to. I fixed it by switching to backup SSD Win10  and from there I found out some .dll file and deleted it which someone recommended in discussion and then uninstalled it. Thank god.

@Daniel-OS01 So im not the only one? I once tried "Start11" by Stardock.com (but I uninstalled it) and I thought it could cause that.

@pyrates999 Version 22H2 (build 22621.2134) Win 11 Home.
It was the latest version of your program ExplorerPatcher.
I didnt change any settings. Did you read what I stated? I said that i opened ep_setup.exe for the first time and on the video you can see what happened immediately  after that.

**Comment by pyrates999** [comment]
Thank you.

Please open up windows event viewer or computer management
Go to Event Viewer and go to Windows Logs -> Application
Refresh the list of logs by clicking on the refresh button

Check for any entries that are recent that has ep_setup.exe in it.

**Comment by real-mack** [comment]
@pyrates999 Why do i have to do that? whats it for?

**Comment by Daniel-OS01** [comment]
> Thank you.
> 
> Please open up windows event viewer or computer management Go to Event Viewer and go to Windows Logs -> Application Refresh the list of logs by clicking on the refresh button
> 
> Check for any entries that are recent that has ep_setup.exe in it.

Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c
Faulting module name: dxgi.dll, version: 22621.1992.56.3, time stamp: 0x64e6228c
Exception code: 0xc0000005
Fault offset: 0x000000000001099d
Faulting process id: 0x0x88F0
Faulting application start time: 0x0x1D9D98B935EBF42
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\dxgi.dll
Report Id: 65ffeb6b-b9d3-4d8c-a6b0-b71b023bc914
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pyrates999** [comment]
You got a preview update installed: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by mephistophen** [comment]
Hello, do you know how to launch de command of uninstall ep_setup.exe /uninstall but quietly ? 

I have to launch multiple uninstall of dozen of workstation because of this issue with Windows Update. 

Thank you

**Comment by pyrates999** [comment]
> Hello, do you know how to launch de command of uninstall ep_setup.exe /uninstall but quietly ?
> 
> I have to launch multiple uninstall of dozen of workstation because of this issue with Windows Update.
> 
> Thank you

Maybe ask this in a new discussion as it would be considered a new feature if it currently does not exist.

**Comment by pyrates999** [comment]
> @pyrates999 Why do i have to do that? whats it for?

For the developers to know the crash details.

**Comment by pyrates999** [comment]
> > Thank you.
> > Please open up windows event viewer or computer management Go to Event Viewer and go to Windows Logs -> Application Refresh the list of logs by clicking on the refresh button
> > Check for any entries that are recent that has ep_setup.exe in it.
> 
> @pyrates999 Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c Faulting module name: dxgi.dll, version: 22621.1992.56.3, time stamp: 0x64e6228c Exception code: 0xc0000005 Fault offset: 0x000000000001099d Faulting process id: 0x0x88F0 Faulting application start time: 0x0x1D9D98B935EBF42 Faulting application path: C:\WINDOWS\explorer.exe Faulting module path: C:\WINDOWS\dxgi.dll Report Id: 65ffeb6b-b9d3-4d8c-a6b0-b71b023bc914 Faulting package full name: Faulting package-relative application ID:

Thank you.

**Comment by Poopooracoocoo** [comment]
ExplorerPatcher has a new update that brings compatibility with OS Build 22621.2283
