### ISSUE TITLE
Volume and Brightness rockers not showing up

### ISSUE THREAD

**Issue by Epixx512** [valinet/ExplorerPatcher#1883]
When I press the volume up/down and brightness up/down buttons, the rockers on the bottom of the screen don't show up. I installed ep because I hate the windows 11 design. I don't wanna upgrade to Windows 10, its too complicated. But that's not the point. The rockers are not there, and it is really annoying. I have to go into the volume flyout to check. Sometimes when I'm in a game, I don't have time for that. Please fix this asap.

**Comment by Wild-Chicken** [comment]
same problem here

**Comment by Poopooracoocoo** [comment]
Duplicate of #1692

Also as a workaround you could use ModernFlyouts
