### ISSUE TITLE
Windows 22621.2213 error found

### ISSUE THREAD

**Issue by Krassikn** [valinet/ExplorerPatcher#1890]
ExplorerPatcher crashes on Windows 22621.2213. None of the supposed fixes works. I used a console to find the error. Here it is if it is of any help fixing the issues. 

I uninstall ExplorerPatcher and remove all registry leftovers. Restarted. New install than restart again. The first time I open the file explorer (any folder) the following error appears in the console - 
"10000 46000000
0 46000000
Error in sub_1800135EC on RoGetActivationFactory."

After this I close the file explorer and on next reopening the ExplorerPatcher crashes and restarts.

This error appears every time on opening any folder than on second opening ExplorerPatcher crashes and restarts.

Hope it is of any help.

**Comment by Poopooracoocoo** [comment]
I don't think this has changed: ExplorerPatcher running on Windows Insider Preview builds is not supported

**Comment by wohack** [comment]
Ok, I have overseen the version shown on the top.
My 5 systems are running Windows 11, OS Build 10.0.22621.2134.
This is the normal august update.
They show exactly the same behavior as the preview.

**Comment by wohack** [comment]
I can open a new issue if necessary.

**Comment by Poopooracoocoo** [comment]
Yes a new issue would be best. Do a quick search before that though

**Comment by wohack** [comment]
Thats the console output during Explorerpatcher restart (symbol download disabled)

funchook create 1
Running on Windows 11, OS Build 10.0.22621.2134.
Loaded symbols
Setup ntdll functions done
Setup user32 functions done
Patched taskbar transparency in newer OS builds
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
[Positioning] Added settings for monitor 0000000000010001 : 0
Progman: 2426336
Progman hook: 9962955
>>> Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
0 0
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[Updates] Starting daemon.



and that the output first time open the file explorer

10000 46000000
0 46000000
Error in sub_1800135EC on RoGetActivationFactory.
