### ISSUE TITLE
Task View no longer working with windows security update KB5029263

### ISSUE THREAD

**Issue by brx6995** [valinet/ExplorerPatcher#1891]
As of the latest update, EP is having a lot of issues. The task view and alt-tab stopped working on the Windows 10 taskbar once Windows auto-installed the latest security update. Considering this is a major part of my daily functions it is an issue. Even though I was able to work around that by continuously uninstalling KB5029263. EP is still crashing once every hour and is majorly draining my CPU because of it keeps trying to relaunch all startup apps. Please fix this issue. 

I use EP because it allows me to put my taskbar on the left side of my screen, which is a feature that was done away with in Windows 11 so turning off EP and using straight Windows 11 is not an option.

**Comment by brx6995** [comment]
Neither are working for me, and my ability to use task view is a hell of a lot more important to me than ALT-TAB as I like to keep my various projects on separate desktop screens. I was able to find a fix in one of the other reported issues for the crashing & CPU drainage. But I still can't find a fix to the task view issue. Despite it being almost a month since the first time this issue came up. It was fine until Windows decided it was going to make KB5029263 a mandatory update. And my issue reports keep getting closed despite the lack of an actual fix.

**Comment by Imold** [comment]
Unfortunately if you need task view your only options are to uninstall KB5029263, or use the Windows 11 taskbar. If you want to uninstall KB5029263, [here's an article on how you can prevent Windows Update from reinstalling it.](https://pureinfotech.com/show-hide-updates-windows-11/)
