### ISSUE TITLE
Windows 11 22621.2215 build can no longer open start menu

### ISSUE THREAD

**Issue by Stealrull** [valinet/ExplorerPatcher#1897]
Updated to this build this morning, and start menu doesn't work unless you uninstall explorer patcher.

Tried resetting to default settings and still couldn't click the start menu, only came back after uninstalling completely.

Can't be clicked on or use keyboards windows key, neither work.

**Comment by sagara129** [comment]
same issue; had to uninstall

**Comment by yukaribbba** [comment]
Same here

**Comment by lindaiyu99** [comment]
same after install KBKB5029351 on win11

**Comment by arsampson** [comment]
Here too.

**Comment by bsdinis1** [comment]
+1

**Comment by chhoumann** [comment]
ExplorerPatcher just downloaded an update for symbols, which resolved the issue for me. I'm on 22621.1992.56.1.

**Comment by Bo-Liu-BL** [comment]
I also encountered this issue. It should be caused by the latest update KB5029351.
See https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

**Comment by yukaribbba** [comment]
After symbol update the issue is solved.

**Comment by Poopooracoocoo** [comment]
Preview Windows updates are not supported

**Comment by nijawang** [comment]
> ExplorerPatcher just downloaded an update for symbols, which resolved the issue for me. I'm on 22621.1992.56.1.

Could you share how to do symbols update?

**Comment by nijawang** [comment]
I have this same issue after update to Win11 22621.2215.
However, startup menu and search operation back to normal after around 2 hour.

**Comment by bsdinis1** [comment]
Solved after downloading symbols, but explorer.exe is still crashing when opening File Explorer

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

**Comment by ltxhhz** [comment]
same issue.
and I didn't installed preview updates
![image](https://github.com/valinet/ExplorerPatcher/assets/51697596/fb3e3507-8bd1-4928-84fd-8acad6ae1e90)
