### ISSUE TITLE
[22000.176] Patch not having effect[solved, but note for others]

### ISSUE THREAD

**Issue by BraINstinct0** [valinet/ExplorerPatcher#19]
After placing the dll at the correct place, it doesn't show any diffrence - but when trying to delete it, it says that it's in use.
Restarted both PC & explorer.exe.

EDIT: wait, it sometimes take some time to become effective. seems like at most ~5 min wait is helpful

**Comment by valinet** [comment]
That 5 mins is the time it takes to download symbols. Obviously it is in use, it is downloading symbols. Normally it should show a toast informing you of this, as described in the README. If you have disabled toasts, you indeed see nothing. The idea is to wait a bit while it downloads the necessary stuff, you can check in Task Manager for network activity.

**Comment by BraINstinct0** [comment]
Yes, I think that toast has been disabled (somewhere in the process of extensive windows modification).
I made a quick PR to the README for those who might(though I'd say unlikely) experience

**Comment by valinet** [comment]
Okay, noted, accepted the merged. Thank you.
