### ISSUE TITLE
[win10 style start menu] "pin to start" and "unpin from start" are unavailable

### ISSUE THREAD

**Issue by 6Tom** [valinet/ExplorerPatcher#1903]
The actual version of Windows is KB5029263 (OS Build 22621.2134), which is a stable version, not a preview. You can find it here:
[https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8](https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8)

In fact, this issue exists in both explorer patcher [22621.1992.56.2](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.2_cfd53c9) and [22621.1992.56.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541)

However, explorer patcher [22621.1555.55.2](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.2_6fb998e) does not have this issue, so I have temporarily rolled back to this version.

I love explorer patcher so much. [valinet](https://github.com/valinet) you are a super hero!

**Comment by pyrates999** [comment]
work around listed here: https://github.com/valinet/ExplorerPatcher/discussions/1679

**Comment by 6Tom** [comment]
Oh, thank you very much for that. Sorry I didn't find this content before. I didn't find relevant information in the issue area and directly started a new issue. Sorry. I'm going to close it right now.
