### ISSUE TITLE
Windows 10 Start menu not working on windows 11 insider build 25284.1000

### ISSUE THREAD

**Issue by asifashraf80** [valinet/ExplorerPatcher#1906]
I installed Explorer Patcher on Windows 11 insider build 25284.1000 and tried to use the windows 10 start menu and it didn't work. It would just not open.

**Comment by pyrates999** [comment]
Insider builds are not supported.  Please close this.

**Comment by asifashraf80** [comment]
oh well, I'll have to dualboot windows 10
