### ISSUE TITLE
Win10 style start menu cannot run on some devices

### ISSUE THREAD

**Issue by Gostronaut** [valinet/ExplorerPatcher#1909]
I  installed EP on three different devices and they obtained different results
When installed on my first VM device, it worked normally
Information for the first device：
      22H2
      22621.2215
      Feature Experience Pack 1000.22622.1000.0
When I installed the second device, it didn't work

![cdry](https://github.com/valinet/ExplorerPatcher/assets/139110182/526fd2e4-d3ef-4942-a5ae-42f57efca379)

The parameters of the second device are the same as those of the first device
I created a new VM and installed it using the same system image, but it encountered the same issue as the second device，So I deleted _C: \Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_Cw5n1h2txyewy\dxgi.dll_
It has encountered this situation↓

![ery](https://github.com/valinet/ExplorerPatcher/assets/139110182/cc0a7856-32df-478e-91e2-bbd829e3d241)

I'm not sure how it caused it, but the same problem also occurred on my other physical host. May it be caused by my system language? Devices that can open the Win10 style start menu are all in English when opening the start menu. After deleting dxgi.dll, the open start menu displays Chinese

![image](https://github.com/valinet/ExplorerPatcher/assets/139110182/c25f085f-3cfd-415b-8bcd-9a28fad06c7b) ![image](https://github.com/valinet/ExplorerPatcher/assets/139110182/29cb42b7-287b-44de-af62-47d80719e55a)

Thank you very much for taking the time to review this issue

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Gostronaut** [comment]
> That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692
> 
> Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.

Thank you, I will soon find the old version of iso, and I remember that the only device that can function properly was previously upgraded from 21h2 to 22h2, while other devices are installed with the latest version of 22h2. Afterwards, I will close this issue

**Comment by Gostronaut** [comment]
> That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692
> 
> Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.

Sorry, I used the 21h1 iso and it still appears to be unable to open the start menu

**Comment by pyrates999** [comment]
Check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

You can check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  If it shows it can't download symbols, your version of windows is not supported.

**Comment by Gostronaut** [comment]
> Check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> You can check using the console in explorer patcher. Open up the properties application for explorer patcher, go to advanced, and click on enable console. If it shows it can't download symbols, your version of windows is not supported.

I have opened the console in previous tests, and all symbols have been successfully downloaded and read. A successful download pop-up window has also popped up in the lower right corner. I have also restarted Explorer and the system, which is consistent with the description in the Wiki, and there are no errors

![QQ截图20230824235906](https://github.com/valinet/ExplorerPatcher/assets/139110182/e1ded482-1502-4259-be31-ee447925badb)


What makes me question is that two of the same system images can use EP's start menu normally, but other machines with the same configuration installed in the same image cannot, including VMs and real machines. The two computers that can be used are a VM using 22h2, as well as a laptop purchased from an offline store. The laptop was upgraded from 21h2 to 22h2, and I installed EP after upgrading to the latest version. EP and start menu are running normally

 I compared the consoles of devices that can run EP normally with those that cannot, and they only have a few different lines

![QQ截图20230825000846](https://github.com/valinet/ExplorerPatcher/assets/139110182/756c273d-f670-41ba-9174-57782957020f)

**Comment by pyrates999** [comment]
You have different versions of explorer patcher installed.  One is 22622.**1555.55**.2.  And the other is 22622.**1992.56**.2 .  Update them all to the latest release here: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Gostronaut** [comment]
> You have different versions of explorer patcher installed. One is 22622.**1555.55**.2. And the other is 22622.**1992.56**.2 . Update them all to the latest release here: https://github.com/valinet/ExplorerPatcher/releases

I'm sorry, I have updated to the latest version of EP in multiple VMs. VMs and physical machines that can still be used normally can still be used. VMs and physical machines that cannot open the start menu cannot be opened

I found the installation files from a long time ago on my hard drive, but they still cannot open the start menu properly

I suspect it's my hardware issue because after deleting dxgi.dll from the system apps StartMenu ExperienceHost, the start menu opened, but it stuck for 1 second when closed. However, there is a VM with the same configuration and a laptop using an Iris integrated graphics card that uses the start menu normally without the need to delete this DLL. If you are willing to provide some suggestions, I will offer you a substantial thank you

**Comment by pyrates999** [comment]
Your console output shows 2 different versions of EP.

**Comment by Gostronaut** [comment]
#704 
I initially referred to all the solutions in this issue, but it did not solve my problem. I also created multiple VMs to try it out separately

**Comment by Gostronaut** [comment]
> Your console output shows 2 different versions of EP.

It's like this, the VM on the left is a console that uses the start menu normally, while the VM on the right cannot open the start menu normally. I just installed the same EP version on the left side for the newly created VM, but did not open the start menu properly. And the vm on the left has also been upgraded to the latest version of EP, and the start menu can also be opened normally

**Comment by Gostronaut** [comment]
#704 
I initially used all the solutions in this issue, but it did not solve my problem. I also created multiple VMs to try it out separately for this purpose

**Comment by pyrates999** [comment]
You did not install the same version on both.  Install this version: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.3_5bda71f

And redo your tests with the console output on both.

**Comment by Gostronaut** [comment]
> You did not install the same version on both. Install this version: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.3_5bda71f
> 
> And redo your tests with the console output on both.



> You did not install the same version on both. Install this version: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.3_5bda71f
> 
> And redo your tests with the console output on both.

I have all updated to the same version, and this is a picture of the console
![QQ截图20230826204023](https://github.com/valinet/ExplorerPatcher/assets/139110182/2ddbf6ce-5bac-42e6-8451-e44ff1c728ad)

On the right is a device that can open the start menu normally, while on the left is a device that cannot open the start menu. Similarly, when I delete dxgi.dll on the left, the start menu can be used normally, but the phenomenon mentioned above will occur

The following image shows the console after I deleted dxgi.dll
![QQ截图20230826204722](https://github.com/valinet/ExplorerPatcher/assets/139110182/65e4b2e9-be23-4bf7-8dbb-d6676a73d492)
If you need more information such as system and files, I would be happy to provide you with some details

**Comment by pyrates999** [comment]
This shows you're running 22621.1992.56.2, I gave you a link to this version 22621.1992.56.3.  Update to it.

But you're testing old versions of windows:

On the left you are running windows 22621.1702, which is this update: https://support.microsoft.com/en-gb/topic/may-9-2023-kb5026372-os-build-22621-1702-ce93c18e-e819-458f-abcf-dc7154ce7e40

On the right you are running windows 22621.1776, which is an insider build: https://www.elevenforum.com/t/kb5026446-windows-11-insider-release-preview-build-22621-1776-22h2.14816/

Insider builds are not supported.

The version of EP is designed for this release: https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

Please close this as the versions you are testing on are not supported.

**Comment by Gostronaut** [comment]
> This shows you're running 22621.1992.56.2, I gave you a link to this version 22621.1992.56.3. Update to it.
> 
> But you're testing old versions of windows:
> 
> On the left you are running windows 22621.1702, which is this update: https://support.microsoft.com/en-gb/topic/may-9-2023-kb5026372-os-build-22621-1702-ce93c18e-e819-458f-abcf-dc7154ce7e40
> 
> On the right you are running windows 22621.1776, which is an insider build: https://www.elevenforum.com/t/kb5026446-windows-11-insider-release-preview-build-22621-1776-22h2.14816/
> 
> Insider builds are not supported.
> 
> The version of EP is designed for this release: https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8
> 
> Please close this as the versions you are testing on are not supported.

Thank you very much for your answer, but one thing is that the device on the right side 1772 can use the start menu, while the device on the left side 1702 is not available. I swapped the window sorting of the two VMs during the screenshot, and I am very sorry

In addition, I have already installed 22621.2134, but EP still does not open the win10 style start menu
![QQ截图20230827010115](https://github.com/valinet/ExplorerPatcher/assets/139110182/1fa850a0-0689-4bf4-a5f8-13ebf26b34bd)

I still need to delete dxgi.dll to use it and there is a lag issue

**Comment by pyrates999** [comment]
It shows it's unable to connect to github.com.

I think this is happening because you can't download the symbols, because that is also being blocked.  And symbols are a technical requirement for EP to function.

And the reason why 1772 works is because insider builds include symbols already.

**Comment by Gostronaut** [comment]
> It shows it's unable to connect to github.com.
> 
> I think this is happening because you can't download the symbols, because that is also being blocked. And symbols are a technical requirement for EP to function.
> 
> And the reason why 1772 works is because insider builds include symbols already.

My writing is incorrect, the one that can run is 1776, not 1772, it's my problem

The symbol can be downloaded normally, as shown in the image above. I just tried using the proxy, but the startmenu is still invalid, even if EP can check for updates and download. Similarly, there are two devices for 1702 and two devices for 1776 each. I don't know why, only one VM for 1776 has its EP correctly opened the start menu, and all 2134 devices (including a total of four physical machines) cannot be used. The other version that can be used is a VM for 2215

I found the images used to install these two VMs and attempted to reproduce this method, but both failed. I also don't know why these two VMs were able to open the startup of EP normally, and they have not used a proxy

If you need more information, I will find it and reply. Thank you for your answer

**Comment by Gostronaut** [comment]
The only way I found is to delete dxgi.dll, but this will cause the start menu to be abnormal

**Comment by Gostronaut** [comment]
> It shows it's unable to connect to github.com.
> 
> I think this is happening because you can't download the symbols, because that is also being blocked. And symbols are a technical requirement for EP to function.
> 
> And the reason why 1772 works is because insider builds include symbols already.

Oh my goodness, I did it. I installed startallback and set it to use the Win10 style. When I closed the startallback start menu, the EP start menu worked normally. I finally understood why some devices can use the EP startmenu because they also installed startallback and set the Win10 style

But I don't know how it works, maybe it's a feature?
