### ISSUE TITLE
Crash and restart explorer with KB5029263 Build 22621.2134

### ISSUE THREAD

**Issue by MaybeAnge** [valinet/ExplorerPatcher#1911]
Crash on last update: [22621.1992.56.3](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.3_5bda71f)

**Comment by arcaeatairitsu** [comment]
also crashes with KB5029351

**Comment by Edwin-Baranov** [comment]
Latest version currently crashes as soon as I right click on taskbar

**Comment by VasiliyIsaichkin** [comment]
Crash on 22621.2215

**Comment by nhnduy** [comment]
> also crashes with KB5029351

Yes. It keeps crashing with Windows Update KB5029351.

**Comment by r00tl34k** [comment]
Crash all time with the last release.

**Comment by Poopooracoocoo** [comment]
Duplicate of #1798
