### ISSUE TITLE
22621.1992.55.3 volume indicator not visible

### ISSUE THREAD

**Issue by aevinj** [valinet/ExplorerPatcher#1916]
windows 11 home - 22H2 - 22621.2215.
tried uninstalling and the indicator returns to normal. reinstalled the latest version and the volume indicator is gone again.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

Work around until this gets fixed: install an application from the microsoft store called "modernflyouts".
