### ISSUE TITLE
The File Explorer Ribbon Can't Be Changed And Stuck On Windows 10's. I want To Use The Windows 11 Ribbon But I Can't.

### ISSUE THREAD

**Issue by vbn47** [valinet/ExplorerPatcher#1917]

**Comment by vbn47** [comment]
Note: Of Course I Tried To Change That In The Explorer Patcher Settings But It Doesn't Change It At All

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by vbn47** [comment]
Windows Version:Windows 11 Pro 64-bit (10.0,Build 22000) 21H2
ExplorerPatcher: Version 22621.1992.563
![image](https://github.com/valinet/ExplorerPatcher/assets/143051530/defd31fb-1746-498c-9307-764afdb7b2a5)

**Comment by pyrates999** [comment]
Try restarting file explorer.

**Comment by vbn47** [comment]
I Did Multiple Times.

**Comment by pyrates999** [comment]
Please wait for a fix then.

**Comment by Amrsatrio** [comment]
Delete `HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}`. If it still doesn't work, you may reopen this.
