### ISSUE TITLE
Win + TAB not working

### ISSUE THREAD

**Issue by klodoma** [valinet/ExplorerPatcher#1920]
If I install [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) then Win + Tab doesn't work anymore. 
Cannot change desktops.

If uninstalled it works. 

Am I missing some settings for this?

**Comment by klodoma** [comment]
Dupplicated of  #1687

**Comment by Girofox** [comment]
`Win + Tab` and `Alt + Tab` definitely works for me in the latest update for EP _22621.1992.56.3_ in both Windows 10 and 11 Taskbar mode. It didn't worked on version `22621.1992.56.1` though.

**Comment by Infernis264** [comment]
On a freshly set up VM running Windows 11 Home build `22621.2134` and EP `22621.1992.56.3`, I can confirm that `Win + Tab` is broken. All settings were left as their default except for taskbar grouping, which was turned on. Turning taskbar grouping off does not resolve the issue.

**Comment by avdhooft** [comment]
After starting EP, alt+tab works fine. But win+tab does not work. And after trying win+tab, alt+tab does not work anymore.
Only restarting EP makes alt+tab work again. 
I'm using Win11 and EP 22621.1992.56.3 and win10 taskbar mode and taskbar grouping Never combine

**Comment by yolomep** [comment]
Will this issue be fixed? Same problem, Windows 11 Home build 22621.2134 and EP 22621.1992.56.3. Which windows version still works or should I downgrade EP? I'm using it for the windows 10 taskbar so the original fix is not applicable.

**Comment by pyrates999** [comment]
Please close this as it is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687
