### ISSUE TITLE
Cannot open desktop folder in Explorer

### ISSUE THREAD

**Issue by GameAreaCZ** [valinet/ExplorerPatcher#1925]
IT just freezes and crashes, same with OneDrive folder.
Windows 11 version 22H2 build 22621.2134

**Comment by kvanbiesen** [comment]
uninstalling KB5028948 and KB5029263 fixed it for me..

**Comment by GameAreaCZ** [comment]
How? When I click uninstall in the history .. nothing is happening.

**Comment by kvanbiesen** [comment]
run as admin -> rundll32.exe shell32.dll,Control_RunDLL appwiz.cpl


or go tru "control panel and then then add/remove software" then you hav
ethe old windows, uninstall windows updates or something similar. You
should be able to uninstall those there....

dont know the exact names as my windows isnt set to english

**Comment by pyrates999** [comment]
What version of EP did you install?

Did you check that symbols were download?  https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by GameAreaCZ** [comment]
IDK what that is, but the uninstall updates helped. Thank you.
