### ISSUE TITLE
ExplorerPatcher.IA-32.dl blocked by BattleEye

### ISSUE THREAD

**Issue by cktger** [valinet/ExplorerPatcher#1927]
After the update yesterday I got the following error message from the AntiCheat program BattleEye when starting Escape from Tarkov: 16:32:12: [INFO] The loading of the file was blocked: "C:\Program Files\ExplorerPatcher\ExplorerPatcher.IA-32.dll".

I can ignore the error message and play the game normally. After I switched back to version 22621.1992.56.1 I didn't get this error message anymore.

Windows 11 Pro for Workstations
Version: 22H2
Build: 22621.2134

**Comment by SiteSplat** [comment]
yes this is annoying. Can the dev look into this issue when possible?

**Comment by Poopooracoocoo** [comment]
Shouldn't you report this to BattleEye?
