### ISSUE TITLE
Constant explorer.exe errors logged after installing EP

### ISSUE THREAD

**Issue by djc5166** [valinet/ExplorerPatcher#193]
Getting (multiple per day) memory dumps and fault logs in event viewer after installing explorer patcher, they look more or less like the following.

Faulting application name: explorer.exe, version: 10.0.22000.120, time stamp: 0xe846e749
Faulting module name: dxgi.dll, version: 22000.258.31.0, time stamp: 0x6171039f
Exception code: 0xc0000005
Fault offset: 0x000000000000ac24
Faulting process id: 0x54b4
Faulting application start time: 0x01d7c6cdde9c78d2
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\dxgi.dll
Report Id: f19825a3-8766-4984-83e5-79e0e42f6c93
Faulting package full name: 
Faulting package-relative application ID:

**Comment by valinet** [comment]
I will close this for now. Feel free to post any updates on your part. Thanks.

**Comment by djc5166** [comment]
I have not seen these event viewer errors and memory dumps since moving to 22000.282.32.0, so whatever it is I think you have potentially solved it.

**Comment by valinet** [comment]
Thanks for the feedback. Yeah, I refactored and fixed quite a few things in the back end in the latest build, paid more attention to some edge cases etc. Polish, we could say, things that had to be done, despite not being so “flashy” in the change log. That it also solved the issues you reported is also a nice bonus, indeed. Thanks.
