### ISSUE TITLE
Right-clicking on taskbar causes crash/restart of Windows

### ISSUE THREAD

**Issue by discgolfdc** [valinet/ExplorerPatcher#1931]
As the title says.  Right-clicking on taskbar causes crash/restart of Windows.  Unable to access a right-click menu on taskbar, let alone the "Properties" menu entry.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎7/‎20/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

**Comment by gameshack** [comment]
Duplicate of these: #1805 #1700 #1527

**Comment by discgolfdc** [comment]
Closed as duplicate.  My apologies.
