### ISSUE TITLE
Taskbar Right click restart Explorerpatcher

### ISSUE THREAD

**Issue by ramonsantana** [valinet/ExplorerPatcher#1932]
If i have the properties settings on taskbar it restarts EP when i right click the taskbar, no context menu.

**Comment by jcharlier** [comment]
That happened to me too after the last windows update.
Windows 11 Version 22H2 (OS Build 22621.2215)

While waiting for a fix, I disabled EP, renaming `dxgi.dll to dxgi.disable.dll in c:\windows\dxgi.dll`
if you can't open explorer to browse for the file, run a new task in task manager (ctrl+shift+esc) with admin privs -> type `CMD `-> then in the prompt enter: `move c:\windows\dxgi.dll c:\windows\dxgi.disable.dll`

**Comment by Poopooracoocoo** [comment]
Duplicate of #1805
