### ISSUE TITLE
Issue with ExplorerPatcher shell extension

### ISSUE THREAD

**Issue by sonhns** [valinet/ExplorerPatcher#194]
I tried ExplorerPatcher shell extension and then I have the issue as described with the logs below. 

**_(this problem was solved when i uninstalled the ExplorerPatcher shell extension and use the manual method by putting the dll file in Windows folder. No more issue so far. Just report this as i might help you to improve this patcher. )_**

Explorer keep Not Responding when browsing large folder or view photo.

First, it seems like there is an issue with Search Indexing. When I click on Search, there is status saying "Search indexing was turned off" and I cannot turn it on. 

And it seems like that Search Indexing issue my PC hanged when view photo.

I copied 2 event logs below.

- SearchIndexers.exe
Faulting application name: SearchIndexer.exe, version: 7.0.22000.282, time stamp: 0x5759ba2c
Faulting module name: ExplorerPatcher.amd64.dll, version: 22000.258.31.4, time stamp: 0x6172fb61
Exception code: 0xc0000005
Fault offset: 0x0000000000006cc0
Faulting process id: 0x2b24
Faulting application start time: 0x01d7c87af839fd5b
Faulting application path: C:\WINDOWS\system32\SearchIndexer.exe
Faulting module path: D:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
Report Id: dbb3b68d-b88b-4273-919f-6325f1e8ffac
Faulting package full name: 

- Photos.exe
The program Microsoft.Photos.exe version 2021.21090.29009.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 600
 Start Time: 01d7c87af3725a76
 Termination Time: 4294967295
 Application Path: C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2021.21090.29009.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe
 Report Id: da4a81ee-15c7-4687-b967-5f65a19b6d04
 Faulting package full name: Microsoft.Windows.Photos_2021.21090.29009.0_x64__8wekyb3d8bbwe
 Faulting package-relative application ID: App
 Hang type: Cross-process

**Comment by valinet** [comment]
Thanks. The shell extension support is experimental; the recommended method is to drop in C:\Windows, indeed. I will close this since I noted your observations and will try to fix these while working to improve this functionality.

**Comment by gex581990** [comment]
Sadly this is still an issue even on the latest build compiled straight from git in visual studio, downloaded artifact from github actions, and latest stable build.
