### ISSUE TITLE
VirusTotal  3 security vendors

### ISSUE THREAD

**Issue by pict0r** [valinet/ExplorerPatcher#1943]
Hi,
Can you explain to me why VirusTotal marked the newest update as unsafe?
Thanks for your time.

![obraz](https://github.com/valinet/ExplorerPatcher/assets/46075912/3033a6cc-0fb9-420d-af4b-374218d2ddef)

**Comment by pyrates999** [comment]
It's likely a false positive.

**Comment by Poopooracoocoo** [comment]
False positive.
