### ISSUE TITLE
Recommendation for this Issues Listing

### ISSUE THREAD

**Issue by TheSQLGuru** [valinet/ExplorerPatcher#1944]
It would be helpful for those who wish to contribute if you would take some time to properly label the current list of issues. Well, at least the ones that you consider worthy of pursuing. I feel that the "Good First Issue" is quite important, as it would allow those who are new to the Open Source community to get started on something that is manageable. I am one of those people (although I am sadly unable to pursue my growing desire to start paying things forward just yet). 

Wonderful product, BTW!! I have an alarm set to remind me to drop you a donation.

**Comment by Amrsatrio** [comment]
I've done my best in labeling recent issues. Thanks for your suggestion!

Donate me too https://ko-fi.com/Amrsatrio 😅
