### ISSUE TITLE
No properties button when i right click the taskbar

### ISSUE THREAD

**Issue by tanyamga** [valinet/ExplorerPatcher#1948]
I opened the ep_setup.exe file and i can tell its open because it makes my taskbar look different, but when i right click the taskbar to there is no properties button. how do i fix this?

using explorer patcher 22621.1992.56.3 on windows 10v 19045.3324

**Comment by Tempri** [comment]
I am experiencing the same thing. I cannot right click the taskbar for properties and all my programs have combined without any options to separate as text and icons.

**Comment by pyrates999** [comment]
to run the explorer patcher properties application, run this from the run menu:
C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.

**Comment by Tempri** [comment]
thanks for that - it seems I have a different issue then as my entire task bar is not recognising i have the explorerpatcher installed at all but I was still able to bring up the properties as instructed by yourself, toggling any of the options seems to do nothing though.

**Comment by pyrates999** [comment]
Verify that symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Azertixe** [comment]
> 

Hello. Not working here. I am on Win11 22H2. Using EP 22621.1992.56.3 with Win10 taskbar.
Any advice ?

**Comment by pyrates999** [comment]
Please post your windows version and build.

**Comment by Azertixe** [comment]
Win11 22H2 22621.2134

**Comment by pyrates999** [comment]
Please show a screenshot of what right clicking on the taskbar does.

**Comment by Azertixe** [comment]
Hi. It does nothing...

**Comment by pyrates999** [comment]
If no menu shows up when you right click, that indicates that the symbols were not downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Azertixe** [comment]
> If no menu shows up when you right click, that indicates that the symbols were not downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
Hi. When i check for updates it says that "No updates are available".

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by Azertixe** [comment]
Hello. Nothing appens in console when i right click on taskbar.
Thanks for your help

EP 22621.2283.57.2
Build 22621.2134
