### ISSUE TITLE
Some issues with ExplorerPatcher shell extension mode

### ISSUE THREAD

**Issue by TundraWork** [valinet/ExplorerPatcher#195]
Hi! Thanks for your brilliant work on this project!

Here's some issues I encountered when trying the new shell extension loading mode of ExplorerPatcher:

- **"Open Start in All apps by default" feature not working** - The Start menu still opens the main page when this option is enabled.
- **Lock screen displays a black background when using Windows spotlight** - The lock screen will display nothing but a black background when using Windows spotlight. The text descriptions and other controls on it works properly.
- **Visual Studio Code can not launch** - VSCode will display a white frame with no contents and immediately have "(not responding)" status on its UI process.

I can confirm these issues do not exist either on dxgi injection mode, or without ExplorerPatcher installed (if applicable).

**Comment by valinet** [comment]
I will close this since this mode is still experimental; I noted the observations, hopefully I will fix them as I work on improving this.

Thanks
