### ISSUE TITLE
No options in Win+X

### ISSUE THREAD

**Issue by TuBeo5866** [valinet/ExplorerPatcher#1950]
When I press Win+X no options (like settings, task manager, etc) show up
ExplorerPatcher version 22621.1992.56.3 
Using Windows 11 22621.1702

**Comment by pyrates999** [comment]
Check that symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new build should have (at least partially) functioning Win+X before the symbols have been downloaded.
