### ISSUE TITLE
For some reason windows 10 taskbar doesnt work in 22631.2262

### ISSUE THREAD

**Issue by Jaxixteen** [valinet/ExplorerPatcher#1953]
does this bug need to be fixed or is something just going wrong for me
![image](https://github.com/valinet/ExplorerPatcher/assets/143366881/fc092361-48ea-4e73-8f18-47b27961e67c)

**Comment by Poopooracoocoo** [comment]
Insider builds are not supported. It's likely not just you. ExplorerPatcher would need to update to support it once an update is released to all
