### ISSUE TITLE
Here is a solution to the explorer error.

### ISSUE THREAD

**Issue by lovebear94** [valinet/ExplorerPatcher#1954]
Uninstalling Windows Update KB5029263 will solve it.

![01](https://github.com/valinet/ExplorerPatcher/assets/142000403/08390d92-c418-4c76-94fc-37ae63ceeeb1)
![02](https://github.com/valinet/ExplorerPatcher/assets/142000403/26ba90fe-c5c7-4c01-9f83-fa98a1b1de80)

**Comment by pyrates999** [comment]
Please close this and post it in the issues that this update causes.
