### ISSUE TITLE
Windows 11 OS Build 22621 2215 tracker (not currently working with Explorer Patcher)

### ISSUE THREAD

**Issue by fredriklundholm** [valinet/ExplorerPatcher#1955]
Microsofts creates preview updates that then roll into production after some time.
One such update is: Windows 11 OS Build 22621 2215
Currently it does not work with explorerpatcher.
Once it is enabled, let's close this issue. I created this post to aviod "Explorer patcher does not worh with the latest W11 22H2 updates".

**Comment by pyrates999** [comment]
Preview updates are not supported.

**Comment by Daisyfan1995** [comment]
> Preview updates are not supported.

Only occurs in Windows 11 22631.2129 (Beta Insider). While what windows 11 (22631.2115 - Beta Channel & 22631.2134 - Preview (No occurs). it still present but no supported in new updates, before the build 2115 beta or build 2134 preview. after the update for beta channel (Build 22631.2129 > Present Build - Beta Channel (22631.2262) & Preview 22621.2215 still present windows 11 taskbar bug when uses windows 10 taskbar in explorer patcher 1992.56.3 but for now (Windows Insider Channel & Preview Updates are not supported in news versions in windows 11).

**Comment by pyrates999** [comment]
Please close this as this will not be looked at due to it being a preview update.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

**Comment by iamstevedavis** [comment]
@pyrates999 I have never in my life had this enabled and I still received the update. I am not saying you are wrong about this being a preview update but I am unsure that your solution of toggling that box for preventing preview updates.

![image](https://github.com/valinet/ExplorerPatcher/assets/5615792/627dc803-dd4b-4464-9278-0e79c997f0bc)

**Comment by pyrates999** [comment]
> @pyrates999 I have never in my life had this enabled and I still received the update. I am not saying you are wrong about this being a preview update but I am unsure that your solution of toggling that box for preventing preview updates.
> 
> ![image](https://user-images.githubusercontent.com/5615792/266187441-627dc803-dd4b-4464-9278-0e79c997f0bc.png)

With that set to off, you will still get prompted for preview updates.  But they will not be automatically installed.  Then you must resist installing any updates labeled as preview.

**Comment by fredriklundholm** [comment]
Non-Preview KB5030219 (OS Build 22621.2283) have been released, superceeding 2215.
