### ISSUE TITLE
"Windows-P" Shortcut Bringing Up "Action Center", "Windows-A" Shortcut Nonresponsive, Running displayswitch.exe opens notifications

### ISSUE THREAD

**Issue by xoxomonstergirl** [valinet/ExplorerPatcher#1958]
Noticed starting yesterday when I attempted to switch monitors.

My Windows-P shortcut (which I use daily to move rooms that I'm working in) no longer worked. Instead it brings up the notification area similar to the one available by clicking on the date/time or pressing "Windows-A"

Running displayswitch.exe through the start menu also just brings up the notifications area.

This is a huge issue for me, since I usually cannot see the other screen when I switch, and it's a lot of work comparable to switch displays without the shortcut. I went through all the options in the app but couldn't figure out what one would impact it. I'm guessing this is a bug, since nothing changed with my option selection over the last couple days. 

Uninstalling app restored windows-p functionality.

**Comment by Poopooracoocoo** [comment]
OS build and EP version?

**Comment by xoxomonstergirl** [comment]
Was latest version of both at the time, I don't believe I have updated
either since then. it says "2023-08 Cumulative Update Preview for Windows
11 Version 22H2 for x64-based Systems (KB5029351)" was installed on 8/23

**Comment by pyrates999** [comment]
Preview updates are not supported by EP.  Uninstall "2023-08 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5029351)".
