### ISSUE TITLE
Volume bar not appearing on screen anymore

### ISSUE THREAD

**Issue by negru13** [valinet/ExplorerPatcher#1964]
Hi,
The volume and brightness bar stopped appearing on the screen when pressing the keyboard controls. 
Please fix this.

Regards

**Comment by ctitoc** [comment]
Same here, also volume and brightness.

Btw thanks devs for the major crash after update solution.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Comment by rune5362** [comment]
"Work around: set to use windows 11 taskbar instead of windows 10 taskbar."
applay =>
ExplorerPatcher restarted repeatedly and eventually got a warning suggesting deletion, so I deleted it.
------
This sentence was written using a translator.
I apologize if I was rude.

**Comment by Poopooracoocoo** [comment]
Duplicate of #1692
