### ISSUE TITLE
Using taskbar on the top is missing window previews

### ISSUE THREAD

**Issue by jpof88** [valinet/ExplorerPatcher#1970]
When multiple windows of the same program are opened, the windows 11 taskbar style groups the icons and because we are missing the previes it is impossible to select one of the windows from the taskbar. this renders using top taskbar useless.

**Comment by InoriILU** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/89334352/e4094cbb-290d-4dec-9c72-7a7a1e6d4ff4)
![2023-09-02 (8)](https://github.com/valinet/ExplorerPatcher/assets/89334352/b3b4e401-9341-439e-8836-2394abbbb6eb)

me too.
but the win 10 taskbar style also shows no difference, and this phenomenon is often accompanied by the crash and restart of explorer.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by pyrates999** [comment]
Are you able to test it by updating to windows 11 22h2?

**Comment by InoriILU** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/89334352/f325543c-360e-46f2-8daf-19397d84e196)
![image](https://github.com/valinet/ExplorerPatcher/assets/89334352/9dfd96aa-21f7-4782-a0d3-2f1cbb78f394)

**Comment by pyrates999** [comment]
Thank you.  Please wait for a fix.

**Comment by Amrsatrio** [comment]
22621.1992. No issues.
<img width="601" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/4d6ed7d3-b7f3-4d58-a899-2fdd38417a47">

**Comment by Amrsatrio** [comment]
I will close this issue since there seem to be no more responses.
