### ISSUE TITLE
Taskbar at the top of my screen hides the top of any new window.

### ISSUE THREAD

**Issue by JJLocke** [valinet/ExplorerPatcher#1972]
ExplorerPatch version 22621.19922.56.3
Windows 11 version 10.0.22621.2134

I prefer the taskbar at the top of my screen. Doing so often makes the top of newly openned windows appear below the taskbar (hidden by the taskbar). This blocks access to the Miminize, Maximum and Close icons at the top right corner of the new window. 

The only way to minimize or close these newly openned windows is to move my taskbar to the side or the bottom of the screen, close or relocate my app window (to below where the taskbar would be), then move the taskbar back to the top.

Had this problem many years ago with WindowsXP, but don't remember what was done to solve this. 
Does with with the taskbar locked or not. Very Annoying!! Ideas???

Thanks!

**Comment by pyrates999** [comment]
does maximizing the window fix it?

**Comment by JJLocke** [comment]
No, because I cannot get to the Maximize button, it's underneath the task bar - hence my problem.

Thanks

**Comment by pyrates999** [comment]
For a work around: Try putting the taskbar on the bottom, rearrange the window so it is not fully at the top, and then move the taskbar on top.

**Comment by lhdigo** [comment]
1. Maybe you can use some mouse gesture softwares to Maximize 、 Minimize and  Closethe window, like Quicker that I am using.
2. Press `Alt + Space ` and then press `x` to Maximize the window (But it's useless for some windows).

**Comment by JJLocke** [comment]
Thanks everyone for your advise. Not sure what I did (if anything) but the problem seems to be resolved. (fingers crossed)

**Comment by JJLocke** [comment]
Thanks everyone for your advise. Not sure what I did (if anything) but the problem seems to be resolved. (fingers crossed)

**Comment by Totooch** [comment]
> Thanks everyone for your advise. Not sure what I did (if anything) but the problem seems to be resolved. (fingers crossed)

Hello there, did you figured out what you did to fix this? I'm having the same problem and I can't get rid of it

Thanks!
