### ISSUE TITLE
Taskbar crashes if i richt click on it

### ISSUE THREAD

**Issue by zERO123331** [valinet/ExplorerPatcher#1993]
If i rightclick on my taskbar, it just restarts and opens the window that you get if you install windows 11 but its blank and after a few seconds it disappear

i am using windows 11 pro insider preview Build 23531.1001
i know that this is the dev channel but the issue happend before i joined the Insider Programme

**Comment by SiteSplat** [comment]
Do you have the update KB5029263 installed?

**Comment by Poopooracoocoo** [comment]
Duplicate of #1952
