### ISSUE TITLE
Search menu opens up in the wrong spot?

### ISSUE THREAD

**Issue by Jaxel** [valinet/ExplorerPatcher#1997]
I use a right-side taskbar. The applications menu opens up properly on the top right by the windows button.

![image](https://github.com/valinet/ExplorerPatcher/assets/3640402/469dcca6-78e7-4119-8843-78499987b0ee)

However, the search menu does not open in the correct spot. It instead opens on the bottom left.

![image](https://github.com/valinet/ExplorerPatcher/assets/3640402/2abb1acc-eb41-4ba4-b89b-55aa252b1208)

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1378

Please close this.
