### ISSUE TITLE
Certain keyboard shortcuts broken

### ISSUE THREAD

**Issue by Someone-Distant** [valinet/ExplorerPatcher#1998]
When having the taskbar style set as Windows 10, certain keyboard shortcuts completely stop functioning, the ones I have noticed are Win+A and Win+N. These shortcuts work perfect when setting the taskbar style back to Windows 11.

---
OS Build: Windows 11 10.0.22621.2134
EP Build: 22621.1992.56.3

**Comment by pyrates999** [comment]
Might be related to this: https://github.com/valinet/ExplorerPatcher/issues/1687

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new version should fix the keyboard shortcuts on 22621.2134+ when using the Win10 taskbar.
