### ISSUE TITLE
Legacy File Transfer GUI issue

### ISSUE THREAD

**Issue by Hissymaster** [valinet/ExplorerPatcher#1999]
for some reason, the animation near the top of the window (where it says something like "Copying 532 items (132MB)") has an animation issue, more specifically, the animation **does** play out correctly but **does not** loop. this might have been an issue because of windows updates or it may also be because one attribute is not specified correctly. (tested on 22621.1702)

https://github.com/valinet/ExplorerPatcher/assets/144076671/4bab4d93-40de-4cd7-8fc9-07ee81d273f0

an example of this bug
(note: mica for everyone is used, it might be the problem)

**Comment by Poopooracoocoo** [comment]
> (note: mica for everyone is used, it might be the problem)

Please do try and isolate the issue

**Comment by Hissymaster** [comment]
the external app mica for everyone is not in fact the issue.

**Comment by Hissymaster** [comment]
it just displays the last frame of the animation indefinitely after playing the animation though once. you may have noticed that if you looked closely at the recording.

**Comment by Hissymaster** [comment]
I am not really sure why that happens though.

**Comment by pyrates999** [comment]
22621.1702 is for an update from May.  Please update to the august 8/2023 update that was released.

**Comment by Hissymaster** [comment]
alright, i will try updating it now. though it is more going to be a re-install using install media because i have been having issues.

**Comment by Vipin2003** [comment]
Not gui issue.... it seems like you are using rectify11. It is rectify11 issue... not Eap

**Comment by Hissymaster** [comment]
just checked on 22621.2134, and it's fine.
