### ISSUE TITLE
Microsoft Office (Word, Excel) Crash

### ISSUE THREAD

**Issue by Zac1209** [valinet/ExplorerPatcher#2002]
When I try to open either Word or Excel, sometimes it works flawlessly and sometimes it doesn't open at all.

I checked my crash log and it says that the module causing it is: ExplorerPatcher.IA-32.dll, version : 22621.1992.56.1.

I'm on Windows 11 22H2 22621.2134, but it's been doing it for multiples versions.

Is it a known bug? Is there a fix ?

Thanks,

**Comment by pyrates999** [comment]
When it happens do the following:

1. open up windows event viewer or computer management
2. go to Event Viewer and go to Windows Logs -> Application
3. check for a recent entry with the exe used for word or excel and paste the results here

**Comment by Zac1209** [comment]
> When it happens do the following:
> 
> 1. open up windows event viewer or computer management
> 2. go to Event Viewer and go to Windows Logs -> Application
> 3. check for a recent entry with the exe used for word or excel and paste the results here

AppName EXCEL.EXE 
  AppVersion 16.0.16731.20170 
  AppTimeStamp 64ea51f2 
  ModuleName ExplorerPatcher.IA-32.dll 
  ModuleVersion 22621.1992.56.1 
  ModuleTimeStamp 64c11e8f 
  ExceptionCode c0000005 
  FaultingOffset 000011a1 
  ProcessId 0x34f4 
  ProcessCreationTime 0x1d9e0381f2b6300 
  AppPath C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE 
  ModulePath C:\Program Files\ExplorerPatcher\ExplorerPatcher.IA-32.dll 
  IntegratorReportId 5275ff3c-f1fd-41a7-adcb-4d58d69bcd3f 
  PackageFullName  
  PackageRelativeAppId

**Comment by pyrates999** [comment]
Do you have this enabled?

https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

If so, disable it and see if it is still crashing.

**Comment by Zac1209** [comment]
> Do you have this enabled?
> 
> https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension
> 
> If so, disable it and see if it is still crashing.

It was enabled. I've disabled it and I'll report back if that fixes it.

Thanks,

**Comment by BraINstinct0** [comment]
Did it fix it?

**Comment by Amrsatrio** [comment]
I've been using EP with the shell extension checkbox ticked for years and haven't felt any crashes related to EP in Word, PowerPoint, and Excel. Closing this issue. You may reopen if it still persists.

**Comment by Zac1209** [comment]
> Did it fix it?

Yes it fixed it! Shell extension made my Office's apps crash on start.
