### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by eduardoxlive** [valinet/ExplorerPatcher#2006]
![explorer_jLfP5YuJ73](https://github.com/valinet/ExplorerPatcher/assets/144181423/f53ac278-bf64-48dc-80b2-636a887795c3)

how do i fix this?

**Comment by eduardoxlive** [comment]
Some icons were superimposed on top of the letters

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by anishsane** [comment]
This is not an ExplorerPatcher issue.
This is a behavior of the recent Windows 11 update.
You can see this behavior without Explorer Patcher installed.

**Comment by Poopooracoocoo** [comment]
Closing due to lack of author response. Comment and I'll reopen.
