### ISSUE TITLE
screen flickers when right clicking

### ISSUE THREAD

**Issue by 20MildWings** [valinet/ExplorerPatcher#2008]
I installed it and everything worked fine, I had it set to the right side of my screen. But when I restarted my computer it complexly broke. It was went back to the bottom left of my screen. My screen flickers when I'm right clicking on the taskbar. I have uninstalled it and reinstalled it.  I also ran TranslucentTB and wallpaper engine no issues before and same thing happens even if I turn wallpaper engine and TranslucentTB off it still happens. Does this append to anyone else also?

System Specs: AMD Ryzen 7 5800X3D, RTX 3070,  32gb corsair Vengeance LPX, ROG Crosshair Vll Dark Hero, WD 770 1tb (main drive), WD 750 512gb (D Drive), Vulcan 1tb (E Drive), 3 li lian uni fans

O.S. Build: 22621.2215

**Comment by Poopooracoocoo** [comment]
Thanks for the detailed report! Closing in favour of #1952
