### ISSUE TITLE
Right click on taskbar kills explorer patcher

### ISSUE THREAD

**Issue by UrielMhezzek** [valinet/ExplorerPatcher#2014]
If i clicketd on taskbar with right mousebutton, the taskbar disappears briefly and i get a errormessage, that explorer patcher is crashing. This has been happening since my last Windows update.

**Comment by iamstevedavis** [comment]
This is impacting me as well, let me know if I can provide any logs or anything that might help.

Current version of windows:
![image](https://github.com/valinet/ExplorerPatcher/assets/5615792/bcbb3b83-33ac-4a9f-9d3d-8ecbd94c6c1e)

**Comment by Poopooracoocoo** [comment]
Duplicate of #1952
