### ISSUE TITLE
All pinned Start Menu apps lost after changing Windows' accent color

### ISSUE THREAD

**Issue by redactedscribe** [valinet/ExplorerPatcher#2018]
This is the second time my highly organized pins (app icons) on the Start Menu have been completely lost. The first time was many months ago, but it just happened again, and this time I have some information on why it may have happened.

Immediately after experimenting with Windows' Settings > Personalization > Colors _accent colours_, I clicked the Start Menu button but it wouldn't open, likely because something was still refreshing or applying. After enough clicks, it did open, but now with no pins other than the default of Edge, Settings, and Explorer.

It's quite disappointing to lose all the folders I had made. Is there any way to get them back, or must I recreate it all once again? Does exporting ExplorerPatcher settings also back up the pinned apps? Currently clicking Import just crashes the ExplorerPatcher Properties window so whatever, likely old, backup I have I cannot test. Restarting explorer.exe didn't help. I really don't want this to happen again.

Thanks.

**Comment by pyrates999** [comment]
work around listed here: https://github.com/valinet/ExplorerPatcher/discussions/1679

**Comment by redactedscribe** [comment]
> work around listed here: #1679

@pyrates999 What is the workaround exactly?

I forgot to mention that I'm using the Windows 11 Start Menu style. Your links appears to be only about Windows 10 Start Menu.

**Comment by pyrates999** [comment]
> > work around listed here: #1679
> 
> @pyrates999 What is the workaround exactly?
> 
> I forgot to mention that I'm using the Windows 11 Start Menu style. Your links appears to be only about Windows 10 Start Menu.

Go to the link and it shows the work arounds available.

**Comment by pyrates999** [comment]
Please close this.

**Comment by redactedscribe** [comment]
> Go to the link and it shows the work arounds available.

I have and it isn't related to this problem as far as I can tell.

**Comment by pyrates999** [comment]
It might be related.  Do the steps still work for you if you try to add the store apps back?

**Comment by redactedscribe** [comment]
Thank you but I do not have problems with pinning or unpinning apps, and I do not use the Windows 10 style Start Menu. The problem is that all pins have been suddenly deleted and I don't want the bug to happen again.

**Comment by pyrates999** [comment]
Ok, please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by redactedscribe** [comment]
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
ExplorerPatcher:           22621.1992.56.3
```

I cannot import or export from ExplorerPatcher without the Properties pop-up window closing/crashing, and it's been many months since I've customised ExplorerPatcher so I'm not sure what is default and what is not.

Taskbar style is Windows 10, Start Menu style is Windows 11, at least.

**Comment by pyrates999** [comment]
Your OS build is not valid.  Please run winver to get the actual value.

**Comment by redactedscribe** [comment]
`22621.2134`

**Comment by pyrates999** [comment]
Is it all manually pinned start menu apps are lost after you change windows accent colours?  Are they all apps from the microsoft app store?

**Comment by redactedscribe** [comment]
All manually pinned and organised. Most in folders, some not. Most apps were installed via EXE/MSI files and via Scoop. I use a mix of installation methods and all pins were unpinned, not only some.

My suspicion is that the problem lies with triggering the Start Menu during the period it was refreshing/updating after a change, but I could be wrong. What is clear is that the result of the bug is an overwriting of the file which stores the Start Menu's state (i.e. its pins etc) with a fresh / blank copy. Therefore, there is no way to get my pins back, and it's not certain that ExplorerPatcher is to blame for it.

Interestingly, I found a year old copy of this file which stores the Start Menu's state, only because for some reason it had switched from being named `start.bin` to `start2.bin` at some point. Unfortunately, this `start.bin` isn't much use since it's so outdated, but I can start to create backups of its folder to never lose my pins again.

## Backing up pins from the Start Menu

The [Start Menu stores its pinned apps in a BIN file](https://www.elevenforum.com/t/backup-and-restore-pinned-items-on-start-menu-in-windows-11.3629/): `%LocalAppData%\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start.bin` (may instead be `start2.bin` or some higher number).

This folder can be backed up regularly if you wish to ensure that you do not lose your pins. If you then restore a `start.bin` backup, [restart the `StartMenuExperienceHost.exe` process](https://www.elevenforum.com/t/restart-start-menu-process-in-windows-11.1102/) to see its effect.

**Comment by pyrates999** [comment]
Very useful information!

**Comment by Amrsatrio** [comment]
Seems like this is a very specific to your installation. Anyways, I have attempted to make fixes that crash the start menu after updates, your issue can also be related closely to it. I don't experience this on my 5 year old installation that is currently on 22621.2428. I spammed the accent color buttons in the settings app and my start menu items, both Win10 and Win11, are still intact.

**Comment by redactedscribe** [comment]
> Seems like this issue is very specific to your installation. Anyways, I have attempted to make fixes to the start menu crashing after updates, your issue can also be related closely to it

Thank you for your attempts to fix things. 

> Therefore, there is no way to get my pins back, and it's not certain that ExplorerPatcher is to blame for it (I tried changing accent colour many times and spamming the Start Menu button but I couldn't reproduce the bug).

As I stated, I couldn't reproduce the bug. At first I believed it was to do with the accent colour since that's what appeared to trigger the crash, then I thought maybe it was "that the problem lies with triggering the Start Menu during the period it was refreshing/updating after a change". Whatever the issue, I'm glad I can back up my start menu.
