### ISSUE TITLE
Crash since last windows 11 update

### ISSUE THREAD

**Issue by HerveRV** [valinet/ExplorerPatcher#2020]
![image](https://github.com/valinet/ExplorerPatcher/assets/2123442/2481365f-77b2-4a12-9836-d4295731a9fc)

impossible to use windows, i must uninstall ExplorerPatcher to work .... :'-(

**Comment by Poopooracoocoo** [comment]
Define "last Windows Update". What's your OS Build and EP version?

**Comment by HerveRV** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/2123442/f3787e5b-d86c-4d41-ab7d-a96214b68d54)

**Comment by HerveRV** [comment]
i loose the ability to use the taskbar, using Slack made a continu cycle of {"refresh desktop" "draw empty taskbar" "clear zone taskbar zone" "refresh Slack"}
in the process, computer can be unusable, because of continus crash of explorer
a friend experience the same thing, i uninstall ExplorerPatcher too... we regret that !

**Comment by Poopooracoocoo** [comment]
https://support.microsoft.com/en-au/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692 Preview updates aren't supported. But frustratingly Microsoft doesn't let you uninstall most cumulative updates...

**Comment by HerveRV** [comment]
Ok...
I hope the fix wouldn't be to hard to find

Thanks !

**Comment by c8c8** [comment]
Within the next month, Microsoft will release the next Win11 update which will include tab ungrouping, labels, and taskbar drag-and-drop.  That, combined with using Portable Start Menu to replace the quick launch toolbar, will make ExplorerPatcher unnecessary for the most part which is good because its only function lately has been to break things.

**Comment by flyoffacliff** [comment]
Within the next month? What's your source on that?
Based on my research and testing it's only on the 23000 series builds, which are only on the dev channel, and haven't even hit beta yet. I think we're still several months out.

**Comment by Jackystu** [comment]
> ![image](https://user-images.githubusercontent.com/2123442/266340026-2481365f-77b2-4a12-9836-d4295731a9fc.png)
> 
> impossible to use windows, i must uninstall ExplorerPatcher to work .... :'-(

Hi, I met the same problem. Now, i can't open the explorer.exe since the ep_setup.exe is running。

I can only open the  windows task manager right now, how can i kill the  ep_setup.exe at windows task manager?

**Comment by pyrates999** [comment]
> > ![image](https://user-images.githubusercontent.com/2123442/266340026-2481365f-77b2-4a12-9836-d4295731a9fc.png)
> > impossible to use windows, i must uninstall ExplorerPatcher to work .... :'-(
> 
> Hi, I met the same problem. Now, i can't open the explorer.exe since the ep_setup.exe is running。
> 
> I can only open the windows task manager right now, how can i kill the ep_setup.exe at windows task manager?

The details tab has all the running processes.  Here's more details on how to uninstall: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

**Comment by Sawtaytoes** [comment]
My version is `22621.2215` like others:
![image](https://github.com/valinet/ExplorerPatcher/assets/3948069/63cee2de-14df-4532-8445-b2049f271ba6)

1. The difference in my build is that Explorer works fine, but the start menu won't come up.
1. Clicking the Start Menu icon doesn't open the Start Menu either.
1. `[WIN][SHIFT][S]` doesn't work to open the Snipping Tool, but it works if I open it manually.
1. `[WIN][TAB]` doesn't work.

I have the latest August 28th, 2023 game-ready version of the NVIDIA drivers if that helps.

Someone posted that ExplorerPatcher wouldn't be needed in some upcoming update, but I use it for a different reason. I want the Windows 95 to 10 style of named and separate start menu items as well as having them be centered (a nice usability feature for these super ultrawide monitors). It's a productivity feature that Microsoft devs removed to make Windows feel more like MacOS.

**Comment by pyrates999** [comment]
> My version is `22621.2215` like others: ![image](https://user-images.githubusercontent.com/3948069/266815081-63cee2de-14df-4532-8445-b2049f271ba6.png)
> 
> 1. The difference in my build is that Explorer works fine, but the start menu won't come up.
> 2. Clicking the Start Menu icon doesn't open the Start Menu either.
> 3. `[WIN][SHIFT][S]` doesn't work to open the Snipping Tool, but it works if I open it manually.
> 4. `[WIN][TAB]` doesn't work.
> 
> I have the latest August 28th, 2023 game-ready version of the NVIDIA drivers if that helps.
> 
> Someone posted that ExplorerPatcher wouldn't be needed in some upcoming update, but I use it for a different reason. I want the Windows 95 to 10 style of named and separate start menu items as well as having them be centered (a nice usability feature for these super ultrawide monitors). It's a productivity feature that Microsoft devs removed to make Windows feel more like MacOS.

Please file what you mentioned as a new issue.

**Comment by Sawtaytoes** [comment]
> Please file what you mentioned as a new issue.

https://github.com/valinet/ExplorerPatcher/issues/2044

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new version should never do irrecoverable crashes like these anymore. There should be no more major issues on 22621 builds up to 22621.2359.
