### ISSUE TITLE
Explorer Crashing When Right Clicking Windows 11 Taskbar

### ISSUE THREAD

**Issue by newtekie1** [valinet/ExplorerPatcher#2025]
In Windows 11 22H2 Build 22621.2134 with the latest non-preview updates installed, if the Taskbar Style in EP is set to Windows 11, right clicking on the Taskbar caused Explorer to crash.

The two options to stop this are to switch to the Windows 10 Taskbar style, or to enable the option "Do not change the taskbar context menu" under advanced options in EP Properties.

**Comment by Poopooracoocoo** [comment]
#1805
