### ISSUE TITLE
StartMenuExperienceHost.exe crashing even after EP is uninstalled

### ISSUE THREAD

**Issue by iAmWednesday** [valinet/ExplorerPatcher#2048]
I have Windows 11 Pro 22H2, OS Build 23486.1000, Insider Preview Build 23486.ni_prerelease.230616-1447. 
I uninstalled EP when I realized Insider is not supported, but StartMenuExperienceHost.exe still crashes every time Start button is pressed.

**Errors:**

Faulting application name: StartMenuExperienceHost.exe, version: 10.0.23486.1000, time stamp: 0x53f78c2e
Faulting module name: ucrtbase.dll, version: 10.0.23486.1000, time stamp: 0xc66a23fe
Exception code: 0xc0000409
Fault offset: 0x000000000007f61e
Faulting process id: 0x0x1B70
Faulting application start time: 0x0x1D9E58D0D0FB8EF
Faulting application path: C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: f726aa2c-3035-4048-abf2-42b005f6ea7e
Faulting package full name: Microsoft.Windows.StartMenuExperienceHost_10.0.23486.1000_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: App

Fault bucket 1933013480384608102, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0
Problem signature:
P1: Microsoft.Windows.StartMenuExperienceHost_10.0.23486.1000_neutral_neutral_cw5n1h2txyewy
P2: praid:App
P3: 10.0.23486.1000
P4: 53f78c2e
P5: ucrtbase.dll
P6: 10.0.23486.1000
P7: c66a23fe
P8: 000000000007f61e
P9: c0000409
P10: 0000000000000007
Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4de6e3d9-7cb6-4582-9b9b-1dc380256e50.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c4654d96-2242-4ca0-9f50-85b14293c658.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bb36f73c-a259-40ec-98d7-6a399aa01091.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a55d9423-c4d5-4d9e-ba26-6ffe58d34332.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4746faac-1307-4bc6-a3c3-1c921a2799b5.tmp.xml
These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_f2e9e8fb2f56ab2ce7ece7a16ee2fa6734de2a0_bb24385b_c3969b8e-a5da-4493-8d9f-1d287783b783
Analysis symbol: 
Rechecking for solution: 0
Report Id: f726aa2c-3035-4048-abf2-42b005f6ea7e
Report Status: 268435456
Hashed bucket: 1ffbecfd650d7c138ad37184d45db766
Cab Guid: 0

**Comment by pyrates999** [comment]
Insider builds and preview updates are not supported by EP.

**Comment by iAmWednesday** [comment]
I realized that, so I uninstalled it, as stated above. But I am still getting the crashes. How do I get it back to the original?

**Comment by pyrates999** [comment]
Reinstall windows with a release version, not an insider build.  And don't install preview updates.

**Comment by Amrsatrio** [comment]
Are there leftover files in C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy? AFAIK EP drops these in that folder.
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/205d1c6b-77b8-49e4-96d7-287ca7364ac1)

**Comment by Amrsatrio** [comment]
I will close this issue since there seem to be no new responses.
