### ISSUE TITLE
VolumeOSD missing

### ISSUE THREAD

**Issue by GittaHuber** [valinet/ExplorerPatcher#2049]
I really appreciate Explorerpatcher, I don't want to do without it any more. Especially since I've always had the taskbar at the top, not at the bottom. But ... I also absolutely need a volume OSD on a PC. Preferably the old, vertical one, but if need be the horizontal one. With the explorer patcher, this disappeared as soon as I switched from Taskbar Win11 to Taskbar Win10. 
Is there a way to have both the Windows 10 style taskbar (i.e. on top) and at the same time not do without the volume OSD? I would be extremely grateful for this. .

**Comment by Poopooracoocoo** [comment]
#1692
