### ISSUE TITLE
Explorer completely restarts after launching new explorer window

### ISSUE THREAD

**Issue by NifTTY** [valinet/ExplorerPatcher#2055]
**Summary:** 
Explorer completely restarts at next window launch after all windows are closed.

**Steps to replicate:**
1. Log into user profile
2. Launch explorer file browser window(s) by any means (taskbar pin, recycle bin, etc)
3. Close (all) open explorer file browser window(s)
4. Launch explorer file browser window by any means (taskbar pin, recycle bin, etc)

**Result:**
Explorer will completely reload including taskbar, wiping out all file explorer windows. 

**_EXAMPLE A+B:_**
Tested on fresh/updated UEFI installations of...
Windows 11 Home 22H2 (22621.2134) [Example A]
Windows 11 Pro 22H2 (22621.2134) [Example B]

Using most recently with EP release 22621.1992.56.3 with default settings
( downloaded from https://github.com/valinet/ExplorerPatcher/releases/download/22621.1992.56.3_5bda71f/ep_setup.exe )

Observed in first-time EP installations from releases as early as 22621.1992.56.1 

**_EXAMPLE C:_**
Notably, this issue has NOT manifested on legacy-installed (MBR) Win11 22H2 (22621.2134) on one specific PC [Example C]. 
This system was originally running 22H1 from a fresh install and was upgraded to 22H2.
Example C has been running EP since 22621.1555.55.2.
Example C was recently running EP 22621.1992.56.1 with the symptom absent.
Example C was just updated to EP 22621.1992.56.3. Still no presence of the symptom.

**Also tested:**
Tried exporting known-good EP settings from Example C and introducing to Example A/B. No change.

**Not tested:** 
Have not attempted to fully remove EP from Example C and reinstall
Have not tested with a fresh user profile on Example C
Have not tested with fresh install of 22H2 + EP 22621.1555.55.2

**OBSERVATIONS:** 
Occasionally (very rarely) the crash/restart will simply stop happening until explorer.exe is restarted manually.

**Comment by alexandrefonceca** [comment]
The same thing happens here, and with each restart, it messes up the order of the open apps on the taskbar. I've tried reinstalling, and the same thing happens; it started happening after yesterday's Windows updates.

**Comment by NifTTY** [comment]
This does not seem to be related to Windows 11 update kb5030219 (suggested in https://github.com/valinet/ExplorerPatcher/issues/2051 ). This may be an entirely different problem.

**Comment by NifTTY** [comment]
Ran into some interesting behavior while testing.


First, observe the typical action in the console from a fresh start.
This is after manually restarting explorer.exe and opening/closing one file browser window:
```[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.1992.56.3.f8433b9d1f5e09e6"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.1992.56.3.f8433b9d1f5e09e6" (valid).
[Updates] Local version obtained from hash is 22622.1992.56.3.
[Updates] No updates are available.
10000 46000000
0 46000000
Error in sub_1800135EC on RoGetActivationFactory.
```
Usually, closing the window and attempting to launch another after this point would cause the unexpected restart/crash.
(see notes at end of this comment regarding RoGetActivationFactory)
```
10000 46000000
0 46000000
Error in sub_1800135EC on RoGetActivationFactory.
10000 46000000
0 46000000
```
(console window closes, new one appears with typical startup)


The weird thing happened when the bug was suddenly absent and there were multiple successful window launches. Note that no changes had been made, and this was in the middle of triggering the bug deliberately over multiple iterations:
```
Error in sub_1800135EC on RoGetActivationFactory.
10000 46000000
0 46000000
10000 46000000
0 46000000
10000 46000000
0 46000000
```
Normal window behavior continued until a manual restart of explorer.exe. The "Restart File Explorer" shortcut started explorer with a new PID as usual, but explorer shell did not appear with desktop/taskbar/etc. 
During this same login session, killing and restarting explorer.exe by other means (taskmgr) also failed to restore the visible desktop/explorer shell. No meaningful differences in the console log during these 'vacant' restarts.
Signing out and back into the user profile restored the explorer shell with desktop/taskbar/etc. 
Further testing resulted in the usual crash/restart with triggers as previously described.



Observable crash: 


Note: The RoGetActivationFactory error may be a mundane behavior of the C++ resource (roapi.h):
https://learn.microsoft.com/en-us/windows/win32/api/roapi/nf-roapi-rogetactivationfactory

**Comment by NifTTY** [comment]
Not sure if CrashCounter is an activate part of EP's behavior, but it has consistently been 0 through this whole ordeal.


![image](https://github.com/valinet/ExplorerPatcher/assets/144926478/a03dec1f-efe4-4b14-a773-362e1006d255)

**Comment by NifTTY** [comment]
My bad. This appears to be a duplicate of #1942
