### ISSUE TITLE
EP keep crashing

### ISSUE THREAD

**Issue by Joune1** [valinet/ExplorerPatcher#2058]
EP keeps crashing when I right-click on the taskbar.
I've followed all the advice but nothing changes

I can access properties but I can't update and I can't uninstall.

However, all the changes made to Windows remain functional. 

Windows 11 Professionnel
22H2
22621.2283
Windows Feature Experience Pack 1000.22662.1000.0

**Comment by dhtpdud** [comment]
same here

**Comment by lokpro** [comment]
Edition	Windows 11 Pro
Version	22H2
Installed on	‎7/‎11/‎2022
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

Faulting application name: explorer.exe, version: 10.0.22621.2283, time stamp: 0x411f7365
Faulting module name: twinui.pcshell.dll, version: 10.0.22621.2215, time stamp: 0xd43f0915
Exception code: 0xc0000005
Fault offset: 0x0000000000036ade
Faulting process id: 0x0x2088
Faulting application start time: 0x0x1D9E6B04B859216
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\twinui.pcshell.dll
Report Id: fcceae69-9a67-4717-957b-4a2a16f36700
Faulting package full name: 
Faulting package-relative application ID:

**Comment by lokpro** [comment]
updated to latest ExplorerPatcher  22621.1992.56.3  and cleared the registry settings Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher, no crashes again.
Sorry not sure which action did fix the problem.

**Comment by dhtpdud** [comment]
I changed the Taskbar style to Windows 11, and this crash happened

**Comment by FullCross** [comment]
> updated to latest ExplorerPatcher 22621.1992.56.3 and cleared the registry settings Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher, no crashes again. Sorry not sure which action did fix the problem.

Yes this really help Thanks.

**Comment by Poopooracoocoo** [comment]
Consolidating all issues with Explorer restarting and symbols not being downloaded with KB5030219 Windows 11 OS Build 22621.2283 in #2051

**Comment by ThiagoScala** [comment]
> > updated to latest ExplorerPatcher 22621.1992.56.3 and cleared the registry settings Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher, no crashes again. Sorry not sure which action did fix the problem.
> 
> Yes this really help Thanks.

Sorry, just for clarification, what files i need to delete on the registry? all of them?

**Comment by tallman69** [comment]
> Sorry, just for clarification, what files i need to delete on the registry? all of them?

Delete the entire `ExplorerPatcher` registry folder at the end of this path:  `HKEY_CURRENT_USER\Software\ExplorerPatcher`
