### ISSUE TITLE
in taskbar click wifi icon can't popup wifi list

### ISSUE THREAD

**Issue by mikePengW** [valinet/ExplorerPatcher#2070]
in taskbar click wifi icon can't popup wifi list

![image](https://github.com/valinet/ExplorerPatcher/assets/13198764/338802bd-ebd9-4f40-bf25-fc4d3970fbaf)

windows 11 start system is can use this function, but use once after this function is not work.

this bug can it be fixed?

**Comment by Poopooracoocoo** [comment]
Please state your OS Build and EP version

**Comment by pyrates999** [comment]
Might be related to: https://github.com/valinet/ExplorerPatcher/issues/1692

Work around until this gets fixed: install an application from the microsoft store called "modernflyouts".

**Comment by Poopooracoocoo** [comment]
Closing due to lack of author response.
