### ISSUE TITLE
Black screen hang on build 22621.2359

### ISSUE THREAD

**Issue by ggets** [valinet/ExplorerPatcher#2075]
Not sure if it's the same as previous issues, so opening up a new one. The issue seems to be related to the following registry key:
`Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell`
and in particular:
`CLauncherTipContextMenu::ShowLauncherTipContextMenu`

Deleting it from the registry fixes the problem.

**Comment by ecsjjgg** [comment]
Yes I had this problem too...

Thx for the fix!

**Comment by pyrates999** [comment]
Insider builds are not supported by EP: https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/

**Comment by mattcoz** [comment]
> Deleting it from the registry fixes the problem.
Thank you!

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new version should never do irrecoverable crashes like these anymore. There should be no more major issues on 22621 builds up to 22621.2359.
