### ISSUE TITLE
Issue with Task view and new update KB5030219

### ISSUE THREAD

**Issue by rgdudley** [valinet/ExplorerPatcher#2078]
It seems that the Task View does not work anymore with this newest build and certain settings?  I'm attaching the reg (as a txt file) I exported out and the desktop switcher does not seem to work unless the "**Taskbar Style: Windows 11"**.
[ExplorerPatcher_22621.1992.56.3.txt](https://github.com/valinet/ExplorerPatcher/files/12622243/ExplorerPatcher_22621.1992.56.3.txt)

Thanks

**Comment by FlameOfArda** [comment]
Same. And i tried uninstalling updates, but the one I had was mandatory

**Comment by young-zhang** [comment]
It's been broken since KB5029263 (Aug 2023 update).

**Comment by Trackerlist** [comment]
Same here, Explorer keeps restarting in loop

**Comment by evandrosouza89** [comment]
same here

**Comment by Poopooracoocoo** [comment]
> It's been broken since KB5029263 (Aug 2023 update).

Yes. Closing in favour of #1687
