### ISSUE TITLE
Windows 10 Start Menu Does not Open on Windows 11

### ISSUE THREAD

**Issue by TheMonkeyMahn** [valinet/ExplorerPatcher#2079]
It just loads... something and doesn't open any start menu.

https://iwouldsmash.brycens.mom/Vd4iv.gif

**Comment by Skyler-Guha** [comment]
Same. It does not work and then crashes after a bit. It happened after the latest update.

**Comment by pyrates999** [comment]
Check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

You can check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  If it shows it can't download symbols, your version of windows is not supported.

**Comment by pyrates999** [comment]
Something is blocking the symbols from being able to download.

Disable any third party firewall software temporarily and then reinstall EP.

**Comment by caccamo88** [comment]
tried, not working :(

**Comment by pyrates999** [comment]
> Just tried, not working :(

After you've disabled any third party firewall, and reinstalled EP, you must open the console in explorer patcher. Open up the properties application for explorer patcher, go to advanced, and click on enable console. If it shows it can't download symbols, your version of windows is not supported.

Did you download EP from here on github?

**Comment by caccamo88** [comment]
thanks, did exactly that, and yes downloaded from github. Also weird is affecting few users. Pretty sure happening since let say one week when as said Windows 11 performed latest updates automatically 

Any way to force (manually) download/install these "symbols"?

**Comment by pyrates999** [comment]
Not sure.  Since they require certain files to be downloaded to specific locations in the file system, and with every new update for windows requiring the version for that new update, probably not.

Please list what third party firewall and antivirus software you are running.

Do you also have any other software installed that modifies windows?  Such as open shell, 7+ taskbar tweaker, and windhawk?

**Comment by caccamo88** [comment]
Have ESET since 10 years, now "ESET Internet Security" for both antivirus and firewall.

I am not behind proxy server or hardware firewall (but maybe my internet provider could used) and about other software installed....I believe none except StartAllBack that yes could interfere with EP but really can't get rid of it (completely uninstalled but still present and completely working starting from C:\Program Files\StartAllBack, should brutally delete the folder? Always preferred to leave it)

**Comment by pyrates999** [comment]
Try disabling the ssl/tls filtering feature: https://support.eset.com/en/kb5833-manage-protocolssltls-filtering-in-eset-windows-home-products

Then install EP.

**Comment by caccamo88** [comment]
no way and ESET is not the guilty: even with that completely uninstalled EP is still unable to download "symbols"

**Comment by pyrates999** [comment]
Then something else is blocking symbols from being able to be downloaded.

What CPU are you running?  I want to check if it's x64 or arm since there are some windows laptops that run on arm.

**Comment by caccamo88** [comment]
AMD Ryzen 7 5800X.
Yes we need to find what have in common: @TheMonkeyMahn @Skyler-Guha what about your hardware config? Windows 11 version, language? Thanks

**Comment by TheMonkeyMahn** [comment]
@caccamo88 I think it's just luck or a problem with another program. Before this, I had installed OpenShell, which caused a few issues, such as the taskbar resetting on right click (win 11 style only) and there was also a custom start menu option, presumably the cause of the issue. I also use English with Windows 11 version 22H2 and OS build 22621.525 with an RTX 3060 laptop edition and an Intel 17-12600k. I have recently factory reset my laptop for space and to get rid of viruses.

**Comment by pyrates999** [comment]
Check that you haven't disabled symbols from being downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by caccamo88** [comment]
You mean the flag "Enable symbols download" under Advanced settings? Yes it is turned on. 
Tempted to revert some latest windows update to see if it really the guilty but never mind I use start button only to shut down the computer :) and have found another way to disconnect/shut down

**Comment by pyrates999** [comment]
EP requiring symbols for your version of windows is a technical requirement.  It needs to be able to download them.

**Comment by Amrsatrio** [comment]
Please install the newly released EP build. The new version should try to make the Win10 start menu show and alt tab work before the symbols have finished downloading.

**Comment by caccamo88** [comment]
new release not solve the issue....nevermind we are only few users, thanks the same

**Comment by caccamo88** [comment]
> ....The new version should try to make the **Win10 start menu** show and...

Sorry didn't realise this part and **can confirm it works thanks**! Never noticed start menu was Win11 by default, always been interested only in Windows 10 **taskbar style** (needed double row taskbar and to add custom toolbar from a folder)

also for reference: even with the very latest version 2261.2361.58.1 (clean installation, firewall off) symbols are unable to download (no W11 start menu style but nevermind!)

**Comment by Amrsatrio** [comment]
In 22621 builds, everything but the "max number of bla bla bla to show" should work when symbols are not or not yet available. If the start menu doesn't show, that means there's a specific issue to your installation.

**Comment by caccamo88** [comment]
update: also "start menu style windows 11"  back to work (but downloading symbols still error lol) . What have done? No idea, or Windows update again itself or this operation needed to perform for another issue worked:

Reset Internet Settings to Default.

1. Navigate to Control Panel and open the Internet Options. (or open Internet Explorer and go to Tools -> Options)

2. Navigate to Security tab and Reset all zones to default level and hit OK to apply the change.


![immagine](https://github.com/valinet/ExplorerPatcher/assets/12472438/1d406e97-1100-4d32-8a3c-69ee58045119)
