### ISSUE TITLE
"Win +A" shortcut does not show Control Center on Windows 11 when using Windows 10 taskbar

### ISSUE THREAD

**Issue by JuaneAranav** [valinet/ExplorerPatcher#2082]
Hello!
I've been using the program for months and I realized that the "Win + A" shortcut was no longer working. I thought it was Windows 11's fault, but once I uninstalled the program, it worked again.
Reviewing the settings, I have enabled the Wi-Fi button to show the control center and disabled the gear wheel, but many times, I prefer to use keyboard shortcuts, and this one is not working.
How can I enable it? Or if it isn't enabled, how much can I donate so you can develop the feature as soon as possible?
Thanks!

**Comment by Poopooracoocoo** [comment]
Also see #1998

**Comment by JuaneAranav** [comment]
> Also see #1998

Thanks bro!
But i would like to use the windows 11 style and have the shortcuts working. :(
