### ISSUE TITLE
Multitasking (Desktop Overview) ist not working

### ISSUE THREAD

**Issue by t-baer** [valinet/ExplorerPatcher#2088]
For a few months now, the "active programs" and the multi-desktop view no longer work.
It is a bug of the explorer patcher, because when I quit EP it works fine. When I start EP, it doesn't work anymore.
Is there a solution for me?

**Comment by RichardHeslopZA** [comment]
Also experiencing this. Winkey + Tab shortcut doesn't work with EP installed. 😢

**Comment by saskosam** [comment]
Also experiencing this issue.
