### ISSUE TITLE
 Can you add a small taskbar without blocking the date?

### ISSUE THREAD

**Issue by hui99995** [valinet/ExplorerPatcher#21]
Can you add a small taskbar without blocking the date? Now change the value of taskbarsi, and the date will be blocked

**Comment by valinet** [comment]
Feature requests should be filled here: https://github.com/valinet/ExplorerPatcher/issues/13

It’s easy to spot, it is pinned at the top of the issues panel.

Afaik, TaskbarSi affects the new taskbar. This software deals with the classic taskbar. If I misunderstood what you want, please explain again, more clearly.

Thanks.
