### ISSUE TITLE
Taskbar context menu items disabled

### ISSUE THREAD

**Issue by sstoenner** [valinet/ExplorerPatcher#2100]
Version 22621.1992.56.3
Taskbar context menu items "Lock the taskbar" and "Taskbar Settings" are disabled...
What could be wrong?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.

Please include what settings you changed in explorer patcher properties application.

**Comment by sstoenner** [comment]
Windows version 22H2, build 22621.2283
The only setting I  have applied is Taskbar style: Windows 10... I cannot
find any other setting that might apply to this issue... Any help is
appreciated.

**Comment by pyrates999** [comment]
Try the following:

1. In ExplorerPatcher Properties, go to Advanced and untick **Do not change the taskbar context menu** - there should be an X beside it
2. In ExplorerPatcher Properties, go to File Explorer and untick **Disable the windows 11 context menu**
3. In ExplorerPatcher Properties, go to Taskbar and set **Taskbar style** to **Windows 11**

**Comment by sstoenner** [comment]
Why would I do that?
I don't want the Windows 11 taskbar style...
Locking/unlocking the taskbar worked in Windows 10.

**Comment by pyrates999** [comment]
We need to find out what setting was causing this.  So please try them.

**Comment by sstoenner** [comment]
OK, I did try that and it made no difference.

**Comment by pyrates999** [comment]
Check here: https://www.tenforums.com/tutorials/105189-enable-disable-taskbar-settings-windows-10-a.html

**Comment by sstoenner** [comment]
Thank you so much ... That did the trick!

**Comment by Poopooracoocoo** [comment]
Closing as this was seemingly resolved and doesn't look like it has to do with EP
