### ISSUE TITLE
Alt + Tab key (window switcher) doesn't work after Win + Tab pressed.

### ISSUE THREAD

**Issue by developer6253** [valinet/ExplorerPatcher#2112]
Alt+tab (Window Switcher) Doesn't work after when i pressed Win+Tab key. until restart explorer.exe. 
when i pressed Win+Tab Key, there is no action for me and then Alt+Tab key no more working.
how to fix it?
------------------------------------------
Windows11 (22H2, build 22621.2283)
Explorer Patcher (22621.1992.56.3)

**Comment by Poopooracoocoo** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1687
