### ISSUE TITLE
Taskbar is not on top of other windows (when not maximized)

### ISSUE THREAD

**Issue by rustydanny** [valinet/ExplorerPatcher#2115]
My taskbar does not stay on top of applications when they're NOT maximized.
Doesn't matter what application it is: Excel, Chrome, Notepad, Windows Explorer

When the window's maximized, everything's as it should be, with the bottom of the window touching the top of the taskbar.

**Comment by Poopooracoocoo** [comment]
Please state your OS build and EP version

**Comment by rustydanny** [comment]
This PC > Properties > Windows 11 Pro, OS Build: 22621.2283

Explorer Patcher says "Running on Windows 11, OS Build 10.0.22621.2283."
Explorer Patcher Version: 22621.1992.56.3

**Comment by rustydanny** [comment]
Thanks. I updated it, restarted the pc, and it still does that.

About: Version 22621.2283.57.2

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application.

Please take a screen shot for what you mean.

**Comment by Amrsatrio** [comment]
They're on top? You seem to be using TranslucentTB. I mean it works fine on 22621.1992 with TranslucentTB and stock 23545.1000 without TTB.
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/dd155996-ee01-4d76-bd69-34604975cdff)
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/a1427eb9-26d2-4146-86cd-4f22d30a231c)

**Comment by rustydanny** [comment]
I don't have transparency effects turned on:

![1](https://github.com/valinet/ExplorerPatcher/assets/145377653/07ccef70-d557-4c16-a2f2-793f4a503d24)

![2](https://github.com/valinet/ExplorerPatcher/assets/145377653/6a8ba0f0-e62a-49a0-8088-243d1a697af0)

**Comment by Poopooracoocoo** [comment]
Seems to be the same issue as #1759

**Comment by rustydanny** [comment]
Turns out I had Explorer Patcher and Open Shell running at the same time. Uninstalled Open Shell, and now it's working. Thank you very much.

**Comment by rustydanny** [comment]
Turns out I had Explorer Patcher and Open Shell running at the same time. Uninstalled Open Shell, and now it's working. Thank you very much

**Comment by Poopooracoocoo** [comment]
You shouldn't be seeing this with Open Shell though. Hm

**Comment by pyrates999** [comment]
What taskbar settings were you using?  Did you have the taskbar set to autohide?
