### ISSUE TITLE
Win logo key + Tab doesn't work and using it disables ALT + Tab as well, only fixable via explorer restart

### ISSUE THREAD

**Issue by Elsayed91** [valinet/ExplorerPatcher#2120]
As title says, any attempt to use win logo key + tab doesn't work and disables further usage of alt + tab as well until I go to the patcher and use Restart File Explorer(*) .
The behavior neither impacts the functionality of the individual keys themselves. I can still use tab, windows key still opens the start menu, but the combinations do not work. 

Upon removing the patcher the functionality returns.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1687. Please close this issue.
