### ISSUE TITLE
Latest version 22621.2283.57.1 does not work on build 22000

### ISSUE THREAD

**Issue by Anixx** [valinet/ExplorerPatcher#2125]
I have updated EP to the latest version, but the taskbar crashes and eventually starts in Windows11 mode rather than Windows 10 mode.
OS build is 22000.2176

**Comment by Anixx** [comment]
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/10bddc4f-2202-4d9a-9eb7-b4e1efd2c4c2)

**Comment by JamesFrankel** [comment]
Yup, same problem here. OS build 10.0.22000.2416

**Comment by Amrsatrio** [comment]
Can confirm. 22000.2416. Please hold on.

**Comment by Amrsatrio** [comment]
Please install 22621.2283.57.2 aka update to the latest EP. I am truly sorry for the inconvenience.
