### ISSUE TITLE
Black Screen ExplorerPatcher 22621.2283.57.1

### ISSUE THREAD

**Issue by TK50P** [valinet/ExplorerPatcher#2131]
I installed Latest Version of ExplorerPatcher, it does not show Taskbar and File explorer
I Restarted system and started explorer.exe manually, but same problem

Version is Windows 10 21H2 (Enterprise LTSC 2021)

**Comment by Poopooracoocoo** [comment]
>Version is Windows 10 21H2 (Enterprise LTSC 2021)

Please state the exact OS build

**Comment by TK50P** [comment]
OS Build is 10.0.19044.3324

**Comment by Amrsatrio** [comment]
Please install 22621.2283.57.2 aka update to the latest EP. I am truly sorry for the inconvenience.
