### ISSUE TITLE
Keep windows 11 Icon in Windows Start why using "Taskbar > Taskbar Style * : Windows 10" > Start button style * : Windows 11

### ISSUE THREAD

**Issue by pareshsojitra** [valinet/ExplorerPatcher#2138]
Hi,

Keep windows 11 Icon in Windows Start while using "Taskbar > Taskbar Style * : Windows 10" > Start button style * : Windows 11

I have used "Start button style * : Windows 11" but still shows windows 10 Icon in Start.

Thank you.

**Comment by Poopooracoocoo** [comment]
Cannot repro. Use discussions for support. Make sure to include your version of ExplorerPatcher and your OS build.
