### ISSUE TITLE
[Taskbar10] Action center, control center and search are misplaced when collapsing taskbar is enabled.

### ISSUE THREAD

**Issue by NotSpaulding** [valinet/ExplorerPatcher#2153]
# Using the Windows 10 taskbar
![Misplaced action center](https://github.com/valinet/ExplorerPatcher/assets/97350911/e40f0719-eb10-47b2-9087-cb5fbb200423)
As you can see, at the start of the recording the taskbar is set to auto-hide which makes the placement of the action center is incorrect, overlapping the taskbar entirely; after that I double click the taskbar to make it stop auto-hiding which fixes the problem.

# Using The Windows 11 taskbar
![Correctly-placed action center](https://github.com/valinet/ExplorerPatcher/assets/97350911/d953e881-93c9-4924-ba4d-ceb2d6f9663f)
In this recording everything works as intended, the action center is placed above the taskbar at all times.

The same issue is present on the control center and the search (ie. when pressing `WIN + S`).

**Comment by Poopooracoocoo** [comment]
It's consistent with how it works on Windows 10 at least

**Comment by pyrates999** [comment]
Looks like Microsoft had saw this bug in windows 10, but hadn't fixed it until windows 11.  This should be closed.

**Comment by NotSpaulding** [comment]
> The reason being is that you wait until the build number text has moved up. The action center is aligning itself to where that text is when the taskbar is set to the windows 10 taskbar.

I don't think that is the case. You can see in the second recording I've provided the build info is still on the bottom when the taskbar is set to auto-hide and the action center is still positioned correctly.

> Have you tried not showing the build number text on the desktop?

Disabling the build info has no effect.

> I would say this would be a bug in windows itself, not EP.

I agree. But the sole purpose of this software is to *patch* Windows's *explorer*. The reason this problem occurs is because Microsoft had no reason to account for something like this, considering the Windows 10 taskbar is not something you have access to normally on Windows 11.

**Comment by pyrates999** [comment]
> > I would say this would be a bug in windows itself, not EP.
> 
> I agree. But the sole purpose of this software is to _patch_ Windows's _explorer_. The reason this problem occurs is because Microsoft had no reason to account for something like this, considering the Windows 10 taskbar is not something you have access to normally on Windows 11.

So whether this can be fixed by EP or not, I will let the developers decide on that.

**Comment by NotSpaulding** [comment]
Of course if it's too hard to implement it's not really worth it considering how small of an issue this is.

In case this helps; I found this other "mod" that reduces the size of the Windows 11 taskbar and has the action center have the correct placement. https://github.com/ramensoftware/windhawk-mods/blob/main/mods/taskbar-icon-size.wh.cpp

**Comment by NotSpaulding** [comment]
This was fixed in release `22621.2506.60.1` with the commits ac268b1 & 7d0cdde. Thanks for your work!
