### ISSUE TITLE
How to move specific screen's taskbar with Win11?

### ISSUE THREAD

**Issue by hlebushekhub** [valinet/ExplorerPatcher#2157]
Is there a way to move specific screen's taskbar to top on win11 with EP? I want my taskbar in one monitor to be on top, other on bottom. Start11 can do it but I'd love to know if there is a way to do so with EP?

**Comment by impeeza** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/41979604/cdf47f85-066b-42f6-a39a-66dc8ca1f021)
