### ISSUE TITLE
New User Creation Issue on Windows 22H2 with ExplorerPatcher

### ISSUE THREAD

**Issue by Konrad90** [valinet/ExplorerPatcher#2159]
Hello,

I'm using the latest version of ExplorerPatcher. I encountered an issue when using ExplorerPatcher on Windows 22H2. Here's a step-by-step breakdown of what I observed:

1. With ExplorerPatcher installed on Windows 22H2, I attempted to create a new local Windows user.
2. After creating the user and trying to sign in, the process hung at a white screen, and I couldn't proceed any further.
3. I then uninstalled ExplorerPatcher and retried signing in with the newly created user. This time, I successfully signed in and was greeted by the Windows new user settings dialog. Everything appeared to work as expected.
4. Later, I reinstalled ExplorerPatcher on my main user account.
5. With ExplorerPatcher reinstalled, I tried signing in to the new user account again. While I could sign in successfully, I received an error dialog stating that ExplorerPatcher crashed three times.

Nevertheless I'm a big fan of ExplorerPatcher. It's added a lot to my Windows experience, and I truly appreciate it.

<img width="500" alt="Screenshot 2023-09-24 013829" src="https://github.com/valinet/ExplorerPatcher/assets/328977/52c79654-8aaa-41e5-9384-3b48a5afb281">

**Comment by Vipin2003** [comment]
Alternate way to create local account is to use "netplwiz". From here, you won't get any issue. Check once

**Comment by Amrsatrio** [comment]
Should be fixed in the latest prerelease.
