### ISSUE TITLE
This software completely breaks windows 11 even if uninstalled

### ISSUE THREAD

**Issue by DominickVale** [valinet/ExplorerPatcher#2168]
Do not install this on windows 11 as apparently it completely fucks up your system in 5 seconds.
Lost my entire setup and a Sunday just because I needed to move the goddamn taskbar on the left like all the other superior OSes do. This is 2023 for you

**Comment by TheSylance** [comment]
Can NOT confirm. Updated yesterday, no issues on Win 11 Pro  Build 2262.
So maybe just an unlucky fluke on your side?

**Comment by DominickVale** [comment]
> Can NOT confirm. Updated yesterday, no issues on Win 11 Pro Build 2262. So maybe just an unlucky fluke on your side?

Typical of my life, still amazed at how easily this thing absolutely shredded my entire system. I've been able to recover windows installations from malware before but couldn't save myself from this utility.

**Comment by BraINstinct0** [comment]
For proper investigation of the issue/cause, providing your specific situation helps a lot.

Please post the `Windows` version and build numbers. You can find this by running `winver`.
Please post the `explorer patcher` version you are using.
Also, if any, please include what settings you changed in `explorer patcher` properties application.

**Comment by Amrsatrio** [comment]
Please calm down. Tell us your Windows version from `winver`. And chances are you downloaded ep_setup.exe into the downloads folder, so you can just open `cmd` and type `%USERPROFILE%\Downloads\ep_setup.exe /uninstall` and then your setup should be back.

**Comment by bradleynielsen** [comment]
I can confirm that 

- [win]+A is broken
- Search from Start menu is broken

Edition	Windows 11 Pro
Version	22H2
Installed on	‎12/‎7/‎2022
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by Poopooracoocoo** [comment]
@bradleynielsen make a new issue.
