### ISSUE TITLE
Broken Start Menu search and Broken Shortcut to "Control Center" ([win]+A)

### ISSUE THREAD

**Issue by bradleynielsen** [valinet/ExplorerPatcher#2170]
I can confirm that the following is broken:
- [win]+A 
- Search from Start menu 

Processor	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz
Installed RAM	64.0 GB (63.9 GB usable)

Edition Windows 11 Pro
Version 22H2
Installed on ‎12/‎7/‎2022
OS build 22621.2283
Experience Windows Feature Experience Pack 1000.22662.1000.0

Other windows mod SW installed:
- PowerToys 0.73

Let me know if other details are needed.

**Comment by Amrsatrio** [comment]
Are you sure you're on the latest EP version?

**Comment by bradleynielsen** [comment]
> y

Yes, I double checked before I commented. I pretty much check for releases every other day because search is broken, but the usefulness of the other features are better.

**Comment by pyrates999** [comment]
Then please post explorer patcher version.

when search is not working:

try this to rebuild the search index: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/windows-search-performance-issues

**Comment by Crow74** [comment]
Can confirm what Bradley said: pressing the Win key, and then start typing to search and quickly start an app doesn't work anymore for me.

**Comment by bradleynielsen** [comment]
The restart works. Thanks for the help.

**Comment by bradleynielsen** [comment]
Uninstall > Restart > Reinstall
