### ISSUE TITLE
Wrong argument to swprintf_s() in dllmain.c

### ISSUE THREAD

**Issue by MarkDuster2** [valinet/ExplorerPatcher#2172]
On [this line](https://github.com/valinet/ExplorerPatcher/blob/fe78dcaa24b26f4f78702664c25a25a41149e3eb/ExplorerPatcher/dllmain.c#L2516) the 2<sup>nd</sup> argument of `swprintf_s()` should be `MAX_PATH`. The [documentation](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-s-sprintf-s-l-swprintf-s-swprintf-s-l#parameters) says it's `sizeOfBuffer`, i.e. the maximum number of characters to store.

**Comment by Amrsatrio** [comment]
We took it from the disassembly of TrayUI::BuildContextMenu(). I've updated that code to look better, require less maintenance, and maybe correct mistakes too.
