### ISSUE TITLE
Windows PowerShell (Admin) doesn't run as admin, and crash occurs when doing Right-Click on the Start button for the second time

### ISSUE THREAD

**Issue by Bahaa-Sobhy** [valinet/ExplorerPatcher#2177]
Hello there Valinet;

There are two issues, I am facing for many months now, 

1. On the Start Menu button, I do Right Click, to get the context-Menu that lists the tools for adminstrating Windows (see the below image)

![image](https://github.com/valinet/ExplorerPatcher/assets/7080504/fcaace77-4172-4c95-9e35-758b91d08f0b)

when I click "Windows PowerShell (Admin)" to open, the PowerShell is not running as administrator, it acts exactly as the non-admin "Windows PowerShell".

![image](https://github.com/valinet/ExplorerPatcher/assets/7080504/de3940ba-b9f3-4c66-b630-922ede8f7519)

2. Furthermore, when I close this non-admin PowerShell window, and again repeat the scenario, once I click on the Start Menu button there's a crash happens (The Taskbar disappear, etc...).

**Note:** the crash - in most cases - is not limited to trying to open the PowerShell, it happens - sometimes - when I try to open the Start Menu button's Context-Menu for the second time after opening any application from it in the first time.

**This is the OS specs:**

![image](https://github.com/valinet/ExplorerPatcher/assets/7080504/6d614602-94b3-49c8-8732-d42dbbe506f5)

**This is the current EP version I'm running:**

![image](https://github.com/valinet/ExplorerPatcher/assets/7080504/3ce2a41c-f72c-4cef-aeae-c16891536b30)

**Here's the error log:**

```
Faulting application name: explorer.exe, version: 10.0.22621.2283, time stamp: 0x411f7365
Faulting module name: ntdll.dll, version: 10.0.22621.2215, time stamp: 0x7a9f67f2
Exception code: 0xc0000374
Fault offset: 0x000000000010c319
Faulting process id: 0x0xC6C
Faulting application start time: 0x0x1D9EF7A36B39322
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: aa2029d8-7667-4969-9d85-ad37b3618e8d
Faulting package full name: 
Faulting package-relative application ID: 
```

Best regards;

**Comment by pyrates999** [comment]
When EP is not installed, can you confirm that opening "Windows PowerShell (Admin)" from the windows key+x menu, does prompt you for elevated privileges?

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2156

Please close this.

**Comment by Bahaa-Sobhy** [comment]
@pyrates999 

> When EP is not installed, can you confirm that opening "Windows PowerShell (Admin)" from the windows key+x menu, does prompt you for elevated privileges?

Without EP, when I run Windows PowerShell (Admin), it really runs as administrator, and I can do all tasks a privileged admin could do.

**Comment by Bahaa-Sobhy** [comment]
> duplicate of: #2156
> 
> Please close this.

OK!
