### ISSUE TITLE
Customise Notification Area Icons does not change with settings

### ISSUE THREAD

**Issue by granterogers** [valinet/ExplorerPatcher#2179]
Launching "customise notification area icons" -> Change a particular application (.e.g Teams) from "notifications only" to "show icon and notifications" has no effect.

After changing and closing the settings windows, and relaunching  "customise notification area icons" I see my changes were not saved and the app remains "notifications only"

Currently, the only way I can have icons on the taskbar is to select "Always show all notifications and icons on the taskbar"

Running EP 22621.2361.58.1 
Windows 22621.2283

Thanks

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Comment by granterogers** [comment]
closed as duplicate : [1454](https://github.com/valinet/ExplorerPatcher/issues/1454)
