### ISSUE TITLE
i tried to uninstall it didnt work

### ISSUE THREAD

**Issue by raf78910** [valinet/ExplorerPatcher#2189]
i used the wiki and it didnt work

**Comment by pyrates999** [comment]
https://github.com/valinet/ExplorerPatcher/wiki#uninstalling

**Comment by raf78910** [comment]
i tried it it didnt work

**Comment by pyrates999** [comment]
describe how it didn't work.

**Comment by pyrates999** [comment]
please show a screen shot of what you mean

**Comment by raf78910** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/145019933/3101222f-313e-4263-948c-b0bab9ada2e7)

**Comment by raf78910** [comment]
i changed the setting to have an X beside it, then i renamed it to ep_uninstall.exe and ran it then it just restarted the program

**Comment by Amrsatrio** [comment]
Did you check the "Register as shell extension"? Try to uncheck it, restart your PC, then `ep_setup.exe /uninstall`. That works for me.

**Comment by raf78910** [comment]
i tried it and it just restarted the taskbar

**Comment by pyrates999** [comment]
Do you have any other applications installed that modifies the windows ui?

**Comment by raf78910** [comment]
No I only have explorer patcher I don't know about any other ones I have downloaded could it be wallpaper engine

**Comment by pyrates999** [comment]
is wallpaper engine an application?  If so, try uninstalling it.

**Comment by raf78910** [comment]
I just deleted it from control panel and it worked!

**Comment by pyrates999** [comment]
Please close this then.
