### ISSUE TITLE
unable to pin softwares in the start menu

### ISSUE THREAD

**Issue by carolpalm** [valinet/ExplorerPatcher#2190]
At first, I could not pin apps like Notepad or Character Map in the start menu, but with other software I had no problem. Now, updated softwares like Photoshop vanished from the Start menu and they don't appear back even after selecting them to be pinned back.

I am using:
Windows 11
Version 22H2
OS Build 22621.2283

Thanks for any help!

**Comment by pyrates999** [comment]
known issues: https://github.com/valinet/ExplorerPatcher/discussions/1679
