### ISSUE TITLE
Windows 10's WiFi Menu buttons don't work

### ISSUE THREAD

**Issue by BlackAnt1968601851** [valinet/ExplorerPatcher#2192]
I have issues with the WiFi Menu not working properly I can't switch on airplane mode or switch off WiFi or switch it back on.
it can be replicated on Windows 11 build 22621.1848 running explorer patcher version 22621.2361.58.1
the steps to replicate is to go into properties on the file explorer and turn on windows 10 flyout in the system tray submenu.
it has a 100% rate of replication.
The buttons only show the text and not the button outline.
![image](https://github.com/valinet/ExplorerPatcher/assets/117094394/d07292cf-7390-48c9-b559-111596dd048d)

**Comment by Poopooracoocoo** [comment]
also see #1201

**Comment by Amrsatrio** [comment]
Temporary workaround: Go to `C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy` and delete `dxgi.dll`. You'll need to do this every EP update.

**Comment by pyrates999** [comment]
You're on an old update: https://support.microsoft.com/en-au/topic/june-13-2023-kb5027231-os-build-22621-1848-8f903600-1293-4431-9c6b-736a4049666c

Please update to the current update: https://support.microsoft.com/en-us/topic/september-12-2023-kb5030219-os-build-22621-2283-8b9ba74f-fdde-4c75-b049-77cf214f4a66

**Comment by Amrsatrio** [comment]
@pyrates999 There is nothing wrong with staying on old versions, especially when Microsoft breaks stuff every update nowadays. Unless it is a Preview version.

**Comment by pyrates999** [comment]
EP is only tested on the current release of windows 10 with the last update released for it.

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. You don't need to delete dxgi.dll from ShellExperienceHost anymore.

**Comment by BlackAnt1968601851** [comment]
Amrsatrio, renaming that DLL seems to work as a workaround.

**Comment by Amrsatrio** [comment]
Yeah but you have to do this every time EP updates.

**Comment by BlackAnt1968601851** [comment]
It also looks like they actually released a proper fix for it in version 22621.2361.58.4

**Comment by Amrsatrio** [comment]
It was me who made the proper fix 😉

**Comment by BlackAnt1968601851** [comment]
oh, Thanks for the fix.
