### ISSUE TITLE
Search window not to align to the left  on version 22454

### ISSUE THREAD

**Issue by ErickWei** [valinet/ExplorerPatcher#22]
It's seems that search window not to align to the left on new version 22454

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Works for me just fine but Windows 10 setup deletes/does not migrate dxgi.dll placed in SystemApps subfolders. Only C:\Windows\dxgi.dll is migrated. You have to copy dxgi.dll to C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy and MicrosoftWindows.Client.CBS_cw5n1h2txyewy again.

**Comment by ErickWei** [comment]
> Works for me just fine but Windows 10 setup deletes/does not migrate dxgi.dll placed in SystemApps subfolders. Only C:\Windows\dxgi.dll is migrated. You have to copy dxgi.dll to C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy and MicrosoftWindows.Client.CBS_cw5n1h2txyewy again.

Yes,I did.
Maybe it's delay,Workable now.
Thanks

**Comment by valinet** [comment]
Yeah, maybe a better way to hook those should be found, but idk how, honestly. StartIsBack does it somehow that the Start sits on the left, maybe they can tell us how…

**Comment by Gaurav-Original-ClassicShellTester** [comment]
> > Works for me just fine but Windows 10 setup deletes/does not migrate dxgi.dll placed in SystemApps subfolders. Only C:\Windows\dxgi.dll is migrated. You have to copy dxgi.dll to C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy and MicrosoftWindows.Client.CBS_cw5n1h2txyewy again.
> 
> Yes,I did.
> Maybe it's delay,Workable now.
> Thanks

Well I have added this line to the settings.ini of ExplorerPatcher in the General section

[General]
ExplorerReadyDelay=600

After logging in, the Windows 11 Start menu is immediately available to me. There is absolutely no delay for logon or for any features.
