### ISSUE TITLE
EP 22621.2361.58.1 not show Copilot in taskbar for Win11 22621.2361

### ISSUE THREAD

**Issue by nijawang** [valinet/ExplorerPatcher#2205]
If any way to show Copilot in taskbar with EP?

**Comment by Poopooracoocoo** [comment]
To be clear, is this with the Windows 10 or Windows 11 taskbar. 
Some people use only various parts of ExplorerPatcher such as the File Explorer tweaks or the Windows 10 Start Menu, so I think its good to ask.

**Comment by jlitz** [comment]
Copilot icon does show up  in Windows 11 version   does not show in Windows 10    I like my taskbar on the top so must use Windows 10 version   so no copilot  icon or  widget icon is  visible just to clarity things.

**Comment by pyrates999** [comment]
Since copilot is windows 11 only and not windows 10, Microsoft may not have added it to the windows 10 taskbar.

**Comment by nijawang** [comment]
Now I just use Win+C to call Copliot.

**Comment by Poopooracoocoo** [comment]
Closing due to lack of response by author. If you are referring to the Windows 10 taskbar, please make a feature request as it isn't a bug. Thank you.

**Comment by Adyextreme01** [comment]
> Copilot icon does show up in Windows 11 version does not show in Windows 10 I like my taskbar on the top so must use Windows 10 version so no copilot icon or widget icon is visible just to clarity things.

ah right now there will be also a windows 10 version of windows copilot  afer all the kernels are the same , `Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowCopilotButton"=dword:00000001` must be added to registry , getViVeTool v0.3.3and `vivetool /enable /id:44776738 /priority:test /store:both`

**Comment by Adyextreme01** [comment]
> If any way to show Copilot in taskbar with EP?

yeah take a look

`https://www.windowslatest.com/2023/11/19/how-to-enable-microsoft-copilot-on-windows-10/`

and if even afer tah the icon is missing place a shortcut  with `microsoft-edge:///?ux=copilot&tcp=1&source=taskbar`

you can the add any custom icons

under some special cases youi need to install latest microsoft web wiew 32or 64 depending on your system
