### ISSUE TITLE
flashing issue after uninstall

### ISSUE THREAD

**Issue by Valley8140** [valinet/ExplorerPatcher#2206]
Hello

I managed to uninstall (latest build) after the [flashing screen issue](https://www.reddit.com/r/Windows11/comments/12tqinw/explorer_patcher_is_there_a_fix_to_the_flashing/), but when I restart the laptop (Dell Inspiron 14 7425) the flashing issue comes back?? Hitting Escape a few times gets me into a regular Windows 11 environment but I still like to get rid of the flashing issue completely. 
I've moved dxgi.dll out of C:/Windows, I noticed it was renamed dxgi.prev?  and rebooted but it gives me still a black screen and just a flashing "Workspaces"button.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Valley8140** [comment]
Windows 11 
22H2
22621.2283

Explorer Patcher 
22621.2361.58.1 (latest)

Unable to change any properties since the start up process ends in a flashing desktop and not able to start any applications.

**Comment by Amrsatrio** [comment]
Please check if these are present:
```
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\AppResolverLegacy.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\dxgi.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\dxgi.prev
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartTileDataLegacy.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\Windows.UI.ShellCommon.pri
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\en-US\StartTileDataLegacy.dll.mui
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\pris2\Windows.UI.ShellCommon.en-US.pri

C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\dxgi.dll
C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\dxgi.prev

C:\Windows\dxgi.dll
C:\Windows\dxgi.prev

C:\Program Files\ExplorerPatcher

HKEY_CURRENT_USER\Software\ExplorerPatcher
```

Try to delete all of those.

**Comment by Valley8140** [comment]
> Please check if these are present:

No sorry that seemed to have no effect at all.

**Comment by pyrates999** [comment]
Did you delete all those files, the directory C:\Program Files\ExplorerPatcher, and did you delete this in the registry editor: HKEY_CURRENT_USER\Software\ExplorerPatcher

**Comment by Valley8140** [comment]
I did delete all the files mentioned in the previous post, rebooted, same situation. Rebooted this morning and it seems to be back to normal (i.e. no flashing). Close as completed...?

**Comment by pyrates999** [comment]
You may need to repair your windows install.  Please run the following in an elevated command prompt or elevated powershell:

```sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup```

Then reboot your computer.

**Comment by Amrsatrio** [comment]
Since your issue seems to be unique to your installation, I'll close this issue as resolved.
