### ISSUE TITLE
Start menu button does nothing

### ISSUE THREAD

**Issue by Csimbi** [valinet/ExplorerPatcher#2211]
Hello,
I just upgraded from WinDOS 10 to WinDOS 11 using WinDOS update.
I quickly realized it was a mistake as Microsoft - in its infinite wisdom - has removed all usability features from the Taskbar.
They should have named it black bar because it does not do anything except taking up real estate.
It can't be moved, resized, icons can't be removed, Quick Launch is gone entirely - so it's generally useless at home and especially at work.
I ended up finding ExplorerPatcher after a few quick searches.
A lot of people seem to like it, so I thought I would give it a go.

I downloaded and installed it by running as admin.
I noticed the start button going to the right - but that's it.
Nothing happens when I click the start menu button.
I rebooted for good measure, but still, nothing.
What kind of info would you need to troubleshoot this?
Keep in mind this is a corporate laptop, so I can't provide dumps as such.
Could these be some IT security policies interfering?

**ExplorerPatcher release info**: 22621.2361.58.1

**WinDOS 11 release info**:
64bit
22H2 release installed on 28 Sep 2023 - added the lastest update on WinDOS update, too.
Build: 22621.2361
XP: WFXP 1000.22674.1000.0

Thank you!

**Comment by Amrsatrio** [comment]
Are you using the Win10 start menu, or the Win11 start menu? If you are using the Win10 start menu, please make sure that you have a stable Internet connection during installation so that files can be downloaded. If start menu still doesn't appear, wait until symbols are downloaded, just in case. And restart Explorer 1-3 times till it can appear.

**Comment by Csimbi** [comment]
Hello,
I had to add ExplorerPatcher only to fix the broken WinDOS 11 taskbar.
WinDOS 10 has resizable, movable, and highly customization taskbar, quick launch included.
I did not think anyone needed ExplorerPatcher on WinDOS 10 - sorry, my bad.
So, yes, what I mentioned above is for WinDOS 11.
I meant to include WinDOS 10 only in the context on the upgrade - sorry about the confusion!

**Comment by Amrsatrio** [comment]
Sorry, I still don't get you -- EP, when used on Win11, has an option to restore the Win10 taskbar and/or the Win10 start menu. When you install EP on Win11, the Win10 taskbar and start menu will be restored by default.

Assuming you run Win11 and haven't changed any settings, have you tried to restart explorer multiple times?

**Comment by Csimbi** [comment]
No worries, I'll keep answering, thanks for your patience!

So, when I installed it, there was no dialog of any type.
Internet connection exists, it's wired, MS Teams works fine.
Anyhow, once the start menu went to the left, I noticed it does nothing.
There was a dialog box suggesting something was not right, and the last item on that list was reboot.
So, I rebooted.
Then, that same dialog come up saying something is not right, so I rebooted yet again.
Getting still no reaction on the Start menu button, I started searching again, tried a those setting, but none worked so I removed those registry changes.
I uninstalled EP and came asking for help.

So, I had two reboots after the installation.

Does EP have a log file of its own that I could check and post?

Thank you!

**Comment by Amrsatrio** [comment]
Did you manage to screenshot that dialog box? You can enable the console in EP properties > Advanced but I'm afraid to say that it has nothing to do with the start menu not showing up.

**Comment by Csimbi** [comment]
No, but I quickly reinstalled and got it for you:
https://i.postimg.cc/fW6gNx9D/PE-Error.png

I did not change any settings from the default.

**Comment by Csimbi** [comment]
I deleted all .prev files.
No, we have no admin privileges are our company.
However, we have a tool that allows us to run software as admin, that's how I could install EP.

Now that I went through the configuration settings, I noticed the Win10/Win11 choices.
The default Win10 is great, it has everything I'd need, except of course the start menu issue I am reporting.

Thanks!

**Comment by Amrsatrio** [comment]
After installing, are these files present?
```
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\AppResolverLegacy.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartTileDataLegacy.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\Windows.UI.ShellCommon.pri
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\en-US\StartTileDataLegacy.dll.mui
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\pris2\Windows.UI.ShellCommon.en-US.pri
```

**Comment by Csimbi** [comment]
No, none of them exist.

**Comment by Amrsatrio** [comment]
Those files are downloaded by ep_setup.exe from github.com. Here's the reference in the source code: https://github.com/valinet/ExplorerPatcher/blob/1738b458667c8fa5cecaf5dc424a9dc31ab5fe33/ep_setup/ep_setup.c#L985

Can you try downloading those files and putting them manually? Seems like the restrictions your IT admin has put on your PC makes it unable to properly put those files.
https://github.com/valinet/ExplorerPatcher/files/8148997/AppResolverLegacy.dll.txt
https://github.com/valinet/ExplorerPatcher/files/8136435/StartTileDataLegacy.pri.txt
https://github.com/valinet/ExplorerPatcher/files/8136442/Windows.UI.ShellCommon.pri.txt
https://github.com/valinet/ExplorerPatcher/files/8136433/StartTileDataLegacy.dll.mui.txt
https://github.com/valinet/ExplorerPatcher/files/8136451/Windows.UI.ShellCommon.en-US.pri.txt

**Comment by Csimbi** [comment]
AppResolverLegacy.dll - check
[StartTileDataLegacy.pri.txt](https://github.com/valinet/ExplorerPatcher/files/8136435/StartTileDataLegacy.pri.txt) This is the StartTileDataLegacy.dll I assume (in the first list). - check
Windows.UI.ShellCommon.pri - check
\en-US\StartTileDataLegacy.dll.mui - check
\pris2\Windows.UI.ShellCommon.en-US.pri - check

No response to click. Going to reboot.

**Comment by pyrates999** [comment]
Please check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

You can check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  If it shows it can't download symbols, your version of windows is not supported.

**Comment by Amrsatrio** [comment]
Please reopen this issue if this issue continues to happen on your end. My recommendation is to downgrade to Windows 10 while it's possible, since EP does not support and was not tested on restricted environments.
