### ISSUE TITLE
Taskbar is clear when installed on windows 11.

### ISSUE THREAD

**Issue by pagedpenguin251** [valinet/ExplorerPatcher#2213]
I updated to windows 11 and wanted to put the task bar on the side but no mater what I do the taskbar is clear.

**Comment by Amrsatrio** [comment]
Are you sure your EP is the latest one? Do you use TranslucentTB or Open Shell? I observe no major issues with the Win10 taskbar on 22631.2361, when I'm using only OldNewExplorer.

**Comment by pyrates999** [comment]
If you have classic shell installed, uninstall it.  It is no longer maintained.  It's replacement is open shell.

**Comment by Amrsatrio** [comment]
I will close this issue since there seem to be no more activity and that the taskbar is just fine on 22631.2361.

**Comment by pagedpenguin251** [comment]
> If you have classic shell installed, uninstall it. It is no longer maintained. It's replacement is open shell.

yes that worked
