### ISSUE TITLE
explorer.exe crashes on startup and when attempting to restart EP

### ISSUE THREAD

**Issue by CephalonSinisite** [valinet/ExplorerPatcher#2216]
It started happening to me today, every system reboot, every EP restart, tried chaning some settings, nothing helped. It crashes a few times then gives me the "Unfortunately, File Explorer is crashing :(" message.
[ExplorerPatcher_22621.2361.58.1.zip](https://github.com/valinet/ExplorerPatcher/files/12765491/ExplorerPatcher_22621.2361.58.1.zip)
![image](https://github.com/valinet/ExplorerPatcher/assets/77461217/e1051edb-ee6d-4814-b570-74b9e0c979a1)
![image](https://github.com/valinet/ExplorerPatcher/assets/77461217/972bfdb7-8849-4052-af7b-25cc0bd2cb78)
![image](https://github.com/valinet/ExplorerPatcher/assets/77461217/79ff3bf1-b203-4a2b-bf43-c6f8539194ea)

**Comment by Hukinator** [comment]
I had the same problem, a reinstall worked for me.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/september-26-2023-kb5030310-os-build-22621-2361-preview-363ac1ae-6ea8-41b3-b3cc-22a2a5682faf

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.

**Comment by Poopooracoocoo** [comment]
@pyrates999 With @amrsatrio's contributions that allow win+x and win10 alt+tab to work without symbols, you can expect more of EP to run on future Insider builds, or at least release preview ones. It should support the release preview, beta and dev channel builds, as per the description of the releases: https://github.com/valinet/ExplorerPatcher/releases.

**Comment by Amrsatrio** [comment]
Is it possible to catch the console output before it crashes? (EP Properties > Advanced > Show console)

**Comment by CephalonSinisite** [comment]
![IMG20230930124053](https://github.com/valinet/ExplorerPatcher/assets/77461217/477b564f-c390-4196-ad85-507feea34248)
![IMG20230930124031](https://github.com/valinet/ExplorerPatcher/assets/77461217/4abfcb82-fc40-4e4e-a2b3-61a78f38feed)
![IMG20230930124049](https://github.com/valinet/ExplorerPatcher/assets/77461217/38acf535-06d2-485e-8c91-fe3a2e58c317)
Those are the three I could catch with my phone, I couldn't make a screenshot after trying for 20 minutes crashing it continously

**Comment by Amrsatrio** [comment]
Does your user folder name contain special characters? Like in this issue where it contains Korean characters. https://github.com/valinet/ExplorerPatcher/issues/2186#issuecomment-1736774733

**Comment by CephalonSinisite** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/77461217/5721b08f-555b-4820-b89a-bc16d24fc4c2)
nope, never did either

**Comment by pyrates999** [comment]
> @pyrates999 With @Amrsatrio's contributions that allow win+x and win10 alt+tab to work without symbols, you can expect more of EP to run on future Insider builds, or at least release preview ones. It should support the release preview, beta and dev channel builds, as per the description of the releases: https://github.com/valinet/ExplorerPatcher/releases.

My opinion is that preview updates and insider builds should be for developers only, not general release.

**Comment by Amrsatrio** [comment]
With the latest EP and Windows (should be 22621.2428), does EP still crash your system?

**Comment by Amrsatrio** [comment]
Another user who experienced the same shell32.dll crash on 22621.2428 fixed it by upgrading to 22621.2506. Apparently it is caused by Wallpaper Engine and not EP itself. Closing this due to no response.
