### ISSUE TITLE
Explorer's right click menu crashes on Moment 4 builds when using the Windows 11 context menu with non-Windows 11 command bar

### ISSUE THREAD

**Issue by djcholapin** [valinet/ExplorerPatcher#2218]
After the last update, I am now unable to use the right click in file explorer, on either a file or a folder. It crashes as soon as I right click.

As a temporary fix, I am able to fix that by ticking "Disable the windows 11 context menu". So this brings back the windows 10 context menu, and I am able to use the right click normally.

Just for the records also, I have applied the workaround mentionned in this post here : https://github.com/valinet/ExplorerPatcher/issues/1591 , which I know cn cause the start menu to crash if doing some actions.

I have also installed the very lasts windows updates.

So not sure if any of this is related at all, if it's related to the EP update vs windows update, the workaround, or both. However, I'm just throwing this here for the records.

Using now win 10 context menu then, even though I liked the Windows 11 one.

**Comment by Amrsatrio** [comment]
Do you really need to use the Win11 context menu with Win10/Win7 command bar?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

**Comment by Vipin2003** [comment]
Working Fine at my side.

**Comment by jed84** [comment]
I am experiencing the same problem.

Win11 22H2 22621.2361
EP 22621.2361.58.1

EP - explorer settings:
![obraz](https://github.com/valinet/ExplorerPatcher/assets/47121522/29f01929-e989-4513-899d-2a1f4a11cc44)

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/september-26-2023-kb5030310-os-build-22621-2361-preview-363ac1ae-6ea8-41b3-b3cc-22a2a5682faf

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by EdwardD808** [comment]
I have the same issue and really wish to continue using this program.  
Windows 11 
![image](https://github.com/valinet/ExplorerPatcher/assets/92354900/bd4c50c9-30f7-44ca-859d-42979c9daf7a)
ExplorerPatcher Version 22621.2428.59.1

My relevant settings: 
![image](https://github.com/valinet/ExplorerPatcher/assets/92354900/cc4dbb53-c8a3-43a4-822a-0afa46114080)

![image](https://github.com/valinet/ExplorerPatcher/assets/92354900/ea9e4867-873b-4578-b57f-5dc6dd5db537)

![image](https://github.com/valinet/ExplorerPatcher/assets/92354900/5e7ca460-b43f-40c3-a6be-a79e210a560a)

![image](https://github.com/valinet/ExplorerPatcher/assets/92354900/09d55713-c2df-40e7-8042-eaef97680069)

**Comment by Amrsatrio** [comment]
@EdwardD808 You're using Win11 command bar with Win11 context menu, it's the default behavior and everything works fine. Which crash are you having?

**Comment by EdwardD808** [comment]
Every time I right click anywhere (except for the taskbar), Explorer crashes.

**Comment by Amrsatrio** [comment]
The workaround for now is to enable this:
<img width="233" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/843b6db4-62f8-4ceb-82e5-8229d0b46ca4">

**Comment by EdwardD808** [comment]
@Amrsatrio Thanks so much for that info!  No more crash, plus I like the look of the now working context menu.

**Comment by martinhodfranco** [comment]
> A solução alternativa por enquanto é habilitar isso: <img alt="imagem" width="233" src="https://private-user-images.githubusercontent.com/20662640/282236479-843b6db4-62f8-4ceb-82e5-8229d0b46ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODI4NzMsIm5iZiI6MTcwNDI4MjU3MywicGF0aCI6Ii8yMDY2MjY0MC8yODIyMzY0NzktODQzYjZkYjQtNjJmOC00Y2ViLTgyZTUtODIyOWQwYjQ2Y2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDExNDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTU3NDUyOTU4NWJiNGZlMDBkNzQyZTUxOGQ0ZThkZjM4NDYzMTJmMjJjZmJlM2EwNjk0YTY4MzZmYzE2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.40AJ7Y4bXbz-39h7kok4WPo09bKE9alHJLCBS0dCoZs">

Como habilitar esse função se não consigo abrir o Explorer Patcher?

**Comment by Justtaway** [comment]
Win11x64 23H2 22631.3085, EP 22621.2861.62.2
After installing KB5034204, Explorer now crashes every time I try to start it.
Scheluder logs:
```
 AppName explorer.exe 
  AppVersion 10.0.22621.3085 
  AppTimeStamp a58eee1c 
  ModuleName ExplorerFrame.dll 
  ModuleVersion 10.0.22621.3085 
  ModuleTimeStamp 0b45ea8a 
  ExceptionCode c0000005 
  FaultingOffset 000000000000862b 
  ProcessId 0xe24 
  ProcessCreationTime 0x1da504e5740ed46 
  AppPath C:\Windows\explorer.exe 
  ModulePath C:\Windows\SYSTEM32\ExplorerFrame.dll 
  IntegratorReportId 2be3db4a-e262-4cf0-9712-74ba0d63641f 
  PackageFullName  
  PackageRelativeAppId  
```

I tried various combinations of those settiings: ![image](https://github.com/valinet/ExplorerPatcher/assets/9951646/fa33cad7-940e-47b9-982d-14b8af1e776b)
Still get crashes. If some additional info is needed, I'll gladly provide it.

**Comment by Amrsatrio** [comment]
@Justtaway Does your Explorer continue to crash even if EP is not installed?

**Comment by Justtaway** [comment]
> @Justtaway Does your Explorer continue to crash even if EP is not installed?

Now that you mention it and I tried uninstallin EP, crash is still there...

**Comment by Amrsatrio** [comment]
Did you ever use ViVeTool to disable feature flags? If so, please revert your changes.

If one disables the tabs feature flag (37634385) or new navigation bar (40950262), starting in 22621.29xx or 22631.29xx Explorer will crash no matter what.

**Comment by Justtaway** [comment]
> Did you ever use ViVeTool to disable feature flags? If so, please revert your changes.
> 
> If one disables the tabs feature flag (37634385) or new navigation bar (40950262), starting in 22621.29xx or 22631.29xx Explorer will crash no matter what.

I don't think I have used it, at least knowingly. Is there any way to check?

**Comment by Amrsatrio** [comment]
Using ViVeTool itself and running `vivetool /query > result.txt`.

**Comment by Justtaway** [comment]
> Using ViVeTool itself and running `vivetool /query > result.txt`. And then search for the respective numbers.

Is that it? Looks like I have tabs disabled. Should I enable it?
![image](https://github.com/valinet/ExplorerPatcher/assets/9951646/70420282-7cc0-448d-ab0b-51e760727269)
![image](https://github.com/valinet/ExplorerPatcher/assets/9951646/4873b7e1-f1c3-4ced-b8c6-6fcdf08ff270)

**Comment by Amrsatrio** [comment]
Yes. It must be enabled.

**Comment by Justtaway** [comment]
> Yes. It must be enabled.

Yes, there is no crash now. I thought I uninstalled QTabBar, but it was still there. Enabled "Windows 10 Ribbon" and it's working fine now. Thanks for helping!

**Comment by Amrsatrio** [comment]
<img width="988" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/31e98c12-086d-4d6f-9e25-d4fd153d9631">

You mean Microsoft fixed this issue?
