### ISSUE TITLE
Moment 4 and Ribbon UI

### ISSUE THREAD

**Issue by alessio89g** [valinet/ExplorerPatcher#2223]
Hi, today I've installed KB5030310 (Moment 4 update) with "Get the latest updates as soon as they're ready for your PC" flag actived.
When the PC rebooted, I've seen some new features, like the new homepage on settings, the new bell icon for notifications and the End task option; but explorer doesn't have anymore the Tabs and has the Ribbon UI (I setted Windows 11 command).
Also, uninstalling ExplorerPatcher, the issue persists. Strangely, I noticed that creating a new account, I got it the new file explorer; so the issue is related to my account…
Any idea?

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You shouldn't be installing preview updates unless you are a developer and are OK with running pre-releases of EP.

As for the moment 4 update, I would wait until EP supports it.

**Comment by alessio89g** [comment]
The flag only enables the new features, the update is available anyway. If you untick that flag, and manually install the update, your build number will be upgraded, but all the new features will be disabled.
If you enable the flag after/before the update, you'll enable the new features.
However, stable EP already supports Moment 4 builds, as described in the Releases changelogs.
Additionally, I already told that creating a new user account, everything works as expected.

When Explorer got the tabs feature, I got a similar issue: when an Explorer window went into background, the command bar became black, and stayed black until I closed that window and reopened it.
Also in this case uninstalling EP I cannot fix the issue and with a new account everything was ok.
After months I realized that it was caused by the mica effect that I setted on "Everywhere" in EP months ago, until this feature became no longer available in newer builds, but it stayed setted.
To fix it, I uninstalled EP, I installed the latest build with this feature available, setted it to the default setting and I updated EP again to the latest version.

I think is something like this

**Comment by Amrsatrio** [comment]
Delete this registry key:
`HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}`

Let me know how it goes.

**Comment by alessio89g** [comment]
Unfortunately, after many attempts (which made the OS feels "dirty"), I have decided to give up for now, so I restored a backup of my system drive. Probably I can re-try next weekend.
Thank you.
In the meantime, other suggestions are welcome.

**Comment by Amrsatrio** [comment]
Please reopen this issue if you still cannot figure this out.

**Comment by alessio89g** [comment]
> Delete this registry key: `HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}`
> 
> Let me know how it goes.

Today I tried again to install the update, obviously I get the same issue, so I try your suggestion, but that key doesn't exist

**Comment by Amrsatrio** [comment]
Any other tweak software you're using? It's highly likely that EP conflicts with another tweak software.

**Comment by alessio89g** [comment]
Winaero Tweaker, but I don't know which tweak can influence this behaviour

**Comment by Amrsatrio** [comment]
Even when you enable "open folders in a separate process" it still doesn't show the new command bar?

**Comment by alessio89g** [comment]
Yes, always RibbonUI

**Comment by alessio89g** [comment]
I don't know if can help, but this is what the console shows when I restart explorer and open a new folder

`Running on Windows 11, OS Build 10.0.22621.2361.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 46F60
ITrayUIHost = 3A52B8
Setup explorer functions done
Setup uxtheme functions done
Failed to open twinui.pcshell.dll
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup windows.storage functions done
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Open Start on monitor thread
EP Service Window thread
Started "Open Start on current monitor" thread.
Initialized taskbar centering module.
Progman: 328906
Progman hook: 852455
0 0
[EnsureXAML] 63 ms.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Install updates automatically".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.2361.58.4.f0ab2cdb0cc00ced"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.2361.58.4.f0ab2cdb0cc00ced" (valid).
[Updates] Local version obtained from hash is 22622.2361.58.4.
[Updates] No updates are available.
0 46000000
10000 46000000
0 46000000
`

and this when I open a folder in a separate process

`0 46000000
10000 46000000
0 46000000
`

**Comment by cozykitten** [comment]
Same issue, Windows 11 explorer tabs were gone and instead some convoluted ribbon (probs how it looked before) was back.
That happened after the update of EP today (probably yesterday for you all).

I tried deleting the registry key mentioned above, didn't change anything, so I restored it.

Then I took a look in EP settings and found this was set to "Windows 10 style" for some reason, even though I didn't touch the settings in weeks.
![image](https://github.com/valinet/ExplorerPatcher/assets/116394977/86318172-cbbc-4b21-ae5d-b248b0ba76e3)

@alessio89g did you double check your EP properties?

**Comment by alessio89g** [comment]
Yes, EP settings is set to "Windows 11 BommandBar (default)"

**Comment by alessio89g** [comment]
I ask myself if there is any way to completely uninstall EP, as if it had never been installed.
I think this because, uninstalling EP the issue is still here, if I reinstall EP it uses the last settings I used and it doesn't need to re-download the symbols, because they are still stored in the drive; and lastly creating a new account, explorer works fine, also with a "fresh" EP with its default settings (the new account finds EP installed by my broken account).
I think, if we could do it (so "reset" explorer), we could fix any issue.

**Comment by pyrates999** [comment]
Here's how to uninstall EP: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

**Comment by alessio89g** [comment]
I found the culprit:
I used this tutorial (point 3) for years in order to disable the Run dialog box history:
`https://www.eehelp.com/question/how-to-turn-off-the-most-recent-list-used-to-term-other-apps/#:~:text=3%20turn%20off,deny%20read%20access.`
Resetting this key Explorer shows the new UI.
I hope I'll find a new way to disable again the Run dialog box history soon.
