### ISSUE TITLE
Can't add titles after update

### ISSUE THREAD

**Issue by HipekGlucio** [valinet/ExplorerPatcher#2224]
Hi. I did an update of ep and it cleared all my pinned titles and i can't add any. I'm clicking "pin to start" and it does nothing. Please fix.

**Comment by Vipin2003** [comment]
Pin to Start won't work anymore You have to Drag n drop apps to tile area. Refer #1679 for more details.

**Comment by Poopooracoocoo** [comment]
Closing as this issue is known
