### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by Epixx512** [valinet/ExplorerPatcher#2226]
whenever i click import settings, the open file window crashes after a second

**Comment by pyrates999** [comment]
Please upload the settings file you're trying to import.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Vipin2003** [comment]
Not happening with me. I've tried it on my 2 laptops but no crash issue is faced by me.

**Comment by Amrsatrio** [comment]
Same. Even on the new UI I've been working on. Closing as can't repro
