### ISSUE TITLE
KB5030310 preview update issue: Explorer process not running and not startable after login

### ISSUE THREAD

**Issue by p-bogi-ba** [valinet/ExplorerPatcher#2232]
Hello, after installing [KB5030310](https://support.microsoft.com/en-au/topic/september-26-2023-kb5030310-os-build-22621-2361-preview-363ac1ae-6ea8-41b3-b3cc-22a2a5682faf) on Win11 22H2 (22621.2283) , reboot and login I got black screen with mouse pointer visible. I found I can start Task Manager with Ctrl-Alt-Del. I found no explorer.exe process running. I attempted to start it from Task Manager 'Run new task' and also from cmd prompt launched that way but explorer did not start without any message. I was able to uninstall that KB using command line
wmic qfe list brief /format:table
wusa /uninstall /kb:5030310
Then after reboot I experience no issue anymore.
I cannot be 100% sure that my issue is related to Explorer Patcher but I consider it as probable since I am using no other Explorer or Start Menu related tweak. My EP settings:

![image](https://github.com/valinet/ExplorerPatcher/assets/115402427/13d30e28-4b25-414d-a0b8-6d3b87762acf)
![image](https://github.com/valinet/ExplorerPatcher/assets/115402427/3ad57685-9a31-455b-abbb-d91c9132a1f5)
![image](https://github.com/valinet/ExplorerPatcher/assets/115402427/4e53dacc-3b29-444b-bff0-4df248f451ad)

**Comment by Amrsatrio** [comment]
Are you sure you are using the **latest** EP version?

**Comment by p-bogi-ba** [comment]
Not ... I see 22621.819.52.2 19-Dec-22. I never updated and I also never had troubles with EP - in fact I forgot about EP being installed. So well it worked. Thank you very much for that. I have it installed mainly because I like the taskbar toolbars.

I will update now but I am still unsure what will happen when the preview update will transform into mandatory one. Do you think my issue is addressed by EP updates?

**Comment by Amrsatrio** [comment]
Of course. Lately we've been testing EP against latest updates including Insider Dev ones so that everyone who use EP can stay updated without major issues.

Please keep EP updated, at all costs, even though it works. Forced updates from Microsoft can introduce issues if you stay on old versions of EP.

**Comment by p-bogi-ba** [comment]
Thanks for your suggestion and all the testing done. I just donated to help with that. I am now on 22621.2361.58.1.

I have notifications disabled system wide ... I will look at EP update before monthly Windows updates.
