### ISSUE TITLE
Right click menu flashing again

### ISSUE THREAD

**Issue by Absolutely565** [valinet/ExplorerPatcher#2238]
Explorer flashes back after using windows 11 right click menu when using windows 10 taskbar

**Comment by Amrsatrio** [comment]
I assume you are using 22621.2361 or 22631.2361. That means your issue is a duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218.

**Comment by Absolutely565** [comment]
EP is 22621.2361, windows version is 22631.2361, then this one account crashes using win11 menu explorer, then other local accounts have no problems

**Comment by Absolutely565** [comment]
I also crash using the windows 11 right click menu under the windows 11 taskbar, is it something to do with the Microsoft account
