### ISSUE TITLE
Volume OSD missing

### ISSUE THREAD

**Issue by skyehasbpd** [valinet/ExplorerPatcher#2240]
This has been an issue before but it appears as though its bugged again

Last time this [Issue appeared](https://github.com/valinet/ExplorerPatcher/issues/2049) was 3 weeks ago

i tried to reinstall EP but nothing changed

**Comment by Poopooracoocoo** [comment]
State your EP version and OS build

**Comment by skyehasbpd** [comment]
EP Version is Latest (22621.2361.58.1) 
OS build is 22621.2283

**Comment by Amrsatrio** [comment]
Hi, sorry to have this issue appear again. Can you show the console (EP Properties > Advanced > Enable console) and screenshot the top part? You'll have a working volume and brightness OSD if you have these lines:
<img width="881" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/7ad3fe0d-0b7d-4970-b656-6dbb437762af">

**Comment by skyehasbpd** [comment]
Here is a screenshot of the console

![image](https://github.com/valinet/ExplorerPatcher/assets/146914337/cb550ed6-a1a9-4627-b50a-65babce88134)


saldy i cannot remember what settings i changed, but i hope this screenshot helps
![image](https://github.com/valinet/ExplorerPatcher/assets/146914337/7c7f4919-9f57-4caf-9c11-760c21edb431)

**Comment by skyehasbpd** [comment]
oh and i have installed [ModernFlyouts](https://www.microsoft.com/store/productid/9MT60QV066RP?ocid=pdpshare) from the Microsoft Store and changed the default flyout to none, which did end up fixing it

![image](https://github.com/valinet/ExplorerPatcher/assets/146914337/25e847a1-d84d-4f98-b60c-0cb06df76bb0)

**Comment by Amrsatrio** [comment]
🤦
