### ISSUE TITLE
It could be an account problem.

### ISSUE THREAD

**Issue by Absolutely565** [valinet/ExplorerPatcher#2241]
I went to use the windows 11 taskbar in using the windows 11 right click menu still crashes but in other local accounts there is no problem

**Comment by Poopooracoocoo** [comment]
State your EP version and OS build

**Comment by Absolutely565** [comment]
windwos11 22631.2361
EP 22621.2361

**Comment by pyrates999** [comment]
Please post the full EP version or post a screen shot in the about section of the EP properties application.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

**Comment by Absolutely565** [comment]
![屏幕截图 2023-10-05 060505](https://github.com/valinet/ExplorerPatcher/assets/146397687/a7ac0773-5b9c-4790-8dad-228f7229e65d)

**Comment by Amrsatrio** [comment]
You must use the Windows 11 command bar if you want to use Windows 11 right click on 22621.2361+.
