### ISSUE TITLE
Couldn't switch to Windows 10 Start Menu at Windows 11 23560.1000 Build

### ISSUE THREAD

**Issue by Muska-Ami** [valinet/ExplorerPatcher#2246]
When I switch to Windows 10 Start Menu and click the Start Menu Button, It doesn't open the menu.

<img width="422" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/79651409/6130352b-8318-4c63-9091-c18acda90220">

**Comment by Amrsatrio** [comment]
Please give me some time to get this build and test functionalities for you. I will support this new Dev build.

**Comment by Vipin2003** [comment]
> Please give me some time to get this build and test functionalities for you. I will support this new Dev build.

Get this build on UUPDUMP....haven't checked if available on official site

**Comment by Amrsatrio** [comment]
@Vipin2003 
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/d4f3ac15-a7d2-4d69-a7df-d4ee98bf0adb)
<img width="159" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/93edd3be-bd24-4101-91ba-bcc73065fc54">

I'm making my way.

@Muska-Ami Have you tried running ep_setup.exe again? You have to reinstall EP every time you've done a feature update/Windows upgrade.

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/64722c90-cdf7-4b4b-8d27-262dafec5b23)

**Comment by Muska-Ami** [comment]
> @Vipin2003 
> ![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/d4f3ac15-a7d2-4d69-a7df-d4ee98bf0adb)
> <img width="159" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/93edd3be-bd24-4101-91ba-bcc73065fc54">
> 
> I'm making my way.
> 
> @Muska-Ami Have you tried running ep_setup.exe again? You have to reinstall EP every time you've done a feature update/Windows upgrade.
> 

Of course I am, I will retry it to see does it works.

**Comment by Muska-Ami** [comment]
Well, When I retry it and it works, but my Menu was in a mess XD(
![屏幕截图 2023-10-06 051142.png](https://github.com/valinet/ExplorerPatcher/assets/79651409/f3a5bff9-d4da-42ce-9bd6-3db933fe4a6d)

**Comment by Amrsatrio** [comment]
Don't mess with your start menu for now, I'll make a new prerelease to fix the mess.

**Comment by Muska-Ami** [comment]
> Well, When I retried it and it works, but my Menu was in a mess XD(
> ![屏幕截图 2023-10-06 051142.png](https://github.com/valinet/ExplorerPatcher/assets/79651409/f3a5bff9-d4da-42ce-9bd6-3db933fe4a6d)
> 
> 

Seem I've lost some Tiles,but it works now.

**Comment by Amrsatrio** [comment]
A new prerelease is being built now, and after installing it your non-UWP apps should appear again.

**Comment by Muska-Ami** [comment]
> A new prerelease is being built now, and after installing it your non-UWP apps should appear again.

Does I need any other steps?I've install the latest releases and restart my computer and restart the explorer, but I don't see them in the app list. D:

![屏幕截图 2023-10-06 065235.png](https://github.com/valinet/ExplorerPatcher/assets/79651409/201de3ef-876a-44c0-9e9e-a2899e80cc4e)

**Comment by Amrsatrio** [comment]
Install the latest official prerelease, but everything will be in English (until the Chinese version's maintainer updates their version):
https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.2_a4f5bd0

This is also possible:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/ec6d1e13-c27d-43ea-b96d-d4deeb415636)

**Comment by Muska-Ami** [comment]
<img width="297" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/79651409/d85704c4-be83-41c4-a0a5-3250c808195e">
Seem I've using the latest prerelease?Maybe I've install the Chinese version before so it's shows Chinese Start Menu

**Comment by Muska-Ami** [comment]
> Install the latest official prerelease, but everything will be in English (until the Chinese version's maintainer updates their version): https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.2_a4f5bd0
> 
> This is also possible: ![image](https://user-images.githubusercontent.com/20662640/273062815-ec6d1e13-c27d-43ea-b96d-d4deeb415636.png)

It's works,thanks!

**Comment by Muska-Ami** [comment]
Er,but seem I can't unpin the tiles (
when click the unpin button it not disappear from the Start Menu

**Comment by Amrsatrio** [comment]
Fix coming really soon.
