### ISSUE TITLE
Windows 10 Start Menu on right, opens OVER taskbar, instead of next to it...

### ISSUE THREAD

**Issue by Jaxel** [valinet/ExplorerPatcher#2248]
This bug seems to have appeared in the most recent version.

EP: 22621.2361.58.1
OS: 10.0.22621.2361

![Untitled-1](https://github.com/valinet/ExplorerPatcher/assets/3640402/9ecfe39c-7198-4716-86b6-f0abeb0db61d)

I have my taskbar set to windows 10 style, and on the right side of my screen. When I click the start menu, instead of it showing to the left of the taskbar, it appears completely over the taskbar. The issue does not appear when the taskbar is on the left, only when it is on the right.

**Comment by pyrates999** [comment]
I would only install release previews if I'm doing development work with EP or helping to test changes done in EP.

**Comment by Jaxel** [comment]
I don't install release previews... and I have "Get the latest updates as soon as they're available" unchecked. This update was still pushed out to me.

**Comment by Amrsatrio** [comment]
SAB seems to have fixed it in their latest release. Give me few days to make a fix for this. I'm currently focusing on reimplementing the old system tray so that the old taskbar is usable again on Canary.

But yeah I agree this build has been getting pushed to the general public.

**Comment by pyrates999** [comment]
> I don't install release previews... and I have "Get the latest updates as soon as they're available" unchecked. This update was still pushed out to me.

It will be pushed to you, it just won't automatically be installed.  You may have clicked the button that says to download and install it when you saw it.  You must not push that button.

I would uninstall it for now.

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/c5b3a27c-d639-4d45-b0d7-12a5abde7351)
