### ISSUE TITLE
Start menu  Windows 11 (default)  - not open

### ISSUE THREAD

**Issue by aklexk** [valinet/ExplorerPatcher#2249]
last release
widows 10.0.22621.2361
Start menu  Windows 11 (default)  - not open

**Comment by Amrsatrio** [comment]
Please reinstall EP while being connected to the Internet -- it downloads files required to get the old start menu to work. If it still doesn't work, please restart Explorer 2-3 times after the symbols have been downloaded.

**Comment by aklexk** [comment]
no effect
