### ISSUE TITLE
Windows 11 22H2 226261.2361 (Moment 4) doesn't allow Copilot, Widgets, or Chat to be displayed on the Win10 taskbar.

### ISSUE THREAD

**Issue by SpaceGameDev568** [valinet/ExplorerPatcher#2250]
I've turned on Copilot, Widgets, and Chat but they don't appear on the Windows 10 taskbar.

![image](https://github.com/valinet/ExplorerPatcher/assets/95051062/fbcf8673-e0c1-493f-81ff-c1e930c78884)
![image](https://github.com/valinet/ExplorerPatcher/assets/95051062/6d28758b-cf66-400d-9b36-8114bcb662b5)

**Comment by Amrsatrio** [comment]
Because Microsoft do not care anymore about the old taskbar. Some day we will try to add these icons but for now you have to use keyboard shortcuts for them. We are focusing on fixing important issues right now such as pin to start and various quirks with the old start menu.

**Comment by Vipin2003** [comment]
> Because Microsoft doesn't care anymore about the old taskbar. Some day we will try to add these icons but for now you have to use keyboard shortcuts for them. We are focusing on fixing important issues right now such as pin to start and various quirks with the old start menu.

Don't know whether it is a issue or a fix thing, but newly Fixed "pin to start" having a prblm that pinning items from desktop (which are not in start menu), it creates a shortcut in start and pins a blank tile first. Let me know if this issue is known or not.

**Comment by tam710562** [comment]
I found a temporary alternative
- First create a shortcut for command `"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --single-argument microsoft-edge:///?ux=copilot&tcp=1&source=taskbar`
- Edit the icon and name as you like
- Pin it to the taskbar

**Comment by bootsmann** [comment]
I also have this issue
![grafik](https://github.com/valinet/ExplorerPatcher/assets/5744853/2b1a6c02-f10a-4e69-a60d-44c0268348ce)

**Comment by SpaceGameDev568** [comment]
Go to Settings -> Personalization -> Taskbar -> Copilot, and turn it off

**Comment by Amrsatrio** [comment]
Closing as I've checked that adding new buttons (like Search and Task View) to the old taskbar is not viable by just modifying the old taskbar.
