### ISSUE TITLE
How to restore Windows 11 desktop icons and behavior after uninstall

### ISSUE THREAD

**Issue by pshellooe** [valinet/ExplorerPatcher#2251]
After trying ExplorerPatcher, I found it to be too disorienting, so I uninstalled following the directions on the wiki. Now my Windows 11 desktop works like Windows XP (wonky grid, the placement line when rearranging icons, etc.). How do I restore the default Windows 11 desktop?

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/7520d7c5-b0fb-46bd-b6eb-a4949c2d2348)

Access this menu through Show more options in the Windows 11 context menu.
