### ISSUE TITLE
Windows 11 22H2 22621.2283 | BattlEye Anti-Cheat is blocking EP

### ISSUE THREAD

**Issue by anthonyrpitts** [valinet/ExplorerPatcher#2264]
**Windows 11 22H2 22621.2283**
**ExplorerPatcher version: 22362.2361.58.4**

Using **BattlEye Anti-Cheat** is **blocking** the following files & **_preventing usage_** of applications from Steam:

> Blocked loading of file: "**C:\Program Files\ExplorerPatcher\ExplorerPatcher.IA-32.dll**".
> Blocked loading of file: "**C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll**". 
> 

14:56:43: Starting BattlEye Service...
14:56:44: Updating...
14:56:48: Launching game...
14:56:51: Note: File blocks can be ignored if they don't cause problems with the game.
14:56:51: [INFO] Blocked loading of file: "C:\Program Files\ExplorerPatcher\ExplorerPatcher.IA-32.dll".
14:57:07: [INFO] Blocked loading of file: "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll".

**Comment by Poopooracoocoo** [comment]
Have you reported this false positive to BattlEye?

**Comment by Amrsatrio** [comment]
Has always been like this if you enable EP as shell extension. This also happens with other Explorer tweakers such as OldNewExplorer. In Fortnite, this doesn't completely prevent the game from launching.

@Poopooracoocoo This is for good. If BE allows EP to load, then one can write actual cheats in the EP code which is not what multiplayer game developers want.

**Comment by pyrates999** [comment]
So if this can't be fixed, please close this.
