### ISSUE TITLE
File Explorer takes a long time to load.

### ISSUE THREAD

**Issue by Smasher47** [valinet/ExplorerPatcher#2268]
Hello my Windows version 22H2 (Build 22621.2361)

Tool Version 22621.2361.58.4

With me, File Explorer takes a long time to load before I can use it.

**Comment by Amrsatrio** [comment]
It's just Windows being Windows. EP has been made as light as possible so that it doesn't negatively affect the general responsiveness compared to when EP is not installed.

I'm using the same build as yours on a MacBook Pro 2020 and I notice no lags whatsoever.
