### ISSUE TITLE
File explorer randomly opening

### ISSUE THREAD

**Issue by gugaalmoco** [valinet/ExplorerPatcher#2269]
Sometimes the File explorer just randomly opens, at first I thought it was when I alt-tabbed and switched windows, but then it just happened while watching a youtube video

**Comment by FallenGR** [comment]
i am having the same issue!

**Comment by squiddytk** [comment]
Same, it's whenever tabbing out or exiting anything fullscreen

**Comment by Amrsatrio** [comment]
Hasn't this always been an issue with all 22H2 builds? Even without EP installed? When something is updated in the folder, Explorer brings itself to front for no reason.

We don't have plans to make a fix for this though.

**Comment by pyrates999** [comment]
Known bug in windows itself: https://www.howtogeek.com/884624/youre-not-alone-windows-11-is-randomly-opening-file-explorer/

**Comment by FallenGR** [comment]
> Hasn't this always been an issue with all 22H2 builds? Even without EP installed? When something is updated in the folder, Explorer brings itself to front for no reason.
> 
> We don't have plans to make a fix for this though.

for me it started once I installed this app. it was not a problem before. and its not bringing windows explorer on the top it opens up a fresh windows explorer instance, i had 25 windows opened yesterday in the span of 25 minutes.... please help.....

**Comment by gugaalmoco** [comment]
> > Hasn't this always been an issue with all 22H2 builds? Even without EP installed? When something is updated in the folder, Explorer brings itself to front for no reason.
> > We don't have plans to make a fix for this though.
> 
> for me it started once I installed this app. it was not a problem before. and its not bringing windows explorer on the top it opens up a fresh windows explorer instance, i had 25 windows opened yesterday in the span of 25 minutes.... please help.....

It also started for me after installing the app.

**Comment by pyrates999** [comment]
@FallenGR @gugaalmoco 

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Amrsatrio** [comment]
@pyrates999 No need to ask about that. I started to experience this since I installed 22621 on my daily drivers which is when it just became RTM. Currently I use 22621.2361 and that happens everytime.

**Comment by gugaalmoco** [comment]
Just to update: after installing the newest Windows 11 update, build 22621.2428, the issue is gone.

**Comment by Amrsatrio** [comment]
It still happens on my daily pc that is on 2428 (try changing EP settings when an Explorer window is open) but since this is a bug in Windows itself it's not worth to be relating this to EP. Just saying.

**Comment by nabil1962** [comment]
It's from Explorer Patcher, I uninstalled it and the issue still happens. I have my windows to the latest version.
