### ISSUE TITLE
Task view doesn't work (resolved, missed an update)

### ISSUE THREAD

**Issue by Usv3re** [valinet/ExplorerPatcher#2274]
Both win+tab and taskbar key does not work, so no way to switch to other desktop
Windows 11 Pro, version 22H2, build 22621.2283
Explorer Patcher version 22621, 1992.56.3

Am I the only one?

**Comment by Poopooracoocoo** [comment]
Update EP

**Comment by Usv3re** [comment]
Oh, thanks. Do I close the topic now?

**Comment by Poopooracoocoo** [comment]
Close it if your issue has been resolved.
