### ISSUE TITLE
Digital signature

### ISSUE THREAD

**Issue by pavolholes** [valinet/ExplorerPatcher#2275]
Hi all and Valentin,
thanks a lot for a great work and amazing project. Is it possible to make the `ep_setup.exe` in the releases signed with digital signature so the Publisher is filled?

Thank you.

**Comment by pyrates999** [comment]
That costs money.  Read here why:

https://codesigningstore.com/free-code-signing-certificate

**Comment by pavolholes** [comment]
Thanks for reply @pyrates999 . Thanks to your comment I found what I need to do some research.

I found the [SigStore](https://www.sigstore.dev/) but that's not valid in Windows OS. But then in the Issues of the SigStore I found [SignPath Foundation](https://signpath.org/about/) mentioned and that might be the solution.
From the https://github.com/sigstore/fulcio/issues/250#issuecomment-1697130810:
> Disclaimer: I work for SignPath
> Just wanted to clarify that for approved OSS projects, the [SignPath Foundation](https://signpath.org/) provides free code signing certificates and of course the usage of [our services](https://about.signpath.io/) are also free.

From the [SignPath for Open Source projects](https://about.signpath.io/product/open-source) I have a feeling it would be doable for the Explorer Patcher since it's a really big project with many stars and widely used. But I believe the repository owner @valinet should contact them via email to get the approval.

**Comment by pyrates999** [comment]
We'll see what happens then.
