### ISSUE TITLE
Windows Update 22621.2428 Breaks Open Start in All Programs

### ISSUE THREAD

**Issue by mmschmieg** [valinet/ExplorerPatcher#2276]
My system just ran Windows Update and installed the latest update (not the Preview). Now, the option to open Start in All Programs no longer has any effect. Nothing serious, but I thought I would let you know.

**Comment by Amrsatrio** [comment]
22621.2428? Release preview versions do not have symbols. But I'll try to make it working without symbols. 😉

**Comment by mmschmieg** [comment]
This is not marked as a preview update, but the standard one released on Update Tuesday.
 
 
 
--- Mike Schmieg
 
The government is that great fiction by which everyone endeavors to live at the expense of everyone else. – Frederic Bastiat

**Comment by mmschmieg** [comment]
Actually, I expect there to be a lot more problems with Explorer Patcher as Microsnot parcels out 23H2, especially since it’s going to be released piecemeal. That may require a complete reworking of the patching.
 
This is not marked as a preview update, but the standard one released on Update Tuesday.
 
 
 
--- Mike Schmieg
 
The government is that great fiction by which everyone endeavors to live at the expense of everyone else. – Frederic Bastiat

**Comment by Amrsatrio** [comment]
Okay this is interesting. Even though this is a general availability release symbols are not available for this one.

<img width="424" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/39db6167-7478-45ab-83c6-44a48cd516dc">

**Comment by mmschmieg** [comment]
I suspect it has something to do with Microsoft’s decision not to release 23H2 as major update, but to release it bit by bit in cumulative updates.
 
 
 
--- Mike Schmieg
 
The government is that great fiction by which everyone endeavors to live at the expense of everyone else. – Frederic Bastiat

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease.
