### ISSUE TITLE
Reporting problems, feature requests, questions and support

### ISSUE THREAD

**Issue by MuzafferB** [valinet/ExplorerPatcher#2278]
Possible Copilot Issue:
I'm using Windows 11 and received an update today. After restart, I can see Copilot as preview under Personalisation/Taskbar. However, nothing shows on Taskbar, even it's turned on. Turned off and on again and restarted file explorer with no luck.
Screenshot: https://imgur.com/a/yBrnx6X

**Comment by Amrsatrio** [comment]
Please use Win+C to invoke copilot when using the Windows 10 taskbar. The old taskbar is no longer updated and it wasn't made in a way where the buttons are customizable by external programs. We have no plans to add the Copilot button.
