### ISSUE TITLE
Start Menu does not open in 22621.2428 and 22635.2419

### ISSUE THREAD

**Issue by Karell2013** [valinet/ExplorerPatcher#2280]
I updated to build 22635.2419 on Windows 11 (23H2), and the Windows 11 start menu does not open 
![image](https://github.com/valinet/ExplorerPatcher/assets/100191384/7d3f143a-ac5c-4aa2-906a-14eb5b90f50f)

**Comment by Amrsatrio** [comment]
A user who've updated to 22621.2428 from Windows 10 is experiencing this issue as well, but on my daily PC which I've just updated from 22621.2361 to 22621.2428 doesn't experience this issue. Weird...

**Comment by Amrsatrio** [comment]
This should not happen again in the latest prerelease.
