### ISSUE TITLE
Taskbar (Left/Right) - problems with multi-column (win11)

### ISSUE THREAD

**Issue by avraam-inside** [valinet/ExplorerPatcher#2283]
When the left taskbar expands, the icons expand too, instead of a second row appearing - which is the expected behavior.

2+ row is already embedded in the horizontal taskbar. Could you finish the functionality and do the same behavior for the vertical taskbar, please?

![image](https://github.com/valinet/ExplorerPatcher/assets/52919010/9eaec731-f069-4a0c-8992-9a27ca895540)

P.S.: there are a lot of questions, some examples: 
https://superuser.com/questions/517701/windows-7-side-taskbar-how-to-have-multiple-icon-columns
https://superuser.com/questions/1361189/multi-column-taskbar-when-its-on-left-right-in-windows
https://www.tenforums.com/general-support/107167-multiple-columns-vertical-taskbar-2.html
and etc

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by avraam-inside** [comment]
@pyrates999 

Windows 11 Pro
22H2 (build 22621.2428)

EP: 22621.2361.58.4

Basic settings

**Comment by pyrates999** [comment]
Thank you.

**Comment by avraam-inside** [comment]
You are welcome! 

If you find the time and fix this windows bug, it will be very nice. Thank you too for your attention

**Comment by pyrates999** [comment]
One of the maintainers would look at this.

**Comment by Amrsatrio** [comment]
We don't have plans in modifying the old taskbar even more. The old taskbar's code is already complicated enough to the point it won't fit in this program I think. Sorry.

**Comment by raminmat** [comment]
For anyone landing here from search: I posted a root-cause analysis of the vertical-taskbar overflow behavior (buttons stranded in off-screen phantom columns) plus a working alignment workaround and a small free auto-recovery tool in #3920 (comment): https://github.com/valinet/ExplorerPatcher/issues/3920#issuecomment-4942509567
