### ISSUE TITLE
Dragging taskbar without restarting explorer

### ISSUE THREAD

**Issue by avraam-inside** [valinet/ExplorerPatcher#2284]
I often have to move the panel depending on the current screen or room, and running the application, restarting the explorer every time is tiring.

Could you optimize this nuance, please?

**Comment by Amrsatrio** [comment]
Please state your Windows build version (from Win+R `winver`) and EP version.

**Comment by avraam-inside** [comment]
Windows 11 Pro
22H2 (build 22621.2428)

EP: 22621.2361.58.4

**Comment by Amrsatrio** [comment]
Are you using a multi monitor setup? I don't really get what you mean. You can change the taskbar's position without restarting Explorer by unlocking the taskbar (via right click) and then dragging it.

**Comment by avraam-inside** [comment]
I was misled by this option, I thought that this is done only through the application interface and with the restart of the explorer

![image](https://github.com/valinet/ExplorerPatcher/assets/52919010/dd6fa6ff-be3c-442f-9658-4d660bc1fb3a)

The taskbar is transferred manually, everything works well

Probably you can close it

But the parameter is still misleading, mb should do something with it...

**Comment by Amrsatrio** [comment]
Some day. Just not in my priority. There are a lot more of important matters to finish atm.
