### ISSUE TITLE
Moment 4 22631.2361 Start menu win 10 doesnt work

### ISSUE THREAD

**Issue by mikailreialt** [valinet/ExplorerPatcher#2285]
I just Installed win 11 23H2, when after install it doesnt work on start10 but start11 works. the weird thing is, the taskbar when on 10 mode it works(but not the start menu, only taskbar)...

**Comment by Amrsatrio** [comment]
Please install the latest prerelease. I changed a lot on the symbol loading code therefore we need couple days to test it before promoting to release. Thanks :)

**Comment by mikailreialt** [comment]
@Amrsatrio after pre-release, same issue, for sake i even updated it to 22631.2428..

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.4_acc0131

This prerelease?

**Comment by mikailreialt** [comment]
yes @Amrsatrio

**Comment by Amrsatrio** [comment]
You're welcome :)
