### ISSUE TITLE
Right click with mouse doesn't work

### ISSUE THREAD

**Issue by BeKa65** [valinet/ExplorerPatcher#2289]
Hallo,
I'm new and I hope I can explain clearly what is my problem.
I love the explorer patcher but since a few days I have the problem, that I can't open some context menus with a right click on the mouse, i.e. on the desktop. When I do it, it starts the "windows action sign" but then the whole screen becomes white and after a few seconds all is like before. Also in the explorer the right click doesn't work, same rection, white screen, the explorer colse and nothing happens.
Maybe somebody has a helpfull hint for me.
Thank you in advance.

**Comment by Amrsatrio** [comment]
Please enable the new command bar if you want to use the new context menu. We have no plans yet making the new context menu work with the old command bar.

**Comment by BeKa65** [comment]
Thank you very much.

 

I did the following and it works now.



 

 

Mit freundlichen Grüßen,

Berndt Kautter

 

Tel.: +49 172 7632681

225, Allée Nicolas Greff

57600 Œting

Frankreich

**Comment by Amrsatrio** [comment]
You're welcome. I'm sorry that I have to delete your reply because it contained your address.
