### ISSUE TITLE
Show all toolbars on multiple monitors?

### ISSUE THREAD

**Issue by llnk** [valinet/ExplorerPatcher#2291]
Hello, I am using ExplorerPatcher especially to have the "add new toolbar" option in windows 11.
But on multiple monitors I noticed that the toolbars only show on the primary monitor. Can I show them on all monitors?

I am refereeing to this option:
![image](https://github.com/valinet/ExplorerPatcher/assets/1444881/f61adf71-f839-4506-8450-cb52c7405f14)

**Comment by pyrates999** [comment]
you mean the taskbar that has the start menu on it?

**Comment by nshannon123** [comment]
@llnk The toolbars always showed on the primary monitor only even back on Windows 10 - This would need to be an enhancement/new feature

**Comment by Amrsatrio** [comment]
We have no plans of modifying the Windows 10 taskbar further to support what you wanted. Sorry.

**Comment by llnk** [comment]
ok no problem, at least we do have it on the primary monitor
