### ISSUE TITLE
add the windows 10 search box

### ISSUE THREAD

**Issue by hairybuthole12** [valinet/ExplorerPatcher#2294]
can you please add the windows 10 search box idk my buttons are moved to the side where it is supposed to be. can u pls just add the search box like this to your app, and make it so you can enable it in the settings. also, you cant change it through regular taskbar settings as it doesnt work.
![image](https://github.com/valinet/ExplorerPatcher/assets/131720327/60ad7279-1056-4049-a9e8-aeb0e48c7853)

**Comment by Amrsatrio** [comment]
Never.

**Comment by bcnb99** [comment]
> Never.

false (not really)

**Comment by hairybuthole12** [comment]
why not
