### ISSUE TITLE
Cannot pin programs that are not displayed in Start or Windows Control Panel

### ISSUE THREAD

**Issue by Tartarusome** [valinet/ExplorerPatcher#2298]
And the option "pin tiles to windows 10 start menu from explorer" dissappeared in the latest version of ep

windows version 22621.2428

**Comment by Amrsatrio** [comment]
I have removed that button because I've tested that you can pin shortcuts directly from Explorer. And yes, I tried pinning folders and exe shortcuts to start on your build and it works just fine. What are you trying to pin?

**Comment by Tartarusome** [comment]
I tried to pin some .exe files(not displayed in "apps page") to the win10 start menu,but nothing happened.
And just now,I deleted all files and folders in the two folders below,I can pin those .exe files,or its shortcuts to the "tiles page"again,but that shortcuts still are not displayed in start menu.
C:\Users\tarta\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
C:\ProgramData\Microsoft\Windows\Start Menu\Programs
![1](https://github.com/valinet/ExplorerPatcher/assets/142856268/7089182b-5eb1-4ebf-a3e9-8682d527e7f4)
![2](https://github.com/valinet/ExplorerPatcher/assets/142856268/66e5e86c-7db1-44ff-bd26-62bcac50fbd8)

**Comment by pyrates999** [comment]
Is this what you meant? https://www.elevenforum.com/t/add-or-remove-items-in-all-apps-in-windows-11-start-menu.2023/

**Comment by Tartarusome** [comment]
> Is this what you meant? https://www.elevenforum.com/t/add-or-remove-items-in-all-apps-in-windows-11-start-menu.2023/

Nope. I just emptied the two path, and didn't put new shortcuts in them.But used "pin to start"button in the context menu. 
The result is exactly in the images, shortcuts were successfully pined to tiles page, but not in the app page.

**Comment by pyrates999** [comment]
The 2 paths contain shortcuts to applications you have installed.  One is for your user.  The other is for all users in the system.  I hope you didn't delete any files in there.

There's no pinning here.  You create a shortcut to each applications executable you want to be added to it.

**Comment by Tartarusome** [comment]
> The 2 paths contain shortcuts to applications you have installed. One is for your user. The other is for all users in the system. I hope you didn't delete any files in there.
> 
> There's no pinning here. You create a shortcut to each applications executable you want to be added to it. The shortcut name is what gets shown in the all apps menu.

I surely did that, but anyway, some apps didn't followed the rule. They showed in the folders ,and didn't showed in the apps menu. How can I fix it.

**Comment by pyrates999** [comment]
Try rebooting.

**Comment by Tartarusome** [comment]
> Try rebooting.

I even reseted my computer, the prob is still there.

**Comment by pyrates999** [comment]
Watch this: https://www.youtube.com/watch?v=Sxt8WrtlUno

Part of it includes how to add an application to the all apps menu in the start menu.

**Comment by Tartarusome** [comment]
> Watch this: https://www.youtube.com/watch?v=Sxt8WrtlUno
> 
> Part of it includes how to add an application to the all apps menu in the start menu.

Really thanks! This video is useful indeed.
