### ISSUE TITLE
ExplorerPatcher reporting wrong version

### ISSUE THREAD

**Issue by BigheadSMZ** [valinet/ExplorerPatcher#230]
Not a huge deal, but the current version of explorer patcher is reporting "258" in the build number instead of "282".

![](https://i.imgur.com/2mZoCpQ.png)

**Comment by valinet** [comment]
Not actually an issue. The version reported by EP is its own version. It's usually kept in sync with the latest Windows build so it's easier to figure out on which build that version has been tested. But the 2 can totally get out of sync and that is a valid state, so to speak. Seems I have forgotten to update the version in the latest build. Will fix it in the next one, thanks.
