### ISSUE TITLE
RAM goes up to 100% when opening Windows 10 Start

### ISSUE THREAD

**Issue by Mattem300** [valinet/ExplorerPatcher#2300]
so, I started getting this issue pretty recently, AND IT IS MAD ANNOYING. Every time you open start, the RAM in your computer is literally going to EXPLODE, and I always have to force shutdown my PC to fix this. Anyway, I started using Windows 11 Start again...
Also I'm pretty sure that the Windows 10 taskbar fits pretty well with the Windows 11 Start Menu... (also that is like the only reason why I started using Explorer Patcher, I used it in the past but I was scared it was somehow like going to corrupt the system files...

![image](https://github.com/valinet/ExplorerPatcher/assets/118678848/f61b82cf-55d6-4ff4-bd8e-c4af033dfbd9)

**Comment by Amrsatrio** [comment]
Please state your Windows version from winver.

**Comment by Amrsatrio** [comment]
@roflcopter4 Perhaps can you help me reviewing this code for memory leaks or such? Seems like this mem leak is a first with this particular case.

https://github.com/valinet/ExplorerPatcher/blob/80f11ae4f91b8137fd8de732717405849d2ec04b/ExplorerPatcher/StartMenuSettings.cpp#L99

**Comment by Mattem300** [comment]
> @roflcopter4 Perhaps can you help me reviewing this code for memory leaks or such? Seems like this mem leak is a first with this particular case.
> 
> https://github.com/valinet/ExplorerPatcher/blob/80f11ae4f91b8137fd8de732717405849d2ec04b/ExplorerPatcher/StartMenuSettings.cpp#L99

umm where is that 


> Please state your Windows version from winver. So it memory leaks when you open the old start menu with the old taskbar?

<img width="276" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/118678848/269934e3-b1c4-4802-9e22-04524e809840">

**Comment by Mattem300** [comment]
> Please state your Windows version from winver. So it memory leaks when you open the old start menu with the old taskbar?

also I use the old taskbar to open start.

**Comment by Amrsatrio** [comment]
It's an ancient preview build of Windows 11. Do you have options to update your Windows?

**Comment by Mattem300** [comment]
I am scanning for new updates...

**Comment by Mattem300** [comment]
it is not showing anything new?

**Comment by Mattem300** [comment]
Apparently, I am already in the queue to leave the insider program? 
![image](https://github.com/valinet/ExplorerPatcher/assets/118678848/31c05924-0473-4216-b717-8b156a9949ce)

**Comment by Mattem300** [comment]
Also, why am I in the insider program for like 1 year?

**Comment by Amrsatrio** [comment]
I guess you'd better attempt to download the latest Windows 11 Media Creation Tool and attempt an in place upgrade or if not possible, a clean install. So that you will still get updates and proper support with EP.

**Comment by Mattem300** [comment]
Alright, I'm not sure if my PC is corrupted but this is the second time my PC literally has corrupted Windows installed into it. The first time was when I upgraded to Windows 11, explorer would always just now work, and now Windows Search and Windows Update is corrupted... Is it just the games I mostly install or what???

**Comment by Mattem300** [comment]
> I guess you'd better attempt to download the latest Windows 11 Media Creation Tool and attempt an in place upgrade or if not possible, a clean install. So that you will still get updates and proper support with EP.

Anyway thanks for the advice

**Comment by Amrsatrio** [comment]
And thanks for pointing out that there is a flaw in my code that fixes start menu folders on 22622.2134+. Because Microsoft's build numbering system has been very confusing lately, the code that were made to support newer builds are run on your ancient build therefore causing unexpected issues.

**Comment by pyrates999** [comment]
> Alright, I'm not sure if my PC is corrupted but this is the second time my PC literally has corrupted Windows installed into it. The first time was when I upgraded to Windows 11, explorer would always just now work, and now Windows Search and Windows Update is corrupted... Is it just the games I mostly install or what???

That can point to issues with your hardware if it keeps happening on a regular basis.

Once you have reinstalled windows, you can do the following to repair it:  Please run the following in an elevated command prompt or elevated powershell:

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by Mattem300** [comment]
so I had just in-place upgraded, and I already feel like I got a new computer... bruh

**Comment by Mattem300** [comment]
so FOR SOME REASON THIS STILL HAPPENS EVEN THOUGH I AM ON Windows 11 22H2 build 22621.2428 .....

**Comment by pyrates999** [comment]
Uninstall EP and see if this is still happens.

**Comment by Amrsatrio** [comment]
Calm down. Try setting your Start Menu to Windows 11, and then open it, and then set back to Windows 10. Let me know if it's resolved. I acknowledge that it was my fault for not writing proper code.

**Comment by Amrsatrio** [comment]
Also, if you want to help me fixing this issue, can you export this registry key into a .reg file and send it here? (Try as .txt extension if GitHub doesn't allow)

HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Start

**Comment by Amrsatrio** [comment]
Here's the newly built prerelease that potentially fixes your issue:

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.4_67b7a27

**Comment by Mattem300** [comment]
> Also, if you don't mind, can you export this registry key into a .reg file and send it here? (Try as .txt extension if GitHub doesn't allow)
> 
> HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Start
> 
> Edit: I've built a new prerelease and please try installing it. Otherwise, if it is still exploding, I recommend to try deleting these values in the said registry key.
> 
> ![image](https://user-images.githubusercontent.com/20662640/277101624-b070825c-05d3-462b-89ae-ee7655455293.png)

Does this break the Windows 11 Start or not?

**Comment by Mattem300** [comment]
> Here's the newly built prerelease that potentially fixes your issue:
> 
> https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.4_67b7a27

So I don't know if it is a Driver or Hardware issue but this didn't really fix anything but only made the lag surface after a few minutes of the start opened

**Comment by Mattem300** [comment]
wait it just fixed something
<img width="407" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/118678848/71e98f50-4863-4281-aa33-cb9dae9614df">

**Comment by Mattem300** [comment]
yeah, i am going to restart now to see if that fixed it

**Comment by Amrsatrio** [comment]
> Does this break the Windows 11 Start or not?

If your Windows 10 start data is not corrupted, it will not.

**Comment by Mattem300** [comment]
Just had to manually crash my computer with CTRL+SCROLL-LOCK.... I don't really think that my Windows 10 Start Data is corrupted... Anyway thanks for the advice, maybe the regedit hack will fix it

**Comment by Mattem300** [comment]
> Also, if you don't mind, can you export this registry key into a .reg file and send it here? (Try as .txt extension if GitHub doesn't allow)
> 
> HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Start
> 
> Edit: I've built a new prerelease and please try installing it. Otherwise, if it is still exploding, I recommend to try deleting these values in the said registry key.
> 
> ![image](https://user-images.githubusercontent.com/20662640/277101624-b070825c-05d3-462b-89ae-ee7655455293.png)

<img width="415" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/118678848/ff3e4382-c780-42f4-8f9d-1ea04ce7aa32">

**Comment by Mattem300** [comment]
Here's the screenshot

**Comment by Mattem300** [comment]
So here's the export as a TXT

**Comment by Mattem300** [comment]
<img width="498" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/118678848/204aa28c-75da-4ac3-8656-634977f38e89">
 
 bro

**Comment by Amrsatrio** [comment]
Bingo. `VisiblePlaces` is corrupted. Try deleting that key and that should do.

**Comment by Mattem300** [comment]
he gone 💀
<img width="503" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/118678848/84c18e78-1c78-421d-aa3d-b8101f589103">

**Comment by Amrsatrio** [comment]
Does the RAM usage still explode now?

**Comment by Mattem300** [comment]
it still does

**Comment by Amrsatrio** [comment]
If it still explodes, then your Windows 10 start menu data is corrupted. I suggest to try this:

1. Go to `HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache\DefaultAccount`
2. `CTRL + F` $start.tilegrid$windows.data.curatedtilecollection.tilecollection
3. Delete `Data`

**Comment by Mattem300** [comment]
Well It makes sense that it is corrupted because my last Windows version that was corrupted had the start search not working so it maybe spread from that into Windows Update and then into Start Data

**Comment by Mattem300** [comment]
and*

**Comment by Amrsatrio** [comment]
So yeah try deleting that `DefaultAccount` key and the `VisiblePlaces` value.

**Comment by Mattem300** [comment]
gone again 💀
<img width="97" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/118678848/c84ebd56-8736-4a8e-8424-189850b7ab3f">

**Comment by Amrsatrio** [comment]
Did it fix the new menu?

**Comment by Mattem300** [comment]
one sec

**Comment by Mattem300** [comment]
yoyoyoyoyoyoyoyo NO WAY

**Comment by Mattem300** [comment]
IT GOT FIXED

**Comment by Amrsatrio** [comment]
So it was due to the old start menu data being corrupted. Might be my fault though for writing the code for fixing start menu folders on 22621.2134+ improperly. In that case, I'm really sorry for that.

Anyways, I'm glad to see your issue being resolved 🎉 You can close this issue.

**Comment by Mattem300** [comment]
It is just time to add all the stuff back and it will work as fine!

**Comment by Mattem300** [comment]
also the Windows 11 start still has its data which is good!
<img width="428" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/118678848/e5ead02c-7163-4089-bd4d-c897a31b59db">
