### ISSUE TITLE
Add option to disable notifications pausing auto-hide

### ISSUE THREAD

**Issue by johnch18** [valinet/ExplorerPatcher#2303]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/2302

<div type='discussions-op-text'>

<sup>Originally posted by **johnch18** October 13, 2023</sup>
I get a fair number of notifications from various applications, and they seem to prevent the taskbar from hiding. I'd like it if I could disable this behavior, so that the notifications display and briefly show the taskbar for a few seconds, after which it would hide itself. It would also be nice to be able to configure the time that the taskbar stays visible</div>

**Comment by pyrates999** [comment]
See answer in https://github.com/valinet/ExplorerPatcher/discussions/2302

**Comment by Amrsatrio** [comment]
We're not in the mood of adding new features yet. Please keep new feature requests in discussions.
