### ISSUE TITLE
Get old Explorer design back?

### ISSUE THREAD

**Issue by SpencerComputers** [valinet/ExplorerPatcher#2304]
Please tell me theres some way to rollback from this attrocious new redesign on W11 22H2?

NEW:
![image](https://github.com/valinet/ExplorerPatcher/assets/35679480/0c62ce35-8d40-46f9-9ad3-6ff0acf1d4e3)

OLD:
![image](https://github.com/valinet/ExplorerPatcher/assets/35679480/10f4ece7-dbd5-4d72-912a-074e6af0e679)

**Comment by Amrsatrio** [comment]
No way to do it with EP right now, but you can try disabling this (instead of enabling): https://twitter.com/phantomofearth/status/1661445223598227456?s=46&t=Z6-Pmwr64FlXa-EAez7Ufw

**Comment by SpencerComputers** [comment]
This works, cheers <3
