### ISSUE TITLE
Uninstalled EP, but still getting symbols downloaded message after a Windows update

### ISSUE THREAD

**Issue by WebslingerX** [valinet/ExplorerPatcher#2305]
Hi,

Like the title says, I uninstalled Explorer Patcher a while ago, and I can't find a trace of it anywhere, but after a Windows update I still get te Symbols downloaded for Windows build..... message.
Is this normal Windows 11 behaviour that I never noticed before or did the uninstaller leave something behind in another location?

I tried re-installing and uninstalling again, but that didn't fix it either.

Not a big deal, but I would still like to know what's going on and what I can do to remove this last remaining bit of EP.

Windows 11, version: 22H2 - 22621.2428

**Comment by pyrates999** [comment]
Try downloading the latest release and installing that, then uninstalling it.

Then reboot.

**Comment by WebslingerX** [comment]
Thank you for the response.
Do you have a more specific insight in why this is happening?
Is disabling this downloading of symbols something that the Dev forgot to put into the uninstall process?

It's hard to test if installing - uninstalling (again) would fix it this time as I would have to wait for the next Windows Update that triggers it, that's why I'm asking if it's something I could easily check / change myself. (like a register setting or deleting a certain file)

**Comment by pyrates999** [comment]
No idea, sorry.

**Comment by pyrates999** [comment]
Maybe you have something else installed that requires symbols to be downloaded.

**Comment by pyrates999** [comment]
For others to help, please post windows version and build.  You can find this by running winver.

**Comment by WebslingerX** [comment]
> Maybe you have something else installed that requires symbols to be downloaded.

Well, come to think of it, when I was trying out various things to get W11 the way I wanted it I also installed Windhawk.
I did uninstall that as well, but I didn't check if it might have left something behind.
I don't even know if it uses symbols, but it seems likely that some of the modules do.

**Comment by pyrates999** [comment]
Then I would also try installing windhawk and then uninstalling it.

**Comment by Amrsatrio** [comment]
Did `C:\Windows\dxgi.dll` remain after uninstallation? I can take a look if that happens on you.

**Comment by WebslingerX** [comment]
Thank you both.
I re-installed and uninstalled both EP and Windhawk, checked if dxgi.dll remained after that, it didn't.
Uninstalled the latest security update and re-installed it and no symbol download message after that.

So this seems to have fixed it.
Will close the issue.
