### ISSUE TITLE
EP crashes when right clicking any file

### ISSUE THREAD

**Issue by Dra-goonn** [valinet/ExplorerPatcher#2306]
Explorer crashed every time I try to right click  on any file or jsut right clicking on the desktop. Screen goes black and I have to Ctrl+Alt+Delete to log out and back in again.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Dra-goonn** [comment]
taken care of now, had to reset to default settings and find the video and go thru to make it look like Win 10 again. either i missed a setting or accidentally clicked on a setting that messed everything up. It's all good now

**Comment by pyrates999** [comment]
Please close this then.

**Comment by Dra-goonn** [comment]
done
