### ISSUE TITLE
Explorer stops working after 2nd clock in a Folder

### ISSUE THREAD

**Issue by twingo999** [valinet/ExplorerPatcher#2307]
Explorer stops working after 2nd clock in a Folder and i have to wait app. 15 Sec if it comes back. Any Idea?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by twingo999** [comment]
Hi, the Windows Version is: 22H2 Build 22621.2428

 

Patcher Version is: 22621.2361.58.4

 

Changed: Taskbar Style : Windows 10 (to have the Bar on Top of the screen) & Register as shell extension.

 

Sometimes I got an event as in sreenshot.

 

 

Thank you.

 

Issue is: Click on a folder – no feedback from explorer for approx.. 10 Seconds. Then it works until I close the explorer. With the next open of explorer the same problem. Works fine in other File managers like Total commander etc. 

Von: pyrates999 ***@***.***> 
Gesendet: Sonntag, 15. Oktober 2023 05:09
An: valinet/ExplorerPatcher ***@***.***>
Cc: twingo999 ***@***.***>; Author ***@***.***>
Betreff: Re: [valinet/ExplorerPatcher] Explorer stops working after 2nd clock in a Folder (Issue #2307)

 

Please post windows version and build. You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by pyrates999** [comment]
Disable **Register as shell extension** and restart file explorer.  You shouldn't be enabling that.  Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by twingo999** [comment]
Thank you very much. That seems to be how it works. I'm deeply impressed with how much work you put into documentation as well. Thanks for that, and the support! Greetings Peter – Did a little donation 7H8744628J690225S

 

Von: pyrates999 ***@***.***> 
Gesendet: Sonntag, 15. Oktober 2023 11:00
An: valinet/ExplorerPatcher ***@***.***>
Cc: twingo999 ***@***.***>; Author ***@***.***>
Betreff: Re: [valinet/ExplorerPatcher] Explorer stops working after 2nd clock in a Folder (Issue #2307)

 

Disable Register as shell extension and restart file explorer. You shouldn't be enabling that. Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by pyrates999** [comment]
I did not document that.  So I'll pass that onto the one who did.

**Comment by twingo999** [comment]
No , Keep it for the patcher
----------------------------------------

16.10.2023 00:01:50 pyrates999 ***@***.***>:

**Comment by Amrsatrio** [comment]
Can you post a screen recording?

**Comment by twingo999** [comment]
You mean with the Problem of the file Explorer?
----------------------------------------

17.10.2023 09:05:25 Amr Satrio ***@***.***>:

**Comment by twingo999** [comment]
I Do IT later.
----------------------------------------

17.10.2023 09:10:41 Amr Satrio ***@***.***>:

**Comment by twingo999** [comment]
AT first a Backup... because now IT works fine
----------------------------------------

17.10.2023 09:10:41 Amr Satrio ***@***.***>:

**Comment by Amrsatrio** [comment]
Yeah. It works fine on me, on the same build as yours. That's why I need more details like a screen recording. But if it doesn't bother you anymore, you can close this issue.

**Comment by twingo999** [comment]
Summary: Dont register as a shell Extension, and the prblem ois gone! Thank you!

**Comment by Amrsatrio** [comment]
You're welcome!
