### ISSUE TITLE
Taskbar in windows 10 mode, start search workview icons mouse hover with no action

### ISSUE THREAD

**Issue by jjasoncool** [valinet/ExplorerPatcher#2315]
This is not urgent style issue.
When mouse hover to the icons, they dont change another hover icons.

e.g.
Win10:
![圖片](https://github.com/valinet/ExplorerPatcher/assets/24731867/94a83a86-e78e-46c9-90c9-75482e33746a)
![圖片](https://github.com/valinet/ExplorerPatcher/assets/24731867/f6a0aaab-567a-426b-acdb-e4db8c001f23)

Win11 with ExplorerPatcher (Win10 mode taskbar)
![圖片](https://github.com/valinet/ExplorerPatcher/assets/24731867/184563f7-18be-4208-9eff-4ae10a77bf3e)

**Comment by Amrsatrio** [comment]
What's your windows build version? This doesn't happen on 22621.2428.

**Comment by jjasoncool** [comment]
Version Windows 11 Pro
Version 22H2
Installed on ‎2023/‎05/‎25
OS build 22621.525
Experience Windows Feature Experience Pack 1000.22634.1000.0

**Comment by jjasoncool** [comment]
> What's your windows build version? This doesn't happen on 22621.2428.

Just happen in remote mode, I use in local is normal.
Maybe is remote software issue.

**Comment by Amrsatrio** [comment]
Alright. By the way, I recommend you to update your Windows version as it was released last year.
