### ISSUE TITLE
The space before the icons on taskbar buttons grows as the taskbar becomes crowded

### ISSUE THREAD

**Issue by Anixx** [valinet/ExplorerPatcher#2316]
The space to the left of the icons of taskbar buttons increases as the number of the buttons grows, which makes the labels less visible.

**Comment by pyrates999** [comment]
Please show a screen shot of what you mean.

**Comment by Anixx** [comment]
This space (red rectangle) grows as the taskbar becomes more crowded:

![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/2e95093d-d7ca-4806-9ea1-0267ba6cae83)
