### ISSUE TITLE
Explorer keeps crashing when right clicking

### ISSUE THREAD

**Issue by Parallel00** [valinet/ExplorerPatcher#2317]
Every single time I right click on either File Explorer or even my desktop, Explorer immediately crashes and restarts itself.  I've changed absolutely nothing about my setup.  I am using Windows 11 22H2 (build 22621.2428).

**Comment by Gandalf58** [comment]
I just came here to see about this rather annoying problem.
Even on the keyboard, the context menu call key crashes

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2292
