### ISSUE TITLE
When I right-click on the taskbar, the file manager will restart. How can I solve this problem?

### ISSUE THREAD

**Issue by w20yun** [valinet/ExplorerPatcher#2318]
After the problem occurred, I uninstalled it, but it didn’t seem to be completely uninstalled, so I reinstalled it, and that’s what happened after that.

If I try to reinstall, the computer will display a black screen and I cannot perform any operations. I can only solve it by logging out of the account through the task manager or restarting.

**Comment by Amrsatrio** [comment]
What's your ExplorerPatcher version and your Windows build version? Mine is 22621.2428 and everything works fine.

**Comment by w20yun** [comment]
I don’t know where it is installed, and I haven’t uninstalled it cleanly. Where can I check the version number? Win11 is 22621.2283.

**Comment by Amrsatrio** [comment]
EP drops files here:

C:\Program Files\ExplorerPatcher
C:\Windows\dxgi.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\dxgi.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\wincorlib.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\wincorlib_orig.dll
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\Windows.UI.ShellCommon.pri
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\pris2\Windows.UI.ShellCommon.en-US.pri
C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\dxgi.dll

Also includes the .prev files of respective files.

Try installing this prerelease and see if your problem persists:
https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.4_a57471f

**Comment by w20yun** [comment]
Thank you. Let me try

**Comment by w20yun** [comment]
Do you need to delete several files in safe mode? It seems that they cannot be deleted normally.

**Comment by w20yun** [comment]
It seems that it has not been set up. What should I do now?

**Comment by Amrsatrio** [comment]
In theory after a restart you should be able to shift+delete those files. Otherwise there is something wrong that would be difficult for me to diagnose.

**Comment by w20yun** [comment]
Then I will restart the computer and try to delete it.

**Comment by w20yun** [comment]
Installing the distribution version seems to solve the problem
