### ISSUE TITLE
Border line in  Battery, Sound, and Calendar.

### ISSUE THREAD

**Issue by trefeon** [valinet/ExplorerPatcher#2323]
![image](https://github.com/valinet/ExplorerPatcher/assets/95156714/4e4898f1-5707-4445-a330-cf5281e5fc5d)

**Comment by trefeon** [comment]
How to disable it? it still exist even when disabled ease of access keyboard (make it easir to use keyboard shortcut already uncheck)

**Comment by pyrates999** [comment]
try this: https://answers.microsoft.com/en-us/windows/forum/all/selection-box-on-windows-being-only-a-white-border/4f8deaa3-24ad-4bed-bbca-b26f7f63d4dd

**Comment by pyrates999** [comment]
does it happen when EP is not installed?

**Comment by Amrsatrio** [comment]
This happens in the OOBE volume panel as well, therefore we won't fix bugs like these. Sorry.
