### ISSUE TITLE
Settings App crash

### ISSUE THREAD

**Issue by gauntfield** [valinet/ExplorerPatcher#2326]
Winver 22H2 (OS Build 22621.2428)

ExplorerPatcher 22621.2361.58.4

When trying to open the settings app from the start menu it flashes up and then crashes, I am able to open it in alternative ways 

Intel Arc Control has a few buttons to open monitor settings in the settings app and if launched from Arc Control it opens fine.

event log info

Faulting application name: SystemSettings.exe, version: 10.0.22621.2428, time stamp: 0x3a143f4b
Faulting module name: ExplorerPatcher.amd64.dll, version: 22621.2361.58.4, time stamp: 0x6520704e
Exception code: 0xc0000005
Fault offset: 0x000000000000d208
Faulting process id: 0x0x1424
Faulting application start time: 0x0x1DA030666668B96
Faulting application path: C:\Windows\ImmersiveControlPanel\SystemSettings.exe
Faulting module path: C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
Report Id: 0b9c0d7f-45ec-48ae-af32-d19a52da97d4
Faulting package full name: windows.immersivecontrolpanel_10.0.6.1000_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: microsoft.windows.immersivecontrolpanel

**Comment by Amrsatrio** [comment]
Did you "register EP as shell extension"? Are you using a release or prerelease build of EP?

**Comment by gauntfield** [comment]
Yes it was registered as an shell extension. 

Using the latest release ExplorerPatcher 22621.2361.58.4

I just uninstalled and reinstalled and choose **not** to register shell extension this time and getting the same behavior

trying to narrow it down, just saw the event viewer info and thought it may be something with EP. Could be something else in windows, may try a fresh OS install this weekend.

**Comment by Amrsatrio** [comment]
If you want to uninstall EP, you have to unregister it as shell extension, restart your PC, and then uninstalling it. Then you can reinstall.

Meanwhile, try the latest prerelease build. It doesn't crash the settings app for me, and I'm using the same build as yours with TranslucentTB and OldNewExplorer.

**Comment by pyrates999** [comment]
You should never enable register as a shell extension: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by Amrsatrio** [comment]
So have you tried a fresh OS install? If you have unregistered EP as shell extension, it's certainly other poorly written tweak software that gets injected into the Settings app via the shell extension mechanism.

**Comment by Amrsatrio** [comment]
Anyways I seem to have fixed this issue in 59.1. Closing this issue.
