### ISSUE TITLE
Typing names in the search of start menu doesn't work

### ISSUE THREAD

**Issue by archz2** [valinet/ExplorerPatcher#2327]
I have faced this issue in multiple versions, including the latest updated ones. All of a sudden, (after hours and days of working fine) the search functionality of start menu stops functioning. When type the name of the software I want to open, nothing happens. 
A reboot of my laptop fixes the issue. Is there a permanent solution to this problem?

**Comment by pyrates999** [comment]
try this to rebuild the search index: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/windows-search-performance-issues

This is a known windows 11 issue.

**Comment by Amrsatrio** [comment]
EP does not modify the behavior of the search menu, as of now. If there are issues, it is out of the scope of EP.
