### ISSUE TITLE
User tab not working in Windows 10 Start menu

### ISSUE THREAD

**Issue by pre41** [valinet/ExplorerPatcher#2328]
![20231020_235500](https://github.com/valinet/ExplorerPatcher/assets/148564482/958df0a7-d1f3-4073-95ef-1cb9f019fd4d)

My windows version is 22H2, 22621.2428, EP version is 22621.2361.58.4. I cannot open the user tab in the start menu.

**Comment by pre41** [comment]
> But can you right click tiles? Perhaps try restarting Explorer after couple minutes because it works fine for me, on the same build as yours.

I did

**Comment by pre41** [comment]
> But can you right click tiles? Perhaps try restarting Explorer after couple minutes because it works fine for me, on the same build as yours.

Yes I can right click tiles.
I reinstalled EP, removed EP registries, reset EP settings to default, restarted my computer, restarted explorer 5 times and more. still persists.

**Comment by pre41** [comment]
Maybe it's not just the user tab, my start menu language was changed to English instead of Korean (which is default and the only language in my computer) since the user tab wasn't working. Seems like I'm experiencing the same issue about languages with #1525 .

**Comment by pyrates999** [comment]
Might be related to this: https://github.com/valinet/ExplorerPatcher/issues/1450

**Comment by pre41** [comment]
Seems like it. Is anyone else experiencing this issue, with an another language than English set to default in your Windows?

**Comment by Amrsatrio** [comment]
Probably related to your Windows _edition_ or in other words the language you chose when downloading the WIndows media. My Windows is English US but with Japanese language pack (not edition) therefore my user button in the old start menu is okay.

**Comment by Amrsatrio** [comment]
Nevermind. Confirmed on 23555.1000 and 23560.1000 (Insider Dev). So now maybe it's related to the account being a local account? Anyhow I will take a look at it later.

**Comment by Tourniquet88** [comment]
> Maybe it's not just the user tab, my start menu language was changed to English instead of Korean (which is default and the only language in my computer) since the user tab wasn't working. Seems like I'm experiencing the same issue about languages with #1525 .

Have you tried it with the latest EP version? I wasn't able to repro it with EP 22621.2428.59.1 and Windows 11 22631.2428.

**Comment by pre41** [comment]
> > Maybe it's not just the user tab, my start menu language was changed to English instead of Korean (which is default and the only language in my computer) since the user tab wasn't working. Seems like I'm experiencing the same issue about languages with #1525 .
> 
> Have you tried it with the latest EP version? I wasn't able to repro it with EP 22621.2428.59.1 and Windows 11 22631.2428.

The language was fixed already.

**Comment by pre41** [comment]
> > Maybe it's not just the user tab, my start menu language was changed to English instead of Korean (which is default and the only language in my computer) since the user tab wasn't working. Seems like I'm experiencing the same issue about languages with #1525 .
> 
> Have you tried it with the latest EP version? I wasn't able to repro it with EP 22621.2428.59.1 and Windows 11 22631.2428.

Thanks for telling me! The issue was fixed and it's now working just like before.
![image](https://github.com/valinet/ExplorerPatcher/assets/148564482/b4e1e671-9853-419e-b79a-db734e47a6ce)
