### ISSUE TITLE
Do

### ISSUE THREAD

**Issue by Absolutely565** [valinet/ExplorerPatcher#2330]
Can you make a long context menu for windows 10 and a button to enable the "classic taskbar context menu" in the properties?

**Comment by Amrsatrio** [comment]
Please show us an example of what you mean.

**Comment by kotenok2000** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/8822292/3d3ac3f9-0534-4fb2-85f9-7794a6408c00)

**Comment by Absolutely565** [comment]
Turning this option on is showing the left 22H2 windows 10 context menu, turning it off is now the EP context menu
The image shows the context menu with this option turned off (don't care if it's in Chinese). ![屏幕截图 2023-10-21 191002](https://github.com/valinet/ExplorerPatcher/assets/146397687/b8940f40-476d-4220-b157-764b41b6d3eb)

**Comment by pyrates999** [comment]
> ![image](https://user-images.githubusercontent.com/8822292/277104289-3d3ac3f9-0534-4fb2-85f9-7794a6408c00.png)

I use windhawk for that.  You can find it here: https://windhawk.net

Then install and enable the mods:

- Disable Immersive Context Menus
- Non Immersive Taskbar Context Menu

**Comment by Absolutely565** [comment]
thank you

**Comment by Absolutely565** [comment]
But I don't like the way it looks, can you make it for win10 22H2

**Comment by pyrates999** [comment]
Windhawk also works in windows 10.

**Comment by Absolutely565** [comment]
Don't like the look of him.Can you move win10's taskbar right click menu to ExplorerPacther?

**Comment by pyrates999** [comment]
That's up to the developers then.

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/ea8ee353-9a58-4a48-b370-05eea463cb36)
Disabling this should be enough. But we cannot revert the context menu style completely back to Win10.
