### ISSUE TITLE
Win 11 Taskbar Start panel does not open

### ISSUE THREAD

**Issue by samfourie** [valinet/ExplorerPatcher#2332]
Since installing 22621.2361.58.4  (Upgrading on ‎2023/‎10/‎05) when in Win 11 or Win 10 mode the Start button does not work.  All other links or shortcuts on the taskbar works but the Start button does not open the Windows 11 Menu 
The Win Menu Shortcut button also has no effect

I downgraded back to 22621.2361.58.1 and it worked (without rebooting)
I removed  22621.2361.58.1 and installed 22621.2361.58.4 and it did not work  (without rebooting)

I rebooted - No Sucsess 
I downgraded back to 22621.2361.58.1 and it worked ( after rebooting)
I removed  22621.2361.58.1 rebooted and installed 22621.2361.58.4 and it did not work  (after rebooting again)

The long and short of it is 22621.2361.58.1 WORKS and 22621.2361.58.4 not
Ps....
(I run three SSD drives as OS'es (2 X Windows and 1 X Linux)

I tried this routine on both my Win 11 bootup's and the same result for both!
My Two Windows 11 Versions are not the same ! 
1 is - Windows 11 Pro 22H2
2 is - Tiny Win 11 23H2 (arhive.org)

Same result on both

My specs (for legal version Windows 11 Pro 22H2)

Processor	Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
Installed RAM	16,0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023/‎10/‎05
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

FOOTNOTE --
NO PRE RELEASE VERSIONS WAS USED !
WINDOWS 11 ALL UPDATES DONE BEFORE ATTEMPING TO USE VERSION 22621.2361.58.4

**Comment by pyrates999** [comment]
Windows 10/11 had updates released on Oct 10.  Please install them and then try to install the current release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.4_b157aba

**Comment by Amrsatrio** [comment]
Is that a release version or prerelease? Anyways, update your Windows and install the latest prerelease.

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.4_a57471f

**Comment by samfourie** [comment]
> Windows 10/11 had updates released on Oct 10. Please install them and then try to install the current release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2361.58.4_b157aba

THAT IS THE VERSION THAT HAS THE BUG ! - 22621.2361.58.4
22621.2361.58.1 WORKS !
22621.2361.58.4 DOES NOT WORK !

**Comment by Amrsatrio** [comment]
Please, calm down, and install the latest Windows 11 update on your 1st installation. Your build number SHOULD be 22621.2428 if you have installed all available updates. And use the linked prerelease version. It works on my main PC, and my laptop. Both English (US) editions with language set to Japanese.

If it still crashes please help me trace your issue:
1. Open Event Viewer (eventvwr.exe)
2. Go to Windows Logs > Application
3. Find an Error line whose **Faulting application name** is **StartMenuExperienceHost.exe**
4. Copy the text that I selected into this issue thread:

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/e4a964d0-5dc1-43be-8aeb-62820eb61213)

5. Upload the ep_setup.exe here (rename as PDF) that you used.

Anyways, we do not support modified builds such as Tiny11.

**Comment by AmirFarbodRM** [comment]
Same Problem.
Here The Event Error:
Faulting application name: StartMenuExperienceHost.exe, version: 10.0.22621.2361, time stamp: 0x661ffc6a
Faulting module name: wincorlib_orig.dll, version: 10.0.22621.2215, time stamp: 0x1d1644b4
Exception code: 0xc0000005
Fault offset: 0x0000000000005726
Faulting process id: 0x0x2EC0
Faulting application start time: 0x0x1DA058DFC9BA73D
Faulting application path: C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
Faulting module path: C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\wincorlib_orig.dll
Report Id: 2f7895d2-6520-4dc1-bc02-4faf587a51c0
Faulting package full name: Microsoft.Windows.StartMenuExperienceHost_10.0.22621.2215_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: App

**Comment by Amrsatrio** [comment]
@AmirFarbodRM Thanks for reporting a similar crash. If you rename dxgi.dll into dxgi-.dll and restarting explorer, does the start menu show up?

**Comment by pksiazek** [comment]
I have same problem too.
I renamed dxgi.dll. Menu shows up after this - but in the middle of screen (as original Win11) not as before.

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by Amrsatrio** [comment]
@pksiazek Hi, thanks for reporting as well. Which build of Windows 11 are you on? It would also be great if you can export `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher` and upload the file here.

**Comment by pksiazek** [comment]
Console (after renaming back dxgi.dll).
No additional input after clicking Start

[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.2361.58.4.f0ab2cdb0cc00ced"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.2361.58.4.f0ab2cdb0cc00ced" (valid).
[Updates] Local version obtained from hash is 22622.2361.58.4.
[Updates] No updates are available.
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for unknown OS version 10.0.22621.2500.
[Symbols] Downloading to "C:\Users\micro\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\WINDOWS\system32\twinui.pcshell.dll" ("f3065ef0799612c687f69f939fc616fc")...
[Symbols] Reading symbols...
[Symbols] Windows 10 window switcher style is not available in this build.
[Symbols] Failure in reading symbols for "C:\WINDOWS\system32\twinui.pcshell.dll".
[EnsureXAML] 31 ms.

**Comment by Amrsatrio** [comment]
10.0.22621.2500.... That's a preview build. Are you in an insider channel? But rest assured I'll go ahead and test this out for you.

**Comment by pksiazek** [comment]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher]

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher\StartDocked]
"StartDocked::LauncherFrame::ShowAllApps"=dword:001ecbb4
"StartDocked::LauncherFrame::OnVisibilityChanged"=dword:001eb3c0
"StartDocked::SystemListPolicyProvider::GetMaximumFrequentApps"=dword:00004af0
"StartDocked::StartSizingFrame::StartSizingFrame"=dword:001c0d60

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher\StartUI]
"StartUI::SystemListPolicyProvider::GetMaximumFrequentApps"=dword:000365f0

**Comment by Amrsatrio** [comment]
Yeah. Certainly try the prerelease version. That should fix your issues.

**Comment by pksiazek** [comment]
After installing preview version Start menu is showing again.
Thanks for help :)

**Comment by Amrsatrio** [comment]
Since OP hasn't replied again, and that the start menu works fine with latest EP and latest 22H2 (22621.2506), I will close this issue.
