### ISSUE TITLE
Crash after crash... is it time to say goodbye to ExplorerPatcher?

### ISSUE THREAD

**Issue by ansorre** [valinet/ExplorerPatcher#2334]
For several months now, with every Windows update we have had to jump through hoops to restore ExplorerPatcher to at least acceptable functioning. Each time the stunts to be done are more complex, and the attempts more numerous. This is on two totally different machines, so it's not a problem of a specific instance. This post is to understand how many people find it so problematic to run ExplorerPatcher, so that I can decide if it's the product that should be abandoned or if I'm doing something fundamental wrong, despite the many hours of work I put in every time to make it work .

**Comment by Poopooracoocoo** [comment]
R.e. the title and sort of sensationalism. It's not a "product" and it's not crashing for me and for many others. I don't mean to invalidate the fact you're experiencing crashes. Definitely make sure EP is up to date as it's somewhat recently received changes that should reduce crashes by reducing its reliance on Windows symbols that change due to Windows updates.

**Comment by pyrates999** [comment]
This is a rant and not reporting any actual bug, therefore should be closed.

**Comment by Amrsatrio** [comment]
Of course I test my "stunts" on a varying amount of builds before they can go live. But still, it ultimately depends on what the user has done to their systems that somehow will break the "stunts". I know what I'm doing with my 5 year old installation that began on 17763 and currently on 22621.2428.

ExplorerPatcher isn't going away, I'm here to continue making and improving the stunts as long as they work.

**Comment by ansorre** [comment]
I'm sorry if this seemed like a rant or if it doesn't contain specific bugs, especially sorry if anyone was offended because it wasn't my intention to offend anyone. Obviously I only have words of thanks for those who created and continue to create this excellent product by offering it for free. The problem is that even describing the bug is very complicated. What simply happens to me is that after any Windows update when I restart the machine everything seems to start fine, and yet any window I try to open in Explorer, explorer.exe crashes. The only other oddity besides this is that even if you completely uninstall EplorerPatcher, explorer.exe continues to crash. The only solution is to perform a restore point to before the last Windows update. Yes obviously I continually update ExplorerPatcher, I read all the issues I find here on. Obviously I try everything, but this is the situation. I also asked myself "why are there so few new issues open?", perhaps I was wrong but I replied that perhaps it is because people abandon the use of this software without saying anything, because perhaps they have understood after months that there is nothing to be done, and since I was doing exactly that too I said: no, let me give it one last try and I wrote. That was the goal, not to make anyone sorry.

**Comment by Amrsatrio** [comment]
> even if you completely uninstall EplorerPatcher, explorer.exe continues to crash. The only solution is to perform a restore point to before the last Windows update.

Did C:\Windows\dxgi.dll remain after uninstallation?

**Comment by pyrates999** [comment]
After uninstalling EP and confirming that C:\Windows\dxgi.dll is no longer there.  I would try to repair your windows install.

To do so, please run the following in an elevated command prompt or elevated powershell:

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by D3cedut0** [comment]
Hi guys I faced the same problem last week, (a lot of crash repeatly and every restart the notification by explorer patched that windows licence is expired...but isn't true)
uninstalled, tried a chkdisk but after 2 restarts it happen again.
I will try the suggested procedure removing the file in C:/ .
Is there also any key in regedit to remove?  Thanks

**Comment by pyrates999** [comment]
> Hi guys I faced the same problem last week, (a lot of crash repeatly and every restart the notification by explorer patcheer that windows licence is expired...but isn't true) uninstalled, tried a chkdisk but after 2 restarts it happen again. I will try the suggested procedure removing the file in C:/ . Is there also any key in regedit to remove? Thanks

If windows says your license has expired, you installed a trial version and haven't installed a key for it in time, therefore it expired.

**Comment by D3cedut0** [comment]
Not Windows, an explorer patcher notify say that. Windows in panel control show an active licence. 

Later I try to remove it as you suggested, and I check if the issue is the same I faced last week.  Thanks

**Comment by pyrates999** [comment]
EP doesn't send notifications if windows has expired.

**Comment by D3cedut0** [comment]
You are right, I misunderstood. What I seen it was only the app crashing, in the while before every crash,  a popup arrived in the notify bar,  instead of the 
the blue warning of the licence expiring (that didn't appear) now uninstalled the tool i see again the notification but this time correctly , in the blue warning (central rectangle) created by Windows.
 The unistalling didn't left any file dxgi.dll in C/Windows , I found only dxgi.prev. Ok for me

**Comment by Amrsatrio** [comment]
I will close this issue since we haven't heard anything back from OP regarding the crashing situation.
