### ISSUE TITLE
Context menu for applications pinned to taskbar (Win11 style) do not show MRU

### ISSUE THREAD

**Issue by turbodb** [valinet/ExplorerPatcher#2338]
On Windows 10, when apps like Excel, Word, etc. were pinned to the taskbar, one could right click on them to bring up a menu that would allow for various non-default launch behaviors.

One of these - at least for MS Office applications, but also for other apps as I recall - was to show recently edited documents. Then, one of those recent documents could be selected from the menu, thereby starting the application and opening the document.

This would save several clicks, as the user would not need to wait for the app to open, then navigate to File | Open, and find the document.

With ExplorerPatcher, the only options on the right-click menu of an application pinned to the taskbar are

- <app name> - launches the app
- Unpin from taskbar - does that

Images of the two behaviors, below.

Win10 - 
<img width="479" alt="Win10" src="https://github.com/valinet/ExplorerPatcher/assets/33507137/5c34f51f-ef73-4119-b6f7-0971528ec41b">

Win 11 w/ExplorerPatcher
![image](https://github.com/valinet/ExplorerPatcher/assets/33507137/6b41702e-2078-4d79-878e-75b28d69e578)

**Comment by Amrsatrio** [comment]
It works fine, on 22621.2361 and 22621.2428. Do you have the "jump lists" option enabled in Start settings?

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/8fb5ab10-d450-4f42-82a6-d486bd9f5a04)

**Comment by turbodb** [comment]
You're right (of course). I had no idea that option existed, as it's always been enabled for me in Win10 and was not enabled (for some reason) on upgrading to Win11.

Thanks for bearing with me. Much appreciated.
