### ISSUE TITLE
no blue hovering over start button

### ISSUE THREAD

**Issue by Rezy774** [valinet/ExplorerPatcher#2340]

**Comment by Rezy774** [comment]
any fix ?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Rezy774** [comment]
22621.2428 is my version and my settings are default exept windows 10 start menu and weather and combine thing

**Comment by Rezy774** [comment]
when i hover over the start button it turns gray not blue

**Comment by Rezy774** [comment]
explorerpatcher is latest build

**Comment by Jazzzed** [comment]
The color of the Start button is controlled by the Accent Colors found in Settings>Personalization>Colors. If you want a blue button, choose the blue accent. A red accent will give you a red button when hovering, etc. There is also a setting there to turn off accent colors on your start menu and taskbar if you just want the button colored.

**Comment by pyrates999** [comment]
Please post explorer patcher version.  Don't just say it's the latest version.

**Comment by Rezy774** [comment]
heres a video

**Comment by Rezy774** [comment]
https://github.com/valinet/ExplorerPatcher/assets/128003302/68fe473c-1437-4f6f-bb25-c2a119bf8000

**Comment by pyrates999** [comment]
That doesn't show the version of EP that you installed.

**Comment by Amrsatrio** [comment]
You seem to have modified more than just installing EP. In that case, it is out of EP's scope. The Win10 taskbar start button is colored when being hovered, on fresh installs and on my 5 year installation (that began on 18362).
