### ISSUE TITLE
Windows 10 style start menu option reverted after Windows 11 update

### ISSUE THREAD

**Issue by That-One-Tiny-Whoop-guy** [valinet/ExplorerPatcher#2345]
I've had ExplorerPatch for around 48 hours now, and it worked flawlessly at first. Then my PC updated Windows 11 last night and when I woke up, the start menu had reverted from Windows 10 style back to Windows 11 style even though the setting is still set to Windows 10. I've attached a screenshot of the issue. If this is merely user error or if I need to provide any further information, please let me know.

Windows version: Windows 11 22H2, build 10.0.22621.2428
ExplorerPatch version: 22621.2361.58.4
![Screenshot (2)](https://github.com/valinet/ExplorerPatcher/assets/64749148/71e7ebaf-c060-453f-b6f8-2f8fd5e08a57)

**Comment by Amrsatrio** [comment]
What if you reinstall EP? I'd assume your PC performed a feature upgrade from 21H2/22000 automatically.

**Comment by Amrsatrio** [comment]
After every feature update yeah. But not after every monthly cumulative updates.
