### ISSUE TITLE
Windows 11 start and search is centered aligned if I use Windows 10 taskbar

### ISSUE THREAD

**Issue by rounk-ctrl** [valinet/ExplorerPatcher#2356]
as the title says.
happens only with windows 10 taskbar

**Comment by Amrsatrio** [comment]
Please tell us your `winver`. As far as I know, it happens on last 3 Insider Dev builds.

**Comment by rounk-ctrl** [comment]
im on 23565

**Comment by Amrsatrio** [comment]
Yeah. Known issue. I will fix this one day.

**Comment by Amrsatrio** [comment]
Formulating the fix right now, just for you.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/36a3f74d-198b-4225-8b2d-514614f873f1)

**Comment by Amrsatrio** [comment]
Fixed the issue, partially. You have to restart Explorer after changing start menu alignment.

A new prerelease is being built. Once it's ready, you can install it and let me know how it goes.

**Comment by Amrsatrio** [comment]
I just discovered an issue that once the screen resolution is changed, or in some cases right after logon, Explorer crashes. Reopening this until it is fixed.

![IMG_5386](https://github.com/valinet/ExplorerPatcher/assets/20662640/5ff4e7ac-42c4-46fc-afc5-78771b90d7fa)

**Comment by Amrsatrio** [comment]
Should be completely fixed and crashless.
