### ISSUE TITLE
Windows 10 Startmenu does not open on 2nd display

### ISSUE THREAD

**Issue by Tourniquet88** [valinet/ExplorerPatcher#2368]
Windows version: 22631.2428 (Release)
EP version: 22621.2428.59.1
Other customization software used: None
Start menu Style: Windows 10

As the title suggests: The Windows 10 Startmenu does not open on the second display. I tried it with the Windows 10 and Windows 11 Taskbar. I also tried it with both the Full Screen option and without it.

**Comment by pyrates999** [comment]
Can you show the settings you changed EP?

**Comment by Tourniquet88** [comment]
Ha ha never mind. I had it set on the "default" option. However the EP default differs from the Windows default option.

On Windows you can open the Startmenu / Startscreen by default on the 2nd monitor. With EP it is set by default to open it on the Primary Monitor. Which can be a problem.

I would like to suggest to change the default to "Monitor on which the cursor is on".

**Comment by pyrates999** [comment]
This should be moved to a discussion then as it is a request for a new feature.

**Comment by Tourniquet88** [comment]
Okay I opened up a discussion: https://github.com/valinet/ExplorerPatcher/discussions/2381

**Comment by pyrates999** [comment]
Thank you.  Now please close this one.
