### ISSUE TITLE
Internet/wifi & battery taskbar icons not responding; other icons work fine

### ISSUE THREAD

**Issue by tony-aw** [valinet/ExplorerPatcher#2371]
So the Internet/wifi & battery taskbar icons are not responding when clicking on them. The other icons work fine. So I can still click on the settings icon (the cog-like icon), and get to the list of wifi/internetconnections and battery status from there. But not directly from the corresponding icons. I suspect it is caused by Explorer Patcher, but I'm not 100% sure.

**Comment by aldeniangman** [comment]
Same. my icons are not showing.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1934
