### ISSUE TITLE
Release 22621.2428.59.1 detected as virus

### ISSUE THREAD

**Issue by E-Unit** [valinet/ExplorerPatcher#2374]
My virus protection (Webroot; managed by admin) detected this release as a threat and removed it. Previous releases have not caused any issues. Although I'm sure I'd be able to download and install it with protection turned off, I haven't tried it just yet. I wanted to bring it to your attention.

**Comment by Amrsatrio** [comment]
Unfortunately there is nothing we can do to evade these detections, especially 3rd party ones. They tend to be way more aggressive than MS defender. Such detections are always false positive and if one doubts if EP is a virus or not the source code is there for people to check.

Have a read: https://github.com/valinet/ExplorerPatcher/wiki/Antivirus-false-positives
