### ISSUE TITLE
Show Windows Build Issue

### ISSUE THREAD

**Issue by mwschramm77** [valinet/ExplorerPatcher#2375]
Hi,

When I choose to 'Show Windows Build Info on Desktop', if works fine on my primary monitor (Windows Monitor 1), but the text is hidden behind the task bars at the bottom of Monitors 2 and 3.

![Monitor_2_Show_Windows_Build_Info](https://github.com/valinet/ExplorerPatcher/assets/57922114/9b4f33cd-ce6a-4f07-a815-8557bf5af833)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by pyrates999** [comment]
Please close this as you have posted it in discussions: https://github.com/valinet/ExplorerPatcher/discussions/2376
