### ISSUE TITLE
Does not stay running, does not show in taskabr

### ISSUE THREAD

**Issue by julerobb1** [valinet/ExplorerPatcher#2377]
As the title states, i cannot make it stay running and exploerer crashes. I don't have any other modifcations installed, and this is the message i get. 
<img width="297" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/25588072/f62ff44d-c61c-4d9b-9972-75b005789e90">
What do i need to do to fix this issue? i just want the have my classic explorer from win 10 back. I have uninstalled a number of times, i just installed win 11 today about three hours ago.  I am running windows 11 pro for workstations. Version 22H2, Build # of Windows : 22621.2506

**Comment by julerobb1** [comment]
Theres no icon or properties to click.

**Comment by julerobb1** [comment]
Update : for some reason, renaming the setup file to "ep_setup (2)" fixed the issue, and it then prompted brought up the UAC screen, i clicked yes and voila i now have a win 10 taskbar back.

**Comment by Amrsatrio** [comment]
Well the solution is to install the updates available for you. We make updates to this software pretty often to prepare for future updates.

**Comment by pyrates999** [comment]
> As the title states, i cannot make it stay running and exploerer crashes. I don't have any other modifcations installed, and this is the message i get. <img alt="image" width="297" src="https://user-images.githubusercontent.com/25588072/279228527-f62ff44d-c61c-4d9b-9972-75b005789e90.png"> What do i need to do to fix this issue? i just want the have my classic explorer from win 10 back. I have uninstalled a number of times, i just installed win 11 today about three hours ago. I am running windows 11 pro for workstations. Version 22H2, Build # of Windows : 22621.2506

That is a preview update.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by julerobb1** [comment]
I also deleted Windows Defender completely.

**Comment by pyrates999** [comment]
I would not be removing windows defender.  It is there for a reason.

You may need to repair your windows install.  Please run the following in an elevated command prompt or elevated powershell:

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by julerobb1** [comment]
I have other antivirus software I use, and defender was taking too much ram and CPU, and preventing the  machine from sleeping. I didnt delete the firewall obviously as that's part of the OS. It also just slowed down the machine. 
 
 
 No errors found. 
 
 came back to the macine today, and the symbols magivally reappeared after restarting explorer via the properties windows. 
 
 
 
 
 On an secondary note, i have noted the "7" style for battery looks a bit more like windows vista, and doesnt apply to the battery in the taskbar, except on click. is it possible to have the aero scheme from 7 imported into explorer patcher?

**Comment by julerobb1** [comment]
on yet another note, how do i make the taskbar not have the window labels, and just the icons? Also, explorer is missing the entire sidebar after running the remove rounded corners from valinet. ill open an issue on that, just to keep things on track

**Comment by Amrsatrio** [comment]
Not in a short time frame, and you should not expect a lot out of that. Also, check "combine taskbar icons on primary taskbar" in EP properties.

**Comment by pyrates999** [comment]
windows defender is usually not active if you have another antivirus software installed.

**Comment by julerobb1** [comment]
did a few driver updates yesterday, win 11 start menu has returned, explorer patcher has no effect on start menu itself at the moment. 
![image](https://github.com/valinet/ExplorerPatcher/assets/25588072/235f92c2-f623-4b2d-99e4-7606fbe433f0)

**Comment by pyrates999** [comment]
what cpu and how much ram does your computer have if I may ask?  And what antivirus are you running that would cause your whole computer to slow down?

**Comment by julerobb1** [comment]
1165 G7, 16 GB and windows defender hogs ram (Antimalware service executable)

**Comment by pyrates999** [comment]
You didn't tell me what antivirus you're using.  You just said windows defender.

I checked back, and windows 11 22621.2506 is a preview update: https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4

You should uninstall it or you can try installing prerelease versions of EP.

I would also check in task manager what applications are using all of your ram.

**Comment by Amrsatrio** [comment]
> win 11 start menu has returned
Can you reinstall EP to restore EP's files into the system's start menu files?

**Comment by julerobb1** [comment]
#> You didn't tell me what antivirus you're using. You just said windows defender.
> 
> I checked back, and windows 11 22621.2506 is a preview update: https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4
> 
> You should uninstall it or you can try installing prerelease versions of EP.
> 
> I would also check in task manager what applications are using all of your ram.

I am not using antivirus. 

I reinstalled EP and all is nornal , minus the fact in dark mode, the text is black an unreadable in file explorer. 
![image](https://github.com/valinet/ExplorerPatcher/assets/25588072/b553928b-ef6f-4465-b2e3-4a5f8076b6cd)
It's readable in light mode.

**Comment by pyrates999** [comment]
Now reinstall windows defender: https://www.lifewire.com/reinstall-windows-defender-in-windows-11-5546960

**Comment by Amrsatrio** [comment]
Go to the advanced section of EP properties and disable the checkbox that says SysListView32.

**Comment by julerobb1** [comment]
#> You didn't tell me what antivirus you're using. You just said windows defender.
> 
> I checked back, and windows 11 22621.2506 is a preview update: https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4
> 
> You should uninstall it or you can try installing prerelease versions of EP.
> 
> I would also check in task manager what applications are using all of your ram.

I am not using any AV. 

Reinstall helped, but now dark mode has a weird bug where the text is dark too making virtually unreadable without jacking up the brightness to and then flash banging myself whenever i swtich to something such as edge or chromium, which is light mode only, despite there being "Dark mode" .

**Comment by julerobb1** [comment]
> #> You didn't tell me what antivirus you're using. You just said windows defender.
> 
> > I checked back, and windows 11 22621.2506 is a preview update: https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4
> > You should uninstall it or you can try installing prerelease versions of EP.
> > I would also check in task manager what applications are using all of your ram.
> 
> I am not using any AV.
> 
> Reinstall helped, but now dark mode has a weird bug where the text is dark too making virtually unreadable without jacking up the brightness to and then flash banging myself whenever i switch to something such as edge or chromium, which is light mode only, despite there being "Dark mode" .

I got rid of windows Defender because it hogged resources, and doesn't do any good until you're already infected.

**Comment by Avatar007z** [comment]
> Go to the advanced section of EP properties and disable the checkbox that says SysListView32.

@Amrsatrio Do you know how to manually change this outside of EP? Unfortunately, the new update of the company antivirus now blocks all ep setup files and the files it deploys, so I am unable to get to the EP properties to uncheck the checkbox, so my File explorer and some open and save dialog boxes are now stuck with black text on black background :( 
I need to be able to fix this outside of EP.

I posted similar question [here (issue 316)](https://github.com/valinet/ExplorerPatcher/issues/316)  as well.

**Comment by pyrates999** [comment]
> > Go to the advanced section of EP properties and disable the checkbox that says SysListView32.
> 
> [@Amrsatrio](https://github.com/Amrsatrio) Do you know how to manually change this outside of EP? Unfortunately, the new update of the company antivirus now blocks all ep setup files and the files it deploys, so I am unable to get to the EP properties to uncheck the checkbox, so my File explorer and some open and save dialog boxes are now stuck with black text on black background :( I need to be able to fix this outside of EP.
> 
> I posted similar question [here (issue 316)](https://github.com/valinet/ExplorerPatcher/issues/316) as well.

try this: https://winclassic.net/thread/126/make-windows-explorer-listview-control?page=1#scrollTo=15261

**Comment by Avatar007z** [comment]
This partially worked. I have some of the text return to normal but other is still dark on dark... 
The research continues.

**Comment by pyrates999** [comment]
If the taskbar and start menu shows dark text still:

Open up EP Properties application, go to advanced, and disable **classic theme mitigations**

Then click on **Restart File Explorer** in bottom left corner.

discussed further here: https://github.com/valinet/ExplorerPatcher/issues/3457

**Comment by Avatar007z** [comment]
Fully deleting the key that the disabler reg file from the winclassic.net forum thread just modifies, solved the issue for me.
So, just as reference for anyone who searches in the future. The solution for me was to delete this key:
HKEY_CLASSES_ROOT\CLSID\{1eeb5b5a-06fb-4732-96b3-975c0194eb39}\
In addition you might want to delete this one as well:
HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{1eeb5b5a-06fb-4732-96b3-975c0194eb39}\

Thanks for pointing me in the right direction to find that key! @pyrates999

**Comment by pyrates999** [comment]
you're welcome :)
