### ISSUE TITLE
Explorer crashes on right click on Windows 11 22h2 build 22621.2506

### ISSUE THREAD

**Issue by rikka0w0** [valinet/ExplorerPatcher#2380]
OS: Windows 11 22h2 build 22621.2506

When the Win11 tab UI is disabled, the Win11-style context menu no longer works, only the classic context menu option works.

It is on a fresh installation of Win11 and ExplorerPatcher.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218
