### ISSUE TITLE
Fixing menu bar on Windows 11 moment update

### ISSUE THREAD

**Issue by LightSlighter25** [valinet/ExplorerPatcher#2383]
Can a fixing Menu Bar on Windows 11 with moment update?
Because with new File Explorer with tab is mostly hide and bug after I set explorer to Windows 7 Command Bar, I was check and uncheck "Menu Bar" but is mostly hide, whereas is not uncheck.

Do you can fix it for next project?

**Comment by Amrsatrio** [comment]
OP is referring to the menu bar in Win7 command bar, which OP wants to always show instead of having to press left alt to summon it.

**Comment by pyrates999** [comment]
Try OldNewExplorer instead.

**Comment by Amrsatrio** [comment]
Is it fixed with the latest prerelease? It should work up to build 23570.

**Comment by Amrsatrio** [comment]
Closing this issue because it has been fixed in the latest prerelease. Tested on 22621.2361 but should be the case with all builds up to 23570.
