### ISSUE TITLE
Conflict with Start11 V2.0.2

### ISSUE THREAD

**Issue by mkvGuy** [valinet/ExplorerPatcher#2385]
There is a conflict with stardocks  Start11 V2.0.2 in that both  Start11 V2.0.2 and explorerpatcher slow down a lot when trying to configure

Let me know if you need debug files or other

**Comment by Amrsatrio** [comment]
I don't want to pay for Start11 just to fix conflicts. Anyways, does this happen with older EP versions such as 22621.1992 with the respective Windows version?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by ctrlcmdshft** [comment]
> I don't want to pay for Start11 just to fix conflicts. Anyways, does this happen with older EP versions such as 22621.1992 with the respective Windows version?

ill purchase a copy of start 11 v2 for you if you want to tackle a fix. and there is also a trial available here https://www.stardock.com/products/start11/

**Comment by Firedoge1** [comment]
不要同时安装多个修改任务栏或开始菜单的程序。Do not install multiple programs at the same time that modify the taskbar or Start menu.

**Comment by Amrsatrio** [comment]
Hi, is this issue still present with the latest release (64.1)?

**Comment by ctrlcmdshft** [comment]
> Hi, is this issue still present with the latest release (64.1)?

no issues here currently

**Comment by Amrsatrio** [comment]
Please feel free to repoen at any time if crashes still happen with Start11. @milesproper2293 can confirm thet Start11 can coexist with EP without crashes. I have fixed the crash related to the language switcher patch which conflicted with Start11 as seen in a GH issue from months ago.
