### ISSUE TITLE
VLC Crashes when using ExplorerPatcher

### ISSUE THREAD

**Issue by randallajohnson** [valinet/ExplorerPatcher#2390]
VLC will crash most of the time when opening. Every 20 or so times it opens. The crashes point to ExplorerPatcher:

Event 1001, Windows Error Reporting:
Fault bucket 1577136152432908815, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: vlc.exe
P2: 3.0.19.0
P3: a6d0a6c0
P4: ExplorerPatcher.amd64.dll
P5: 22621.2361.58.4
P6: 6520704e
P7: c00000fd
P8: 000000000001c00f
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e4cad8c2-eda7-49f7-94ff-18483367c3fd.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f2a040a2-57f3-4c4d-bd29-ae49d2717374.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0a283943-39ab-4e78-8938-e3934f51c9e1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e4ad9dca-cf32-4759-848d-2e272d3decac.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f61cd22e-a861-4279-af0d-818a870c0585.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_vlc.exe_2b24dd6dd3e3f0c87ca4d59e7be8869c7d6ef2b1_db627b7b_307d920f-a882-47e8-88a8-78aed83b01e5

Analysis symbol: 
Rechecking for solution: 0
Report Id: f954a001-57ad-47d5-8a9c-aa51331a8bac
Report Status: 268435456
Hashed bucket: 36724ff6c971816245e31cf980309a0f
Cab Guid: 0

Event 1000, Application Error
Faulting application name: vlc.exe, version: 3.0.19.0, time stamp: 0xa6d0a6c0
Faulting module name: ExplorerPatcher.amd64.dll, version: 22621.2361.58.4, time stamp: 0x6520704e
Exception code: 0xc00000fd
Fault offset: 0x000000000001c00f
Faulting process id: 0x5e70
Faulting application start time: 0x01da0dd2ea66ce11
Faulting application path: C:\Program Files\VideoLAN\VLC\vlc.exe
Faulting module path: C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
Report Id: f954a001-57ad-47d5-8a9c-aa51331a8bac
Faulting package full name: 
Faulting package-relative application ID: 

WER Contents:
Version=1
EventType=APPCRASH
EventTime=133434338610082087
ReportType=2
Consent=1
UploadTime=133434338613782762
ReportStatus=268435456
ReportIdentifier=307d920f-a882-47e8-88a8-78aed83b01e5
IntegratorReportIdentifier=f954a001-57ad-47d5-8a9c-aa51331a8bac
Wow64Host=34404
NsAppName=vlc.exe
OriginalFilename=vlc.exe
AppSessionGuid=00005e70-0001-0085-11ce-66ead20dda01
TargetAppId=W:00060db90c880dcc59f4b5f21b1512d4534600000904!0000d515303cbca3a8ae7a0463fecd418d81b314e650!vlc.exe
TargetAppVer=2058//09//08:06:27:12!fc365!vlc.exe
BootId=4294967295
ServiceSplit=3201028360
TargetAsId=1519
UserImpactVector=808452912
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=36724ff6c971816245e31cf980309a0f
Response.BucketTable=4
Response.LegacyBucketId=1577136152432908815
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=vlc.exe
Sig[1].Name=Application Version
Sig[1].Value=3.0.19.0
Sig[2].Name=Application Timestamp
Sig[2].Value=a6d0a6c0
Sig[3].Name=Fault Module Name
Sig[3].Value=ExplorerPatcher.amd64.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=22621.2361.58.4
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=6520704e
Sig[6].Name=Exception Code
Sig[6].Value=c00000fd
Sig[7].Name=Exception Offset
Sig[7].Value=000000000001c00f
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.22000.2.0.0.768.101
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=c953
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=c953b720e79f6352c7258dee1cde72a3
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=4e70
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=4e702163d34fc06d681a3b04703cd71d
UI[2]=C:\Program Files\VideoLAN\VLC\vlc.exe
LoadedModule[0]=C:\Program Files\VideoLAN\VLC\vlc.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\Windows\SYSTEM32\AcGenral.DLL
LoadedModule[6]=C:\Windows\System32\msvcrt.dll
LoadedModule[7]=C:\Windows\System32\sechost.dll
LoadedModule[8]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[9]=C:\Windows\System32\USER32.dll
LoadedModule[10]=C:\Windows\System32\win32u.dll
LoadedModule[11]=C:\Windows\System32\GDI32.dll
LoadedModule[12]=C:\Windows\System32\gdi32full.dll
LoadedModule[13]=C:\Windows\System32\msvcp_win.dll
LoadedModule[14]=C:\Windows\System32\ucrtbase.dll
LoadedModule[15]=C:\Windows\System32\ole32.dll
LoadedModule[16]=C:\Windows\System32\combase.dll
LoadedModule[17]=C:\Windows\System32\RPCRT4.dll
LoadedModule[18]=C:\Windows\System32\SHELL32.dll
LoadedModule[19]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[20]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[21]=C:\Windows\SYSTEM32\MPR.dll
LoadedModule[22]=C:\Windows\SYSTEM32\SspiCli.dll
LoadedModule[23]=C:\Windows\System32\IMM32.DLL
LoadedModule[24]=C:\Program Files\VideoLAN\VLC\libvlc.dll
LoadedModule[25]=C:\Windows\SYSTEM32\WININET.dll
LoadedModule[26]=C:\Program Files\VideoLAN\VLC\libvlccore.dll
LoadedModule[27]=C:\Windows\System32\WS2_32.dll
LoadedModule[28]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[29]=C:\Windows\system32\rsaenh.dll
LoadedModule[30]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[31]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[32]=C:\Windows\System32\shcore.dll
LoadedModule[33]=C:\Windows\SYSTEM32\windows.storage.dll
LoadedModule[34]=C:\Windows\SYSTEM32\wintypes.dll
LoadedModule[35]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[36]=C:\Windows\SYSTEM32\TextShaping.dll
LoadedModule[37]=C:\Windows\system32\uxtheme.dll
LoadedModule[38]=C:\Windows\System32\MSCTF.dll
LoadedModule[39]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_9d947278b86cc467\comctl32.dll
LoadedModule[40]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[41]=C:\Windows\SYSTEM32\textinputframework.dll
LoadedModule[42]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[43]=C:\Windows\SYSTEM32\CoreMessaging.dll
LoadedModule[44]=C:\Windows\SYSTEM32\CoreUIComponents.dll
LoadedModule[45]=C:\Windows\SYSTEM32\dbghelp.dll
LoadedModule[46]=C:\Windows\SYSTEM32\dbgcore.DLL
LoadedModule[47]=C:\Windows\SYSTEM32\winmm.dll
LoadedModule[48]=C:\Program Files\VideoLAN\VLC\plugins\logger\libfile_logger_plugin.dll
LoadedModule[49]=C:\Program Files\VideoLAN\VLC\plugins\logger\libconsole_logger_plugin.dll
LoadedModule[50]=C:\Program Files\VideoLAN\VLC\plugins\keystore\libmemory_keystore_plugin.dll
LoadedModule[51]=C:\Program Files\VideoLAN\VLC\plugins\access\liblibbluray_plugin.dll
LoadedModule[52]=C:\Program Files\VideoLAN\VLC\plugins\access\libdvdnav_plugin.dll
LoadedModule[53]=C:\Program Files\VideoLAN\VLC\plugins\access\libvdr_plugin.dll
LoadedModule[54]=C:\Program Files\VideoLAN\VLC\plugins\access\libfilesystem_plugin.dll
LoadedModule[55]=C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libprefetch_plugin.dll
LoadedModule[56]=C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libcache_read_plugin.dll
LoadedModule[57]=C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libskiptags_plugin.dll
LoadedModule[58]=C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libhds_plugin.dll
LoadedModule[59]=C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libadf_plugin.dll
LoadedModule[60]=C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libinflate_plugin.dll
LoadedModule[61]=C:\Program Files\VideoLAN\VLC\plugins\demux\libplaylist_plugin.dll
LoadedModule[62]=C:\Program Files\VideoLAN\VLC\plugins\lua\liblua_plugin.dll
LoadedModule[63]=C:\Program Files\VideoLAN\VLC\plugins\stream_extractor\libarchive_plugin.dll
LoadedModule[64]=C:\Program Files\VideoLAN\VLC\plugins\stream_filter\librecord_plugin.dll
LoadedModule[65]=C:\Program Files\VideoLAN\VLC\plugins\demux\libdirectory_demux_plugin.dll
LoadedModule[66]=C:\Program Files\VideoLAN\VLC\plugins\meta_engine\libtaglib_plugin.dll
LoadedModule[67]=C:\Program Files\VideoLAN\VLC\plugins\misc\libxml_plugin.dll
LoadedModule[68]=C:\Program Files\VideoLAN\VLC\plugins\audio_output\libmmdevice_plugin.dll
LoadedModule[69]=C:\Windows\System32\clbcatq.dll
LoadedModule[70]=C:\Windows\System32\MMDevApi.dll
LoadedModule[71]=C:\Windows\System32\DEVOBJ.dll
LoadedModule[72]=C:\Windows\SYSTEM32\cfgmgr32.dll
LoadedModule[73]=C:\Windows\SYSTEM32\AUDIOSES.DLL
LoadedModule[74]=C:\Windows\System32\Windows.UI.dll
LoadedModule[75]=C:\Program Files\VideoLAN\VLC\plugins\control\libwin_msg_plugin.dll
LoadedModule[76]=C:\Program Files\VideoLAN\VLC\plugins\control\libhotkeys_plugin.dll
LoadedModule[77]=C:\Program Files\VideoLAN\VLC\plugins\control\libwin_hotkeys_plugin.dll
LoadedModule[78]=C:\Program Files\VideoLAN\VLC\plugins\gui\libqt_plugin.dll
LoadedModule[79]=C:\Windows\system32\dataexchange.dll
LoadedModule[80]=C:\Windows\system32\twinapi.appcore.dll
LoadedModule[81]=C:\Windows\system32\explorerframe.dll
LoadedModule[82]=C:\Program Files\VideoLAN\VLC\plugins\services_discovery\libmediadirs_plugin.dll
LoadedModule[83]=C:\Program Files\VideoLAN\VLC\plugins\services_discovery\libmicrodns_plugin.dll
LoadedModule[84]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[85]=C:\Program Files\VideoLAN\VLC\plugins\services_discovery\libpodcast_plugin.dll
LoadedModule[86]=C:\Program Files\VideoLAN\VLC\plugins\services_discovery\libsap_plugin.dll
LoadedModule[87]=C:\Program Files\VideoLAN\VLC\plugins\services_discovery\libupnp_plugin.dll
LoadedModule[88]=C:\Program Files\VideoLAN\VLC\plugins\services_discovery\libwindrive_plugin.dll
LoadedModule[89]=C:\Windows\SYSTEM32\WindowsCodecs.dll
LoadedModule[90]=C:\Program Files\VideoLAN\VLC\plugins\demux\libmp4_plugin.dll
LoadedModule[91]=C:\Program Files\VideoLAN\VLC\plugins\demux\libavi_plugin.dll
LoadedModule[92]=C:\Program Files\VideoLAN\VLC\plugins\demux\libasf_plugin.dll
LoadedModule[93]=C:\Program Files\VideoLAN\VLC\plugins\demux\libes_plugin.dll
LoadedModule[94]=C:\Program Files\VideoLAN\VLC\plugins\demux\libflacsys_plugin.dll
LoadedModule[95]=C:\Program Files\VideoLAN\VLC\plugins\demux\libtta_plugin.dll
LoadedModule[96]=C:\Program Files\VideoLAN\VLC\plugins\demux\libnuv_plugin.dll
LoadedModule[97]=C:\Program Files\VideoLAN\VLC\plugins\demux\libmpc_plugin.dll
LoadedModule[98]=C:\Program Files\VideoLAN\VLC\plugins\demux\libwav_plugin.dll
LoadedModule[99]=C:\Program Files\VideoLAN\VLC\plugins\demux\libcaf_plugin.dll
LoadedModule[100]=C:\Program Files\VideoLAN\VLC\plugins\demux\libsid_plugin.dll
LoadedModule[101]=C:\Program Files\VideoLAN\VLC\plugins\demux\libmkv_plugin.dll
LoadedModule[102]=C:\Program Files\VideoLAN\VLC\plugins\demux\libogg_plugin.dll
LoadedModule[103]=C:\Program Files\VideoLAN\VLC\plugins\demux\libdiracsys_plugin.dll
LoadedModule[104]=C:\Program Files\VideoLAN\VLC\plugins\access\liblive555_plugin.dll
LoadedModule[105]=C:\Program Files\VideoLAN\VLC\plugins\demux\libsmf_plugin.dll
LoadedModule[106]=C:\Program Files\VideoLAN\VLC\plugins\demux\libadaptive_plugin.dll
LoadedModule[107]=C:\Program Files\VideoLAN\VLC\plugins\codec\libwebvtt_plugin.dll
LoadedModule[108]=C:\Program Files\VideoLAN\VLC\plugins\codec\libttml_plugin.dll
LoadedModule[109]=C:\Program Files\VideoLAN\VLC\plugins\demux\libvoc_plugin.dll
LoadedModule[110]=C:\Program Files\VideoLAN\VLC\plugins\demux\libgme_plugin.dll
LoadedModule[111]=C:\Program Files\VideoLAN\VLC\plugins\demux\librawvid_plugin.dll
LoadedModule[112]=C:\Program Files\VideoLAN\VLC\plugins\demux\libpva_plugin.dll
LoadedModule[113]=C:\Program Files\VideoLAN\VLC\plugins\demux\libimage_plugin.dll
LoadedModule[114]=C:\Program Files\VideoLAN\VLC\plugins\demux\libts_plugin.dll
LoadedModule[115]=C:\Program Files\VideoLAN\VLC\plugins\demux\libaiff_plugin.dll
LoadedModule[116]=C:\Program Files\VideoLAN\VLC\plugins\demux\libmod_plugin.dll
LoadedModule[117]=C:\Program Files\VideoLAN\VLC\plugins\meta_engine\libfolder_plugin.dll
LoadedModule[118]=C:\Windows\SYSTEM32\policymanager.dll
LoadedModule[119]=C:\Windows\SYSTEM32\msvcp110_win.dll
LoadedModule[120]=C:\Windows\System32\p9np.dll
LoadedModule[121]=C:\Windows\System32\drprov.dll
LoadedModule[122]=C:\Windows\System32\ntlanman.dll
LoadedModule[123]=C:\Windows\System32\davclnt.dll
LoadedModule[124]=C:\Windows\System32\WINSTA.dll
LoadedModule[125]=C:\Windows\System32\wkscli.dll
LoadedModule[126]=C:\Windows\SYSTEM32\cscapi.dll
LoadedModule[127]=C:\Windows\System32\netutils.dll
LoadedModule[128]=C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
LoadedModule[129]=C:\Windows\System32\COMDLG32.dll
LoadedModule[130]=C:\Windows\System32\PSAPI.DLL
LoadedModule[131]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[132]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22000.2003_none_4c4fc4c1c574dc79\gdiplus.dll
LoadedModule[133]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[134]=C:\Windows\SYSTEM32\PROPSYS.dll
LoadedModule[135]=C:\Windows\SYSTEM32\RstrtMgr.DLL
LoadedModule[136]=C:\Windows\SYSTEM32\OLEACC.dll
LoadedModule[137]=C:\Windows\SYSTEM32\ncrypt.dll
LoadedModule[138]=C:\Windows\SYSTEM32\BCRYPT.DLL
LoadedModule[139]=C:\Windows\SYSTEM32\NTASN1.dll
LoadedModule[140]=C:\Windows\SYSTEM32\Windows.UI.FileExplorer.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22000
OsInfo[3].Key=ubr
OsInfo[3].Value=2538
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=101
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222387736
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22000.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32577
OsInfo[19].Key=svolsz
OsInfo[19].Value=930
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=210604
OsInfo[22].Key=bldtm
OsInfo[22].Value=1628
OsInfo[23].Key=bldbrch
OsInfo[23].Value=co_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22000.2538.amd64fre.co_release.210604-1628
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Core
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=fconid
OsInfo[34].Value=19638787,0,2,0;25704915,1,2,1;34508795,0,2,0;35825666,0,1,1;37474955,0,1,1;37609034,0,1,0;37801696,0,1,1;37837060,0,1,1;37926348,0,1,0;38406949,0,1,0;38651681,0,1,1;39263329,1,2,0;39319950,0,2,0;39545181,1,2,0;39645403,0,1,1;39909691,0,2,1;40025975,0,1,0;40325239,0,1,1;40741162,0,2,1;40984526,0,1,0;40997837,0,1,1;41172767,0,1,0;41217122,0,2,1;41342071,0,1,1;42621370,0,2,1;42676171,0,2,1;42870786,0,2,1;43754025,0,2,1;43882373,0,2,1;44047927,0,2,1;44171630,0,2,1;44173337,0,1,1;44191982,0,2,1;44255354,0,2,1;44309843,0,2,1;44310074,0,2,1;44469385,0,2,1;44595946,0,2,1;44608279,0,2,1;44612805,0,2,1;44757028,0,2,1;44770519,0,2,1;44784664,0,2,1;44889433,0,2,1;44970661,0,2,1;44976542,0,2,1;44986715,0,2,1;44986778,0,2,1;44986802,0,2,1;44987689,0,2,1;45026700,0,2,1;45047952,0,2,1;45048083,0,2,1;45113578,0,2,1;45121754,0,2,1;45126150,0,2,1;45185354,0,2,0;45231502,0,2,1;45233630,0,2,1;45250404,0,2,1;45250511,0,2,1;45276658,0,2,1;45279760,0,2,1;45416041,0,2,1;46077170,0,2,1;46570133,0,2,1;46613606,0,2,1
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=VLC media player
AppPath=C:\Program Files\VideoLAN\VLC\vlc.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=A02CE19DDF21843D86C714E282B11399
MetadataHash=-276229573

**Comment by Amrsatrio** [comment]
Try disabling "register as shell extension" in EP properties and then File Explorer. I'm not sure what's causing these shell extension crashes...

**Comment by Amrsatrio** [comment]
Please update your EP and then the shell extension system should work again.
