### ISSUE TITLE
Inconsistent taskbar and tray menus appearance when "Skin taskbar and tray popup menus" is disabled

### ISSUE THREAD

**Issue by dimmskii** [valinet/ExplorerPatcher#2391]
![image](https://github.com/valinet/ExplorerPatcher/assets/4108751/4b9df11c-8788-4052-a3fc-3966912c5861)

Winver in screenshot.

**Comment by pyrates999** [comment]
You're running an out of date version from 8th August 2023.  Please install windows update excluding any preview updates.

**Comment by Amrsatrio** [comment]
<img width="334" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/412678cb-29a2-4f3a-a409-ac56426e09fd">

Yeah, there is an issue with disabling the immersive context menus here on Win11 too.

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. Note that if you have other tweak software like 7++ Taskbar Tweaker this _may_ stay broken.

**Comment by dimmskii** [comment]
No, it is not fixed as of latest cumulative patch 22H2 (Nov I believe. This isn't a preview build either; symbols failed to download)

![image](https://github.com/valinet/ExplorerPatcher/assets/4108751/e8f3d9a9-475f-43da-89aa-1f7f4c6aa883)

**Comment by dimmskii** [comment]
> You're running an out of date version of windows 10 from 8th August 2023. Please install windows update excluding any preview updates.

Microsoft fed alert.
