### ISSUE TITLE
Please add the ability to pin applications to secondary monitor taskbar.

### ISSUE THREAD

**Issue by Ilc-Ilia-Developer** [valinet/ExplorerPatcher#2394]
Could you please make a way to pin applications to not only the primary monitor's taskbar but to any secondary monitor taskbar please.

**Comment by pyrates999** [comment]
First Microsoft has to provide a way to specify which taskbar to pin applications to, in the code.  If they do, then yes.  If they don't, then no.

**Comment by Amrsatrio** [comment]
We have no plans of further modifying the taskbar to support what you wanted. Sorry.
