### ISSUE TITLE
Taskbar icon isn't centered

### ISSUE THREAD

**Issue by Ross2750** [valinet/ExplorerPatcher#2395]
The taskbar icon when taskbar location is set to left or right the taskbar icon is not centered
![image](https://github.com/valinet/ExplorerPatcher/assets/122451270/c0c7bf54-ceb7-475d-9960-c4ed2471b17a)

**Comment by pyrates999** [comment]
It is centered actually.

**Comment by Ross2750** [comment]
no it's not
![image](https://github.com/valinet/ExplorerPatcher/assets/122451270/cff9a5bc-9683-443e-a8a9-3ef6b027bc99)

**Comment by pyrates999** [comment]
prove it.
