### ISSUE TITLE
Updated taskbar context menus

### ISSUE THREAD

**Issue by ZeldrexK0DE** [valinet/ExplorerPatcher#2397]
Is it possible to have an menu like this from Startisback 
I know using both isnt recommended but i really miss the functionality this provides alongside quick access to file locatoins
like for example osu only allows unpinning instead of showing other options and some pinned programs show nothing at all. that issue is spread over a lot of custom shortcuts or programs on the defualt taskbar with EP installed.
![image](https://github.com/valinet/ExplorerPatcher/assets/83987610/ec91146c-3d8a-4499-a21e-c97842ea1d4b)
![image](https://github.com/valinet/ExplorerPatcher/assets/83987610/92afe001-d358-48e8-ad13-86abbe188275)

**Comment by pyrates999** [comment]
If startisback has it, then you should keep using that instead.

**Comment by ZeldrexK0DE** [comment]
> If startisback has it, then you should keep using that instead.

theres no way EP can intergrate something like this?

**Comment by Amrsatrio** [comment]
Perhaps check the "Jump lists" setting in your Start settings. I can use what you meant just fine.

<img width="321" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/0411d07a-d6a5-4f75-82b9-1e7d1d031181">
