### ISSUE TITLE
No network icon on latest pre release 

### ISSUE THREAD

**Issue by ZeldrexK0DE** [valinet/ExplorerPatcher#2398]
https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2428.59.1_ac268b1
Has no network icon at all 
![image](https://github.com/valinet/ExplorerPatcher/assets/83987610/1f1b8c60-12c5-4e75-85a3-e615411b4c0b)

**Comment by pyrates999** [comment]
Check in the settings app to be sure you have set the network icon to be shown.  It has an option to show or hide it.

![image](https://github.com/valinet/ExplorerPatcher/assets/106135298/cec4b164-8cef-477d-aa24-aae4cbe72b2f)

**Comment by ZeldrexK0DE** [comment]
> Check in the settings app to be sure you have set the network icon to be shown. It has an option to show or hide it.
> 
> ![image](https://user-images.githubusercontent.com/106135298/280499486-cec4b164-8cef-477d-aa24-aae4cbe72b2f.png)
> 
> And please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application.

The toggle still doesnt show in the task bar
![image](https://github.com/valinet/ExplorerPatcher/assets/83987610/703da386-dcf4-463e-b42c-661bb0714466)

**Comment by pyrates999** [comment]
Your windows version is incomplete.  Please check what winver shows you.

You can also try setting it to show all icons in the system tray then.

**Comment by ZeldrexK0DE** [comment]
> Your windows version is incomplete. Please check what winver shows you.
> 
> You can also try setting it to show all icons in the system tray then.

![image](https://github.com/valinet/ExplorerPatcher/assets/83987610/39bbf305-9ba1-4273-a901-3fbea1d06c0a)

**Comment by ZeldrexK0DE** [comment]
> > Your windows version is incomplete. Please check what winver shows you.
> > You can also try setting it to show all icons in the system tray then.
> 
> ![image](https://user-images.githubusercontent.com/83987610/280531323-39bbf305-9ba1-4273-a901-3fbea1d06c0a.png)

setting all icons also doesnt show it

**Comment by pyrates999** [comment]
Please show a screen shot after you set it to show all icons in the system tray.

![image](https://github.com/valinet/ExplorerPatcher/assets/106135298/ea06adc3-4ad0-40b6-8711-bb0676d647c6)

**Comment by ZeldrexK0DE** [comment]
> Please show a screen shot after you set it to show all icons in the system tray.
> 
> ![image](https://user-images.githubusercontent.com/106135298/280558226-ea06adc3-4ad0-40b6-8711-bb0676d647c6.png)

sadly my taskbar doesnt load at all with just explorerpatcher installed
![image](https://github.com/valinet/ExplorerPatcher/assets/83987610/c64ea1a9-10b0-4fa6-b7c7-ca3a3e592048)
 though like i said before the setting was already on (icon shows cuz SaB is installed doesnt on ExplorerPatcher)

**Comment by pyrates999** [comment]
Try this.  Go to Run, type in services.msc and hit enter. Then make sure **Network List Services** is set to **Automatic**, and then start the service, reboot.

**Comment by Amrsatrio** [comment]
If your taskbar does not load at all with just EP enabled, then that means you have customized your system so much to the point that there is something out of our expectations. Closing this issue since this isn't a supported scenario. Sorry.
