### ISSUE TITLE
Windows 11 23H2 update breaks start menu

### ISSUE THREAD

**Issue by tbcam88** [valinet/ExplorerPatcher#2399]
Installing the 23H2 update renders the start menu completely empty (aside from any Microsoft apps you may still have installed).

![Untitled](https://github.com/valinet/ExplorerPatcher/assets/19891537/cab0c919-952a-4331-a706-323816fd3585)

[https://www.xda-developers.com/microsoft-windows-11-start-menu-bug/](url)

ExplorerPatcher even gets a mention in the above article where M$ refuse to address the problem - personally, I'd wear this like a badge of honour! 😄

Anyways, it'd be ideal if Valinet could perhaps confirm a fix will be in the works at some stage. Long live EP! 👌

**Comment by p-bogi-ba** [comment]
I installed yesterday 23H2 and I have no issue. But before the update I updated ExplorerPatcher to 22621.2428.59.1.

**Comment by tbcam88** [comment]
> I installed yesterday 23H2 and I have no issue. But before the update I updated ExplorerPatcher to 22621.2428.59.1.

I've now tested a second time with the latest EP update and all is indeed well. Thanks for your contribution, Sir! 😎

**Comment by tbcam88** [comment]
> I installed yesterday 23H2 and I have no issue. But before the update I updated ExplorerPatcher to 22621.2428.59.1.

I've now tested a second time with the latest EP update and all is indeed well. Thanks for your contribution, Sir! 😎
