### ISSUE TITLE
Crash / constant reloading

### ISSUE THREAD

**Issue by djamadeus** [valinet/ExplorerPatcher#2404]
after last windows update my system kept crashing/reloading explorer all the time. After already having re-installed windows I found out in the threads here that it might have very likely been Explorer Patcher. there I wanted to ask, in case this ever happens again:
could you provide a reg-script that uninstalls EP (or just prevents it from loading)?
so without working desktop it can be run via new task in task manager or so?

BTW; love the tool otherwise :)

**Comment by pyrates999** [comment]
If EP crashes 3 times, it shows an error message that windows then loads without EP.  From there you can uninstall it using the normal method.

![image](https://github.com/valinet/ExplorerPatcher/assets/106135298/b7cd7712-f5b9-471c-8028-78cdcb52cb2b)

**Comment by Amrsatrio** [comment]
Please let me know about the Windows build number you're on right now, among with other tweak software you have installed right now.

I strive my best to provide crash-free experiences on latest release versions but there are still the slightest chances of crashing especially when other tweak software is installed, such as Wallpaper Engine and Open Shell/Classic Shell.

**Comment by djamadeus** [comment]
Thx for the tip. I was indeed on old version, which also didn't notify me about new releases. And since it worked so flawless seamlessly I forgot it existed^^ until that patch. That crash detection in new version is an awesome Idea!!

**Comment by djamadeus** [comment]
I can't give you the build number anymore since I already re-installed everything, Sry. But new version works fine so far.
