### ISSUE TITLE
 Can I put a shortcut to a folder on the start menu tile by ExplorerPatcher

### ISSUE THREAD

**Issue by limit4ever** [valinet/ExplorerPatcher#2417]
win10的磁贴可以把文件夹的快捷方式放在C:\ProgramData\Microsoft\Windows\Start Menu\Programs目录下就能添加文件夹了，不知道explorerpatcher可不可以实现

**Comment by Amrsatrio** [comment]
Please rewrite your issue in English so that we all can understand clearly.

**Comment by limit4ever** [comment]
Win10 tiles can put the shortcut of the folder in the C:\ProgramData\Microsoft\Windows\Start Menu\Programs directory to add the folder. I don’t know if explorerpatcher can implement it.

**Comment by pyrates999** [comment]
Win10 tiles.  Is that an application?  Can you link to it?

**Comment by WangTooNaive** [comment]
> Win10 tiles. Is that an application? Can you link to it?

He/She means tiles in win10 start menu. I think he/she wants to add folder shortcuts to startmenu as it does in win10

**Comment by pyrates999** [comment]
Do you mean adding folders under applications list to the windows 11 start menu?

**Comment by limit4ever** [comment]
> Win10 tiles. Is that an application? Can you link to it?Win10 磁贴。这是一个应用程序吗？你能链接到它吗？

What I mean is the tile function in the start menu of win10 system. Can I put a shortcut to a folder on the start menu tile by ExplorerPatcher?I apologize for not expressing myself clearly.

**Comment by limit4ever** [comment]
> Do you mean adding folders under applications list to the windows 11 start menu?您的意思是将应用程序列表下的文件夹添加到 Windows 11 开始菜单吗？

Yes, that's correct. I'm looking to add shortcuts for folders to the tiles on the Windows 11 Start Menu for easy access.

**Comment by limit4ever** [comment]
> > Win10 tiles. Is that an application? Can you link to it?Win10 磁贴。这是一个应用程序吗？你能链接到它吗？
> 
> He/She means tiles in win10 start menu. I think he/she wants to add folder shortcuts to startmenu as it does in win10他/她是指 win10 开始菜单中的磁贴。我认为他/她想像在 win10 中一样将文件夹快捷方式添加到开始菜单

Thank you for clarifying. That's exactly what I meant.

**Comment by pyrates999** [comment]
Try this: https://www.makeuseof.com/windows-11-taskbar-pin-almost-anything/

**Comment by Firedoge1** [comment]
亲测可以
