### ISSUE TITLE
Taskbar on windows 11 goes black when changed Windows 10 style

### ISSUE THREAD

**Issue by maharaji1984** [valinet/ExplorerPatcher#2419]
![Screenshot 2023-11-10 065117](https://github.com/valinet/ExplorerPatcher/assets/150419104/e8aab72a-7cc6-4c14-a1a4-d341bdf02443)

Windows 11 Enterprise 
22621 220506-1250
Explorer patch : 22621 2428 5.9.1

Taskbar when has been changed as Taskbar/Taskbar Style/Windows10/ Restart Explorer and taskbar goes black as attached.
I dont know if its a known issue but just wanted to share.

**Comment by Amrsatrio** [comment]
Please disable this:
<img width="487" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/60fefc58-5beb-4388-8c02-f01c3b452d5d">
