### ISSUE TITLE
Windows 11 start menu shows instead of the windows 10.

### ISSUE THREAD

**Issue by ChoPsyer** [valinet/ExplorerPatcher#2425]
Everytime I hit the windows key or click on the windows logo it shows the windows 11 start menu when it's set to windows 10. The version of windows is Windows 11 23H2 25977.1000 Canary. 

https://github.com/valinet/ExplorerPatcher/assets/150528754/0b17992b-df13-4be7-8be3-58d60f233045

What can I do?

**Comment by Amrsatrio** [comment]
A lot of things such as the Win10 start menu and Win10 taskbar system tray have been nuked from Canary. We're now very well aware of these issues. If you want to use them please downgrade to another build than Canary, Dev is okay. Sorry about that.

**Comment by ChoPsyer** [comment]
> A lot of things such as the Win10 start menu and Win10 taskbar system tray have been nuked from Canary. We're now very well aware of these issues. If you want to use them please downgrade to another build than Canary, Dev is okay. Sorry about that.

But I dont want to lose all my files just to downgrade

**Comment by Amrsatrio** [comment]
Y
