### ISSUE TITLE
New Features in Latest EP 2506.60.1 are buggy

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#2429]
Firstly, I appreciate the Developer that he implemented mica and use of gallery with old address bar. But these are currently buggy. After applying (for both settings to work properly) we have to change the theme from L -to- D or vice versa. Wihout that, they seems to not match with current theme.

https://file.io/zVeaZxI7ljw8

**Comment by pyrates999** [comment]
Please confirm the following:

So this works:

1. set settings to be in light mode
2. in EP properties application, go to **File Explorer** and set **Control Interface** to **windows 11 command bar (default)**
3. click on **Restart File Explorer**
4. open up **This PC** on desktop
5. command bar in file explorer matches system light and dark mode setting
6. repeat this with settings set to dark mode

This does not work:

1. set settings to be in light mode
2. in EP properties application, go to **File Explorer** and set **Control Interface** to **windows 11 command bar (classic address bar)**
3. click on **Restart File Explorer**
4. open up **This PC** on desktop
5. command bar in file explorer shows dark mode setting
7. while keeping file explorer open, open up settings app and change to dark mode, then light mode
8. file explorer changes command bar to now be light mode

This does not work:

1. set settings to be in light mode
2. in EP properties application, go to **File Explorer** and set **Control Interface** to **windows 7 command bar**
3. click on **Restart File Explorer**
4. open up **This PC** on desktop
5. command bar in file explorer shows dark mode setting
6. while keeping file explorer open, open up settings app and change to dark mode, then light mode
7. file explorer changes command bar to now be light mode

I noticed that you didn't test the **Control Interface** to **windows 10 ribbon**.  Is that working here?

**Comment by pyrates999** [comment]
Also, please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

**Comment by Vipin2003** [comment]
> Also, please post windows version and build. You can find this by running winver. And I'll assume you meant the EP version as 22621.2506.60.1.

Ya...winner. is 2506. Ribbon UI also has same behaviour

**Comment by Amrsatrio** [comment]
Thanks for reporting. I might have missed something as I wasn't able to wait till I committed everything so I could sleep 😂😂😂

**Comment by Vipin2003** [comment]
Can't it be possible for you to extend the mica for address bar in win11 command bar too...like you did with win7 command bar. Just Asking

**Comment by Amrsatrio** [comment]
I don't know how the method works. It's skidded from SAB and I'd rather not get people to create more GitHub issues.

**Comment by Amrsatrio** [comment]
Check DIscord. I might drop you my local EP build to try to find out the issue.

**Comment by Amrsatrio** [comment]
Fixed.
