### ISSUE TITLE
Bug in Windows File Explorer - Windows 11 23H2 (22635)

### ISSUE THREAD

**Issue by Karell2013** [valinet/ExplorerPatcher#2431]
![image](https://github.com/valinet/ExplorerPatcher/assets/100191384/fa6892f9-4af4-47b2-b641-891107c3b9b0)
Hello, after the last update of explorer patcher, the window bar turned black, the same thing happens to the previous design of the Windows 11 file explorer but at the same time my PC slows down when using the Windows one as well. 7.

**Comment by Amrsatrio** [comment]
Let's troubleshoot your issue. Does disabling "Hide search bar completely" work?

**Comment by Amrsatrio** [comment]
Fixed.
