### ISSUE TITLE
Want ExplorerPatcher on Canary builds

### ISSUE THREAD

**Issue by Saswat2005** [valinet/ExplorerPatcher#2436]
ExplorerPatcher gave us the ability to make Windows 11 customized to Windows 10 with this feature, compatible with the current builds and the insider builds like the dev, beta, and release versions. I need ExplorerPatcher on the Canary build, in which I am running build 25992 of Windows 11.

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.
