### ISSUE TITLE
How Does the Control icon on the taskbar be removed ?  

### ISSUE THREAD

**Issue by Jerryhash** [valinet/ExplorerPatcher#244]
How Does the Control icon on the taskbar be removed ?   See attached screenshot.
![Control](https://user-images.githubusercontent.com/93473348/139581473-eb29701b-22da-4089-8924-4c528ce448e1.png)

**Comment by valinet** [comment]
Please, please, please, I don't know how many times or in what way to ask, please read a bit about the recommendations before posting here. Also, please read the README thoughtfully.

First of all, this is not an issue, so it does not belong here. Second of all, if it belongs to discussions, it only does so if it has not been asked already in the exact same form a couple of times, for example: https://github.com/valinet/ExplorerPatcher/discussions/222. Third of all, EP already has an option for hiding that, it's in the "System tray" section. That "thing there you described is the control center button, and EP clearly has an option for hiding that, as I said.

Closing this as it is not, by any stretch of the imagination, an issue.

Thanks
