### ISSUE TITLE
After clicking on "Customize notification area icon" on ExplorerPatcher Properties, it does not redirect to that page when ExplorerPatcher is installed on Windows latest Germanium OS (#47257192)

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#2442]
Windows 11 Germanium OS
ExplorerPacther: 22621.2506.60.1

**Repro Steps:**
1.Deploy the latest OS 
2.Perform windows and store updates 
3.Install the application from vendor site 
4.Launch the Properties (Explorer Patcher)
5.Taskbar > click on “Customizer notification area icon”
6.Observe 

Expected Result: 
Should be able to redirect to the “Customizer notification area icon” folder
-
Actual Result:
Can’t redirect to the “Customizer notification area icon” folder

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/discussions/2363

**Comment by Michellehdr** [comment]
@Amrsatrio this issue is no the same as https://github.com/valinet/ExplorerPatcher/discussions/2363. Can you take a look? Thanks!

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by devwolf1** [comment]
@Amrsatrio this is same as #2363 as its trying to open a control panel page for the old systray that isnt supported
