### ISSUE TITLE
"Chevron, Ethernet, Sound, Date & Time and Notification" icons are missing from Taskbar when ExplorerPatcher is installed on Windows latest Germanium OS (#47257188)

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#2443]
Windows 11: latest Germanium OS
ExplorerPatcher: 22621.2506.60.1
**Repro Steps:**
1.Deploy the latest OS.
2.Perform windows and store updates.
3.Install the application from vendor site. 
4.Observe the taskbar on bottom right corner.

Expected Result:
Options like Shevron, Ethernet, Sound, Settings, Date & Time and Notifications icons are missing

Actual Result:
All option should appear in the taskbar

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/discussions/2363
