### ISSUE TITLE
[Request] Pressing the sound button in the system tray opens the Win11 layout

### ISSUE THREAD

**Issue by Archilyte** [valinet/ExplorerPatcher#2448]
I wanted to request this because the new layout is actually pretty cool now, it even has the right click menu built-in. It's accessed just like the WIn11 WI-FI layout

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by Archilyte** [comment]
[aight](https://github.com/valinet/ExplorerPatcher/discussions/2454)
