### ISSUE TITLE
bug : Classic Menu bar appears in all explorer interfaces

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#2451]
Classic menu bar appears in explorer without doing anything. If we restart or reopen explorer and leave it as it is, then the menu bar appears and attach with that instance. After opening new explorer or creating new tab, it vanishes in new tab but again leaving that tab also for 5 min, makes the menu bar reappear.

![image](https://github.com/valinet/ExplorerPatcher/assets/93650504/0c532f05-b175-4fff-a579-31d8b45afac5)

**Comment by Amrsatrio** [comment]
Well you are using OldNewExplorer or something else, check its settings as well as always show menu bar or something in folder options. Even though I do not experience this on my main PC this is out of EP's scope 🤷
