### ISSUE TITLE
Icon for "Safely Remove Hardware and Eject Media" is always hidden, even though I have the icon turned on "Show"

### ISSUE THREAD

**Issue by rustydanny** [valinet/ExplorerPatcher#2452]
![settings](https://github.com/valinet/ExplorerPatcher/assets/145377653/1ca85390-ed81-463d-bff3-ec7905649224)
![taskbar](https://github.com/valinet/ExplorerPatcher/assets/145377653/2d94a556-04c5-4963-850e-6d139c726ac3)

I would like the icon to be always showing, but I have to click on the taskbar caret to get to the "safely remove.." icon.
This is not an issue when EP is turned off.

**Comment by Amrsatrio** [comment]
Can't you drag the icon from the overflow popup to the taskbar?

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/discussions/1172
