### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Unkrown6YT** [valinet/ExplorerPatcher#2459]
Here are the ideas that should be added:
Windows 10 search box
Windows 10 search menu (customizable)
Windows 7 start menu (also customizable)
Windows 7 taskbar
More Windows 7 options
Windows 7 start icon when the taskbar style is Windows 10 (possibly)
Windows 8 (8.1) taskbar, start menu, and more

**Comment by pyrates999** [comment]
Install Open Shell if you want the windows 7 start menu.

**Comment by pyrates999** [comment]
Windows 7 start menu has a search box.  It's in the start menu itself, which I prefer.
