### ISSUE TITLE
Randomly Stopped Working Yesterday

### ISSUE THREAD

**Issue by Belle170** [valinet/ExplorerPatcher#2460]
Normally I have my taskbar at the top of my screen and yesterday it just stopped no warning. My screen froze and went black for a few seconds and then turned back on and it was suddenly at the bottom. No errors or warning or anything. Yesterday I updated my drivers but I don't remember if that was before or after the program stopped working.

**Comment by Amrsatrio** [comment]
Are you running 22621.2715 now? If so, there might be a rare case where if you somehow got the second chance OOBE (or SCOOBE, you can Google it) ExplorerPatcher will sporadically crash and after that things will be stable.

**Comment by Belle170** [comment]
I have no idea I thought it auto updated.

**Comment by Belle170** [comment]
Where do I update it?

**Comment by Amrsatrio** [comment]
EP Properties > Updates > Update program and restart Explorer

**Comment by Belle170** [comment]
Thank you that worked!

**Comment by Amrsatrio** [comment]
Nice! Glad it worked! Unlike [this other issue](https://github.com/valinet/ExplorerPatcher/issues/2457) that has been stirring me up...
