### ISSUE TITLE
When using the Win10 taskbar, clicking on the battery, network, and time/date buttons is not effective.

### ISSUE THREAD

**Issue by XGntsl** [valinet/ExplorerPatcher#2462]
When using the Win10 taskbar, clicking on the battery, network, and time/date buttons is not effective. Sometimes clicking on them a second time can only succeed, and sometimes even a few times cannot be done. When I find it difficult to click on the taskbar, I click on the 'Battery, Network, and Time/Date' buttons and then click on them to open it.

**Comment by XGntsl** [comment]
win11 21h2

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1934

**Comment by XGntsl** [comment]
The first translation was inaccurate. When using the Win10 taskbar, clicking on the battery, network, and time/date buttons is not effective. Sometimes clicking on them a second time can only succeed, and sometimes even a few times cannot be done. When I find it difficult to click on it, I click on the taskbar and then click on the 'Battery, Network, and Time/Date' buttons to open it.

**Comment by XGntsl** [comment]
The first translation is not accurate. Clicking on the battery, network, and time/date buttons is not valid when using the Win10 taskbar. Sometimes a second click on them can only succeed, and sometimes even a few times it cannot be done. When I found it difficult to click on it, I first clicked on the taskbar, and then clicked on the "Battery, Network, and Time/Date" button to open it.

**Comment by pyrates999** [comment]
Still a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1934

**Comment by XGntsl** [comment]
This is the final translation. When using the win10 taskbar,Battery,Net,Time and date these buttons are invalid to click,Sometimes the second click can be successful,Sometimes a few clicks can't work,I found that when I can't click out,Click on the taskbar,Then click on the 'battery,Net,Date and date'These buttons can be clicked.

**Comment by XGntsl** [comment]
ExplorerPatcher version 22621.2428.59.1 
This is already the latest version

**Comment by pyrates999** [comment]
There's an update to EP actually https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2506.60.1_9e7c1e6

**Comment by Amrsatrio** [comment]
That update does not fix this bug yet.
