### ISSUE TITLE
Can I Contrib for Korean Language?

### ISSUE THREAD

**Issue by TK50P** [valinet/ExplorerPatcher#2463]
Hello, I want to Contrib ExplorerPatcher Korean translation.
I'm still not good at it, but I want to give it a try.

**Comment by creeper-0910** [comment]
You can contribute by sending a pull request to this repository!
https://github.com/valinet/ExplorerPatcher-L10N

**Comment by Amrsatrio** [comment]
You can try, and then others can attempt to improve. Good luck!

**Comment by pyrates999** [comment]
> Sorry I am going to comment/ping here just in case.
> 
> Basically after the localization update is there any way, or will there be a way to manually set the language to the one a user wants?
> 
> #2458

Please comment there as commenting here is off topic.
