### ISSUE TITLE
Widgets not appearing

### ISSUE THREAD

**Issue by Chaython** [valinet/ExplorerPatcher#2466]
Can't get the widgets applet to appear in taskbar?
`Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ImportOK"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"OldTaskbar"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
"SearchboxTaskbarMode"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowTaskViewButton"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarDa"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_AutoHideTaskbar"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"SkinMenus"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"CenterMenus"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"FlyoutMenus"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7]
"TipbandDesiredVisibility"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"HideControlCenterButton"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarSD"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_RegisterAsShellExtension"=dword:00000000
[-HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]
@=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"LegacyFileTransferDialog"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UseClassicDriveGrouping"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_FileExplorerCommandUI"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableImmersiveContextMenu"=dword:00000000
[-HKEY_CURRENT_USER\Software\Classes\CLSID\{056440FD-8568-48e7-A632-72157243B55B}\InprocServer32]
@=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_DisableModernSearchBar"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ShrinkExplorerAddressBar"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"HideExplorerSearchBar"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"MicaEffectOnTitlebar"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"Start_ShowClassicMode"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarAl"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_Start_MaximumFrequentApps"=dword:00000006
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StartPage]
"MonitorOverride"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_StartDocked_DisableRecommendedSection"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StartPage]
"MakeAllAppsDefault"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
"AltTabSettings"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"LastSectionInProperties"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ClockFlyoutOnWinC"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ToolbarSeparators"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"PropertiesInWinX"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"NoMenuAccelerator"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableOfficeHotkeys"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableWinFHotkey"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_DisableRoundedCorners"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableAeroSnapQuadrants"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"Start_PowerButtonAction"=dword:00000002
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectSystemToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectProgramsAndFeaturesToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectDateAndTimeToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectNotificationIconsToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdatePolicy"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdatePreferStaging"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdateAllowDowngrades"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdateURL"=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdateURLStaging"=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"AllocConsole"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"Memcheck"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"TaskbarAutohideOnDoubleClick"=dword:00000000
[HKEY_CURRENT_USER\Control Panel\Desktop]
"PaintDesktopVersion"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ClassicThemeMitigations"=dword:00000000
[-HKEY_CURRENT_USER\Software\Classes\CLSID\{1eeb5b5a-06fb-4732-96b3-975c0194eb39}\InprocServer32]
@=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"NoPropertiesInContextMenu"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"EnableSymbolDownload"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ExplorerReadyDelay"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher]
"XamlSounds"=dword:00000000
`

**Comment by Amrsatrio** [comment]
No.

**Comment by Chaython** [comment]
> No.

There's a toggle to show widget in taskbar in your GUI, but toggling it doesn't change anything in the askbar

**Comment by pyrates999** [comment]
If you're running windows 11, it already supports widgets.
If you're running windows 10, Microsoft removed the code for widgets already.
