### ISSUE TITLE
Why not delete unnecessary files when uninstalling

### ISSUE THREAD

**Issue by a2596519067** [valinet/ExplorerPatcher#2468]
Why not delete unnecessary files when uninstalling,  such as "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\wincorlib.prev"
"C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\wincorlib_orig.prev"

**Comment by a2596519067** [comment]
And ![image](https://github.com/valinet/ExplorerPatcher/assets/67247524/2667bc26-b688-4b83-9518-3d27f4680086).

**Comment by a2596519067** [comment]
If there are any more, please let me know and I will manually delete them.

**Comment by Girofox** [comment]
Some `.prev` and especially `.pri` files are created by Windows natively, for example in System32 folder, so according to WizTree with filter "*.prev" this seems be everything.

**Comment by Amrsatrio** [comment]
Fixed in the next update that I will publish soon.
