### ISSUE TITLE
Small UWP icon

### ISSUE THREAD

**Issue by imlighty** [valinet/ExplorerPatcher#2469]
![image](https://github.com/valinet/ExplorerPatcher/assets/45460688/3d333d02-705a-452c-b100-fbaef7acfa7e)

This has been an issue on Windows 10, but when using ExplorerPatcher and enabling the Windows 10 taskbar, the UWP icon for Minecraft still looks small in the taskbar, but when using the Windows 11 taskbar, everything is fine. Would there be a way to add a patch to fix this? Not gonna lie, this bug bothers me a lot for some reason.

**Comment by pyrates999** [comment]
Have you tried changing it's icon?

**Comment by imlighty** [comment]
> Have you tried changing it's icon?

I can't really do that with an UWP app

**Comment by pyrates999** [comment]
do other UWP apps also have this behavior when you are using the windows 10 taskbar?

Also, please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by imlighty** [comment]
Other apps, like the Microsoft Store for example, don't seem to have this issue.

![image](https://github.com/valinet/ExplorerPatcher/assets/45460688/11e50bfc-0942-4246-a1bd-631604168bf4)

![image](https://github.com/valinet/ExplorerPatcher/assets/45460688/0d0d8fce-4072-4df3-9cd8-3d4138551e47)

![image](https://github.com/valinet/ExplorerPatcher/assets/45460688/c15d45db-a8e7-4e2b-ae87-31c0492f2fc4)

![image](https://github.com/valinet/ExplorerPatcher/assets/45460688/53c6dec9-d9e9-4143-805e-5f6f1603d578)

**Comment by imlighty** [comment]
I didn't change any other setting. This was a bug on Windows 10 too (without ExplorerPatcher)

**Comment by pyrates999** [comment]
Since this occurs when EP is not installed, it is not for EP to fix.
