### ISSUE TITLE
Constant issues

### ISSUE THREAD

**Issue by hosm100** [valinet/ExplorerPatcher#2471]
The application constantly seems to be crashing my explorer making simple tasks harder. I can even uninstall it. Its a huge inconvenience.

![image](https://github.com/valinet/ExplorerPatcher/assets/138240259/31f66031-b6c1-49d4-84da-25ec765b1c92)

**Comment by Amrsatrio** [comment]
Do you have any other tweak software installed? (Such as Wallpaper Engine and Start11)

**Comment by hosm100** [comment]
I did not.

**Comment by Amrsatrio** [comment]
Are you sure you are running the latest ExplorerPatcher?

**Comment by hosm100** [comment]
Well i can run the latest build because the build before didn't work, and updates and uninstalling failed. I just decided to reset my PC as my recovery point got overwritten.

**Comment by Amrsatrio** [comment]
We are always here to help so we can try to fix your issue without resetting your PC 🤷

Since you reset your PC, I consider this issue as solved.
