### ISSUE TITLE
If possible to change display language?

### ISSUE THREAD

**Issue by nijawang** [valinet/ExplorerPatcher#2472]
I could not find any option to change display language.
It always shows language of computer, I just want to show English.
Thank you.

**Comment by pyrates999** [comment]
if you mean in EP, the current release shows it's settings in english.

**Comment by wsy** [comment]
I think this feature is especially important for those who want to help translate ExplorerPatcher.

For example, I came across two strings that I consider confusing today.
If I could change the language of EP, I can immediately know what's the original English text there without going through source code between two repositories.

**Comment by Amrsatrio** [comment]
Doing it right now.
<img width="1061" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/a99029b6-8b22-4542-85fc-685b7a8f6903">

For now one can set the language through EP's registry but I still have to make the dropdown of supported languages to easily switch between.

**Comment by Amrsatrio** [comment]
<img width="496" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/9b05ef55-41c6-4474-90eb-0e3006876cdd">

**Comment by Amrsatrio** [comment]
Made a new prerelease that includes this new feature.
