### ISSUE TITLE
Remove "Start backup" button from File Explorer

### ISSUE THREAD

**Issue by ghnp5** [valinet/ExplorerPatcher#2477]
Hey!

I wonder how easy it would be to create a setting to remove this ridiculous non-removable "Start backup" button? :)

<img width="376" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/57591332/7107a5a3-31b8-457d-8ed9-e9edb5303b59">

--

It even flashes 🙄

Thank you very much!

**Comment by Amrsatrio** [comment]
Do you really, really need to use the new navigation bar? For now you have to change the entire style of the top bar in order to get rid of it.

**Comment by ghnp5** [comment]
Thanks. I wasn't aware.

I don't necessarily need to use the "new navigation bar", if it doesn't revert too much of the File Explorer.

However, I've just tried to enable:
- Disable navigation bar
- Disable modern search bar

Restarted File Explorer, but it looks the same to me.

The settings:

<img width="476" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/57591332/fb62f13e-bd8c-4068-980a-9fa8f443bc03">

**Comment by Amrsatrio** [comment]
I mean, changing the Control Interface.

FYI, If you are using those other than Windows 11, you have to disable the Windows 11 context menu or it will crash.

**Comment by ghnp5** [comment]
Many thanks!! That works for me for the time being!

Hopefully Microsoft will revert this mad change. It's ridiculous!


Just putting the link of the Feedback Forum, in case anyone wants to put a Like and/or add a Reply...

https://techcommunity.microsoft.com/t5/windows-11/remove-quot-start-backup-quot-from-file-explorer/m-p/3947200

**Comment by Amrsatrio** [comment]
They will never, unless pushed by the EU 😂😂😂. For example, they are reverting the fat address bar (and its hideous modern search) in the latest release preview of Windows 10, as a feature flag. That is because the EU has been pushing MS to make Microsoft Edge uninstallable, for the sake of consumer rights :)

**Comment by ghnp5** [comment]
Yeah, then I hope EU forces them to revert this!! 😄
Cheers - good day!
