### ISSUE TITLE
No Date & Time on Tskbar

### ISSUE THREAD

**Issue by Kazi-Rasel** [valinet/ExplorerPatcher#248]
Hi,
I've installed the taskbar successfully but there is no Time & Date showing in taskbar.
Thanks,
Rasel

**Comment by novaeye** [comment]
in config gui:
Taskbar -> Enable mssing system tray icons

**Comment by valinet** [comment]
Not an issue

**Comment by Kazi-Rasel** [comment]
> 
> 
> in config gui: Taskbar -> Enable mssing system tray icons

Can you please explain

**Comment by valinet** [comment]
It's literally almost the first option in the Properties GUI:

![image](https://user-images.githubusercontent.com/6503598/139699740-fd3febb6-9ea1-4abd-8081-f10d42461b27.png)

Getting to the Properties GUI is literally the first thing the README talks about after the installation process:

![image](https://user-images.githubusercontent.com/6503598/139699822-edf21df9-fafb-4395-a538-8a7bd5991309.png)

Thanks

**Comment by Kazi-Rasel** [comment]
Thanks a lot :)
