### ISSUE TITLE
The file ep_setup.exe is not opening

### ISSUE THREAD

**Issue by scoopermcpooper** [valinet/ExplorerPatcher#2480]
I am on windows 11 and whenever I installed the setup file. Whenever I try to open the file "ep_setup" it says, "Search for app in the store? You need to install an app for this task. Would you like to search for one in the store?". Whenever you click  yes, it just opens the Microsoft Store and says "The thing you are looking for isn't here." Someone please help!
![issue-screenshot](https://github.com/valinet/ExplorerPatcher/assets/78576194/788c077c-0811-4548-86a1-b06db32fb829)

**Comment by Amrsatrio** [comment]
Does that mean you cannot run any exe files? This is not a EP problem anyways.

There is somewhere in Settings that restricts apps to only Microsoft Store apps and you need to change that.

**Comment by scoopermcpooper** [comment]
> Does that mean you cannot run any exe files? This is not a EP problem anyways.
> 
> There is somewhere in Settings that restricts apps to only Microsoft Store apps and you need to change that.

Thank you, it magically worked after I changed the setting (although the setting was already on).
