### ISSUE TITLE
Taskbar randomly starts crash looping after days of runtime

### ISSUE THREAD

**Issue by distay0xGit** [valinet/ExplorerPatcher#2481]
This is an issue I've been having recently, and it's always reappeared around 4 days after "fixing" it each time.

Usually, when it starts crashing, I see the Alt+F4 shutdown menu appear and the taskbar try and shift to the bottom, and checking the Event Viewer log at the time of the crash loop shows that it's always a 0xC0000409 error with 0x00000000000E925F as the fault offset, with Taskbar.dll being at fault.

I can mitigate the issue by running the EP update command from a command line, but it says an error occurred servicing ExplorerPatcher before returning the taskbar.

I realize I may sound stupid, but it's been plaguing me for some time.

OS version: Windows 11 v22H2 (22621.2428)
EP version: EP 22621.2506.60.1

**Comment by Amrsatrio** [comment]
So this crash loops with the new taskbar? (Because Taskbar.dll is the DLL that contains supporting code for the Win11 taskbar)

**Comment by pyrates999** [comment]
Please install the windows 11 November update and see if this is still happening.

**Comment by MadGoatHaz** [comment]
Same thing here, November update seems to have started the issue.

**Comment by pyrates999** [comment]
> Same thing here, November update seems to have started the issue.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by distay0xGit** [comment]
Might be sharing too much, but some of my settings I think may be relevant:
![image](https://github.com/valinet/ExplorerPatcher/assets/39865752/d0d33a01-24dd-4952-a54a-5f553f91c7b2)
![image](https://github.com/valinet/ExplorerPatcher/assets/39865752/3d4c1f75-cb02-41b7-9649-32fd9107bea8)

**Comment by pyrates999** [comment]
Try this:

1. Open task manager
2. Go to details tab
3. Close all explorer.exe instances
4. Go to file, run, and put explorer.exe

**Comment by distay0xGit** [comment]
I'm fairly certain I tried to do that before and didn't see improvements, but next time the crash loop occurs for me, I will let you know if that works.

**Comment by distay0xGit** [comment]
I've tried it a few times by now, but didn't really bother to talk about it because my network adapter started breaking down.
Restarting explorer.exe directly does work, but it's only a temporary fix.

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

Then when it happens, copy and paste the results from the console in here.

**Comment by Amrsatrio** [comment]
Does this issue still occur?

**Comment by distay0xGit** [comment]
I haven't been able to get the issue to reoccur after updating to EP v22621.2506.60.1 and OS v22621.2715.
My PC runtime has exceeded 2 months at this point, and I just haven't been able to get it to crash loop again.
Might have been fixed with the update, I don't know.

**Comment by Amrsatrio** [comment]
Alright. I'll close this issue then.
