### ISSUE TITLE
Tasbar moved to the side of the screen AT LAST!!! Thank you.

### ISSUE THREAD

**Issue by gggirlgeek** [valinet/ExplorerPatcher#2482]
Just a thank you to the Devs. You are my heroes. I have not used Windows 11 until now because I CAN'T STAND my taskbar placed on the bottom of the screen. My laptop screen is just too small for that mess. Even on my 85" TV, I can't see over the coffee table, or my feet to read the taskbar. In addition, I only have to open 4 apps to run out of space on the horizontal taskbar. (1920x1080, 150% DPI on all computers (because I'm not an eagle!)) However, even at the bottom, with ExplorerPatcher, the taskbar can be resized to fit more apps like in previous versions of Windows. Then it an can be Auto-Hidden, if you really must.

Also, thank you for making hidden tray icons work, and Never-Combine apps in the taskbar works great too. I also use the Win10 Start Menu with the Programs list open on the side.

All other patches I've tried for 2 years have some fundamental flaw that makes Win11 even more annoying than the default settings. There's nothing else I need. You're gods! Donation coming.

-Win11Pro 23H2 22621.2506
-ExplorerPatcher v. 22621.2506.60.1

Look how pretty! 
<img width="312" alt="Taskbar on the side of the screen ExplorerPatcher" src="https://github.com/valinet/ExplorerPatcher/assets/2652614/dd433eda-c32e-4edc-9c39-8fc1a533bb36">

**Comment by Amrsatrio** [comment]
You're welcome!
