### ISSUE TITLE
File Explorer keeps 'bringing to front'

### ISSUE THREAD

**Issue by E-Unit** [valinet/ExplorerPatcher#2484]
To be honest, I am not certain if its EPs fault or not. I am trying to find a pattern to this behaviour but have not been able to pinpoint to anything as of yet. Every x number of minutes (it's not consistent) the File explorer will be brought to the front of other open apps and steal the focus of other windows. Occasionally, the task bar seems to flash (refresh?) when this happens but I don't always catch it to confirm if it does it every time. Again, I don't know if it is EPs doing or part of a windows 'feature' that is causing it. If this has been brought up for discussion before, please mark this issue as closed and/or redirect me to said issue. TIA.

**Comment by pyrates999** [comment]
Your version of windows is from July.  Update by installing November updates.

**Comment by E-Unit** [comment]
I'm SOL on that one then. I just checked and I cannot update since it is managed by our IT department (my work computer). I'll have to wait until they push that update through to be able to continue verifying if the problem will still exist.

**Comment by Amrsatrio** [comment]
This is inherently a bug in Windows 11 22H2 itself, not a bug with EP. However, if you set the command bar to other than Windows 11 through EP, EP tries to disable the "Tabs" feature flag that is to blame for this inherent explorer-bringing-to-front bug.

**Comment by pyrates999** [comment]
I would not be installing EP on your work computer since they can take away your admin privileges at any time.

**Comment by E-Unit** [comment]
Thanks @Amrsatrio, I will give it a try. 
@pyrates999, I am completely transparent with our IT support (3rd party, mostly remote except on Thursdays). They are aware of the fact that EP gets flagged as malicious when trying to download updates for it. They've been pretty good to deal with so far.

**Comment by pyrates999** [comment]
Ok, just be aware of that then.
