### ISSUE TITLE
Ver 22621.1555.55.1 stopped working this morning on Win11, but ver 22621.2506.60.1 installer = "This app can't run on this PC.  To find a version for your PC, check wtih the software publisher."

### ISSUE THREAD

**Issue by DeepCoreII** [valinet/ExplorerPatcher#2486]
As far as I am concerned, ExplorerPatcher is an absolute MUST for Windows 11.  SO many basic features were taken out of Windows 11.  THANK YOU!!!

Up until now, I have been running ver 22621.1555.55.1 on my Windows 11 PC at work.  This morning when I logged onto the PC ExplorerPatcher was no longer loading/working.  Rebooting the PC did not make a difference.  Opening up ExplorerPatcher Properties and clicking "Restart File Explorer" does not resolve the issue.

I went to GitHub, downloaded the latest release (ver 22621.2506.60.1), but when I tried to run the installer (as Administrator) I receive this message.  
   This app can't run on your PC
   To find a version for your PC, check with the software publisher.

I am logged on with an account that is a member of the local Administrators group.  
![2023_11_21 Cannot install EP ver 22621 2506 60 1 on Win11 Build 22621 2715](https://github.com/valinet/ExplorerPatcher/assets/73230748/8f8a421a-ec8a-4e13-ac1b-05788abcc6fb)

I have adjusted the Compatibility Mode, but no luck.

When I clicked on "Check for updates" and/or "Update program and restart File Explorer" nothing seems to happen.

My PC is running Windows 11 Version 22H2, Build 22621.2715 and I have confirmed that build "22621.2715" is listed as one of the Tested OS's.  I have attached a screenshot of my WinVer as well as a screenshot of the error when trying to run the latest installer.  

Your assistance and/or suggestions are greatly appreciated.  Thank you for your time and hard work.  :)

**Comment by DeepCoreII** [comment]
I am uploading a screenshot of the most recent Microsoft patches that were installed yesterday after I signed off.  I assume one of these broke ExplorerPatcher.

Unfortunately, I am unable to remove any of these patches.
![2023_11_21b Win11 Update History](https://github.com/valinet/ExplorerPatcher/assets/73230748/f51748db-8e5c-48d2-bc90-4587d2b2f610)

**Comment by Amrsatrio** [comment]
That means the ep_setup that you just downloaded is corrupt. I've installed your exact WIndows build on 9ish PCs of mine and my friends so far, and there have been no issues regarding running the setup.

Sorry to say that this is not EP's fault.
