### ISSUE TITLE
Slow typists cannot rename files

### ISSUE THREAD

**Issue by DesktopMasters** [valinet/ExplorerPatcher#2489]
1. Click on file name
2. Press F2 so you are renaming it.
3. Wait 30 to 90 seconds
At some point it will pop out of renaming mode as if you hit escape.   If you are a slow typist you will never be able to complete renaming a file.  I have noticed on some computers it seems to happen faster than others.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Amrsatrio** [comment]
Please tell us your Windows build version through winver, and the current Control Interface you are using (check in Explorer section of EP properties).

I'm using Windows 7 command bar with latest prerelease of EP and I don't experience your issue.

**Comment by pyrates999** [comment]
Open up task manager and when you try to rename a file, check to see if anything is taking up the cpu.

**Comment by Amrsatrio** [comment]
Closing due to being irreproducible and due to inactivity.
