### ISSUE TITLE
When using the win10 taskbar, after clicking the notification button, the notification interface is still win11.

### ISSUE THREAD

**Issue by XGntsl** [valinet/ExplorerPatcher#2490]
When using the win10 taskbar, after clicking the notification button, the notification interface is still win11.
![TX IJ@7QSG~CN(LKKRDB6X9](https://github.com/valinet/ExplorerPatcher/assets/117980999/8075d96f-a048-4c72-b637-b7db266677bc)
![8 TO{WPO }A WCLO)DYN607](https://github.com/valinet/ExplorerPatcher/assets/117980999/37b055e9-cffd-4c05-9612-063e474ad0ab)

**Comment by Amrsatrio** [comment]
Expected behavior. We cannot fully bring back the old menu because there are a lot of usability bugs.
