### ISSUE TITLE
Colors on taskbar got "black" when Windows 10 style is activated.

### ISSUE THREAD

**Issue by Lukitotz** [valinet/ExplorerPatcher#2496]
After installing the few last versions, this problem shows up and still remains.
Tried to uninstal, waited a month for a bug fix, but it seems to be a problem that's affects only me. 
I'll put some screens, and hope someone have gone through this and solved!

Taskbar (blacked and the writing color also black)
![bug1](https://github.com/valinet/ExplorerPatcher/assets/53786828/5efaa6b2-913c-4c3e-b8f3-1e7551fb3ef9)

This is the popup menu for ExplorerPatcher
![bug2](https://github.com/valinet/ExplorerPatcher/assets/53786828/41b42e03-9b2d-4ce4-b798-9491da992af0)

Configuration
![bug3](https://github.com/valinet/ExplorerPatcher/assets/53786828/02f9bd9e-3e4b-46df-9435-6d4b6dbda229)

I'm using windows 11 Pro - 22H2 comp. 22621.2715 with Ex. Pack 1000.22677.1000.0

My machine is a Dell Optiplex 5060 powered by I7-8700@3.2ghz + 32GB DDR4 + Radeon R5 340x

Thanks in advance.

**Comment by Lukitotz** [comment]
> This was fixed in a previous release. Don't install older releases of EP.

I'm using the last update. I'll try uninstall and reinstal the last update again.

**Comment by pyrates999** [comment]
You didn't post the version of EP.  Please post it.

**Comment by Lukitotz** [comment]
> You didn't post the version of EP. Please post it.

The version is 22621.2506.60.1
After uninstalling this last version, deleting the folder on registries (regedit), rebooting, installing again, seems to be working. 
I'll keep testing.

Anyway, I'm sorry for posting this issue, once this is already fixed (as you said before), but I really was experiencing something here. Perhaps after removing manualy the regedit HKEY_CURRENT_USER>Software>ExplorerPatcher

**Comment by pyrates999** [comment]
Glad to hear it's now working.
