### ISSUE TITLE
win 10 taskbar do not work

### ISSUE THREAD

**Issue by andrew0711171** [valinet/ExplorerPatcher#2499]
hi i am using explorer patcher on  26635.2771 and the win 10 taskbar do not work. is there any way to fix it

**Comment by Amrsatrio** [comment]
It works on my laptop with 22635.2771 (Release Preview). Are you using the latest prerelease?

**Comment by andrew0711171** [comment]
It does not work for me since i am using the latest beta insider build

**Comment by Amrsatrio** [comment]
https://cdn.discordapp.com/attachments/1175626807454736424/1175935544962842747/ep_setup.exe

This should work. If this restored the taskbar for you, then I will make a prerelease that contains the fix.

**Comment by andrew0711171** [comment]
it did not work

**Comment by Amrsatrio** [comment]
https://cdn.discordapp.com/attachments/1175626807454736424/1178237689661763684/ep_setup.exe

Can you try this? This should be newer than the one I posted earlier.

**Comment by andrew0711171** [comment]
also did not work

**Comment by Amrsatrio** [comment]
In what way does it not work?

**Comment by andrew0711171** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/95656509/e78ac917-789d-499b-a4b6-bd3bfdc00a3e)
here is the issue i have

**Comment by Amrsatrio** [comment]
1. WIth my custom EP build, do you see "I'm about to crash"? Also, if you open Event Viewer > Windows Logs > Application, do you see any Error entries mentioning explorer.exe?
2. Are you using any other tweak software like Start11 and Wallpaper Engine?

**Comment by andrew0711171** [comment]
it working for me now with your custom build please release a prerelease

**Comment by Amrsatrio** [comment]
Really? And if you install the latest official prerelease build, it's back to Windows 11?

**Comment by andrew0711171** [comment]
i havent tried it but i think it wont work

**Comment by Amrsatrio** [comment]
The fix should be live in the latest release.
