### ISSUE TITLE
Wrong start menu  position display on the secondary screen

### ISSUE THREAD

**Issue by DarkSissi** [valinet/ExplorerPatcher#2500]
When using a multi-screen monitor, the start menu on the secondary screen is displayed in the wrong position when the Windows key is pressed.
Clicking the windows icon on the secondary screen can display the position correctly.

Feature request: When the Alt+Tab key combination is pressed, the switching window interface is displayed on the corresponding desktop.

**Comment by pyrates999** [comment]
Please put your feature request into discussions.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by toarshad** [comment]
Start button and Search icon automatically go to left side of the screen. Rest of the icon are moved to the center of the Taskbar. 
If centered with Start button, icons other than Start and Search move on right side with notification area.
Kindly resolve this. I am using Windows 11 Build 22631.2715.
Thanks.

**Comment by fihnakis** [comment]
Also having this issue with pressing start button, menu displays halfway off secondary monitor screen. Here's what it looks like.
![start button](https://github.com/valinet/ExplorerPatcher/assets/30006560/97331c39-4bd9-46d8-ac31-a286a2830c82)

**Comment by pyrates999** [comment]
> Start button and Search icon automatically go to left side of the screen. Rest of the icon are moved to the center of the Taskbar. If centered with Start button, icons other than Start and Search move on right side with notification area. Kindly resolve this. I am using Windows 11 Build 22631.2715. Thanks.

Please file as a separate issue.

**Comment by ARestrepo228** [comment]
> Start button and Search icon automatically go to left side of the screen. Rest of the icon are moved to the center of the Taskbar. If centered with Start button, icons other than Start and Search move on right side with notification area. Kindly resolve this. I am using Windows 11 Build 22631.2715. Thanks.

Did you not check this option? 
![image](https://github.com/valinet/ExplorerPatcher/assets/131640765/2b459962-0840-4926-94e2-f876d466d197)

**Comment by ARestrepo228** [comment]
The "Centered" opition
![image](https://github.com/valinet/ExplorerPatcher/assets/131640765/5aa086ad-5d04-4182-8cb2-80ad27cfcd70)
The "Centered With Start Button" Option
![image](https://github.com/valinet/ExplorerPatcher/assets/131640765/ddf1c35d-5544-4061-836b-82618b0cda5b)

**Comment by fihnakis** [comment]
Yes both options are checked. Will post versions later when I'm home but it's latest 23h2 win 11 build and latest EP version

**Comment by fihnakis** [comment]
> > Yes both options are checked. Will post versions later when I'm home but it's latest 23h2 win 11 build and latest EP version
> 
> did you tried to reinstall EP?

Yes, this is a completely fresh install of Win11 ver 23H2 Build 22631.2715 and EP 22621.2506.60.1

**Comment by DarkSissi** [comment]
> Please put your feature request into discussions.
> 
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application.

sorry for that,I will post a new thread for this
