### ISSUE TITLE
Unofficial website

### ISSUE THREAD

**Issue by zwresn453** [valinet/ExplorerPatcher#2511]
Bing (and therefore also DuckDuckGo) are still showing explorerpatcher.com (technocare.app) in search results for "explorerpatcher".

Non-tech savvy users who see this application recommended in news articles may accidentally download from this site, which could cause reputation issues for this project if the website owners decide to inject malware.

I'm not sure what needs to be done to get it delisted, so I just wanted to let you know in case you didn't.

**Comment by pyrates999** [comment]
if it's a scam website, report it like this video mentions how: https://www.youtube.com/watch?v=0fIUiv9-UFk
