### ISSUE TITLE
"ep_gui.dll" high cpu usage

### ISSUE THREAD

**Issue by MuscularPuky** [valinet/ExplorerPatcher#2515]
it seems to just GUI application

[rundll32.z01.txt](https://github.com/valinet/ExplorerPatcher/files/13489690/rundll32.z01.txt)
[rundll32.z02.txt](https://github.com/valinet/ExplorerPatcher/files/13489695/rundll32.z02.txt)
[rundll32.z03.txt](https://github.com/valinet/ExplorerPatcher/files/13489698/rundll32.z03.txt)
[rundll32.zip](https://github.com/valinet/ExplorerPatcher/files/13489713/rundll32.zip)

**Comment by MuscularPuky** [comment]
+COM Surrogate
[dllhost.zip](https://github.com/valinet/ExplorerPatcher/files/13489803/dllhost.zip)

**Comment by Amrsatrio** [comment]
Closing due to no response
