### ISSUE TITLE
an app using your code(?) on the microsoft store

### ISSUE THREAD

**Issue by GentlemanMC** [valinet/ExplorerPatcher#2518]
https://apps.microsoft.com/detail/9MZ625MT9GJW?hl=en-us&gl=US

all the settings are the exact same the ui is just different
and it sells for one dollar

**Comment by zakius** [comment]
by the screens itself it looks like everything is done according to license, but if you have access to the software can you verify if the source code of the published app is available with proper build instructions?

**Comment by zakius** [comment]
on the screens you provided there is a link to source code but it's not clear if it links here or to the derived code

being open source, including GNU GPL 2.0, doesn't stop you from charging for convenience, but it requires all derived work to be compliant too

**Comment by pyrates999** [comment]
The owner of this repository will need to report it then as a copyright violation I think.
