### ISSUE TITLE
Hiding cortana is not working

### ISSUE THREAD

**Issue by eddiejibson** [valinet/ExplorerPatcher#252]
So normally on the right click of taskbar -> hide Cortana the Cortana icon disappears next to the windows icon. However, sadly, looks like this is no longer working. Any ideas?

This is version 22000.282.32.0 (pre release).

Cheers

**Comment by valinet** [comment]
Fixed. 

The explanation is that the Cortana button has been repurposed to show the widgets panel, so it is now tied to the registry setting that alters that. Thus, if you go to "Taskbar settings" in Settings and toggle Widgets, it will show the former Cortana button which when clicked will display the widgets panel. The menu label should be updated at some point, maybe. Or just removed. Same with the icon, it should be updated at some point.

Anyway, that context menu entry is fixed for now, it works.
