### ISSUE TITLE
Icon for New MS Teams can't be pinned to taskbar notification area

### ISSUE THREAD

**Issue by tansbil** [valinet/ExplorerPatcher#2520]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/2514

<div type='discussions-op-text'>

<sup>Originally posted by **tansbil** November 27, 2023</sup>
It isn't possible to pin the icon for the new MS Teams UI to the taskbar notification area.  I like being able to see what my status is, e.g. to know whether I have unread texts without having to open the Teams app.  I can't do that with the new Teams.</div>

**Comment by MaximillianC** [comment]
I'm pretty sure whatever issue you're having is an MS Teams issue; not an Explorer Patcher issue.  I am using the new MS Teams myself, and I'm able to see the new Teams icon in the system tray just like the "old" Teams.

**Comment by pyrates999** [comment]
Please close this and discuss it further in: https://github.com/valinet/ExplorerPatcher/discussions/2514
