### ISSUE TITLE
right clicking causes file explorer to crash

### ISSUE THREAD

**Issue by Jadenheart101** [valinet/ExplorerPatcher#2522]
happens on both the desktop and file explorer

**Comment by lenoobideal** [comment]
Same here

**Comment by BookOfSpring** [comment]
same here too, i thought groupy 1 and 2 cause crash on multiple selected files

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

Please close this.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218
