### ISSUE TITLE
Toolbar icons not resizing when switching monitors.

### ISSUE THREAD

**Issue by milos0004** [valinet/ExplorerPatcher#2528]
I've added multiple toolbars that display files and shortcut icons in specific folders (with the file name and folder name hidden), however the toolbar icons don't resize when switching between monitors with different resolutions / scales. So when switching from a monitor with a low to high resolution monitor, the icons will be too small, and vise vera.  You can see the other taskbar icons, tray icons etc. get resized but the toolbar icons don't.

restarting windows explorer fixes the issue until switching monitors again.

Check images for clarification.
Version: [22621.2506.60.1] but this has been an issue since i've been using it

Windows version 22H2 22621.2715

<img width="200" alt="Screenshot 2" src="https://github.com/valinet/ExplorerPatcher/assets/60904196/135092fb-0c4f-4066-9d4c-b17cea7032ee">
![Screenshot 3](https://github.com/valinet/ExplorerPatcher/assets/60904196/b3b34482-eff0-4b8e-98a0-4e78ab536b4e)
<img width="199" alt="Screenshot 4" src="https://github.com/valinet/ExplorerPatcher/assets/60904196/d37c7f35-bf4c-436d-a8e9-e875418e4843">

**Comment by milos0004** [comment]
I've just tried that, and it's still happening. I can see all the other icons being resized except for the toolbar icons

**Comment by milos0004** [comment]
I misspoke, the bug does goes away when i uninstall ep and restart. However, what i meant was that the issue returns once i reinstall ep after the restart. Apologies for the confusion

**Comment by pyrates999** [comment]
Ok, please wait for a developer to respond here then.

**Comment by Amrsatrio** [comment]
This is a bug that is present under Windows 10 as well. As it is not a bug related to EP, we have no plans to make a workaround for this. Sorry.
