### ISSUE TITLE
ExplorerPatcher not working on Windows on ARM?

### ISSUE THREAD

**Issue by wochgn** [valinet/ExplorerPatcher#2529]
Hi there, I have a tablet with a Qualcomm Snapdragon ARM SoC running Windows 11 Version 22621.2715, and I was trying to get Windows 10 style taskbar with latest version of ExplorerPatcher. However, no matter how I tried, the ExplorerPatcher seemed not working and everything Windows 11 had not been changed at all. I don't know if it's the issue of ARM version of Windows...
Here are some screenshots of my situation and system configuration. 
![image](https://github.com/valinet/ExplorerPatcher/assets/62789090/d11922ce-195f-4530-87ad-0cd3059e5877)
![image](https://github.com/valinet/ExplorerPatcher/assets/62789090/c739d1a9-239b-4ad8-b4ff-7abb2594a651)
![image](https://github.com/valinet/ExplorerPatcher/assets/62789090/7cb86944-f1b6-4c1d-b8f3-76d0b6bf11d2)

**Comment by pyrates999** [comment]
EP only runs on Windows 10/11 x64 that has an x86-64 cpu.  Arm CPU's do not work with it.

**Comment by foorschtbar** [comment]
I have also a Lenovo ARM machine here, too bad that there is no build for Windows on ARM :(

**Comment by Amrsatrio** [comment]
If only I can get one at a reasonable price here in my country...

**Comment by foorschtbar** [comment]
For ARM testing/developing you can use Oracles [free Ampere A1 (ARM) machines](https://www.oracle.com/cloud/free/)
