### ISSUE TITLE
Turn off virtual desktop switching animation individually

### ISSUE THREAD

**Issue by yige-yigeren** [valinet/ExplorerPatcher#2531]
We all know that you can turn it off in the advanced system options of the control panel, but it will also turn off all in-window animations, making it look very stiff(even WSA will follow this setting). Is there a way to individually disable the animation of virtual desktop switching (I have wallpaper, and the original switching of Windows will be very ugly)

Windows 11 Profestional 23H2 22631.2715
Windows Pack 1000.22677.1000.0
ExplorerPatcher 22621.2428.59.1

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by yige-yigeren** [comment]
> We all know that you can turn it off in the advanced system options of the control panel, but it will also turn off all in-window animations, making it look very stiff(even WSA will follow this setting). Is there a way to individually disable the animation of virtual desktop switching (I have wallpaper, and the original switching of Windows will be very ugly)
> 
> Windows 11 Profestional 23H2 22631.2715 Windows Pack 1000.22677.1000.0 ExplorerPatcher 22621.2428.59.1

oh ok
