### ISSUE TITLE
WIN BUTTON then TYPE-TO-SEARCH randomly stops working

### ISSUE THREAD

**Issue by DavidBevi** [valinet/ExplorerPatcher#2533]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/2532

<div type='discussions-op-text'>

<sup>Originally posted by **DavidBevi** December  1, 2023</sup>
I'm used to **press the Win button and just start typing to search** files and folders. **Sometimes it doesn't work**. I've tried relaunching explorer, but it does nothing.

Can you tell me if there's a solution?

**EP Ver**: 22621.2506.60.1 -- **Win Ver**: 11 Pro 22621.2715 -- **Taskbar style**: Win10 -- **Start menu style**: Win10
(I don't know which info is relevant and which not, if asked I'll gladly edit it!)
</div>

**Comment by pyrates999** [comment]
Please close this as you opened a discussion about it.
