### ISSUE TITLE
Heads up: to anyone using Windows 11 canary build, please disable id "42537950" with vivetool before using this program 

### ISSUE THREAD

**Issue by tilsgee** [valinet/ExplorerPatcher#2534]
As reported by winaero 

https://winaero.com/microsoft-is-finally-killing-the-windows-10-taskbar-code-in-windows-11/

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.

**Comment by Amrsatrio** [comment]
The latest prerelease should automatically disable it.
