### ISSUE TITLE
Switching between virtual desktops doesn't hide the apps opened on the other desktops.

### ISSUE THREAD

**Issue by milos0004** [valinet/ExplorerPatcher#2537]
EP Version: [22621.2506.60.1] 
Windows version 11 22H2 22621.2715

When switching between virtual desktops (win + tab) the window switcher (alt + tab) correctly doesn't allow you to switch to apps/windows opened on other desktops, however, the taskbar will still show all the apps open on every virual desktop, even when you switch to a desktop with no windows/apps open. The way it works on a default windows install is that it would hide any app that was open in another virtual window.

In the photo below every app/window marked red should not be showing as open in the taskbar since I am on the "Desktop 2" desktop and all those apps have been opened on the "Productivity" Desktop. The only thing that should be showing is the app in green.
<img width="952" alt="Screenshot 2023-12-01 171316 (Custom)" src="https://github.com/valinet/ExplorerPatcher/assets/60904196/5b140226-17f8-4d66-be7e-e81bd6fc6c09">
The oposite should be shown when on the "Productivity" desktop. 
<img width="953" alt="Screenshot 2023-12-01 171245 (Custom)" src="https://github.com/valinet/ExplorerPatcher/assets/60904196/e1353468-926e-4a05-b3aa-52bfd6626823">
I have tried uninstalling and restarting, and the issue is still present.
If this is an intentional design choice, would it be possible to add an option to restore the way it works on default windows?

**Comment by pyrates999** [comment]
Uninstall EP and then reboot.  Does this still happen?
