### ISSUE TITLE
Disable rounded corners requesting command prompt 

### ISSUE THREAD

**Issue by Xbladed** [valinet/ExplorerPatcher#2549]
When trying to disable the rounded corners, this screen appears
![Screenshot 2023-12-04 115014](https://github.com/valinet/ExplorerPatcher/assets/132031334/817d0197-e465-4981-aee9-e7890a18d9b2)

It never did this before, but I have recently executed sfc /runnow to fix something else.

**Comment by pyrates999** [comment]
can you click on show more details and take a screen shot of that so we know what command is trying to be ran.

**Comment by pyrates999** [comment]
sorry, just realized I also need this from you:

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Xbladed** [comment]
I'm on windows 11 23H2 and build 22631.2792 
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/e2320b88-98d8-4e65-8363-538d4284210a)
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/f0577620-61bc-4e6e-bd92-99ab4a8df87e)
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/9e92b0bd-385a-4ee5-8023-7e518fbc1a41)
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/bfbf1496-7916-4a56-8127-765abb8f2393)
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/1d7758f9-bdd1-423e-ae30-1014e45eb11a)
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/db82ef92-10f5-4c6f-bd00-a137ccf2d914)
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/5ce08173-58e9-49e9-a6b6-a7e91f76e914)
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/e8b0fbba-48c6-4c3e-879a-68a29f863ed2)
No changes to advanced
![image](https://github.com/valinet/ExplorerPatcher/assets/132031334/d3f95735-6348-4ad3-b43f-e29e1f2a485a)

**Comment by Xbladed** [comment]
So I managed to fix it by just uninstalling and reinstalling. Weird.
