### ISSUE TITLE
Up-Right buttons is too big in Windows 11

### ISSUE THREAD

**Issue by peter8777555** [valinet/ExplorerPatcher#2551]
I hope back to small buttons.
Thank you.

![1](https://github.com/valinet/ExplorerPatcher/assets/29886853/ccb071ca-6459-41bb-8079-c32d8d17497c)

**Comment by Amrsatrio** [comment]
This is out of the scope of this program. Sorry.

**Comment by peter8777555** [comment]
How to Change Size of Caption Buttons in Windows 10
https://www.tenforums.com/tutorials/79900-change-size-caption-buttons-windows-10-a.html

But it does NOT work in Windows 11.
