### ISSUE TITLE
Start menu background staying rendered on screen for a while

### ISSUE THREAD

**Issue by Herrcookiekiller** [valinet/ExplorerPatcher#2554]
When using both `Taskbar style : Windows 10` and `Start menu Style : Windows 10` the start menu background stays rendered after closing the start menu.

This does not happen when using `Taskbar style : Windows 11` and `Start menu Style : Windows 10`

I however need the Taskbar to be the Windows 10 style for it to become compact (overall height and icons)

![menustaying](https://github.com/valinet/ExplorerPatcher/assets/40491077/944cf180-54b3-4ea0-a7be-d97d3453569e)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include any other settings you changed in explorer patcher properties application.

**Comment by Herrcookiekiller** [comment]
Build 22621.2715
Explorer Patcher 22621.2506.60.1_9e7c1e6

I changed a lot of things, there isnt an indicator for what the default checkboxes are.

Not to worry, i restarted my laptop 3 times and reapplied the Taskbar style and everything was fixed... no idea how.
