### ISSUE TITLE
"Explorer.exe" is crashing and Machine interface turn blank after installed the application on Windows GE (#47794095)

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#2558]
ExplorerPatcher v22621.2506.60.1
**Repro Steps:**
1. Deploy the latest OS 
2. Perform windows and store updates 
3. Install the application from vendor site 
4. Run the setup file
5. Observe the Explorer.exe Crash.

**Observations: -**
After installing the Application, System fails to work with black screen, need to schedule the machine to work.

Actual Result:
Explorer.exe Crash and blank screen is observed after installing the Application

**NOTE:** 
The bug only repros on Ge with the app's latest pre-release version [22621.2506.60.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2506.60.1_a7a3d27) (built on 11/20/2023). This particular change (commit [72f1458](https://github.com/valinet/ExplorerPatcher/commit/72f1458afe08ae3a2a0b2cf237238ece729ac5b1)) of the app code is accessing the system binary pnidui.dll, which was removed from Ge for more than one year, and results in the explorer crash. We would like to inform you that the file you refer to (pnidui.dll) no longer exists in the next version of Windows. You may need to fix the code to be able to support the future Windows.

**Comment by Amrsatrio** [comment]
Thank you for reporting this. Actually I have the code that modifies pnidui.dll covered in an if check on my machine, just haven't pushed it yet. Cheers :)

**Comment by Michellehdr** [comment]
@Amrsatrio thanks for your quite response. Is there any plan on when the code will be pushed? Thanks!

**Comment by Michellehdr** [comment]
@Amrsatrio is there any timeline on when 22621.2787 will be released? Thanks!

**Comment by Amrsatrio** [comment]
Hi, sorry for late reply. There are still some localization stuff that needs triaging, and I hope I can make a new release by this weekend.

As for Canary/GE, at the moment we are not aiming to fully support/quickly fix bugs on Canary/GE builds because I've observed a lot of broken features in it and at the moment keeping up with the new GE builds can be tiring (at least for me).

**Comment by Amrsatrio** [comment]
Made a new prerelease which contains the fix. I will promote it into a release build in less than a day if there are no reported issues. Sorry if this took too long. Cheers :)
