### ISSUE TITLE
Colors changed causing menus to be obscured

### ISSUE THREAD

**Issue by skematik** [valinet/ExplorerPatcher#2560]
Installing ep on a new windows 11 dell 5540, colors seem to be off in a way that the forground matches the background obscuring menus, looks okay until i run some software then things become obscured, can't figure out how to fix it, guessing it's a color setting issue in windows. Any ideas? Great app by the way, been using it for over a year. Thanks
![Screenshot 2023-12-05 160638](https://github.com/valinet/ExplorerPatcher/assets/5450809/262399d4-2740-4e4f-b043-c813af6d21b2)

**Comment by Amrsatrio** [comment]
In EP settings > Advanced, disable "Classic theme mitigations" or something. It should fix your issues.

**Comment by Gillesdu38** [comment]
Hi, i tried to use 
C :\Windows\System32\rundll32.exe « C :\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll »
as recommended by mail, but i don't now how or where use it. i paste directly in  directory and also in the execute command but Windows ask me to indicate a software...  I founded the DDL but i cannot open it. Windows ask me to indicate a software...

**Comment by pyrates999** [comment]
to run the explorer patcher properties application, run this from the run menu:
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.

**Comment by Amrsatrio** [comment]
Why does it have to be so hard... one can find Properties (ExplorerPatcher) in the start menu or search for it...
