### ISSUE TITLE
After E-Patcher install, the system tray icons gone.

### ISSUE THREAD

**Issue by RayElProOficial** [valinet/ExplorerPatcher#2562]
![image](https://github.com/valinet/ExplorerPatcher/assets/88939475/211c691e-c495-4aac-ba23-81c91f3940b0)

**· OS VERSION: ** Winddows 10.0.26002.1000 (Windows 11 23H2 Canary-Insider)
**EPatcher version: ** 22621.2506.60.1
**Other problems: **
Start menu is windows 11's

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.

**Comment by abditube1345** [comment]
and if you update microsoft broke explorerpatcher

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/discussions/2363
