### ISSUE TITLE
UI Window Size

### ISSUE THREAD

**Issue by reindex-ot** [valinet/ExplorerPatcher#2574]
I would like to be able to change the size as I feel the size is too small.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by Amrsatrio** [comment]
I've expanded the width of the properties window to accomodate other languages in the latest prerelease.

最新のプレリリースではほかの言語に合わせるためにプロパティウインドウの幅を広げました。
