### ISSUE TITLE
No System Tray

### ISSUE THREAD

**Issue by generouspanda** [valinet/ExplorerPatcher#2578]
I'm using Explorer Patcher with the latest insider preview, and when I set it as the windows 10 taskbar, there is no system tray shown.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/discussions/2363

**Comment by highlanderc** [comment]
did this get fixed?

**Comment by Amrsatrio** [comment]
Soon this month. Hold your breath or roll back.

**Comment by highlanderc** [comment]
awesome.. what version didn't have this issue?

**Comment by highlanderc** [comment]
thanks .. donated again for your efforts.
