### ISSUE TITLE
功能请求与Bug报告Feature requests and bug reports

### ISSUE THREAD

**Issue by Firedoge1** [valinet/ExplorerPatcher#2579]
此英文翻译使用ChatGPT生成，仅供参考This English translation was generated using ChatGPT and is for reference only.
1.The power, network, and sound menus in the bottom right corner notification area are still square-shaped, and the animation isn't smooth enough.
2.The Control Center button cannot be repositioned.
3.The buttons for widgets and Copilot cannot be displayed on the taskbar.
5.Unable to search on the full-screen start screen; the search panel is located below the start screen in the "Layer" (normally, it should be in the upper "Layer").

1.右下角通知区域的电源网络声音菜单还是直角，而且动画不够丝滑
2.控制中心按钮无法改变位置
3.无法在任务栏上显示小组件按钮和Copilot按钮
4.搜索面板还是Windows 11样式
5.无法在全屏开始屏幕上搜索，搜索面板位于开始屏幕下方的“图层”（正常情况应该在上方的“图层”）

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by Amrsatrio** [comment]
We will backport the Copilot button to the Windows 10 taskbar of Windows 11 from Windows 10 explorer in the future. However, other issues you've mentioned have been reported here before.
