### ISSUE TITLE
Microsoft Security Update KB5033375 Messes up Start Menu Position

### ISSUE THREAD

**Issue by ZarroTsu** [valinet/ExplorerPatcher#2582]
Microsoft Security Update KB5033375

When the Taskbar style is set to 'Windows 10' and the Start menu style is set to 'Windows 11', the start menu will always seem to open in the middle of the screen, even with Windows 11 system settings telling it to open on the left. Changing the Taskbar style to 'Windows 11' "fixes" the issue, but setting it back to 'Windows 10' it reverts to opening in the middle.

Uninstalling KB5033375 also fixes the issue, but the update installs again as soon as possible since it's marked as a Security Update.

**Comment by KyodaiKen** [comment]
It's starting...

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please install the latest pre-release.
