### ISSUE TITLE
[Feature Request] Would you mind make the weather on the taskbar go all the way left beyond a centered start button?

### ISSUE THREAD

**Issue by Rellawing** [valinet/ExplorerPatcher#2587]
**[Feature Request] Would you mind make the weather on the taskbar go all the way left beyond a centered start button?**

On Windows 10, selecting the left option makes a blank space appear to the right of the start button. If it would show up all the way to the left, it would help to make up for how News and Interests cannot be moved from where it is (as far as I know). That way, the taskbar would be more like Windows 11's.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
