### ISSUE TITLE
[Bug] with 22635.2850

### ISSUE THREAD

**Issue by LexBoosT** [valinet/ExplorerPatcher#2588]
On Windows 11 22635.2915, If I try to open a window, the explorer reboot, working correctly on version 22635.2850

**Comment by pyrates999** [comment]
Since you are running a developer preview of windows 11, please try to install the latest pre-release of EP.

**Comment by vandelin586** [comment]
I have tried this with no successful results

**Comment by vandelin586** [comment]
well you say pre release? Should I select in the options menu to allow unofficial releases or whatever that option is?

**Comment by Amrsatrio** [comment]
Please install the latest pre-release.
