### ISSUE TITLE
Menu is centered even it's selected left

### ISSUE THREAD

**Issue by rols2015** [valinet/ExplorerPatcher#2589]
Hi, after the last windows update, I got menu centered.
![image](https://github.com/valinet/ExplorerPatcher/assets/16349586/63090839-9005-43da-996d-7074021ca18e)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please install the latest pre-release.

**Comment by rols2015** [comment]
Thank you @Amrsatrio upgrading to the latest release solved the issue.
