### ISSUE TITLE
search box

### ISSUE THREAD

**Issue by hairybuthole12** [valinet/ExplorerPatcher#2590]
can you maybe add a feature where instead of having the search icon o

nly showing, maybe it will be able to show a search box like this: 
![Screenshot 2023-12-15 181547](https://github.com/valinet/ExplorerPatcher/assets/131720327/a9396eb8-407b-436e-8feb-2175d02465ba)

this would be awesome, and even if the answer is no, please respond so i know you read this.

also in settings when you change it from search icon to search bar, it doesnt work.

**Comment by Amrsatrio** [comment]
No.

**Comment by hairybuthole12** [comment]
> No.

why not

**Comment by Amrsatrio** [comment]
Can you stop begging? This is like the third time you asked for this. You have been saying this like it is easy to bring the code from Windows 10 to the Windows 10 taskbar in Windows 11, and doesn't take a significant time to do so. One cannot load exe's as if they were dll's. And I don't want to make ExplorerPatcher modify system files on disk.

Go learn programming and reverse engineering so you know how hard it is. Sorry if I sound rude.
