### ISSUE TITLE
Malware Detection Site says this is Lumma Stealer?

### ISSUE THREAD

**Issue by KrazyKleb** [valinet/ExplorerPatcher#2591]

**Comment by Amrsatrio** [comment]
False positive. We added a new DLL recently that contains the Properties GUI and its translations. That DLL gets loaded by the EP DLL that is injected into explorer as a "data file" to retrieve the texts related to updates and symbols. That's all I can say.

**Comment by KrazyKleb** [comment]
"False positive?" How could it get marked as lumma stealer

**Comment by KrazyKleb** [comment]
Also why does nothing happen when I open up the exe

**Comment by Amrsatrio** [comment]
You know, antiviruses can use machine learning algorithms which is not always perfect. I've went through all the code in EP and I can confirm that there are no such code that harvests data. The code is all there for everyone to check, there are no code outside this repository that gets included into the ep_setup.exe that everyone downloads.

**Comment by KrazyKleb** [comment]
Still haven't talked about why the exe does nothing
