### ISSUE TITLE
[Feature Request] Remove old update files

### ISSUE THREAD

**Issue by FrzMtrsprt** [valinet/ExplorerPatcher#2593]
# Feature Description
Automatically remove old update files in `%APPDATA%\ExplorerPatcher\`.

# Step to reproduce
1. Install an old version of ExplorerPatcher
2. Go to the `Updates` tab and click `Update program and restart File Explorer`
3. Wait for the update to finish, and observe `%APPDATA%\ExplorerPatcher\`

# Current behaviour
The update files are not removed after in-app updates.

<img width="313" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/15852717/e71b95f1-13cb-4a13-8849-a696dc3b444c">

# Expected behaviour
The update files are removed everytime the program updates, or everytime the program starts.

**Comment by ARestrepo228** [comment]
For Feature Requests Use Discussions

**Comment by Cecelia72** [comment]
I don't understand what I am supposed to do with all of this information to fix my PC?

**Comment by milesprower2293** [comment]
> I don't understand what I am supposed to do with all of this information to fix my PC?

try deleting those files

**Comment by Cecelia72** [comment]
I would like to unsubscribe and close my account with you, it seems kind of funny that I sign up with you and all of a sudden I have a credit alert, please destroy all of my information!!!!
    On Monday, February 5, 2024 at 08:17:14 PM MST, Miles Prower ***@***.***> wrote:  
 
 



I don't understand what I am supposed to do with all of this information to fix my PC?


try deleting those files

**Comment by Amrsatrio** [comment]
Implemented in 66.4.
