### ISSUE TITLE
mouse pointer changes either horizontally or vertically when hovering over start menu

### ISSUE THREAD

**Issue by johnb35** [valinet/ExplorerPatcher#2594]
So I have open shell installed and also installed explorer patcher on my new build.  However. if I uninstall either one then the pointer works as normal.  Here's the kicker though.  I have another system with the same 2 programs and it works just fine.  Can someone help me track this down to what needs to be changed or fixed?  Anyone else having this issue?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

please show a screen shot of what you mean.

**Comment by johnb35** [comment]
Hi,

So after some diagnosing between my 2 machines I realized I was running an older version of Open Shell.  4.4.170 along with Explorer Patcher and I had no issues.  On my new pc I was running version 4.4.181 with Explorer patcher.  I have now figured out that any version of Open Shell newer than 4.4.180 will cause this issue.  So maybe between the 2 of you developers you can figure out what is causing this to happen between these 2 apps.  If I uninstall either app, the mouse works like it should so there is a conflict somewhere.  It's possible that the first item in the change log is causing this.  It's labeled "Windows 11 Start Button Support"  Here is the link to what I mean.  https://github.com/Open-Shell/Open-Shell-Menu/releases?page=2   First release on that page. So for now I have Open Shell version 4.4.180 installed and its working fine.  If I were to install 4.4.181, it causes the issue.  I'm running Windows 11 build 22H2 22621.2861.  Thanks.  
![20231217_150336](https://github.com/valinet/ExplorerPatcher/assets/154016456/e352a399-2ba7-4e66-a592-9f9067f87174)
![20231217_150342](https://github.com/valinet/ExplorerPatcher/assets/154016456/a435aa2c-8f2b-47a0-ae3a-0c12e77cfdc2)

**Comment by pyrates999** [comment]
Openshell is now at version 4.4.191.  Please update to that.

**Comment by Firedoge1** [comment]
不要同时安装多个修改任务栏或开始菜单的程序Do not install multiple programs that modify the taskbar or Start menu at the same time

**Comment by johnb35** [comment]
> 不要同时安装多个修改任务栏或开始菜单的程序Do not install multiple programs that modify the taskbar or Start menu at the same time

Nope, that has nothing to do with it.  The new versions of open shell is what is causing the issue with Explorer Patcher.  Anything above 4.4.180 causes the issue.  

> Openshell is now at version 4.4.191. Please update to that.
> 
> Also, that pointer icon is shown when you can resize your taskbar. Please right click on it and make sure that **lock the taskbar** is ticked.

No, that has nothing to do with resizing the taskbar since the mouse isn't anywhere near the top of the taskbar.  See attached image that is how you resize the taskbar, not when hovering over the start button.  As I said, installing any version of Open Shell newer than 4.4.180 causes the issue.  If the 2 developers don't want to work together to fix this issue than thats fine.  
![resize taskbar](https://github.com/valinet/ExplorerPatcher/assets/154016456/0ae73da9-6fa7-42ac-81f4-7b876ba06f84)

**Comment by pyrates999** [comment]
Can you please right click on the taskbar and make sure that lock the taskbar is ticked.  Then check if this is still happening.
