### ISSUE TITLE
Clock has weird square separating symbol instead of usual colon. 

### ISSUE THREAD

**Issue by anthony75smith75** [valinet/ExplorerPatcher#2597]
Have installed this app on a couple of Windows 11 systems so far and have noticed that when I move the taskbar to the left or right hand sides so that it is vertical instead of horizontal the clock gets broken.  A weird square separating symbol instead of the usual colon appears within. The actual clock continues to function normally but visually looks broken. Have checked all options in Explorer Patcher and can't see any relevant settings. How can we get the clock back to normal?

![Taskbar with broken clock](https://github.com/valinet/ExplorerPatcher/assets/77678231/cf7f7bd6-02ef-4e57-b180-d4bd8f4f1ce0)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by lancerdoom1** [comment]
This happen when you have deleted windows fonts or replaced with the different font. I believe windows uses Segoe font for all platforms.

**Comment by anthony75smith75** [comment]
I'm using the following:

Windows 1122H2 Build 22621.2715
Explorer Patcher v22621.2861.62.1 Latest

An older version of Explorer Patcher did exactly the same thing. Different Windows updates over the months have also not effected the problem. Have not installed any other UI modifiers for my Windows 11 and have seen this exact problem on multiple machines. Reproduction of this issue looks quite straight forward. Install Explorer Patcher and then drag the task bar to one of the two possible vertical positions. Instantly the clock fault occurs with no current way I know of fixing it. No other settings need changing for the fault to occur.

**Comment by anthony75smith75** [comment]
Confirming that this weird clock square symbol fault is caused by a change in the system font! Yes for real. If you use an app like "Winaero Tweaker" to change the system font to something bold and easier to read, for example, you will then get this behavior from the clock in Explorer Patcher. Changing back to the normal windows Segoe system font (not bold) restores the clock with normal colon as expected. So the question now becomes, could we allow custom fonts for normal clock colon in future builds? Seems simple and non-complicated to achieve?

**Comment by pyrates999** [comment]
> Confirming that this weird clock square symbol fault is caused by a change in the system font! Yes for real. If you use an app like "Winaero Tweaker" to change the system font to something bold and easier to read, for example, you will then get this behavior from the clock in Explorer Patcher. Changing back to the normal windows Segoe system font (not bold) restores the clock with normal colon as expected. So the question now becomes, could we allow custom fonts for normal clock colon in future builds? Seems simple and non-complicated to achieve?

Please submit this request under discussion then and close this issue.
