### ISSUE TITLE
Suggestion:Change a small fact

### ISSUE THREAD

**Issue by gailium119** [valinet/ExplorerPatcher#26]
SHGetFolderPathW(
            NULL,
            CSIDL_COMMON_APPDATA,
            NULL,
            SHGFP_TYPE_CURRENT,
            wszSettingsPath
        );
(Line 2948)
Change the   CSIDL_APPDATA to CSIDL_COMMON_APPDATA and make the pdbs store in C:\ProgramData instead of the user appdata folder(therefore,enabling it to be stored in install.wim)

**Comment by valinet** [comment]
It is a bit more complicated than that. As far as I know, common app data is available for all users to read/write to, but once some user writes there, the file's ACLs are set to that users and other users' reads/writes are virtualized and redirected to another directory. So, a bit more care should be taken if implementing this, like making sure the ACLs of the newly created folder allow anyone to read/write to the files created there. I am not that familiar with storing data there; I use only a single user on all my computers.

With that being said, I am open to accepting a pull request properly addressing this, you can be my guest writing this patch. Unfortunately, personally, I do not have much time at the moment to work on this anymore, but I am open to having it implemented some time and will surely look into it once I get less busy and maybe have some time to work on this again.
