### ISSUE TITLE
Blacked out icons with latest patch when using registry hack to delete arrows from icons.

### ISSUE THREAD

**Issue by derpina-ai** [valinet/ExplorerPatcher#2600]
![image](https://github.com/valinet/ExplorerPatcher/assets/153082447/d20acf60-7e92-4f47-94f1-548d873405e8)

Is there any way to remove arrows from shortcuts using ExplorerPatcher? Because the Shell Icons interferes with the latest patch, worked fine before.

**Comment by pyrates999** [comment]
No because it doesn't fall under the uses that EP is for.  But here's how: https://www.majorgeeks.com/content/page/remove_shortcut_arrow_icon.html

**Comment by derpina-ai** [comment]
Thanks @pyrates999, this hack seems to work along with EP. This can be closed I think.

**Comment by pyrates999** [comment]
Please close it then.
