### ISSUE TITLE
crash after update

### ISSUE THREAD

**Issue by juliustram123** [valinet/ExplorerPatcher#2605]
Hello i updated windows 11 to the lastest version (idk the update name tbh) and when i tried to start ep its said that it crashed more that three times. I also tried to unistall, delete the keys in regedit. Any fix?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.  You can download the latest version here: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2861.62.1_9444eee

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by juliustram123** [comment]
okay so I can’t tell you exactly what options did i changed but here is what I remembered: 
windows 10 taskbar, win 10 start menu, win 10 « alt tab » disable cornered windows and I think that’s all. I use the last version (like i updated it via the app) and i use lively wallpaper (idk if its really a UI modificator) 
Thanks for you reply!

**Comment by pyrates999** [comment]
Please uninstall EP and download the latest release and try to install that.

**Comment by juliustram123** [comment]
I've already done that but I forgot to mention that on a boot that i did after the EP uninstall I've got a bluescreen but it rebooted normally after. Idk if it's mean something

**Comment by pyrates999** [comment]
Please post windows version and build. You can find this by running winver.

**Comment by juliustram123** [comment]
I'm sorry but I can't access my pc rn but here is all I know:
I'm on windows 11 home, lastest update I could find in windows update. Sorry for the inconvenience...

**Comment by pyrates999** [comment]
When you can access it, please let me know.

**Comment by juliustram123** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/70858772/d778d7d3-87e2-457e-a61c-ba8d58d9b2a0)

**Comment by Amrsatrio** [comment]
Please install the latest newly released version. There was an issue where long strings in the French translations crashed Explorer when attempting to download symbols. 

We're really sorry for this bug specific to your locale 🙏
