### ISSUE TITLE
Custom volume flyout?

### ISSUE THREAD

**Issue by Chaython** [valinet/ExplorerPatcher#2606]
https://github.com/File-New-Project/EarTrumpet
Would it be possible to use their flyout instead of the default windows flyouts?

**Comment by pyrates999** [comment]
Open up the EP properties application, and go to system tray.  Look under `When clicking a system icon in the system tray, open`, and look for the `sound` option.  From there you can select which one you want.

**Comment by Chaython** [comment]
> Open up the EP properties application, and go to system tray. Look under `When clicking a system icon in the system tray, open`, and look for the `sound` option. From there you can select which one you want.
You only have the choice between the windows 7 and the windows 10 flyout.
Ear Trumpet, exposes the windows 10 mixer in a flyout.
![image](https://github.com/valinet/ExplorerPatcher/assets/6486343/5de53f62-1194-492f-a148-04f0f97f4cb9)
Its just annoying to have two speaker icons.
I had previously requested ET to add support to replace the windows 11 flyout w/ their own and they said they don't think there's a way to... But maybe ET can be implemented into W10 flyout on EP

**Comment by Chaython** [comment]
> You can hide the system tray icon for sound so you only see the ear trumpet one.

You're right, for anyone looking: shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9} turn system icons on/off and remove sound
