### ISSUE TITLE
ep_setup.exe classed as Virus.

### ISSUE THREAD

**Issue by DavidCF77** [valinet/ExplorerPatcher#2610]
Hi,
valinet /[ExplorerPatcher](https://github.com/valinet/ExplorerPatcher)
Just tried to install ep_setup.exe and
NORTON blocked it saying it was Threat name WS.Reputation.1
Just thought I would let you know.

**Comment by garyh140** [comment]
Same problem with Norton also Windows security reporting as virus as well

**Comment by Amrsatrio** [comment]
As with all unsigned software, it takes time for it to gain reputation and not be detected as a "virus". There is really nothing we can do, other than buying an expensive signing certificate only so that these will not happen anymore.

**Comment by pyrates999** [comment]
Chrome is only flagging it cuz not many people have downloaded it.  It will still allow you to download it.  You just gotta press the option to allow it under the download icon in the toolbar.

**Comment by pyrates999** [comment]
A self signed certificate would cause this to be flagged more often I think.  Signing with an authentic certificate has been discussed here: https://github.com/valinet/ExplorerPatcher/discussions/2353

**Comment by Amrsatrio** [comment]
I will close this as this is not something we can fix in the short term, or at least under our control.
