### ISSUE TITLE
Can't Check for New Updates

### ISSUE THREAD

**Issue by mmschmieg** [valinet/ExplorerPatcher#2611]
Just installed 22631.2861.62.2 on OS 22631.2861 on three machines here. No problems on two of them, but the third will no longer allow update checking in Properties. Ran the console and everything looks fine there. Ran uninstall and reinstalled, but no change. Something is messed up with this machine, but I'm not sure what.

**Comment by pyrates999** [comment]
Please post the console contents when it is trying to check for updates.

**Comment by mmschmieg** [comment]
The console seems to indicate that the update check and update command are working, but nothing else appears in notifications.

 

This is check for updates:

[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".

[Updates] Path to module: C:\Windows\dxgi.dll

[Updates] Checking against hash "22622.2861.62.2.c2b7c0292fff8608"

[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe

[Updates] Hash of remote file is "22622.2861.62.2.c2b7c0292fff8608" (valid).

[Updates] Local version obtained from hash is 22622.2861.62.2.

[Updates] No updates are available.

 

This is install updates and restart Explorer Looks the same as above, but that makes sense since there are no updates to install:

[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".

[Updates] Path to module: C:\Windows\dxgi.dll

[Updates] Checking against hash "22622.2861.62.2.c2b7c0292fff8608"

[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe

[Updates] Hash of remote file is "22622.2861.62.2.c2b7c0292fff8608" (valid).

[Updates] Local version obtained from hash is 22622.2861.62.2.

[Updates] No updates are available.

**Comment by mmschmieg** [comment]
Found the problem. Something turned off File Explorer notifications. Don't know that it was the EP installation. As I said, this computer seems to have some problems and I may be doing a repeat of my clean installation on it.

**Comment by pyrates999** [comment]
Ok, please close this then.
