### ISSUE TITLE
Explorerpatcher Full installation (offline installation)?

### ISSUE THREAD

**Issue by TK50P** [valinet/ExplorerPatcher#2612]
Hello I am tasking unattend install explorerpatcher (integrate install.wim)
However do you have to release full installer?
because if not have network connection, ep can't download more synbols.
So I suggest release as offline installer next version (if possible)

**Comment by pyrates999** [comment]
Symbols change with each new update for windows.  So they can't be bundled.

https://github.com/valinet/ExplorerPatcher/wiki/Symbols
