### ISSUE TITLE
Explorer Crashes and Restarts When Right-Clicking the Windows logo or using Win+X Menu

### ISSUE THREAD

**Issue by MG665** [valinet/ExplorerPatcher#2617]
**Summary**
Right clicking the Windows Start Menu (Or using the Win+X shortcut) after launching an app from it causes Explorer to crash and restart.

**Steps to Reproduce**

1. Launch any app or option from the Start Menu by accessing it via Win+X
2. Right click the Start Menu icon
3. Explorer will crash and automatically restart

**Expected Behavior**
Right clicking the Start Menu or using Win+X should not cause Explorer to crash.

**Actual Behavior**
After launching something from the Win+X shortcut, using it again or right clicking the same menu causes Explorer to crash and restart.

**Event Log Details**
Below are the events logged when the crash occurs:

```
Faulting application: explorer.exe
Version: 10.0.22621.2792
Timestamp: 0xfbda1990

Faulting module: twinui.pcshell.dll
Version: 10.0.22621.2861
Timestamp: 0xa5744518

Exception code: 0xc0000005
Fault offset: 0x00000000000210b9

Process ID: 0x0xE8C
Start time: 0x0x1DA365829406FEB

Path: C:\WINDOWS\explorer.exe
Module path: C:\WINDOWS\SYSTEM32\twinui.pcshell.dll

Report Id: f917bc18-6bd6-4a9e-8d76-70ccfa6c57db

This suggests the crash may be related to the twinui.pcshell.dll module.

System Details
Windows 11 version 23H2

```

**Comment by Amrsatrio** [comment]
If you were referring to the Terminal entry, then it's already known. Other than those entries, I can't reproduce this bug. Sorry.
