### ISSUE TITLE
Start menu win 11 recommended apps section

### ISSUE THREAD

**Issue by hecode** [valinet/ExplorerPatcher#2622]
The Start menu win 11 style is still showing recommended apps section since quite a few versions ago.
Checking the disable recommended apps should remove that.

what i noticed is that if i connect another monitor, the 2nd monitor doesn't have the recommended section while the main one does. and if only one is connected then the section is always showing.

Windows 11, OS Build 22631.2715
ExplorerPatcher Version 22621.2861.62.2

**Comment by pyrates999** [comment]
Where is this option where you can disable showing of recommended apps?

**Comment by hecode** [comment]
> Where is this option where you can disable showing of recommended apps?

![Screenshot 2023-12-26 065907](https://github.com/valinet/ExplorerPatcher/assets/2666129/df426d70-2d3a-4bcd-a650-f85e6adc97ff)

**Comment by pyrates999** [comment]
This has been fixed already I think: https://github.com/valinet/ExplorerPatcher/issues/2212

**Comment by hecode** [comment]
> This has been fixed already I think: #2212
> 
> But some have reported that it doesn't work.
It still hasn't for me. and here i added the notice about 2nd monitor that it actually works there but not on primary nor if just 1 monitor.

**Comment by NocturnalKing** [comment]
Not sure if this is related but I'll add it here just in case; when I press the search icon instead of the windows 10 version i get the windows 11 center screen pop up
![Screenshot 2023-12-26 074504](https://github.com/valinet/ExplorerPatcher/assets/49161708/156e003c-2113-4c32-8045-4076c05d85fb)

**Comment by pyrates999** [comment]
> Not sure if this is related but I'll add it here just in case; when I press the search icon instead of the windows 10 version i get the windows 11 center screen pop up ![Screenshot 2023-12-26 074504](https://private-user-images.githubusercontent.com/49161708/292890306-156e003c-2113-4c32-8045-4076c05d85fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzE4MTYsIm5iZiI6MTcwMzY3MTUxNiwicGF0aCI6Ii80OTE2MTcwOC8yOTI4OTAzMDYtMTU2ZTAwM2MtMjExMy00YzMyLTgwNDUtNDA3NmMwNWQ4NWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEwMDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNmI5YTFjMzE1ZTcyNWJlZmMxOTRjYWM2Y2Q1ZDAwM2RlMzJjZTg0MzY2ZDFiMzNlZTc2NmYyNGQyZDZmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2_a03Ikwcx3IUaCN8R4AG5H1G-cBtuD4Dx1oH16Tz90)

Please file this as a separate issue.

**Comment by hecode** [comment]
i should mention the main monitor is 4k if that makes a difference. Please look into it when you can.

**Comment by hecode** [comment]
I wanted to update that the issue was resolved somehow in one of the latest versions. 

Windows 11, OS Build 22631.2861
ExplorerPatcher Version 22621.3296.64.1
