### ISSUE TITLE
"pin To Start"Only appears in the right-click menu of the Start menu.

### ISSUE THREAD

**Issue by cloudrflight** [valinet/ExplorerPatcher#2623]
"Pin To Start"按钮仅仅在开始菜单的右键菜单中出现，在其他地方出现的是"固定到'开始'菜单"，例如：资源管理器的右键菜单，显示的是"固定到'开始'菜单"，点击这个无法正常的将应用添加到windows磁铁当中；有很多软件在开始菜单中找不到，所以没法点击“Pin To Start"按钮；
The "Pin To Start" button only appears in the right-click menu of the Start menu

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by cloudrflight** [comment]
> 请发布 Windows 版本和构建。您可以通过运行 winver 找到它。 请发布资源管理器补丁版本。
> 
> 请包括您在资源管理器修补程序属性应用程序中更改的设置。
> 
> 请包括您安装的任何其他会修改 Windows 用户界面的软件。

Windows Version is  `Win11，21H2(22000.675)`
![image](https://github.com/valinet/ExplorerPatcher/assets/95400333/3d99db5d-1ae7-47a4-aa7a-0e37d2d4f9fc)

**Comment by pyrates999** [comment]
Version 21h2 build 22000.675 is from May 2022 and is an old version and thus not tested against.  Only the current versions 22h2 for windows 10/11 and 23h2 for windows 11 is tested against.

At the very least, you can install the current updates for 21h2, which should get your build number to 22000.1335.  Here's the update:  https://support.microsoft.com/en-au/topic/december-13-2022-kb5021234-os-build-22000-1335-56a94ce4-7122-447d-98d8-360e95fc0cf9

**Comment by cloudrflight** [comment]
this button `Pin to Start` is valid
![image](https://github.com/valinet/ExplorerPatcher/assets/95400333/16934924-383a-4bdc-928b-f93e927a5894)

this button `固定在'开始'屏幕` is invalid，（I don't know where it came from，may be windows11 official button）
![image](https://github.com/valinet/ExplorerPatcher/assets/95400333/5f71eb37-8602-4f1f-a17a-fd7a0dc21df5)

**Comment by cloudrflight** [comment]
> ere's
OK，thank's

**Comment by pyrates999** [comment]
Please install this update in windows update: https://support.microsoft.com/en-au/topic/december-13-2022-kb5021234-os-build-22000-1335-56a94ce4-7122-447d-98d8-360e95fc0cf9
