### ISSUE TITLE
Taskbar became transparent after updates

### ISSUE THREAD

**Issue by Torgut** [valinet/ExplorerPatcher#2625]
I just got a new Lenovo laptop, installed ExplorerPatcher, all perfect. Meanwhile the computer did its updates routine and when it finished the taskbar was transparent. Icons and text is there, but the bar itself, grey in my case, is gone, I assume went transparent. What can I do?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Torgut** [comment]
1) Windows v. 22H2 OS Build 22621.2861

2) Latest

3) Can't recall it all. What I know it's that the taskbar was beautiful, opaque, grey color. Then Lenovo finished the updates and it was gone.

4) Before that, nothing. After, uninstalled Explorer Patcher and tried TaskAllBack and the transparency in the taskbar remained. If I adopt the Win 11 taskbar style it becomes opaque as it should.

**Comment by Torgut** [comment]
Apologies, my mistake, a setting in ClassicShell was causing the issue. Solved. Thank you for your time :-)

**Comment by pyrates999** [comment]
Classic Shell is no longer maintained.  Please switch over to Open Shell.  Latest release of that is 4.4.191.
