### ISSUE TITLE
Scoop Support

### ISSUE THREAD

**Issue by pstaszko** [valinet/ExplorerPatcher#2628]
Is there any reason not to make a Scoop manifest for Explorer Patcher? It looks like it might be relatively easy. I might take a crack at it for myself and am wondering if it would be worth submitting to the main scoop archive or whatever.

**Comment by pyrates999** [comment]
Go ahead.  Anyone can contribute as it is open source.

**Comment by pstaszko** [comment]
I have the install part working, but I'm not sure what it takes to do an uninstall. Is there a command line parameter for that in ep_setup.exe?
