### ISSUE TITLE
Windows 10 Windows Switcher - Arrow keys non-functional when holding Alt

### ISSUE THREAD

**Issue by ChronSyn** [valinet/ExplorerPatcher#263]
**Describe the bug**

When using the Windows 10 style window switcher, the arrow keys do not function when the window switcher interface is open

**To Reproduce**

1. Open the explorer patcher settings UI

2. Click on 'Window switcher'

3. Select 'Window Switcher (Alt + Tab) style *', and set it to 'Windows 10'

4. Restart file explorer (either through the UI, or via task manager or any other method)

5. Once Windows explorer has restarted, press alt + tab to show the window switcher

6. Press the arrow keys and note that they do not allow selecting/highlighting/navigating between windows in the UI

**Expected behavior**

I expect to be able to select different application windows from the alt+tab interface using the arrow keys.

**Environment**

 - Windows Version: Windows 11 Pro 22000.282

 - ExplorerPatcher Version: 22000.282.32.4

**Additional context**

The arrow keys function correctly when using the Windows 11 style window switcher.

**Comment by valinet** [comment]
Well, it’s simply not current functionality. The arrow keys work if you invoke the switcher with Ctrl+Alt+Tab which just keeps it on screen. If you test there, you see they work, this has just been recently implemented. Problem is, I don’t know how to make it work in a low overhead way when still holding Alt when normally invoking, as I simply do not get messages on the window when pressing the arrow keys. If I were to get those, the thing would work already. Thus, I paused hacking something in this area as well until I figure out how to do it properly. If you know or find a way or figure out what’s going on, we can speed up and add that it and have it enabled there as well. As I said, the support is there, it just misses this link at the moment.

Thanks

**Comment by valinet** [comment]
Fixed in latest release. Keys now work correctly when switcher is shown when holding the `ALT` key.
