### ISSUE TITLE
Explorer pacther refresh click boton right mouse

### ISSUE THREAD

**Issue by martinhodfranco** [valinet/ExplorerPatcher#2632]
When I right-click on a file or on the desktop, the explorer reinstalls. I already reinstalled and the problem continues.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

please close this

**Comment by Amrsatrio** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218
