### ISSUE TITLE
Copilot

### ISSUE THREAD

**Issue by waeemo** [valinet/ExplorerPatcher#2634]
can't enable Copilot and Widgets  in taskbar 
thanks

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by waeemo** [comment]
windows 11 pro 23H2 (22631.2861)
Explorer Patcher 22621.2861.62.2

taskbar style :widows 10 (if choose windows 11 can't add toolbar to tasbar)
I enable Copilot and Widgets in "more taskbar options in setting app "
start button style: windows 11
combine Taskbar icons :always
start menu style : windows 11

I didn't install any tools that modifies the UI of windows

and when press search button it is apear up. can't show down as windows 11 by default
can you add all options that exist when choose :'windows 10" in Taskbar style to options if I choose windows 11 because I just keep all options like widows 11 except toolbar to add computer shortlik and du meter tools
thaks

**Comment by ARestrepo228** [comment]
> can't enable Copilot and Widgets in taskbar thanks

those options are not available on the windows 10 taskbar

**Comment by pyrates999** [comment]
Windows 10 taskbar doesn't have widgets as far as I know because that is a windows 11 taskbar only feature.
It did have gadgets from left over windows 7 code, but that code was removed in windows 10 before windows 11 was released.

As for copilot, that is something that is just being added to windows 10.  It would make little sense for MS to then add it to the windows 10 taskbar code in windows 11.

**Comment by waeemo** [comment]
ok thank you
can you keep windows 11 taskbar  as it and add option to add toolbar

**Comment by pyrates999** [comment]
option to add what toolbar?

**Comment by waeemo** [comment]
the same toolbar that exist in windows 10 (I want to add m computer and Du meter toolbar) 
meaning I want to let every thing as it in widows 11 and add Du meter and my computer to taskbar
![Screenshot 2024-01-03 082532](https://github.com/valinet/ExplorerPatcher/assets/115794189/ce6ba105-d6fd-4612-800f-2a1dbdffb480)
thanks

**Comment by pyrates999** [comment]
Adding custom toolbars is beyond what EP is for, sorry.

**Comment by Amrsatrio** [comment]
The Copilot button is not available on the Windows 10 taskbar of Windows 11. We may have plans to add it, but not in the short time frame. Closing this for now.

**Comment by Kirshi912** [comment]
ah, if someone really need it (copilot). keep this in mind (windows + C)

**Comment by YKefasu** [comment]
https://github.com/valinet/ExplorerPatcher/issues/2866#issuecomment-2019126665
