### ISSUE TITLE
Can multiple tabs in a same program be moved separately?

### ISSUE THREAD

**Issue by lijian12345** [valinet/ExplorerPatcher#2635]
In current version, many tabs in a same program can only be moved in the meantime like this:
![动画](https://github.com/valinet/ExplorerPatcher/assets/26590220/591d582f-e986-4cf8-a554-ee3d0df61c96)

so I wonder if multiple tabs in a same program can be moved separately?

**Comment by pyrates999** [comment]
That is beyond what EP is made for.
