### ISSUE TITLE
v22621.2861.62.2 - Explorer process keeps opening&crashing 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [valinet/ExplorerPatcher#2637]
I got a very similar issue to this one:
https://github.com/valinet/ExplorerPatcher/issues/2355

Except this time the open&crash occurs automatically, repeatedly . Got it after purchasing a new PC.

This means Explorer process restarts every second. I can't reach the properties of "Explorer Patcher" via the taskbar (it gets restarted too). I barely succeeded to kill Explorer so it won't restart itself.
What should I do? I tried to remove "Explorer Patcher" by opening "control panel" via the task-manager app, and tried to restart, and it still occurs. Somehow I also still see "Explorer Patcher" window telling me I should probably remove it:

![image](https://github.com/valinet/ExplorerPatcher/assets/5357526/1dec18c0-dfa1-45d4-9085-13a1546c867f)

This started after I've set some settings but forgot about the workaround. I think what caused it is the "file explorer"->"Disable the windows 11 context menu".

Any way perhaps to reset this via some command that I can just run? Or to get to the "Explorer patcher" properties window without having Explorer running at all (no taskbar)?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 OK sorry about that. It's probably very similar to before though. A bit hard this time as there is no Explorer at all now. I have to do it all via task-manager.
For "winver" , I got this:
"version 21H2 (OS build 22000.2538) "
Windows 11 home.

As for the apps that I've installed, it's the same as before, except for "Mica for everyone" which I haven't installed yet:
7+TT, OpenShell. 
I also use QTTabBar, but this is for a toolbar.

About the settings, I can't reach it because I can't be so quick to reach the taskbar, right click, open properties and go over all of them - all in one second (and the window will probably be destroyed).

What I can tell you is that I've enabled the setting I've mentioned, of "disable the windows 11 context menu", and I restarted the explorer process after that.
Another thing I changed is just "remember last used section in this window", but that shouldn't cause issues.
I don't think I changed anything more. If so, maybe very few.

**Comment by AndroidDeveloperLB** [comment]
Seems after I removed them all, it became fine...
Had to go to "control panel" and do it, and then restart the OS.
Weird thing is that the context menu is now full, despite Explorer-patcher being removed...

**Comment by pyrates999** [comment]
Please try updating to Windows 11 version 22H2 or 23H2 as EP is not tested on 21H2.

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 How odd. Both PCs say they have the latest version of Windows.
Isn't  22H2 newer than 21H2 ? How do I update to those you mentioned?

I hope this will solve the issue. I will check what you wrote later. If you have link for me, please share it

**Comment by pyrates999** [comment]
If these are work computers, they may require them to stay on 21h2.

If not, you can go here to download windows 11 to then update it to 23h2: https://www.microsoft.com/en/software-download/windows11

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 OK I updated to it, re-installed the open-shell addon, and the issue came back.
Maybe I should try a different alternative. The main reason I use it is for its start-menu.
The rest of its features aren't so important for me.

Can I send you a video of the issue, but in private? I have the Twitter chat with you from last time...

**Comment by pyrates999** [comment]
I never talked to you on twitter.  To reset EP settings, open the EP properties application, go to about, and click on restore default settings.

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 Oh I talked with someone else:
https://github.com/valinet/ExplorerPatcher/issues/2355#issuecomment-1780953498

Sorry about this. I can send you in various ways if you wish.

About the version of EP, it's 22621.2861.62.2

I tried to reset to default and then install open-shell. Still same issue.
Maybe I will need to dig into the registry (and file system) and find some traces of open-shell. Maybe need to remove them as maybe the uninstaller doesn't work well for it.

**Comment by pyrates999** [comment]
What is the version of open shell you're installing?

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 The version that I'm installing of Open-Shell is 4.4.191:
https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.191

**Comment by pyrates999** [comment]
Ok, that is the latest release.

Let's try the following:

1. uninstall explorer patcher by trying what is documented here: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To#how-to-uninstall
2. uninstall open shell
3. run regedit and delete the following:
- [ ] Computer\HKEY_CURRENT_USER\SOFTWARE\ExplorerPatcher
- [ ] Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher
4. reboot
5. install EP
6. install open shell

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 Still got this issue.
I wonder if I can remove possible traces of open-shell.
I think it happened after importing my settings from my previous PC.
Can I send you the settings I've imported? Maybe you can reproduce it after that.

**Comment by pyrates999** [comment]
This is the only registry entry for open shell that I could find: HKLM\Software\OpenShell\StartMenu\Settings

So uninstall open shell and delete that.  Then install open shell again.

**Comment by pyrates999** [comment]
Please wait for a developer to respond.

**Comment by AndroidDeveloperLB** [comment]
I decided to reset the OS as it also crashed in some Google Drive folder for some reason.
Also I decided to send the PC to the lab, but of course for a different reason (it made weird noise every 2 minutes or so).

**Comment by pyrates999** [comment]
Sounds like hardware issues then.

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 The sound? yes. But the issue I've explained here... I don't think so.

**Comment by pyrates999** [comment]
More like ram and cpu hardware issues.  I would boot into the memory tester to verify the ram and cpu is ok.

**Comment by AndroidDeveloperLB** [comment]
@pyrates999 I will let the lab decide.

**Comment by Amrsatrio** [comment]
As what you've discovered, please revert all of your changes made using ViVeTool. Disabling the tabs feature flag now results in explorerframe refusing to start at all.

**Comment by AndroidDeveloperLB** [comment]
@Amrsatrio Too late for this. After I got back the PC and I've reset it, all works well now, including what I did with ViVeTool
