### ISSUE TITLE
How to revert it?

### ISSUE THREAD

**Issue by Rueruehere** [valinet/ExplorerPatcher#2646]
I would like to know how to go back to Windows 11 theme. I can't find it under add or remove nor in the background running programs on the taskbar

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please explore the Properties window yourself. Access it by right clicking the taskbar or searching ExplorerPatcher through the start menu. The option to revert to the Windows 11 taskbar is available there under the Taskbar section. Issues are for issues only not for inquiries.
