### ISSUE TITLE
Option to hide certain windows in Window Switcher

### ISSUE THREAD

**Issue by AstudilloMarillo** [valinet/ExplorerPatcher#2647]
I'd love the option to (permanently) hide certain windows from the Window Switcher. As an example, I have Epic Pen running all the time and have global shortcuts that make me immediately make live annotations using it. For that to work it has to continuously run in the background and since it kinda creates a transparent full screen layer it shows up in the Window Switcher (4 times even if you don't have 'Group windows of the same app' enabled). I never have any need to be able to switch to any of those windows, so I'd love to just be able to hide it.

**Comment by pyrates999** [comment]
Look at windhawk and creating your own mod for it.

**Comment by AstudilloMarillo** [comment]
> Look at windhawk and creating your own mod for it.

I do use Windhawk, so I checked if there was any existing mod that does this, but unfortunately not. I wouldn't know how to make it myself, unfortunately.

**Comment by pyrates999** [comment]
You can always try to learn.

**Comment by AstudilloMarillo** [comment]
> You can always try to learn.

Right now, I have a feature request for this already existing application. If it gets rejected, that's perfectly alright. I don't have the time to learn the skill of modding this myself at this moment in my life.
