### ISSUE TITLE
Buggy Taskbar when multiple windows with labels are open.

### ISSUE THREAD

**Issue by hemanth4121** [valinet/ExplorerPatcher#2650]
![image](https://github.com/valinet/ExplorerPatcher/assets/70093629/858f420a-5bac-4159-b9b9-ac5c8df45b45)
How do I reduce the huge gap visible towards the right side of the taskbar overflow menu? It's very inconvenient.

**Comment by pyrates999** [comment]
try 7+ taskbar tweaker and windhawk.

**Comment by Amrsatrio** [comment]
At the moment ExplorerPatcher does not modify the Windows 11 taskbar therefore this is not considered as an issue.

**Comment by raminmat** [comment]
Related, for anyone researching EP taskbar overflow behavior: a root-cause analysis of how the vertical taskbar handles overflow (extra buttons are laid into real layout columns positioned exactly one taskbar-width off-screen, and with centered alignment they never re-flow back) plus a workaround and a small free auto-recovery tool is in #3920: https://github.com/valinet/ExplorerPatcher/issues/3920#issuecomment-4942509567
