### ISSUE TITLE
Add ability to resize taskbar for multiple rows

### ISSUE THREAD

**Issue by MiddleSiggy** [valinet/ExplorerPatcher#2651]
Is it possible to add the feature to allow us to resize the taskbar again and get 2 rows of icons?

Thank you

**Comment by pyrates999** [comment]
This is for windows 10, but it's the same for windows 11: https://www.customguide.com/windows-10/move-and-resize-the-taskbar

**Comment by MiddleSiggy** [comment]
Thank you, I had too many icons so finding an empty space was... not easy.. that worked.

**Comment by Almaric78** [comment]
Thank you very much, I thought it wasn't possible, and in fact it is, we can put this wonderful bar in 2 rows! 👍

**Comment by meerable** [comment]
What about a vertical taskbar with multiple columns? I have not found a solution for this. I created a feature request #4498
