### ISSUE TITLE
Toolbar size options too few, cannot adjust the size to middle, only big and small

### ISSUE THREAD

**Issue by joshhu** [valinet/ExplorerPatcher#2652]
Hi, I am using EP and very happy with that. The only thing that keeps bothering me it that the size of toolbar. I have built a folder to store some frequently used shortcuts and added to toolbar. However the icon size of the tool bar is either too big or too small. I can change the toolbar icon size by toolbar menu icon size
![image](https://github.com/valinet/ExplorerPatcher/assets/10594453/7bd6e825-aa42-47d2-8895-d6b44bd1a2b6)

The result is either the icons are too big or too small. 
![image](https://github.com/valinet/ExplorerPatcher/assets/10594453/be4b4e7b-69c8-4e87-b1f6-c697dec4b8d4)
![image](https://github.com/valinet/ExplorerPatcher/assets/10594453/ca300292-9226-4dd9-a206-26f53e00a335)

I tried to find the value to adjust all over and googled it almost everywhere, I still cannot do it. I tried the windows registry and no luck. Can the function be added to EP? 

Thank you.

I am using Windows 11 Professional.

**Comment by pyrates999** [comment]
https://softkeys.uk/blogs/blog/how-to-make-taskbar-icons-smaller-windows-11

**Comment by tallman69** [comment]
@joshhu 
In Windows 11 the icon size option for toolbars in the windows 10 taskbar is part of Microsoft's code tor the windows 10 taskbar.  If you have a Windows 10 compute, you will see that the only icon size options for taskbar toolbars is Large or Small.  There is no setting in EP to change the toolbar icon size.  That option may be available in other taskbar customization apps.

**Comment by joshhu** [comment]
> https://softkeys.uk/blogs/blog/how-to-make-taskbar-icons-smaller-windows-11

All the settings that article mentioned are not there. not working at all

**Comment by tallman69** [comment]
Yes, the settings are no longer there. According to this article those settings were removed starting with build 22621.1343:

https://www.elevenforum.com/t/change-size-of-taskbar-icons-in-windows-11.45/

The article also explains how to change the icon size for the windows 11 taskbar.  However, the Windows 11 taskbar does not support toolbars, and since you are using a toolbar on your taskbar that means that you are using the Windows 10 toolbar.  From what I have found the Windows 10 taskbar only had two icon sizes available, large and small:

https://www.tenforums.com/tutorials/25233-use-large-small-taskbar-buttons-windows-10-a.html

**Comment by joshhu** [comment]
> Yes, the settings are no longer there. According to this article those settings were removed starting with build 22621.1343:
> 
> https://www.elevenforum.com/t/change-size-of-taskbar-icons-in-windows-11.45/
> 
> The article also explains how to change the icon size for the windows 11 taskbar. However, the Windows 11 taskbar does not support toolbars, and since you are using a toolbar on your taskbar that means that you are using the Windows 10 taskbar. From what I have found the Windows 10 taskbar only had two icon sizes available, large and small:
> 
> https://www.tenforums.com/tutorials/25233-use-large-small-taskbar-buttons-windows-10-a.html
> 
> I checked my Windows 10 laptop, and it indeed only has the large and small icon options for the taskbar. Also changing the taskbar icon size does not change the size of the icons on my Quich Launch toolbar. As you have found, the toolbars icon size is controlled by the setting you showed in you first post.

A slim chance is that whenever I upgrade NVidia driver, before rebooting, the size of toolbar icons becomes somewhere between large and small, that's why I think it is adjustable.
