### ISSUE TITLE
Settings button is missing in start menu

### ISSUE THREAD

**Issue by goshante** [valinet/ExplorerPatcher#2653]
Settings button (that is always on the left corner of menu) just randomly disappeared from "Windows 10" start menu. How to bring it back?

**Comment by pyrates999** [comment]
First reboot.

Then please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by xiurenfuwo** [comment]
Same problem.
Have rebooted.
MS version 22621.2861,latest explore patcher and default settings.
Traffic monitor installed.

**Comment by goshante** [comment]
This problem is for the last month, rebooted over 100 times I think.
Windows 11 22H2 OS Build 22621.2283
Don't use any other software that affects my UI
Issue is on your side.

**Comment by pyrates999** [comment]
Please post explorer patcher version.

**Comment by Amrsatrio** [comment]
Add back the settings button through Settings > Personalization> Start > Choose which folders to appear in Start. This is because in 22621.2134 the storage location for the folders thing has moved in the registry.
