### ISSUE TITLE
Bulk Rename Utility crashing with most recent update

### ISSUE THREAD

**Issue by martinmain** [valinet/ExplorerPatcher#2655]
With the recent update, it is crashing an application I use to bulk rename files in a directory and throwing the following errors, the earlier revision was not doing this.

//=====================================================
Exception report created by Bulk Rename Utility
Version details: 3.4.4.0 64-bit
System details: Windows - MajorVersion : 10 , MinorVersion : 0, ProductType : 1, ServicePack : 0.0
//=====================================================

Exception code: C0000005 ACCESS_VIOLATION
Fault address:  9C22D283 01:0000C283 C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll

Call stack:
Address   Frame     Function            SourceFile
9C22D283  0521B6C0  0001:0000C283 C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
9C23C9DC  0521B740  0001:0001B9DC C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
9C24001E  0521BEF0  0001:0001F01E C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
9C2448F7  0521CDE0  0001:000238F7 C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
C65A20FB  0521CF10  0001:000310FB C:\WINDOWS\System32\combase.dll
C65A2060  0521CF80  0001:00031060 C:\WINDOWS\System32\combase.dll
C65A1EE0  0521D0C0  0001:00030EE0 C:\WINDOWS\System32\combase.dll
C65A1DE1  0521D100  0001:00030DE1 C:\WINDOWS\System32\combase.dll
C65A1D4F  0521D130  0001:00030D4F C:\WINDOWS\System32\combase.dll
C65A2CEA  0521D1C0  0001:00031CEA C:\WINDOWS\System32\combase.dll
C65A3930  0521D340  0001:00032930 C:\WINDOWS\System32\combase.dll
C65A13DC  0521D3D0  0001:000303DC C:\WINDOWS\System32\combase.dll
C65A2EAC  0521D480  0001:00031EAC C:\WINDOWS\System32\combase.dll
C664C548  0521D4D0  0001:000DB548 C:\WINDOWS\System32\combase.dll
C6653D3C  0521D520  0001:000E2D3C C:\WINDOWS\System32\combase.dll
C6649752  0521D5B0  0001:000D8752 C:\WINDOWS\System32\combase.dll
C65A3794  0521D600  0001:00032794 C:\WINDOWS\System32\combase.dll
C65A13DC  0521D690  0001:000303DC C:\WINDOWS\System32\combase.dll
C65A6568  0521D730  0001:00035568 C:\WINDOWS\System32\combase.dll
C65A13DC  0521D7C0  0001:000303DC C:\WINDOWS\System32\combase.dll
C65B2DA1  0521E5C0  0001:00041DA1 C:\WINDOWS\System32\combase.dll
C65B238E  0521E6F0  0001:0004138E C:\WINDOWS\System32\combase.dll
C65B219C  0521E7D0  0001:0004119C C:\WINDOWS\System32\combase.dll
C2AE82CC  0521E810  0001:000472CC C:\WINDOWS\SYSTEM32\apphelp.dll
C36754BA  0521ED20  0001:001444BA C:\WINDOWS\SYSTEM32\windows.storage.dll
C37D4DAC  0521ED90  0001:002A3DAC C:\WINDOWS\SYSTEM32\windows.storage.dll
C37EB092  0521F180  0001:002BA092 C:\WINDOWS\SYSTEM32\windows.storage.dll
C36994ED  0521F2A0  0001:001684ED C:\WINDOWS\SYSTEM32\windows.storage.dll
C367EEDE  0521F430  0001:0014DEDE C:\WINDOWS\SYSTEM32\windows.storage.dll
C36994ED  0521F550  0001:001684ED C:\WINDOWS\SYSTEM32\windows.storage.dll
C3635055  0521F630  0001:00104055 C:\WINDOWS\SYSTEM32\windows.storage.dll
C36DF711  0521F690  0001:001AE711 C:\WINDOWS\SYSTEM32\windows.storage.dll
C363B96C  0521FBB0  0001:0010A96C C:\WINDOWS\SYSTEM32\windows.storage.dll
C3B441F5  0521FE10  0001:006131F5 C:\WINDOWS\SYSTEM32\windows.storage.dll
C3B4423E  0521FE40  0001:0061323E C:\WINDOWS\SYSTEM32\windows.storage.dll
C8156CED  0521FF20  0001:00005CED C:\WINDOWS\System32\shcore.dll
C7AD257D  0521FF50  0001:0001157D C:\WINDOWS\System32\KERNEL32.DLL
C82EAA58  0521FFD0  0001:00059A58 C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by martinmain** [comment]
I have gone back through the revisions and all is fine again with this utility on 2261-2428-59-1 except the start menu won't left align which was why I upgraded explorerpatcher

**Comment by pyrates999** [comment]
Please submit this to the github for Bulk Rename Utility.

**Comment by martinmain** [comment]
Having posted on Bulk Rename Utility site, unlikely they will do anything since their software is a stable release from July 2022 which works on Windows systems without ExplorerPatcher, indeed it works fine on the ExplorerPatcher release from October 2023 I mention, something in subsequent releases is in conflict

**Comment by pyrates999** [comment]
You should post the version of EP that it works on.

**Comment by pyrates999** [comment]
I think I found your post.  Here's some details you should add:

1. link to this github project
2. the output you get when you run it with the current release of EP

**Comment by martinmain** [comment]
I did earlier it works up to 59

Sent from my iPad

On 5 Jan 2024, at 17:46, pyrates999 ***@***.***> wrote:

﻿


You should post the version of EP that it works on.

**Comment by martinmain** [comment]
In September 2023,  I allowed my Windows 10 Pro installation to upgrade to Windows 11

Immediately I disliked the scale of the taskbar and the start menu and opened Winaero Tweaker which referred me to the ExplorerPatcher gitthib site which I duly installed and made some amendments to closer reflect my Windows 10 configuration

In late December after a Windows 11 upgrade (Version 10.0.22631 Build 22631), the start menu which had been previously left aligned was central again despite the left alignment setting

I opened the ExplorerPatcher and allowed this to upgrade to current revision and all was good with the Start menu left alignment again.

The other day I tried to open my Bulk Rename Utility (https://www.bulkrenameutility.co.uk) from the context menu to amend a batch of media files for my Plex server and nothing opened; I then the tried to open the application directly and nothing, I eventually opened the app as System Administrator which created the following log report

/=====================================================
Exception report created by Bulk Rename Utility
Version details: 3.4.4.0 64-bit
System details: Windows - MajorVersion : 10 , MinorVersion : 0, ProductType : 1, ServicePack : 0.0
//=====================================================

Exception code: C0000005 ACCESS_VIOLATION
Fault address: 9C22D283 01:0000C283 C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll

Call stack:
Address Frame Function SourceFile
9C22D283 0521B6C0 0001:0000C283 C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
9C23C9DC 0521B740 0001:0001B9DC C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
9C24001E 0521BEF0 0001:0001F01E C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
9C2448F7 0521CDE0 0001:000238F7 C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
C65A20FB 0521CF10 0001:000310FB C:\WINDOWS\System32\combase.dll
C65A2060 0521CF80 0001:00031060 C:\WINDOWS\System32\combase.dll
C65A1EE0 0521D0C0 0001:00030EE0 C:\WINDOWS\System32\combase.dll
C65A1DE1 0521D100 0001:00030DE1 C:\WINDOWS\System32\combase.dll
C65A1D4F 0521D130 0001:00030D4F C:\WINDOWS\System32\combase.dll
C65A2CEA 0521D1C0 0001:00031CEA C:\WINDOWS\System32\combase.dll
C65A3930 0521D340 0001:00032930 C:\WINDOWS\System32\combase.dll
C65A13DC 0521D3D0 0001:000303DC C:\WINDOWS\System32\combase.dll
C65A2EAC 0521D480 0001:00031EAC C:\WINDOWS\System32\combase.dll
C664C548 0521D4D0 0001:000DB548 C:\WINDOWS\System32\combase.dll
C6653D3C 0521D520 0001:000E2D3C C:\WINDOWS\System32\combase.dll
C6649752 0521D5B0 0001:000D8752 C:\WINDOWS\System32\combase.dll
C65A3794 0521D600 0001:00032794 C:\WINDOWS\System32\combase.dll
C65A13DC 0521D690 0001:000303DC C:\WINDOWS\System32\combase.dll
C65A6568 0521D730 0001:00035568 C:\WINDOWS\System32\combase.dll
C65A13DC 0521D7C0 0001:000303DC C:\WINDOWS\System32\combase.dll
C65B2DA1 0521E5C0 0001:00041DA1 C:\WINDOWS\System32\combase.dll
C65B238E 0521E6F0 0001:0004138E C:\WINDOWS\System32\combase.dll
C65B219C 0521E7D0 0001:0004119C C:\WINDOWS\System32\combase.dll
C2AE82CC 0521E810 0001:000472CC C:\WINDOWS\SYSTEM32\apphelp.dll
C36754BA 0521ED20 0001:001444BA C:\WINDOWS\SYSTEM32\windows.storage.dll
C37D4DAC 0521ED90 0001:002A3DAC C:\WINDOWS\SYSTEM32\windows.storage.dll
C37EB092 0521F180 0001:002BA092 C:\WINDOWS\SYSTEM32\windows.storage.dll
C36994ED 0521F2A0 0001:001684ED C:\WINDOWS\SYSTEM32\windows.storage.dll
C367EEDE 0521F430 0001:0014DEDE C:\WINDOWS\SYSTEM32\windows.storage.dll
C36994ED 0521F550 0001:001684ED C:\WINDOWS\SYSTEM32\windows.storage.dll
C3635055 0521F630 0001:00104055 C:\WINDOWS\SYSTEM32\windows.storage.dll
C36DF711 0521F690 0001:001AE711 C:\WINDOWS\SYSTEM32\windows.storage.dll
C363B96C 0521FBB0 0001:0010A96C C:\WINDOWS\SYSTEM32\windows.storage.dll
C3B441F5 0521FE10 0001:006131F5 C:\WINDOWS\SYSTEM32\windows.storage.dll
C3B4423E 0521FE40 0001:0061323E C:\WINDOWS\SYSTEM32\windows.storage.dll
C8156CED 0521FF20 0001:00005CED C:\WINDOWS\System32\shcore.dll
C7AD257D 0521FF50 0001:0001157D C:\WINDOWS\System32\KERNEL32.DLL
C82EAA58 0521FFD0 0001:00059A58 C:\WINDOWS\SYSTEM32\ntdll.dll

I tried to reinstall the Bulk Rename Utility several times including the context menu selection but this yielded no positive results.

I then tried installing earlier versions of ExplorerPatcher (62>61>60) until Bulk Rename Utility started working again with the 59 version (I did not bother with any pre-release revisions).

Bulk Rename Utility is currently working, only caveat I is am living with a centre aligned start menu, otherwise ExplorerPatcher is performing well.

**Comment by pyrates999** [comment]
I meant for you to add that to your post on the Bulk Rename Utility forum.

**Comment by Amrsatrio** [comment]
If you unregister EP as shell extension, does it work?

**Comment by martinmain** [comment]
I have never registered EP as a shell extension

**Comment by Amrsatrio** [comment]
Since this software is available for free for non commercial usage, I'll begin investigating shortly.

**Comment by Amrsatrio** [comment]
Are you using the latest EP? I tried matching your crash logs with this release https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2861.62.2_9b68cc0 but they don't match.

**Comment by martinmain** [comment]
Hi Amr,

 
I am using release 59 at the moment which works fine in relation to the Bulk Rename Utility. I worked backwards through the 62, 61, and 60 release versions, so the crash log could have been from 61 or 60 and not 62. I didn’t load any of the pre-release revisions.

**Comment by martinmain** [comment]
> Since this software is available for free for non commercial usage, I'll begin investigating shortly.

Hi Amr, just wondering if you were able to replicate the problem?

**Comment by Amrsatrio** [comment]
Unfortunately I wasn't able to replicate the problem :(

**Comment by martinmain** [comment]
Interesting, I think I will go ahead and allow EP to upgrade and see what happens

**Comment by martinmain** [comment]
Bizzarely, it seems to be working fine again and I have my start menu left aligned again :)
