### ISSUE TITLE
Window titles are not hidden and stacked.

### ISSUE THREAD

**Issue by Schlapp7** [valinet/ExplorerPatcher#2658]
Greetings,

I have set in the Windows settings that the titles of the windows and programs should be hidden:
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/c6eef903-a3ea-4972-ad2e-f421bb81f3b8)

Unfortunately, ExplorerPatcher does not take this into account:
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/6ddecd7f-2b66-4d8b-8d63-42d524c63fb3)

This is what it should look like:
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/f6a01b45-47cc-4eb3-a322-9711bcd637cd)

I also noticed that the windows that belong to a program, such as: Explorer cannot be merged or stacked:
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/33f28b22-4781-42bf-99a7-c7a227d54a77)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/09226809-93ab-4ed0-a1d6-a149e36df3a1)

I hope the problem can be solved.

Best regards.

Operating system : Windows 11 Pro
Version : 10.0.22621.2861 / 22H2
Version of the program : 22621.2861.62.2
System language : German

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Schlapp7** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/277f8793-3767-4624-b539-40e0a2cd0e31)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/d087b3c2-74bc-48b4-98c8-a1966bf4ab45)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/1a067641-4780-428b-be11-ff2f25bd4984)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/859e6747-c0b8-4ad6-9a7a-66015ba93aaa)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/1b792e77-5846-4790-9429-a85c7aad339e)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/803836bd-8d9b-4d7d-bf1c-5bfadf615d9a)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/bc1fec08-5204-4638-a9f8-767b4c2d53dc)
![image](https://github.com/valinet/ExplorerPatcher/assets/45624526/6b8b6e59-e929-4d02-8280-2f3b5f293838)

I have not installed any other programs that change the UI.

**Comment by pyrates999** [comment]
if you are using the windows 11 taskbar, Microsoft intended to show the labels beside each icon in the taskbar.

https://www.bleepingcomputer.com/news/microsoft/windows-11s-new-never-combine-icons-feature-is-almost-usable/

**Comment by Amrsatrio** [comment]
There is an option for that in the Taskbar section. It's set to Never combine by default. Please change it to Always combine.

**Comment by Schlapp7** [comment]
Greetings,

As I mentioned at the beginning, this setting has already been made in the settings.

Also supported by a screenshot.

**Comment by Schlapp7** [comment]
Forget it.
I overlooked the setting option for this in ExplorerPatcher.

I apologize.
