### ISSUE TITLE
partially broken on build 2591.1000

### ISSUE THREAD

**Issue by hanifnau092** [valinet/ExplorerPatcher#2659]
windows 10 start menu does not work on build 2591.1000
[Uploading Screen Recording - Made with FlexClip.webm…]()

**Comment by pyrates999** [comment]
That's not a valid windows version and build.  Please run winver to find out.

**Comment by minenightowl** [comment]
Most likely talking about 22593.1 but that's W11

Hani please press the Windows key + R, type winver, and hit enter, then please let us know or send a screenshot of your Version and OS Build number, EX:
![image](https://github.com/valinet/ExplorerPatcher/assets/29973351/1e9c6bfb-d786-4810-9e3c-358ab4626234)

**Comment by hanifnau092** [comment]
![Uploading Screenshot 2024-01-07 061512.png…]()

**Comment by Amrsatrio** [comment]
Windows 10 start menu is no longer available in 25921+. We have no plans in bringing it back.
