### ISSUE TITLE
Is it possible to add a setting button here?

### ISSUE THREAD

**Issue by HolyDamn9527** [valinet/ExplorerPatcher#2660]
![image](https://github.com/valinet/ExplorerPatcher/assets/155826848/da69396e-3a13-45ca-bb1d-de0d0bb7d269)

Is it possible to add a setting button at the position where the red circle marked? Because I am accustomed to use it in Windows 10

**Comment by pyrates999** [comment]
That is beyond what EP is for.

**Comment by Amrsatrio** [comment]
Add it in the page where you do the same for the Windows 11 start menu.
