### ISSUE TITLE
Drag and drop on the address bar in File Explorer

### ISSUE THREAD

**Issue by TheMNSTR** [valinet/ExplorerPatcher#2663]
Hi,

In the September patch, Microsoft removed the drag and drop on address bar feature in File Explorer.
See also here: https://www.reddit.com/r/Windows11/comments/174shxq/new_update_doesnt_let_me_drag_files_onto_the/

Do you think it would be possible for you to bring it back somehow?
I don't know about others, but I miss it dearly.

**Comment by pyrates999** [comment]
Unless the code exists still, it could be.  Otherwise it cannot be re-enabled.

**Comment by Amrsatrio** [comment]
You can do it by switching the command bar to Windows 10 or Windows 7. I recommend the Windows 7 command bar because window position saving works with it.
