### ISSUE TITLE
Gallery Feature with Classic Explorer Interfaces (i.e. Ribbion UI and Win7 Command Bar)

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#2667]
Here I found it bymistakenly, when we switch from win11 Command bar to classic Ribbion UI and Command Bar without restarting explorer, we can have "Gallery" feature. But the bugs are : 
1. (Ribbion UI) Only "Back" button is glitched. You can't use back button.
2. (Command Bar 7) Explorer crashes while using "Back" button.

![image](https://github.com/valinet/ExplorerPatcher/assets/93650504/72e06026-b79d-43eb-b597-55b67a875e35)

@Amrsatrio already told me about the 2nd issue on Discord about crashing explorer with Command Bar 7. Is there any possibility to retain "Gallery" with classic explorers too.
Also, SAB is using some other method for using "Gallery" with Classic explorer. You can check it.

**Comment by Amrsatrio** [comment]
The more you compare this with SAB the more I am tired with you.

**Comment by Vipin2003** [comment]
> The more you compare this with SAB the more I am tired with you.

I'm just putting it as soon i found it 😂😂😂 No issue if cant be done.
