### ISSUE TITLE
Made system stuck on a black screen after login

### ISSUE THREAD

**Issue by slikts** [valinet/ExplorerPatcher#267]
After rebooting and logging in with ExplorerPatcher installed, my PC was just showing a black screen. Ctrl+Shift+Esc brought up the Task Manager, and trying to start explorer.exe was showing a "This application was unable to start correctly" error. I recovered the system by running `del C:\Windows\dxgi.dll` and `del %appdata%\ExplorerPatcher` from an administrator shell started from Task Manager. Many people would assume they have to reinstall, and an initial guess is that something in `%appdata%\ExplorerPatcher` got corrupted, so it's a fault with this tool for being unable to recover from corrupted data.

![image](https://user-images.githubusercontent.com/137872/140277959-950f77df-d8a8-4b46-b260-d6bd2c88d76f.png)

**Comment by valinet** [comment]
It's probably exactly this: https://github.com/valinet/ExplorerPatcher/discussions/264 which is the same as this: https://github.com/valinet/ExplorerPatcher/issues/265

> an initial guess is that something in `%appdata%\ExplorerPatcher` got corrupted, so it's a fault with this tool for being unable to recover from corrupted data.
Don't think that's actually the case.

**Comment by deletedpaula1p-cloud** [comment]
had the same thing but the pc fully stopped working
