### ISSUE TITLE
OS global font not respected

### ISSUE THREAD

**Issue by jay-ramani** [valinet/ExplorerPatcher#2670]
Explorer Patcher has never followed the OS wide font setting. For example, I have set the OS-wide font for all texts (via [Winaero Tweaker](https://winaerotweaker.com/)) to Ubuntu Condensed. However, Explorer Patcher disregards that and sets its own custom font instead. See the attached screenshot.

OS version: Windows 11 22H2
Build Number: 22621.2861
Explorer Patcher version: 22621.2861.62.2

![Bug - Insconsistent Font](https://github.com/valinet/ExplorerPatcher/assets/7327430/3ea3411a-b8f5-4767-8b90-32e1b1ee2490)

**Comment by Amrsatrio** [comment]
It is a WebView of a portion of the Google search results page for "weather", so Google decides which font to use.

**Comment by jay-ramani** [comment]
Thanks for the clarification. Is there no way to override the font?

Cheers,
Jay

**Comment by pyrates999** [comment]
Probably not.
