### ISSUE TITLE
New Windows 11 build not supported?

### ISSUE THREAD

**Issue by oznetmaster** [valinet/ExplorerPatcher#2671]
The latest Windows 11 release build is 22631.3007.

It is not listed as supported, and it gives an error message when it goes to download symbols.

**Comment by Amrsatrio** [comment]
Give it a day or two for symbols to be available. Anyways, in the latest EP symbols serve as a fallback method to find required stuff so it shouldn't be a big problem.

**Comment by KuanRe** [comment]
The start menu of Windows 10 is gone, and the menu of 11 is displayed with an animation of 10

**Comment by Amrsatrio** [comment]
@KuanRe I haven't updated to the latest version that just came out today, but have you tried reinstalling EP?

**Comment by pyrates999** [comment]
The windows 11 release build 22631.3007 just came out.  You're gonna have to wait for EP developers to figure out what changed with it.

**Comment by Amrsatrio** [comment]
Update: I've installed 22621.3007 and the Windows 10 start menu still works fine. So please try reinstalling EP because it looks like you've just performed a feature upgrade.

**Comment by pyrates999** [comment]
22621.3007 is windows 11 22h2, while 22631.3007 is windows 11 23h2.

**Comment by Amrsatrio** [comment]
They share the same files.

**Comment by KuanRe** [comment]
After reinstalling, my issue was resolved

> Update: I've installed 22621.3007 and the Windows 10 start menu still works fine. So please try reinstalling EP because it looks like you've just performed a feature upgrade.

**Comment by Amrsatrio** [comment]
Closing this issue as symbols for .3007 are now available.
