### ISSUE TITLE
右键任务栏显示的菜单希望可以选择性的去除部分功能

### ISSUE THREAD

**Issue by Legend-Fish** [valinet/ExplorerPatcher#2672]
<img width="253" alt="屏幕截图 2024-01-10 163023" src="https://github.com/valinet/ExplorerPatcher/assets/156165134/24a7bd25-9991-4931-9018-72e6086f941c">
有些窗口的功能对大多人并不适用，反而会显得臃肿，希望可以选择性的去除某些功能，
另外希望可以将图中的“属性”与“任务管理器(K)”调换位置，让他更像win11的样子，也更美观，多谢

**Comment by Amrsatrio** [comment]
We have no plans to add the stuff that you wanted.

**Comment by Legend-Fish** [comment]
> 有些窗口的功能对大多人并不适用，反而会显得臃肿，希望可以选择性的去除某些功能， 另外希望可以将图中的“属性”与“任务管理器（K）”调换位置，让他更像win11的样子，也更美观，多谢

Some window functions are not suitable for most people and may appear bulky. I hope to selectively remove certain functions. Additionally, I hope to swap the positions of the "Properties" and "Task Manager (K)" in the image, making it more like Win11 and more aesthetically pleasing. Thank you

**Comment by Legend-Fish** [comment]
> 我们没有计划添加您想要的内容。

Okay, thank you for your efforts

**Comment by pyrates999** [comment]
look at windhawk and the mods it provides.
