### ISSUE TITLE
Start11 compatibility

### ISSUE THREAD

**Issue by huckleberrypie** [valinet/ExplorerPatcher#268]
So for the heck of it I installed Start11 alongside this patcher. I know this isn't really ideal, but there's a bit of an issue when I right-clicked on the start orb in that the Start11 context menu is blank and incorrectly placed.

**Comment by valinet** [comment]
Can you post a screenshot?

**Comment by huckleberrypie** [comment]
Actually scratch that. Turns out that I forgot to uninstall Open Shell and that accounted for the conflict.

**Comment by valinet** [comment]
Okay, glad that you sorted it out. Thanks for reporting back.

**Comment by huckleberrypie** [comment]
> 
> 
> Okay, glad that you sorted it out. Thanks for reporting back.

No problem! :)
