### ISSUE TITLE
Crash caused by KB5032190

### ISSUE THREAD

**Issue by limit4ever** [valinet/ExplorerPatcher#2682]
After updating this patch (KB5032190), the resource manager patch keeps crashing, and it seems that it cannot be uninstalled even if I uninstall the update. Is there any way to solve it?
![%7B68CA6418-003B-4975-9086-D8FAA45C6ADE%7D](https://github.com/valinet/ExplorerPatcher/assets/130027040/f0ef104c-7f71-400b-8fc0-936cd83239c8)

**Comment by pyrates999** [comment]
Please provide more details on what the resource manager patch is.

**Comment by Amrsatrio** [comment]
Closing due to no response.
