### ISSUE TITLE
[ISSUE] Weather information is not available in some countries.

### ISSUE THREAD

**Issue by Monutchuan** [valinet/ExplorerPatcher#2683]
I think this requires more informants.
![螢幕擷取畫面 2024-01-01 180409](https://github.com/valinet/ExplorerPatcher/assets/139550892/54b61500-99f5-4f70-b584-0415db27a9c3)

**Comment by pyrates999** [comment]
Weather is provided by google and requires internet access.  If it doesn't provide weather information for your country, that can't be helped.

**Comment by Monutchuan** [comment]
> Weather is provided by google and requires internet access. If it doesn't provide weather information for your country, that can't be helped.

It does, and this only works in countries that don't block Google.

**Comment by pyrates999** [comment]
That can't be fixed by EP as this output comes from google, sorry.
