### ISSUE TITLE
[BUG] Taskbar scaling reversed for touch and connected keyboard.

### ISSUE THREAD

**Issue by Monutchuan** [valinet/ExplorerPatcher#2684]
Keyboard not connected (touch)
![螢幕擷取畫面 2024-01-12 160419](https://github.com/valinet/ExplorerPatcher/assets/139550892/0b04d0af-6c7b-4a93-be92-762ac9fcc001)
Keyboard connected
![螢幕擷取畫面 2024-01-12 160354](https://github.com/valinet/ExplorerPatcher/assets/139550892/f2cd8dcb-add7-4eb2-a1bb-bc189b81c403)

**Comment by pyrates999** [comment]
what is the bug here?

**Comment by Monutchuan** [comment]
> what is the bug here?

I'm using a Surface Pro 7, which includes a keyboard cover. Under normal circumstances (Windows 10), when the keyboard cover is removed or folded, the taskbar's icons become widely spaced to facilitate touch. After connecting the keyboard cover, the icon spacing will be normal. I'm now running ExplorerPatcher on Windows 11, using the Windows 10 taskbar, and then the problem described above occurred: the other way around. The result is the exact opposite of how things normally work. When the keyboard cover is removed or folded, the icons are at normal spacing, but after being connected, the spacing becomes wider.

**Comment by pyrates999** [comment]
Oh I see.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Monutchuan** [comment]
> Oh I see.
> 
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application.
> 
> Please include any other software you have installed that modifies the UI of windows.

winver: Windows 11 Home 23H2 (OS Build 22631.3007)
explorer patcher version: 22621.2861.62.2
settings include:
[ExplorerPatcher_22621.2861.62.2.txt](https://github.com/valinet/ExplorerPatcher/files/13929832/ExplorerPatcher_22621.2861.62.2.txt)
other ui software: not yet

**Comment by pyrates999** [comment]
Can you do screen shots of the settings you changed in EP?

**Comment by Monutchuan** [comment]
> Can you do screen shots of the settings you changed in EP?

[ScreenShot.zip](https://github.com/valinet/ExplorerPatcher/files/13929861/ScreenShot.zip)

**Comment by pyrates999** [comment]
You can drag and drop the image files here.

**Comment by Monutchuan** [comment]
> You can drag and drop the image files here.

Yeah, but files may a lot.
![1](https://github.com/valinet/ExplorerPatcher/assets/139550892/ecc38c0f-35cf-443d-9706-8ee2194a188f)
![2](https://github.com/valinet/ExplorerPatcher/assets/139550892/cb5096a2-9515-4fd4-b79c-49c4af23c08b)
![3](https://github.com/valinet/ExplorerPatcher/assets/139550892/44544aff-8cd8-40b0-b7a6-7d9568180d9d)
![4](https://github.com/valinet/ExplorerPatcher/assets/139550892/be4d15d0-9199-449b-8152-df5ee5f3692c)
![5](https://github.com/valinet/ExplorerPatcher/assets/139550892/33f2dbfc-d09d-439d-8f63-b5f7c924522d)
![6](https://github.com/valinet/ExplorerPatcher/assets/139550892/fae7161b-dd1e-455c-a906-5f7c1d800cb1)
![7](https://github.com/valinet/ExplorerPatcher/assets/139550892/ebb62fb8-c977-4346-a6a5-b8a4049e0641)
![8](https://github.com/valinet/ExplorerPatcher/assets/139550892/19e682d5-956b-4274-83d9-429ffb0d5416)

**Comment by pyrates999** [comment]
In File Explorer, untick register as shell extension and click on restart file explorer.  That can cause crashes.

https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by Monutchuan** [comment]
> In File Explorer, untick register as shell extension and click on restart file explorer. That can cause crashes.
> 
> https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

I try this, seems nothing happened.

**Comment by pyrates999** [comment]
Ok, it shouldn't be ticked anyways.

Click on **About** on the left side.  Click on **export current settings** to save your settings to a file and then click on **restore default settings** to reset EP settings.

Click on restart file explorer.

See if it still happens.

If it does, uninstall EP and reboot.  Then see if it still happens.

**Comment by PrintI8** [comment]
I have also been experiencing this issue since Windows 11 22H2. Prior to this update the scaling was correct. I have troubleshooted and it still happens. I am on a Surface Pro 8.

**Comment by Amrsatrio** [comment]
I'll try to get a 2in1 device like the Lenovo Ideapad Duet 3i and see if I can do something.

**Comment by Amrsatrio** [comment]
Reproduced the issue. 22621.3155.

**Comment by Monutchuan** [comment]
Well, I don't think this problem can be fixed, even though I provided quite a bit of information it won't be useful. Therefore, the best way is to use the current UI in the current system to avoid compatibility.

**Comment by Amrsatrio** [comment]
Please update EP and use Windows 10 (ExplorerPatcher) taskbar. It doesn't have enlarged buttons when the keyboard is detached.
