### ISSUE TITLE
[Bug] 22631.3078

### ISSUE THREAD

**Issue by LexBoosT** [valinet/ExplorerPatcher#2688]
Hello, i've some problem with 22631.3078 with latest Explorer Patcher. Impossible to go to the explorer patcher settings, when I activate the details pane it is gray and when I hide it the window becomes full transparent.
![Capture d'écran 2024-01-12 131948](https://github.com/valinet/ExplorerPatcher/assets/44103115/502ff22f-0ea0-4de5-a4bf-ec42212ecf61)

**Comment by LexBoosT** [comment]
Normal view if i quit explorer and re-open without details pane:
![Capture d'écran 2024-01-12 132044](https://github.com/valinet/ExplorerPatcher/assets/44103115/c6fe1d74-ddb4-4732-a14f-edb63464d1e4)

**Comment by LexBoosT** [comment]
22631.3007:
![image](https://github.com/valinet/ExplorerPatcher/assets/44103115/27742172-2646-48e5-93d6-257fa89880f8)

**Comment by pyrates999** [comment]
If you have classic shell installed, uninstall it. That is no longer maintained.

The replacement is open shell.

**Comment by Amrsatrio** [comment]
As this is outside EP's scope unfortunately I can do nothing about it. Sorry.
