### ISSUE TITLE
large icons in the TaskBar are invisible, only occasionally the icons appear

### ISSUE THREAD

**Issue by s3n0** [valinet/ExplorerPatcher#2690]
Hi.

**Large icons** in the TaskBar are invisible, only occasionally the icons appear (right side of the screenshot). 
However, the **small icons** in the TaskBar work correctly (left side of the screenshot). 
See the attached screenshot of both cases of TaskBars:

![preview_image](https://github.com/valinet/ExplorerPatcher/assets/13181404/c9439596-8f48-4fb5-8add-2054438538f8)

**Explorer Patch** = 22621.2861.62.2
**Windows 11** = 22621.3007

Should I simply wait for the repair ? Or where could there be a mistake ?

Thanks.

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by s3n0** [comment]
Hi.

Thanks for the response.

I do not use any other software for modifying the Windows-11 GUI. BTW this is a fresh and clean install of Windows-11.

I only changed the display scale from 100% to 122% in Windows-11. Of course, I already tried to return the scale to 100%, but that didn't help. Large icons in the taskbar are still poorly displayed - they disappear.

**I found that the fact that only the very first (large) icon in the taskbar (at the very top, on the right) works correctly.** That is that it is not lost. If I moved, for example, the TotalCommander application (icon) to the first position in the taskbar, then the TotalCommander icon worked correctly (always visible - when the application is running but also when it is not running).

And I found out another one important fact. **The disappearance of large icons in the taskbar applies only to running applications.** If the application is not running (not highlighted in the taskbar), then its icon is always visible (it does not disappear).

_Unfortunately... I have already made a lot of changes in ExplorerPatcher, because I was trying to see if the loss of large icons would not be fixed by various changes. However, this problem with disappearing large icons persists from the first launch of ExplorerPatcher + immediately after switching to the Win10 taskbar type and after moving to the right side of the screen._

**Comment by pyrates999** [comment]
Reset EP settings and start over trying to troubleshoot this.  Document the settings you change in EP so you can find out what is causing this.

I would first uninstall EP, reboot, and see if it still happens.

**Comment by Lipraty** [comment]
I believe that this issue is with Windows 11 itself. I have encountered it frequently, before installing EP, from the initial release version to the present.

**Comment by s3n0** [comment]
So I tried... 
1. resetting EP configuration - didn't help 
2. and also EP reinstall + Windows 11 reboot - didn't help

**Comment by pyrates999** [comment]
I don't think this is caused by EP and is a bug in windows.

**Comment by s3n0** [comment]
But I still left the 122% scaling in Windows-11.

However, I do not rule out that this could also be a problem.

I tested it again. Change the scale, e.g. from 122% to 123%. And the EP taskbar (on the right side of my screen + using the large icons) remained intact - remained working fine.

**Comment by pyrates999** [comment]
Uninstall EP and see if it still occurs.

**Comment by s3n0** [comment]
> Uninstall EP and see if it still occurs.

I dont know what you mean. Should I uninstall + install again ? If so... by what exact procedure ? Should I also reboot Windows 11 and so on ? Or what exactly is the procedure that you have in mind ?

Or do you mean that after uninstalling EP it will be bad even in Windows 11 ? Because everything worked OK - in Windows 11. 

My problem personaly is mainly that it is not possible to move the taskbar to the right side of the screen - in new versions of Windows 11. That's the reason why I also use this EP.

**Comment by pyrates999** [comment]
Uninstall EP and see if it occurs again.  You are to test if it happens when EP is not installed.

**Comment by s3n0** [comment]
I had it uninstalled last night for about 1 hour. Everything worked fine (without EP installed).

However, I logically only used the taskbar at the bottom of the screen. Unfortunately, new versions of Windows-11 do not allow you to move the taskbar to the right part of the screen. But this is irrelevant anyway, because EP hid the big icon even when the taskbar was at the bottom of the screen. However, the small icons also worked fine on the bottom taskbar of EP (i.e. they were not hidden).

**Comment by pyrates999** [comment]
Thank you for verifying it.  Now with EP installed again, and it set to the side of the screen, let's check what happens when using the console in explorer patcher.

Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by s3n0** [comment]
Hi. Immediately after clicking the "Enable console" option, one window appeared. However, they remained quite empty (black area). After closing this console window (by clicking on the cross in the upper right part of the windows), the new console started. I assume correctly... that closing the console window also meant an automatic restart and re-launch of the EP. So... there were also some new entries in the console window, during the start of the EP.

```
Running on Windows 11, OS Build 10.0.22621.3007.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 47780
Patched taskbar transparency in newer OS builds
ITrayUIHost = 3B2318
explorer.exe!TrayUI_CreateInstance() = 19B6DC
Setup explorer functions done
Setup uxtheme functions done
[AC] rcMonitorAssignment = 247F1
[AC] rcWorkAssignment = 248A1
[AC] blockBegin = 24806
[AC] blockEnd = 248B7
[AC] Patched!
[CC] rcMonitorAssignment = 66EFB
[CC] rcWorkAssignment = 66FC8
[CC] blockBegin = 66F13
[CC] blockEnd = 66FE1
[CC] Patched!
[TC] rcMonitorAssignment = 5B6A0
[TC] rcWorkAssignment = 5B756
[TC] blockBegin = 5B6BA
[TC] blockEnd = 5B76F
[TC] Patched!
[TV] firstCallPrep = 2F665
[TV] firstCallCall = 2F66F
[TV] Patched!
[HC] match1 = 1D56D
[HC] match2 = 1D634
[HC] writeAt = 1D22E
[HC] cleanup = 1D645-1D65A
[HC] Patched!
PenMenuSystemTrayManager::GetDynamicSystemTrayHeightForMonitor() = 45D430
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
wil::details::FeatureImpl<__WilFeatureTraits_Feature_Servicing_TaskbarMultiMon_38545217>::__private_IsEnabled() = 10BEB8
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
[Positioning] Added settings for monitor 0000000000010001 : 0
Registered Win+A, Win+B, and Win+N
Progman: 131314
Progman hook: 393863
>>> Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
0 0
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.2861.62.2.c2b7c0292fff8608"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.2861.62.2.c2b7c0292fff8608" (valid).
[Updates] Local version obtained from hash is 22622.2861.62.2.
[Updates] No updates are available.
```

Do you need to find out something more with the help of the console ?

The second attempt to close the console window did the same thing... so trying to close the console probably restarts EP. I've turned it off for now, with the help of unchecking it in the EP settings.

```
Running on Windows 11, OS Build 10.0.22621.3007.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 47780
Patched taskbar transparency in newer OS builds
ITrayUIHost = 3B2318
explorer.exe!TrayUI_CreateInstance() = 19B6DC
Setup explorer functions done
Setup uxtheme functions done
[AC] rcMonitorAssignment = 247F1
[AC] rcWorkAssignment = 248A1
[AC] blockBegin = 24806
[AC] blockEnd = 248B7
[AC] Patched!
[CC] rcMonitorAssignment = 66EFB
[CC] rcWorkAssignment = 66FC8
[CC] blockBegin = 66F13
[CC] blockEnd = 66FE1
[CC] Patched!
[TC] rcMonitorAssignment = 5B6A0
[TC] rcWorkAssignment = 5B756
[TC] blockBegin = 5B6BA
[TC] blockEnd = 5B76F
[TC] Patched!
[TV] firstCallPrep = 2F665
[TV] firstCallCall = 2F66F
[TV] Patched!
[HC] match1 = 1D56D
[HC] match2 = 1D634
[HC] writeAt = 1D22E
[HC] cleanup = 1D645-1D65A
[HC] Patched!
PenMenuSystemTrayManager::GetDynamicSystemTrayHeightForMonitor() = 45D430
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
wil::details::FeatureImpl<__WilFeatureTraits_Feature_Servicing_TaskbarMultiMon_38545217>::__private_IsEnabled() = 10BEB8
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
[Positioning] Added settings for monitor 0000000000010001 : 0
Registered Win+A, Win+B, and Win+N
Progman: 263088
Progman hook: 721905
>>> Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
0 0
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.2861.62.2.c2b7c0292fff8608"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.2861.62.2.c2b7c0292fff8608" (valid).
[Updates] Local version obtained from hash is 22622.2861.62.2.
[Updates] No updates are available.
```

**Comment by pyrates999** [comment]
When you enable console, it will keep reopening console until you disable it.  Just needed the output from the console when this occurred.  Thanks.

Please wait for a developer to respond.

**Comment by s3n0** [comment]
Ah... OK... anyway, thanks for your help and your response.

And... however... now that everything is working... there is nothing interesting (no error) to see in the console... or am I wrong ?

**Comment by pyrates999** [comment]
You must be referring to this:

![image](https://github.com/valinet/ExplorerPatcher/assets/106135298/61dcbad7-de3c-40c2-81c3-22d7cc3ef541)

Notice how Microsoft says it's **not recommended**.

**Comment by s3n0** [comment]
All right. However, this scaling of the size of objects on the screen probably did not cause my problem. I've used it before + and I'm still using it now.

As I wrote, I don't rule out a possible problem with changing the image scaling in Win-11. 

But... it works even now... when I use 122% scaling. I even pushed it to 123% yesterday and there was no change in the big EP icons. Everything works without a problem even if I try to move the taskbar to the bottom + to the right. Also, if I do other settings, the large icons remain.

_Since the very beginning of using EP, I have another / another problem, but I don't want to write it here, because it is not related to the topic. It's about the fact that I can't turn on / off the icons in the SysTray area. I see only two system ones there and I can't change anything there. When I try to change, nothing happens and I always see the same icons there (two system icons - the icon for removing the memory external device + the icon for the network interface)._

**Comment by s3n0** [comment]
You are probably responding to my new problem, with the impossibility of changing the behavior of the icons in the SysTray (1. hide / 2. permanent display / 3. display only during notifications).

I tried it with the console on of course. When trying to change the behavior of the SysTray icons in the EP configuration, only this was shown in the console:
```0 46000000```
And really nothing else. And of course, there was no change in the SysTray icon settings. I'm trying to get it to see the Skype icon always visible in the systray. But it doesn't work.

**Comment by pyrates999** [comment]
No, I was referring to your original bug when getting the EP console output.

As for your new problem, that has been reported here: https://github.com/valinet/ExplorerPatcher/issues/1454

**Comment by Amrsatrio** [comment]
Having custom scaling factor set is an unsupported scenario. Taskbar icons show up fine on supported scaling factors such as 125%, 150%, 175%, 200%, and 225%.

Also, regarding the taskbar issue, you can just drag the icons from the tray icon overflow into the taskbar. A fix for the customize notification area icons window will come this year (I hope).
