### ISSUE TITLE
Gnome overview style taskview

### ISSUE THREAD

**Issue by developer91234** [valinet/ExplorerPatcher#2691]
Consider adding the following functionality:

- In the task view, show the taskbar even if it's hidden.
- Windows key opens the taskview
- Implement type-to-search in the taskview, i.e. any alphanumeric keystroke gets sent to the window start/search menu.

This would essentially reproduce gnome overview functionality, enabling the user to have a completely empty main workspace, maximizing space for open windows and eliminating distractions.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
