### ISSUE TITLE
Bitdefender blocking ExplorerPatcher

### ISSUE THREAD

**Issue by NicciZar** [valinet/ExplorerPatcher#2698]
```
Windows 10 Pro 22H2

EP Version 22621.2861.62.2

Bitdefender Build 27.0.25.116
```

Using Bitdefender Internet Security blocks Explorer Patcher with Advanced Threat Defense

![image](https://github.com/valinet/ExplorerPatcher/assets/43537611/c1cdfe91-d107-486e-a1ab-f5e995491a21)

![image](https://github.com/valinet/ExplorerPatcher/assets/43537611/dc04c5de-fa8a-4db0-9d4d-baaaf38099a9)

I sadly cannot exempt the folder nor that ep_gui.dll from the Advanced Threat Defense (there can only be .exe files..)
Maybe there is anyone having the same problems or having a solution (except not using Bitdefender or ExplorerPatcher ofc)

**Comment by rdebath** [comment]
Raise a false positive report.
https://www.bitdefender.com/consumer/support/answer/29358/

Also "ATD" is a bit fragile, it's reasonable to turn it off.

**Comment by s3n0** [comment]
This is strange because I also use BitDefender-Free ... and I don't see any report for EP.

**EP:** 22621.2861.62.2
**WIN11:** 22621.3007
**BitDefender:** Antivirus-Free 27.0.25.1116 (12.1.2024) + database engine v7.95936 / update 13043231 (16.1.2024)

**Comment by NicciZar** [comment]
@s3n0 
I am not sure if Bitdefender Free uses the Advanced Threat Detection system. (seems like a paid feature)
Could you check if you have the part "Advanced Threat Defense" within the "Protection" category?

![image](https://github.com/valinet/ExplorerPatcher/assets/43537611/632c4c3c-b577-488b-b156-cff160812155)

I also reported it as false positive. 
I am not sure if I will hear back from them but I sent them the file and the link to this repo

**Comment by s3n0** [comment]
@NicciZar yes, I noticed that I basically only use FREE Antivirus and that the problem is with another version of BitDefender. But the fault will lie in something else. The FREE version also uses the protection you mentioned:

![obrázok](https://github.com/valinet/ExplorerPatcher/assets/13181404/f3098c2f-e42c-4e60-bf3e-5c23519d90bc)

**Comment by NicciZar** [comment]
@s3n0 thanks for checking! I guess we will now have to wait or disable ATD for the meantime.

**Comment by s3n0** [comment]
So... it happened to me, too. The exact same message that blocked EP, through "rundll.exe" + "explorer.exe" and some other applications:

![BitDefender report](https://github.com/valinet/ExplorerPatcher/assets/13181404/3f81d3c9-91f0-4ae8-b020-b1acec01e833)

This happened when I tried to uncheck the top three options in the "System tray" section of the EP configuration, for my own experimentation (related to another EP issue). When I left these 3 options as "X" (crossed out) and restarted EP...

![BitDefender and EP](https://github.com/valinet/ExplorerPatcher/assets/13181404/e1b6341b-a74b-4544-ac97-08b6b9f3bc08)

...then I got the same message from BitDefender (Free Antivirus edition): "Bitdefender detected potentially malicious behavior and blocked all associated applications."

**Comment by NicciZar** [comment]
Great addition @s3n0 !
Could you also raise a false positive report?
https://www.bitdefender.com/consumer/support/answer/29358/

When I made the report, I selected "False Positive", Sample Type: "File" (then I uploaded ep_gui.dll)
Detection name for me is: SuspiciousBehavior.106C1B9C1C160B
(I assume the name is different)

![image](https://github.com/valinet/ExplorerPatcher/assets/43537611/35f0e465-7a91-46d8-9a73-98edb840dc0f)

**Comment by Amrsatrio** [comment]
Is this still an issue now? I want to close this issue because there's nothing we can do to fix antivirus false positives.
