### ISSUE TITLE
1Password stopped working

### ISSUE THREAD

**Issue by RussKie** [valinet/ExplorerPatcher#270]
Encountered a peculiar bug with https://github.com/valinet/ExplorerPatcher/releases/tag/22000.258.31.0 - 1Password password manager stopped showing all its windows, e.g. the "mini" window:
![image](https://user-images.githubusercontent.com/4403806/140318611-002e70c0-1e14-43e2-bf7f-3150cc5a1a72.png)
...and the main window:
![image](https://user-images.githubusercontent.com/4403806/140318768-b43182d7-1b8f-4f6a-bcfb-eb406c9e31d0.png)

A web browser's plugin would show the window, but then it's impossible to add or edit entries...

I have deleted dxgi.dll and rebooted but that didn't help. Then after I ran `regsvr32 /u ExplorerPatcher.amd64.dll` and rebooted 1Password started working again. But now Windows is not very usable.... /sigh

**Comment by Anixx** [comment]
Why are not you testing with the latest version 22000.282.32.5?

**Comment by Anixx** [comment]
https://github.com/valinet/ExplorerPatcher/releases

**Comment by valinet** [comment]
And the idea is that the shell extension is experimental and mainly NOT NEEDED. The README does not mention it yet for good reason. It’s only required to enable some workflows when using the classic theme at the moment, and even then, it’s still experimental. Just dropping dxgi.dll in C:\Windows is enough to get the functionalities of the patcher.

Thanks

**Comment by RussKie** [comment]
Tried without the patcher, all good.

**Comment by Anixx** [comment]
> Tried without the patcher, all good.

Instead of trying without, did you try with the latest version?
