### ISSUE TITLE
Can't run .exe AT ALL

### ISSUE THREAD

**Issue by sYanjiink** [valinet/ExplorerPatcher#2702]
When i run the .exe file, it doesnt do anything at all. Its not even open. Its not seen anywhere in task manager. My OS is up to date, my graphic drivers as well, idk wth is goin on

**Comment by Amrsatrio** [comment]
Turn off UAC. Turn off your antivirus,. And see if it opens.

**Comment by sYanjiink** [comment]
still nothing happened. theres no notif from defender in the first place when i start the .exe. I do read something about it will not work on canary ver of windows, whatever that means. so prob i have that canary builds rn in my laptop

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.

Please include any other software you have installed that modifies the UI of windows.

Try downloading the exe again.

**Comment by sYanjiink** [comment]
Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎07-‎Aug-‎23
OS build	22631.3007
Serial number	MP2FQR9M
Experience	Windows Feature Experience Pack 1000.22681.1000.0

I did download Stardok Start11, but already uninstalled

Nah, this my own laptop

**Comment by pyrates999** [comment]
Please right click on the ep_setup.exe file and select properties.  Show screen shots of the general and details tab.

**Comment by sYanjiink** [comment]
okay somehow it works now. thx yall for helping
