### ISSUE TITLE
Taskbar icons don't show on second monitor

### ISSUE THREAD

**Issue by rcwachter** [valinet/ExplorerPatcher#2709]
I'm using the Windows 10 style taskbar and on my second monitor, I don't see any icons on my taskbar. I went into the Windows 11 personalization settings under taskbar and the setting for all displays.
![image](https://github.com/valinet/ExplorerPatcher/assets/97169604/c9359cbc-6b34-4b20-9243-55bfb9e76e4e)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
If you are using TranslucentTB, I can confirm that this issue occurs when it is open. I have no plans yet to fix it or see what's wrong in TTB's code which causes it.

Closing due to no response.

**Comment by pyrates999** [comment]
Another application you can try for a transparent taskbar is NiceTaskBar.
