### ISSUE TITLE
Windows 10 start menu hangs when closing

### ISSUE THREAD

**Issue by eviltek2099** [valinet/ExplorerPatcher#2711]
![image](https://github.com/valinet/ExplorerPatcher/assets/7232257/dc698dba-5429-4163-bd6a-58b645adba60)
As seen by the attached image the Windows 10 start menu on a Windows 11 installation hangs when closing. 
This happens weather using windows key or mouse click on or off the start button.  The icons and controls on the menu disappear quickly but the menu itself hangs for around 2-3 seconds.
i have 3 screens as imaged here:
![image](https://github.com/valinet/ExplorerPatcher/assets/7232257/725c6cde-1856-4169-a9e5-146e6f8bb1eb)

Edition	Windows 11 Pro
Version	23H2
Installed on	‎12/‎29/‎2023
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0
Processor	11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 GHz
Installed RAM	48.0 GB (47.8 GB usable)
Device ID	26E43D32-52BE-4AC3-A572-40A8075B041F
Product ID	00330-80000-00000-AA343
System type	64-bit operating system, x64-based processor
Display card	RTX 3060

**Comment by eviltek2099** [comment]
ok, never mind... I found this post https://github.com/valinet/ExplorerPatcher/issues/2666#issue-2070338051 after posting this issue. Restarting File Explorer corrects the issue. Sorry ;)

**Comment by h4rry431** [comment]
Who would need 48gb of ram? Just wondering :)
