### ISSUE TITLE
Multiple issues: No start and File Explorer icon, search icon cannot be removed, 

### ISSUE THREAD

**Issue by mr-september** [valinet/ExplorerPatcher#2714]
Fresh install, I have tried toggling and restarting of almost every option in Explorer Patcher's taskbar settings page in an attempt to reset.

1. No windows/start icon, area cannot be clicked at all. Keyboard windows key still works.
2. Search icon/magnifying glass icon cannot be removed. Yes I have checked various options both in EP and native Windows settings.
3. File Explorer icon is missing/truncated. In the attached screenshot, the small orange rectangle at the middle-bottom, immediately to the left of Outlook icon, shows the active and clickable area which opens/switches to File Explorer.

<img width="121" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/45350177/fa55ff2c-0bbe-4008-8a61-206da9a60df7">

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by mr-september** [comment]
Windows 11 22H2 (OS Build 22621.3007).

ExplorerPatcher Version 22621.2861.62.2.

Changed settings in the main post - toggled things on and off because the problem occurred immediately on first install/run of EP, 99% sure that I am right now back to the default/factory EP settings.

Other software: Powertoys, Wallpaper Engine, possibly leftover bits of uninstalled EP from a few months ago?

**Comment by pyrates999** [comment]
In the EP properties application, go to **About**.  And click on **Restore default settings**.  Then click on **Restart File Explorer** in the bottom left corner.

See if it is still happening.

**Comment by mr-september** [comment]
> Do you have StartAllBack installed as well?

Thank you! This was it. Very sorry, I completely forgot that it was installed (since it doesn't show up in the start menu search, but found it in Add or Remove Programs).

Removing StartAllBack immediately fixed the issues, but I will Restore default settings just in case.
