### ISSUE TITLE
Centered StartMenu doesn't show on the main display when auto-hide taskbar is ON.

### ISSUE THREAD

**Issue by abolog** [valinet/ExplorerPatcher#2715]
winver: Windows 10 - 22H2 (Build 19045.2006)
EPver: Latest (22621.2861.62.2) tried others too

Video: https://streamable.com/6tw2az

How to reproduce bug:
1. Place the external monitor (set as main) on top of the other monitor.
2. Enable Autohide Taskbar
3. Enable Centered Start Menu

I tried changing "show where the cursor is" but no effect.

**Comment by abolog** [comment]
Oh, ok.
So the bug is still alive? Or is there a fix?

**Comment by pyrates999** [comment]
It means the bug has not been fixed yet, if it is a bug.
