### ISSUE TITLE
Icons in taskbar toolbars are not scaled when screen resolution changes

### ISSUE THREAD

**Issue by Kaptensanders** [valinet/ExplorerPatcher#2718]
Taskbar style: Windows 10

Icons in a "quicklaunch" style toolbar does not resize properly when screen resolution changes, eg connecting/disconnecting an external monitor. 

![image](https://github.com/valinet/ExplorerPatcher/assets/24979195/cd126dc3-cdab-47ef-94e0-e2887682522c)

becomes

![image](https://github.com/valinet/ExplorerPatcher/assets/24979195/bff7ff35-1990-4b0a-bdfd-9818d3461a15)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Kaptensanders** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/24979195/a22bb01e-1e3f-459f-9848-4b069d663ad3)
![image](https://github.com/valinet/ExplorerPatcher/assets/24979195/b3c3be9d-d4a1-473e-ab03-81d7cf75f75e)
![image](https://github.com/valinet/ExplorerPatcher/assets/24979195/13c4898b-7a5c-45ef-b925-25ce09c3e721)

Everything else is set to default (untouched)

No other UI-modifying software installed on the system

**Comment by pyrates999** [comment]
I tried this on windows 10 and got the same result.

This isn't something that EP can fix because the code to adjust the icon size in the custom made quick launch toolbar is not there I think.  Sorry :)

**Comment by pyrates999** [comment]
Here's the article I followed to add a quick launch toolbar:

https://www.lifewire.com/add-quick-launch-toolbar-in-windows-10-5115231

from the article:

Why Was the Quick Launch Toolbar Removed?

While the Quick Launch toolbar was quite helpful, and many people liked it, the ability to [pin apps to the taskbar](https://www.lifewire.com/pin-to-taskbar-windows-10-4584056) took its place in the default Windows design. If you don’t already take advantage of app pinning, it’s pretty useful in its own right. You can right-click any app on your taskbar and choose to pin it to either the start menu or taskbar for easy access.

If you have a set of apps that you use regularly but don’t necessarily want them to run on startup, consider pinning them to the taskbar. The quick launch menu is better if you have more than a handful of apps you want easy access to, but pinning is convenient for a handful of your most commonly used apps.
