### ISSUE TITLE
[Bug]There was no response after installation, it still looks like it's the default

### ISSUE THREAD

**Issue by AlexanderDash** [valinet/ExplorerPatcher#2719]
Windows 11 Home Chinese Version
Version 21H2
Operating system version 22000.2538
Snapdragon 8cx Gen 3

![Snipaste_2024-01-20_02-23-14](https://github.com/valinet/ExplorerPatcher/assets/134115886/7c8769a3-22e2-4da9-a3a0-5e081c0843bf)

**Comment by pyrates999** [comment]
EP runs on x86-64 cpu's only.
