### ISSUE TITLE
[22635.3066] Missing acrylic on Windows 10 taskbar

### ISSUE THREAD

**Issue by LEXMENBR** [valinet/ExplorerPatcher#2722]
EP get full transparent no classic-Shel or Open-shell intalled.
transparency disabled in configs.
Edição	Windows 11 Pro
Versão	23H2
Instalado em	‎18/‎01/‎2024
Compilação do SO	22635.3066
Experiência	Windows Feature Experience Pack 1000.22685.1000.0

![WV](https://github.com/valinet/ExplorerPatcher/assets/98248375/2c4f8b6c-0704-411c-a1cc-352777ae7d74)

**Comment by pyrates999** [comment]
You're in the Beta channel for your windows version: https://blogs.windows.com/windows-insider/2024/01/19/announcing-windows-11-insider-preview-build-22635-3066-beta-channel/

Please show a screen shot of it being transparent.

**Comment by LEXMENBR** [comment]
![Screenshot (22h 30m 43s)](https://github.com/valinet/ExplorerPatcher/assets/98248375/670c4e0d-a19e-4ca2-9471-698f098aa349)

What else can i provide?

**Comment by LEXMENBR** [comment]
![Screenshot (22h 31m 59s)](https://github.com/valinet/ExplorerPatcher/assets/98248375/743328b8-1ade-41a7-ad86-9b8e2fb533b3)

**Comment by LEXMENBR** [comment]
I get a message that the Explorer Patcher OS ( forgot the name) has download a new version, Ep restarded and get transparend.

**Comment by pyrates999** [comment]
Can you uninstall EP, reboot, and see if it is still transparent?

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/68f42e3f-ee86-4cd7-a239-70605383f32a)

Can confirm. 22635.3066. Although this doesn't happen on 22631.3078...

**Comment by LEXMENBR** [comment]
> Can you uninstall EP, reboot, and see if the taskbar is still transparent?

If i UNINSTALL EP and it goes back to the original Windows 11 Taskbar, and works fine,
Im deleting now ALL entries of EP in the Registry, and re-install EP.

![Screenshot (16h 55m 34s)](https://github.com/valinet/ExplorerPatcher/assets/98248375/8ce4fa6b-487b-4bfa-982b-56a861481eb3)

**Comment by LEXMENBR** [comment]
I was unable to delete the registry entries referring to the installation location in Explorerpatcher! But I managed to delete all other entries and remnants of files and folders.
![Screenshot (16h 58m 03s)](https://github.com/valinet/ExplorerPatcher/assets/98248375/87a1e22a-874a-423e-af68-2c20ea4e1c34)

**Comment by LEXMENBR** [comment]
After all that, it remains transparent...


![Screenshot (17h 18m 13s)](https://github.com/valinet/ExplorerPatcher/assets/98248375/90da2c6f-de32-46c6-b06d-afb5b96b2b44)

**Comment by LEXMENBR** [comment]
Tryed creating a new windows 11 user, same thing hapens.

**Comment by Amrsatrio** [comment]
Yeah because a fix in ExplorerPatcher is needed. There is nothing more you can do as a user.

**Comment by zeldaoot6969** [comment]
I have the exact same issue in 22635.3066, but I think it looks really cool and I think it could be a really cool feature. Is this possible?

**Comment by pyrates999** [comment]
If you want a transparent taskbar, where you control how transparent it is, look at [NiceTaskBar](https://apps.microsoft.com/detail/9PKL2S93XWB5?hl=en-US&gl=US).

**Comment by Amrsatrio** [comment]
Please update to the latest beta build: 10.0.22635.3130. And update ExplorerPatcher to the latest prerelease version as well to have fixed action center and toast center positioning. Acrylic works again there, but should it breaks again, this issue may be reopened.
