### ISSUE TITLE
21H2 → 22H2 has broken "Open Start in All apps by default"

### ISSUE THREAD

**Issue by u01jmg3** [valinet/ExplorerPatcher#2726]
It looks like updating from Windows 11 21H2 to 22H2 has broken "Open Start in All apps by default" ("Properties" → "Start menu") in that it no longer has any effect.

Apologies if there's already an issue for this - I couldn't see one.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1427

please close this.
