### ISSUE TITLE
No start icon, app icons look weird.

### ISSUE THREAD

**Issue by pwsh7** [valinet/ExplorerPatcher#2728]
Using Windows 11 22H2 and ExplorerPatcher 22621.2861.62.2 
image of issue:
![image](https://github.com/valinet/ExplorerPatcher/assets/84739184/570098ec-7071-403f-ac56-fab798d28712)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please do not use ExplorerPatcher and StartAllBack at the same time. You have to settle with only one. We do not support such scenarios.
