### ISSUE TITLE
[19045.3448] Can't launch Start Menu, Action Center, Volume & Clock

### ISSUE THREAD

**Issue by RedstarDev** [valinet/ExplorerPatcher#2729]
Windows 10 22H2, Build 19045.3448
ExplorerPatcher Version: 22621.2861.62.2

I can't launch the Start Menu, Action Center, Volume & Clock.
Uninstalling EP and cleaning the registry at Computer\HKEY_CURRENT_USER\SOFTWARE\ExplorerPatcher didn't help.
I had Shell from NileSoft, as well as oldNewExplorer installed. Both uninstalled now, but that didn't help either.
Already did an sfc /scannow & all the Dism /Online /Cleanup-Image /ScanHealth stuff. No errors found.

I have the two January updates from Microsoft failing to install: (KB5034122) & (KB5034441).
These fail to install for many users.
The issue started on Friday, January 19th, after a reboot.

Is this a known issue? Any help is greatly appreciated!

**Comment by pyrates999** [comment]
KB5034122 didn't have any reports of failing to install.

However KB5034441 did have reports of failing to install.

Nothing to do with EP here.

You may need to repair your windows install.  Please run the following in an elevated command prompt or elevated powershell:

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by Vipin2003** [comment]
Not Reproduced on My Side...It's working fine
