### ISSUE TITLE
No address bar with Windows 11 preview 10.0.22494.1000

### ISSUE THREAD

**Issue by SamuFr** [valinet/ExplorerPatcher#273]
I have updated to the last Windows preview 10.0.22494.1000.
The address bars of windows folders are now missing.
I downbacked to the previous version (address bar is back) and updated it again. The problem is the same: no address bar.
Did anyone get the same issue ?

**Comment by PGomersall** [comment]
It is working for me in that version 22494. I did have to do this update from the ISO as Windows Update broke. This is reported issue here:
https://techcommunity.microsoft.com/t5/windows-insider-program/windows-update-broken-after-trying-to-update-to-build-22494-dev/m-p/2924255 
![AddressBar](https://user-images.githubusercontent.com/43388507/140418747-2166426b-fd6c-432d-a213-7a4b25244d33.png)
