### ISSUE TITLE
Import/export settings

### ISSUE THREAD

**Issue by NinFanBoyFTW** [valinet/ExplorerPatcher#2731]
Hi. I have been loving ExplorerPatcher. It has made Windows 11 usable. I wanted to know if there was an easy way, or if there could be a way to implement an import/export settings button into Explorer patcher. My biggest issue with ExplorerPatcher right now, is that there are so many little tweaks that I do after installing that, for me to put it onto another computer, it takes a while to configure everything  how I like it.

**Comment by pyrates999** [comment]
In the EP properties application, go to About and you'll see there is import and export settings options.

**Comment by NinFanBoyFTW** [comment]
Ahh, thank you for that info. Seems like it would be better visible in it's own menu or something like that, but that's just my two cents. Awesome, thanks again.

**Comment by pyrates999** [comment]
You're welcome.
