### ISSUE TITLE
Excuse me, how to uninstall clearly?

### ISSUE THREAD

**Issue by 674019130** [valinet/ExplorerPatcher#2733]
I'm on Windows 11, and I noticed the version "Build 22621.ni_realease.220506-1250" can choose union the taskbar icon or not, so I'm trying to uninstall it, please help, thx.

**Comment by pyrates999** [comment]
https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To#how-to-uninstall

**Comment by 674019130** [comment]
> https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To#how-to-uninstall

Thanks!
