### ISSUE TITLE
[22631.3007] Other system tray icon not showing when set to ON

### ISSUE THREAD

**Issue by Svan987** [valinet/ExplorerPatcher#2736]
Just in case I am using Windows 11 Pro (Build 22631-3007). It's a fresh install with Atlas Playbook 0.3.2
It's working normally before installing Explorer Patcher.
I know this build is not yet officialy supported.

**Comment by pyrates999** [comment]
Which system tray icon is not showing?

**Comment by Amrsatrio** [comment]
The toggle in the settings app no longer works and we have no plans yet to make it work. Please toggle it through the "Customize notification area icons" link in the Taskbar section of ExplorerPatcher properties.
