### ISSUE TITLE
how to add app to win 10 style start menu on win11?

### ISSUE THREAD

**Issue by trcrsired** [valinet/ExplorerPatcher#2737]

**Comment by pyrates999** [comment]
https://www.windowscentral.com/add-app-shortcuts-start-menu-manually-windows-10

**Comment by Erosion139** [comment]
> https://www.windowscentral.com/add-app-shortcuts-start-menu-manually-windows-10

This is not the solution to the problem. He is not having issues with how to use windows 10. He cannot pin things to the start menu because the functionality is broken. It needs a fix or workaround (the existing workaround does not work.)

**Comment by pyrates999** [comment]
He hasn't gone into details for what happens when he has tried to pin an app to the windows 10 start menu.  He needs to provide that.

**Comment by Amrsatrio** [comment]
Closing for no info provided. Pin to Start from the Start Menu and Explorer works fine. Though Pin to Start from Search currently does not work.
