### ISSUE TITLE
Not working win 11

### ISSUE THREAD

**Issue by vampiregoat699** [valinet/ExplorerPatcher#2741]
This worked great in windows 10 but upon upgrading to win 11 and re-installing the start menu I tried to change from 11 to 10 version still used the win 11 version no matter what I tried.

**Comment by zc5162** [comment]
Please make sure you have this option turned on, and if the problem is solved after turning it on, please turn off this issue.
![image](https://github.com/valinet/ExplorerPatcher/assets/139825029/ff4c48c5-4c18-4fed-9bb7-b13cfd46e914)

**Comment by j-oliveras** [comment]
After updating from Windows 11 22H2 to 23H2 I had the same problem. The start menu was always in Windows 11 style. I solved it uninstalling and reinstalling ExplorerPatcher.

**Comment by Amrsatrio** [comment]
Yes, one has to reinstall EP after a feature upgrade. We have no plans of making it automatic.
