### ISSUE TITLE
[bug, Taskbar10] Opera icon broken after downloading a file.

### ISSUE THREAD

**Issue by dimani128** [valinet/ExplorerPatcher#2742]
I'm using the win 10 taskbar style on win 11, and when I download a file in Opera, the progress bar appears normally:
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/db671c6b-e6bb-47b7-9943-314fdfde00d5)
But, after it's finished, it turns red, and the only thing I have found that (temporarily) fixes it is restarting opera.
After download:
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/cf26f4f6-b00a-4471-b639-6b9910a03976)
After restarting:
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/419b8a50-20f5-4a2e-a8fc-2712b9075e64)

**Comment by Amrsatrio** [comment]
Maybe try to confirm this too on Windows 10? This is more of an Opera bug instead of Windows.

**Comment by dimani128** [comment]
If you mean try the same thing with the 11 taskbar on the OS Windows 10, I don't have 10, but I can try it with the 11 version on 11.

In progress:
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/e417767e-99cd-4ba1-9c51-47dcbe08e2a5)
After download finished (Slightly red bottom bar):
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/77576312-dcdf-4a08-bc0c-9cedb6545cd3)
After restarting (blue bottom bar):
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/3541cec3-d472-40d9-a98f-b9ddb4d20d76)

Also, restarting File Explorer resets the icon too.

**Comment by dimani128** [comment]
I tested it with Edge:
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/f2ee6bc2-aff6-44cc-b568-cb748295f24e)
And after it finished it just went back to normal.

Opera is supposed to (I think) make it so that it turns orange and appears on the taskbar no matter what desktop you're on (I hope I didn't explain that terribly)

**Comment by pyrates999** [comment]
Since you tested it on the windows 11 taskbar and it still happened.  Can you uninstall EP and then test it to see if it still occurs with Opera?

**Comment by dimani128** [comment]
I did. It appears to be Opera's fault.
During:
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/7b526802-e58a-435b-8fbb-98c725e0e55c)
After:
![image](https://github.com/valinet/ExplorerPatcher/assets/43250455/1379d77d-cbef-4787-b374-ad1bf05ac8ee)
