### ISSUE TITLE
Windows 10 Start menu not opening

### ISSUE THREAD

**Issue by ORanGeOfficial** [valinet/ExplorerPatcher#2747]
Windows 10 start menu not opening. Uninstalling ExplorerPatcher fixed the problem, but after reinstalling, start menu stopped opening again.

**ExplorerPatcher version:** 22621.2861.62.2
**Windows 10 version:** 19045.3636

**Comment by pyrates999** [comment]
Install the January 9/2024 update.  You're running a preview update from Oct 26/2023.

**Comment by Amrsatrio** [comment]
The Start Menu appears fine on 19045.3930. Please consider updating.
