### ISSUE TITLE
Taskbar items take a really long time to show up when starting Windows, can't access the start menu, and file explorer suddenly changes from Windows 11 style to Windows 10

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [valinet/ExplorerPatcher#2751]
Yesterday this happened.
Using KB5033734

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by H-A-M-G-E-R** [comment]
explorer patcher version 22621.2861.62.2
windows 11 build 22000.2538

**Comment by pyrates999** [comment]
Please check that symbols were downloaded.

**Comment by pyrates999** [comment]
That version of windows is from October 2023.  Please install the December 11/2023 update.

**Comment by H-A-M-G-E-R** [comment]
when i checked for updates i don't see the update above

**Comment by pyrates999** [comment]
Can you show a screen shot of the settings application checking for updates?

**Comment by Amrsatrio** [comment]
My 22000 machine, updated to the last cumulative update for 22000, still works fine. At that time I also saw my friend having similar issues as you when preparing a fresh 22621 installation, so I believe this was a mishap on MS' side that got fixed quickly.
