### ISSUE TITLE
Pressing the windows logo does not respond.

### ISSUE THREAD

**Issue by IQminecraft** [valinet/ExplorerPatcher#2755]
version: windows22h2

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by IQminecraft** [comment]
I'm sorry. I didn't have enough information.
Correction.
- version : windows10 22h2 190453803
- Explorer Ptacher version : 22621.2861.62.2
- Changed settings : style of start button
※**The windows logo is no longer responsive using either setting.**

**Comment by pyrates999** [comment]
First install the January 9/2024 windows update.

**Comment by IQminecraft** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/118362666/63ae55a8-36f5-4256-88bc-3c6c2ce1c579)
Sorry for the delay in responding.
The position of the style of start button is the blue line in the image.
Also, I could not update windows.

**Comment by pyrates999** [comment]
You will need to update windows before this can be looked at.  Please keep trying to update windows.

**Comment by IQminecraft** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/118362666/bb68b043-89f0-4d3b-a824-3d49b4c3b335)
An error occurs.

**Comment by pyrates999** [comment]
If this is a work computer, they may be controlling when you get updates.

**Comment by IQminecraft** [comment]
Unfortunately, it's a gaming pc.

**Comment by pyrates999** [comment]
Try a previous release of EP then.

**Comment by IQminecraft** [comment]
I see.i will try.

**Comment by IQminecraft** [comment]
I try delete ep to install old ep.
but when delete ep, fixed windows logo.
Problem solved.
Thank you!

**Comment by pyrates999** [comment]
Please list the version of EP you installed that fixed it.  Don't update EP then until your pc has the latest windows updates.

**Comment by Amrsatrio** [comment]
I could not reproduce the issue under Windows 10 22H2. Sorry.
