### ISSUE TITLE
Adding Google Chrome to Start -> Symbol / Icon shows an empty frame

### ISSUE THREAD

**Issue by Richi22** [valinet/ExplorerPatcher#2756]
So far only experianced with Google Chrome

![image](https://github.com/valinet/ExplorerPatcher/assets/74529451/5f95b40b-2470-4ef7-bd39-e02c19a1f295)

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/2d9ade57-b9cf-43fd-8aa9-919fbfbc85bd)

Works fine on 22621.3085 🤷

**Comment by Amrsatrio** [comment]
Closing this as I'm unable to reproduce this issue.
