### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by Hunter23071985** [valinet/ExplorerPatcher#2757]
Hi!
Please add the [russian translation](https://github.com/valinet/ExplorerPatcher/issues/175#issuecomment-949841068) of **Leserg73** to the About section of Properties window.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by Amrsatrio** [comment]
We'll check the translation PRs once we're about to make a new release. Which is next month.
