### ISSUE TITLE
Remove icons from Windows Explorer Titlebar

### ISSUE THREAD

**Issue by Hunter23071985** [valinet/ExplorerPatcher#2758]
Hi!
Please add feature to remove icons from Windows Explorer Titlebar.
This feature is implemented in [TBarIconBlanker](https://www.askvg.com/how-to-remove-program-icons-from-windows-titlebar-and-taskbar-buttons/) - in Windows Vista and later, it hides only the title bar icons.
ExplorerPatcher also has this feature, but it only works well if Control interface from Win7 is selected.
Thank you!

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
