### ISSUE TITLE
Cleaner address bar

### ISSUE THREAD

**Issue by Hunter23071985** [valinet/ExplorerPatcher#2759]
Hi!
Please add feature to cleaner address bar.
This feature is implemented in [Blank It BY NEIIO](https://skinpacks.com/blank-it-for-windows-10/).
It would be great to see this feature in ExplorerPatcher.
Thank you!

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
