### ISSUE TITLE
Disable control interface

### ISSUE THREAD

**Issue by Hunter23071985** [valinet/ExplorerPatcher#2760]
Hi!
Please add feature to disable control interface.
Now in File Explorer - Control Interface is implemented W11 Command Bar, W11 Address Bar, W10 Ribbon, W7 Command Bar.
It would be great to see feature "Disable control interface" on this list.
Thank you!

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
