### ISSUE TITLE
Transparency settings not applied for Win 10 taskbar style.

### ISSUE THREAD

**Issue by AJolly** [valinet/ExplorerPatcher#2765]
When using the Win 10 taskbar style, the accessibility - transparency setting is not applied to the taskbar.  
(ie, there's no way to have the taskbar not be translucent).  This is less than ideal for usability :/

![image](https://github.com/valinet/ExplorerPatcher/assets/91493/1a45172a-3ece-46d0-a25c-5c36b1b9f144)

![image](https://github.com/valinet/ExplorerPatcher/assets/91493/04a44023-d47e-43e1-a3de-b68961c897a1)

**Comment by Adam-S-Amir** [comment]
Second this. Taskbar is transparent on win 10 mode. Win 11 mode, taskbar is translucent, but everything is all screwy looking.

**Comment by pyrates999** [comment]
Windows 10 doesn't support transparency in the taskbar.  If you want transparency in the taskbar, look at [NiceTaskBar](https://apps.microsoft.com/detail/9PKL2S93XWB5?hl=en-US&gl=US) from the microsoft app store.

**Comment by Amrsatrio** [comment]
If you disable transparency effects, then everything becomes opaque because that's what it says. If you want it to be transparent, but without blurs, please use another tweak software such as that or TranslucentTB.

**Comment by AJolly** [comment]
It seems to fixed itself.   

And to be clear I did not want any form of transparency, but the Windows 10 taskbar was being transparent.
