### ISSUE TITLE
taskbar still showing when fullscreen

### ISSUE THREAD

**Issue by idklololololololol** [valinet/ExplorerPatcher#2783]
can someone tell me what's going up? (no screenshot cuz WINDOWS ALSO DOESN'T WANT TO SCREENSHOT CUZ IT'S SO BROKEN)

**Comment by idklololololololol** [comment]
oh i just restarted and fixed everything yea all that for this pointless thing (also i use win + prt scr to screenshot, yea my computer is old)

**Comment by Amrsatrio** [comment]
Windows issue. Just keep alt tabbing and Win+T to juggle around its z-order.

**Comment by pyrates999** [comment]
Another way is to open up task manager and kill explorer.exe and then run task manager again and run explorer.exe
