### ISSUE TITLE
Problem with File open dialogs in Websites

### ISSUE THREAD

**Issue by furchtlos76** [valinet/ExplorerPatcher#2785]
Hi, i had a strange problem. Suddenly when clicking file upload buttons in chrome, firefox and edge did not open the file dialog / explorer to select/upload files. After searching, disabling tools, plugins, restarting, uninstalling/installing browsers for some hours, i finaly found out that explorer patcher must be the problem, after clicking on "restore default settings" everything works again. I did not change any settings before the problem appeard and i could not find the setting doing this. On a second computer of mine with - i think - the same settings i did not have that problem. Anyone else ever had that?

Version 222621.2861.62.2 on Windows 11 Build 22621.220506-1250

**Comment by Amrsatrio** [comment]
No, at least not me. If the issue cannot be reproduced, I cannot fix it.

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by pyrates999** [comment]
if you enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

Don't ever enable this feature unless you know what you're doing.
