### ISSUE TITLE
Touchpad Gestures not working after enabling SysListView32 Explorer

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#2787]
1. TouchPad Gestures does not work in Explorer after enabling SysListView32. In normal explorer (with disabling SysListView32), every gesture works fine but they doesn't work in SysListView32. Also, not even "Pinch to Zoom" for changing explorer view is also not working. IDK if it can be fixed or not.
2. SyslistView32 does not render Dark theme properly for Explorer. It works fine with Light Mode.

Is there any solution for these OR can these issues be fixed or not? Gesture issue is most imp. bcoz I personally like that. But without Gestures, it feels like creep.

**Comment by pyrates999** [comment]
According to this: https://github.com/valinet/ExplorerPatcher/issues/316

The SyslistView32 option is just a registry setting.  So EP can't fix that I don't think.

**Comment by Vipin2003** [comment]
After reading the post, I found that it can be fixed but valinet has no time for that at that time. And this is personally for the 1st issue. And if @Amrsatrio can check for this if the gesture support for it can work or not.
