### ISSUE TITLE
Not working w/Build 26040 (Canary Channel, Win 11 / Server 2025)

### ISSUE THREAD

**Issue by rkmfl** [valinet/ExplorerPatcher#2794]
The latest version of Explorer Patcher 22621.2861.62.2

Is not working w/Windows Build 26040 (Canary Channel, Win 11 / Server 2025)

It hides the tray area, **with or without** customization.

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.

**Comment by rkmfl** [comment]
> Canary builds are not supported because the code is not final and can change with each new release.

I'm not looking for it to be supported; I've already uninstalled.

Rather, I'm sharing in the event it helps.

The 26040 release is relatively static / won't reverse-out anything, such as the new taskbar changes. It's offered for bug fixes but the issue that exists now with EP will persist in the taskbar.
