### ISSUE TITLE
After the Windows menu is closed, it must wait for 1-2 seconds to completely disappear

### ISSUE THREAD

**Issue by YoulQey** [valinet/ExplorerPatcher#2796]
![NVIDIA_Share_GBg4mwbhjL](https://github.com/valinet/ExplorerPatcher/assets/53635729/4d554ea5-3cbf-47ea-9b25-51d278bf722d)

After the Windows menu is closed, it must wait for 1-2 seconds to completely disappear
I have to wait until it disappears before clicking on the content below, which gives people a very uncomfortable feeling. Is there a way to solve this problem? thanks！

**Comment by Unkrown6YT** [comment]
you need to restart Explorer.exe

**Comment by YoulQey** [comment]
> 您需要重新启动Explorer.exe

Thank you, the problem has been perfectly resolved. I thought I had already restarted "Explorer.exe"
