### ISSUE TITLE
Taskbar can't be moved to top or side of the screen any more.

### ISSUE THREAD

**Issue by pgrm0000** [valinet/ExplorerPatcher#2798]
After I assume some Windows 11 update, the taskbar is stuck on the bottom of the screen and can't be moved. The option of moving is no longer present in EP's settings.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by pgrm0000** [comment]
Win 11 Pro 22H2 build 22621.3007
EP version 22621.2861.62.2 (downloaded today and reinstalled new to check if it would help)
I don't have screenshoots unfortunatelly, I've uninstalled EP for now (without the option to move taskbar, it was not usefull any more). I didn't change any settings, this morning my PC woke up with the taskbar on the bottom and no option to change it in EP, like there was no place in EP's configuration menu, where this could be configured. The only configurable thing left was if the icons should be in the center or on the side.
No other software installed that modified the GUI.

I hope it helps.

**Comment by pyrates999** [comment]
Here's where to change it: https://github.com/valinet/ExplorerPatcher/wiki/All-features#primarysecondary-taskbar-location-on-screen

You need to change it to the windows 10 taskbar though in order for it to be on the left or right side as the windows 11 taskbar only supports being on the top or bottom.

**Comment by Nestoro** [comment]
Encountering same issue.
Version 23H2 (OS Build 22635.3350)
22621.3296.64.1

Windows 10 Taskbar is selected in ep and upon selecting a different taskbar location nothing happens except for the option changing to the selected value...

**Comment by pyrates999** [comment]
> Encountering same issue. Version 23H2 (OS Build 22635.3350) 22621.3296.64.1
> 
> Windows 10 Taskbar is selected in ep and upon selecting a different taskbar location nothing happens except for the option changing to the selected value...

That is an insider preview: https://blogs.windows.com/windows-insider/2024/03/13/announcing-windows-11-insider-preview-build-22635-3350-beta-channel/

Please open a new issue if you want it fixed as this was closed already.
