### ISSUE TITLE
Unicode symbols in path

### ISSUE THREAD

**Issue by gjf** [valinet/ExplorerPatcher#280]
Just a question: does the ExplorerPatcher affect on path in save/open dialog of Explorer?

I will explain the issue: I have a path that includes Unicode symbols: G:\ΔFosB\WorkData\
With update to Windows 11 some programs fail to open or save in this folder because of symbol Δ (investigating this issue I see the path is recognized as G:\ ?FosB\WorkData\ )- I am not sure is it pure Windows 11 bug or caused by ExplorerPatcher.

Windows 10 worked fine with this path.

![Screenshot 2021-11-05 181803](https://user-images.githubusercontent.com/322186/140534519-9c58f1db-f9b4-4b9a-b595-b76a5beed0de.png)

**Comment by valinet** [comment]
EP does not inject other programs than explorer except when used as shell extension which is not currently recommended. Save/open file dialogs are hosted by those apps, not bu Explorer.
