### ISSUE TITLE
 To switch language I have  to hold one of the keys and press another.  Pressing them simultaneously doesn't work. Windows 10 taskbar

### ISSUE THREAD

**Issue by BlackRule** [valinet/ExplorerPatcher#2803]
This prevents me from using Windows 10 taskbar. with Windows 11 taskbar there is no such issue.
 EP 22621.2861.62.2
 W11 22621.1922

**Comment by pyrates999** [comment]
Your windows 11 needs updates.  Please install them.  Do not install preview updates though.

The version should then be 22621.3007: https://support.microsoft.com/en-us/topic/january-9-2024-kb5034123-os-builds-22621-3007-and-22631-3007-3f7e169f-56e8-4e6e-b6b8-41f4aa4b9b88

**Comment by BlackRule** [comment]
@pyrates999 thanks I'll test on vm

**Comment by BlackRule** [comment]
@pyrates999 I created a vm with exact same versions of Win & EP. In it the problem doesn't exist. Even if I pass kb through. So it's software issue on my particular windows install. I have no clue how to fix it though. So I'll have to stick to w11 taskbar(

**Comment by BlackRule** [comment]
Holy cow! It was "asus driver updater" or something that had an icon in tray and was installed by my UEFI (motherboard). I closed it and no issue anymore.  So if people from internet face the same issue they'll now! In general Not just with EP mb.
