### ISSUE TITLE
22621.3007. There is no setting option when right-clicking on the taskbar.

### ISSUE THREAD

**Issue by mixian95** [valinet/ExplorerPatcher#2804]
The win11 version is 22621.3007. There is no setting option when right-clicking on the taskbar.

**Comment by pyrates999** [comment]
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by pyrates999** [comment]
Please show a screen shot of what you get when you right click on the taskbar.

**Comment by mixian95** [comment]
Thanks for your quick reply.
Versions 22621.2861.62.2 and 22621.2861.62.2 are used. Right-clicking only has the original two options, so no software settings have been made. The system does not use software to modify the taskbar, but only uses a software to change the right-click menu and restore the right-click menu to win10.But this does not seem to have anything to do with the taskbar (it is not StartAllBack-like software), it is just a small tool that may restore the right-click menu through the registry.

![1707559985056_d](https://github.com/valinet/ExplorerPatcher/assets/67423851/8ae1dc89-9cdd-4d69-a636-4c3a26088ab5)

**Comment by Amrsatrio** [comment]
Is your device ARM64?

**Comment by mixian95** [comment]
13th Gen Intel(R) Core(TM) i5-13500H   2.60 GHz

**Comment by pyrates999** [comment]
In the EP Properties application, make sure this option is not enabled: https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings#hide-the-program-settings-item-properties-from-the-taskbar-context-menu
