### ISSUE TITLE
Clock and System Tray icons disappeared after Windows 11 Home Insider Preview Build 26052 Release 240202.1419

### ISSUE THREAD

**Issue by Bambooster1** [valinet/ExplorerPatcher#2806]
First, after the previous Insider Preview update, the taskbar turned clear and could not be changed.  You could barely see the icons unless you had a solid background.  The most current preview killed the system clock and the icons showing Volume, Internet, Action Center, etc. when using the Windows 10 Taskbar style in ExplorerPatcher.  

Second (this may be a Windows 11 problem, and not an ExplorerPatcher problem), the entire Notification Area Icons area does not work.  You can't customize notification area icons at all.

**Comment by pyrates999** [comment]
If you have classic shell installed, uninstall it. That is no longer maintained.

The replacement is open shell.

**Comment by pyrates999** [comment]
26000 builds are canary builds.  Canary builds are not supported because the code is not final and can change with each new release.

**Comment by HM100** [comment]
@pyrates999 You're right on this one but since days ago, 26000 builds are also available on Dev Channel beginning with 26052. So support for Germanium builds are still not planned. If yes, then this issue may be closed.
