### ISSUE TITLE
Win 23H2 ( Build 22631.3085) - EP crashing

### ISSUE THREAD

**Issue by XiaomiDE** [valinet/ExplorerPatcher#2808]
Hi,

since a few days i'm getting crashes with EP and this windows version.
Tried resetting everything, uninstalling, reinstalling but that didn't help. Even with a normal setup and no changes it immediately crashes 3 times.

Nothing changed to my PC as of lately but i did notice KB5034204 did change something with the explorer stuff, maybe it's related to the issue?

I noticed i can still force upon the reg changes i saved via regedit but some things don't seem right. eg i cannot open EP by rightclicking taskbar and go to it's settings, i need to open it via the start menu instead. Whenever i restart the explorer after changing something, it crashes - while preserving most of the changes though. Strange.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by XiaomiDE** [comment]
Winver is in the title but i'll include here again to make it easier to view all at once ;)

Win 23H2 ( Build 22631.3085)
EP version: 22621.2861.62.2
![rundll32_fkAcswX97e](https://github.com/valinet/ExplorerPatcher/assets/99801452/63a53ff7-74fa-4962-8f98-1dd6c1d5237d)
![rundll32_uskFquoRZv](https://github.com/valinet/ExplorerPatcher/assets/99801452/3f28f304-fd7f-4a34-b0fc-d2bca9cef1f3)
![rundll32_hnhRFoOJmy](https://github.com/valinet/ExplorerPatcher/assets/99801452/d887f38c-e5cb-4e46-be5c-098c8ecd42ca)
![rundll32_CmNz4YeMVI](https://github.com/valinet/ExplorerPatcher/assets/99801452/71a30a0b-08c4-4140-a4ae-8ca4b872ed18)
![rundll32_aFbTQnfkik](https://github.com/valinet/ExplorerPatcher/assets/99801452/44f84330-79d2-4148-bf5d-e04f45382bea)
![rundll32_wJs5n0Tbhh](https://github.com/valinet/ExplorerPatcher/assets/99801452/26acebb6-9236-46f6-927f-abfede8ca46f)
![rundll32_4V6RxKJpFm](https://github.com/valinet/ExplorerPatcher/assets/99801452/3c6c5995-e646-45a1-9847-512fdea7ce74)
![rundll32_Hp8IwURWcq](https://github.com/valinet/ExplorerPatcher/assets/99801452/8f01794f-f30b-4061-9782-726a7b3576fc)
![rundll32_T8lojeytLj](https://github.com/valinet/ExplorerPatcher/assets/99801452/9236856c-6afc-488f-8547-2682084350cd)
![rundll32_myZR7MDeP4](https://github.com/valinet/ExplorerPatcher/assets/99801452/ad44d778-6013-48d0-a513-2c0b0957e54d)

Nothing else that modifies windows UI.

**Comment by pyrates999** [comment]
Go to **About** and click on **Restore default settings**.

You are also running a preview update: https://support.microsoft.com/en-au/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Try downloading and installing the latest pre-release of EP to see if it also fixes it.

**Comment by XiaomiDE** [comment]
If anything, it made it worse. After loading my reg settings again the same issue persists.
I will check if reverting any Win updates might fix it.

**Comment by XiaomiDE** [comment]
If anything, it made it worse. After loading my reg settings again the same issue persists.
I will check if reverting any Win updates might fix it.

EDIT: So after reverting the last update from Windows, everything works fine again. For now i will disable my Windows updates since something clearly messed up for some reason.

If i can do anything to help you pinpoint the issue, tell me what you need, i'd be glad to help!

**Comment by pyrates999** [comment]
What reg settings did you load in?  They might be causing this.

**Comment by XiaomiDE** [comment]
[ExplorerPatcher_22621.2506.60.1.reg.zip](https://github.com/valinet/ExplorerPatcher/files/14232326/ExplorerPatcher_22621.2506.60.1.reg.zip)

These are active now again and working fine, as before.

**Comment by pyrates999** [comment]
you were importing a previous reg file from EP?

**Comment by XiaomiDE** [comment]
no, that's the one i saved before trying to fix it.
And since i reverted back to the previous EP version i also loaded my old reg file again. So version and regfile of the version that worked before windows did "something".

**Comment by Amrsatrio** [comment]
May I ask what did you use to modify the font? I use latest prerelease and .3085 on my laptop and it works fine.

**Comment by XiaomiDE** [comment]
> May I ask what did you use to modify the font? I use latest prerelease and .3085 on my laptop and it works fine.

I just replaced it manually in the registry.

@pyrates999 
Sadly this morning it started having issues again and cashed, resulting in  mix of applied settings and ignored settings (like eg small taskbar gone).

**Comment by pyrates999** [comment]
I would stop directly applying it in the registry and instead apply the settings again using the EP properties application.

**Comment by XiaomiDE** [comment]
Well i just load the saved settings into EP, so not directly at all.

**Comment by pyrates999** [comment]
I would restore default settings, and then apply each setting you want changed.  Do not import the previous settings file.

**Comment by XiaomiDE** [comment]
Will try that tomorrow morning, g2g to work now.

Will keep you posted.

**Comment by XiaomiDE** [comment]
> I would restore default settings, and then apply each setting you want changed. Do not import the previous settings file.

So i just reverted back to standard settings, restarted, uninstalled EP, restarted, installed EP and BOOM: crashes immediately after fresh install.

**Comment by pyrates999** [comment]
So does it crash before you change settings in EP Properties application? Or after?

**Comment by archef2000** [comment]
Win 23H2 ( Build 22631.3085)
EP version: 22621.2861.62.2
Always crashes. Updating to the latest pre release fixes it.

**Comment by capricorn8** [comment]
After I updated my computer to build 22631.3155 yesterday, EP is crashing constantly. The latest pre-release (first entry on the release page) doesn't fix this issue. Any ideas?

![Update History](https://github.com/valinet/ExplorerPatcher/assets/33000800/a286f5bf-1555-46e3-a237-86f3afd252c1)

**Comment by Amrsatrio** [comment]
Can you show the error logs in event viewer that mentions explorer.exe?

**Comment by capricorn8** [comment]
Sure!

 

Is that sufficient?

 

Log Name:      Application

Source:        Application Error

Date:          14.02.2024 08:58:36

Event ID:      1000

Task Category: Application Crashing Events

Level:         Error

Keywords:      

User:          CAPRICORN\Karsten

Computer:      CAPRICORN

Description:

Faulting application name: explorer.exe, version: 10.0.22621.3155, time stamp: 0x3fb2d7a4

Faulting module name: ntdll.dll, version: 10.0.22621.3085, time stamp: 0xbced4b82

Exception code: 0xc0000005

Fault offset: 0x00000000000a5f26

Faulting process id: 0x0x3840

Faulting application start time: 0x0x1DA5F1B9CAF2D14

Faulting application path: C:\WINDOWS\explorer.exe

Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll

Report Id: c8db57cf-d68f-48dc-9fb5-ae29dfb035dc

Faulting package full name: 

Faulting package-relative application ID: 

Event Xml:

<Event xmlns= <http://schemas.microsoft.com/win/2004/08/events/event> http://schemas.microsoft.com/win/2004/08/events/event>

  <System>

    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />

    <EventID>1000</EventID>

    <Version>0</Version>

    <Level>2</Level>

    <Task>100</Task>

    <Opcode>0</Opcode>

    <Keywords>0x8000000000000000</Keywords>

    <TimeCreated SystemTime="2024-02-14T07:58:36.6870821Z" />

    <EventRecordID>61874</EventRecordID>

    <Correlation />

    <Execution ProcessID="3728" ThreadID="17504" />

    <Channel>Application</Channel>

    <Computer>CAPRICORN</Computer>

    <Security UserID="S-1-5-21-579709098-2198602927-3524710196-1002" />

  </System>

  <EventData>

    <Data Name="AppName">explorer.exe</Data>

    <Data Name="AppVersion">10.0.22621.3155</Data>

    <Data Name="AppTimeStamp">3fb2d7a4</Data>

    <Data Name="ModuleName">ntdll.dll</Data>

    <Data Name="ModuleVersion">10.0.22621.3085</Data>

    <Data Name="ModuleTimeStamp">bced4b82</Data>

    <Data Name="ExceptionCode">c0000005</Data>

    <Data Name="FaultingOffset">00000000000a5f26</Data>

    <Data Name="ProcessId">0x3840</Data>

    <Data Name="ProcessCreationTime">0x1da5f1b9caf2d14</Data>

    <Data Name="AppPath">C:\WINDOWS\explorer.exe</Data>

    <Data Name="ModulePath">C:\WINDOWS\SYSTEM32\ntdll.dll</Data>

    <Data Name="IntegratorReportId">c8db57cf-d68f-48dc-9fb5-ae29dfb035dc</Data>

    <Data Name="PackageFullName">

    </Data>

    <Data Name="PackageRelativeAppId">

    </Data>

  </EventData>

</Event>

**Comment by Amrsatrio** [comment]
Unfortunately it doesn't help. I have to give you a custom ExplorerPatcher exe to help me in diagnosing the error. Do you have a Discord?

**Comment by XiaomiDE** [comment]
I'm still crashing as well even with the newest pre-release.

Discord: xashbe

**Comment by capricorn8** [comment]
If you want to know, whether this is okay for me – yes!

**Comment by PC-Shark966** [comment]
> After I updated my computer to build 22631.3155 yesterday, EP is crashing constantly. The latest pre-release (first entry on the release page) doesn't fix this issue. Any ideas?

Ich habe das selbe Problem
Nach dem Deinstall des Updates KB5034765 geht alles wie vorher.
die Windows Version ist die 23H2 - 22631.3085

**Comment by khei** [comment]
I'd like to comment, but first: Restarting EP worked

...I'd like to share a happening that maybe shed light on the mentioned problems when starting my laptop this morning I feel might be relevant:
>>>
Pre Windows loading there was a BIG WHITE NOTICE from Microsoft asking me if I'd like to [Sync Accounts] <>
I'm in Europe, so this is some kind of new customer acceptance scheme that EU Law has imposed onto Microsoft? 
This was blocking entry to Windows logon, ie: I **had**  to "Accept or Deny" 

I answered "No" to this new sync-thing ...then loading of Windows cont'd: 

= EP crashed saying ".. tried 3 times..etc"

(have NEVER had any EP problems before now ...)

PS. My last reg-backup I don't want to use as its old "ExplorerPatcher_22621.1555.55.1.reg" dated from may 5, 2023:
If same next Win-boot to Reset settings to default and perform 3rd reboot

- - - - - - - - - - - 
Explorer Patcher Version P ver. 22621.2861.62.2
Windows 11 Pro 23H2 - 22631.3085
Windows Feature Experience Pack 1000.22684.1000.0

**Comment by Amrsatrio** [comment]
So, the pattern seems to be that only EU users are having the crashes... I am well aware that EP crashes when it goes into OOBE. Thanks for the hints, I will try to fix it.

**Comment by PC-Shark966** [comment]
> By any chance do you guys use Start11, StartAllBack, or similar utilities? I just upgraded 3 of my devices to 22621.3155 and one of my devices to 22631.3155 and everything works fine.
> 
> I might push a new prerelease later today which I don't know if it will fix your issues or not.

Ja das lag wirklich daran:
Ich hatte Open Shell für das Startmenue drauf
https://github.com/Open-Shell/Open-Shell-Menu
Ich mag das neue Menue nicht.
das wäre noch eine Verbesserung im ExplorerPatcher :-)

Jetzt scheint es mit dem Win-Update (KB5034765) jetzt auch zu laufen.
DANKE

**Comment by capricorn8** [comment]
Also for, it seems that Open Shell is causing the issue.

Is that something you can fix in EP? Honestly, I don't want to give up any of these two :-)

**Comment by geircito** [comment]
Everything working just fine here :-)

**Comment by pyrates999** [comment]
What version of open shell are you running?

**Comment by PC-Shark966** [comment]
Die Letzte Version 4.4.191

**Comment by Amrsatrio** [comment]
> Also for me, it seems that Open Shell is causing the issue.
> 
> Is that something you can fix in EP? Honestly, I don't want to give up any of these two :-)

If the same versions of EP and Open-Shell work in the previous Windows build but not on the latest Windows build, please report in their Issues section.

**Comment by Amrsatrio** [comment]
> I'm still crashing as well even with the newest pre-release.
> 
> Discord: xashbe

Sent you a friend request!

**Comment by XiaomiDE** [comment]
As others i'm also in EU.

https://github.com/valinet/ExplorerPatcher/issues/2808#issuecomment-1943467133 seems to sum it up perfectly.
Today everything worked fine without issues for some reason.

Only thing UI related i have that maybe might be causing issues is PowerToys but afaik i have made no UI or explorer changes there that would interfere.

> > I'm still crashing as well even with the newest pre-release.
> > Discord: xashbe
> 
> Sent you a friend request!

Accepted. Might be hard to chat due to time zone difference though, will see ;)

**Comment by PC-Shark966** [comment]
Hallo,
Ich habe nun OpenShell Deinstalliert und wieder neu Installiert.
Es geht wieder.
Es kam danach das Update vom ExplorerPatcher und auch jetzt geht alles wie immer.
Mehrere Neustarts durchgeführt - TOP
DANKE

Windows version: 23H2 (22631.3155)
ExplorerPatcher version: 22621.3007.63.1
OpenShell: version 4.4.191

**Comment by Zataroons** [comment]
> Also for me, it seems that Open Shell is causing the issue.
> 
> Is that something you can fix in EP? Honestly, I don't want to give up any of these two :-)

Sorry, to confirm, you disabled OpenShell and EP works?

I'm on W11 .3155 as well, EP constantly crashing. Tried to uninstall but the system refuses to roll it back. I found one fix to stop the crashing in File Explorer Options; when I selected "Launch folder windows in a separate process" it stopped crashing, but File Explorer still refuses to open any actual windows.

Also an EU user, btw.

**Comment by capricorn8** [comment]
> Sorry, to confirm, you uninstall OpenShell and EP works? I tried that, doesn't do it for me.

In OpenShell, under "General Behavior" I unchecked "Start automatically for all users". That did the job. Once EP has been successfully loaded, I could manually start the StartMenu.exe part of Open Shell.

With the latest pre-release of EP this workaround is not needed anymore. Everything as it should be.

**Comment by capricorn8** [comment]
> Sorry, to confirm, you uninstall OpenShell and EP works? I tried that, doesn't do it for me.

In OpenShell, under "General Behavior" I unchecked "Start automatically for all users". That did the job. Once EP has been successfully loaded, I could manually start the StartMenu.exe part of Open Shell.

With the latest pre-release of EP this workaround is not needed anymore. Everything as it should be.

**Comment by Zataroons** [comment]
> > Sorry, to confirm, you uninstall OpenShell and EP works? I tried that, doesn't do it for me.
> 
> In OpenShell, under "General Behavior" I unchecked "Start automatically for all users". That did the job. Once EP has been successfully loaded, I could manually start the StartMenu.exe part of Open Shell.
> 
> With the latest pre-release of EP this workaround is not needed anymore. Everything as it should be.

Okay, I tried that, went to OpenShell settings, disabled "start automatically for this user", restarted, nothing. Strangely, it doesn't work for me. I don't know. Maybe you got lucky I guess.

Windows 11 .3155, ExplorerPatcher 3007.63.1 and OpenShell 4.4.191

**Comment by pyrates999** [comment]
Please install the latest pre-release and try again.

**Comment by Amrsatrio** [comment]
If the latest prerelease of EP fixed the crashes, I will promote it into a release and this issue may be closed.

**Comment by capricorn8** [comment]
> If the latest prerelease of EP fixed the crashes, I will promote it into a release and this issue may be closed.

For me, it does ! Many thanks !!

**Comment by Zataroons** [comment]
Windows 11 .3155, ExplorerPatcher 3007.63.1 and OpenShell 4.4.191 still crashing for me.

**Comment by pyrates999** [comment]
> Windows 11 .3155, ExplorerPatcher 3007.63.2 and OpenShell 4.4.191 still crashing for me.
> 
> You guys want a log from me or something maybe? Just let me know what to do, no problem.

Please post windows version and build.  You posted the last part only.  Always post the full number.  You can find this by running winver.
Please post explorer patcher version by posting a screen shot in about from the EP Properties application.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.  You said just EP and open shell 4.4.191?

**Comment by Amrsatrio** [comment]
@pyrates999 Sending the last part only for this context is fine. 22621 and 22631 share the same files.

**Comment by Zataroons** [comment]
> @pyrates999 Sending the last part only for this context is fine. 22621 and 22631 share the same files.
> 
> @Zataroons Does uninstalling open-shell resolve the issue? I just need the time to understand how open-shell works then I can try to piece together a fix if that is indeed causing the crashes.

I tried to uninstall OpenShell, still nothing. Even with EP uninstalled, File Explorer just refuses to open; if I disable the "launch folder windows in a separate process" in File Explorer Options, then File Explorer just crashes every time I open anything. If I enable it, then it just doesn't open anything. I think something had a breakdown in the Windows Registry so I tried an /sfcscan with EP uninstalled, but nothing.

Haven't changed any settings since last year. Last year I had another File Explorer crash issue, someone recommended I change the context menu to Windows 10. I did, also had to disable the Windows 11 right-click menu but then it all worked. I tested it by switching back to the W11 version a few days ago but it didn't work so I switched it back to the W10 version, as you can see in the screenshots below. I'm pretty sure I restarted after this so it was before the Windows 11 22631.3155 update set in.

I even tried to uninstall the .3155 update multiple times, but it just refuses to, I don't know why.

I do use Windows Tweaker from the Windows Club but I haven't touched it in months so I don't think that's causing any issues? Other than that, I downloaded Files to have access to File Explorer in the meanwhile but I only added that last night, long after everything else.

I'll send the screenshots separately below for clutter.

**Comment by Amrsatrio** [comment]
It looks like you have disabled the Tabs feature flag, or some other feature flag. You need to reset them because disabling them is causing crashes now. It is unrelated to EP.

**Comment by Zataroons** [comment]
![Screenshot 2024-02-17 111405](https://github.com/valinet/ExplorerPatcher/assets/151464655/7e0a6dd9-a6e0-4c10-9514-7b320c930a64)
![Screenshot 2024-02-17 112650](https://github.com/valinet/ExplorerPatcher/assets/151464655/98a9f3cf-96b1-4bab-b86e-f27a810c5411)
![Screenshot 2024-02-17 112658](https://github.com/valinet/ExplorerPatcher/assets/151464655/99d2cc0b-28d4-4e1d-8a85-43fd4504a06b)
![Screenshot 2024-02-17 112705](https://github.com/valinet/ExplorerPatcher/assets/151464655/3b953b69-f1ac-4d30-ab01-b7c17634ecef)
![Screenshot 2024-02-17 112714](https://github.com/valinet/ExplorerPatcher/assets/151464655/96000630-5317-44ff-b5a8-f82685b881aa)
![Screenshot 2024-02-17 112741](https://github.com/valinet/ExplorerPatcher/assets/151464655/6f9b6a88-531b-46b3-b2c3-7a28ddf8545d)
![Screenshot 2024-02-17 112747](https://github.com/valinet/ExplorerPatcher/assets/151464655/01fdb062-bfa2-45cd-8a0b-664ae20ae7c2)
![Screenshot 2024-02-17 112754](https://github.com/valinet/ExplorerPatcher/assets/151464655/85f75798-6b88-4f3e-8d4b-93209b882756)
![Screenshot 2024-02-17 112806](https://github.com/valinet/ExplorerPatcher/assets/151464655/a9db9098-9e62-4b39-b2b7-47a938691a39)
![Screenshot 2024-02-17 112811](https://github.com/valinet/ExplorerPatcher/assets/151464655/dcdf12b4-d869-491a-b7c6-ae33fe968dc4)

**Comment by Zataroons** [comment]
> It looks like you have disabled the Tabs feature flag, or some other feature flag. You need to reset them using ViVeTool because disabling them is causing crashes now. It is unrelated to EP.
> 
> Check this out: [#2355 (comment)](https://github.com/valinet/ExplorerPatcher/issues/2355#issuecomment-1947307575)

This? OK, I'll give it a shot now and let you know https://github.com/thebookisclosed/ViVe/releases

**Comment by Zataroons** [comment]
> It looks like you have disabled the Tabs feature flag, or some other feature flag. You need to reset them using ViVeTool because disabling them is causing crashes now. It is unrelated to EP.
> 
> Check this out: [#2355 (comment)](https://github.com/valinet/ExplorerPatcher/issues/2355#issuecomment-1947307575)

The ViVETool command worked perfectly, File Explorer is back, reinstalled OpenShell, everything still working.

Sadly I guess I'll have to get used to the tabs or to Windows 10, but a small price to pay for the bigger package.

Thanks again!
