### ISSUE TITLE
Windows 11 personalization settings crashes 80% of the time when it is opened from the desktop right click menu

### ISSUE THREAD

**Issue by WillaBytes** [valinet/ExplorerPatcher#2809]
Windows 11 personalization settings crashes 80% of the time when it is opened from the desktop right click menu. In Event Viewer it states that ExplorerPatcher has something to do with it. The Windows settings window pops up for a split second, then blinks and disappears. Sometimes it stays open, but most of the times it crashes.

Here are the Event Viewer logs:
```
AppName SystemSettings.exe 
AppVersion 10.0.22621.2792 
AppTimeStamp 3a143f4b 
ModuleName ExplorerPatcher.amd64.dll 
ModuleVersion 22621.2861.62.2 
ModuleTimeStamp 65858f42 
ExceptionCode c0000005 
FaultingOffset 000000000000d283 
ProcessId 0x51c 
ProcessCreationTime 0x1da5d49cad4511b 
AppPath C:\Windows\ImmersiveControlPanel\SystemSettings.exe 
ModulePath C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll 
IntegratorReportId a9ec445f-08a2-49f7-aafb-99226837e6ad 
PackageFullName windows.immersivecontrolpanel_10.0.6.1000_neutral_neutral_cw5n1h2txyewy 
PackageRelativeAppId microsoft.windows.immersivecontrolpanel 
```

How can I resolve this issue? Extremely good utility otherwise. Makes Windows usable! :)

**Comment by Amrsatrio** [comment]
Please disable "Register this utility as shell extension" in EP properties -> File Explorer.
