### ISSUE TITLE
Win10 related features appear to have been removed in 24H2

### ISSUE THREAD

**Issue by hoiyuyiu** [valinet/ExplorerPatcher#2810]
(the f*ing MS has just released their latest Dev&Canary Build of Win11 (26xxx) 24H2, yes, Dev channel directly jump from 22h2 to 24h2)

And it seems that the notification area of Win10 taskbar has been removed in the latest dev&canary build of Win11 (Dev 26052.1100). 
I don't actually sure cuz i am not so familiar with the Registry
BUT the notification area of win10 taskbar do disappear and the related settings are empty or unable to change
![image](https://github.com/valinet/ExplorerPatcher/assets/61400426/470e503e-d9bb-4018-baab-81d6395dae45)

System icon cannot be set, or in other words, it disappeared
![image](https://github.com/valinet/ExplorerPatcher/assets/61400426/61af900a-a2b6-4c62-af66-264f8ce5ec65)
other application icons have gone either and I have opened the corresponding settings window, it was blank, but I just couldn't open it again, so I couldn't provide the picture. 

Also, the rounded corners can't be disable as well......

I don't expect these settings to work again, I'm now more reporting this awful situation. Of course, it will be pretty good if these features can be restored, if not, then I can only tell that it's a pity

**Comment by Amrsatrio** [comment]
The system tray will come back, don't worry. It's in the final phases of testing.
