### ISSUE TITLE
File explorer open when app enter or exits fullscreen

### ISSUE THREAD

**Issue by rappepi** [valinet/ExplorerPatcher#2811]
When an application enters or exits full-screen mode, a file explorer opens. This bug started when I installed EP and remains the same even after attempting to uninstall the program.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please describe the app that you used in order to trigger this issue.

**Comment by rappepi** [comment]
After installing the lastest pre-release of explorer patcher, the issue I was experiencing has been resolved.
Thanks a lot for your help.
