### ISSUE TITLE
Right-click End Task not functional with Windows 10 taskbar style

### ISSUE THREAD

**Issue by iN0053** [valinet/ExplorerPatcher#2812]
Per title, the right-click option "End task" doesn't work when taskbar style is set to Windows 10. The right click option is enabled in window's own settings > system > for developers and isn't on by default. The feature has no issues when the taskbar is left as Windows 11. Might just be that since it was introduced in windows 11 the old taskbar style is missing a component that makes the right-click option function.

**Comment by pyrates999** [comment]
I remember this being asked about before in another issue.

**Comment by Amrsatrio** [comment]
Just to point out that the old taskbar in Windows 11 is frozen in time, in 2021. One day we'll touch the code that summons the jump lists, don't worry.

**Comment by Amrsatrio** [comment]
For my future reference, the feature flag is 42592269 (EndTask) and is toggleable on 22621.2361.

**Comment by Amrsatrio** [comment]
This feature will come in the reimplemented taskbar, ETA June-August 2024. (I hope)

**Comment by Amrsatrio** [comment]
The reimplemented taskbar has been released for 22H2 and 23H2, which includes the End Task feature. Closing.

**Comment by gex581990** [comment]
I'm on latest pre-release and end task still doesn't work

**Comment by Amrsatrio** [comment]
Use Windows 10 (ExplorerPatcher) taskbar style. We no longer offer more support on the stock Windows 10 taskbar.

**Comment by gex581990** [comment]
> Use Windows 10 (ExplorerPatcher) taskbar style. We no longer offer more support on the stock Windows 10 taskbar.

Ahhh! I didn't notice that was a new option! Thank you! Now it works just fine.

**Comment by XDiZi** [comment]
win 11 23H2 22631.2861 
win 10 taskbar explorer patcher works wierd
gives me an old style popup *screenshot* saying that the program is not responding (it is responding)
even if i click end task it is still not closing)
does anyone know the fix to this? or maybe the cause?
(i used windhawk earlier to customize the taskbar)

<img width="349" height="243" alt="Image" src="https://github.com/user-attachments/assets/42df5b0f-48ac-4d39-ab8d-3c41bc0f826a" />

**Comment by Amrsatrio** [comment]
Known issue. Initially the 11 taskbar end task handler code does this too, but then they updated the code to fix it. I haven't integrated the update yet.

**Comment by XDiZi** [comment]
> Known issue. Initially the 11 taskbar end task handler code does this too, but then they updated the code to fix it. I haven't integrated the update yet.

Alright, thanks :3 
could you notify me when the fix is out?

**Comment by XDiZi** [comment]
> Known issue. Initially the 11 taskbar end task handler code does this too, but then they updated the code to fix it. I haven't integrated the update yet.

is it out?
