### ISSUE TITLE
Doubled icons in Windows 10 taskbar

### ISSUE THREAD

**Issue by firminunderscore** [valinet/ExplorerPatcher#2813]
![image](https://github.com/valinet/ExplorerPatcher/assets/40271484/c8caf21d-8967-46b3-b66c-c8d707e35d22)
When I open applications, they are duplicates. I've tried to unpin and re-pin them, but nothing changes. I don't have the problem on the Windows 11 taskbar.

**Comment by tallman69** [comment]
If you are using the Windows 10 style Taskbar, It would appear the that you have the Quick Launch toolbar activated.  Right click on an open space on the taskbar, then hover the pointer over `Toolbars`.  If `Quick Launch` has a check mark next to it, uncheck it.

**Comment by firminunderscore** [comment]
No, I don't. It keeps doing it 😕
![image](https://github.com/valinet/ExplorerPatcher/assets/40271484/9f24d073-d109-43c7-8b7f-1e171fc3663c)

**Comment by Amrsatrio** [comment]
An issue common to Chromium browsers. Try to unpin the pinned Edge, and pin the opened Edge. At least it works for Chrome.

**Comment by firminunderscore** [comment]
Already tried, it doesn't work. It does it on all my software

**Comment by pyrates999** [comment]
You may have the option to not combine icons in the taskbar.  Please disable it: https://www.lifewire.com/how-to-disable-taskbar-button-grouping-2626110

**Comment by firminunderscore** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/40271484/1f046b51-e296-43e4-a996-357802b21c9c)
😐

**Comment by Amrsatrio** [comment]
> You may have the option to not combine icons in the taskbar. Please disable it: https://www.lifewire.com/how-to-disable-taskbar-button-grouping-2626110

Have you tried this?

**Comment by firminunderscore** [comment]
> ![image](https://private-user-images.githubusercontent.com/40271484/304649938-1f046b51-e296-43e4-a996-357802b21c9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNzQ5OTAsIm5iZiI6MTcwODA3NDY5MCwicGF0aCI6Ii80MDI3MTQ4NC8zMDQ2NDk5MzgtMWYwNDZiNTEtZTI5Ni00M2U0LWE5OTYtMzU3ODAyYjIxYzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDA5MTEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMGRlZTBkNzYyY2EyZDRlMzUwNjc3MjQyYjFjYmQ0NjcyMGM0NWI5NzVmMDM1MDU3M2FlNzVkZDk2YzMxNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2E02cV-LjG7kZS4L8jM0tYkRrrVUT3B2qUUZNxEVoNk) 😐

yes.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
> Please include any other software you have installed that modifies the UI of windows.

Yeah, I cannot reproduce your issue with that unchecked, so I suspect something else like 7+ Taskbar Tweaker must be modifying your taskbar.

**Comment by firminunderscore** [comment]
Hey, I apologize for the delayed response, I've been busy.
Regarding your question, I don't have any additional software that modifies the Taskbar behavior installed. I do have AltDrag, but I don't believe it's relevant to the issue. I've attempted various troubleshooting methods found online, but none have been successful. Additionally, it's worth noting that this issue doesn't occur on the Windows 11 Taskbar, as mentioned previously.

**Comment by pyrates999** [comment]
Uninstall AltDrag and see if this still occurs.

**Comment by firminunderscore** [comment]
> Uninstall AltDrag and see if this still occurs.

it happens again 😐

**Comment by pyrates999** [comment]
Ok, open up EP properties application and go to about and click on restore default settings.  This will reset the settings in EP.  Then click on restart file explorer in the bottom left corner.

Does it still occur?

**Comment by firminunderscore** [comment]
> Ok, open up EP properties application and go to about and click on restore default settings. This will reset the settings in EP. Then click on restart file explorer in the bottom left corner.
> 
> Does it still occur?

I don't know what I did to screw it up, but this thing seems to be working now. 🎉
Thanks for the help and have a nice day!
