### ISSUE TITLE
Win 11 10.0.22631.3155 - cannot read symbols

### ISSUE THREAD

**Issue by JYewdall** [valinet/ExplorerPatcher#2814]
After todays windows update explorerpatcher was struggling. I had to restore default settings and reboot a couple of times before it populated my taskbar.

Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.2861.62.2.c2b7c0292fff8608"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.2861.62.2.c2b7c0292fff8608" (valid).
[Updates] Local version obtained from hash is 22622.2861.62.2.
[Updates] No updates are available.
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for OS version 10.0.22631.3155.
[Symbols] Downloading to "C:\Users\john\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartDocked.dll" ("cd34dd474b18805a609c0a96a26834bc")...
[Symbols] Reading symbols...
[Symbols] Failure in reading symbols for "C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartDocked.dll".
[Symbols] Downloading symbols for "C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartUI.dll" ("b5efa79107344354c420269188acc612")...
[Symbols] Reading symbols...
[Symbols] Failure in reading symbols for "C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartUI.dll".
[Symbols] Finished gathering symbol data.
[Symbols] Finished "Download symbols" thread.
[EnsureXAML] 15 ms.

**Comment by Amrsatrio** [comment]
Give it a day, they will be available.
