### ISSUE TITLE
Live Tiles option missing

### ISSUE THREAD

**Issue by robbely** [valinet/ExplorerPatcher#2817]
The "Pin tiles to Windows 10 Start menu from File Explorer" seems to be missing in the latest version (22621.2861.62.2). Is there a way I can still activate this feature?

(OS ver 23H2 22631.3155)

**Comment by milesprower2293** [comment]
> The "Pin tiles to Windows 10 Start menu from File Explorer" seems to be missing in the latest version (22621.2861.62.2). Is there a way I can still activate this feature?
> 
> (OS ver 23H2 22631.3155)

that's because you now can pin stuff from regular file explorer windows

**Comment by robbely** [comment]
> > The "Pin tiles to Windows 10 Start menu from File Explorer" seems to be missing in the latest version (22621.2861.62.2). Is there a way I can still activate this feature?
> > (OS ver 23H2 22631.3155)
> 
> that's because you now can pin stuff from regular file explorer windows

Maybe I'm looking in the wrong place, I was trying to get live tiles working (it worked on an earlier version)

**Comment by robbely** [comment]
NVM, it seems like it was a temporary glitch - it went away after the second restart
