### ISSUE TITLE
Win 23H2 (Build 22631.3155)

### ISSUE THREAD

**Issue by kaste** [valinet/ExplorerPatcher#2819]
After the automatic Windows Update and its required restart, EP crashes and finally disabled itself.  I just guess that it is the Security Update (KB5034765) as it at least mentions **explorer.exe** in its release notes.

**Comment by Amrsatrio** [comment]
When you try to restart Explorer, does EP make Explorer crash again?

**Comment by kaste** [comment]
Not sure what you mean.   I now have the vanilla Windows experience, the standard status bar.  It looks like EP did everything right in disabling itself.  

Should I manually start EP again?  Because the vanilla explorer is running.

**Comment by Amrsatrio** [comment]
Yeah. Anyways, let's continue the discussion in https://github.com/valinet/ExplorerPatcher/issues/2808.
