### ISSUE TITLE
Windows Start Menu not working on Windows 11 22631.3155

### ISSUE THREAD

**Issue by JackTheKiller94** [valinet/ExplorerPatcher#2821]
The Windows 10 start menu style in ExplorerPatcher (version 22621.2861.62.2) no longer works in Windows 11 version 22631.3155.
![Screenshot 2024-02-14 163424](https://github.com/valinet/ExplorerPatcher/assets/47596947/732e22a5-73f9-48b9-accd-43d17764013b)

**Comment by geircito** [comment]
No problem here :-)

**Comment by geircito** [comment]
No problem here :-)

**Comment by Zataroons** [comment]
Same. Updated Windows, now File Explorer crashes every time I open it.

From the last time I had this issue;
- File Explorer, "disable Windows 11 context menu" is already selected.
- File Explorer, "Control Interface" is already set to Windows 10.

The only other modification program I use is OpenShell, but I don't think the OP uses that.

**Comment by JackTheKiller94** [comment]
> Similar issue. Not sure if you want it in a separate thread; updated Windows 11 to 22631.3155, now File Explorer crashes every time I open it.
> 
> From the last time I had this issue ( [#2457 (comment)](https://github.com/valinet/ExplorerPatcher/issues/2457#issuecomment-1818393246) );
> 
> * File Explorer, "disable Windows 11 context menu" is already selected.
> * File Explorer, "Control Interface" is already set to Windows 10.
> 
> Tried switching "Taskbar style" from Windows 10 to Windows 11, same issue.
> 
> The only other modification program I use is OpenShell, but I don't think the OP uses that.

ExplorerPatcher works normally, apart from just the handling of the Start menu. Not only does the Windows 10 menu not appear, but also the Windows 11 menu can no longer be customised.

Be that as it may, I have now reverted to the previous Windows build, and it is back to working as before.

**Comment by pyrates999** [comment]
Check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

Open up EP properties application and go to advanced, and check that **Enable symbols download** is ticked.

Symbols need to be downloaded for every new update of windows because they change with each new update for windows.

You can check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by Amrsatrio** [comment]
Please reinstall ExplorerPatcher.
