### ISSUE TITLE
W11 build 22621.3155 file explorer broken

### ISSUE THREAD

**Issue by Lost-In-Cyberspace** [valinet/ExplorerPatcher#2825]
Windows updated and I couldn't open File Explorer until I uninstalled ExplorerPatcher. So it's no explorer patcher or no File Explorer. As no FE means no Control Panel as well, I had uninstall EP.  Any other ideas?

**Comment by geircito** [comment]
My windows update to went smootly, no issues at all.

Windows version: 23H2 (22631.3155)
ExplorerPatcher version: 22621.2861.62.2 (3 weeks ago)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Have you tried the latest prerelease? I'm running 22621.3155 (should be the same as 22621.3155) and I have no issues with my File Explorer with Windows 7 command bar.

**Comment by Lost-In-Cyberspace** [comment]
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application. These should be screen shots.
> 
> Please include any other software you have installed that modifies the UI of windows.

The windows version and build are as in the header, namely W11 build 22621.3155. I don't have any other UI modifying software installed, not so far as I know, anyway. As far as the EP changes goes, I'm not sure: they were minimal. I uninstalled and reinstalled without applying any settings and immediately couldn't get File Explorer to open. I don't know if the reinstallation picked up settings i had made previously. (I imagined that uninstalling would prevent that, but maybe not.) With EP installed but disabled, FE won't start.

**Comment by janseris** [comment]
I installed Windows Update yesterday and now explorer crashes when I try open any window.

**Comment by Lost-In-Cyberspace** [comment]
> * Have you tried the latest prerelease?
> * Have you ever installed QTTabBar?
> * Have you ever messed around using ViVeTool? Because if you disable the feature flag for Tabs it will cause Explorer to always crash since a recent build.
> 
> I'm running 22621.3155 (should be the same as 22621.3155) and I have no issues with my File Explorer with Windows 7 command bar.

EP was from 2 December 2023. I did get a message about a new version, but it told me to (right?) click on the FE status bar, or perhaps toolbar and as I couldn't open FE I couldn't do that. I don't know if running ep_setup.exe will always fetch the newest version of just the version current when it was downloaded. The file name gives no clue, but the properties give version 22621.2506.60.1 - probably indicates that it installs a specific version. Like as not I changed the file name when I downloaded it. I'll know not to do that again.
I'll try the latest build.

**Comment by Lost-In-Cyberspace** [comment]
Latest build seems to have resolved the problem ...

**Comment by Amrsatrio** [comment]
Yep, that's it. Feel free to close this issue as completed.

**Comment by Lost-In-Cyberspace** [comment]
Thanks for your attention. I cannot tell you how much I hate MS messing with the UI the whole time.
