### ISSUE TITLE
Introduced Search Box doesn't work as expected.

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#2827]
Very Very thanks to @Amrsatrio for fixing the Flyout behaviour and delay. And also for Search Box. But there is a issue with Search Box that it doesn't work properly. I'm currently on 22621.2861 build (22H2) and enabled the Search Box. But it doesn't type on Taskbar. Rather than, it opens it normally like it opens when having only search icon. Check this for better understanding : 
[Recording 2024-02-15 093814.zip](https://github.com/valinet/ExplorerPatcher/files/14291317/Recording.2024-02-15.093814.zip)

**Comment by Amrsatrio** [comment]
This is pain to fix, since Win11 uses a completely different UWP app for the Search system. I am not planning to fix this at least this year.

**Comment by Amrsatrio** [comment]
Can this issue be closed because I feel like I don't want to be bothered with this?

**Comment by Vipin2003** [comment]
Its OK..at least you introduced it. Any plans to work on classic address bar with win 11 CB?
