### ISSUE TITLE
[URGENT] `wincorlib_orig.dll` is not properly being created on preview build `22621.3007.63.1`

### ISSUE THREAD

**Issue by ImportTaste** [valinet/ExplorerPatcher#2829]
I tried the latest preview version (22621.3007.63.1) just now, and when clicking on the Start button or pressing the <kbd>⊞ Win</kbd> key, nothing happens. The Start Menu does not open.

![image](https://github.com/valinet/ExplorerPatcher/assets/53661808/04d143ee-a8ee-411e-9d7e-42347866c6b5)

**Comment by Amrsatrio** [comment]
Thank you very much for spotting the oversight! Fixed in .63.2. Please let me know if there are still other issues on Windows 10 EP is not as widely tested there.
