### ISSUE TITLE
Explorerpatcher Windows 10 Start Menu Bug

### ISSUE THREAD

**Issue by let-biuld** [valinet/ExplorerPatcher#2833]
When I select the Win10 start menu and center it, if I don't open it for a long time, the Win10 start menu will pop up from the left and then move to the center when I open it again.

**Comment by Amrsatrio** [comment]
We have no plans on fixing this for now.

**Comment by let-biuld** [comment]
OK,Thanks
________________________________
发件人: Amr Satrio ***@***.***>
发送时间: 2024年2月16日 17:30
收件人: valinet/ExplorerPatcher ***@***.***>
抄送: let-biuld ***@***.***>; Author ***@***.***>
主题: Re: [valinet/ExplorerPatcher] Explorerpatcher Windows 10 Start Menu Bug (Issue #2833)


We have no plans on fixing this for now.

―
