### ISSUE TITLE
question about start menu windows 8

### ISSUE THREAD

**Issue by myrik228** [valinet/ExplorerPatcher#2834]
Is it possible to return the start menu from Windows 8 and any other functions from it? 
I just like its interface

**Comment by pyrates999** [comment]
Install open shell: https://github.com/Open-Shell/Open-Shell-Menu

**Comment by myrik228** [comment]
> Install open shell: https://github.com/Open-Shell/Open-Shell-Menu

![Снимок экрана 2024-02-16 224111](https://github.com/valinet/ExplorerPatcher/assets/121326836/4b905a28-0eb8-4dfa-96b4-6deee3cae6fd)
Sorry but I meant the full screen start menu of Windows 8

**Comment by Amrsatrio** [comment]
No. It was removed from Windows 10 way back in late 2015.

**Comment by myrik228** [comment]
> No. It was removed from Windows 10 way back in late 2015.

okey thank you
