### ISSUE TITLE
Explorer.exe stuck.

### ISSUE THREAD

**Issue by canerksk** [valinet/ExplorerPatcher#2835]
After receiving the latest update yesterday, when I open any folder, that folder, namely explorer.exe, Windows Explorer freezes. There was no such problem before, yesterday. I did not install any other application other than ep_setup.exe on the computer. Whenever I go into a folder and right click on any file (.html, .css, .js, .psd, .txt), it goes right away. There is no problem when navigating within the folder, it goes away when you right click. Sometimes it also happens when I enter the Downloads folder or any folder, it does not open the folder and does not respond.

OS version: Windows 11 23H2
OS Build:  22631.3155
OS Experience: Windows Feature Experience Pack 1000.22684.1000.0

**Comment by pyrates999** [comment]
Please try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3007.63.2_fb28688

**Comment by Amrsatrio** [comment]
Please state your EP version, and screenshot the File Explorer section of the EP properties window.

**Comment by canerksk** [comment]
I think this problem is caused by my operating system.
