### ISSUE TITLE
[Feature Request] An option to hide system icon

### ISSUE THREAD

**Issue by barraIhsan** [valinet/ExplorerPatcher#2836]
![image](https://github.com/valinet/ExplorerPatcher/assets/57800056/227b9c0b-b3c1-4aaf-8499-78a66aaba0ff)
Add a "hide" option here.

Use cases:
If you use [EarTrumpet](https://eartrumpet.app), the default audio in the system tray will be useless. The best approach (what I'm doing right now), is to put the default audio to the "Show hidden icon" thing. yes, I know it's "hidden", but it's just unnecessary to have it there.

**Comment by Amrsatrio** [comment]
Can't you hide it through the Customize system icons in the notification area?

**Comment by barraIhsan** [comment]
Customize system icons?

*also, mb, I should create a discussion instead of issues*

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/1ecca287-4b80-4a65-9d1b-239a7eafc21f)
Here

**Comment by barraIhsan** [comment]
oh, thanks.
*again, I'm sorry for creating issue*
