### ISSUE TITLE
Windows Explorer Crashing After Upgrade

### ISSUE THREAD

**Issue by hschlossberg** [valinet/ExplorerPatcher#2840]
Updates this morning for both Windows OS and ExplorerPatcher.  If I try opening MyPC or a shortcut to a folder (Windows Explorer), Windows Explorer only restarts each time (i.e. desktops and taskbar go blank and redraw).  Right-clicking on MyPC and selecting Properties seems to do nothing at all.  This all worked fine yesterday.  

After crashign Explorer a few times EP showed a message saying to restart EP (which I did) or uninstall (which I'd rather not do).

EP Version: 22621.3007.63.2
OS Build: 22621.3155
Windows Feature Experience Pack 1000.22684.1000.0
Windows 11 Professional

I see that an Explorer crash bug was fixedfor when the system is in OOBE... but I'm not sure how to tell if I am in OOBE or not.

**Comment by hschlossberg** [comment]
After uninstalling EP and then restarting my computer, the problem persists. Even after uninstalling today's Windows Update and restarting again, the problem persists.  Sigh.  Closing this issue.

**Comment by pyrates999** [comment]
If you disabled tabs using the vivetool, enable them again.
