### ISSUE TITLE
Search Box disappears when clicked on 

### ISSUE THREAD

**Issue by HAYDENCRAFT2008** [valinet/ExplorerPatcher#2842]
![image](https://github.com/valinet/ExplorerPatcher/assets/141458603/8444d912-f377-4493-bc14-a90a4d09cb94)

 
Title says it all, but how do I fix this if I can?

**Comment by HAYDENCRAFT2008** [comment]
So is this a bug or not??

**Comment by Amrsatrio** [comment]
It is a bug, which I won't fix because of how Search works under Windows 11.

**Comment by HAYDENCRAFT2008** [comment]
Well thanks for clarification. Too bad it doesn Work
