### ISSUE TITLE
Start menu settings not working

### ISSUE THREAD

**Issue by Irolan** [valinet/ExplorerPatcher#2845]
Several of the Start Menu settings don't work.
- Switching the style to Windows 10 doesn't do anything.
- The option to deactivate "recommended" doesn't work.
- The option to open "Start" in all apps by default doesn't work.

**Comment by Amrsatrio** [comment]
* Tell us your Windows OS build found in `winver`.
* Have you reinstalled ExplorerPatcher?

**Comment by Irolan** [comment]
I should have thought about reinstalling. I had installed ExporerPatcher and then ran Windows updates. Then I tried to change settings. Apparently the Windows updates caused some of the settings to not take effect. Reinstalling ExporerPatcher solved the issue.
Thank you.
