### ISSUE TITLE
Windows 10 taskbar doesn't hide in windows 11

### ISSUE THREAD

**Issue by Chaython** [valinet/ExplorerPatcher#2852]
Windows 10 taskbar doesn't hide in windows 11... a few pixels of the taskbar are visible when it is hidden, this is bad because I have an OLED.
I don't see it in full taskbar, but I do in small.
https://github.com/valinet/ExplorerPatcher/assets/6486343/a7ebbbb7-7d6e-4e5e-a49f-700942257168

**Comment by Amrsatrio** [comment]
This is a Windows issue since ages, not an EP issue. I am an OLED user too, I do have plans to mitigate this, but not this month or next month.
