### ISSUE TITLE
windows 10 style start menu not working after new windows 11 update

### ISSUE THREAD

**Issue by Jfeltz4** [valinet/ExplorerPatcher#2853]
the windows 10 style start menu isnt working after new windows 11 version 23h2 update (released around 17/02/2024) installed, only windows 11 style start menu displays. i apply the windows 10 style and restart file explorer and it displays windows 11 style start menu, i reapply the default windows 11 style and restart FE, then reapply windows 10 style and restart FE and it still stays on windows 11 style, also tried restarting my laptop and still displays windows 11 style start menu

**Comment by Jfeltz4** [comment]
![Screenshot (2)](https://github.com/valinet/ExplorerPatcher/assets/160378130/7f173461-30ef-4a00-b1df-e60fdc7fac29)

**Comment by Jfeltz4** [comment]
![Screenshot (2)](https://github.com/valinet/ExplorerPatcher/assets/160378130/76c729e4-ffa2-4505-b7f3-f0c889626ae0)

**Comment by milesprower2293** [comment]
reinstall explorer patcher
