### ISSUE TITLE
Not working after Windows 10 Feb Update 2024

### ISSUE THREAD

**Issue by XahidX** [valinet/ExplorerPatcher#2854]
Hello,

Explorer patcher stop working after February update 2024 for Windows 10 22H2, 
Weather widget also disappear (tried, Update weather now, clear local data)
Only One icon displays on the Taskbar, either network or volume or whatever you pick the last one)
These are the issues I observe. 

Windows 10 Version 22H2 OS Builds 19045.4046
Last update KB5034763
Explorer patcher updated to 22621.3007.63.2

Restarting computer/explorer does not change anything.

**Comment by pyrates999** [comment]
Uninstall EP and reinstall it.

**Comment by Amrsatrio** [comment]
If you install EP 22621.2861.62.2, does everything work?

**Comment by XahidX** [comment]
After Uninstall EP and Reinstall it, Partially works, 
Weather widget is completely gone, does not work anymore.
Icons are back volume/network etc. 
Thanks for Reply.

**Comment by Amrsatrio** [comment]
Alright. Weather issue is already discussed here: https://github.com/valinet/ExplorerPatcher/issues/2818
