### ISSUE TITLE
Turn each item on or off individually

### ISSUE THREAD

**Issue by CShisan** [valinet/ExplorerPatcher#2856]
I want each item to be turned on or off individually. In fact, I only want to use the "Start Menu" item because I need to customize my windows with other applications.The activation of other items causes problems when I use it with other applications.

**Comment by pyrates999** [comment]
Please elaborate.

**Comment by Amrsatrio** [comment]
He meant just like https://github.com/valinet/ExplorerPatcher/discussions/2828

**Comment by CShisan** [comment]
> Please elaborate. 请详细说明。

![image](https://github.com/valinet/ExplorerPatcher/assets/55305718/ff2fcd45-0ecc-4d6d-b830-e199909d5d5b)
I only want to open this item and not other items.

**Comment by CShisan** [comment]
> He meant just like #2828他的意思就像#2828

It should mean something similar

**Comment by Amrsatrio** [comment]
Sorry, we have no plans for this for now.
