### ISSUE TITLE
show notification icons not working

### ISSUE THREAD

**Issue by au10tic1** [valinet/ExplorerPatcher#2859]
running the latest version, whenever i  try to go into the section called: "Customize Notification area icons" and i try to to always show icons and notifications for a particular program, windows 11 freezes up the first time around, then after windows file explorer restarts on its own and i attempt to do it again, the changes made do not work, i even manually restart windows file explorer..

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.
