### ISSUE TITLE
EP + Start11, no Start11 settings entry on taskbar right click

### ISSUE THREAD

**Issue by djc5166** [valinet/ExplorerPatcher#286]
Not sure if this is a Start11 issue or EP issue, when both are installed side by side the S11 settings selection is missing from the task bar right click menu.

![image](https://user-images.githubusercontent.com/19207074/140556506-648d4129-c870-4999-99c3-f4d0f1192322.png)

vs

![image](https://user-images.githubusercontent.com/19207074/140556532-abd46825-fd88-4e2c-9b1c-cbbc169877e7.png)

**Comment by valinet** [comment]
The new taskbar when using Start11 presents a menu created by Start11.

Start11 only knows to work with that. When you enable the old taskbar, Start11 had no code to alter the menu of the old taskbar, which is totally different. So, the untouched old taskbar menu is shown, which never had any Start11 option.

So, this is not an issue with EP.
