### ISSUE TITLE
The taskbar is too wide

### ISSUE THREAD

**Issue by zhubing96** [valinet/ExplorerPatcher#2863]
How to reduce the taskbar width?  Use explorepatcher to set the vertical taskbar, the taskbar is too wide.

**Comment by zhubing96** [comment]
The taskbar is as follows:
![taskbar](https://github.com/valinet/ExplorerPatcher/assets/131648116/b92a6135-22de-4bd7-a687-0e32f7b4ebc9)
The system configuration is as follows:
![system](https://github.com/valinet/ExplorerPatcher/assets/131648116/47fc8f7d-0389-4de3-9c90-94ebd708e75e)
The explorerpathcer configuration is as follows:
![explorepatcher](https://github.com/valinet/ExplorerPatcher/assets/131648116/ac385b1c-067e-4f04-80f9-b401ce1f5d2b)

**Comment by pyrates999** [comment]
right click on the taskbar and tick **lock the taskbar**.  Then you can resize it.
