### ISSUE TITLE
Enable the Copilot button on the taskbar

### ISSUE THREAD

**Issue by paulor1982** [valinet/ExplorerPatcher#2866]
Hello!

With the latest Windows 11 updates, the copilot button appears fixed on the Windows 11 taskbar. Is it Enabled? I like to use the taskbar at the top but I can only do this if I use the Windows 10 taskbar style and in this version it is not possible to enable the copilot button on the taskbar.

Thanks in advance!

**Comment by milesprower2293** [comment]
For feature suggestions use discussions
https://github.com/valinet/ExplorerPatcher/discussions

**Comment by zake2002v2** [comment]
It's also added in Windows 10 as well, [located where the notification area should be](https://github.com/valinet/ExplorerPatcher/assets/42307974/41a6f42b-03ff-4965-bab9-4815f4d6f8c2), it seems to push the notifications button to the side
If I may add to the suggestion, it should instead replace the no longer working Cortana button!

**Comment by Amrsatrio** [comment]
The copilot button will come later in the reimplemented taskbar.

**Comment by YKefasu** [comment]
I found a way to do this:
![image](https://github.com/valinet/ExplorerPatcher/assets/129555908/78b7af47-f07e-44ba-8157-d3ccdd931234)

1. Desktop > right click > new > shortcut
2. Browse to location of edge browser
3. Once the shortcut is made, right click > properties
4. In the target field, just add `microsoft-edge://?ux=copilot&tcp=1&source=taskbar` after the target exe
it should be like ` "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" microsoft-edge://?ux=copilot&tcp=1&source=taskbar `

![image](https://github.com/valinet/ExplorerPatcher/assets/129555908/518db3cb-64cc-4c5b-b667-65e1281faea3)

5. change the icon to copilot 

![image](https://github.com/valinet/ExplorerPatcher/assets/129555908/97f5cae1-6248-419e-a084-b569b1a708bd)

7. Right click shortcut > more options > pin to taskbar

**Comment by zake2002v2** [comment]
No @YKefasu, that is NOT part of the actual taskbar! All you did was simply create a shortcut to open the Copilot button, that’s not what we want! What we want is the actual Copilot button to actually properly function correctly!
