### ISSUE TITLE
3rd Taskbar Style that simply re-enables Toolbars

### ISSUE THREAD

**Issue by wad11656** [valinet/ExplorerPatcher#2870]
([This post](https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems) says Discussions is closed so I guess I'll post here)

Can we please add a 3rd Taskbar Style that simply re-enables Toolbars? I don't want the pretty blue start button or the cute round search bars to disappear/change. Thank you.

----

Edit: Also...Is this project at risk of completely not working/losing all ability to restore Windows 10 taskbar functionalities, i.e. Toolbars?:

https://github.com/valinet/ExplorerPatcher/discussions/2586#discussioncomment-8523402

**Comment by Amrsatrio** [comment]
> Edit: Also...Is this project at risk of completely not working/losing all ability to restore Windows 10 taskbar functionalities, i.e. Toolbars?:

No, the project is not at risk as I've reimplemented the taskbar. But will the reimplemented taskbar survive updates or not is another story.

**Comment by Amrsatrio** [comment]
Sorry, we have no plans for this for now.
