### ISSUE TITLE
Right clicking explorer sidebar causes crash.

### ISSUE THREAD

**Issue by xSimone** [valinet/ExplorerPatcher#2872]
<img width="555" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/16178961/5c12c31e-8d43-4cbe-b60f-e0a4811a3eac">

If I right click any of this, explorer crashes and has to restart.. or it hangs and does nothing, and I have to force it myself.

**Comment by Amrsatrio** [comment]
1. Please state your Windows build number found in `winver`.
2. If you uninstall ExplorerPatcher, does it still crash when right clicking?

**Comment by AudioAnchorite** [comment]
Aha! I was wondering why I have to wait over a minute for the right-click menu to pop up. Explorer isn't crashing in my case, but any kind of right-clicking will cause a hang in explorer of over a minute. If I go into EP Properties and turn of "Disable the Windows 11 Context Menu", then there will be no more lag. The Windows 10 context menu seems to be glitching out.

I ran DISM and SFC, which fixed something else, but not this.

Windows 11, 23H2, OS Build 22631.3155

**Comment by xSimone** [comment]
That makes a lot of sense, I forgot I use the context menu instead of Win11's atrocious one. 

Thanks for expanding on that AudioAnchorite.

**Comment by AudioAnchorite** [comment]
OK, in my case, I discovered that the issue was actually being caused by iCloud for Windows. Mind you, I also ran DISM and SFC which did repair some issues with my OS image, and I also uninstalled and reinstalled EP twice while problem-solving. So, there could have been a combination of things going on, but regardless, I have completely solved my issues.

**Comment by pyrates999** [comment]
Can you tell us what version of iCloud for Windows you had installed?

I also think this was caused by your windows install having corruption that was then repaired by running sfc and dism.

**Comment by AudioAnchorite** [comment]
According to Windows 11 Installed Apps, the version was 15.0.215.0

**Comment by AudioAnchorite** [comment]
> I have iCloud installed too, if this helps.
> 
> Re-enabling Windows 11 Context Menu stops the issue.
> 
> Going back to Windows 10 Context Menu brings the issue back.
> 
> The problem still exists for me, and I do not know how else to share information.

Try uninstalling iCloud for Windows, that fixed my issue. I was able to reinstall it afterwards with no issue.

**Comment by Amrsatrio** [comment]
Sorry to say that issues with the old context menu (even when opened via show more options) are beyond EP's scope. There's not much we can do regarding it.
