### ISSUE TITLE
Incorrect search ui

### ISSUE THREAD

**Issue by NocturnalKing** [valinet/ExplorerPatcher#2875]
When I press the search icon instead of the windows 10 version i get the windows 11 center screen pop up with the rounded corners and general UI. 
![292890306-156e003c-2113-4c32-8045-4076c05d85fb](https://github.com/valinet/ExplorerPatcher/assets/49161708/80ec13e4-43ed-43d6-965d-006a0e568c7b)

I don't believe this is an issue on my end but if it seems like that I will provide screenshots of my current settings as well. Thanks in advance!

**Comment by HAYDENCRAFT2008** [comment]
I don't think it's doable to recreate, I at least wish it was square

**Comment by Amrsatrio** [comment]
The Windows 10 search cannot be restored. It is not a bug, it is what Windows 11 is.

**Comment by NocturnalKing** [comment]
alright i suppose it is what it is

**Comment by XuanChen1234** [comment]
I like to use the Windows 10 search UI, If you need to add the Windows 10 search UI + highlights option, so much better.

Windows 10's big search icon:
![306643482-e245d386-a75d-4700-91cd-121573fa8bed](https://github.com/valinet/ExplorerPatcher/assets/140480110/c7d4eb26-4987-4fb4-bf2c-ef444ebb9095)

Windows 10 21H2's search UI, have a highlights:
![256128351-38a2eb79-97fc-4d40-9d67-e2110abd520b](https://github.com/valinet/ExplorerPatcher/assets/140480110/9222d60a-2998-49b4-9c10-ad9fb9594e27)

Besides, also the news and interests, in Taskbar:
![306615010-881198df-c010-4216-849d-25efb3e2bc8f](https://github.com/valinet/ExplorerPatcher/assets/140480110/222149f0-ea12-4971-8c5e-2e90079f3d80)

@HAYDENCRAFT2008 The file location in Windows 10 is here: C:\Windows\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy
