### ISSUE TITLE
Option to combine only pinned taskbar icons

### ISSUE THREAD

**Issue by Karmalakas** [valinet/ExplorerPatcher#2884]
On Win 10 I used to have pinned icons always combined, but others were shown fully as usual. I believe this was the default behavior there for pinned. Would it be possible to have this on Win 11?

**Comment by pyrates999** [comment]
This is something MS would have to do and is beyond what EP is for.

**Comment by Amrsatrio** [comment]
Not at the moment. We have plans to reimplement the taskbar app buttons way later this year, and attempt to implement suggestions from the community.

Also, issues are for real issues only, not feature requests.
