### ISSUE TITLE
Unable to install due to "virus" in the file 

### ISSUE THREAD

**Issue by Aleeeh** [valinet/ExplorerPatcher#2889]
I was trying to update the program, but Windows 11 says it's virus and I do not find any workaround. Here's a screenshot of what I get when I try to execute it. 

![image](https://github.com/valinet/ExplorerPatcher/assets/24904169/65a017d5-95c2-4233-962d-98780f4191e0)
 

Thanks in advance for the help!

**Comment by MGM175** [comment]
Managed to replicate the issue; Windows Defender classifies the installer as "Trojan:Win32/Wacatac.B!ml", preventing the updating.

**Comment by realzoulou** [comment]
Same with me
* Windows 11 Home, 23H2, OS Build 22631.3155, Experience Windows Feature Experience Pack 1000.22684.1000.0
* Detected Backdoor:Win32/Bladabindi!ml ...  for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe
* Last Windows Malicious Software Removal Tool x64 : v5.121 (KB890830)

**Comment by bdurrer** [comment]
Interesting that mine named it differently:

`Detected Trojan:Win32/Wacatac.B!ml`

**Comment by IvansPhoto** [comment]
Windows Defender on my PC considers this as a `Backdoor:Win32/Bladabindi!ml.`

**Comment by CopyPasteAdmin** [comment]
same hier:
![grafik](https://github.com/valinet/ExplorerPatcher/assets/144927824/baec9beb-fba4-4901-aeaf-d2e9fb51dee9)

**Comment by pniaps** [comment]
This is duplicated in #2873
