### ISSUE TITLE
NEW EXPLORERPATCHER UPDATE HAS BEEN DETECTED AS MALWARE

### ISSUE THREAD

**Issue by ravenastar-js** [valinet/ExplorerPatcher#2890]
I have already performed several ExplorerPatcher updates, this was the only update that was detected as malware

:link: https://www.virustotal.com/gui/file/0d46bd6e83d661567efd6d79ae760a041f6a1ea72b4b043da428c7fbb93ad27f/details
:link: https://www.filescan.io/uploads/65d66fe126f1ddc579a3ad96/reports/ae3624c2-2831-409d-84d2-f5a985706031/overview
:link: https://hybrid-analysis.com/sample/0d46bd6e83d661567efd6d79ae760a041f6a1ea72b4b043da428c7fbb93ad27f/65d5dace634440950d069075
:link: https://tria.ge/240221-rvfq8sgh6v

---

VERSION DETECTED AS MALWARE => [22621.3007.63.3](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3007.63.3_1517de0)

**Comment by andrewjmetzger** [comment]
Tracked in https://github.com/valinet/ExplorerPatcher/issues/2873
