### ISSUE TITLE
Showing taskbar icon doesn't work at all

### ISSUE THREAD

**Issue by hondacbr600** [valinet/ExplorerPatcher#2895]
The issue occurs only when trying to show a specific icon, if i tick "Always show all icons..." they all show up.
![image](https://github.com/valinet/ExplorerPatcher/assets/15723130/8f0150e0-0483-4e05-860e-c345f4ecdce9)

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2273
