### ISSUE TITLE
EP Setup detected as "HackTool:Win64/Patcher!MSR" by Defender recently

### ISSUE THREAD

**Issue by Girofox** [valinet/ExplorerPatcher#2896]
It seems that Windows Defender seems to target EP setup as a whole. For me the file `C:\Program Files\ExplorerPatcher\ep_setup.exe` gets detected as `HackTool:Win64/Patcher!MSR` very recently despite disabled auto update of EP in settings. This seems like heuristic behavior detected because nothing changed at that file at all.

The detection signature `HackTool:Win64/Patcher!MSR` is not even malicious because Explorer Patcher is a ... well, drumroll ...  patcher, and does not even change any .exe or .dll file.

![image](https://github.com/valinet/ExplorerPatcher/assets/43116061/98ee69ba-1c83-4c36-b020-9868fad87167)

**Comment by Amrsatrio** [comment]
It techincally does change exe and dll files, but only in memory. Hence still a patcher. But seems like Microsoft classifies this thing as a software to break license agreements like crack software. I don't know 🤷

**Comment by Amrsatrio** [comment]
Anyways let's discuss this in https://github.com/valinet/ExplorerPatcher/issues/2873

**Comment by Girofox** [comment]
> It techincally does change exe and dll files, but only in memory. Hence still a patcher. But seems like Microsoft classifies this thing as a software to break license agreements like crack software. I don't know 🤷

What i find weird is that this happens so recently, Microsoft never bothered before, and EP exists long time already. Could be that Windows Defender is very aggressively because of heuristics and relatively new releases.
