### ISSUE TITLE
Unexpected consequences after updating to 63.4

### ISSUE THREAD

**Issue by Anixx** [valinet/ExplorerPatcher#2898]
After updating from 63.3 to 63.4 instantly the taskbar disappeared and I faced the authentication method setup screen that suggested me to set up face recognition or fingerprints. There was no way to exit, and the task manager was not appearing.

I pressed Ctrl+Alt+Del and choose to exit the session. After re-logon the taskbar appeared for about 1 second and again I was thrown to the authentication method setup. 

I was able to pass this screen only by agreeing to change the authentication method.

This is on Win11 22000.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Anixx** [comment]
Microsoft Windows [Version 10.0.22000.2176]

EP version: 22621.3007.63.4

**Comment by Anixx** [comment]
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/327adc46-9343-4f89-9104-3bce553fde08)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/41cebabe-d4ad-4c88-bd1a-f886b99ebfff)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/b42747ee-0cf0-4287-aa55-abeb1295798a)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/932aef56-3e78-43cd-9a16-2189fd0b6b1e)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/12b46463-ab5e-40f0-8200-a3ec2ee66429)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/ce70255b-372c-4dd3-a8d9-04549b4b6dc7)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/73cd3f18-88dd-4882-a61c-a42dd08960fc)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/faf8d1f7-2b62-417a-bdc7-73a7495772bc)
![изображение](https://github.com/valinet/ExplorerPatcher/assets/1271736/b5af3f6e-1bd8-4c06-a60a-6d9da62b3ffe)

**Comment by Amrsatrio** [comment]
You sure that "Show suggestions" and so on in Notifications is off? I did not change anything in the main DLL, only in the setup.

**Comment by Anixx** [comment]
I have notifications (if you mean the toasts) switched off.

**Comment by pyrates999** [comment]
You're running a version of windows from July 2023: https://support.microsoft.com/en-gb/topic/july-11-2023-kb5028182-os-build-22000-2176-fb3fb398-9c2d-4f2f-bede-6c610a560731

Please update to the current windows updates for it.  The build number should be: 22000.2777

**Comment by Amrsatrio** [comment]
> I have notifications (if you mean the toasts) switched off.

No not that, the checkboxes at the bottom that should say suggestions or something.

**Comment by Amrsatrio** [comment]
SCOOBE-related crashes have been fixed in 64.1.
