### ISSUE TITLE
Windows 24H2 build 26052.1100 breaks a lot of things

### ISSUE THREAD

**Issue by tauras129** [valinet/ExplorerPatcher#2899]
I upgraded to the latest windows version on the dev channel insider program and suddenly the windows 10 task bar and start menu are both broken( as in task bar has no clock or anything else on that side of the taskbar, and start menu is windows 11 start menu )

**Comment by pyrates999** [comment]
Please post explorer patcher version.  You should be running the latest pre-release if it is newer then the latest release.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.
