### ISSUE TITLE
Microsoft removed the Cortana button in 22621 because I think they've been deprecating it and keeping the button in the old taskbar was a burden for them to atleast make explorer.exe compile.

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#2916]
We found that the taskbar option in ExplorerPatcher found that "Show Cortana button" was gone.
Please add that option back.
I appreciate any and all advice and help, thanks!
![image](https://user-images.githubusercontent.com/140480110/307830680-01cd8eed-7204-4796-b4df-f00d298a2ba7.png)

**Comment by HAYDENCRAFT2008** [comment]
I wish Cortana opened Copilot
