### ISSUE TITLE
There is a conflict between the desktop terminal and the right-click ban on Windows 11

### ISSUE THREAD

**Issue by 4everImmortality** [valinet/ExplorerPatcher#2921]
I found there is some system modification plug-ins conflict with the right-click menu of Windows 11.
When I turn up the ExplorerPatcher
![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/e5b9fcb2-9442-4e5c-bb87-59f649b5b139)
the selection 'Open in terminal' disapear
When I restored the right-click to the Windows 11 style, it became normal.
![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/d09c945c-2ad7-4c87-83f5-a6e369b6c672)

Windows11 23H3
![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/3c23bdbd-3671-49a6-bb4f-63f3189cd49d)
![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/ccba96cc-a7f2-4307-9732-517f07841831)

**Comment by 4everImmortality** [comment]
> I don't think windows 10 menu's supported a terminal application.

![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/7e97bf9a-ff99-4bcb-83f4-8ad9ce8c10de)
It works in my laptop windows 11 22h2.

**Comment by pyrates999** [comment]
Ok, might be a version difference between 22h2 and 23h2 then, where 22h2 has the terminal option and 23h2 does not right now.

Can you post the build number of your windows 11 22h2?  You can find this by running winver.

**Comment by 4everImmortality** [comment]
> Ok, might be a version difference between 22h2 and 23h2 then, where 22h2 has the terminal option and 23h2 does not right now.
> 
> Can you post the build number of your windows 11 22h2? You can find this by running winver.

sure
![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/6d30843a-d10d-4905-bfdc-3eb1e27a2a36)

**Comment by pyrates999** [comment]
Microsoft might have removed the terminal option from the windows 10 menu in windows 11 starting in 23h2.  Can someone else confirm this?

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/78d9dcf7-709a-4c43-b2b2-f9d9c1dae6a2)
Fine on Canary. But I had to search for it first and then it'd appear in the classic right click menu.

**Comment by tjstheiii** [comment]
Try shift-right click. If I run terminal from start bar search it opens PowerShell window, but says it's an older version. If you shift right click a folder or the desktop you get the added option to Open PowerShell window here. I do now see open in terminal on the regular, but I have already searched and opened it and it still says it's an older version. If you want a specific version it looks like there is a flag.  (e.g. open with shift-click then "PowerShell.exe -Version 2.0") (ps: 23H2 build 22631.3296)

**Comment by 4everImmortality** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/2abf5e1d-7fe9-4f60-b2bd-6f1b233015b9)
![image](https://github.com/valinet/ExplorerPatcher/assets/69960602/4a27f1f1-07e6-433c-ba77-84baccc28ca8)

well， it fixed after I update the Windows terminal to the newest version, I guess the problem is may be that the registry of the terminal only wrote the new version of the win11 style context menu in the previous version, but not the old version of the context menu, and the new Windows and terminal versions fixed this issue. Thank you for your interest in this issue.
