### ISSUE TITLE
i cannot uninstall explorer patcher

### ISSUE THREAD

**Issue by 0s9df8c0sdfd0** [valinet/ExplorerPatcher#2925]
when i try to uninstall explorer patcher i get a error
![Screenshot 2024-02-29 150131](https://github.com/valinet/ExplorerPatcher/assets/159628909/a4fdae28-b461-4809-8374-8552901201ce)

**Comment by Amrsatrio** [comment]
ep_setup.exe has been deleted by Defender due to MS falsely flagging it as a virus. Please download the latest prerelease and rename it to ep_uninstall.exe, and run it.
