### ISSUE TITLE
Can't change Tab Switcher

### ISSUE THREAD

**Issue by hlebushekhub** [valinet/ExplorerPatcher#2926]
I'm on 23H2 (22631.3155) and EP stopped working with the Tab Switcher (alt + tab). None of the options change the Tab Switcher, it stays default (as in the pic). Has anyone else encountered such a problem?

![7Pq4YpkfgA](https://github.com/valinet/ExplorerPatcher/assets/75308456/143c4ef7-a7e8-4da9-86d1-e826d253e0bf)

**Comment by Amrsatrio** [comment]
That tab switcher does not look like the default one offered by Windows 11 22H2. Are you using any other tweak software?

**Comment by Amrsatrio** [comment]
Closing due to no response.
