### ISSUE TITLE
Request: Removing the app label from the taskbar

### ISSUE THREAD

**Issue by agenel** [valinet/ExplorerPatcher#2927]
It is a great patcher. I want to thank all the contributors first. 

I use the taskbar in a vertical position at the right of the screen. The labels of the apps appear in the worst possible way (see the image below). It would be great to see only the icon without the labels. 

Thanks in advance.  
![Screenshot 2024-02-29 231415](https://github.com/valinet/ExplorerPatcher/assets/26494804/44284da5-9361-4dd1-a023-78d23d143d37)

**Comment by pyrates999** [comment]
Set the icons to be combined then.  It doesn't show the label then.

**Comment by agenel** [comment]
That worked perfectly! Thanks!
