### ISSUE TITLE
Feature Request - File Explorer Control Interface

### ISSUE THREAD

**Issue by MidnightInAurora** [valinet/ExplorerPatcher#2930]
First I want to say thank you for a great app.  All of the UI issues I had when bringing up and testing Win 11 IOT Ent were resolved with a combination of the barely-functional OpenShell and the intelligently designed ExplorerPatcher.

For my uses, two of the most useful apps on Win 11 are the tabbed Notepad and tabbed File Explorer.  However, I despise change.  That's why my desktop has remained basically the same since the days of Windows 2000 Professional.

I really like the ExplorerPatcher option to revert back to the Windows 10 Ribbon.  However, I also really like the tabbed feature in the stock Win 11 File Explorer release.

My request - A fifth option in the Control Interface setting, i,e. "Windows 10 Ribbon with Windows 11 Tabs."

Bet it's not as easy as it sounds.

Thank you for a great product.

Jim
Aurora, Colorado USA

**Comment by pyrates999** [comment]
The code for the tabs has to be there for windows 10 explorer ribbon in order to activate it.  And there's no reason for Microsoft to back port that feature from the windows 11 explorer to the windows 10 explorer.  So I don't see this happening.

**Comment by Amrsatrio** [comment]
> Bet it's not as easy as it sounds.

Unfortunately that is very true. That combined with changes MS keeps pushing, I don't think this is viable to maintain.
