### ISSUE TITLE
start menu tiles color

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#2932]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/2386

<div type='discussions-op-text'>

<sup>Originally posted by **flowercatte** November  2, 2023</sup>
Hello! When I'm using windows 10 tiles on the start menu, they're the monochrome color that was pushed in a later update. is there a way to configure them to show the accent color as the background like in the older style of windows 10?</div>

**Comment by XuanChen1234** [comment]
@valinet

**Comment by valinet** [comment]
@XuanChen1234 You have been blocked on my account for repeatedly spamming my mail inbox with unnecessary tagging. *Ești un nesimțit*.
