### ISSUE TITLE
Add an option to bring the 21996 action center

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#2933]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1110

<div type='discussions-op-text'>

<sup>Originally posted by **Lixkote** March 19, 2023</sup>
You can get it working by replacing the files, but its very unstable.
You can also add an option to make it rouneded like with the Windows 10 Start Menu.
![image](https://user-images.githubusercontent.com/95425619/226119347-2989246a-078c-445f-82df-defd54621f24.png)
</div>

**Comment by XuanChen1234** [comment]
@valinet

**Comment by valinet** [comment]
@XuanChen1234 You have been blocked on my account for repeatedly spamming my mail inbox with unnecessary tagging. **Ești un nesimțit**.
