### ISSUE TITLE
HackTool:Win64/Patcher!MSR in https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

### ISSUE THREAD

**Issue by NWeissenberg** [valinet/ExplorerPatcher#2938]
Microsoft Defender erkennt HackTool:Win64/Patcher!MSR in https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe, durch Update des ExplorerPatchers
Bedrohung hoch

**Comment by Amrsatrio** [comment]
Please download 62.2 release or 63.4 pre-release, which are not detected by defender. Both 63.2 and 63.3 have been flagged by MS as virus and there were not much that we can do.
