### ISSUE TITLE
Feature Suggestion：Add network proxy option to weather widget

### ISSUE THREAD

**Issue by AelepantB** [valinet/ExplorerPatcher#2941]
I love this app. It solved a problem for me. Win11 does not let me adjust the taskbar height or change the taskbar merging function. I tried many ways to make the Win11 taskbar behave like before, but none of them worked. Your app fixed this issue for me.

The weather widget is really great. I don't have to open the browser or my phone to check the weather forecast. Sometimes, looking out of the window is not very reliable.

My suggestion: Add a proxy option in the weather widget. This would allow users who care about their privacy or have poor connections to choose their preferred network.

Thank you for creating such a wonderful product.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
