### ISSUE TITLE
Win 23H2 ( Build 22631.3235) - EP crashing

### ISSUE THREAD

**Issue by capricorn8** [valinet/ExplorerPatcher#2950]
After 3w of silence on installing EP 22621.3007.63.4 and predecessors, I'm now experiencing the same exact issue as described in #2808. Even the same workaround I figured out 3w ago (do not automatically start Open-Shell, but only once the system is up) works this time as well.

I'm on 10.0.22631.3235 meanwhile.

**Comment by Amrsatrio** [comment]
Just installed Open-Shell 4.4.191 on 22635.3276 with all but IE features checked during installation, I observe no crashes. Even works with my reimplemented taskbar that is soon-to-be-released. Don't have a device that I can update to that preview version at the moment. I'm confused...

**Comment by Amrsatrio** [comment]
Uninstalled the latest cumulative update to rolled back to a previous Beta build, and this happened:

![D605E650-DA4F-47CB-ADF4-16C85E686563](https://github.com/valinet/ExplorerPatcher/assets/20662640/c15b99be-9a51-4e2c-ba10-5f64bc8dfdf4)

Uninstalled EP and now it's in an irrecoverable crash loop. So I think this is an Open-Shell issue.

**Comment by Amrsatrio** [comment]
Updated to your exact build. Open-Shell works fine without crashes.

**Comment by capricorn8** [comment]
This recent issue is strange indeed.

Today morning EP crashed rightaway. I completely uninstalled Open-Shell and rebooted multiple times - no change, EP kept crashing.

Then it seemed that FileMenuTools (by LopeSoft) might be causing the issue. I also uninstalled this utility. The first reboot was fine but during subsequent ones EP kept crashing.

Currently my workaround is to boot the system (with Open-Shell and FileMenuTools), accept EP crash during run-up, the run EP_setup TWICE. The first run leads to another crash, the second run is successful and after that everything seems to be fine.

**Comment by Monutchuan** [comment]
Its usually happen on W11, I am very very afraid to use this app (I still have 50% trust in it).
So we have to stop system updates or use W10, this is the better way.

**Comment by capricorn8** [comment]
> Its usually happen on W11, I am very very afraid to use this app (I still have 50% trust in it).

For me EP has been super stable on W11 for a long time - until the Win update 3w ago.

**Comment by capricorn8** [comment]
> Currently my workaround is to boot the system (with Open-Shell and FileMenuTools), accept EP crash during run-up, the run EP_setup TWICE. The first run leads to another crash, the second run is successful and after that everything seems to be fine.

Unfortunately, my conclusion was too quick. The first crash seems to trigger a restart of File Explorer which leads to some apps not loaded again (eg. Adobe Cloud).

As much as I love using EP, for the time being I see no other way than to uninstall and hoping that someday these issues will have disappeared in smoke....

**Comment by Amrsatrio** [comment]
If you have Discord, please contact me on Discord, I'll give you a special build of EP that should be able to pin down where the crash is (like in the photo above). The link to the server is in the README/main page of this repo.

**Comment by capricorn8** [comment]
I don't have Discord. Can we handle this through mail and/or messenger?

**Comment by Daxfight** [comment]
Hi I got the same issue. 

Restarting Windows, I open up with Explorer crash message.
Installing again, makes it crash again.

2nd install, all goes well and explorer patcher works fine. 
Perhaps I can do it via discord, maybe it'll be the same issue for him? 

Edition	Windows 11 Home
Version	23H2
OS build	22631.3235
Experience	Windows Feature Experience Pack 1000.22687.1000.0

EP: 22621.2861.62.2

**Comment by pyrates999** [comment]
> I don't have Discord. Can we handle this through mail and/or messenger?

you can access discord through a web browser.

**Comment by Amrsatrio** [comment]
If the issues are related to Second Chance OOBE, or whatever MS is pushing to you after logon, then I've tested that the latest prerelease should have it fixed. Feel free to reopen if it's still happening.

**Comment by capricorn8** [comment]
The latest version works like a charm, also in presence of Open-Shell / FileMenuTools and even with most recent Win update KB5035853 (10.0.22631.3296).

Thanks a lot for your effort to make it work again!

**Comment by Amrsatrio** [comment]
You're welcome! Always at your service.
