### ISSUE TITLE
Taskbar Position not working on secondary monitors

### ISSUE THREAD

**Issue by Vaneeyo** [valinet/ExplorerPatcher#2958]
![image](https://github.com/valinet/ExplorerPatcher/assets/103961848/4082a18f-3d55-4edc-a0d1-903552c72d3d)
I'm on Win 11 23H2 Build 22631.3155. Only the taskbar on my primary monitor on the top. But I have set them all to top

**Comment by pyrates999** [comment]
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Vaneeyo** [comment]
After multiple restarts of my computer it suddenly started to work normally. I'm going to close this issue.
