### ISSUE TITLE
"Explorer.exe" crash is observed and captured by windbg after installing the application on Windows 11 insider build.

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#2959]
ExplorerPatcher version: 22621.3007.63.4
Windows 11 insider build
Repro steps :
1. Deploy the latest OS 
2. Perform windows and store updates 
3. Install the application from vendor site 
4. Run the setup file
5. Observe the Explorer.exe Crash.

Observations: -
1. After installing the Application, wait for 10-15 seconds Crash will be observed.
2. Need to restart the machine.
3. Performed same machine validation and issue Repro in Ge and Not Repro in Moments scenarios.

**Comment by Amrsatrio** [comment]
Hi, I'm very happy to resolve this issue. Which exact build of Ge does the crash occur in?

**Comment by Michellehdr** [comment]
@Amrsatrio the bug was found on GE build: 26071.1

**Comment by Amrsatrio** [comment]
According to https://changewindows.org/timeline/pc, it is an unreleased build, therefore there's nothing I can do until it is publicly released.

**Comment by Michellehdr** [comment]
@Amrsatrio can we keep this ticket open until the build is publicly released?

**Comment by Amrsatrio** [comment]
Sure thing.

**Comment by riverar** [comment]
@Michellehdr Can you clarify who you are and your intentions? Perhaps update your GitHub profile? Are you working on top-crashers from internal Watson data?

**Comment by Amrsatrio** [comment]
Fixed in 64.2, and tested on the recently released GE build 26080.

**Comment by riverar** [comment]
@Michellehdr Would be great to get a reply.

**Comment by pyrates999** [comment]
> @Michellehdr Would be great to get a reply.

This was already fixed in a pre-release.

**Comment by riverar** [comment]
> > @Michellehdr Would be great to get a reply.
> 
> This was already fixed in a pre-release.

Unrelated to my questions tho, right? 👍

**Comment by pyrates999** [comment]
Please don't pester other github users.

**Comment by Michellehdr** [comment]
@riverar @pyrates999 our tester confirmed this bug has been fixed. Please let me know if you have any other concern. Thanks!

**Comment by riverar** [comment]
@Michellehdr Hey there, if you could answer the questions above that'd be great. https://github.com/valinet/ExplorerPatcher/issues/2959#issuecomment-1995220984
