### ISSUE TITLE
Start menu will not change to Windows 10 on Windows 11 Build 22621

### ISSUE THREAD

**Issue by OscarHullFirebase** [valinet/ExplorerPatcher#2961]
Hi. I set my ExplorerPatcher just today to use a windows 10 taskbar and start menu. however when I opened the start, it is the default windows 11 one and not Windows 10.

**Comment by milesprower2293** [comment]
https://www.lifewire.com/classic-start-menu-in-windows-11-5189891

**Comment by Amrsatrio** [comment]
Please reinstall EP after performing a feature upgrade. We will mitigate this in a future release, by adding a notification that says "ExplorerPatcher needs to be reinstalled".
