### ISSUE TITLE
Toolbar icon only option is lager

### ISSUE THREAD

**Issue by The1GrayMagic** [valinet/ExplorerPatcher#2963]
The toolbar on Windows 10 had icons that were just the app image (no text of the app). Example a folder would just show the folder icon and not the icon and its folder name. Is there an option for the smaller icons for this?

**Comment by tallman69** [comment]
Unlock the taskbar.  Right click in an open area of the toolbar.  At the top of the context menu hover the pointer over `View` and then click on `Small Icons`.  From that same context menu, you can choose whether or not to show titles and/or text for the icons. Then you can lock the taskbar to save a little space if you like.

**Comment by The1GrayMagic** [comment]
What I want: ![IMG_2640](https://github.com/valinet/ExplorerPatcher/assets/140342558/5285eaed-c71e-4970-84ba-d33fe1d3f900)
What happens for small and large icons![es](https://github.com/valinet/ExplorerPatcher/assets/140342558/dbfdb065-d06d-444a-a6d8-dee6484e1735)
![e](https://github.com/valinet/ExplorerPatcher/assets/140342558/48f99a96-bac2-4b31-8b04-e9dfc28f5ef2)

**Comment by pyrates999** [comment]
This might be what you want: https://www.lifewire.com/how-to-disable-taskbar-button-grouping-2626110

**Comment by The1GrayMagic** [comment]
This video shows how to: [https://www.youtube.com/watch?v=kJD61-rm0mA](https://www.youtube.com/watch?v=kJD61-rm0mA). You need to click on the two bars of the grouping, not the taskbar it self.
