### ISSUE TITLE
"VoiceMeeter" Tray icon is bugged

### ISSUE THREAD

**Issue by 1nstntKaRma** [valinet/ExplorerPatcher#2966]
"VoiceMeeter Banana" Tray icon is missing ..
every startup needs to manually open VoiceMeeter, Disable Tray Icon, Enable Tray Icon.

if open properties > Restart File Explorer > VoiceMeeter Tray Icon Disappears agian.

**Comment by pyrates999** [comment]
Please enable all tray icons due to this: https://github.com/valinet/ExplorerPatcher/issues/1454

**Comment by 1nstntKaRma** [comment]
wait all my tray icons have to be visible 24/7 so VoiceMeeter tray icon is not bugged?
is that what you ment?


cuz i have like 16 of them, i cant XD.

**Comment by pyrates999** [comment]
ok, it might be a bug with voicemeeter then.

**Comment by Amrsatrio** [comment]
Please confirm if the bug exists under the Windows 11 taskbar. If it exists too, then it means it's a bug on VoiceMeeter's side.

**Comment by Amrsatrio** [comment]
Closing due to no response.
