### ISSUE TITLE
In Safe Mode, Explorerpatcher crashes the explorer, crashes are looped 

### ISSUE THREAD

**Issue by MONADE38** [valinet/ExplorerPatcher#2968]
In Safe Mode, Explorerpatcher crashes the explorer, crashes are looped 
and it is impossible to run a prgramm (crash too fast) 
and impossible to exit safe mode
windows 11 23H2

**Comment by Amrsatrio** [comment]
Please hold down Ctrl+Alt+Shift when Explorer is starting up. I've been thinking of fixing this issue since long.

**Comment by Dogway** [comment]
Experiencing the same issue, but on normal boot.

Icons are not rendered (black squares), and display blinks black, looped crashes

**Comment by Dogway** [comment]
> @Dogway Please try the latest EP 64.1 with the latest Windows build, and make a new issue explaining reproduction steps.

I did a few changes to fix it. Updated to 64.2 second pre-release. And for good measure updated OpenShell to latest in case there was a conflict. So far no more hang issues.

Typically I get shortcut icons rendered in black (in Desktop and file explorer), but for the last few days all seems nice. Now I blocked autoupdates as everything looks stable.

Thank you!

**Comment by MONADE38** [comment]
Hey, guys. (windows 11 23H2) 
I have version 64.1 and all windows updates, and I no longer have looping crashes in Safe Mode. 
Thank you very much! 
Can I make a suggestion? 
I'm using Win11clocktoogler with explorerpatcher, do you think these functions can integrate into explorerpatcher ? 
I think the soft "taskbar tweaker ++"functions too ! 
I say it like that, 
I don't realize how much work goes into your software, but anyway thank you very much, everything works very well now in safe mode! 
Have a nice day

**Comment by pyrates999** [comment]
> Hey, guys. (windows 11 23H2) I have version 64.1 and all windows updates, and I no longer have looping crashes in Safe Mode. Thank you very much! Can I make a suggestion? I'm using Win11clocktoogler with explorerpatcher, do you think these functions can integrate into explorerpatcher ? I think the soft "taskbar tweaker ++"functions too ! I say it like that, I don't realize how much work goes into your software, but anyway thank you very much, everything works very well now in safe mode! Have a nice day

Please file this under a new discussion.
