### ISSUE TITLE
[Fixed in prerelease 64.1] After installing KB5035853 (W11 22631.3296), the TaskBar is transparent

### ISSUE THREAD

**Issue by zme-ul** [valinet/ExplorerPatcher#2975]
![Untitled](https://github.com/valinet/ExplorerPatcher/assets/25272649/3229ca74-6023-4555-80ec-f51e97928b45)

**Comment by Dyaxler** [comment]
Same... ever after updating to the latest Pre-Release build of EP.

**Comment by PrivateRoDee** [comment]
Same issue

**Comment by davdat** [comment]
I also just updated KB5035853 and can confirm this behaviour. Win 10 Taskbar is transparent, Win 11 is not. Was working correctly before update.

**Comment by PrivateRoDee** [comment]
I uninstalled the update, its back to normal.

**Comment by 0AA55H** [comment]
Mine is also transparent. I hope someone will make a fix...

**Comment by TomasDresler** [comment]
Having the same symptoms, I really beg for update!

**Comment by Amrsatrio** [comment]
I will make a fix within 24 hours. Please be patient.

**Comment by rarnold99** [comment]
> I will make a fix within 24 hours. The code patterns that Valinet wrote to restore the acrylic doesn't work anymore with the latest build, and needs updating. Please be patient.

Excellent! Thanxs in advance!

**Comment by elmondohummus** [comment]
> I will make a fix within 24 hours. The code patterns that Valinet wrote to restore the acrylic doesn't work anymore with the latest build, and needs updating. Please be patient.

Thank you very much!

**Comment by topwizprogramming** [comment]
I have this problem too, looking forward to the fix.

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. Feel free to let me know of further problems, and sorry for the inconvenience.

**Comment by mjtDeCompile** [comment]
Prerelease fixed it. Thanks !

**Comment by ytakahashi1981** [comment]
When I tried to update to the pre-release, Norton Data Protector reports this.
(note: this is my first update from pre-release channel.)
![image](https://github.com/valinet/ExplorerPatcher/assets/16332474/d2cdb801-4fce-4a07-a532-3bdcde48c481)
Cause: A suspicious operation attempted to delete a file protected by a data protector
Target: C:\Windows\dxgi.prev

Why is this behavior caused? If the reason is using pre-release channel, I think it's no probrem.(expecting installable from stable-channel.)

**Comment by Jackysi** [comment]
Pre-release fixed it. Thank you for superfast fix for something that shouldn't be required to done in the first place. Sorry Yes I am super annoyed by the way Microsoft is handling Windows.

**Comment by Amrsatrio** [comment]
Reopening this issue until the EP update that fixes this becomes a release build.

**Comment by Amrsatrio** [comment]
@ytakahashi1981 `C:\Windows\dxgi.dll` is ExplorerPatcher's code that is injected into `explorer.exe`, not a Windows system file. This has been this way since the birth of EP, and unfortunately many antiviruses (and some people) do not like how EP is designed. Maybe pressing プロレスの除外 would help?

**Comment by ytakahashi1981** [comment]
@Amrsatrio thank you, I see.
I wondered if this issue's fix causes the behaviour, but I understood not have to worry👍

**Comment by Epyon83** [comment]
Just want to confirm pre-release fixed transparent taskbar in Win11; thanks for the quick fix <3

**Comment by AKVADUS** [comment]
Also have this transparent bug. But I'm not rushing to install pre-release and fix it. I assume, that it might be pretty nice feature for EP - to have an option to keep task bar transparent or solid. Also it would be nice to have an ability to choose the transparency in a full range - up to fully sold state. I hope it is not hard to implement, and it would be very useful feature.

**Comment by photoshooters** [comment]
Could someone tell me how to install pre-release version please?

**Comment by Epyon83** [comment]
> Could someone tell me how to install pre-release version please?

checkbox for pre-release installation under updates, search for new update; bam ur done

**Comment by opus-x** [comment]
For a temporary fix when using OpenShell and for those who want to wait for an official release, read this:
https://github.com/valinet/ExplorerPatcher/discussions/1807#discussioncomment-8768138

**Comment by baldoarturo** [comment]
I just want to say I had this issue and cannot believe how fast it was fixes
This is a superb work! Making a donation right ahead

**Comment by JRAndreassen** [comment]
Hi...
I have the latest update but background and foreground color is black.
Si I can't see the menu etc..
It is visible when mouse is hoovering, so it's not a show-stopper.
Any indication on how I can change the background color ?
![image](https://github.com/valinet/ExplorerPatcher/assets/8507596/b80923b4-9a48-4726-b009-0e28f63b838e)

**Comment by squarerank** [comment]
Are we able to make this available in normal version! It seems the prerelease fixed the issue but not sure if I'm wanting pre releases. Unless it is usually stable!

**Comment by Amrsatrio** [comment]
@JRAndreassen Hi, are you running EP 64.1 downloaded from https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.1_9e9c016?

**Comment by Amrsatrio** [comment]
@squarerank I am afraid if #2873 would happen again. I want to give it few days to see the evolution of [detections on VirusTotal](https://www.virustotal.com/gui/file/167f90fad0d3df4e2bfd4a6b07e459a6e414f63fa20e473aedc8c82f3b21eaef/detection).

**Comment by squarerank** [comment]
@Amrsatrio Gotcha no problem! I'm just so glad it's fixed and so quickly as well! :) Thx a bunch!

**Comment by JRAndreassen** [comment]
> @JRAndreassen Hi, are you running EP 64.1 downloaded from https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.1_9e9c016?

ExplorerPatcher v 22621.3007.63.2
 Win 11, OS Build 22631.3296

**Comment by JRAndreassen** [comment]
> Hi... I have the latest update but background and foreground color is black. Si I can't see the menu etc.. It is visible when mouse is hoovering, so it's not a show-stopper. Any indication on how I can change the background color ? ![image](https://private-user-images.githubusercontent.com/8507596/312511755-b80923b4-9a48-4726-b009-0e28f63b838e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjUxMjIsIm5iZiI6MTcxMDQyNDgyMiwicGF0aCI6Ii84NTA3NTk2LzMxMjUxMTc1NS1iODA5MjNiNC05YTQ4LTQ3MjYtYjAwOS0wZTI4ZjYzYjgzOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTQwMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBiM2Y2MDEzZjJkMjFmZTRhNWQ4YjU1YmJhNDRlMzA5ZWRiZWMxNWMzODFkM2Q2NjJjMmMyYzZmZDUzNWE2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x_hOfLfKluTZZ-DCaNhL5naiCzDde5C3U64wEgu9PG4)
> 
> Sorry if this is a dup... Thanks JR
This has been resolved with the latest update [2261.3296.64.1]

**Comment by lvt1693** [comment]
I'm sorry to ask, but how to unfix this? It's like a cool feature to me.

**Comment by pyrates999** [comment]
> I'm sorry to ask, but how to unfix this? It's like a cool feature to me.

Install NiceTaskBar from the windows store if you want it.  It is not going to be unfixed as it was an actual bug.
