### ISSUE TITLE
User menu inaccessible from win10 start menu

### ISSUE THREAD

**Issue by PlusLaplace** [valinet/ExplorerPatcher#2977]
While I was using the windows 10 start menu, I noticed that when I click on my own user icon, the user menu (lock, sign out, change acc. settings) does not show up. 

I am using version 22621.2861.62.2 of EP, running windows 11 23H2 Build no 22631.3296.

**Comment by pyrates999** [comment]
open up task manager and kill explorer.exe and then run task manager again and run explorer.exe

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by PlusLaplace** [comment]
I have done killed and rerun exporer.exe, issue still persists.

I've only changed a few settings in ep, namely the start menu style. Here are the screenshots
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/08444050-e054-4690-a0c2-fe856492033a)
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/afa5f67c-3023-43bb-bc33-ef3de4a71c83)
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/d5597348-1842-4303-a9e1-19eac76de614)
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/c29b7f06-efa8-4a90-b119-e3124a466903)
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/72cc2a88-8e24-41f8-b92c-375646a3cdb9)
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/4a50d642-22dc-474c-93bd-0f827193394d)
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/c75c0c2d-adb9-4dc5-a68a-449af301c868)
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/ecab90b4-d2d8-4537-8243-fb14a25c7184)

There is no other software I am currently using that modifies the UI of Windows.

Additionally, a new version of ep came out between my original post and this one (version 22621.3296.64.1) I have updated to this version, but the issue has not been resolved.

**Comment by pyrates999** [comment]
In EP properties application, click on file explorer, untick register as shell extension and click restart file explorer in the bottom left corner.

**Comment by PlusLaplace** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/163222795/f159010e-480d-46c5-9ccb-1043d1e58756)

Done, however, this has not solved the issue.

**Comment by pyrates999** [comment]
Thank you.

Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  Copy and paste the results here.

**Comment by PlusLaplace** [comment]
Running on Windows 11, OS Build 10.0.22631.3296.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 47430
ITrayUIHost = 3BD318
explorer.exe!TrayUI_CreateInstance() = 1A5DFC
Setup explorer functions done
Setup uxtheme functions done
[SMA] match1 = E2A4D
[SMA] match2 = E2A8C
[SMA] match3 = 3300C
[SMA] CStartExperienceManager::GetMonitorInformation() = 1066B8
[SMA] CExperienceManagerAnimationHelper::Begin() = 72B46C
[SMA] CExperienceManagerAnimationHelper::End() = 2669FE
[SMA] match7a in CStartExperienceManager::Hide() = 3F81B
[SMA] match7b in CStartExperienceManager::Hide() = 2AD46F
[SMA] CStartExperienceManager::OnViewCloaking() = 71030
[SMA] match9 in CStartExperienceManager::OnViewHidden() = 3300C
[SMA] CStartExperienceManager::OnViewUncloaked() = 72750
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup windows.storage functions done
Setup inputswitch functions done
Setup peopleband functions done
Installed hooks.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
Progman: 786622
Progman hook: 461441
0 0
[EnsureXAML] 94 ms.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.3296.64.1.15361a1b13c6f570"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.3296.64.1.15361a1b13c6f570" (valid).
[Updates] Local version obtained from hash is 22622.3296.64.1.
[Updates] No updates are available.

**Comment by pyrates999** [comment]
Did you try to access the user menu from the start menu while the EP console was running?

**Comment by PlusLaplace** [comment]
Yes

**Comment by pyrates999** [comment]
Try switching to the windows 11 start menu and see if that shows the user menu.

**Comment by PlusLaplace** [comment]
It does

**Comment by pyrates999** [comment]
did you run vivetool to disable or enable anything?

**Comment by PlusLaplace** [comment]
My apologies, I'm not familiar with vivetool. Was I supposed to?

**Comment by pyrates999** [comment]
Ok, just checking if you enabled or disabled any windows features using the vivetool.

**Comment by PlusLaplace** [comment]
I definitely didn't. I made sure to check if I actually did and just forgot about it, but that doesn't seem to be the case either. Could there be another reason for the console to not be showing anything?

**Comment by Amrsatrio** [comment]
Try switching to the 11 start menu and check your user icon. Is there a yellow dot on it? Try dismissing it, don't know if it would make a difference though.

**Comment by PlusLaplace** [comment]
There is no yellow dot

**Comment by pyrates999** [comment]
In the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

**Comment by Amrsatrio** [comment]
Identified the issue that causes this in StartUI.dll. Will make a new prerelease version which will include the fix.

**Comment by Amrsatrio** [comment]
Fixed in https://github.com/valinet/ExplorerPatcher/commit/d11445afdad5d2b05826dfa6d6c987a740ee5b05
