### ISSUE TITLE
Trying to narrow down a weird laptop screen bug

### ISSUE THREAD

**Issue by xSimone** [valinet/ExplorerPatcher#2980]
Hello,

So as of the past week I've suddenly had this odd bug that I cannot seem to find the root cause of.

The bug is when I leave my Laptop alone until it activates its screen saver / turns off its screen, when I come back and move my mouse, nothing happens.

The screen remains black, the hard disk indicator starts processing and then all of a sudden, bang, it crashes and I'm going through post as if I just ordered a reboot of the system.

Anyone having the same problem?

Asus Scar 18, Win11 Latest

**Comment by Amrsatrio** [comment]
Please state the ExplorerPatcher version you're using.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
> hard disk indicator starts processing

> ordered a reboot of the system

Looks lke your laptop bluescreened? Should not be EP's fault based on my experience with it in the past 2 years.

**Comment by xSimone** [comment]
[031724-9234-01.dmp](https://github.com/valinet/ExplorerPatcher/files/14626570/031724-9234-01.dmp)

Maybe this can help

**Comment by pyrates999** [comment]
You can try analyzing the dmp file by following the instructions here: https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/crash-dump-files

**Comment by Jazzzed** [comment]
I experienced this same issue yesterday. I’m also using a laptop. It went into a screensaver, and when I tried to exit out, there was little to no response from explorer. My desktop did appear, but you couldn’t click and open anything including EP. Memory was a runaway train. Nearly 95% in use. I have 16GB of RAM, and its usually no more than 40% during regular usage. Rebooting fixed the issue, but being a laptop, the only way to reboot was to unscrew the bottom and remove the battery. The computer wouldn’t respond when trying a hard shut down from the power button. Also the internal fan was full power during this episode. 

EP 22621.3296.64.1
Windows 22631.3296

**Comment by pyrates999** [comment]
what laptop did you experience this on?  What is the model number?

did you try holding down the power button for 10 seconds at least to force it to turn off?

**Comment by Jazzzed** [comment]
Its a Dell Precision 3541 with an i7 processor and a Nvidia Quadro P620 video card. I tried everything I could think of to shut it down before pulling the battery, yes.

**Comment by pyrates999** [comment]
Sounds like you got power issues with that laptop.  Therefore this is not a bug caused by EP.

**Comment by Jazzzed** [comment]
Lol. Wrong answer.
