### ISSUE TITLE
News app on start menu

### ISSUE THREAD

**Issue by robbely** [valinet/ExplorerPatcher#2985]
On windows 10, the news app cycles between news story images and some news story text, but in 11 with explorer patcher it only cycles through images.

This seems to be only an issue with microsoft news, is this something that can be fixed

**Comment by Amrsatrio** [comment]
Not really. The Windows 10 start menu is facing extinction as it is no longer present in 24H2, so fixing it is not really worth the effort in the long run.

**Comment by robbely** [comment]
Did you mean that this is something missing in windows 11 that's not worth putting/coding back in, or just a bug that's not worth looking into?

**Comment by Amrsatrio** [comment]
> something missing in windows 11 that's not worth putting/coding back in

Yup.

**Comment by robbely** [comment]
> Yup.

OK many thanks. It's a shame Microsoft decided to kill off tiles as it was one of Windows 10's best features.

I know fixing this is beyond the scope of this particular app, but it would be great if some clever person on GitHub did create a fix.
