### ISSUE TITLE
trasparent background on task bar after last W11 update

### ISSUE THREAD

**Issue by photoshooters** [valinet/ExplorerPatcher#2987]
Hello, after last - today - update on Windows 11 the background of the task bar is transparent.
![image](https://github.com/valinet/ExplorerPatcher/assets/14160350/0bc180ae-4994-4140-a8a7-9a2759141a2b)

**Comment by metallserge** [comment]
same with Windows 10 taskbar style

**Comment by photoshooters** [comment]
> same with Windows 10 taskbar style

yes, I mean when I set Windows 10 taskbar style

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2975
