### ISSUE TITLE
A good reason to make a feature from the bug (transparency).

### ISSUE THREAD

**Issue by AKVADUS** [valinet/ExplorerPatcher#2993]
The recent transparency bug really looks good in certain cases. As for me - it is a really good feature and I would use it with pleasure for good. I suggest, that it will be a good and simple feature to improve EP variability. If you could make this optional feature - that would be just great.   
Anyway, thank you for a great job with EP.

**Comment by aemsx** [comment]
+1

**Comment by Cyberdr3am** [comment]
+1 with the last windows update the taskbar is transparent

**Comment by ekungurov** [comment]
The way it worked is awful because it makes text unreadable.

**Comment by anderfam** [comment]
The bug causing the taskbar to be transparent makes it very difficult for me to see my icons.  How soon will this be fixed?  Is there a workaround until it is fixed?

**Comment by t-n-z** [comment]
great program, thank you for bringing back simple and elegant functionality taken away by windows.. but i too am having the transparency bug, its the lesser of two evils, i much prefer it over the fat taskbar and i could see the other guys' perspective over how it would look pretty good in certain circumstances, but at the ,moment its difficult to operate, hopefully theres a fix soon

**Comment by AKVADUS** [comment]
Bug is already fixed - please read the corresponding topic. This topic is an idea to save a transparent option as a feature for the next EP releases. In my config,, text is readable enough. 
![transparent](https://github.com/valinet/ExplorerPatcher/assets/163304153/5459f965-ffa9-4696-86d3-6243a8864236)

**Comment by t-n-z** [comment]
I found the relevant pre-release (link to the thread for transparent taskbar as a bug here for anyone else who lands on this thread first: https://github.com/valinet/ExplorerPatcher/discussions/953), apologies for taking this topic off-track Akvadus, but thanks for pointing me in the right direction to fix.

**Comment by pyrates999** [comment]
If you want a transparent taskbar, where you can adjust the transparent level, install NiceTaskBar from the Microsoft Store.

I vote against this because there's no way to adjust the transparency with this bug.

**Comment by mmschmieg** [comment]
I agree that this would be a nice feature to have. I was pleasantly surprised by the transparency as I have had that set in Ultimate Windows Tweaker, but it stopped working with Windows 11.

**Comment by AKVADUS** [comment]
> If you want a transparent taskbar, where you can adjust the transparent level, install NiceTaskBar from the Microsoft Store.
I use EP and don't wont to install any additional software, what can result the conflicts with EP etc. Adjustable transparency is a nice option of course, but it'll make EP heavier. However, the optional switch between solid and full transparent state will probably cost nothing.

**Comment by Amrsatrio** [comment]
As I've said here: https://github.com/valinet/ExplorerPatcher/discussions/3003

Sorry for being dismissive here, but what about installing TranslucentTB? It should take less than a minute to install it from the Microsoft Store.

First, I'd like to say that I'm not sponsored or affiliated in any way with it, but figured that I like it very much with two reasons being lightweight and compatible with EP.

Second, if I add this feature into the Windows 10 taskbar, people would beg me to add stuff like different behaviors during different situations like what TTB can do. As well as making the 11 taskbar transparent, and if they ever stop working they can become a bother for me to maintain. So for now I'm not considering to make this a feature.

Thank you for your understanding.

**Comment by RobaloAmigo** [comment]
+1 for making it as feature

**Comment by mmschmieg** [comment]
> As I've said here: #3003
> 
> Sorry for being dismissive here, but what about installing TranslucentTB? It should take less than a minute to install it from the Microsoft Store.
> 
> First, I'd like to say that I'm not sponsored or affiliated in any way with it, but figured that I like it very much with two reasons being lightweight and compatible with EP.
> 
> Second, if I add this feature into the Windows 10 taskbar, people would beg me to add stuff like different behaviors during different situations like what TTB can do. As well as making the 11 taskbar transparent, and if they ever stop working they can become a bother for me to maintain. So for now I'm not considering to make this a feature.
> 
> Thank you for your understanding.

I understand where you are coming from. I checked out TTB and it works fine. No sense in duplicating it or reinventing the wheel. Thanks for the tip on that.

**Comment by Amrsatrio** [comment]
> +1 for making it as feature. TranslucentTB is working today but can stop working at any time.

If TTB stops working, the sole dev devoted on making the taskbar transparent will make a fix.

I am really busy right now with reimplementing the Windows 10 taskbar so this project can still stay alive in the future.

**Comment by AKVADUS** [comment]
Thank you for answer and pointing on to TranslucentTB. Have already installed it - it is OK. However, this is an additional process, which is eating about 15Mb of RAM, and which has to be included in autorun.... Not such a nice solution, as it might be within EP.

**Comment by Joduai** [comment]
I thought transparent taskbar was a feature in latest tueasday patch.
I am disappointed that this is just a bug, and updating EP fixed this.
Would be fantastic if EP allowed to make taskbar transparent, as it looks great on darker wallpapers.
Using another program just for this is not a good option.

**Comment by ekungurov** [comment]
@Joduai it's a bug, and usability (UX) of it is awful. Idk maybe you were lucky with your wallpaper colors, but in general the captions are unreadable.

**Comment by pyrates999** [comment]
@Joduai it isn't going to be added to EP.  Install the suggest third party application instead.
