### ISSUE TITLE
Fortnite BattleEye launcher detects explorerpatcher.IA-32.dll as suspicious on latest update

### ISSUE THREAD

**Issue by mariokiller64** [valinet/ExplorerPatcher#2999]
21:34:42: Installing BattlEye Service...
21:34:44: BattlEye Service has been successfully installed.
21:34:44: Updating...
21:34:49: Launching game...
21:34:52: Note: File blocks can be ignored if they don't cause problems with the game.
21:34:52: [INFO] Blocked loading of file: "C:\Program Files\ExplorerPatcher\ExplorerPatcher.IA-32.dll".

This just started happening after I downloaded the latest explorerpatcher 22621.3296.64.1
the game still loads, so I suppose I could ignore it, but I did think it was odd, and didn't want any future problems or issues arising from this.

![Screenshot 2024-03-13 214444](https://github.com/valinet/ExplorerPatcher/assets/447783/80077026-0c71-4129-981d-0b30d451d362)

**Comment by Amrsatrio** [comment]
Has always been this way. You can safely ignore that message. Or you can disable shell extension in the file explorer section of EP properties.

I've been playing Fortnite with EP installed since 2022 and you van trust my words.
