### ISSUE TITLE
Virus Total Report shows three security vendors have flagged this update

### ISSUE THREAD

**Issue by CloudNetworkArchitect-JT** [valinet/ExplorerPatcher#3000]
https://www.virustotal.com/gui/file/167f90fad0d3df4e2bfd4a6b07e459a6e414f63fa20e473aedc8c82f3b21eaef

![ExplorerPatcher VirusTotal Report](https://github.com/valinet/ExplorerPatcher/assets/100221556/83f217dc-361d-44eb-bef8-0b55fbcbca80)

**Comment by Yasukii** [comment]
please read https://github.com/valinet/ExplorerPatcher/issues/2873#issuecomment-1956366298

its false positive, its in the nature of the programm

Jfc ppl these days....
