### ISSUE TITLE
Can't uninstall ExplorerPatcher

### ISSUE THREAD

**Issue by HoofedEar** [valinet/ExplorerPatcher#3004]
![screenshot01](https://github.com/valinet/ExplorerPatcher/assets/1261392/34a4c835-ea2e-44a7-96b2-82a047de3319)

I keep receiving this error when I try to uninstall ExplorerPatcher. I have followed each of the steps as described in the README. Each of them results in this error, and ExplorerPatcher still starting and running. 

I would like to remove this program from my computer, how can I proceed? 

Thank you.

**Comment by Amrsatrio** [comment]
Please screenshot the contents of your C:\Program Files\ExplorerPatcher folder.

**Comment by HoofedEar** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/1261392/dc1b59c2-de9a-44ca-9468-5f033d94ab7d)

**Comment by Amrsatrio** [comment]
Please delete all the .prev files, and try to uninstall normally again.
