### ISSUE TITLE
Internet flyout broken

### ISSUE THREAD

**Issue by 0s9df8c0sdfd0** [valinet/ExplorerPatcher#3010]
The internet flyout for the windows 10 one does not show the buttons.
![Screenshot 2024-03-15 114650](https://github.com/valinet/ExplorerPatcher/assets/159628909/dfa86076-877d-4680-9255-a1257076be1f)

**Comment by Amrsatrio** [comment]
I think you have "UseLiteLayout" enabled in HKLM\Software\Microsoft\Windows\Control Center. Or you are running a 22621 build older than 22621.1413.

**Comment by Amrsatrio** [comment]
Closing due to no follow-up response.
