### ISSUE TITLE
BattleEye Launcher Issue (Game Launcher)

### ISSUE THREAD

**Issue by patlinGER** [valinet/ExplorerPatcher#3014]
![BattleEye](https://github.com/valinet/ExplorerPatcher/assets/96003725/c62ba2a2-6031-49c5-bdcf-08fb5447cb89)

**Comment by pyrates999** [comment]
submit this to BattleEye Service.  Not a bug with EP.

**Comment by Amrsatrio** [comment]
Please disable shell extensions. Not a problem on EP's side, nothing we can do. The point if anticheats is to block loading of unknown DLLs otherwise one could put cheats in EP and use it to cheat.
