### ISSUE TITLE
Cant install update

### ISSUE THREAD

**Issue by mm-video** [valinet/ExplorerPatcher#3017]
I can neither install the update nor delete the current version.
In both cases the popup window opens telling me to restart either the service or windows.
Both measures do not work.
What can I do?
![image](https://github.com/valinet/ExplorerPatcher/assets/136805484/e18a3214-5168-4199-9918-d1d10041c321)

**Comment by Amrsatrio** [comment]
Please screenshot me your C:\Program Files\ExplorerPatcher folder contents.

**Comment by mm-video** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/136805484/6060a4ea-948d-4dc7-819b-48be90b49ab2)

**Comment by Amrsatrio** [comment]
Please delete the .prev files and try to uninstall again.

**Comment by mm-video** [comment]
Ok, thanks. I got it de- and reinstalled and also updated...
