### ISSUE TITLE
[24H2] Task Manager context menu option on taskbar does not function

### ISSUE THREAD

**Issue by mibby** [valinet/ExplorerPatcher#3021]
Windows 11 Version 24H2 (OS Build 26080.1)
ExplorerPatch 22621.3296.64.1
Taskbar style: Windows 11

Right clicking the taskbar to open the context menu and choosing ``Task Manager`` does not open the Task Manager process. Task Manager does open if I use ``ctrl + shift + esc`` or search ``Task Manager`` in start.

Exported settings: [ExplorerPatcher_22621.3296.64.1.zip](https://github.com/valinet/ExplorerPatcher/files/14631057/ExplorerPatcher_22621.3296.64.1.zip)

**Comment by pyrates999** [comment]
That is a canary build: https://www.elevenforum.com/t/windows-11-insider-canary-26080-1-and-dev-build-26080-1201-kb5037135-24h2-march-15.23445/

Canary builds are not supported because the code is not final and can change with each new release.

**Comment by pyrates999** [comment]
26058.1 and 26058.1000 are not the same build of windows.

And stuff changes in between canary builds that doesn't guarantee EP will work.

**Comment by Amrsatrio** [comment]
Fixed in 66.5.
