### ISSUE TITLE
Task Bar still transparent

### ISSUE THREAD

**Issue by egglys** [valinet/ExplorerPatcher#3022]
After the last Windows Update 13 March 2024 (Windows 11 Pro) my Taskbar suddenly got transparent. I installed the latest Explorer Patcher but no help, taskbar stays transparent. I even uninstalled explorer Patcher and reinstalled it, no help. Is there a solution for this please? Thank you

**Comment by GimbalDCS** [comment]
+1 , would like the opaque taskbar back please, especially when working with a virtual desktop, I can see the other taskbar behind my OS taskbar when the screen is not active, confusing!
