### ISSUE TITLE
Explorer window size and postion not saved/remembered

### ISSUE THREAD

**Issue by skymaster7** [valinet/ExplorerPatcher#3025]
After installing ExplorerPatcher, my explorer windows no longer remember if I resize or move them. They always appear in the same position and size as when I first installed ExplorerPatcher. 

To reproduce: Before installing ExplorerPatcher, I can move and resize explorer windows and it remembers the next time I open an Explorer window. As soon as I install ExplorerPatcher, it only ever opens in the same exact position and size as when I installed it.

If I uninstall ExplorerPatcher, I can resize the last open explorer window, close it, re-open explore, and it remembers the size and position of what I last used.

**Comment by Amrsatrio** [comment]
Please continue the discussion here: https://github.com/valinet/ExplorerPatcher/issues/2243
