### ISSUE TITLE
The clock not showing

### ISSUE THREAD

**Issue by JotaCartas** [valinet/ExplorerPatcher#3028]
when changing Taskbar style to Windows 10 (in windows 11 SI), the clock disapears

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/discussions/2363

If you are runnind Dev or Canary, we're in the process of making our own implementation of the Windows 10 taskbar. Microsoft has removed the System Tray code from the old taskbar in those builds.
