### ISSUE TITLE
After updating Windows 11 to 22000.318 am getting Unable to Find Symbols

### ISSUE THREAD

**Issue by PGomersall** [valinet/ExplorerPatcher#303]
Looks like the ExplorerPatcher\Taskbar is broken now in 22000.318
Only updated 1 system though.

**Comment by valinet** [comment]
Works fine for me over here, the symbols were redownloaded and everything's back to working (build 22000.318 as well). Idk, maybe Microsoft takes a while until they publish the files. This has been a thing last month as well, they usually publish the symbols around the time the build is pushed out to people, give or take a few hours. If it takes a few days, then it becomes worrisome.

The 2 system files for which symbols are needed (`twinui.pcshell.dll` and `StartDocked.dll`) have not even been changed. I have pushed an update to hard code the symbols for this build as well (as was the case with the previous build), so it's even more convenient (22000.318.34.0).

Thanks

**Comment by PGomersall** [comment]
Thanks for the explanation.
