### ISSUE TITLE
Windows 10 start menu not working after a long update

### ISSUE THREAD

**Issue by FlyRetroGamer** [valinet/ExplorerPatcher#3034]
For some reason, after a long update my start menu stopped working, and I couldn't do anything to fix it.

My current edition is Home
Build Info: 22621.ni_release.220506-1250

[console.log](https://github.com/valinet/ExplorerPatcher/files/14670992/console.log)

**Comment by Amrsatrio** [comment]
Please always reinstall ExplorerPatcher after doing feature upgrades.
