### ISSUE TITLE
Taskbar Icon Size & Taskbar Width

### ISSUE THREAD

**Issue by navalega0109** [valinet/ExplorerPatcher#3036]
Hi Team,

Can we use this software to make the taskbar icon size small? Also, Can we increase the width of taskbar by unlocking the taskbar?

Refer the url link to more understand the features.

1. Link --> https://www.youtube.com/watch?v=FnU_itLYlVo
2. Link --> https://www.youtube.com/watch?v=fGXKYG0V_vk

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by Amrsatrio** [comment]
1. Yes
2. Yes

Issues are for reporting bugs only, for inquiries we recommend using Discussions or via our Discord server (the invite in the README).
