### ISSUE TITLE
Oversized Taskbar

### ISSUE THREAD

**Issue by SilasNFQ** [valinet/ExplorerPatcher#3037]
Hi I'm not sure if this already is an issue, but for two days now my Taskbar is a little oversized 😅 
I think letting an image talk for the problem will make it obvious what I'm talking about:
![image](https://github.com/valinet/ExplorerPatcher/assets/158474489/1566a1ac-3a11-49fc-a419-2ac275f32964)
![image](https://github.com/valinet/ExplorerPatcher/assets/158474489/84d2e699-ebca-4555-b645-ba5d004f1a4c)

I guess there is not much more to say about it, besides that I already tried fixing it by shortening the Date output but that did nothing. 
Hopefully this is something fixable.

Ty in advance 😄

**Comment by pyrates999** [comment]
Right click on it and select **lock the taskbar**.  Then on the bottom of it, it will turn into an arrow and you can resize it.

**Comment by SilasNFQ** [comment]
Thank you @pyrates999 that was too obvious 😅
