### ISSUE TITLE
Alternative way to install updates of ExplorerPatcher without admin rights?

### ISSUE THREAD

**Issue by Chris-de-ze** [valinet/ExplorerPatcher#3038]
ExplorerPatcher is the best complementary tool to use on Win11 PC. It makes life and work simple and easy.
 Would it be possible to install updates (new versions) of ExplorerPatcher to a Win11 PC with no admin rights but which already has a previous version of ExplorerPatcher installed ?

**Comment by Amrsatrio** [comment]
No. It is a requirement for EP to have certain files in C:\Windows.

**Comment by Chris-de-ze** [comment]
What is the main reason that you strongly do not recommend using EP on managed work PCs even with admin rights?.
Does the EP software create any problems?
As far as I know, the functionality that EP brings out is already inherent but hidden in Windows 11 software.
So where the harm lies?

**Comment by Amrsatrio** [comment]
It is no longer the case in 24H2, that is why.

**Comment by Chris-de-ze** [comment]
I am running 23H2. Sorry, but why It is no longer the case in 24H2? Did MS bring back the hidden functionality and there is no need for EP?

**Comment by Amrsatrio** [comment]
Microsoft wants everyone on 24H2 to stop using the 10 taskbar that happens to remain in explorer.exe. Decompiling the taskbar to make a faithful reimplementation is the only way to keep using it. However this means it has a high chance of breaking between updates and I do not want to be responsible for losses due to that. That is why I said that business users should not rely on EP anymore at least on 24H2.

**Comment by Chris-de-ze** [comment]
Thank you for the thorough explanation. That means we return back to stone age with the new 24H2 upgrade!

**Comment by Amrsatrio** [comment]
And for EP I believe deleting ep_dwm.exe...........

**Comment by Chris-de-ze** [comment]
I have paused updates of Win11. Do you happen to know if we can rely on EP on 24H2? 
Or is Microsoft still blocking installation of EP and upgrades on 24H2?

**Comment by pyrates999** [comment]
You can stay on 23h2.  You don't have to upgrade to 24h2 when it comes out.

**Comment by Chris-de-ze** [comment]
Just two questions please:

1) On an office PC running Windows 11, the latest Win update blocked  ExplorerPatcher. After login, a black screen appears and I have to run three times "C:\Windows\explorer.exe", to enter Windows. ExplorerPatcher is not shown on the list of potential programs to uninstall. How ExplorerPatcher can be completely removed?  

2) On a personal PC  running Windows 11, will ExplorerPatcher work with 24h2? Can I update from 23H2 to 24H2 and still have the ExplorerPatcher functionality?

**Comment by pyrates999** [comment]
You need to add the exclusions to CHECKPOINT End Point Security Antivirus.  If you can't do that, then you should not be installing EP on this work computer.
