### ISSUE TITLE
right clicking on the start menu not working

### ISSUE THREAD

**Issue by zoghal** [valinet/ExplorerPatcher#304]
hi dear,
I saw this problem in all the updates. I thought to myself that it would be better to inform you about this problem.

when i opens start menu and right clicking on the any shortcut programs ,no context menu showing:

https://user-images.githubusercontent.com/174688/141051087-595a9a30-4b63-4381-a7e0-a886f75a3ec8.mp4

**Comment by valinet** [comment]
Yeah, it’s a known problem with the Windows 10 Start menu in Windows 11, it’s not caused by EP, it happens no matter how you enable the Windows 10 Start menu. Btw, how did you enable it?

Also, another slight issue is that the menu takes a while until it closes.

Thanks
