### ISSUE TITLE
Issue with keyboard input for pinned icons in the Start Menu on Windows 11!

### ISSUE THREAD

**Issue by developer6253** [valinet/ExplorerPatcher#3041]
I am experiencing a keyboard input error when attempting to select items using the keyboard for pinned icons in the Start Menu on Windows 11. 

Additionally, keyboard events are not functioning when clicking the 'All Apps' button, rendering it impossible to search and select items . 

My Windows version is 11 (23H2) Build 22631.3296. 

I would really appreciate it if you could resolve this issue.

Thank you very much for developing such useful and great software. 

: )

**Comment by Amrsatrio** [comment]
Which start menu? The stock Windows 11 one or the restored Windows 10 one?

**Comment by developer6253** [comment]
At the time of reporting, the issue occurred within the Windows 11 menu.

However, after rebooting the system yesterday, it seems to be functioning normally again.

It appears that this may not be a bug. 

My apologies for any confusion.
