### ISSUE TITLE
March Update Taskbar & Sys Tray menus blank

### ISSUE THREAD

**Issue by dsi1** [valinet/ExplorerPatcher#3044]
After performing the update on my Win-11 PC I noticed that the Date/Time space allocation was blank but the DAte/Time exists as a mouse rollover.  cannot get it to restore.  I right-clicked on the System Tray and the pop-up menu is blank but the submenu > is there and there is a checkmark at the beginning of a line entry but no visible writing as a link button.  The same right-click blank menu occurs when I do so on the taskbar.   I believe the invisible links are active in the blank menus but have no idea what the links say.   I could not find an ExplorerPatcher program exe file to open up the program other than using the search function as it does not show up in the Start Menu program list.

**Comment by pyrates999** [comment]
to run the explorer patcher properties application, run this from the run menu:
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by dsi1** [comment]
Thank you, working now,
Best,
dsi1

**Comment by pyrates999** [comment]
Please close this then.
