### ISSUE TITLE
Display mode will not change to Full Start Screen

### ISSUE THREAD

**Issue by CohenEllsworth** [valinet/ExplorerPatcher#3046]
When i try to change it to full start screen, it has me put in an administrator code since i made a new profile and the old one is the administrator. I put in the code and then it sends me back but nothing changed. It doesn't let me change App Display either.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by CohenEllsworth** [comment]
Wait. never mind i got it. I just had to change my new profile to administrator. Sorry for any inconvenience.

**Comment by pyrates999** [comment]
Please close this.

**Comment by Amrsatrio** [comment]
Feeling like Admin shouldn't be needed to change full screen start options. Will consider this in the future.
