### ISSUE TITLE
No Access to Properties Menu with Windows 11 Taskbar

### ISSUE THREAD

**Issue by Ocraftyone** [valinet/ExplorerPatcher#305]
If you enable the program, disable "Enable  Windows 10 taskbar" in the properties windows, there is no way to access the properties window. Can the properties window be made a separate executable that has a shortcut? I would assume that the only way to access the config again would be through a re installation.

**Comment by Ocraftyone** [comment]
I see that you can manually set the value with a registry tweak but that would be really inconvenient just to change a setting

**Comment by valinet** [comment]
Run the following command: `rundll32 C:\Windows\dxgi.dll,ZZGUI`

Added a mention about it in the README as well, it was kind of hidden previously, there were only a couple of threads in Discussions mentioning it from time to time.

Thanks
