### ISSUE TITLE
Fix Request for Alt+Tab (Windows Switcher) with Three-Finger Gesture in Win10

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#3057]
When we change the ALT+TAB (Windows Switcher) to any other like NT or Simple, it works fine with the ALT+TAB combination. But it shows the Win10 Switcher while using it with Touchpad Gesture (3-Finger). This functionality works fine in Windows 11 with a perfect sync, but not with Win10. I think that it doesn't injected completely in Win10 system. Umm...Can it be fixed or not @Amrsatrio ?

**With ALT+TAB**
![image](https://github.com/valinet/ExplorerPatcher/assets/93650504/8f3dae19-9090-4cdf-b04f-7cede2b26adc)

**WITH TOUCHPAD GESTURE:**
![image](https://github.com/valinet/ExplorerPatcher/assets/93650504/d734633c-e9fb-4c71-8f8d-7553ca3fa233)

**Comment by Amrsatrio** [comment]
Don't know. And I have no plans to figure this out.
