### ISSUE TITLE
多一个英语（美国）键盘

### ISSUE THREAD

**Issue by changzhongxinxin** [valinet/ExplorerPatcher#3059]
安装后输入法会多一个英语键盘
![Clip_2024-03-27_22-57-37](https://github.com/valinet/ExplorerPatcher/assets/68383493/c6180520-7502-424d-8498-f6866699e348)

即使安装英语语言再删除也不能去掉那个英语键盘

**Comment by pyrates999** [comment]
Being unable to install the english keyboard is something Microsoft would need to work on.

This request is not for EP to handle.

**Comment by changzhongxinxin** [comment]
不是不能安装英文键盘，是安装EP之后多了个英文键盘始终无法删除，删除EP重启系统英文键盘就消失了


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月28日(周四) 凌晨1:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [valinet/ExplorerPatcher] 多一个英语（美国）键盘 (Issue #3059)




 
Being unable to install the english keyboard is something Microsoft would need to work on.
 
This request is not for EP to handle.
 
&mdash;

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1347

**Comment by changzhongxinxin** [comment]
窗口切换器原因
