### ISSUE TITLE
Taskbar empty after waking screen

### ISSUE THREAD

**Issue by krryan** [valinet/ExplorerPatcher#3065]
With the taskbar set to Windows 10 mode, whenever my screen turns off and I wake it up again, all of my taskbar buttons are gone, as if I didn’t have any programs open. The programs are still open, and if I Alt+Tab to switch between them, each returns to the taskbar when it becomes the foreground program, but this is an irritating process—I’ve mostly just gone for restarting Explorer, instead, it’s faster.

This problem dates back to KB5035853 (W11 22631.3296): when I got that update, I experienced #2975, and since I saw it had been fixed in an upcoming release, I turned on “Receive pre-release versions, if available (not recommended)” in ExplorerPatcher. That solved #2975 for me, but caused this problem. (Also caused the Weather app to not work—I just have a “People” button where the weather is supposed to be, which goes away if I turn off the Weather app.) I’ve since turned pre-release versions off (since the fix for #2975 is now in the stable version), and I’ve also tried reinstalling ExplorerPatcher, but neither works: taskbar buttons keep disappearing.

Turning my Taskbar to Windows 11 mode eliminates the problem, but I don’t really want to do that since the Win10 Taskbar is most of the reason for using ExplorerPatcher. (Also, the Weather app apparently disappears completely as an option in that mode? So no telling if it “would” fix the other problem, though that’s much more minor for me.)

Versions and settings:
* Windows:
  | Edition | Windows 11 Pro |
  |:--------|:-------------------|
  | Version | 22H2
  | Installed on | 12/‎5/‎2022
  | OS build | 22621.3296
  | Experience | Windows Feature Experience Pack 1000.22687.1000.0
  * Windows Power Plan is set to “Balanced” with “Turn off the display: 5 minutes” and “Put the computer to sleep: Never” so we are only talking about the display turning off, in theory.
* ExplorerPatcher ~22621.3296.64.1~ 22621.3527.65.1
  * Taskbar
    * Taskbar style * : Windows 10
      - Primary taskbar location on screen * : Bottom (default)
      - Secondary taskbar(s) location on screen : Bottom (default)
      - Search : Hidden
      - ✘ Show Task view button
      - ✘ Automatically hide the taskbar
      - Start button style * : Windows 10 (default)
      - Primary taskbar alignment : At screen edge (default)
      - Secondary taskbar alignment : At screen edge (default)
      - Combine taskbar icons on primary taskbar : Never combine (default)
      - Combine taskbar icons on secondary taskbar : Never combine (default)
      - Taskbar icon size : Large (default)
  * File Explorer
    * ✘ Register as a shell extension

More settings available on request, though I think they’re pretty much all just set to the default.

I do not have any other programs installed that affect Explorer or the taskbar. I originally had one “7+ Taskbar Tweaker” installed (it’s the reason I want the Win10 taskbar in the first place), but I uninstalled it and the problem persists.

I was recommended to run the ExplorerPatcher console to get more diagnostic information.

When I first opened the console, I got:
```
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.3296.64.1.15361a1b13c6f570"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.3296.64.1.15361a1b13c6f570" (valid).
[Updates] Local version obtained from hash is 22622.3296.64.1.
[Updates] No updates are available.
```

Then when I woke the computer and the taskbar items were missing, I had

```
[Positioning] Removed settings for monitor: 000000003A6307BD
[Positioning] Removed settings for monitor: 0000000027A60A3B
[Positioning] Added settings for monitor 000000003ACE0855 : 0
[Positioning] Removed settings for monitor: 000000003ACE0855
[Positioning] Added settings for monitor 00000000036D08DD : 0
[Positioning] Added settings for monitor 000000003ACF0855 : 0
[EnsureXAML] 31 ms.
```

(I have two monitors, if it matters.)

**Comment by Amrsatrio** [comment]
Do you have TranslucentTB or similar programs installed?

**Comment by krryan** [comment]
I have a program called “7+ Taskbar Tweaker” but I disabled it to test this bug. It worked perfectly fine before (and in fact they are the ones who pointed me here, because it doesn’t work with Win11 and this was the solution to that).

**Comment by pyrates999** [comment]
So did you uninstall 7+ taskbar tweaker or find the setting in it that caused this?

**Comment by krryan** [comment]
@pyrates999 I don’t believe 7+ Taskbar Tweaker _did_ cause this: turning it off did not fix the problem. I haven’t fully uninstalled it to try that, which I might tomorrow, but I’m doubtful that it will help.

**Comment by pyrates999** [comment]
Let's see what happens when you uninstall 7+ Taskbar Tweaker.

**Comment by pyrates999** [comment]
When this happens, open up task manager and kill explorer.exe and then run task manager again and run explorer.exe.

Does that fix it?

In EP properties application, in Fil Explorer, do you have register as shell extension enabled?  If so, disable it and do the above again.

**Comment by krryan** [comment]
I will do that next time it happens (it did not as I just woke up the screen), but for the record, using “Restart File Explorer (*)” within ExplorerPatcher does fix things, which I presume runs basically the same process.

“✘ Register as a shell extension” per Properties, under File Explorer.

**Comment by pyrates999** [comment]
You are correct.  I do the above sometimes when things stop working for me with explorer and clicking restart explorer in EP properties application doesn't fix it.

**Comment by krryan** [comment]
OK, to be clear: killing and restarting explorer (whether through EP or Task Manager) fixes the issue—until the next time the screen turns off. Then I get it again. It happens pretty consistently in Win10 mode (the earlier statement that it hadn’t happened was because I’d put it into Win11 mode to avoid the bug).

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  Copy and paste the results here.

**Comment by krryan** [comment]
When I first opened the console, I got:
```
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.3296.64.1.15361a1b13c6f570"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.3296.64.1.15361a1b13c6f570" (valid).
[Updates] Local version obtained from hash is 22622.3296.64.1.
[Updates] No updates are available.
```

Then when I woke the computer and the taskbar items were missing, I had

```
[Positioning] Removed settings for monitor: 000000003A6307BD
[Positioning] Removed settings for monitor: 0000000027A60A3B
[Positioning] Added settings for monitor 000000003ACE0855 : 0
[Positioning] Removed settings for monitor: 000000003ACE0855
[Positioning] Added settings for monitor 00000000036D08DD : 0
[Positioning] Added settings for monitor 000000003ACF0855 : 0
[EnsureXAML] 31 ms.
```

(I have two monitors, if it matters.)

**Comment by pyrates999** [comment]
Lets see what one of the developers have to say.

**Comment by krryan** [comment]
Well, to try to make things easier, I’ve consolidated all of the information in the opening post.

**Comment by krryan** [comment]
Updated to 22621.3296.64.1 this morning and still experiencing this problem.

**Comment by krryan** [comment]
Updated to 22621.3527.65.1, still experiencing the same problem.

**Comment by pyrates999** [comment]
can you try updating to the latest pre-release? https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by krryan** [comment]
@pyrates999 I got a full release today, which didn’t help, and then I tried the pre-release, as you suggest—and it may have done the trick? I’ve only woken up my computer once since getting it, but it had all the taskbar buttons it was supposed to have, and that’s the first time I’ve seen that in Win10 mode since this all started, so that’s a good sign. I’ll come back and close tomorrow or so, assuming it continues to behave.

**Comment by krryan** [comment]
@pyrates999 Spoke too soon; just woke up my computer again and the taskbar buttons are missing again. Not sure what was different between the first time and this time.

**Comment by pyrates999** [comment]
can you post a screen shot of what the taskbar normally looks like and another screen shot of when this happens after you wake the computer from sleep?

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/issues/3781
