### ISSUE TITLE
[22635.3420] When Windows 10 Start menu style is selected, the Windows 11 Start menu appears instead.

### ISSUE THREAD

**Issue by Amrsatrio** [valinet/ExplorerPatcher#3066]
**Windows version:** 22635.3420 (Beta channel)
**EP version:** 64.2

## Steps to reproduce
1. Install all updates up to 22635.3420.
2. Install [ExplorerPatcher version 64.2](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.2_699ef06).
3. Open ExplorerPatcher's Properties window.
4. Go to Start menu section.
5. Set Start menu style to Windows 10.
6. Restart Explorer.
7. Open the start menu.
8. Observe that the 11 menu is shown instead of the 10 one.

## Additional information
Upon investigating further, I've seen that 3420's StartMenuExperienceHost.exe no longer has the Windows PPI edition check that uses [GetProductInfo](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getproductinfo) which is [intercepted by EP](https://github.com/valinet/ExplorerPatcher/blob/7ef39c285a86bac75118be82e533b554ffe69686/ep_startmenu/ep_sm_main.c#L24) to enable the old menu. More intricate patches are needed to restore the Windows 10 start menu on this build onwards.

## Video evidence
https://cdn.discordapp.com/attachments/1211286128125153290/1223359447322202274/20240329-1951-50.8268292.mp4?ex=66199145&is=66071c45&hm=a611524b2d039f8bd2dfbf9c9a74dc2758ef23855c7f0c0c750bad6e1da99dbf&

**Comment by pyrates999** [comment]
that's an insider preview: https://blogs.windows.com/windows-insider/2024/03/29/announcing-windows-11-insider-preview-build-22635-3420-beta-channel/

**Comment by Amrsatrio** [comment]
Yep, I am posting this myself so that everyone including me is aware on this. I've clearly added (Beta channel) to indicate that it's a Beta build.

Critical issues in 22621-bases builts lime those in Beta and RP cannot be taken lightly as for this case it only takes a week or two for the issue to appear on broader channels like Release Preview or even Release, which would impact our reputation.

**Comment by pyrates999** [comment]
Oh I didn't even notice it was you posting it lol

**Comment by chuck00000** [comment]
Same issue in 26090

**Comment by SherlockChiang** [comment]
Same for me, surprised to find win11 theme startup after updating my OS

**Comment by PandaFiredoge** [comment]
我也是，开始菜单无法修改为Win10

Me too, the start menu cannot be modified to Win10

**Comment by 171h** [comment]
+1

**Comment by pyrates999** [comment]
Might be related to this: https://github.com/valinet/ExplorerPatcher/issues/3053

**Comment by Amrsatrio** [comment]
@pyrates999 No, this unrelated to that.

**Comment by Amrsatrio** [comment]
Made a new prerelease that should allow the 10 menu to show up again, but pin to start is now broken yet again:

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.2_5e25663

**Comment by pseudo555** [comment]
64.2 seems to solve the issue, but there is also another regression when using win10 taskbar. The button that handle sound is missing. I get the one from network, the locale for keyboad, a cog button then the hour.
This wasn't the case before updating windows.

**Comment by Amrsatrio** [comment]
Hi @pseudo555, please file a separate issue. I've never encountered this issue even in latest Canary/24H2 builds.

**Comment by PandaFiredoge** [comment]
> Made a new prerelease that should allow the 10 menu to show up again, but pin to start is now broken yet again:制作了一个新的预发布版本，应该允许 10 菜单再次显示，但启动的固定现在再次被破坏：
> 
> https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.2_5e25663

另一个问题：浅色模式下动态磁贴不显示内容

Another problem: live tiles do not display content in light mode

**Comment by pseudo555** [comment]
> Hi @pseudo555, please file a separate issue complete with the details. I've never encountered this issue even in latest Canary/24H2 builds.

ne need anymore, the 64.3 you published make explorerpatcher working fine on my windows (fr 11 23h2 - 22631.3374)

**Comment by Amrsatrio** [comment]
Fix is live in the newly built latest release of EP, version 65.2. Further issues like this will be closed immediately without any explanations.
