### ISSUE TITLE
How to add tile to windows 10 style start menu? Adding to start adds to windows 11's default one, not the classic one

### ISSUE THREAD

**Issue by trcrsired** [valinet/ExplorerPatcher#3068]

**Comment by pyrates999** [comment]
Live tiles have always been unstable in 22621 onwards. We have no plans of fixing it as Microsoft has removed the Windows 10 start menu in 26xxx builds.

Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1621

Please close this.

**Comment by Amrsatrio** [comment]
And don't forget to restart Explorer after changing the start menu style.
