### ISSUE TITLE
ExplorerPatcher Makes Windows Taskbar Transparent

### ISSUE THREAD

**Issue by MaroisConsulting** [valinet/ExplorerPatcher#3080]
As described here:
https://answers.microsoft.com/en-us/windows/forum/all/after-an-update-my-taskbar-is-suddenly-100/3a0a1f8b-4373-490b-ba22-72116cd4e46f

When I uninstalled ExplorerPatcher my taskbar was no longer transparent.

**Comment by Amrsatrio** [comment]
Update your EP.
