### ISSUE TITLE
Uninstalling Explorer Patcher after update removed my W11 taskbar.

### ISSUE THREAD

**Issue by jbezugs** [valinet/ExplorerPatcher#3083]
Hey there,

Got a new to me W11 computer today, and decided to install explorer patcher. Everything was working on the initial install until a preview update was pushed to my computer (KB5035942).

After that update, I noticed the task bar starting to become very delayed in loading in, and the search and start menu were no longer working.   With those issues, I decided I should un-install explorer patcher.

When uninstalling, whether it be via the explorer patcher properties menu, or via the CMD, upon completion of the un-installation, my original task bar no longer appears.

This has persisted with restarts, removing the ExplorerPatcher registry entry, etc etc.

I have also removed the preview update from my PC, but to no avail.  Would be happy to pull logs or do some more investigation if I can be pointed in the right direction.  

My current OS build is 22631.3296, Windows Feature Experience Pack 1000.22688.1000.0

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by jbezugs** [comment]
As an additional note - I have re-installed ExplorerPatcher and noticed that if I change my Start Menu style to Windows 10, I am served with a start menu again.  If I make the Start Menu style W11, it does not appear.

Switching between taskbar styles (W11 or W10) does not matter. I am always left with the W10 task bar.  This makes me think that my W11 taskbar and said functionality has been nuked somehow.

**Comment by onepointfive-REAL** [comment]
### Once you login try doing:
CTRL + ALT + DEL
Click: Task manager
Then press: Run new task
Type in: cmd.exe
Once you are served at a command prompt then do:
taskkill /f /im explorer.exe
explorer.exe

_**I hope this worked cause this happend to my brother too**_

**Comment by onepointfive-REAL** [comment]
### _**Or just deal with it**_
Sorry i use one every day but yeah

**Comment by jbezugs** [comment]
Update: Jumping back to a system restore point prior to installing ExplorerPatcher has brought the original task bar back, however the start menu is still missing and now throws a critical error upon hitting the windows button (which can be cleared by restarting explorer.exe, but the issue persists. Quick access menu and notification drawer are now broken as well.

Group policies mean no PowerShell fixes possible, so we will ride this out and see...

**Comment by jbezugs** [comment]
After much troubleshooting, solved! 

Go to C:\Windows\System32\AppLocker and delete all files in there.

AppLocker was probably enforcing some rules that included blocking my taskbar and access to the windows store, really weird

from there I could run the following script in an elevated powershell 

taskkill /F /IM explorer.exe ; taskkill /F /IM SearchApp.exe ; taskkill /F /IM SearchUI.exe; taskkill /F /IM ShellExperienceHost.exe; taskkill /F /IM StartMenuExperiencehost.exe ; Start-Sleep 2 ; cd $Env:localappdata\Packages\Microsoft.Windows.ShellExperienceHost_cw5n1h2txyewy ; Remove-Item -Recurse -Force .\TempState\ ; cd $Env:localappdata\Packages\Microsoft.Windows.StartMenuExperiencehost_cw5n1h2txyewy ; Remove-Item -Recurse -Force .\TempState\ ; Add-AppxPackage -register "C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\AppxManifest.xml" -DisableDevelopmentMode ; Add-AppxPackage -register "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\AppxManifest.xml" -DisableDevelopmentMode ; Start-Process "explorer.exe"

**Comment by pahisada** [comment]
Jbezugs, just wanted to say thanks (a million ) for this solution a year later!  After hours of trying everything out there, deleting applocker files immediately returned explorer to business as usual.  I was about to take the nuclear option with W11 until I tried this.  There are still many people out there with this issue - will try to share this.

**Comment by LarsErikOsterud** [comment]
Tried all above. But still can't get backl the Windows 11 taskbar.
And updates on my system fails at 100%. Even in-place upgrade.
Help!
