### ISSUE TITLE
ms-settings:display and ms-settings:personalization error

### ISSUE THREAD

**Issue by onepointfive-REAL** [valinet/ExplorerPatcher#3084]
So i updated my explorer patcher version and i had no idea this was an issue until apps tried to access it like right clicking the background and clicking on display settings.
I also did Win + R and typed in ms-settings: and nothing poped up
It might be an uwp error but i have no idea if its explorer patcher or something else

**Comment by onepointfive-REAL** [comment]
### **PLEASE RESPOND**
My spelling is crummy right now sorry

**Comment by Amrsatrio** [comment]
Not an EP issue, if you have "Register as shell extension" disabled.
