### ISSUE TITLE
Can't run in latest Dev/Can  build 26100

### ISSUE THREAD

**Issue by chuck00000** [valinet/ExplorerPatcher#3085]
![Screenshot 2024-04-04 105714](https://github.com/valinet/ExplorerPatcher/assets/98159699/53e2bfcd-0f89-4fe2-8f09-0e7ec68f85e4)

**Comment by Amrsatrio** [comment]
https://fxtwitter.com/StartIsBack/status/1775660727719928173

You're not supposed to use ExplorerPatcher on Dev/Canary at the moment.
