### ISSUE TITLE
[22621.3296.64.3][win11] Win10 taskbar background truns to black background,and right-click menu text not display.

### ISSUE THREAD

**Issue by saobee** [valinet/ExplorerPatcher#3092]
black background..
![image](https://github.com/valinet/ExplorerPatcher/assets/4122529/7eb0a1f2-151e-46b9-b729-257daea60acc)

not display text..
![image](https://github.com/valinet/ExplorerPatcher/assets/4122529/ba3a7106-38fe-44c9-aecd-14d627454962)

**Comment by Amrsatrio** [comment]
Please disable Classic theme mitigation in EP Properties > Advanced.

**Comment by saobee** [comment]
Thank you for the solution, it works fine.
