### ISSUE TITLE
[WIKI] Misspell found on Windows 11 taskbar style section

### ISSUE THREAD

**Issue by NemusCraft** [valinet/ExplorerPatcher#3094]
![image](https://github.com/valinet/ExplorerPatcher/assets/95968788/6157136f-a3ef-46d8-8607-64060846beab)
As you can see, the blue highlighted text is the misspelled text on wiki

https://github.com/valinet/ExplorerPatcher/wiki/All-features#windows-11

**Comment by Amrsatrio** [comment]
Fixed. Thank you for spotting the oversight.
