### ISSUE TITLE
Today i have an update geforce drivers and crashed EP

### ISSUE THREAD

**Issue by gorillale** [valinet/ExplorerPatcher#3095]
After update the screen driver on gefoce experience the EP will bring up black screen.
After more times to shut of power from windows, i can login again.
the only the solution is to deinstall ep for ever!

after reinstall ep, the same crash is done. 
no windows update, only gforce driver 552.12. :(

have other same effect?

regards

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by gorillale** [comment]
Win11pro, 22621.ni_release.220506-1250
I have removed all win updates after 04.2024, 
Graphic Driver uninstalled with DDU and 552.12 reinstalled
EP new installed, now works without black screen before or after login.
I think win has installed pre updates.
regards

**Comment by pyrates999** [comment]
Yes, looks like this was a windows issue, not an EP issue.  Please close this.
