### ISSUE TITLE
Can't run EP setup

### ISSUE THREAD

**Issue by ExaFlop1** [valinet/ExplorerPatcher#3096]
On Win 11 26100.1 EP setup crashes Windows Explorer. There is a message after restarting Windows:
https://i.postimg.cc/L5tLZc0f/image-png-4894f46a9afc826d9f52f80b8561f1d7.png

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.

**Comment by Amrsatrio** [comment]
Get the latest prerelease or set taskbar style to Windows 11. Microsoft does not want us to use the old taskbar on 24H2 anymore.
