### ISSUE TITLE
[Bug] Start menu not opening

### ISSUE THREAD

**Issue by BraINstinct0** [valinet/ExplorerPatcher#31]
(Might be worth as a template)

Windows Version: Windows 11 22000.194
EPatcher Version: 22000.194.0.22
StartIsBack applied: False

Summarized Issue: Start Menu not opening on click
Details: After upgrading to 0.22 for the (awesome) GUI test, all other features seem to work; but even after restarts&waits, the Start Menu doesn't show(work).

**Comment by valinet** [comment]
Yeah, I know, it drives me nuts. I am investigating it now. Use the older DLL. Something got fucked up, I don't know what.

**Comment by BraINstinct0** [comment]
No(literally yes but I'm okay with it) problem, all changes can cause bugs.
