### ISSUE TITLE
Skype not working

### ISSUE THREAD

**Issue by Qisatra** [valinet/ExplorerPatcher#310]
Hi. Builds  33.7 and 34.1 skype window not showing after launch. I try compatibility options and launch as administrator but nothing help.  In task manager he seen like active process but impossible do anything. In build 33.2 he  works. Im tested this on 3 PCs and all is same. Please check it and fix if possible. Thanks

**Comment by valinet** [comment]
Please stop using EP as shell extension, it's not ready for everyday use. Track and post your problems in this thread: https://github.com/valinet/ExplorerPatcher/issues/259. Skype works fine when you only drop `dxgi.dll` in `C:\Windows`.

Thanks
