### ISSUE TITLE
WIN 10 start button is not Win 11 style

### ISSUE THREAD

**Issue by yahyagirayesen123** [valinet/ExplorerPatcher#3106]
Hello, I wanted this application to have the taskbar on Win 11, the start button does not work on Win 11, can you help me?

**Comment by pyrates999** [comment]
Update to the latest pre-release of EP.

**Comment by djjester611** [comment]
still doeesn't work

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Closing due to lack of details and no response.
