### ISSUE TITLE
打开开始菜单bug

### ISSUE THREAD

**Issue by yu31343** [valinet/ExplorerPatcher#3109]
win10开始菜单：资源管理器刚启动时，比如刚开机时，即使设置了开始菜单居中，如果是第一次打开开始菜单，它仍然会显示在靠左的位置，非常短的时间后才会自动回到居中位置。这个问题不影响使用，但对强迫症来说确实不太美观

**Comment by pyrates999** [comment]
That has been declined to be fixed: https://github.com/valinet/ExplorerPatcher/issues/2815
