### ISSUE TITLE
Can't unpin from start

### ISSUE THREAD

**Issue by portex7000** [valinet/ExplorerPatcher#3110]
I can't unpin anything from start. I had this issue once, but it was fixed. However, now i can't unpin again

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3066

Please close this.

**Comment by portex7000** [comment]
I HAVE ISSUE CANNOT "UNPIN FROM START". HOW is windows 11 start menu appears instead of windows 10 the same thing???!

**Comment by pyrates999** [comment]
Don't yell.  And check the issue this is a duplicate of for the answer.
