### ISSUE TITLE
[Feature] win11 explorer NavBar(Address Bar)/CommandBar (Xaml) hide option

### ISSUE THREAD

**Issue by Undisputed00x** [valinet/ExplorerPatcher#3111]
Hi there, explorer tabs is the best and the only useful feature on win11 explorer but i am used to a minimalistic look of explorer which  can be accomplished on win7/10 explorer but not on win11 tabbed explorer because Navigation Bar (Address Bar) and the Command Bar are implemented in WinUI 3/Xaml.

**Below my minimalistic look of win7 explorer by hiding NavBar using EP and CommandBar with a tweak on theme files:**
<details><summary>Details</summary>
<p>

![320283534-8bd9b115-35c2-400e-8d75-7b45f3e36b17](https://github.com/valinet/ExplorerPatcher/assets/80290008/1caa0a57-8aa6-4723-9388-d7ea407d3061)

</p>
</details> 

Could ExplorerPatcher implement an option to hide the new NavBar (which EP already does on win7/10 explorer) but also the new CommandBar

**Below my try using [UWPSpy ](https://github.com/m417z/UWPSpy)to demonstrate my feature request:**
<details><summary>Details</summary>
<p>

![320234400-04c7b4f2-3acc-4af5-b02a-73f542a50d29](https://github.com/valinet/ExplorerPatcher/assets/80290008/d49d9d4a-b555-4ebd-8103-598f41d1304a)
![320234405-35f38d7e-c2a5-4d49-9ce3-f74682063ddd](https://github.com/valinet/ExplorerPatcher/assets/80290008/74a7eac6-98f7-4465-9333-95f9ff2dbc26)

</p>
</details>

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
