### ISSUE TITLE
What the heck is this toolbar in file explorer

### ISSUE THREAD

**Issue by Steperman5692** [valinet/ExplorerPatcher#3113]
There is a weird toolbar that appears randomly sometimes in file explorer; this happen ever since I install explorerpatcher. How do I remove it? 
![Screenshot 2024-04-09 010601](https://github.com/valinet/ExplorerPatcher/assets/132756638/e7faae10-b628-493c-9a48-96260fca019c)

**Comment by pyrates999** [comment]
That's the file menu bar in windows explorer.  It's always had it.

**Comment by Steperman5692** [comment]
I know but how do I remove it or at least disable it.

**Comment by pyrates999** [comment]
https://www.elevenforum.com/t/add-or-remove-menu-bar-in-file-explorer-in-windows-11.7643/

**Comment by Anixx** [comment]
> I know but how do I remove it or at least disable it.

There is a bug in Win11 22h2 and 23h2: the menu bar appears when it is not needed and disappeears when it is needed. It appears after you change the visual style,for instance.

I want it to be visible always but it is not visible until a visual style is changed.

See here: https://github.com/valinet/ExplorerPatcher/issues/2676 and here: https://github.com/valinet/ExplorerPatcher/discussions/2994

**Comment by pyrates999** [comment]
Should this be closed then as a duplicate?

**Comment by Anixx** [comment]
I have checked it, and my conclusion:

1. This does not depend on ExplorerPatcher running or not, as this post suggests
2. It does not depend on the Win7 Command Bar being activated as the linked post suggests.

Without any EP and with default Win11 Command bar the menubar appears on any Window Metrics change or refresh, for instance, with simple deskn.cpl, the legacy color scheme CP applet.

**Comment by Amrsatrio** [comment]
Make sure you don't have `HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Toolbar\ShowDiscussionButton`. Delete it if it exists.

Sources:
- https://superuser.com/questions/642861/menu-bar-of-windows-explorer-in-windows7-is-gone
- https://www.reddit.com/r/Windows11/comments/vlxlnz/that_menu_bar_showed_up_after_the_last_update/
