### ISSUE TITLE
ExplorerPatcher fails to load on a restart or Windows Update

### ISSUE THREAD

**Issue by lovetolearncode** [valinet/ExplorerPatcher#3128]
Not sure why this is happening, but after a Windows Update, and a restart ExplorerPatcher failed to load. However, if I right-click and select Properties, ExplorerPatcher's properties comes up. So it is kind of loaded???

Also, there is no way to add a new toolbar.

It is like  ExplorerPatcher is in a quasi place.
Any suggestion please?
![Screenshot 2024-04-12 070645](https://github.com/valinet/ExplorerPatcher/assets/63200493/0f159c7b-a896-4c41-98bc-daaefc6d0adc)

**Comment by pyrates999** [comment]
Uninstall EP and reinstall it.

Then please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by lovetolearncode** [comment]
Hello and thanks for the response!

Here is what I have: 



 

I un-installed it and then re-booted.

I then reinstalled it and the Quick Launch still does not show up. Also, there is no way to select Quick Launch as the option to load it does not appear when I open up “Properties”

 



 

 

This worked fine until the latest Windows 11 .NET update.

 

I hope this helps!

I love the Quick Launch and hope you can figure this out for me.

Cheers!

Russ 😊

 

Russell J. Torlage
President

SOTA Instruments Inc.

***@***.***

Tel: 1-250-770-2022

**Comment by pyrates999** [comment]
In the EP properties application, remember the settings you changed in it.  Then go to **About** and click on **Restore default settings**.  Then reboot.

Then In the EP properties application, reapply your settings.

**Comment by lovetolearncode** [comment]
Thank you so much!!!!

Restore default settings did the trick!

All is well again.

Cheers and thanks for a GREAT program!!!!

Russ 😊
