### ISSUE TITLE
Added shortcuts to start menu don't show up until one sign out / sign in.

### ISSUE THREAD

**Issue by aybe** [valinet/ExplorerPatcher#3129]
**Version:**

ExplorerPatcher:

`22621.3296.64.1`

Windows:
```
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎12/‎10/‎2023
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0
```

**Context:**

Migrated an MSYS installation from old computer to new, by copying it over network (it's portable).

Also ensured to copy the start menu items to the new place:

<img width="538" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/1537591/2b60e000-f912-4e88-babb-9fc774cb803b">

**Problem:**

Copied start menu items will not show unless one signs out and signs in again:

<img width="237" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/1537591/3c001fbd-637c-45c2-8e2b-0b228ce6b74f">

Tried to put them in either of these places:

`C:\ProgramData\Microsoft\Windows\Start Menu\Programs`

`C:\Users\aybe\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`

But to no avail, only signing out/in got the software to pick up the new start menu entries.

After signing out and signing in again, they finally show up:

<img width="237" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/1537591/6173ec56-fe7b-4ce2-b8c1-d54a655a4d9c">

PS: I don't use any other start menu related improvements beside ExplorerPatcher.

**Comment by pyrates999** [comment]
Does this happen with any shortcut that you add to here?

C:\ProgramData\Microsoft\Windows\Start Menu\Programs

C:\Users\aybe\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

**Comment by aybe** [comment]
Good catch,

When I copy a single shortcut to the folder, it immediately shows up in recently added and the menu itself.

But when I copy a folder containing shortcuts, it won't appear unless signing out.

**Comment by pyrates999** [comment]
Then this is not a bug with EP.  Here's what you need to do every time: https://www.makeuseof.com/windows-11-restart-start-menu/

**Comment by aybe** [comment]
Tried restarting both the start menu and Explorer, nothing... it's ok, sign out will do.

And yes you're right, it's not related to EP but to Windows. 🤣

Thanks!
