### ISSUE TITLE
Combine taskbar doesn't combine on latest feature update

### ISSUE THREAD

**Issue by joshdotylmi** [valinet/ExplorerPatcher#313]
Hey I'm testing out this .dll and noticing that when loaded on the latest feature release build of windows 10. Build 22499 prerelease 211105-1550. When i disable the "Enable windows 10 Taskbar" my explorer goes into a crash loop.

One other thing i noticed is that with windows 10 taskbar enabled the "combine taskbar icons" set to "Always combine" doesn't seem to work, and all of my taskbar items have the full text titles in the task bar.

**Comment by valinet** [comment]
EP only enables the use of the old taskbar, it doesn't impose a mode for it. Make sure you do not have conflicting registry entries. 

As for running EP without Windows 10 taskbar, it was indeed a bug, I now fixed it. Thanks.
