### ISSUE TITLE
Adaptive taskbar centering (compensate clock, tray, etc.)

### ISSUE THREAD

**Issue by BiosNod** [valinet/ExplorerPatcher#3130]
It seems ExplorerPatcher can't adaptive center taskbar, for example TaskBarX (https://github.com/ChrisAnd1998/TaskbarX) have option "compensate clock, tray, etc." and can center taskbar at center only in taskbarlist area instead of full screen width.

I know ExplorerPatcher have option "Centered, at screen edge when full" but... It's not adaptive centering.
![изображение](https://github.com/valinet/ExplorerPatcher/assets/16207244/1edc6844-3831-45aa-9fa7-164ba7494ba9)

I suggest adding an option "Center using adaptive alignment". Also when you use adaptive centering (in TaskbarX) you never need to move taskbar list at screen edge when full because adaptive centering is very smooth centering mode
 
Example of non-adaptive centering and how to do adaptive centering (only in the red zone without completely moving to the left edge):
<img width="1280" alt="Adaptive center" src="https://github.com/valinet/ExplorerPatcher/assets/16207244/94894688-e35b-4c29-aee7-c94282a06ce6">

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by BiosNod** [comment]
> Issues are for bugs only, not feature requests. Please post feature requests in discussions.

Okay (https://github.com/valinet/ExplorerPatcher/discussions/3131), can you delete this issue?
