### ISSUE TITLE
search box goes invisible when clicked or when opening start menu

### ISSUE THREAD

**Issue by Rezy774** [valinet/ExplorerPatcher#3133]
just a lil issue to fix not much

**Comment by Rezy774** [comment]
btw my version is win11 23H2 or 22631.3296

**Comment by Rezy774** [comment]
i love explorer patcher and im glad it now has the search box but just please fix those

**Comment by Rezy774** [comment]
btw im using latest explorer patcher ver

**Comment by ItsKade** [comment]
hey why wont they fix this
I saw something about windows deleting the windows 10 taskbar but will I still be able to use the windows 10 taskbar with EP and start menu in the future after this and will this fix be applied if you recreate a windows 10 taskbar also if EP creates their own version of the windows 10 taskbar for ep will we still have all the features that the current ep windows 10 taskbar
