### ISSUE TITLE
File Explorer is crashing

### ISSUE THREAD

**Issue by 1SonNguyen** [valinet/ExplorerPatcher#3135]
[Window Title]
ExplorerPatcher

[Main Instruction]
Unfortunately, File Explorer is crashing :(

[Content]
It seems that File Explorer closed unexpectedly 3 times in less than 10 seconds each time when starting up. This might indicate a problem caused by ExplorerPatcher, which might be unaware of recent changes in Windows, for example when running on a new OS build.
Here are a few recommendations:
• If an updated version is available, you can update ExplorerPatcher and restart File Explorer. [This is the latest version https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe]
• On GitHub, you can view releases, check the current status, discuss or review the latest issues.
• If you suspect this is not caused by ExplorerPatcher, please uninstall any recently installed shell extensions or similar utilities. [explorer.exe is crashing when I am installing ExplorerPatcher]
• If no fix is available for the time being, you can uninstall ExplorerPatcher, and then later reinstall it when a fix is published on GitHub. Rest assured, even if you uninstall, your program configuration will be preserved.

I am sorry for the inconvenience this might cause; I am doing my best to try to keep this program updated and working.

ExplorerPatcher is disabled until the next File Explorer restart, in order to allow you to perform maintenance tasks and take the necessary actions.

[Dismiss]
Windows build 26100.1 ge_release https://blogs.windows.com/windows-insider/2024/04/03/announcing-windows-11-insider-preview-build-26100-canary-and-dev-channels/

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.
