### ISSUE TITLE
All files into TEMP Folder disappear (deleted?)

### ISSUE THREAD

**Issue by wetabax** [valinet/ExplorerPatcher#3136]
Is this possible, that ExporePatcher deletes all files included into TEMP folder under c:\?

I checked that it creates a folder TMP under c:\ - can I remove it?

thanks

walter tabax

**Comment by pyrates999** [comment]
Issues are for bugs only.  Please post in discussions.

**Comment by wetabax** [comment]
Windows PC Manager has done this, nothing to do with ExplorerPatcher. Sorry
