### ISSUE TITLE
Certain functions broken with Win10 taskbar style aligned to the left of the screen.

### ISSUE THREAD

**Issue by TheZOSv** [valinet/ExplorerPatcher#3139]
Hi!

I want to use the Windows 10 taskbar style. However if I set the alignment to the left on the primary screen the following functions are not working properly:
- WIN+A hotkey (WIN+N works)
- Control Center button
- Network: Windows 11 WiFi flyout

If I restart explorer, one of the functions mentioned above works for a single time (draws up the UI) but after closing/dismissing it it's not being displayed anymore until the next explorer restart. All working fine if the taskbar is positioned at the bottom. 

I just checked before sending this ticket:
Setting the taskbar to the left or right won't display the control center or the Windows 11Wifi flyout properly. Setting it to the top is a hit or miss, sometimes it draws the UI at the perfect position, sometimes it's at the edge of the screen.
I believe it has something to do with the UI rendering at a weird position relative to the taskbar.

I'm on version 22621.3296.64.1
Windows 11 23H2 22631.3447

**Comment by pyrates999** [comment]
Can you install a pre-release version of EP and see if it works?

**Comment by TheZOSv** [comment]
I was testing inside a sandbox and it was working as expected, however I've updated it on the live machine and the issue persists.

**Comment by pyrates999** [comment]
Please check the version matches of EP for both.
