### ISSUE TITLE
Can't work on Win11 Beta (22635.3420)

### ISSUE THREAD

**Issue by LittlenineLst** [valinet/ExplorerPatcher#3141]
The explorer patcher(stable version) cant work properly on Windows 11 beta (OS 22635.3420). The problem is the start menu cant be changed to Windows 10 style. 
Best Regards :)
![image](https://github.com/valinet/ExplorerPatcher/assets/78347375/f9304659-45a1-4a9b-a82d-94f7697f24d5)

**Comment by LittlenineLst** [comment]
Winver Screenshot
![image](https://github.com/valinet/ExplorerPatcher/assets/78347375/e1c9ab0d-7ce6-4ee7-a1a8-b1f5a4e10132)

**Comment by LittlenineLst** [comment]
Software Version
![image](https://github.com/valinet/ExplorerPatcher/assets/78347375/b5b9fce9-d73b-4eb8-8a0c-6586ccd2b193)

**Comment by LittlenineLst** [comment]
Thanks😉but still can't

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3066

Please close this.

**Comment by LittlenineLst** [comment]
I will , thanks.
Best Regards ;)
