### ISSUE TITLE
No installation required

### ISSUE THREAD

**Issue by ArthurGanzerli** [valinet/ExplorerPatcher#3144]
Wouldn't there be a way to run the program that needs installation? As a portable execution?
Because on the work PC, I'm not an administrator user, so I can't launch any programs.

![Captura de Tela (11)](https://github.com/valinet/ExplorerPatcher/assets/167311627/c9e2b633-b2f7-4739-968e-41040cff4ed3)

PS.  I used Google Translate as I don't speak English

**Comment by pyrates999** [comment]
No, because it requires admin privileges to install and update.  This has been asked before.
