### ISSUE TITLE
Use Win10 Start menu won't Launch, crashed the File Explorer in Canary 26200, 

### ISSUE THREAD

**Issue by chuck00000** [valinet/ExplorerPatcher#3149]
Select Win10 Start menu, Click taskbar Start button won't Launch Start Menu, crashed the File Explorer in Canary 26200, 

Solution:
Need to switch to Windows 11 Start menu first,   click Start button to launch win11 Start menu; 

then switch back to Win10 Start Menu, it 'll launch Win10 Start menu successfully, not crash the explorer.

Restart PC & Explorer will repeat this issue.

I'm sure it will happen to other builds very soon.

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.

**Comment by chuck00000** [comment]
> > Select Win10 Start menu, Click taskbar Start button won't Launch Start Menu, crashed the File Explorer in Canary 26200,
> > Solution: Need to switch to Windows 11 Start menu first, click Start button to launch win11 Start menu;
> > then switch back to Win10 Start Menu, it 'll launch Win10 Start menu successfully, not crash the explorer.
> > Restart PC & Explorer will repeat this issue.
> > I'm sure it will happen to other builds very soon.
> 
> the windows 10 start menu has been removed on 25xxx/26xxx builds. if you want the old start menu you can use start11 or downgrade to 22000/22621/22631

You can copy StartUI.dll to the folder, It 'll shows the Win10 Start menu option in Explorer Patcher
