### ISSUE TITLE
Explorer.exe crashes every so often

### ISSUE THREAD

**Issue by kamil96500** [valinet/ExplorerPatcher#3150]
After using windows 11 crashed explorer.exe version 22621.3296.64.1 after 4-5 days
The problem generally occurs in windows 11 23H2 I bet because I keep having problems with explorer.exe. I thought your version would fix it, but unfortunately not, the regular version also causes crashes.
When I go to the event preview it is still error 1002.

Is it possible to do something about it?
Let me explain how it starts in my case:

explorer.exe first crashes sound (shuts down), then the taskbar disappears, then the desktop.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by kamil96500** [comment]
Thank you for your reply

Windows 11: 23H2
Compilation: 22631.3447
Unfortunately I do not know how to translate the settings in explorer patcher this I am forced to show in Polish, because I come from Poland.
![Zrzut ekranu (341)](https://github.com/valinet/ExplorerPatcher/assets/167643032/1fc57c50-6afe-42a6-846b-407a59312826)
![Zrzut ekranu (342)](https://github.com/valinet/ExplorerPatcher/assets/167643032/d289a776-fe5b-4435-a9e3-2b7f4685c80d)
![Zrzut ekranu (343)](https://github.com/valinet/ExplorerPatcher/assets/167643032/ca374196-ea3f-4c73-a3de-6a9385fae0a1)
![Zrzut ekranu (344)](https://github.com/valinet/ExplorerPatcher/assets/167643032/9a54ff8d-f70b-4ac5-9046-24ccac7f8557)
![Zrzut ekranu (345)](https://github.com/valinet/ExplorerPatcher/assets/167643032/5862a8e6-ba77-4203-bd4e-4088a4ed1045)
![Zrzut ekranu (346)](https://github.com/valinet/ExplorerPatcher/assets/167643032/bccf8623-1597-4796-9b8f-f15de0a431a7)
![Zrzut ekranu (347)](https://github.com/valinet/ExplorerPatcher/assets/167643032/9a3ffa0c-a89e-43ab-8f69-d042a8acc812)

I would like to add that on Tuesday microsoft will release a system update on what is called patch tuesday, so I think we will wait until Tuesday, maybe microsoft will fix the bug, because the crashes are caused by microsoft.

**Comment by pyrates999** [comment]
Patch Tuesday already happened for April on April 9th.

if you enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

if you disabled tabs in windows file explorer, you must re-enable them, otherwise you will have crashes:

```
vivetool /reset /id:37634385

reboot

vivetool /disable /id:37634385

vivetool /enable /id:37634385

reboot
```

this is not a bug with EP

**Comment by kamil96500** [comment]
I followed the recommended steps you provided and we'll see if it fixes.

I generally had the cards on, but I reset according to your recommendations.

**Comment by Amrsatrio** [comment]
Hi, any updates on this issue? I am not experiencing periodic crashes on 22621.34xx and 22621.34xx, so there is nothing I can do to fix your crashes.

**Comment by kamil9650** [comment]
In general, after the latest update of Windows 11 (from April 23), the current explorer.exe problems have been solved, but I am still checking whether it is for sure.
