### ISSUE TITLE
Google settings obstructing weather widget

### ISSUE THREAD

**Issue by millweedz** [valinet/ExplorerPatcher#3151]
Hi all,

Im getting this popup when using the weather widget. Any ideas? I can't click on anything or it will show a gray screen and send me back to the same screen with the pop up. 
<img width="511" alt="popup" src="https://github.com/valinet/ExplorerPatcher/assets/167653452/9fbefaf3-29a8-4632-acb9-ca423890bee3">

**Comment by pyrates999** [comment]
That is from google's website and not something for EP to fix, sorry.

**Comment by millweedz** [comment]
I'm not expecting EP to fix it, I'm just asking if there's a way to sign in or another way to get rid of this. Is this info connected to a browser on my pc or something?

**Comment by Pedro36511** [comment]
press tab on the Google widget and the more you try by pressing enter, it goes away.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2767
