### ISSUE TITLE
Why does the explorer open every minute?

### ISSUE THREAD

**Issue by Belugono** [valinet/ExplorerPatcher#3152]
Every **minute**

**Comment by pyrates999** [comment]
Uninstall EP and see if it still happens.

**Comment by Belugono** [comment]
Windows 11 Pro
Microsoft Windows
Version 22H2 (OS Build 22621.1105)

ExplorerPatcher version: 22621.3296.64.1

![image](https://github.com/valinet/ExplorerPatcher/assets/121515137/ad8b0997-d44c-48b8-aa9c-f6b314bce880)
![image](https://github.com/valinet/ExplorerPatcher/assets/121515137/485ff808-fbc5-402c-9f6a-a9c7d6c43f5d)

Custom Cursor.

And when the ExplorerPatcher properties are open, then they do not open
But now it stopped due to the fact that the computer was turned on 2 hours ago,
it works for 2 hours then does not open the explorer.exe.

I've already deleted it several times
If I reinstall it again, the explorers will open again.

**Comment by Belugono** [comment]
I only changed the start menu and taskbar

**Comment by pyrates999** [comment]
Your windows version is from January: https://support.microsoft.com/en-gb/topic/january-10-2023-kb5022303-os-build-22621-1105-c45956c6-4ccb-4216-832c-2ec6309c7629

Please install the windows updates for April: https://support.microsoft.com/en-gb/topic/april-11-2023-kb5025239-os-build-22621-1555-5eaaaf42-bc4d-4881-8d38-97e0082a6982
