### ISSUE TITLE
Installing ExplorerPatcher reverts to old Windows 11 search experience

### ISSUE THREAD

**Issue by fo723** [valinet/ExplorerPatcher#3154]
What was previously thought to be caused by EverythingToolbar (fixed after a system restore) has been caused by ExplorerPatcher. I'm on Windows 11 version 23H2 build 22631.3447 which has 3 options for search experiences on the taskbar (search icon, search pill, search bar) I've noticed that upon installing of EP, then not only does ExplorerPatcher refuse to appear in any context menus (even when the necessary options are enabled), it also reverts the search experience on the taskbar to only one option, which upon enabling turns on only the pill option. No other options are available. In addition to this, in the start menu, it also reverts the rounded search bar back to more of a rectangular one with sharper corners. Also, in conjunction with this, search indexing also seems to be disabled. 

I understand that EP restores old Windows components, but from my knowledge it has no ability to restore some from older Windows 11 feature updates, including the updated search experience, which doesn't appear to be an option in the main configuration "Properties" window. Maybe it's some sort of internal configuration?

Very confusing.
Screenshots will be attached.
![bandicam 2024-04-21 20-23-24-918](https://github.com/valinet/ExplorerPatcher/assets/165129634/539688fc-ede3-4091-8bde-8b1dab0350c1)
![bandicam 2024-04-21 20-30-06-167](https://github.com/valinet/ExplorerPatcher/assets/165129634/5885747c-4054-4174-99b4-74f9387dc0e9)

For reference this is how it's supposed to look like:
![image](https://github.com/valinet/ExplorerPatcher/assets/165129634/34a351b2-e6c4-4f63-bc7d-74791a5dba72)
![image](https://github.com/valinet/ExplorerPatcher/assets/165129634/e4974cab-95f2-459a-bfaa-e842cf537f44)

**Comment by pyrates999** [comment]
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

to run the explorer patcher properties application, run this from the run menu:
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.

**Comment by fo723** [comment]
I am no longer using ExplorerPatcher, but the version I was using was the latest one, 22621.3296.64.1. 

The only option I changed was to show classic drive grouping. Even upon installing it without changing any settings this issue began to show.

I do not plan on using ExplorerPatcher again, but I would like a fix for the downgraded search experience.

The taskbar context menu still didn't work after enabling this option.

**Comment by pyrates999** [comment]
Your screen shots show 2 different sections for the search bar settings:

1. Personalization -> Taskbar
2. System -> Taskbar

**Comment by fo723** [comment]
It's a poorly made demo. You can clearly see that in the navigation pane Personalization is selected.

**Comment by pyrates999** [comment]
Even though you think personalization has been selected, the title window still shows:

System -> Taskbar

**Comment by fo723** [comment]
Nevertheless, the point still stands:

ExplorerPatcher downgraded my Windows Search experience.

**Comment by pyrates999** [comment]
You could try repairing your windows install next.  Please run the following in an elevated command prompt or elevated powershell:

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by fo723** [comment]
There were no errors found.

**Comment by pyrates999** [comment]
Did you run the rest of the commands or did you stop with `chkdsk C:`?

**Comment by fo723** [comment]
I ran the rest of the commands. It's fine though. I'll probably be
switching away from Windows to either something entirely different or some
modified version. Thanks for your help.

**Comment by pyrates999** [comment]
One more thing you can try is If you install EP again, in the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

**Comment by puppygirlstink** [comment]
I have the same issue! I have tried everything mentioned above, still Windows 11 start menu. Also started around the same time this issue was created. Version: 22621.3527.65.5

**Comment by pyrates999** [comment]
> I have the same issue! I have tried everything mentioned above, still Windows 11 start menu. Also started around the same time this issue was created. Version: 22621.3527.65.5

install the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

And if not fixed, file a new issue as this is closed.
