### ISSUE TITLE
[Windows 11] Clicking Windows icon does not bring up menu

### ISSUE THREAD

**Issue by virajkarandikar** [valinet/ExplorerPatcher#3156]
Using on OS Windows 11 23H2

![image](https://github.com/valinet/ExplorerPatcher/assets/16838694/9472a94f-df98-4c5e-a7db-7b9c30f968b6)

![image](https://github.com/valinet/ExplorerPatcher/assets/16838694/00db4241-a620-45d1-9734-263ff97ef2e3)

Settings screenshots above.

Clicking on "Windows Icon" on task bar does not do anything. 
Clicking on "Search Icon" works and brings up the Search pane.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by eindrawan** [comment]
Im having the same issue, then installing the latest version
https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.1_9e9c016
works

**Comment by Amrsatrio** [comment]
What is your Windows build? Please screenshot the entirety of the About page.

**Comment by Amrsatrio** [comment]
Closing due to no response and irreproducibility.
