### ISSUE TITLE
Greyed out taskbar quick settings Taskbar win 11

### ISSUE THREAD

**Issue by hecode** [valinet/ExplorerPatcher#3159]
in a recent update the quick settings that come up when clicking on sound/lan icon that has sound settings and night mode has been completely greyed out and unclickable no matter how many explorer and windows restarts. (the menu comes up but disabled) (Taskbar win 11)

I think it started around the time the start menu recommendations section still showing but empty issue was resolved.

Windows 11, OS Build 22631.2861
ExplorerPatcher Version 22621.3296.64.1

**Comment by pyrates999** [comment]
Please update your windows version as your version is from December 2023: https://support.microsoft.com/en-gb/topic/december-12-2023-kb5033375-os-builds-22621-2861-and-22631-2861-90f983aa-efb6-4caa-9cab-7e5cfa00ed36

**Comment by Amrsatrio** [comment]
Night mode being grayed out indicate that your graphics drivers are not properly installed.

Also, please check if the issues persist when EP is not installed.

**Comment by hecode** [comment]
the windows update fixed it, thanks
