### ISSUE TITLE
Window 11 blue screens within 1 min or so of startup 

### ISSUE THREAD

**Issue by hoylegj** [valinet/ExplorerPatcher#3161]
Version 22641.3296.64.3 and 64.1
Win 23H2  22631.3447

I moved the task bar to the left, all was fine
A few days later I put in back to the bottom, my blue screen started. 
I moved it back to the Left, still blue screened 
Uninstalled, still blue screened
Cleared out reg, still blue screened 
Reinstalled, still blue screened 
Started safe mode, no problem

Is there a script to restore the reg back to standard?   
Are there files that need deleting? after he uninstall? 
Blue screen between 30-90seconds. 

regards Geoff.

**Comment by pyrates999** [comment]
if you disabled tabs in windows file explorer, you must re-enable them, otherwise you will have crashes:

```
vivetool /reset /id:37634385

reboot

vivetool /disable /id:37634385

vivetool /enable /id:37634385

reboot
```

this is not a bug with EP

**Comment by hoylegj** [comment]
thanks for your response. 

I've looked everywhere and can not see how to disable or enable explorer tab.

No I have not disabled explorer tabs intentionally.  Could I have done it via this tool accidentally?

many thanks for your help

**Comment by pyrates999** [comment]
Did you try those commands anyways?  EP was disabling tabs in an earlier release.

You can also try in EP properties application, click on **file explorer**, untick **register as shell extension** and click **restart file explorer** in the bottom left corner.

**Comment by hoylegj** [comment]
Thanks, I just tried the commands above, had to install and run them in safe mode as I do not get a chance before it crashes in normal mode. 

No joy still crashed 30 seconds after restart, safe mode still works 

regards Geoff.

**Comment by pyrates999** [comment]
Does uninstalling EP fix it?

**Comment by hoylegj** [comment]
No, I assume it's changed something in registry and that does not get reset on uninstall

**Comment by pyrates999** [comment]
what about if you create a new local user?  That shouldn't have any changes done to the registry.

**Comment by hoylegj** [comment]
Good idea, let me try that.

**Comment by Amrsatrio** [comment]
This doesn't seem like something that EP causes to your system... perhaps there's a hardware problem caused by increased CPU load. Are you running on a custom built PC, prebuilt PC, or a laptop by the way?

**Comment by hoylegj** [comment]
Nope, just the same arrr

**Comment by hoylegj** [comment]
Think I'm ready to blow windows11 away and go back to 10 ;-)

**Comment by hoylegj** [comment]
Thanks all, it's strange I grant you, nothing was installed after apart from the standard Microsoft patches and the issue started after moving the bar back to standard, but I accept it could be something else.  I will look through the event logs before I blow it all away.  Can't say I like windows 11 and will probably go back to windows 10 until 11 has the functionality I need. I've been in I.T. For 30 years as a developer and DBA so I will have a poke around. It's a test machine so not to much of an issue.  Be nice to understand it issue though. 

Regards Geoff

**Comment by pyrates999** [comment]
One more thing you can try is on the user you normally use, in the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

**Comment by Amrsatrio** [comment]
Yeah I believe it's a coincidence and not an issue within EP itself. Feel free to reopen if you have ascertained that this issue happens only when EP is installed.
