### ISSUE TITLE
Win32/Small UI on taskbar right-click menu

### ISSUE THREAD

**Issue by gaven1880** [valinet/ExplorerPatcher#3164]
I love ExplorerPatcher and have been using it for a while, but I noticed that recently, the taskbar right-click menu has reverted to a smaller Win32 UI and I don't like how it looks.

Is this just me?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please post a screenshot so that I can understand your problem better.

**Comment by Amrsatrio** [comment]
Closing due to no response.

**Comment by gaven1880** [comment]
im not on github that much but i wanted to check so here are responses:

@pyrates999 
I use Windows 11 23H2 (build 22631.3447), with modified winver
![image](https://github.com/valinet/ExplorerPatcher/assets/167988752/6c68d195-116c-4442-b5e1-cfd115cc8555)

@Amrsatrio 
![image](https://github.com/valinet/ExplorerPatcher/assets/167988752/150b64d2-f7f5-4a65-b137-956a335eb6c0)
this is how it looks like (its supposed to be taller)

**Comment by Amrsatrio** [comment]
<img width="599" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/b5a94297-94e1-4eb3-9297-15788c47726c">

If you want it to be taller, then it has to be on. Otherwise you are using another software to disable "immersive menus".

**Comment by gaven1880** [comment]
thanks
