### ISSUE TITLE
Hide labels not working for Win 10 taskbar on Win 11

### ISSUE THREAD

**Issue by RatMonkey0** [valinet/ExplorerPatcher#3167]
Hi,
I have the exe installed on a Windows 11 machine so I can move my taskbar to the left of the screen, which is working great, however, the "Combine taskbar buttons and hide labels" does not seem to be working. Applications are not combined and have full labels regardless of which setting I choose.
I checked other known bugs and could not see this, thus I am raising a new one.
OS version is 23H2 (OS Build 22631.3447)
Thanks.

**Comment by pyrates999** [comment]
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by RatMonkey0** [comment]
Hi,
Explorer Patcher version is:
![image](https://github.com/valinet/ExplorerPatcher/assets/168012767/07afbb1f-cf5c-4453-a26f-be9005a719bd)
The only setting I have changed is the Taskbar Style to Windows 10:
![image](https://github.com/valinet/ExplorerPatcher/assets/168012767/1fdb2958-b004-4f5d-ad73-64380df32264)
I also did switch the Start Menu to Windows 10, but decided to switch it back to Windows 11:
![image](https://github.com/valinet/ExplorerPatcher/assets/168012767/70e83a1e-007a-479a-86d7-341d00d163ad)
As far as I am aware, there is no other Windows UI modification software installed.

**Comment by Amrsatrio** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/76c821a9-5bf7-4980-bc9e-4e2e0fc92ce0)

**Comment by RatMonkey0** [comment]
What an idiot I am lol - I was looking in the normal Windows settings, didn't see that there in the properties! (facepalm) Thanks for your help!! :)
