### ISSUE TITLE
search box font is weird when its on

### ISSUE THREAD

**Issue by chancelovesgames** [valinet/ExplorerPatcher#3171]
![image](https://github.com/valinet/ExplorerPatcher/assets/158217415/e54e17d5-6f00-47b4-925c-c59fad2c2971)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.
