### ISSUE TITLE
SEARCH MENU DOESN'T ALLOW ME TO PIN TO START MENU

### ISSUE THREAD

**Issue by SKU003** [valinet/ExplorerPatcher#3172]
I've tried to pin an app to start menu via the search menu and no matter what I try it never works. I know I can use the start menu area however some apps aren't there until I go to the search menu and pick it from there. Because I like to customize my start menu look and so it's hard to use if I can't get it from there or even from the taskbar it just doesn't work. Also, I've checked also in File Explorer you can't also. It's quite limiting.

Also let me just add that for some reason there is a delay when closing start menu as you can see.

https://github.com/valinet/ExplorerPatcher/assets/117542049/81127ec1-6da8-46d7-aca0-7421b75d2018

**Comment by pyrates999** [comment]
Is this the same thing? https://github.com/valinet/ExplorerPatcher/issues/2752

**Comment by SKU003** [comment]
It's similar, yet not straightforward for me to find a solution which would you advise me to use, to fix it or a work around that isn't something that needs much to be done?

**Comment by pyrates999** [comment]
Follow the instructions for the work around then.
