### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by Quantic17** [valinet/ExplorerPatcher#3173]
With the latest windows update (2024-04 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5036980))
the start menu is no longer showing the windows 10 menu but defaults to the Windows 11 menu.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3162

please close this.

**Comment by Quantic17** [comment]
Done
