### ISSUE TITLE
Can't use windows 10 start menu after update.

### ISSUE THREAD

**Issue by LtSerg** [valinet/ExplorerPatcher#3174]
![imagen](https://github.com/valinet/ExplorerPatcher/assets/123405671/36e81f7a-a4a1-4444-9847-8aba0e0cc5d8)

Updated windows, now I cannot access the windows 10 start menu even though I have selected it in the configuration.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3066
