### ISSUE TITLE
22621.3527.65.1 Black Screen

### ISSUE THREAD

**Issue by mbsl4y3r** [valinet/ExplorerPatcher#3176]
This release keeps failing and crashing explorer.exe

Tried multiple restarts and multiple installs. If anyone else gets stuck, you need to ctrl+alt+delete and right click on a background process and Open File Location, then either reinstall an older version, for search for explorer.exe in c:\ and keep clicking it until the explorerpatcher.exe error finally pops up and stays disabled and you will be back on w11 normal.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by mbsl4y3r** [comment]
I closed out the issue and moved it to discussions where it should have been. Release has also been pulled a new working one released.

Anyways, V 22H2 B 22621.3447
