### ISSUE TITLE
Start menu issue since the laste update

### ISSUE THREAD

**Issue by clementamiri** [valinet/ExplorerPatcher#3181]
Hi there, 

Since the last update, my start menu displayed windows 11 style and not windows 10 style. I tried to play with all properties in the set up. There is no way to bring back windows 10 start menu style . 

![Capture d'écran 2024-04-25 191735](https://github.com/valinet/ExplorerPatcher/assets/38793501/d646dd83-2432-4b84-80fc-8af177da9ce6)
![Capture d'écran 2024-04-25 191735](https://github.com/valinet/ExplorerPatcher/assets/38793501/2d455e5e-310c-483c-8933-bdbebf3a4461)
![Capture d'écran 2024-04-25 191754](https://github.com/valinet/ExplorerPatcher/assets/38793501/8e839ed7-a0c5-4841-a861-972845fa3279)
![Capture d'écran 2024-04-25 191804](https://github.com/valinet/ExplorerPatcher/assets/38793501/e9f92a15-19bf-4aa1-afcf-578f8802724d)
![Capture d'écran 2024-04-25 191817](https://github.com/valinet/ExplorerPatcher/assets/38793501/06158a62-a658-4c89-a6b8-dc42a843ad63)

If someone have an idea or solution, it will be great for me ;) 
Thanks for the help!

**Comment by abbychau** [comment]
me too

**Comment by mehdi-abdelkhalek** [comment]
This happened to me yesterday after a Windows update.
I am using latest ExplorerPatcher stable version 22621.3296.64.1
My OS:
Edition	Windows 11 Home Single Language
Version	23H2
OS build	22631.3527
Experience	Windows Feature Experience Pack 1000.22700.1003.0

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.1_0976666

Please, be aware with the latest prerelease builds. Since you all are running a *preview*, in other words, *optional* update, be sure to check EP's prerelease builds which may contain the fixes for the preview updates.

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by Mr-Dizzy** [comment]
如果你受不了这样，我建议你还是先把这个windows版本回退来的比较快，设置 - windows更新 - 更新历史记录 - 卸载更新 ，找到这次更新并卸载然后重启就行了

**Comment by joelagrell** [comment]
> Get this prerelease build of EP:
> 
> https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.1_0976666
> 
> Please, be aware with the latest prerelease builds. Since you all are running a _preview_, in other words, _optional_ update, be sure to check EP's prerelease builds which may contain the fixes for the preview updates.

this pre-release fixed it for me :) thanks a lot!

**Comment by clementamiri** [comment]
> Get this prerelease build of EP:
> 
> https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.1_0976666
> 
> Please, be aware with the latest prerelease builds. Since you all are running a _preview_, in other words, _optional_ update, be sure to check EP's prerelease builds which may contain the fixes for the preview updates.

Thank you !!
