### ISSUE TITLE
Cannot get the W10 startmenu back.

### ISSUE THREAD

**Issue by TomasL-SE** [valinet/ExplorerPatcher#3185]
Suddenly today, the old start menu disappeared, and EP cannot get.
 it back.
EP is V 22621.3296.64.1
Win is 23H2, 22631.3527

**Comment by Markcoruk** [comment]
Same here Windows 11 menu is rubbish.

**Comment by SANSKARLKE** [comment]
fix it as soon as possible please

**Comment by Fr0stX76** [comment]
Use the [new pre-release](https://github.com/valinet/ExplorerPatcher/releases/download/22621.3527.65.1_0976666/ep_setup.exe)

**Comment by TomasL-SE** [comment]
Yepp, that worked.
My latest update was KB5036980, apperantly it introduces the new look in the standard startmenu

**Comment by TomasL-SE** [comment]
only drawback is that "Live Tiles" does not work.

**Comment by robtgmann** [comment]
Same here.

**Comment by dmiller423** [comment]
ugh...

**Comment by matrixcomputer73** [comment]
Same here 23H2 22631.3527 Help Please . I can't stand  the  windows 11 start menu

**Comment by pyrates999** [comment]
I use open shell with the windows 7 style start menu.  So much better then any of the newer start menu's that came out after it.

**Comment by TomasL-SE** [comment]
well, I like the panels in W10 menue

**Comment by robtgmann** [comment]
How does one do that?   I don’t see a windows 7 option within EP
 

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------
Robert Goldmann
Clarity & Performance Coaching
Executives, Professionals, Business owners
www.ClarityAndPerformance.com <http://www.clarityandperformance.com/> 
www.ActFromChoice.com <http://www.actfromchoice.com/> 
510.495.4444
--------------------------------------------------------------------------------------

**Comment by pyrates999** [comment]
This is openshell: https://github.com/Open-Shell/Open-Shell-Menu
