### ISSUE TITLE
Explorer.exe crashing regularly with ExplorerPatcher 22621.3296.64.1

### ISSUE THREAD

**Issue by ch826** [valinet/ExplorerPatcher#3186]
I have been experiencing regular crashes of Explorer.exe. Navigating around the system results in Explorer.exe crashing. I can simply be copying a file from one folder to the other, doing nothing else, and halfway through the process (with nothing else being done), Explorer.exe crashes.

I have used ExplorerPatcher successfully for a long time without problem. Everything used to run perfectly. Occasionally, a Windows update would be automatically installed and ExplorerPatcher would stop working, but after applying an ExplorerPatcher update, everything would begin working again. 

However, after the last Windows system automatic update happened (a month or so ago), this is when Explorer.exe crashes started happening. I updated ExplorerPatcher to the most recent version that is installed by the installer (22621.3296.64.1). Crashes continue occurring regularly. I looked for a solution on Gibhub, saw someone mention checking to see whether "Register as shell extension" was enabled, as this might cause crashes if it is enabled. That feature is not enabled in my settings. I tried switching to Windows 11 style taskbar via ExplorerPatcher settings, but the crashes still occur. I'm not sure what to do.

I have loved using ExplorerPatcher and would certainly hate to go back to using Windows 11's taskbar, but the way things currently stand, the system is becoming too unusable. Any ideas?

I am running Windows 11, OS Build 22631.3296.
 
Information from Event Viewer:

Faulting application name: explorer.exe, version: 10.0.22621.3296, time stamp: 0x48d2cb32
Faulting module name: explorer.exe, version: 10.0.22621.3296, time stamp: 0x48d2cb32
Exception code: 0xc0000409
Fault offset: 0x00000000000a2c30
Faulting process id: 0x0x1C17C
Faulting application start time: 0x0x1DA980489D4DA5E
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\explorer.exe
Report Id: eabeedb1-99e9-4543-a96c-ba3373fe81d2
Faulting package full name: 
Faulting package-relative application ID: 

(Thanks for any help.)

**Comment by pyrates999** [comment]
Please install the april 9 2024 update for windows 11.

Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by JoTechOfficial** [comment]
I had the same issue but it went away after a while.
