### ISSUE TITLE
Win 10 Start Menu Not Working

### ISSUE THREAD

**Issue by ndg8743** [valinet/ExplorerPatcher#3198]
I just did a Windows update, and now the start menu is Windows 11 style even though its set to Win 10.
![image](https://github.com/valinet/ExplorerPatcher/assets/73437724/667acaef-a109-499c-8708-7c2a8c8f04a5)
Windows 11, version 23H2

**Comment by ndg8743** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/73437724/aeef83ef-8a96-44b4-a50e-2c5b71ccb1f5)
sorry this update specifically

**Comment by ashefpv** [comment]
What version of ExplorerPatcher and Windows 11 are you running? There have been some recent updates to ExplorerPatcher.

https://github.com/valinet/ExplorerPatcher/releases

•Taskbar10: The Windows 10 taskbar option is now no longer available on 26002+.
This is to comply with Microsoft's removal of the stock Windows 10 taskbar in explorer.exe of said builds.

**Comment by ndg8743** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/73437724/3d92ee33-ed56-4df2-b5e3-c268096b13b2)
i made sure to update it first b4 I even made this an issue, but was up to date
