### ISSUE TITLE
Modern Search Box is always disabled in 22000.194.0.22 and 22000.194.0.20

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [valinet/ExplorerPatcher#32]
The option to keep/enable the modern search box is not working in these versions even if the INI has:
[General]
AllowModernSearchBox=1

or even if it is set in the GUI in the newest version.

Going back to 22449.1000.0.18 or disabling ExplorerPatcher does bring it back. I am on Windows 11 22468.1000.

**Comment by valinet** [comment]
`AllowModernSearchBox=1` is deprecated; the patcher now has nothing to do with that functionality anymore; I remove it in favor of setting the relevant registry keys and having File Explorer automatically give up or not on the new search box and use the old one. As far as the patcher is concerned, it really never touches anything about that anymore, besides the new GUI setting the relevant registry entries for you.

Also, I cannot reproduce this 'bug' on my machine which is on 22000.194. I don't test anymore on Insider builds, I can't do all the stuff at the same time...

To debug, make sure no shell "extension" like ExplorerPatcher or StartIsBack is running, then make sure you do not have the following registry key: `HKEY_CURRENT_USER\Software\Classes\CLSID\{1d64637d-31e9-4b06-9124-e83fb178ac6e}\TreatAs` and then that should be it, the modern search box should show.

I will push a new version of the patcher in a couple of hours that addresses a few issues, including that bug where it fails to load in `StartMenuExperienceHost.exe`. Maybe that automagically fixes it...?

**Comment by Gaurav-Original-ClassicShellTester** [comment]
I feel really stupid and silly for wasting your time. It's a StartIsBack issue.

**Comment by valinet** [comment]
No worries, mistakes happen, no grudge held. I am glad that you figured it out.

**Comment by valinet** [comment]
Scenario #3 should not happen. ExplorerPatcher does not touch that search box anymore. It is just a registry entry and that's it. If something happens, it is not on my part. Do you have `StartIsBack64.dll` in `%appdata%\ExplorerPatcher` as well in scenario #3? If you run ExplorerPatcher and leave the modern search box enabled in it, it is StartIsBack's problem what it does with it, PERIOD. I don't touch it in the code. I don't understand how it might happen, but I think it is something else...
