### ISSUE TITLE
Feature Request: Use classic Contect Menu in fodler windows but modern Contect Menu on desktop

### ISSUE THREAD

**Issue by DavidXanatos** [valinet/ExplorerPatcher#3202]
I would like to use the classical context menu in folder windows, but not on the desktop.
As I run explorer folder windows in a separate process this should be quite easy EP would only need a setting and detect if it lives in the shell explorer or the browse fodlers explorer and apply the hack for classic context menu conditionally

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
