### ISSUE TITLE
Microsoft Copilot taskbar button in the system tray is missing 

### ISSUE THREAD

**Issue by ZeX2024** [valinet/ExplorerPatcher#3206]
Hi everyone .. I'm using win 11 64-bit  .. Copilot taskbar button in the bottom-right corner is disappeared  , is there a way to bring it back ..thanks
![Copilot button](https://github.com/valinet/ExplorerPatcher/assets/168536242/e12c095c-1233-4348-a9e1-db7134b29214)

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/issues/2866#issuecomment-2002120921
