### ISSUE TITLE
Unaible to uninstall ExplorerPatcher

### ISSUE THREAD

**Issue by DraganVictor14** [valinet/ExplorerPatcher#3211]
I cannot uninstall ExplorerPatcher (on 24H2) after installing it!
Have someone an ideea how to uninstall it?
![Screenshot 2024-05-01 114329](https://github.com/valinet/ExplorerPatcher/assets/85784251/bd61f28a-c2d8-4356-95a1-71be9876f5e2)

**Comment by Amrsatrio** [comment]
Download the latest EP setup, rename it to ep_uninstall.exe. I will not try to get around this for now.
