### ISSUE TITLE
[Compatibility issue] Windows Cumulative Update KB5036980 20240428

### ISSUE THREAD

**Issue by Hippologist** [valinet/ExplorerPatcher#3212]
Current version does not support the new update patch KB5036980 on 20240428. (Win11)
Once the system has been updated, the start menu disappears and never runs.

Then I tried to downgrade by uninstalling the patch KB5036980
Now it works again as before.

An update for this patch will be a good idea.

Best,

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
@pyrates999 3527 is supposed to be supported by the latest version of EP. However the start menu not appearing bug might indicate that the user has something else installed that interferes with EP's new method of restoring the 10 start menu.

**Comment by Amrsatrio** [comment]
@Hippologist Please specify the "Current version" of EP you're using. I have no issues with the start menu on EP 65.2.

**Comment by pyrates999** [comment]
> @pyrates999 3527 is supposed to be supported by the latest version of EP. I am daily driving it on my laptop and I haven't spotted any issues yet other than explorer crashing when navigating away from the new XAML Home and Gallery.
> 
> However the start menu not appearing bug might indicate that the user has something else installed that interferes with EP's new method of restoring the 10 start menu.

This was before I knew you had done a release to support the preview update.

**Comment by TotemicWeevil** [comment]
> Current version does not support the new update patch KB5036980 on 20240428. (Win11) Once the system has been updated, the start menu disappears and never runs.
> 
> Then I tried to downgrade by uninstalling the patch KB5036980 Now it works again as before.

I have the same problem - my start menu and right click options aren't working at all.... I have looked for the offending update so that I can uninstall it - but I can't find it to remove it. Windows update history says it's there, but I can't find it.
Any suggestions?

**Comment by Hippologist** [comment]
> > Current version does not support the new update patch KB5036980 on 20240428. (Win11) Once the system has been updated, the start menu disappears and never runs.
> > Then I tried to downgrade by uninstalling the patch KB5036980 Now it works again as before.
> 
> I have the same problem - my start menu and right click options aren't working at all.... I have looked for the offending update so that I can uninstall it - but I can't find it to remove it. Windows update history says it's there, but I can't find it. Any suggestions?

The newest version of EP successfully solved the old issue.
Try updating the EP.exe by redownloading it, and it will works for each Win11Patch.
At least works for me.

**Comment by TotemicWeevil** [comment]
> The newest version of EP successfully solved the old issue. Try updating the EP.exe by redownloading it, and it will works for each Win11Patch. At least works for me.

Sadly didn't work for me. I re-installed (latest version) and tested - nope, nada, zip. nothing doing. my start button still won't work when left clicked on. Although, right click now works for some reason.

**Comment by TotemicWeevil** [comment]
Does anyone know how to uninstall the offending KB btw? I've read elsewhere that it's causing issues on computers that aren't logged into a M$ account - ie it's screwing with local accounts (somehow)....

**Comment by Amrsatrio** [comment]
@TotemicWeevil Do you see the "wait" cursor when you press the start button? Does the start menu work when it is set to Windows 11? Does it also work if EP is not installed?

**Comment by TotemicWeevil** [comment]
> @TotemicWeevil Do you see the "wait" cursor when you press the start button? Does the start menu work when it is set to Windows 11? Does it also work if EP is not installed?
> 
> I have a feeling that you should reset your Windows 10 start menu layout if the 11 menu doesn't work as well.

When left clicking on the start menu - either version - I get the animation that the button has been pressed, but no text or action of any type - so no menu at all.
Uninstalling EP doesn't fix the issue either.

**Comment by Amrsatrio** [comment]
Yeah seems like it's a Windows issue all over again...

**Comment by TotemicWeevil** [comment]
> Yeah seems like it's a Windows issue all over again...

As I asked earlier, is there a way that you're aware of the uninstall KB5036980? I have looked at removing it via DISM but its not listed in the packages that I can see - unless it's been renamed somehow.
The only other option I have is to re-install windows 11, which I don't want to do unless I really have to.

**Comment by pyrates999** [comment]
Try this:

1. Click Start and type cmd in the Start menu search box. Right-click it and click Run as administrator.
2. In the command prompt, type in the following command format and hit Enter to proceed the process:
```
wusa /uninstall /kb:5036980
```

**Comment by TotemicWeevil** [comment]
> Try this:
> 
>     1. Click Start and type cmd in the Start menu search box. Right-click it and click Run as administrator.
> 
>     2. In the command prompt, type in the following command format and hit Enter to proceed the process:
> 
> 
> ```
> wusa /uninstall /kb:5036980
> ```

Sadly, this update is actually apart of my installation of windows and cannot be removed :(
Oh well, incoming reformat and re-install of everything....

**Comment by pyrates999** [comment]
Then take this as a lesson learned and don't install preview updates.

**Comment by TotemicWeevil** [comment]
> Then take this as a lesson learned and don't install preview updates.

I'll have you know that I'm NOT using a preview update ... I'm using 23H2 build 22631.3527.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/april-23-2024-kb5036980-os-builds-22621-3527-and-22631-3527-preview-5a0d6c49-e42e-4eb4-8541-33a7139281ed

**Comment by TotemicWeevil** [comment]
Well I certainly didn't install it on purpose.. I downloaded Win 11 Pro directly from m$. Windows update installed that KB.

**Comment by pyrates999** [comment]
If windows update installed it. then you need to do the following to prevent preview updates from being installed automatically again:

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by TotemicWeevil** [comment]
Thanks for the info. I've gone and turned off the Get updates.. option, so thanks once again.
I have applied EP again to this machine and despite having the offending KB, it took with no adverse effects thus far - fingers crossed that it continues that way in the future.
