### ISSUE TITLE
KEEPS CRASHING MY PC 💻 

### ISSUE THREAD

**Issue by SKU003** [valinet/ExplorerPatcher#3213]
I don't understand the problem, I can't uninstall it, I can't update it and maybe even changing a setting or two can cause it to crash my PC. It keeps bringing the blue screen and this is quite frequent, and it's making me worried that I'd need to factory reset my whole PC.

ExplorerPatcher
Version 22621.3296.64.1
@ 2006-2024 VALINET Solutions SRL. All rights reserved.

Running on Windows 11, OS Build 22631.3447.

![2024_05_01 8_31 pm Office Lens](https://github.com/valinet/ExplorerPatcher/assets/117542049/e148c38b-c9d7-43de-9579-192b048ff19d)

**Comment by pyrates999** [comment]
You may need to repair your windows install.  Please run the following in an elevated command prompt or elevated powershell:

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by Amrsatrio** [comment]
Delete C:\Windows\dxgi.dll and see if the BSODs still persist. I still do not believe that EP is a source of BSODs.

**Comment by SKU003** [comment]
I'll try them out, and give feedback on a later date.

**Comment by SKU003** [comment]
You could be right for all I know, I'm not quite knowledgeable behind what causes the issues, yet for all I know is when I try to install the new update or try to uninstall it via “Rename ep_setup.exe to ep_uninstall.exe and run that.” it produces the same results. 


https://github.com/valinet/ExplorerPatcher/assets/117542049/0c64d6d8-ebf5-4817-998c-9e5f74ad0581

**Comment by pyrates999** [comment]
Try the following:

1. boot into safe mode
2. open up an elevated command prompt or elevated powershell
3. open up task manager and kill explorer.exe process
4. in the elevated command prompt or elevated powershell, run the following:
```
del /P C:\Windows\dxgi.dll
```
5. reboot and see if the BSOD is still happening

**Comment by SKU003** [comment]
It worked, although trying to end Explorer.exe wasn't there. The other method worked. 

I can say my Windows taskbar is back now and so it just hasn't brought back the old Windows 11 start menu. So I thought I could switch it back by downloading the updated Explorer Patcher afresh but the same thing happened. Would you recommend that I don't use EP in the meantime or what would you suggest? 

Although, thank you, since I learnt a thing or two. 



![20240505_000636.jpg](https://github.com/valinet/ExplorerPatcher/assets/117542049/cf537cb3-897f-4399-afc6-7ef27ef2ac60)

**Comment by pyrates999** [comment]
Do you see explorer.exe in task manager when windows is booted normally?  Is your user an administrator account?

**Comment by SKU003** [comment]
Yes to all the above, However, the same issue occurs when I try to end the task. It'll just crash.

![0szhaT0wOz](https://github.com/valinet/ExplorerPatcher/assets/117542049/5d839d3c-51b9-4929-a6a2-0e19fcc82bfb)
![0OsEfFuY1O](https://github.com/valinet/ExplorerPatcher/assets/117542049/4853679d-4008-4540-8044-d8fba604cce1)

**Comment by pyrates999** [comment]
Can you uninstall EP or does your pc bsod at that point as well?

In task manager, when selecting windows explorer, and clicking on the restart button, does it happen after you uninstall EP?

In task manager, when you stop all processes named explorer.exe, does it happen after you uninstall EP?

**Comment by pyrates999** [comment]
Did you also try repairing your windows install?

**Comment by SKU003** [comment]
The bsod happens no matter what I do, so even trying to uninstall it, the same thing happens. I followed the uninstall guide and still the same thing happened.

When the bsod comes up and it tells me to repair it says nothing is wrong so I'm stuck with the same problem.

**Comment by pyrates999** [comment]
This sounds like hardware to me.  At this point, I would try reinstalling windows.  Backup everything you have before you do that.

**Comment by SKU003** [comment]
I understand, thanks for the advice.
