### ISSUE TITLE
Search button not working

### ISSUE THREAD

**Issue by Zatheroger** [valinet/ExplorerPatcher#3215]
I'm on Windows 11 Pro Version 23H2 OS build 22631.3447 WITH ExplorerPatcher version 22621.3527.65.2. The search button doesn't work, the shortcut Windows+Q doesn't do anything, and the home menu search also doesn't work.

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please check if there is `FullscreenCXHRunning` in `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\CloudExperienceHost\Fullscreen`. If there is one, please delete the `Fullscreen` subkey in the sidebar.

**Comment by CallMeLewis** [comment]
> Please check if there is `FullscreenCXHRunning` in `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\CloudExperienceHost\Fullscreen`. If there is one, please delete the `Fullscreen` subkey in the sidebar.

Also checked on my machine and this subkey doesnt exist. My system is running 22631.3527 and search in start menu no longer responds. Even tested by uninstalling explorerpatcher and still does not work. I believe this may be a windows issue.

**Comment by ded811** [comment]
> Please check if there is `FullscreenCXHRunning` in `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\CloudExperienceHost\Fullscreen`. If there is one, please delete the `Fullscreen` subkey in the sidebar.

That worked for me thanks.
