### ISSUE TITLE
Trojan:Win32/Vigorf.A

### ISSUE THREAD

**Issue by ircserkan** [valinet/ExplorerPatcher#3225]
Update 22621.3527.65.2 raises a Trojan warning. I wonder why ?

**Comment by mkjeller** [comment]
Confirming, latest signature update to Windows Defender triggers a "Severe" warning for "Vigorf.A" in any Explorer Patcher Executables or registry entries.
EP continues to function as expected, however.

**Comment by Fableton** [comment]
in my case it throw
![image](https://github.com/valinet/ExplorerPatcher/assets/5140964/af8684f1-5a8a-41b8-8f43-ccc7864426d6)

**Comment by Bixilon** [comment]
So, I am actually rolling out explorer patcher for some devices (~30). Windows 11 is imho unusable.

@Microsoft: I need to work, not to try your experimental stuff. Why are you interfering my productivity? The old design lets me find windows really quickly and in the small tiles new one thing I need to click through 10 windows first. Also in large environments you can't just update to windows 11, you don't want that your users (who might have no clue about computers) to not find anything again. They are used to their old environment. Please stop!


I have no doubt that this project is maleware free, the one problem is: How to add an exception without user confirmation? I can understand that windows does that by design (I mean it should), but I never had an such an error yet. Does anybody have any clue?

**Comment by ircserkan** [comment]
22621.3527.65.1 It does not give this warning in its version, but it gives this warning in version 65.2.

**Comment by tienthanh2509** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/1713444/ca12948b-7ef1-4d6d-bf24-db03febeb5af)
Windows defender blocked new update HackTool:Win64/ExplorerPatcher!MTB

**Comment by Rolzzz** [comment]
> ![image](https://private-user-images.githubusercontent.com/1713444/327916679-ca12948b-7ef1-4d6d-bf24-db03febeb5af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTY0MDEsIm5iZiI6MTcxNDc5NjEwMSwicGF0aCI6Ii8xNzEzNDQ0LzMyNzkxNjY3OS1jYTEyOTQ4Yi03ZWYxLTRkNmQtYmYyNC1kYjAzZmViZWI1YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDRUMDQxNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJmYTJhMDYyMGYzZGVlNmU4OGFmN2NmZDk2OTVmY2Y0YjFjZGY1NzFjZmU4OWQ5MDZjN2QzMWNiMGRlYzc3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pXZ1SOoij3qv04Elu9HbxQYL2TA0D3no7zNrZ5Edng8) Windows defender blocked new update HackTool:Win64/ExplorerPatcher!MTB

yeah I got same... will uninstall for now... bit of a shame was may saviour for a really fucked Win11 gui

**Comment by pyrates999** [comment]
This is a false positive.

Update your windows defender signatures by going to settings -> updates & security -> windows security
Then click on virus & threat protection
Under virus & threat protection updates, click on check for updates
Then click on the button named check for updates

Then if it is still being detected as malicious, you can try to submit it as a false positive to Microsoft: https://www.microsoft.com/en-us/wdsi/filesubmission

You can also set windows defender to exclude C:\Program Files\ExplorerPatcher so future updates won't be blocked by windows defender.
You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

**Comment by Amrsatrio** [comment]
@pyrates999 Please do not suggest to submit this to MS. They clearly do not like EP anymore given the current state of events, so they will definitely mark this as virus again. It is pointless. At this point users have to compile their own EP to live with it without any interruptions from Defender.

**Comment by pyrates999** [comment]
Sorry.  I won't suggest that in the future.

**Comment by sruPL** [comment]
I watched some videos pointing to the facts that Microsoft is blocking programs like EP and other similar programs "fixing" Windows or bringing back old tools, UIs or settings in the latest Windows 11 24H2 update. Really worrying news.

**Comment by Bixilon** [comment]
So, on my side it is solved. I could install the latest version without any issue.

Can anybody confirm this?

thanks @microsoft!

**Comment by Rolzzz** [comment]
I just checked and my laptop is still running 22621.3527.65.1 on mine with no update available.

My gaming machine I haven't tried again since issue... will monitor on my laptop for next update.

**Comment by Bixilon** [comment]
@Rolzzz Okay, let me clairify what I meant: I could clean install 22621.3527.65.1 on my windows 11 device without needing to change any windows defender settings (they are the default; no exceptions added)

**Comment by tienthanh2509** [comment]
Build 22621.3527.65.1 is clean now and it can install without disable windows defender
