### ISSUE TITLE
Failure in reading symbols for "C:\Windows\explorer.exe".

### ISSUE THREAD

**Issue by classicrocker883** [valinet/ExplorerPatcher#3227]
Not sure what this is about. I am not having any issues, but this came up, I thought I would post it anyway.

to reproduce:
- Enable Console
- Close CMD Window (if it is blank)
- - another terminal pops up and gives this:
```ini
Running on Windows 11, OS Build 10.0.22621.3447.
[Symbols] Symbols for "explorer" are not available.
Attempting to download symbol data; for now, the program may have limited functionality.
Setup user32 functions done
explorer.exe!CImmersiveColor::GetColor() = A865C
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 47430
ITrayUIHost = 3C0318
explorer.exe!TrayUI_CreateInstance() = 1A94EC
Setup explorer functions done
Setup uxtheme functions done
[SMA] matchVtable = 78EBC0
...
[Updates] Starting daemon.
...
[Updates] No updates are available.
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for OS version 10.0.22621.3447.
[Symbols] Downloading to "C:\Users\Andrew\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\Windows\explorer.exe" ("7be03dcc9e6eee0f811f680c66ca05e0")...
[Symbols] Reading symbols...
[Symbols] Failure in reading symbols for "C:\Windows\explorer.exe".
```

**Comment by Amrsatrio** [comment]
You'd only have non working search box option, other than that you can ignore that message.

https://ramensoftware.com/windhawk-and-symbol-download-errors

**Comment by Amrsatrio** [comment]
Microsoft has made explorer.exe symbols available again.

**Comment by classicrocker883** [comment]
> Microsoft has made explorer.exe symbols available again.

hey nice, no more error, or technically warning

**Comment by shodanx2** [comment]
What is the url to download these symbols (in my case for OS build 10.0.19045.2006 )
And where do you need to put them to avoid the error notification automatically ?

My copie of windows does not have internet access.

**Comment by pyrates999** [comment]
Internet access is required.  Windows symbols change with each new monthly release of updates for windows.

**Comment by shodanx2** [comment]
I am running airgapped windows 10 22h2, it will never update. How can I obtain and install the symbols, manually without an internet connection for that specific version ? thanks

**Comment by Amrsatrio** [comment]
@shodanx2 If you're not using some settings for customizing the start menu behavior, symbols are optional. EP now looks for required stuff in the binaries without them.
