### ISSUE TITLE
Secondary taskbar is empty since last Windows update (10.0.22631 Build 22631) when on Windows 10 mode

### ISSUE THREAD

**Issue by Nenrikido** [valinet/ExplorerPatcher#3233]
Hi, i'm using 2 screens and since last update, on Windows 10 mode, the taskbar on the 2nd screen is empty when before it had the same programs displaying as the main taskbar.
It works fine in windows 11 mode (although the main taskbar shows text and the secondary doesn't, which is weird)
Is there a setting that changed ? I tried to tinker with everything to no avail

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
There is a known issue where the secondary taskbar app icons would be empty if TranslucentTB is running. Are you using TTB?

**Comment by Nenrikido** [comment]
> There is a known issue where the secondary taskbar app icons would be empty if TranslucentTB is running. Are you using TTB?

Yes ! I just figured that out too that by unloading translucentTB, is works.
Would there be a workaround to have a translucent taskbar with icons on all the taskbars ?

**Comment by Nenrikido** [comment]
I found a workaround : i have to enable the "show taskbar border" in TTB settings for Desktop and visible window

I'll close this issue then, sorry for the bother

**Comment by pyrates999** [comment]
For transparency, I run NiceTaskBar.
