### ISSUE TITLE
Please help! Can't uninstall.

### ISSUE THREAD

**Issue by WinAurora** [valinet/ExplorerPatcher#3234]
I just wanted to uninstall explorerpatcher but it gave me this error. I'm kind of shaking. is there anyway to fix this?
![Screenshot 2024-05-05 233924](https://github.com/valinet/ExplorerPatcher/assets/168923855/51a3a127-db67-4b64-9c4b-e6115e1eb273)

**Comment by WinAurora** [comment]
**UPDATE: Just now i have found it's Windows Defender causing these issues.**
Is the way to fix this error by manually downloading the same setup.exe i have used to download EP? or is the ep_setup.exe file in the Program Files\ExplorerPatcher different?

**Comment by WinAurora** [comment]
**FIXED!**
If anyone is having the same problem as me, do what i did below:
**- Turned off Windows Security (Defender)**
**- Downloaded the ep_setup.exe file (It has to be the same setup file you used to download ExplorerPatcher!)**
**- Cut/Copy and then Paste the ep_setup.exe file that you downloaded to C:\Program Files\ExplorerPatcher**
**- Go back to ExplorerPatcher, then Uninstall.**

_**IF YOU GET AN ERROR WHICH SAYS "ERROR SERVICING EXPLORERPATCHER", IT DOESN'T MATTER. EXPLORERPATCHER STILL UNINSTALLS.**_

**Comment by pyrates999** [comment]
You can also set windows defender to exclude the following:
1. C:\Program Files\ExplorerPatcher
2. %APPDATA%\ExplorerPatcher

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.
