### ISSUE TITLE
Does this hide Ethernet, Sound and Noti icon? 

### ISSUE THREAD

**Issue by WilliamLeGod** [valinet/ExplorerPatcher#3246]
![image](https://github.com/valinet/ExplorerPatcher/assets/70202711/41046319-ccf6-4aee-ad49-49ad5fe58902)
Hi guys!

Does this software hide Ethernet, Sound and Noti icon? 

Many thanks!

**Comment by Amrsatrio** [comment]
I don't know about the 11 taskbar but you can hide them if the 10 taskbar is used.
