### ISSUE TITLE
更新最新版本win11后，底部导航栏老是崩溃，启动删除程序提示“此应用无法在此设备上运行”，

### ISSUE THREAD

**Issue by Liuxin4950** [valinet/ExplorerPatcher#3249]
程序兼容性助手开发者具PC此应用无法在此设备上运行ExplorerPatcherVALINET Solutions SRLCharn此应用会导致 Windows上出现安全性或性能问题，因此无法运行。
Program Compatibility Assistant Developer with PC This application cannot run on this device ExplorerPatcherVALINET Solutions SRLCharn This application causes security or performance issues on Windows and therefore cannot run.
可能有新版本可用。
New versions may be available.
请联系你的软件提供商获取在此版本的Windows 上运行的更新版本。
Contact your software provider for an updated version that runs on this version of Windows.
W允许 WindoOffi了解更多取消会近
W Allow WindoOffi to learn more about cancellation will be near

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

**Comment by Amrsatrio** [comment]
Up to MS if they want to remove the hardblock from EP on 26100+. We have no plans yet of renaming our exe names to get around that.
