### ISSUE TITLE
Disabling Context Menu Skinning not affecting Desktop/File Explorer 

### ISSUE THREAD

**Issue by pancakerings** [valinet/ExplorerPatcher#3252]
**ignore the weirdly dark context menu when i enable it (it's on my end)**

https://github.com/valinet/ExplorerPatcher/assets/123368490/d9a283db-7ee0-4a8c-81b2-342fb68bcc42

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
There is a separate setting for that in the File Explorer section.

**Comment by pancakerings** [comment]
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.
> 
> Please include any other software you have installed that modifies the UI of windows.

yeah, my bad. here it is btw

![image](https://github.com/valinet/ExplorerPatcher/assets/123368490/51cd0567-1444-4f98-b55e-eb79237e731d)
