### ISSUE TITLE
(Win 11 Build 26100.1) Program Compatiblity Assistant: This app can't run on this device 

### ISSUE THREAD

**Issue by tasnimtamim** [valinet/ExplorerPatcher#3253]
Opening ep_setup.exe shows the following error message. Disabling Program Compatibility Assistant through Group Policy did not help, neither did turning off Windows Security.  
Attached screenshot with winver
Clicking [Learn More](https://go.microsoft.com/fwlink/?LinkId=2265144) takes me straight to ExplorerPatcher GitHub page. 
![123](https://github.com/valinet/ExplorerPatcher/assets/52713990/7010781f-4de7-446b-9602-8aa3f6df8093)

**Comment by Amrsatrio** [comment]
Rename the setup exe, we have no plans of getting around this.

**Comment by lapo-luchini** [comment]
Moving the taskbar on the left of the screen no longer available on 24H2 though. :(

**Comment by tasnimtamim** [comment]
> Moving the taskbar on the left of the screen no longer available on 24H2 though. :(

You sure? Although I rolled back from 24H2, I remember still being able to move start menu to left.

**Comment by pyrates999** [comment]
24h2 doesn't have the windows 10 taskbar code anymore.
