### ISSUE TITLE
Can not uninstall

### ISSUE THREAD

**Issue by RedEd023** [valinet/ExplorerPatcher#3254]
when i click uninstall i get 

[Window Title]
C:\Program Files\ExplorerPatcher\ep_setup.exe

[Content]
Windows cannot find 'C:\Program Files\ExplorerPatcher\ep_setup.exe'. Make sure you typed the name correctly, and then try again.

[OK]

how do i uninstall this patch?

**Comment by Amrsatrio** [comment]
Disable Windows Defender realtime protection, download ep_setup.exe, rename it to ep_uninstall.exe, and execute.
