### ISSUE TITLE
Cant move taskbar to top windows 11

### ISSUE THREAD

**Issue by ziarmandhost** [valinet/ExplorerPatcher#3255]
I set here top location, but nothing changed, then I clicked restart file explorer, it blinks and nothing changed (its still at the bottom)
<img width="593" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/30569343/134c6a1d-f615-4caf-86eb-4fff1aaac913">

**Comment by ziarmandhost** [comment]
<img width="388" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/30569343/b44fed35-2e58-45db-a5b6-c9220c13662b">

**Comment by Amrsatrio** [comment]
I don't know why it never worked but you can always right click the old taskbar, unlock it, and drag it to the top

**Comment by ziarmandhost** [comment]
@Amrsatrio that worked thanks!
