### ISSUE TITLE
Windows Defender is now flagging ExplorerPatcher as high risk malware, FYI

### ISSUE THREAD

**Issue by MartijnDekkers-EI** [valinet/ExplorerPatcher#3260]

**Comment by MartijnDekkers-EI** [comment]
<img width="424" alt="Screenshot 2024-05-10 171811" src="https://github.com/valinet/ExplorerPatcher/assets/122533599/771e0525-f995-446c-95fe-cd230b588318">

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

please close this.
