### ISSUE TITLE
Windows 10 Start Menu Style Suddenly Stopped Working Today

### ISSUE THREAD

**Issue by rushk68** [valinet/ExplorerPatcher#3278]
Not sure what happened but suddenly my Start Menu reverted back to Windows 11 this morning and I can't figure out how to get it back to Windows 10.  I searched this thread and found Closed Issue #3236 and that wasn't my problem (see screenshot).  I already had those settings disabled so I'm not sure what my issue is.  Any suggestions would be greatly appreciated.  Thanks so much!

![Win 11 Start Menu Reverted Screen Shot](https://github.com/valinet/ExplorerPatcher/assets/169947133/0f28cf22-b414-4c32-882d-75a26c53834f)

**Comment by pyrates999** [comment]
Install the latest pre-release here: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by rushk68** [comment]
It must have happened automagically!  The update fixed it.  Thank you SO much, I really appreciate you and this fabulous piece of software. 🌞
