### ISSUE TITLE
Until this issue is clarified DO NOT INSTALL THIS

### ISSUE THREAD

**Issue by brockjab48** [valinet/ExplorerPatcher#3279]
ok so recently i decided to put the Explorer Patcher through triage(https://tria.ge/240516-anpxwsbh44) and it popped up a lumma, i would like to know if this is true and any fix incase it is. -brockjab

**Comment by Amrsatrio** [comment]
No it is not true. I already reported that it is a false positive but I guess they did nothing to address that.
