### ISSUE TITLE
Windows 10 Taskbar style tray icons not showing up

### ISSUE THREAD

**Issue by audiolomb** [valinet/ExplorerPatcher#3281]
I believe this started after the last round of MS Patches (May 2024).

Even though notification area icons are set to be visible (see an example below),

![image](https://github.com/valinet/ExplorerPatcher/assets/43075373/c4f6c255-2452-496d-b69e-d0245492dde5)

they do not appear in the notification area:

![image](https://github.com/valinet/ExplorerPatcher/assets/43075373/2c6bc728-d61f-4de8-b324-f39d9cf5d608)

Thank you.

**Comment by pyrates999** [comment]
Did you update to a pre-release of EP?  Did you set it to use the windows 10 taskbar instead of windows 11 taskbar?

If true to both, duplicate of: https://github.com/valinet/ExplorerPatcher/discussions/2363

please close this.

**Comment by audiolomb** [comment]
Will close.
Thank you.
