### ISSUE TITLE
Explorer Patcher Start Menu does not work.

### ISSUE THREAD

**Issue by Rob07erto** [valinet/ExplorerPatcher#3282]
Explorer Patcher Start Menu does not work.

**Comment by Rob07erto** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/48226111/04104c53-6d8e-4ada-b825-d13652a0edf5)
On this new update I recieved on windows 11, I can't access the old windows 10 start menu.

**Comment by pyrates999** [comment]
Update to the latest pre-release.  You either installed the preview windows update that was released in April, or installed the regular windows update that was released in May.

**Comment by Trojgarb** [comment]
The latest prerelease doesn't solve the problem for Windows 22631.3593.

**Comment by mustafatoktas** [comment]
I am also using version 22631.3593. Explorerpatcher works without any problems.
You can see from the picture the version of Epxlorerpatcher I use.
![Ekran görüntüsü 2024-05-16 194117](https://github.com/valinet/ExplorerPatcher/assets/52534609/ddf91c3f-f81a-4ab5-ac50-e18cdacc814b)

**Comment by Trojgarb** [comment]
I wasn't precise enough. EP works on 22631.3593, but not for Windows 10 style and options. I hope the next update will solve all problems.

**Comment by Amrsatrio** [comment]
If your EP is older than 65.1 then of course the 10 start menu wouldn't work. Install EP 65.1 or newer.

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.1_0976666

I tested it myself and it works.
