### ISSUE TITLE
Win10's calendar display without event

### ISSUE THREAD

**Issue by Latisha19** [valinet/ExplorerPatcher#3285]
Actually I downloaded ExplorerPatcher to retrieve the win10 calendar and its events to display on my win11 operating system. But don't know why, I can only show the calendar, but the events disappear. Are there any settings I'm missing?

About my notebook: Windows 11 Home 23H2, OS Build: 22631.3593

![image](https://github.com/valinet/ExplorerPatcher/assets/85289926/4cfd804e-f284-4bea-847e-566cba3b2f72)

**Comment by pyrates999** [comment]
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

If you haven't updated yet, please install this version: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.2_c245b8f

If that doesn't work, try this pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by Amrsatrio** [comment]
This feature is no longer supported because the legacy Mail and Calendar app has been superseded by the new web-based Outlook app (which is bad in my opinion). You need that legacy Mail and Calendar app to have the events view back, and I haven't found ways to prevent it from kicking you into the new Outlook app.

**Comment by Latisha19** [comment]
@Amrsatrio So until I found a way to get my old Mail and Calendar apps back, I won't be able to view events in your calendar using this app, right?

**Comment by Amrsatrio** [comment]
Yep.

**Comment by Latisha19** [comment]
So sad to hear that. Hope one day I can find something to get them back...QQ
