### ISSUE TITLE
The wrong shape of the Windows icon on the taskbar

### ISSUE THREAD

**Issue by Misha20062006** [valinet/ExplorerPatcher#3289]
The Windows button on the taskbar became the wrong color and shape when I switched the taskbar style to windows 10. I could leave the Windows 11 style, but then the description disappears from the windows open on the taskbar. What to do?
![Screenshot_1](https://github.com/valinet/ExplorerPatcher/assets/127858528/bc8003b5-847e-49a2-9b3d-a1c5fcf91917)
![Screenshot_2](https://github.com/valinet/ExplorerPatcher/assets/127858528/49c7a789-2502-445a-9c20-786c520b2583)

**Comment by pyrates999** [comment]
You have your taskbar icon size set to small I believe: https://github.com/valinet/ExplorerPatcher/wiki/All-features#taskbar-icon-size

**Comment by milesprower2293** [comment]
change your start button style to windows 10 on the windows 10 taskbar
and for the 11 taskbar use this windhawk mod:
https://windhawk.net/mods/taskbar-labels
or update your OS to the latest version
