### ISSUE TITLE
User menu unresponsive in Win10 Start Menu option

### ISSUE THREAD

**Issue by vince613** [valinet/ExplorerPatcher#3290]
When trying to switch users or log out, the user menu is unresponsive when clicking while using ExplorerPatcher's Windows 10 Start Menu.

Repro:
Install latest Windows 11 Update (22631.3593)
Install latest ExplorerPatcher version (22621.3527.65.1)
Open the start menu and click your user icon

Expected:  A menu opens with the option to sign out or switch users
Actual: No menu displays, the icon simply plays the animation for being clicked

**Comment by Trojgarb** [comment]
I have the same Windows update version and in above pre-release of EP taskbar cannot be moved to the top. Menu start look like in Windows 10, but closes with few seconds delay.

**Comment by vince613** [comment]
> Install the latest pre-release https://github.com/valinet/ExplorerPatcher/releases/download/22621.3527.65.5_6f6666b/ep_setup.exe

Thanks, didn't see that.  I'll close this out.

> I have the same Windows update version and in above pre-release of EP taskbar cannot be moved to the top. Menu start look like in Windows 10, but closes with few seconds delay.

Please make your own issue for this.  Closing.
