### ISSUE TITLE
Win 11 23H2 22631.3593 Breaks ExplorerPatcher Start Menu

### ISSUE THREAD

**Issue by Tuvalis** [valinet/ExplorerPatcher#3294]
Got a new system and ran Windows Updates which automatically installed 23H2 build 22631.3593 which broke ExplorerPatcher Windows 10 Start Menu setting. Cannot get the Win 10 Start Menu to work. Have reset default settings, uninstalled, reinstalled. Nothing works.

**Comment by pyrates999** [comment]
Install the latest pre-release of EP.

**Comment by Tuvalis** [comment]
OH! Didn't realize there was a pre-release. Installed and working fine. Thank you!
