### ISSUE TITLE
How does this work? does it uninstalls correctly? 

### ISSUE THREAD

**Issue by Himanshu-Singh-Chauhan** [valinet/ExplorerPatcher#3297]
So, I installed explorer patcher, I used it to for a bit and then wanted to uninstall, so I did, and everything is reverted back to as it was, at least it looks like it. 
I want to know whether uninstalling it completely reverts the changes it did or leaves something behind, for example I read that it changes registry and loading of dll files, so does uninstalling reverts those registry files and loading of dll. 
How does it affect the performance of windows if does not restore completely?
I am thinking to clean install windows now but it's a lot of hassle. should I do it?

**Comment by Amrsatrio** [comment]
No. You just need to delete these two reg keys if you didn't modify settings that modify Explorer's look:
- HKCU\Software\ExplorerPatcher
- HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher

Also, issues are for bug reports only.

**Comment by Himanshu-Singh-Chauhan** [comment]
thanks, sorry for asking it in issues, but discussions sections are basically dead. 
also it does not change or abuse the loading sequence of dll files, right? - https://www.reddit.com/r/Windows11/comments/zbbfxq/what_does_explorer_patcher_really_do/

thanks again.

**Comment by Amrsatrio** [comment]
It does abuse the DLL load order but only by placing files in the same folder as the exes themselves. It does not modify the registry for that.
