### ISSUE TITLE
Windows patch May 14, 2024—KB5037771 (OS Builds 22621.3593 and 22631.3593) disabling Start Button

### ISSUE THREAD

**Issue by jtvvb** [valinet/ExplorerPatcher#3301]
Windows 11 patch May 14, 2024—KB5037771 (OS Builds 22621.3593 and 22631.3593) installed automatically on my workstation late last week, and the ExplorerPatcher start menu button no longer responds. If I uninstall this patch from Windows, ExplorerPatcher starts working again. Has anyone else experience this? If so, is there a patch that I missed from Valinet?

**Comment by Amrsatrio** [comment]
First of all, what's the EP version you're running right now?

**Comment by jtvvb** [comment]
> First of all, what's the EP version you're running right now? With .3593 Windows update installed but with EP not installed, does the start menu work?

Edition	Windows 11 Pro
Version	22H2
Installed on	‎3/‎18/‎2023
OS build	22621.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

**Comment by jtvvb** [comment]
EP version 22621.1992.56.3

**Comment by jtvvb** [comment]
Looks like my EP version was way out of date. I got it updated and the problem has resolved itself.

**Comment by jtvvb** [comment]
Looks like my EP version was way out of date. I got it updated and the problem has resolved itself.
