### ISSUE TITLE
ExplorerPatcher crashing Explorer.exe on latest Windows 11 Release Preview Build 22631.3668

### ISSUE THREAD

**Issue by avenirtheavali** [valinet/ExplorerPatcher#3304]
Hello there, and I hope you are well this fine day!

I have been using ExplorerPatcher on Windows 11 ever since I found out about this project, and it's been great. I am also a part of the Windows Release Preview Channel, and about 2 days ago I updated to the Windows 11 Release Preview Build 22631.3668, and unfortunately this update has broken ExplorerPatcher. With it installed, it will crash Explorer when opening and closing the Start Menu. Sadly, this renders ExplorerPatcher completely unusable. 

Here is my current Windows build:
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎12/‎30/‎2023
OS build	22631.3668
Experience	Windows Feature Experience Pack 1000.22700.1009.0

**Comment by pyrates999** [comment]
If you're gonna run preview versions of windows, always install the latest pre-release version of EP.  Also enable updates to pre-release versions of EP when checking for updates.
