### ISSUE TITLE
Windows 11 version 24H2 PROBLEM

### ISSUE THREAD

**Issue by gaslanov** [valinet/ExplorerPatcher#3309]

**Comment by gaslanov** [comment]
<img width="346" alt="Screenshot 2024-05-23 152157" src="https://github.com/valinet/ExplorerPatcher/assets/12820534/63cc28b1-45be-4334-b992-a69f713a9109">

**Comment by Amrsatrio** [comment]
Rename ep_setup.exe to anything else. Blame MS for blocking us on 24H2.
