### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by digitalfrost84** [valinet/ExplorerPatcher#331]
This happened with 22000.318.36.1 while I was connected via rdesktop. The taskbar just went away, I tried manually restarting explorer.exe via task manager but it didn't work. Event log shows:

Faulting application name: Explorer.EXE, version: 10.0.22000.120, time stamp: 0xe846e749
Faulting module name: Explorer.EXE, version: 10.0.22000.120, time stamp: 0xe846e749
Exception code: 0xc0000602
Fault offset: 0x00000000001b6e63
Faulting process id: 0x3d1c
Faulting application start time: 0x01d7d717213f635b
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\WINDOWS\Explorer.EXE
Report Id: 832104ce-4be8-4699-847d-58086a368945
Faulting package full name: 
Faulting package-relative application ID: 

1 second later:

The shell stopped unexpectedly and explorer.exe was restarted.

1 second later:

Faulting application name: explorer.exe, version: 10.0.22000.120, time stamp: 0xe846e749
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0x20cc
Faulting application start time: 0x01d7d76a5e5468c2
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 0624aa85-60b1-4ade-a946-262a45b3dfbb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by valinet** [comment]
General directions for troubleshooting: https://github.com/valinet/ExplorerPatcher/issues/320#issuecomment-966469498
