### ISSUE TITLE
Can't install ExplorerPatcher on Windows 11 24H2

### ISSUE THREAD

**Issue by lengoc-quang** [valinet/ExplorerPatcher#3312]
## Edition
Windows 11 24H2 (build 26100.712)
## Problem
A pop-up showing when I run the setup (the latest version, `22621.3527.65.5`) and it said:
![image](https://github.com/valinet/ExplorerPatcher/assets/139666607/cab96678-25fd-46b1-a85f-a0cf686192ab)
## How to reproduce
Just update to this version and run the setup.

Please help me to install this program!
Thank you so much!

**Comment by robpomeroy** [comment]
See #3053

**Comment by pyrates999** [comment]
see here: https://github.com/valinet/ExplorerPatcher/issues/3229

**Comment by lengoc-quang** [comment]
It just restart Explorer and also not working.

**Comment by pyrates999** [comment]
this is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3229#issuecomment-2096773457

please close this.
