### ISSUE TITLE
HOW CAN I DISABLE APP ICONS FROM SHOWING

### ISSUE THREAD

**Issue by SKU003** [valinet/ExplorerPatcher#3323]
I wanted to know if there is a feature in EP where I can stop the program icons from showing because I wanted to use a dock that I will get from rainmeter, so I can have the apps at the bottom and have the taskbar at the top without the apps showing just like the macOS Menu. I'd prefer not to get a third party software because I prefer the windows looks of it using EP.

![Screenshot 2024-05-27 221037](https://github.com/valinet/ExplorerPatcher/assets/117542049/72f635fc-02ce-4043-83ed-8a1001e1a4dc)

**Comment by pyrates999** [comment]
how will you know what app you have opened if the app icon is not showing in the taskbar?

**Comment by pyrates999** [comment]
Look at windhawk.  It might be able to do what you want with one of its plugins.
