### ISSUE TITLE
The taskbar Icons don't align with the start menu icon

### ISSUE THREAD

**Issue by Elitepanther1** [valinet/ExplorerPatcher#3324]
![image](https://github.com/valinet/ExplorerPatcher/assets/168889892/0ccc5d6f-14ad-4c54-a139-d55655f7a95c)
For some reason the app icons don't want to align with the start menu icon, is like there is padding that doesn't let it go to the left

**Comment by pyrates999** [comment]
Considering the windows 10 taskbar is going away in 24h2, I don't think this will be fixed.
