### ISSUE TITLE
Bluetooth does not auto connect after EP setup

### ISSUE THREAD

**Issue by redzie** [valinet/ExplorerPatcher#3325]
Hello,
I was searching here and I cannot find the Bluetooth does not auto connect or I missed it.  If I did, please guide me to the thread.  
After connected, when I restart or turn off the mouse or game controller, I have to sync it.  Or go back to regular Win 11 taskbar, the it will auto connect.

I already re-installed EP twice.  Tried it on my other computer, same thing
Any help will be appreciated.  I will use the USB dongle for now.

Windows 11 23H2
Build:  22632.3593
Latest Patch version: I installed on 5/28/2024
No other software was install.  Except Bluetooth drive to use my mouse and keyboard.

Red

**Comment by pyrates999** [comment]
did you mean build 22631.3593?

Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by redzie** [comment]
Hello,

Yes you are correct 22631.3593
When I uninstall EP, Bluetooth connects right away, no need to re-pair each time it disconnect.
Explorer Patcher Version:  22621.3527.65.1
I did not change anything in the Property, honestly
 I don't know what to change.  Just click on it and use the way it comes.
No other software was install.  Explorer Patcher was the first thing I installed.
![EP version](https://github.com/valinet/ExplorerPatcher/assets/4544048/da53fea3-4544-4861-9b39-cc62d34c7fb8)

![01](https://github.com/valinet/ExplorerPatcher/assets/4544048/cba0cd5c-c8d6-4730-94c1-7fe363fc9acd)
![02](https://github.com/valinet/ExplorerPatcher/assets/4544048/f2e0b4ab-86e7-4db4-8202-3ee0cdb610f5)
![03](https://github.com/valinet/ExplorerPatcher/assets/4544048/dcc34650-577d-4746-85fd-c7414fc18203)
![04](https://github.com/valinet/ExplorerPatcher/assets/4544048/b5d4a5dc-a849-4674-86b2-accdafe1a6d7)
![05](https://github.com/valinet/ExplorerPatcher/assets/4544048/2dd782e8-be71-4656-8455-b4c8f3fb3ead)
![06](https://github.com/valinet/ExplorerPatcher/assets/4544048/2f77fdb2-ceb3-49b4-9698-d6c7864f19bc)
![07](https://github.com/valinet/ExplorerPatcher/assets/4544048/0744ff15-37b1-447d-85a2-df1813aa6d44)
![08](https://github.com/valinet/ExplorerPatcher/assets/4544048/a375b755-5045-4f61-b7e9-e7d145f37eab)
![09](https://github.com/valinet/ExplorerPatcher/assets/4544048/7fbd489e-ef30-40c0-8511-322aca1472b7)

Red

**Comment by pyrates999** [comment]
Try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by redzie** [comment]
Hello,

I came back from work and turn on the computer.
Back to square one.  Same issue.  
As much I love the explorer patcher to have the quick launch.  If I have to use without it to get bluetooth, then I will.
I have other devices that connect to bluetooth.

Red

**Comment by pyrates999** [comment]
Is there a reason why you don't just plug your keyboard in directly instead of connecting via blue tooth?  I understand why you have a blue tooth mouse though.

**Comment by redzie** [comment]
Really sadly upsetting with your remark question "Is there a reason why you don't just plug your keyboard in directly instead."
I have a Odin 1, v2 and v3.  I only said it at the beginning for keyboard testing.  My daily usages are my corded keyboard. All using cable connection, NO bluetooth as you assumed.  You really assume what I connect to bluetooth.  For my bluetooth connection our mouse, 2, xbox control, my surround sound speakers, bluetooth steering wheel, and bluetooth laser printer.

Does it matter what I plug in.  The problem here is that the bluetooth does not work with you ep.

Due to your remark, I will close this ticket.  I will figure out on my own.
