### ISSUE TITLE
Can't install with latest 24h2 update installed 

### ISSUE THREAD

**Issue by brunobola** [valinet/ExplorerPatcher#3327]
Can't install with latest 24h2 update installed.
Image of Microsoft blocking execution:

![image](https://github.com/valinet/ExplorerPatcher/assets/10889019/3395d8ca-e766-4ae5-931d-51d52bf4b4c1)

**Comment by pyrates999** [comment]
this is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3229#issuecomment-2096773457

please close this.

**Comment by brunobola** [comment]
@pyrates999 thanks.
