### ISSUE TITLE
EP doesn't move the taskbar on the secondary monitor

### ISSUE THREAD

**Issue by KarkanAlzwayed** [valinet/ExplorerPatcher#3328]
I can do everything else but move the taskbar to the top or any other side. The choice never changes, it always shows "bottom".
Version: 22621.3527.65.5

Windows:
Edition	Windows 11 Pro
Version	23H2
Installed on	‎5/‎24/‎2024
OS build	22631.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

**Comment by pyrates999** [comment]
If it's the windows 11 taskbar, it doesn't have options for the sides and top.  It only supports being on the bottom.

This would be something Microsoft has to implement.

**Comment by KarkanAlzwayed** [comment]
It's set to win10, not 11. The "secondary taskbar(s) location on screen" can never be set to anything else. It's stuck to "bottom"

![image](https://github.com/valinet/ExplorerPatcher/assets/49320606/da2de58e-a434-4a36-b33f-9a0f4e84bbc2)

**Comment by pyrates999** [comment]
https://www.customguide.com/windows-10/move-and-resize-the-taskbar

**Comment by KarkanAlzwayed** [comment]
What? My friend, I'm on windows 11. Those options you have in the link don't exist on windows 11.

**Comment by pyrates999** [comment]
You are you windows 11, but set it to windows 10 taskbar.  Therefore those options for unlocking the taskbar by right clicking on it should be there.  And then you can move it.

If you don't get those options when you right click on the taskbar, post a screen shot please.

**Comment by SwissAire** [comment]
Hi, I have the same issue. I can move the Primary Taskbar (i.e., to the Left), but when I try to do the same for the Secondary taskbar(s) (I have three screens in total), I can see the options to select Top, Bottom, or Right, but no matter what I select, it continues to show "Bottom (default)".
![image](https://github.com/valinet/ExplorerPatcher/assets/171324685/4b78f478-3e27-4cc4-99b0-2dd5019c5bc7)
