### ISSUE TITLE
Can't Bring up Sign-Out Options With Windows 10 Style Start Menu

### ISSUE THREAD

**Issue by Papple476** [valinet/ExplorerPatcher#3333]
Clicking my user profile in the Windows 10 style start menu doesn't do anything.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Papple476** [comment]
Windows 11 23H2 OS Build 22631.3593
Patcher Version 22621.3527.65.1
No other UI software installed
![Screenshot 2024-05-30 021631](https://github.com/valinet/ExplorerPatcher/assets/170271410/3907d6ed-6871-4c71-9c19-a395708089c3)
![Screenshot 2024-05-30 021547](https://github.com/valinet/ExplorerPatcher/assets/170271410/bba38f63-ee52-45e5-8446-91334506baa4)
![Screenshot 2024-05-30 021552](https://github.com/valinet/ExplorerPatcher/assets/170271410/3995f333-6c9a-426a-a276-9adf8fd8a904)
![Screenshot 2024-05-30 021557](https://github.com/valinet/ExplorerPatcher/assets/170271410/c55a7b81-1ec4-45ca-8951-645fb652c613)
![Screenshot 2024-05-30 021601](https://github.com/valinet/ExplorerPatcher/assets/170271410/a1eb3ab8-24a5-471d-92ac-53a9b05b3c5e)
![Screenshot 2024-05-30 021606](https://github.com/valinet/ExplorerPatcher/assets/170271410/4fa90deb-de9a-43ee-bedd-07cd2fd10144)
![Screenshot 2024-05-30 021611](https://github.com/valinet/ExplorerPatcher/assets/170271410/dfda75be-cd0d-4720-8531-3cee0f95699f)
![Screenshot 2024-05-30 021615](https://github.com/valinet/ExplorerPatcher/assets/170271410/9a75beed-0adc-43ea-9413-41c8b504ca06)
![Screenshot 2024-05-30 021620](https://github.com/valinet/ExplorerPatcher/assets/170271410/ca28f992-7bc9-4c98-8dd0-bab4588831ab)
![Screenshot 2024-05-30 021625](https://github.com/valinet/ExplorerPatcher/assets/170271410/994a1e66-e6d8-4d7b-a2f6-2977b742f6f2)

**Comment by pyrates999** [comment]
Try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

I recall this being mentioned in another issue on here and getting fixed.

**Comment by Papple476** [comment]
That worked. Thank you!
