### ISSUE TITLE
Windows version permamently spoofed by Explorer Patcher

### ISSUE THREAD

**Issue by efeme4** [valinet/ExplorerPatcher#3336]
Explorer Patcher changed my windows version from windows 11 to windows 10 enterprise and uninstalling doesn't change it back

Concretely, it changed my version to 10.0.22621.2792

**Comment by pyrates999** [comment]
that's not possible.

**Comment by Amrsatrio** [comment]
EP does not mess with your system that deep, that's all I can say.

**Comment by efeme4** [comment]
It's not something very meaningfull, windows keeps behaving like it's windows 11, but some programs like WSL2 report the windows version as 10.0.22621.2792 when running commands as wsl --version. Maybe some other program somehow changed but using EP it's the only windows tweaking i've done lately, so I can't think of any other possibility.
