### ISSUE TITLE
Disable/hide the notification icon

### ISSUE THREAD

**Issue by SwissAire** [valinet/ExplorerPatcher#3337]
Hi,

Is there an option to disable the notification icon?
![image](https://github.com/valinet/ExplorerPatcher/assets/171324685/900fbe60-5ac5-4090-b6e2-28fc495548e8)

**Comment by pyrates999** [comment]
https://www.auslogics.com/en/articles/action-center-in-windows-11/

**Comment by Amrsatrio** [comment]
Yes.
<img width="599" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/2556cfbc-d803-4edf-be56-658d454bbd3b">

And find for action center. Turn it off.
