### ISSUE TITLE
Start Icon, no more right click

### ISSUE THREAD

**Issue by DeanosT50** [valinet/ExplorerPatcher#3338]
Since the last Windows 11 update a few days ago, I have lost the ability to right click the start Icon.

Nothing happens when I do it now and sometimes it will actually crash the desktop if I try too many times.

I have always used this to quickly get to the Shut Down menu.

Not sure if it's my machine or what it is.

Thanks

**Comment by Amrsatrio** [comment]
Hi, please tell me your Windows build number found by running `winver`.

**Comment by DeanosT50** [comment]
Version 23H2 (OS Build 22631.3672)

Hope this helps.

**Comment by DeanosT50** [comment]
I found this in Pull Request..
Fix Start button context menu #2174

Very similar if not, the same issue...

**Comment by Amrsatrio** [comment]
Please try installing the latest prerelease. 65.1 has problems with getting the start button right click to work when symbols are not yet downloaded.

**Comment by DeanosT50** [comment]
Thanks. Will give it a try and let you know the outcome.
Not at my machine right now. 👍

**Comment by DeanosT50** [comment]
I didn't have the "download symbols" option enabled. Not 100% sure what this is...?

But enabled prereleases, downloaded and installed V2261.3527.65.5 and all looks to be working again.

Thanks for the help.

**Comment by pyrates999** [comment]
Unless you're running a development version of windows where symbols are included, that option should never be turned off.  Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by DeanosT50** [comment]
Thanks again. All sorted and now I almost understand... 🤣🤣

**Comment by Amrsatrio** [comment]
I have just made 65.5 the latest release so this issue that is unique to 65.2 and earlier can be closed.
