### ISSUE TITLE
Symbols fails to download after update to 22000.346

### ISSUE THREAD

**Issue by RobertSpir** [valinet/ExplorerPatcher#334]
today microsoft released new preview updates version 22000.346 and the symbols again fail to download. It seems that microsoft is not releasing symbols until the updates are released to general public

**Comment by valinet** [comment]
Yeah, it seems so. That's not necessarily bad. I know how to find the things in the DLL without the symbols as well. If you send me `twinui.pcshell.dll` and `StartDocked.dll`, I can fix it already, hopefully.

**Comment by f242** [comment]
@valinet  [pack.zip](https://github.com/valinet/ExplorerPatcher/files/7530816/pack.zip)
pass 12345

**Comment by valinet** [comment]
Thanks, I will have a look.

**Comment by valinet** [comment]
Built-in support for 22000.346 release preview has been included in the latest version. I will close this issue now, as I consider it solved.

Thanks
