### ISSUE TITLE
PSA: Windows 10 Start menu issues and quirks

### ISSUE THREAD

**Issue by vjce** [valinet/ExplorerPatcher#3340]
When I put my corner preferences on "Not rounded" it doesn't sharpen the corners. It just stays the same. Is there a way I can fix this?
![Screenshot 2024-05-31 202844](https://github.com/valinet/ExplorerPatcher/assets/169033244/c2091438-b8f2-4006-9b8d-e6abc5e71bbd)

**Comment by milesprower2293** [comment]
> When I put my corner preferences on "Not rounded" it doesn't sharpen the corners. It just stays the same. Is there a way I can fix this? ![Screenshot 2024-05-31 202844](https://private-user-images.githubusercontent.com/169033244/335763378-c2091438-b8f2-4006-9b8d-e6abc5e71bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjAzNTAsIm5iZiI6MTcxNzIyMDA1MCwicGF0aCI6Ii8xNjkwMzMyNDQvMzM1NzYzMzc4LWMyMDkxNDM4LWI4ZjItNDAwNi05YjhkLWU2YWJjNWU3MWJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwNTM0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGE4MDRiMGVjNWE2YThhMmMwODhkZDcxNTIxNGVhNWJlMjI5NzE2NTZlNzc5ODlkMGJkMWY3ZGM1YjhiNzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Nio6EOcgUBubYf1qbVGIIZGox7VCxxjs9wKGIq8NJ4)

to disable rounded corners on windows enable this option on the "Other" section
![image](https://github.com/valinet/ExplorerPatcher/assets/131640765/81a684a3-a625-4a77-9c8c-c5bf195bae22)

**Comment by vippium** [comment]
Close Issue of resolved.
