### ISSUE TITLE
Some type of weird scaling issues next to system icon area on Taskbar10

### ISSUE THREAD

**Issue by ItzExvirnity** [valinet/ExplorerPatcher#3343]
For some reason, earlier today; I noticed that the taskbar icon area was somehow broken, I do not know how to explain it, but when an icon is next to the language switcher flyout button, the icon disappears, I think it is a scaling issue, my scaling is on 110% and I use MacType, it is not an MacType issue, this does not happen on Taskbar11, I tried a virtual machine with MacType and ExplorerPatcher with the same settings and it does occur there. I hope this is a scaling issue. Also, I use 110% cause my monitor looks much better at that scaling.

Here is the About Windows:

Microsoft Windows Home
Version 23H2 (OS Build 22631.3593)

Attached file:

https://github.com/valinet/ExplorerPatcher/assets/118678848/48d423cc-3ee6-495f-ae39-6dd9400bd90a

**Comment by pyrates999** [comment]
If you changed the font to MacType, try changing it back to the default font.  This is to check if the font MacType is causing this or not.
