### ISSUE TITLE
How do i change the font in taskbar10 and fix messed up icon

### ISSUE THREAD

**Issue by Steperman5692** [valinet/ExplorerPatcher#3347]
I was wondering how can I change the font of taskbar10  and fix messed up icons
![Screenshot 2024-06-02 171649](https://github.com/valinet/ExplorerPatcher/assets/132756638/c81e8c65-47ec-4abc-b525-38189c9b198f)

**Comment by pyrates999** [comment]
https://support.microsoft.com/en-us/windows/change-the-size-of-text-in-windows-1d5830c3-eee3-8eaa-836b-abcc37d99b9a

As for the icons, that is up to the application itself that uses them.
