### ISSUE TITLE
WTF IS THIS

### ISSUE THREAD

**Issue by NDevDiscord** [valinet/ExplorerPatcher#3352]
why tria.ge says that this is password stealer? https://tria.ge/240603-t6slaadg92/behavioral1

**Comment by NDevDiscord** [comment]
oops wrong link here the real link https://tria.ge/240603-t6slaadg92/static1

**Comment by uwidev** [comment]
I also got this warning.

**Comment by JimmyJones97** [comment]
what is the issue ? its normal to have false positives.

if you look at the reason its marked like that its due to:

`Unsigned PE 1 IoCs
Checks for missing Authenticode signature.`

basically its because the setup is not signed, if you are worried just build from source and use that.

**Comment by KernFerm** [comment]
you look at the code...

**Comment by NDevDiscord** [comment]
> you look at the code...

im a python user lol

**Comment by pyrates999** [comment]
All builds of EP are done by github servers.

**Comment by KernFerm** [comment]
How the exe are built 

If you make exe in venv you won't have issue the exe will be safe to use , any one can make ep installer if you know what you are doing 

Seems that installer does some internal changes to system 

![Screenshot_20240604_081452_Chrome.jpg](https://github.com/valinet/ExplorerPatcher/assets/152947339/a31e2bba-5f72-4ea6-b7ef-f9b46dbb37e7)

That isn't good lol 
That's from the ep installer 

That installer isn't safe

**Comment by KernFerm** [comment]
Looks like a rootkit they way everything is laid out in the website that a user posted about the ep installer

**Comment by pyrates999** [comment]
where did you download the ep_setup.exe from?

**Comment by NDevDiscord** [comment]
> where did you download the ep_setup.exe from?
https://github.com/valinet/ExplorerPatcher/

**Comment by pyrates999** [comment]
Try this pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

Then right click on it and select properties.  And show the screen shot of it.

**Comment by Amrsatrio** [comment]
Nothing we can do regarding those "detections". If you do not trust this program then don't use it, easy.

**Comment by KernFerm** [comment]
[use virus total scan the exe](https://www.virustotal.com/gui/home/upload)
