### ISSUE TITLE
Wallpaper is black after about 10 minutes of the application running

### ISSUE THREAD

**Issue by XorrDev** [valinet/ExplorerPatcher#3353]
Hi, 

I came across an issue when using this application. Essentially, after about 10 minutes, my wallpaper is just displaying black.

Temporary fix: I right click the taskbar and i see restart explorer. It works for about 10 minutes before doing this again.

What could be the issue here? Thanks!
![image](https://github.com/valinet/ExplorerPatcher/assets/52389664/a0d2c4c4-22c0-4513-af3b-35948cc80aa1)

**Comment by pyrates999** [comment]
Try updating to the pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by XorrDev** [comment]
still occuring on pre-release

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  Wait for the wall paper to go black, and copy and paste the results here.

**Comment by XorrDev** [comment]
I waited about 6 hours with the console open with no results, but when i disabled the console and reloaded again, I'm having the same issue. I'm very confused, would the console have any affect on this?

**Comment by pyrates999** [comment]
Please show your wallpaper settings.

**Comment by XorrDev** [comment]
Hi,

I wanted to get back to you with an update. Looks like it was due to my wallpaper was removed from its original directory. Changing the wallpaper seemed to fix it. I guess sometimes we assume the problem is more complex than it is! 

Thanks again for your help!
