### ISSUE TITLE
If there are spaces in the exe file path, it cannot be pinned to the Start menu.

### ISSUE THREAD

**Issue by tjf1616666** [valinet/ExplorerPatcher#3356]
When there are spaces in the exe file path, it cannot be fixed to the start menu. Is this an operation performed using the cmd command,？can double quotation marks be added to the path？

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

**Comment by tjf1616666** [comment]
WIN11PRO23H2，22631.3737

**Comment by tjf1616666** [comment]
example：Photoshop2022，path：D:\software\work\PS2022\Adobe Photoshop 2022\Photoshop.exe,there are spaces in the exe file path

**Comment by pyrates999** [comment]
are you right clicking on it in the start menu and selecting pin?

**Comment by Robeok** [comment]
same issue

**Comment by Amrsatrio** [comment]
Can't repro. I can pin `C:\Users\satri\Downloads\test folder\err.exe` fine. As well as `D:\Downloads\pdbripper_win32_portable_2.03\test folder\pdbripper.exe` fine. And they open as expected too.

I know that there are some cases where Pin to Start just fails even in Windows 10, and I categorize that as Windows issue. EP is just a tool that restores them so they're out of scope of this program.
