### ISSUE TITLE
Quick Launch and Toolbars menu is gone

### ISSUE THREAD

**Issue by makaii84** [valinet/ExplorerPatcher#3358]
Hi,

I have been using Explorer Patcher to have quicklaunch toolbar. Suddenly, after a reboot today, the quicklaunch is gone, and so is the Toolbars menu from tray right-click (see attached picture).

I am running Windows 11 Pro. Explorer patcher is installed, I can access the options (attached picture_2)

What could have happened?
Thanks, Cs.

![ep_no_toolbars](https://github.com/valinet/ExplorerPatcher/assets/171696850/10663d7d-414c-499e-9593-dbb406f18797)
![ep_options](https://github.com/valinet/ExplorerPatcher/assets/171696850/110a323a-4d60-4979-be6c-3ad7aa02cbe7)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by pyrates999** [comment]
Can you also translate to english what those are on the menu when you right clicked on the taskbar?

**Comment by makaii84** [comment]
> Can you also translate to english what those are on the menu when you right clicked on the taskbar?

hi pyrates999, thank you for you time:
in english it is:
- Cascade windows
- Show windows stacked
- Show windows side by side
- Show the desktop
- Undo cascade widonws
- Task manager
- Properties
- Taskbar settings

**Comment by makaii84** [comment]
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.
> 
> Please include any other software you have installed that modifies the UI of windows.

Windows 11 Pro - built: 23H2 22631.3593
EP version: 22621.3527.65.1
No additional software is installed. We are running WithSecure Elements Agent 

thank you!

Screenshots attached for settings:
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/15ab18f9-386f-459e-b2b1-da499c4fb6d6)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/e0166513-476d-4561-a9ca-74e16aecac0f)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/9818efef-1ad4-4197-888d-d11214b59d3a)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/cdbe0781-5dc3-4200-b6b1-2f9fc2ea116e)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/aecb636a-7eeb-4381-84ed-3052fee0dbb6)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/ed6ace2f-295e-4613-af0c-fab37834dd1d)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/72c0a35c-0300-4905-8dc5-a3f7cc6449a1)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/3d10b376-3a8b-4861-9181-d3a0964bdb91)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/6374971d-987a-47ae-8058-002bc21a9d76)
![image](https://github.com/valinet/ExplorerPatcher/assets/171696850/30fc9946-7923-4b4c-bbc0-400eb7e168fb)

**Comment by pyrates999** [comment]
Try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

If the quick launch and toolbar menu's are still not showing, can you uninstall Secure Elements Agent?  And see if it shows up then?

**Comment by makaii84** [comment]
> Try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b
> 
> If the quick launch and toolbar menu's are still not showing, can you uninstall Secure Elements Agent? And see if it shows up then?

Thank you Pyrates999, the 65.5 version update fixed the problem, toolbar is back! :)

Cheers, and I am very thankful for this great app!
Cs.
