### ISSUE TITLE
Always show all icons and notifications on the taskbar

### ISSUE THREAD

**Issue by kyrcy** [valinet/ExplorerPatcher#3360]
With ExplorerPatcher (latest release and pre-release) installed in Windows 11 24H2 and under properties, customize notification area icons, no icons are listed and Always show all icons and notifications on the taskbar can no be ticked. Is this a known issue? Is there a workaround?
![Notification Area Icons](https://github.com/valinet/ExplorerPatcher/assets/171546696/0170cda1-4289-4496-8a25-200ffd3a0d05)

**Comment by pyrates999** [comment]
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by kyrcy** [comment]
Clicking on the box to tick does nothing. I tried 22621.3527.65.5 and 22621.3527.65.2 and it happens with both versions with default settings. I don't think I have any other software that modifies the UI of windows.

**Comment by pyrates999** [comment]
This looks like Microsoft has stated removing the system tray icon options for the windows 10 taskbar then.

Please wait for a developer to respond.
