### ISSUE TITLE
This app can't run on this device

### ISSUE THREAD

**Issue by kyrcy** [valinet/ExplorerPatcher#3361]
When trying to uninstall ExplorerPatcher (latest release and pre-release) in Windows 11 24H2 the message This app can't run on this device appears. How can I uninstall it?
![Program Compatibility Assistant](https://github.com/valinet/ExplorerPatcher/assets/171546696/97f7b981-806b-4711-af61-1284c6fef1c0)

**Comment by kyrcy** [comment]
I managed to uninstall by renaming ep_setup.exe to ep_uninstall.exe, but it shouldn't install anyway if there are issues.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3053

please close this.
