### ISSUE TITLE
Explorer patcher crashes when username is not english(ascii)

### ISSUE THREAD

**Issue by wjinhill0803** [valinet/ExplorerPatcher#3365]
can you support non-ascii usernames?

**Comment by pyrates999** [comment]
can you create a new username that is not in english to verify it is not something else causing it?  Please let us know what username it is that you chose to test this.

I am not asking for your current username.

**Comment by wjinhill0803** [comment]
I made two new account (english name, non-english name) and first one didn't crash but second one did. name was testacc and 테스트 .

**Comment by pyrates999** [comment]
what language is that? mandarin or Cantonese perhaps?

**Comment by 4accccc** [comment]
> what language is that? mandarin or Cantonese perhaps?

neither of them. that's korean.

**Comment by pyrates999** [comment]
ah ok.  So it must be the korean version of windows 11 then.  Or is it windows 10?
