### ISSUE TITLE
Taskbar doesn't stay on top after monitors goes to sleep mode

### ISSUE THREAD

**Issue by ChakraaThePanda** [valinet/ExplorerPatcher#3367]
- Version 22621.3527.65.1
- Running on Windows 11, OS Build 22631.3593.
- Start Menu Style: Windows 10
- Amount of Screens: 4
- Taskbar location: All the way to the right

Whenever your screens goes to sleep mode after being inactive for the set amount in your Windows settings, more often than not when you login back to your desktop, the taskbar no longer behave correctly.
It doesn't want to stay on top and instead has a "ghost", empty version of itself in the middle screen, although my taskbar is always located on my right-most monitor.

**Comment by pyrates999** [comment]
can you try the latest pre-release? https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by ChakraaThePanda** [comment]
I installed 22621.3527.65.5

I'll check back in if I don't see the bug happen after a while or if I do see it again

**Comment by ChakraaThePanda** [comment]
So, it still _happens_, but now it takes about 20-30 seconds for it to fix itself instead of having to relaunch the ExplorerPatcher manually

**Comment by pyrates999** [comment]
please take a screen shot of you mean by the taskbar of being a ghost.

**Comment by ChakraaThePanda** [comment]
So, turns out its kind of hard for me to correctly take a screenshot of the issue without showing any personal information when it happens.
If you open a new window of any program, the "ghost" sidebar disappears and goes back to normal.

So, knowing this, I will just open a new Notepad in the future when this issue occurs, and it will fix itself.

Sorry for not being able to provide more information on this.

**Comment by pyrates999** [comment]
You can blur out the personal information by editing the screen shot in paint if you need to.
