### ISSUE TITLE
taskbar showing filename next to icon for open apps

### ISSUE THREAD

**Issue by starlisa** [valinet/ExplorerPatcher#3368]
As you can see in this screenshot, the name of the page is showing to the right of the icon. This happens any time an app that's on the taskbar is open. How can I make it stop? I want only _icons_ on the taskbar.
![image](https://github.com/valinet/ExplorerPatcher/assets/36451429/1b8a6107-9907-428b-b50b-aecba1d0f674)

**Comment by pyrates999** [comment]
See answer here: https://github.com/valinet/ExplorerPatcher/discussions/1884#discussioncomment-9726454

**Comment by milesprower2293** [comment]
> As you can see in this screenshot, the name of the page is showing to the right of the icon. This happens any time an app that's on the taskbar is open. How can I make it stop? I want only _icons_ on the taskbar. ![image](https://private-user-images.githubusercontent.com/36451429/338156478-1b8a6107-9907-428b-b50b-aecba1d0f674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTgzMjQsIm5iZiI6MTcxODE5ODAyNCwicGF0aCI6Ii8zNjQ1MTQyOS8zMzgxNTY0NzgtMWI4YTYxMDctOTkwNy00MjhiLWI1MGItYWVjYmExZDBmNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzMTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZTQxMTVlYzZlNDIwNTQ2NDM4ZGUxYWMxOWZkMzkwZTAzNGU0NzhhNWQzOGU3NWZjZjdmNGFiMmY1ZTI3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P6MU6pn0CVi6dCCDbFt-pPTHva-ncpsjYc747If69mg)

right click your taskbar
open properties
click on combine taskbar icons on primary taskbar
click on always combine
