### ISSUE TITLE
Can't re-launch explorer.exe after killing the process

### ISSUE THREAD

**Issue by CrendKing** [valinet/ExplorerPatcher#337]
Another issue. Don't know if you can repro this time.

When fresh start or sign out-sign in, the explorer.exe starts fine with EP. However, if I just kill the process and restart it with Process Explorer/Hacker, it won't start. The event viewer shows this crash info:
```
Faulting application name: explorer.exe, version: 10.0.22000.120, time stamp: 0xe846e749
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0x2fe4
Faulting application start time: 0x01d7d88edf892854
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 607212dd-9c65-4958-9cfb-75dc6837797d
Faulting package full name: 
Faulting package-relative application ID: 
```
If I rename dxgi.dll at this point and start explorer.exe, it'd start.

This starts about one-two weeks ago.

**Comment by fernando-granco** [comment]
Yeah, I was about to post it, latest version has been crashing explorer a lot, sometimes after reboot it won't start at all and it takes a few tries to get the process running again. I will downgrade mine for now.

**Comment by valinet** [comment]
Builds are now automated, they may introduce regressions sometimes. It’s not intentional. I know about these issues, they have been reported elsewhere as well, I am working on some fixes and will push them as soon as ready.

Thanks

**Comment by valinet** [comment]
Hopefully the latest release addresses this issue as well. Thanks.
