### ISSUE TITLE
New UWP apps no longer show in start menu

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [valinet/ExplorerPatcher#3371]
All of the newly installed apps no longer appear in the app list in the start menu and all apps that update refuse to open. I use the Windows 10 Start menu option and uninstalling explorer patcher or disabling the Windows 10 Start menu doesn't change anything. Also if an app icon changes after an update through the store it doesn't change. Please help!

**Comment by pyrates999** [comment]
Do they work from the windows 11 start menu?

Try the steps listed here: https://www.tenforums.com/tutorials/3175-reinstall-re-register-apps-windows-10-a.html

Since they don't seem to work after you've uninstalled EP, I don't think this is a bug with EP, sorry.

**Comment by ThunderboltCommunicationsCorp** [comment]
No they don't show in the Windows 11 start menu either. But they do show in the search box and other users normally.

**Comment by pyrates999** [comment]
What if you uninstall EP?  Do UWP apps show then in the start menu?

**Comment by ThunderboltCommunicationsCorp** [comment]
Unfortunately no, from what I can tell the damage has already been done. I attempted to install EP on a VM with the latest version of Windows 11 as well and exported and applied the settings from EP in my main pc to the VM. The same happened. Upon uninstalling, nothing changes. Resetting the changes to default, nothing still.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by ThunderboltCommunicationsCorp** [comment]
I'm using Windows 11 Home 23H2 fully updated build 22631.3737, I'm running Explorer Patcher v22621.352765.5 and I know it's a pre-release, the same issue occurs in the main release. The pages I've modified are as follows:
![Annotation 2024-06-12 200120](https://github.com/valinet/ExplorerPatcher/assets/82360021/5d720fc4-be0b-4800-9be9-d2cb46af8a5b)
![Annotation 2024-06-12 200131](https://github.com/valinet/ExplorerPatcher/assets/82360021/1f51e2ab-ac28-4200-9936-ac9fe6a7d71b)

**Comment by pyrates999** [comment]
In the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

If that doesn't fix it, try this.  Please run the following in an elevated command prompt or elevated powershell:

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by ThunderboltCommunicationsCorp** [comment]
I tested the fix you gave me and got no errors (bad files). Thanks anyway.

**Comment by pyrates999** [comment]
Ok, not sure what is causing this then.

**Comment by Amrsatrio** [comment]
Still having this issue?

**Comment by Amrsatrio** [comment]
Closing due to no response and irreproducibility.
