### ISSUE TITLE
Open Start in All apps by default no longer working after Windows Update KB5039212

### ISSUE THREAD

**Issue by tomkimberlin** [valinet/ExplorerPatcher#3372]
https://github.com/valinet/ExplorerPatcher/assets/6531977/40fa1a32-3148-4e83-a3b4-d73b8247bae9

**Comment by ovalhed** [comment]
> explorer_2024-06-11_09-55-46PM.mp4

Pardon my question as a relative newbie on settings in EP, however, I viewed your display and compared it to my own computer display and I'm not seeing on my screen what you're displaying.

My current installed info:
EP settings for EP Version 22621.3527.65.1 updated 2024-06-11. 
My computer: WIn11 Pro, ver23H2,OS Build 22631.3737
Same KB5039212 update installed 2024-06-11.

Comparing to your posted mp4 file, I don't see on my computer both of the items checked that appear in your comment for start menu.

Is your mp4 post of options that used to be in EP, or are in your version of EP after running today's EP update and re-starting EP?

I'm wondering what I should be seeing today.

That said, I trust the creative coders working on EP will do their best in the coming days to correct the latest disruptions WIndows updates seem to cause each month.

**Comment by watashigoto** [comment]
Mine crashed instead, probably because I change the taskbar to windows 10 style. 

It works again after I uninstalling the update.

**Comment by tomkimberlin** [comment]
> Try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

That did the trick. Thank you!
