### ISSUE TITLE
EP 22621.3527.65.1 will not install on Win11 22H2 (22621.3737)

### ISSUE THREAD

**Issue by mtrcyclemark** [valinet/ExplorerPatcher#3376]
When I double-click the ep_setup.exe I am prompted to provide admin consent & immediately after clicking "Yes" (to provide admin consent) the whole desktop (including taskbar) goes white for 2 - 3 seconds & then the desktop returns.

**Comment by pyrates999** [comment]
What version of EP are you trying to install?

Do you have any antivirus installed that may block it?  Is this a work computer?

Open up windows event viewer or computer management
Go to Event Viewer and go to Windows Logs -> Application

Is there any entries that have ep_setup.exe in them?

**Comment by Amrsatrio** [comment]
EP is fine on 22621.3737. The installer also behaves like that. There is nothing wrong.
