### ISSUE TITLE
Properties wont open?

### ISSUE THREAD

**Issue by craxton** [valinet/ExplorerPatcher#3382]
after right clicking and hitting properties, 
it will not bring up the main window. 
it starts too, then closes. 
i checked my exclusions, and virus settings.
theyre all set to overlook explorer patcher,
and the DLL this uses (i believe its the DLL)
i tried removing it, letting virus software "pause" it
and then readding etc. nothing seems to be working.
im not sure this is a new issue, but i couldnt find 
any others with this issue, or perhaps my "wording"
in searching was not accurate. 
windows build 23h2
OS version 22631.3737

i also tried the preview build by *uninstalling* then
reinstalling again. once installed, i see no options
upon the startup of the application like i did when first installing.
https://github.com/valinet/ExplorerPatcher/assets/62484595/6c2fc1bf-4ae1-4305-87e1-9b7babb902af

**Comment by craxton** [comment]
i figured out a "work-around" hack...if you will,
it seems that the properties tab wont open by right clicking
on the task bar, but i can "search" for the properties
in search functions and open as an admin. but minus that
i tried making it run as an admin, but that still never solved the
right click issue. but at least i can view and change things.
still, i used revo to remove this completely and it still persists to be an issue.

i did leave some empty folders but i wouldnt suspect those to be issues.

**Comment by pyrates999** [comment]
to run the explorer patcher properties application, run this from the run menu:
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.

**Comment by notsureserious** [comment]
Hmm, made the change and restarted explorer - no bueno.  Maybe it's needs a reboot.  Anyway - thanks for the CMD line - that works fine :-)

**Comment by craxton** [comment]
no dice, when trying to run this it does the same thing..
the only way to open the properties section is to right click 
and run as admin on the "icon" by searching in search bar 
or setting it to run as admin. 
the properties option is available when right clicking
on taskbar, it just doesnt open. as shown in the screen recording
i showed prior.
im unsure whats happened or why this has happened. 

![Screenshot (30)](https://github.com/valinet/ExplorerPatcher/assets/62484595/09c9a91e-d15d-4411-b2d0-b26d07385f95)

**Comment by pyrates999** [comment]
Is your user a member of the group administrators?

**Comment by craxton** [comment]
yes, its an admin. its the only account.
seemingly so however, it would seem right click
now works again. upon a restart after using the run
command you gave.

**Comment by craxton** [comment]
> to run the explorer patcher properties application, run this from the run menu: `C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`
> 
> Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.

Solution ^^^^
