### ISSUE TITLE
Win10 Taskbar will bug when clicking on the Win10 start menu to close it.

### ISSUE THREAD

**Issue by jmtalec** [valinet/ExplorerPatcher#3383]
Hello,

After a resent update,
I have a problem on `Windows Feature Experience Pack 1000.22700.1009.0` (**KB5037853**)

When I click on the **win10** taskbar's **start menu button**, explorer restarts few times and the issue is not fixed.
*Note*: I am using the `aero light` cached theme on my computer.
Here's a gif describing the issue:
[https://vizysound.com/Public_Content/animate.gif](https://vizysound.com/Public_Content/animate.gif)

Yours

**Comment by pyrates999** [comment]
Try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by Amrsatrio** [comment]
I have made 65.5 the latest release a few days ago, which have fixed the issue related to start menu crashing explorer when symbols are not yet downloaded.

**Comment by jmtalec** [comment]
It works fine, thank you
