### ISSUE TITLE
Weather widget borders bugged, cut content

### ISSUE THREAD

**Issue by DRAKONIIUS** [valinet/ExplorerPatcher#3389]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/3386

<div type='discussions-op-text'>

<sup>Originally posted by **DRAKONIIUS** June 15, 2024</sup>
<img width="1180" alt="Screenshot 2024-06-14 153218" src="https://github.com/valinet/ExplorerPatcher/assets/114786355/3826202c-99b7-4af5-9261-41d9d170a8c4">
As I change the corner shape it always displays the not rounded one.
The text in the top border is cut.</div>

**Comment by pyrates999** [comment]
https://github.com/valinet/ExplorerPatcher/discussions/3386#discussioncomment-9780707

**Comment by DRAKONIIUS** [comment]
Thanks to pyrates999 > Update to the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by Amrsatrio** [comment]
I have just made 65.5 the latest release so this issue that is unique to 65.2 and earlier can be closed.
