### ISSUE TITLE
How to revert back to Windows 11 Start button?

### ISSUE THREAD

**Issue by Gigafrost** [valinet/ExplorerPatcher#339]
When downloading the Explorer patcher, I was amazed with how awesome it was to finally gain a lot of the Win 10 functionality. Excellent job to the devs!

However for the life of me, I can't find any way to simply change the Windows 10 start menu button to the flat Windows 11 one. I like the look of the Win 11 start button a lot more than Windows 10, so I was wondering... Is there an option to simply switch between the two? If not, could one be added so people like me can keep the functionality of the Patcher, while keeping the Windows 11 icon on the start button?

Thanks~!

**Comment by sisericm** [comment]
@Gigafrost 
Check this thread.
[https://github.com/valinet/ExplorerPatcher/discussions/142]

**Comment by Gigafrost** [comment]
> @Gigafrost Check this thread on the the discussions tab. [https://github.com/[/discussions/142](https://github.com/valinet/ExplorerPatcher/discussions/142)]

I'd much prefer a method without downloading third party software. I assume theres no way to change the start menu using just explorer patcher?

**Comment by sisericm** [comment]
Not at this point @Gigafrost , however Valinet has hinted that a solution may drop in a later release.

**Comment by Gigafrost** [comment]
> Not at this point @Gigafrost , however Valinet has hinted that a solution may drop in a later release.

Gotcha, thanks for offering to help! I'll give it a try then in the meantime. Hopefully the devs make this a native feature so we don't have to do these workarounds for just changing a single icon.

**Comment by valinet** [comment]
> 
> 
> > Not at this point @Gigafrost , however Valinet has hinted that a solution may drop in a later release.
> 
> Gotcha, thanks for offering to help! I'll give it a try then in the meantime. Hopefully the devs make this a native feature so we don't have to do these workarounds for just changing a single icon.

dev*

If it were that easy, I would have done it already. I also haven't been idling in the recent times too. Furthermore, it's Microsoft's product that's lacking a functionality, I like to think of everything this patcher offers as a bonus.

Thanks.
