### ISSUE TITLE
Windows 11 24H2 release candidate issues. [Version 10.0.26100.863]

### ISSUE THREAD

**Issue by Hawkeye666** [valinet/ExplorerPatcher#3391]
This morning, for a test I upgraded my Windows 11 to the Insier preview/release candidate [Version 10.0.26100.863]. I see a couple of problems so far which I assume are changes in Windows that might need to be compensated for. I uninstalled EP before running the update, and then re-installed it after. No error massages on the re-install since I had previously told Windows the setup EXE is safe. When I ran the install I got the configuration dialog and all my previous settings appeared to be in place. Enablling Dev mode, and adding EP_SETUP.EXE to the exclusions list for Defender do not help. But...

1.  The "properties" context menu options is not there when I right click on the taskbar so I cannot configure Explorer Patcher. Such as forcing an update check.

2.  Trying to run ep_setup.exe from the Program Files folder doesn't throw an error message nor do anything else. If I run it as Admin then I get..."This app can't run on this device....This app can't run because it causes security of performance issues on Windows? dialog box. There is not option to override this block, only "learn moire" and "Cancel."

I'll be rolling back the Windows 11 build for now. I just wanted to let you know about this issue. I'll be glad to help more if I can, just let me know. "Hawkeye666" Github account name.

**Comment by pyrates999** [comment]
try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.1_0976666

**Comment by Hawkeye666** [comment]
I cannot move the taskbar to the left side of the screen. Nor can I drag it anywhere. So far the only thing I see is that the file explorer and context menus are more like Windows 10 than 11. It also appears that along with whatever changed in the Windows build I canoot use Stardock's Start11V2 along with Explorer Patcher any longer, as when I have Start11 running as well then I no longer get the taskbar controls to access Explorer Patcher settings. This is strange since the same versions of Start11 and Explorer patcher work fine together on the previous build of Win11. I do not expect you to make Explorer Patcher work for me exactly the way I want. Thank you for all the work you do. This is a great utility and I only wish I could get the combo to work as I want...

I was afraid the day would come when I wouldn't be able to get my desktop to look and work the way I really want. I guess now I have to figure out what I'm going to do about it, what combination of utilities will give me the closest thing to Win 10 as I can get.

Cheers and keep up the great work.

**Comment by pyrates999** [comment]
The windows 11 taskbar doesn't support being put on anywhere but the bottom part of the screen.  This is something MS would have to implement.

**Comment by Hawkeye666** [comment]
It’s just that with Windows 11 [Version 10.0.22631.3807] all of this does work Explorer Patcher gives me the ability to move the task bar to the left side vertically when setting Taskbar style to Windows 10. But in the newer Windows 11 build this setting is no longer an option. Start11 gives me the Start Menu I like. With the newer build Start 11 allows me to move the Taskbar to the top or bottom but not to either side, and Taskbar now seems to require Windows 11 style in EP.

Like I said I understand this was just a function/feature set I had come to rely upon with the older versions. I don’t expect my special case to be sustainable.


Val Peterson


"Wisdom is the algorithm through which we pass the minutiae of our lives. The quality of this filter determines whether we are perceived as wise or otherwise. As with all data processing a failure in the system can occur because of a faulty algorithm, inaccurate data, operator error, or any combination of the three. No wonder so few are thought to be wise."

Wesley Russell Martinson, Milchtoaste; My Hometown.

**Comment by pyrates999** [comment]
The reason why you don't see that option is because in windows 11 24h2, the windows 10 taskbar code was removed.  So EP can't enable it.  Earlier builds of 24h2 did have the code still, but not later builds.

See here for more details: https://github.com/valinet/ExplorerPatcher/issues/3053

**Comment by Hawkeye666** [comment]
Understood.


Val Peterson


"Wisdom is the algorithm through which we pass the minutiae of our lives. The quality of this filter determines whether we are perceived as wise or otherwise. As with all data processing a failure in the system can occur because of a faulty algorithm, inaccurate data, operator error, or any combination of the three. No wonder so few are thought to be wise."

Wesley Russell Martinson, Milchtoaste; My Hometown.

**Comment by Amrsatrio** [comment]
Please discuss issues related to 24H2 here: https://github.com/valinet/ExplorerPatcher/issues/3398
