### ISSUE TITLE
Crashing When start button clicked

### ISSUE THREAD

**Issue by Master-Mind-Robotics** [valinet/ExplorerPatcher#3392]
I'm an insider
Edit : Fixed when updating to pre-release

**Comment by pyrates999** [comment]
try updating to the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

also wait till the symbols are done downloading: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by csolisr** [comment]
In my particular case, the app crashes altogether when attempting to download symbols (the last line I can capture before crashing is `[Symbols] Downloading symbols for "C:\WINDOWS\explorer.exe" ("d89cf953f80ba1ad267a98fe3932eaf8")...` )

**Comment by Master-Mind-Robotics** [comment]
> In my particular case, the app crashes altogether when attempting to download symbols (the last line I can capture before crashing is `[Symbols] Downloading symbols for "C:\WINDOWS\explorer.exe" ("d89cf953f80ba1ad267a98fe3932eaf8")...` )

I think I got that as well

**Comment by pyrates999** [comment]
Please try to wait until you get the notification that symbols are done downloading.

**Comment by Amrsatrio** [comment]
I have just made 65.5 the latest release so this issue that is unique to 65.2 and earlier can be closed.

**Comment by Master-Mind-Robotics** [comment]
> I have just made 65.5 the latest release so this issue that is unique to 65.2 and earlier can be closed.

Thanks
