### ISSUE TITLE
Win+X "Properties" language bug

### ISSUE THREAD

**Issue by duk6046** [valinet/ExplorerPatcher#34]
"Properties" is "속성" in Korean, but only displayed "속"

![화면 캡처 2021-10-03 094249](https://user-images.githubusercontent.com/32978164/135735594-1e5c27da-d84d-4fb1-82f6-725d9bb2899d.png)

**Comment by valinet** [comment]
The string I take from `ExplorerFrame.dll` is "Properties (Alt+Enter)" in English. I always assume there is a space before "(" and truncate at that, but in some locales that might not be the case, so I now truncate on "(" when I don't find a " " before it. Hopefully it works, thanks for pointing it out.

**Comment by BraINstinct0** [comment]
I had the same issue, but this has been solved by the new release. confirmation below.(Ninja'd issue, even better: solved before reporting!)
![image](https://user-images.githubusercontent.com/29201475/135736526-20217a28-4291-4211-944a-32b107d41cc4.png)
Also surprising to see another Korean user. The main issue might be that most Korean strings use multibyte characters.

**Comment by valinet** [comment]
No, it's not the multibyte stuff, English strings also use multibyte characters, only that just 1 byte is used, most of the time. But not really that anymore, I think emoji take 2 bytes as well, and I use those in the GUI, for example. The application is coded with multibyte strings in mind (UTF-16 LE) and uses that internally mostly, as Windows anyway uses that. Thus, everything should display properly. Whatever is taken from UTF-8 is also properly converted, or should be (the file describing the GUI is saved in UTF-8). "Modern" coding practices =))

In this instance, it was just what I said, an oversight on my part over how the string would look. To be honest, even now, an even better version would be to also take into consideration when multiple spaces might be present, but I don't think that happens in any locale (have something like "Properties        (Alt+Enter"). Plus, spaces after a work do not matter when displaying it anyway, in most cases. It is fine for now, I guess. Not a deal breaking thing either. It's good the string is localized, the menu would look out of place with one random English string in the middle of it.

Speaking about modern coding practices, the GUI is also DPI aware per monitor v2, of course.

**Comment by valinet** [comment]
@duk6046 Forgot to say, yeah, I have updated the DLL in place, please redownload from the latest same release. Sorry.

**Comment by duk6046** [comment]
Ok thanks
