### ISSUE TITLE
Not able to uninstall ExplorerPatcher

### ISSUE THREAD

**Issue by SecretGamerV071** [valinet/ExplorerPatcher#3400]
![image](https://github.com/valinet/ExplorerPatcher/assets/95269740/7192c099-7afe-4dea-88a5-5301ae99846b)
![image](https://github.com/valinet/ExplorerPatcher/assets/95269740/528616d1-8bc1-4997-862b-b08fd464a6ca)

**Comment by Amrsatrio** [comment]
Please download 65.1 and rename the setup file to ep_uninstall.exe.
