### ISSUE TITLE
ExplorerPatcher 22621.3527.65.1 destroyed "Safely Remove Hardware" menu

### ISSUE THREAD

**Issue by tomybyte** [valinet/ExplorerPatcher#3404]
v22621.2506.60.1
![grafik](https://github.com/valinet/ExplorerPatcher/assets/2370936/ff46822f-dba5-46de-b985-c2d65b95cb2a)

v22621.2861.62.1 until v22621.3527.65.1
![grafik](https://github.com/valinet/ExplorerPatcher/assets/2370936/c1498179-b099-4bed-bc82-f6c5dce95cd0)

**Comment by pyrates999** [comment]
can you try the pre-release of EP? https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by tomybyte** [comment]
@pyrates999 this version works!

v22621.3527.65.5.pre
![grafik](https://github.com/valinet/ExplorerPatcher/assets/2370936/8dcef3ec-57e4-46ba-b6fe-96185695abf5)

**Comment by pyrates999** [comment]
Great, please close this then.
