### ISSUE TITLE
Updating Program via PowerShell

### ISSUE THREAD

**Issue by LookingForWayOut** [valinet/ExplorerPatcher#3409]
Hello.

Is there a way to update the program (including those symbol messages) via Windows 11 Enterprise Powershell, instead of the ExplorerPatcher's properties option?

Thank you.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by LookingForWayOut** [comment]
Okay, okay. Some program pages on this website do not even have a discussions tab, only an issues tab, so did not notice it here. Did not think it be a discussion though since it is not a feature request but a question, but I will post a copy of this there then.
Thanks.
