### ISSUE TITLE
Weather Widget UI bug

### ISSUE THREAD

**Issue by RahulPorel** [valinet/ExplorerPatcher#3414]
Screenshot of the actual problem:

![Screenshot (831)](https://github.com/valinet/ExplorerPatcher/assets/98636266/d3fab874-0411-4054-9231-bab9fa66908f)

 I have used all default settings & I am running windows 11.

**Comment by mustafatoktas** [comment]
You can try using the latest pre-release version of Explorer patcher.

**Comment by pyrates999** [comment]
This was fixed in the pre-release of EP actually.  Please update to that: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b
