### ISSUE TITLE
Windows 10 Start Menu Is Not Displaying?

### ISSUE THREAD

**Issue by NocturnalKing** [valinet/ExplorerPatcher#3415]
Hey there guys, when I opened up the start menu the windows 11 menu was being displayed even though my settings had not been touched and was displaying the windows 10 menu up till now. Is there any issue on my end that I can fix or has there been an update that changed this? I have attached screenshots if it helps at all, thanks in advance!

![Screenshot 2024-06-22 203346](https://github.com/valinet/ExplorerPatcher/assets/49161708/a9868edd-e57c-4764-9a5b-eafac181e7b7)
![Screenshot 2024-06-22 203409](https://github.com/valinet/ExplorerPatcher/assets/49161708/1cd19701-a167-457f-ab02-23c27e964ba0)

**Comment by mustafatoktas** [comment]
Update to the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

**Comment by NocturnalKing** [comment]
Oh ok got it. Sad but not much to do about it.
