### ISSUE TITLE
Fullscreen start Menu - lack search mode

### ISSUE THREAD

**Issue by mike9ar** [valinet/ExplorerPatcher#3422]
Fullscreen start Menu It's amazing, the animation and the possibility of having the boards in full screen makes it very useful, but it lacks the possibility of searching using the keyboard like the traditional start menu. There is also no magnifying glass icon for this purpose.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.
