### ISSUE TITLE
Taskbar is transparent, can't undo

### ISSUE THREAD

**Issue by sulth1** [valinet/ExplorerPatcher#3423]
Hello,

I have read all the previous threads about the same issue. They all got the issue solved by installing the lastest update. It doesn't work for me, the taskbar is still transparent. 

Have a good day.

**Comment by mustafatoktas** [comment]
Please write the name of the Windows operating system you are using along with its build number.

Uninstall Explorer patcher completely, then restart your computer. Then install it again. If the same problem persists, please write again.

Do you use similar applications such as TaskbarX, start11, startAllBack, Windhawk or translucentTB?

**Comment by sulth1** [comment]
I am on Windows 11. 

I have tried uninstalling explorer completely, and reinstalling the last version. Same effect.

Hm... Maybe Shell Classic Explorer? Although it doesn't affect the taskbar, and there doesn't seem to be a setting related to the taskbar there.

**Comment by sulth1** [comment]
> > I am on Windows 11.
> > I have tried uninstalling explorer completely, and reinstalling the last version. Same effect.
> > Hm... Maybe Shell Classic Explorer? Although it doesn't affect the taskbar, and there doesn't seem to be a setting related to the taskbar there.
> 
> If you have classic shell installed, uninstall it. That is no longer maintained.
> 
> The replacement is open shell.

Thank you, it worked!
