### ISSUE TITLE
Some things look like 11 when they shouldn't!

### ISSUE THREAD

**Issue by mynewgithubaccou** [valinet/ExplorerPatcher#3425]
So, the search menu is still the Windows 11 one with rounded corners, the notification center is still the Windows 11 one, it should be the Windows 10 one with action center controls in there aswell, boot screen is still the Windows 11 one, should have the Windows 10 font and the position of the time and stuff in the Windows 10 spot, it should also be that we can have the Windows 10 settings app aswell as being able to choose Windows 10 wallpapers and Windows 10 boot screen  as well, it doesn't have enough things made to look like Windows 10, including paint, also, WHERE THE HECK IS INTERNET EXPLORER? Search bar also disappears when trying to search.
![Screenshot 2024-06-26 205435](https://github.com/valinet/ExplorerPatcher/assets/173901935/d2c067aa-f50e-4c60-b794-2d8313cac9cf) 
![Screenshot 2024-06-26 205424](https://github.com/valinet/ExplorerPatcher/assets/173901935/9f2c8a56-5009-4d45-9b05-6bd2ce49d320)

![Screenshot 2024-06-26 205512](https://github.com/valinet/ExplorerPatcher/assets/173901935/6af6a748-354e-455b-8bfc-ea1311928323)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by bbmaster123** [comment]
this isn't a windows 10 transformation pack...
_"This project aims to **enhance** the working environment on Windows"_

try looking more towards windhawk, that might be more what you're looking for I think

**Comment by mynewgithubaccou** [comment]
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.
> 
> Please include any other software you have installed that modifies the UI of windows.



> this isn't a windows 10 transformation pack... _"This project aims to **enhance** the working environment on Windows"_
> 
> try looking more towards windhawk, that might be more what you're looking for I think

Is that safe to use windhawk though? Like it's not a virus that could infect my $3000 machine.

**Comment by pyrates999** [comment]
Yes, windhawk is safe: https://windhawk.net

You also have installed a preview update: https://support.microsoft.com/en-us/topic/june-25-2024-kb5039302-os-builds-22621-3810-and-22631-3810-preview-0ab34e3f-bca9-4a52-a1a4-404bf8162f58

To prevent preview updates from automatically installing:

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.
