### ISSUE TITLE
cant install on W11 iot LTSC, it says this app cant run on this device 

### ISSUE THREAD

**Issue by Sparklingx** [valinet/ExplorerPatcher#3426]
![image](https://github.com/valinet/ExplorerPatcher/assets/85538352/24689137-0146-4211-8f29-5cbe51ce3740)

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/issues/3398

**Comment by exequielross** [comment]
I installed it succesfully on both, Win11 IoT Enterprise 23H2 and Win11 IoT LTSC 2024 24H2. Main difference is (as it's mentioned in the main page), 23H2 old taskbar implementation relies on native win code, and 24H2 old taskbar implementation is a reimplementation code injected by ExplorerPatcher.
