### ISSUE TITLE
Alt-Tab Duplicates Windows Playing Videos

### ISSUE THREAD

**Issue by neurokinnetix** [valinet/ExplorerPatcher#3430]
When Alt-Tabbing while playing a video on Youtube/Netflix/Amazon Prime/Etc, the same window is displayed in multiple instances when choosing which window you wish to tab into.

For example, I will have only one tab in my browser playing the video, however when alt-tabbing it shows multiple instances of the same window.

After clicking on the X button to close the additional windows, the closed window still remains within the selection of windows displayed when alt-tabbing however it no longer shows a "preview" of the window and just has a white label with the name of the last closed tab/window.

**Comment by mustafatoktas** [comment]
In which version of the operating system are you experiencing this problem?

Which version of Explorer patcher are you using?

**Comment by Amrsatrio** [comment]
A lot of information is missing here.

1. Your Windows build number found by running winver.exe (example: 22631.3737)
2. The browser you're using that is exhibiting the issues (example: Google Chrome, Firefox)
3. ExplorerPatcher version (example: 65.5)
4. Alt-Tab style being used (example: Windows 10)

Personally, I would say that it is a Windows bug as alt tab has been working perfectly on me who's daily driving 22631.3737.

**Comment by Amrsatrio** [comment]
Closed due to no response and irreproducibility on my end.

**Comment by demidgoev747-blip** [comment]
Alt-Tab дублирует вкладки, воспроизводя видео?
Тогда есть решение. другого варианты нету:

  1. Если у вас браузер (yandex, google ,brave или другие) то делаем это.
  2. Заходим в настройки браузера.
  3. Если там есть поле поиска, то вводим это: 👉 (Использовать аппаратное ускорение).
  4. Отключаем этот параметр и перезапускаем браузер.

Результат: в итоге при просмотре видео и нажатии Alt-Tab, вкладки дублироваться не будут.

❗❗ ГЛАВНЫЕ МИНУСЫ ❗❗👉 все сайты будут лагать из-за прозрачные или анимированые элементы.
