### ISSUE TITLE
If Action Center is turn off by group policy, the Clock flyout does not open

### ISSUE THREAD

**Issue by PureOcean** [valinet/ExplorerPatcher#3435]
There are two ways to turn off the Action Center icon at the far right of the taskbar.

ExplorerPatcher -> Properties -> Taskbasr -> Customize system icons... -> Action Center -> Off
or
Run on Command Prompt/Terminal or WIN+R:
1) `explorer shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}` 
2) Click to "Turn system icons on or off"

In this way, there is no problem when Action Center is turn off. (A mysterious setting that does not make changes to the Registry.)

Also Action Center is can be turn off by group policy:

`Reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v "DisableNotificationCenter" /t REG_DWORD /d "1" /f`
`gpupdate /force`

If this setting is set, the (Windows 11) Clock flyout does not open on taskbar. 

- HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ImmersiveShell
- UseWin32TrayClockExperience -> 2: Win 11 style cannot open
- UseWin32TrayClockExperience -> 0: Win 10 style can open
- UseWin32TrayClockExperience -> 1: Win 7 style can open

My OS: Windows 11 (10.0.22631.3737)
ExplorerPatcher version: 22621.3527.65.5

**Comment by pyrates999** [comment]
can you uninstall EP, and then make the changes where EP is not used to make this change?  Does it still happen?
