### ISSUE TITLE
When the taskbar is erected on the right side of the screen, The start menu will be blocked by the taskbar.

### ISSUE THREAD

**Issue by caliban511** [valinet/ExplorerPatcher#3438]
当任务栏竖在屏幕右侧时，
开始菜单会被任务栏遮挡在下面。
When the taskbar is erected on the right side of the screen,
The start menu will be blocked by the taskbar.

![Screenshot_2024-07-01-12-20-12-637-edit_org mozilla firefox](https://github.com/valinet/ExplorerPatcher/assets/13557387/0290760d-f5f1-4aa2-a9ca-19ab8fa04131)

<img width="921" alt="snipaste_20240630_005614" src="https://github.com/valinet/ExplorerPatcher/assets/13557387/1c31f86d-9941-445d-85f8-9439d3f17d14">

**Comment by Yjorch** [comment]
Same problem here. I have the taskbar in the right, and if I press once, the Start Menu goes below the taskbar, if I press a second time, the Start Menu goes above the taskbar, blocking the start menu button.

**Comment by pyrates999** [comment]
Have you thought about setting the taskbar to autohide?  Then it will only be on top when you move the mouse to it.  And you can access the stuff that would normally be behind it.

**Comment by ajcolson** [comment]
I had the same issue reported here and also found that KB5039302 needed to be uninstalled to mitigate the issue. Curiously, only when the taskbar is docked to the right of the screen does the start menu and taskbar have overlap. Everywhere else was fine even with KB5039302 installed. Just speculating, but it looked as though the position of the start menu was being drawn is closer to the edge of the screen when KB5039302 is installed.

**Comment by pyrates999** [comment]
If that's the case, then this is something for Microsoft to fix since they caused it with KB5039302.

**Comment by Amrsatrio** [comment]
Fixed in 66.4
