### ISSUE TITLE
Task Bar went blank

### ISSUE THREAD

**Issue by boppink** [valinet/ExplorerPatcher#344]
after i did the first step my taskbar completely went blank and its been that way for 10 minutes

**Comment by sisericm** [comment]
Which Win release are you on @boppink?
There is a current issue on the W11 .346 update as MS are dragging their heels releasing[ symbol files](https://github.com/valinet/ExplorerPatcher/issues/334). If you are on .314, there is an intermittent error showing up on the latest release (36.1) that can be mitigated by using an earlier release 36.0 / 35 etc.

Valinet is aware of the issues and a new release is imminent.

**Comment by boppink** [comment]
I gave up, I restarted windows hoping it would come back and it did. I got the win10 taskbar but I didn't want issues like that in the future so I uninstalled it and it went perfectly fine.

**Comment by boppink** [comment]
![image](https://user-images.githubusercontent.com/87575784/141689057-f6a52de0-3a00-422b-b869-fa23657f3045.png)

**Comment by sisericm** [comment]
For what its worth, the patcher has proved rock solid on the whole.
FYI, this [thread](https://github.com/valinet/ExplorerPatcher/issues/320) covers the issues you experienced. 
Glad its back up fine now.

**Comment by valinet** [comment]
The latest release includes mitigations for this issue. It should not happen anymore, it seemed not to manifest on my test setups. I will close this issue and the related ones, but we can continue chatting should you still encounter problems with this.
