### ISSUE TITLE
How to show just the icons of apps opened, not their names

### ISSUE THREAD

**Issue by BLANK0104** [valinet/ExplorerPatcher#3440]
Hii there,

Right now, my taskbar looks like this whenever I open any apps but ideally in windows 11, it just showed icons even when app was opened so I was wondering if it was possible to achieve that look.
![image](https://github.com/valinet/ExplorerPatcher/assets/115344345/d0ced2fb-7102-4537-a35c-af5b484fad6b)

I want this feature because my task bar looks extremely bad when i open an app with tabs, for example:
![image](https://github.com/valinet/ExplorerPatcher/assets/115344345/021f1693-a236-4999-8f3d-a774ef7dfa50)

I dont really know about how will i fix this look  but i think that only showing icons and not the names of the app may fix this.

and while I'm at it can i also know if its possible to just show the task bar on desktop and hide it whenever i open an app in full screen? i know i'm asking for a lot but if possible, please let me know

**Comment by milesprower2293** [comment]
> Hii there,
> 
> Right now, my taskbar looks like this whenever I open any apps but ideally in windows 11, it just showed icons even when app was opened so I was wondering if it was possible to achieve that look.
> ![image](https://github.com/valinet/ExplorerPatcher/assets/115344345/d0ced2fb-7102-4537-a35c-af5b484fad6b)
> 
> I want this feature because my task bar looks extremely bad when i open an app with tabs, for example:
> ![image](https://github.com/valinet/ExplorerPatcher/assets/115344345/021f1693-a236-4999-8f3d-a774ef7dfa50)
> 
> I dont really know about how will i fix this look  but i think that only showing icons and not the names of the app may fix this.
> 
> and while I'm at it can i also know if its possible to just show the task bar on desktop and hide it whenever i open an app in full screen? i know i'm asking for a lot but if possible, please let me know

Open search and type properties, open properties (explorer patcher) click on combine taskbar icons on primary taskbar and choose always combine

**Comment by BLANK0104** [comment]
thanks, your solution worked....and my last question, is there also any way to make the taskbar appear on desktop and automatically hide when i open an app in fullscreen or maximized window?

**Comment by itsjayway** [comment]
@BLANK0104 with default settings, my taskbar already automatically hides on fullscreen apps (try F12 in your browser). For maximized windows I cannot say the same...

**Comment by BLANK0104** [comment]
@itsjayway thanks for your help this far...my issue has been satisfied and now it looks much much better.... thanks
