### ISSUE TITLE
Start Menu stays open for a few seconds after close

### ISSUE THREAD

**Issue by astanciu** [valinet/ExplorerPatcher#3441]
- Open Start Menu
- Click on desktop to close it
- the contents of the menu dissapear but it leaves behind the window it occupied for 2 or 3 seconds, then that goes away too

![image](https://github.com/valinet/ExplorerPatcher/assets/1675025/cfcebf77-f3ec-48e8-bd11-8fd1f46ada68)

**Comment by Amrsatrio** [comment]
Restart Explorer after changing Start menu settings. We will have this issue fixed in the next EP update.
