### ISSUE TITLE
Searchbar for the Windows 10 taskbar apparently glitches when I open Search

### ISSUE THREAD

**Issue by golfballthegolfster** [valinet/ExplorerPatcher#3442]
![image](https://github.com/valinet/ExplorerPatcher/assets/155264247/c566bdc7-ce8f-4a77-833f-bbfc7f290a7a)

**Comment by pyrates999** [comment]
Please explain how it is glitching.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by golfballthegolfster** [comment]
![Screenshot 2024-07-03 113403](https://github.com/valinet/ExplorerPatcher/assets/155264247/79d95167-2c58-461e-9a84-cb5799d94662)
![Screenshot 2024-07-03 113409](https://github.com/valinet/ExplorerPatcher/assets/155264247/666c8f4d-9336-44d3-b9d2-1ac86e7b8fbb)
![Screenshot 2024-07-03 113413](https://github.com/valinet/ExplorerPatcher/assets/155264247/c7200503-1da9-424b-bd81-31de5de83d9b)
![Screenshot 2024-07-03 113417](https://github.com/valinet/ExplorerPatcher/assets/155264247/7d9020ab-db43-4aaa-8f2b-9845002c1bdd)
