### ISSUE TITLE
Latest release based on 62dcb98 triggers Trojan:Win32/Casdet!rfn in Windows Defender and Chrome download

### ISSUE THREAD

**Issue by uschindler** [valinet/ExplorerPatcher#3444]
It looks like the latest release based on 62dcb98 triggers the Trojan:Win32/Casdet!rfn Trojan warning. This causes update to fail when done from within the app.

If you try to manually download via Chrome, it gets blocked by Chrome, too.

**Comment by pyrates999** [comment]
If Chrome reports it blocked a suspicious file being downloaded when you try to download EP, chrome always does that with files that aren't frequently downloaded:
* https://support.google.com/chrome/answer/6261569

And Chrome provides a link to this for you to read in the download popup menu if you're interested.  Please click it next time.

I checked virustotal and only webroot is detecting this.

And github does all the builds of EP.  So it can only build from the source code that is on here.  If you want to, you can check the source code yourself.

**Comment by Amrsatrio** [comment]
> latest release

No, it is the latest prerelease.

**Comment by uschindler** [comment]
> > latest release
> 
> No, it is the latest prerelease. Also, I have pushed another commit (which means a new prerelease) which seems to be not detected yet for now.

Yes sorry for the incorrect info. It was the prerelease. The new one from today was accepted. Chrome complained, but Windows Defender not, so installation was possible.

Uwe

**Comment by uschindler** [comment]
I'll close this.

**Comment by pyrates999** [comment]
> Chrome complained

Chrome will always do that with new files that haven't been downloaded a lot.
