### ISSUE TITLE
Explorer crash after KB5039338 update

### ISSUE THREAD

**Issue by VanGHub** [valinet/ExplorerPatcher#3448]
After windows updated itself and installed KB5039338, whenever I right click on the start button to get the context menu, explorer.exe acts berserk and then crashes and ExplorerPatcher also crashes and my taskbar and start menu change back to Windows-11 default and a new Copilot icon appears at the bottom-right-hand corner of the taskbar. After restarting explorer.exe in task manager it returns to my settings, but if I right click on start button this happens again. This might have to do with the possible issues with taskbar, explained in the update page: https://support.microsoft.com/en-au/topic/june-25-2024-kb5039302-os-builds-22621-3810-and-22631-3810-preview-0ab34e3f-bca9-4a52-a1a4-404bf8162f58
Windows 11 Pro 23H2
OS Build: 22631.3810

**Comment by Amrsatrio** [comment]
Update your EP.
