### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by gjf** [valinet/ExplorerPatcher#345]
The latest version shows a notification about update, when trying to update the program dowloads somethin (showing appropriate notification again), but finishes with error:
![Screenshot 2021-11-14 220952](https://user-images.githubusercontent.com/322186/141695023-4d5d5e51-ae00-461b-ba57-7bfe767031a3.png)

**Comment by valinet** [comment]
I was doing a bit of testing for 5 minutes... try now.

**Comment by gjf** [comment]
Same. Now "Check updfates" also fails.

**Comment by valinet** [comment]
What commit is written in the release notes you downloaded? What is the exact message you get? Enable the console, look at the output in the console. Please be more verbose.

**Comment by valinet** [comment]
Also, uninstall everything and start afresh. In the first hour I had some trouble, as I said, those versions are bugged. What is now uploaded is fine.

**Comment by gjf** [comment]
Yup, seems the buggy version was installed. Sorry about that.
Will separate dxgi.dll file be released in future? Or only in installer form?

**Comment by valinet** [comment]
It's already released, just not included in "releases" so it is easier for people, newbies etc. All build files are always uploaded in the artifacts of the respective build.

For the latest build, for example, on GitHub, go to "Actions" - click the top most entry ("Fixed automatic updates; improved setup") and then you find "Artifacts". There is an archive there: "ep_bin_multi_bcc1bca_master.zip". It contains all the build files, including symbols for debugging. Those are the exact same file that are extracted by the installer. So yeah, for those wanting them, they are uploaded and always available there. In releases, I think I will only upload what is required for most users.

Thanks

**Comment by gjf** [comment]
OK then I would ask about the feature for installer: is it possible to ask user about immediate Explorer restart (present action by default) or apply uddate after reboot?
Sometimes Explorer restart leads to errors especially when active copying process is present.

**Comment by valinet** [comment]
Idk, I guess I could pop up a window... like, it should be pretty obvious to close other tasks before using this... once you place the DLL in the folder, as soon as you start a new instance, it will get loaded in memory... scheduling it for reboot is too overarching... why not update when you actually reboot, like, this only notifies you about updates when it starts, then it is up to the user to check manually during the session. So the only issue would be the initial install which after the UAC prompt just restarts Explorer, as told in the README. Yeah, idk, however you put it, some prefer it one way, some the other way...

**Comment by gjf** [comment]
Let's go here: https://github.com/valinet/ExplorerPatcher/discussions/347
I started a discussion so it would be more convenient.
