### ISSUE TITLE
Two potential malware detected in ep_setup.exe, commit 6f6666b5

### ISSUE THREAD

**Issue by hjmus** [valinet/ExplorerPatcher#3451]
Two potential malwares were detected by two vendors respectively:
- Vendor: Gridinsoft (no cloud)
  - Malware: Spy.Win64.Gen.tr
- Vendor: Sophos
  - Malware: Generic ML PUA (PUA)

Affected commit: https://github.com/valinet/ExplorerPatcher/commit/6f6666b5279f122bea300cb48c375e2e883d3ae6
But I believe the same problem existed long time ago according to Google search.

**Comment by Amrsatrio** [comment]
Yes, it has been like this since last year. This is outside of our control, so there's nothing we can do to eliminate those detections, sorry.
