### ISSUE TITLE
When using the File Explorer, the label in the taskbar is now always suffixed by " - File Explorer'

### ISSUE THREAD

**Issue by Olfdev** [valinet/ExplorerPatcher#3452]
Hello,

I think a Windows update did this, but I can't find how to get rid of it. The File Explorer label in the taskbar now have a suffix " - File Explorer".

![bEsw6T 1](https://github.com/valinet/ExplorerPatcher/assets/80658604/b8b437df-136e-4bd9-a02f-052bedc4e130)

Is there a way to remove it?

Thanks!

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Olfdev** [comment]
Hello, thanks for the answer. Here are the requested informations:

- Windows 11 version 23H2 22635.3858
- Explorer Patcher version 22621.3527.65.5

I don't have any other software that modifies the UI.

I have no idea how to change the language of EP to English so I'll wait for an answer before posting the screenshots.

**Comment by pyrates999** [comment]
how'd you make your taskbar purple?

**Comment by Themivoc** [comment]
> Hello, thanks for the answer. Here are the requested informations:
> 
> * Windows 11 version 23H2 22635.3858
> * Explorer Patcher version 22621.3527.65.5
> 
> I don't have any other software that modifies the UI.
> 
> I have no idea how to change the language of EP to English so I'll wait for an answer before posting the screenshots.

Same issue here! Windows 11 Pro, 23H2, Version 10.0.22631 Build 22631

**Comment by Olfdev** [comment]
Now my "- File Explorer" is localized (in French for me).

**Comment by pyrates999** [comment]
does this happen on the windows 11 taskbar?

**Comment by Olfdev** [comment]
Actually, I'm also using Open Shell, so I don't know:
- If it is a Win 11 update
- If it is an Explorer Patcher update
- If it is an Open Shell update

@Themivoc , do you also use Open Shell?

**Comment by pyrates999** [comment]
I'm on openshell 4.4.191.  Be sure you are on the same version.

**Comment by Olfdev** [comment]
I am indeed on 4.4.191.

**Comment by pyrates999** [comment]
Then disable or uninstall whatever you did to get the purple taskbar.

**Comment by Olfdev** [comment]
The purple taskbar is an Open Shell setting, so if you do use Open Shell as well but don't have the " : File Explorer" suffix, then we can safely say that it doesn't come from Open Shell. I could uninstall it entirely but I really don't want to mess up my configuration, my start menu, etc for such a little issue. 😥

**Comment by Olfdev** [comment]
Problem solved. This is coming from a Win11 Insider update. So we all have this soon or later. Someone just confirmed it to me:
![bKo74CH](https://github.com/user-attachments/assets/40b2b26d-2059-4060-91ba-a2d451350a64)
