### ISSUE TITLE
Taskbar does not hide window labels or show search "box"

### ISSUE THREAD

**Issue by lokanu** [valinet/ExplorerPatcher#3453]
Taskbar does not hide window labels. It does not use the native Win11 setting to hide labels, and does not have its own hide labels options, shown here:
![image](https://github.com/valinet/ExplorerPatcher/assets/174963519/b5c1703c-9a36-4af5-a640-8db9ce3f1368)

In addition to this, the search "box" doesn't work, only the icon. If you set it to search box, it remains the icon:
   ![image](https://github.com/valinet/ExplorerPatcher/assets/174963519/d619fc8d-289f-438c-946d-8ac231ce5584)

**Comment by milesprower2293** [comment]
> Taskbar does not hide window labels. It does not use the native Win11 setting to hide labels, and does not have its own hide labels options, shown here: ![image](https://private-user-images.githubusercontent.com/174963519/346359244-b5c1703c-9a36-4af5-a640-8db9ce3f1368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTI0NjcsIm5iZiI6MTcyMDM5MjE2NywicGF0aCI6Ii8xNzQ5NjM1MTkvMzQ2MzU5MjQ0LWI1YzE3MDNjLTlhMzYtNGFmNS1hNjQwLThkYjljZTNmMTM2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QyMjQyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjA0YTUwMDY2ZmEyMWVjZTIxOWViNDUwMGQ0YmY4MWE2YzE4MmE5ZTllZWU2ZGUzMmJjZmM5NTZlYjU0NTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ba-9nCyCyJzZvFdYl18b-jbEGrU1cY4Ps5HzhpR8KB8)
> 
> In addition to this, the search "box" doesn't work, only the icon. If you set it to search box, it remains the icon: ![image](https://private-user-images.githubusercontent.com/174963519/346359023-d619fc8d-289f-438c-946d-8ac231ce5584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTI0NjcsIm5iZiI6MTcyMDM5MjE2NywicGF0aCI6Ii8xNzQ5NjM1MTkvMzQ2MzU5MDIzLWQ2MTlmYzhkLTI4OWYtNDM4Yy05NDZkLThhYzIzMWNlNTU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QyMjQyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmVkNWE5ZDcyODIyOTY1YmVmOGRiOTQ3YTY5ZWExOTg4YTRmOTYzMTFmYjg3OTNhNWZjMWFlYjZhYjY1NmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7PXsII_MEDFKVXzHfcs6jj6Cc3gZ97m9LZAWCn4oWcA)

to hide taskbar labels open search and type prperties and open properties (ExplorerPatcher) then click on combime taskbar icons on primary taskbar and change "never combine (default)" to "always combine".
and for the search box wait that explorer downloads symbols and restart file explorer.

**Comment by lokanu** [comment]
Thank you, both options worked! Looks like there needs to be an asterisk on the "Search:" option; restarting Explorer did the trick.

**Comment by milesprower2293** [comment]
> Thank you, both options worked! Looks like there needs to be an asterisk on the "Search:" option; restarting Explorer did the trick.

the searchbox requires symbols on to show up 22H2+, when there are no symbols or some symbols for explorer the searchbox is not going to work
