### ISSUE TITLE
Search hiding itself when i click start button

### ISSUE THREAD

**Issue by A-Cloud-maker** [valinet/ExplorerPatcher#3454]
pls fix this and also add win10 search

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 144527](https://github.com/valinet/ExplorerPatcher/assets/175002212/fbc983bf-5f18-4bbe-a739-8171b7e47ad4)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 144738](https://github.com/valinet/ExplorerPatcher/assets/175002212/b0f4597a-2c5b-42a5-9a63-b638eea54ec1)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 144854](https://github.com/valinet/ExplorerPatcher/assets/175002212/4a849c00-e480-431d-810e-b89be9f10c60)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145014](https://github.com/valinet/ExplorerPatcher/assets/175002212/40e71366-d7c9-474f-8d2b-1cd285a8ce99)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145038](https://github.com/valinet/ExplorerPatcher/assets/175002212/810b40b3-0bff-43d8-b6ef-14b01f3f172f)

**Comment by A-Cloud-maker** [comment]
![Uploading Screenshot 2024-07-08 145056.png…]()

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145056](https://github.com/valinet/ExplorerPatcher/assets/175002212/bfd0f7a4-0809-4674-ad6f-2607ff0ae235)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145116](https://github.com/valinet/ExplorerPatcher/assets/175002212/57b270a6-6c00-414a-8251-129cef7f56f6)

**Comment by pyrates999** [comment]
did it happen after you installed this preview update? https://support.microsoft.com/en-us/topic/june-25-2024-kb5039302-os-builds-22621-3810-and-22631-3810-preview-0ab34e3f-bca9-4a52-a1a4-404bf8162f58

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145136](https://github.com/valinet/ExplorerPatcher/assets/175002212/4a8df554-e60f-4178-8ad3-d018c3843a78)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145151](https://github.com/valinet/ExplorerPatcher/assets/175002212/2dbb5e1a-5831-4cfe-9259-1d8cbae59e94)

**Comment by A-Cloud-maker** [comment]
is this enough information or do u want more

**Comment by A-Cloud-maker** [comment]
if u wont respond then more it is

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145210](https://github.com/valinet/ExplorerPatcher/assets/175002212/8325935c-c7db-4205-9aaa-d67ca4c9d917)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145229](https://github.com/valinet/ExplorerPatcher/assets/175002212/1badb762-d71a-4c7d-ae09-d4b2afc0b6ef)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145244](https://github.com/valinet/ExplorerPatcher/assets/175002212/408078d9-ffdf-46b2-b852-6d89562bfc1f)

**Comment by A-Cloud-maker** [comment]
![Screenshot 2024-07-08 145306](https://github.com/valinet/ExplorerPatcher/assets/175002212/29dc1e1e-3e56-470e-bf0e-b3016d92b6c7)

**Comment by pyrates999** [comment]
I did respond.  Please check.

**Comment by A-Cloud-maker** [comment]
oh brother, THESE MODS STINK!

**Comment by Amrsatrio** [comment]
ok

**Comment by A-Cloud-maker** [comment]
you gonna fix it now?

**Comment by A-Cloud-maker** [comment]
or make a new program that is called "ExplorerPatcher fixer"
