### ISSUE TITLE
After restarting PC or locking and logging back in, the taskbar icons are misaligned and duplicated.

### ISSUE THREAD

**Issue by kimutaku001** [valinet/ExplorerPatcher#3458]
I am using version 22621.3527.65.5, system version Windows 11 Pro.
Version: 23H2
Installation date: 2024/7/2
OS build: 22631.3593
Experience: Windows Feature Experience Pack 1000.22700.1003.0
![image](https://github.com/valinet/ExplorerPatcher/assets/5381853/83afd9ad-c3bb-476b-b15b-1e641bd46934)
Restarting the plugin fixed it.

**Comment by kimutaku001** [comment]
On a side note, I'm using multiple monitors

**Comment by pyrates999** [comment]
I think this has already been submitted as an issue: https://github.com/valinet/ExplorerPatcher/issues/2788
If so, please close this.

**Comment by kimutaku001** [comment]
> I think this has already been submitted as an issue: #2788 If so, please close this.
ok, thx

**Comment by kimutaku001** [comment]
equals #2788
