### ISSUE TITLE
Is Explorer Patcher infected?

### ISSUE THREAD

**Issue by mustafatoktas** [valinet/ExplorerPatcher#3459]
I don't think it's likely, but could Explorer patcher have a virus?

In windows 11 home 23H2 22631.3672 version, windows defender caught the trojan virus as seen in the picture. The affected item appears to be ep_setup.exe.

Does anyone have any information about this?

EP version: 22621.3810.66.1

![Ekran görüntüsü 2024-07-09 104644](https://github.com/valinet/ExplorerPatcher/assets/52534609/8899a7ca-b22c-4f11-926b-968581ce8b22)

**Comment by Amrsatrio** [comment]
No, it is a false positive.

**Comment by Amrsatrio** [comment]
https://www.reddit.com/r/StableDiffusion/comments/11vtmyn/windows_defender_threat_defender/

**Comment by VarunAgw** [comment]
Same with Avast. Never happened in the past but only today when trying to update

**Comment by Amrsatrio** [comment]
In this update I am introducing a new DLL which is 2.4 MB big, which is the reimplemented taskbar. That might be the reason, it takes a bit of time till it gets well known and reputable.

**Comment by pyrates999** [comment]
And all builds of EP are done by github servers.  So you can check the source code yourself to verify :)

**Comment by Amrsatrio** [comment]
@pyrates999 Not anymore when the taskbar is included. I cannot open source that without getting a DMCA or some sort, although I really want to.

**Comment by VarunAgw** [comment]
@pyrates999 It's not about trust.

Getting anti-virus warning is really annoying for everyone. No one likes a software which gets false positive.

**Comment by mustafatoktas** [comment]
You are thinking wrong. There is really a great effort behind the EP application. I don't care if it's a false positive situation. This app gives me everything I want.

**Comment by pyrates999** [comment]
Well I hope you open source it because the other alternative is for someone to buy the software StartAllBack.  I don't see how you can get a DMCA claim though since it would be your own code.

**Comment by Amrsatrio** [comment]
No, the logic is not. It is Microsoft's.

**Comment by Amrsatrio** [comment]
66.1 ep_setup.exe is no longer detected as Casdet. Closing this issue.

**Comment by mustafatoktas** [comment]
I am using EP's 66.1 ep_setup.exe version. Windows Defender detected Casdet as a virus in this version.


![Ekran görüntüsü 2024-07-10 153435](https://github.com/valinet/ExplorerPatcher/assets/52534609/55024d32-dbac-482e-a373-3d3efc00bfba)

**Comment by Amrsatrio** [comment]
Update your definitions, I updated mine and downloaded 66.1 with no problems.

**Comment by mustafatoktas** [comment]
Thank you ✅
