### ISSUE TITLE
The start menu apperas under the takbar

### ISSUE THREAD

**Issue by vbickov** [valinet/ExplorerPatcher#3462]
This happened after the last update (7/9/2024). When the taskbar is on the right side, the start menu actually appears under the taskbar. See attached snapshot:

![task-bar-start-menu](https://github.com/valinet/ExplorerPatcher/assets/49466977/30354e3b-ec3c-47aa-bbfd-ee9acbbf9537)

**Comment by vbickov** [comment]
Thanks.

**Comment by shadowdreamer** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/4878501/c9c936c1-066c-48ee-b854-f0988713c79b)
save issue with win10 style start menu,thanks

**Comment by Amrsatrio** [comment]
A new prerelease build with the fix is being built now.
