### ISSUE TITLE
Windows 10 taskbar glitch

### ISSUE THREAD

**Issue by randomidiot2887** [valinet/ExplorerPatcher#3468]
My issue is that I have a 2 in one. When I select windows 10 taskbar, it’s fine until I rotate my display to tablet mode and back. Then the icons are too much spaced. Also want it to hide in tablet mode and show in laptop mode. I still use the win 10 start menu with win 11 taskbar. Please try to fix this

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2684

**Comment by Amrsatrio** [comment]
I have a Windows tablet, in which I can try to fix this and test my fix on. The fix will be only in the Windows 10 (ExplorerPatcher) taskbar. Don't worry.

**Comment by Amrsatrio** [comment]
Please update EP and use Windows 10 (ExplorerPatcher) taskbar. It doesn't have enlarged buttons when the keyboard is detached.
