### ISSUE TITLE
Unable to install on Windows 11 IoT Enterprice LTSC eval

### ISSUE THREAD

**Issue by Maor545** [valinet/ExplorerPatcher#3470]
When installing on Windows 11 IoT Enterprice LTSC eval build 26100
windows show error message
`Program Compatibility assistant
This App cant run on this device

This App cant run on this device because it causes security or performance issues on Windows
`

**Comment by milesprower2293** [comment]
> When installing on Windows 11 IoT Enterprice LTSC eval build 26100 windows show error message `Program Compatibility assistant This App cant run on this device
> 
> This App cant run on this device because it causes security or performance issues on Windows `

rename the ep_setup

**Comment by Maor545** [comment]
works!!!
