### ISSUE TITLE
Explorer crashes when hitting win+tab with Windows 10 EP Taskbar Style

### ISSUE THREAD

**Issue by hecknt** [valinet/ExplorerPatcher#3471]
I was able to replicate this on both Windows 11 22631.3737 and 22631.3880 with ExplorerPatcher 22621.3810.66.1

Whenever you set the taskbar style to Windows 10 (ExplorerPatcher) and disable the Show Task view button option and restart explorer, and you hit Win+Tab to bring up the task view screen, explorer crashes within a few seconds. From my testing, this only happens when:
- The Taskbar Style is set to Windows 10 (ExplorerPatcher)
- The Start button style is set to Windows 11
- The Task View Button is not shown

Here's a video:

https://github.com/user-attachments/assets/ec7fe7ba-4f61-417d-9000-28d43588794b

**Comment by Amrsatrio** [comment]
Reproduced this issue. I will fix this in the next prerelease.
