### ISSUE TITLE
Windows 10 Start menu won't launch in the lastest Canary build 26252

### ISSUE THREAD

**Issue by chuck00000** [valinet/ExplorerPatcher#3472]
Windows 10 Start menu won't launch in the latest Canary build 26252, Although I put "StartUI.dll" to the "C:/Windows/ SystemApps/ StartMenuExperienceHost_cw5n1h2txyewy", It won't launch the Windows 10 Start Menu, The Win10 Start menu worked before Canary 26252.

It seems Microsoft changed something again.

**Comment by pyrates999** [comment]
Canary builds are not supported because the code is not final and can change with each new release.

**Comment by Amrsatrio** [comment]
Yeah. They nuked StartUI resources out of that build. The only way to make it work again is to use it with old pri files loaded through hooks that existed in older versions of EP.

Also, I don't want to make Windows 10 start menu on 24H2 really apparent as a feature yet so sorry if I close this.
