### ISSUE TITLE
Win + X doesn't work with Win11 22631

### ISSUE THREAD

**Issue by Lgb1962** [valinet/ExplorerPatcher#3475]
Since Win11 updated to 22631.3880, Win + X no longer works for me (it produces no result) with EP 22621.3527.65.1, Win10 Taskbar set to Vertical/Left.

**Comment by Amrsatrio** [comment]
Please wait until symbols have finished downloading.

**Comment by Amrsatrio** [comment]
1. Are you using any other tweak software?
2. Are you using Windows 10 or Windows 10 (ExplorerPatcher) taskbar?

**Comment by plofhaan** [comment]
I am running EP **22621.3810.66.1** on 22631.3880 with the Win10 taskbar set to Horizontal/Bottom. It's working fine for me on 2 different laptops, but in recent months it can happen that either EP cannot download the new symbols or it cannot download some of the new symbols. Simply choosing to reboot again always fixes it, though, at least if the new symbols have already been published by Microsoft.

**Comment by Lgb1962** [comment]
For me, the EP update dialog updated to 22621.3527.65.5, which fixed the glitches I was seeing.

**Comment by pyrates999** [comment]
> I am running EP **22621.3810.66.1** on 22631.3880 with the Win10 taskbar set to Horizontal/Bottom. It's working fine for me on 2 different laptops, but in recent months it can happen that either EP cannot download the new symbols or it cannot download some of the new symbols. Simply choosing to reboot again always fixes it, though, at least if the new symbols have already been published by Microsoft.

Being unable to download symbols sounds like an issue with your windows installation.
