### ISSUE TITLE
Pre Version 22621.3810.66.1 has issues with Win 11 Pro 24H2 26120.961

### ISSUE THREAD

**Issue by CloudeLecaw** [valinet/ExplorerPatcher#3477]
![14-07-2024_08-33-47](https://github.com/user-attachments/assets/36140113-08d6-4597-ab4e-5bbeb1bc41bc)

When i update to version 22621.3810.66.1 the Settings windows does not open anymore.
a white windows opens for a secound and than it disapears.

Interesting part: When 22621.3810.66.1 was installed i noticed also my Windows Settingsmenue just shows me a blank white site.
Now i downgraded to 22621.3527.65.5 what fixed the issue and all is normal aggain.

i tried it 3 times with same result.
a restart of the OS didnt solved it too when 22621.3810.66.1 was installed

**Comment by CloudeLecaw** [comment]
sloved because the issue allready exist in #3461

**Comment by sigmallyx** [comment]
How did you do the downgrade?

**Comment by CloudeLecaw** [comment]
i took the setup from last version and reinstalled
(i got the setup file still in the hdd, and only delet them after i made sure an other version fixed it)

well download latest 66.1 the issue is solved in it.

the current latest has a new issue if your on a latest Windows preview 24h2 version. the Settings option on rightclick is not there anymore, but i still uograded because i can call it from the settings link in the Windows startmenue

**Comment by CloudeLecaw** [comment]
> How did you do the downgrade?

i took the setup from 22621.3527.65.5 and reinstalled.
(i got the setup file still in the hdd, and only delet them after i made sure an other version fixed it)
(by the way..this is what you call a backup) ;)

well download and use latest prev version now because the issue is solved in it.
(i am also using the german settings)

the current latest has a new issue if your on a latest Windows preview 24h2 version. the Settings option on rightclick ib the taskbar disapeared, but i still upgraded because i can call it from the settings link in the Windows startmenue.
(havent testens if a full reinstall might help, because the Upgrade to latest Windows prev was like a whole setup, might this broke something...i will report my result later, so no urgent case to report for the moment...)
