### ISSUE TITLE
please fix this in a new update

### ISSUE THREAD

**Issue by microm98gittthub** [valinet/ExplorerPatcher#3479]
the option to put taskbar on top of the screen is available, but it does not work
you can put in top in the properties settings but not working
![image](https://github.com/user-attachments/assets/2c311ae4-d649-44ad-acfc-b926d7ddd5eb)
![image](https://github.com/user-attachments/assets/f16afdad-f443-409a-b3de-f1a313005210)

additional: does the app automatically get updated when  you add smt new?

**Comment by milesprower2293** [comment]
> the option to put taskbar on top of the screen is available, but it does not work you can put in top in the properties settings but not working ![image](https://private-user-images.githubusercontent.com/175564440/348569170-2c311ae4-d649-44ad-acfc-b926d7ddd5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTQzMTQsIm5iZiI6MTcyMDk5NDAxNCwicGF0aCI6Ii8xNzU1NjQ0NDAvMzQ4NTY5MTcwLTJjMzExYWU0LWQ2NDktNDRhZC1hY2ZjLWI5MjZkN2RkZDVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQyMTUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDg0Yjg2ZmJhNDk1MDAzMmFlMGQ5N2QxNWFjNDI2YWQxYjhiMTA2OWQxZmY5Yzg0YjRkMDIxNjQwZjdjOTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3FV4l6WV9Hus5AkrDcU26wEHYB-AHkt3njueHvIvSPQ) ![image](https://private-user-images.githubusercontent.com/175564440/348569195-f16afdad-f443-409a-b3de-f1a313005210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTQzMTQsIm5iZiI6MTcyMDk5NDAxNCwicGF0aCI6Ii8xNzU1NjQ0NDAvMzQ4NTY5MTk1LWYxNmFmZGFkLWY0NDMtNDA5YS1iM2RlLWYxYTMxMzAwNTIxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQyMTUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YThjMmFjYmIxNDVlMjJiMmEyZGVlZmUzMWZkZDk2OGNiNTQ5NThmYTllZjJjNzM4Y2Y2MzU5ZGRjYWU4Y2RlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.52__4dhv1OxeLsS1eoGhQQ17IvmHEbjXGpt1yQTVwl4)
> 
> additional: does the app automatically get updated when you add smt new?

you have to restart explorer or unlock the taskbar and drag the taskbar to the top
