### ISSUE TITLE
Windows 10 Startmenü don't work since update to OS Version 22635.3930

### ISSUE THREAD

**Issue by Freschnek** [valinet/ExplorerPatcher#3481]
Windows 10 Startmenü don't work since update to OS Version 22635.3930. I've tried the stable and latest pre-release 22621.3810.66.1 version of Explorerpatcher. With the pre-release, the Preferences Windows will not pop up.

**Comment by pyrates999** [comment]
You're running an insider preview build: https://blogs.windows.com/windows-insider/2024/07/12/announcing-windows-11-insider-preview-build-22635-3930-beta-channel/

Windows 10 start menu and taskbar are no longer accessible in this build.

Try updating to the latest pre-release if you want the windows 10 taskbar still. Not sure if it has the system tray implemented, and there is a known bug where settings doesn't work: https://github.com/valinet/ExplorerPatcher/issues/3461

**Comment by Amrsatrio** [comment]
Sorry, referred to the wrong issue. Anyways,

![image](https://github.com/user-attachments/assets/dd961d56-ab7e-4765-a63d-ea2e725200fe)

Some files need to be placed in C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy so please give me some more time to prepare stuff up.

**Comment by Freschnek** [comment]
I'm back on a stable operating system version, everything works again now.

**Comment by Amrsatrio** [comment]
Fixed. A new prerelease version with this fix is being built right now.
