### ISSUE TITLE
switching between dark/light mode, the Start button and search button icons disappear (Taskbar10)

### ISSUE THREAD

**Issue by Corporation001** [valinet/ExplorerPatcher#3486]
As title, after switching between dark/light mode in Windows, the Start button and search button icons disappear on Taskbar10.
![image](https://github.com/user-attachments/assets/46bdfe84-2773-467c-b7fc-af136d80c0f5)
Needs to restart Explorer.exe to solved.
![image](https://github.com/user-attachments/assets/f9f13567-f013-4523-a87e-94c608765061)
![image](https://github.com/user-attachments/assets/4a7fb911-099a-449f-baf0-ce2b7e77f927)
EP Setting : Taskbar Style : Windows 10 (ExplorerPatcher)
Windows Ver : Windows 11 22H2 (Build 22621.3380)
EP Ver : 22621.3810.66.1 (Latest)
Thank you!

**Comment by Amrsatrio** [comment]
This should be fixed in the next prerelease, the issue is that I forgot to cache the icon scale when the theme refreshes.

**Comment by Corporation001** [comment]
> This should be fixed in the next prerelease, the issue is that I forgot to cache the icon scale so that when the theme refreshes it reads the last scale as 0, therefore nothing is visible.

thank you for your support!

**Comment by Corporation001** [comment]
Fixed in the latest build.
