### ISSUE TITLE
Windows 10 Style Win+Tab Desktop Switcher

### ISSUE THREAD

**Issue by abhigyan2001** [valinet/ExplorerPatcher#3490]
The Windows 11 Task View Desktop Switcher (Win+Tab) is quite slow and laggy to open and to switch to other desktops, and the Windows 10 Task View used to work like a dream.

Would it be possible to update the Task View to use the old Windows 10 Style Task View, where the desktops are displayed at the top and the open applications are all shown below that?

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by milesprower2293** [comment]
> The Windows 11 Task View Desktop Switcher (Win+Tab) is quite slow and laggy to open and to switch to other desktops, and the Windows 10 Task View used to work like a dream.
> 
> Would it be possible to update the Task View to use the old Windows 10 Style Task View, where the desktops are displayed at the top and the open applications are all shown below that?

The windows 10 taskview can't be restored on 22H2+
