### ISSUE TITLE
[Win10 taskbar in Win11] Setting any notification area icon to always visible crasher Explorer

### ISSUE THREAD

**Issue by Shassk** [valinet/ExplorerPatcher#3492]
Exactly what the title says. Because of this all icons are hidden now and I can't control it unless I switch back to Win11 style.
Latest EP version (just updated)(persisted in several older ones since late May at least).
Taskbar configured to Win10 style + never combine + top position.
Windows 11 Home 22631.3593 with ReviOS configured (thought it might be important).
If any additional info/testing from me is needed just tell me which one.

**Comment by pyrates999** [comment]
You're windows version is from May: https://support.microsoft.com/en-us/topic/may-14-2024-kb5037771-os-builds-22621-3593-and-22631-3593-e633ff2f-a021-4abb-bd2e-7f3687f166fe

Please install updates for windows first.

EP is only tested against the latest windows version.

**Comment by Shassk** [comment]
>You're windows version is from May

Then what a coincidence the latest EP version was released exactly 1 day after that.

>EP is only tested against the latest windows version.

Is it tho?
Release notes state the opposite:
```
Tested on OS builds
22621.3296, 22621.3447, 22621.3527, 22635.3566, 26058.1000, 26120.461, and 26200.5001.
(Note: 22621 and 22631 share the same OS files)

```
Which also mentiones my 22631 version.

>Please install updates for windows first.

Not to mention same release notes state this:
```
Taskbar10: The Windows 10 taskbar option is now no longer available on 26002+
```
Which won;t help me solve the problem in any way.

**Comment by pyrates999** [comment]
Please install latest windows updates before I'm able to help.

**Comment by Shassk** [comment]
I repeat: how am I supposed to install "latest updates" if they disable this function entirely?

**Comment by pyrates999** [comment]
Uninstall EP and then install latest windows updates.

**Comment by pyrates999** [comment]
For setting the system tray icons, you can drag and drop the icon in the system tray to the popup menu that you don't want shown.

If this is what you're talking about, it is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

please close this.

**Comment by Shassk** [comment]
It is indeed, thanks.

**Comment by Shassk** [comment]
Worked just fine
