### ISSUE TITLE
Windows 11 transfer dialog cut off

### ISSUE THREAD

**Issue by ntzb** [valinet/ExplorerPatcher#3494]
Hi, using Explorer Patcher 22621.3527.65.1, on Windows 11 22H2 build 22621.1848
sometimes, the explorer file transfer GUI element gets buggy, and the right part is cut off:
![image](https://github.com/user-attachments/assets/9b8bfcef-deb0-415a-b78a-a171193159e3)
is this a known issue? any solutions?

also sometimes, the wifi network list has blank names (can still choose to connect to a network, just don't know which one it is).

restarting explorer.exe solves both of these issues

**Comment by pyrates999** [comment]
Your windows version is from June of last year: https://support.microsoft.com/en-us/topic/june-13-2023-kb5027231-os-build-22621-1848-8f903600-1293-4431-9c6b-736a4049666c

Please install the latest windows updates.

**Comment by Amrsatrio** [comment]
Please update your system and try to see if this problem persists when EP is not installed. EP does not modify the file transfer dialog if you don't have "Always use legacy file transfer dialog" enabled.
