### ISSUE TITLE
Conflict with Alt drag while using SimpleWindowSwitcher

### ISSUE THREAD

**Issue by SupLiCatinG** [valinet/ExplorerPatcher#3497]
As i mentioned in the title i cant use both of them, i want to add SimpleWindowSwitcher to Alt Drag's process blacklist. May i ask the process name of SimpleWindowSwitcher?

**Comment by Amrsatrio** [comment]
SimpleWindowSwitcher runs in explorer.exe.

**Comment by SupLiCatinG** [comment]
Thanks, it works as intended while using default one but i found *|MultitaskingViewFrame on blacklist is there any other identifiers for SimpleWindowSwitcher?

**Comment by SupLiCatinG** [comment]
it was SimpleWindowSwitcher_{BEA057BB-66C7-4758-A610-FAE6013E9F98}, also alt snap (which is fork of alt drag) includes this as pre-included blacklist.
