### ISSUE TITLE
After the software is uninstalled, there are many garbled characters in Chinese!!!

### ISSUE THREAD

**Issue by suheng1921** [valinet/ExplorerPatcher#3502]
I wanted to change the size of the Windows 11 taskbar, so I installed ExplorePatcher. After installation I didn't find the feature I was looking for, so I uninstalled it.
After the software is uninstalled, there are a lot of Chinese garbled characters, including the desktop file Chinese name garbled characters, the region setting Chinese garbled characters, the task manager Chinese garbled characters and so on..

How should I solve these garbled codes ?

<img width="605" alt="ExplorerPatcher版本信息" src="https://github.com/user-attachments/assets/1ced2e12-53c3-4283-a8b9-9999e0e44586">
<img width="193" alt="桌面文件中文名称乱码" src="https://github.com/user-attachments/assets/93efea5b-522e-4e69-84e2-1a3bc62b7c83">
<img width="312" alt="区域设置中文乱码" src="https://github.com/user-attachments/assets/1bde6b06-b4fd-4d67-9578-41c231b92e9b">
<img width="823" alt="任务管理器内容中文乱码" src="https://github.com/user-attachments/assets/89aba470-c8e4-42ee-9f0d-df1b21dc8f0a">

**Comment by Amrsatrio** [comment]
You seem to be using a modded font, which is outside of our supported usage scenarios.
