### ISSUE TITLE
LOVE YOU BRO

### ISSUE THREAD

**Issue by onlinejo** [valinet/ExplorerPatcher#3503]
GO DONATE !!!!!!!!!!!!!!!!!!!!!!!!!!!!! 

https://www.paypal.com/donate?business=valentingabrielradu%40gmail.com&no_recurring=0&item_name=ExplorerPatcher

https://ko-fi.com/amrsatrio

**Comment by Amrsatrio** [comment]
Yeah, thanks and all, but this isn't the place for this.

**Comment by onlinejo** [comment]
=)
