### ISSUE TITLE
Network tray does not show in the system tray in Taskbar10 (EP)

### ISSUE THREAD

**Issue by w4lll** [valinet/ExplorerPatcher#3507]
The network tray does not show in Taskbar10 (EP) and the network tray is greyed out in "Customize system icons in the notification area". However, the network tray is shown when using StartAllBack. Is there any fix for this? Currently running on Windows 11 24H2.
![taskbar10epnonetworktray](https://github.com/user-attachments/assets/b8761694-d559-4ce3-bb27-85cef93728c5)

**Comment by milesprower2293** [comment]
Microsoft removed the network button from the legacy system tray because they have been removing the 10 taskbar on 24H2

**Comment by Amrsatrio** [comment]
pnidui.dll will be bundled with EP in a future release.

**Comment by Amrsatrio** [comment]
Fixed in 66.4
