### ISSUE TITLE
Defender flags Explorer Patcher files while updating as a trojan (Backdoor:Win32/Bladabindi!ml)

### ISSUE THREAD

**Issue by IoveBread** [valinet/ExplorerPatcher#3511]
![Ekran Görüntüsü (43)](https://github.com/user-attachments/assets/baa42ab4-5099-4350-8536-5fbc558c66ef)

**Comment by ArashShiri** [comment]
Was just about to add this as an issue, but also got this now 
![image](https://github.com/user-attachments/assets/95e6eeab-8c68-47dc-a74c-d78290e05b2b)

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.
