### ISSUE TITLE
Explorer crashes after a while when trying to right click icons on the taskbar

### ISSUE THREAD

**Issue by Dave1482** [valinet/ExplorerPatcher#3514]
Explorer crashes after a while when trying to right click icons on the taskbar when set to either Windows 10 implementations when the taskbar is set to be on top

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Assuming your version is 22635.39xx

Temporary solution: Use vivetool to disable `40874676`. This looks like a punishment from Microsoft to those who use the classic taskbar.

**Comment by Amrsatrio** [comment]
Closing due to irreproducibility, lack of details, and no response.

**Comment by Dave1482** [comment]
Sorry, couldn't respond til now
Windows 11 Pro 23H2
22631.3958
Latest pre-release of ExplorerPatcher

**Comment by Dave1482** [comment]
@Amrsatrio 
@pyrates999

**Comment by Dave1482** [comment]
[ExplorerPatcher_22621.3880.66.3.zip](https://github.com/user-attachments/files/16421408/ExplorerPatcher_22621.3880.66.3.zip)
Might as well have the full settings file in there

**Comment by pyrates999** [comment]
Please do not tell us you have the latest pre-release without telling us the version of it.

Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Dave1482** [comment]
22621.3880.66.3

I can get you screenshots when I'm home, but both the Windows 10 and the Windows 10 (ExplorerPatcher) modes have this issue for me

I don't have any other programs that mess with how Windows looks

**Comment by Dave1482** [comment]
nevermind, it started working somehow lol, but here are my settings anyways

![Screenshot 2024-07-30 181231](https://github.com/user-attachments/assets/36e94de7-82c7-4157-ba88-fbc207e93308)
![Screenshot 2024-07-30 181328](https://github.com/user-attachments/assets/7f0fbfa6-9312-43d3-88a0-e37b230125fd)
![Screenshot 2024-07-30 181321](https://github.com/user-attachments/assets/1ca2efe9-f949-4849-90bf-58dd7298f77e)
![Screenshot 2024-07-30 181311](https://github.com/user-attachments/assets/2412e027-87fe-47a1-9728-a3fcbd814cc3)
![Screenshot 2024-07-30 181254](https://github.com/user-attachments/assets/7391af95-10aa-4278-b011-c440a8676afa)
![Screenshot 2024-07-30 181250](https://github.com/user-attachments/assets/db12f94d-cfe8-4fce-9c26-2ff4763699d0)
![Screenshot 2024-07-30 181245](https://github.com/user-attachments/assets/563e7ef1-a4bc-4b97-8725-b9086f2f1101)
![Screenshot 2024-07-30 181242](https://github.com/user-attachments/assets/4c3856ab-52c3-4d9e-bd2b-9edbe3b9126a)
![Screenshot 2024-07-30 181239](https://github.com/user-attachments/assets/51685bad-9a35-49b5-b2e1-8c9e183804f0)
![Screenshot 2024-07-30 181235](https://github.com/user-attachments/assets/8d4f2435-b11b-48f5-8c7a-0ca476c1d232)

**Comment by pyrates999** [comment]
Ok, glad to hear it :)
