### ISSUE TITLE
Search box is invisible after opening start menu

### ISSUE THREAD

**Issue by Usernamamama** [valinet/ExplorerPatcher#3518]
**Isue**
After install and opening start menu search box is invisible _I am spanish_

example:
![image](https://github.com/user-attachments/assets/168d6b5b-e65f-4387-973f-4b625b6aeb38)

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3107

please close this as this isn't planned to be fixed due to windows 11 24h2 removing the windows 10 start menu code entirely.
