### ISSUE TITLE
ExplorerPatcher Properties not displayed after update

### ISSUE THREAD

**Issue by BraINstinct0** [valinet/ExplorerPatcher#352]
Been using it without any issues 'till 22000.346 update.
Updated ExplorerPatcher to 22000.318.37.1.

After that, the 'options' showed from right-clicking is missing.
![image](https://user-images.githubusercontent.com/29201475/141703612-bbe8c432-cd2a-44c6-a5d3-b97b7e520913.png)
(Apologies for interface being in Korean, I can confirm that the settings is missing from it. It should be '속성', but isn't there.)

Note: (as always) my AV interfered with both the installation and un-installation. However I don't think this is the issue, as I flagged it as safe, uninstalled, rebooted and reinstalled it.

**Comment by BraINstinct0** [comment]
Note that it shows as 22000.318.37.1 in installed apps.

**Comment by valinet** [comment]
> 
> 
> Been using it without any issues 'till 22000.346 update. Updated ExplorerPatcher to 22000.318.37.1.
> 
> After that, the 'options' showed from right-clicking is missing. ![image](https://user-images.githubusercontent.com/29201475/141703612-bbe8c432-cd2a-44c6-a5d3-b97b7e520913.png) (Apologies for interface being in Korean, I can confirm that the settings is missing from it. It should be '속성', but isn't there.)
> 
> Note: (as always) my AV interfered with both the installation and un-installation. However I don't think this is the issue, as I flagged it as safe, uninstalled, rebooted and reinstalled it.

Not an issue. Please read the long text in the release notes and the new README as well:

![image](https://user-images.githubusercontent.com/6503598/141703962-6a5154fd-530e-47da-9985-8d65f1b38dd5.png)

> 
> 
> Note that it shows as 22000.318.37.1 in installed apps.

So, what's wrong about that?

**Comment by BraINstinct0** [comment]
Yes I noticed it - but it was already checked(did not touch that option before testing).
However un-checking and checking it simply solved it.

To summarize:
1. Option enabled before update
2. Win+X not showing it after update
3. taskbar - right-click - Properties show 'Add shortcut to...' as enabled.
4. un-checking and checking makes the option appear in Win+X menu.

**Comment by valinet** [comment]
> Yes I noticed it - but it was already checked(did not touch that option before testing).

This was actually a bug, I fixed it. Thanks.

**Comment by Ainz-00al-G0wn** [comment]
Yeah i don't have the opting in either Win+X or right click...
