### ISSUE TITLE
Combine taskbar icons option doesn't function on Windows 10 (EP) taskbar

### ISSUE THREAD

**Issue by hecknt** [valinet/ExplorerPatcher#3525]
Tested on 26100.1301 and 22631.3880

Regardless of what you set the Combine taskbar icons option to on the Windows 10 (EP) taskbar, it will always function the same as the "Always combine" option does on the standard Windows 10 taskbar.

**Comment by Amrsatrio** [comment]
Set the option through the Settings app for now.

**Comment by PeaceByJesus** [comment]
See https://ramensoftware.com/7-taskbar-tweaker/comment-page-54#comment-14811

**Comment by Amrsatrio** [comment]
Fixed in 66.7. It is now being built.
