### ISSUE TITLE
Taskbar is show in front of the Start menu

### ISSUE THREAD

**Issue by Eccenux** [valinet/ExplorerPatcher#3533]
Steps to reproduce:

1. Move the main taskbar to the right.
2. Open the Start menu.
3. Observe that the Start menu appears below the taskbar. Screen below.

BTW. Is there a way perhaps to change z-index of the taskbar to always be on the bottom (haven't found an option for that).

![screen](https://github.com/user-attachments/assets/5d71bee8-a64d-4ca1-8395-23eb27b1ef99)

Similar issue for other menus (True Lanuch Bar)
![obraz](https://github.com/user-attachments/assets/2309341d-e77b-4cca-93f0-35156c2e80b0)

**Comment by Amrsatrio** [comment]
This one is fixed in the 66.4 pre-release. I cannot turn that into a release yet because Defender is still flagging it right now.

**Comment by Eccenux** [comment]
That works much better! Thanks :-)
![Start menu fixed](https://github.com/user-attachments/assets/6027fc48-0eff-4602-88ea-936e197d4386)

This fixed it:
![ExPatcher menu](https://github.com/user-attachments/assets/3153946c-e336-487b-9643-083c9ea361e0)

BTW. ESET Antivirus doesn't have a problem with the exe file nor with the dll :-)

Also, in case anyone looking for a True Lanuch Bar / Free Lanuch Bar solution, you have to change TLB Settings (disable overlap):
![TLB options screen](https://github.com/user-attachments/assets/558095a2-ee93-4cf6-b55c-d562bd7f027b)
