### ISSUE TITLE
System Tray Not Showing All Icons

### ISSUE THREAD

**Issue by dbman86** [valinet/ExplorerPatcher#3534]
Using w/ Win 10 taskbar.  reinstalled Win 10 and then upgraded to win 11, and now all the icons in the system tray are not showing.  When I uninstall EP and use Windows 11, it works.  

in EP settings I went to "customize system icons in the notification area" but it doesn't seem to work.

how can I get EP to just show all the system tray notification icons like I was able to before?

thank you
 
![image](https://github.com/user-attachments/assets/02334e67-611d-416a-bad9-48a6fd7fb8d1)

**Comment by pyrates999** [comment]
You can drag and drop the icon in the system tray to the popup menu that you don't want shown.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this.
