### ISSUE TITLE
weather icon

### ISSUE THREAD

**Issue by CHAFAN2** [valinet/ExplorerPatcher#3535]
so.. the weather menu is kind of weird suddenly because there is a google thingy. i cant explain it but i hope u understand
![image](https://github.com/user-attachments/assets/8df29fa8-897b-4f55-a755-880608f5bcd0)

**Comment by pyrates999** [comment]
Try going through this guide: https://github.com/valinet/ExplorerPatcher/wiki/Weather

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2767
