### ISSUE TITLE
Windows 10 styled Start menu has no animation and freezes for 3 seconds

### ISSUE THREAD

**Issue by Comeonnoob** [valinet/ExplorerPatcher#3536]
Explorerpatcher version - 22621.3527.65.5
Windows version - 11 23H2 22631.3958

Windows 10 styled start menu no longer has a proper open animation, only the contents inside of it animate, and it freezes for like 3 seconds when trying to close it.
I also tried to change between docked or floating start menu to check if that's the reason

https://github.com/user-attachments/assets/8bdf1259-b1e6-4b03-b837-4ba67327c238

**Comment by pyrates999** [comment]
I believe this was fixed in a pre-release.  Please try installing the latest pre-release of EP.

**Comment by milesprower2293** [comment]
> Explorerpatcher version - 22621.3527.65.5 Windows version - 11 23H2 22631.3958
> 
> Windows 10 styled start menu no longer has a proper open animation, only the contents inside of it animate, and it freezes for like 3 seconds when trying to close it. I also tried to change between docked or floating start menu to check if that's the reason
> 
>  Recording.2024-08-06.003829.mp4

Restart Windows explorer to fix that issue

**Comment by Comeonnoob** [comment]
> Restart Windows explorer to fix that issue
Restarting fixed it, thanks!
No need to waste time with pre-release ExplorerPatcher
