### ISSUE TITLE
custom icons for shortcuts disappear?

### ISSUE THREAD

**Issue by RabidLime** [valinet/ExplorerPatcher#3537]
bit of an odd one...

- W11 Enterprise
- W11 Start Menu on screen edge
- pinning things to start has a 50/50 chance that any set custom icon will disappear

pretty certain it's explorer patcher, but installing it makes custom icons for shortcuts disappear in the start menu. i have custom icons for the shortcuts, and change them via Properties > Shortcut > Change Icon. but after running ExplorerPatcher, those icons disappear. reassigning the icons doesn't fix anything, and the icon only disappears in the start menu - right clicking on start menu shortcut > open file location... opens the the icons in an explorer window and they show up normally.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Pinning to Start from Explorer has always been unstable and unpredictable, even on Windows 10. We can't do anything about it.
