### ISSUE TITLE
search menu is wrong

### ISSUE THREAD

**Issue by CHAFAN2** [valinet/ExplorerPatcher#3539]
idk how to explain but the search menu is still the win 11 one how i get the windows 10 search menu 
![image](https://github.com/user-attachments/assets/f5fb918e-ac95-4321-ae64-8d4c00d59de1)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

**Comment by CHAFAN2** [comment]
ok il post it

**Comment by CHAFAN2** [comment]
![image](https://github.com/user-attachments/assets/cb69cceb-3c88-43ce-87d3-6b447b306e4d)

**Comment by Amrsatrio** [comment]
Not possible to get the 10 search menu back on 11.
