### ISSUE TITLE
With 24H2 the windows 10 audio flyout doesn't appearing

### ISSUE THREAD

**Issue by MM275** [valinet/ExplorerPatcher#3542]
windows 11 24H4 build 26100.1301
ExplorerPatcher prerelease version 22621.3880.66.4

**Comment by pyrates999** [comment]
you installed a preview update: https://support.microsoft.com/en-au/topic/july-30-2024-kb5040529-os-build-26100-1301-preview-89f3ad4f-a5fe-4065-b217-01e622133ca1

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by Amrsatrio** [comment]
When you click the notification center button, does the notification center flyout appear? We cannot reproduce your issue using the same build as yours.

**Comment by MM275** [comment]
> When you click the notification center button, does the notification center flyout appear? We cannot reproduce your issue using the same build as yours.

yes, the notification center appear

**Comment by MM275** [comment]
> you installed a preview update: https://support.microsoft.com/en-au/topic/july-30-2024-kb5040529-os-build-26100-1301-preview-89f3ad4f-a5fe-4065-b217-01e622133ca1
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.
> 
> You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.
> 
> Does the audio flyout using the windows 10 version work, if you uninstall this preview update?

i don't use this, but i'm in insider beta

**Comment by MM275** [comment]
> you installed a preview update: https://support.microsoft.com/en-au/topic/july-30-2024-kb5040529-os-build-26100-1301-preview-89f3ad4f-a5fe-4065-b217-01e622133ca1
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.
> 
> You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.
> 
> Does the audio flyout using the windows 10 version work, if you uninstall this preview update?

i cannot uninstall the last update (the  last update is the installation of windows 11 24H2)

**Comment by pyrates999** [comment]
Open up task manager and kill explorer.exe and then run task manager again and run explorer.exe.  If that doesn't fix it, reboot.

If that doesn't fix it, remember the settings you used in the EP properties application.  Then in the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

**Comment by Amrsatrio** [comment]
A new 26100 build has dropped. Still cannot open the audio flyout?

**Comment by Amrsatrio** [comment]
Closing due to no response and irreproducibility.
