### ISSUE TITLE
Microsoft Defender recognizes ExplorerPatcher as dangerous software

### ISSUE THREAD

**Issue by stardepp** [valinet/ExplorerPatcher#3544]
Microsoft Defender recognizes ExplorerPatcher as dangerous software:

![Windows-Sicherheit-stgru 07-08-2024 11_04_56](https://github.com/user-attachments/assets/7d3c98be-f8d9-440f-a23b-32c05e23faf9)
![Windows-Sicherheit-stgru 07-08-2024 11_03_18](https://github.com/user-attachments/assets/f5aae5f5-9087-4207-b26a-b731df72fd17)
![Threat description search results - Microsoft Security Intelligence - Vivaldi-stgru 07-08-2024 10_52_37](https://github.com/user-attachments/assets/69688765-ddf1-43d8-bbf5-32f56533a3cc)
![Windows-Sicherheit-stgru 07-08-2024 10_52_26](https://github.com/user-attachments/assets/3343d483-ab7c-45fe-a372-1e3908018da8)
![-stgru 07-08-2024 10_51_34](https://github.com/user-attachments/assets/74ea4bd7-a3fc-4052-b402-6ed7877eb859)

However, I was able to deactivate this warning.

This post serves as information for other users and the DEVELOPER

Best regards stardepp

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

You can also set windows defender to exclude the following:
1. C:\Program Files\ExplorerPatcher
2. %APPDATA%\ExplorerPatcher

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

**Comment by stardepp** [comment]
@pyrates999 Many thanks for this tip. But how exactly do I activate it in Windows Defender?

**Comment by pyrates999** [comment]
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by Amrsatrio** [comment]
There is nothing we can do. They don't like us, not even appealing to their security response team would do anything. Sorry that things have to be this way, they kept nuking more stuff so that we have to go wild on the patches.

**Comment by Amrsatrio** [comment]
More on this:
https://github.com/valinet/ExplorerPatcher/issues/3228
