### ISSUE TITLE
No weather option available 22621.3880.66.4 EP

### ISSUE THREAD

**Issue by minhgi** [valinet/ExplorerPatcher#3546]
I selected taskbar with explorerpatcher and weather options isn't available.  Is there feature no longer an option?

**Comment by Amrsatrio** [comment]
Yeah, for now. The weather feature relies on the now deprecated people button and needs a lil bit of rearchitecting to make it working again.

**Comment by minhgi** [comment]
Thanks for the update

**Comment by Amrsatrio** [comment]
I'd say this should be better be left open to remind me about it in the future.

**Comment by minhgi** [comment]
Hehe.  Thanks for reminder.  I reopened.

**Comment by Amrsatrio** [comment]
![image](https://github.com/user-attachments/assets/d0eb36ab-ac17-405b-afb3-c0643ac0b37e)
I gotchu.

**Comment by minhgi** [comment]
Thank you very much for your work. MS always break thing and you have to go patch them. Lol 😂

**Comment by minhgi** [comment]
Please closed the ticket if you feel it have been full filled.

**Comment by Amrsatrio** [comment]
I'll close this once a release build containing this feature has been published. I still have some more urgent stuff in my todo list for next version. One being unable to pin to the taskbar by dragging an icon to it.

**Comment by pyrates999** [comment]
I should point out that I do have a weather option when I open the EP properties application, but I can't click on it to enable weather:

![image](https://github.com/user-attachments/assets/a88c9af6-7c4d-4f4b-a843-9f2e74227de1)

**Comment by fesarlis** [comment]
Same here. However the reason for this post is that I have a confusion regarding this widget and if it is the same as 'News and interests'. In my case the news widget appears properly (as weather icon) and it shows the big news window (which I don't know if can be customised). Is your weather widget totally different from the news widget?
W10 19045.5011 / EP 22621.3880.66.6.

**Comment by pyrates999** [comment]
News and Interests is what MS includes in windows 10.

**Comment by Amrsatrio** [comment]
Fixed in 66.7. It is now being built.

**Comment by minhgi** [comment]
Thank you.. You rẻ the best. Prefer the win10 layout compare win11. Ugh
