### ISSUE TITLE
Smaller spaces between tray icons.

### ISSUE THREAD

**Issue by ItzExvirnity** [valinet/ExplorerPatcher#3547]
It is pretty self explanatory. The spaces between tray icons are smaller. 

ExplorerPatcher:
![image](https://github.com/user-attachments/assets/644726a7-0473-46ea-8bb8-7fed59e948ed)

Windows 10:
![image](https://github.com/user-attachments/assets/ad8c4039-92e4-4aa9-8101-fd261aa33077)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by pyrates999** [comment]
you got a preview update installed: https://support.microsoft.com/en-us/topic/july-25-2024-kb5040527-os-builds-22621-3958-and-22631-3958-preview-de3e1e24-0c07-4210-9777-8e03a1446bae

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

You also enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

And try switching the taskbar to **windows 10 (Explorer Patcher)**, not **windows 10**, as that **windows 10** one is Microsoft's implementation of it.

**Comment by pyrates999** [comment]
> ![image](https://private-user-images.githubusercontent.com/118678848/356304363-a8269c41-09fa-4d3d-aeca-6d6e2bbf1b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjMxNzUsIm5iZiI6MTcyMzE2Mjg3NSwicGF0aCI6Ii8xMTg2Nzg4NDgvMzU2MzA0MzYzLWE4MjY5YzQxLTA5ZmEtNGQzZC1hZWNhLTZkNmUyYmJmMWIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMDIxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWQxNWUxNWY4MjMwODNjMGM5MDgyYTEzYTdjZDdhMzVhMzg2MzRlZjE3NjczMDk2NjExNjU0ZmJmZDEwMmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6kBQyJrtHIUGTyNi8i7UzfRnkorNny-s2MyybQrhKt4) And I don't even have insider set up

You don't have to have insider setup to get preview updates.  But with that off, you will now only be prompted to install them.  Do not install them unless you prefer installing pre-releases of EP and needing to file bug reports on here for any bugs that were found.  If you don't mind doing that, then we appreciate it.

And did you untick **Register as shell extension** in EP properties application?

**Comment by milesprower2293** [comment]
> > > It is pretty self explanatory. The spaces between tray icons are smaller.
> > > ExplorerPatcher: ![image](https://private-user-images.githubusercontent.com/118678848/356227584-644726a7-0473-46ea-8bb8-7fed59e948ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDkyNDEsIm5iZiI6MTcyMzE0ODk0MSwicGF0aCI6Ii8xMTg2Nzg4NDgvMzU2MjI3NTg0LTY0NDcyNmE3LTA0NzMtNDZlYS04YmI4LTdmZWQ1OWU5NDhlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQyMDI5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmFjNDBkMjhlZDkwNzI1ZWNkNmZlYjA4NTE1NmY2MjhlZjE0ZDgxOGNjMTY2ZjMwN2U1NDliNGE0OWMxZTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Eu-SGLiPERFYBazMFi9-S3h6EEsy87rPf4jd3PcFLT4)
> > > Windows 10: ![image](https://private-user-images.githubusercontent.com/118678848/356229157-ad8c4039-92e4-4aa9-8101-fd261aa33077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDkyNDEsIm5iZiI6MTcyMzE0ODk0MSwicGF0aCI6Ii8xMTg2Nzg4NDgvMzU2MjI5MTU3LWFkOGM0MDM5LTkyZTQtNGFhOS04MTAxLWZkMjYxYWEzMzA3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQyMDI5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTMxZmQ0MzhiNTBlNTQ4YTZlZWFhYTJmMGFmYjcyZDM0MjJhYzdiOTI2YWIxY2VmZDM3ZDViYTc5NmIzZWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.51ehj8BaAEEiT1DC89C_qEPgeaa7ImPBFVr-cBiTMTA)
> > 
> > 
> > your example on how the windows 10 tray icons look like is how those look on tablet mode
> 
> The thing is that... it's not on tablet mode.

there are 2 types of tablet mode on WIndows 10
the first one is the one that you can enable from the action center / settings app
and the second one is the one that enables when your device has a touch screen that make some things of the taskbar wider like the pinned / opened programs (Taskband) and the system tray

**Comment by Amrsatrio** [comment]
Not a bug.
