### ISSUE TITLE
Win 10 Start menu left side hidden behind taskbar

### ISSUE THREAD

**Issue by MarcusBoswijk** [valinet/ExplorerPatcher#3548]
I have the taskbar and start menu in the windows 10 style and on the left side of my screens.
When opening the start menu the left side of the menu is hidden behind the taskbar (Profile and Power menus)
If i restart the explorer the menu pops out to the right so it is not hidden 1 time but then it breaks again and it is behind the taskbar until i click on an empty part of the menu to bring it to the top.
Either the start menu should always move so it is not behind the taskbar or it should be on top instead of behind the taskbar.

**Comment by pyrates999** [comment]
Please show screen shot of what you mean.  You can blur out any personal info that is shown like your username.

**Comment by MarcusBoswijk** [comment]
As you can see the start menu is under the taskbar until i click on the start menu.
https://i.imgur.com/pkvHlG2.png
https://i.imgur.com/zHI1n29.png
I have noticed it only starts doing this if i used the start menu on any of my non primary screens.
As long as i only use the start menu from my primary screen it works finelike this:
https://i.imgur.com/Y7PusKJ.png
Where the whole menu is shifted to the right.
But if i open the start menu on any other screen(start menu also on left side of screen) then it breaks on all screens untill i restart File Explorer.

**Comment by Amrsatrio** [comment]
Latest prerelease has it fixed but it has been flagged as malware by MS. Check the releases page for instructions on how to install the latest prerelease.

https://github.com/valinet/ExplorerPatcher/releases
