### ISSUE TITLE
Time and date missing from systray and other important icons

### ISSUE THREAD

**Issue by AndyIreland** [valinet/ExplorerPatcher#355]
while using this the Time and date missing from systray and other important icons and I cannot select small taskbar buttons they are too huge - do you reckon I have installed it right? 
![win 11 taskbar no clock](https://user-images.githubusercontent.com/49172217/141708648-40ac1150-2b77-4f89-90ed-131b22e8f12e.jpg)

Am using it on windows 11

**Comment by valinet** [comment]
Please use discussions, why is this an issue?

To enable system icons, refer to https://github.com/valinet/ExplorerPatcher/discussions/354

Taskbar buttons can be adjusted by right clicking taskbar - Properties and its right there on the main page among the options: "Taskbar icon size".

Please read the README and check the configuration window. Thanks.
