### ISSUE TITLE
Constantly notifying to update to the current installed version?

### ISSUE THREAD

**Issue by k-basara** [valinet/ExplorerPatcher#3560]
Title basically says all.
Using version 22621.3527.65.5 on Windows 10, the notification will appear after user login.
![epatch](https://github.com/user-attachments/assets/0eb31e27-fc48-4ada-8089-8b1b4f6b5659)

**Comment by pyrates999** [comment]
In the EP properties application, please go to **Updates** and show the settings you're using with a screen shot of it.

**Comment by k-basara** [comment]
> In the EP properties application, please go to **Updates** and show the settings you're using with a screen shot of it.

Here is my update settings. I think I didn't change these.
![epatch2](https://github.com/user-attachments/assets/cf1c72cb-a80d-4c5e-940c-df4528f25826)

**Comment by pyrates999** [comment]
those settings seems to be ok.

Lets check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

Then copy and paste the output from it here when windows shows a notification that there is a new release of EP.

**Comment by k-basara** [comment]
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Using hardcoded hash.
[Updates] Checking against hash "22622.3527.65.5.86649ef60f89750b"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.3527.65.5.4dc5c4ef26f8e30b" (valid).
[Updates] Local version obtained from hash is 22622.3527.65.5.
[Updates] An update is available.

**Comment by Amrsatrio** [comment]
Are you running the latest 65.5 downloaded from the releases page?

**Comment by k-basara** [comment]
> Are you running the latest 65.5 downloaded from the releases page? There may be several "65.5" EPs released.

Maybe not, my setup file was downloaded at July 1st. Just gave a look at the release section, the newest setup file was released 2 weeks ago with the same version number.

**Comment by Amrsatrio** [comment]
Yeah that explains it.

**Comment by k-basara** [comment]
> Yeah that explains it. Please install that version.

But if I click the update notification, it leads me to the May 15 release (marked as Latest in green).

**Comment by pyrates999** [comment]
So then you download that version and install it.
