### ISSUE TITLE
Jump list not working

### ISSUE THREAD

**Issue by Steperman5692** [valinet/ExplorerPatcher#3562]
I have notice that jump list aren't working when I right-click on an app in Taskbar10.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Steperman5692** [comment]
Windows: Windows 11 64-bit Build 22631.4037
ExplorerPatcher Version: 22621.3527.65.5
ExplorerPatcher Settings:
![image](https://github.com/user-attachments/assets/57880f86-f57b-4662-bcd7-63fa81c1c8e1)
![image](https://github.com/user-attachments/assets/8098c63a-f6d4-4a3c-a861-cce374314ae2)
![image](https://github.com/user-attachments/assets/4552f0b6-8d24-42dd-94a8-6b8692f4ed16)
![image](https://github.com/user-attachments/assets/f3a4707f-758d-4009-9c05-76b8bb382fa0)
![image](https://github.com/user-attachments/assets/af93cdeb-1193-4435-bb7b-cec9ab2c527d)
![image](https://github.com/user-attachments/assets/7dcf4362-3a65-4525-a77a-d1e974bf696d)
![image](https://github.com/user-attachments/assets/31999100-fe76-4644-a6fd-fcd87d39ef4e)
![image](https://github.com/user-attachments/assets/a465d0f7-9ddb-440e-bf76-c0078e36739a)
![image](https://github.com/user-attachments/assets/7c63dc67-9c4c-40f9-9517-899963de33a4)
Other Software I use: Nilesoft Shell and Wintoys
