### ISSUE TITLE
Windows 10 Start menu completely non-functional after update

### ISSUE THREAD

**Issue by ValidSpider** [valinet/ExplorerPatcher#3563]
Windows 11 24H2

Build 26100.1457

Has been fully functional for months up until an hour ago when the system updated. Now the start menu will not open and right clicking the taskbar does not show the 'Properties' context anymore. Uninstalling brings back functionality of the start menu. Reinstalling solves nothing. The only updates it performed were:

2024-08 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 24H2 for x64 (KB5042098)
2024-08 Cumulative Update for Windows 11 Version 24H2 for x64-based Systems (KB5041571)
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.417.111.0) - Current Channel (Broad)
Windows Malicious Software Removal Tool x64 - v5.127 (KB890830)

Hoping this is not another attempt from MS to kill EP...

**Comment by Amrsatrio** [comment]
What's the EP version that you have right now? And yeah MS is actively fighting against EP right now.

**Comment by sloke123** [comment]
EP has stopped working since last night. Even the start menu won't open anymore. Had to uninstall it.

**Comment by hecknt** [comment]
running 26100.1457 and the start menu opens fine for me

**Comment by Pattzxrns** [comment]
running newest version and works fine for me

**Comment by jiut** [comment]
Me too. The explorer and the taskbar are completely non-functional.

EP 22621.3880.66.4
Win 11 Pro 23H2 22631.4037

update installed:
KB5042131
KB5041585
KB5042099
KB890830

**Comment by mc30207** [comment]
running 22621.3880.66.4 on arm win 11. the start menu can work show on the bottom, but can't show on the top when set the taskbar on the top (still show on the bottom).

**Comment by Amrsatrio** [comment]
@mc30207 What's your Windows build number?

**Comment by Amrsatrio** [comment]
Closing this issue because there are no major problems with the start menu on latest 26100 builds. Even on the newly released 27xxx it works 🤷
