### ISSUE TITLE
[ARM64] [26100.1457] The Start Menu does not change position along with the taskbar after Windows update KB5041571

### ISSUE THREAD

**Issue by mc30207** [valinet/ExplorerPatcher#3566]
windows version: win11 arm 26100.1150 24H2
explorerpatcher version: 22621.3880.66.4
device: surface laptop 7 snapdragon x plus

As mentioned at the beginning, the Start Menu does not change position along with the taskbar after the Windows update KB5041571. I tried adjusting various settings after the update to make the Start Menu appear in the correct position, but nothing worked. So, I uninstalled the Windows updates from this morning and found that KB5041571 is causing the Start Menu to display in the wrong position. Please help confirm whether this is a software issue or if I have configured something incorrectly. Thank you.

**Comment by Amrsatrio** [comment]
Hi, I have tested that the start menu should position correctly on build 26100.1150 ARM64. Please make sure to restart Explorer after changing the Start menu to Windows 10. If the original 10 animations work, then the positioning should work as well because the patch depends on that.

**Comment by mc30207** [comment]
Hello, the issue on my computer occurs after installing the KB5041571 update. I've tried restarting both the software and the computer, restoring the Windows 11 default taskbar, and even uninstalling the software. However, once the KB5041571 update is installed, the Start menu only appears at the bottom of the screen, with the animation always coming up from the bottom, regardless of the taskbar's position. I'm not sure why this is happening.

**Comment by mc30207** [comment]
Hello, the issue on my computer occurs after installing the KB5041571
update. I've tried restarting both the software and the computer, restoring
the Windows 11 default taskbar, and even uninstalling the software.
However, once the KB5041571 update is installed, the Start menu only
appears at the bottom of the screen, with the animation always coming up
from the bottom, regardless of the taskbar's position. I'm not sure why
this is happening.

Amr Satrio ***@***.***> 於 2024年8月17日 週六 下午6:08寫道：

**Comment by Amrsatrio** [comment]
Ok that's 26100.1457. Sorry that it happened, ARM64 version of EP is still in its very early stages so the stuff needed to get the start menu patched properly is still not mature.

**Comment by mc30207** [comment]
No problem, I look forward to your future fixes. Thank you in advance.

**Comment by Amrsatrio** [comment]
![image](https://github.com/user-attachments/assets/9779a935-1500-4d55-b79d-b47283bd3619)

Working on turning the reds into greens.

**Comment by Amrsatrio** [comment]
Fixed in 66.5.

![image](https://github.com/user-attachments/assets/633bdea7-2382-4c94-a3da-af92ddfac72f)
