### ISSUE TITLE
Add shortcut key to toggle auto-hide taskbar.

### ISSUE THREAD

**Issue by LakeSuperior** [valinet/ExplorerPatcher#3567]
Dear programmer,  Now to hide taskbar is only double click taskbar,  Using shortcut to toggle auto-hide taskbar is more convenient and more simple.

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

The source code is also available here, so you can add this yourself if you want it.
