### ISSUE TITLE
Cannot show hidden items in file explorer 

### ISSUE THREAD

**Issue by leehamgold42** [valinet/ExplorerPatcher#3571]
When selecting the hidden items tick box in the view tab of file explorer, it won't stay checked and when I try to turn it on in the options, it disappears. is there a work around for this?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by estevaocm** [comment]
I have the same problem after installing 22621.3880.66.4. Windows version 23H2 (22631.4037). I'm only using for taskbar, other settings should be default. 
![image](https://github.com/user-attachments/assets/b95a6bbf-2a0e-4c91-971a-f663703414fb)

**Comment by pyrates999** [comment]
Thank you.  I wanted to check if you had enabled **register as shell extension**.

If you uninstall EP, reboot, does this still occur?

**Comment by estevaocm** [comment]
I'm sorry, I hadn't followed the antivirus instructions before. I'm using Bitdefender Free and once I set the required exceptions, the show hidden files setting was back working normally.

**Comment by pyrates999** [comment]
I would say bitdefender may be interfering then with this.

**Comment by LiamGoldfinch** [comment]
Thanks everyone for ur suggestion, I managed to fix the problem

**Comment by pyrates999** [comment]
Please close this then.
