### ISSUE TITLE
Bug: Transparent Taskbar disabled after Fullscreen games/videos

### ISSUE THREAD

**Issue by shadowking1443** [valinet/ExplorerPatcher#3573]
Hello team!

After launching a full screen application, such as a game or video, the taskbar changes back to acrylic as opposed to transparent. The only workaround to then get it back to transparent is to restart file explorer. 

![Screenshot 2024-08-18 162343](https://github.com/user-attachments/assets/0a2efa47-0526-4bf4-a805-c027c2285c54)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by pyrates999** [comment]
If you want a transparent taskbar, install [NiceTaskBar](https://apps.microsoft.com/detail/9pkl2s93xwb5?hl=en-US&gl=US).

**Comment by shadowking1443** [comment]
Windows Version: 23H2 (OS Build 22631.4037) x64

Explorer Patch Version: 22621.3527.65.5

The only other software that would modify it is Start11.

![Screenshot 2024-08-18 212233](https://github.com/user-attachments/assets/e98a73d9-58b6-41e5-a129-3fe6ab301a6f)
![Screenshot 2024-08-18 212243](https://github.com/user-attachments/assets/a78e1fbc-2a7e-44a9-b963-67ec89c8dd79)
![Screenshot 2024-08-18 212257](https://github.com/user-attachments/assets/553bc71f-5b04-4b0b-9090-4d195cce1596)
![Screenshot 2024-08-18 212306](https://github.com/user-attachments/assets/ca6834c7-db7f-453c-b199-c4a39acf92fd)
![Screenshot 2024-08-18 212317](https://github.com/user-attachments/assets/6525e357-6568-4d4e-bc6d-39addf2c2355)
![Screenshot 2024-08-18 212325](https://github.com/user-attachments/assets/bcaa2f7b-42dd-4193-b212-71905c14cc76)
![Screenshot 2024-08-18 212336](https://github.com/user-attachments/assets/d3d2d31a-3b3f-431d-92de-4b446dcd0beb)
![Screenshot 2024-08-18 212343](https://github.com/user-attachments/assets/e1ea7f3e-0ca6-41ec-85d3-a1c614013cf1)

**Comment by pyrates999** [comment]
try installing the latest pre-release of EP: https://github.com/valinet/ExplorerPatcher/releases

if you're running windows defender, set windows defender to exclude the following:

1. %ProgramFiles%\ExplorerPatcher
2. %APPDATA%\ExplorerPatcher
3. Directory that you downloaded ep_setup.exe to

**Comment by Amrsatrio** [comment]
Transparent taskbar is not a feature provided by EP.
