### ISSUE TITLE
Flyouts are hidden / don't appear when taskbar is set to top of screen

### ISSUE THREAD

**Issue by UltraGit** [valinet/ExplorerPatcher#3574]
aligning a Windows 10 style taskbar to the top of the screen, and the right-click flyouts no long er appear - moving the tasbar to the bottom of the screen, they work fine, then disappear again when the taskbar is again moved to the top. so I am assuming the flyout positioning remains relative to the taskbar icon, rather than adjusting for the top position layout.  This did work just fine a few versions ago - perhaps some other flyout fix is now affecting this configuration negatively.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by pyrates999** [comment]
Is this the same thing as what you are referring to? https://github.com/valinet/ExplorerPatcher/issues/3139

**Comment by idonnno** [comment]
Exactly the same issue here after the recent Windows update, worked fine before Windows update, broken as UltraGit says plus some visual anomalies after update, restoring default settings and reinstalling EP got rid of the visual anomalies, but the issue described here remains.
It doesn’t seem to be the same issue from #3139 .
Windows version 23H2 22631.4037 x64
EP version 22621.3527.65.5
The taskbar settings seem to be the only relevant ones here, will provide all the pages if needed. Also, the flyout that appears when taskbar is placed at the bottom is win11 style, I don’t remember if it was like this before.
No other UI modifying software installed.
![属性 2024_08_19 23_35_57](https://github.com/user-attachments/assets/9a47e7f9-0ce4-45be-9262-8b985dee18f1)

**Comment by pyrates999** [comment]
You enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by braX6666** [comment]
I am having the same problem. I do not have the Shell Extensions option enabled. If I were to guess, I would say the flyouts are appearing above the top of the screen. It started after the Windows 11 update on August 13.

**Comment by pyrates999** [comment]
Try installing the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by braX6666** [comment]
> Try installing the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

That has resolved the problem for me. Thank you.

**Comment by idonnno** [comment]
Disabling [register as shell extension] didn’t work, updating to pre-release solved the problem. Thank you.

**Comment by UltraGit** [comment]
LAtest pre -release ver fixed. Thank you - closing issue
