### ISSUE TITLE
Unable to add shortcut, icon to Start menu

### ISSUE THREAD

**Issue by Mihail-Lazarev** [valinet/ExplorerPatcher#3575]
The list of programs that are in the Start menu only includes programs that you install. Any other icons or files that you would normally add through the Windows/Program Data/Microsoft/Start Menu folder simply don't appear there. For example, it is impossible to add an icon for the Portable version of the program.
In the taskbar the icons are pinned normally.
![Снимок экрана 2024-08-18 215236](https://github.com/user-attachments/assets/655af7fe-8048-42ff-9af4-2cbe3e3eeddb)
On the screenshot I tried to add a folder "Lightroom" and "LightroomPortable" shortcut but it did not appear.

**Comment by pyrates999** [comment]
From: https://superuser.com/questions/947985/cant-pin-some-applications-to-start-menu-in-windows-10

1. Copy the shortcut to %AppData%\Microsoft\Windows\Start Menu\Programs
2. It should now show up in the start menu under Recently added
3. Pin it now

**Comment by Erosion139** [comment]
> From: https://superuser.com/questions/947985/cant-pin-some-applications-to-start-menu-in-windows-10
> 
>     1. Copy the shortcut to %AppData%\Microsoft\Windows\Start Menu\Programs
> 
>     2. It should now show up in the start menu under Recently added
> 
>     3. Pin it now

This did it for me, thanks so much!

**Comment by pyrates999** [comment]
Please close this.

**Comment by Mihail-Lazarev** [comment]
The advice here didn't help me, but I found another solution. The problem wasn't related to Explorer Patcher.

**Comment by Mihail-Lazarev** [comment]
Closing
