### ISSUE TITLE
Error is observed while importing settings file and while clicking on Restore default setting option on Explorer Patcher

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#3584]
Repro Steps
1. Deploy latest OS build (26120.1350).
2. Perform Windows Updates.
3. Install the application from vendor site.
4. Launch the application.
5. Click on Setting and uninstall Option.
6. Click on Import settings.
7. Select the supported file .
8. Observe.
9. Click on default settings.
10. observe

NOTE: This bug only repro on Windows insider build

Actual Result:
Error is observed while importing a file and performing default setting
![Error](https://github.com/user-attachments/assets/6d9f7dbe-bd96-42ce-a3bd-37b66adf289b)

**Comment by Michellehdr** [comment]
Hi Team, could you please take a look at this bug?

**Comment by Michellehdr** [comment]
@valinet could you please take a look at this bug? Thanks!

**Comment by Michellehdr** [comment]
@valinet could you please take a look at this bug? Thanks!

**Comment by Michellehdr** [comment]
@valinet could you please take a look at this bug? Thanks!

**Comment by Michellehdr** [comment]
@Amrsatrio, could you please take a look at this bug? Thanks!

**Comment by valinet** [comment]
Do you really think it is okay to spam tag us every week here? 😡 Don’t want to be rude, but what steps have you taken when it comes to looking into it? 😕

**Comment by Michellehdr** [comment]
@valinet Glad to see your reply. Sorry for checking every week. that is because I did not see anyone starts to look at this ticket. I was still trying to understand your process to bug management. To add more info: this bug is a regression bug, and it is only repro on 26120.1350 or higher OS version.

**Comment by valinet** [comment]
First and foremost, try to understand not tagging people just because you feel entitled to. Sorry, but I missed the part where you were explaining why you haven’t looked into it yourself.
