### ISSUE TITLE
Will ExplorerPatcher 22621.3880.66.4 (and later) still remain the legacy balloon notification tray?

### ISSUE THREAD

**Issue by TK50P** [valinet/ExplorerPatcher#3586]
I seen 22621.3880.66.4 release.
You said:
_With this update, ExplorerPatcher is now officially compatible and supported on Windows 11 24H2_
_- EP's taskbar implementation for 24H2 is now available_
![image](https://github.com/user-attachments/assets/42145f02-311f-4936-9da8-9d4271b50ae7)
but, my BIG qustion is this implement. (Windows 7/8.1 Balloon Notification)
Will you add this option for next release? or still able?

**Comment by milesprower2293** [comment]
The reimplemented taskbar already has that if i remember correctly you can enable it the same way as the regular 10 taskbar
also: this section is for **Issues** only for feature requests use [Discussions](https://github.com/valinet/ExplorerPatcher/discussions)

**Comment by Amrsatrio** [comment]
Yes. Also not a bug.
