### ISSUE TITLE
Right Clicking programs does not display function Menus on Windows 10 Taskbar at top of screen

### ISSUE THREAD

**Issue by Guardians6521** [valinet/ExplorerPatcher#3587]
With Windows 10 Taskbar set to top of screen, right clicking the programs themselves (or anything thats NOT The taskbar itself) does not open the menu for other functions associated with the right click. (I dont know UI terms) Shift+right click does not bring up the correct menu, it brings up the very basic program management menu (open, open file location, etc)

However, when returning the taskbar to windows 11 style, the right-click function works as it should bringing up the menus for other higher functions such as right clicking sticky notes and "Hide All Notes" or "Show All Notes"

I wonder if maybe the menu is displaying above the taskbar off screen, and not reorientating itself below the taskbar?

Ive tried a few reinstalls of explorer patcher and explorer restarts, and some of the online fixes for right click being broken online, its definitely something up w Patcher or Windows 11 not allowing patcher to do something/ broken right click functionality on the pinned taskbar programs/icons

Lastest versions of W11 & EP at time of posting, feels like this problem is very recent. I dont remember having this issue a few weeks ago.

Its been driving me nuts, Thanks!

**Comment by efojug** [comment]
What is your Windows version? Everything seems to work fine on 27686.

**Comment by sigh8** [comment]
I'm also having the save problem on windows11 23H2 **only** when taskbar location is set to "Top". Right-clicking on any program in the taskbar displays this weird bar and nothing else.
![image](https://github.com/user-attachments/assets/85913fb1-186d-4d6c-90f0-ce28195e88cb)

**Comment by 0x000hx** [comment]
same. running the latest patcher

windows ver: 22631.4037

**Comment by efojug** [comment]
This may be a unique issue with the beta channel. I did not encounter this problem when using the top taskbar on canary 27686
![image](https://github.com/user-attachments/assets/37053ed5-b14e-42eb-8534-4cd251b12ac5)

**Comment by pyrates999** [comment]
Try installing the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by cor-of-org** [comment]
> Try installing the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

This fixes the issue for me (22621.3880.66.4). Thanks!

**Comment by Guardians6521** [comment]
> Yup, latest Windows update broke this again today.

The new update fixed this

**Comment by cor-of-org** [comment]
Damn, I'm one digit off. How do I get it to keep itself updated?

**Comment by Guardians6521** [comment]
> Damn, I'm one digit off. How do I get it to keep itself updated?

Theres a setting in the updates tab in properties i think.

but for sure theres a check for updates function in that update tab

**Comment by pyrates999** [comment]
Open up EP properties application and go to Updates on the left side.  From there you can check for new updates and install the latest update.  You can also set it to install pre-releases.
