### ISSUE TITLE
switching between users is hidden in a side taskbar

### ISSUE THREAD

**Issue by Tsurha** [valinet/ExplorerPatcher#3590]
In a side taskbar, when a different user is trying to login, the option to select him is hidden. Please see screen capture.
Apologies if this is known and was discussed a million times. I'm new here.

![image](https://github.com/user-attachments/assets/18105584-9882-4042-8339-8b77ce10badb)

**Comment by pyrates999** [comment]
Install the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

It has the fix for the start menu appearing on top of the windows taskbar when it's not at the bottom.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3464

**Comment by Amrsatrio** [comment]
@pyrates999 Prerelease does not fix this issue and I have no plans to make it fix the alignments. But maybe some day I want to look into disabling it...

**Comment by pyrates999** [comment]
Understood :)
