### ISSUE TITLE
when using taskbar style windows 10(ExplorerPatcher), links in email(mail and calendar)stop working after a period of time

### ISSUE THREAD

**Issue by jw0785** [valinet/ExplorerPatcher#3596]
restarting file explorer temporarily solves the issue.

**Comment by pyrates999** [comment]
if you enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by jw0785** [comment]
![image](https://github.com/user-attachments/assets/da8ab24f-bdde-4ac2-9394-83a44cfd913f)

**Comment by pyrates999** [comment]
can you post the version of EP that you installed?  It should be in the section named About.

**Comment by jw0785** [comment]
![image](https://github.com/user-attachments/assets/13ffd4a1-60a3-456d-b8fe-d7d5a969b3e4)

**Comment by pyrates999** [comment]
Try and install the latest pre-release of EP: https://github.com/valinet/ExplorerPatcher/releases

**Comment by jw0785** [comment]
seems not recurring now

**Comment by pyrates999** [comment]
If it doesn't happen for another week, please close this.

**Comment by Amrsatrio** [comment]
EP does not affect the behavior of other apps when you have shell extension disabled.
