### ISSUE TITLE
No Windows 10 start menu style after updating

### ISSUE THREAD

**Issue by orchestrascores** [valinet/ExplorerPatcher#3597]
Hi, I just updated my computer, after that I noticed the start menu only shows Windows 11. I updated the symbols, still nothing. The program is missing "Start menu style" from Start menu. Please fix this. Thank you!

PS.
Oh, anyway my build is now 22631.4112.
ExplorerPatcher version 22621.3527.65.5 (Windows and EP are not a pre-release, dev, canary or etc.)
2024-08 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5041587)
![Screenshot 2024-08-28 103200](https://github.com/user-attachments/assets/3be3f841-32b3-4ee1-950e-af3993b51ec2)
![Screenshot 2024-08-28 103620](https://github.com/user-attachments/assets/c25b8251-e675-46c3-8ce1-30c7c689843b)

**Comment by lydecker71** [comment]
I am having the same issue.

**Comment by Soulreaver1977** [comment]
Same issue here.

**Comment by orchestrascores** [comment]
> Same issue here.
> 
> :EDIT Solved with 22621.3880.66.4 (manually downloaded and installed, was not found by the program's update feature)

Oh, was it a canary, prerelease, or etc. build?

**Comment by Soulreaver1977** [comment]
> > Same issue here.
> > :EDIT Solved with 22621.3880.66.4 (manually downloaded and installed, was not found by the program's update feature)
> 
> Oh, was it a canary, prerelease, or etc. build? The latest release was the same as the version of my EP. ![Screenshot 2024-08-28 131515](https://private-user-images.githubusercontent.com/109718472/362142508-0dbdc027-3611-4b96-a73e-704acf36c58b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjUzODEsIm5iZiI6MTcyNDgyNTA4MSwicGF0aCI6Ii8xMDk3MTg0NzIvMzYyMTQyNTA4LTBkYmRjMDI3LTM2MTEtNGI5Ni1hNzNlLTcwNGFjZjM2YzU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwNjA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODNhNDVhNWI1M2I5ZDI0N2QwOGEyYjMwNGY3ZDQ5YzM1NTFjODAyMDJmMWRhMzUwODdkMjQwMzk0YjgzY2E3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wFCyFNDjQiLFXhVRkUIwX7OgpVF07IhQSatk4kCUXmA)

I don't know which kind of build it is. I just took the latest one. Only version number is mentioned:

![image](https://github.com/user-attachments/assets/bf3824f5-4c62-424e-869f-0c1ebe62d7f5)

**Comment by randomidiot2887** [comment]
Yup. works.

**Comment by pyrates999** [comment]
> Same issue here.
> 
> :EDIT Solved with 22621.3880.66.4 (manually downloaded and installed, was not found by the program's update feature)

That's because newer builds are pre-releases, and you have to set EP properties application to check for pre-releases.

**Comment by randomidiot2887** [comment]
Then can you make this in the main biulds as well? what actrully whent wrong?

**Comment by GMss2** [comment]
I am having the same issue.

**Comment by randomidiot2887** [comment]
like download a prerelease version from here. https://github.com/valinet/ExplorerPatcher/releases
the version as of the time i posted this is 22621.3880.66.4.
or you can set EP to install prerelease versions

**Comment by randomidiot2887** [comment]
> > Same issue here.
> > :EDIT Solved with 22621.3880.66.4 (manually downloaded and installed, was not found by the program's update feature)
> 
> That's because newer builds are pre-releases, and you have to set EP properties application to check for pre-releases.
downlaod the latest version from https://github.com/valinet/ExplorerPatcher/releases

**Comment by pyrates999** [comment]
I'm not the owner of this repo, so I can't do that.  But the reason it hasn't been released is because of windows defender detecting EP as a hack tool, when it is not.  Blame MS for that.  I post the link I did that shows all releases and pre-releases because it includes instructions on what directories you need to exclude from windows defender before you download and install EP.

**Comment by randomidiot2887** [comment]
well. i followed them and it works perfectly. i know its not your fault. can you let the owner know? or is it not possible? im new to commenting.

**Comment by pyrates999** [comment]
The owner is well aware and is trying to avoid AV falsely detecting EP.  So they do pre-releases until it is stable and is no longer falsely detected by AV.

**Comment by pyrates999** [comment]
You can't install EP if AV is preventing it.

**Comment by randomidiot2887** [comment]
Ok. I’ll leave it for now. Hope 24H2 will be smooth

**Comment by DMessham** [comment]
I was able to get it to work by selecting "allow on device" in windows defender

**Comment by pyrates999** [comment]
In your AV, you'd have to exclude all the directories that EP installs itself to.  And not all users are willing to do that on here.  So that's why there is such a long pre-release for it.

**Comment by orchestrascores** [comment]
> > Same issue here.
> > :EDIT Solved with 22621.3880.66.4 (manually downloaded and installed, was not found by the program's update feature)
> 
> That's because newer builds are pre-releases, and you have to set EP properties application to check for pre-releases.

I won't download pre-releases, I'll wait for it to become a full release

**Comment by pyrates999** [comment]
This should be closed because the solution has been offered.

**Comment by orchestrascores** [comment]
> This should be closed because the solution has been offered.

I know the solution, but I won't do it. I am now officially closing the issue.
