### ISSUE TITLE
Start Menu Style not visible in Properties

### ISSUE THREAD

**Issue by darkov19** [valinet/ExplorerPatcher#3603]
Issue: Basically the title, This is did not happen right after windows update but a few days after I updated the windows.

Windows Version:
![image](https://github.com/user-attachments/assets/68af3628-aa64-4a52-8633-6ccc2e45f2d2)

Properties:
![image](https://github.com/user-attachments/assets/2d7df12a-20ee-45fd-a000-a024e7c133b9)

**Comment by ChrAlpha** [comment]
I met the same issue today right after updating `KB5041587`.

**Comment by kyc20010501** [comment]
I had the same problem and I thought it was something wrong with my computer

**Comment by rajeevkrao** [comment]
Even I have the same problem. I had previously installed windhawk and I thought this was causing the problem. But even after I uninstalled it, the startmenu style option is not visible.

**Comment by pyrates999** [comment]
install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by xiao-cold** [comment]
> install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

After updating to "KB5041587" (Windows 23H2), I encountered the same issue where the Start Menu style was not visible in the properties. 
 Following the advice from another user in this thread, I downloaded and installed the latest pre-release version [22621.3880.66.4](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.4_3c50ea3). After doing so, the Windows 10 Start Menu style returned to normal.

**Comment by icevincible** [comment]
> install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

how to install the pre-release?

**Comment by pyrates999** [comment]
> > install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases
> 
> how to install the pre-release?

Same way you install the release, except look for the label pre-release.

**Comment by Liudprand** [comment]
For me, the Windows says there's a virus when I download the pre-release file. :( 

Maybe it's just being over-cautious/monopolistic, but I'm a bit hesitant to ignore it.

**Comment by Liudprand** [comment]
> For me, the Windows says there's a virus when I download the pre-release file. :(
> 
> Maybe it's just being over-cautious/monopolistic, but I'm a bit hesitant to ignore it.

Actually it seems to have blocked the download, so I couldn't ignore it and install even if I wanted to.

**Comment by pyrates999** [comment]
Read the release notes of the pre-release of what folders you are to exclude for windows defender or whatever AV you have installed.

**Comment by Liudprand** [comment]
I'll give that a go - thanks.
