### ISSUE TITLE
Please update the software :(  Too many bugs make the software almost unusable

### ISSUE THREAD

**Issue by CyanDragonS** [valinet/ExplorerPatcher#3606]
After updating KB5041587, on Windows11 23H2(Build 22621), the start menu will directly prompt Critical Error, and require logout without other options, and the rollback update can not eliminate the fault. In the end, you can only deprecate the software or reinstall the system.

The software hasn't been updated in almost four months. Almost all Windows11 versions higher than 23H2 (22621) are not supported, and the 26100(LTSC Preview) version will directly indicate that the application will not run on this computer. Whether the author can update as soon as possible, there are many bugs, almost can not be used.

 thank all authors.

**Comment by djcholapin** [comment]
My laptop just updated to KB5041587 automatically as well just now, I'm running on 23H2. Using the latest (stable) version of EP, and I have a similar issue, not the same but similar, the start menu has reverted to the windows 11 menu. You can no loner use the windows 10 menu.

Does someone know a workaround to get it reactivated until a permanent fixed is applied ?

@CyanDragonS the author is providing this software for free, probably on his free time, we can consider ourselves lucky that we have such a great app, the win 10 menu is critical to me. Let's see if we can have a workaround until then.

**Comment by pyrates999** [comment]
Wrong.  There are pre-releases: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment]
Yeah there's prereleases that works with the latest builds. The problem is this software is too popular so MS likes to give this an antivirus flag to deter the general public from using the software.

**Comment by ErikaXGH** [comment]
> Wrong. There are pre-releases: https://github.com/valinet/ExplorerPatcher/releases

omg your my life savior. i disabled real time protection time off and used for defender from the description after running it it worked and i turned real time protection time on and it didn't say threats detected. thanks pyrates999. and i used sandbox if it was a virus

**Comment by CyanDragonS** [comment]
Pre-release versions I've tried still cause crashes.
Thanks to all the developers, I am still waiting patiently for the latest update. I've been looking at recent reviews and I'm not saying that the software is bad, I love the software, but maybe Microsoft has been blocking the software because of the popularity of the software?

**Comment by pyrates999** [comment]
MS has added EP to Windows Defender because they don't want us using the windows 10 taskbar and windows 10 start menu.  They want us to see the ads in the windows 11 taskbar and windows 11 start menu.
