### ISSUE TITLE
Problem with icons text and Start Menu Style (Windows 11 23H2)

### ISSUE THREAD

**Issue by f-c-s** [valinet/ExplorerPatcher#3607]
Hello,
On the new versions there are 2 problems:
- current: Start menu style is not available, the option leads into standard windows menu style
- version 22621_3880 - adds shadow to icon text on desktop,  although the best performance settings is set with active only option (clear fonts), It probably happened after de-installing current versions, because of problem with no possibility to choose the style of menu.

I have to revert to version 22621.2861.62.2 to clear previous installation.

Regards
ML

**Comment by pyrates999** [comment]
Install the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment]
1. Install prerelease
2. Not EP that caused it
