### ISSUE TITLE
the windows start menu is now windows 11 and i had the old start menu. fix this

### ISSUE THREAD

**Issue by ErikaXGH** [valinet/ExplorerPatcher#3610]

**Comment by CHAFAN2** [comment]
i got the same thing the shitty win 11 start menu is back somehow

**Comment by CHAFAN2** [comment]
is there any fix even

**Comment by pyrates999** [comment]
Install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by gex581990** [comment]
> Install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

I have the same issue and latest pre-release doesn't fix it

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3603
