### ISSUE TITLE
What happens if I do an update while explorerpatcher is still on?

### ISSUE THREAD

**Issue by githubberguy** [valinet/ExplorerPatcher#3612]
I really wanna know since people years ago said that's I need to know now

**Comment by pyrates999** [comment]
Unless it's an upgrade of windows like from 22h2 to 23h2, you can leave EP installed.  So leaving EP installed while doing monthly updates is ok.  But you uninstall EP if you're gonna do a major upgrade.

**Comment by githubberguy** [comment]
Ok, I will make sure to check every update, since I already use 23H2 and 24H2 is coming so it's a very good thing that you told me
