### ISSUE TITLE
Install isn't working on Windows 11 Home 24H2 26100.1457

### ISSUE THREAD

**Issue by schieco** [valinet/ExplorerPatcher#3623]
I have a brand new computer, running Windows 11 home, and I cannot install the ExplorerPatcher which is so unfortunate! 

I thought maybe in the tons of initial windows updates the OS build had gotten upgraded, so I tried to uninstall it and I got the "This app can't run on your PC" - so I renamed the install executable to ep_uninstall and could uninstall it that way, but then I reinstalled it and still have the same problem. Basically it didn't do anything, and when I right-click on the task bar, nothing happens at all. No context menu appears.

Help! I saw in a forum that someone with the same problem still had an older explorerpatcher executable lying around which worked without issue for them - but I do not know where to get an older executable. 

Windows info:
Edition	Windows 11 Home
Version	24H2
Installed on	‎8/‎21/‎2024
OS build	26100.1457
Serial number	PF527RFF
Experience	Windows Feature Experience Pack 1000.26100.11.0

Thanks,
Sara

**Comment by Amrsatrio** [comment]
ExplorerPatcher version 66.1 and older are blocked by Microsoft from being installed on 26100. Please use the latest 66.4 prerelease, and also please configure your Defender exclusions for smooth sailing.
