### ISSUE TITLE
Windows 10 Start Menu Not Displaying Anymore

### ISSUE THREAD

**Issue by cobimaestro** [valinet/ExplorerPatcher#3627]
Randomly it stopped dispalying a Windows 10 Start Menu even after uninstalling/reinstalling, changing to 11 and back to 10 and ensuring I have the latest version installed.

**Comment by devaiahkk03** [comment]
I heard that they were removing the win10 taskbar from windows, I was having issues with it not displaying app list, but with the new windows update its completely gone. WIndows might have removed it while adding the new start menu customisations.
It looks terrible but I guess its the only option we have until a fix.

**Comment by Amrsatrio** [comment]
Download latest prerelease.
