### ISSUE TITLE
Pop up menu cut off

### ISSUE THREAD

**Issue by susa13** [valinet/ExplorerPatcher#3628]
Hi,
This is a very niche issue that seems to only affect the taskbar when it is at the top of your screen
The pop up menu whenever you right click an application is cut off starting from the top and you can only access the first item from the dropdown.
Image below shows me right-clicking on Steam.

![pop up menu cut off](https://github.com/user-attachments/assets/7ed011cd-fd03-4ed4-ace3-e07c7562eb5f)

**Comment by Amrsatrio** [comment]
Download latest prerelease.
