### ISSUE TITLE
Windows 10 taskbar right-click icon context menu not showing

### ISSUE THREAD

**Issue by neuralnermal** [valinet/ExplorerPatcher#3629]
Normally if you right-click the minimized icon on the taskbar there should be a context menu depending on the app:
![How-to-Open-Right-Click-Menu-for-Icons-on-Taskbar-in-Windows-10-Pic-2](https://github.com/user-attachments/assets/27e537e0-6abb-484a-8cd4-eb1c9e928f69)

But when the taskbar style is set to 'Windows 10', and the taskbar location is set to 'top'. The context menu does not appear.
If it is set to 'bottom' it appears normally.

I've kept this setting for months, and it only started doing this last week Friday I think. Afaik, there wasn't a major update I did for the past week? 

The only major change I can think of is running a registry cleaner on CCleaner. I've had some relatives come over and the kids wanted to play with the computer so I let them. After uninstalling all the game launchers from Riot, Blizzard etc, and some anti-cheats that need kernel excess for some reason, I just assumed it would be good to run registry cleaner. Can't remember if the issue started occurring after that or before that though.

**Comment by Amrsatrio** [comment]
Download latest prerelease.
