### ISSUE TITLE
Win10 style start menu disappered

### ISSUE THREAD

**Issue by Gepeti72** [valinet/ExplorerPatcher#3631]
Win10 style start menu disappered from application settings and so can not be switched on. Win11 start menu reappered after Windows 11, version 23H2 update. Please fix.

**Comment by pyrates999** [comment]
Install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by MaitieS** [comment]
I had the same exact question since yesterday. It's most likely because you also updated to the newest W11 Update? Because a week ago it worked just fine.
