### ISSUE TITLE
Windows 10 style menu not available anymore

### ISSUE THREAD

**Issue by Franck-75** [valinet/ExplorerPatcher#3632]
With the last windows update, the windows 10 menu style is not working anymore.

Explorer Patcher 22621.3527.65.5
No new stable version available.
Windows Family 11 version 23H2 build 22631.4112
Localisation : French

I don't see anymore "Windows 10 presentation" on Explorer Patcher's Start Menu screen parameter.

**Comment by pyrates999** [comment]
install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases
