### ISSUE TITLE
Keyboard layout switching

### ISSUE THREAD

**Issue by Cetarik** [valinet/ExplorerPatcher#3641]
Without ExplorerPatcher I was able to switch keyboard layout (language) with a shortcut L ctrl+ L shift (or L alt + L shift) but after installing ExplorerPatcher I am not able to use this shortcut. Am I doing something wrong? Is there some setting that might affect this function?
Version 22621.3527.65.5
Thanks

**Comment by pyrates999** [comment]
Please install latest pre-release to see if it fixes it: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Cetarik** [comment]
No change with 22621.3880.66.5

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Cetarik** [comment]
Win11 23H2 22631.4037 x64

![image](https://github.com/user-attachments/assets/c1d82cce-8a1f-49cd-9666-b99b07102687)
![image](https://github.com/user-attachments/assets/5bd0c3de-8862-4333-8924-c2ceff70af3b)
![image](https://github.com/user-attachments/assets/3cb1dd3d-0118-4e62-88bd-606a37071a7c)
![image](https://github.com/user-attachments/assets/984a7f5c-f17a-4986-abb6-f598b9fd4aaa)
![image](https://github.com/user-attachments/assets/cb9437af-255a-4e32-91b5-2d652994f946)
![image](https://github.com/user-attachments/assets/44d543f9-cd1c-4286-a702-1d6205af54b8)
![image](https://github.com/user-attachments/assets/da1ec913-bdb4-427d-a2af-e38de4d00736)
![image](https://github.com/user-attachments/assets/49c55167-1b57-470c-92fe-bed774369b36)
![image](https://github.com/user-attachments/assets/c39f8a07-ae98-422a-b15f-801cd02fdbb6)
![image](https://github.com/user-attachments/assets/90418d1f-1c5f-4996-924d-2f2daeef7d51)
![image](https://github.com/user-attachments/assets/ec79be3f-3414-48a9-a5e9-80763041d85e)
No other software that modifies windows UI was installed.

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

Let me know if that fixes it or not.

**Comment by Cetarik** [comment]
So I did what you told me to do - no change.
But I have found out that not even manual selection of keyboard layout doesnt work.
Everything was fixed by restarting explorer and then whole computer.
Computer was running only for a 3 hours from shutdown.
But I guess this is not an issue of your program, but probably a windows issue.
Sorry for any inconveniences and thank you for a great app!

**Comment by pyrates999** [comment]
Ok, please close this then.
