### ISSUE TITLE
Where's thew Windows 10 style start menu option?

### ISSUE THREAD

**Issue by GuestTheGamer** [valinet/ExplorerPatcher#3643]
![Screenshot 2024-09-06 110558](https://github.com/user-attachments/assets/6c2704b1-9cd6-4e67-8068-ccf2fa3a1e00)

**Comment by jenshoerburger** [comment]
- Please read rule for the issues area: You may not use "issues" on github for discussions. Go to discussions.
- in Discussions this problem has been already solved: install the current pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.5_5094108
