### ISSUE TITLE
Bluetooth cannot add new device

### ISSUE THREAD

**Issue by ctx26** [valinet/ExplorerPatcher#3645]
Thank you for your great work!
Just noticed one problem when adding a new bluetooth device.
No reaction after I clicking 'Add device' at the bluetooth settings in windows setting, see below. After uninstalling ExplorerPatcher, back to normal.

![image](https://github.com/user-attachments/assets/b6e093db-31c8-4aef-99e8-5bfc583ef563)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

**Comment by Amrsatrio** [comment]
Closing due to no response and irreproducibility on 22631.4391.
