### ISSUE TITLE
Trying to install pre-release on windows 11 is not working

### ISSUE THREAD

**Issue by schieco** [valinet/ExplorerPatcher#3647]
I was told to use the pre-release version 66.4 or higher, and I disabled Windows Defender Smartscreen so it lets me run the executable, but it is not running. Nothing happens when I try to run it.  No error, just nothing.

I tried to run this as was suggested:
Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"

But I get this error, and I cannot figure out where to put the manual exclusions as I turned off webroot and don't see where it would be blocking files. 

Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

OS:
Edition	Windows 11 Home
Version	24H2
Installed on	‎8/‎21/‎2024
OS build	26100.1591
Serial number	PF527RFF
Experience	Windows Feature Experience Pack 1000.26100.18.0

**Comment by Amrsatrio** [comment]
Run the commands in Powershell as Admin. It won't work if you run as regular user.
