### ISSUE TITLE
Audio control issues

### ISSUE THREAD

**Issue by hecode** [valinet/ExplorerPatcher#3648]
since the last win update i did recently, the audio control has been having issues. it shows up but moving the volume slider doesn't work and selecting a different output also doesn't work, it expands the list but clicking the other output doesn't work.
restarting ExplorerPatcher fixes both issues.
win 11 style/default

Edition	Windows 11 Pro
OS build	22631.4112
Experience	Windows Feature Experience Pack 1000.22700.1034.0

ExplorerPatcher
Version 22621.3527.65.5

**Comment by pyrates999** [comment]
do you mean killing the explorer.exe process and running it again fixes it?

**Comment by hecode** [comment]
> do you mean killing the explorer.exe process and running it again fixes it?

ah, yes exactly, i always do it from the app bottom left "Restart File Explorer"

**Comment by hecode** [comment]
Sorry i missed to add that this happens sometimes, not all the time. if i notice a pattern i will comment with it

**Comment by hecode** [comment]
likely explorer itself
