### ISSUE TITLE
[23H2] Win10 taskbar right-click menus cutoff

### ISSUE THREAD

**Issue by L1ghtmann** [valinet/ExplorerPatcher#3649]
System:
- 23H2 [22631.4112]

Issue:
- Taskbar right-click menus cutoff 
<img width="266" alt="{7C56A92C-B506-43E0-BD9C-1858AA0615E4}" src="https://github.com/user-attachments/assets/1c1287d2-81dc-4427-affc-9e8615510477">

ExplorerPatcher config:
-  Win10 style
- Top-aligned

If there's anything else I can test/provide, please let me know. Thanks!

**Comment by pyrates999** [comment]
Please post explorer patcher version.

**Comment by L1ghtmann** [comment]
V22621.3527.65.5

**Comment by pyrates999** [comment]
install the latest pre-release here: https://github.com/valinet/ExplorerPatcher/releases

read the release notes regarding AV

**Comment by L1ghtmann** [comment]
Appears to be fixed in v22621.3880.66.5. Thanks!
