### ISSUE TITLE
Not able to switch between explorer windows sometimes

### ISSUE THREAD

**Issue by hecode** [valinet/ExplorerPatcher#3653]
Another issue i found that occurs sometimes other than the audio thing. is that sometimes for example if i had 2 or more different explorer windows open and i want to switch between them, it doesn't switch. for example in one window is downloads folder and in another is documents. when i go to the file explorer in the taskbar and hover it will show the two windows, now when i click the other, it doesn't switch.
restarting file explorer fixes this but of course closes all the windows that were open.

Edition Windows 11 Pro
OS build 22631.4112
Experience Windows Feature Experience Pack 1000.22700.1034.0

ExplorerPatcher
Version 22621.3527.65.5

**Comment by pyrates999** [comment]
If you're using windows 10 taskbar, you should install the latest pre-release.

Then open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by hecode** [comment]
Using windows 11 Taskbar

**Comment by pyrates999** [comment]
does it happen if you uninstall EP?

**Comment by hecode** [comment]
I haven't tried uninstalling it

**Comment by pyrates999** [comment]
Try that and let me know if you still are experiencing this.

**Comment by hecode** [comment]
i had it uninstalled for 3 days so far and it hasn't happened. https://github.com/valinet/ExplorerPatcher/issues/3648 hasn't happened either.

**Comment by hecode** [comment]
scratch that, an issue with the controls popup that opens with Bluetooth, audio, etc. not opening is occurring with it uninstalled. happened after putting pc to sleep multiple times.

**Comment by pyrates999** [comment]
then this is not caused by EP.  Please close this.

**Comment by hecode** [comment]
> then this is not caused by EP. Please close this.

will do
