### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by Markcoruk** [valinet/ExplorerPatcher#3657]
It's stopped working today after update.

**Comment by pyrates999** [comment]
What stopped working in EP?

Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Markcoruk** [comment]
After recent windows update. Reverted back to windows 11 menu.

**Comment by pyrates999** [comment]
You don't say what is not working, so all I can say is install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

If that doesn't fix it, please supply the info I am asking for.

**Comment by Markcoruk** [comment]
Hi thanks all working now. Installed the pre release.
