### ISSUE TITLE
taskbar unlocked & make it taller 

### ISSUE THREAD

**Issue by seb6600** [valinet/ExplorerPatcher#3658]
what happened to the taskbar option working, until last week it was unlocked and i could ajust the hide as far as i please, not now.. i using the kast version as always..

### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/622

<div type='discussions-op-text'>

<sup>Originally posted by **valinet** January  2, 2022</sup>
Please read **[this document](https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems)** outlining some general guidelines regarding problem reporting, feature requests, questions and support tickets regarding ExplorerPatcher, especially if it's the first time posting here. You are welcome to discuss the document in this thread.

Thank you</div>

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Change your taskbar to Windows 10 or Windows 10 (ExplorerPatcher).

**Comment by seb6600** [comment]
it is and always has been set as win10 taskbar which i could adjust, recently it just locked to small without me doing it, , still locked and cannot enlarge it now..

**Comment by pyrates999** [comment]
Pre-releases will not show as updates unless you set that in EP Properties application.

And you must manually download them and read the release notes for them as you must exclude it with your AV: https://github.com/valinet/ExplorerPatcher/releases
