### ISSUE TITLE
taskbar also worked great, now not unlocked and no options for this, it was always adjustable in height

### ISSUE THREAD

**Issue by seb6600** [valinet/ExplorerPatcher#3659]
what happened to the taskbar option working, until last week it was unlocked and i could adjust the hide as far as i please, not now.. i using the last version as always.. and there is no options to UNLOCK the TASKBAR, that for height adjustment, which was a normal part of an unlocked taskbar..

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3658

please close this.
