### ISSUE TITLE
Explorer keeps crashing and restarts after restarting the explorer.exe (Pre-Release 22621.3880.66.4)

### ISSUE THREAD

**Issue by RedDragonTix** [valinet/ExplorerPatcher#3661]
This happens when trying to restart explorer, and it just keeps crashing and restarts over and over, keeps flashing!

happens on Pre-Release 22621.3880.66.4!

restarting the PC fixed and it works but ExplorerPatcher doesn't work anymore, trying to restart explorer.exe again, it keeps crashing and restarts!

even reinstalling with the stable release doesn't work, not even upgrading to latest pre-release version, so I cannot even reinstall explorerpatcher

it also happens even with ep uninstalled!

OS: Windows 11 LTSC IoT 24H2

**Comment by RedDragonTix** [comment]
somehow I've managed to update EP and it works, but it's still a problem with restarting explorer

so I have to restart PC in order to make changes working

**Comment by Amrsatrio** [comment]
What's your Windows build number? "Windows 11 LTSC IoT 24H2" is not complete.

**Comment by RedDragonTix** [comment]
> What's your Windows build number? "Windows 11 LTSC IoT 24H2" is not complete.

26100.1457

**Comment by Amrsatrio** [comment]
Are you using any other tweak software like Windhawk, StartAllBack, TranslucentTB, Wallpaper Engine, or such?

**Comment by foreachthing** [comment]
I can't even download it:
![image](https://github.com/user-attachments/assets/12e27897-5afc-4bc4-9b7a-975c96697a27)

Bitdefender blocks it.
Windows 11, 22H2, 22621.4112

**Comment by Amrsatrio** [comment]
@foreachthing Read the warning section in the Releases page. You clearly did not read it.

**Comment by S2GB47** [comment]
Having similar issue with latest version of EP
After selecting update whole screen became white, restarting PC reverted to win 11 default taskbar.
I downloaded 22621.3880.66.4 setup and ran it and now it is working again.
I am on Win 11 Pro 23H2 22631.4037

**Comment by pyrates999** [comment]
If using windows 10 taskbar, open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by RedDragonTix** [comment]
> Are you using any other tweak software like Windhawk, StartAllBack, TranslucentTB, Wallpaper Engine, or such?

I'm using Windhawk so I tried to turn it off and then restart explorer
and same thing

**Comment by RedDragonTix** [comment]
> > > Are you using any other tweak software like Windhawk, StartAllBack, TranslucentTB, Wallpaper Engine, or such?
> > 
> > 
> > I'm using Windhawk so I tried to turn it off and then restart explorer and same thing
> 
> how did you turn off windhawk? Did you just disable the mods it was using? Try uninstalling windhawk and rebooting.

I just right click on the tray and exit

**Comment by pyrates999** [comment]
That doesn't disable it I don't think.  Do a proper uninstall of windhawk, reboot, and then try.  It might be one of the mods that is causing it.

**Comment by RedDragonTix** [comment]
> That doesn't disable it I don't think. Do a proper uninstall of windhawk, reboot, and then try. It might be one of the mods that is causing it.

even if I uninstalled Windhawk and rebooted the computer, it still flashes when I restart explorer

**Comment by pyrates999** [comment]
did you actually do that just now?

**Comment by RedDragonTix** [comment]
> did you actually do that just now?

yes

**Comment by pyrates999** [comment]
with EP installed, when it happens again:

1. open up windows event viewer or computer management
2. go to Event Viewer and go to Windows Logs -> Application
3. copy and paste the log of explorer.exe crashing here

**Comment by RedDragonTix** [comment]
> > with EP installed, when it happens again:
> > ```
> > 1. open up windows event viewer or computer management
> > 
> > 2. go to Event Viewer and go to Windows Logs -> Application
> > 
> > 3. copy and paste the log of explorer.exe crashing here
> > ```
> 
> that's a lot of explorer crashing logs so I will post only one:
> 
> `Faulting application name: Explorer.EXE, version: 10.0.26100.1301, time stamp: 0x570046f0 Faulting module name: ucrtbase.dll, version: 10.0.26100.863, time stamp: 0xa51207be Exception code: 0xc0000409 Fault offset: 0x00000000000a514e Faulting process id: 0x20CC Faulting application start time: 0x1DB045CE638E89E Faulting application path: C:\WINDOWS\Explorer.EXE Faulting module path: C:\WINDOWS\System32\ucrtbase.dll Report Id: e63e880d-3784-4c4e-8515-ea21d22cc2d8 Faulting package full name: Faulting package-relative application ID: `

they are the same except the IDs are different

**Comment by pyrates999** [comment]
if you enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by RedDragonTix** [comment]
> if you enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.
> 
> Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

but it's disabled already

**Comment by pyrates999** [comment]
Try uninstalling bitdefender and see if explorer is still crashing.

**Comment by RedDragonTix** [comment]
> Try uninstalling bitdefender and see if explorer is still crashing.

I don't have it installed

**Comment by pyrates999** [comment]
does explorer keep crashing after you uninstall EP?

**Comment by RedDragonTix** [comment]
> does explorer keep crashing after you uninstall EP?

yes, it keeps crashing after uninstall it, and then restart explorer

**Comment by Amrsatrio** [comment]
Try with both Windhawk and EP uninstalled. If it still crashes, I'm afraid that a clean install may be needed.

**Comment by S2GB47** [comment]
> If using windows 10 taskbar, open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**. We no longer offer more support on the stock Windows 10 taskbar.

Thank you that worked

**Comment by RedDragonTix** [comment]
I found out the cause of this, it was Retrobar's fault!
