### ISSUE TITLE
Microsoft Defender troubles

### ISSUE THREAD

**Issue by OldFox-62** [valinet/ExplorerPatcher#3662]
Update to ExplorerPatcher Version 22621.3880.66.5 

On Windows 11 (23H2 Build 22631.4112)

Microsoft Defender:
"Operation did not complete successfully because the file contains a virus or potentially unwanted software"

**Comment by Amrsatrio** [comment]
> [!WARNING]
> <ins>**You are downloading a file flagged as malware by Microsoft and very likely by other major antivirus vendors.**</ins> We believe that this false flag indicates Microsoft's hatred against this software, not because this contains a virus or such.
>
> Please include the following files and folders in your antivirus' exclusion list to prevent issues due to antivirus detections:
> * `C:\Program Files\ExplorerPatcher`
> * `%APPDATA%\ExplorerPatcher`
> * `C:\Windows\dxgi.dll`
> * `C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy`
> * `C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy`
>
> For Defender, you can run the following script in PowerShell as an administrator:
> ```ps1
> Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
> Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
> Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
> Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
> Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy"
> ```
> If you are downloading from this page, please temporarily disable real-time protection or save to a folder excluded from antivirus scans.
>
> Issues related to antivirus detections **will be closed immediately**. Discuss about this in #3228.

Read. For BitDefender add those paths manually in its UI.
