### ISSUE TITLE
22621.3880.66.5 Win64:MalwareX-gen [Trj]

### ISSUE THREAD

**Issue by scooller** [valinet/ExplorerPatcher#3663]
I try to install the latest version but the antivirus gives a virus alert **Win64:MalwareX-gen [Trj]**

**Comment by Amrsatrio** [comment]
Did you read the warning section in here?

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.5_5094108

**Comment by KidAmnesiac** [comment]
I also receive warnings stating that the latest update is infected by **Trojan.GenericKD.74037883**
