### ISSUE TITLE
HackTool:Win32/Patcher!MTB

### ISSUE THREAD

**Issue by NWeissenberg** [valinet/ExplorerPatcher#3665]
Windows Security reports HackTool:Win32/Patcher!MTB in file: C:\Users\NWeis\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

**Comment by falvarezr** [comment]
Kaspersky also.

**Comment by SuperBadger77** [comment]
McAfee also.

**Comment by sat515** [comment]
Kaspersky: Malware was deteced by KSN 
UDS: DangerousObject.Multi.Generic  epsetup.exe

**Comment by EscalatorMan** [comment]
McAfee reports update as a threat and blocks it

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/issues/3228

Discuss it here.
