### ISSUE TITLE
[226xx.4169+] The start menu style option: Windows 10 not working

### ISSUE THREAD

**Issue by Davidms404** [valinet/ExplorerPatcher#3667]
My last update to Windows 11 (23H2) is causing an issue with the start menu style. Only the Windows 11 option works, and selecting the Windows 10 option makes the menu disappear. 

I have the latest ExplorerPatcher update, by the way.

**Comment by milesprower2293** [comment]
Install the latest pre release:
https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.5_5094108
Before installin put the setup file in the exclusion list of your Antivirus software (Defender, Avast, etc)

**Comment by Davidms404** [comment]
> Install/reinstall the latest release: https://github.com/valinet/ExplorerPatcher/releases Before installing follow the instructions to prevent defender from removing or blocking the setup file

I tried the recommendations twice, but the same problem keeps occurring. I only use Windows Defender, added the exceptions with PowerShell and disabled Defender's real-time protection, but it still doesn't work. The only thing that isn't working is the Start menu style in the Windows 10 option. Any idea?

**Comment by pyrates999** [comment]
Please show a screen shot of you running the windows powershell script.  You probably aren't running powershell with elevated privileges.  To do that, right click on powershell and select run as administrator.

**Comment by Davidms404** [comment]
> Please show a screen shot of you running the windows powershell script. You probably aren't running powershell with elevated privileges. To do that, right click on powershell and select run as administrator.

As I mentioned earlier, I followed all the recommendations. Here’s a screenshot showing that the exceptions were added correctly. And yes, I ran PowerShell as administrator. Could it be an issue with ExplorerPatcher? 
![Sin título](https://github.com/user-attachments/assets/f2a77cdc-7038-44a4-a5b3-1013c573b11b)

**Comment by pyrates999** [comment]
That shows no errors when running the PowerShell commands. Did you see errors before?

**Comment by Davidms404** [comment]
No error appears, the rest of the program seems to work fine. Only that option doesn't work.

**Comment by pyrates999** [comment]
Install release 66.5 here: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Davidms404** [comment]
The problem persists no matter which version I install, everything was working fine until Windows 11 updated. Whenever I click on the start icon, it stays selected, but the menu doesn't appear.
![Sin título](https://github.com/user-attachments/assets/ad8696c4-cf9e-4d3b-9dae-37c9d6eba329)

**Comment by Amrsatrio** [comment]
Can you screenshot the contents of your C:\Program Files\ExplorerPatcher? And the lamguage folders inside?

**Comment by Davidms404** [comment]
> Can you screenshot the contents of your C:\Program Files\ExplorerPatcher? And the contents of the pris folder? This might be related to your Display language being anything else other than English. I also need the language code of your current display language.

The language code is es-ES and here are the screens

ExplorerPatcher folder:
![explorerpatcher](https://github.com/user-attachments/assets/c1e1adb4-fe38-4cf8-b0fb-10a4c234d641)

Pris folder: 
![pris](https://github.com/user-attachments/assets/4eb26f14-236f-4034-9b4f-78a80393c30d)

**Comment by jallenjens** [comment]
> Install/reinstall the latest release: https://github.com/valinet/ExplorerPatcher/releases Before installing follow the instructions to prevent defender from removing or blocking the setup file

I was having this issue and this fixed it for me.

**Comment by pyrates999** [comment]
> I have the same problem. OS version is Windows 11 Workstation 23H2 22631.4169. The language code is zh-CN. I've tried both 22621.3880.66.6 and 22621.3880.66.5, all not work with the start manu. Like the subject, I updated Windows a few days ago, and then explorerpatcher does not work anymore. But the difference is that I have been disabled Windows Defender instead of adding exclusion items.

Do you have another AV installed?

Try adding the excluded directories using the powershell script as well.

**Comment by Amrsatrio** [comment]
@wangyan-life If you open the details page in Task Manager, is StartMenuExperienceHost running? If yes, kill it and try opening the start menu again.

**Comment by wangyan-life** [comment]
> > I have the same problem. OS version is Windows 11 Workstation 23H2 22631.4169. The language code is zh-CN. I've tried both 22621.3880.66.6 and 22621.3880.66.5, all not work with the start manu. Like the subject, I updated Windows a few days ago, and then explorerpatcher does not work anymore. But the difference is that I have been disabled Windows Defender instead of adding exclusion items.
> 
> Do you have another AV installed?
> 
> Try adding the excluded directories using the powershell script as well.

Thanks for reply! I do not use any AV software. I also disable the SmartScreen function.

**Comment by wangyan-life** [comment]
> @wangyan-life If you open the details page in Task Manager, is StartMenuExperienceHost running? If yes, kill it and try opening the start menu again.

I reinstalled version 22621.3880.66.6. I found that when I used the Windows 11 startmenu style, the StartMenuexperIncehost process was running well and the start menu could be opened smoothly. And when I enable the startmenu style of Windows 10, the StartMenuexperientHost process will disappear. At this time, I click on the start menu button, and there will be two StartMenuexperientHost processesone, one of which is running, the other one is hunging up. At the end, the start menu will not have any reactions, and the mouse pointer will be stuck. I think this is the problem ...
<img width="910" alt="1" src="https://github.com/user-attachments/assets/badab8f3-2d9e-4a86-9f6d-0d73c5d8851a">

**Comment by pyrates999** [comment]
kill both processes named StartMenuExperienceHost.exe

**Comment by IssacKramer** [comment]
Same Problem to me after upgrading to windows 22631.4169  - Start button for win10 style stopped working.
(only right click of it working - left click not.
Installed 66.5 and 66.6 version and same behavior.
There is a strange GAP near windows start and the taskbar as showing in pic.
Worked good before windows update last week.
![image](https://github.com/user-attachments/assets/f0773957-9e1b-4dfa-81d6-c1a52ff7d193)

**Comment by azerik92** [comment]
I don't even have the option for Start Menu style anymore. It's just completely gone.

**Comment by pyrates999** [comment]
> I don't even have the option for Start Menu style anymore. It's just completely gone.

Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

**Comment by azerik92** [comment]
> > I don't even have the option for Start Menu style anymore. It's just completely gone.
> 
> Please post windows version and build. You can find this by running winver. Please include if you are running x86-64 or Arm. And what language your windows is in. Please post explorer patcher version.
 
 23H2 build 22631.4169 Windows 11 Pro
 
 English United States
 
 Followed instructions to update to the most recent version of Explorer Patcher when I noticed Windows updating last night broke the start menu. Have tried everything in this thread so far.

**Comment by wangyan-life** [comment]
> 杀死名为 StartMenuExperienceHost.exe 的两个进程

Thanks for reply! But...No need to turn it off manually. Whenever I click the start menu button, it will run it by itself and automatically close it after 1 second.

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by azerik92** [comment]
> Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**. We no longer offer more support on the stock Windows 10 taskbar.

Yes I've seen that and chosen that option, it still doesn't work for me. My short term solution is installing StartAllBack and using it's taskbar for now, so long as I have the working EP Start10 menu I'll make due.

**Comment by Amrsatrio** [comment]
@pyrates999 He wants to have the 10 start menu again. It is not related at all with the taskbar.

@azerik92 Update to 66.4 or newer to have the 10 start menu *somewhat* back again. This month's patch nuked it from the system files. Make sure to follow the instructions for configuring your antivirus.

**Comment by Amrsatrio** [comment]
Also, change your taskbar to Windows 10 (ExplorerPatcher) and restart Explorer. If it doesn't work, I will have to investigate otherwise it is a user error.

**Comment by azerik92** [comment]
> @azerik92 Update to 66.4 or newer to have the 10 start menu _somewhat_ back again. This month's patch nuked it from the system files. Make sure to follow the instructions for configuring your antivirus.

66.6 didn't have a working Start10 menu for me, and neither did 66.5 initially until I switched to an insider preview build of Windows. I had the folders as exceptions in Windows Defender throughout that whole process, so it was something about 22631.4169 specifically breaking EP for me.

> Also, change your taskbar to Windows 10 (ExplorerPatcher) and restart Explorer. If it doesn't work, I will have to investigate otherwise it is a user error.

The "Windows 10 (ExplorerPatcher)" taskbar option only has partial functionality for me at the moment. It regularly ignores the "Always Combined" setting for taskbar icons until I turn it off then on, and occasionally on boot will just default to the Win11 taskbar.

**Comment by Amrsatrio** [comment]
I have investigated further and found that the issue is caused by some weird conditions in the UWP app system which prevents reading C:\Program Files *for some users*. In the next update I will move the resource files to the StartMenuExperienceFolder so that it will work for all. Stay tuned.

**Comment by Amrsatrio** [comment]
> It will also reset my taskbar position on boot every time without fail.

@azerik92 https://github.com/valinet/ExplorerPatcher/issues/3719

Will consider it in a future build.

**Comment by pivov** [comment]
Hi, is there any temporary solution till the moment will be developed new version of ExplorerPacher?

**Comment by pivov** [comment]
Hi, can someone to hep my with it?

**Comment by ecceMatth** [comment]
Have (had?) the same issue. At some point I launched the installer "ep_setup.exe" as an administrator. And now it works. I don't know if that's what did it, but I thought I'd let you know.
ExplorerPatcher V 22621.3880.66.6
Windows 11 23H2 22631.4317 fr-fr

**Comment by pyrates999** [comment]
Start menu style set to windows 10 works in english versions of windows right now, but not chinese.

**Comment by Davidms404** [comment]
The problem was fixed in the lastest update.

**Comment by Davidms404** [comment]
The problem was fixed in the lastest update.

**Comment by Amrsatrio** [comment]
Just want to add in case anyone else still have non-working 10 start menu.

The advanced permissions for Program FIles should look like this:

<img width="384" alt="image" src="https://github.com/user-attachments/assets/a9bab078-9917-40c0-b789-67de53218409">

If it's different, then I suggest to do an in-place upgrade, or even better, a clean install.
