### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by JustThat70** [valinet/ExplorerPatcher#3668]
From the console:

[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Using hardcoded hash.
[Updates] Checking against hash "22622.3880.66.5.320c4bb6f886ecab"
[Updates] Update URL: /download/ep_setup.exe
[Updates] Unable to check for updates because the remote server is unavailable.

I am on the internet and this worked up until I manually updated to this release. I've disabled the firewall and that does not resolve the issue

**Comment by Amrsatrio** [comment]
Check if notifications for Explorer are enabled.

**Comment by PierrotIV** [comment]
Same here:
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Using hardcoded hash.
[Updates] Checking against hash "22622.3880.66.5.320c4bb6f886ecab"
[Updates] Update URL: /download/ep_setup.exe
[Updates] Unable to check for updates because the remote server is unavailable.

![Capture d'écran 2024-09-11 091016](https://github.com/user-attachments/assets/3e96e364-b2b8-432d-b9bb-9be844604468)

It happens since I applied #3228

**Comment by pyrates999** [comment]
are you at a work network?

**Comment by PierrotIV** [comment]
> are you at a work network?

Home but similar to a professional network.

**Comment by pyrates999** [comment]
Check your network then.  And if you're going through a proxy, that might be blocking this.

**Comment by PierrotIV** [comment]
> Check your network then. And if you're going through a proxy, that might be blocking this.

That was a good thought but:
- it worked perfectly well before 22622.3880.66.5 update
- no proxy here

Btw I checked and no dns request is sent when trying to check for updates, meaning the problem doesn't "get out" from the OS.

Other point I checked, I'm using Kaspersky as AV and firewall. I disabled it, meaning Windows Defender activates itself in place of Kaspersky, and that doesn't change the issue.

**Comment by pyrates999** [comment]
Then disable Defender.

**Comment by PierrotIV** [comment]
> Then disable Defender.

No change

**Comment by JayKay-Gitz** [comment]
Same issue here since updating to latest version.  "Unable to check for updates"

- Was working prior to 22621.3880.66.5 update
- No vpn, proxy, other issues with network connections

**Comment by pyrates999** [comment]
Did you disable windows firewall?  And then try to check for updates?

**Comment by PierrotIV** [comment]
> Did you disable windows firewall? And then try to check for updates?

I did, no change.

**Comment by Amrsatrio** [comment]
Alright, I'll admit that I changed some stuff in the updater code so something might have slipped. If you don't mind helping me in troubleshooting the issue, does deleting the UpdateURL key fix it?

**Comment by PierrotIV** [comment]
> Alright, I'll admit that I changed some stuff in the updater code so something might have slipped. If you don't mind helping me in troubleshooting the issue, does deleting the UpdateURL key fix it?

No problem.
Update was not working because HKEY_CURRENT_USER\Software\ExplorerPatcher\UpdateURL was empty.
Filling it with https://github.com/valinet/ExplorerPatcher/releases/latest did restore update functionality.

**Comment by JayKay-Gitz** [comment]
> Alright, I'll admit that I changed some stuff in the updater code so something might have slipped. If you don't mind helping me in troubleshooting the issue, does deleting the UpdateURL key fix it?

I had already changed the key, but i just tried deleting the key and the update function is still working.  Not sure if that would be the case if someone hadn't updated and tested it prior to deleting.

**Comment by Amrsatrio** [comment]
Okay so the problem is if that key is present but empty then the updater won't work. Will fix it tomorrow.

**Comment by ARM07470** [comment]
I just deleted the key, restarted File Explorer and updates worked.  Put it back w/no value and it stopped working.  So, yes, the issue is if the key is present but empty.  I never touched that key before, so I'm not sure when it got added w/a null value.

**Comment by s-renz** [comment]
> does deleting the UpdateURL key fix it?

Yes. Just deleting it, without changing anything first, does fix it

**Comment by Apocalypse612** [comment]
Same issue here after running the .ps1 script provided to allow all EP updates through the Windows Defender firewall. Since the last update was complaining. I ran the script, then got the update, then this error occurred. Can confirm delete the reg key listed above fixed the issue.

**Comment by Amrsatrio** [comment]
Promoted 66.6 into release - should fix the updates issue. Sorry for those who updated to 66.5 and used the Restore default settings in the past. I'll pin this.
