### ISSUE TITLE
Microsoft Windows Security flagging latest update as a virus

### ISSUE THREAD

**Issue by topwizprogramming** [valinet/ExplorerPatcher#3669]
[Window Title]
C:\Users\topwi\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

[Content]
C:\Users\topwi\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Comment by Thetechoftacos** [comment]
Read the front page

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/issues/3228#issuecomment-2094065943
