### ISSUE TITLE
Win+X shotrcut doesn't work in ExplorerPatcher's taskbar implementation

### ISSUE THREAD

**Issue by Juriyx** [valinet/ExplorerPatcher#3671]
Hello. Thank you for your great taskbar!

Although in the current stable version of ExplorerPatcher with your taskbar implementation chosen, Win+X shortcut doesn't open the standard Win 10/11 menu. Instead, it selects the first window on the taskbar:
![2024-09-11_132818](https://github.com/user-attachments/assets/36107852-1383-49db-b233-cfe6b5787395)

**Comment by Amrsatrio** [comment]
Yes, known limitation. You can keep this open until I fix it.

**Comment by RoyiNamir** [comment]
same here. shows rectangles : 
![image](https://github.com/user-attachments/assets/32cbb83e-7eb8-45e0-8cd7-c77acdd8d091)

**Comment by wikiepeidia** [comment]
it also happened to me on LTSC 24 26100.1301 , and on version LTSC 24 26100.1702 right clicking the start button also acts like win X problem(each right click point to another app on taskbar...), whereas you still can open the win x menu on 1301 by right clicking it.

**Comment by frog1014** [comment]
same on 
版本	23H2
安裝於	‎2023/‎6/‎20
OS 組建	22631.4249
體驗	Windows Feature Experience Pack 1000.22700.1041.0

**Comment by rolojeldres** [comment]
in version 22621.3880.66.6 right click is opening the win x menu. thanks for the app!

**Comment by Waytoogo** [comment]
I found that the problem only happens if I have Open Shell installed. If I uninstall open shell my win+x menu works fine with the new windows 10 taskbar. The new taskbar and Open Shell don't play well together.

**Comment by m0rkeulv** [comment]
If `right click opens Win + X menu` is enabled in Open Shell, right clicking start button will  en up just looping trough your open apps taskbar previews. if disabled the Open shell context menu opens. This does not happen with StartAllBack so  i belive it should be possible to fix

![openshell](https://github.com/user-attachments/assets/637c5149-4853-4eaf-a477-05334094b652)

**Comment by christianbearslyclark** [comment]
Agreed....It should be fix......Start11  and WinX  works Great.

**Comment by rolojeldres** [comment]
I don't have  Open Shell installed and EP still does not work with win+x, just going though the taskbar apps icons.

**Comment by pyrates999** [comment]
Did no one read the second comment?

**Comment by Amrsatrio** [comment]
Fixed in 66.7. It is now being built.

**Comment by christianbearslyclark** [comment]
.... the new Update works great with WinX....Thank You.   

 It was a pain.    😆

Windows 11  24H2   26100.2161
