### ISSUE TITLE
ExplorerPatcher Update 3880.66.5 triggers Windows Security virus notification on Win 11 23H2

### ISSUE THREAD

**Issue by DJ1951** [valinet/ExplorerPatcher#3672]
ExplorerPatcher version 22621.3880.66.5 update will not install -  Windows Security is providing a notification that https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe contains a virus or potentially unwanted software. I'm running Windows 11 Pro 23H2 with all updates installed.

**Comment by milesprower2293** [comment]
> ExplorerPatcher version 22621.3880.66.5 update will not install - Windows Security is providing a notification that https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe contains a virus or potentially unwanted software. I'm running Windows 11 Pro 23H2 with all updates installed.

That's a false positive, Microsoft doesn't want users to use the Windows 10 shell on 11.
try putting ep_setup.exe on the exclusions

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges.

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

**Comment by Amrsatrio** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

**Comment by DJ1951** [comment]
Thanks for the suggestion! Ep_setup.exe didn't survive the Windows Security
action and notification on my computer, so, in order to circumvent this
false positive, I had to exclude the folder that ep_setup.exe is
(temporarily) stored in while updating (apparently you can't put a file
exclusion in for Windows Security if the file doesn't exist to be found and
put in the Exclusions list). Note that I haven't ever had this issue before
with updating ExplorerPatcher, and my computer always had Win 11 Pro
running since I purchased it new, so unless the most recent changes to
Windows 11 have specifically targeted apps like ExplorerPatcher to prevent
updates, there may be a hidden issue. Kudos to the author of this software;
I support a number of senior citizens that don't prefer to update the "look
and feel" of their computer's UI just because Microsoft thinks that's the
appropriate thing to do.
