### ISSUE TITLE
Issue installing updates.

### ISSUE THREAD

**Issue by zabersan** [valinet/ExplorerPatcher#3673]
I'm having an error issue when trying to update the program, it downloads everything but when it goes to install them, powershell throws so many errors. I have added those exceptions told by the github page in the antivirus, but that didn't work.

https://github.com/user-attachments/assets/df8f8cf0-1ffe-4630-81c9-c1e7cc1121c3

OS: Windows 11 23H2 (Build 22631.4112)

ExplorerPatcher Version: 22621.3527.65.5

PC Specs (incase this is needed):

```
Brand:	MSI
Model:	Aegis R 13NUE-458US
CPU: Intel Core i7-13700F 2.10 GHz
RAM: 16 GB DDR5 (2 x 8 GB) 4800 MHz
Storage: 2 TB M.2 NVMe Gen3 SSD
PSU: 650W 80 PLUS Gold
Cooling System:	RGB Fan Cooling
OS: Windows 11 Home 64-bit
Mobo: MSI PRO B760-VC WIFI
CPU: Intel Core i7 13th Gen Intel Core i7-13700F
GPU: GeForce RTX 4070
Storage:
SSD: 2 TB PCIe
SSD: 1 TB
HDD: 2 TB
HDD: 500 GB
HDD: 250 GB

Monitor 1: LS24AG30x
Resolution: 1080p @ 3840 x 2160 HD
Refresh rate: 144 Hz

Monitor 2: E320-A0
Resolution: 1080p
Refresh rate: 60 Hz

Monitor 3: Inspiron 3263
Resolution: 1080p @ 3840 x 2160 HD
Refresh rate: 60 Hz

```

**Comment by princessgiggles** [comment]
Windows defender is preventing install because of a potential virus??  HackTool:Win32/Patcher!MTB

**Comment by zabersan** [comment]
> Windows defender is preventing install because of a potential virus?? HackTool:Win32/Patcher!MTB

it shouldn't be because i've added it as an exception.

**Comment by Lyhtande** [comment]
I have the same issue with Bitdefender virus scanner:

![ep](https://github.com/user-attachments/assets/8fabe4e9-b798-4b17-b9d5-f354e9260382)

**Comment by zabersan** [comment]
It's more so an issue if it not building the update, idk how else to screenshot the powershell window, as when I go to try and copy the text and stuff it closes the window. Only other thing i can think of would be if it made a log file, and idk where that'd be. Apologies, I'm not very good at making bug reports.

**Comment by zabersan** [comment]
Nvm, I did not see there was a toggle. Apologies for wasting anyones time.
![Screenshot 2024-09-11 144050](https://github.com/user-attachments/assets/15a09de8-c7f1-4fe9-a48e-e062152c2692)
![Screenshot (22)](https://github.com/user-attachments/assets/ce2238cd-247f-4016-9607-480ed395b1de)
