### ISSUE TITLE
Hide the gear in Windows 10 style taskbar

### ISSUE THREAD

**Issue by Foeglas** [valinet/ExplorerPatcher#3675]
First, the Windows 11 default taskbar style for comparison:
<img width="166" alt="{1E0C6285-04EA-472E-8006-1F225BB5D9E3}" src="https://github.com/user-attachments/assets/adfe71fb-5801-4ab9-aa91-dc06bf2ca585">
Now Windows 10 or Windows 10 (ExplorerPatcher) style:
<img width="204" alt="{1299A23D-8C83-4289-9B30-1836C0EE175D}" src="https://github.com/user-attachments/assets/4040e1c9-274b-4afa-beff-adbc4d20d2d0">
I'm probably just blind but I can't find a setting to hide the new gear icon between volume and time. "Customize notification area icons" only includes Power, Network, Volume, and tray icons. "Turn system icons on or off" includes Clock, Volume, Meet Now (grayed out), Microphone, Network, Power, Input Indicator, and Action Center, and none of those seem to affect the gear either.

**Comment by Amrsatrio** [comment]
Find "Hide control center button" in EP properties.
