### ISSUE TITLE
Fatal Error LNK1104

### ISSUE THREAD

**Issue by Divisionic** [valinet/ExplorerPatcher#3680]
When updating Explorer Patcher to it's newest update, it fails with this message:

```
"C:\Users\user\AppData\Roaming\ExplorerPatcher\ep_make\repo\ExplorerPatcher.sln" (clean;Build target) (1) ->
"C:\Users\user\AppData\Roaming\ExplorerPatcher\ep_make\repo\ExplorerPatcher\ExplorerPatcher.vcxproj.metaproj" (default target) (14:3) ->
"C:\Users\user\AppData\Roaming\ExplorerPatcher\ep_make\repo\ExplorerPatcher\ExplorerPatcher.vcxproj" (default target) (15:3) ->
(Link target) ->
LINK : fatal error LNK1104: cannot open file 'funchook.lib' [C:\Users\user\AppData\Roaming\ExplorerPatcher\ep_make\repo\ExplorerPatcher\ExplorerPatcher.vcxproj]

1731 Warning(s)
1 Error(s)
```

Not sure what to do here.

Here are my Windows Specifications:

- Windows 11 Home
- 23H2
- 22631.4169
- Windows Feature Experience Pack 1000.22700.1034.0

**Comment by Amrsatrio** [comment]
Turn off "Build updates locally before installing" in EP properties > Updates.

I may have forgotten to push an update to ep_make because I changed something in the build process of EP to facilitate builds for ARM64.

**Comment by Divisionic** [comment]
> Turn off "Build updates locally before installing" in EP properties > Updates.
> 
> I may have forgotten to push an update to ep_make because I changed something in the build process of EP to facilitate builds for ARM64.

That did indeed fixed it!
Biggest problem was trying to workaround Windows Defender, but other than that, it worked flawlessly!
Thank you very much, this ticket can be closed now.
