### ISSUE TITLE
Inquiries about use

### ISSUE THREAD

**Issue by 4naE** [valinet/ExplorerPatcher#3681]
If you display the left side of the taskbar, the date is not displayed on the clock.
Is there a setting that enables date display?

![image](https://github.com/user-attachments/assets/5232a68d-2523-46e6-9a89-ff631fa29328)

In addition, the secondary monitor does not display the system tray.
Is there a way to display the system tray the same as the main monitor?
![image](https://github.com/user-attachments/assets/625b7b63-f7a8-4065-b84f-fc7d002e1343)

**Comment by Amrsatrio** [comment]
Right click the taskbar to unlock it. Resize it to be a little bit bigger to have the date shown.

**Comment by 4naE** [comment]
It's been resolved.
Thank you very much for your kind reply.

Is there a way for the system tray to show on secondary monitor just like one main monitor?

(one monitor)
![image](https://github.com/user-attachments/assets/6a0146a4-0a75-4ae5-a5e6-620649fafbb0)

(secondary monitor)
![image](https://github.com/user-attachments/assets/6f669d46-433d-48f3-8f52-ed1d172d12d6)
