### ISSUE TITLE
Win 10 Start Menu doesn't work after installing 22631.4169

### ISSUE THREAD

**Issue by genlosha** [valinet/ExplorerPatcher#3686]
After updating to 23H2 (22631.4169), the Windows 10 Start Menu doesn't open at all. 

The loading indicator appears near my cursor for 1 second and that's all.

The Windows 11 Start Menu works fine. 

I tried both the latest pre-release and the latest release, with the same result. 

Happening on both my computers.

**Comment by afargnoli-ops** [comment]
My PC updated to 22H2 (22631.4169) yesterday, and I had to uninstall Explorer Patcher to be able to use right-clicks on icons in the taskbar. Any idea whether and when this can be fixed? (BTW, before uninstalling, I did a check for updates in Explorer Patcher. Let me add that Microsoft really hates Explorer Patcher.)

**Comment by genlosha** [comment]
> My PC updated to 22H2 (22631.4169) yesterday, and I had to uninstall Explorer Patcher to be able to use right-clicks on icons in the taskbar. Any idea whether and when this can be fixed? (BTW, before uninstalling, I did a check for updates in Explorer Patcher. Let me add that Microsoft really hates Explorer Patcher.)

**Comment by genlosha** [comment]
> > My PC updated to 22H2 (22631.4169) yesterday, and I had to uninstall Explorer Patcher to be able to use right-clicks on icons in the taskbar. Any idea whether and when this can be fixed? (BTW, before uninstalling, I did a check for updates in Explorer Patcher. Let me add that Microsoft really hates Explorer Patcher.)

Can confirm your issue while using Windows 11 Taskbar

**Comment by Amrsatrio** [comment]
Update your EP.

**Comment by afargnoli-ops** [comment]
It is easy to reproduce. It only got broken yesterday (so it's not stale). If this is a duplicate, you need to link what it's a duplicate of. All that's left is that you stubbornly refuse to fix it. What am I missing?

**Comment by Amrsatrio** [comment]
66.5 works if you meant by the jump list clipping or not showing when right clicking taskbar buttons whem the taskbar is not at the bottom. Make sure you configure the antivirus.

**Comment by afargnoli-ops** [comment]
Terima kasih. Saya akan mencoba mengonfigurasi antivirus.

**Comment by afargnoli-ops** [comment]
My laptop is running CrowdStrike Falcon and I see no way for me to add to an exclusion list. I guess Microsoft won this round.

**Comment by Amrsatrio** [comment]
https://github.com/Amrsatrio/ExplorerPatcher/releases/tag/22621.3880.66.6_92fce8c

Download this build in my fork.

**Comment by genlosha** [comment]
> https://github.com/Amrsatrio/ExplorerPatcher/releases/tag/22621.3880.66.6_92fce8c
> 
> Download this build in my fork.

Didn't help with Win 10 Start Menu not working

**Comment by Amrsatrio** [comment]
@genlosha What's your display language?

**Comment by genlosha** [comment]
> @genlosha What's your display language?

English US

**Comment by Amrsatrio** [comment]
Cam tou screenshot the contents of your C:\Program Files\ExplorerPatcher folder?

**Comment by genlosha** [comment]
> Can you screenshot the contents of your C:\Program Files\ExplorerPatcher folder?

![explorer_8chE7iSxpb](https://github.com/user-attachments/assets/a7ab8eae-480a-45ac-9d8d-263d40616743)

**Comment by Amrsatrio** [comment]
What's inside the pris folder?

**Comment by genlosha** [comment]
> What's inside the pris folder?

Windows.UI.ShellCommon.en-US.pri

**Comment by Amrsatrio** [comment]
Yeah this is weird. I do not know why it doesn't work on your end. What I can say is the patch that was released yesterday obliterated the old start menu. And the countermeasures in EP don't work on your Windows install.

**Comment by genlosha** [comment]
> Yeah this is weird. I do not know why it doesn't work on your end. What I can say is the patch that was released yesterday obliterated the old start menu. And the countermeasures in EP don't work on your Windows install.

Fully uninstalled EP, changed display language back and forth, installed the build from your fork and it works now :/

**Comment by afargnoli-ops** [comment]
Terima kasih banyak! Ini bekerja seperti pesona, dan saya tidak perlu mengubah pengaturan apa pun.
