### ISSUE TITLE
Bug: start menu behind vertical taskbar

### ISSUE THREAD

**Issue by anatoliy-savchak** [valinet/ExplorerPatcher#3688]
On Windows 11 Pro (23H2 / 22631.4169) when I have right vertically aligned docking of the taskbar in Windows 10 mode, when Windows keyboard button pressed the Start menu will appear behind taskbar effectively hiding certain portion of that window.

Current workaround is to focus (by mouse clicking) on taskbar, point mouse cursor on taskbar and only then press Win key on kb.

![image](https://github.com/user-attachments/assets/82b9c4ae-9dbf-4c0b-82b4-b71fe6997cf4)

**Comment by Amrsatrio** [comment]
Outdated EP.

**Comment by anatoliy-savchak** [comment]
@Amrsatrio you were right. Updating EP fixed these issues, thanks!
