### ISSUE TITLE
ExplorerPatcher v22621.3880.66.5 - no action and no resulting installation

### ISSUE THREAD

**Issue by theCountIsContinuing** [valinet/ExplorerPatcher#3689]
Running Win 11 Home 23H2  OS Build 22631.4169
i've been using ExplorerPatcher for several years and appreciate your work developing it!!

i wanted to update the appl, so i read the info about antivirus configuration instructions and updated Windows Defender as recommended. then i downloaded ep_setup.exe from https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.5_5094108 - no warnings from WinDefender.

i went to the downloaded folder on my system and double clicked the ep_setup.exe to open it.
The cursor turned into a spinning circle for a few seconds then changed back to an arrow.
No prompt for UAC, no install dialogs, nothing!
Windows taskbar remains as Windows 11 created it.

any ideas or suggestions?
thanks.

**Comment by Amrsatrio** [comment]
Did your screen go dark? Maybe SmartScreen or something else is blocking it.

**Comment by pyrates999** [comment]
did you run the powershell commands to exclude the directories to be able to install EP?

do you have another AV installed?

**Comment by atani21** [comment]
Same issue here. No SmartScreen or anything of the sort installed. Used to be able to install ExplorerPatcher by directly running ep_setup.exe. For some reason, the latest exe would not work.

**Comment by pyrates999** [comment]
If you have smartscreen set to block exe's that are not signed, that is what may occur.

**Comment by Amrsatrio** [comment]
@atani21 Maybe the setup crashed. Check event viewer > application and find for an error entry that says ep_setup.exe inside.

**Comment by atani21** [comment]
Got it. It really was Windows Defender's SmartScreen blocking it, even though I added the exe to exclusion from Antivirus. Thanks.

**Comment by theCountIsContinuing** [comment]
hey folks, thanks for info and suggestions.
some answers.

1. Did your screen go dark? ==> it did go dark when finally got it running. but w/ the older version, when opening ep_setup.exe to install, no visible or behind the scenes actions/results whatsoever.

2. Maybe SmartScreen or something else is blocking it ==> i used Chrome to download ep_setup.exe, so SmartScreen is not applicable here.  Once it downloaded, Windows Defender detected the "malware". i followed the instructions about adding ExplorerPatcher folders to the WD exclusion list. The .exe is now able to be opened, just nothing happens.

3. Only have Windows Defender running.

4. i checked the event viewer but couldnt find any events related to ep_setup.exe

5. fortunately, i downloaded a prior ExplorerPatcher version, installed it w/out problems and it runs w/out problems. that version even auto-updated itself to 22621.3880.66.6 which continues to run w/out problems.

thanks for the info and help!

**Comment by pyrates999** [comment]
SmartScreen is used when you try to run an exe, not download it.  Please check your smartscreen settings so that it allows unsigned exe's.

Please see release notes here for the powershell commands to run: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment]
Is still an issue with latest 67.1?

**Comment by Amrsatrio** [comment]
Closing due to no repro and no response.
