### ISSUE TITLE
explorer.exe keeps crashing unless patcher temporarily disables itself

### ISSUE THREAD

**Issue by VirgilMing** [valinet/ExplorerPatcher#3690]
`winver`: windows 11 pro workstation, 22631.4169
patcher: 22621.3880.66.5

I followed the note about excluding related paths for defender on release page. 
I also read 

> with EP installed, when it happens again:
> 1. open up windows event viewer or computer management
> 2. go to Event Viewer and go to Windows Logs -> Application
> 3. copy and paste the log of explorer.exe crashing here
>
> _Originally posted by @pyrates999 in https://github.com/valinet/ExplorerPatcher/issues/3661#issuecomment-2343839587_

and I found no event from `explorer.exe` at all, but only `info` from `Winlogon`. The general page roughly says (my system is Chinese and so is this message, not quite sure about the translation) "shell program accidentally exits, C:\Windows\system32\userinit.exe is restarted". [One example of detailed info](http://www.pastebin.com/bTKkA4YS), only time and EventRecordID changes.

I also enabled explorer console, but the command window closes before I can see anything that seems helpful.

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
Please uninstall ExplorerPatcher and see if the crashes continue.

**Comment by VirgilMing** [comment]
> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.
> 
> Please include any other software you have installed that modifies the UI of windows.
> 
> Do you have another AV installed?

It was a fresh installation of ExplorerPatcher directly downloaded here. The crash happened immediately after initial installation. I hadn't changed anything inside the ExplorerPatcher property.  
Just in case, I manually edited registry to restore old-school right-click context menu before installing ExplorerPatcher.

There were some other software installed indeed, but they were laptop's OEM software (Honor Magicbook Art 14, some AI-related productivity software, if that matters), and I *think* there shouldn't be any other antivirus. At least not on program list in "win+i" settings.

> Please uninstall ExplorerPatcher and see if the crashes continue.

Not anymore. I saw that dialog after crashing in 10 sec consecutively 3 times, which said ExplorerPatcher temporarily disables itself, and then explorer.exe seemed to be working just fine. 

One more thing that came to me: I tried editing properties controlling start menu to win10-style. After crashing three times and self-disabling, this change seemed to persist and explorer.exe didn't complain.

------

Yet another note: this machine is actually not mine, and I have no idea if I can have any other chance to do more field test.

**Comment by pyrates999** [comment]
> Just in case, I manually edited registry to restore old-school right-click context menu before installing ExplorerPatcher.

Please post what registry changes you made here.

**Comment by Amrsatrio** [comment]
Try uninstalling your current version and install 65.5.

**Comment by VirgilMing** [comment]
> > Just in case, I manually edited registry to restore old-school right-click context menu before installing ExplorerPatcher.
> 
> Please post what registry changes you made here.

`reg add "HKCU\SOFTWARE\CLASSES\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve`

I believe this was the change.

**Comment by pyrates999** [comment]
Delete that registry key, reboot, and then install EP.  Does it happen then?

**Comment by localhosted** [comment]
> reg add "HKCU\SOFTWARE\CLASSES\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve

I've just added this entry before installing ExplorerPatcher and I had no crash. Everything is working fine

**Comment by pyrates999** [comment]
> > reg add "HKCU\SOFTWARE\CLASSES\CLSID{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve
> 
> I've just added this entry before installing ExplorerPatcher and I had no crash. Everything is working fine

what version of EP did you install?

**Comment by Amrsatrio** [comment]
Is EP still crashing on your end?

**Comment by Amrsatrio** [comment]
Closing due to no response.
