### ISSUE TITLE
Maximized Windows Hides Bottom Portion Under Taskbar

### ISSUE THREAD

**Issue by numeralnathan** [valinet/ExplorerPatcher#3694]
I have 3 monitors.  The main monitor and the second monitor do not have this problem.  The third monitor allows for maximized windows to show up behind the taskbar.  This makes accessing the bottom portion of the window impossible because the taskbar is over it.

**Comment by pyrates999** [comment]
Update EP.

**Comment by Amrsatrio** [comment]
This seems like it has been reported before. The solution is to restart Explorer. @pyrates999 I did not make attempts to fix this bug.

**Comment by numeralnathan** [comment]
The update seemed to have fixed the problem.

**Comment by pyrates999** [comment]
Oh I thought it was the same as the start menu showing on top of the task bar.
