### ISSUE TITLE
No Toolbars / QuickLaunch on Win 11 LTSC 2024

### ISSUE THREAD

**Issue by metal450** [valinet/ExplorerPatcher#3696]
Just trying out ExplorerPatcher on Win 11 IoT Enterprise LTSC 24H2, build 26100.1742. I'm using EP 22621.3880.66.6.

When I right-click the taskbar, the only options are:
Cascade Windows
Show windows stacked
Show windows side by side
Show the desktop
Task Manager
Properties
Taskbar Settings

I can't find any way to add Toolbars (for Quick Launch). Is this a known issue? Is there any way to get QuickLaunch?

**Comment by pyrates999** [comment]
did you do this?

Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by Amrsatrio** [comment]
Use Windows 10 (ExplorerPatcher) taskbar. Toolbars will not be added to the 11 taskbar.

**Comment by metal450** [comment]
Ahhh that's it, thanks! It wasn't really clear from the UI that that was even a dropdown - just looked informational. But the plaintext is indeed a dropdown, changing that & rebooting fixed it. Thanks :)

**Comment by Amrsatrio** [comment]
I know the old GUI is soooo simple and is really due for a revamp.....

**Comment by kenvix** [comment]
When I upgraded to the 24H2, I was confused by the text on the EP's UI and interpreted it to mean that “Explorerpatcher doesn't yet support the use of the win10 style taskbar on the 24H2” until I saw this posting. I think the text on the UI may need some updating.

**Comment by pyrates999** [comment]
> When I upgraded to the 24H2, I was confused by the warning text on the EP's UI and interpreted it to mean that “Explorerpatcher doesn't yet support the use of the win10 style taskbar on the 24H2” until I saw this posting. I think the text on the EP‘s UI may need some updating.

You should uninstall EP before doing upgrades.
