### ISSUE TITLE
unable to install latest version 22621.3880.66.6 with error: "... caused by one or more of the backup files from previous update still being in use. unloacking the files should fix this issue."

### ISSUE THREAD

**Issue by iwan1979** [valinet/ExplorerPatcher#3702]
Hi,

Was excited to install this latest v22621.3880.66.6. but then keep hitting this error (1st screenshot) although i have turn off the shell extension and rebooted my laptop for several times.
Currently i am on v22621.3527.65.5 with Win11 Pro 23H2 as shown on 2nd screenshot.
Kindly advice how to resolve this issue.

Thanks

![20240915_143941](https://github.com/user-attachments/assets/b5cea8fa-e1d0-47e5-8ded-a4e98c085147)
![20240915_145531](https://github.com/user-attachments/assets/7ae3c5c1-b903-4988-b3ca-2d492cf52dc7)

**Comment by pyrates999** [comment]
did you do what it said to do?

**Comment by iwan1979** [comment]
yes and rebooted few times without any success. infact installing from the manual downloaded ep_setup.exe or via the update in property's screen were encountered with same error windows.

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another AV installed?

**Comment by iwan1979** [comment]
Hi.

I resolved the issue by uninstalling the old one and reinstall the new version.
I don't install any software that modified the windows' UI as i only use explorerpatch for that purpose.
Anyway, we can close this case by now.

Thanks
