### ISSUE TITLE
V 22621.3880.66.6

### ISSUE THREAD

**Issue by Bermudagirl52** [valinet/ExplorerPatcher#3706]
Unable to download as Windows Security says it's a severe trojan. If I have to remove ExplorerPatcher, how do I do that?

**Comment by 4NXIE7Y** [comment]
same issue
![image](https://github.com/user-attachments/assets/20a4e8c8-908c-4a54-81bf-9c3878ce6147)

**Comment by 4NXIE7Y** [comment]
> same issue ![image](https://private-user-images.githubusercontent.com/98228741/367616907-20a4e8c8-908c-4a54-81bf-9c3878ce6147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Mjg3NDAsIm5iZiI6MTcyNjQyODQ0MCwicGF0aCI6Ii85ODIyODc0MS8zNjc2MTY5MDctMjBhNGU4YzgtOTA4Yy00YTU0LTgxYmYtOWMzODc4Y2U2MTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE5MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMDE5NGU1NTYzOGRiY2JlYmI2YTRhNDdkZDhkODVjNmM4OGY3MzBlMmFkOWRjMWI4MDI4MzE4YzEwNzUyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VTT9AvMkbRu0fLYOTnpLUOTnIli8aW3BwHoaXFlUpEo)

https://github.com/valinet/ExplorerPatcher/issues/3228#issuecomment-2094065943 this solves everything

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

All builds of EP are done by github build servers against the source code in the repo.  Only binary is the reimplemented windows 10 taskbar and windows 10 start menu files.  There is no third party build servers.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges.

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.
