### ISSUE TITLE
EP stopped working on Win11 today

### ISSUE THREAD

**Issue by GronbergInfo** [valinet/ExplorerPatcher#3709]
EP: 22621.3880.66.3

Edition	Windows 11 Enterprise
Version	23H2
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by pyrates999** [comment]
Install latest release as you are running a pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by pyrates999** [comment]
> The latest release is also detected by Defender as malicious: https://www.virustotal.com/gui/file/1c4e1847c722db18d58216c43aa40ad87c8a38aa6196e69d55c0687b8506bf94 https://www.virustotal.com/gui/file/f23419768ecc7a906df026ae45d92270544d08f743090186bd7e3f7592e2dd6f
> 
> Same Windows version & OSBuild, definition versions as follows:
> 
> AntispywareSignatureLastUpdated: 16/09/2024 04:15:04 AntivirusSignatureLastUpdated: 16/09/2024 04:15:01 NISSignatureLastUpdated: 16/09/2024 04:15:01 AMEngineVersion: 1.1.24070.3 AMProductVersion: 4.18.24070.5 AMServiceVersion: 4.18.24070.5 AntispywareSignatureVersion: 1.417.732.0 AntivirusSignatureVersion: 1.417.732.0 NISEngineVersion: 1.1.24070.3 NISSignatureVersion: 1.417.732.0 QuickScanSignatureVersion: 1.417.641.0

Already discussed here: https://github.com/valinet/ExplorerPatcher/issues/3228

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

All builds of EP are done by github build servers against the source code in the repo.  Only binary is the reimplemented windows 10 taskbar and windows 10 start menu files.  There is no third party build servers.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges.

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.

**Comment by ziqingyi** [comment]
yes
