### ISSUE TITLE
BitDefender does not like the new update system

### ISSUE THREAD

**Issue by zme-ul** [valinet/ExplorerPatcher#371]
BitDefender Free blew a gasket when I tried to auto-update ExplorerPatcher to 22000.318.37.2

**Comment by sisericm** [comment]
Prior to this update, there was a note on the README about A/V false postives. It is quoted on this thread #372.

**Comment by valinet** [comment]
Thanks @BraINstinct0, @sisericm. 

@zme-ul I can't do much about it. I think the note from the previous README summarizes it well. I removed it temporarily and intend to provide it via the wiki, which I can update separately from the main README. It just takes a while to put everything together, that's all.

Regarding the issue at hand, as I said, I can't do much about it. The user has the full rights and the authority to decide whether to run this or not. Personally, what can I say, I vouch for it, but you don't have to take my word, exclude me entirely:
* The source code is fully public
* Builds are automatically generated using standard compiling tools on GitHub's infrastructure without any intervention from me
* Releases are delivered straight from the untouched builds by GitHub's infrastructure as well
Unless GitHub or the compiler tools do something shady, what you get is an exact machine code representation of the source code that you can see, clone and publicly inspect in the repository.

Thanks
