### ISSUE TITLE
Weather tab missing from 66.6

### ISSUE THREAD

**Issue by TotemicWeevil** [valinet/ExplorerPatcher#3715]
As the title says, the weather tab is missing (for me at least) in the latest release. Not sure if this in intentional or not - can someone pleas advise?

**Comment by milesprower2293** [comment]
> As the title says, the weather tab is missing (for me at least) in the latest release. Not sure if this in intentional or not - can someone pleas advise?

The weather icon is not available on the reimplemented taskbar yet that's why the weather tab is missing

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3546
