### ISSUE TITLE
Taskbar Icon Right Click Issue

### ISSUE THREAD

**Issue by equestsolutions** [valinet/ExplorerPatcher#3716]
After latest Windows Update, I'm unable to right click on any icons in the toolbar to display options for that app (i.e. MS Word, Outlook, etc.)

**Comment by milesprower2293** [comment]
Install the [latest version of ExplorerPatcher](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.6_92fce8c)

**Comment by equestsolutions** [comment]
Miles,

 

I’m extremely grateful for your message. I have to admit though, that I’m not extremely confident I know how/which file specifically to download for the latest version.

 

I really love this application, but I’m afraid I’m going to do the wrong thing and screw something up.

 

Would it at all be possible to be more specific as to which file/s I need to download or provide more specific steps so that I can download the latest version and resolve my issue?

 

Thanks in advance for your help.

 

 

Thank You,

 

Al Karaptian

 <http://www.equestsolutions.com/> eQuest Solutions Inc.

Phone:  310.937.3388

 ***@***.***> ***@***.***

 <http://www.linkedin.com/in/alkaraptian>   <https://x.com/equestrecruiter>   <https://www.instagram.com/equestrecruiter/> 

www.eQuestSolutions.com

**Comment by milesprower2293** [comment]
The file that you need to download is ep_setup.exe if your device is an amd64 device (remember to put it on the exclusion list of your antivirus software)

**Comment by pyrates999** [comment]
@equestsolutions your phone number is being shown.  Edit your message on here and don't respond via email next time.
