### ISSUE TITLE
Taskbar reimplementation loses position retention

### ISSUE THREAD

**Issue by nx5314** [valinet/ExplorerPatcher#3719]
The Windows 10 ExplorerPatcher reimplementation will, upon a restart of explorer.exe, always return the primary taskbar to the primary monitor regardless of whether it was moved to a different monitor. Tested with three displays.

Win11 build 22631.4169
EP buid 22621.3880.66.6

**Comment by milesprower2293** [comment]
did you wait for a couple of minutes after relocating the taskbar?

**Comment by nx5314** [comment]
yeah it doesn't seem to make a difference how long after it is

**Comment by pyrates999** [comment]
Is there a setting in EP Properties application, that you set where you change what monitor the taskbar will be on?  Or did you just right click on it, untick lock the taskbar, move it, and then reticked lock the taskbar?

Does it do the same thing if you reboot?

**Comment by nx5314** [comment]
Yes, this is by dragging the taskbar to a new monitor, then locking taskbar again. Doesn't make a difference locked or unlocked, and a full reboot results in the same.

**Comment by valinet** [comment]
I remember a talk about this back when I was enabling the disabled but still there Windows 10 taskbar back in the Windows 11 22000 days. It’s actually a bug/glitch that went on unresolved for so much time that people took it as a feature. I think I did something about it, reimplemented the bug or something, maybe the reimplemented taskbar needs that as well, although my memory is too vague now.

If I find the old thread where this is discussed, maybe it’s a good start for remembering what I actually did and see from there…

**Comment by milesprower2293** [comment]
Found those threads #171 and [#14](https://github.com/valinet/ExplorerPatcher/issues/14#issuecomment-937252714)

**Comment by 4yx** [comment]
Another helpful thread related to this issue is #504, where the commit af204332d6f286dae0ac5d9e3ce1eec69c09d74c that provided a fix for a similar issue was first referenced.

From what I could find, the change was first introduced in prerelease [22000.348.40.0](https://github.com/valinet/ExplorerPatcher/releases/tag/22000.348.40.0_c7c94b3) on Dec 5, 2021.

The relevant code is still present on `dllmain.c`: https://github.com/valinet/ExplorerPatcher/blob/92fce8c90267fc9036e816435badc71b12027380/ExplorerPatcher/dllmain.c#L8513-L8597

**Comment by milesprower2293** [comment]
@nx5314 i can confirm that this issue is present on ep_taskbar.0.dll (Explorer Patcher's taskbar for Windows 10)

**Comment by Solithe** [comment]
Updated Windows to 24H2 and have the same issue now.

**Comment by fdutheil** [comment]
Same issue here with same Win11/EP versions on 2 displays. 
Restarting EP or reboot Win11 reset the primary taskbar to the primary monitor.

**Comment by Amrsatrio** [comment]
The hook @4yx pointed is now applied into 66.7's reimplemented taskbar. 66.7 is now being built.
