### ISSUE TITLE
2 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by JoelFB** [valinet/ExplorerPatcher#372]
https://www.virustotal.com/gui/file/950a1eb9698f3c48f141c748cd8a653a6adb64a01c7cb754e3152ce5534223bf

![image](https://user-images.githubusercontent.com/2984333/141824328-fad43aef-aa3c-427e-ad02-2fbcc263425c.png)

**Comment by valinet** [comment]
Thanks @sisericm. 

@JoelFB I can't do much about it. I think the note from the previous README summarizes it well. I removed it temporarily and intend to provide it via the wiki, which I can update separately from the main README. It just takes a while to put everything together, that's all.

Regarding the issue at hand, as I said, I can't do much about it. The user has the full rights and the authority to decide whether to run this or not. personally, what can I say, I vouch for it, but you don't have to take my word, exclude me entirely:
* The source code is fully public
* Builds are automatically generated using standard compiling tools on GitHub's infrastructure without any intervention from me
* Releases are delivered straight from the untouched builds by GitHub's infrastructure as well
Unless GitHub or the compiler tools do something shady, what you get is an exact machine code representation of the source code that you can see, clone and publicly inspect in the repository.

Thanks
