### ISSUE TITLE
Windows Switcher NT mode does not work on Win11 v24H2

### ISSUE THREAD

**Issue by mayureshs** [valinet/ExplorerPatcher#3720]
Windows Switcher when selected on Window NT does not show any icons on Alt + Tab. However Windows 10 mode it does work. 

Edition	 Windows 11 Enterprise
Version	  24H2
OS build	  26100.1742
Experience Windows Feature Experience Pack 1000.26100.18.0
![image](https://github.com/user-attachments/assets/389a902e-9d1e-40f8-bc4f-eeb8c226bcec)

**Comment by milesprower2293** [comment]
Microsoft removed the NT window switcher on a 25xxx build and it is not possible (at the moment) to bring it back on 24H2+ builds
