### ISSUE TITLE
Will NOT let me download

### ISSUE THREAD

**Issue by cowboysdude** [valinet/ExplorerPatcher#3722]
![winver](https://github.com/user-attachments/assets/d152fd63-1e7d-461e-a585-52b422fad4ef)

Will NOT let me download and YES I ran the powershell script and rebooted...... just keeps reporting this has a virus....

HOW do I fix that?

**Comment by mayureshs** [comment]
Change the default download location and add the location in the exclusion list in windows defender.

**Comment by cowboysdude** [comment]
Well since I have NO idea how to do that LMAO  Is there a place to go to figure out how to do that exactly?  Thank you
