### ISSUE TITLE
Activating the taskbar widget

### ISSUE THREAD

**Issue by 4naE** [valinet/ExplorerPatcher#3723]
You are using the taskbar with Windows 10.
You have enabled the widget in the action bar option, but it is not actually enabled.
Please teach me the way.
(setting)
![image](https://github.com/user-attachments/assets/db4979d2-afcc-4a1d-b3d5-6debb068b848)
(task bar)
![image](https://github.com/user-attachments/assets/30964860-f8a6-40d6-b62c-0bc18bf7f6ae)

**Comment by milesprower2293** [comment]
The Widgets/weather/news & interests icon is not an option on the reimplemented taskbar at the moment
