### ISSUE TITLE
Windows Security Quarantined my Update

### ISSUE THREAD

**Issue by hamzagad** [valinet/ExplorerPatcher#3726]
Windows Security stopped my update process for version: 22621.3880.66

Detected: HackTool:Win64/ExplorerPatcher!MTB
Details: This program has potentially unwanted behavior.
Date: 21-Sep-24 11:13 PM
Affected items:
file: C:\Users\Primasoft2\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

This never happened before

**Comment by RustedEmber** [comment]
I have the same problem. I was going to create an issue about it, but you got here first.

**Comment by 4yx** [comment]
This is a known issue, please check the pinned issue #3228 or the warning in the [CHANGELOG](https://github.com/valinet/ExplorerPatcher/blob/master/CHANGELOG.md) (also mentioned in the releases) for more information.
