### ISSUE TITLE
Windows 11 24H2 Build 26100.1742 "Virus" (yes, again)

### ISSUE THREAD

**Issue by coraphise** [valinet/ExplorerPatcher#3731]
First and foremost, I **hate** Windows 11...

Ever since this latest build update slipped through, I can't run ExplorerPatcher _at all_. :( Windows constantly tries to tell me it's a virus, I can't download with any browser, I can't disable Defender to bypass it...

And yes, I've added the exclusions.

Since I can't seem to find the discussion(s) pertaining to all of this, can anyone either help here, or guide me back to the discussion(s)? I'm a little too frustrated right now.

Thanks in advance for any help or guidance you can provide.

**Comment by coraphise** [comment]
OK, to follow up...

I added a new text file to my downloads folder, named it "ep_setup.exe", added THAT as an exclusion... AND SUCCESSFULLY DOWNLOADED THE SETUP PROGRAM AGAIN! 🥳

Piss off MS... you really do NOT know how to keep happy customers.

**Comment by pyrates999** [comment]
read the release notes to find out what files and directories you need to exclude with your av: https://github.com/valinet/ExplorerPatcher/releases

**Comment by coraphise** [comment]
So, as I noted in my original post:
"And yes, I've added the exclusions."

That didn't matter, my system still flagged ep_setup.exe as it was downloaded. I'm sure that's because this is a work system.

I'm tired of being told how I can use my machine, but I give up too. Instead of the computer being a tool I use, I'm just going to be the tool the computer uses. 🙄

**Comment by pyrates999** [comment]
You need to exclude the directory that you download ep_setup.exe as well.  Create a directory inside the downloads directory and exclude that.  Then download ep_setup.exe to there.
