### ISSUE TITLE
Can't uninstall.

### ISSUE THREAD

**Issue by oana-marina** [valinet/ExplorerPatcher#3738]
When I tried to uninstall i got the message it can't find the setup exe. I went ahead to delete all registry entries and folders from Program files and AppData Remote (as IT was freaking out about unauthorized software) , but I still have the Properties option (which errors out) on the taskbar right click and the Quick Launch toolbar. How do I get rid of those?
<img width="814" alt="image" src="https://github.com/user-attachments/assets/1344e5d8-dce9-4b00-a67e-d8b0ca912b42">

**Comment by pyrates999** [comment]
read the release notes here on what you need to exclude in windows defender or whatever AV you have installed: https://github.com/valinet/ExplorerPatcher/releases

then reinstall EP and then uninstall by following this: https://github.com/valinet/ExplorerPatcher/wiki/Installer-How-To

**Comment by Somasonic** [comment]
I'm in the same situation, Defender has quarantined the setup file so I can't uninstall and the security office want the software gone. I have no control over the Defender config, so are there any manual steps for removal? Thanks.

**Comment by pyrates999** [comment]
try downloading this version: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

it wasn't detected by windows defender.

then rename ep_setup.exe to ep_uninstall.exe and run ep_uninstall.exe.  That should uninstall it.

**Comment by Somasonic** [comment]
That seems to have done the trick, thank you so much. I did get the below error, but ExplorerPatcher does seem to be gone regardless. 

![image](https://github.com/user-attachments/assets/0238ca55-b769-4cb9-a62b-4a7933d6f09c)

**Comment by pyrates999** [comment]
I advise that you don't install EP on work computers where you are not part of the sys admin group.
