### ISSUE TITLE
[New Feture Request] Add "Open all apps by default" to the win10 start menu

### ISSUE THREAD

**Issue by wuyilingwei** [valinet/ExplorerPatcher#3741]
[✔] I tried searching the issue and didn't see any similar issues. 

Considering that there are many issues in this project, I can't guarantee that there are absolutely no similar issues. If I raised a duplicate issue, please close it.

Thank you very much for providing the "Open by default as application list" feature for the win11 start menu.

Is this also possible for the start menu in win10 full screen mode?

Because MS doesn't optimize win11 well, my surface probably won't be updated to win11, but for win10, explorer patcher has limited options, and there is no function like win11 defaulting to the app list.

I tried many group policies/registries, but there is only one outdated group policy that only supports win8/8.1. I also tried many other methods. Microsoft is amazing in you can disabling almost all functions on the start menu, but the only thing missing is the tile page they removed in win11.

Win10 22h2 19045.4780

**Comment by pyrates999** [comment]
try this: https://support.microsoft.com/en-us/windows/make-start-full-screen-13bc1e29-65dd-ba38-e3ec-7959b8d770dc

**Comment by wuyilingwei** [comment]
> try this: https://support.microsoft.com/en-us/windows/make-start-full-screen-13bc1e29-65dd-ba38-e3ec-7959b8d770dc

You may have misunderstood what I meant. I hope that the full-screen start menu opens with an application list, not a tile.

Unfortunately, MS does not remember the last selected tab, so your solution does not work.

**Comment by wuyilingwei** [comment]
If possible, completely removing the pinned tile is also a possible solution.

But I cannot find gpedit / reg setting of this. may be they do not prepare this

**Comment by milesprower2293** [comment]
@wuyilingwei use [Discussions](https://github.com/valinet/ExplorerPatcher/Discussions)

**Comment by wuyilingwei** [comment]
> @wuyilingwei use [Discussions](https://github.com/valinet/ExplorerPatcher/Discussions) for feature requests
