### ISSUE TITLE
Taskbar disappears

### ISSUE THREAD

**Issue by Frostedblood** [valinet/ExplorerPatcher#3742]
If computer monitors go to sleep or the computer goes to sleep upon awakening the taskbar disappears on my secondary monitor. I have to restart File-explorer each time to reenable multiple monitor task-bar.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another AV installed?

**Comment by Frostedblood** [comment]
I'm running Windows 11 Pro 64-bit (10.0, Build 22631). System language is English. I'm not running any other UI programs or AV.

Thanks for the quick response. I've attached the settings I've been using. 

![image](https://github.com/user-attachments/assets/3eb4b834-5f59-449e-83ac-4e89f85d8e99)
![image](https://github.com/user-attachments/assets/bdd458b6-21e0-486a-b358-4eb334da3284)
![image](https://github.com/user-attachments/assets/12440642-2a0a-4ecb-ad69-134b33f5fd80)
![image](https://github.com/user-attachments/assets/ef7a0c3a-924f-4f92-9516-adeb566c6c48)
![image](https://github.com/user-attachments/assets/6c8e5879-7cd7-45cb-9492-c96724efde0d)
![image](https://github.com/user-attachments/assets/aa695c05-6c4f-4ca6-a6c5-0c8b7003e5ba)
![image](https://github.com/user-attachments/assets/672562e3-f506-4be9-b6de-ecabebdc5601)
![image](https://github.com/user-attachments/assets/465db7a6-dd7f-49d5-af30-47ed18fbe73b)
![image](https://github.com/user-attachments/assets/f38f5bfd-0e04-41df-9ade-10f6eabbed3b)
![image](https://github.com/user-attachments/assets/81c52978-328d-432a-991b-1071b687d154)
![image](https://github.com/user-attachments/assets/bd9211fe-3d94-45ff-8729-5cece2c71768)

**Comment by Frostedblood** [comment]
Automatically hide the taskbar is disabled in Windows.
![image](https://github.com/user-attachments/assets/ab52cb18-df64-4a34-8381-6ca34797803d)

I'm not sure what your second question is asking. I installed ExplorerPatcher the day I updated to W11 and have been using it the entire time for my taskbar settings.

**Comment by milesprower2293** [comment]
Starting from version 66.1 we made a reimplementation of the Windows 10 taskbar to replace the native Windows 10 taskbar that is being removed from Windows 11 builds specially 24H2
![{2D7C0602-26C8-4ED1-A51B-DB4450749939}](https://github.com/user-attachments/assets/7d2b789a-0f93-406a-98ab-30ad00e7caaf)

**Comment by pyrates999** [comment]
You enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by Frostedblood** [comment]
The advice provided seems to have resolved the issue. Thanks for the help!
