### ISSUE TITLE
Some app icons go blank in windows 10(explorer patcher) Taskbar

### ISSUE THREAD

**Issue by jw0785** [valinet/ExplorerPatcher#3754]
Reproduce: Open Okular

**Comment by Amrsatrio** [comment]
![image](https://github.com/user-attachments/assets/4646862b-68f1-4fb0-9427-046b2bb611ac)

Repro on my end. 22621.3296 ep_taskbar.2.dll

Stay tuned for a fix.

**Comment by Amrsatrio** [comment]
![image](https://github.com/user-attachments/assets/872f66c6-3b06-4f9f-aba4-6777854c59c3)

Fix coming in the next EP release.

**Comment by Amrsatrio** [comment]
Fixed in 66.7. It is now being built.
