### ISSUE TITLE
Discord Notify Dot missing

### ISSUE THREAD

**Issue by LittlDog** [valinet/ExplorerPatcher#3763]
Since one of the last Updates, (not sure wich), the red dot indicating new messages is missing on the Discord Window in the Taskbar.
But it still appears on the Discord Symbol.

![image](https://github.com/user-attachments/assets/ea1528fe-678a-461d-baa8-53439643e58e)

**Comment by pyrates999** [comment]
This is most likely a bug with discord and not EP.

**Comment by LittlDog** [comment]
It worked before the Update. And it's still working when i disable the explorer Patcher.

**Comment by LittlDog** [comment]
Win 11 64Bit
23H2 (Build 22631.4169)

![image](https://github.com/user-attachments/assets/81064bde-a23d-41ce-9354-15b51344299c)

![image](https://github.com/user-attachments/assets/6f7e9f1c-936d-46be-8fef-3c593653611f)
![image](https://github.com/user-attachments/assets/ee8627af-eece-433f-8650-7826b1deb36a)
![image](https://github.com/user-attachments/assets/d37263c4-ae7c-4990-af3c-c64038d46883)
![image](https://github.com/user-attachments/assets/6dc91915-de05-401b-9641-c88c19ab60c7)
![image](https://github.com/user-attachments/assets/a48f7613-e103-400b-a39a-fcfe3de218a7)
![image](https://github.com/user-attachments/assets/bdc0f42c-ca88-4bc2-b12f-01cc5b09b765)
![image](https://github.com/user-attachments/assets/71ecdcfb-be50-4e8a-8fe2-9ac6c21cf92b)

No other Software installed that modifies any UI

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by LittlDog** [comment]
Did that and restarted it, sadly it didn't changed anything.

**Comment by pyrates999** [comment]
does any other applications do that?

**Comment by LittlDog** [comment]
I don't use any other applications wich use a visible Dot for notifications on the Taskbar Window.
But adding something to the Title in the Taskbar Icons. like for Twitter or other sites, works.

**Comment by pyrates999** [comment]
I've enabled notifications on discord and will see if it is happening to me.

**Comment by LittlDog** [comment]
Thanks for your help ^^

Notifications are enabled, but it only causes the Taskbar window to blink in Yellow when there is a new Private Messages or Ping.

**Comment by pyrates999** [comment]
I saw the notifications popping up, and then removing itself.  No red dot was shown.

**Comment by LittlDog** [comment]
It should be look like this, every time there is an unread message 
![image](https://github.com/user-attachments/assets/d5d23da6-f273-481a-9cef-f065a31e6656)

**Comment by LittlDog** [comment]
Reinstalled the Explorer Patcher.. It's working now.
Don't know why it wasn't working in the first place.
Many thanks for your help and sorry for the stress.
