### ISSUE TITLE
ep_taskbar does not support Windhawk mods

### ISSUE THREAD

**Issue by 123SONIC321** [valinet/ExplorerPatcher#3769]
After switching from Windows 11's default taskbar to ExplorerPatcher, 2 mods from [Windhawk](https://github.com/ramensoftware/windhawk) ([Disable grouping on the taskbar](https://github.com/ramensoftware/windhawk-mods/blob/31cb0bda3c0d239f220fad072bd4a2be53c6ff05/mods/taskbar-grouping.wh.cpp), [Middle click to close on the taskbar](https://github.com/ramensoftware/windhawk-mods/blob/31cb0bda3c0d239f220fad072bd4a2be53c6ff05/mods/taskbar-button-click.wh.cpp)) are no longer functioning as expected.
I've reached out to the mod developer and he told me "Compatibility with ExplorerPatcher is not a priority, sorry. You can also try asking the ExplorerPatcher authors about it, perhaps there's an easy solution on their side."
Is this issue solvable? If not, do you have any alternative solutions that can perform the functions of the two mods I mentioned without causing conflicts with ExplorerPatcher?

**Comment by pyrates999** [comment]
did you try disabling grouping in EP?

**Comment by pyrates999** [comment]
Then you need to wait until the windhawk mod for removing labels from the taskbar icons has been updated to use the taskbar: **windows 10 (ExplorerPatcher) taskbar**.

**Comment by pyrates999** [comment]
Or you can also wait for that option to be available in EP.

**Comment by pyrates999** [comment]
you would need to ask the developers on here for that.

**Comment by Juriyx** [comment]
I agree and want to add that also the "Taskbar Thumbnail Reorder" mod doesn't work on Windows 10 (ExplorerPatcher) taskbar implementation on Windows 11 24H2 (build 26100.1742)

**Comment by Amrsatrio** [comment]
Yeah this is certainly something that I must fix. I've been in talks with Michael on how to achieve this. Hopefully by exporting the functions in ep_taskbar DLL mods can mod it easily. But in the end each of the taskbar mods need to be updated.

**Comment by Juriyx** [comment]
> Hopefully by exporting the functions in ep_taskbar DLL mods can mod it easily.
Have you considered adding the “Allow to change window order on Taskbar” option to ExplorerPatcher settings?

**Comment by Amrsatrio** [comment]
No, I haven't considered anything. In the past couple months I have been working on reimplementing the Windows 7 start menu, with no time left on working on the taskbar and other aspects of EP.

**Comment by pyrates999** [comment]
The windows 7 start menu can already be reimplemented by installing open shell, as I have installed it.  I can't stand even the windows 10 start menu.

**Comment by Amrsatrio** [comment]
It's not really the same as the original 7 start menu.

**Comment by Amrsatrio** [comment]
Preliminary Windhawk mod support has been introduced with 66.7. It is now being built. Please report further issues to respective mod authors.
