### ISSUE TITLE
File Explorer AND Taskbar crashing, & weather widget gone

### ISSUE THREAD

**Issue by KG1959** [valinet/ExplorerPatcher#3770]
![WeatherWidget-gone](https://github.com/user-attachments/assets/7805872a-94a5-44a5-80cf-f8364224a17e)
![Security-blocked-No-Restore](https://github.com/user-attachments/assets/101f01fe-c8c8-41e5-9c3e-33003cc603c1)

ISSUE: Uploaded to Win 11 24H2, and lots of issues since then.  File Explorer (and the entire Taskbar at the bottom) crashes every few minutes.  NOTE: In Windows "Security", it shows "Threat Blocked" and quarantined, but differently than in the past, it doesn't allow "Restore".  Very odd!

Also, in the "Properties" tab of this Explorer Patcher, the "Weather" tab on the left side is gone.  No Weather showing up in Properties anymore (not sure how to restore that).

VERSIONS: ExplorerPatcher version is 22621.3880.66.6.  And it is now Windows version: 24H2 (OS Build 26 100. 1742).  

See attached.  Thanks folks!

**Comment by pyrates999** [comment]
Don't upgrade to windows 11 24h2 while EP is installed.  Uninstall it first.

Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

All builds of EP are done by github build servers against the source code in the repo.  Only binary is the reimplemented windows 10 taskbar and windows 10 start menu files.  There is no third party build servers.

This is a false positive.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges.

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.

No weather is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3546

Then reinstall EP and open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by KG1959** [comment]
Thanks folks!  Well, 24H2 is already installed.  SO, if I uninstall EP completely, restart, and then install EP again, would that likely work?  Just double-checking before I close this out!

**Comment by pyrates999** [comment]
Read previous comment.

**Comment by KG1959** [comment]
Sorry for the questions, but I don't have the smarts of you folks (sorry!)  Your initial response said "Don't upgrade to windows 11 24h2 while EP is installed. Uninstall it first.".  I can't uninstall 24H2 easily (my system is pushing back on this), so if I don't uninstall 24H2, and instead uninstall EP, restart system, and then install EP again, do you know if that would work?  Sorry if these are dumb questions, but just trying to get it dumbed down for me, lol.  Thanks!

**Comment by pyrates999** [comment]
I meant you should uninstall EP, reboot, and then install EP.

**Comment by KG1959** [comment]
Thanks!  I actually did uninstall EP, reboot, and then install EP.  Still crashing File Explorer every few minutes.  Ugh.

**Comment by pyrates999** [comment]
After you install EP, in the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

**Comment by KG1959** [comment]
Thanks!  But this is what happens: 
![Error](https://github.com/user-attachments/assets/0598b98b-db1f-4bc3-9799-aed36cbad482)

**Comment by Amrsatrio** [comment]
Weather is not yet supported but I may attempt reimplementing the code supporting it in the taskbar.

Regarding crashing, https://github.com/valinet/ExplorerPatcher/issues/3605

**Comment by KG1959** [comment]
Done (above!).  Still crashes every few minutes.  Win 11 Ver 24H2 (OS Build 26.100.2033).  Wish there was a fix (or another program that worked with this newer version of Win 11).  So far, not working!

**Comment by Amrsatrio** [comment]
![image](https://github.com/user-attachments/assets/37f14edd-d6a4-41f7-b281-d0fed9239352)

I gotchu on the weather part. For the crashing, are you getting them when you're receiving notifications?

**Comment by KG1959** [comment]
Hi again!  Weather part = I am not worried about that.  But the crashing is the problem (not sure - notifications do come through, so guessing not the issue).  Microsoft has this program locked out very tightly, and it will not stay working for more than a few minutes at a time.  I just logged into Discord, as requested!

**Comment by Ha7yad** [comment]
@KG1959 Are you saying that the taskbar is crashing? Or is it your PC crashing.

**Comment by Ha7yad** [comment]
If the taskbar is crashing, I have had that too. I tried to Uninstall it, but it wouldn't work. There was just no taskbar. I suggest that you **TRY** uninstalling  EP (not required), to see if the situation get's resolved. If your taskbar is there with no crashes, you are good. You can try installing EP again. But if the taskbar isn't there, I suggest you to _not_ restart your computer. This is because your taskbar may not load correctly and you might lose access to your PC/Laptop. The desktop most likely will not be shown because if you try to restart EP it will remove the desktop for a bit. Before uninstalling it, just to be _safe,_ open the EP Install page.  You are pretty much stuck with EP if that happens to you, and the only way to resolve it is to pretty much reinstall Windows. I hope this helps. Make sure to **ping** me if you have a question.

**Comment by pyrates999** [comment]
Since you can't restore default settings in EP:

Try the following:

1. uninstall explorer patcher
2. delete the registry keys: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher" "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher"
3. reboot
4. install the latest explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by KG1959** [comment]
Thanks pyrates999! But I just used Amr's custom pre release version of EP, and it worked perfectly (I didn't need to do any of the stuff above). All is well!

**Comment by JosefKuba** [comment]
> Thanks pyrates999! But I just used Amr's custom pre release version of EP, and it worked perfectly (I didn't need to do any of the stuff above). All is well!
--------
I have the same problem, where can I get the pre-release version?

**Comment by pyrates999** [comment]
A new pre-release is created when the changes that fixed the crash are committed to the git repository here.

**Comment by KG1959** [comment]
> > Thanks pyrates999! But I just used Amr's custom pre release version of EP, and it worked perfectly (I didn't need to do any of the stuff above). All is well!
> 
> I have the same problem, where can I get the pre-release version?

Hi JosefKuba, = Amr said to go to this discord link (scroll through comments, and you'll see the pre-release version he did for 24H2) -- it has worked absolutely flawlessly on my PC from what I can see (no more EP / File Explorer crashes, and weather works again).  https://discord.com/channels/1155912047897350204/1155912052687241228 .  Amr is the wizard on this one, so he'd have to answer any questions on it.....  It was an amazing release for me!

**Comment by pyrates999** [comment]
Having more people test builds on discord is always good.

**Comment by KG1959** [comment]
> Fixed in 66.7.

Thanks Amr!  So is 66.7 the latest official build in GitHub/from-Valinet?  If so, I can let the auto-update in "Properties" of EP allow it update again?  Just making sure, as it would overwrite what you had uploaded last week, which I have been avoiding.  Just checking!

**Comment by pyrates999** [comment]
It's a pre-release.  So you must set updates to check for pre-releases first.
