### ISSUE TITLE
W11 24H 26100.1742 Taskbar on bottom using EP Version: 22621.3880.66.6

### ISSUE THREAD

**Issue by haylebob** [valinet/ExplorerPatcher#3773]
Hello,

After the update, EP [version: 22621.3880.66.6](https://github.com/valinet/ExplorerPatcher/commit/92fce8c90267fc9036e816435badc71b12027380) no longer works. 
I only have the taskbar at the bottom and can no longer move it up. Is this in the works or can it no longer be implemented?

thank you
Michael

**Comment by DeanosT50** [comment]
Yup. Not working for me either after the big Win 11 update.
Looks to be a totally new version also.

No beta option to instal either.

**Comment by DeanosT50** [comment]
I managed to fix it and get it all working again.

Re-downloaded the install file and reran setup as-is.

Then I discovered there is a Win 10 Taskbar (ExplorerPatcher) version. Selected that and restarted Explorer and all is happy again!
New symbols also downloaded and installed.

![image](https://github.com/user-attachments/assets/4ec529e9-4411-4f3a-bc0c-c2b445bb3d52)

**Comment by pyrates999** [comment]
Please see this: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

Then open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by haylebob** [comment]
Hello,

does that mean that the taskbar at the top works with the “Windows 10
Explorer Patcher” setting?

Am Di., 8. Okt. 2024 um 13:47 Uhr schrieb pyrates999 <
***@***.***>:

**Comment by pyrates999** [comment]
yes.

**Comment by haylebob** [comment]
Hello
sadly it doesn't works
there is no "Windows 10 Explorer Patcher" Option anymore
what do i wrong ?

Am Di., 8. Okt. 2024 um 15:12 Uhr schrieb pyrates999 <
***@***.***>:

**Comment by haylebob** [comment]
sorry my fault it works now i forgot to run setup.exe again 😊

Am Mi., 9. Okt. 2024 um 06:27 Uhr schrieb Hayle Bob ***@***.***>:
