### ISSUE TITLE
[Bug, 24H2] ExplorerPatcher's Windows 10 (ExplorerPatcher) has a display issue when resuming from sleep

### ISSUE THREAD

**Issue by SteadyStatus21** [valinet/ExplorerPatcher#3776]
Hello! 

Noticed this after updating to Windows 11 24H2 (OS Build 26100.1882), where when resuming using the device from sleep, the taskbar appears to be below the screen, and it takes a restart of ExplorerPatcher for it to update it back. Keep in mind, I have a device that is 2K resolution (2880 x 1800px). 

Normal and expected operation style:
![image](https://github.com/user-attachments/assets/9f32b06e-77e0-4ad6-9d50-6d5175946fea)

After resuming from sleep on my laptop:
![image](https://github.com/user-attachments/assets/e9907e9c-1f64-489f-9342-5b770ba19dc3)
(Image from Pixel 8 Pro):
![PXL_20241008_212058122~2](https://github.com/user-attachments/assets/1a0a4c7d-20fd-46c2-b7df-6e172545cecd)

Thanks ExplorerPatcher Community!

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another AV installed?

**Comment by SteadyStatus21** [comment]
> Please post windows version and build. You can find this by running winver. Please include if you are running x86-64 or Arm. And what language your windows is in. Please post explorer patcher version.

Windows 11 Version 24H2 (OS Build 26100.1882 | Windows Feature Experience Pack 1000.26100.23.0), running x64. Windows is in **English (United States)**. ExplorerPatcher Version **22621.3880.66.6**.

![image](https://github.com/user-attachments/assets/3124060a-158f-4f15-86c4-49cb6cb002ce)

> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.

![image](https://github.com/user-attachments/assets/1aa8c026-8a18-4cc0-a01e-e60273a15a9e)

> Please include any other software you have installed that modifies the UI of windows.

None, only ExplorerPatcher. (Though, not sure if Microsoft PowerToys is something to include here)

> Do you have another AV installed?

No, only the default Windows Security / Defender with exclusions for all of ExplorerPatcher's files. (I ran the PowerShell as admin from the releases page)

**Comment by SteadyStatus21** [comment]
Another thing that I noticed is it only happens when my laptop goes to sleep for long periods of time, short periods (ie. <15 mins) seems to not affect the system.

**Comment by pyrates999** [comment]
is your laptop set to hibernate while sleeping?

**Comment by SteadyStatus21** [comment]
> is your laptop set to hibernate while sleeping?

No, I use the standard sleep on Windows instead.
![image](https://github.com/user-attachments/assets/43dae394-a3b0-48b8-acca-12fff3c57c56)

**Comment by SteadyStatus21** [comment]
> does opening up EP properties application and clicking on restart file explore fix it?

Yes it does, that is what I end up doing to solve the issue and fix Explorer.

**Comment by SteadyStatus21** [comment]
Closing this issue, as a Microsoft Update (`2024-10 Cumulative Update for Windows 11 Version 24H2 for x64-based Systems (KB5044284)`) seemed to fix this issue. Sorry for the troubles. Thank you pyrates999 for your help :)
