### ISSUE TITLE
[24H2] Explorer Patcher Taskbar doesnt let you drag and drop icons onto it to pin them.

### ISSUE THREAD

**Issue by weeniemount** [valinet/ExplorerPatcher#3779]
title. a small quirk but it just doesnt work
![image](https://github.com/user-attachments/assets/c204c34f-f0fc-4bf8-8a98-16bcb44a7582)
icons that are dragged to the taskbar get completely ignored, and i have to switch to the win 11 taskbar to pin them, or open the app and pin it that way

EDIT: explorer patcher version: 22621.3880.66.6

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

Try opening up the application first.  With the application open, then try to pin it.

**Comment by Amrsatrio** [comment]
May be related to https://github.com/valinet/ExplorerPatcher/issues/3735

**Comment by weeniemount** [comment]
is a bit related, but its for dragging from the start menu.

**Comment by Amrsatrio** [comment]
Don't worry anyways, the code that handles it is in ep_taskbar so investigating the issue and fixing it should be trivial.

**Comment by weeniemount** [comment]
alright, nice then!

**Comment by Amrsatrio** [comment]
As expected this is yet another unnecessary breakage MS has been giving us in 24H2.

**Comment by Amrsatrio** [comment]
Implemented the fix into the code. Will come in the next EP release, ETA less than a week (I hope).

**Comment by Amrsatrio** [comment]
Fixed in 66.7. It is now being built.

**Comment by weeniemount** [comment]
nice. thanks!
