### ISSUE TITLE
“win+x” shortcut fails and instead switches focus on the taskbar.

### ISSUE THREAD

**Issue by Miner2541** [valinet/ExplorerPatcher#3780]
I've determined that it's an ExplorerPatcher problem by constantly closing the software
the version I installed is 22621.3880.66.6
just like this
![image](https://github.com/user-attachments/assets/22ec37a1-9652-4563-a656-959bee03031e)

**Comment by pyrates999** [comment]
do you have any other software installed that modifies windows?

**Comment by Miner2541** [comment]
only snipaste 2.9.1
![image](https://github.com/user-attachments/assets/59445b6d-2592-4b1d-87fb-abe3f191535f)

**Comment by Miner2541** [comment]
This bug is only present when taskbar style : windows 10 (ExplorerPatcher).
If I switch to the other two options, “win+x” goes back to normal

**Comment by christianbearslyclark** [comment]
Agreed......win+x”  does not work for  24H2 ......need to be update.

**Comment by Waytoogo** [comment]
I found that the problem only happens if I have Open Shell installed. If I uninstall open shell my win+x menu works fine with the new windows 10 taskbar. The new taskbar and Open Shell don't play well together.

**Comment by Amrsatrio** [comment]
Win+X shortcut is just not implemented on the reimplemented taskbar, yet. It's on me, not on OpenShell.

**Comment by Waytoogo** [comment]
> Win+X shortcut is just not implemented on the reimplemented taskbar, yet. It's on me, not on OpenShell.

That is interesting because the win+x menu works fine on the re-implemented taskbar, if I uninstall Open Shell.
This is on 24h2.

**Comment by Jonny5555555** [comment]
Hi there happening to me also Open Shell has not had a update in years :< so heres hoping it can get patched here
