### ISSUE TITLE
Open programs on taskbar disappears, when waking up from sleep

### ISSUE THREAD

**Issue by hpace8** [valinet/ExplorerPatcher#3781]
Version 22621.3880.66.6

Good morning!

Saw the other issues about programs disappearing from taskbar when 2nd monitor is plugged in.
I'm using a 2nd monitor, plugged in always.

I get this issue **consistently**, when waking up the laptop from sleep. Only the most recent window in foreground appears on the taskbar. 

Only when I use **Alt+Tab** to bring the other program windows to the foreground one-by-one, then they appear on the taskbar again. 

Any advice?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another AV installed?

**Comment by hpace8** [comment]
> @hpace8 Under windows system -> display settings, ther is some option (don't know the correct english translation) for "multiple displays". Two option: "Memorize window positions based on display connection" and "Minimize windows when display is diconnected":

Unchecking "Minimize windows.." seem to have worked! Thank you @1kartafal4
