### ISSUE TITLE
Windows 11 Update will not install due to security or performance issues

### ISSUE THREAD

**Issue by davecummins2000** [valinet/ExplorerPatcher#3783]
ExplorerPatcher
Version 22621.3880.66.6

![image](https://github.com/user-attachments/assets/88fe346d-a8a2-4d76-80af-96be78943b2d)

**Comment by pyrates999** [comment]
Uninstall EP.  Then upgrade to windows 11 24h2.

And MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

All builds of EP are done by github build servers against the source code in the repo.  Only binary is the reimplemented windows 10 taskbar and windows 10 start menu files.  There is no third party build servers.

This is a false positive.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges.

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.

After you're done this, then you can install the latest release of EP.
