### ISSUE TITLE
Right click window menu badly scaled when taskbar is on the side

### ISSUE THREAD

**Issue by PabloBelmonte** [valinet/ExplorerPatcher#3785]
When I place the taskbar on either left or right, and right click on an icon, the popup window that appear isn't correctly displayed, especially for icons closer to the top of the screen.

For example, if I right click on a pinned Chrome icon when the taskbar is at the bottom (default), it shows a list of recent and most frequently visited pages. However, if I move the taskbar to the left, it now shows a smaller window for that same list, that is rendered from the top of the screen up to the position of the icon. Consequently, the closer to the top the icon is, the smaller the window. This is very frustrating when I try to use VSCode, for example, and try to rapidly navigate through my workspaces.

This is even worse if the taskbar is on the right. In this case, the issue appears not only on the vertical axis, but also on the horizontal, rendering only half of the popup window. When taskbar is at the top, it doesn't even show the popup.

I’m on a Windows 11 Pro OS, and the patcher is on latest version (22621.3527.65.5).

1) Example of expected behavior (taskbar at the center):
![image](https://github.com/user-attachments/assets/0c4c5a34-9e52-4aa4-a06a-ef2fe70c4a81)

2) Small popop with taskbar at the left:
![image](https://github.com/user-attachments/assets/a329331b-fdf8-4129-963d-2b129401aa2b)

3) Cropped popop with taskbar at the right:
![image](https://github.com/user-attachments/assets/a9e5a8af-ed32-4b4f-b0d0-310d40c26027)

Thank you.

**Comment by Amrsatrio** [comment]
65.5 is not the latest version. Please update. Don't forget to read the warning.
