### ISSUE TITLE
Win11 Home Start Menu

### ISSUE THREAD

**Issue by KofCAlan** [valinet/ExplorerPatcher#3787]
Yesterday I did an in-place repair install of Win11 Home 23H2 from a freshly downloaded ISO. Everything went smoothly and the previous issues were resolved. But it broke my Win10 style Start menu setup; all I have now is the Win11 menu. I can't get ExplorerPatcher to reimplement the Win10 style, and Microsoft has negated the registry key to implement the change.

EP indicates there are no EP updates available for my installation. Would it help if I uninstalled and reinstalled EP, or is there something else I should try?

All help greatly appreciated!

**Comment by Amrsatrio** [comment]
10 start menu is gone in your build. Reinstall EP; it may work or stay not working.

**Comment by Ha7yad** [comment]
@KofCAlan, can you please send me a screenshot of your issue?

**Comment by Ha7yad** [comment]
Give me your version by using Winver. Also give me your explorer patcher version

**Comment by Ha7yad** [comment]
Send screenshots of the settings

**Comment by KofCAlan** [comment]
When I updated the app it resumed working. Sent from my Verizon, Samsung Galaxy smartphoneGet Outlook for AndroidFrom: Ha7yad ***@***.***>Sent: Saturday, October 12, 2024 7:31:18 PMTo: valinet/ExplorerPatcher ***@***.***>Cc: KofCAlan ***@***.***>; Mention ***@***.***>Subject: Re: [valinet/ExplorerPatcher] Win11 Home Start Menu (Issue #3787)
Give me your version by using Winver. Also give me your explorer patcher version

**Comment by pyrates999** [comment]
Then please close this if it is working you.

**Comment by pyrates999** [comment]
BTW github has an android app.  So you can install that to respond instead of responding via email.

**Comment by KofCAlan** [comment]
Solved by latest update.

**Comment by Ha7yad** [comment]
@KofCAlan I am glad to hear that it's fixed.
