### ISSUE TITLE
[24H2] Explorer Patcher Win10 Taskbar doesn't work with Battery Flyout

### ISSUE THREAD

**Issue by captainfalcon23** [valinet/ExplorerPatcher#3791]
When clicking the battery flyout and using the EP Win10 taskbar, the flyout just doesn't appear. This wasn't an issue and worked fine pre 24H2.

**Comment by pyrates999** [comment]
Known issue: https://github.com/valinet/ExplorerPatcher/issues/3640#issuecomment-2332201135

please close this.
