### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by kriznokoff** [valinet/ExplorerPatcher#3793]
Whenever I open file explorer and try to open 'Home' or 'Gallery' or 'User - Personal' explorer completely crashes and restarts. I know this is an ExplorerPatcher issue because I uninstalled it (which it wouldn't install at first and it was erroring so I just renamed the install file) Not sure why this was happening. Im going to reinstall ExplorerPatcher and see if it continues happening.

**Comment by Ha7yad** [comment]
@kriznokoff Give me an update once you reinstall ExplorerPatcher

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another AV installed?

**Comment by kriznokoff** [comment]
![image](https://github.com/user-attachments/assets/b3b107f7-5e6b-4fbf-801e-b7888b2946d6)

**Comment by kriznokoff** [comment]
I don't have ExplorerPatcher installed anymore and can't seem to find a way to reinstall it? I can't find the files to install it on this github page. Please direct me in the right way

**Comment by kriznokoff** [comment]
I cannot install EP now because of the false virus detection.

**Comment by Ha7yad** [comment]
@kriznokoff Turn off any anti-virus things

**Comment by kriznokoff** [comment]
@Ha7yad just did that

**Comment by kriznokoff** [comment]
It only happens when I try to open the one drive file

**Comment by Ha7yad** [comment]
Is it working?

**Comment by Ha7yad** [comment]
So do you have EP installed now?

**Comment by kriznokoff** [comment]
yes

**Comment by Ha7yad** [comment]
Ok. Is the taskbar functional?

**Comment by kriznokoff** [comment]
im going to restore to default settings in properties

**Comment by kriznokoff** [comment]
yes

**Comment by Ha7yad** [comment]
Ok. If you get a error send it

**Comment by Ha7yad** [comment]
Did it work?

**Comment by kriznokoff** [comment]
So I found something:
![image](https://github.com/user-attachments/assets/668a498d-dfae-4a10-b28f-25be9d18edd4)
When I reset my settings the problem is fixed but when I turn on the settings I normally use it starts happening again

**Comment by Ha7yad** [comment]
So when you turn on the settings you want it starts crashing?

**Comment by kriznokoff** [comment]
File explorer only crashes when I click on these
![image](https://github.com/user-attachments/assets/c0f735a6-ee5c-4db3-97e1-d5320f38190c)
in file explorer

**Comment by kriznokoff** [comment]
so yes

**Comment by Ha7yad** [comment]
So it's file explorer ok. Does the taskbar crash with it?

**Comment by kriznokoff** [comment]
Yeah, Its like I reset file explorer from the properties menu

**Comment by Ha7yad** [comment]
Weird

**Comment by Ha7yad** [comment]
That might be your problem. It doesn't happen to me. Do you want to run a Virtual Machine if you can?

**Comment by kriznokoff** [comment]
I use the windows 10 ribbon and when I returned It back to being the Windows 11 Command Bar it fixed the issue. So maybe theres a bug with the Windows 10 Ribbon?

**Comment by Ha7yad** [comment]
Windows 10 Ribbon ok. Let me try that. Please hold.

**Comment by Ha7yad** [comment]
Oh.

**Comment by kriznokoff** [comment]
Yeah, whenever I have windows 10 ribbon or Windows 7 option and click through 
![image](https://github.com/user-attachments/assets/6483f474-bc00-4f38-bb96-1a18b51e0880)
it crashes

**Comment by Ha7yad** [comment]
It happens to me too.

**Comment by kriznokoff** [comment]
Now we're getting somewhere

**Comment by Ha7yad** [comment]
This is a bug

**Comment by Ha7yad** [comment]
Try staying with **Windows 11 Command Bar**

**Comment by Ha7yad** [comment]
Does it happen when you use Windows 11 Command Bar?

**Comment by kriznokoff** [comment]
Nope

**Comment by Ha7yad** [comment]
Ok, this is a bug. You can close this issue if you want. Ping me for anymore help.

**Comment by kriznokoff** [comment]
Alright, thanks!

**Comment by Ha7yad** [comment]
No problem

**Comment by pyrates999** [comment]
See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).
