### ISSUE TITLE
Windows 10 Taskbar not compatible with Windows 11 LTSC 24H2

### ISSUE THREAD

**Issue by Roslinger** [valinet/ExplorerPatcher#3795]
Taskbar10 doesnt work in Windows 11 LTSC 2024 (24H2) Build: 26100.2033

**Comment by milesprower2293** [comment]
Install the latest version of explorerpatcher, then open properties (explorerpatcher), click on "Taskbar Style" and set 'Windows 10 (ExplorerPatcher) and restart explorer
