### ISSUE TITLE
The weather widget has changed

### ISSUE THREAD

**Issue by jongleeat** [valinet/ExplorerPatcher#3797]
I've used Windows 11 pro with ExplorerPatcher version 22621.3880.66.6.
But the weather widget has changed as follows:
![image](https://github.com/user-attachments/assets/1fb6837b-f856-4604-a92c-b2494ede47ee)

What could be the problem with me?

**Comment by pyrates999** [comment]
Widen your taskbar.

**Comment by jongleeat** [comment]
Thank you, pyrates999.
I can see the whole screen.
![image](https://github.com/user-attachments/assets/2b5b3c8c-e5d8-4c43-b177-0e4ff6d0d439)

But the last version of EP's weather doesn't have goole search input box and login button.
Is it a change of recent version of EP's weather.

**Comment by pyrates999** [comment]
Try going through this guide: https://github.com/valinet/ExplorerPatcher/wiki/Weather

**Comment by milesprower2293** [comment]
that's a known issue with weather and there are no plans to fix it yet

**Comment by jongleeat** [comment]
OK, I got it.

Thanks.
