### ISSUE TITLE
Leaving exclusions excluded (e.g C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\*)

### ISSUE THREAD

**Issue by styalos** [valinet/ExplorerPatcher#3799]
![image](https://github.com/user-attachments/assets/da905a75-cfb0-498c-b2f5-acc4b2b0e493)
Do i have to leave these files excluded or can i un-exclude them after installation?

**Comment by milesprower2293** [comment]
you have to leave those files excluded to prevent your antivirus software from removing dxgi.dll and break explorerpatcher's functionality
