### ISSUE TITLE
Check for updates button seems not to do anything

### ISSUE THREAD

**Issue by Anixx** [valinet/ExplorerPatcher#380]
At least, under classic theme, there is no visible output.

If to click "Update", the patcher updates and explorer restarts in a few seconds.

**Comment by valinet** [comment]
Toasts work fine under classic theme as well, I see them all the time when testing in the VM where I have this set up, maybe you have notifications turned off altogether...? That indeed means this along with all the other apps cannot show toasts.

![image](https://user-images.githubusercontent.com/6503598/141885479-5dc3e041-59f1-466b-b456-d68c077b8742.png)
