### ISSUE TITLE
Several Features Lost on Win 11 Build 26100.2033

### ISSUE THREAD

**Issue by alxbglez** [valinet/ExplorerPatcher#3800]
Many features have been lost in Windows 11 Build 26100.2033, to give a few examples:

taskbar -> Primary taskbar alignment (at screen edge)
taskbar -> Secondary taskbar alignment (at screen edge)
weather menu

**Comment by Ha7yad** [comment]
@alxbglez Hello, I am Ha7yad that help's people with problems on Explorer Patcher. Can you please send me a screen shot of the **Taskbar** section on Explorer Patcher?

**Comment by alxbglez** [comment]
Of course.

![image](https://github.com/user-attachments/assets/9d7ed112-219e-4028-b860-90a8729bb77a)
![image](https://github.com/user-attachments/assets/a76fc321-594b-4473-a77e-e53f472657ce)

**Comment by alxbglez** [comment]
![image](https://github.com/user-attachments/assets/e8b60d72-d5ee-4400-aba6-d61bb8852388)

**Comment by alxbglez** [comment]
In addition to the "Weather" option, the ability to place the bar on the left, right or top of the screen was lost.

**Comment by alxbglez** [comment]
I apologize for so many messages, maybe I did something wrong, after several restarts of the application and Windows (although I just updated to Windows 11 PRO) I can now move the bar from one place to another. Thanks for the response and interest in helping, friend.

**Comment by Ha7yad** [comment]
Ok, so you might want to blame Microsoft on that because they were the one who updated it. Try **Windows 10 (Explorer Patcher)**

**Comment by pyrates999** [comment]
weather is not yet supported on the windows 10 (ExplorerPatcher) taskbar: https://github.com/valinet/ExplorerPatcher/issues/3546
