### ISSUE TITLE
EP Properties Window Crashing

### ISSUE THREAD

**Issue by mattdoot** [valinet/ExplorerPatcher#3802]
When I right click the taskbar using ep and go to open the properties window It opens a white window then shortly after closes. I tried uninstalling and reinstalling and then uninstalling, deleting registry keys and reinstalling again but that didn't work

**Comment by mattdoot** [comment]
I don't know what I did but It started working. I believe ep is the only software I use that modifies the UI of windows. 
![Screenshot_234](https://github.com/user-attachments/assets/aba467f9-1083-4b06-94d9-8236f6e41322)
![Screenshot_233](https://github.com/user-attachments/assets/ff488152-3f8d-477b-af3d-c6f067995b4d)
Sorry for not understanding, but what Is AV?

**Comment by pyrates999** [comment]
AV=antivirus

**Comment by Amrsatrio** [comment]
I need more info. Check %localappdata%\CrashDumps and tell me if there are any that says rundll32.exe

**Comment by pyrates999** [comment]
to run the explorer patcher properties application, run this from the run menu:
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

Let me know if this works.

**Comment by mattdoot** [comment]
> I need more info. Check %localappdata%\CrashDumps and tell me if there are any that says rundll32.exe

There's 9 of these files

**Comment by Amrsatrio** [comment]
Pick the latest one, rename as txt and upload here.

**Comment by mattdoot** [comment]
> Pick the latest one, rename as txt and upload here.

[rundll32.exe.8736.dmp](https://github.com/user-attachments/files/17393704/rundll32.exe.8736.dmp)

**Comment by Amrsatrio** [comment]
I have no idea either why this fmemopen function returned NULL. I assume you were low on memory?

<img width="641" alt="image" src="https://github.com/user-attachments/assets/54f471a0-ce7e-49dd-9c44-0fe58af5a6ab">

**Comment by Amrsatrio** [comment]
@pyrates999 Next time please guide users who report crashing issues to post their latest dump file related to the affected exe in `%LOCALAPPDATA%\CrashDumps`. Thanks

**Comment by mattdoot** [comment]
> I have no idea either why this fmemopen function returned NULL. I assume you were low on memory?
> 
> <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/20662640/377011692-54f471a0-ce7e-49dd-9c44-0fe58af5a6ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzUwNjcsIm5iZiI6MTcyOTA3NDc2NywicGF0aCI6Ii8yMDY2MjY0MC8zNzcwMTE2OTItNTRmNDcxYTAtY2U3ZS00OWRkLTljNDQtMGZlNThhZjVhNmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEwMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTI1N2MxOGUxOGUxMzc0ZGEzYjhlYjNiY2E1MDlkMGIxZTRhMTY4NTM2NzdlYzUxZjJjOTk2ZDhiZjEwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a2MGsanWEZm52u69hyeVilcW87RmMk5cQTsyctDmd_4">

Yeah I only have 4 gigs of ram but I plan to upgrade it soon

**Comment by Amrsatrio** [comment]
Yeah that explains it. I advise to upgrade to at least 8GB to avoid further problems.
