### ISSUE TITLE
Windows 10 taskbar is not available in this version of Windows

### ISSUE THREAD

**Issue by Vexatuspl** [valinet/ExplorerPatcher#3806]
Since the update on the 9th of OCT I'm getting this message. Start menu is also the ^&%* W11 style and can't change it.
W11 Pro 24H2.
What kind of details can I provide to help resolving this issue?

**Comment by Amrsatrio** [comment]
It's gone. Reinstall EP to install the reimplemented taskbar appropriate your version. Windows 10 (ExplorerPatcher) will be available.

**Comment by JanDidden-VNV** [comment]
@Amrsatrio, i have reinstalled EP but still get the "Windows 10 taskbar is not available in this version of Windows" on my upgraded 24H2 system. When will the Windows 10 Taskbar be available for Win11 24H2?

**Comment by JanDidden-VNV** [comment]
Thx @Amrsatrio. Switched Taskbar style to Windows 10 (ExplorerPatcher).I can now add back my toolbars, but still not my Quick launch

**Comment by gurie2024** [comment]
i am using W11 PRO 24H2 and still can show taskbar icon size options
![image](https://github.com/user-attachments/assets/e9b08fe4-ef5f-41f1-a9e2-4270a0accbf1)

but on other computer using W11 Enterprise 24H2 the option are missing
![image](https://github.com/user-attachments/assets/7a7bc22a-d7f2-4131-a017-c343559826bf)

**Comment by Amrsatrio** [comment]
@gurie2024 Click the text that says Windows 10

**Comment by gurie2024** [comment]
@Amrsatrio that is the display when i click W10 taskbar style other option are win 11
![image](https://github.com/user-attachments/assets/7968ebd9-a3b1-4bb1-8925-9ea8edd1b2c3)
![image](https://github.com/user-attachments/assets/402e2bec-37e4-4139-ba4e-586902f258f8)
above are the comparison

**Comment by pyrates999** [comment]
Update your EP version to get the EP implemented version of windows 10 taskbar: https://github.com/valinet/ExplorerPatcher/releases

Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by gurie2024** [comment]
hi @pyrates999 there is no windows 10 (explorerpatcher) options on the applications, only Windows 11(default) and Windows 10
see image below
![image](https://github.com/user-attachments/assets/af1c8ede-3ae7-4c9b-8033-4cfd3c721eb1)

**Comment by pyrates999** [comment]
Hi @gurie2024 

Open up EP Properties application and go to about tab and post the version that you see there.

**Comment by gurie2024** [comment]
@pyrates999 version 22621.4317.67.1

they both in pic i send are same version but somehow the menu are different

**Comment by Amrsatrio** [comment]
Screenshot your C:\Program Files\ExplorerPatcher folder.

**Comment by gurie2024** [comment]
@Amrsatrio check below
![image](https://github.com/user-attachments/assets/55bb71e0-e377-48b9-9894-7c7b3dbd3b4d)

**Comment by Amrsatrio** [comment]
The contents.

**Comment by gurie2024** [comment]
do you mean this @Amrsatrio 

![image](https://github.com/user-attachments/assets/9a031ca8-65bb-44b0-b058-68e1c29f0597)

**Comment by Amrsatrio** [comment]
Yes. But please screenshot the About page of the Properties window once again. There's no way that it does not appear, I need to investigate deeply in this case.

**Comment by Amrsatrio** [comment]
Try to uninstall EP. Make sure that folder is cleanly gone. Then install again. Make sure of exclusions as well.
