### ISSUE TITLE
Can´t update Windows 11

### ISSUE THREAD

**Issue by rafael-venaglia** [valinet/ExplorerPatcher#3810]
I am getting this problem.
![image](https://github.com/user-attachments/assets/6619ec05-5c20-4ebc-9456-fab519017143)

I tried to update ExplorerPatcher, but it says "no updates are avaliable".

I just have the windows defender as "anti virus". And I already done the commands in the PowerShell.

**Comment by Neekodesu** [comment]
![image](https://github.com/user-attachments/assets/0cdaa0a5-ae94-4d66-ae4f-51d4907b5fe2)
same here

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another AV installed?

**Comment by pyrates999** [comment]
You most likely have an old version of EP installed.  Download the latest from here: https://github.com/valinet/ExplorerPatcher/releases

Before installing, read the release notes about the powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

**Comment by Amrsatrio** [comment]
Uninstall EP before updating. You can reinstall afterwards.
