### ISSUE TITLE
anyone knows how to fix this?

### ISSUE THREAD

**Issue by notbackspacedotnet** [valinet/ExplorerPatcher#3812]
![Screenshot 2024-10-17 025512](https://github.com/user-attachments/assets/0f293593-9238-4754-9852-1022753a97c0)

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.
