### ISSUE TITLE
add the option to make the taskbar (located on the left or right) thinner

### ISSUE THREAD

**Issue by pekatron9000** [valinet/ExplorerPatcher#3813]

**Comment by pyrates999** [comment]
Right click on the taskbar and untick `Lock the taskbar`.  Then you can make it thinner using the mouse icon.  Then right click on the taskbar and tick `Lock the taskbar`.

**Comment by pekatron9000** [comment]
> Right click on the taskbar and untick `Lock the taskbar`. Then you can make it thinner using the mouse icon. Then right click on the taskbar and tick `Lock the taskbar`.

No, that's not it. I need a MUCH thinner taskbar.
like this:
![photo62460234_457277766](https://github.com/user-attachments/assets/e6d0b218-6fa1-4937-85a7-a8d448b6b6a4)

**Comment by pyrates999** [comment]
Issues are for bugs only, not feature requests.  Please post feature requests in discussions.

**Comment by pyrates999** [comment]
and look at windhawk if they have a mod that does this.

**Comment by Amrsatrio** [comment]
We do not accept new feature requests at this time. You can request the Windhawk community for a mod that can implement this. https://github.com/m417z/7-Taskbar-Tweaker/blob/5111fc16501d5862fccb08bad93c5d9d3fc9ad5f/dll/wnd_proc.c#L4455
