### ISSUE TITLE
[Xmeters] Appears to be supported

### ISSUE THREAD

**Issue by Nick2bad4u** [valinet/ExplorerPatcher#3815]
Just an FYI, not sure if this is useful to you guys, but I have been using [Xmeters](https://entropy6.com/xmeters/) for a long time it appears to work properly with the taskbar reimplementation.

Not sure if that's useful information to add to the wiki for supported mods under [this article](https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#%EF%B8%8F-warning---read-thoroughly-before-using)

I have no relationship to this mod, so feel free to close and remove this if it's not useful information.

**Comment by Amrsatrio** [comment]
This is not a tweak but rather an add on. It integrates into the taskbar using official documented methods which is through the Desk Band APIs, so compatibility is expected. But still, worth to be added. Thanks.
