### ISSUE TITLE
ESET Internet Security blocks wincorlib.dll in ExplorerPatcher version 22621.3880.66.7

### ISSUE THREAD

**Issue by 0xc0000142** [valinet/ExplorerPatcher#3817]
Time 2024/10/17 18:29:58
Scanner Real-time file system protection
Object type File
Object C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\wincorlib.dll
Detection Suspicious Object
Action Cleaned by deletion
User 0XLAPTOP\0xc0000142
Information An event occurred on a new file created by application: F:\Downloads\IDM\Programs\ep_setup_2.exe (226EF8DDF5525975C0BEB7D423671EC2B0569C96).
Hash 16ECA391B4A5DE0A5480A255E8FAF57198A74B46
First seen here 2024/10/17 12:16:04

I got ExplorerPatcher to work by overwriting 22621.3880.66.6

 
![image](https://github.com/user-attachments/assets/32097175-8c5d-4ccb-90e3-b70a98c0f3bb)

**Comment by pyrates999** [comment]
Read release notes here on what you need to exclude for all antiviruses: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment]
Nothing we can do to fix this. Please do not use EP on work machines.

**Comment by konrad79** [comment]
> Read release notes here on what you need to exclude for all antiviruses: https://github.com/valinet/ExplorerPatcher/releases

But even if I exclude the listet files and folders in ESET, the ep_setup.exe still doesn'r run and is killed.

**Comment by packetdog** [comment]
> But even if I exclude the listet files and folders in ESET, the ep_setup.exe still doesn'r run and is killed.

You're excluding the folder where ep_setup.exe is downloaded too? It would be best to exclude the full path only as excluding the downloads folder is probably not a great idea. When you run the installer, I believe it copies itself to a temp folder to run, this could be where we're running into trouble. If you look at the ESet quarantine or detections history, are you not able to create an exclusion there also?
