### ISSUE TITLE
[New Feture Request] When using multiple monitors, handle the shortcuts Win, Win+R, and Win+D.

### ISSUE THREAD

**Issue by eAtmApp** [valinet/ExplorerPatcher#3818]
When using multiple monitors, pressing the shortcuts Win, Win+D, and Win+R will perform the relevant actions on the monitor where the mouse is located.

"I previously wrote a small tool that uses a global keyboard hook to implement Win+D (Show Desktop) functionality across different monitors. I can share the code separately.

Additionally, after analysis, the Win+R function is located here: explorer.protected: unsigned long __cdecl Tray::_RunDlgThreadProc(struct tagRECT *)."

**Comment by Amrsatrio** [comment]
We do not accept new feature requests at this time. But you may wish to use Windhawk to achieve said functionality. Make a mod which hooks that function. Latest prerelease of EP has some classes exported in the taskbar which should help you in making mods.
