### ISSUE TITLE
CLOSED - how do i uninstall on 24h2?

### ISSUE THREAD

**Issue by salrn** [valinet/ExplorerPatcher#3819]
windows says that the app cant be run on my pc. im unable to uninstall and my explorer keeps glitching. what do i do?

**Comment by salrn** [comment]
FIXED ALREADY! I used a old version of ep, from my old drive. i just installed the new version and uninstalled from there.

**Comment by pyrates999** [comment]
please close this.

**Comment by Ha7yad** [comment]
@salrn Click Close by the comment button
