### ISSUE TITLE
Win+X menu broken on W10 (Explorer Patcher) Taskbar Style 24H2

### ISSUE THREAD

**Issue by manofgloss** [valinet/ExplorerPatcher#3820]
I appreciate this is for 24H2 that has only just dropped.

Using the standard W11 taskbar style (W10 is not supported), both the right click on start button and the Win+X hotkey bring up the menu correctly. When using the W10 Explorer Patcher style, it seems to cycle through the taskbar items. Both using right-click and win+X does the same action of cycling through the taskbar items.

Not sure if this is intended behaviour but I can't see it documented or as an option anywhere, so thought I'd raise it. Cheers!

![image](https://github.com/user-attachments/assets/c2888517-08c2-4388-aeb0-52a3c408727c)

**Comment by pyrates999** [comment]
install pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment]
Duplicate of #3671
