### ISSUE TITLE
[24H2] System control flyout needs scrolling to reach all buttons

### ISSUE THREAD

**Issue by bege10** [valinet/ExplorerPatcher#3823]
With 23H2 the flyout was higher and all buttons could be seen in 4 lines.
Now there are only 2 lines to be seen and it needs scrolling.
Is it possible to enlarge the flyout to the previous size?

ExplorerPatcher 22621.3880.66.7

![Screenshot 2024-10-16 093624](https://github.com/user-attachments/assets/dc1fe5b6-f653-4d10-b8bb-5713d4eb2e8e)

**Comment by pyrates999** [comment]
please post your windows build number. You can find out by running winver.

**Comment by bege10** [comment]
Build 26100.2033

**Comment by bege10** [comment]
Yes.

**Comment by pyrates999** [comment]
what if you change it to the windows 11 taskbar?  Does it happen then?

**Comment by milesprower2293** [comment]
Starting with Windows 11 24H2 the notification center and control center are now managed by different executables

**Comment by Amrsatrio** [comment]
This is not a bug. This is yet another questionable decision MS has made in 24H2.

**Comment by Amrsatrio** [comment]
We're not accepting new feature requests right now -- please reach out to Windhawk if someone is able to make a mod that can stretch its height so that scrolling is no longer required. Sorry.
