### ISSUE TITLE
SSMS Object reference not set to an instance of an object. (ObjectExplorer)

### ISSUE THREAD

**Issue by Gusabo** [valinet/ExplorerPatcher#3827]
After installing and uninstalling ExplorerPatcher, on a PC with Win11, SQL Server Management Studio begin to raise the error "Object reference not set to an instance of an object. (ObjectExplorer)" when right-clicking over an object (table, function, sp, etc)
Already tried reinstalling SSMS and the error persists
Any help would be appreciated 
Thanks

**Comment by Amrsatrio** [comment]
Is there any stack trace persisting to that?

**Comment by Amrsatrio** [comment]
https://stackoverflow.com/questions/25574884/sql-server-2012-error-object-reference-not-set-to-an-instance-of-an-object
https://www.google.com/search?q=ssms+object+reference+not+set+to+an+instance+of+an+object

I really doubt EP has anything to do with this.
