### ISSUE TITLE
Explorer patcher update costantly fails

### ISSUE THREAD

**Issue by kryllgore** [valinet/ExplorerPatcher#3828]
![Snap1](https://github.com/user-attachments/assets/ff19af7e-2e01-4799-9752-4c1281a34392)

Maybe someone can tell something about this picture?

**Comment by pyrates999** [comment]
what version of visual studio did you install?  And what edition? community? professional? enterprise?

**Comment by kryllgore** [comment]
Professional.

**Comment by pyrates999** [comment]
and version?

**Comment by Amrsatrio** [comment]
Disable "Build updates locally before installing". I have yet to fix ep_make.
