### ISSUE TITLE
Blocking installation of Windows update

### ISSUE THREAD

**Issue by VulcanTourist** [valinet/ExplorerPatcher#3830]
ExplorerPatcher is blocking installation of a Windows update for 24H2, proceeds to 14% installed and then this:

![screenshot_00010](https://github.com/user-attachments/assets/5870f346-c285-4412-9415-13ecccd07ef5)

**Comment by VulcanTourist** [comment]
Trying to terminate that dialog results in failure with the error code 0xc1900209, a repeat notification "Can't install updates", and the reappearance of a Fix Issue button in the Windows Update window.

**Comment by BumperPopcorn6** [comment]
Me too. Trying pre-release version...

**Comment by BumperPopcorn6** [comment]
Well, EP works on 11 24h2, but windows 10 taskbar is gone, only win10 tsakbar (EP's version)

**Comment by Amrsatrio** [comment]
Uninstall EP before installing 24H2. You can reinstall afterwards. My recommendation is to freeze your system on 23H2.

**Comment by VulcanTourist** [comment]
> My recommendation is to freeze your system on 23H2.

Well that's already been accomplished simply by doing nothing.  24H2 can't install with ExplorerPatcher present.
You don't explicitly say it, so is Explorer Patcher compatible and functional with 24H2, if uninstalled and reinstalled afterward?  If so, then why the recommendation to freeze a system at 23H2?

**Comment by Amrsatrio** [comment]
Yes it is compatible. But we will never know what will MS break next in future 24H2 updates.

**Comment by VulcanTourist** [comment]
> Yes it is compatible. But we will never know what will MS break next in future 24H2 updates.

Other than missing or avoiding new features, are there adverse consequences from simply preventing 24H2 from installing?  23H2 will still get security patches and such that are unaffected by holding back 24H2?

**Comment by Amrsatrio** [comment]
Yes. You will still continue receiving monthly updates until 23H2's end of support date which is more than a year from now still.

**Comment by VulcanTourist** [comment]
If I lose the Windows 10 taskbar, the consequences for me are **much** worse than for most people.  I use an application called True Launch Bar that depends upon the legacy Quick Launch folder, and since I think that disappears entirely without the Windows 10 taskbar then that would also disable True Launch Bar.  I have configured ***everything*** I use within the custom menus I created with it.  Being forced to abandon that would be quite destructive.  I don't know if I can find a suitable alternative.

**Comment by Amrsatrio** [comment]
That's what I'm talking about. I heard that it still works in 24H2 **today**, but future updates might nuke more remnants of the 10 taskbar such as the code for supporting taskbar toolbars. It's better to stay safe. Or if you don't mind you can jump ship to 10 LTSC.

**Comment by caliban511** [comment]
> 如果我丢失了 Windows 10 任务栏，对我来说的后果 **比大多数人要严重 **得多 _**。我使用一个名为 True Launch Bar 的应用程序，该应用程序依赖于旧版快速启动文件夹，并且由于我认为如果没有 Windows 10 任务栏，该应用程序就会完全消失，那么这也会禁用 True Launch Bar。我已经 **_在用它创建的自定义菜单中配置了我使用的 所有内容 。被迫放弃这一点将是相当具有破坏性的。我不知道是否能找到合适的替代方案。

 True Launch Bar 是好软件，我也一直在用。
