### ISSUE TITLE
Taskbar does not remember position

### ISSUE THREAD

**Issue by JohnChristmann** [valinet/ExplorerPatcher#3831]
On Windows 11 24H2 (26100.2033) I set up ExplorerPatcher (22621.3880.66.6) in Windows 10 (ExplorerPatcher) mode so that I can keep the taskbar only on my secondary display.  Any time the Explorer crashes (which it seems to randomly several times per day,) on every reboot, or when manually restarted through the settings, the taskbar resets to being on the primary display.  This did not happen in Windows 10 (regular) mode on Windows 11 23H2 previously (nor did the crashes, but that's another matter.)

**Comment by Amrsatrio** [comment]
Download latest prerelease. It is fixed there. I haven't promoted it to release because there are some other bug fixes I want to publish in 66.8.

**Comment by JohnChristmann** [comment]
Thanks, will do.
