### ISSUE TITLE
Show Weather on Taskbar not working due to the file being deleted.

### ISSUE THREAD

**Issue by MaxwellTheGoober** [valinet/ExplorerPatcher#3835]
Hello, I'm here since windows deleted the file used to enable the show weather on taskbar, Does anyone know how to get the file back, and where to put it in? I reinstalled but it doesnt seem to do anything, not even resetting my settings.

**Comment by MaxwellTheGoober** [comment]
And yeah, I know i just submitted an closed issue, but i thought reinstalling would work.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3546

please close this.

Please install the latest pre-release for weather to work again: https://github.com/valinet/ExplorerPatcher/releases

**Comment by MaxwellTheGoober** [comment]
> duplicate of: #3546
> 
> please close this.
> 
> Please install the latest pre-release for weather to work again: https://github.com/valinet/ExplorerPatcher/releases

Sorry, I HAVE tried that, but it unfortunately hasnt worked, I'll close it, but thanks for assisting.

**Comment by pyrates999** [comment]
can you post the EP version you have installed?  Open up the EP properties application and click on About on the left side.

**Comment by MaxwellTheGoober** [comment]
> can you post the EP version you have installed? Open up the EP properties application and click on About on the left side.
![rundll32_vWO2l3nS4G](https://github.com/user-attachments/assets/1bbbebc7-3d0c-46a0-8fe1-e58918501f86)

**Comment by pyrates999** [comment]
did you run the powershell commands to add exclusions for windows defender?

**Comment by MaxwellTheGoober** [comment]
> did you run the powershell commands to add exclusions for windows defender?

Yep.
![ApplicationFrameHost_E8UXoGyXxE](https://github.com/user-attachments/assets/70500132-f980-4a93-af99-d79558416f67)
It gave this when downloading, RTP off and installed
![ApplicationFrameHost_nPp94hGB93](https://github.com/user-attachments/assets/9bf9d430-4450-45c2-b9e0-2f700af93b8c)
But it still refused to work

**Comment by pyrates999** [comment]
Try adding the directory that you download ep_setup.exe as well.  It might be interfering with the install of EP.

**Comment by MaxwellTheGoober** [comment]
> Try adding the directory that you download ep_setup.exe as well. It might be interfering with the install of EP.

I downloaded it straight into /downloads, Should i just, disable checks for /downloads or do i put it into something like Documents?

**Comment by pyrates999** [comment]
Create a sub directory for it and move ep_setup.exe into that sub directory.  Then exclude that subdirectory in windows defender.

**Comment by MaxwellTheGoober** [comment]
> Create a sub directory for it and move ep_setup.exe into that sub directory. Then exclude that subdirectory in windows defender.

So i uninstall EP, make a folder? then download EP_Setup.EXE into that  folder?

**Comment by pyrates999** [comment]
make a folder for ep_setup.exe.  Add that same folder to the exclusions list for windows defender.  Then download ep_setup.exe to that folder.

**Comment by MaxwellTheGoober** [comment]
> make a folder for ep_setup.exe. Add that same folder to the exclusions list for windows defender. Then download ep_setup.exe to that folder.

No luck. Did that, set it up, didnt work.

**Comment by pyrates999** [comment]
Make sure you're on the windows 10 taskbar:

Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by MaxwellTheGoober** [comment]
> Make sure you're on the windows 10 taskbar:
> 
> Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**. We no longer offer more support on the stock Windows 10 taskbar.
Where exactly is that? I can't seem to locate it.

**Comment by pyrates999** [comment]
are you on windows 10 or 11? and what is your windows build number?  you can find this by running winver.

**Comment by MaxwellTheGoober** [comment]
> are you on windows 10 or 11? and what is your windows build number? you can find this by running winver.

WIN 10, 22H2, 19045.5011

**Comment by pyrates999** [comment]
Ah same as me then.  So I can confirm this isn't because a file was deleted.  If it's working on windows 11 in the pre-release, It's a bug in EP on windows 10.

**Comment by MaxwellTheGoober** [comment]
> Ah same as me then. So I can confirm this isn't because a file was deleted. If it's working on windows 11 in the pre-release, It's a bug in EP on windows 10.

awh, that sucks ;w;

**Comment by MaxwellTheGoober** [comment]
> Found this is discussed here: #3405

Yeah, i don't think i have the brain capacity to make it work again XD.
