### ISSUE TITLE
Windows update disables compatibility

### ISSUE THREAD

**Issue by BigHoss** [valinet/ExplorerPatcher#3836]
after updating to 24H2 I get the following error when I try to start explorer patcher
![image](https://github.com/user-attachments/assets/e47bc4c9-469a-4336-b758-58f6540716c1)

**Comment by pyrates999** [comment]
When upgrading windows, you are to uninstall EP first.

Uninstall it and install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

Read release notes to find out what directories and files to exclude from windows defender before installing it.

**Comment by milesprower2293** [comment]
Are you installing 66.6?

**Comment by BigHoss** [comment]
i installed via winget. the prerelease solved the issue, thx for the help
