### ISSUE TITLE
[226xx.4317+] Win+X menu does not work even after symbols have been downloaded

### ISSUE THREAD

**Issue by gtdurham** [valinet/ExplorerPatcher#3837]
The lastest update from Microsoft, KB5044380 breaks the right click start menu on the task bar.

**Comment by pyrates999** [comment]
that's a preview update: https://support.microsoft.com/en-us/topic/october-22-2024-kb5044380-os-builds-22621-4391-and-22631-4391-preview-9a8db86a-815d-470a-be95-1aa2ad1feb05

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by andersoncursino** [comment]
I can confirm the issue, maybe is not only KB5044033 but KB5044285 too. And I can confirm that both are not preview update, they are updated on regular update even with the options to get the last updates as soon as available off.

**Comment by Amrsatrio** [comment]
Developed the fix, will come in 66.8 or 67.1. We have some other bugs to polish first. Thanks for your patience.

**Comment by pyrates999** [comment]
> I can confirm the issue, maybe is not only KB5044033 but KB5044285 too. And I can confirm that both are not preview update, they are updated on regular update even with the options to get the last updates as soon as available off.

That's correct because MS didn't include the word preview in the webpages about them.

**Comment by gorillale** [comment]
Ich hatte das auch und es wird mir auch kein Update auf 24H vorgeschlagen, Auch Norton mach keine Update mehr auf die 24.x.

Für Valinet tut es mir echt leid, hat ja bis jetzt sehr gut funktioniert und herzlichen dank für seine Arbeit, die Spende hat er sich 100x verdient.

Anschreiend hat es Microsoft geschafft die User noch mehr zu Quälen damit man die Toolbar nicht mehr benutzen kann. Und ich habe nun die Schnauze voll und programmiere mir selber eine Toolbar, so wie die Linkbar, aber wo ich das ganze so gruppieren kann wie ich die Symbole haben will.
(die Menus habe ich bereits auf win11 umgestellt, da ich die nur ganz selben benutze)

Aber der ZORN auf Microsoft wächst so nur mehr und ich verstehe nicht dass Benutzer die Programmieren auf diese Toolbar angewiesen sind und ein PC kein Tablet oder Handy ist. 
Microsoft es einfach nicht begreifen will dass die User es so wollen. 

Nun neue Programme werden nur noch gekauft wenn sie auf Win + Linus ausführbar sind, da ich Microsoft nicht mehr traue , denn da wird wohl dann noch mehr an Abzocke und Abos kommen.

**Comment by Nano33320** [comment]
Bonjour
J'utilise explorer patcher pour plusieurs raisons liées au manque/perte fonctionnalité de Windows 11
mais la plus importante pour mon usage concerne "l'épinglage" de fichiers sur le menu d'une application
![image](https://github.com/user-attachments/assets/ab1ae678-bb3d-4c27-a236-5733307f83e4)
J'aimerai retrouver cette fonctionnalité qui existait dans Win 10 et plus dans Win 11.
Explorer Patcher permet de la retrouver.
je suppose qu'une ou plusieurs ligne dans la base de registre en sont la cause.
Est-il possible d'avoir ce correctif/modification ?
Merci
---- Google translation ----
Hello
I use explorer patcher for several reasons related to the lack/loss of functionality of Windows 11
but the most important for my use concerns the "pinning" of files on the menu of an application
![image](https://github.com/user-attachments/assets/ab1ae678-bb3d-4c27-a236-5733307f83e4)
I would like to find this functionality that existed in Win 10 and more in Win 11.
Explorer Patcher allows to find it.
I suppose that one or more lines in the registry are the cause.
Is it possible to have this fix/modification?
Thanks

**Comment by pyrates999** [comment]
> Bonjour J'utilise explorer patcher pour plusieurs raisons liées au manque/perte fonctionnalité de Windows 11 mais la plus importante pour mon usage concerne "l'épinglage" de fichiers sur le menu d'une application ![image](https://private-user-images.githubusercontent.com/116868108/380600450-ab1ae678-bb3d-4c27-a236-5733307f83e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTgyNzYsIm5iZiI6MTczMDA5Nzk3NiwicGF0aCI6Ii8xMTY4NjgxMDgvMzgwNjAwNDUwLWFiMWFlNjc4LWJiM2QtNGMyNy1hMjM2LTU3MzMzMDdmODNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNjQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDEyYjBiZDY3ZDQ5OWQ2ODcyMWQ2NzM3ZjUzYmVkZDRmMTVjMTJhNzgwOTE3NGFhMGE4MTdhODRiMDlkZmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pfvOgsU4nzxLyQ3aL2OxAM0SIX2AWfuKRm68OrUr8JQ) J'aimerai retrouver cette fonctionnalité qui existait dans Win 10 et plus dans Win 11. Explorer Patcher permet de la retrouver. je suppose qu'une ou plusieurs ligne dans la base de registre en sont la cause. Est-il possible d'avoir ce correctif/modification ? Merci ---- Google translation ---- Hello I use explorer patcher for several reasons related to the lack/loss of functionality of Windows 11 but the most important for my use concerns the "pinning" of files on the menu of an application ![image](https://private-user-images.githubusercontent.com/116868108/380600450-ab1ae678-bb3d-4c27-a236-5733307f83e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTgyNzYsIm5iZiI6MTczMDA5Nzk3NiwicGF0aCI6Ii8xMTY4NjgxMDgvMzgwNjAwNDUwLWFiMWFlNjc4LWJiM2QtNGMyNy1hMjM2LTU3MzMzMDdmODNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNjQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDEyYjBiZDY3ZDQ5OWQ2ODcyMWQ2NzM3ZjUzYmVkZDRmMTVjMTJhNzgwOTE3NGFhMGE4MTdhODRiMDlkZmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pfvOgsU4nzxLyQ3aL2OxAM0SIX2AWfuKRm68OrUr8JQ) I would like to find this functionality that existed in Win 10 and more in Win 11. Explorer Patcher allows to find it. I suppose that one or more lines in the registry are the cause. Is it possible to have this fix/modification? Thanks

Please post feature requests in discussions.

**Comment by Amrsatrio** [comment]
67.1 containing the fix is being built.

**Comment by Amrsatrio** [comment]
67.1 has been promoted to release. Closing this issue.
