### ISSUE TITLE
[ep_taskbar] Toolbar item sort order not remembered in dropdown toolbars

### ISSUE THREAD

**Issue by dunsparce9** [valinet/ExplorerPatcher#3841]
Only started happening after switching to EP's taskbar implementation.

Consider a vertical toolbar like this:
![{CB66FFDC-0913-40B3-B5E1-01127FABD478}](https://github.com/user-attachments/assets/45dd1709-8a89-459e-ab20-faa02ad62def)

When the sort order is changed (via dragging items around), it used to stay between Explorer and/or Windows restarts. After EP's taskbar in 24H2, the sort order always reverts to alphabetical after each restart.

Weirdly enough, the sort order \*is\* saved on horizontal toolbars like these, but not on vertical toolbars.

![{38BF1010-B0A3-48CE-88AD-4DBEEF49E39E}](https://github.com/user-attachments/assets/20d41e31-10ce-4bb1-bda1-6de02ba31eab)

**Comment by pyrates999** [comment]
please don't open duplicate tickets: https://github.com/valinet/ExplorerPatcher/issues/3805

please close this.
