### ISSUE TITLE
Menus on task bar

### ISSUE THREAD

**Issue by Santi3141** [valinet/ExplorerPatcher#3845]
Helo,

with Windows actualisation 26100.2033, EP 22621.3880.66.6 was unable to work on my computer. EP 22621.3880.66.7 is working but I am unable to add menus to the taskbar in form of folders with direct accesses as I used to do. For me one of the best features of EP.

Thanks.

**Comment by pyrates999** [comment]
do you mean quick launch toolbar?  See this comment: https://github.com/valinet/ExplorerPatcher/issues/3805#issuecomment-2424200209

**Comment by Santi3141** [comment]
Saw it and yes, what I want is to use quick launch toolbar. I am not able to use them in the last version of EP.

**Comment by milesprower2293** [comment]
@Santi3141 right click you taskbar press toolbars then press 'New toolbar' and put this path
%APPDATA%\Microsoft\Internet Explorer\Quick Launch
