### ISSUE TITLE
flashing icons

### ISSUE THREAD

**Issue by Garze23** [valinet/ExplorerPatcher#3848]
![image](https://github.com/user-attachments/assets/06ede3f3-d58a-4fab-ba0d-37db04cd45b0)
hello, as you can see the icons in the taskbar flash and this is already deactivated in the windows taskbar settings

-taskbar hidden automatically
-taskbar: windows 10
-small icons

would you have a solution to disable it ?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another antivirus installed?

**Comment by Garze23** [comment]
![image](https://github.com/user-attachments/assets/86b6fe5d-9379-4018-9924-8e8230f8a933)
-x86-64
-french
![image](https://github.com/user-attachments/assets/1ba90a92-1d13-4b55-8e5a-993993418498)
![image](https://github.com/user-attachments/assets/89c1d71d-4f8f-4d07-b660-c9baea1e3dbc)
![image](https://github.com/user-attachments/assets/957c6bcb-12fd-4021-9ed9-c2ff0791a04b)
![image](https://github.com/user-attachments/assets/c655da72-5fd8-4bd3-98b5-330859ac9135)
![image](https://github.com/user-attachments/assets/6185fa4e-04d6-41ef-a4fe-006da723bb77)
![image](https://github.com/user-attachments/assets/274426fc-4cc7-4276-b968-edd9ac329391)
![image](https://github.com/user-attachments/assets/82e89e26-91f1-4af6-a289-a6ef08d3a7ee)
![image](https://github.com/user-attachments/assets/24d7e2f4-a98c-480a-b46d-313fcc6be38b)
![image](https://github.com/user-attachments/assets/a176c608-3aab-4508-a57a-4b7908f4e931)
![image](https://github.com/user-attachments/assets/2d4ad0f7-f68f-4dce-afd9-c77ba2a06616)
only windows defender

**Comment by pyrates999** [comment]
and you tried this? https://www.partitionwizard.com/partitionmagic/windows-10-taskbar-flickering.html

The method used in windows 11 may not effect the windows 10 taskbar.  Did you try restarting file explorer using the EP properties application?

**Comment by Garze23** [comment]
no result for the link
yes so many times that i restart the explorer in explorer patcher

**Comment by pyrates999** [comment]
and rebooting didn't help?

**Comment by pyrates999** [comment]
try this: https://www.thewindowsclub.com/disable-flashing-taskbar-buttons-windows

It involves a registry change.  You will need to restart file explorer using EP Properties application after.

**Comment by Garze23** [comment]
![image](https://github.com/user-attachments/assets/089aecc0-0bf6-4e82-a4f2-da7e73dd3699)
it didn't work and i restarted the file explorer

**Comment by pyrates999** [comment]
Ok, considering the windows 10 taskbar is no longer available in windows 11 24h2.  Could you try the following:

Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.

**Comment by Garze23** [comment]
this didn't work either and I restarted the file explorer again

**Comment by pyrates999** [comment]
One last thing, did you disable `show badges` in settings? https://github.com/valinet/ExplorerPatcher/wiki/All-features#primarysecondary-taskbar-location-on-screen

If that doesn't work, please wait for a developer to respond.

**Comment by Garze23** [comment]
![image](https://github.com/user-attachments/assets/e6f57e7b-cab9-4ac7-ab75-420917d184b7)
I can't even activate it in any case

**Comment by pyrates999** [comment]
Try this: https://www.elevenforum.com/t/enable-or-disable-show-badges-on-taskbar-apps-in-windows-11.3659/

And I read if you set the icon size in the taskbar to be small instead of large, the option to show badges will be greyed out.

**Comment by Garze23** [comment]
this didn't work either even with the taskbar size set to large and I restarted the file explorer again

**Comment by Garze23** [comment]
no this solution still does nothing even that changed to 1 the values on the register

**Comment by pyrates999** [comment]
Ok, please wait for a developer to respond.

**Comment by Amrsatrio** [comment]
Duplicate of #2498

**Comment by Amrsatrio** [comment]
The new setting in Windows 11 is not implemented in the Windows 10 taskbar. Some day I will implement it to the Windows 10 (ExplorerPatcher) taskbar.

Anyways to fulfill your needs, consider checking this post: https://superuser.com/questions/1332330/how-to-disable-flashing-icons-in-windows-10-taskbar

**Comment by Garze23** [comment]
no, it doesn't work, and what's more I've already tried it

**Comment by JLsteely** [comment]
Any ETA on when this will be implemented? Still an issue, a fix would be incredible!
