### ISSUE TITLE
Windows 10 alt+tab opacity

### ISSUE THREAD

**Issue by Neko-urself** [valinet/ExplorerPatcher#385]
Hi,

Changing opacity doesn't seem to do anything.
it looks like its always 100% opaque.

https://i.imgur.com/qcvLILG.png
screenshot taken on top of github while writing this.

Thanks

**Comment by valinet** [comment]
Opacity works only with acrylic theme for the moment, it's already mentioned.

**Comment by Neko-urself** [comment]
yes, i was doing this all with the acrylic theme. at least that what it says on the setting but i just noticed that changing that setting doesnt do anything

**Comment by BraINstinct0** [comment]
Before further discussing: 
1. Try restarting Explorer.
2. Try restarting system.
3. Iff issues persist, post screenshots that clearly show this issue.

That way the issue can be determined/addressed more easily.

**Comment by Neko-urself** [comment]
thats from boot, switched from windows 11 switcher to windows 10 and restarted explorer. it was already set on those settings before i switched to windows 10 switcher.
![image](https://user-images.githubusercontent.com/17310755/142154548-1208d10c-ab8b-4530-83ef-a05a4947a10e.png)
![image](https://user-images.githubusercontent.com/17310755/142154790-551d916c-634f-4a33-bc88-d132b85a4946.png)

**Comment by Neko-urself** [comment]
just restarted my pc, still the same as the 2nd screenshot

**Comment by valinet** [comment]
Maybe check this out, idk, acrylic works for me just fine, some reported it is a power plan thing, idk exactly… it’s a thing an app asks the compositor to do, from thereon, the compositor decides to do it or not and you get some result. Of course, transparency with no theme would be great as well, I plan to do that at some point, that was the plan originally but some complications made me implement acrylic and mica first.

https://github.com/microsoft/microsoft-ui-xaml/issues/2737

**Comment by Neko-urself** [comment]
wow, it was a transparrency setting in accessibility. . . i never changed that setting not sure why it was set to off.

Thanks for resolving that for me!

**Comment by valinet** [comment]
You're welcome. Can you tell exactly what worked for you in a short message here so that other users potentially facing the same problem have a way to solve it for themselves as well? Thanks.

**Comment by Neko-urself** [comment]
The fix was in:

Windows Settings  >  Accessibility  >  Visual Effects
set "Transparrency Effects" to On

![image](https://user-images.githubusercontent.com/17310755/142170010-e5fc0319-a699-4099-b3ab-824fa2f1e769.png)
