### ISSUE TITLE
ep_explorer win 10 taskbar not locked on multiple monitors

### ISSUE THREAD

**Issue by puuhbear** [valinet/ExplorerPatcher#3855]
ExplorerPatcher Version: 22621.3880.66.6
Win11 Pro 24H2 build 26100.2161
taskbar style: Windows 10 (ExplorerPatcher) 

I like my main taskbar (and the system tray) on my left monitor (not the main screen) but it keeps reverting to the middle monitor (main screen) after every restart. "Lock all taskbars" does prevent from moving the taskbar manually but still moves the tasbar back to the middle screen after restarting the PC or the ExplorerPatcher

**Comment by Solithe** [comment]
Fixed in 66.7

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.7_78e6248

**Comment by puuhbear** [comment]
thank you :)
