### ISSUE TITLE
Option that is not there

### ISSUE THREAD

**Issue by Sapelain** [valinet/ExplorerPatcher#3857]
In the sidebar does not appear in the configuration, images ni documents.

When I enter the configuration I can't find how to put the shortcuts.

W10 menu
![Sin título](https://github.com/user-attachments/assets/ac01a560-28cb-4453-ae31-4be1cc9ecc76)

Windows 11 24h2

![idioma 2](https://github.com/user-attachments/assets/877897cf-760d-4dc8-af2f-7f3f2a42f263)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another antivirus installed?

**Comment by milesprower2293** [comment]
You can do it the same way as the 11 Start menu

**Comment by Sapelain** [comment]
Thanks
