### ISSUE TITLE
Tiles configuration file and ability to customize Tile layout

### ISSUE THREAD

**Issue by seu-yx** [valinet/ExplorerPatcher#3859]
# Description
Hello, I am using Windows 11 and would like to know the exact location of the configuration file that stores the layout for the Windows 10 Start Menu Tiles. Additionally, I am interested in understanding if it is possible to directly modify this configuration file to customize the layout of Tiles. Because I’m experiencing the same issue as described in #3842. When I pin an item to the Start Menu and attempt to right-click to resize it, the Start Menu crashes.

# Environment
Operating System: Windows 11 23h2 22631.4391
version: 22621.3880.66.6

Thank you very much for your assistance!

**Comment by Amrsatrio** [comment]
I have fixed the issue in 67.1. For the configuration files I do not really know, but they are binary serialized in the registry, and doesn't seem like easily modifiable by hand.
