### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by shenhaipaopaoa** [valinet/ExplorerPatcher#3860]
1.I am unable to place programs such as Edge Browser and File Explorer on Win10 style full screen Lives Tiles. when right clicking on it, it will wait 1 second and then open.
2.When right clicking on the taskbar, the translation is incomplete.

Both the official and pre-release versions have these issues at 26100.2033

Environment
Operating System: Windows 11 24h2 26100.2033

language
Chinese

Thank you very much for your assistance!

**Comment by pyrates999** [comment]
might be related to this: https://github.com/valinet/ExplorerPatcher/issues/3667

do you have the start menu style set to windows 10?

**Comment by milesprower2293** [comment]
@shenhaipaopaoa 
1. that's a current bug on the 10 start menu you can discuss about that issue on here: #3842 
2. you can ask Amrsatrio if you want to help with the translation on the reimplemented taskbar
