### ISSUE TITLE
"Disable rounded corners for application windows" does not work

### ISSUE THREAD

**Issue by Shatteredpaw** [valinet/ExplorerPatcher#3862]
Hi there.
I've encountered an issue while trying to use the "Disable rounded corners" setting after updating to 24H2.
I have tried both the stable, and pre-release versions of ExplorerPatcher, with no such luck.
I am using Windows 11 24H2, build 26100.2033.
Any help would be appreciated, thank you.

**Comment by pyrates999** [comment]
is it related to this? https://github.com/valinet/ExplorerPatcher/issues/3555

did you tick "Disable quadrants when snapping"?

**Comment by pyrates999** [comment]
after unticking "Disable quadrants when snapping", did you then try ticking "Disable rounded corners"?

**Comment by milesprower2293** [comment]
At the moment the patch for rounded doesn't work and there are not plans to fix it yet

**Comment by neurokinnetix** [comment]
this was such an important feature for me! i would be eternally grateful if you could please fix at the earliest convenience

**Comment by Caracarn** [comment]
+1 in support for trying to revive this feature in 24H2. Without it, my other 3 machines will have to continue running 23H2 a lot longer.

**Comment by Margen67** [comment]
This still works: https://github.com/valinet/Win11DisableRoundedCorners

**Comment by gtaiscool236** [comment]
> This still works: https://github.com/valinet/Win11DisableRoundedCorners

i tried it and it does nothing for me.

**Comment by obliterationnn** [comment]
Please fix this
