### ISSUE TITLE
Windows 11 detecting weather host stub as a posible virus 

### ISSUE THREAD

**Issue by jvhellraiser** [valinet/ExplorerPatcher#3863]
Windows 11 is blocking weather app from loading, at first it did gave me and option to let the app load from inside the antivirus  windows security program but today was block but i did not got the notification from the antivirus program and the program still got block from loading a screen grab
![Screenshot 2024-10-31 085708](https://github.com/user-attachments/assets/6332c125-3934-41c6-86a7-79060727e5d2)
i am not sure whats happening but if this continues i can keep the program install since i dont like my taskbar be working half way.

**Comment by nexusV2** [comment]
On my system the weather stopped working today (Unable to load weather information
Make sure that the location you have entered is correct. Verify that you are connected to the Internet. ) 
When pressig the reload button wether shows up for about 2 seconds and disappears again.

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

All builds of EP are done by github build servers against the source code in the repo.  Only binary is the reimplemented windows 10 taskbar and windows 10 start menu files.  There is no third party build servers.

This is a false positive.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.

**Comment by nexusV2** [comment]
It´s not the same. I had excluded EP and weather widget suddenly stopped working yesterday.

**Comment by milesprower2293** [comment]
@nexusV2 known issue about the explorerpatcher's weather widget and there are no plans to fix it yet
