### ISSUE TITLE
Windows11 Update で、スタートの右クリックが使えなくなった！

### ISSUE THREAD

**Issue by shinya-hirotake** [valinet/ExplorerPatcher#3866]
最新？の Windows Upate を実行していなかった少し古いパソコンでは、スタートの右クリックが使えていたが、
Windows Update を実行したら、使えなくなった！
いろいろと、ネットを調べて、対応を検討したが、いまだに、使えない。
マイクロソフトが「意識的に」、妨害している？
あきらめて、必要な「リンク？」を起動している。

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3837

please close this.
