### ISSUE TITLE
Option to Always Reveal Action List

### ISSUE THREAD

**Issue by CompuGenius-Programs** [valinet/ExplorerPatcher#3867]
Is it possible to add an option that will automatically show the Action List here:
![image](https://github.com/user-attachments/assets/6b1bc639-b5d9-49d0-9a75-1bedcb2a9c77)

Even switching to the Windows 10 start menu shows this search interface, and I can't find any other solutions.

**Comment by Amrsatrio** [comment]
No. Please submit a mod request to Windhawk. We do not tweak the search app and will never be.

**Comment by CompuGenius-Programs** [comment]
Thank you.
