### ISSUE TITLE
Show icons & notifications options are not visible on Customize notification area icons dialog in Windows Insider build. 

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#3868]
ExplorerPatcher: v22621.3880.66.6
Windows Insider Build
Repro Steps:
1. Deploy latest Windows Insider OS build.
2. Perform Windows Updates.
3. Install the latest version of ExplorerPatcher from official website.
4. Launch the application.
5. Click on taskbar & click on customize notifications area icon option
6. observe

Actual result: Show icons & notifications options are not visible on Customize notification area icons dialog.

NOTE: those options show well on non Windows insider build
![image](https://github.com/user-attachments/assets/6028590f-46db-4820-98e8-5d330dadfbc9)

**Comment by pyrates999** [comment]
They might be removed on the insider build you're running as EP only links to that control panel.

**Comment by milesprower2293** [comment]
It seems that Stobject.dll is gone...

**Comment by Michellehdr** [comment]
@milesprower2293 did you see the fix on 27744.1000? I still could see the bug on latest build (27749.1000)
