### ISSUE TITLE
A Windows 10 Taskbar is not supported (It was till update)

### ISSUE THREAD

**Issue by deeseem** [valinet/ExplorerPatcher#3872]
I wasn't going to bother updating Windows if it broke EPs taskbar fix. It appears that it has, as when I go into the EP properties it says Windows 10 taskbar is not supported in this version.

The only reason I updated is I checked here and it said it was now working on the latest Windows 11 update. Is this likely to be fixed at any point or I just to have roll back and hope it works on the previous 11 build still?

At least I didn't update my laptop, and hopefully a rollback will sort out the taskbar problem, but best people who use EP explicitly and primarily to get a suitable user friendly taskbar will know things may not go as hoped for if they upgrade to MS's fantastic new build.

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by deeseem** [comment]
![Win11EPatcherFail](https://github.com/user-attachments/assets/cff77e37-3033-4a94-a5b9-80e6831755d2)

Screenshot of EP, Taskbar, and just to note that I'm greatful for your work on this project. At least I had a usable taskbar for  some of my time on 11. Need to look for other options and a next move, as I draw the line at not being able to resize my taskbar. Too far MS. For no good reason.

**Comment by Amrsatrio** [comment]
> Open up EP Properties application, go to taskbar, and set taskbar style to Windows 10 (ExplorerPatcher), not Windows 10. We no longer offer more support on the stock Windows 10 taskbar.

Yes. Do as said. It's the only way we can get the 10 taskbar experience on latest 24H2. And you chose to upgrade to 24H2, which means you're still subject to their almost monthly breakages.

Regarding the README, I will update it shortly.
