### ISSUE TITLE
Clicking right button on the icon at the Start menu fails to bring about a list of recent files opened by the application

### ISSUE THREAD

**Issue by Volod-D** [valinet/ExplorerPatcher#3873]
It is sometimes very convenient to open some recently opened files, say, in Word, by right-clicking on the Word icon at the Start menu. Then a brakedown of many recent files appeared, and I could chose the one I need. 

Unfortunately, this option fails after the last update. When I righ-click a small round appears as if the system is preparing the list, then the Start meny just closes.

**Comment by pyrates999** [comment]
if you enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by pyrates999** [comment]
Try the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

It has a fix for jump lists.

**Comment by Amrsatrio** [comment]
Duplicate of #3842
