### ISSUE TITLE
Clarify the warning

### ISSUE THREAD

**Issue by sacrosanctic** [valinet/ExplorerPatcher#3878]
![image](https://github.com/user-attachments/assets/e266b145-db52-4c5a-a518-cb31f27f0175)

After seeing Microsoft's warning and trying to find reassurance, the way this warning presents itself can lead users to think they are indeed downloading a virus.

### Suggestion
`Microsoft is flagging Explorer Patcher as malicious software. This is likely due to their hatred against Explorer Patcher, not because it contains viruses.`

**Comment by Amrsatrio** [comment]
What about this?

![image](https://github.com/user-attachments/assets/b822be99-46dc-4b2d-a9cc-984223b58795)

**Comment by Amrsatrio** [comment]
Edited.
