### ISSUE TITLE
"Windows cannot access the specified device, path, or file."

### ISSUE THREAD

**Issue by Kandosii** [valinet/ExplorerPatcher#3881]
Experienced on Widnows 11 Pro, Version 23H2, OS build 22631.4317. 

ExplorerPatcher is still working, but cannot update. Attempting to update from either within the application or from the latest installer results in the following error message. Running as admin does not change the result.

![image](https://github.com/user-attachments/assets/7b065264-d53e-4a29-aa6a-8e9a72d691af)

**Comment by pyrates999** [comment]
windows defender or your AV might be blocking it.

make sure you run the powershell commands to add the exclusions that EP needs: https://github.com/valinet/ExplorerPatcher/releases

If you have another antivirus, you must add those exclusions manually.

**Comment by Kandosii** [comment]
Interesting. I'd already applied those exclusions for a previous update, but I noticed Windows Defender was hanging on something. Restarted, still couldn't update from the  ep_setup.exe installer for 22621.4317.67.1, but updating from within ExplorerPatcher worked. Previously, both were triggering the issue.

**Comment by Amrsatrio** [comment]
Defender prevented the install. Turn off real-time protection before running the exe (which you have to make sure that you downloaded from the real source). After running it, delete the exe so that you won't get notified afterwards.

**Comment by pyrates999** [comment]
I would also add the directory you download ep_setup.exe to.  Make it a specific directory instead of the regular downloads directory.
