### ISSUE TITLE
ep-taskbar forget its position after reboot

### ISSUE THREAD

**Issue by Protheus23** [valinet/ExplorerPatcher#3883]
I have 3 Monitors and the Taskbar is located on the second monitor (not the primary).
After reboot the ep taskbar is always on the primary monitor.

Windows 11 Pro
Windows Version: 23H2 (Build 22631.4169) (Rolled Back from 24H2 but the issue was the same in 24H2)
Architecture: x64 (AMD Ryzen 7 3700X)
Windows Language: German
EP Version: 22621.3880.66.6

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

**Comment by Protheus23** [comment]
done

**Comment by pyrates999** [comment]
Thank you.  Please wait for a developer to respond.
