### ISSUE TITLE
this happens to me everyday

### ISSUE THREAD

**Issue by YOYYORYYODABOB** [valinet/ExplorerPatcher#3886]
so when i open my minecraft launcher and move any app the whole explorer justs crashes i uninstalled and it still keeps happening to me i want to fix it because it looks like it isnt uninstalled yet due to the windows security problem when i installed this it uninstalled the ep_setup due to false positives now i cant remove it

**Comment by pyrates999** [comment]
See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

**Comment by Amrsatrio** [comment]
Configure the exclusions, and then uninstall. Or go to C:\Windows and rename dxgi.dll to dxgi-.dll or delete it. Then restart Explorer. If Explorer keeps crashing then it's not EP who's causing it.
