### ISSUE TITLE
Defect - EP blocks system restore

### ISSUE THREAD

**Issue by explor202** [valinet/ExplorerPatcher#3892]
When attempting to use system restore, the restore process fails. The message displayed indicates an issue with the weather feature of EP, even though that's not currently used on this PC.

Windows 11, 24H2

**Comment by Amrsatrio** [comment]
What's the message?

**Comment by explor202** [comment]
![ScreenShot001](https://github.com/user-attachments/assets/79fad187-235d-498e-86d3-676acbfec56c)

**Comment by Amrsatrio** [comment]
But really, have you added the exclusions as pointed out in here?

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.4317.67.1_b93337a

**Comment by Amrsatrio** [comment]
Closing due to no further replies and that this is Defender-related which is out of our control.
