### ISSUE TITLE
Explorer Patch 10 

### ISSUE THREAD

**Issue by SHIELD22** [valinet/ExplorerPatcher#3894]
I had all the Instilation Problems have the Big Update from Windows patch 84 they used 3 of them it Flags if you have ti Inplace Install and don't take the updates cause you have them already on yopu're P  you have revo Uninstaller to uninstall Exploer patch to get the Windows  24     .iso to install then when try to install Power shell 7 had a few Gitchs you put the What was typed in the page before you in stall i turned off my avg and real time it didn't give me the error but looks like each line went then it stops it doesn't say completed when I Install the latest update the task bar gos a way for a bit then come back the windows calaender and clockl  doesn'tr show the windows 10 Flyout style I used tweak areo and it didn't when into regedit to install this
and this din't work they blocked a lot of installs and turned them off to except anything from windows 10
Here's how to:
1. Run the REGEDIT
2. Browse the following location: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\ImmersiveShell
3. Now, select the key called "UseWin32TrayClockExperience".
4. Change its value data to "1".
And the best thing about this feature is that you don't need to log off or restart your PC in order to apply changes. You're good to go! :)
  it's Not my Bosegame Pc The manifacture won't take the new version and install them on there New Pcs untill they get a full working version with these features restores when you Have more them 4MB of ram and have 64gb of ram Ryzen 7 or 9 it's meat's the standards of whats requiered for high disk useage  what ever Instal Direct In regedit  it's ither turned off or removed  check All the reg edit Windows 10 setting's at the windows Botton the unit there proc in there and eDesktop exploer thats has all the setting's when i had 23H2 they where  24H2 before the 84 windows Patch that fixed the 8gn  aand cmd bug also messes up other windows setting's and delete removes them from the Operating system check all your'e setting's for regedit user and and local maching all the setting's that use to be i had to restore some back and Put back Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Configuration Manager

Dword32   EnablePeriodicBackup   value 1

to Hold my reg edit back ups ...

The Power Shell command to restore it has been blocked ot starts it then stops halfware through it .

When you try to run the application,
 1. Smart App Control will check to see if the app is safe. 
 2. If the security service can not identify and predict application safety, then smart app will check to see if the app has a valid signature. 
 3. Apps with valid signatures are allowed to run and apps without a valid signature are blocked. 

Where are the settings:
All the Smart App Control settings are located in App & Browser control 
 Start - Search for Smart App Control and select Smart App Control System 

You can set the value to registry key below to control Smart App Control behavior
HHKLM\SYSTEM|CurrentControlSet\Control\CI\Policy
0 - Off
1 - Enforce
2 - Evaluate

**Comment by Amrsatrio** [comment]
I don't understand if this is supposed to be a bug report or otherwise.
