### ISSUE TITLE
7+ Taskbar Tweaker

### ISSUE THREAD

**Issue by cjahn50** [valinet/ExplorerPatcher#3897]
For any of you that uses 7+ Taskbar Tweaker and have not yet updated to version 22621.4317.67.1, be aware that 7+ Taskbar Tweaker will not work. I had to go back to version 22621.3880.66.6. I've emailed Michael to let him know. If I hear back from him I'll update this thread.

**Comment by Amrsatrio** [comment]
7+ Taskbar Tweaker will no longer receive new features such as support with EP's taskbar. A price to pay if you upgrade to 24H2.

Instead, check Windhawk mods that ported its features.

https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#why-is-7-taskbar-tweaker-not-compatible-with-this

**Comment by cjahn50** [comment]
In my config I am using the Windows 10 taskbar not the Windows 10 EP implementation. Should this not be working then?  And I'm on 23H2.

**Comment by cjahn50** [comment]
Amr,

 

In my config I am using the Windows 10 taskbar not the Windows 10 EP
implementation. Should this not be working then? And I'm on 23H2.

 

I'm including Michael Maltsev <https://m417z.com/>  in this reply.

 

Best regards,

Carl Jahn

Email:  ***@***.***> ***@***.***

Cell: 214-729-4455

**Comment by pyrates999** [comment]
@cjahn50 your phone number is showing!

**Comment by pyrates999** [comment]
I don't think no one should be replying to github via email because it doesn't filter out all of your personal information

**Comment by cjahn50** [comment]
Sorry forgot Michael’s email ☹

 

From: ***@***.*** ***@***.***> 
Sent: Thursday, November 7, 2024 7:30 PM
To: 'valinet/ExplorerPatcher' ***@***.***>; 'valinet/ExplorerPatcher' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [valinet/ExplorerPatcher] 7+ Taskbar Tweaker (Issue #3897)

 

Amr,

 

In my config I am using the Windows 10 taskbar not the Windows 10 EP implementation. Should this not be working then? And I'm on 23H2.

 

I’m including Michael Maltsev <https://m417z.com/>  in this reply.

 

Best regards,

Carl Jahn

Email:  ***@***.***> ***@***.***

Cell: 214-729-4455

**Comment by pyrates999** [comment]
@cjahn50 log into github and delete your comments if you don't want your phone number exposed.
