### ISSUE TITLE
open window names on taskbar missing after latest update

### ISSUE THREAD

**Issue by Boing7678** [valinet/ExplorerPatcher#3901]
Hi, I just installed the new update and now the open windows in the taskbar have no title on the right of them anymore
![grafik](https://github.com/user-attachments/assets/38602ae5-cb65-48d9-962c-4837d860ddc8)
I can't find an option to reenable that anywhere in the settings
![grafik](https://github.com/user-attachments/assets/796c4afd-47d0-4237-91f4-6bd4ab9cbdf6)
this is what it looked like before: (Ignore the open windows, I just looked at old screenshots and cropped this out)
![grafik](https://github.com/user-attachments/assets/b50d0981-2334-486d-8761-3060d16ad65e)

**Comment by Amrsatrio** [comment]
Change it in the Settings app, specifically the Taskbar settings page, scroll down, go to Taskbar behavior section.

Please read the changelog before reporting issues.
