### ISSUE TITLE
Weather problem

### ISSUE THREAD

**Issue by Panzimy** [valinet/ExplorerPatcher#3904]
I tried weather in EP but it show some error... I will send more info after some time

**Comment by Panzimy** [comment]
I have 23H2

**Comment by pyrates999** [comment]
can you show a screen shot of the error?

**Comment by Panzimy** [comment]
https://github.com/user-attachments/assets/ac60d04b-fe0a-447f-8810-5f13d8ebd3c2


https://github.com/user-attachments/assets/859499a3-5412-485c-b441-bbfedcd53676

Here is video

**Comment by Panzimy** [comment]
Sorry after restart is OK
