### ISSUE TITLE
 To use the Windows 10 Start menu ....not visible

### ISSUE THREAD

**Issue by bluehenve** [valinet/ExplorerPatcher#3905]
Hi

I just reinstalled ExplorerPatcher.
I dont see the option, mentioned in README part 5: 
"To use the Windows 10 Start menu, go to the "Start menu" section and change the Start menu style to Windows 10."
?

Regards, Henrik

**Comment by pyrates999** [comment]
did you open up `Properties (ExplorerPatcher)`?

**Comment by bluehenve** [comment]
[cid:4fc07c9e-88f2-4e26-b569-dc876339cc5c]



Med venlig hilsen

Henrik Vestergaard
Power BI udvikler
***@***.*** ***@***.***>  | +45 50 15 52 99
henrikBLUEvestergaard | www.henrikv.dk<http://henrikv.dk/>  |  CVR 42753262



________________________________

**Comment by pyrates999** [comment]
@bluehenve don't respond via email because now it is showing your phone number.

**Comment by pyrates999** [comment]
@bluehenve you need to also edit your previous comment that you replied via email

**Comment by bluehenve** [comment]
Yes I opened Properties and under menu item 'Start menu', the first option is 
'More Start menu options in the Settings app', not 
"To use the Windows 10 Start menu, go to the "Start menu" section and change the Start menu style to Windows 10."

**Comment by pyrates999** [comment]
can you show a screen shot?

**Comment by bluehenve** [comment]
Sure
![Clipboard](https://github.com/user-attachments/assets/0afb3bad-7403-4890-9184-334eaa5cabc4)

**Comment by pyrates999** [comment]
you need to install the latest release, which is 22621.4317.67.1: https://github.com/valinet/ExplorerPatcher/releases

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender.

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.

**Comment by bluehenve** [comment]
Great, I'll do it.
I've installede EP with winget:
   winget install  valinet.ExplorerPatcher -e --silent
That might not get the latest relase?

**Comment by pyrates999** [comment]
probably not.

**Comment by bluehenve** [comment]
Great, worked. Sooo nice to have jumplists back when Rclik on an app in the taskbar 💪
