### ISSUE TITLE
unpin from start not working

### ISSUE THREAD

**Issue by PoepieFloepie** [valinet/ExplorerPatcher#3906]
unpin to start dont work anymore

if i select a icon pinned to start ,and i right click the icon ,it is saying pin to start and not unpin to start

pin to start also dont work anymore

this happens only in wondows 10 start menu mode

i have windows 11 24H2 version 26120.2222

**Comment by pyrates999** [comment]
can you post your EP version that you have installed?

**Comment by PoepieFloepie** [comment]
the latest version ,i tryed older version wich work with 24H2 but still the same

i always install the latest version

**Comment by pyrates999** [comment]
answering with latest version doesn't answer the question.

**Comment by PoepieFloepie** [comment]
what i see now is folders i can unpin,but icons i cant unpin or pin to start
now i have stuck microsoft icons that i can not remove or unpin

**Comment by PoepieFloepie** [comment]
![Schermafbeelding 2024-11-09 164017](https://github.com/user-attachments/assets/02be0a42-76bc-4a5c-b06a-b69880c33ae2)

in english it say pin to start

windows 11 24H2 version 26120.2222
explorerpatcher version 22621.4317.67.1 tryed to revert to older version still the same
windows 10 start menu

**Comment by pyrates999** [comment]
you're running an insider build: https://blogs.windows.com/windows-insider/2024/11/08/announcing-windows-11-insider-preview-build-26120-2222-dev-channel/

please wait for a developer to respond.

**Comment by PoepieFloepie** [comment]
so how can i completely reset explorer patcher with all icon removed and default settings

i tryed default settings but the icons stay

**Comment by PoepieFloepie** [comment]
oke i downgrade to windows 11 24H2 version 26120.2200 and it working again ,i can unpin again

**Comment by milesprower2293** [comment]
@PoepieFloepie A fix for this was made and it will be available for the next prerelease
