### ISSUE TITLE
Files history is not shown when taskbar icon clicked.

### ISSUE THREAD

**Issue by ymt-2520** [valinet/ExplorerPatcher#3909]
when right click, opened files history is not shown.
does anyone know how to solve this.
regards you...

![{7A7965F3-DCC6-4304-813F-BF0526FAD2DA}](https://github.com/user-attachments/assets/10e6a79d-4afe-43b1-835e-91f729e9434a)

**Comment by pyrates999** [comment]
do you mean there is no file history shown in the jump lists?

Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

**Comment by ymt-2520** [comment]
Oh, sorry.
current version is
windows: 23H2 22631.4317 (x64 Intel 12th Processor)
explorer patcher: 22621.4317.67.1
Setting language is Japanese.

but this problem has occured since 6 months ago (when I installed this program first time).

![image](https://github.com/user-attachments/assets/65da246d-4dc6-471e-92d9-0e24cca1accf)
![{2044BD9C-7925-4021-A51F-E65A7ED0FC2C}](https://github.com/user-attachments/assets/6ec46536-8a12-426d-b104-14162682c328)

**Comment by pyrates999** [comment]
what if you uninstall EP?  Does the history in jump lists return?

**Comment by Amrsatrio** [comment]
![image](https://github.com/user-attachments/assets/c86b1e16-67e8-41a9-8b56-a983bf90fbb6)

Please screenshot this page of the Settings app. I need to make sure that you have this setting enabled.
この設定がオンになっていることを確認するため、設定アプリのこのページのスクリーンショットを撮影してください。

**Comment by ymt-2520** [comment]
@ pyrates999
I tried "uninstall -> reboot ->reinsatall". but it's not worked yet.

@ Amrsatrio
![settings](https://github.com/user-attachments/assets/b900b851-bb7a-4f88-b5ab-dcfc9b534f94)
it's already turned on..., but one content is grayed-out (this maybe not related to the problem).
オンになっていますが、表示されないままです。
ただ、多分関係ないとは思いますが、「よく使うアプリを表示する」がグレーアウトしてはいます。

**Comment by ymt-2520** [comment]
I don't know the reason, but this problem is fixed. Thanks to your cooprates.
理由はわかりませんが、いつの間にか解決したようです。協力ありがとうございました。
