### ISSUE TITLE
Taskbar position on right or left of screen is broken

### ISSUE THREAD

**Issue by glenviewjeff** [valinet/ExplorerPatcher#3912]
I keep my taskbar on the right. Worked great until today; I presume a Windows 11 update broke it. Tried uninstalling and reinstalling EP. No longer shows active applications in the taskbar, no window titles in taskbar, start button doesn't work (when taskbar is on left side, including windows button on keyboard. Windows button is fine for right side taskbar for some reason). Top and bottom screen locations work fine. When I switch active application, the highlighted application in the taskbar does change to the active one, but no indication of what applications are concurrently open.

Screenshot shows what it looks like despite multiple applications open in addition to chrome.

![image](https://github.com/user-attachments/assets/6b2aa4ab-1008-4c3f-b1aa-81a3a48e29bc)

**Comment by pyrates999** [comment]
do you have classic theme enabled?

in EP Properties application, go to advanced

disable: Enable advanced mitigations for correct rendering using classic theme

click on Restart File Explorer in bottom left corner.

**Comment by glenviewjeff** [comment]
Thanks so much for the response; this was already disabled. I don't know what you mean by "classic theme" and don't see any explanation in the docs. Are you referring to a Windows theme? I'm using Windows 11 with the Windows 10 taskbar style and Windows 10 start menu style in EP. I happen to be using a "custom theme" in Windows 11, though I suspect it's just saying that because I chose my wallpaper. 

![image](https://github.com/user-attachments/assets/c52fa027-b9e8-4edc-84c6-67be7e32cd38)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

**Comment by pyrates999** [comment]
If you mean the taskbar is too wide, right click on it and untick `Lock the taskbar`.  Then resize it using your mouse.  Then right click on it and tick `Lock the taskbar`.

**Comment by glenviewjeff** [comment]
x86 Windows version below. To be clear, I've been using this application successfully for years without changing the arrangement. The taskbar is that width because the taskbar normally displays the title of each active window. Besides this being broken, there are many more running applications besides Chrome at the time of the original post screenshot. Part of the taskbar failure is that it appears as if Chrome is the only running application. When the taskbar is moved to the bottom of the screen, all appears normal. 

I should also add that my PC crashed with BSOD for the first time in a very long time, and I am pretty sure this only arose possibly immediately after the BSOD. 

![image](https://github.com/user-attachments/assets/0e8f441c-30a4-4e3c-b177-2fa3440ae9fe)

**Comment by Amrsatrio** [comment]
In 67.1, EP now uses the same registry value for the Combine taskbar items option. Please check the relevant setting in the EP Properties window or Settings app > Taskbar behaviors.

Regarding the Start menu not showing on the left side, I cannot reproduce this isue using the 10 Start menu. Are you using the 10 one or the 11 one?

**Comment by glenviewjeff** [comment]
Windows 11 style doesn't allow taskbar on the left/right, only Windows 10 style. I never keep it on the left, only on the right, so I'm not concerned about the start menu problem; you can ignore it other than an FYI. The combining items is only one symptom; another key defect is that all but the currently focused window's app incorrectly show as if they are not running in the taskbar when the taskbar is on the right (or left.)

**Comment by Amrsatrio** [comment]
> In 67.1, EP now uses the same registry value for the Combine taskbar items option. Please check the relevant setting in the EP Properties window or Settings app > Taskbar behaviors.

Please do me a favor by doing this.

> Windows 11 style doesn't allow taskbar on the left/right, only Windows 10 style.

I did not refer to the taskbar. I referred to the start menu.

**Comment by Amrsatrio** [comment]
It is normal. Combined taskbar buttons on right taskbar do look like that.

**Comment by glenviewjeff** [comment]
> It is normal. Combined taskbar buttons on right taskbar do look like that.

I certainly may be wrong, but I swear in the past I would still see titles for applications that were open but not combined when only one window was open for an application. Screenshot below demonstrates this. Google Keep is not open, but docs has two windows active. 

![image](https://github.com/user-attachments/assets/317d471c-746c-47a2-9664-36772134f19a)

**Comment by Amrsatrio** [comment]
Please post a full uncropped screenshot to better explain what you mean. I suspect that since your screenshot is cropped the colored bar is left out in the cropping.

**Comment by Amrsatrio** [comment]
The little blue indicator on the right is the indicator that shows if the button has windows open. Here, a screenshot from a fresh Windows 10 VM.

![image](https://github.com/user-attachments/assets/68975bee-61ab-43cf-baac-9a42223e2648)

> Only the active window is highlighted

Yes, that's the way it is in Windows 10, unlike in Windows 7 and 8. On 7 and 8 it looked like this:

![image](https://github.com/user-attachments/assets/e0b42d79-a4d2-42e5-9a3f-9b8723534def)

**Comment by glenviewjeff** [comment]
Thank you for all of your patient guidance. I have no idea how or why the taskbar settings must have changed to "always combine," seemingly on their own, perhaps with a stray mouse click, what I had attributed to an ExplorerPatcher update. It was clearly a false memory of mine about the Windows 7/8 taskbar's style showing running tasks via highlighting as you showed in the previous post. Apparently running tasks are only indicated by the title text and the accompanying blue bar, or only the blue bar if you're always combining windows.

**Funny story:** the light-blue bars indicating open apps is virtually invisible on my 40" monitor due to poor viewing angles. I was aware of them on the lower taskbar, but couldn't see them on the right-hand taskbar. 

> The little blue indicator on the right is the indicator that shows if the button has windows open. Here, a screenshot from a fresh Windows 10 VM.
> 
> ![image](https://private-user-images.githubusercontent.com/20662640/384999690-68975bee-61ab-43cf-baac-9a42223e2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTMzMTMsIm5iZiI6MTczMTg1MzAxMywicGF0aCI6Ii8yMDY2MjY0MC8zODQ5OTk2OTAtNjg5NzViZWUtNjFhYi00M2NmLWJhYWMtOWE0MjIyM2UyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDE0MTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NmY1MmZmM2M5ZjdkNDQ3NjcwZGM1ODdjY2MxMWQ2NTBiMzk0ZmI3MTNiMWNiZTJjZjA5MTUzZTkzMTBmMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KFJI3hXwIxN7zEYWP0vGPmzjjhykYkoPbSYd-AI_yNQ)
> 
> > Only the active window is highlighted
> 
> Yes, that's the way it is in Windows 10, unlike in Windows 7 and 8. On 7 and 8 it looked like this:
> 
> ![image](https://private-user-images.githubusercontent.com/20662640/385000061-e0b42d79-a4d2-42e5-9a3f-9b8723534def.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTMzMTMsIm5iZiI6MTczMTg1MzAxMywicGF0aCI6Ii8yMDY2MjY0MC8zODUwMDAwNjEtZTBiNDJkNzktYTRkMi00MmU1LTlhM2YtOWI4NzIzNTM0ZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDE0MTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MTZhNjIzZjgyNjIzOGM5NjBhZGEzZjE2MWRmMzM4ODdjZWVmMjI3ZGQzMWU4OWE0YTQzMGVhMDVjZjFlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s7Xh567Mb2KXfChBnnYE_y3O6P8o6aAIEVx0EOJXN2U)

**Comment by pyrates999** [comment]
check this for how to uncombine taskbar icons and show text: https://www.xda-developers.com/how-enable-taskbar-ungrouping-labels-windows-11/

**Comment by glenviewjeff** [comment]
Thanks, I was able to get it back to its previous configuration a few days
ago when I posted the update here.

**Comment by raminmat** [comment]
For anyone landing here from search: the 'apps not showing on left/right taskbar' symptom has a root-cause analysis and a working workaround (alignment setting + free auto-recovery tool) posted in #3920: https://github.com/valinet/ExplorerPatcher/issues/3920#issuecomment-4942509567
