### ISSUE TITLE
What a nigtmare

### ISSUE THREAD

**Issue by philhop1** [valinet/ExplorerPatcher#3913]
Was causing a Black screen after login, finally found out this program was to blame and removed it 23H2 

Almost did a full reinstall

**Comment by pyrates999** [comment]
this explains what you need to do when you get a black screen after login: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#help-my-screen-is-black

Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

**Comment by Amrsatrio** [comment]
Hi, really sorry that happened. If you don't mind, can you send the latest crash dump for explorer.exe in `%LOCALAPPDATA%\CrashDumps`? If it is indeed the latest version of ExplorerPatcher (67.1) it would really help in preventing similar crashes like this on other users in the future.

**Comment by Amrsatrio** [comment]
Closed due to no response.
