### ISSUE TITLE
The Windows 10 action bar is not available in this version of Windows.

### ISSUE THREAD

**Issue by Luxryu** [valinet/ExplorerPatcher#3915]
The Windows 10 action bar is not available in this version of Windows.
Please help me
![error](https://github.com/user-attachments/assets/67fd8681-f202-4230-b7f5-c845a8e16c05)

**Comment by pyrates999** [comment]
see this discussion: https://github.com/valinet/ExplorerPatcher/discussions/3903#discussioncomment-11209205

**Comment by Luxryu** [comment]
@pyrates999 해결 방법이 없습니까?

**Comment by pyrates999** [comment]
I linked you to the solution, but according to the link I posted, action center will never be added as an option to EP, because of the reasons stated.

**Comment by Amrsatrio** [comment]
Click the Windows 10 text. Select Windows 10 (ExplorerPatcher). I agree the the user interface is bad and is due for a revamp.
