### ISSUE TITLE
Context menu not fully show when using vertical taskbar

### ISSUE THREAD

**Issue by dekconcat** [valinet/ExplorerPatcher#3916]
![image](https://github.com/user-attachments/assets/12c282cd-abb6-45a8-8efc-a56f4eabf721)

**Comment by pyrates999** [comment]
that is very weird.

Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

**Comment by dekconcat** [comment]
sry, i forgot update ExplorerPatcher.
after update everything work perfectly
