### ISSUE TITLE
Taskbar icon bug when switching desktops

### ISSUE THREAD

**Issue by Bardwen** [valinet/ExplorerPatcher#3917]
Anyone else having this issue?  It doesn't always happen.  Not sure exactly what causes it.  See pic for details -- notice how the terminal icon is bugged.  I've tried disabling animations in windows settings.

![Screenshot 2024-11-13 000716](https://github.com/user-attachments/assets/eb30a016-5c9a-40b4-892c-09c183cdaa7b)

**Comment by pyrates999** [comment]
please elaborate as I don't see what is wrong in the picture.

**Comment by Amrsatrio** [comment]
This is because the taskbar centering is more of a "hack". I keep experiencing this as well. As a workaround reorder an icon and it should be rearranged properly.
