### ISSUE TITLE
Right clicking on Start doesn't bring out the right click menu

### ISSUE THREAD

**Issue by pierremont** [valinet/ExplorerPatcher#3922]
Hello!

When you right click on the Windows 11 Start button there should be a long Windows menu (with the Run action, among others).
There was a recent Windows update, and perhaps it collided with the Explorer app.

Thank you.

**Comment by pyrates999** [comment]
If you are referring to the windows preview update that was released near the end of october, that was fixed with the latest release of EP version: 22621.4317.67.1

https://github.com/valinet/ExplorerPatcher/releases

This was fixed with that.  Please check if you have not installed it yet.

**Comment by pierremont** [comment]
My system updated a few days ago.
It's like you said, though. I checked for an update from inside the application, it updated and the start menu is working fine now.

Thank you!

**Comment by pyrates999** [comment]
Please close this then.

**Comment by pierremont** [comment]
Solved in an already released update. Closing issue.
