### ISSUE TITLE
taskbar on incorrect monitor 

### ISSUE THREAD

**Issue by nvmenerd** [valinet/ExplorerPatcher#3926]
Hello! I recently had a windows system update (to 11 Pro 23H2 22631.4460) and the primary taskbar with all my icons is appearing on the wrong monitor. In windows dispaly settings, the main monitor is correct. When uninstalling EP, the primary taskbar is in the correct monitor. Even with EP installed and running the Win11 taskbar it is correct. However, switching to 10 or EP's custom 10 puts it in the wrong monitor. It seems like everything else is fine and EP just doesn't put the primary taskbar in the right spot. Could be because of the update.

Any help is appreciated!

**Comment by Amrsatrio** [comment]
Unlock the taskbar and drag it to your preferred monitor I guess?

**Comment by nvmenerd** [comment]
....bruh. that worked lol. thanks.
