### ISSUE TITLE
German translation wrong

### ISSUE THREAD

**Issue by Gaminguide1000** [valinet/ExplorerPatcher#3927]
![grafik](https://github.com/user-attachments/assets/27d4ccfe-f8e6-4014-bca0-a9f7ad951b18)
![grafik](https://github.com/user-attachments/assets/1284053f-dd0e-4ea3-b628-fcc5c1e2c095)

First screenshot:
its supposed to say "Akkustatus: 1 Std 30 min (14%) Verbleibend 
Stromsparmodus aktiviert"
Also you could use "übrig" instead of verbleibend
Second screenshot:
its supposed to say "Lautsprecher" instead of "Speakers"

**Comment by Amrsatrio** [comment]
These are not part of EP. They're part of official Windows binaries. For the Speakers you can rename your Speakers device to be Lautsprecher through the legacy Sound control panel applet accessible via sndvol.exe, clicking the icon for system sounds, and then going to playback, double clicking your desired playback device, and then renaming it.
