### ISSUE TITLE
Explorer keeps pinning random folders?

### ISSUE THREAD

**Issue by akanestar** [valinet/ExplorerPatcher#3929]
I'm not sure if this makes sense, but for some reason, explorer keeps pinning folders that I have not manually pinned.
I attached some screenshots. Had to blur things out for work reasons.

![Screenshot 2024-11-15 151537](https://github.com/user-attachments/assets/5ee84ce5-aef1-4c8a-b102-7c92417ff334)

![Screenshot 2024-11-15 150401](https://github.com/user-attachments/assets/a2826ff8-c37b-4be9-886f-697cf1b9bc41)

**Comment by pyrates999** [comment]
https://support.microsoft.com/en-us/windows/pin-remove-and-customize-in-quick-access-7344ff13-bdf4-9f40-7f76-0b1092d2495b

You probably have `Show frequently used folders in Quick Access` ticked in file explorer Folder Options.

**Comment by Amrsatrio** [comment]
Not an EP issue. It has always been like this since the early days of Windows 10.
