### ISSUE TITLE
Partial incompatibility with TransluscentTb.

### ISSUE THREAD

**Issue by GrigolattoFacundo** [valinet/ExplorerPatcher#3930]
TransluscentTb is a software that makes exactly that, the taskbar is clear like if it was hidden but it is not.

With Explorer patcher, while using any taskbar besides windows 11 (default), taskbar icons on the secondary display (I only have 2) don't show unless I click the start button on that display. icons also permanently show if I turn off any of the 2 softwares.

I used transluscentTb back in windows 10 and I had no problem so I think it might be an explorer patcher issue

![imagen](https://github.com/user-attachments/assets/9b541b19-d25c-43c4-945d-8abb4ad40a94)
![imagen](https://github.com/user-attachments/assets/56a7d502-b9eb-48cb-85f9-f38bdc520d7a)

Windows 11 Pro build 22631.4460
ExplorerPatcher Version 22621.4317.67.1
TransluscentTb 2024.1

**Comment by pyrates999** [comment]
check if you have EP updated with this release: https://github.com/valinet/ExplorerPatcher/releases

there was a windows update that caused the taskbar to be transparent with a previous release of EP.

**Comment by GrigolattoFacundo** [comment]
> check if you have EP updated with this release: https://github.com/valinet/ExplorerPatcher/releases
> 
> there was a windows update that caused the taskbar to be transparent with a previous release of EP.

Yes I have exactly that release, my OS build is not in the tested builds tho

**Comment by Panzimy** [comment]
Because there can be some incompatibility it's looking like that EP can't do anything with start menu because was already edited

**Comment by Panzimy** [comment]
I tested it and there are some bugs but that is because EP is changing code and TB also and because there are some  incompitabilities it get that what you say

**Comment by Panzimy** [comment]
But something in my case is OK

**Comment by Panzimy** [comment]
Like this
![image](https://github.com/user-attachments/assets/bc1cc1e9-3674-44c6-b8bc-3bc15f727224)

**Comment by Panzimy** [comment]
And please try to change some settings what can do this

**Comment by pyrates999** [comment]
Please post your EP version.

**Comment by Panzimy** [comment]
@pyrates999 EP is newest to this day

**Comment by Amrsatrio** [comment]
Bug with TTB not EP. I cooperated with the maker one day to fix this issue, haven't tried again now since I rarely use multi monitors.
