### ISSUE TITLE
"Windows Powershell (Admin)" runs powershell as non-admin

### ISSUE THREAD

**Issue by rbcam** [valinet/ExplorerPatcher#3936]
When I right-click on the Start menu icon and choose "Windows Powershell (Admin)", a terminal window running powershell opens, but it does not have administrator privileges. For example, running "powercfg /requests" produces the error "This command requires administrator privileges and must be executed from an elevated command prompt."

Windows 11 Pro 23H2, build 22631.4460
EP 22621.4317.67.1

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2156
