### ISSUE TITLE
Symbols download might be the cause of both Blue Screen of Death crashes

### ISSUE THREAD

**Issue by GregariousJB** [valinet/ExplorerPatcher#3939]
My first bluescreen failed at bluescreening and I don't have an error log for it, but I noticed a notification that Explorer Patcher had downloaded new symbols and didn't think much of it.

Second BSD has an error log that came with it, along with the exact same notification that symbols were downloaded for EP. This time I'm ready.

![bsd](https://i.imgur.com/Cc71zH8.png)

[bsd.txt](https://github.com/user-attachments/files/17789031/bsd.txt)

The BSD is tagged as `UNEXPECTED_STORE_EXCEPTION`, which suggests using the Windows Memory Diagnostics program to check for errors. I did this with 0 results/errors found. I also did `SFC /scannow` with no results, either.

OS: Win 11 LTSC 24H2 (fresh reformat last month)
Settings: Only "Disable Win 11 context menu" enabled after install

**Comment by pyrates999** [comment]
can you upload the `111624-9359-01.dmp` file that the bsd.txt file references?  Here's some help with reading it and finding it: https://www.windowsdigitals.com/windows-11-dump-file-location/

**Comment by GregariousJB** [comment]
[ExplorerPatcherCrash.dmp](https://github.com/user-attachments/files/17791682/ExplorerPatcherCrash.dmp)

**Comment by pyrates999** [comment]
can you post your EP version?  Just in case you installed an older version.

**Comment by GregariousJB** [comment]
![v](https://i.imgur.com/wDamopU.png)

**Comment by pyrates999** [comment]
Ok, in EP Properties application can you untick `Disable Win 11 context menu` and see if the crash still occurs in regedit.exe?

**Comment by GregariousJB** [comment]
> see if the crash still occurs in regedit.exe?

Not sure what this means. I know how to open regedit but where would the crash appear there? Also, the crash (seemingly) only occurs when symbols are downloaded.

**Comment by pyrates999** [comment]
so it doesn't occur now?

**Comment by GregariousJB** [comment]
I'm confused. The details are in my first post.

After each BSD I noticed a notification that symbols had updated, but it might be a coincidence. Maybe they just happened to update when my PC came back online and the notification was after the reboot, not before. Not sure. I only know these two crashes are connected very closely to two symbols updates, so I came here just in case.

**Comment by Amrsatrio** [comment]
I don't know what to say but, since me and the active people in the EP Discord server have been happily using this software without very frequent BSODs, it seems like this issue is related to your hardware. Maybe you experience BSODs during load. So, with that said, I can't do much to fix this issue. A user mode program that can bug check/BSOD is definitely a bug in Windows or your hardware.

**Comment by GregariousJB** [comment]
That's fine. That's still helpful - knowing this isn't happening to anyone else. It means EP is unlikely the cause. Thank you anyway.

**Comment by pyrates999** [comment]
The only reason for EP to download new windows symbols is if a windows update is installed, and a reboot occurs after.

Is this what happens?

1. install windows update
2. windows update says to reboot, so you reboot
3. you finish rebooting
4. bsod crash occurs and system needs to boot back up
5. then you get notification that symbols are being downloaded
6. then you get another notification that symbols have been downloaded

Is that what happens?

**Comment by pyrates999** [comment]
nevermind.

**Comment by GregariousJB** [comment]
That's an interesting point. I do recall a BSOD happening, then Windows was acting like an update happened before I hit the login screen. Maybe Windows Update is the cause and EP got caught in the crossfire because of the notifications.

**Comment by pyrates999** [comment]
here's how to view bsod logs in windows: https://www.makeuseof.com/windows-bsod-log-file-location/
