### ISSUE TITLE
Control Panel Redirection prevention does not work on Windows 10 21H2

### ISSUE THREAD

**Issue by happymimimix** [valinet/ExplorerPatcher#3941]
The "prevent the following control panel links from being redirected to the settings app" does not work on Windows 10 21H2! 
![image](https://github.com/user-attachments/assets/a8ba4e7a-ccec-49ce-ba77-cf7455e9cf65)

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2346

please close this.

**Comment by happymimimix** [comment]
> duplicate of: #2346
> 
> please close this.

So when will you fix this?

**Comment by Amrsatrio** [comment]
Duplicate of #2346
