### ISSUE TITLE
windows Start menu button not working after security update

### ISSUE THREAD

**Issue by JeffHox** [valinet/ExplorerPatcher#3942]
Every time windows 11 installs the Kb5046633 security update left clicking the mouse on the window start menu  con does not open the menu.  The right click still works though.  The only way to get it working again it to keep uninstalling the update. this has been going on since the update first came out.   thanks

**Comment by milesprower2293** [comment]
try reinstalling ExplorerPatcher

**Comment by pyrates999** [comment]
If you meant right clicking on the start menu doesn't work, that's been fixed with the newest release of EP.  Please uninstall the current version and install the newest release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment]
You must be doing something wrong if the start menu does not work *even after a full reinstall*. Make sure you're running EP 67.1. Make sure exclusions have been properly configured.

**Comment by JeffHox** [comment]
yes i am running EP 67.1 and have tried resetting everything to default
setting and have prompted windows antivirus not to interfere.  I
believe i've done everything correctly.  I will try
reinstalling with antivirus deactivated and see if that helps.

**Comment by pyrates999** [comment]
Before installing EP, if you're not using a third party antivirus, right click on powershell and select run as administrator.  Then run the following to exclude these from windows defender:

```
Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy"
```

if you get the error: 0x800106ba, it means Windows Defender is not active, and you do have another antivirus installed that is currently running.  If so, you'll need to add the above exclusions to it, which should be:

```
"C:\Program Files\ExplorerPatcher"
"%APPDATA%\ExplorerPatcher"
"C:\Windows\dxgi.dll"
"C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
"C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy"
```

**Comment by JeffHox** [comment]
Thanks for the reply.  Oddly enough after months of it happening when
Windows updated  after uninstaling and reinstalling explorerpatch and then
uninstall the update and then Resintalling it as well the problem fixed
itself without needing anymore intervention.  Go figure.    I really
appreciate your assistance in attempting to resolve this issue. If it
happends again i will run your exclude.  I had run a similar exlcude
previously before i uninstalled and reinstalled the security update so
maybe that was what did it.     Anyhow, thanks again

**Comment by pyrates999** [comment]
I suspect that windows defender was interfering in this.  So some files were being quarantined that EP needs to function.

**Comment by Amrsatrio** [comment]
Glad to see that you got your problem resolved. Remember, the Windows 10 start menu is now no longer part of Windows 11 22H2/23H2 so it can break anytime.
