### ISSUE TITLE
7T Taskebar Tweaker

### ISSUE THREAD

**Issue by cjahn50** [valinet/ExplorerPatcher#3943]
I am running Windows 11 23H2. The lastest update - 22621.4317.67.1 prevents 7T Taskbar Tweaker from working. It worked as expected up until this update. I went back to EP 22621.3880.66.6 and 7tt works as it should. I am not running 24H2.

**Comment by milesprower2293** [comment]
7+ Taskbar Tweaker will no longer receive new features such as support with EP's taskbar. A price to pay if you upgrade to 24H2 or use EP's taskbar.

Instead, check Windhawk mods that ported its features.

https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#why-is-7-taskbar-tweaker-not-compatible-with-this
