### ISSUE TITLE
Right click on task bar not showing expected settings can't unlock taskbar

### ISSUE THREAD

**Issue by AJolly** [valinet/ExplorerPatcher#3944]
Recently right clicking on the taskbar gives a completely different menu than I'm expecting. this means I can no longer find the option to Unlock the taskbar in order to resize it.

This seems to persist even in safe mode, and also with a brand new user profile.  
Win 11
Version 23H2
OS Build 22631.3447
Windows Feature Experience Pack 1000.22688.1000.0
Explorer Patcher 22621.4317.67.1

If there's a way to even just work around it and always unlock the taskbar/set it to double height, that'd be great.  
It's only happening on one of my 3 pcs, but the other two are running slightly different build/pack numbers?

![image](https://github.com/user-attachments/assets/d3b5b3d9-4403-4829-a81f-bc492deb533c)
![image](https://github.com/user-attachments/assets/eef22035-4999-4f6a-9fcc-9f7275dbda8c)
![image](https://github.com/user-attachments/assets/f277ad15-f7a5-4cb3-aa7c-4446be43a2ac)
![Screenshot 2024-11-18 180159](https://github.com/user-attachments/assets/9af07aca-0bdd-40bb-a0f8-107a697b7958)

**Comment by milesprower2293** [comment]
Uninstall nilesoft shell and the lock taskbar option should be available
Also this is not an ExplorerPatcher related issue

**Comment by AJolly** [comment]
@milesprower2293 Thank you so much!
