### ISSUE TITLE
Unable to completely uninstall Explorer Patcher 

### ISSUE THREAD

**Issue by crimle** [valinet/ExplorerPatcher#3946]
I uninstalled Explorer Patcher using Windows Control Panel > Apps > Uninstall. For the moment, this seemed to be successful. But from that moment I am getting a black screen from time to time. After manually restarting explorer.exe several times, an error message is being displayed, telling me that explorer patcher has crashed 3 times. Obviously, there still are some files or maybe services running somewhere in the background. 

May I ask for hint how and where to find these files in order to get rid of them?
Thank you and kind regards
Chris

**Comment by Amrsatrio** [comment]
Install latest EP and uninstall it again. Use the uninstall button in the Properties window. Make sure these are deleted: C:\Windows\dxgi.dll, %APPDATA%\ExplorerPatcher, HKCU\Software\ExplorerPatcher.
