### ISSUE TITLE
Search box at bottom, taskbar pinnned to top

### ISSUE THREAD

**Issue by SteadyStatus21** [valinet/ExplorerPatcher#3948]
I really can't explain this too well, but I have not found any options to move the Windows Search from the bottom of the screen to the top of the screen. **Is this possible?** 

This GIF shows what I am talking about:
![Animation](https://github.com/user-attachments/assets/4ecbeb38-8bf7-4757-9100-d53d2a208fc6)

**Comment by milesprower2293** [comment]
The Windows 11 search menu was never designed to be on the top. so for now it is a no
