### ISSUE TITLE
Cannot Update Software

### ISSUE THREAD

**Issue by msimon2310** [valinet/ExplorerPatcher#3952]
Hello,

I am a relatively new user. I am not vety computer saavy !!!

I have been trying to update my EP for several months now and due to a known Windows Security Issue with EP I have been unable to do so. I have tried my best to follow the instructions provided to update Defender with the Exclusions but I still cannot get past the Security Error indicating that Windows does not like EP......

Any help here would be appreciated.

I can be reached at msimon2310@comcast.net 

Thx,

**Comment by Amrsatrio** [comment]
Please uninstall EP. I mean for real. Due to stuff MS has been doing EP is no longer for the average users.
