### ISSUE TITLE
Advice please Microsoft bans updates to windows 11 if ExplorerPatcher is installed

### ISSUE THREAD

**Issue by robtgmann** [valinet/ExplorerPatcher#3954]
Today, Nov 21,2024I was denied ability to download the latest update to Windows 11 Pro,  Version 10.022631 Build 22631

I am running EP Version 2261.4317.67.1

Here's the notification
![Screenshot 2024-11-21 150407](https://github.com/user-attachments/assets/dd13607d-55ef-408c-91e4-3339af368da0)

I'm prepared to give up microsoft upgrades to maintain EP, but maybe you have another suggestion.

**Comment by pyrates999** [comment]
You're attempting an upgrade to windows 11 24h2.  Please uninstall EP.  Then do the upgrade.  Then install the latest release of EP from here: https://github.com/valinet/ExplorerPatcher/releases
