### ISSUE TITLE
Windows 10 start button logo missing

### ISSUE THREAD

**Issue by Penguinwt** [valinet/ExplorerPatcher#3957]
![where](https://github.com/user-attachments/assets/32cffc6a-3051-4262-bd4f-da163ae3547a)

i just change the taskbar style to the windows 10 taskbar and the start button logo just missing. wtf

**Comment by milesprower2293** [comment]
Are you using a custom theme?

**Comment by Amrsatrio** [comment]
@Penguinwt We need more info. Are you using a custom theme? Do you have other mods? Is the button clickable? What is your Windows build?

**Comment by Penguinwt** [comment]
> @Penguinwt Are you using a custom theme?

Nope.

**Comment by Penguinwt** [comment]
> @Penguinwt We need more info. Are you using a custom theme? Do you have other mods? Is the button clickable? What is your Windows build?

i have no other custom theme, the windows build is 226221, button are clickable..

**Comment by pyrates999** [comment]
please post the windows build number.  You can find out by running winver.  Please also post the EP version.

**Comment by sandwichzei** [comment]
> @Penguinwt We need more info. Are you using a custom theme? Do you have other mods? Is the button clickable? What is your Windows build?

can't tell about op's versions, but i have the same problem as them too (it's definitely 24h2's fault but oh well), here are my versions
![Screenshot 2024-11-24 205429](https://github.com/user-attachments/assets/85eeafa6-7f5b-4a9f-82ad-38a708e196f0)

**Comment by Amrsatrio** [comment]
Use Windows 11 start button style.
