### ISSUE TITLE
explorer patcher can't be uninstalled or updated, breaking windows desktop

### ISSUE THREAD

**Issue by WhiteEnderman12** [valinet/ExplorerPatcher#3959]
Hello!
I first installed Explorer patcher half a year ago, 
when I got bored of it I wanted to uninstall it but I couldn't because it just kept saying what is shown in the image below:
![ap](https://github.com/user-attachments/assets/bbccd576-0c9c-40e1-999d-37efd75a4f01)

I tried all the steps it didn't help. back then I thought "oh well, doesn't take up that much storage space anyways. " Now after some recent updates explorer.exe won't launch until I go into regedit and delete HKCU\Software\explorerpatcher. I have to do this everytime explorer starts (every time I log in or it crashes). I also tried updating it to a newer version but I get the exact same error.

No I'm wondering, can I maybe use one of those uninstaller programms that you can find online (like IObit Uninstaller) to forcefully remove Explorerpatcher or will this brick the system?

any help is appreciated.

**Comment by Amrsatrio** [comment]
Follow the steps in here: https://github.com/valinet/ExplorerPatcher/issues/3955#issuecomment-2492975622

**Comment by WhiteEnderman12** [comment]
thanks  it actually worked
