### ISSUE TITLE
search box broken in 23h2

### ISSUE THREAD

**Issue by apixhed** [valinet/ExplorerPatcher#3961]
![Screenshot 2024-11-23 172801](https://github.com/user-attachments/assets/b078e7ac-b23f-4bb3-b6ec-7e2e9c3a1358)
weird.

**Comment by pyrates999** [comment]
Please explain with more details.  How is search broken?

**Comment by apixhed** [comment]
its just sometimes vanish and sometimes there

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.
