### ISSUE TITLE
Multiple incidents: battery, windows explorer menu bar, error messages

### ISSUE THREAD

**Issue by none3** [valinet/ExplorerPatcher#3962]
1. Battery button at bottom taskbar not responding as in previous versions like 23h2, in previous versions, the small menu should show up to change power plan.
2. Windows explorer Menu bar like File, Edit, View, Tools not working as of 24h2
3. Error messages in console
shell\explorer\taskband2\TaskBand.cpp(7309)\ep_taskbar.5.dll!00007FFB3CD55D1D: (caller: 00007FFB3CD5075E) ReturnHr(1) tid(25c0) 80073B1F ResourceMap Not Found.
shell\explorer\taskband2\TaskBand.cpp(5323)\ep_taskbar.5.dll!00007FFB3CD5077A: (caller: 00007FFB3CD48C51) LogHr(2) tid(25c0) 80073B1F ResourceMap Not Found.
(is it normal)

My build, versions, settings
EP: 22621. 4317.67.1
OS: 26100.2314 (24h2)
Taskbar style: Windows 10 (ExplorerPatcher)

![image](https://github.com/user-attachments/assets/d7497a35-ccc8-48ed-acf0-22b30790d977)

**Comment by pyrates999** [comment]
Please show what settings you changed in EP Properties application.

**Comment by none3** [comment]
![image](https://github.com/user-attachments/assets/2f51ce8b-f588-4ef0-ab01-3b27f5bcadb2)
![image](https://github.com/user-attachments/assets/453def4f-ed1d-4f74-add0-4c9bf1adda53)
![image](https://github.com/user-attachments/assets/92027629-74a7-423b-8ed7-8b5d8b2afa23)
![image](https://github.com/user-attachments/assets/31d86f78-b2dd-485c-bc11-4327007947c5)
![image](https://github.com/user-attachments/assets/5e91f5a1-e0be-4851-944c-76159bae29a5)
![image](https://github.com/user-attachments/assets/4ea30f3f-f406-4ab5-b146-02cf15d84974)
![image](https://github.com/user-attachments/assets/ad90f268-6848-46ae-acaf-ffdc78831629)
![image](https://github.com/user-attachments/assets/87a10a60-c7bd-4008-97cd-15b56a200c0e)
![image](https://github.com/user-attachments/assets/fce132b4-f86c-4dad-a961-1cafad8b35a6)
![image](https://github.com/user-attachments/assets/ac4e0926-4c37-445c-8f38-23c2e85d3bcb)

**Comment by none3** [comment]
![image](https://github.com/user-attachments/assets/6d62ba34-7052-4fda-af93-06c1a002cde1)
![image](https://github.com/user-attachments/assets/6c74d0f9-e036-48c7-be77-247928aea656)
![image](https://github.com/user-attachments/assets/eb365ab6-495e-4447-b6fe-45f80e7440f9)
![image](https://github.com/user-attachments/assets/6d4f25bb-5b6a-43a3-b0c9-2b56d1c42fd8)
![image](https://github.com/user-attachments/assets/c27b355b-57fc-427c-b4a2-1d961eacaed3)
![image](https://github.com/user-attachments/assets/4be37220-b200-4df0-a7e5-530d89e97626)
![image](https://github.com/user-attachments/assets/fcc78233-f350-4763-8f36-208f569be285)
![image](https://github.com/user-attachments/assets/e8456c3e-bff3-47c8-bd66-c69168d85d4f)
![image](https://github.com/user-attachments/assets/cec006e3-0b44-4e10-8833-c60238db95fd)
![image](https://github.com/user-attachments/assets/803ad6d1-3b7a-4347-8582-0146aaba0fc9)

**Comment by pyrates999** [comment]
In EP properties application, click on **file explorer**, untick **register as shell extension** and click **restart file explorer** in the bottom left corner.

**Comment by none3** [comment]
What about the menu bar, battery icon?

**Comment by pyrates999** [comment]
when you click on the battery and nothing appears, it could be this: https://github.com/valinet/ExplorerPatcher/issues/3640#issuecomment-2332201135

In EP properties application, click on system tray on the left side, you may have the battery option set to windows 10.  Change it to be windows 7.

For file explorer, the setting `Control Interface` being set to `Windows 11 Command Bar (classic Address Bar)` stopped working.  Here's a link to a comment indicating how they fixed it using windhawk: https://github.com/valinet/ExplorerPatcher/issues/2771#issuecomment-2030912792

**Comment by Amrsatrio** [comment]
Duplicate:
https://github.com/valinet/ExplorerPatcher/issues/3640
https://github.com/valinet/ExplorerPatcher/issues/2676

The error message does not matter if you do not use narrator.
