### ISSUE TITLE
"Primary taskbar location on screen" not found.

### ISSUE THREAD

**Issue by srOsaad** [valinet/ExplorerPatcher#3965]
![image](https://github.com/user-attachments/assets/68bdd043-b605-4875-b01e-d0907fbf9c25)

Sir, I am new to Windows 11 and I really want to move my taskbar to the right. So, I followed a YouTube video and tried your app. But according to the tutorial there should be a "Primary taskbar location on screen" option in "Taskbar" tab. I want to know if you have removed it or not. If you have, then how can I access it now and if you haven't, then where is the option now?

**Comment by milesprower2293** [comment]
click on the taskbar style text and click on Windows 10 (ExplorerPatcher) and restart file explorer

**Comment by srOsaad** [comment]
When I am trying to write something in search it is changing it's position
from right-center to bottom-center. I want it to show up right and stay
there the whole time or bottom. Is there any solution?

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.
