### ISSUE TITLE
[Win10 start nenu] If I have czech language as system language, English frases in Start menu and File Explorer are presented

### ISSUE THREAD

**Issue by Panzimy** [valinet/ExplorerPatcher#3967]
As a I said a problem with start menu is that some frases are from english not czech like (Format: English frase presented/Czech frase what will be in this place (older versions of 23H2 or EP **I don't know** now) like from Start menu: New/Nový, Power/Napájení and from File explorer: Downloads/Stažené soubory others are OK but I found that if I update my PC to new version of 23H2 or EP (**I don't know**) some frases are changed from czech to english. **I don't know if this is a problem by microsoft**

**Comment by pyrates999** [comment]
this might be why: https://github.com/valinet/ExplorerPatcher/issues/3927#issuecomment-2479119705

**Comment by Panzimy** [comment]
Ok but anything what can help?

**Comment by pyrates999** [comment]
If it's part of a windows binary, then there is not much that can be done.  But please wait for a developer to confirm.

**Comment by Panzimy** [comment]
Ok

**Comment by Panzimy** [comment]
And yeah I found that the Power button is on Windows 11 normaly working

**Comment by Panzimy** [comment]
And yeah new is OK in Windows 11 settings

**Comment by Panzimy** [comment]
@Amrsatrio Please do something with this

**Comment by Panzimy** [comment]
> If it's part of a windows binary, then there is not much that can be done. But please wait for a developer to confirm.

@pyrates999 
That is not what you think that was other problem
