### ISSUE TITLE
Windhawk issues

### ISSUE THREAD

**Issue by cjahn50** [valinet/ExplorerPatcher#3972]
It appears that version 22621.4317.67.1 causes issue with Windhawk. Taskbar labels are as expected with version 66.6, but revert to Windows 11 boxes with version 67.1.  I'm using Windhawk because 7+ Taskbar Tweaker no longer works with 67.1.

**Comment by milesprower2293** [comment]
what Windows version are you using? also which taskbar style are you using?

**Comment by cjahn50** [comment]
Windows 11 Pro
Version 23H2
OS Build 22631.4460

In EP Taskbar style* : Windows 10

**Comment by milesprower2293** [comment]
> Windows 11 Pro Version 23H2 OS Build 22631.4460
> 
> In EP Taskbar style* : Windows 10

Starting with version 66.7 the Windows 10 taskbar label settings can be changed on the Windows 11 settings app

**Comment by cjahn50** [comment]
Can you elaborate? What specifically is the Window 11 settings app?

**Comment by milesprower2293** [comment]
![image](https://github.com/user-attachments/assets/073cdf07-fecf-43c4-b10e-61c231ce9bbf)

**Comment by cjahn50** [comment]
And can I assume that the issue with Windhawk not displaying labels is related to 67.1? And lastly, why would there be a 66.7 version if 67.1 is current?

**Comment by cjahn50** [comment]
Will those new personalizations allow me to see these types if taskbar labels?

![image](https://github.com/user-attachments/assets/39e9a4f8-2e2c-415c-bee6-f4294e8e2543)

**Comment by milesprower2293** [comment]
Yes

**Comment by milesprower2293** [comment]
> And can I assume that the issue with Windhawk not displaying labels is related to 67.1? And lastly, why would there be a 66.7 version if 67.1 is current?
> 

And no Windhawk does not have anything to do with your "issue".
starting with version 66.7. Taskbar labels are set to always. 
if you want to set labels, go to your taskbar settings and set it to never or combine when taskbar is full

**Comment by cjahn50** [comment]
I would swear to you I did that when I updated to 67.1.  The screen scrape is using 66.6 and 7+ Taskbar Tweeker.  I currently have the combine and hide in windows set to Never. Will that work in 67.1? Or do I need to wait for 66.7?

**Comment by pyrates999** [comment]
Did you try it on 67.1?

**Comment by cjahn50** [comment]
Yes. And I specifically set the Windhawk mod to show the complete label. All I got was a window 11 icon for each Edge instance I had open. No labels at all. At that time I had Outlook and Firefox (single instance) open and all showed just the icon, not label.

**Comment by pyrates999** [comment]
Not in windhawk, in the windows settings application.  Right click on the taskbar and select taskbar settings.

**Comment by cjahn50** [comment]
It's set there as well. I can try again tomorrow. And I'll let you know how it goes.

**Comment by pyrates999** [comment]
disable the windhawk mod and only set it in the windows settings application.

**Comment by milesprower2293** [comment]
> Yes. And I specifically set the Windhawk mod to show the complete label. All I got was a window 11 icon for each Edge instance I had open. No labels at all. At that time I had Outlook and Firefox (single instance) open and all showed just the icon, not label.
> 
> This is the Windhawk mod:
> 
> ![image](https://private-user-images.githubusercontent.com/130588556/390223958-acd5e7a5-c694-4e20-aab3-957a53aaac15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzgwOTMsIm5iZiI6MTczMjY3Nzc5MywicGF0aCI6Ii8xMzA1ODg1NTYvMzkwMjIzOTU4LWFjZDVlN2E1LWM2OTQtNGUyMC1hYWIzLTk1N2E1M2FhYWMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMzIzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODA1OTAxZmFjNzY2ZTI1OGY0YTZlOGVmYzFmYmUxYzQyYWM2M2M2ZGEzNTE5YWVmNWZhZThmMTlhYjY1ZGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hzrlJfKA3FMpBvThhg_AB7HFsVrar-X2u2bg1BXc2QU)

that mod is only compatible with the Windows 11 taskbar not the 10 taskbar
