### ISSUE TITLE
2024-11 Cumulative Update Preview for Windows 11 Version 23H2 breaks ExplorerPatcher

### ISSUE THREAD

**Issue by lovetolearncode** [valinet/ExplorerPatcher#3975]
Hello!
I just did a Windows update and 2024-11 Cumulative Update Preview for Windows 11 Version 23H2 breaks ExplorerPatcher.
I un-installed ExplorerPatcher, and re-installed it to no avail.

I cannot get it to work even thought it is installed. The regular Windows 11 Taskbar comes up.
Please help.

**Comment by milesprower2293** [comment]
Open your search menu and type properties and click on 'Properties (ExplorerPatcher)' then click on the taskbar style text and choose Windows 10 (ExplorerPatcher) and restart file explorer

**Comment by milesprower2293** [comment]
The disable rounded corners issue is already a known issue and for now there are no plans to fix it yet

**Comment by lovetolearncode** [comment]
Thanks much!

I just used this utility:

https://github.com/valinet/Win11DisableRoundedCorners

 

and it works fine!

Cheers,

Russ J
