### ISSUE TITLE
Taskbar is lagging and makes computer freeze

### ISSUE THREAD

**Issue by Rickx058** [valinet/ExplorerPatcher#3977]
I upgraded from 10 to 11 on 25-11-2024 through the Windows update system and it all went smooth. Windows 11 was installed without issues and worked perfect. No lag or whatsoever. After that, I done the last Windows updates and gave the computer a fresh reboot before installing ExplorerPatcher. 

**The issues**
1. If I spam click an opened application (like Discord) from the task bar a bunch, it'll freeze up the taskbar and eventually even the application itself (Discord) and sometimes the whole computer for like a minute. Same goes for if you spam the start button, computer will freeze up after 5 seconds of spamming.
3. Dragging a window (i.e. Chrome) causes freezes/stutters. Is often the case with web browsers. If I drag a tab out to my second monitor, it often freezes for 5 - 10 seconds. 
4. But even with daily slow use of the taskbar, it often glitches (random crashes and restarts of explorer.exe) 
5. Windows in general open/close very slow, even opening my documents or the taskmanager takes way longer than before 

**ExplorerPatcher settings**
As I was already using EP on my work laptop without any issues for the past 6 months, I took those settings over 1:1. Those are: https://imgur.com/a/2e32L17

**PC Specs**
My computer isn't slow either, have decent specs: 
- Windows 11 Pro (legal, no crack), 23H2, 22631.4460, Windows Feature Experience Pack 1000.22700.1047.0
- W11 is installed on a: NVMe m.2 Samsung SSD 970 1 TB drive
- ExplorerPatcher version: 22621.4317.67.1 (latest)
- Ryzen 5 5600
- 32 GB DDR4 3600
- RTX 3080

**Comment by Rickx058** [comment]
**I think I found the issue. Issue can be closed as EP is not the problem.**

Another program, that didn't cause any troubles in Windows 10, is causing the lagging/freezing with EP installed in Windows 11. EP works smooth and without any issues when the other program isn't active, but starts glitching when I do open the program. It's clearly caused by the program, not by EP. 
To verify this I installed the same program on my W11 work laptop with EP installed, and even though the lagging/freezing/glitching is nowhere as bad as on my gaming computer, it does still happen. Meaning that the specific program is causing the problems and not EP.

**Comment by pyrates999** [comment]
try updating your gpu drivers.

**Comment by Rickx058** [comment]
> What program was causing this to happen? I've had this happen twice already, once I even had to force shut down my PC.

It was a game called CygnusMS (MSK.exe), a private server based on the original game MapleStory. For some reason when I run that game it starts lagging like crazy. So yeah, can only play that game as long as I don't touch anything else. Doesn't happen with other games luckily. 

> try updating your gpu drivers.
Done that, didn't change anything.
