### ISSUE TITLE
Can't open windows 10 start menu

### ISSUE THREAD

**Issue by Verssgn** [valinet/ExplorerPatcher#3982]
I started having this issue today. I am pretty sure I have not updated Windows. I tried turning off all apps that might interfere with it. The Windows 11 start menu works fine, just 10 doesn't.

Nothing happens when I click the Windows button (Keyboard) or the Windows icon.
![NVIDIA_Share_5bhbTGkGvT-ezgif com-optimize (1)](https://github.com/user-attachments/assets/c099455f-5f21-423a-88c6-3350510d4e31)

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by pyrates999** [comment]
You can also try using a static background instead of a live wallpaper.

If that doesn't fix it:

Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

**Comment by Verssgn** [comment]
Ok here is a full issue with proper information:
Windows version: 23H2 (OS BUILD 22631.4460)
Language: English
System Type: x64
EP Version: 22621.4317.67.1

Issue: The Windows 10 start menu doesn't work (No matter if the taskbar is set in Windows 11 or Windows 10 mode)
I tried: 
- Switching between the Win 10 start menu and the Win 11 start menu does nothing.
- closing all other apps (including the live wallpaper).
- Restarting a bunch of times, updating windows, updating ep.
- Switching to the Windows 11 start menu works properly, this issue only happens with Win 10 start menu.
- Reinstalling EP

Screenshots:
![NVIDIA_Share_KVIkigUyEP](https://github.com/user-attachments/assets/96866485-2ad5-4bd2-81e0-099dc2bea20f)
![NVIDIA_Share_MszZsPiGIj](https://github.com/user-attachments/assets/a341aae5-d1f7-45cc-b32e-c16ad04eda43)

**Comment by pyrates999** [comment]
Did you click on Restart File Explorer when changing the taskbar setting?

Do you have any other software installed that modifies the UI, like windhawk?

**Comment by Verssgn** [comment]
Yes I did, I only had 7+ Taskbar Tweaker (Which I uninstall to check) and Translucent TB (Which is turned off).

**Comment by pyrates999** [comment]
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  Try clicking on the start menu button several times.  Copy and paste the results here.

**Comment by Verssgn** [comment]
When I click the start button nothing gets printed, when I restart explorer patcher these are the prints:
```
Running on Windows 11, OS Build 10.0.22631.4541.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 4EB30
ITrayUIHost = 3EE468
explorer.exe!TrayUI_CreateInstance() = 1DDCEC
Setup explorer functions done
Setup uxtheme functions done
ILauncherTipContextMenuVtbl = 798048
CLauncherTipContextMenu::ShowLauncherTipContextMenu() = 1CB780
CLauncherTipContextMenu::GetMenuItemsAsync() = 6BD4B0
[SMA] matchVtable = 79DE38
[SMA] matchSingleViewShellExperienceFields = 10272D
[SMA] matchAnimationHelperFields = 10276C, +0x240, +0x260
[SMA] matchTransitioningToCortanaField = 428E24, +0x2C8
[SMA] CStartExperienceManager::GetMonitorInformation() = E8FD8
[SMA] CExperienceManagerAnimationHelper::Begin() = 738F5C
[SMA] CExperienceManagerAnimationHelper::End() = 2C68D2
[SMA] matchHideA in CStartExperienceManager::Hide() = E94D
[SMA] matchHideB in CStartExperienceManager::Hide() = E98D
[SMA] Advertising successful animations patching.
[JVP] matchOffsetTrayStuckPlace = 42DCDA
[JVP] matchOffsetRcWorkArea = 42DD7C
[JVP] matchEnsureWindowPosition = 42C28C
Setup twinui.pcshell functions done
[TB] Using 'ep_taskbar.2.dll'
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup peopleband functions done
Installed hooks.
Open Start on monitor thread
EP Service Window thread
Started "Open Start on current monitor" thread.
Started "Signal shell ready" thread.
Initialized taskbar centering module.
UtcToTzTime() = timedate.cpl+21F94
Registered Win+A, Win+B, and Win+N
[Positioning] Added settings for monitor 0000000000010001 : 0
[Positioning] Added settings for monitor 0000000000010003 : 0
Progman: 131658
Progman hook: 131837
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Using hardcoded hash.
[Updates] Checking against hash "22622.4317.67.1.8bfca71add96d3de"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.4317.67.1.8bfca71add96d3de" (valid).
[Updates] Local version obtained from hash is 22622.4317.67.1.
[Updates] No updates are available.
0 0
shell\explorer\taskband2\TaskBand.cpp(7309)\ep_taskbar.2.dll!00007FFAC82C5371: (caller: 00007FFAC82BFDB2) ReturnHr(1) tid(2c74) 80073B1F ResourceMap Not Found.
shell\explorer\taskband2\TaskBand.cpp(5323)\ep_taskbar.2.dll!00007FFAC82BFDCE: (caller: 00007FFAC82B82A5) LogHr(1) tid(2c74) 80073B1F ResourceMap Not Found.
shell\explorer\TrayUI.cpp(6109)\ep_taskbar.2.dll!00007FFAC827EB1B: (caller: 00007FFAC8274CBC) LogHr(2) tid(2c74) 80004005 Unspecified error
shell\explorer\TrayItem.cpp(390)\ep_taskbar.2.dll!00007FFAC8251153: (caller: 00007FFAC8252828) ReturnHr(2) tid(2c74) 80004005 Unspecified error
shell\explorer\TrayItem.cpp(390)\ep_taskbar.2.dll!00007FFAC8251153: (caller: 00007FFAC8252828) ReturnHr(3) tid(2c74) 80004005 Unspecified error
shell\explorer\TrayItem.cpp(390)\ep_taskbar.2.dll!00007FFAC8251153: (caller: 00007FFAC8252828) ReturnHr(4) tid(2c74) 80004005 Unspecified error
```

**Comment by pyrates999** [comment]
Thank you.  I think that will help the developers figure out why it's not working for you.

**Comment by Amrsatrio** [comment]
Have you ever installed Rectify11 before?

**Comment by Verssgn** [comment]
Oh damn, will it cause any other issues outside of the start menu? Also I am guessing I should close this issue now. Maybe it could be caused by a virus since I am really confused what else it could have caused it.

**Comment by Amrsatrio** [comment]
With the classic Mail & Calender UWP app (that's now being deprecated), I read some forum posts that it fails to open when UWP apps (ALL APPLICATION PACKAGES) cannot access the Program Files folder. I can't recall anything more other than that.

**Comment by Verssgn** [comment]
Well that’s unfortunate, guess I will clean install. I going to close the issue now, thank you very much for your assistance.

**Comment by Amrsatrio** [comment]
You're welcome, always at your service.
