### ISSUE TITLE
No context menu for pinned apps

### ISSUE THREAD

**Issue by derrapf** [valinet/ExplorerPatcher#3985]
As requested here the new issue:

I am using EP 22621.3527.65.5 and Win 1123H2 22631.4460 (by the way: Why can I not copy this version from the "about screen"?
My taskbar is on top. I have taskbar Tweaker installed; but still have the issue when I close taskbar Tweaker.

Problem: 
There is no right mouse-button context menu on the pinned applications in the taskbar
It works with the taskbar at the bottom.
Is there any fix to that? I use EP because I want the taskbar on top of my screen

BR Ralf

**Comment by pyrates999** [comment]
update your version of EP, it is out of date: https://github.com/valinet/ExplorerPatcher/releases

Read the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender.

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active, which means you need to add those files and directories to be excluded in your antivirus program.

**Comment by derrapf** [comment]
Ah thanks! I could without any problems update to 22621.4317.67.1
Now it works again.
Nevertheless: Would it be possible to make the text in the about-box of the properties window selectable? Then the users could copy and paste things like the version number (which is obviously a cumbersome number) into those threads.
BR Ralf

**Comment by pyrates999** [comment]
Please file that under Discussions.
