### ISSUE TITLE
Random Notepad crash

### ISSUE THREAD

**Issue by CaniniMichele** [valinet/ExplorerPatcher#3986]
Hi,
from some release ago, sometime when I open a text file, after that Notepad start for a while it crash with this error:

Windows 11 Enterprise 23H2

Faulting application name: Notepad.exe, version: 11.2409.9.0, timestamp: 0x6705deae
Faulting module name: ExplorerPatcher.amd64.dll, version: 22621.4317.67.1, timestamp: 0x67262c6d
Exception code: 0xc0000005
Fault offset: 0x000000000000d438
Faulting process ID: 0x0x4568
Faulting application start time: 0x0x1DB424C7342D5F6
Faulting application path: C:\Program Files Files\WindowsApps\Microsoft.WindowsNotepad_11.2409.9.0_x64__8wekyb3d8bbwe\Notepad\Notepad.exe
Faulting module path: C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
Report ID: 384d1fd0-ee71-4738-8d08-a18e8e03c0a3
Faulting full package name: Microsoft.WindowsNotepad_11.2409.9.0_x64__8wekyb3d8bbwe
Application ID for the faulting package: App

**Comment by pyrates999** [comment]
In EP properties application, click on **file explorer**, untick **register as shell extension** and click **restart file explorer** in the bottom left corner.

Here's why not to enable it: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension
