### ISSUE TITLE
Update links are not clickable

### ISSUE THREAD

**Issue by dbob456** [valinet/ExplorerPatcher#3996]
![image](https://github.com/user-attachments/assets/d87c93b3-4878-4035-8f59-e42d873e
Update links are not clickable

**Comment by pyrates999** [comment]
please upload your image again as I can't view it.

**Comment by dbob456** [comment]
[image: image.png]

**Comment by pyrates999** [comment]
You can't upload images via email.  Please log into the github website using your web browser.

**Comment by dbob456** [comment]
"Check for updates" and "Update program and restart File Explorer"
Hyperlinks do nothing. It's like clicking on "normal" text. Nothing happens.

**Comment by pyrates999** [comment]
Check if you've disabled notifications on windows 11 for EP.

**Comment by dbob456** [comment]
Ah.... Had do not disturb on thankyou. Great progam. Thanx

**Comment by pyrates999** [comment]
Please close this then.
