### ISSUE TITLE
Zending Type verkeerd 

### ISSUE THREAD

**Issue by Schoonmaakdoekje** [valinet/ExplorerPatcher#3997]
Bestellingen van België of NL schieten soms naar de verkeerde Zending Type, het gebeurt vaker dat de belgen als Letter Box worden aangemeld terwijl dit International Boxable Packets moet zijn. (en andersom)

<img width="208" alt="belgie-staat verkeerd" src="https://github.com/user-attachments/assets/f5cf4810-6709-448d-9705-37d317c2b778">

**Comment by Amrsatrio** [comment]
Unrelated to this project.
