### ISSUE TITLE
Quick Launch Missing / No longer able to add folders to the task bar with 24H2

### ISSUE THREAD

**Issue by Digioso** [valinet/ExplorerPatcher#3999]
Hi!

I exported my Explorer Patcher configuration, uninstalled EP, then updates to 24H2.
Then installed newest EP version (22621.4317.67.1) and imported my configuration.

Until now I had the Quick Launch pinned to my taskbar, but I am no longer able to add any folders to the taskbar since the update.
Has this feature been removed?
I tried all taskbar styles (11, 10, 10 (EP) but it's no longer working. The option to add a folder to the task bar is missing.

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3696

Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by Digioso** [comment]
Thanks! This only seems to be working after a reboot. I had Windows 10 (ExplorerPatcher) enabled, but still couldn't add the folder. Now, after a reboot, the options are there.

**Comment by DaveJ61** [comment]
Hi, My quicklaunch has also completely gone. I son't know whether it had anything to do with me forcing removal of Microsoft Edge with Gwek Uninstaller, but I don't think so as i was there for a few hours. Then I came back home to find the quick launch gone. I am using Windows 10 (ExplorerPatcher)

**Comment by pyrates999** [comment]
> Thanks! This only seems to be working after a reboot. I had Windows 10 (ExplorerPatcher) enabled, but still couldn't add the folder. Now, after a reboot, the options are there.

Open up EP properties application and click on Restart File Explorer in the bottom left corner.

**Comment by Amrsatrio** [comment]
26100.2314 adding folders to the taskbar works.
![image](https://github.com/user-attachments/assets/d181b221-e505-4ec5-97b5-229585473e8a)
