### ISSUE TITLE
Openshell taskbar skinning broken when using Windows 10 taskbar on 24H2.

### ISSUE THREAD

**Issue by Pokemonfan1000** [valinet/ExplorerPatcher#4001]
Hi! I updated to Windows 11 24H2 and got the Windows 10 taskbar back, however, the taskbar skin that I use via Openshell is broken. The entire taskbar is black except for the Task view button and the notification area icons, which take on the taskbar skin I applied. If I remove the skin, make the taskbar transparent, and blue colored, that is fine. I have to use EP's Windows 10 taskbar, as the original W10 taskbar got removed in 24H2 (where the taskbar skin worked fine), so this leads me to believe it is a problem with EP's W10 taskbar, not with Openshell. Here's a screenshot that shows what happens when an image texture is applied via Openshell when using the EP Win10 taskbar (If you use 23H2 or earlier, you'll be fine as you still have the original Windows 10 taskbar).

![Screenshot 2024-12-04 173122](https://github.com/user-attachments/assets/1b1e3635-d538-4531-84e4-5293a1bac93e)

**Comment by Pokemonfan1000** [comment]
Here's what the taskbar should look like if the skin applied correctly.

![CWOF_Taskbar](https://github.com/user-attachments/assets/8d8a6945-2ce5-4c07-9483-9900c3ee4546)

**Comment by KunjanChauhan** [comment]
I hit install Win 11 24H2 update by mistake and received the following dialog.

![image](https://github.com/user-attachments/assets/37349409-a8ef-46d9-b766-19dbac9d640e)

And the install failed with error code: 0xc1900209

It's nice that MSFT didn't just kill Explorer Patcher.

**Comment by Amrsatrio** [comment]
Nothing we can do. Report this to Open-Shell.
