### ISSUE TITLE
Taskbar separators appearing even though they're switched off

### ISSUE THREAD

**Issue by Vansaska** [valinet/ExplorerPatcher#4003]
A couple of weeks ago, || separators started showing up on my taskbar even though I hadn't touched any settings and "Show separators between taskbar toolbars" has always been set to off. I've tried toggling it on and off and restarting everything but they're still there. Is there any way to get rid of them?

**Comment by Vansaska** [comment]
Windows 10 – if I switch to Windows 11 it doesn't happen.

**Comment by pyrates999** [comment]
Just in case: Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by Vansaska** [comment]
OK tried that, no change though.

**Comment by pyrates999** [comment]
can you show a screen shot of what you mean by taskbar separators?

**Comment by pyrates999** [comment]
Those are taskbar dividers.  Right click on the taskbar and tick **Lock the taskbar**.

**Comment by Vansaska** [comment]
Oh, yes, I see! Apologies!
