### ISSUE TITLE
Keyboard combination WIN+C does not work on Win11 24H2

### ISSUE THREAD

**Issue by ethanwind** [valinet/ExplorerPatcher#4005]
Good afternoon.
Yesterday I have updated Windows 11 to 24H2 version, previously uninstalling Explorer Patcher. After the update I have reinstalled the program but, since then, the keyboard combination WIN+C does not work anymore, that is to say that it won't open Win10 calendar flyout.
Is it possible to fix this issue in further development?
Thank you so much.

**Comment by pyrates999** [comment]
Not caused by EP: https://arstechnica.com/google/2024/06/winc-windows-most-cursed-keyboard-shortcut-is-getting-retired-again/

Use this instead to create custom keyboard shortcuts: https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager

**Comment by ethanwind** [comment]
Thanks for your reply.
I apologize. I thought it was an incompatibility issue.
Thanks also for your suggestion.

**Comment by ethanwind** [comment]
It would be useful to know which is the key combination that opens Windows 10 calendar flyout in Windows 11.
May anyone help me? Thanks.

**Comment by pyrates999** [comment]
Try windows key + N: https://www.ionos.ca/digitalguide/server/configuration/windows-11-keyboard-shortcuts/

**Comment by ethanwind** [comment]
> Try windows key + N: https://www.ionos.ca/digitalguide/server/configuration/windows-11-keyboard-shortcuts/

Thank you, but I was searching for **Windows 10** calendar flyout, not the new one.

**Comment by pyrates999** [comment]
try: WIN + ALT + D

but according to this, it no longer works: https://www.reddit.com/r/WindowsHelp/comments/163h5j7/shortcut_to_open_datecalendar_panel_from_windows/

**Comment by pyrates999** [comment]
Please wait for a developer to respond though just in case.

**Comment by ethanwind** [comment]
> try: WIN + ALT + D
> 
> but according to this, it no longer works: https://www.reddit.com/r/WindowsHelp/comments/163h5j7/shortcut_to_open_datecalendar_panel_from_windows/

I had already tried this combination but with no luck...

**Comment by Susko3** [comment]
<kbd>Win</kbd>+<kbd>Alt</kbd>+<kbd>D</kbd> works for me when using Windows 10 clock flyout (EP Properies → System tray → Clock).
