### ISSUE TITLE
Taskbar does not remember number of rows and does not use reg setting

### ISSUE THREAD

**Issue by AJolly** [valinet/ExplorerPatcher#4007]
The win 10 taskbar style Does not seem to remember the number of rows I have set, or the lock setting.
It seems to always go back to a single row, and a locked taskbar. 

This may happen to me more frequently because I switch between a three monitor set up and a different single monitor setup frequently during my day.

I've tried setting in the registry Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3 Settings, row 28n FE to 2, but that doesn't work.

https://windowsreport.com/windows-11-taskbar-2-rows/

Any advice would be appreciated!
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎4/‎22/‎2024
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0

EP 22621.4317.67.1

**Comment by rEd2k** [comment]
Exact same problem here with exact same fix attempted with exact same result as you, unfortunately.

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by rEd2k** [comment]
> Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**. We no longer offer more support on the stock Windows 10 taskbar.

Problem exists with the "Windows 10 (ExplorerPatcher)" option set. Appears that the "Windows 10 (ExplorerPatcher)" option is limited in functionality as there is no "lock/unlock" taskbar setting vs the standard "Windows 10" setting, and therefor no taskbar resizing is possible. I also use a double high taskbar, but alas, this not possible currently with the "Windows 10 (ExplorerPatcher)" option as far as I can tell, and no reg edit helps either.

**Comment by pyrates999** [comment]
please see this: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

**Comment by AJolly** [comment]
@rEd2k I've got two lines with Win 10 EP
![image](https://github.com/user-attachments/assets/8501ebda-af92-4e27-bc61-c18266d31fcd)

**Comment by rEd2k** [comment]
> @rEd2k I've got two lines with Win 10 EP ![image](https://private-user-images.githubusercontent.com/91493/393645893-8501ebda-af92-4e27-bc61-c18266d31fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2OTY3NzcsIm5iZiI6MTczMzY5NjQ3NywicGF0aCI6Ii85MTQ5My8zOTM2NDU4OTMtODUwMWViZGEtYWY5Mi00ZTI3LWJjNjEtYzE4MjY2ZDMxZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDIyMjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMDY5M2M5OTNjOGFiMmQ4ODA5YzVjZDZmZjc1NTJlMjhiZGE1OGUyNDI5MmQ1YzRhYmU4ZDhjNWRhNDE4NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aE4KaFYMxS5cm3-SHL8NSEuu0S7l1MoCejl8SCtQrqY)

How? I did the exact same regedit you did and I have the exact same settings you have on that screen shot you posted. What am I doing wrong here? Are you able to lock/unlock the taskbar to resize it? Or is it the regedit you did, or a different regedit I am unaware of? Thanks for posting your results btw, it gives me hope to get my double taskbar back ;)

**Comment by Amrsatrio** [comment]
Do not use StuckRects3 and MMStuckRects3, they're for the stock Windows 10/Windows 11 taskbar. Use StuckRectsLegacy and MMStuckRectsLegacy respectively.

**Comment by rEd2k** [comment]
> Do not use StuckRects3 and MMStuckRects3, they're for the stock Windows 10/Windows 11 taskbar. Use StuckRectsLegacy and MMStuckRectsLegacy respectively.

Hi, I do not have "MMStuckRectsLegacy" in my registry. Also, I found that when I change the "StuckRectsLegacy" in anyway, it just restores back to 01 at the row 28, FE column. Maybe I need an entry for the "MMStuckRectsLegacy" and may then the "StuckRectsLegacy" entry will stay, I don't know. Any idea why I may be missing the entry you are referring to? Know anywhere I could grab the reg file to add it? Thanks and again, sorry for keeping the topic alive, I know you want it closed.

**Comment by Urgo** [comment]
@rEd2k not sure if this will fix it for you, but I've been watching this issue for a couple of days now having the same problem. I just checked over @AJolly's screen shot comparing it to my settings (I didn't change anything) and then clicked the restart explorer from on that screen shot vs how I was doing it before in task manager. That seemed to fix it for me giving me the [x] lock task bar option again at last.  Maybe I just got lucky, but maybe this is the fix you needed too!

**Comment by rEd2k** [comment]
> @rEd2k not sure if this will fix it for you, but I've been watching this issue for a couple of days now having the same problem. I just checked over @AJolly's screen shot comparing it to my settings (I didn't change anything) and then clicked the restart explorer from on that screen shot vs how I was doing it before in task manager. That seemed to fix it for me giving me the [x] lock task bar option again at last. Maybe I just got lucky, but maybe this is the fix you needed too!

First of all I would like to thank @Urgo for your response as it gave me more drive to look deeper. The issue wasn't fixed by Urgo's suggestion unfortunately, but it got me thinking that it MUST be possible to fix and @Ajolly had success. I found the answer [here in this old post]https://github.com/valinet/ExplorerPatcher/discussions/2629?sort=old and it 100% fixed the issue which had nothing to do with any of the "StuckRectsLegacy" or my missing "MMStuckRectsLegacy" registry entries. 

I'm hoping that the developers see this thread and possibly take the time to add a simple registry check upon install of the software and auto fix the possible issue, or maybe make a REG file download available to those that may have the missing/greyed out "lock the taskbar" option. Of course assuming that the "Windows 10 (ExplorerPatcher)" option has been enabled first! This option was always selected in my case and is not the root cause of my woes either.

I hope this helps someone out there who has this issue, it really is an easy reg fix, but a fix that seems to have gotten away from some, I hope it can be addressed. Otherwise, I love explorerpatcher, and any bug or small thing is worth it. I will always have this software installed and I appreciate all the work that goes into it. Thank you guys :)

**Comment by pyrates999** [comment]
The TaskbarLockAll registry entry is mentioned here: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.TaskBar2::TaskbarLockAll

And it would most likely be set by your windows domain system administrators on a work computer.  If that's the case, talk to your work IT department.

**Comment by rEd2k** [comment]
> The TaskbarLockAll registry entry is mentioned here: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.TaskBar2::TaskbarLockAll
> 
> And it would most likely be set by your windows domain system administrators on a work computer. If that's the case, talk to your work IT department.

To clarify, my situation was similar to that of the user in the old post I found, where once I upgraded to Windows version 26100.2454 I did have my taskbar locked. In PubliusTX situation there was an upgrade from windows 10 to windows 11. In my case it was that huge update to 26100.2454 while having the taskbar set to locked beforehand and lost all functionality of the lock/unlock ability in explorerpatcher. I'm guessing any large update with many changes to the taskbar can have this effect and lockout the lock/unlock functionality while using explorerpatcher. If true, I say to any out there to make sure to UNLOCK your taskbar before doing any updates to windows! THEN one can install explorerpatcher afterwards as a precautionary measure.

**Comment by AJolly** [comment]
This doesnt help my problem with it not remembering  taskbar height.  Weirdly, the problem mostly happens on the primary monitor.

**Comment by AJolly** [comment]
> Do not use StuckRects3 and MMStuckRects3, they're for the stock Windows 10/Windows 11 taskbar. Use StuckRectsLegacy and MMStuckRectsLegacy respectively.

@Amrsatrio  Can you give more details on how to get the taskbar to remember the height/lock settings? Since you've closed the issue.

**Comment by jimklimov** [comment]
For future readers: one bit I've missed that the "Lock Taskbar" setting is not in the FE Properties app, it is in the context menu of the taskbar itself (like it was in Win 10 and before).

**Comment by pyrates999** [comment]
Because the lock taskbar option has always been in the right click menu of the taskbar.
