### ISSUE TITLE
Duplicate window shown on Win10 Window Switcher

### ISSUE THREAD

**Issue by BraINstinct0** [valinet/ExplorerPatcher#401]
~Similar to (but the exact opposite of) #161, now~ _duplicate_ windows are sometimes shown on Windows 10 style Window Switcher.

![image](https://user-images.githubusercontent.com/29201475/142128862-91cf6ae4-2ebd-482a-a6d8-32459d90ea9d.png)

The duplicate window is normally one, and is shown as one in Win11 style or Win+Tab.
I am not sure when this behavior started, but at least it is not critical(since well, at least you can see it).

**Comment by valinet** [comment]
Restarting it fixes it.

It started a while ago. I don’t understand it, I don’t know how to fix it, for the life in me I cannot figure out why the check whether a window is already in the list does not catch it.

Please consider contributing.

**Comment by valinet** [comment]
Like, when have you experienced this? For me, it only happens after restarting Explorer with some windows open...

**Comment by valinet** [comment]
Anyway, I tried a fix, I will test it, don't know if it solves the issue exactly, and will probably be merged with a subsequent update, it can't make it worse either.

**Comment by BraINstinct0** [comment]
> Like, when have you experienced this? For me, it only happens after restarting Explorer with some windows open...

Yes, I think it is the case too.
At least I got one reproducible result: (while Win10 style for Window Switcher is selected)
1. open any(_any_, other than the properties setting for ExplorerPatcher as that will be closed soon)
2. Restart Explorer
3. the 'last open( active ) window' will be duplicated.

Seems like that's the only case for now.

**Comment by valinet** [comment]
Yeah, it's the only case of adding windows that did not have a check... can you reproduce it 100% of times? If so, can you test the new version a bit?

[dxgi.zip](https://github.com/valinet/ExplorerPatcher/files/7552343/dxgi.zip)

**Comment by BraINstinct0** [comment]
Yes, it was reproduced 100% of the time, and testing the above release multiple times(about 20 times)(with several settings) no more duplicates.

**Comment by valinet** [comment]
Well, that's great then, thanks for the input. I will push the update soon, today most probably, thank you very much for the feedback.
