### ISSUE TITLE
Windows 10 Taskbar is not available with this version of Windows - 24H2

### ISSUE THREAD

**Issue by granterogers** [valinet/ExplorerPatcher#4011]
Hi Guys,

Just updated Windoze to 24H2 and can no longer use the Win 10 Taskbar

![image](https://github.com/user-attachments/assets/28fe91e8-0d80-4ba6-839f-f9f6edafddfb)

EP 22621.4317.67.1
Windows 24H2 (26100.2314)

Thanks for any help!

**Comment by granterogers** [comment]
apologies, just realised I need to select Windows 10 Explorer Patcher.... still "Taskbar Tweaker" doesn't work any more, but that is an issue for a different forum.

**Comment by granterogers** [comment]
in case anyone was in the same boat, I had to stop using "Taskbar Tweaker" and migrate to Windhawk

**Comment by pyrates999** [comment]
taskbar tweaker is mentioned here as not supported by Windows 10 Explorer Patcher taskbar: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation
