### ISSUE TITLE
Unable to Install ExplorerPatcher

### ISSUE THREAD

**Issue by Bermudagirl52** [valinet/ExplorerPatcher#4014]
Had to uninstall ExplorerPatcher to install Windows 11 24H2, but can not reinstall it after the upgrade. I really want EP back please!

**Comment by pyrates999** [comment]
See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active, which means you need to add those files and directories to be excluded in your antivirus program.
