### ISSUE TITLE
Windows 10 taskbar is not available in this version of Windows

### ISSUE THREAD

**Issue by IronEddie42** [valinet/ExplorerPatcher#4015]
I tried searching but didn't find anything similar ...

![image](https://github.com/user-attachments/assets/0ae694f5-dcc2-4b98-8418-b98ef23cff6a)
![image](https://github.com/user-attachments/assets/c45b7814-2b26-48b1-a2e0-b64d7c390da9)

Not sure if there's a way to fix this, but I am seriously missing my EP.

Any help is much appreciated.

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

please see this for more info: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

**Comment by IronEddie42** [comment]
> Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**. We no longer offer more support on the stock Windows 10 taskbar.
> 
> please see this for more info: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

Awesome - thank you for the quick reply.

One more small thing that I can't seem to figure out - is there for it to always show all of the system tray icons, instead of hiding some?

**Comment by IronEddie42** [comment]
Disregard - I found the setting.  Thanks!
