### ISSUE TITLE
Windows 10 Explorer Patcher Taskbar on EP build 22621.4317.67.1 fails to work and instead launches default Windows 11 Taskbar on Windows 11 Build 26100.2454

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [valinet/ExplorerPatcher#4017]
Upon installing explorer patcher and using the PowerShell command provided to disable windows defender from detecting it, the **Windows 10 taskbar recreation when selected doesn't launch** and instead uses the **default Windows 11 Taskbar**. Before you ask, I have no other customization software except StartAllBack and upon uninstalling it **nothing changes**.

**Comment by milesprower2293** [comment]
open your search menu and type Properties and click on 'Properties (ExplorerPatcher)' then click on the 'Taskbar style' text and choose Windows 10 (ExplorerPatcher) and restart file explorer

**Comment by ThunderboltCommunicationsCorp** [comment]
No you're wrong. I already did that and you would know that if you bothered to actually read what I'm saying! It doesn't show the windows 10 but instead shows the Windows 11 taskbar, AFTER selecting the taskbar to be "Windows 10 (Explorer Patcher)".

**Comment by pyrates999** [comment]
Uninstall StartAllBack and retry what was suggested.
