### ISSUE TITLE
Weird issue with the search box?

### ISSUE THREAD

**Issue by gtaiscool236** [valinet/ExplorerPatcher#4018]
![image](https://github.com/user-attachments/assets/d4d86b76-e6ed-49ec-94f0-7860cb84918e)
It disappears when i open either search or the start menu

**Comment by gtaiscool236** [comment]
![image](https://github.com/user-attachments/assets/5c53e46a-e172-4208-89d2-fd5d2ccbac80)
oh and here's my windows version

**Comment by Shin-God** [comment]
I have the same problem, how should I solve it

**Comment by milesprower2293** [comment]
> I have the same problem, how should I solve it

It can't be fixed
Windows 11 uses a different search program

**Comment by Shin-God** [comment]
> > I have the same problem, how should I solve it
> 
> It can't be fixed Windows 11 uses a different search program

ok...thank you
