### ISSUE TITLE
Pasting Defender Script into Powershell Results in Multiple Errors

### ISSUE THREAD

**Issue by lmservas** [valinet/ExplorerPatcher#4021]
I copied and pasted the defender script provided for whitelisting the various EP files, etc. but I get the following errors when doing so:

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Wind ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:1
+ Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Wind ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

**Comment by lmservas** [comment]
I fixed my Powershell profile so that it operates as administrator and tried again but got the following errors still:

PS C:\Users\lmser> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
Get-Process : A positional parameter cannot be found that accepts argument 'Add-MpPreference'.
At line:1 char:1
+ PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Program Files\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetProcessCommand

PS C:\Users\lmser> Add-MpPreference : Operation failed with the following error: 0x%1!x!
Add-MpPreference : A positional parameter cannot be found that accepts argument ':'.
At line:1 char:1
+ Add-MpPreference : Operation failed with the following error: 0x%1!x!
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-MpPreference], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Add-MpPreference

PS C:\Users\lmser> At line:1 char:1
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.

PS C:\Users\lmser> + Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
At line:1 char:2
+ + Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
+   ~~~~~~~~~~~~~~~~
Unexpected token 'Add-MpPreference' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:2
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
At line:1 char:6
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+      ~
Missing expression after unary operator '+'.
At line:1 char:7
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+       ~~~~~~~~~~~~
Unexpected token 'CategoryInfo' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
At line:1 char:6
+     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
+      ~
Missing expression after unary operator '+'.
At line:1 char:7
+     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
+       ~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'FullyQualifiedErrorId' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>
PS C:\Users\lmser> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
Get-Process : A positional parameter cannot be found that accepts argument 'Add-MpPreference'.
At line:1 char:1
+ PS C:\Users\lmser> Add-MpPreference -ExclusionPath "$env:APPDATA\Expl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetProcessCommand

PS C:\Users\lmser> Add-MpPreference : Operation failed with the following error: 0x%1!x!
Add-MpPreference : A positional parameter cannot be found that accepts argument ':'.
At line:1 char:1
+ Add-MpPreference : Operation failed with the following error: 0x%1!x!
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-MpPreference], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Add-MpPreference

PS C:\Users\lmser> At line:1 char:1
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.

PS C:\Users\lmser> + Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
At line:1 char:2
+ + Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
+   ~~~~~~~~~~~~~~~~
Unexpected token 'Add-MpPreference' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:2
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
At line:1 char:6
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+      ~
Missing expression after unary operator '+'.
At line:1 char:7
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+       ~~~~~~~~~~~~
Unexpected token 'CategoryInfo' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
At line:1 char:6
+     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
+      ~
Missing expression after unary operator '+'.
At line:1 char:7
+     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
+       ~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'FullyQualifiedErrorId' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>
PS C:\Users\lmser> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
Get-Process : A positional parameter cannot be found that accepts argument 'Add-MpPreference'.
At line:1 char:1
+ PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\dxgi.d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetProcessCommand

PS C:\Users\lmser> Add-MpPreference : Operation failed with the following error: 0x%1!x!
Add-MpPreference : A positional parameter cannot be found that accepts argument ':'.
At line:1 char:1
+ Add-MpPreference : Operation failed with the following error: 0x%1!x!
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-MpPreference], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Add-MpPreference

PS C:\Users\lmser> At line:1 char:1
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.

PS C:\Users\lmser> + Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
At line:1 char:2
+ + Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
+   ~~~~~~~~~~~~~~~~
Unexpected token 'Add-MpPreference' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:2
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
At line:1 char:6
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+      ~
Missing expression after unary operator '+'.
At line:1 char:7
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+       ~~~~~~~~~~~~
Unexpected token 'CategoryInfo' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
At line:1 char:6
+     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
+      ~
Missing expression after unary operator '+'.
At line:1 char:7
+     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
+       ~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'FullyQualifiedErrorId' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>
PS C:\Users\lmser> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
Get-Process : A positional parameter cannot be found that accepts argument 'Add-MpPreference'.
At line:1 char:1
+ PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\System ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetProcessCommand

PS C:\Users\lmser> Add-MpPreference : Operation failed with the following error: 0x%1!x!
Add-MpPreference : A positional parameter cannot be found that accepts argument ':'.
At line:1 char:1
+ Add-MpPreference : Operation failed with the following error: 0x%1!x!
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-MpPreference], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Add-MpPreference

PS C:\Users\lmser> At line:1 char:1
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.

PS C:\Users\lmser> + Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Wind ...
>> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
>>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
>>
>> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
>> Add-MpPreference : Operation failed with the following error: 0x%1!x!
>> At line:1 char:1
>> + Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
>> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
>>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
>>
>> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
>> Add-MpPreference : Operation failed with the following error: 0x%1!x!
>> At line:1 char:1
>> + Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
>> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
>>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
>>
>> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
>> Add-MpPreference : Operation failed with the following error: 0x%1!x!
>> At line:1 char:1
>> + Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
>> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
>>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference
>>
>> PS C:\Users\lmser> Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
>> Add-MpPreference : Operation failed with the following error: 0x%1!x!
>> At line:1 char:1
>> + Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Wind ...
At line:1 char:2
+ + Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Wi ...
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Wi ...
+   ~~~~~~~~~~~~~~~~
Unexpected token 'Add-MpPreference' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:2
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ...
+  ~
Missing expression after unary operator '+'.
At line:1 char:3
+ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
>>    CimException
At line:1 char:6
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+      ~
Missing expression after unary operator '+'.
At line:1 char:7
+     + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\M ...
+       ~~~~~~~~~~~~
Unexpected token 'CategoryInfo' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\lmser>     + FullyQualifiedErrorId : HRESULT 0xc0000142,Add-MpPreference

**Comment by pyrates999** [comment]
If you have another Antivirus installed, you must add the exclusions to that instead.  And when posting powershell script and the output you get from it, use the Code feature:

![image](https://github.com/user-attachments/assets/4620e5cd-16c0-46f0-9baa-c3b737a891d8)

**Comment by milesprower2293** [comment]
@lmservas you have to run powershell as an administrator

**Comment by pyrates999** [comment]
That error is because you have McAfee installed.  You must add the exclusions to McAfee then.  And McAfee is active even if you have not activated it.

Check here to verify what antivirus you have active: https://learn.microsoft.com/en-us/windows/security/operating-system-security/system-security/windows-defender-security-center/windows-defender-security-center
