### ISSUE TITLE
Windows Switcher Alt+Tab style - windows 10 doesn't change

### ISSUE THREAD

**Issue by win-mac-net** [valinet/ExplorerPatcher#4024]
Windows 10 style doesn't show icons in alt+tab (windows 10 classic alt+tab).  It looks just like windows 11 default style.
Windows 11 24H2

**Comment by milesprower2293** [comment]
The Windows NT alt+tab switcher was removed on Windows 11 24H2 and there are no plans or methods to bring it back

**Comment by Amrsatrio** [comment]
Have you restarted explorer after changing to 10 alt tab? No issues here on latest release 24H2.

**Comment by win-mac-net** [comment]
Yes I restarted my computer multiple times.
