### ISSUE TITLE
Windows 11, Version 24H2 Update Problem

### ISSUE THREAD

**Issue by zitalorna** [valinet/ExplorerPatcher#4025]
I am not able to install Windows 11, Version 24H2 update. I receive an error message which states: 

The following things need your attention to continue the installation and keep your Windows settings, personal files and apps.
ExplorerPatcher. 
This app can't run because it causes security or performance issues on Windows. A new version may be available. Check with your software provider for an updated version that runs on this version of Windows.

I currently have the latest version of ExplorerPatcher. Are there any solutions?

**Comment by HamadaSukenao** [comment]
According to the [Releases](https://github.com/valinet/ExplorerPatcher/releases) page, it is recommended you uninstall ExplorerPatcher before updating to Windows 11 24H2. You can then reinstall with your configs all intact.

**Comment by zitalorna** [comment]
Many thanks for the response.
