### ISSUE TITLE
missing windows start icon 

### ISSUE THREAD

**Issue by 00Hawk00** [valinet/ExplorerPatcher#4026]
when i set the style to Windows 10 (explorerpatcher) i loose the windows start icon in the task bar. i still have access to the menu by putting the mouse cursor right to the edge.
is there a way of re enabling the icon without having to use the default style? My main reason for using EP is i have the taskbar set to the left edge of the screen.

**Comment by 00Hawk00** [comment]
start button style doesn't do anything ..

**Comment by Amrsatrio** [comment]
Do not use StartAllBack and EP at the same time. Choose the software of your preference but not both.
