### ISSUE TITLE
secondary taskbar does not want to relocate

### ISSUE THREAD

**Issue by Poellebob** [valinet/ExplorerPatcher#4027]
on win 11 24H2 os build 26.100.2605
the second task bar is at the bottom always but i set it to be at the top
![Skærmbillede 2024-12-12 154139](https://github.com/user-attachments/assets/a6419a04-c971-414c-93b8-1ab0a685ff9b)
![Skærmbillede 2024-12-12 154306](https://github.com/user-attachments/assets/52a679b7-4dbc-4cfe-8531-e48ad0ddb593)

**Comment by Amrsatrio** [comment]
Can't you unlock the taskbar and drag it? I have no plans on fixing the dropdown there.
