### ISSUE TITLE
Windows version 24H2 wont install due to exploer patcher

### ISSUE THREAD

**Issue by fidorulz** [valinet/ExplorerPatcher#4032]
So been using explorer patcher for a while and suddenly windows is refusing to install updates because of the app

here is a screenshot of the error

any ideas?
![Untitled](https://github.com/user-attachments/assets/edf40a14-c305-400e-ab33-3e6437479434)

**Comment by Ramessu** [comment]
I just encountered the same issue with the same notification while trying to install the same Windows Update.

**Comment by fidorulz** [comment]
Its broken completely now. I uninstalled the app in order to install the update and windows now wont allow the option to install it at all

**Comment by Ramessu** [comment]
Sorry to hear that. We'll have to wait for an update if that's even possible now. I backed out of the Windows Update and will wait an update to ExplorerPatcher before I attempt anything.

**Comment by lsd-techno** [comment]
I use installer version 22621.3880.66.6 on amd64 platform, everything went well, then update it to current version. Then reboot. Until reboot task bar wont fix on side after EP restart.

There is small issue in full screen start mode, transparency looks like too much. But that is still better than W11 start butt.

**Comment by TCHarp01** [comment]
> Its broken completely now. I uninstalled the app in order to install the update and windows now wont allow the option to install it at all

I did the same thing, and now, without my quick launch menu, I am getting more and more pissed off at Windows11 for this pure bullshit they're making me use.  I wonder why anyone would think this crap was worth forcing on everyone?

**Comment by Amrsatrio** [comment]
Why does anyone not know that EP should be uninstalled first before starting the update to 24H2. Hmph.

**Comment by TCHarp01** [comment]
I am just angry because MS seems to have built blocks into this new version of Win11.  From what I have been able to find, they have some special hate for Explorer Patcher.  Not because it doesn't work, but because if undoes the "forced into Windows new garbage" thing.

**Comment by Amrsatrio** [comment]
I am too. Then the users must actively participate in fighting them. One of them is by getting rid of the blocks or finding their own ways around it.

**Comment by Amrsatrio** [comment]
@fidorulz Please make sure that C:\Program Files\ExplorerPatcher and %APPDATA%\ExplorerPatcher do not exist. Then restart your PC, and try to run the update again.

**Comment by TCHarp01** [comment]
My box has completed the 24H2 upgrade.  If I run ep_setup.exe that I downloaded in May of 2013, will it pick up the latest version of EP to install?  Sorry for redundant questions, perhaps.  I am an old man and stopped writing code back in the early 1990s.

**Comment by TCHarp01** [comment]
> My box has completed the 24H2 upgrade. If I run ep_setup.exe that I downloaded in May of 2013, will it pick up the latest version of EP to install? Sorry for redundant questions, perhaps. I am an old man and stopped writing code back in the early 1990s.
Well, Win11 shut that down before it even got started.
![Untitled](https://github.com/user-attachments/assets/efc4a670-1e49-4ad8-8186-b6dee2bec34e)

**Comment by pyrates999** [comment]
> My box has completed the 24H2 upgrade. If I run ep_setup.exe that I downloaded in May of 2013, will it pick up the latest version of EP to install? Sorry for redundant questions, perhaps. I am an old man and stopped writing code back in the early 1990s.

No.  Download the newest EP from here: https://github.com/valinet/ExplorerPatcher/releases
