### ISSUE TITLE
anyone experienced settings, display, graphics crashes

### ISSUE THREAD

**Issue by none3** [valinet/ExplorerPatcher#4034]
![image](https://github.com/user-attachments/assets/265683f8-3655-4bcd-8982-6ccfa45a68c1)

It loops for few seconds and closes itself.. sometimes randomly didn't crash, not sure if it's related to ep..
os: 26100.2314
ep: 22621.4317.67.1

settings, same as before
![image](https://github.com/user-attachments/assets/5534b8e3-e8f8-4f0f-a05e-f9ce05da3e6c)
![image](https://github.com/user-attachments/assets/f24e66f5-9698-48fa-8497-f91a15208801)

**Comment by pyrates999** [comment]
open up windows event viewer or computer management
go to Event Viewer and go to Windows Logs -> Application

Check in EP properties application that **register as shell extension** is not ticked. So in EP properties application, click on **file explorer**, untick **register as shell extension** and click **restart file explorer** in the bottom left corner.

Here's why not to enable it: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by none3** [comment]
- System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-12-15T00:13:29.7400283Z 
 
   EventRecordID 11102 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  26548 
   [ ThreadID]  26552 
 
   Channel Application 
 
   Computer DESKTOP-N7E4QFM 
 
  - Security 

   [ UserID]  S-1-5-21-3632296243-2000527971-3966054565-1001 
 

- EventData 

  AppName SystemSettings.exe 
  AppVersion 10.0.26100.2454 
  AppTimeStamp fe7803c7 
  ModuleName unknown 
  ModuleVersion 0.0.0.0 
  ModuleTimeStamp 00000000 
  ExceptionCode c0000409 
  FaultingOffset 00007ffdce3a328f 
  ProcessId 0x860 
  ProcessCreationTime 0x1db4e86268b75de 
  AppPath C:\Windows\ImmersiveControlPanel\SystemSettings.exe 
  ModulePath unknown 
  IntegratorReportId 5cd77b1d-58a5-4087-ab27-f011721e7931 
  PackageFullName windows.immersivecontrolpanel_10.0.8.1000_neutral_neutral_cw5n1h2txyewy 
  PackageRelativeAppId microsoft.windows.immersivecontrolpanel 


Repeated error

- System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-12-15T00:16:03.3841945Z 
 
   EventRecordID 11107 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  15092 
   [ ThreadID]  12232 
 
   Channel Application 
 
   Computer DESKTOP-N7E4QFM 
 
  - Security 

   [ UserID]  S-1-5-21-3632296243-2000527971-3966054565-1001 
 

- EventData 

  AppName SystemSettings.exe 
  AppVersion 10.0.26100.2454 
  AppTimeStamp fe7803c7 
  ModuleName ntdll.dll 
  ModuleVersion 10.0.26100.2454 
  ModuleTimeStamp 7cb6b6a8 
  ExceptionCode c0000374 
  FaultingOffset 00000000000881f5 
  ProcessId 0x2d08 
  ProcessCreationTime 0x1db4e8635c31ecd 
  AppPath C:\Windows\ImmersiveControlPanel\SystemSettings.exe 
  ModulePath C:\WINDOWS\SYSTEM32\ntdll.dll 
  IntegratorReportId 64c4e3ba-0223-4d2f-b8bf-33d96b7ccdae 
  PackageFullName windows.immersivecontrolpanel_10.0.8.1000_neutral_neutral_cw5n1h2txyewy 
  PackageRelativeAppId microsoft.windows.immersivecontrolpanel 

settings in ep already crossed "registered as shell extension" as in previous closed post
![image](https://github.com/user-attachments/assets/7524a924-d95d-489e-97b5-f41813e1fb22)

**Comment by pyrates999** [comment]
In EP Properties application, go to File Explorer and change Control Interface to Windows 7 Command Bar.  Then click on Restart File Explorer.

**Comment by none3** [comment]
changed to 
![image](https://github.com/user-attachments/assets/cb3446da-9772-4b66-8ff6-2deb5e33c911)

Still crashes randomly
- System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-12-15T03:24:22.7683153Z 
 
   EventRecordID 4414 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  19132 
   [ ThreadID]  5460 
 
   Channel Application 
 
   Computer DESKTOP-KRNLT6R 
 
  - Security 

   [ UserID]  S-1-5-21-2445277980-3934193519-1514002110-1001 
 

- EventData 

  AppName SystemSettings.exe 
  AppVersion 10.0.26100.2454 
  AppTimeStamp fe7803c7 
  ModuleName ntdll.dll 
  ModuleVersion 10.0.26100.2454 
  ModuleTimeStamp 7cb6b6a8 
  ExceptionCode c0000374 
  FaultingOffset 00000000000881f5 
  ProcessId 0x266c 
  ProcessCreationTime 0x1db4ea0acf4789e 
  AppPath C:\Windows\ImmersiveControlPanel\SystemSettings.exe 
  ModulePath C:\WINDOWS\SYSTEM32\ntdll.dll 
  IntegratorReportId 9a3297b1-b66b-4c39-a819-c618d7c2bdab 
  PackageFullName windows.immersivecontrolpanel_10.0.8.1000_neutral_neutral_cw5n1h2txyewy 
  PackageRelativeAppId microsoft.windows.immersivecontrolpanel

**Comment by Amrsatrio** [comment]
Uninstall EP, restart your PC, and see if the problem persists.

**Comment by none3** [comment]
Tried it, 
1. Uninstall EP completely and make a restart.
2. After restart, delete all EP registry keys : HKEY_CURRENT_USER\Software\ExplorerPatcher and HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher
3. Make another restart.
4. Install EP again.
5. Wait for Symbols to be downloaded.
6. After symbols notification, make one last restart.

Still crashes

**Comment by pyrates999** [comment]
If you uninstall EP, and reboot, does the crash still happen?

**Comment by none3** [comment]
> If you uninstall EP, and reboot, does the crash still happen?

It still crashes, so it's not ep problem.....

**Comment by pyrates999** [comment]
You may need to repair your windows install.  Please run the following in an elevated command prompt (right click on command prompt icon and select run as administrator) or elevated powershell (right click on powershell icon and select run as administrator):

```
chkdsk C:
```

If it tells you there are errors, then run this:

```
chkdsk C: /F
```

Reboot to run it on boot.  Keep running that command until it reports no errors.  Then run this to repair windows:

```
sfc /scannow
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /checkhealth
dism /online /cleanup-image /analyzecomponentstore
dism /online /cleanup-image /startcomponentcleanup
```

Then reboot your computer.

**Comment by none3** [comment]
C:\Users\Power Rangers>chkdsk c:
The type of the file system is NTFS.
Volume label is Windows 11.

WARNING!  /F parameter not specified.
Running CHKDSK in read-only mode.

Stage 1: Examining basic file system structure ...
  1498112 file records processed.
File verification completed.
 Phase duration (File record verification): 15.39 seconds.
  15846 large file records processed.
 Phase duration (Orphan file record recovery): 4.63 milliseconds.
  0 bad file records processed.
 Phase duration (Bad file record checking): 0.17 milliseconds.

Stage 2: Examining file name linkage ...
  284 reparse records processed.
  1787016 index entries processed.
Index verification completed.
 Phase duration (Index verification): 35.19 seconds.
  0 unindexed files scanned.
 Phase duration (Orphan reconnection): 6.55 seconds.
  0 unindexed files recovered to lost and found.
 Phase duration (Orphan recovery to lost and found): 0.54 milliseconds.
  284 reparse records processed.
 Phase duration (Reparse point and Object ID verification): 4.84 milliseconds.

Stage 3: Examining security descriptors ...
Security descriptor verification completed.
 Phase duration (Security descriptor verification): 86.18 milliseconds.
  144453 data files processed.
 Phase duration (Data attribute verification): 0.22 milliseconds.
CHKDSK is verifying Usn Journal...
  34009856 USN bytes processed.
Usn Journal verification completed.
 Phase duration (USN journal verification): 222.30 milliseconds.

Windows has scanned the file system and found no problems.
No further action is required.

 480376831 KB total disk space.
 143040220 KB in 910747 files.
    472812 KB in 144454 indexes.
         0 KB in bad sectors.
   1619619 KB in use by the system.
     65536 KB occupied by the log file.
 335244180 KB available on disk.

      4096 bytes in each allocation unit.
 120094207 total allocation units on disk.
  83811045 allocation units available on disk.
Total duration: 57.46 seconds (57464 ms).

C:\Users\Power Rangers>sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection did not find any integrity violations.

C:\Users\Power Rangers>dism /online /cleanup-image /scanhealth

Deployment Image Servicing and Management tool
Version: 10.0.26100.1150

Image Version: 10.0.26100.2605

[==========================100.0%==========================] No component store corruption detected.
The operation completed successfully.


No errors, do you still want to run "dism /online /cleanup-image /restorehealth"???

**Comment by pyrates999** [comment]
Yes, run all the commands please.

**Comment by none3** [comment]
C:\Users\Power Rangers>dism /online /cleanup-image /restorehealth

Deployment Image Servicing and Management tool
Version: 10.0.26100.1150

Image Version: 10.0.26100.2605

[==========================100.0%==========================] The restore operation completed successfully.
The operation completed successfully.

C:\Users\Power Rangers>dism /online /cleanup-image /checkhealth

Deployment Image Servicing and Management tool
Version: 10.0.26100.1150

Image Version: 10.0.26100.2605

No component store corruption detected.
The operation completed successfully.

C:\Users\Power Rangers>dism /online /cleanup-image /analyzecomponentstore

Deployment Image Servicing and Management tool
Version: 10.0.26100.1150

Image Version: 10.0.26100.2605

[==========================100.0%==========================]

Component Store (WinSxS) information:

Windows Explorer Reported Size of Component Store : 10.67 GB

Actual Size of Component Store : 10.40 GB

    Shared with Windows : 7.78 GB
    Backups and Disabled Features : 2.45 GB
    Cache and Temporary Data : 165.82 MB

Date of Last Cleanup : 2024-12-16 20:24:30

Number of Reclaimable Packages : 2
Component Store Cleanup Recommended : Yes

The operation completed successfully.

C:\Users\Power Rangers>dism /online /cleanup-image /startcomponentcleanup

Deployment Image Servicing and Management tool
Version: 10.0.26100.1150

Image Version: 10.0.26100.2605

[===========================70.0%========                  ]
The operation completed successfully.

Completed

Sometimes random crashes still occur...

**Comment by pyrates999** [comment]
then run this until it reports no errors:
`
sfc /scannow
`
Then reboot your computer.

**Comment by none3** [comment]
C:\Users\Power Rangers>sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection did not find any integrity violations.

reboot after posting

**Comment by pyrates999** [comment]
sorry, I didn't see that the last dism command didn't get to 100%.  Please run this again:
```
dism /online /cleanup-image /startcomponentcleanup
```

**Comment by none3** [comment]
C:\Users\Power Rangers>dism /online /cleanup-image /startcomponentcleanup

Deployment Image Servicing and Management tool
Version: 10.0.26100.1150

Image Version: 10.0.26100.2605

[===========================70.0%========                  ]
The operation completed successfully.

yeah no idea why it stopped at 70% and said completed successfully.

**Comment by none3** [comment]
I'll do that later probably towards weekend, need more time for the process as it may take hours

**Comment by Amrsatrio** [comment]
I suggest updating your display drivers first before doing anything else. Also, closing this issue since this is not an EP issue.

**Comment by pyrates999** [comment]
Yes, make sure the iso you download is for 24h2 of windows 11.
