### ISSUE TITLE
Why cant i remove the icons?

### ISSUE THREAD

**Issue by AlexLovesBobbie** [valinet/ExplorerPatcher#4038]
I had these icons for months but decided to completely remove and move icons, but somehow, when i right click, it says "Add to start" even though its already added?

![bbb](https://github.com/user-attachments/assets/a60e8312-afcc-4c96-b36b-0faf13a193b0)

Is there maybe a way to completely reset the start menu?

**Comment by pyrates999** [comment]
You can discuss windows 10 start menu related issues here: https://github.com/valinet/ExplorerPatcher/discussions/1679

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3984
