### ISSUE TITLE
关于任务栏处右键菜单About the right-click menu at the taskbar

### ISSUE THREAD

**Issue by 536143095** [valinet/ExplorerPatcher#4040]
![{07073DF2-EED6-480A-B4D8-FF65AB7C051C}](https://github.com/user-attachments/assets/8e7f1d79-d2ed-4183-9e3d-3e13499714a4)
上图中使用了windows11样式但右键菜单依然是windows10样式（没有云母效果），但windows标上右键菜单是正常的(如下图）
The windows 11 style is used in the above figure, but the context menu is still windows 10 style (no mica effect), but the context menu on windows is normal

**Comment by Amrsatrio** [comment]
![image](https://github.com/user-attachments/assets/d5657902-4f9d-4a74-a5de-07ba309f5a3b)
