### ISSUE TITLE
Can't uninstall because file has a 'virus'

### ISSUE THREAD

**Issue by englishtb** [valinet/ExplorerPatcher#4041]
I installed EP ages ago and forgot about and want to get rid of it now as it keeps causing me issues like I cant update my PC, explorer crashes after like 10 seconds etc. Anyway I have been having a myriad of issues but this is what I am getting now after some troubleshooting. 
![yf](https://github.com/user-attachments/assets/21847d76-caff-4cf4-b37a-3e013afb3398)
It says there is some virus. I really cant get rid of it can anyone guide me on what to do itll be greatly appreciated. Also I need a simplistic guide Im not that tech savvy or whatever I just downloaded this cuz I like windows 10s look more.

**Comment by englishtb** [comment]
Also I tried uninstalling in settings and control panel. 
And I tried deleting the file. It still came back and I had to redownload the setup

**Comment by pyrates999** [comment]
See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active, which means you need to add those files and directories to be excluded in your antivirus program.

**Comment by Amrsatrio** [comment]
Follow the instructions to add exclusions. After adding the exclusions, you can uninstall via Installed apps.

**Comment by Amrsatrio** [comment]
> explorer crashes after like 10 seconds etc

It would be appreciated if you can try EP again one more time, but this time updating to version 67.1 that can be downloaded through the link pointed by @pyrates999 above. See if it still crashes. If it still crashes, and if you don't mind, we can work together towards fixing the crash. On my 22H2 and 24H2 devices running latest 67.1 and properly configured exclusions, EP works fine without crashes.
