### ISSUE TITLE
When will there be a new version

### ISSUE THREAD

**Issue by shenhaipaopaoa** [valinet/ExplorerPatcher#4044]
When will there be a new version?,It's uncomfortable not to use EP.

**Comment by shenhaipaopaoa** [comment]
"Pin to start" is not working

**Comment by pyrates999** [comment]
Please check here for suggestions in getting pin to start working: https://github.com/valinet/ExplorerPatcher/discussions/1679

**Comment by Amrsatrio** [comment]
I've made the fix but updates in the GitHub's MSVC compiler toolchain prevented ARM64 builds from succeeding for some reason. I need more time to fix it. For now you can compile EP yourself to have pin to start fixed, or join the EP Discord server where I can give you my homemade build of EP with the fix.
