### ISSUE TITLE
taskbar issue

### ISSUE THREAD

**Issue by blecaplol** [valinet/ExplorerPatcher#4047]
when i fullscreen media player or any app or even games the task bar disappear. even writing this post on chrome it disappear.
also how do i make bigger icons? so many things just simply mess up when i didnt touch anything at all

**Comment by Amrsatrio** [comment]
Isn't it intended behavior? Suppose in this screen, a Chrome or Firefox or whatever window you press F11, the window becomes fullscreen, occupying the space where the taskbar is at. Of course the taskbar disappears until you exit fullscreen, alt tab to another window, or press Win+T. I see no behavioral problems at all on 26100.2314 so I'm not sure what your problem is. If you can accurately describe your problem and confirm that the problem does not exist on Windows 11 taskbar, I can try my best to fix the issue.

**Comment by Amrsatrio** [comment]
For bigger icons, do you mean making the icons larger than Windows 10's "large" taskbar that is enabled by default? Or enlarging from small taskbar icons to large taskbar icons? Assuming you want the latter, please try opening the Properties dialog, go to the Taskbar section, and then find make sure this is set to Large.
![image](https://github.com/user-attachments/assets/e155d399-3f54-4a3e-b863-e11cf92965bf)

**Comment by blecaplol** [comment]
thanks the icon has been fix. my main issue is the taskbar below here mark yellow line its a background game. mind u never had issue until today or so.
![g1](https://github.com/user-attachments/assets/3899a9b8-5c87-4904-a53a-7a23ef771dbc)

it can be any program im using and somehow there is invisible taskbar and yuh. hope i explained it clearer

**Comment by Amrsatrio** [comment]
Can you alt tab multiple times until the taskbar shows up? Or spam Win+T? Spamming Win+T should spawn the taskbar no matter what.

**Comment by blecaplol** [comment]
> Can you alt tab multiple times until the taskbar shows up? Or spam Win+T? Spamming Win+T should spawn the taskbar no matter what.

yup it appear but its not permanent. any program i attempt to max screen size still has that invisible taskbar preventing it from doing so.

**Comment by Amrsatrio** [comment]
I don't really understand what you mean. Do you want the taskbar to be always visible on fullscreen apps or...?

**Comment by blecaplol** [comment]
yes, i want the taskbar to always be visible, as it should have always been—maybe not when i am, say, watching a full-screen movie or playing a game. something happened that now causes the taskbar to be invisible in any full-screen app
