### ISSUE TITLE
Build failure and instruction for manual local deployment?

### ISSUE THREAD

**Issue by kgflying** [valinet/ExplorerPatcher#405]
Repro 
1. Download the source.zip
2. Open in VS19.
3. Build the release.

Observed:
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_error.c': No such file or directory
1>sws_RegistryMonitor.c
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_RegistryMonitor.c': No such file or directory
1>sws_vector.c
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_vector.c': No such file or directory
1>sws_window.c
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_window.c': No such file or directory
1>sws_WindowHelpers.c
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_WindowHelpers.c': No such file or directory
1>sws_WindowSwitcher.c
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_WindowSwitcher.c': No such file or directory
1>sws_WindowSwitcherLayout.c
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_WindowSwitcherLayout.c': No such file or directory
1>sws_WindowSwitcherLayoutWindow.c
1>c1 : fatal error C1083: Cannot open source file: '..\libs\sws\SimpleWindowSwitcher\sws_WindowSwitcherLayoutWindow.c': No such file or directory
.
...

May you please finish this doc https://github.com/valinet/ExplorerPatcher/wiki/Compiling? And add some docs about how to manually deploy bits?

Thanks.

**Comment by BraINstinct0** [comment]
For the time being, (I'm not sure if it's up to date but)
1) the previous(longer) Readme file had the instructions [here](https://github.com/valinet/ExplorerPatcher/tree/e167cfdc91240940a03dcfc11ad72158224a5120#compiling).
2) fork the project, open up the workflow file build.yml(.github/workflows/build.yml), and edit secrets.PAT to secrets.GITHUB_TOKEN.
That will compile the source automatically, and make a release of it in your fork.

Note that both are just temporary solutions.

**Comment by BraINstinct0** [comment]
Related to the second solution: #400
