### ISSUE TITLE
Windows Update blocked by ExplorerPatcher

### ISSUE THREAD

**Issue by PhiLhoSoft** [valinet/ExplorerPatcher#4053]
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

ExplorerPatcher Version 22621.4317.67.1

### Repro Windows Versions

Windows 11, version 23H2 22631.4460

### 3rd party tweak software installed

None.

### Describe the bug

Windows Update indicates it cannot proceed to do the update, on a professional laptop (security / update policies set by the enterprise).
I clicked on the button to investigate, and after a long while, a modal appears with "Elements requiring your attention".
"The following elements need your attention to continue the installation…"
"ExplorerPatcher"
"This application might not work because it provoques security or performance issues in Windows. A new version might be available. Check if an update works in this version of Windows."

Note: maybe it is related to the virus detection issues [Issue #3670](https://github.com/valinet/ExplorerPatcher/issues/3670) or [Issue #3228](https://github.com/valinet/ExplorerPatcher/issues/3228) mentioned at the creation of the issue.
Although the software hasn't been explicitly indicated as such by Windows Defender.
If that's so, the main problem is then that I cannot apply the solution (see 2nd screenshot, in an admin PS shell), probably because of the security policy of the enterprise.

I post that here, perhaps there is no solutions, but at least it will make something to search for.

### Expected outcome

Update as usual.

### Actual outcome

Update is blocked.

### Media

![image](https://github.com/user-attachments/assets/fc8c1ef0-9111-4caa-95bc-b640697cfe84)
![image](https://github.com/user-attachments/assets/31e2e989-eb4d-4273-ab6d-ad20eb3f7cc0)

**Comment by 2hug** [comment]
same here

**Comment by Jazzzed** [comment]
> The Properties window says "Windows 10 taskbar is not available in this version of Windows."
> 
> Is it possible to reenable this capability - or have I overlooked something?

That is referencing the native Windows 10 taskbar, which Microsoft removed in 24H2. You will want to select Windows 10 (explorer patcher) from that menu. That is EP’s re-creation of the Windows 10 taskbar.

**Comment by sbn83** [comment]
Thank you, Jazzzed.  I had missed that the top line on the properties was offering me a selection of taskbar styles.  I've now changed it to "Windows 10 (explorer patcher)" but am still having trouble stretching the taskbar height to allow for 2 lines.  Can you help me see what I'm still missing?  I should also mention that the taskbar's right-click menu still isn't showing the Lock option.

Thanks!

**Comment by pyrates999** [comment]
You must uninstall EP before upgrading to windows 11 24h2.

Then before installing EP again:

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active, which means you need to add those files and directories to be excluded in your antivirus program.

---

Then open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

Please see this for more info: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

To resize your taskbar after doing the above, right click on the taskbar and untick **Lock the taskbar**.  Then you can drag the top of it to be 2 lines.  Then right click on the taskbar and tick **Lock the taskbar**.

**Comment by sbn83** [comment]
Thank you for those detailed instructions!  With those additional steps, I was able to get it to work as expected.
