### ISSUE TITLE
Taskbar style: Windows 10(ExplorerPatcher), date in system tray disappear in certain conditions

### ISSUE THREAD

**Issue by jw0785** [valinet/ExplorerPatcher#4056]
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

22621.4317.67.1

### Repro Windows Versions

Edition	Windows 11 Pro
Version	24H2
OS build	26100.2605

### 3rd party tweak software installed

Mactype

### Describe the bug

Date not time disappear in system tray when
1. using small icon
2. top or bottom

Conditions: 
1. Start up
3. Explorer crash

Solution:
1. Manually click "restart file explorer*" in properties
3. Unlock taskbar and move it to other location then back

### Expected outcome

Display date normally

### Actual outcome

Inconsistent

**Comment by Amrsatrio** [comment]
I cannot reproduce your issue. My clock is still visible when I set the size to small or moving the tray to the top.

**Comment by AnarchistBeauty** [comment]
My date and time appear when the taskbar is at the top and the bottom, but only the time shows when it's at the left or right of my screen.

**Comment by Amrsatrio** [comment]
Date on small icon disappears on small taskbar, that has been the way since the taskbar was born in 1995. It's not a bug.

@AnarchistBeauty Resize the taskbar to be a bit bigger.
