### ISSUE TITLE
Explorer Patcher Setup Not Running Properly But Upon Restart It Works + Explorer Patcher Not Uninstalling At All

### ISSUE THREAD

**Issue by Acheronreal** [valinet/ExplorerPatcher#4060]
### Before reporting your issue

- [ ] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [ ] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

Explorer Patcher 22621.4317.67.1 (Latest Version According To Github)

### Repro Windows Versions

![Screenshot 2024-12-21 132908](https://github.com/user-attachments/assets/2d5e90aa-498e-4b5d-a0e6-0eb170168b4b)

### 3rd party tweak software installed

Tried installing Audio Band and EP at the same time as AB requires EP, but that didnt work properly too, uninstalled it

### Describe the bug

1. Installed Audioband, didnt work without EP so I tried installing it with EP
2. EP setup didnt run properly, stating that a "specific module cant be found" (cannot provide a screenshot of the full msg as the screenshot tool stopped working as soon as I ran the setup application) 
3. Restarted the laptop; the taskbar changes to windows 10 despite the setup not running properly
4. Decided that since Audioband didnt work I would uninstall EP as well
5. Tried all of the steps mentioned here: https://github.com/valinet/ExplorerPatcher/discussions/1345, does not work
6. Tried to uninstall from the properties app, does not work, instead breaks my laptop leading to me restarting over and over again
7. Keeps saying that the setup file is not in program files; moved it there, still doesnt work, also says that the dll files dont exist or smth like that (picture attached)

![image](https://github.com/user-attachments/assets/af0c30bf-66ce-45c7-8cd9-d643251ad238)

Upon clicking the button again:
![image](https://github.com/user-attachments/assets/50157c73-8d4a-40cc-88c1-ca76640976fa)

note: moving the setup file to the program files directory seems to revert the output back to the former picture

### Expected outcome

I expect to be able to delete the application

### Actual outcome

Keeps breaking and/or restarting my PC

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.  22631 is not the full build number.  It is in the format of **#.#**.

---

You probably didn't run the powershell script for adding exclusions to it.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges (right click on powershell and select run as administrator).

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active, which means you need to add those files and directories to be excluded in your antivirus program.

---

Check here **C:\Program Files\ExplorerPatcher** for any files with the **.prev** file extension.  Delete the files with the **.prev** file extension.

If you don't have file extensions being shown, open up File Explorer:

1. Go to tools -> Folder Options.
2. OR if you have the ribbon enabled in File Explorer, go to the View tab and click on Options on the right side.
3. In Folder Options, click on the View tab.
4. Untick Hide extensions for known file types.

Then you can delete all the **.prev** files in **C:\Program Files\ExplorerPatcher**.

**Comment by Amrsatrio** [comment]
Use EP 67.1, not any other version. Shift+delete all files in C:\Program Files\ExplorerPatcher. Run the 67.1 setup as admin, and then uninstall again if you wish. Should fix it.
