### ISSUE TITLE
Win11 24H2 not supported?

### ISSUE THREAD

**Issue by proxypunker** [valinet/ExplorerPatcher#4067]
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

Explorer Patcher 22621.4317.67.1

### Repro Windows Versions

Windows 11 24H2 (Build 26100.1742)

### 3rd party tweak software installed

None.

### Describe the bug

Before Win11 Update to 24H2 I have researched and was so happy to find out, that it was supported. But when I install EP after 24H2 Update, it says that it does not run on this version of Windows - WTF?! 
![2024-12-25 07_39_19-Issues · valinet_ExplorerPatcher – Mozilla Firefox](https://github.com/user-attachments/assets/acaf52a3-c89e-4c75-8af9-7aab41479ad9)

### Expected outcome

I expected that EP runs in 24H2 and let me move the taskbar to the right side.

### Actual outcome

It does not work.

**Comment by ImSwordQueen** [comment]
The windows 10 taskbar isn't supported in 24H2. You need to use "Windows 10 (ExplorerPatcher)" instead which is a [custom reimplementation of the 10 taskbar](https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation)

**Comment by proxypunker** [comment]
> The windows 10 taskbar isn't supported in 24H2. You need to use "Windows 10 (ExplorerPatcher)" instead which is a [custom reimplementation of the 10 taskbar](https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation)

Ah, thank you so much! I just had to switch the style to "Windows 10 (ExplorerPatcher". DUH! I'm sorry, I'm a dev by myself but I'm sure many ppl will fall for this. ^^ 
![2024-12-25 12_05_31-Eigenschaften](https://github.com/user-attachments/assets/ec121d37-1ad9-4074-bc8a-461a86719392)

**Comment by achernyakevich** [comment]
@proxypunker As soon as solution worked for you could you close the issue so other users will treat it as really working. :)
