### ISSUE TITLE
Translation problem: Taskbar right-click menu

### ISSUE THREAD

**Issue by LuLuLuOfficial** [valinet/ExplorerPatcher#4068]
### Before reporting your issue

- [x] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [x] I do not have "register as shell extension" enabled
- [ ] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

22621.4317.67.1

### Repro Windows Versions

Windows 11 24H2 26100.2033

### 3rd party tweak software installed

None

### Describe the bug

The taskbar right-click menu is not fully Chinese(Language -> Chinese Simplified)

### Expected outcome

Options are displayed as Chinese text

### Actual outcome

Most of the options are displayed in English text

### Media

![屏幕截图 2024-12-26 095500](https://github.com/user-attachments/assets/94772ab5-eea7-4be9-bfc0-8d0f3a99e17b)

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3519

please close this.

**Comment by LuLuLuOfficial** [comment]
Ok, thanks for your reply
