### ISSUE TITLE
Cannot pin or unpin start menu tiles with Windows 10 start menu

### ISSUE THREAD

**Issue by that1sysadmin** [valinet/ExplorerPatcher#4074]
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

ExplorerPatcher 22621.4317.67.1

### Repro Windows Versions

Windows 11 version 24H2, build 26100.2605, x64

### 3rd party tweak software installed

Nilesoft Shell (not in use)

### Describe the bug

1. Install ExplorerPatcher (of course)
2. Set start menu to Windows 10
3. Right click any app and click pin to start
4. Right click new tile and click unpin from start

### Expected outcome

The app should be pinned to the right-hand side of the start menu and you should be able to unpin the tile from the start menu.

### Actual outcome

The app does not pin anywhere to start, and when dragging the icon over from the left-hand side of the start menu, you cannot unpin the tile.

### Media

https://github.com/user-attachments/assets/a906b354-61a2-4315-aae1-f828de71e309

**Comment by ShaunV2** [comment]
Already reported here https://github.com/valinet/ExplorerPatcher/issues/3984 you should check other issues posted before making a new thread to avoid duplicate posts.

**Comment by that1sysadmin** [comment]
> Already reported here #3984 you should check other issues posted before making a new thread to avoid duplicate posts.

Alright, my mistake, I don't speak Chinese.
