### ISSUE TITLE
Functional Windows 10 network flyout need to click twice

### ISSUE THREAD

**Issue by f242** [valinet/ExplorerPatcher#410]
i need to click twice (not dobleclick) to show flyout
windows 10 volume flyout works fine from first click

i can reproduce
click on volume then click on network

ver 22000.318.38.0
win11 22000.346

**Comment by valinet** [comment]
Fixed in the latest build. Mitigated the issue at least. The flyouts themselves may be buggy. It's not my fault, I just enable them after a long journey. Read some technical details here: https://valinet.ro/2021/11/18/Functional-Windows-10-flyouts-on-Windows-11.html
