### ISSUE TITLE
Multiplied releases

### ISSUE THREAD

**Issue by jed84** [valinet/ExplorerPatcher#411]
Is there a specific reason why are we getting multiple of the same (similar?) releases within minutes?
Just today we have got 22000.318.38.0, 22000.318.38.1 and 22000.318.38.2 and this is happening most of the time when there is a new release.

I appreciate the new features and the hard work of the dev.

I just wonder if there is a specific reason why releases are getting multiplied?

**Comment by valinet** [comment]
First of all, please, issues is for issues. Is this an issue? I don't think so. Then post in discussions, please.

Second of all, how should I push builds then? Delay new features for a few hours just so, or how? it just happened that I implemented something, and then something else, so naturally I released that as well. Builds are continuously generated for releases, which just happen sometime one after the other in quick succession. Reason? Idk, personal inspiration, hard work, patience, maybe. I usually pack multiple things together, but sometimes it just happens I discover something after pushing a release. That's all.
