### ISSUE TITLE
Run dialog (Win+R) does not maintain history

### ISSUE THREAD

**Issue by extesy** [valinet/ExplorerPatcher#417]
When I execute some command using Win+R dialog, it used to have a history of past commands on Win10 but with 
ExplorerPatcher it's always empty. It even has a dropdown control for showing this history so I guess it's some bug.

**Comment by plofhaan** [comment]
I don't have this bug. Running on Windows 11 official build 22000.318 and using Open-Shell (latest).

**Comment by valinet** [comment]
No, it’s not a bug, it works for me as well, but instead of investigating the root cause, it is always easier to blame this app.
