### ISSUE TITLE
Taskbar is black and all messed up

### ISSUE THREAD

**Issue by ParanormalBanana** [valinet/ExplorerPatcher#420]
When I tried installing the latest version of ep, the taskbar went black and everything is messed up and unuseable, except for the start menu. I can't use right click on the taskbar, and right click on start menu doesn't show "properties" so it is impossible to access GUI and see if settings are causing the issue. 
I had to uninstall ep, I can't fix it.

**Comment by BraINstinct0** [comment]
Is it that Taskbar is not showing, or shown but working improperly? The former would mean that explorer.exe is not (re)started, and the latter would mean a definite bug by itself.
Could use some screenshots or details here, though.

**Comment by valinet** [comment]
Yeah, can’t do much based on that description… GUI can be accessed by running rundll32 C:\Windows\dxgi.dll,ZZGUI

**Comment by ParanormalBanana** [comment]
How can I provide diagnostics to you? I can take a screenshot of the issue, but it won't do ware metter than just explaining
