### ISSUE TITLE
System Slowed Down

### ISSUE THREAD

**Issue by usernz** [valinet/ExplorerPatcher#421]
Hi,  

Build 22000.318.38.2 slowed my whole system down - Windows 11 Build 22000.318. Going back to build 22000.318.37.5 fixed the issue.

**Comment by valinet** [comment]
It’s probably something else. Have you seen the changelog and the actual code that changed? There are a few additions in isolated areas, nothing core has changed. Plus, how can I investigated based on your description? “Slowed my whole system down” - what does that mean? This app does nothing continuously in the background.
