### ISSUE TITLE
If newer pre-release installed ep prompts for "newer version" which is release version which is older.

### ISSUE THREAD

**Issue by PGomersall** [valinet/ExplorerPatcher#428]
Just installed the pre-release 22000.318.38.4 and after install ep thinks 22000.318.38.2 is newer - getting the toast flyout.

**Comment by valinet** [comment]
Updater checks among releases only. It sees the version is different, it notifies about an update (a different release available on the remote server). Works as expected.

**Comment by PGomersall** [comment]
I understand the reasoning.
However, that just means if you have pre-release you then have to manually check your releases page to see if there is a newer release version than the installed pre-release. Maybe some thought needed here to better inform all users?
Maybe you could add the version number of the release that is available to the update toast; that may make it clearer. I'll let you think on it.
Again, regards for the great work.

**Comment by valinet** [comment]
For the moment, it's fine the way it is. Thx.

**Comment by Galixte** [comment]
https://github.com/valinet/ExplorerPatcher/releases/tag/22000.318.38.9_65aa7a7 fixes this.
