### ISSUE TITLE
add support 22000.348 plz

### ISSUE THREAD

**Issue by f242** [valinet/ExplorerPatcher#429]
add support 22000.348 plz
each time you need manually adaptation for new build? and no way to automate it?

**Comment by f242** [comment]
new dll
[pack.zip](https://github.com/valinet/ExplorerPatcher/files/7572648/pack.zip)

**Comment by valinet** [comment]
I won't provide fixes for this anymore, it's robotic work. Wait for Microsoft to push the symbols or just use the old version. They anyway don't add anything new or useful, why does everyone have to run some random different build...? Years old bugs are ignored, what do you expect when upgrading from 346 to 348 anyway...?

> each time you need manually adaptation for new build? and no way to automate it?
Read some explanations here: https://github.com/valinet/ExplorerPatcher/issues/129. I won't repeat myself.

**Comment by valinet** [comment]
I even think you can use the files from 346 in place of 348. Idk, try it.

**Comment by RobertSpir** [comment]
yep, updated hashes in source with 348 versions and everything works

**Comment by valinet** [comment]
Blindly replacing hashes is not a production level solution. Did you confirm that the functions for which symbols are needed are still at those offsets? Or at least, does WinX, skinned menus and Start hooks work? Even then, I can’t release an update to the general public with hardcoded addresses that “seem” to work. They have to be verified manually against the binary.
