### ISSUE TITLE
Feature requests: updated Windows orb + setting tasbkar background + aligning the taskbar to the centre (wth the orb)

### ISSUE THREAD

**Issue by jed84** [valinet/ExplorerPatcher#43]
Hello,
First thing - great job for improving the broken Windows 11 by restoring the old good taskbar!
Thank you!

I am also having a few feature requests. Would be great to see the following in ExplorerPatcher:
1. to add an updated Windows orb so it matches Windows 11 logo (and perhaps a feature that allows setting your own orb)
2. to allow the user to set their prefered background of the taskbar (so we don't have to rely on TaskbarX)
3, to  align the taskbar (including the orb) to the centre (so once again we don't have to rely on TaskbarX)

The first feature would make the toolbar feel more like Win11 toolbar.
The last two are more about improving the way the taskbar works. Currently, if Windows Explorer crashes, we have to restart not only explorer.exe, but also TaskbarX. Sadly TaskbarX seems to be very buggy on Win11 and I believe it would be beneficial to not rely on the software.

**Comment by valinet** [comment]
They will eventually come in a future update, that's the plan, they are already on my to-do list. But it will take a while, the project goes through a reorganization and everything is merged together. Indeed, I don't want to rely on TaskbarX as end goal as well, for the same reasons you listed, so as I said, it will be in here at some point, but it just is going to take a little longer. About #1, I am not working on anything regarding it at the moment, but I will take it into consideration, sure.

Just a request: there is a "feature requests" thread, please use that in the future for these kind of posts. I know it may seem like the message gets lost in there, but it does not, I read through it. It too will eventually be reorganized into something more proper, but I am just a single person maintaining all of this so I can't do all of these instantly.

Thank you.
