### ISSUE TITLE
does not work with Windows 11 build 22000.348

### ISSUE THREAD

**Issue by onemen** [valinet/ExplorerPatcher#445]
After updating to build 22000.348 ExplorerPatcher stop working

![explorerpatcher](https://user-images.githubusercontent.com/3650909/142993914-8e46244b-237a-4230-9307-129bde207c46.png)

are there any symbols files in need to install ?

**Comment by valinet** [comment]
There is already an issue about this, why do you feel like creating duplicates?

https://github.com/valinet/ExplorerPatcher/issues/440
