### ISSUE TITLE
Failed to open Win 10 Network flyout

### ISSUE THREAD

**Issue by haytcb** [valinet/ExplorerPatcher#467]
When clicking the network icon, the flyout cannot be shown, -only the shadow appears as shown below.
![epn](https://user-images.githubusercontent.com/57446162/143375350-ed91b826-1914-4f0b-b4fa-6958423a42e7.jpg)

ExplorerPatcher: 22000.348.39.1
Windows: Windows 11 Home Edition, ver 22000.348

Thanks.

**Comment by valinet** [comment]
I tested it in a clean VM:

![image](https://user-images.githubusercontent.com/6503598/143441959-0bb5a968-3f32-4338-9ea0-6080c9b4ba8d.png)

Idk, the way to enable it is pretty convoluted anyway, it seems to work on my computer where I have WiFi as well, but yeah, that's as much variety as I can get. As far as the patching is concerned, the involved files should be identical (`C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\Windows.UI.QuickActions.dll` with SHA256: `e6fdb089da1330d3dc1cad526db84f4450668e29486df7a656d87d1d0383cff4`) so the patch should work identical. If it fails for whatever reason on your PC, if that's the case, then it's something else anyway. The patch is described here: https://valinet.ro/2021/11/18/Functional-Windows-10-flyouts-on-Windows-11.html. Try to follow on the footsteps there and troubleshoot it, other than that, idk, use one of the other options provided by EP.

Thanks
