### ISSUE TITLE
Problem with Close button look in Explorer Thumbnail in Win11.

### ISSUE THREAD

**Issue by vkp2001** [valinet/ExplorerPatcher#468]
There is a Issue with Close button as corners are not rounded. It behave like Win10 look. This Issue is coming in some PC. I have 2 PC's but it was coming only in my low-end PC.  Please fix this issue regarding look & feel of Window 11.

![Screenshot 2021-11-25 090142](https://user-images.githubusercontent.com/79749815/143375414-64f00071-c0b0-411b-a860-cf97aa1a1c8d.png)

ExplorerPatcher Ver. : 22000.348.39.1
Windows Ver. I'm using : 22000.318 Professional

**Comment by valinet** [comment]
Works fine for me. Pardon, looks fine for me:

![image](https://user-images.githubusercontent.com/6503598/143439400-c6bab8d7-678d-4acb-8ef6-08386de164dc.png)

This program enables the taskbar from Windows 10, with whatever looks it happened to have from Windows 10. If some parts of it are skinned for free by some global changes in Windows 11 to look like Windows 11, then those look like Windows 11, other than that, everything else is untouched. I like the look. Or I like to have the choice. StartAllBack rounds off everything and comes with some more "customizations" if you are more interested in that kind of stuff.

I don't consider this an issue, hence won't fix.

**Comment by vkp2001** [comment]
I'm using ExplorerPatcher and StartAllBack together. It is working fine in ExporerPatcher ver. : 22000.318.38.5 but not in latest build.
