### ISSUE TITLE
Black Bar after Unistall

### ISSUE THREAD

**Issue by Mohamet92** [valinet/ExplorerPatcher#469]
Hello! Afrer unistall the app i have black screen as you can see to the attach image!

![1](https://user-images.githubusercontent.com/38325608/143392735-363cfa8a-e06b-43e7-b3ce-de6c4960f534.png)

Any help about this ?

**Comment by Anixx** [comment]
Did y read README? Before uninstalling you should put the taskbar into horizontal position, because the Win11 taskbar does not support vertical position.

**Comment by Anixx** [comment]
Maybe vilanet could add to the functionality of the /uninstall switch the placement of the taskbar to the bottom automatically?

**Comment by valinet** [comment]
This shouldn’t happen on the latest versions. Windows 10 taskbar positioning is kept separate now (a different registry entry for StuckRects3 when using the Windows 10 taskbar). That’s the way to properly fix this, and it’s been implemented. If it doesn’t work, it’s a problem, but idk, it worked in my testing.

**Comment by valinet** [comment]
Tested this just now on latest release, uninstalled with Windows 10 taskbar to the left, it uninstalled just fine and the Windows 11 taskbar appeared at the bottom. I'd say not a problem with EP. There is actual code that mitigates this and it works: https://github.com/valinet/ExplorerPatcher/blob/493cf276875783da4d96121939daea0bbc86b8bb/ExplorerPatcher/dllmain.c#L4773. Idk, maybe a glitch, maybe something else, can't know for sure. Install again, put it back to the bottom, uninstall and that should be it.

Thanks

**Comment by Mohamet92** [comment]
I make a test now! Is put the bar back to the bottom! I unistall the EP but AGAIN by task bar dissapear! After install it again, then the task bar work fine!

**Comment by valinet** [comment]
So it’s something else or what? If you remove EP, how can it still affect it? Maybe it is some other program, idk… for me, when I uninstall it, it reverts to the Windows 11 taskbar just fine. What can I do anyway without being able to reproduce…? There are too many variables involved anyway.

**Comment by Mohamet92** [comment]
I make a test now! Is put the bar back to the bottom! I unistall the EP but AGAIN by task bar dissapear

**Comment by BraINstinct0** [comment]
Mostly...it arise from not trying to manually restart explorer.exe when anything unexpected happens...
