### ISSUE TITLE
clock/date position

### ISSUE THREAD

**Issue by echivalent** [valinet/ExplorerPatcher#479]
Until updating my windows, all things worked good (windows11, top taskbar, small icons). after update, the area of time/date gets chopped as in this screenshot
![Screenshot 2021-11-26 235631](https://user-images.githubusercontent.com/95106577/143658092-df4150df-b87c-4046-bd09-9b4b14931d1c.png)
.
If i choose windows 10 taskbar, all is good, except that i cannot move it to top.
i updated to latest patcher version, reset to defaults, nothing seems to resolve the situation.
Thank you!

**Comment by valinet** [comment]
Windows 11 taskbar is not made to be used with small icons. It's a well known problem of the Windows 11 taskbar, not much EP can do about it. The Windows 11 taskbar is only supported in its stock configuration, as shipped by Microsoft, small icons and moving it to the top are hacks and prone to breaking, as you just saw.

**Comment by echivalent** [comment]
thank you for the quick response. if i choose windows 10 taskbar(i actually like it more), is there any way to position it to top?

**Comment by valinet** [comment]
Yup, right click it, uncheck Lock all taskbar or Lock taskbar, drag it to top, optionally right click it again and relock it and profit.

**Comment by valinet** [comment]
> thank you for the quick response.
> <<nevermind the question about w10, i am stupid, the taskbar was locked>>

Yeah, no worries, I am glad that you sorted it out, and don’t worry, apparently it’s not that obvious, I get this question often around here.
