### ISSUE TITLE
ExplorerPatcher has effect, similar to UserPreferenceMask, bit 17, regardless of settings

### ISSUE THREAD

**Issue by Anix-x** [valinet/ExplorerPatcher#48]
Various bits of User Preference Mask can be set using UPMCalc utility:
https://www.softpedia.com/get/Tweak/Registry-Tweak/UPMCalc.shtml

The bit 17 has the following effects:

In Windows Classic theme:
Set:
* The borders of pull-down (standard) menus are flat.
* The pull-down menus selection in File Explorer is by color (Win-95 style)

Unset: 
* The borders of the menus are 3D
* The Explorer drop-down menus are selected with bevel (3D effect, Win-98/2000 style)

In Win11 theme:
Set: 
* The selection of drop-down menus in Explorer is rectangular (Win-95 style), while in non-Explorer apps it remains rounded.

Unset:
* The selection of drop-down menus in Explorer is rounded, as in other apps.
* The File Explorer context menus in Win11 have 3D border effect (not fitting well with the theme)

ExplorerPatcher seems to force the effect of bit17 being set, regardless of actual registry value. This disallows the Classic Theme users from having 3D borders in menus.

In Simple Classic Theme program this bit can be unset with 4th button in right column (Make buttons 3D).

Note that changing user preference mask requires re-login to the session to take effect.

**Comment by valinet** [comment]
> 
> ExplorerPatcher seems to force the effect of bit17 being set, regardless of actual registry value. This disallows the Classic Theme users from having 3D borders in menus.

"seems to" is much more different than "does"; does it do it or not?

**Comment by Anix-x** [comment]
It does force the effect. The actual value of the bit remains unchanged.

**Comment by Anix-x** [comment]
Without ExplorerPatcher, the bit 17 as set by UPMCalc or SimpleClassicTheme affects the appearance, with ExplorerPatcher it always behaves as if the bit was set, even if it is unset.
I have no StartAllBack.
The differewnce under Classic theme is indicated above.

Below, the Win11 theme with ExplorerPatcher or bit 11 set:
![image](https://user-images.githubusercontent.com/92230793/136677784-a7286deb-f463-4cd9-b117-eea37ce30547.png)

**Comment by valinet** [comment]
Just as an idea, I don't touch those. So directly, no chance of messing with them. Indirectly, I don't know. Anyway, I will close this for now as it seems to me that it is not an application bug, but feel free to come back and report your findings and if there is indeed an identifiable problem, I will try to fix it. Thanks.
