### ISSUE TITLE
can you make uninstaller please

### ISSUE THREAD

**Issue by antajl** [valinet/ExplorerPatcher#485]
I can't open explorer, control panel or any windows settingsto uninstall it. I can only launch programs with "directory opus". Can you help me?

**Comment by novaeye** [comment]
rename dxgi.dll (in C:\Windows) to dxgi.dll.remove,  and restart

**Comment by valinet** [comment]
ep_setup.exe /uninstall

**Comment by BraINstinct0** [comment]
What is file manager? Isn't that file explorer?

**Comment by antajl** [comment]
> What is file manager? Isn't that file explorer?
directory opus. Explorer didn't work at all.
Novaeye solved my problem

**Comment by valinet** [comment]
I added an option in the latest pre-release (40.4) to rename `ep_setup.exe` to `ep_uninstall.exe` and run that and it will behave directly as the uninstaller.
