### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Noekoe** [valinet/ExplorerPatcher#486]
Hi,

Thanks for your great app!

Looks like your app doesnt work anymore since tonight.

**Comment by BraINstinct0** [comment]
Is it after a windows update?
I didn't get a new update yet, but I'm assuming there might be one.
First try updating Explorerpatcher.

**Comment by BraINstinct0** [comment]
P.S. Usually, apps don't break by itself; it is highly likely that something has changed on your side, which led to ExplorerPatcher breaking.

To investigate further into this issue:
1) Which version of ExplorerPatcher are you using?
2) Which version of Windows are you using(including the build number)
3) By 'ExplorerPatcher has broken', what do you expect it to do, and what is actually happening? e.g. windows 11 taskbar is showing instead of win 10 version, the screen is all just black, etc.
4) Is there anything else that might've changed recently?

**Comment by Noekoe** [comment]
Hi, 

Im using the latest version dowloaded yesterday from Github.
Im using Windows 11 Pro Build 22000.348
Well i used it only to ungroup on the taskbar. That stopped working. Plus i dont see the options wheel in the taskbar anymore. It also got removed from clicking right on the taskbar.

I didnt update Windows, so nothing changed.
I clarify this a bit.
I installed ExplorerPatcher last weekend on my home PC with Windows 11 Home Build 22000.348. I didnt touch it since last weekend. Yesterday i received a new laptop from work where  I installed ExplorerPatcher on. When i got back from the office i opend my laptop and saw it didnt work anymore. So I turned on my PC to check if it was working but it didnt. As stated before I didnt touch my PC since last weekend.

**Comment by BraINstinct0** [comment]
1) First, the 'ungroup' feature only work for the windows 10 taskbar. Make sure if it is set to win10, not win11.
2) Also, if ExplorerPatcher is installed it _should_ show its Options when right-clicking the taskbar... try `rundll32 C:\Windows\dxgi.dll,ZZGUI` and see what happens. This normally directly opens the 'options' gui for ExplorerPatcher, so if it shows but the 'options' is missing then I'd consider it a bug.
3) The most recent Stable version of ExplorerPatcher is 22000.348.39.1. I'm pretty sure you installed the right one, but it still helps to check - it definitely works with 348. 
4) Try Enabling `Advanced` > `Enable Symbol Downloads`, and give it some time to download symbols. Some functions need it to work. (Note that you need internet connection to first let it download symbols. It does work without it, albeit with less function.)

Still I don't think this is a completely expected situation, (in the meanwhile try uninstall-reinstall) Honestly I can't really guess what's happening exactly, as ExplorerPatcher has been quite stable for several days. Any ideas @valinet ?

**Comment by bratskij** [comment]
Thanks for your great app! Im using Windows 11 Pro Build 22000.348, ExplorerPatcher is 22000.348.39.1.

**Comment by valinet** [comment]
Idk...
