### ISSUE TITLE
Tasbar disappears

### ISSUE THREAD

**Issue by BroniSyn** [valinet/ExplorerPatcher#489]
Randomly my taskbar will disappear.
The only way to bring it back is to restart explorer.exe

**Comment by BroniSyn** [comment]
Why was it closed?

**Comment by valinet** [comment]
I cannot confirm this as an issue. I use this app daily, my taskbar sits just fine.

**Comment by BraINstinct0** [comment]
To have it re-opened or get further help, provide a specific, reproducible situation(if you don't know, try taking notes whenever it does, and see what's common.) that crash happens.
Also, at least windows build/EP version/any other possibly interfering programs should be noted.

**Comment by BroniSyn** [comment]
OK. Windows 11 21H2 build 22000.348. EP 22000.348.39.1
It only happens when I use my computer for a while. At first systray icons flash, they disappear but they recover by themselves.
Then, a whole taskbar slides down so I can only see little bit of a Start button. When I click on it the taskbar will recover. But it works only once. When the taskbar slides down again, clcking on that tiny bit of Start button does nothing.
In order to bring the taskbar back I have to restart expolrer.exe

**Comment by BraINstinct0** [comment]
Hmm, same build, same version here. The taskbar sliding down sounds like 'auto-hide' turned on, but the systray icon flashing and taskbar not recovering sounds like Explorer.exe or ExplorerPatcher halting.
Unfortunately, seems like that's not an issue solvable on my level. (I'm not the Dev™️)
If the 'auto-hide' is turned on try disabling it(yes, it uses the same setting from win 11's settings app.). Don't think it will be much helpful, though.
Besides, if you happen to figure out on which situation(like when which program has run) causes it that might be more helpful.

**Comment by BroniSyn** [comment]
Auto hide is definitely not on. The taskbar doesn't disappear completely. It's like hanging by a thread at the bottom of the screen. I can see just a bit of a start button. Next time it happens I'll post a screenshot. Very weird.

**Comment by valinet** [comment]
Yeah, idk, to identify whether it’s a crash, I already provided instructions on how to enable crash dumps. Other than that, really, idk, I can’t envision every scenario and configuration out there.

**Comment by BroniSyn** [comment]
I don't see any instructions how to provide crash dumps.

**Comment by valinet** [comment]
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by BroniSyn** [comment]
OK. I did it. Let's wait for a crash

**Comment by BroniSyn** [comment]
It just happened but I don't see any dmp file from today.
This is how my taskbar looks like after the crash. You can see very tiny bit of Start button i lower left corner.
![SNAG-0003](https://user-images.githubusercontent.com/88322844/144639963-9d1c8663-224c-45e3-b5a7-c85e2ffa7be9.png)

**Comment by valinet** [comment]
If you do not see a dump file and followed the instructions carefully, then it’s not a crash. Anyway, idk what to say about it.

**Comment by BroniSyn** [comment]
Before EP I was using StartAllBack and the very same issue was happening and I have a dmp file for that instance, if it's of any help
[explorer.exe.2540.dmp.zip](https://github.com/valinet/ExplorerPatcher/files/7651077/explorer.exe.2540.dmp.zip)

**Comment by valinet** [comment]
Okay, so it is not an EP problem then... it's something else that's conflicting that both of these apps do not expect. Idk, it's very hard to guess, you have to figure this out yourself.

The dump file you provided shows the crash as indeed originating in StartIsBack's DLL:

![image](https://user-images.githubusercontent.com/6503598/144641425-1273dec7-d4eb-4c4d-8580-daf1648d545d.png)

You can disassemble and decompile that specific version of the DLL look around at that address in order to maybe figure out what was happening. Unfortunately, without symbols, no friendly name for that address is provided, it's just some place in StartIsBack's code, you will have to figure it out mostly from the context what it does.

**Comment by BroniSyn** [comment]
thank you :)

**Comment by valinet** [comment]
> thank you :)

You're welcome. It may be some other app as well that plays around with **something** and both EP and StartAllBack do not account for that because we don't know about it... idk, as I said, I simply don't know.

Btw, dump files can be opened using WinDbg for example. Install that from the Microsoft Store and then double click the file and it will get loaded in there and you can explore it yourself as well.

**Comment by BroniSyn** [comment]
Yes, I just installed WinDbg :)

**Comment by Simplestas** [comment]
This crash on NULL access does not make sense, but I've tried to protect for that in SAB 3.1.5.

**Comment by valinet** [comment]
> This crash on NULL access does not make sense, but I've tried to protect for that in SAB 3.1.5.

What do you mean? Are you the developer of SAB?

**Comment by Simplestas** [comment]
It seems so

**Comment by valinet** [comment]
🤣 Nice to meet you 😀

So, what’s the safeguard? What’s the actual problem, where doesnit happen?

Also, any idea regarding #236? It’s a pretty old and weird bug.

Thanks

**Comment by Simplestas** [comment]
Well, there's no stack below StartAllBackX64, so I'm not sure what is the reason, and safeguards are kinda blind hits (check that allocation does not fail, check that window procedure is not called from another thread).

As for #236, I can't reproduce it. SAB has a number a workarounds to make Notification Area Icons dialog work, but it does not crash for me in described scenario without them.

**Comment by valinet** [comment]
All right, thanks for checking it out. Maybe I figure it out some day 😀

Also, many thanks for your great apps, I learned A LOT off of them. They really are a living knowledge base. Thank you very much for the work that you do.
