### ISSUE TITLE
"Open Start in All apps by default" is inconsistent

### ISSUE THREAD

**Issue by Accelyte** [valinet/ExplorerPatcher#490]
Version 22000.348.39.1, Windows 11 Pro 21H1 22000.348

Happens when repeatedly clicking the start menu button *QUICKLY*:
- first click: opens start menu in All apps
- second click: closes the start menu
- third click: opens the start menu in Pinned/Recommended menu

Consecutive clicks after this close and open the start menu in Pinned/Recommended. Doesn't seem to happen when clicking slowly though.

**Comment by valinet** [comment]
Can we bother searching old issues (and generally reading the single rule written in CAPITAL LETTERS) before opening identical ones?

https://github.com/valinet/ExplorerPatcher/issues/40
