### ISSUE TITLE
White line in Dark Theme

### ISSUE THREAD

**Issue by BoB3R** [valinet/ExplorerPatcher#495]
Hello,

First of all thanks for a great work! I am big fan of "Quick Launch", when I added it via toolbars in dark theme I've got white spacing. Is it something that can be fixed? I've attached screen shot below:
![image](https://user-images.githubusercontent.com/58575145/144472874-f4926fae-bfee-4b4c-b223-bee409e965e9.png)

**Comment by valinet** [comment]
Disable “Show separators between toolbars”. Other than that, not much can be done that I know of at the moment.

**Comment by BoB3R** [comment]
ah sorry didn't saw that one, works like a charm. Thanks!
