### ISSUE TITLE
Taskbar does not stay anchored when moved to another monitor

### ISSUE THREAD

**Issue by AlienXAXS** [valinet/ExplorerPatcher#504]
I have no idea if you're able to fix this one, but I thought I would put in a ticket for it anyways.

If you move the taskbar to another monitor, and either reboot or close and re-start explorer, the task bar will be on the side of the screen where you left it, but only on your primary display.

**Comment by valinet** [comment]
This has been asked a million times by now, there are plenty of old threads discussing this thing. Here's one of them where I give some info about this: https://github.com/valinet/ExplorerPatcher/issues/14#issuecomment-936412362.

tl;dr The fact this worked in Windows 10 was a bug. It was never intended to work. During Windows 11 development, they fixed it and then axed altogether the old taskbar. Main taskbar is meant to stay on primary monitor only. There is a setting in "Advanced" Properties where I tried to mitigate this but I wasn't that successful. Remains an area open for investigation. Dependable workaround is to set the primary monitor the one that you want the main taskbar to sit on.

**Comment by valinet** [comment]
I enabled this behavior in the latest pre-release version.
