### ISSUE TITLE
Can't uninstall ExplorerPatcher

### ISSUE THREAD

**Issue by ShirovoVajco** [valinet/ExplorerPatcher#510]
I wanted to try ExplorerPatcher, so i installed it. But now i want to uninstall it. But when i go to Programs and Features" in Control Panel, or "Apps and features" in the Settings app. It doesn't show the ep_setup.exe /uninstall. So is there another way to uninstall it ?

**Comment by Meyu-Sys** [comment]
how did you do it

**Comment by valinet** [comment]
Rename ep_setup.exe to ep_uninstall.exe and run that.

**Comment by LarsErikOsterud** [comment]
I have a similar problem. But can't delete the files. They are "locked" (in use).
Neither uninstall or new install works (same message). How do I "unlock" them?

**Comment by pyrates999** [comment]
Boot into safe mode to uninstall them.
