### ISSUE TITLE
Enlarge the taskbar size and the icon size

### ISSUE THREAD

**Issue by JGLW** [valinet/ExplorerPatcher#542]
Is there a possibility to enlarge the taskbar size and the icon size as in Windows 10? Or do I use the special registry settings in Windows 11?

**Comment by valinet** [comment]
Have you read this? https://github.com/valinet/ExplorerPatcher/issues/56

**Comment by JGLW** [comment]
I did now. Sorry.

Johan Wouters
________________________________
