### ISSUE TITLE
Windows 10 start menu possible ?

### ISSUE THREAD

**Issue by F3000** [valinet/ExplorerPatcher#544]
Hi , thanks for the great Programm . 

Is it possible for you to add the win10 start menu layout ?

**Comment by valinet** [comment]
Is it so difficult to look a bit around before deciding to post? Don’t get me wrong, it’s the third time I have to repeat this in the last day or so.

Have you read this? https://github.com/valinet/ExplorerPatcher/issues/56

From there, have you searched past discussions? Do you feel like this qualifies as an issue?
