### ISSUE TITLE
!!! README : RULES !!! DO NOT FILE ISSUES !!! USE DISCUSSIONS

### ISSUE THREAD

**Issue by valinet** [valinet/ExplorerPatcher#56]
## [UPDATE: READ THIS](https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems)

Old (but still relevant) post:

THIS SECTION IS INTENDED FOR DEVELOPERS TO TRACK ACTUAL ISSUES, PROBLEMS, BUGS, WORK IN PROGRESS FEATURES OF THE APPLICATION. THE ONLY REASON THIS SECTION IS OPEN TO THE GENERAL PUBLIC IS BECAUSE SOME DESIGN GENIUS AT GITHUB/MICROSOFT DECIDED NOT TO OFFER AN OPTION TO RESTRICT THIS AND [CONSTANTLY IGNORED THE COMMUNITY ASKING THIS FOR YEARS](https://github.com/dear-github/dear-github/issues/293).

DISCUSSIONS: https://github.com/valinet/ExplorerPatcher/discussions

QUESTIONS REGARDING THE FUNCTIONALITY OF THE APP, HOW TO ACHIEVE SOMETHING ETC ARE MORE THAN OK, BUT SHOULD BE POSTED IN THE "DISCUSSIONS" TAB. FROM NOW ON (THE OLD THREADS HERE WERE SIMPLY IGNORED); I WILL SIMPLY CLOSE AND IGNORE ANY NON-ISSUE POSTED HERE.

ALSO, FEATURE REQUESTS AND ENHANCEMENTS DO NOT QUALIFY AS ISSUES AND SHOULD BE SIMILARLY POSTED IN THE "DISCUSSIONS" TAB, WHERE OTHER PEOPLE CAN DISCUSS THEM EASILY, VOTE ON THEM AND WORK TOWARDS A GENERAL RESOLUTION FOR THE PROBLEM. Once a feature request/enhancement is decided on, it may appear here as an issue for the developers to track the implementation.

Some other points:
* Also, please double check that the "issue" you are facing is an actual issue. The documentation is posted there for a reason. PLEASE, take the time to read the documentation and help us improve it if you find it is lacking in some areas (opening an issue for that is fine, but a pull request would be even way better).
* Things are pretty convoluted already in Windows, we do not need to make them even more convoluted. It is HIGHLY RECOMMENDED to disable any other shell extensions, plugins, whatever, test whether the problem happens on a clean slate as well, and only then report the issue. If it does not happen, try to enable other stuff one at a time and see where the conflict may come from.
* Please refrain from opening issues with a 1-line description of the problem. Please describe in detail what is happening, so we can get to solving it more easily. Besides issues tracking on-going implementation features, my goal is to solve most bugs as quickly as possible, as they are disturbing for users. This is only achievable if the issue description is detailed and on-point.
* For simple issues, like fixing the documentation, the README etc, you are highly encouraged to fork the repository, fix the file and make a pull request which we'll review and integrate, so that it is less work to do on our side and things move a bit faster.

Thank you

**Comment by vyrnius** [comment]
may someone help me pls? after updating windows 11 ExplorerPatcher keeps on crashing. reinstalled the newest version already 3x times but nothing helps... 

Windows Build: 22621.2134

**Comment by ChristianGruen** [comment]
A suggestion… You can add a template page for creating new issues:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

After we’ve done that in our own project, the number of unwanted new issues went down a lot.

Thanks for ExplorerPatcher, it’s just great.

**Comment by real-yfprojects** [comment]
Is this still up-to-date? The post over on the discussions page redirects to a link that states issues should be reported as github issue tickets. Where am I expected to report my bug now?

**Comment by dmiller423** [comment]
Looks like they aren't really interested.. I have seen numerous issues closed as #wontfix sadly and this says they simply don't want the issues to be displayed.
