### ISSUE TITLE
Badges don´t work anymore

### ISSUE THREAD

**Issue by alegend2k** [valinet/ExplorerPatcher#570]
hey there,
I got a problem - even badges are set to ON they don´t work anymore when using Explorer Patcher.
I tried StartallBack - and here the batches work when using Win 10 taskbar!
Any clue ? hint ? I want to use explorer patcher....

**Comment by BraINstinct0** [comment]
What do you mean by "badges"?

**Comment by alegend2k** [comment]
small number in app showin how many msgs you got
![image](https://user-images.githubusercontent.com/26001704/146166291-5df60e8a-3d95-4e18-82d2-848235084d30.png)

**Comment by valinet** [comment]
Seems to work just fine for me.

![image](https://user-images.githubusercontent.com/6503598/146174264-8621dbe3-875a-4d81-b83e-6d8a94eff35c.png)
