### ISSUE TITLE
Missing entry in twinui_pcshell_SN definition?

### ISSUE THREAD

**Issue by jdp1024** [valinet/ExplorerPatcher#587]
In `symbols.c`:

```
const char* twinui_pcshell_SN[TWINUI_PCSHELL_SB_CNT] = {
    TWINUI_PCSHELL_SB_0,
    TWINUI_PCSHELL_SB_1,
    TWINUI_PCSHELL_SB_2,
    TWINUI_PCSHELL_SB_3,
    TWINUI_PCSHELL_SB_4,
    TWINUI_PCSHELL_SB_5,
    TWINUI_PCSHELL_SB_6,
    TWINUI_PCSHELL_SB_7
};
```

`TWINUI_PCSHELL_SB_8` is not there. Is it deliberated?

Currently the function offset for `winrt::Windows::Internal::Shell::implementation::MeetAndChatManager::OnMessage` is hardcoded, so EP works fine.

**Comment by valinet** [comment]
No, it's a mistake. Added that relatively recently and forgot to add that there as well. Corrected now, thanks.
