### ISSUE TITLE
Add support for Win+Alt+D keyboard shortcut (time/date fly-out)

### ISSUE THREAD

**Issue by bzzrak** [valinet/ExplorerPatcher#591]
Windows 10 has a built-in shortcut to bring up the date flyout, it is not supported in EP. I propose that it's added for completeness's sake.

Source (the "windows logo key" section):
https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec#WindowsVersion=Windows_10

**Comment by valinet** [comment]
I have implemented this in the latest version (.17).

Merry Christmas and a happy new year!

**Comment by bzzrak** [comment]
My apologies and thanks. Happy holidays to you too!
