### ISSUE TITLE
limit width of taskbar buttons

### ISSUE THREAD

**Issue by f242** [valinet/ExplorerPatcher#596]
any way to limit width of buttons in task bar?
![image](https://user-images.githubusercontent.com/10371194/147373096-8f5b3fa8-8c11-4837-8e75-9a4893f949ef.png)
22000.376.40.18
win11 22000.376

**Comment by Flexman** [comment]
I've occasionally seen that when playing about with different EP settings. A reboot always put it back to normal for me.

**Comment by valinet** [comment]
Can we stop opening issues when they’re not? Is it so hard to read this: #56 and use Discussions if still necessary. Someone asked this some time ago. Indeed, Windows has some bug that makes it behave like that from time to time. I never trigger it, but I saw it once. To limit the button width, as I said in the other thread, Google is very useful: https://windowsloop.com/change-taskbar-buttons-width/

Literally took 10 seconds to find it on Google. How is this an issue with EP? And if it is, duplicating threads is of no use.
