### ISSUE TITLE
Symbols fail to read in Windows 11 Build 22523

### ISSUE THREAD

**Issue by Shaughn-david** [valinet/ExplorerPatcher#607]
In build 22523 the symbols download successfully but the symbols fail to read for "twinui.pcshell.dll" which makes the Win+X menu, Wi-Fi flyout, and Battery flyout fail to launch. The Start Menu sometimes crashes too.

Console:

funchook create 1
Attempting to download symbol data; for now, the program may have limited functionality.
Setup user32 functions done
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup sndvolsso functions done
Setup shell32 functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Installed hooks.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
Progman: 394006
Progman hook: 1114953
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "fdde7cdaef522608ec6df2b9119e2185"
[Updates] Update URL: https://api.github.com/repos/valinet/ExplorerPatcher/releases?per_page=1
[Symbols] Started "Download symbols" thread.
[Symbols] Attempting to download symbols for unknown OS version 10.0.22523.1000.
[Symbols] Downloading to "C:\Users\Shaughn\AppData\Roaming\ExplorerPatcher\".
[Symbols] Downloading symbols for "C:\Windows\system32\twinui.pcshell.dll"...
[Updates] Prerelease update URL: "https://github.com/valinet/ExplorerPatcher/releases/download/22000.376.40.20_d35cdeb/ep_setup.exe"
[Updates] Release notes URL: "https://github.com/valinet/ExplorerPatcher/releases/tag/22000.376.40.20_d35cdeb"
[Symbols] Reading symbols...
[Updates] Hash of remote file is "fdde7cdaef522608ec6df2b9119e2185" (valid).
[Updates] No updates are available.
0 0
[Symbols] Hooking Win+C is not available for this build.
[Symbols] Failure in reading symbols for "C:\Windows\system32\twinui.pcshell.dll".

**Comment by Shaughn-david** [comment]
I am also on version 22000.376.40.20 of ExplorerPatcher.

**Comment by valinet** [comment]
EP is not supported on Insider Preview builds.
