### ISSUE TITLE
Newest Version Breaks Windows 10

### ISSUE THREAD

**Issue by Icodeforfunidkbu** [valinet/ExplorerPatcher#608]
Hey, just wanted to let you know running ep_setup on Windows 10 21H1 gave my computer the Black Screen of Death. The only way I found to fix it was to go Ctrl+Shift+Esc, and open cmd, and get to ep_setup and run ep_setup /uninstall. I sorta freaked out about it, but if you can fix this please do.

**Comment by valinet** [comment]
This application is called “ExplorerPatcher for **Windows 11**”.
