### ISSUE TITLE
virustotal reports a virus

### ISSUE THREAD

**Issue by rebroad** [valinet/ExplorerPatcher#611]
https://www.virustotal.com/gui/file/fa0437336aeb6e9414ec3ba9b32e425aa6aab5e918d59a06364bf5dba91026d0

I've tested this on 2 computers, and on Windows and on Linux, so I think it's unlikely that all 3 OSs are infected.

**Comment by valinet** [comment]
Similar thread: https://github.com/valinet/ExplorerPatcher/issues/265
