### ISSUE TITLE
there's no minimize all windows button

### ISSUE THREAD

**Issue by pjotrekdev** [valinet/ExplorerPatcher#621]
there's no minimize all windows button, it should be on the right side

**Comment by valinet** [comment]
Can we stop opening issues without firstly determining if it's just a problem on our side? Like, actually read #56...?

Right click taskbar, choose Properties, then:

![image](https://user-images.githubusercontent.com/6503598/147889706-78828581-6e14-4d3d-b0ac-c9cd81eaa349.png)

Or, right click taskbar, choose Taskbar settings, then:

![image](https://user-images.githubusercontent.com/6503598/147889738-2dfefb4c-45f8-4eb1-bbe2-32215742f57a.png)

That's what you have probably modified, forgot about, and then ofc it's an issue with EP...

There are instructions that only take 3 minutes to read before opening tickets in the wrong places.
