### ISSUE TITLE
ExplorerPatcher failed to load on InsiderBuild  10.0.22526.1000

### ISSUE THREAD

**Issue by DenisMtfl** [valinet/ExplorerPatcher#643]
Installer starts then white screen and nothing happens.
Only deleting the dll-File fix the problem. Explorer Patcher ist not able to load here.

**Comment by valinet** [comment]
I just tried it today there, it worked.

![image](https://user-images.githubusercontent.com/6503598/148506962-bb783397-e7e0-445b-a213-05c9f879baf9.png)

Anyway, EP is not supported on Insider Preview builds.

Also, please read [here](https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems): do not open issues, use discussions, and search similar threads before reposting similar info. This is the third thread about this already.
