### ISSUE TITLE
Disable the Installed Updates Control Panel redirection to the Settings app.

### ISSUE THREAD

**Issue by Shaughn-david** [valinet/ExplorerPatcher#644]
Here is the Vive command syntax: ".\vivetool addconfig 36731482 1"

Velocity number thing: "36731482"

This doesn't yet happen in the Release version but will be implemented in the future.

Currently the redirection happens in builds 22523+

**Comment by valinet** [comment]
So, what should EP do and why is it an issue regarding EP?

https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems

**Comment by valinet** [comment]
And post in Discussions, as the page clearly says.
