### ISSUE TITLE
When switching virtual desktops, the taskbar is not refreshed in time

### ISSUE THREAD

**Issue by photkey** [valinet/ExplorerPatcher#645]
there may still be applications opened by Virtual Desktop C under the taskbar; when switching to Virtual Desktop C again, the taskbar does not appear the applications of Virtual Desktop C in time, and only when clicking an application does the taskbar appear the other applications.
![VirtualDesktop](https://user-images.githubusercontent.com/60434581/148752360-2c593381-83e1-4a1b-a0d1-cc59b15912fb.gif)

**Comment by valinet** [comment]
Cannot reproduce. Some applications behave weirdly, their taskbar buttons behave strangely. Those are niche cases, I do not have the time to fix all the bugs in the world. Best is to upgrade to Windows 10 if you want the 100% fully compatible experience.

Also: https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems
