### ISSUE TITLE
Explorer Doesn't Load on Latest Prerelease

### ISSUE THREAD

**Issue by danchemistruck** [valinet/ExplorerPatcher#651]
I'm running Windows Insider Build 22526.rs_prerelease.211215-1332 and explorer.exe will not load. I had to uninstall Explorer Patcher to get the desktop GUI to load.

**Comment by valinet** [comment]
ExplorerPatcher is not supported on Insider Preview builds. Also: https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems
