### ISSUE TITLE
Installer crashes on Win11 Insider Preview Arm (Apple M1 + VMWare Fusion Technical Preview arm64)

### ISSUE THREAD

**Issue by MelaninForbes** [valinet/ExplorerPatcher#689]
Installer(ep_setup.exe) just forces Explorer.exe to restart.

How to reproduce :
1)Prepare and run VM with Windows 11 insider Preview (arm) on Mac OS Monterey (CPU = Apple M1) in VMWare Fusion Technical Preview (arm64);
2)Copy ep_setup.exe on VM;
3)run ep_setup.exe by double clicking

**Comment by valinet** [comment]
![image](https://user-images.githubusercontent.com/6503598/149848838-b61b09b1-c508-4089-8b9f-02f5ff027deb.png)

Related:
https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems

About this "issue":
https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems
