### ISSUE TITLE
Bug: Taskbar stuck to top

### ISSUE THREAD

**Issue by prog-rajkamal** [valinet/ExplorerPatcher#707]
I was playing with Taskbar positioning settings, and found a couple of bugs:

![image](https://user-images.githubusercontent.com/11518519/150476650-6935bab4-42dd-4113-9f0a-ab1e8d57950d.png)

1. the primary taskbar is stuck on "Top" and other options "left", "right" and bottom do not work
2. None of the options work for secondary taskbar location

My OS info:
1. Windows 21H2 (OS Build 22000.434)
2. Windows Enterprise

PS: I just discovered this tool today. apart from this issue, this is fantastic.

**Comment by valinet** [comment]
They work on my side, same build.

**Comment by prog-rajkamal** [comment]
Don't if it was root cause or not, but i had taskbar set to "lock". with taskbar "unlocked", I was able to move them around.

**Comment by valinet** [comment]
Yeah, that was the cause. With locked taskbar, you can't drag it around.
