### ISSUE TITLE
Request feature 

### ISSUE THREAD

**Issue by dav1dsrz** [valinet/ExplorerPatcher#714]
Can u add a option for hide programs running in tasbark.

By example: 

I want to auto hide "Picture in picture" Window showed by browsers, because they're using much space, so this feature will help with this problem.

This option can be settled by a input textbox separated by commas.

Regards and thank you!

**Comment by valinet** [comment]
I also kindly asked to read some simple rules before posting in these forums: https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems

How is this an issue?

**Comment by Poopooracoocoo** [comment]
this really sounds like a feature request for browsers. this'd be a better feature request for 7+ taskbar tweaker or something but is still way too niche, dontcha think?
