### ISSUE TITLE
settings.ini - 404

### ISSUE THREAD

**Issue by D3V-OPS** [valinet/ExplorerPatcher#76]
Link to settings.ini leads to nowhere. Fix it, pls.

**Comment by valinet** [comment]
Okay, thanks for the tip. Idk, I will see how I proceed on the future, I copy paste the template for release notes from the previous version and just change some of the text. Why are old releases needed anyway? They're there just for historic reference, everyone should daily drive the latest version if possible. May I ask what the reason for using old versions is?
