### ISSUE TITLE
Tray Icons

### ISSUE THREAD

**Issue by ErnieAlex** [valinet/ExplorerPatcher#766]
After installing E-patcher, my Wamp no longer shows up in the icons tray.  Several others are hidden all of a sudden, also.
Is this fixable?
The patcher was such a great item to use.  I can not work with ease again.  Thank you for this tool!  But, I need to access all my icons in the tray that were previously there.  BUG?

**Comment by bonxz** [comment]
![image](https://user-images.githubusercontent.com/61289944/152017537-3d5f23bc-6ecd-4985-a6f3-14df4c081b17.png)
Just customize the icons u want to show or hide in the taskbar.

**Comment by ErnieAlex** [comment]
Have you tested it by installing Wamp first, then ExplorerPatcher, then try to start Wamp and there is no icon.
It was there before I installed the patcher!

**Comment by ErnieAlex** [comment]
Well, this is solved.  Odd thing with Windows 11.  If you are running the Patcher and all of a sudden your Wamp tray icon goes away, you have to do this to get it back.
Run Task Manager
Look for the AeTrayMenu near the top and end-task it.  (This will not stop Wamp, just the tray menu section)
Then, run Wamp again and it should reload the tray icon for it.

Not sure why this happens.  It only started once patcher was installed.   Not sure if this fix is permanent or a one time problem.
