### ISSUE TITLE
Remove title text in taskbar

### ISSUE THREAD

**Issue by daniel-lo** [valinet/ExplorerPatcher#767]
Hi .. is there a way to only show app icons .. without the windows title next to it?
Didn't find a checkbox for that.

**Comment by Poopooracoocoo** [comment]
Sounds like a job for 7+ Taskbar Tweaker.

**Comment by valinet** [comment]
https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems

**Comment by daniel-lo** [comment]
![grafik](https://user-images.githubusercontent.com/4311558/152099836-f52fc25d-32dc-4dfc-b9bb-b0bc3bbbde41.png)

**Comment by Poopooracoocoo** [comment]
https://superuser.com/questions/30007/is-there-any-way-to-hide-taskbar-labels-and-not-combine-taskbar-buttons describes the following:
- Go to ExplorerPatcher's properties and select `always combine, hide labels`
https://github.com/valinet/ExplorerPatcher/wiki/All-features#always-combine-hide-labels
- Go to 7+ Taskbar Tweaker and select `don't combine grouped buttons`
![image](https://user-images.githubusercontent.com/51363864/152158698-5ea40ea2-74ea-4f40-a391-03e07383ec1e.png)
---
Valentin's wiki linked above tells you to create discussions for questions and feature requests, and bugs are delegated to issues. I hope this helps :)

**Comment by daniel-lo** [comment]
@Poopooracoocoo 

Interesting .. thank you!

**Comment by Poopooracoocoo** [comment]
@daniel-lo 
So did that work? Was that what you were looking for?

**Comment by daniel-lo** [comment]
@Poopooracoocoo 

Have yet to try .. I find it a bit complicated because I expected it to default to the way it worke with Win10.
If I work my self through it I will let you know :-)

**Comment by Poopooracoocoo** [comment]
OHHHHH. You hadn't clarified!! If you just want the default from Windows 7 to 11, you just select always combine, hide labels in Explorer Patcher's properties. You don't need 7+ Taskbar Tweaker to do that.

I get that it's a bit tricky to understand. Windows 11 doesn't come with any other options and by default Explorer Patcher uses the developer's (and many others) favourite configuration and thus shows labels. Because Windows 11 doesn't have this option in its Settings app, Explorer Patcher has its own properties window that lets you access the old settings from versions prior to Windows 10.

**Comment by daniel-lo** [comment]
I didn't find hide labels :-(

**Comment by Poopooracoocoo** [comment]
Just edited my comment to clarify what the setting is actually called

**Comment by daniel-lo** [comment]
Works .. thank you! What I notice is that I can't toggle 10/11 taskbar .. nothing happens .. it stays 10.

**Comment by daniel-lo** [comment]
got it .. didn't pay attention to the asterix .. will continue with it now :-)

**Comment by Mulakulu** [comment]
>     * Go to ExplorerPatcher's properties and select `always combine, hide labels`
For more clarification, here's how to do it on the newest version 22621.3296.64.1.
Click on taskbar.
Set taskbar style to windows 10 for more options (You can switch back later).
Near the bottom, switch "Combine taskbar icons on primary/secondary taskbar(s)" to "Always Combine".
You can now switch back to windows 11 if you want to.
