### ISSUE TITLE
The command in README to ungroup icons doesn't work

### ISSUE THREAD

**Issue by CodeSpartan** [valinet/ExplorerPatcher#77]
It adds the key to the registry, but the key doesn't seem to do anything. I'm still seeing explorer windows grouped in the taskbar after killing all explorer.exe processes and starting one.

Edition	Windows 11 Pro
Version	21H2
OS build	22000.258
Experience	Windows Feature Experience Pack 1000.22000.258.0

**Comment by valinet** [comment]
Thanks. There are 3 commands regarding this in the README. 

The first one sets a group policy, so it needs administrator access, which was not specified in the README and this was corrected. It did not work, no registry entries were created when running from regular cmd, it yielded an error 5, "Access is denied".

The 2 other commands work just fine. There is also the GUI which you can use to set these up.

At any point, you can consider forking the repo, fixing the problem and making a pull request with the changes. Thanks. I consider this fixed.
