### ISSUE TITLE
Weather disappears in Taskbar after restoring from Sleep Mode

### ISSUE THREAD

**Issue by gjf** [valinet/ExplorerPatcher#771]
22000.469.42.4 issue.
After restoring from Sleep Mode I see "People" icon rather than Weather in task bar.
When going to Settings of ExplorerPatcher and opening "Customize system icons" the standard Windows settings opened and the system hangs for a moment. After that the task bar has been "restarted" and Weather appears back.

**Comment by valinet** [comment]
It’s broken in .4. I don’t have time to fix it right now. Also, should have checked this out: https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems
