### ISSUE TITLE
Weather Widget Becomes People Widget

### ISSUE THREAD

**Issue by Satomilee** [valinet/ExplorerPatcher#777]
loss of internet connection due to laptop being put into sleep mode and when woken up the weather widget becomes the win10 people widget, restarting the explorer process fixes this issue

**Comment by SpIdErPiGgY1984** [comment]
Yes I can confirm that

**Comment by IgnacioMonge** [comment]
I have the same problem.

**Comment by valinet** [comment]
The external process where the widget is hosted (one of the `dllhost.exe` instances, the one with parameters something like `/ProcessId:A6EA...`) likely crashes. Attach with WinDbg (or any debugger), wait for it to happen and see what the stack trace indicates. Or enable *FULL* crash dumps as I said multiple times now it's described [here](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps), collect a *FULL* crash dump and upload that here.

As it stands now, this issue provides no meaningful info:

* no crash dump
* no version info
* no Windows build number
* nothing that's indicated [here](https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems) as being useful

**Comment by Wontell** [comment]
I have the same issue
