### ISSUE TITLE
Cannot use Windows 10 Battery, Network,... Flyout on Windows 11

### ISSUE THREAD

**Issue by Hoang-Gia-Bao** [valinet/ExplorerPatcher#796]
Hello, I have used your tool but I can't change my icon to Windows 10 Flyout but I can change to Windows 7. How to solve. Thanks

**Comment by fmatak** [comment]
I also have the same issue. I am using windows 11 insider dev channel. Battery icon windows 10 flayout is not working. But if I change to windows 7, it shows windows 7 battery popup.

**Comment by Poopooracoocoo** [comment]
@fmatak You could've used discussions. It's also useful to provide your version of EP and Windows build number. And EP doesn't support Windows Insider builds.
