### ISSUE TITLE
Windows 11 language switcher is no longer shown since build 22543

### ISSUE THREAD

**Issue by ripkaby** [valinet/ExplorerPatcher#811]
Probably due to MS updating how the language switcher works, only the windows 10 language switcher is shown under windows 10 taskbar. Another issue is that the windows 11 taskbar no longer stays on top.

**Comment by valinet** [comment]
Thanks for the report.

EP is not supported on Insider Preview builds as per https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems

I will wait for the next update to get finalized and get publicly released, and then see what is still there and can be patched to continue working.

Thanks.
