### ISSUE TITLE
Bugs when using laptop:

### ISSUE THREAD

**Issue by Syth-1** [valinet/ExplorerPatcher#839]
Explorer patcher works perfectly on my desktop - just installed it on my laptop and noticed 2 bugs so far: 

1) when using win10 task bar, clicking battery icon only works roughly 1/3rd of the time. Using win7 battery fly out style works without issue, only occurs when using win10 style. When it does fail the cursor changes to a loading icon for a split second or two. 

2) when opening the right click desktop context menu, it allows to scroll which shouldn't be possible, if you do scroll it crashes explorer.exe - I believe this may be due to text scaling set to 125%, where on normal 100% this is not an issue.

**Comment by valinet** [comment]
https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems
