### ISSUE TITLE
White line on windows 11 taskbar

### ISSUE THREAD

**Issue by currall** [valinet/ExplorerPatcher#871]
There is a white line on the bottom of the taskbar in every section other than my pinned icons. Only happens on the main monitor in windows 11 taskbar.

![image](https://user-images.githubusercontent.com/29579820/154297809-bbb68dd3-7082-4395-985a-474999f9fd2b.png)

**Comment by valinet** [comment]
AGAIN, THIS WAS SIMPLY IGNORED:

![image](https://user-images.githubusercontent.com/6503598/154298731-eb0fde6e-1b90-4ddc-a8e8-51b352ee3bfd.png)

Properties - Other - Show separators between taskbar toolbars
