### ISSUE TITLE
I don't see the Weather option/tab in Properties

### ISSUE THREAD

**Issue by GalGreenfield** [valinet/ExplorerPatcher#878]
I don't see the Weather option/tab in Properties to be able to enable it.

Could you please help me debug htis?

**Comment by valinet** [comment]
![image](https://user-images.githubusercontent.com/6503598/154298731-eb0fde6e-1b90-4ddc-a8e8-51b352ee3bfd.png)

**Comment by GalGreenfield** [comment]
Thanks, I somehow missed that. 😅
