### ISSUE TITLE
Invisible text on black background in Properties on High Contrast theme

### ISSUE THREAD

**Issue by JacobSC51** [valinet/ExplorerPatcher#885]
Windows 11 x64 Build 22000.493
ExplorerPatcher Pre-Release 22000.493.42

When using a High Contrast theme, the properties menu contents become unreadable, with the exception of context dialogs:
![image](https://user-images.githubusercontent.com/47087244/154545953-f079fd0b-b1b6-441f-9355-e2c6508a7291.png)

Disabling High Contrast makes everything display correctly again:
![image](https://user-images.githubusercontent.com/47087244/154546124-d871d6ec-d058-442f-ad2e-1d8859d194f3.png)

It appears that all clickable elements are still functional, just not visible.

**Comment by valinet** [comment]
Which high contrast theme?

**Comment by valinet** [comment]
Anyway, will be fixed in the next pre-release.

**Comment by valinet** [comment]
Fixed in latest pre-release (42.15).
