### ISSUE TITLE
ExplorerPatcher hack available in ThisIsWin11

### ISSUE THREAD

**Issue by Belim** [valinet/ExplorerPatcher#89]
hi,
just fyi, since i appreciate your ExplorerPatcher hack very much, i have integrated it into my tool [ThisIsWin11](https://github.com/builtbybel/ThisIsWin11/releases/tag/0.86.23) for the sake of simplicity.
 
..of course just an installation automatism, which originates from your installation instruction.
![Image 6](https://user-images.githubusercontent.com/57478606/137276033-1c879a10-39e1-4859-a97c-49faec51e881.png)

**Comment by valinet** [comment]
Hey, thanks, that’s ok.
