### ISSUE TITLE
Weather Tooltip 

### ISSUE THREAD

**Issue by samaellain** [valinet/ExplorerPatcher#892]
![image](https://user-images.githubusercontent.com/56184334/154801494-ff9dff4c-9748-4835-bb66-4405ab6a93b3.png)
This tooltip appear frequently and stay above all windows, only vanish restarting explorer or using the option update weather now.
Windows 11 Pro 21H2 22000.493

**Comment by Poopooracoocoo** [comment]
Use discussions.

Do you happen to be using a device with a touchscreen? It could be a Chromium issue which means this'd be out of EP's scope. The weather feature uses Edge WebView and Edge is based on Chromium.

**Comment by valinet** [comment]
Yeah, sometimes it happens on my end too, but it disappears when the mouse is moved. It’s a WebView2/Chromium bug, or at least they should add a mention about what developers would have to do/not do to trigger that.

Maybe Microsoft will address it in the future.

**Comment by Poopooracoocoo** [comment]
This is the Chromium issue I've been following: https://bugs.chromium.org/p/chromium/issues/detail?id=1146981 It could be the same as this issue
