### ISSUE TITLE
Install on windows 10 makes desktop go black and taskbar has disappeared

### ISSUE THREAD

**Issue by Ast3r0ids** [valinet/ExplorerPatcher#935]
Please help. I installed this thinking it lets you modify explorer. Nothing happened: no install window or anything. My taskbar and wallpaper are completely missing and so are my context menus and every other desktop feature. I need help removing or fixing this. Please help immediatley.

**Comment by edo9300** [comment]
Chipping is as i got the exact same issue right now, didn't do anyhting, just run teh installer, got an error popup window saying something about a backup, and then explorer died
![image](https://user-images.githubusercontent.com/18705342/155846765-7e2504b6-278b-4620-b227-7c6a24f3b884.png)

**Comment by valinet** [comment]
Just uninstall it? Btw, these features are in testing for a reason. Which Windows version? I tested it on 22H2, LTSC 2021 and LTSC 2019, others idk.

Also, I specifically asked for support tickets to be opened in Discussions, but yeah…
