### ISSUE TITLE
opacity of simple window switcher is not working

### ISSUE THREAD

**Issue by CloudGlitch** [valinet/ExplorerPatcher#943]
opacity of simple window switcher is not working for windows 11

**Comment by valinet** [comment]
It is working

**Comment by valinet** [comment]
I said a couple of times already, fill in proper reports: #56.

**Comment by CloudGlitch** [comment]
Iam sorry it is working for default theme when I checked again, but the acrylic theme is not working for me

**Comment by valinet** [comment]
Acrylic only works when the computer is not power saving, when transparency effects are permitted at OS level etc. Check to make sure that you have those enabled.
