### ISSUE TITLE
The option to disable immersive menus does not disable them in File Explorer

### ISSUE THREAD

**Issue by Anix-x** [valinet/ExplorerPatcher#96]
Without the option to disable immersive menus on we have the default Windows 11 menus:
![image](https://user-images.githubusercontent.com/92230793/137415234-7ac13f8a-4b78-4102-88ef-290ec23b9a46.png)
If we enable the option that claims to **disable** the immersive menus, we get the usual immersive menues, introduced in Windows 10, and known as such. They do not fit with the Windows theme and font settings, do not support subpixel hinting, and not compatible with Windows Classic theme:
![immersivemenu](https://user-images.githubusercontent.com/92230793/137414714-b1d699f2-8eaa-47b6-af6b-a877c3b38581.png)
Now, if we install ExplorerContextMenuTweaker, we get the non-immersive menus, that fully fit with the current theme and can be used without theming (e.g., under "Classic" theme). They use subpixel hinting and ClearType:
![non-immersive](https://user-images.githubusercontent.com/92230793/137414848-a3f547cf-7b2d-475a-bb98-ae8401347660.png)
And this is the same non-immersive menu when not themed:
![classic](https://user-images.githubusercontent.com/92230793/137414891-998b4f2c-ec43-4c29-9776-f2eec5c91e18.png)

**Comment by valinet** [comment]
Okay, so I ask again, what is the proposal?

**Comment by Anix-x** [comment]
Possibly, to change the wording to less confusing, such as "Disable Windows 11-style menus" or "Enable Windows 10-style menus" or "Enable full/complete menus".

**Comment by Anix-x** [comment]
The Immersive menu as well as the Win11 menu both use the greyscale antialiasing and do not respect the systemwide font settings (the font size is greater than system default).
This, in particular, shows, that implementing non-immersive menus is beneficial not only to users of Classic theme.

As to how to tell apart immersive menu from non-immersive themed, look at
* Font (immersive uses greyscale hinting and bigger font)
* The ">" characters indicating submenus (they are bigger)
* When the bit 17 in User Preference Mask is unset, there is a difference in the border (see the pictures above). 
* The length of separators are different as you can see on the pictures above.
On Windows 10 the difference was much greater, but on Win11 they "themed up" the immersive menus a bit to better match the system theme.

**Comment by Anix-x** [comment]
On your picture the menus are in the Classic theme, non-immersive and UPM 17 is set :-)

**Comment by Anix-x** [comment]
Thank you very much, this is great!

**Comment by Anix-x** [comment]
What about the taskbar context menus? It has the same problem as File Explorer (whe menus are immersive and empty in Classic theme), but currently there is a decent solution: TaskbarContextMenuTweaker by the same author as ExplorerContextMenuTweaker.
Will your fix work the same way for the taskbar as for File Explorer? Then there would be no need in these two programs.

**Comment by valinet** [comment]
> 
> 
> What about the taskbar context menus? It has the same problem as File Explorer (the menus are immersive and empty in Classic theme), but currently there is a decent solution: TaskbarContextMenuTweaker by the same author as ExplorerContextMenuTweaker. Will your fix work the same way for the taskbar as for File Explorer? Then there would be no need in these two programs.

Yeah, it works, will be added as an option in the next release. I disabled owner drawing (immersive menu) for taskbar right click, system tray icons right click, clock right click, language right click, notification icon right click, show desktop right click, secondary taskbar right click, secondary clock right click, Win+X menu, plus in File Explorer windows.
