### ISSUE TITLE
Windows 10 Taskbar problem

### ISSUE THREAD

**Issue by Mike219913** [valinet/ExplorerPatcher#999]
sometimes windows 10 taskbar in center, (if you enable search and task view icons) aren't placed correctly
![Снимок экрана 2022-03-05 213516](https://user-images.githubusercontent.com/79721704/156898521-2c4aef26-e4d7-46fa-9d7a-90386fa5fbe6.jpg)
y

**Comment by Mike219913** [comment]
it's real

**Comment by valinet** [comment]
I have fixed this in the latest pre-release.
